SMT-RAT: smtrat::WrapperExternal Class Reference
smtrat::WrapperExternal Class Reference
Public Member Functions
DLL_EXPORT void setLemmaLevel (int _level)
Set level for lemma generation.
DLL_EXPORT std::size_t parseFormula (const char *input, char *buffer, std::size_t bufferSize)
Parse formula.
DLL_EXPORT bool inform (const char *_constraint, const char *_name)
Informs the solver about a constraint.
DLL_EXPORT bool add (const char *_subformula, const char *_name)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
DLL_EXPORT std::size_t addWithVariables (const char *_subformula, const char *_name, char *buffer, std::size_t bufferSize)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
DLL_EXPORT void addInformationRelevantFormula (const char *_formula)
Adds formula as InformationRelevantFormula.
DLL_EXPORT void clearInformationRelevantFormula ()
Clear all InformationRelevantFormula.
DLL_EXPORT unsigned check ()
Checks the so far added formulas for satisfiability.
DLL_EXPORT void push ()
Pushes a backtrack point to the stack of backtrack points.
DLL_EXPORT bool pop ()
Pops a backtrack point from the stack of backtrack points.
DLL_EXPORT void reset ()
Resets the solver.
DLL_EXPORT std::size_t infeasibleSubsets (char *buffer, std::size_t bufferSize) const
DLL_EXPORT std::size_t getModelEqualities (char *buffer, std::size_t bufferSize) const
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
DLL_EXPORT std::size_t model (char *buffer, std::size_t bufferSize) const
DLL_EXPORT std::size_t allModels (char *buffer, std::size_t bufferSize) const
DLL_EXPORT std::size_t lemmas (char *buffer, std::size_t bufferSize) const
Returns the lemmas/tautologies which were made during the last solving provoked by check().
DLL_EXPORT std::size_t formula (char *buffer, std::size_t bufferSize) const
DLL_EXPORT std::size_t getAssignmentString (char *buffer, std::size_t bufferSize) const
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
DLL_EXPORT std::size_t getAssertionsString (char *buffer, std::size_t bufferSize) const
Prints the so far added formulas.
DLL_EXPORT std::size_t getInfeasibleSubsetString (char *buffer, std::size_t bufferSize) const
Prints the first found infeasible subset of the set of received formulas.
Static Public Member Functions
static DLL_EXPORT WrapperExternal * createWrapper (const char *)
static DLL_EXPORT void disposeWrapper (WrapperExternal *wrapper)
Private Member Functions
std::size_t copyResult (const std::ostringstream &stream, char *buffer, std::size_t bufferSize) const
Writes a stream into a buffer for an external program.
bool tryCopyOld (char *buffer, std::size_t bufferSize) const
Tries to write lastBuffer into a buffer for an external program.
Private Attributes
SOLVER * solver
carl::parser::Parser< Poly > parser
std::string lastBuffer = ""
Detailed Description
Definition at line 24 of file smtrat-wrapper.h.
Member Function Documentation
add()
bool smtrat::WrapperExternal::add (const char * _subformula, const char * _name)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The formula to add.
_name The name of the constraint used as a label.
Returns
false, if it is easy to decide whether adding this formula creates a conflict; true, otherwise.
Definition at line 38 of file smtrat-wrapper.cpp.
addInformationRelevantFormula()
void smtrat::WrapperExternal::addInformationRelevantFormula (const char * _formula)
Adds formula as InformationRelevantFormula.
Parameters
formula The formula to add.
Definition at line 75 of file smtrat-wrapper.cpp.
addWithVariables()
std::size_t smtrat::WrapperExternal::addWithVariables (const char * _subformula, const char * _name, char * buffer, std::size_t bufferSize)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
It also returns the formula and the set of variables.
Parameters
_subformula The formula to add.
_name The name of the constraint used as a label.
buffer The stream to print on.
Returns
needed buffersize if the current one is too small, 0 otherwise
Definition at line 50 of file smtrat-wrapper.cpp.
allModels()
std::size_t smtrat::WrapperExternal::allModels (char * buffer, std::size_t bufferSize) const
Returns
A list of all assignments, such that they satisfy the conjunction of the so far added formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 154 of file smtrat-wrapper.cpp.
check()
unsigned smtrat::WrapperExternal::check ()
Checks the so far added formulas for satisfiability.
Returns
True, if the conjunction of the so far added formulas is satisfiable; False, if it not satisfiable; Unknown, if this solver cannot decide whether it is satisfiable or not.
Definition at line 88 of file smtrat-wrapper.cpp.
copyResult()
std::size_t smtrat::WrapperExternal::copyResult (const std::ostringstream & stream, char * buffer, std::size_t bufferSize) const private
Writes a stream into a buffer for an external program.
Parameters
stream The stream to write
buffer The buffer to write into.
buffersize The current buffersize.
Returns
needed buffersize if the current one is too small, 0 otherwise
Definition at line 224 of file smtrat-wrapper.cpp.
formula()
std::size_t smtrat::WrapperExternal::formula (char * buffer, std::size_t bufferSize) const
Returns
The conjunction of so far added formulas.
Definition at line 182 of file smtrat-wrapper.cpp.
Referenced by addInformationRelevantFormula().
getAssertionsString()
std::size_t smtrat::WrapperExternal::getAssertionsString (char * buffer, std::size_t bufferSize) const
Prints the so far added formulas.
Parameters
_out The stream to print on.
Returns
needed buffersize if the current one is too small, 0 otherwise
Definition at line 204 of file smtrat-wrapper.cpp.
getAssignmentString()
std::size_t smtrat::WrapperExternal::getAssignmentString (char * buffer, std::size_t bufferSize) const
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
Parameters
The stream to print on.
Returns
needed buffersize if the current one is too small, 0 otherwise
Definition at line 194 of file smtrat-wrapper.cpp.
getInfeasibleSubsetString()
std::size_t smtrat::WrapperExternal::getInfeasibleSubsetString (char * buffer, std::size_t bufferSize) const
Prints the first found infeasible subset of the set of received formulas.
Parameters
_out The stream to print on.
Returns
needed buffersize if the current one is too small, 0 otherwise
Definition at line 214 of file smtrat-wrapper.cpp.
getModelEqualities()
std::size_t smtrat::WrapperExternal::getModelEqualities (char * buffer, std::size_t bufferSize) const
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
Returns
A list of vectors of variables, stating that the variables in one vector are assigned to equal values.
Definition at line 126 of file smtrat-wrapper.cpp.
infeasibleSubsets()
std::size_t smtrat::WrapperExternal::infeasibleSubsets (char * buffer, std::size_t bufferSize) const
Returns
All infeasible subsets of the set so far added formulas.
Note, that the conjunction of the so far added formulas must be inconsistent to receive an infeasible subset.
Definition at line 112 of file smtrat-wrapper.cpp.
inform()
bool smtrat::WrapperExternal::inform (const char * _constraint, const char * _name)
Informs the solver about a constraint.
Optimally, it should be informed about all constraints, which it will receive eventually, before any of them is added as part of a formula with the interface add(..).
Parameters
_constraint The constraint to inform about.
_name The name of the constraint used as a label.
Returns
false, if it is easy to decide (for any module used of this solver), whether the constraint itself is inconsistent; true, otherwise.
Definition at line 26 of file smtrat-wrapper.cpp.
lemmas()
std::size_t smtrat::WrapperExternal::lemmas (char * buffer, std::size_t bufferSize) const
Returns the lemmas/tautologies which were made during the last solving provoked by check().
These lemmas can be used in the same manner as infeasible subsets are used.
Returns
The lemmas/tautologies made during solving.
Definition at line 168 of file smtrat-wrapper.cpp.
model()
std::size_t smtrat::WrapperExternal::model (char * buffer, std::size_t bufferSize) const
Returns
An assignment of the variables, which occur in the so far added formulas, to values of their domains, such that it satisfies the conjunction of these formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 144 of file smtrat-wrapper.cpp.
parseFormula()
std::size_t smtrat::WrapperExternal::parseFormula (const char * input, char * buffer, std::size_t bufferSize)
Parse formula.
Parameters
input String to parse
buffer Buffer for resulting string
bufferSize Size of buffer
Returns
needed buffersize if the current one is too small, 0 otherwise
Definition at line 15 of file smtrat-wrapper.cpp.
pop()
bool smtrat::WrapperExternal::pop (void)
Pops a backtrack point from the stack of backtrack points.
This provokes, that all formulas which have been added after that backtrack point are removed.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 100 of file smtrat-wrapper.cpp.
push()
void smtrat::WrapperExternal::push (void)
Pushes a backtrack point to the stack of backtrack points.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 94 of file smtrat-wrapper.cpp.
setLemmaLevel()
void smtrat::WrapperExternal::setLemmaLevel (int _level)
Set level for lemma generation.
Parameters
_level Level with correspondence: 0 -> NONE 1 -> NORMAL 2 -> ADVANCED
Definition at line 7 of file smtrat-wrapper.cpp.
tryCopyOld()
bool smtrat::WrapperExternal::tryCopyOld (char * buffer, std::size_t bufferSize) const private
Tries to write lastBuffer into a buffer for an external program.
Parameters
buffer The buffer to write into.
buffersize The current buffersize.
Returns
true, if there was something to write, false otherwise
Definition at line 241 of file smtrat-wrapper.cpp.
Referenced by addWithVariables(), allModels(), formula(), getAssertionsString(), getAssignmentString(), getInfeasibleSubsetString(), getModelEqualities(), infeasibleSubsets(), lemmas(), model(), and parseFormula().
The documentation for this class was generated from the following files:
smtrat-wrapper/smtrat-wrapper.h
smtrat-wrapper/smtrat-wrapper.cpp