SMT-RAT: benchmax::RedlogTool Class Reference
benchmax::RedlogTool Class Reference
#include <RedlogTool.h>
Public Member Functions
RedlogTool (const std::string &pathToTool, RedlogMode mode)
virtual std::string getCallToTool (const std::string &extraArguments="") const
virtual BenchmarkResult getAnswer (const std::string &output) const
std::string name () const
fs::path binary () const
const std::map< std::string,
std::string > & attributes () const
std::size_t attributeHash () const
virtual std::string getCommandline (const std::string &file) const
virtual std::string getCommandline (const std::string &file, const std::string &localBinary) const
bool isExtension (const fs::path &path, const std::string &extension) const
Checks if the file extension of the given path matches the given extension.
virtual bool canHandle (const fs::path &) const
virtual void additionalResults (const fs::path &, BenchmarkResults &) const
Protected Attributes
RedlogMode mMode
std::string mName
fs::path mBinary
std::string mArguments
std::map< std::string,
std::string > mAttributes
Detailed Description
Definition at line 18 of file RedlogTool.h.
Constructor & Destructor Documentation
benchmax::RedlogTool::RedlogTool (const std::string & pathToTool, RedlogMode mode)
Definition at line 29 of file RedlogTool.cpp.
Member Function Documentation
virtual void benchmax::Tool::additionalResults (const fs::path & , BenchmarkResults &) const inline virtual inherited
Definition at line 96 of file Tool.h.
Referenced by benchmax::LocalBackend::execute(), and benchmax::ssh::SSHScheduler::executeJob().
std::size_t benchmax::Tool::attributeHash () const inline inherited
Definition at line 65 of file Tool.h.
Referenced by benchmax::Database::addTool(), and benchmax::Database::getToolID().
const std::map<std::string,std::string>& benchmax::Tool::attributes () const inline inherited
Definition at line 61 of file Tool.h.
Referenced by benchmax::Database::addTool().
fs::path benchmax::Tool::binary () const inline inherited
Definition at line 57 of file Tool.h.
Referenced by benchmax::ssh::SSHScheduler::executeJob(), benchmax::CondorBackend::generateSubmitFile(), benchmax::operator<<(), and benchmax::ssh::SSHScheduler::uploadTool().
virtual bool benchmax::Tool::canHandle (const fs::path &) const inline virtual inherited
Reimplemented in benchmax::SMTRAT.
Definition at line 88 of file Tool.h.
Referenced by benchmax::CondorBackend::generateSubmitFile().
virtual BenchmarkResult benchmax::RedlogTool::getAnswer (const std::string & output) const virtual
virtual std::string benchmax::RedlogTool::getCallToTool (const std::string & extraArguments = "") const virtual
virtual std::string benchmax::Tool::getCommandline (const std::string & file) const inline virtual inherited
Definition at line 74 of file Tool.h.
Referenced by benchmax::LocalBackend::execute(), benchmax::ssh::SSHScheduler::executeJob(), and benchmax::CondorBackend::generateSubmitFile().
virtual std::string benchmax::Tool::getCommandline (const std::string & file, const std::string & localBinary) const inline virtual inherited
Definition at line 77 of file Tool.h.
bool benchmax::Tool::isExtension (const fs::path & path, const std::string & extension) const inline inherited
Checks if the file extension of the given path matches the given extension.
Definition at line 84 of file Tool.h.
Referenced by benchmax::SMTRAT::canHandle().
std::string benchmax::Tool::name () const inline inherited
Definition at line 53 of file Tool.h.
Referenced by benchmax::Database::addTool(), and benchmax::Database::getToolID().
Field Documentation
std::string benchmax::Tool::mArguments protected inherited
Definition at line 47 of file Tool.h.
Referenced by benchmax::Tool::getCommandline(), and benchmax::SMTRAT::SMTRAT().
std::map<std::string,std::string> benchmax::Tool::mAttributes protected inherited
Definition at line 48 of file Tool.h.
Referenced by benchmax::Tool::attributeHash(), benchmax::Tool::attributes(), and benchmax::SMTRAT::SMTRAT().
fs::path benchmax::Tool::mBinary protected inherited
Definition at line 46 of file Tool.h.
Referenced by benchmax::Tool::binary(), and benchmax::Tool::getCommandline().
RedlogMode benchmax::RedlogTool::mMode protected
Definition at line 22 of file RedlogTool.h.
std::string benchmax::Tool::mName protected inherited
Definition at line 45 of file Tool.h.
Referenced by benchmax::Tool::name().
The documentation for this class was generated from the following files:
benchmax/tools/RedlogTool.h
benchmax/tools/RedlogTool.cpp