SMT-RAT: smtrat::ICPModule< Settings > Class Template Reference
smtrat::ICPModule< Settings > Class Template Reference
Data Structures
struct comp
Typedefs:
struct formulaPtrComp
struct linearVariable
struct weights
Public Types
typedef carl::FastPointerMap< Poly *, weights > WeightMap
typedef Settings SettingsType
enum LemmaType : unsigned { NORMAL = 0, PERMANENT = 1 }
Public Member Functions
std::string moduleName () const
ICPModule (const ModuleInput *, Conditionals &, Manager *const =NULL)
Constructors:
~ICPModule ()
Destructor:
bool informCore (const FormulaT &)
Informs the module about the given constraint.
bool addCore (ModuleInput::const_iterator)
The module has to take the given sub-formula of the received formula into account.
void removeCore (ModuleInput::const_iterator)
Removes everything related to the given sub-formula of the received formula.
Answer checkCore ()
Checks the received formula for consistency.
void updateModel () const
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
EvalRationalIntervalMap getCurrentBoxAsIntervals () const
FormulasT getCurrentBoxAsFormulas () const
bool inform (const FormulaT &_constraint)
Informs the module about the given constraint.
void deinform (const FormulaT &_constraint)
The inverse of informing about a constraint.
virtual void init ()
Informs all backends about the so far encountered constraints, which have not yet been communicated.
bool add (ModuleInput::const_iterator _subformula)
The module has to take the given sub-formula of the received formula into account.
virtual Answer check (bool _final=false, bool _full=true, carl::Variable _objective=carl::Variable::NO_VARIABLE)
Checks the received formula for consistency.
virtual void remove (ModuleInput::const_iterator _subformula)
Removes everything related to the given sub-formula of the received formula.
virtual void updateAllModels ()
Updates all satisfying models, if the solver has detected the consistency of the received formula, beforehand.
virtual std::list< std::vector< carl::Variable > > getModelEqualities () const
Partition the variables from the current model into equivalence classes according to their assigned value.
unsigned currentlySatisfiedByBackend (const FormulaT &_formula) const
virtual unsigned currentlySatisfied (const FormulaT &) const
bool receivedVariable (carl::Variable::Arg _var) const
Answer solverState () const
std::size_t id () const
void setId (std::size_t _id)
Sets this modules unique ID to identify itself.
thread_priority threadPriority () const
void setThreadPriority (thread_priority _threadPriority)
Sets the priority of this module to get a thread for running its check procedure.
const ModuleInput * pReceivedFormula () const
const ModuleInput & rReceivedFormula () const
const ModuleInput * pPassedFormula () const
const ModuleInput & rPassedFormula () const
const Model & model () const
const std::vector< Model > & allModels () const
const std::vector< FormulaSetT > & infeasibleSubsets () const
const std::vector< Module * > & usedBackends () const
const carl::FastSet< FormulaT > & constraintsToInform () const
const carl::FastSet< FormulaT > & informedConstraints () const
void addLemma (const FormulaT &_lemma, const LemmaType &_lt=LemmaType::NORMAL, const FormulaT &_preferredFormula=FormulaT(carl::FormulaType::TRUE))
Stores a lemma being a valid formula.
bool hasLemmas ()
Checks whether this module or any of its backends provides any lemmas.
void clearLemmas ()
Deletes all yet found lemmas.
const std::vector< Lemma > & lemmas () const
ModuleInput::const_iterator firstUncheckedReceivedSubformula () const
ModuleInput::const_iterator firstSubformulaToPass () const
void receivedFormulaChecked ()
Notifies that the received formulas has been checked.
const smtrat::Conditionals & answerFound () const
bool isPreprocessor () const
carl::Variable objective () const
bool is_minimizing () const
void excludeNotReceivedVariablesFromModel () const
Excludes all variables from the current model, which do not occur in the received formula.
void updateLemmas ()
Stores all lemmas of any backend of this module in its own lemma vector.
void collectTheoryPropagations ()
void collectOrigins (const FormulaT &_formula, FormulasT &_origins) const
Collects the formulas in the given formula, which are part of the received formula.
void collectOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
bool hasValidInfeasibleSubset () const
void checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string &_filename="smaller_muses", unsigned _maxSizeDifference=1) const
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
virtual std::pair< bool, FormulaT > getReceivedFormulaSimplified ()
void print (const std::string &_initiation="***") const
Prints everything relevant of the solver.
void printReceivedFormula (const std::string &_initiation="***") const
Prints the vector of the received formula.
void printPassedFormula (const std::string &_initiation="***") const
Prints the vector of passed formula.
void printInfeasibleSubsets (const std::string &_initiation="***") const
Prints the infeasible subsets.
void printModel (std::ostream &=std::cout) const
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
void printAllModels (std::ostream &=std::cout)
Prints all assignments of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Static Public Member Functions
static void freeSplittingVariable (const FormulaT &_splittingVariable)
static void addAssumptionToCheck (const FormulaT &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_subformulas, Answer _status, const std::string &_label)
static void addAssumptionToCheck (const FormulasT &_formulas, bool _consistent, const std::string &_label)
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const FormulaSetT &_formulas, bool _consistent, const std::string &_label)
static void addAssumptionToCheck (const ConstraintsT &_constraints, bool _consistent, const std::string &_label)
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
static void storeAssumptionsToCheck (const Manager &_manager)
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Static Public Attributes
static std::vector< std::string > mAssumptionToCheck
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static std::set< std::string > mVariablesInAssumptionToCheck
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static size_t mNumOfBranchVarsToStore = 5
The number of different variables to consider for a probable infinite loop of branchings.
static std::vector< Branching > mLastBranches = std::vector<Branching>(mNumOfBranchVarsToStore, Branching(typename Poly::PolyType(), 0))
Stores the last branches in a cycle buffer.
static size_t mFirstPosInLastBranches = 0
The beginning of the cyclic buffer storing the last branches.
static std::vector< FormulaT > mOldSplittingVariables
Reusable splitting variables.
Protected Member Functions
ModuleInput::iterator eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins=false)
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
virtual void deinformCore (const FormulaT &)
The inverse of informing about a constraint.
bool anAnswerFound () const
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
void clearModel () const
Clears the assignment, if any was found.
void clearModels () const
Clears all assignments, if any was found.
void cleanModel () const
Substitutes variable occurrences by its model value in the model values of other variables.
ModuleInput::iterator passedFormulaBegin ()
ModuleInput::iterator passedFormulaEnd ()
void addOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
Adds the given set of formulas in the received formula to the origins of the given passed formula.
const FormulaT & getOrigins (ModuleInput::const_iterator _formula) const
Gets the origins of the passed formula at the given position.
void getOrigins (const FormulaT &_formula, FormulasT &_origins) const
void getOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
std::pair< ModuleInput::iterator, bool > removeOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
std::pair< ModuleInput::iterator, bool > removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
void informBackends (const FormulaT &_constraint)
Informs all backends of this module about the given constraint.
virtual void addConstraintToInform (const FormulaT &_constraint)
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
std::pair< ModuleInput::iterator, bool > addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula)
Copies the given sub-formula of the received formula to the passed formula.
bool originInReceivedFormula (const FormulaT &_origin) const
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula)
Adds the given formula to the passed formula with no origin.
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
Adds the given formula to the passed formula.
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const FormulaT &_origin)
Adds the given formula to the passed formula.
void generateTrivialInfeasibleSubset ()
Stores the trivial infeasible subset being the set of received formulas.
void receivedFormulasAsInfeasibleSubset (ModuleInput::const_iterator _subformula)
Stores an infeasible subset consisting only of the given received formula.
std::vector< FormulaT >::const_iterator findBestOrigin (const std::vector< FormulaT > &_origins) const
void getInfeasibleSubsets ()
Copies the infeasible subsets of the passed formula.
std::vector< FormulaSetT > getInfeasibleSubsets (const Module &_backend) const
Get the infeasible subsets the given backend provides.
const Model & backendsModel () const
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
void getBackendsModel () const
void getBackendsAllModels () const
Stores all models of a backend in the list of all models of this module.
virtual Answer runBackends (bool _final, bool _full, carl::Variable _objective)
Runs the backend solvers on the passed formula.
virtual Answer runBackends ()
void clearPassedFormula ()
std::vector< FormulaT > merge (const std::vector< FormulaT > &, const std::vector< FormulaT > &) const
Merges the two vectors of sets into the first one.
size_t determine_smallest_origin (const std::vector< FormulaT > &origins) const
bool probablyLooping (const typename Poly::PolyType &_branchingPolynomial, const Rational &_branchingValue) const
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
Adds a lemmas which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
bool branchAt (carl::Variable::Arg _var, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
bool branchAt (carl::Variable::Arg _var, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
void splitUnequalConstraint (const FormulaT &)
Adds the following lemmas for the given constraint p!=0.
unsigned checkModel () const
void addInformationRelevantFormula (const FormulaT &formula)
Adds a formula to the InformationRelevantFormula.
const std::set< FormulaT > & getInformationRelevantFormulas ()
Gets all InformationRelevantFormulas.
bool isLemmaLevel (LemmaLevel level)
Checks if current lemma level is greater or equal to given level.
Static Protected Member Functions
static bool modelsDisjoint (const Model &_modelA, const Model &_modelB)
Checks whether there is no variable assigned by both models.
Protected Attributes
std::vector< FormulaSetT > mInfeasibleSubsets
Stores the infeasible subsets.
Manager *const mpManager
A reference to the manager.
Model mModel
Stores the assignment of the current satisfiable result, if existent.
std::vector< Model > mAllModels
Stores all satisfying assignments.
bool mModelComputed
True, if the model has already been computed.
bool mFinalCheck
true, if the check procedure should perform a final check which especially means not to postpone splitting decisions
bool mFullCheck
false, if this module should avoid too expensive procedures and rather return unknown instead.
carl::Variable mObjectiveVariable
Objective variable to be minimized. If set to NO_VARIABLE, a normal sat check should be performed.
std::vector< TheoryPropagation > mTheoryPropagations
std::atomic< Answer > mSolverState
States whether the received formula is known to be satisfiable or unsatisfiable otherwise it is set to unknown.
std::atomic_bool * mBackendsFoundAnswer
This flag is passed to any backend and if it determines an answer to a prior check call, this flag is fired.
Conditionals mFoundAnswer
Vector of Booleans: If any of them is true, we have to terminate a running check procedure.
std::vector< Module * > mUsedBackends
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
std::vector< Module * > mAllBackends
The backends of this module which have been used.
std::vector< Lemma > mLemmas
Stores the lemmas being valid formulas this module or its backends made.
ModuleInput::iterator mFirstSubformulaToPass
Stores the position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
carl::FastSet< FormulaT > mConstraintsToInform
Stores the constraints which the backends must be informed about.
carl::FastSet< FormulaT > mInformedConstraints
Stores the position of the first constraint of which no backend has been informed about.
ModuleInput::const_iterator mFirstUncheckedReceivedSubformula
Stores the position of the first (by this module) unchecked sub-formula of the received formula.
unsigned mSmallerMusesCheckCounter
Counter used for the generation of the smt2 files to check for smaller muses.
std::vector< std::size_t > mVariableCounters
Maps variables to the number of their occurrences.
Private Types
template<template< typename > class Operator>
using Contractor = carl::Contraction< Operator, Poly >
Private Member Functions
void resetHistory (icp::ContractionCandidate *)
Methods:
void addConstraint (const FormulaT &_formula)
icp::IcpVariable * getIcpVariable (carl::Variable::Arg _var, bool _original, const icp::LRAVariable *_lraVar)
void activateNonlinearConstraint (const FormulaT &_formula)
void activateLinearConstraint (const FormulaT &_formula, const FormulaT &_origin)
bool initialLinearCheck (Answer &_answer)
Performs a consistency check on the linearization of the received constraints.
bool checkNotEqualConstraints ()
void contractCurrentBox ()
Answer callBackends (bool _final=false, bool _full=true, carl::Variable _objective=carl::Variable::NO_VARIABLE)
Poly createNonlinearCCs (const ConstraintT &_constraint, const std::vector< Poly > &_tempMonomes)
Creates the non-linear contraction candidates from all items in mTemporaryMonomes and empties mTemporaryMonomes.
void createLinearCCs (const FormulaT &_constraint, const FormulaT &_original)
Creates the linear contraction candidates corresponding to the given linear constraint.
void fillCandidates ()
Fills the IcpRelevantCandidates with all nonlinear and all active linear ContractionCandidates.
bool addCandidateToRelevant (icp::ContractionCandidate *_candidate)
Adds the specific candidate to IcpRelevantCandidates.
bool removeCandidateFromRelevant (icp::ContractionCandidate *_candidate)
Removes a candidate from the icpRelevantCandidates.
void updateRelevantCandidates (carl::Variable::Arg _var)
Update all affected candidates and reinsert them into icpRelevantCandidates.
icp::ContractionCandidate * chooseContractionCandidate ()
Method to determine the next combination of variable and constraint to be contracted.
void contraction (icp::ContractionCandidate *_selection)
Calls the actual contraction function and implements threshold functionality.
void setContraction (icp::ContractionCandidate *_selection, icp::IcpVariable &_icpVar, const DoubleInterval &_contractedInterval)
void setContraction (const FormulaT &_constraint, icp::IcpVariable &_icpVar, const DoubleInterval &_contractedInterval, bool _allCCs)
void updateRelativeContraction (const DoubleInterval &_interval, const DoubleInterval &_contractedInterval)
void updateAbsoluteContraction (const DoubleInterval &_interval, const DoubleInterval &_contractedInterval)
std::map< carl::Variable, double > createModel (bool antipoint=false) const
double sizeBasedSplittingImpact (std::map< carl::Variable, icp::IcpVariable *>::const_iterator _varIcpVarMapIter) const
Selects the next splitting direction according to different heuristics.
FormulaSetT createPremiseDeductions ()
std::vector< FormulaT > createPremise ()
FormulasT createBoxFormula (bool _onlyOriginalVariables)
bool performSplit (bool _contractionApplied, bool &_moreContractionFound)
bool splitToBoundedIntervalsWithoutZero (carl::Variable &_variable, Rational &_value, bool &_leftCaseWeak, bool &_preferLeftCase, std::vector< std::map< carl::Variable, icp::IcpVariable *>::const_iterator > &_suitableVariables)
void sizeBasedSplitting (carl::Variable &_variable, Rational &_value, bool &_leftCaseWeak, bool &_preferLeftCase)
bool satBasedSplitting (carl::Variable &_variable, Rational &_value, bool &_leftCaseWeak, bool &_preferLeftCase)
double satBasedSplittingImpact (icp::IcpVariable &_icpVariable, const EvalDoubleIntervalMap &_intervals, const DoubleInterval &_seperatedPart, bool _calculateImpact)
void splittingBasedContraction (icp::IcpVariable &_icpVar, const FormulaT &_violatedConstraint, const DoubleInterval &_contractedInterval)
bool tryTestPoints ()
bool checkBoxAgainstLinearFeasibleRegion ()
Checks the actual intervalBox with the LRASolver.
void pushBoundsToPassedFormula ()
Creates Bounds and passes them to PassedFormula for the Backends.
RationalInterval doubleToRationalInterval (carl::Variable::Arg _var, const DoubleInterval &_interval, EvalRationalIntervalMap::const_iterator _initialIntervalIter) const
FormulaT intervalBoundToFormula (carl::Variable::Arg _var, const DoubleInterval &_interval, EvalRationalIntervalMap::const_iterator _initialIntervalIter, bool _upper) const
FormulasT variableReasonHull (icp::set_icpVariable &_reasons)
Compute hull of defining origins for set of icpVariables.
FormulasT createConstraintsFromBounds (const EvalDoubleIntervalMap &_map, bool _isOriginal=true)
creates constraints for the actual bounds of the original variables.
FormulaT getReceivedFormulas (const FormulaT &_deduction)
Parses obtained deductions from the LRA module and maps them to original constraints or introduces new ones.
void remapAndSetLraInfeasibleSubsets ()
Sets the own infeasible subset according to the infeasible subset of the internal lra module.
double calculateCurrentBoxSize ()
void addProgress (double _progress)
void setBox (icp::HistoryNode *_selection)
Set all parameters of the module according to the selected HistoryNode.
bool intervalsEmpty (const EvalDoubleIntervalMap &_intervals) const
bool intervalsEmpty (bool _original=false) const
bool contractionCandidatesHaveLegalOrigins () const
bool contractionCandidatesHaveLegalOrigins (const ContractionCandidates &_ccs) const
bool contractionCandidateHasLegalOrigins (const icp::ContractionCandidate &_cc) const
bool fulfillsTarget (icp::ContractionCandidate &_cc) const
bool fulfillsTarget (const DoubleInterval &_interval) const
void debugPrint () const
Printout of actual tables of linear constraints, active linear constraints, nonlinear constraints and active nonlinear constraints.
void printAffectedCandidates () const
Prints the mapping from variable to ContractionCandidates which contain this variable.
void printIcpVariables () const
Prints all icpVariables.
void printIcpRelevantCandidates () const
Prints all icpRelevant candidates with their weight and id.
void printIntervals (bool _original=false) const
Prints all intervals from mIntervals, should be the same intervals as in mHistoryActual->intervals().
void printPreprocessedInput (std::string _init="") const
Prints all intervals from mIntervals, should be the same intervals as in mHistoryActual->intervals().
void printContraction (const icp::ContractionCandidate &_cc, const DoubleInterval &_before, const DoubleInterval &_afterA, const DoubleInterval &_afterB=DoubleInterval::emptyInterval(), std::ostream &_out=std::cout) const
Private Attributes
carl::FastMap< Poly, Contractor< carl::SimpleNewton > > mContractors
Members:
icp::ContractionCandidateManager mCandidateManager
std::set< icp::ContractionCandidate *, icp::contractionCandidateComp > mActiveNonlinearConstraints
std::set< icp::ContractionCandidate *, icp::contractionCandidateComp > mActiveLinearConstraints
std::map< const icp::LRAVariable *, ContractionCandidates > mLinearConstraints
std::map< ConstraintT, ContractionCandidates > mNonlinearConstraints
FormulaSetT mNotEqualConstraints
std::map< carl::Variable, icp::IcpVariable * > mVariables
EvalDoubleIntervalMap mIntervals
EvalRationalIntervalMap mInitialIntervals
Model mFoundSolution
std::set< std::pair< double, unsigned >, comp > mIcpRelevantCandidates
carl::FastMap< FormulaT, FormulaT > mLinearizations
carl::FastMap< FormulaT, FormulaT > mDeLinearizations
carl::FastMap< Poly, carl::Variable > mVariableLinearizations
std::map< carl::Variable, Poly > mSubstitutions
icp::HistoryNode * mHistoryRoot
icp::HistoryNode * mHistoryActual
ModuleInput * mValidationFormula
smtrat::Conditionals mLRAFoundAnswer
LRAModule< LRASettingsICP > mLRA
std::queue< FormulasT > mBoxStorage
bool mIsIcpInitialized
bool mSplitOccurred
bool mInvalidBox
bool mOriginalVariableIntervalContracted
bool mLRAFoundSolution
double mTargetDiameter
double mContractionThreshold
double mDefaultSplittingSize
SplittingHeuristic mSplittingHeuristic
unsigned mNumberOfReusagesAfterTargetDiameterReached
double mRelativeContraction
double mAbsoluteContraction
int mCountBackendCalls
double mGlobalBoxSize
double mInitialBoxSize
double mCovererdRegionSize
Static Private Attributes
static const unsigned mSplittingStrategy = 0
Detailed Description
template<class Settings>
class smtrat::ICPModule< Settings >
Definition at line 32 of file ICPModule.h.
Member Function Documentation
activateLinearConstraint()
template<class Settings > void smtrat::ICPModule< Settings >::activateLinearConstraint (const FormulaT & _formula, const FormulaT & _origin) private
Parameters
_formula
Definition at line 572 of file ICPModule.cpp.
activateNonlinearConstraint()
template<class Settings > void smtrat::ICPModule< Settings >::activateNonlinearConstraint (const FormulaT & _formula) private
Parameters
_formula
Definition at line 544 of file ICPModule.cpp.
add()
bool smtrat::Module::add (ModuleInput::const_iterator _subformula) inherited
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Definition at line 153 of file Module.cpp.
Referenced by smtrat::PModule::add(), smtrat::Manager::add(), smtrat::LRAModule< smtrat::LRASettingsICP >::addCore(), smtrat::Manager::getBackends(), and smtrat::EQModule< smtrat::EQSettingsForPreprocessing >::P_add_implicit_edge().
addAssumptionToCheck() [1/4]
void smtrat::Module::addAssumptionToCheck (const FormulaT & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_formula The formula which should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1019 of file Module.cpp.
Referenced by smtrat::Module::addLemma(), smtrat::Module::checkCore(), smtrat::Module::getInfeasibleSubsets(), smtrat::VSModule< Settings >::logConditions(), smtrat::vs::State::passConflictToFather(), and smtrat::VSModule< Settings >::runBackendSolvers().
addAssumptionToCheck() [2/4]
void smtrat::Module::addAssumptionToCheck (const ModuleInput & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_subformulas The sub-formulas whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1032 of file Module.cpp.
addAssumptionToCheck() [3/4]
void smtrat::Module::addAssumptionToCheck (const FormulasT & _formulas, bool _consistent, const std::string & _label) static inherited
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
Parameters
_formulas The formulas, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1058 of file Module.cpp.
addAssumptionToCheck() [4/4]
void smtrat::Module::addAssumptionToCheck (const ConstraintsT & _constraints, bool _consistent, const std::string & _label) static inherited
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
Parameters
_constraints The constraints, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1079 of file Module.cpp.
addCandidateToRelevant()
template<class Settings > bool smtrat::ICPModule< Settings >::addCandidateToRelevant (icp::ContractionCandidate * _candidate) private
Adds the specific candidate to IcpRelevantCandidates.
Parameters
_candidate
Definition at line 978 of file ICPModule.cpp.
addConstraint()
template<class Settings > void smtrat::ICPModule< Settings >::addConstraint (const FormulaT & _formula) private
Parameters
_splitOccurred
Returns
Definition at line 461 of file ICPModule.cpp.
addConstraintToInform()
void smtrat::Module::addConstraintToInform (const FormulaT & _constraint) protected virtual inherited
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
Parameters
_constraint The constraint to add.
Reimplemented in smtrat::SATModule< Settings >.
Definition at line 900 of file Module.cpp.
addCore()
template<class Settings > bool smtrat::ICPModule< Settings >::addCore (ModuleInput::const_iterator) virtual
The module has to take the given sub-formula of the received formula into account.
Parameters
The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Reimplemented from smtrat::Module.
Definition at line 122 of file ICPModule.cpp.
addInformationRelevantFormula()
void smtrat::Module::addInformationRelevantFormula (const FormulaT & formula) protected inherited
Adds a formula to the InformationRelevantFormula.
Parameters
formula Formula to add
Definition at line 1197 of file Module.cpp.
addLemma()
void smtrat::Module::addLemma (const FormulaT & _lemma, const LemmaType & _lt = LemmaType::NORMAL, const FormulaT & _preferredFormula = FormulaT(carl::FormulaType::TRUE)) inline inherited
Stores a lemma being a valid formula.
Parameters
_lemma The eduction/lemma to store.
_lt The type of the lemma.
Definition at line 535 of file Module.h.
addOrigin()
void smtrat::Module::addOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Adds the given set of formulas in the received formula to the origins of the given passed formula.
Parameters
_formula The passed formula to set the origins for.
_origins A set of formulas in the received formula of this module.
Definition at line 867 of file Module.h.
addReceivedSubformulaToPassedFormula()
std::pair<ModuleInput::iterator,bool> smtrat::Module::addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula) inline protected inherited
Copies the given sub-formula of the received formula to the passed formula.
Note, that there is always a link between sub-formulas of the passed formulas to sub-formulas of the received formulas, which are responsible for its occurrence.
Parameters
_subformula The sub-formula of the received formula to copy.
Definition at line 926 of file Module.h.
Referenced by smtrat::Module::checkCore().
addSubformulaToPassedFormula() [1/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula) inline protected inherited
Adds the given formula to the passed formula with no origin.
Note that in the next call of this module's removeSubformula, all formulas in the passed formula without origins will be removed.
Parameters
_formula The formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 942 of file Module.h.
Referenced by smtrat::Module::addReceivedSubformulaToPassedFormula(), smtrat::Module::addSubformulaToPassedFormula(), and smtrat::CNFerModule::checkCore().
addSubformulaToPassedFormula() [2/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origins The link of the formula to add to the passed formula to sub-formulas of the received formulas, which are responsible for its occurrence
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 956 of file Module.h.
addSubformulaToPassedFormula() [3/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const FormulaT & _origin) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origin The sub-formula of the received formula being responsible for the occurrence of the formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 970 of file Module.h.
allModels()
const std::vector<Model>& smtrat::Module::allModels () const inline inherited
Returns
All satisfying assignments, if existent.
Definition at line 486 of file Module.h.
Referenced by smtrat::Manager::allModels().
anAnswerFound()
bool smtrat::Module::anAnswerFound () const inline protected inherited
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
Returns
True, if one of them has determined a result.
Definition at line 806 of file Module.h.
Referenced by smtrat::Module::foundAnswer(), and smtrat::Module::runBackends().
answerFound()
const smtrat::Conditionals& smtrat::Module::answerFound () const inline inherited
Returns
A vector of Booleans: If any of them is true, we have to terminate a running check procedure.
Definition at line 613 of file Module.h.
Referenced by smtrat::Manager::getBackends().
branchAt()
bool smtrat::Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true, bool _useReceivedFormulaAsPremise = false) protected inherited
Adds a lemmas which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
Note that the given value is rounded down and up, if the given variable is integer-valued.
Parameters
_polynomial The variable to branch for. _integral A flag being true, if all variables in the polynomial to branch for are integral.
_value The value to branch at.
_premise The sub-formulas of the received formula from which the branch is followed. Note, that a premise is not necessary, as every branch is a valid formula. But a premise can prevent from branching unnecessarily.
_leftCaseWeak true, if a branching in the form of (or (<= p b) (> p b)) is desired. false, if a branching in the form of (or (< p b) (>= p b)) is desired.
_preferLeftCase true, if the left case (polynomial less(or equal) 0 shall be chosen first. false, otherwise.
_useReceivedFormulaAsPremise true, if the whole received formula should be used as premise
Definition at line 498 of file Module.cpp.
callBackends()
template<class Settings > Answer smtrat::ICPModule< Settings >::callBackends (bool _final = false, bool _full = true, carl::Variable _objective = carl::Variable::NO_VARIABLE) private
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
Definition at line 729 of file ICPModule.cpp.
check()
Answer smtrat::Module::check (bool _final = false, bool _full = true, carl::Variable _objective = carl::Variable::NO_VARIABLE) virtual inherited
Checks the received formula for consistency.
Note, that this is an implementation of the satisfiability check of the conjunction of the so far received formulas, which does actually nothing but passing the problem to its backends. This implementation is only used internally and must be overwritten by any derived module.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
True, if the received formula is satisfiable; False, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented in smtrat::PModule.
Definition at line 92 of file Module.cpp.
Referenced by smtrat::PModule::check(), and smtrat::Manager::check().
checkBoxAgainstLinearFeasibleRegion()
template<class Settings > bool smtrat::ICPModule< Settings >::checkBoxAgainstLinearFeasibleRegion () private
Checks the actual intervalBox with the LRASolver.
Returns
Definition at line 2419 of file ICPModule.cpp.
checkCore()
template<class Settings > Answer smtrat::ICPModule< Settings >::checkCore () virtual
Checks the received formula for consistency.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
SAT, if the received formula is satisfiable; UNSAT, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented from smtrat::Module.
Definition at line 309 of file ICPModule.cpp.
checkInfSubsetForMinimality()
void smtrat::Module::checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string & _filename = "smaller_muses", unsigned _maxSizeDifference = 1) const inherited
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
Parameters
_infsubset The infeasible subset to check for minimality.
_filename The name of the file to store the infeasible subsets in order to be able to check their infeasibility.
_maxSizeDifference The maximal difference between the sizes of the subsets compared to the size of the infeasible subset.
Definition at line 1147 of file Module.cpp.
Referenced by smtrat::GBModule< Settings >::checkCore().
checkModel()
unsigned smtrat::Module::checkModel () const protected inherited
Returns
false, if the current model of this module does not satisfy the current given formula; true, if it cannot be said whether the model satisfies the given formula.
Definition at line 611 of file Module.cpp.
checkNotEqualConstraints()
template<class Settings > bool smtrat::ICPModule< Settings >::checkNotEqualConstraints () private
Returns
Definition at line 610 of file ICPModule.cpp.
chooseContractionCandidate()
template<class Settings > icp::ContractionCandidate * smtrat::ICPModule< Settings >::chooseContractionCandidate () private
Method to determine the next combination of variable and constraint to be contracted.
Parameters
_it
Returns
a pair of variable and constraint
Definition at line 1046 of file ICPModule.cpp.
collectOrigins()
void smtrat::Module::collectOrigins (const FormulaT & _formula, FormulasT & _origins) const inherited
Collects the formulas in the given formula, which are part of the received formula.
If the given formula directly occurs in the received formula, it is inserted into the given set. Otherwise, the given formula must be of type AND and all its sub-formulas part of the received formula. Hence, they will be added to the given set.
Parameters
_formula The formula from which to collect the formulas being sub-formulas of the received formula (origins).
_origins The set in which to store the origins.
Definition at line 985 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
constraintsToInform()
const carl::FastSet<FormulaT>& smtrat::Module::constraintsToInform () const inline inherited
Returns
The constraints which the backends must be informed about.
Definition at line 511 of file Module.h.
contractCurrentBox()
template<class Settings > void smtrat::ICPModule< Settings >::contractCurrentBox () private
Parameters
_splitOccurred
TODO: compare against mRelativeContraction or candidate->RWA()
Definition at line 630 of file ICPModule.cpp.
contraction()
template<class Settings > void smtrat::ICPModule< Settings >::contraction (icp::ContractionCandidate * _selection) private
Calls the actual contraction function and implements threshold functionality.
Parameters
_selection
create prequesites: ((oldBox AND CCs) -> newBox) in CNF: (oldBox OR CCs) OR newBox
Definition at line 1069 of file ICPModule.cpp.
createBoxFormula()
template<class Settings > FormulasT smtrat::ICPModule< Settings >::createBoxFormula (bool _onlyOriginalVariables) private
Parameters
_onlyOriginalVariables
Returns
Definition at line 1637 of file ICPModule.cpp.
createConstraintsFromBounds()
template<class Settings > FormulasT smtrat::ICPModule< Settings >::createConstraintsFromBounds (const EvalDoubleIntervalMap & _map, bool _isOriginal = true) private
creates constraints for the actual bounds of the original variables.
Returns
Definition at line 2815 of file ICPModule.cpp.
createLinearCCs()
template<class Settings > void smtrat::ICPModule< Settings >::createLinearCCs (const FormulaT & _constraint, const FormulaT & _original) private
Creates the linear contraction candidates corresponding to the given linear constraint.
Parameters
_constraint
_origin
Definition at line 895 of file ICPModule.cpp.
createModel()
template<class Settings > std::map< carl::Variable, double > smtrat::ICPModule< Settings >::createModel (bool antipoint = false) const private
Parameters
antipoint
Returns
Definition at line 1321 of file ICPModule.cpp.
createPremiseDeductions()
template<class Settings > FormulaSetT smtrat::ICPModule< Settings >::createPremiseDeductions () private
Returns
Definition at line 1610 of file ICPModule.cpp.
currentlySatisfied()
virtual unsigned smtrat::Module::currentlySatisfied (const FormulaT &) const inline virtual inherited
Returns
0, if the given formula is conflicted by the current model; 1, if the given formula is satisfied by the current model; 2, otherwise; 3, if we do not know anything (default)
Reimplemented in smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, and smtrat::LRAModule< smtrat::LRASettingsICP >.
Definition at line 387 of file Module.h.
currentlySatisfiedByBackend()
unsigned smtrat::Module::currentlySatisfiedByBackend (const FormulaT & _formula) const inherited
Returns
0, if the given formula is conflicted by the current model; 1, if the given formula is satisfied by the current model; 2, otherwise 3, if we do not know anything (default)
Definition at line 316 of file Module.cpp.
deinform()
void smtrat::Module::deinform (const FormulaT & _constraint) inherited
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Definition at line 139 of file Module.cpp.
Referenced by smtrat::Manager::deinform().
deinformCore()
virtual void smtrat::Module::deinformCore (const FormulaT &) inline protected virtual inherited
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Reimplemented in smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, and smtrat::LRAModule< smtrat::LRASettingsICP >.
Definition at line 766 of file Module.h.
determine_smallest_origin()
size_t smtrat::Module::determine_smallest_origin (const std::vector< FormulaT > & origins) const protected inherited
Parameters
origins A vector of sets of origins.
Returns
The index of the smallest (regarding the size of the sets) element of origins
Definition at line 423 of file Module.cpp.
eraseSubformulaFromPassedFormula()
template<class Settings > ModuleInput::iterator smtrat::ICPModule< Settings >::eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins = false) protected virtual
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
Afterwards the sub-formula is removed from the passed formula.
Parameters
_subformula The sub-formula to remove from the passed formula.
_ignoreOrigins SAT, if the sub-formula shall be removed regardless of its origins (should only be applied with expertise).
Returns
Reimplemented from smtrat::Module.
Definition at line 1523 of file ICPModule.cpp.
findBestOrigin()
std::vector< FormulaT >::const_iterator smtrat::Module::findBestOrigin (const std::vector< FormulaT > & _origins) const protected inherited
Parameters
_origins
Returns
Definition at line 714 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
firstSubformulaToPass()
ModuleInput::const_iterator smtrat::Module::firstSubformulaToPass () const inline inherited
Returns
The position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
Definition at line 597 of file Module.h.
Referenced by smtrat::Manager::getBackends().
firstUncheckedReceivedSubformula()
ModuleInput::const_iterator smtrat::Module::firstUncheckedReceivedSubformula () const inline inherited
Returns
The position of the first (by this module) unchecked sub-formula of the received formula.
Definition at line 589 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore().
getIcpVariable()
template<class Settings > icp::IcpVariable * smtrat::ICPModule< Settings >::getIcpVariable (carl::Variable::Arg _var, bool _original, const icp::LRAVariable * _lraVar) private
Parameters
_var
_original
_lraVar
Returns
Definition at line 531 of file ICPModule.cpp.
getInfeasibleSubsets()
std::vector< FormulaSetT > smtrat::Module::getInfeasibleSubsets (const Module & _backend) const protected inherited
Get the infeasible subsets the given backend provides.
Note, that an infeasible subset in a backend contains sub formulas of the passed formula and an infeasible subset of this module contains sub formulas of the received formula. In this method the LATTER is returned.
Parameters
_backend The backend from which to obtain the infeasible subsets.
Returns
The infeasible subsets the given backend provides.
Definition at line 732 of file Module.cpp.
getInformationRelevantFormulas()
const std::set< FormulaT > & smtrat::Module::getInformationRelevantFormulas () protected inherited
Gets all InformationRelevantFormulas.
Returns
Set of all formulas
Definition at line 1203 of file Module.cpp.
getModelEqualities()
std::list< std::vector< carl::Variable > > smtrat::Module::getModelEqualities () const virtual inherited
Partition the variables from the current model into equivalence classes according to their assigned value.
The result is a set of equivalence classes of variables where all variables within one class are assigned the same value. Note that the number of classes may not be minimal, i.e. two classes may actually be equivalent.
Returns
Equivalence classes.
Definition at line 328 of file Module.cpp.
Referenced by smtrat::Manager::getModelEqualities().
getOrigins() [1/3]
const FormulaT& smtrat::Module::getOrigins (ModuleInput::const_iterator _formula) const inline protected inherited
Gets the origins of the passed formula at the given position.
Parameters
_formula The position of a formula in the passed formulas.
Returns
The origins of the passed formula at the given position.
Definition at line 877 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets().
getOrigins() [2/3]
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulasT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 1024 of file Module.h.
getOrigins() [3/3]
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulaSetT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 1037 of file Module.h.
getReceivedFormulaSimplified()
std::pair< bool, FormulaT > smtrat::Module::getReceivedFormulaSimplified () virtual inherited
Returns
A pair of a Boolean and a formula, where the Boolean is true, if the received formula could be simplified to an equisatisfiable formula. The formula is equisatisfiable to this module's reveived formula, if the Boolean is true.
Reimplemented in smtrat::PModule.
Definition at line 970 of file Module.cpp.
Referenced by smtrat::Manager::getInputSimplified().
hasValidInfeasibleSubset()
bool smtrat::Module::hasValidInfeasibleSubset () const inherited
Returns
true, if the module has at least one valid infeasible subset, that is all its elements are sub-formulas of the received formula (pointer must be equal).
Definition at line 1129 of file Module.cpp.
id()
std::size_t smtrat::Module::id () const inline inherited
Returns
A unique ID to identify this module instance.
Definition at line 411 of file Module.h.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::addCandidateToRelevant(), smtrat::ICPModule< smtrat::ICPSettings4 >::removeCandidateFromRelevant(), and smtrat::ICPModule< smtrat::ICPSettings4 >::updateRelevantCandidates().
infeasibleSubsets()
const std::vector<FormulaSetT>& smtrat::Module::infeasibleSubsets () const inline inherited
Returns
The infeasible subsets of the set of received formulas (empty, if this module has not detected unsatisfiability of the conjunction of received formulas.
Definition at line 495 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets(), smtrat::Manager::infeasibleSubsets(), smtrat::Manager::printInfeasibleSubset(), and smtrat::ICPModule< smtrat::ICPSettings4 >::remapAndSetLraInfeasibleSubsets().
inform()
bool smtrat::Module::inform (const FormulaT & _constraint) inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Definition at line 132 of file Module.cpp.
Referenced by smtrat::Manager::add(), smtrat::Manager::getBackends(), smtrat::Manager::inform(), and smtrat::Manager::Manager().
informBackends()
void smtrat::Module::informBackends (const FormulaT & _constraint) inline protected inherited
Informs all backends of this module about the given constraint.
Parameters
_constraint The constraint to inform about.
Definition at line 905 of file Module.h.
informCore()
template<class Settings > bool smtrat::ICPModule< Settings >::informCore (const FormulaT &) virtual
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Reimplemented from smtrat::Module.
Definition at line 103 of file ICPModule.cpp.
informedConstraints()
const carl::FastSet<FormulaT>& smtrat::Module::informedConstraints () const inline inherited
Returns
The position of the first constraint of which no backend has been informed about.
Definition at line 519 of file Module.h.
Referenced by smtrat::Manager::getBackends().
init()
void smtrat::Module::init () virtual inherited
Informs all backends about the so far encountered constraints, which have not yet been communicated.
This method must not be called twice and only before the first runBackends call.
Reimplemented in smtrat::EQModule< Settings >, smtrat::EQModule< smtrat::EQSettingsForPreprocessing >, smtrat::IntBlastModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::LRAModule< smtrat::LRASettingsICP >, smtrat::PBPPModule< Settings >, smtrat::NewCADModule< Settings >, smtrat::BVModule< Settings >, smtrat::CurryModule< Settings >, smtrat::PBGaussModule< Settings >, smtrat::NRAILModule< Settings >, and smtrat::FPPModule< Settings >.
Definition at line 254 of file Module.cpp.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::addCore(), and smtrat::SATModule< Settings >::checkCore().
initialLinearCheck()
template<class Settings > bool smtrat::ICPModule< Settings >::initialLinearCheck (Answer & _answer) private
Performs a consistency check on the linearization of the received constraints.
Parameters
_answer The answer of the consistency check on the linearization of the received constraints.
Returns
true, if the linear check led to a conclusive answer which should be returned by this module; false, otherwise.
Definition at line 2305 of file ICPModule.cpp.
isLemmaLevel()
bool smtrat::Module::isLemmaLevel (LemmaLevel level) protected inherited
Checks if current lemma level is greater or equal to given level.
Parameters
level Level to check.
Definition at line 1208 of file Module.cpp.
isPreprocessor()
bool smtrat::Module::isPreprocessor () const inline inherited
Returns
true, if this module is a preprocessor that is a module, which simplifies its received formula to an equisatisfiable formula being passed to its backends. The simplified formula can be obtained with getReceivedFormulaSimplified().
Definition at line 623 of file Module.h.
lemmas()
const std::vector<Lemma>& smtrat::Module::lemmas () const inline inherited
Returns
A constant reference to the lemmas being valid formulas this module or its backends made.
Definition at line 581 of file Module.h.
Referenced by smtrat::Manager::lemmas().
merge()
std::vector< FormulaT > smtrat::Module::merge (const std::vector< FormulaT > & _vecSetA, const std::vector< FormulaT > & _vecSetB) const protected inherited
Merges the two vectors of sets into the first one.
({a,b},{a,c}) and ({b,d},{b}) -> ({a,b,d},{a,b},{a,b,c,d},{a,b,c})
Parameters
_vecSetA A vector of sets of constraints.
_vecSetB A vector of sets of constraints.
Returns
The vector being the two given vectors merged.
Definition at line 397 of file Module.cpp.
model()
const Model& smtrat::Module::model () const inline inherited
Returns
The assignment of the current satisfiable result, if existent.
Definition at line 478 of file Module.h.
Referenced by smtrat::Module::backendsModel(), smtrat::Module::clearModels(), smtrat::Module::getBackendsAllModels(), and smtrat::Manager::model().
modelsDisjoint()
bool smtrat::Module::modelsDisjoint (const Model & _modelA, const Model & _modelB) static protected inherited
Checks whether there is no variable assigned by both models.
Parameters
_modelA The first model to check for.
_modelB The second model to check for.
Returns
true, if there is no variable assigned by both models; false, otherwise.
Definition at line 634 of file Module.cpp.
moduleName()
template<class Settings> std::string smtrat::ICPModule< Settings >::moduleName () const inline virtual
Returns
The name of the given module type as name.
Reimplemented from smtrat::Module.
Definition at line 135 of file ICPModule.h.
passedFormulaBegin()
ModuleInput::iterator smtrat::Module::passedFormulaBegin () inline protected inherited
Returns
An iterator to the end of the passed formula. TODO: disable this method
Definition at line 849 of file Module.h.
passedFormulaEnd()
ModuleInput::iterator smtrat::Module::passedFormulaEnd () inline protected inherited
Returns
An iterator to the end of the passed formula.
Definition at line 857 of file Module.h.
performSplit()
template<class Settings > bool smtrat::ICPModule< Settings >::performSplit (bool _contractionApplied, bool & _moreContractionFound) private
Parameters
_contractionApplied
_moreConstactionFound
Returns
If a split has happened.
Definition at line 1657 of file ICPModule.cpp.
pPassedFormula()
const ModuleInput* smtrat::Module::pPassedFormula () const inline inherited
Returns
A pointer to the formula passed to the backends of this module.
Definition at line 462 of file Module.h.
Referenced by smtrat::Manager::getBackends().
pReceivedFormula()
const ModuleInput* smtrat::Module::pReceivedFormula () const inline inherited
Returns
A pointer to the formula passed to this module.
Definition at line 446 of file Module.h.
print()
void smtrat::Module::print (const std::string & _initiation = "***") const inherited
Prints everything relevant of the solver.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1214 of file Module.cpp.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::activateNonlinearConstraint().
printAllModels()
void smtrat::Module::printAllModels (std::ostream & _out = std::cout) inherited
Prints all assignments of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1290 of file Module.cpp.
Referenced by smtrat::Manager::printAllAssignments().
printInfeasibleSubsets()
void smtrat::Module::printInfeasibleSubsets (const std::string & _initiation = "***") const inherited
Prints the infeasible subsets.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1265 of file Module.cpp.
printModel()
void smtrat::Module::printModel (std::ostream & _out = std::cout) const inherited
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1280 of file Module.cpp.
Referenced by smtrat::Manager::printAssignment().
printPassedFormula()
void smtrat::Module::printPassedFormula (const std::string & _initiation = "***") const inherited
Prints the vector of passed formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1247 of file Module.cpp.
printReceivedFormula()
void smtrat::Module::printReceivedFormula (const std::string & _initiation = "***") const inherited
Prints the vector of the received formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1234 of file Module.cpp.
probablyLooping()
bool smtrat::Module::probablyLooping (const typename Poly::PolyType & _branchingPolynomial, const Rational & _branchingValue) const protected inherited
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
Parameters
_branchingPolynomial The polynomial to branch at (in most branching strategies this is just a variable).
_branchingValue The value to branch at.
Returns
true, if this branching is probably part of an infinite loop of branchings; false, otherwise.
Definition at line 446 of file Module.cpp.
remove()
void smtrat::Module::remove (ModuleInput::const_iterator _subformula) virtual inherited
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
_subformula The sub formula of the received formula to remove.
Reimplemented in smtrat::PModule.
Definition at line 174 of file Module.cpp.
Referenced by smtrat::PModule::remove(), smtrat::Manager::remove(), and smtrat::LRAModule< smtrat::LRASettingsICP >::removeCore().
removeCandidateFromRelevant()
template<class Settings > bool smtrat::ICPModule< Settings >::removeCandidateFromRelevant (icp::ContractionCandidate * _candidate) private
Removes a candidate from the icpRelevantCandidates.
Parameters
_candidate
Definition at line 1000 of file ICPModule.cpp.
removeCore()
template<class Settings > void smtrat::ICPModule< Settings >::removeCore (ModuleInput::const_iterator) virtual
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
The sub formula of the received formula to remove.
Reimplemented from smtrat::Module.
Definition at line 221 of file ICPModule.cpp.
resetHistory()
template<class Settings > void smtrat::ICPModule< Settings >::resetHistory (icp::ContractionCandidate * _cc) private
Methods:
Reset to state before application of this cc.
Reset the current state to a state before this contraction was applied. As we only have two states, we check, if this cc has been used yet and if so, we reset the state, else the state remains unchanged.
Parameters
_cc [description]
Definition at line 449 of file ICPModule.cpp.
rPassedFormula()
const ModuleInput& smtrat::Module::rPassedFormula () const inline inherited
Returns
A reference to the formula passed to the backends of this module.
Definition at line 470 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Manager::getBackends().
rReceivedFormula()
const ModuleInput& smtrat::Module::rReceivedFormula () const inline inherited
Returns
A reference to the formula passed to this module.
Definition at line 454 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Module::generateTrivialInfeasibleSubset().
runBackends()
Answer smtrat::Module::runBackends (bool _final, bool _full, carl::Variable _objective) protected virtual inherited
Runs the backend solvers on the passed formula.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
True, if the passed formula is consistent; False, if the passed formula is inconsistent; Unknown, otherwise.
Reimplemented in smtrat::PModule.
Definition at line 752 of file Module.cpp.
Referenced by smtrat::Module::checkCore().
satBasedSplitting()
template<class Settings > bool smtrat::ICPModule< Settings >::satBasedSplitting (carl::Variable & _variable, Rational & _value, bool & _leftCaseWeak, bool & _preferLeftCase) private
Parameters
_variable
_value
_leftCaseWeak
_preferLeftCase
Returns
Definition at line 1850 of file ICPModule.cpp.
setBox()
template<class Settings > void smtrat::ICPModule< Settings >::setBox (icp::HistoryNode * _selection) private
Set all parameters of the module according to the selected HistoryNode.
Parameters
_selection the Node which contains the new context
Definition at line 2975 of file ICPModule.cpp.
setId()
void smtrat::Module::setId (std::size_t _id) inline inherited
Sets this modules unique ID to identify itself.
Parameters
_id The id to set this module's id to.
Definition at line 420 of file Module.h.
Referenced by smtrat::Manager::getBackends().
setThreadPriority()
void smtrat::Module::setThreadPriority (thread_priority _threadPriority) inline inherited
Sets the priority of this module to get a thread for running its check procedure.
Parameters
_threadPriority The priority to set this module's thread priority to.
Definition at line 438 of file Module.h.
Referenced by smtrat::Manager::getBackends().
sizeBasedSplitting()
template<class Settings > void smtrat::ICPModule< Settings >::sizeBasedSplitting (carl::Variable & _variable, Rational & _value, bool & _leftCaseWeak, bool & _preferLeftCase) private
Parameters
_variable
_value
_leftCaseWeak
_preferLeftCase
Definition at line 1806 of file ICPModule.cpp.
sizeBasedSplittingImpact()
template<class Settings > double smtrat::ICPModule< Settings >::sizeBasedSplittingImpact (std::map< carl::Variable, icp::IcpVariable *>::const_iterator _varIcpVarMapIter) const private
Selects the next splitting direction according to different heuristics.
Parameters
_targetDiameter
Returns
Definition at line 1548 of file ICPModule.cpp.
solverState()
Answer smtrat::Module::solverState () const inline inherited
Returns
True, if this module is in a state, such that it has found a solution for its received formula; False, if this module is in a state, such that it has determined that there is no solution for its received formula; Unknown, otherwise.
Definition at line 403 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), smtrat::Module::getReceivedFormulaSimplified(), and smtrat::Module::updateAllModels().
splitUnequalConstraint()
void smtrat::Module::splitUnequalConstraint (const FormulaT & _unequalConstraint) protected inherited
Adds the following lemmas for the given constraint p!=0.
(p!=0 <-> (p<0 or p>0)) and not(p<0 and p>0)
Parameters
_unequalConstraint A constraint having the relation symbol !=.
Definition at line 588 of file Module.cpp.
storeAssumptionsToCheck()
void smtrat::Module::storeAssumptionsToCheck (const Manager & _manager) static inherited
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Parameters
_manager The manager object of this solver to store the assumptions for.
Definition at line 1099 of file Module.cpp.
Referenced by smtrat::Manager::~Manager().
threadPriority()
thread_priority smtrat::Module::threadPriority () const inline inherited
Returns
The priority of this module to get a thread for running its check procedure.
Definition at line 429 of file Module.h.
Referenced by smtrat::Manager::getBackends().
tryTestPoints()
template<class Settings > bool smtrat::ICPModule< Settings >::tryTestPoints () private
Parameters
_solution
Returns
Definition at line 2195 of file ICPModule.cpp.
updateAbsoluteContraction()
template<class Settings > void smtrat::ICPModule< Settings >::updateAbsoluteContraction (const DoubleInterval & _interval, const DoubleInterval & _contractedInterval) private
Parameters
_interval
_contractedInterval
Definition at line 1265 of file ICPModule.cpp.
updateRelativeContraction()
template<class Settings > void smtrat::ICPModule< Settings >::updateRelativeContraction (const DoubleInterval & _interval, const DoubleInterval & _contractedInterval) private
Parameters
_interval
_contractedInterval
Definition at line 1225 of file ICPModule.cpp.
updateRelevantCandidates()
template<class Settings > void smtrat::ICPModule< Settings >::updateRelevantCandidates (carl::Variable::Arg _var) private
Update all affected candidates and reinsert them into icpRelevantCandidates.
Parameters
_var
Definition at line 1017 of file ICPModule.cpp.
usedBackends()
const std::vector<Module*>& smtrat::Module::usedBackends () const inline inherited
Returns
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
Definition at line 503 of file Module.h.
Referenced by smtrat::Module::getReceivedFormulaSimplified().
variableReasonHull()
template<class Settings > FormulasT smtrat::ICPModule< Settings >::variableReasonHull (icp::set_icpVariable & _reasons) private
Compute hull of defining origins for set of icpVariables.
Parameters
_reasons
Returns
Definition at line 2761 of file ICPModule.cpp.
The documentation for this class was generated from the following files:
smtrat-modules/ICPModule/ICPModule.h
smtrat-modules/ICPModule/ICPModule.cpp