SMT-RAT: smtrat::Model Class Reference
smtrat::Model Class Reference
Data type for a assignment assigning a variable, represented as a string, a real algebraic number, represented as a string.
#include <Model.h>
Public Types
using Map = std::map< ModelVariable, ModelValue >
Public Member Functions
auto at (const Map::key_type &key) const -> decltype(mData.at(key))
auto begin () const -> decltype(mData.begin())
auto end () const -> decltype(mData.end())
auto empty () const -> decltype(mData.empty())
auto size () const -> decltype(mData.size())
void clear ()
template<typename P >
auto insert (const P &pair) -> decltype(mData.insert(pair))
template<typename P >
auto insert (Map::const_iterator it, const P &pair) -> decltype(mData.insert(it, pair))
template<typename... Args>
auto emplace (const Map::key_type &key, Args &&...args) -> decltype(mData.emplace(key, std::forward< Args >(args)...))
template<typename... Args>
auto emplace_hint (Map::const_iterator it, const Map::key_type &key, Args &&...args) -> decltype(mData.emplace_hint(it, key, std::forward< Args >(args)...))
Map::iterator erase (const ModelVariable &variable)
Map::iterator erase (const Map::iterator &it)
Map::iterator erase (const Map::const_iterator &it)
void clean ()
auto find (const Map::key_type &key) const -> decltype(mData.find(key))
auto find (const Map::key_type &key) -> decltype(mData.find(key))
template<typename T >
void assign (const Map::key_type &key, const T &t)
void merge (const Model &model, bool overwrite=false)
Private Attributes
Map mData
std::map< ModelVariable,
std::size_t > mUsedInSubstitution
Detailed Description
Data type for a assignment assigning a variable, represented as a string, a real algebraic number, represented as a string.
Basically a wrapper around std::map.
Definition at line 13 of file Model.h.
Member Typedef Documentation
using smtrat::Model::Map = std::map<ModelVariable,ModelValue>
Definition at line 16 of file Model.h.
Member Function Documentation
template<typename T > void smtrat::Model::assign (const Map::key_type & key, const T & t) inline
Definition at line 98 of file Model.h.
auto smtrat::Model::at (const Map::key_type & key) const -> decltype(mData.at(key)) inline
Definition at line 22 of file Model.h.
auto smtrat::Model::begin () const -> decltype(mData.begin()) inline
Definition at line 27 of file Model.h.
Referenced by smtrat::CubeLIAModule< Settings >::checkCore(), smtrat::BVModule< Settings >::checkCore(), smtrat::Module::excludeNotReceivedVariablesFromModel(), smtrat::getRationalAssignmentsFromModel(), smtrat::isPartOf(), smtrat::Module::modelsDisjoint(), smtrat::operator<<(), and smtrat::Manager::printAssignment().
void smtrat::Model::clean () inline
Definition at line 79 of file Model.h.
Referenced by smtrat::Module::cleanModel(), smtrat::Manager::printAssignment(), and smtrat::Module::printModel().
void smtrat::Model::clear () inline
Definition at line 41 of file Model.h.
Referenced by smtrat::Module::clearModel(), smtrat::Module::clearModels(), and smtrat::SATModule< Settings >::updateModel().
template<typename... Args> auto smtrat::Model::emplace (const Map::key_type & key, Args &&... args) -> decltype(mData.emplace(key,std::forward<Args>(args)...)) inline
Definition at line 53 of file Model.h.
Referenced by smtrat::getDefaultModel().
template<typename... Args> auto smtrat::Model::emplace_hint (Map::const_iterator it, const Map::key_type & key, Args &&... args) -> decltype(mData.emplace_hint(it, key,std::forward<Args>(args)...)) inline
Definition at line 57 of file Model.h.
auto smtrat::Model::empty () const -> decltype(mData.empty()) inline
Definition at line 34 of file Model.h.
Referenced by smtrat::Module::excludeNotReceivedVariablesFromModel(), smtrat::Manager::printAssignment(), and smtrat::Module::printModel().
auto smtrat::Model::end () const -> decltype(mData.end()) inline
Definition at line 30 of file Model.h.
Referenced by smtrat::Manager::check(), smtrat::ModelPolynomialSubstitution::evaluate(), smtrat::Module::excludeNotReceivedVariablesFromModel(), smtrat::getDefaultModel(), smtrat::getRationalAssignmentsFromModel(), smtrat::isPartOf(), smtrat::Module::modelsDisjoint(), smtrat::operator<<(), smtrat::Manager::optimum(), smtrat::Manager::printAssignment(), smtrat::satisfies(), and smtrat::BVModule< Settings >::transferBackendModel().
Map::iterator smtrat::Model::erase (const ModelVariable & variable) inline
Definition at line 60 of file Model.h.
Referenced by smtrat::parser::InstructionHandler::cleanModel(), erase(), smtrat::Module::excludeNotReceivedVariablesFromModel(), and smtrat::Manager::printAssignment().
Map::iterator smtrat::Model::erase (const Map::iterator & it) inline
Definition at line 63 of file Model.h.
Map::iterator smtrat::Model::erase (const Map::const_iterator & it) inline
Definition at line 66 of file Model.h.
auto smtrat::Model::find (const Map::key_type & key) const -> decltype(mData.find(key)) inline
Definition at line 89 of file Model.h.
Referenced by smtrat::Manager::check(), smtrat::MCBModelSubstitution::evaluate(), smtrat::ModelPolynomialSubstitution::evaluate(), smtrat::getDefaultModel(), smtrat::Module::modelsDisjoint(), smtrat::Manager::optimum(), smtrat::satisfies(), and smtrat::BVModule< Settings >::transferBackendModel().
auto smtrat::Model::find (const Map::key_type & key) -> decltype(mData.find(key)) inline
Definition at line 92 of file Model.h.
template<typename P > auto smtrat::Model::insert (const P & pair) -> decltype(mData.insert(pair)) inline
Definition at line 45 of file Model.h.
Referenced by smtrat::SATModule< Settings >::updateModel(), and smtrat::IntBlastModule< Settings >::updateModelFromBV().
template<typename P > auto smtrat::Model::insert (Map::const_iterator it, const P & pair) -> decltype(mData.insert(it, pair)) inline
Definition at line 49 of file Model.h.
void smtrat::Model::merge (const Model & model, bool overwrite = false) inline
Definition at line 103 of file Model.h.
Referenced by smtrat::Module::getBackendsModel().
auto smtrat::Model::size () const -> decltype(mData.size()) inline
Definition at line 37 of file Model.h.
Field Documentation
Map smtrat::Model::mData private
Definition at line 18 of file Model.h.
Referenced by assign(), at(), begin(), clean(), clear(), emplace(), emplace_hint(), empty(), end(), erase(), find(), insert(), merge(), and size().
std::map<ModelVariable, std::size_t> smtrat::Model::mUsedInSubstitution private
Definition at line 19 of file Model.h.
The documentation for this class was generated from the following file:
lib/datastructures/model/Model.h