SMT-RAT: smtrat::union_find< T, no_compression, MaxTracebackLength > Class Template Reference
smtrat::union_find< T, no_compression, MaxTracebackLength > Class Template Reference
Implements a union-find datastructure, a datastructure containing an array of entries.
#include <union_find.h>
Public Member Functions
union_find ()
Construct union-find datastructure with an empty array of entries.
union_find (std::size_t size_)
Construct union-find datastructure with an array of size_ default-constructed elements.
template<typename InputIterator >
union_find (InputIterator begin_, typename std::enable_if< !std::is_void< T >::value, InputIterator >::type end_)
Construct union-find datastructure, copying the sequence identified by [begin_,end_) into the array.
union_find (const union_find &other)
union_find & operator= (const union_find &other)
std::size_t find (std::size_t index_) const noexcept
Find the index of the representative of the entry at index index_.
bool equivalent (std::size_t index1, std::size_t index2) const noexcept
Determines if the two entries at positions index1 and index2 are considered equivalent, that is find(index1) == find(index2).
bool union_ (std::size_t index1, std::size_t index2) noexcept
Make the entries identified by index1 and index2 equivalent.
std::size_t fast_union (std::size_t rep1, std::size_t rep2)
As union_, but does NOT compute find(rep1), find(rep2), but assumes both indices are already pointing to representatives.
template<bool Ignore = true>
std::enable_if< !std::is_void< T >::value &&Ignore, std::size_t >::type add (const T &value)
Add a new default-constructed value to the end of this union find array.
void set_class (std::size_t i, std::size_t c)
std::size_t rank (std::size_t i)
The rank (upper bound on the height of the tree rooted at i) of the entry at index i.
template<bool Ignore = true>
std::enable_if< !std::is_void< T >::value &&Ignore, T >::type & operator[] (std::size_t index_) noexcept
Access to values (only if T is not void, relies on C++11 feature: default template arguments for template methods).
template<bool Ignore = true>
std::enable_if< !std::is_void< T >::value &&Ignore, const T >::type & operator[] (std::size_t index_) const noexcept
Access to values (only if T is not void, relies on C++11 feature: default template arguments for template methods), const.
std::size_t size () const noexcept
Returns the number of entries in this union-find datastructure.
template<bool Ignore = true>
std::enable_if<!std::is_void< T >::value &&Ignore, void >::type initialize (std::size_t new_size)
Initialize the union-find datastructure with an array of new_size default-constructed entries, version for T != void.
template<bool Ignore = true>
std::enable_if< std::is_void< T >::value &&Ignore, void >::type initialize (std::size_t new_size)
Initialize the union-find datastructure with an array of new_size default-constructed entries, version for T == void.
template<typename InputIterator >
std::enable_if<!std::is_void< T >::value &&!std::is_void< InputIterator >::value, void >::type initialize (InputIterator begin_, InputIterator end_)
Initialize the union-find datastructure with an array of entries copied from the sequence [begin_,end_).
Private Types
typedef uf_impl::uf_data_wrapper< T, sizeof(std::size_t)==8 &&!no_compression > wrapper_type
Private Member Functions
std::size_t P_do_find (std::size_t index_) noexcept
Perform the find operation (walk the path until an entry with class == index is found).
std::size_t P_union_by_rank (std::size_t index1, std::size_t index2)
Union the two elements (must be representatives) by rank.
Private Attributes
std::vector< wrapper_type > M_array
The backing vector of the datastructure.
Detailed Description
template<typename T = void, bool no_compression = true, std::size_t MaxTracebackLength = 64>
class smtrat::union_find< T, no_compression, MaxTracebackLength >
Implements a union-find datastructure, a datastructure containing an array of entries.
Basically, this is an array of elements of type T with the following extra structure: Every entry is contained in an equivalence class identified by a single representative entry. In order to find this representative, every element has an associated parent entry; if this is the entry itself, the entry is the representative of its equivalence class. Using a rank count (basically a lower bound for the height of the tree below an entry), the height of the trees below the representative entries is ALWAYS less than ceil(log2(#entries)). Moreover, while finding the parent of an entry, all entries on the path to the root are set to directly point to the root element. This improves the amortized number of steps used to find the representative of an entry from O(log2(n)) to O(a(n)) where a(n) is the inverse of the Ackermann function. All this extra structure is embedded directly within the array.
Definition at line 158 of file union_find.h.
Member Function Documentation
add()
template<typename T = void, bool no_compression = true, std::size_t MaxTracebackLength = 64> template<bool Ignore = true> std::enable_if< !std::is_void<T>::value && Ignore, std::size_t>::type smtrat::union_find< T, no_compression, MaxTracebackLength >::add (const T & value) inline
Add a new default-constructed value to the end of this union find array.
This does not check for the uniqueness of this entry. This method can not be used if T is void. Returns the index associated with the new entry (i.e. the size of the UF structure before the call).
Definition at line 252 of file union_find.h.
fast_union()
template<typename T = void, bool no_compression = true, std::size_t MaxTracebackLength = 64> std::size_t smtrat::union_find< T, no_compression, MaxTracebackLength >::fast_union (std::size_t rep1, std::size_t rep2) inline
As union_, but does NOT compute find(rep1), find(rep2), but assumes both indices are already pointing to representatives.
Returns the new representative of both elements after the operation; this will either be rep1 or rep2.
Definition at line 237 of file union_find.h.
find()
template<typename T = void, bool no_compression = true, std::size_t MaxTracebackLength = 64> std::size_t smtrat::union_find< T, no_compression, MaxTracebackLength >::find (std::size_t index_) const inline noexcept
Find the index of the representative of the entry at index index_.
Note that this method is const-qualified as it does not change the observable behaviour of this class, but it is not bitwise-const due to the path compression behaviour. Therefore it is not safe to call this method from different threads on the same UF datastructure without external synchronization.
Definition at line 201 of file union_find.h.
Referenced by smtrat::union_find< g_iterator, !smtrat::EQSettingsForPreprocessing ::uf_use_compression, smtrat::EQSettingsForPreprocessing ::uf_max_traceback_length >::equivalent(), smtrat::union_find< g_iterator, !smtrat::EQSettingsForPreprocessing ::uf_use_compression, smtrat::EQSettingsForPreprocessing ::uf_max_traceback_length >::fast_union(), and smtrat::union_find< g_iterator, !smtrat::EQSettingsForPreprocessing ::uf_use_compression, smtrat::EQSettingsForPreprocessing ::uf_max_traceback_length >::union_().
union_()
template<typename T = void, bool no_compression = true, std::size_t MaxTracebackLength = 64> bool smtrat::union_find< T, no_compression, MaxTracebackLength >::union_ (std::size_t index1, std::size_t index2) inline noexcept
Make the entries identified by index1 and index2 equivalent.
As this is determined by the union-by-rank mechanism, either one of find(index1) or find(index2) can become the index of the new representative of both entries. Returns false when this operation did no changes on the datastructure and true otherwise.
Definition at line 219 of file union_find.h.
The documentation for this class was generated from the following file:
lib/datastructures/eq/union_find.h