SMT-RAT: ManageSolversDialog Class Reference
ManageSolversDialog Class Reference
Data Structures
class DeleteSolverAction
class ExportSolverAction
class OkAction
class SolverNameDocumentListener
class TakeOverSolverNameAction
Public Member Functions
ManageSolversDialog (GUI gui, String solverNameSuggestion)
Static Public Member Functions
static String showDialog (GUI gui, String solverNameSuggestion)
Private Member Functions
void checkSolverName ()
String findCorrespondingSolverName (ArrayList< String > list, String value)
void updateAvailableSolvers (String solverName, boolean add)
Static Private Attributes
static final int DIALOG_PADDING
static final int LIST_HEIGHT
static ArrayList< String > existingSolverNames
static String notAllowedSolverName
static boolean existingSolverNameEntered
static String solverName
static JTextField solverNameTextField
static JButton exportButton
static JScrollPane availableSolversScrollPane
Detailed Description
Definition at line 35 of file ManageSolversDialog.java.
Constructor & Destructor Documentation
ManageSolversDialog.ManageSolversDialog (GUI gui, String solverNameSuggestion) inline
Definition at line 49 of file ManageSolversDialog.java.
Referenced by showDialog().
Member Function Documentation
void ManageSolversDialog.checkSolverName () inline private
Definition at line 125 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog.SolverNameDocumentListener.changedUpdate(), ManageSolversDialog.SolverNameDocumentListener.insertUpdate(), ManageSolversDialog(), and ManageSolversDialog.SolverNameDocumentListener.removeUpdate().
String ManageSolversDialog.findCorrespondingSolverName (ArrayList< String > list, String value) inline private
Definition at line 151 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog.ExportSolverAction.actionPerformed(), and checkSolverName().
static String ManageSolversDialog.showDialog (GUI gui, String solverNameSuggestion) inline static
Definition at line 119 of file ManageSolversDialog.java.
void ManageSolversDialog.updateAvailableSolvers (String solverName, boolean add) inline private
Definition at line 165 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog.DeleteSolverAction.actionPerformed(), ManageSolversDialog.ExportSolverAction.actionPerformed(), and ManageSolversDialog().
Field Documentation
JScrollPane ManageSolversDialog.availableSolversScrollPane static private
Definition at line 47 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog().
final int ManageSolversDialog.DIALOG_PADDING static private
Definition at line 37 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog().
boolean ManageSolversDialog.existingSolverNameEntered static private
Definition at line 42 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog.ExportSolverAction.actionPerformed(), and checkSolverName().
ArrayList<String> ManageSolversDialog.existingSolverNames static private
Definition at line 40 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog.ExportSolverAction.actionPerformed(), checkSolverName(), ManageSolversDialog(), and updateAvailableSolvers().
JButton ManageSolversDialog.exportButton static private
Definition at line 46 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog().
final int ManageSolversDialog.LIST_HEIGHT static private
Definition at line 38 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog().
String ManageSolversDialog.notAllowedSolverName static private
Definition at line 41 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog().
String ManageSolversDialog.solverName static private
Definition at line 43 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog.ExportSolverAction.actionPerformed(), showDialog(), and updateAvailableSolvers().
JTextField ManageSolversDialog.solverNameTextField static private
Definition at line 45 of file ManageSolversDialog.java.
Referenced by ManageSolversDialog().
The documentation for this class was generated from the following file:
gui/ManageSolversDialog.java