SMT-RAT: smtrat::NewCAD_LOLIS Class Reference
smtrat::NewCAD_LOLIS Class Reference
Public Member Functions
bool inform (const FormulaT &_constraint)
Informs the solver about a constraint.
void deinform (const FormulaT &_constraint)
The inverse of informing about a constraint.
bool add (const FormulaT &_subformula, bool _containsUnknownConstraints=true)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Answer check (bool _full=true)
Checks the so far added formulas for satisfiability.
void push ()
Pushes a backtrack point to the stack of backtrack points.
bool pop ()
Pops a backtrack point from the stack of backtrack points.
void pop (size_t _levels)
void clear ()
void addObjective (const Poly &_objective, bool _minimize=true)
void removeObjective (const Poly &_objective)
const std::vector< std::pair
< Poly, std::pair
< carl::Variable, bool > > > & objectives () const
const Poly & firstObjective () const
void reset ()
const std::vector< FormulaSetT > & infeasibleSubsets () const
std::list< std::vector
< carl::Variable > > getModelEqualities () const
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
const Model & model () const
const std::vector< Model > allModels () const
ModelValue optimum (const Poly &_objFct) const
std::vector< FormulaT > lemmas ()
Returns the lemmas/tautologies which were made during the last solving provoked by check().
const ModuleInput & formula () const
ModuleInput::iterator formulaBegin ()
ModuleInput::iterator formulaEnd ()
void printAssignment () const
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
void printAllAssignments (std::ostream &_out=std::cout)
Prints all assignments of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
void printAssertions (std::ostream &=std::cout) const
Prints the so far added formulas.
void printInfeasibleSubset (std::ostream &=std::cout) const
Prints the first found infeasible subset of the set of received formulas.
void printBackTrackStack (std::ostream &=std::cout) const
Prints the stack of backtrack points.
void printStrategyGraph (std::ostream &_os=std::cout) const
Prints the strategy of the solver maintained by this manager.
const std::vector< Module * > & getAllGeneratedModules () const
std::ostream & rDebugOutputChannel ()
const QuantifierManager & quantifierManager () const
QuantifierManager & quantifierManager ()
const carl::QuantifiedVariables & quantifiedVariables () const
carl::QuantifiedVariables & quantifiedVariables ()
const Logic & logic () const
Logic & rLogic ()
void addInformationRelevantFormula (const FormulaT &formula)
Adds formula to InformationRelevantFormula.
void clearInformationRelevantFormula ()
Deletes all InformationRelevantFormula.
void setLemmaLevel (LemmaLevel level)
Sets the current level for lemma generation.
bool isLemmaLevel (LemmaLevel level)
Checks if current lemma level is greater or equal to given level.
std::pair< bool, FormulaT > getInputSimplified ()
ModuleInput::iterator remove (ModuleInput::iterator _subformula)
Removes the formula at the given position in the conjunction of formulas, which will be considered for the next satisfiability check.
Protected Member Functions
ModuleInput::iterator remove (const FormulaT &_subformula)
Temporarily added: (TODO: Discuss with Gereon) Removes the given formula in the conjunction of formulas, which will be considered for the next satisfiability check.
void setStrategy (const std::initializer_list< BackendLink > &backends)
void setStrategy (const BackendLink &backend)
template<typename Module >
BackendLink addBackend (const std::initializer_list< BackendLink > &backends={})
template<typename Module >
BackendLink addBackend (const BackendLink &backend)
BackendLink & addEdge (std::size_t from, std::size_t to)
std::vector< Module * > getAllBackends (Module *_module) const
Gets all backends so far instantiated according the strategy and all previous enquiries of the given module.
std::vector< Module * > getBackends (Module *, std::atomic_bool *)
Get the backends to call for the given problem instance required by the given module.
const std::set< FormulaT > & getInformationRelevantFormulas ()
Gets all InformationRelevantFormulas.
Detailed Description
Definition at line 10 of file NewCAD_LOLIS.h.
Member Function Documentation
bool smtrat::Manager::add (const FormulaT & _subformula, bool _containsUnknownConstraints = true) inherited
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The formula to add.
_containsUnknownConstraints true, if the formula to add contains constraints, about which this solver was not yet informed.
Returns
false, if it is easy to decide whether adding this formula creates a conflict; true, otherwise.
Definition at line 106 of file Manager.cpp.
Referenced by smtrat::Manager::check().
void smtrat::Manager::addInformationRelevantFormula (const FormulaT & formula) inline inherited
Adds formula to InformationRelevantFormula.
Parameters
formula Formula to add
Definition at line 411 of file Manager.h.
Referenced by smtrat::Module::addInformationRelevantFormula().
const std::vector<Model> smtrat::Manager::allModels () const inline inherited
Returns
A list of all assignments, such that they satisfy the conjunction of the so far added formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 260 of file Manager.h.
Answer smtrat::Manager::check (bool _full = true) inherited
Checks the so far added formulas for satisfiability.
Returns
True, if the conjunction of the so far added formulas is satisfiable; False, if it not satisfiable; Unknown, if this solver cannot decide whether it is satisfiable or not.
Definition at line 136 of file Manager.cpp.
void smtrat::Manager::deinform (const FormulaT & _constraint) inherited
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Definition at line 101 of file Manager.cpp.
const ModuleInput& smtrat::Manager::formula () const inline inherited
Returns
The conjunction of so far added formulas.
Definition at line 284 of file Manager.h.
std::vector<Module*> smtrat::Manager::getAllBackends (Module * _module) const inline protected inherited
Gets all backends so far instantiated according the strategy and all previous enquiries of the given module.
Parameters
_module The module to get all backends so far instantiated according the strategy and all previous enquiries of this module.
Returns
All backends so far instantiated according the strategy and all previous enquiries of the given module.
Definition at line 504 of file Manager.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula(), smtrat::Module::init(), and smtrat::Module::runBackends().
const std::vector<Module*>& smtrat::Manager::getAllGeneratedModules () const inline inherited
Returns
All instantiated modules of the solver belonging to this manager.
Definition at line 350 of file Manager.h.
vector< Module * > smtrat::Manager::getBackends (Module * , std::atomic_bool *) protected inherited
Get the backends to call for the given problem instance required by the given module.
Parameters
_formula The problem instance.
_requiredBy The module asking for a backend.
_foundAnswer A conditional
Returns
A vector of modules, which the module defined by _requiredBy calls in parallel to achieve an answer to the given instance.
Definition at line 418 of file Manager.cpp.
Referenced by smtrat::Module::init(), and smtrat::Module::runBackends().
const std::set<FormulaT>& smtrat::Manager::getInformationRelevantFormulas () inline protected inherited
Gets all InformationRelevantFormulas.
Returns
Set of all formulas
Definition at line 558 of file Manager.h.
Referenced by smtrat::Module::getInformationRelevantFormulas().
std::pair< bool, FormulaT > smtrat::Manager::getInputSimplified () inherited
Returns
A pair of a Boolean and a formula, where the Boolean is true, if the input formula could be simplified to an equisatisfiable formula. The formula is equisatisfiable to this solver's input formula, if the Boolean is true.
Definition at line 232 of file Manager.cpp.
std::list< std::vector< carl::Variable > > smtrat::Manager::getModelEqualities () const inherited
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
Returns
A list of vectors of variables, stating that the variables in one vector are assigned to equal values.
Definition at line 182 of file Manager.cpp.
const std::vector< FormulaSetT > & smtrat::Manager::infeasibleSubsets () const inherited
Returns
All infeasible subsets of the set so far added formulas.
Note, that the conjunction of the so far added formulas must be inconsistent to receive an infeasible subset.
Definition at line 177 of file Manager.cpp.
bool smtrat::Manager::inform (const FormulaT & _constraint) inherited
Informs the solver about a constraint.
Optimally, it should be informed about all constraints, which it will receive eventually, before any of them is added as part of a formula with the interface add(..).
Parameters
_constraint The constraint to inform about.
Returns
false, if it is easy to decide (for any module used of this solver), whether the constraint itself is inconsistent; true, otherwise.
Definition at line 96 of file Manager.cpp.
bool smtrat::Manager::isLemmaLevel (LemmaLevel level) inline inherited
Checks if current lemma level is greater or equal to given level.
Parameters
level Level to check.
Definition at line 437 of file Manager.h.
Referenced by smtrat::Module::isLemmaLevel().
std::vector< FormulaT > smtrat::Manager::lemmas () inherited
Returns the lemmas/tautologies which were made during the last solving provoked by check().
These lemmas can be used in the same manner as infeasible subsets are used.
Returns
The lemmas/tautologies made during solving.
Definition at line 221 of file Manager.cpp.
const Logic& smtrat::Manager::logic () const inline inherited
Returns
A constant reference to the logic this solver considers.
Definition at line 394 of file Manager.h.
Referenced by smtrat::Module::checkInfSubsetForMinimality(), and smtrat::ICPModule< Settings >::ICPModule().
const Model & smtrat::Manager::model () const inherited
Returns
An assignment of the variables, which occur in the so far added formulas, to values of their domains, such that it satisfies the conjunction of these formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 187 of file Manager.cpp.
Referenced by smtrat::Manager::check(), smtrat::Manager::optimum(), and smtrat::Manager::printAssignment().
ModelValue smtrat::Manager::optimum (const Poly & _objFct) const inherited
Parameters
_objFct The objective function to obtain the minimal assignment for.
Returns
The minimal assignment of the given objective function. Note, that a previous check call must have returned True beforehand. Note, that the objective must be added by addObjective beforehand.
Definition at line 193 of file Manager.cpp.
bool smtrat::Manager::pop (void) inherited
Pops a backtrack point from the stack of backtrack points.
This provokes, that all formulas which have been added after that backtrack point are removed.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 277 of file Manager.cpp.
Referenced by smtrat::Manager::check().
void smtrat::Manager::printAllAssignments (std::ostream & _out = std::cout) inline inherited
Prints all assignments of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
Parameters
The stream to print on.
Definition at line 313 of file Manager.h.
void smtrat::Manager::printAssertions (std::ostream & _out = std::cout) const inherited
Prints the so far added formulas.
Parameters
_out The stream to print on.
Definition at line 356 of file Manager.cpp.
void smtrat::Manager::printAssignment () const inherited
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
Parameters
The stream to print on.
Definition at line 237 of file Manager.cpp.
void smtrat::Manager::printBackTrackStack (std::ostream & _out = std::cout) const inherited
Prints the stack of backtrack points.
Parameters
_out The stream to print on.
Definition at line 394 of file Manager.cpp.
void smtrat::Manager::printInfeasibleSubset (std::ostream & _out = std::cout) const inherited
Prints the first found infeasible subset of the set of received formulas.
Parameters
_out The stream to print on.
Definition at line 373 of file Manager.cpp.
void smtrat::Manager::printStrategyGraph (std::ostream & _os = std::cout) const inline inherited
Prints the strategy of the solver maintained by this manager.
Parameters
_out The stream to print on.
Definition at line 340 of file Manager.h.
void smtrat::Manager::push (void) inline inherited
Pushes a backtrack point to the stack of backtrack points.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 151 of file Manager.h.
Referenced by smtrat::Manager::check().
const carl::QuantifiedVariables& smtrat::Manager::quantifiedVariables () const inline inherited
Returns
A constant reference to the variables, which are bound by a quantifier.
Definition at line 380 of file Manager.h.
carl::QuantifiedVariables& smtrat::Manager::quantifiedVariables () inline inherited
Returns
A reference to the variables, which are bound by a quantifier.
Definition at line 387 of file Manager.h.
const QuantifierManager& smtrat::Manager::quantifierManager () const inline inherited
Returns
A constant reference to the managing unit for the quantifiers occurring in the formulas to solve.
Definition at line 366 of file Manager.h.
QuantifierManager& smtrat::Manager::quantifierManager () inline inherited
Returns
A reference to the managing unit for the quantifiers occurring in the formulas to solve.
Definition at line 373 of file Manager.h.
std::ostream& smtrat::Manager::rDebugOutputChannel () inline inherited
Returns
The stream to print the debug information on.
Definition at line 358 of file Manager.h.
ModuleInput::iterator smtrat::Manager::remove (ModuleInput::iterator _subformula) inherited
Removes the formula at the given position in the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The position of the formula to remove.
Returns
An iterator to the formula after the position of the just removed formula. If the removed formula has been the last element, the end of the conjunction of formulas, which will be considered for the next satisfiability check is returned.
Definition at line 270 of file Manager.cpp.
ModuleInput::iterator smtrat::Manager::remove (const FormulaT & _subformula) inline protected inherited
Temporarily added: (TODO: Discuss with Gereon) Removes the given formula in the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The formula to remove.
Returns
An iterator to the formula after the position of the just removed formula. If the removed formula has been the last element, the end of the conjunction of formulas, which will be considered for the next satisfiability check is returned.
Definition at line 473 of file Manager.h.
Logic& smtrat::Manager::rLogic () inline inherited
Returns
A reference to the logic this solver considers.
Definition at line 402 of file Manager.h.
void smtrat::Manager::setLemmaLevel (LemmaLevel level) inline inherited
Sets the current level for lemma generation.
Parameters
level Level
Definition at line 428 of file Manager.h.
The documentation for this class was generated from the following file:
lib/strategies/NewCAD_LOLIS.h