SMT-RAT: vs::Substitution Class Reference
vs::Substitution Class Reference
Public Types
enum Type {
NORMAL, PLUS_EPSILON, MINUS_INFINITY, PLUS_INFINITY,
INVALID
}
The type of a substitution.
Public Member Functions
Substitution (const carl::Variable &_variable, const Type &_type, carl::PointerSet< Condition > &&_oConditions, smtrat::ConstraintsT &&_sideCondition=smtrat::ConstraintsT())
Constructs a substitution with no square root term to map to.
Substitution (const carl::Variable &, const smtrat::SqrtEx &_term, const Type &_type, carl::PointerSet< Condition > &&_oConditions, smtrat::ConstraintsT &&_sideCondition=smtrat::ConstraintsT())
Constructs a substitution with a square root term to map to.
Substitution (const Substitution &_substitution)
Copy constructor.
~Substitution ()
The destructor.
const carl::Variable & variable () const
const smtrat::SqrtEx & term () const
void setTerm (const smtrat::Rational &_value)
Sets the substitution term to the given rational.
Type & rType ()
const Type & type () const
carl::PointerSet< Condition > & rOriginalConditions ()
const carl::PointerSet< Condition > & originalConditions () const
const smtrat::ConstraintsT & sideCondition () const
const carl::Variables & termVariables () const
unsigned valuate (bool _preferMinusInf=true) const
bool operator== (const Substitution &) const
void print (bool _withOrigins=false, bool _withSideConditions=false, std::ostream &_out=std::cout, const std::string &_init="") const
Prints this substitution on the given stream, with some additional information.
Private Attributes
carl::Variable mVariable
The variable to substitute.
smtrat::SqrtEx * mpTerm
The pointer (if != NULL) to the square root term to substitute the variable for.
Type mType
The type.
carl::Variables * mpTermVariables
The variables occurring in the term to substitute for.
carl::PointerSet< Condition > mOriginalConditions
The conditions from which this substitution has been originated. (e.g. [x -> 2] could have had the origins {x-2<=0, x^2-4=0})
smtrat::ConstraintsT mSideCondition
The side conditions, which have to hold to make this substitution valid. (e.g. [x -> 1/a] has the side condition {a!=0})
Detailed Description
Definition at line 16 of file Substitution.h.
Constructor & Destructor Documentation
Substitution() [1/2]
vs::Substitution::Substitution (const carl::Variable & _variable, const Type & _type, carl::PointerSet< Condition > && _oConditions, smtrat::ConstraintsT && _sideCondition = smtrat::ConstraintsT())
Constructs a substitution with no square root term to map to.
Parameters
_variable The variable to substitute of the substitution to construct.
_type The type of the substitution of the substitution to construct.
_oConditions The original conditions of the substitution to construct.
_sideCondition The side conditions of the substitution to construct.
Definition at line 14 of file Substitution.cpp.
Substitution() [2/2]
vs::Substitution::Substitution (const carl::Variable & _variable, const smtrat::SqrtEx & _term, const Type & _type, carl::PointerSet< Condition > && _oConditions, smtrat::ConstraintsT && _sideCondition = smtrat::ConstraintsT())
Constructs a substitution with a square root term to map to.
Parameters
_variable The variable to substitute of the substitution to construct.
_term The square root term to which the variable maps to.
_type The type of the substitution of the substitution to construct.
_oConditions The original conditions of the substitution to construct.
_sideCondition The side conditions of the substitution to construct.
Definition at line 29 of file Substitution.cpp.
Member Function Documentation
operator==()
bool vs::Substitution::operator== (const Substitution & _substitution) const
Parameters
The substitution to compare with.
Returns
true, if this substitution is equal to the given substitution; false, otherwise.
Definition at line 142 of file Substitution.cpp.
originalConditions()
const carl::PointerSet<Condition>& vs::Substitution::originalConditions () const inline
Returns
A constant reference to the original conditions of this substitution.
Definition at line 123 of file Substitution.h.
Referenced by vs::State::addChild(), print(), and vs::State::updateOCondsOfSubstitutions().
print()
void vs::Substitution::print (bool _withOrigins = false, bool _withSideConditions = false, std::ostream & _out = std::cout, const std::string & _init = "") const
Prints this substitution on the given stream, with some additional information.
Parameters
The substitution to compare with.
Returns
true, if this substitution is less than the given substitution; false, otherwise.
Parameters
_withOrigins A flag indicating whether to print also the origins of this substitution.
_withSideConditions A flag indication whether to also the side conditions of this substitution.
_out The stream to print on.
_init The string to print at the beginning of every row.
Definition at line 185 of file Substitution.cpp.
Referenced by vs::State::printAlone().
rOriginalConditions()
carl::PointerSet<Condition>& vs::Substitution::rOriginalConditions () inline
Returns
A reference to the original conditions of this substitution.
Definition at line 115 of file Substitution.h.
Referenced by vs::State::deleteOrigins().
rType()
Type& vs::Substitution::rType () inline
Returns
A reference to the type of this substitution.
Definition at line 99 of file Substitution.h.
setTerm()
void vs::Substitution::setTerm (const smtrat::Rational & _value) inline
Sets the substitution term to the given rational.
Parameters
_value The value to set the substitution term to.
Definition at line 89 of file Substitution.h.
sideCondition()
const smtrat::ConstraintsT& vs::Substitution::sideCondition () const inline
Returns
A constant reference to the side condition of this substitution.
Definition at line 131 of file Substitution.h.
Referenced by vs::State::addChild(), operator==(), vs::State::passConflictToFather(), and print().
term()
const smtrat::SqrtEx& vs::Substitution::term () const inline
Returns
A constant reference to the term this substitution maps its variable to.
Definition at line 80 of file Substitution.h.
Referenced by vs::State::addChild(), vs::operator<<(), operator==(), vs::State::updateOCondsOfSubstitutions(), and valuate().
termVariables()
const carl::Variables& vs::Substitution::termVariables () const inline
Returns
A constant reference to the variables occurring in the substitution term.
Definition at line 139 of file Substitution.h.
Referenced by vs::State::solutionSpace().
type()
const Type& vs::Substitution::type () const inline
Returns
A constant reference to the type of this substitution.
Definition at line 107 of file Substitution.h.
Referenced by vs::State::addChild(), vs::State::addConflictSet(), vs::operator<<(), operator==(), vs::State::solutionSpace(), vs::substituteInfLessGreater(), smtrat::VSModule< Settings >::updateModel(), valuate(), and vs::State::~State().
valuate()
unsigned vs::Substitution::valuate (bool _preferMinusInf = true) const
Parameters
_preferMinusInf A flag indicating whether to valuate the substitution type best or otherwise worst.
Returns
The valuation of this substitution according to a heuristic.
Definition at line 60 of file Substitution.cpp.
Referenced by vs::State::updateValuation().
variable()
const carl::Variable& vs::Substitution::variable () const inline
Returns
A constant reference to the variable this substitution substitutes.
Definition at line 72 of file Substitution.h.
Referenced by vs::operator<<(), operator==(), vs::State::solutionSpace(), smtrat::VSModule< Settings >::substituteAll(), vs::substituteInfLessGreater(), vs::substituteNotTrivialCase(), and vs::substituteTrivialCase().
The documentation for this class was generated from the following files:
lib/modules/VSModule/Substitution.h
lib/modules/VSModule/Substitution.cpp