SMT-RAT: smtrat::lra::Tableau< Settings, T1, T2 > Class Template Reference
smtrat::lra::Tableau< Settings, T1, T2 > Class Template Reference
Data Structures
class Iterator
struct LearnedBound
Public Member Functions
Tableau (ModuleInput::iterator _defaultBoundPosition)
void setSize (size_t _expectedHeight, size_t _expectedWidth, size_t _expectedNumberOfBounds)
size_t size () const
void setBlandsRuleStart (size_t _start)
const std::vector< Variable< T1, T2 > * > & rows () const
const std::vector< Variable< T1, T2 > * > & columns () const
const carl::FastMap< carl::Variable, Variable< T1, T2 > * > & originalVars () const
const carl::FastPointerMap< typename Poly::PolyType, Variable< T1, T2 > * > & slackVars () const
const T1 & currentDelta () const
const carl::FastMap< FormulaT, std::vector< const Bound< T1, T2 > * > * > & constraintToBound () const
carl::FastMap< FormulaT, std::vector< const Bound< T1, T2 > * > * > & rConstraintToBound ()
size_t numberOfPivotingSteps () const
void resetNumberOfPivotingSteps ()
carl::FastPointerMap< Variable< T1, T2 >, LearnedBound > & rLearnedLowerBounds ()
carl::FastPointerMap< Variable< T1, T2 >, LearnedBound > & rLearnedUpperBounds ()
void resetTheta ()
std::vector< typename carl::FastPointerMap< Variable< T1, T2 >, LearnedBound >::iterator > & rNewLearnedBounds ()
bool entryIsPositive (const TableauEntry< T1, T2 > &_entry) const
bool entryIsNegative (const TableauEntry< T1, T2 > &_entry) const
auto defaultBoundPosition () const
bool isActive (const Variable< T1, T2 > &_var) const
EntryID newTableauEntry (const T2 &_content)
void removeEntry (EntryID _entryID)
Variable< T1, T2 > * getVariable (const Poly &_lhs, T1 &_factor, T1 &_boundValue)
Variable< T1, T2 > * getObjectiveVariable (const Poly &_lhs)
std::pair< const Bound< T1, T2 > *, bool > newBound (const FormulaT &_constraint)
void removeBound (const FormulaT &_constraint)
void activateBound (const Bound< T1, T2 > *_bound, const FormulaT &_formula)
void deleteVariable (Variable< T1, T2 > *_variable, bool _optimizationVar=false)
Variable< T1, T2 > * newNonbasicVariable (const typename Poly::PolyType *_poly, bool _isInteger)
Variable< T1, T2 > * newBasicVariable (const typename Poly::PolyType *_poly, bool _isInteger)
void activateBasicVar (Variable< T1, T2 > *_var)
g
void deactivateBasicVar (Variable< T1, T2 > *_var)
void storeAssignment ()
void resetAssignment ()
EvalRationalMap getRationalAssignment () const
void adaptDelta (const Variable< T1, T2 > &_variable, bool _upperBound, T1 &_minDelta) const
void compressRows ()
std::pair< EntryID, bool > nextPivotingElement ()
std::pair< EntryID, bool > optimizeIndependentNonbasics (const Variable< T1, T2 > &_objective)
std::pair< EntryID, bool > nextPivotingElementForOptimizing (const Variable< T1, T2 > &_objective)
std::pair< EntryID, bool > nextZeroPivotingElementForOptimizing (const Variable< T1, T2 > &_objective) const
EntryID isSuitable (const Variable< T1, T2 > &_basicVar, bool _forIncreasingAssignment) const
bool betterEntry (EntryID _isBetter, EntryID _than) const
std::vector< const Bound< T1, T2 > *> getConflict (EntryID _rowEntry) const
std::vector< std::vector< const Bound< T1, T2 > *> > getConflictsFrom (EntryID _rowEntry) const
void updateBasicAssignments (size_t _column, const Value< T1 > &_change)
Variable< T1, T2 > * pivot (EntryID _pivotingElement, bool _optimizing=false)
void update (bool _downwards, EntryID _pivotingElement, std::vector< Iterator > &_pivotingRowLeftSide, std::vector< Iterator > &_pivotingRowRightSide, bool _optimizing=false)
Updates the tableau according to the new values in the pivoting row containing the given pivoting element.
void addToEntry (const T2 &_toAdd, Iterator &_horiIter, bool _horiIterLeftFromVertIter, Iterator &_vertIter, bool _vertIterBelowHoriIter)
Adds the given value to the entry being at the position (i,j), where i is the vertical position of the given horizontal iterator and j is the horizontal position of the given vertical iterator.
void rowRefinement (Variable< T1, T2 > *_basicVar)
Tries to refine the supremum and infimum of the given basic variable.
size_t boundedVariables (const Variable< T1, T2 > &_var, size_t _stopCriterium=0) const
size_t unboundedVariables (const Variable< T1, T2 > &_var, size_t _stopCriterium=0) const
size_t checkCorrectness () const
bool rowCorrect (size_t _rowNumber) const
bool isConflicting () const
const Poly::PolyType * gomoryCut (const T2 &_ass, Variable< T1, T2 > *_rowVar)
Creates a constraint referring to Gomory Cuts, if possible.
size_t getNumberOfEntries (Variable< T1, T2 > *_rowVar)
void collect_premises (const Variable< T1, T2 > *_rowVar, FormulasT &premises) const
Collects the premises for branch and bound and stores them in premises.
void printHeap (std::ostream &_out=std::cout, int _maxEntryLength=30, const std::string _init="") const
void printEntry (EntryID _entry, std::ostream &_out=std::cout, int _maxEntryLength=20) const
void printVariables (bool _allBounds=true, std::ostream &_out=std::cout, const std::string _init="") const
void printLearnedBounds (const std::string _init="", std::ostream &_out=std::cout) const
void printLearnedBound (const Variable< T1, T2 > &_var, const LearnedBound &_learnedBound, const std::string _init="", std::ostream &_out=std::cout) const
void print (EntryID _pivotingElement=LAST_ENTRY_ID, std::ostream &_out=std::cout, const std::string _init="", bool _friendlyNames=true, bool _withZeroColumns=false) const
Private Attributes
bool mRowsCompressed
size_t mWidth
size_t mPivotingSteps
size_t mMaxPivotsWithoutBlandsRule
size_t mVarIDCounter
ModuleInput::iterator mDefaultBoundPosition
std::stack< EntryID > mUnusedIDs
carl::IDPool mVariableIdAllocator
Id allocator for the variables.
std::vector< Variable< T1, T2 > * > mRows
std::vector< Variable< T1, T2 > * > mColumns
std::list< std::list< std::pair< Variable< T1, T2 > *, T2 > > > mNonActiveBasics
std::vector< TableauEntry< T1, T2 > > * mpEntries
std::vector< Variable< T1, T2 > * > mConflictingRows
Value< T1 > * mpTheta
T1 mCurDelta
carl::FastMap< carl::Variable, Variable< T1, T2 > * > mOriginalVars
carl::FastPointerMap< typename Poly::PolyType, Variable< T1, T2 > * > mSlackVars
carl::FastMap< FormulaT, std::vector< const Bound< T1, T2 > * > * > mConstraintToBound
carl::FastPointerMap< Variable< T1, T2 >, LearnedBound > mLearnedLowerBounds
carl::FastPointerMap< Variable< T1, T2 >, LearnedBound > mLearnedUpperBounds
std::vector< typename carl::FastPointerMap< Variable< T1, T2 >, LearnedBound >::iterator > mNewLearnedBounds
Detailed Description
template<class Settings, typename T1, typename T2>
class smtrat::lra::Tableau< Settings, T1, T2 >
Definition at line 204 of file Tableau.h.
Constructor & Destructor Documentation
Tableau()
template<class Settings, typename T1, typename T2> smtrat::lra::Tableau< Settings, T1, T2 >::Tableau (ModuleInput::iterator _defaultBoundPosition)
Parameters
_defaultBoundPosition
Member Function Documentation
activateBasicVar()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::activateBasicVar (Variable< T1, T2 > * _var)
g
Parameters
_var
activateBound()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::activateBound (const Bound< T1, T2 > * _bound, const FormulaT & _formula)
Parameters
_bound
_formula
addToEntry()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::addToEntry (const T2 & _toAdd, Iterator & _horiIter, bool _horiIterLeftFromVertIter, Iterator & _vertIter, bool _vertIterBelowHoriIter)
Adds the given value to the entry being at the position (i,j), where i is the vertical position of the given horizontal iterator and j is the horizontal position of the given vertical iterator.
Note, that the entry might not exist, if its current value is 0. Then the horizontal iterator is located horizontally before or after the entry to change and the vertical iterator is located vertically before or after the entry to add.
Parameters
_toAdd The value to add to the content of the entry specified by the given iterators and their relative position to each other.
_horiIter The iterator moving horizontally and, hence, giving the vertical position of the entry to add the given value to.
_horiIterLeftFromVertIter true, if the horizontally moving iterator is left from or equal to the horizontal position of the iterator moving vertically, and, hence, left from or equal to the position of the entry to add the given value to; false, it is right or equal to this position.
_vertIter The iterator moving vertically and, hence, giving the horizontal position of the entry to add the given value to.
_vertIterBelowHoriIter true, if the vertically moving iterator is below or exactly at the vertical position of the iterator moving horizontally, and, hence, below or exactly at the position of the entry to add the given value to; false, it is above or equal to this position. If the entry existed (!=0) and is removed because of becoming 0, the iterators are set according to the given relative positioning.
betterEntry()
template<class Settings, typename T1, typename T2> bool smtrat::lra::Tableau< Settings, T1, T2 >::betterEntry (EntryID _isBetter, EntryID _than) const
Parameters
_isBetter
_than
Returns
boundedVariables()
template<class Settings, typename T1, typename T2> size_t smtrat::lra::Tableau< Settings, T1, T2 >::boundedVariables (const Variable< T1, T2 > & _var, size_t _stopCriterium = 0) const
Parameters
_var
_stopCriterium
Returns
checkCorrectness()
template<class Settings, typename T1, typename T2> size_t smtrat::lra::Tableau< Settings, T1, T2 >::checkCorrectness () const
Returns
collect_premises()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::collect_premises (const Variable< T1, T2 > * _rowVar, FormulasT & premises) const
Collects the premises for branch and bound and stores them in premises.
Parameters
_rowVar
premises
columns()
template<class Settings, typename T1, typename T2> const std::vector<Variable<T1, T2>*>& smtrat::lra::Tableau< Settings, T1, T2 >::columns () const inline
Returns
Definition at line 442 of file Tableau.h.
constraintToBound()
template<class Settings, typename T1, typename T2> const carl::FastMap<FormulaT, std::vector<const Bound<T1, T2>*>*>& smtrat::lra::Tableau< Settings, T1, T2 >::constraintToBound () const inline
Returns
Definition at line 471 of file Tableau.h.
Referenced by smtrat::LRAModule< smtrat::LRASettingsICP >::getSlackVariable().
deactivateBasicVar()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::deactivateBasicVar (Variable< T1, T2 > * _var)
Parameters
_var
defaultBoundPosition()
template<class Settings, typename T1, typename T2> auto smtrat::lra::Tableau< Settings, T1, T2 >::defaultBoundPosition () const inline
Returns
Definition at line 554 of file Tableau.h.
deleteVariable()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::deleteVariable (Variable< T1, T2 > * _variable, bool _optimizationVar = false)
Parameters
_variable
getConflict()
template<class Settings, typename T1, typename T2> std::vector< const Bound<T1, T2>* > smtrat::lra::Tableau< Settings, T1, T2 >::getConflict (EntryID _rowEntry) const
Parameters
_rowEntry
Returns
getConflictsFrom()
template<class Settings, typename T1, typename T2> std::vector< std::vector< const Bound<T1, T2>* > > smtrat::lra::Tableau< Settings, T1, T2 >::getConflictsFrom (EntryID _rowEntry) const
Parameters
_rowEntry
Returns
getNumberOfEntries()
template<class Settings, typename T1, typename T2> size_t smtrat::lra::Tableau< Settings, T1, T2 >::getNumberOfEntries (Variable< T1, T2 > * _rowVar)
Parameters
_rowVar
Returns
number of entries in the row belonging to _rowVar
getRationalAssignment()
template<class Settings, typename T1, typename T2> EvalRationalMap smtrat::lra::Tableau< Settings, T1, T2 >::getRationalAssignment () const
Returns
gomoryCut()
template<class Settings, typename T1, typename T2> const Poly::PolyType* smtrat::lra::Tableau< Settings, T1, T2 >::gomoryCut (const T2 & _ass, Variable< T1, T2 > * _rowVar)
Creates a constraint referring to Gomory Cuts, if possible.
Parameters
_ass
_rowVar
Returns
NULL, if the cut can´t be constructed; otherwise the valid constraint is returned.
isSuitable()
template<class Settings, typename T1, typename T2> EntryID smtrat::lra::Tableau< Settings, T1, T2 >::isSuitable (const Variable< T1, T2 > & _basicVar, bool _forIncreasingAssignment) const
Parameters
_basicVar
_forIncreasingAssignment
Returns
newBasicVariable()
template<class Settings, typename T1, typename T2> Variable<T1, T2>* smtrat::lra::Tableau< Settings, T1, T2 >::newBasicVariable (const typename Poly::PolyType * _poly, bool _isInteger)
Parameters
_poly
_originalVars
_isInteger
Returns
newBound()
template<class Settings, typename T1, typename T2> std::pair<const Bound<T1,T2>*, bool> smtrat::lra::Tableau< Settings, T1, T2 >::newBound (const FormulaT & _constraint)
Parameters
_constraint
Returns
newNonbasicVariable()
template<class Settings, typename T1, typename T2> Variable<T1, T2>* smtrat::lra::Tableau< Settings, T1, T2 >::newNonbasicVariable (const typename Poly::PolyType * _poly, bool _isInteger)
Parameters
_poly
_isInteger
Returns
newTableauEntry()
template<class Settings, typename T1, typename T2> EntryID smtrat::lra::Tableau< Settings, T1, T2 >::newTableauEntry (const T2 & _content)
Parameters
_content
Returns
nextPivotingElement()
template<class Settings, typename T1, typename T2> std::pair<EntryID, bool> smtrat::lra::Tableau< Settings, T1, T2 >::nextPivotingElement ()
Returns
nextPivotingElementForOptimizing()
template<class Settings, typename T1, typename T2> std::pair<EntryID,bool> smtrat::lra::Tableau< Settings, T1, T2 >::nextPivotingElementForOptimizing (const Variable< T1, T2 > & _objective)
Returns
numberOfPivotingSteps()
template<class Settings, typename T1, typename T2> size_t smtrat::lra::Tableau< Settings, T1, T2 >::numberOfPivotingSteps () const inline
Returns
Definition at line 487 of file Tableau.h.
optimizeIndependentNonbasics()
template<class Settings, typename T1, typename T2> std::pair<EntryID,bool> smtrat::lra::Tableau< Settings, T1, T2 >::optimizeIndependentNonbasics (const Variable< T1, T2 > & _objective)
Parameters
_objective
Returns
originalVars()
template<class Settings, typename T1, typename T2> const carl::FastMap< carl::Variable, Variable<T1,T2>*>& smtrat::lra::Tableau< Settings, T1, T2 >::originalVars () const inline
Returns
Definition at line 450 of file Tableau.h.
Referenced by smtrat::LRAModule< smtrat::LRASettingsICP >::originalVariables().
pivot()
template<class Settings, typename T1, typename T2> Variable<T1, T2>* smtrat::lra::Tableau< Settings, T1, T2 >::pivot (EntryID _pivotingElement, bool _optimizing = false)
Parameters
_pivotingElement
updateAssignments
Returns
print()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::print (EntryID _pivotingElement = LAST_ENTRY_ID, std::ostream & _out = std::cout, const std::string _init = "", bool _friendlyNames = true, bool _withZeroColumns = false) const
Parameters
_pivotingElement
_out
_init
_friendlyNames
_withZeroColumns
printEntry()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::printEntry (EntryID _entry, std::ostream & _out = std::cout, int _maxEntryLength = 20) const
Parameters
_entry
_out
_maxEntryLength
printHeap()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::printHeap (std::ostream & _out = std::cout, int _maxEntryLength = 30, const std::string _init = "") const
Parameters
_out
_maxEntryLength
_init
printLearnedBound()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::printLearnedBound (const Variable< T1, T2 > & _var, const LearnedBound & _learnedBound, const std::string _init = "", std::ostream & _out = std::cout) const
Parameters
_var
_learnedBound
_init
_out
printLearnedBounds()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::printLearnedBounds (const std::string _init = "", std::ostream & _out = std::cout) const
Parameters
_init
_out
printVariables()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::printVariables (bool _allBounds = true, std::ostream & _out = std::cout, const std::string _init = "") const
Parameters
_allBounds
_out
_init
rConstraintToBound()
template<class Settings, typename T1, typename T2> carl::FastMap<FormulaT, std::vector<const Bound<T1, T2>*>*>& smtrat::lra::Tableau< Settings, T1, T2 >::rConstraintToBound () inline
Returns
Definition at line 479 of file Tableau.h.
removeEntry()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::removeEntry (EntryID _entryID)
Parameters
_entryID
rLearnedLowerBounds()
template<class Settings, typename T1, typename T2> carl::FastPointerMap<Variable<T1,T2>, LearnedBound>& smtrat::lra::Tableau< Settings, T1, T2 >::rLearnedLowerBounds () inline
Returns
Definition at line 503 of file Tableau.h.
rLearnedUpperBounds()
template<class Settings, typename T1, typename T2> carl::FastPointerMap<Variable<T1,T2>, LearnedBound>& smtrat::lra::Tableau< Settings, T1, T2 >::rLearnedUpperBounds () inline
Returns
Definition at line 511 of file Tableau.h.
rNewLearnedBounds()
template<class Settings, typename T1, typename T2> std::vector<typename carl::FastPointerMap<Variable<T1,T2>, LearnedBound>::iterator>& smtrat::lra::Tableau< Settings, T1, T2 >::rNewLearnedBounds () inline
Returns
Definition at line 524 of file Tableau.h.
rowCorrect()
template<class Settings, typename T1, typename T2> bool smtrat::lra::Tableau< Settings, T1, T2 >::rowCorrect (size_t _rowNumber) const
Parameters
_rowNumber
Returns
rowRefinement()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::rowRefinement (Variable< T1, T2 > * _basicVar)
Tries to refine the supremum and infimum of the given basic variable.
Parameters
_basicVar The basic variable for which to refine the supremum and infimum.
rows()
template<class Settings, typename T1, typename T2> const std::vector<Variable<T1, T2>*>& smtrat::lra::Tableau< Settings, T1, T2 >::rows () const inline
Returns
Definition at line 434 of file Tableau.h.
setSize()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::setSize (size_t _expectedHeight, size_t _expectedWidth, size_t _expectedNumberOfBounds) inline
Parameters
_expectedHeight
_expectedWidth
_expectedNumberOfBounds
Definition at line 408 of file Tableau.h.
size()
template<class Settings, typename T1, typename T2> size_t smtrat::lra::Tableau< Settings, T1, T2 >::size () const inline
Returns
Definition at line 418 of file Tableau.h.
slackVars()
template<class Settings, typename T1, typename T2> const carl::FastPointerMap<typename Poly::PolyType, Variable<T1,T2>*>& smtrat::lra::Tableau< Settings, T1, T2 >::slackVars () const inline
Returns
Definition at line 458 of file Tableau.h.
Referenced by smtrat::LRAModule< smtrat::LRASettingsICP >::slackVariables().
unboundedVariables()
template<class Settings, typename T1, typename T2> size_t smtrat::lra::Tableau< Settings, T1, T2 >::unboundedVariables (const Variable< T1, T2 > & _var, size_t _stopCriterium = 0) const
Parameters
_var
_stopCriterium
Returns
update()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::update (bool _downwards, EntryID _pivotingElement, std::vector< Iterator > & _pivotingRowLeftSide, std::vector< Iterator > & _pivotingRowRightSide, bool _optimizing = false)
Updates the tableau according to the new values in the pivoting row containing the given pivoting element.
The updating is applied from the pivoting row downwards, if the given flag _downwards is true, and upwards, otherwise.
Parameters
_downwards The flag indicating whether to update the tableau downwards or upwards starting from the pivoting row.
_pivotingElement The id of the current pivoting element.
_pivotingRowLeftSide For every element in the pivoting row, which is positioned left of the pivoting element, this vector contains an iterator. The closer the element is to the pivoting element, the smaller is the iterator's index in the vector.
_pivotingRowRightSide For every element in the pivoting row, which is positioned right of the pivoting element, this vector contains an iterator. The closer the element is to the pivoting element, the smaller is the iterator's index in the vector.
_updateAssignments If true, the assignments of all variables will be updated after pivoting.
updateBasicAssignments()
template<class Settings, typename T1, typename T2> void smtrat::lra::Tableau< Settings, T1, T2 >::updateBasicAssignments (size_t _column, const Value< T1 > & _change)
Parameters
_column
_change
The documentation for this class was generated from the following file:
smtrat-modules/LRAModule/tableau/Tableau.h