SMT-RAT: smtrat::cad::Bitset Class Reference
smtrat::cad::Bitset Class Reference
This class is a simple wrapper around boost::dynamic_bitset.
#include <Bitset.h>
Public Types
using BaseType = boost::dynamic_bitset<>
Public Member Functions
Bitset (bool defaultValue=false)
Bitset (BaseType &&base, bool defaultValue)
Bitset (const std::initializer_list< std::size_t > &bits, bool defaultValue=false)
auto resize (std::size_t num_blocks) const -> decltype(mData.resize(num_blocks, mDefault))
Bitset & operator-= (const Bitset &rhs)
Bitset & operator|= (const Bitset &rhs)
Bitset & set (std::size_t n, bool value=true)
Bitset & reset (std::size_t n)
bool test (std::size_t n) const
bool any () const
bool none () const
auto count () const noexcept
auto size () const
auto num_blocks () const
auto find_first () const
auto find_next (std::size_t pos) const
Static Public Attributes
static auto constexpr npos
static auto constexpr bits_per_block
Private Member Functions
void ensureSize (std::size_t pos)
Private Attributes
BaseType mData
bool mDefault
Friends
void alignSize (const Bitset &lhs, const Bitset &rhs)
bool operator== (const Bitset &lhs, const Bitset &rhs)
bool operator< (const Bitset &lhs, const Bitset &rhs)
Bitset operator~ (const Bitset &lhs)
Bitset operator& (const Bitset &lhs, const Bitset &rhs)
Bitset operator| (const Bitset &lhs, const Bitset &rhs)
std::ostream & operator<< (std::ostream &os, const Bitset &b)
Detailed Description
This class is a simple wrapper around boost::dynamic_bitset.
Its purpose is to allow for on-the-fly resizing of the bitset. Formally, a Bitset object represents an infinite bitset that starts with the bits stored in mData extended by mDefault. Whenever a bit is written that is not yet stored explicitly in mData or two Bitset objects with different mData sizes are involved, the size of mData is expanded transparently.
Definition at line 16 of file Bitset.h.
Member Typedef Documentation
using smtrat::cad::Bitset::BaseType = boost::dynamic_bitset<>
Definition at line 18 of file Bitset.h.
Constructor & Destructor Documentation
smtrat::cad::Bitset::Bitset (bool defaultValue = false) inline
Definition at line 30 of file Bitset.h.
smtrat::cad::Bitset::Bitset (BaseType && base, bool defaultValue) inline
Definition at line 31 of file Bitset.h.
smtrat::cad::Bitset::Bitset (const std::initializer_list< std::size_t > & bits, bool defaultValue = false) inline
Definition at line 32 of file Bitset.h.
Member Function Documentation
bool smtrat::cad::Bitset::any () const inline
Definition at line 67 of file Bitset.h.
Referenced by smtrat::cad::CADCore< CoreHeuristic::BySample >::operator()(), and smtrat::cad::Projection< Incrementality::FULL, BT, Settings >::project().
auto smtrat::cad::Bitset::count () const inline noexcept
Definition at line 76 of file Bitset.h.
void smtrat::cad::Bitset::ensureSize (std::size_t pos) inline private
Definition at line 24 of file Bitset.h.
Referenced by reset(), and set().
auto smtrat::cad::Bitset::find_first () const inline
Definition at line 86 of file Bitset.h.
Referenced by smtrat::cad::ConflictGraph::addSample(), and smtrat::cad::IDPool::get().
auto smtrat::cad::Bitset::find_next (std::size_t pos) const inline
Definition at line 89 of file Bitset.h.
Referenced by smtrat::cad::ConflictGraph::addSample().
bool smtrat::cad::Bitset::none () const inline
Definition at line 71 of file Bitset.h.
auto smtrat::cad::Bitset::num_blocks () const inline
Definition at line 83 of file Bitset.h.
Referenced by smtrat::cad::IDPool::get(), and resize().
Bitset& smtrat::cad::Bitset::operator-= (const Bitset & rhs) inline
Definition at line 40 of file Bitset.h.
Bitset& smtrat::cad::Bitset::operator|= (const Bitset & rhs) inline
Definition at line 46 of file Bitset.h.
Bitset& smtrat::cad::Bitset::reset (std::size_t n) inline
Definition at line 58 of file Bitset.h.
Referenced by smtrat::cad::IDPool::get(), and smtrat::cad::CADConstraints< smtrat::cad::debug::DebugSettings::backtracking >::remove().
auto smtrat::cad::Bitset::resize (std::size_t num_blocks) const -> decltype(mData.resize(num_blocks, mDefault)) inline
Definition at line 36 of file Bitset.h.
Referenced by smtrat::cad::IDPool::get().
Bitset& smtrat::cad::Bitset::set (std::size_t n, bool value = true) inline
Definition at line 53 of file Bitset.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addToProjection(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection(), Bitset(), smtrat::cad::CAD< Settings >::evaluateSample(), smtrat::cad::IDPool::free(), smtrat::cad::BaseProjection< Settings >::getPolyForLifting(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::removePolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::removePolynomial(), smtrat::cad::Projection< Incrementality::FULL, BT, Settings >::removePolynomial(), and smtrat::cad::Sample::Sample().
auto smtrat::cad::Bitset::size () const inline
Definition at line 80 of file Bitset.h.
Referenced by smtrat::cad::IDPool::free(), smtrat::cad::IDPool::get(), and smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::removePolynomial().
bool smtrat::cad::Bitset::test (std::size_t n) const inline
Definition at line 63 of file Bitset.h.
Referenced by smtrat::cad::ConflictGraph::addSample(), smtrat::cad::Origin::erase(), smtrat::cad::CAD< Settings >::evaluateSample(), and smtrat::cad::BaseProjection< Settings >::getPolyForLifting().
Friends And Related Function Documentation
void alignSize (const Bitset & lhs, const Bitset & rhs) friend
Definition at line 93 of file Bitset.h.
Referenced by operator-=(), and operator|=().
Bitset operator& (const Bitset & lhs, const Bitset & rhs) friend
Definition at line 112 of file Bitset.h.
bool operator< (const Bitset & lhs, const Bitset & rhs) friend
Definition at line 103 of file Bitset.h.
std::ostream& operator<< (std::ostream & os, const Bitset & b) friend
Definition at line 123 of file Bitset.h.
bool operator== (const Bitset & lhs, const Bitset & rhs) friend
Definition at line 98 of file Bitset.h.
Bitset operator| (const Bitset & lhs, const Bitset & rhs) friend
Definition at line 117 of file Bitset.h.
Bitset operator~ (const Bitset & lhs) friend
Definition at line 109 of file Bitset.h.
Field Documentation
auto constexpr smtrat::cad::Bitset::bits_per_block static
Definition at line 20 of file Bitset.h.
Referenced by smtrat::cad::IDPool::get().
BaseType smtrat::cad::Bitset::mData mutable private
Definition at line 22 of file Bitset.h.
Referenced by any(), count(), ensureSize(), find_first(), find_next(), none(), num_blocks(), operator-=(), operator|=(), reset(), resize(), set(), size(), and test().
bool smtrat::cad::Bitset::mDefault private
Definition at line 23 of file Bitset.h.
Referenced by any(), none(), operator-=(), operator|=(), resize(), and test().
auto constexpr smtrat::cad::Bitset::npos static
Definition at line 19 of file Bitset.h.
Referenced by smtrat::cad::ConflictGraph::addSample(), and smtrat::cad::IDPool::get().
The documentation for this class was generated from the following file:
lib/datastructures/cad/utils/Bitset.h