SMT-RAT: smtrat::LRAModule< Settings > Class Template Reference
smtrat::LRAModule< Settings > Class Template Reference
A module which performs the Simplex method on the linear part of it's received formula.
#include <LRAModule.h>
Data Structures
struct Context
Stores a formula, being part of the received formula of this module, and the position of this formula in the passed formula.
Public Types
typedef Settings::BoundType LRABoundType
Number type of the underlying value of a bound of a variable within the LRAModule.
typedef Settings::EntryType LRAEntryType
Type of an entry within the tableau.
typedef lra::Bound< LRABoundType, LRAEntryType > LRABound
Type of a bound of a variable within the LRAModule.
typedef lra::Variable< LRABoundType, LRAEntryType > LRAVariable
A variable of the LRAModule, being either a original variable or a slack variable representing a linear polynomial.
typedef lra::Value< LRABoundType > LRAValue
The type of the assignment of a variable maintained by the LRAModule. It consists of a tuple of two value of the bound type.
typedef Settings SettingsType
typedef carl::FastMap< carl::Variable, LRAVariable * > VarVariableMap
Maps an original variable to it's corresponding LRAModule variable.
typedef carl::FastPointerMap< typename Poly::PolyType, LRAVariable * > ExVariableMap
Maps a linear polynomial to it's corresponding LRAModule variable.
typedef carl::FastMap< FormulaT, std::vector< const LRABound * > * > ConstraintBoundsMap
Maps constraint to the bounds it represents (e.g., equations represent two bounds)
typedef carl::FastMap< FormulaT, Context > ConstraintContextMap
Stores the position of a received formula in the passed formula.
typedef lra::Tableau< typename Settings::Tableau_settings, LRABoundType, LRAEntryType > LRATableau
The tableau which is the main data structure maintained by the LRAModule responsible for the pivoting steps.
enum LemmaType : unsigned { NORMAL = 0, PERMANENT = 1 }
Public Member Functions
std::string moduleName () const
LRAModule (const ModuleInput *_formula, Conditionals &_conditionals, Manager *_manager=NULL)
Constructs a LRAModule.
virtual ~LRAModule ()
Destructs this LRAModule.
bool informCore (const FormulaT &_constraint)
Informs this module about the existence of the given constraint, which means that it could be added in future.
void deinformCore (const FormulaT &_constraint)
The inverse of informing about a constraint.
void init ()
Initializes the tableau according to all linear constraints, of which this module has been informed.
bool addCore (ModuleInput::const_iterator _subformula)
The module has to take the given sub-formula of the received formula into account.
void removeCore (ModuleInput::const_iterator _subformula)
Removes everything related to the given sub-formula of the received formula.
Answer checkCore ()
Checks the received formula for consistency.
Answer processResult (Answer _result)
void updateModel () const
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
unsigned currentlySatisfied (const FormulaT &) const
const EvalRationalMap & getRationalModel () const
Gives a rational model if the received formula is satisfiable.
Answer optimize (Answer _result)
Answer checkNotEqualConstraints (Answer _result)
void processLearnedBounds ()
void createInfeasibleSubsets (lra::EntryID _tableauEntry)
EvalRationalIntervalMap getVariableBounds () const
Returns the bounds of the variables as intervals.
void printLinearConstraints (std::ostream &_out=std::cout, const std::string _init="") const
Prints all linear constraints.
void printNonlinearConstraints (std::ostream &_out=std::cout, const std::string _init="") const
Prints all non-linear constraints.
void printConstraintToBound (std::ostream &_out=std::cout, const std::string _init="") const
Prints the mapping of constraints to their corresponding bounds.
void printBoundCandidatesToPass (std::ostream &_out=std::cout, const std::string _init="") const
Prints the strictest bounds, which have to be passed the backend in case.
void printRationalModel (std::ostream &_out=std::cout, const std::string _init="") const
Prints the current rational assignment.
void printTableau (std::ostream &_out=std::cout, const std::string _init="") const
Prints the current tableau.
void printVariables (std::ostream &_out=std::cout, const std::string _init="") const
Prints all lra variables and their assignments.
const VarVariableMap & originalVariables () const
const ExVariableMap & slackVariables () const
const LRAVariable * getSlackVariable (const FormulaT &_constraint) const
bool inform (const FormulaT &_constraint)
Informs the module about the given constraint.
void deinform (const FormulaT &_constraint)
The inverse of informing about a constraint.
bool add (ModuleInput::const_iterator _subformula)
The module has to take the given sub-formula of the received formula into account.
virtual Answer check (bool _final=false, bool _full=true, carl::Variable _objective=carl::Variable::NO_VARIABLE)
Checks the received formula for consistency.
virtual void remove (ModuleInput::const_iterator _subformula)
Removes everything related to the given sub-formula of the received formula.
virtual void updateAllModels ()
Updates all satisfying models, if the solver has detected the consistency of the received formula, beforehand.
virtual std::list< std::vector< carl::Variable > > getModelEqualities () const
Partition the variables from the current model into equivalence classes according to their assigned value.
unsigned currentlySatisfiedByBackend (const FormulaT &_formula) const
bool receivedVariable (carl::Variable::Arg _var) const
Answer solverState () const
std::size_t id () const
void setId (std::size_t _id)
Sets this modules unique ID to identify itself.
thread_priority threadPriority () const
void setThreadPriority (thread_priority _threadPriority)
Sets the priority of this module to get a thread for running its check procedure.
const ModuleInput * pReceivedFormula () const
const ModuleInput & rReceivedFormula () const
const ModuleInput * pPassedFormula () const
const ModuleInput & rPassedFormula () const
const Model & model () const
const std::vector< Model > & allModels () const
const std::vector< FormulaSetT > & infeasibleSubsets () const
const std::vector< Module * > & usedBackends () const
const carl::FastSet< FormulaT > & constraintsToInform () const
const carl::FastSet< FormulaT > & informedConstraints () const
void addLemma (const FormulaT &_lemma, const LemmaType &_lt=LemmaType::NORMAL, const FormulaT &_preferredFormula=FormulaT(carl::FormulaType::TRUE))
Stores a lemma being a valid formula.
bool hasLemmas ()
Checks whether this module or any of its backends provides any lemmas.
void clearLemmas ()
Deletes all yet found lemmas.
const std::vector< Lemma > & lemmas () const
ModuleInput::const_iterator firstUncheckedReceivedSubformula () const
ModuleInput::const_iterator firstSubformulaToPass () const
void receivedFormulaChecked ()
Notifies that the received formulas has been checked.
const smtrat::Conditionals & answerFound () const
bool isPreprocessor () const
carl::Variable objective () const
bool is_minimizing () const
void excludeNotReceivedVariablesFromModel () const
Excludes all variables from the current model, which do not occur in the received formula.
void updateLemmas ()
Stores all lemmas of any backend of this module in its own lemma vector.
void collectTheoryPropagations ()
void collectOrigins (const FormulaT &_formula, FormulasT &_origins) const
Collects the formulas in the given formula, which are part of the received formula.
void collectOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
bool hasValidInfeasibleSubset () const
void checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string &_filename="smaller_muses", unsigned _maxSizeDifference=1) const
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
virtual std::pair< bool, FormulaT > getReceivedFormulaSimplified ()
void print (const std::string &_initiation="***") const
Prints everything relevant of the solver.
void printReceivedFormula (const std::string &_initiation="***") const
Prints the vector of the received formula.
void printPassedFormula (const std::string &_initiation="***") const
Prints the vector of passed formula.
void printInfeasibleSubsets (const std::string &_initiation="***") const
Prints the infeasible subsets.
void printModel (std::ostream &=std::cout) const
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
void printAllModels (std::ostream &=std::cout)
Prints all assignments of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Static Public Member Functions
static void freeSplittingVariable (const FormulaT &_splittingVariable)
static void addAssumptionToCheck (const FormulaT &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_subformulas, Answer _status, const std::string &_label)
static void addAssumptionToCheck (const FormulasT &_formulas, bool _consistent, const std::string &_label)
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const FormulaSetT &_formulas, bool _consistent, const std::string &_label)
static void addAssumptionToCheck (const ConstraintsT &_constraints, bool _consistent, const std::string &_label)
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
static void storeAssumptionsToCheck (const Manager &_manager)
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Static Public Attributes
static std::vector< std::string > mAssumptionToCheck
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static std::set< std::string > mVariablesInAssumptionToCheck
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static size_t mNumOfBranchVarsToStore = 5
The number of different variables to consider for a probable infinite loop of branchings.
static std::vector< Branching > mLastBranches = std::vector<Branching>(mNumOfBranchVarsToStore, Branching(typename Poly::PolyType(), 0))
Stores the last branches in a cycle buffer.
static size_t mFirstPosInLastBranches = 0
The beginning of the cyclic buffer storing the last branches.
static std::vector< FormulaT > mOldSplittingVariables
Reusable splitting variables.
Protected Member Functions
bool anAnswerFound () const
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
void clearModel () const
Clears the assignment, if any was found.
void clearModels () const
Clears all assignments, if any was found.
void cleanModel () const
Substitutes variable occurrences by its model value in the model values of other variables.
ModuleInput::iterator passedFormulaBegin ()
ModuleInput::iterator passedFormulaEnd ()
void addOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
Adds the given set of formulas in the received formula to the origins of the given passed formula.
const FormulaT & getOrigins (ModuleInput::const_iterator _formula) const
Gets the origins of the passed formula at the given position.
void getOrigins (const FormulaT &_formula, FormulasT &_origins) const
void getOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
std::pair< ModuleInput::iterator, bool > removeOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
std::pair< ModuleInput::iterator, bool > removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
void informBackends (const FormulaT &_constraint)
Informs all backends of this module about the given constraint.
virtual void addConstraintToInform (const FormulaT &_constraint)
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
std::pair< ModuleInput::iterator, bool > addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula)
Copies the given sub-formula of the received formula to the passed formula.
bool originInReceivedFormula (const FormulaT &_origin) const
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula)
Adds the given formula to the passed formula with no origin.
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
Adds the given formula to the passed formula.
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const FormulaT &_origin)
Adds the given formula to the passed formula.
void generateTrivialInfeasibleSubset ()
Stores the trivial infeasible subset being the set of received formulas.
void receivedFormulasAsInfeasibleSubset (ModuleInput::const_iterator _subformula)
Stores an infeasible subset consisting only of the given received formula.
std::vector< FormulaT >::const_iterator findBestOrigin (const std::vector< FormulaT > &_origins) const
void getInfeasibleSubsets ()
Copies the infeasible subsets of the passed formula.
std::vector< FormulaSetT > getInfeasibleSubsets (const Module &_backend) const
Get the infeasible subsets the given backend provides.
const Model & backendsModel () const
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
void getBackendsModel () const
void getBackendsAllModels () const
Stores all models of a backend in the list of all models of this module.
virtual Answer runBackends (bool _final, bool _full, carl::Variable _objective)
Runs the backend solvers on the passed formula.
virtual Answer runBackends ()
virtual ModuleInput::iterator eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins=false)
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
void clearPassedFormula ()
std::vector< FormulaT > merge (const std::vector< FormulaT > &, const std::vector< FormulaT > &) const
Merges the two vectors of sets into the first one.
size_t determine_smallest_origin (const std::vector< FormulaT > &origins) const
bool probablyLooping (const typename Poly::PolyType &_branchingPolynomial, const Rational &_branchingValue) const
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
Adds a lemmas which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
bool branchAt (carl::Variable::Arg _var, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
bool branchAt (carl::Variable::Arg _var, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
void splitUnequalConstraint (const FormulaT &)
Adds the following lemmas for the given constraint p!=0.
unsigned checkModel () const
void addInformationRelevantFormula (const FormulaT &formula)
Adds a formula to the InformationRelevantFormula.
const std::set< FormulaT > & getInformationRelevantFormulas ()
Gets all InformationRelevantFormulas.
bool isLemmaLevel (LemmaLevel level)
Checks if current lemma level is greater or equal to given level.
Static Protected Member Functions
static bool modelsDisjoint (const Model &_modelA, const Model &_modelB)
Checks whether there is no variable assigned by both models.
Protected Attributes
std::vector< FormulaSetT > mInfeasibleSubsets
Stores the infeasible subsets.
Manager *const mpManager
A reference to the manager.
Model mModel
Stores the assignment of the current satisfiable result, if existent.
std::vector< Model > mAllModels
Stores all satisfying assignments.
bool mModelComputed
True, if the model has already been computed.
bool mFinalCheck
true, if the check procedure should perform a final check which especially means not to postpone splitting decisions
bool mFullCheck
false, if this module should avoid too expensive procedures and rather return unknown instead.
carl::Variable mObjectiveVariable
Objective variable to be minimized. If set to NO_VARIABLE, a normal sat check should be performed.
std::vector< TheoryPropagation > mTheoryPropagations
std::atomic< Answer > mSolverState
States whether the received formula is known to be satisfiable or unsatisfiable otherwise it is set to unknown.
std::atomic_bool * mBackendsFoundAnswer
This flag is passed to any backend and if it determines an answer to a prior check call, this flag is fired.
Conditionals mFoundAnswer
Vector of Booleans: If any of them is true, we have to terminate a running check procedure.
std::vector< Module * > mUsedBackends
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
std::vector< Module * > mAllBackends
The backends of this module which have been used.
std::vector< Lemma > mLemmas
Stores the lemmas being valid formulas this module or its backends made.
ModuleInput::iterator mFirstSubformulaToPass
Stores the position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
carl::FastSet< FormulaT > mConstraintsToInform
Stores the constraints which the backends must be informed about.
carl::FastSet< FormulaT > mInformedConstraints
Stores the position of the first constraint of which no backend has been informed about.
ModuleInput::const_iterator mFirstUncheckedReceivedSubformula
Stores the position of the first (by this module) unchecked sub-formula of the received formula.
unsigned mSmallerMusesCheckCounter
Counter used for the generation of the smt2 files to check for smaller muses.
std::vector< std::size_t > mVariableCounters
Maps variables to the number of their occurrences.
Private Member Functions
void learnRefinements ()
Adds the refinements learned during pivoting to the deductions.
void learnRefinement (const typename LRATableau::LearnedBound &_learnedBound, bool _upperBound)
FormulasT createPremise (const std::vector< const LRABound *> &_premiseBounds, bool &_premiseOnlyEqualities) const
void adaptPassedFormula ()
Adapt the passed formula, such that it consists of the finite infimums and supremums of all variables and the non linear constraints.
bool checkAssignmentForNonlinearConstraint ()
Checks whether the current assignment of the linear constraints fulfills the non linear constraints.
void activateBound (const LRABound *_bound, const FormulaT &_formula)
Activate the given bound and update the supremum, the infimum and the assignment of variable to which the bound belongs.
void activateStrictBound (const FormulaT &_neqOrigin, const LRABound &_weakBound, const LRABound *_strictBound)
Activates a strict bound as a result of the two constraints p!=0 and p<=0 resp.
void setBound (const FormulaT &_constraint)
Creates a bound corresponding to the given constraint.
void simpleTheoryPropagation ()
Adds simple deduction being lemmas of the form (=> c_1 c_2) with, e.g.
void simpleTheoryPropagation (const LRABound *_bound)
void propagate (const LRABound *_premise, const FormulaT &_conclusion)
void propagateLowerBound (const LRABound *_bound)
void propagateUpperBound (const LRABound *_bound)
void propagateEqualBound (const LRABound *_bound)
bool gomoryCut ()
bool mostInfeasibleVar (bool _tryGomoryCut, carl::Variables &_varsToExclude)
bool branch_and_bound ()
Creates a branch and bound lemma.
bool assignmentConsistentWithTableau (const EvalRationalMap &_assignment, const LRABoundType &_delta) const
Checks whether the found assignment is consistent with the tableau, hence replacing the original variables in the expressions represented by the slack variables equals their assignment.
bool assignmentCorrect () const
Private Attributes
bool mInitialized
A flag, which is true if this module has already set all bounds corresponding to the constraint, of which this module has been informed.
bool mAssignmentFullfilsNonlinearConstraints
A flag which is true, if the non-linear constraints fulfill the current assignment.
bool mStrongestBoundsRemoved
A flag which is set, if a supremum or infimum of a LRAModule variable has been changed.
bool mOptimumComputed
bool mRationalModelComputed
bool mCheckedWithBackends
LRATableau mTableau
Contains the main data structures of this module.
carl::FastSet< FormulaT > mLinearConstraints
Stores all linear constraints of which this module has been once informed.
carl::FastSet< FormulaT > mNonlinearConstraints
Stores all non-linear constraints which are currently added (by assertSubformula) to this module.
ConstraintContextMap mActiveResolvedNEQConstraints
Those constraints p!=0, which are added to this module (part of the received formula), which are resolved by a constraints as p<0, p<=0, p>=0 or p>0.
ConstraintContextMap mActiveUnresolvedNEQConstraints
Those constraints p!=0, which are added to this module (part of the received formula), which are not yet resolved by a constraints as p<0, p<=0, p>=0 or p>0.
carl::Variable mDelta
The delta value, which influencing the assignment such that it also fulfills all strict inequalities (cf.
std::vector< const LRABound *> mBoundCandidatesToPass
Stores the bounds, which would influence a backend call because of recent changes.
EvalRationalMap mRationalAssignment
Detailed Description
template<class Settings>
class smtrat::LRAModule< Settings >
A module which performs the Simplex method on the linear part of it's received formula.
Definition at line 28 of file LRAModule.h.
Constructor & Destructor Documentation
LRAModule()
template<class Settings > smtrat::LRAModule< Settings >::LRAModule (const ModuleInput * _formula, Conditionals & _conditionals, Manager * _manager = NULL)
Constructs a LRAModule.
Parameters
_type The type of this module being LRAModule.
_formula The formula passed to this module, called received formula.
_settings [Not yet used.]
_conditionals Vector of Booleans: If any of them is true, we have to terminate a running check procedure.
_manager A reference to the manager of the solver using this module.
Definition at line 23 of file LRAModule.cpp.
Member Function Documentation
activateBound()
template<class Settings > void smtrat::LRAModule< Settings >::activateBound (const LRABound * _bound, const FormulaT & _formula) private
Activate the given bound and update the supremum, the infimum and the assignment of variable to which the bound belongs.
Parameters
_bound The bound to activate.
_formula The constraints which form this bound.
Definition at line 914 of file LRAModule.cpp.
activateStrictBound()
template<class Settings > void smtrat::LRAModule< Settings >::activateStrictBound (const FormulaT & _neqOrigin, const LRABound & _weakBound, const LRABound * _strictBound) private
Activates a strict bound as a result of the two constraints p!=0 and p<=0 resp.
p>=0.
Parameters
_neqOrigin The constraint with != as relation symbol.
_weakBound The bound corresponding to either a constraint with <= resp. >= as relation symbol.
_strictBound The bound to activate corresponding to either a constraint with < or > as relation symbol.
Definition at line 970 of file LRAModule.cpp.
add()
bool smtrat::Module::add (ModuleInput::const_iterator _subformula) inherited
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Definition at line 153 of file Module.cpp.
Referenced by smtrat::PModule::add(), smtrat::Manager::add(), smtrat::LRAModule< smtrat::LRASettingsICP >::addCore(), smtrat::Manager::getBackends(), and smtrat::EQModule< smtrat::EQSettingsForPreprocessing >::P_add_implicit_edge().
addAssumptionToCheck() [1/4]
void smtrat::Module::addAssumptionToCheck (const FormulaT & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_formula The formula which should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1019 of file Module.cpp.
Referenced by smtrat::Module::addLemma(), smtrat::Module::checkCore(), smtrat::Module::getInfeasibleSubsets(), smtrat::VSModule< Settings >::logConditions(), smtrat::vs::State::passConflictToFather(), and smtrat::VSModule< Settings >::runBackendSolvers().
addAssumptionToCheck() [2/4]
void smtrat::Module::addAssumptionToCheck (const ModuleInput & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_subformulas The sub-formulas whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1032 of file Module.cpp.
addAssumptionToCheck() [3/4]
void smtrat::Module::addAssumptionToCheck (const FormulasT & _formulas, bool _consistent, const std::string & _label) static inherited
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
Parameters
_formulas The formulas, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1058 of file Module.cpp.
addAssumptionToCheck() [4/4]
void smtrat::Module::addAssumptionToCheck (const ConstraintsT & _constraints, bool _consistent, const std::string & _label) static inherited
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
Parameters
_constraints The constraints, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1079 of file Module.cpp.
addConstraintToInform()
void smtrat::Module::addConstraintToInform (const FormulaT & _constraint) protected virtual inherited
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
Parameters
_constraint The constraint to add.
Reimplemented in smtrat::SATModule< Settings >.
Definition at line 900 of file Module.cpp.
addCore()
template<class Settings > bool smtrat::LRAModule< Settings >::addCore (ModuleInput::const_iterator _subformula) virtual
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Reimplemented from smtrat::Module.
Definition at line 77 of file LRAModule.cpp.
addInformationRelevantFormula()
void smtrat::Module::addInformationRelevantFormula (const FormulaT & formula) protected inherited
Adds a formula to the InformationRelevantFormula.
Parameters
formula Formula to add
Definition at line 1197 of file Module.cpp.
addLemma()
void smtrat::Module::addLemma (const FormulaT & _lemma, const LemmaType & _lt = LemmaType::NORMAL, const FormulaT & _preferredFormula = FormulaT(carl::FormulaType::TRUE)) inline inherited
Stores a lemma being a valid formula.
Parameters
_lemma The eduction/lemma to store.
_lt The type of the lemma.
Definition at line 535 of file Module.h.
addOrigin()
void smtrat::Module::addOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Adds the given set of formulas in the received formula to the origins of the given passed formula.
Parameters
_formula The passed formula to set the origins for.
_origins A set of formulas in the received formula of this module.
Definition at line 867 of file Module.h.
addReceivedSubformulaToPassedFormula()
std::pair<ModuleInput::iterator,bool> smtrat::Module::addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula) inline protected inherited
Copies the given sub-formula of the received formula to the passed formula.
Note, that there is always a link between sub-formulas of the passed formulas to sub-formulas of the received formulas, which are responsible for its occurrence.
Parameters
_subformula The sub-formula of the received formula to copy.
Definition at line 926 of file Module.h.
Referenced by smtrat::Module::checkCore().
addSubformulaToPassedFormula() [1/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula) inline protected inherited
Adds the given formula to the passed formula with no origin.
Note that in the next call of this module's removeSubformula, all formulas in the passed formula without origins will be removed.
Parameters
_formula The formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 942 of file Module.h.
Referenced by smtrat::Module::addReceivedSubformulaToPassedFormula(), smtrat::Module::addSubformulaToPassedFormula(), and smtrat::CNFerModule::checkCore().
addSubformulaToPassedFormula() [2/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origins The link of the formula to add to the passed formula to sub-formulas of the received formulas, which are responsible for its occurrence
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 956 of file Module.h.
addSubformulaToPassedFormula() [3/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const FormulaT & _origin) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origin The sub-formula of the received formula being responsible for the occurrence of the formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 970 of file Module.h.
allModels()
const std::vector<Model>& smtrat::Module::allModels () const inline inherited
Returns
All satisfying assignments, if existent.
Definition at line 486 of file Module.h.
Referenced by smtrat::Manager::allModels().
anAnswerFound()
bool smtrat::Module::anAnswerFound () const inline protected inherited
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
Returns
True, if one of them has determined a result.
Definition at line 806 of file Module.h.
Referenced by smtrat::Module::foundAnswer(), and smtrat::Module::runBackends().
answerFound()
const smtrat::Conditionals& smtrat::Module::answerFound () const inline inherited
Returns
A vector of Booleans: If any of them is true, we have to terminate a running check procedure.
Definition at line 613 of file Module.h.
Referenced by smtrat::Manager::getBackends().
assignmentConsistentWithTableau()
template<class Settings > bool smtrat::LRAModule< Settings >::assignmentConsistentWithTableau (const EvalRationalMap & _assignment, const LRABoundType & _delta) const private
Checks whether the found assignment is consistent with the tableau, hence replacing the original variables in the expressions represented by the slack variables equals their assignment.
Parameters
_assignment The assignment of the original variables.
_delta The calculated delta for the given assignment.
Returns
true, if the found assignment is consistent with the tableau; false, otherwise.
Definition at line 1374 of file LRAModule.cpp.
assignmentCorrect()
template<class Settings > bool smtrat::LRAModule< Settings >::assignmentCorrect () const private
Returns
true, if the encountered satisfying assignment for the received formula indeed satisfies it; false, otherwise.
Definition at line 1390 of file LRAModule.cpp.
branch_and_bound()
template<class Settings > bool smtrat::LRAModule< Settings >::branch_and_bound () private
Creates a branch and bound lemma.
Returns
true, if the solution is not in the domain, false, otherwise.
Definition at line 1309 of file LRAModule.cpp.
branchAt()
bool smtrat::Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true, bool _useReceivedFormulaAsPremise = false) protected inherited
Adds a lemmas which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
Note that the given value is rounded down and up, if the given variable is integer-valued.
Parameters
_polynomial The variable to branch for. _integral A flag being true, if all variables in the polynomial to branch for are integral.
_value The value to branch at.
_premise The sub-formulas of the received formula from which the branch is followed. Note, that a premise is not necessary, as every branch is a valid formula. But a premise can prevent from branching unnecessarily.
_leftCaseWeak true, if a branching in the form of (or (<= p b) (> p b)) is desired. false, if a branching in the form of (or (< p b) (>= p b)) is desired.
_preferLeftCase true, if the left case (polynomial less(or equal) 0 shall be chosen first. false, otherwise.
_useReceivedFormulaAsPremise true, if the whole received formula should be used as premise
Definition at line 498 of file Module.cpp.
check()
Answer smtrat::Module::check (bool _final = false, bool _full = true, carl::Variable _objective = carl::Variable::NO_VARIABLE) virtual inherited
Checks the received formula for consistency.
Note, that this is an implementation of the satisfiability check of the conjunction of the so far received formulas, which does actually nothing but passing the problem to its backends. This implementation is only used internally and must be overwritten by any derived module.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
True, if the received formula is satisfiable; False, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented in smtrat::PModule.
Definition at line 92 of file Module.cpp.
Referenced by smtrat::PModule::check(), and smtrat::Manager::check().
checkAssignmentForNonlinearConstraint()
template<class Settings > bool smtrat::LRAModule< Settings >::checkAssignmentForNonlinearConstraint () private
Checks whether the current assignment of the linear constraints fulfills the non linear constraints.
Returns
true, if the current assignment of the linear constraints fulfills the non linear constraints; false, otherwise.
Definition at line 890 of file LRAModule.cpp.
checkCore()
template<class Settings > Answer smtrat::LRAModule< Settings >::checkCore () virtual
Checks the received formula for consistency.
Returns
SAT, if the received formula is satisfiable; UNSAT, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented from smtrat::Module.
Definition at line 326 of file LRAModule.cpp.
checkInfSubsetForMinimality()
void smtrat::Module::checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string & _filename = "smaller_muses", unsigned _maxSizeDifference = 1) const inherited
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
Parameters
_infsubset The infeasible subset to check for minimality.
_filename The name of the file to store the infeasible subsets in order to be able to check their infeasibility.
_maxSizeDifference The maximal difference between the sizes of the subsets compared to the size of the infeasible subset.
Definition at line 1147 of file Module.cpp.
Referenced by smtrat::GBModule< Settings >::checkCore().
checkModel()
unsigned smtrat::Module::checkModel () const protected inherited
Returns
false, if the current model of this module does not satisfy the current given formula; true, if it cannot be said whether the model satisfies the given formula.
Definition at line 611 of file Module.cpp.
collectOrigins()
void smtrat::Module::collectOrigins (const FormulaT & _formula, FormulasT & _origins) const inherited
Collects the formulas in the given formula, which are part of the received formula.
If the given formula directly occurs in the received formula, it is inserted into the given set. Otherwise, the given formula must be of type AND and all its sub-formulas part of the received formula. Hence, they will be added to the given set.
Parameters
_formula The formula from which to collect the formulas being sub-formulas of the received formula (origins).
_origins The set in which to store the origins.
Definition at line 985 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
constraintsToInform()
const carl::FastSet<FormulaT>& smtrat::Module::constraintsToInform () const inline inherited
Returns
The constraints which the backends must be informed about.
Definition at line 511 of file Module.h.
currentlySatisfied()
template<class Settings > unsigned smtrat::LRAModule< Settings >::currentlySatisfied (const FormulaT & _formula) const virtual
Returns
0, if the given formula is conflicted by the current model; 1, if the given formula is satisfied by the current model; 2, otherwise
Reimplemented from smtrat::Module.
Definition at line 483 of file LRAModule.cpp.
currentlySatisfiedByBackend()
unsigned smtrat::Module::currentlySatisfiedByBackend (const FormulaT & _formula) const inherited
Returns
0, if the given formula is conflicted by the current model; 1, if the given formula is satisfied by the current model; 2, otherwise 3, if we do not know anything (default)
Definition at line 316 of file Module.cpp.
deinform()
void smtrat::Module::deinform (const FormulaT & _constraint) inherited
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Definition at line 139 of file Module.cpp.
Referenced by smtrat::Manager::deinform().
deinformCore()
template<class Settings > void smtrat::LRAModule< Settings >::deinformCore (const FormulaT & _constraint) virtual
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Reimplemented from smtrat::Module.
Definition at line 64 of file LRAModule.cpp.
determine_smallest_origin()
size_t smtrat::Module::determine_smallest_origin (const std::vector< FormulaT > & origins) const protected inherited
Parameters
origins A vector of sets of origins.
Returns
The index of the smallest (regarding the size of the sets) element of origins
Definition at line 423 of file Module.cpp.
eraseSubformulaFromPassedFormula()
ModuleInput::iterator smtrat::Module::eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins = false) protected virtual inherited
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
Afterwards the sub-formula is removed from the passed formula.
Parameters
_subformula The sub-formula to remove from the passed formula.
_ignoreOrigins True, if the sub-formula shall be removed regardless of its origins (should only be applied with expertise).
Returns
Reimplemented in smtrat::ICPModule< Settings >, smtrat::ICPModule< smtrat::ICPSettings1 >, and smtrat::ICPModule< smtrat::ICPSettings4 >.
Definition at line 832 of file Module.cpp.
findBestOrigin()
std::vector< FormulaT >::const_iterator smtrat::Module::findBestOrigin (const std::vector< FormulaT > & _origins) const protected inherited
Parameters
_origins
Returns
Definition at line 714 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
firstSubformulaToPass()
ModuleInput::const_iterator smtrat::Module::firstSubformulaToPass () const inline inherited
Returns
The position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
Definition at line 597 of file Module.h.
Referenced by smtrat::Manager::getBackends().
firstUncheckedReceivedSubformula()
ModuleInput::const_iterator smtrat::Module::firstUncheckedReceivedSubformula () const inline inherited
Returns
The position of the first (by this module) unchecked sub-formula of the received formula.
Definition at line 589 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore().
getInfeasibleSubsets()
std::vector< FormulaSetT > smtrat::Module::getInfeasibleSubsets (const Module & _backend) const protected inherited
Get the infeasible subsets the given backend provides.
Note, that an infeasible subset in a backend contains sub formulas of the passed formula and an infeasible subset of this module contains sub formulas of the received formula. In this method the LATTER is returned.
Parameters
_backend The backend from which to obtain the infeasible subsets.
Returns
The infeasible subsets the given backend provides.
Definition at line 732 of file Module.cpp.
getInformationRelevantFormulas()
const std::set< FormulaT > & smtrat::Module::getInformationRelevantFormulas () protected inherited
Gets all InformationRelevantFormulas.
Returns
Set of all formulas
Definition at line 1203 of file Module.cpp.
getModelEqualities()
std::list< std::vector< carl::Variable > > smtrat::Module::getModelEqualities () const virtual inherited
Partition the variables from the current model into equivalence classes according to their assigned value.
The result is a set of equivalence classes of variables where all variables within one class are assigned the same value. Note that the number of classes may not be minimal, i.e. two classes may actually be equivalent.
Returns
Equivalence classes.
Definition at line 328 of file Module.cpp.
Referenced by smtrat::Manager::getModelEqualities().
getOrigins() [1/3]
const FormulaT& smtrat::Module::getOrigins (ModuleInput::const_iterator _formula) const inline protected inherited
Gets the origins of the passed formula at the given position.
Parameters
_formula The position of a formula in the passed formulas.
Returns
The origins of the passed formula at the given position.
Definition at line 877 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets().
getOrigins() [2/3]
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulasT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 1024 of file Module.h.
getOrigins() [3/3]
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulaSetT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 1037 of file Module.h.
getRationalModel()
template<class Settings > const EvalRationalMap & smtrat::LRAModule< Settings >::getRationalModel () const
Gives a rational model if the received formula is satisfiable.
Note, that it is calculated from scratch every time you call this method.
Returns
The rational model.
Definition at line 472 of file LRAModule.cpp.
getReceivedFormulaSimplified()
std::pair< bool, FormulaT > smtrat::Module::getReceivedFormulaSimplified () virtual inherited
Returns
A pair of a Boolean and a formula, where the Boolean is true, if the received formula could be simplified to an equisatisfiable formula. The formula is equisatisfiable to this module's reveived formula, if the Boolean is true.
Reimplemented in smtrat::PModule.
Definition at line 970 of file Module.cpp.
Referenced by smtrat::Manager::getInputSimplified().
getSlackVariable()
template<class Settings> const LRAVariable* smtrat::LRAModule< Settings >::getSlackVariable (const FormulaT & _constraint) const inline
Parameters
_constraint The constraint to get the slack variable for.
Returns
The slack variable constructed for the linear polynomial without the constant part in the given constraint.
Definition at line 293 of file LRAModule.h.
getVariableBounds()
template<class Settings > EvalRationalIntervalMap smtrat::LRAModule< Settings >::getVariableBounds () const
Returns the bounds of the variables as intervals.
Returns
The bounds of the variables as intervals.
Definition at line 725 of file LRAModule.cpp.
gomoryCut()
template<class Settings > bool smtrat::LRAModule< Settings >::gomoryCut () private
Returns
true, if a branching occurred. false, otherwise.
Definition at line 1267 of file LRAModule.cpp.
hasValidInfeasibleSubset()
bool smtrat::Module::hasValidInfeasibleSubset () const inherited
Returns
true, if the module has at least one valid infeasible subset, that is all its elements are sub-formulas of the received formula (pointer must be equal).
Definition at line 1129 of file Module.cpp.
id()
std::size_t smtrat::Module::id () const inline inherited
Returns
A unique ID to identify this module instance.
Definition at line 411 of file Module.h.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::addCandidateToRelevant(), smtrat::ICPModule< smtrat::ICPSettings4 >::removeCandidateFromRelevant(), and smtrat::ICPModule< smtrat::ICPSettings4 >::updateRelevantCandidates().
infeasibleSubsets()
const std::vector<FormulaSetT>& smtrat::Module::infeasibleSubsets () const inline inherited
Returns
The infeasible subsets of the set of received formulas (empty, if this module has not detected unsatisfiability of the conjunction of received formulas.
Definition at line 495 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets(), smtrat::Manager::infeasibleSubsets(), smtrat::Manager::printInfeasibleSubset(), and smtrat::ICPModule< smtrat::ICPSettings4 >::remapAndSetLraInfeasibleSubsets().
inform()
bool smtrat::Module::inform (const FormulaT & _constraint) inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Definition at line 132 of file Module.cpp.
Referenced by smtrat::Manager::add(), smtrat::Manager::getBackends(), smtrat::Manager::inform(), and smtrat::Manager::Manager().
informBackends()
void smtrat::Module::informBackends (const FormulaT & _constraint) inline protected inherited
Informs all backends of this module about the given constraint.
Parameters
_constraint The constraint to inform about.
Definition at line 905 of file Module.h.
informCore()
template<class Settings > bool smtrat::LRAModule< Settings >::informCore (const FormulaT & _constraint) virtual
Informs this module about the existence of the given constraint, which means that it could be added in future.
Parameters
_constraint The constraint to inform about.
Returns
false, if the it can be determined that the constraint itself is conflicting; true, otherwise.
Reimplemented from smtrat::Module.
Definition at line 45 of file LRAModule.cpp.
informedConstraints()
const carl::FastSet<FormulaT>& smtrat::Module::informedConstraints () const inline inherited
Returns
The position of the first constraint of which no backend has been informed about.
Definition at line 519 of file Module.h.
Referenced by smtrat::Manager::getBackends().
isLemmaLevel()
bool smtrat::Module::isLemmaLevel (LemmaLevel level) protected inherited
Checks if current lemma level is greater or equal to given level.
Parameters
level Level to check.
Definition at line 1208 of file Module.cpp.
isPreprocessor()
bool smtrat::Module::isPreprocessor () const inline inherited
Returns
true, if this module is a preprocessor that is a module, which simplifies its received formula to an equisatisfiable formula being passed to its backends. The simplified formula can be obtained with getReceivedFormulaSimplified().
Definition at line 623 of file Module.h.
lemmas()
const std::vector<Lemma>& smtrat::Module::lemmas () const inline inherited
Returns
A constant reference to the lemmas being valid formulas this module or its backends made.
Definition at line 581 of file Module.h.
Referenced by smtrat::Manager::lemmas().
merge()
std::vector< FormulaT > smtrat::Module::merge (const std::vector< FormulaT > & _vecSetA, const std::vector< FormulaT > & _vecSetB) const protected inherited
Merges the two vectors of sets into the first one.
({a,b},{a,c}) and ({b,d},{b}) -> ({a,b,d},{a,b},{a,b,c,d},{a,b,c})
Parameters
_vecSetA A vector of sets of constraints.
_vecSetB A vector of sets of constraints.
Returns
The vector being the two given vectors merged.
Definition at line 397 of file Module.cpp.
model()
const Model& smtrat::Module::model () const inline inherited
Returns
The assignment of the current satisfiable result, if existent.
Definition at line 478 of file Module.h.
Referenced by smtrat::Module::backendsModel(), smtrat::Module::clearModels(), smtrat::Module::getBackendsAllModels(), and smtrat::Manager::model().
modelsDisjoint()
bool smtrat::Module::modelsDisjoint (const Model & _modelA, const Model & _modelB) static protected inherited
Checks whether there is no variable assigned by both models.
Parameters
_modelA The first model to check for.
_modelB The second model to check for.
Returns
true, if there is no variable assigned by both models; false, otherwise.
Definition at line 634 of file Module.cpp.
moduleName()
template<class Settings> std::string smtrat::LRAModule< Settings >::moduleName () const inline virtual
Returns
The name of the given module type as name.
Reimplemented from smtrat::Module.
Definition at line 43 of file LRAModule.h.
mostInfeasibleVar()
template<class Settings > bool smtrat::LRAModule< Settings >::mostInfeasibleVar (bool _tryGomoryCut, carl::Variables & _varsToExclude) private
Parameters
_varsToExclude The variable on which we do not want to branch.
Returns
true, if the solution is not in the domain, false, otherwise.
Definition at line 1316 of file LRAModule.cpp.
originalVariables()
template<class Settings> const VarVariableMap& smtrat::LRAModule< Settings >::originalVariables () const inline
Returns
A constant reference to the original variables.
Definition at line 276 of file LRAModule.h.
passedFormulaBegin()
ModuleInput::iterator smtrat::Module::passedFormulaBegin () inline protected inherited
Returns
An iterator to the end of the passed formula. TODO: disable this method
Definition at line 849 of file Module.h.
passedFormulaEnd()
ModuleInput::iterator smtrat::Module::passedFormulaEnd () inline protected inherited
Returns
An iterator to the end of the passed formula.
Definition at line 857 of file Module.h.
pPassedFormula()
const ModuleInput* smtrat::Module::pPassedFormula () const inline inherited
Returns
A pointer to the formula passed to the backends of this module.
Definition at line 462 of file Module.h.
Referenced by smtrat::Manager::getBackends().
pReceivedFormula()
const ModuleInput* smtrat::Module::pReceivedFormula () const inline inherited
Returns
A pointer to the formula passed to this module.
Definition at line 446 of file Module.h.
print()
void smtrat::Module::print (const std::string & _initiation = "***") const inherited
Prints everything relevant of the solver.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1214 of file Module.cpp.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::activateNonlinearConstraint().
printAllModels()
void smtrat::Module::printAllModels (std::ostream & _out = std::cout) inherited
Prints all assignments of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1290 of file Module.cpp.
Referenced by smtrat::Manager::printAllAssignments().
printBoundCandidatesToPass()
template<class Settings> void smtrat::LRAModule< Settings >::printBoundCandidatesToPass (std::ostream & _out = std::cout, const std::string _init = "") const
Prints the strictest bounds, which have to be passed the backend in case.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
printConstraintToBound()
template<class Settings> void smtrat::LRAModule< Settings >::printConstraintToBound (std::ostream & _out = std::cout, const std::string _init = "") const
Prints the mapping of constraints to their corresponding bounds.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
printInfeasibleSubsets()
void smtrat::Module::printInfeasibleSubsets (const std::string & _initiation = "***") const inherited
Prints the infeasible subsets.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1265 of file Module.cpp.
printLinearConstraints()
template<class Settings> void smtrat::LRAModule< Settings >::printLinearConstraints (std::ostream & _out = std::cout, const std::string _init = "") const
Prints all linear constraints.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
printModel()
void smtrat::Module::printModel (std::ostream & _out = std::cout) const inherited
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1280 of file Module.cpp.
Referenced by smtrat::Manager::printAssignment().
printNonlinearConstraints()
template<class Settings> void smtrat::LRAModule< Settings >::printNonlinearConstraints (std::ostream & _out = std::cout, const std::string _init = "") const
Prints all non-linear constraints.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
printPassedFormula()
void smtrat::Module::printPassedFormula (const std::string & _initiation = "***") const inherited
Prints the vector of passed formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1247 of file Module.cpp.
printRationalModel()
template<class Settings> void smtrat::LRAModule< Settings >::printRationalModel (std::ostream & _out = std::cout, const std::string _init = "") const
Prints the current rational assignment.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
printReceivedFormula()
void smtrat::Module::printReceivedFormula (const std::string & _initiation = "***") const inherited
Prints the vector of the received formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1234 of file Module.cpp.
printTableau()
template<class Settings> void smtrat::LRAModule< Settings >::printTableau (std::ostream & _out = std::cout, const std::string _init = "") const
Prints the current tableau.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
printVariables()
template<class Settings> void smtrat::LRAModule< Settings >::printVariables (std::ostream & _out = std::cout, const std::string _init = "") const
Prints all lra variables and their assignments.
Parameters
_out The output stream to print on.
_init The beginning of each line to print.
probablyLooping()
bool smtrat::Module::probablyLooping (const typename Poly::PolyType & _branchingPolynomial, const Rational & _branchingValue) const protected inherited
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
Parameters
_branchingPolynomial The polynomial to branch at (in most branching strategies this is just a variable).
_branchingValue The value to branch at.
Returns
true, if this branching is probably part of an infinite loop of branchings; false, otherwise.
Definition at line 446 of file Module.cpp.
remove()
void smtrat::Module::remove (ModuleInput::const_iterator _subformula) virtual inherited
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
_subformula The sub formula of the received formula to remove.
Reimplemented in smtrat::PModule.
Definition at line 174 of file Module.cpp.
Referenced by smtrat::PModule::remove(), smtrat::Manager::remove(), and smtrat::LRAModule< smtrat::LRASettingsICP >::removeCore().
removeCore()
template<class Settings > void smtrat::LRAModule< Settings >::removeCore (ModuleInput::const_iterator _subformula) virtual
Removes everything related to the given sub-formula of the received formula.
Parameters
_subformula The sub formula of the received formula to remove.
Reimplemented from smtrat::Module.
Definition at line 187 of file LRAModule.cpp.
rPassedFormula()
const ModuleInput& smtrat::Module::rPassedFormula () const inline inherited
Returns
A reference to the formula passed to the backends of this module.
Definition at line 470 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Manager::getBackends().
rReceivedFormula()
const ModuleInput& smtrat::Module::rReceivedFormula () const inline inherited
Returns
A reference to the formula passed to this module.
Definition at line 454 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Module::generateTrivialInfeasibleSubset().
runBackends()
Answer smtrat::Module::runBackends (bool _final, bool _full, carl::Variable _objective) protected virtual inherited
Runs the backend solvers on the passed formula.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
True, if the passed formula is consistent; False, if the passed formula is inconsistent; Unknown, otherwise.
Reimplemented in smtrat::PModule.
Definition at line 752 of file Module.cpp.
Referenced by smtrat::Module::checkCore().
setBound()
template<class Settings > void smtrat::LRAModule< Settings >::setBound (const FormulaT & _constraint) private
Creates a bound corresponding to the given constraint.
Parameters
_constraint The constraint corresponding to the bound to create.
Definition at line 1020 of file LRAModule.cpp.
setId()
void smtrat::Module::setId (std::size_t _id) inline inherited
Sets this modules unique ID to identify itself.
Parameters
_id The id to set this module's id to.
Definition at line 420 of file Module.h.
Referenced by smtrat::Manager::getBackends().
setThreadPriority()
void smtrat::Module::setThreadPriority (thread_priority _threadPriority) inline inherited
Sets the priority of this module to get a thread for running its check procedure.
Parameters
_threadPriority The priority to set this module's thread priority to.
Definition at line 438 of file Module.h.
Referenced by smtrat::Manager::getBackends().
simpleTheoryPropagation()
template<class Settings > void smtrat::LRAModule< Settings >::simpleTheoryPropagation () private
Adds simple deduction being lemmas of the form (=> c_1 c_2) with, e.g.
c_1 being p>=1 and c_2 being p>0.
Definition at line 1026 of file LRAModule.cpp.
slackVariables()
template<class Settings> const ExVariableMap& smtrat::LRAModule< Settings >::slackVariables () const inline
Returns
A reference to the original variables.
Definition at line 284 of file LRAModule.h.
solverState()
Answer smtrat::Module::solverState () const inline inherited
Returns
True, if this module is in a state, such that it has found a solution for its received formula; False, if this module is in a state, such that it has determined that there is no solution for its received formula; Unknown, otherwise.
Definition at line 403 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), smtrat::Module::getReceivedFormulaSimplified(), and smtrat::Module::updateAllModels().
splitUnequalConstraint()
void smtrat::Module::splitUnequalConstraint (const FormulaT & _unequalConstraint) protected inherited
Adds the following lemmas for the given constraint p!=0.
(p!=0 <-> (p<0 or p>0)) and not(p<0 and p>0)
Parameters
_unequalConstraint A constraint having the relation symbol !=.
Definition at line 588 of file Module.cpp.
storeAssumptionsToCheck()
void smtrat::Module::storeAssumptionsToCheck (const Manager & _manager) static inherited
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Parameters
_manager The manager object of this solver to store the assumptions for.
Definition at line 1099 of file Module.cpp.
Referenced by smtrat::Manager::~Manager().
threadPriority()
thread_priority smtrat::Module::threadPriority () const inline inherited
Returns
The priority of this module to get a thread for running its check procedure.
Definition at line 429 of file Module.h.
Referenced by smtrat::Manager::getBackends().
usedBackends()
const std::vector<Module*>& smtrat::Module::usedBackends () const inline inherited
Returns
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
Definition at line 503 of file Module.h.
Referenced by smtrat::Module::getReceivedFormulaSimplified().
Field Documentation
mDelta
template<class Settings> carl::Variable smtrat::LRAModule< Settings >::mDelta private
The delta value, which influencing the assignment such that it also fulfills all strict inequalities (cf.
Integrating Simplex with DPLL(T) by B. Dutertre and L. de Moura).
Definition at line 115 of file LRAModule.h.
mTableau
template<class Settings> LRATableau smtrat::LRAModule< Settings >::mTableau private
Contains the main data structures of this module.
It maintains for each LRAModule variable a row or a column. On this tableau pivoting can be performed as the well known Simplex method performs.
Definition at line 96 of file LRAModule.h.
Referenced by smtrat::LRAModule< smtrat::LRASettingsICP >::getSlackVariable(), smtrat::LRAModule< smtrat::LRASettingsICP >::originalVariables(), and smtrat::LRAModule< smtrat::LRASettingsICP >::slackVariables().
The documentation for this class was generated from the following files:
smtrat-modules/LRAModule/LRAModule.h
smtrat-modules/LRAModule/LRAModule.cpp