SMT-RAT: smtrat::ModelSubstitution Class Reference
smtrat::ModelSubstitution Class Reference abstract
#include <ModelSubstitution.h>
Public Member Functions
ModelSubstitution ()
virtual ~ModelSubstitution ()
virtual ModelValue evaluate (Model &model)=0
Evaluates this substitution with respect to the given model.
virtual bool dependsOn (const ModelVariable &) const
Checks whether this substitution needs the given model variable.
virtual void print (std::ostream &os) const
Prints this substitution to the given output stream.
virtual void multiplyBy (const Rational &_number)=0
Multiplies this model substitution by a rational.
virtual void add (const Rational &_number)=0
Adds a rational to this model substitution.
template<typename Iterator >
const ModelValue & getModelValue (Iterator _mvit, Model &_model)
Static Public Member Functions
template<typename Substitution , typename... Args>
static ModelValue create (Args &&...args)
Detailed Description
Definition at line 14 of file ModelSubstitution.h.
Constructor & Destructor Documentation
smtrat::ModelSubstitution::ModelSubstitution () inline
Definition at line 17 of file ModelSubstitution.h.
virtual smtrat::ModelSubstitution::~ModelSubstitution () inline virtual
Definition at line 18 of file ModelSubstitution.h.
Member Function Documentation
virtual void smtrat::ModelSubstitution::add (const Rational & _number) pure virtual
Adds a rational to this model substitution.
Implemented in smtrat::ModelPolynomialSubstitution, and smtrat::MCBModelSubstitution.
template<typename Substitution , typename... Args> static ModelValue smtrat::ModelSubstitution::create (Args &&... args) inline static
Definition at line 48 of file ModelSubstitution.h.
virtual bool smtrat::ModelSubstitution::dependsOn (const ModelVariable &) const inline virtual
Checks whether this substitution needs the given model variable.
Reimplemented in smtrat::ModelPolynomialSubstitution, and smtrat::MCBModelSubstitution.
Definition at line 24 of file ModelSubstitution.h.
virtual ModelValue smtrat::ModelSubstitution::evaluate (Model & model) pure virtual
Evaluates this substitution with respect to the given model.
Implemented in smtrat::ModelPolynomialSubstitution, and smtrat::MCBModelSubstitution.
template<typename Iterator > const ModelValue& smtrat::ModelSubstitution::getModelValue (Iterator _mvit, Model & _model) inline
Definition at line 37 of file ModelSubstitution.h.
Referenced by smtrat::MCBModelSubstitution::evaluate(), and smtrat::ModelPolynomialSubstitution::evaluate().
virtual void smtrat::ModelSubstitution::multiplyBy (const Rational & _number) pure virtual
Multiplies this model substitution by a rational.
Implemented in smtrat::ModelPolynomialSubstitution, and smtrat::MCBModelSubstitution.
virtual void smtrat::ModelSubstitution::print (std::ostream & os) const inline virtual
Prints this substitution to the given output stream.
Reimplemented in smtrat::ModelPolynomialSubstitution, and smtrat::MCBModelSubstitution.
Definition at line 28 of file ModelSubstitution.h.
Referenced by smtrat::operator<<().
The documentation for this class was generated from the following file:
lib/datastructures/model/ModelSubstitution.h