SMT-RAT: smtrat::SATModule< Settings > Class Template Reference
smtrat::SATModule< Settings > Class Template Reference
Implements a module performing DPLL style SAT checking.
#include <SATModule.h>
Data Structures
struct Abstraction
Stores all information regarding a Boolean abstraction of a constraint.
struct ClauseInformation
struct CNFInfos
struct lemma_lt
struct LiteralClauses
struct UnorderedClauseLookup
struct VarData
Stores information about a Minisat variable.
struct VarOrderLt
struct WatcherDeleted
[Minisat related code]
Public Types
typedef Settings SettingsType
enum LemmaType : unsigned { NORMAL = 0, PERMANENT = 1 }
Public Member Functions
SATModule (const ModuleInput *_formula, Conditionals &_foundAnswer, Manager *const _manager=nullptr)
Constructs a SATModule.
~SATModule ()
Destructs this SATModule.
bool addCore (ModuleInput::const_iterator)
The module has to take the given sub-formula of the received formula into account.
Answer checkCore ()
Checks the received formula for consistency.
void removeCore (ModuleInput::const_iterator)
Removes everything related to the given sub-formula of the received formula.
void updateModel () const
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
void updateAllModels ()
Updates all satisfying models, if the solver has detected the consistency of the received formula, beforehand.
void updateInfeasibleSubset ()
Updates the infeasible subset found by the SATModule, if the received formula is unsatisfiable.
void cleanUpAfterOptimizing (const std::vector< Minisat::CRef > &_excludedAssignments)
void removeUpperBoundOnMinimal ()
void addConstraintToInform (const FormulaT &)
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
void addConstraintToInform_ (const FormulaT &_formula)
void addBooleanAssignments (EvalRationalMap &_rationalAssignment) const
Adds the Boolean assignments to the given assignments, which were determined by the Minisat procedure.
void print (std::ostream &_out=std::cout, const std::string &_init="") const
Prints everything.
void printCurrentAssignment (std::ostream &=std::cout, const std::string &="") const
Prints the current assignment of the SAT solver.
void printConstraintLiteralMap (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the constraints to literal map.
void printFormulaCNFInfosMap (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the formulas to clauses map.
void printClauseInformation (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the clause information.
void printBooleanVarMap (std::ostream &_out=std::cout, const std::string &_init="") const
Prints map of the Boolean within the SAT solver to the given Booleans.
void printBooleanConstraintMap (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the literal to constraint map.
void printClause (Minisat::CRef _clause, bool _withAssignment=false, std::ostream &_out=std::cout, const std::string &_init="") const
Prints the clause at the given reference.
void printClause (const Minisat::vec< Minisat::Lit > &, bool _withAssignment=false, std::ostream &_out=std::cout, const std::string &_init="") const
Prints the clause resulting from the given vector of literals.
void printClauses (const Minisat::vec< Minisat::CRef > &_clauses, const std::string _name, std::ostream &_out=std::cout, const std::string &_init="", int=0, bool _withAssignment=false, bool _onlyNotSatisfied=false) const
Prints all given clauses.
void printDecisions (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the decisions the SAT solver has made.
void printPropagatedLemmas (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the propagated lemmas for each variables which influence its value.
void printLiteralsActiveOccurrences (std::ostream &_out=std::cout, const std::string &_init="") const
Prints the literals' active occurrences in all clauses.
void collectStats ()
Collects the taken statistics.
bool inform (const FormulaT &_constraint)
Informs the module about the given constraint.
void deinform (const FormulaT &_constraint)
The inverse of informing about a constraint.
virtual void init ()
Informs all backends about the so far encountered constraints, which have not yet been communicated.
bool add (ModuleInput::const_iterator _subformula)
The module has to take the given sub-formula of the received formula into account.
virtual Answer check (bool _final=false, bool _full=true, carl::Variable _objective=carl::Variable::NO_VARIABLE)
Checks the received formula for consistency.
virtual void remove (ModuleInput::const_iterator _subformula)
Removes everything related to the given sub-formula of the received formula.
virtual std::list< std::vector< carl::Variable > > getModelEqualities () const
Partition the variables from the current model into equivalence classes according to their assigned value.
unsigned currentlySatisfiedByBackend (const FormulaT &_formula) const
virtual unsigned currentlySatisfied (const FormulaT &) const
bool receivedVariable (carl::Variable::Arg _var) const
Answer solverState () const
std::size_t id () const
void setId (std::size_t _id)
Sets this modules unique ID to identify itself.
thread_priority threadPriority () const
void setThreadPriority (thread_priority _threadPriority)
Sets the priority of this module to get a thread for running its check procedure.
const ModuleInput * pReceivedFormula () const
const ModuleInput & rReceivedFormula () const
const ModuleInput * pPassedFormula () const
const ModuleInput & rPassedFormula () const
const Model & model () const
const std::vector< Model > & allModels () const
const std::vector< FormulaSetT > & infeasibleSubsets () const
const std::vector< Module * > & usedBackends () const
const carl::FastSet< FormulaT > & constraintsToInform () const
const carl::FastSet< FormulaT > & informedConstraints () const
void addLemma (const FormulaT &_lemma, const LemmaType &_lt=LemmaType::NORMAL, const FormulaT &_preferredFormula=FormulaT(carl::FormulaType::TRUE))
Stores a lemma being a valid formula.
bool hasLemmas ()
Checks whether this module or any of its backends provides any lemmas.
void clearLemmas ()
Deletes all yet found lemmas.
const std::vector< Lemma > & lemmas () const
ModuleInput::const_iterator firstUncheckedReceivedSubformula () const
ModuleInput::const_iterator firstSubformulaToPass () const
void receivedFormulaChecked ()
Notifies that the received formulas has been checked.
const smtrat::Conditionals & answerFound () const
bool isPreprocessor () const
virtual std::string moduleName () const
carl::Variable objective () const
bool is_minimizing () const
void excludeNotReceivedVariablesFromModel () const
Excludes all variables from the current model, which do not occur in the received formula.
void updateLemmas ()
Stores all lemmas of any backend of this module in its own lemma vector.
void collectTheoryPropagations ()
void collectOrigins (const FormulaT &_formula, FormulasT &_origins) const
Collects the formulas in the given formula, which are part of the received formula.
void collectOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
bool hasValidInfeasibleSubset () const
void checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string &_filename="smaller_muses", unsigned _maxSizeDifference=1) const
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
virtual std::pair< bool, FormulaT > getReceivedFormulaSimplified ()
void print (const std::string &_initiation="***") const
Prints everything relevant of the solver.
void printReceivedFormula (const std::string &_initiation="***") const
Prints the vector of the received formula.
void printPassedFormula (const std::string &_initiation="***") const
Prints the vector of passed formula.
void printInfeasibleSubsets (const std::string &_initiation="***") const
Prints the infeasible subsets.
void printModel (std::ostream &=std::cout) const
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
void printAllModels (std::ostream &=std::cout)
Prints all assignments of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Static Public Member Functions
static void freeSplittingVariable (const FormulaT &_splittingVariable)
static void addAssumptionToCheck (const FormulaT &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_subformulas, Answer _status, const std::string &_label)
static void addAssumptionToCheck (const FormulasT &_formulas, bool _consistent, const std::string &_label)
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const FormulaSetT &_formulas, bool _consistent, const std::string &_label)
static void addAssumptionToCheck (const ConstraintsT &_constraints, bool _consistent, const std::string &_label)
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
static void storeAssumptionsToCheck (const Manager &_manager)
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Static Public Attributes
static std::vector< std::string > mAssumptionToCheck
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static std::set< std::string > mVariablesInAssumptionToCheck
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static size_t mNumOfBranchVarsToStore = 5
The number of different variables to consider for a probable infinite loop of branchings.
static std::vector< Branching > mLastBranches = std::vector<Branching>(mNumOfBranchVarsToStore, Branching(typename Poly::PolyType(), 0))
Stores the last branches in a cycle buffer.
static size_t mFirstPosInLastBranches = 0
The beginning of the cyclic buffer storing the last branches.
static std::vector< FormulaT > mOldSplittingVariables
Reusable splitting variables.
Protected Member Functions
virtual bool informCore (const FormulaT &)
Informs the module about the given constraint.
virtual void deinformCore (const FormulaT &)
The inverse of informing about a constraint.
bool anAnswerFound () const
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
void clearModel () const
Clears the assignment, if any was found.
void clearModels () const
Clears all assignments, if any was found.
void cleanModel () const
Substitutes variable occurrences by its model value in the model values of other variables.
ModuleInput::iterator passedFormulaBegin ()
ModuleInput::iterator passedFormulaEnd ()
void addOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
Adds the given set of formulas in the received formula to the origins of the given passed formula.
const FormulaT & getOrigins (ModuleInput::const_iterator _formula) const
Gets the origins of the passed formula at the given position.
void getOrigins (const FormulaT &_formula, FormulasT &_origins) const
void getOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
std::pair< ModuleInput::iterator, bool > removeOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
std::pair< ModuleInput::iterator, bool > removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
void informBackends (const FormulaT &_constraint)
Informs all backends of this module about the given constraint.
std::pair< ModuleInput::iterator, bool > addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula)
Copies the given sub-formula of the received formula to the passed formula.
bool originInReceivedFormula (const FormulaT &_origin) const
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula)
Adds the given formula to the passed formula with no origin.
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
Adds the given formula to the passed formula.
std::pair< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const FormulaT &_origin)
Adds the given formula to the passed formula.
void generateTrivialInfeasibleSubset ()
Stores the trivial infeasible subset being the set of received formulas.
void receivedFormulasAsInfeasibleSubset (ModuleInput::const_iterator _subformula)
Stores an infeasible subset consisting only of the given received formula.
std::vector< FormulaT >::const_iterator findBestOrigin (const std::vector< FormulaT > &_origins) const
void getInfeasibleSubsets ()
Copies the infeasible subsets of the passed formula.
std::vector< FormulaSetT > getInfeasibleSubsets (const Module &_backend) const
Get the infeasible subsets the given backend provides.
const Model & backendsModel () const
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
void getBackendsModel () const
void getBackendsAllModels () const
Stores all models of a backend in the list of all models of this module.
virtual Answer runBackends (bool _final, bool _full, carl::Variable _objective)
Runs the backend solvers on the passed formula.
virtual Answer runBackends ()
virtual ModuleInput::iterator eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins=false)
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
void clearPassedFormula ()
std::vector< FormulaT > merge (const std::vector< FormulaT > &, const std::vector< FormulaT > &) const
Merges the two vectors of sets into the first one.
size_t determine_smallest_origin (const std::vector< FormulaT > &origins) const
bool probablyLooping (const typename Poly::PolyType &_branchingPolynomial, const Rational &_branchingValue) const
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
Adds a lemmas which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
bool branchAt (carl::Variable::Arg _var, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
bool branchAt (carl::Variable::Arg _var, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false)
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, bool _useReceivedFormulaAsPremise=false, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
void splitUnequalConstraint (const FormulaT &)
Adds the following lemmas for the given constraint p!=0.
unsigned checkModel () const
void addInformationRelevantFormula (const FormulaT &formula)
Adds a formula to the InformationRelevantFormula.
const std::set< FormulaT > & getInformationRelevantFormulas ()
Gets all InformationRelevantFormulas.
bool isLemmaLevel (LemmaLevel level)
Checks if current lemma level is greater or equal to given level.
Static Protected Member Functions
static bool modelsDisjoint (const Model &_modelA, const Model &_modelB)
Checks whether there is no variable assigned by both models.
Protected Attributes
std::vector< FormulaSetT > mInfeasibleSubsets
Stores the infeasible subsets.
Manager *const mpManager
A reference to the manager.
Model mModel
Stores the assignment of the current satisfiable result, if existent.
std::vector< Model > mAllModels
Stores all satisfying assignments.
bool mModelComputed
True, if the model has already been computed.
bool mFinalCheck
true, if the check procedure should perform a final check which especially means not to postpone splitting decisions
bool mFullCheck
false, if this module should avoid too expensive procedures and rather return unknown instead.
carl::Variable mObjectiveVariable
Objective variable to be minimized. If set to NO_VARIABLE, a normal sat check should be performed.
std::vector< TheoryPropagation > mTheoryPropagations
std::atomic< Answer > mSolverState
States whether the received formula is known to be satisfiable or unsatisfiable otherwise it is set to unknown.
std::atomic_bool * mBackendsFoundAnswer
This flag is passed to any backend and if it determines an answer to a prior check call, this flag is fired.
Conditionals mFoundAnswer
Vector of Booleans: If any of them is true, we have to terminate a running check procedure.
std::vector< Module * > mUsedBackends
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
std::vector< Module * > mAllBackends
The backends of this module which have been used.
ModuleInput::iterator mFirstSubformulaToPass
Stores the position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
carl::FastSet< FormulaT > mConstraintsToInform
Stores the constraints which the backends must be informed about.
carl::FastSet< FormulaT > mInformedConstraints
Stores the position of the first constraint of which no backend has been informed about.
ModuleInput::const_iterator mFirstUncheckedReceivedSubformula
Stores the position of the first (by this module) unchecked sub-formula of the received formula.
unsigned mSmallerMusesCheckCounter
Counter used for the generation of the smt2 files to check for smaller muses.
std::vector< std::size_t > mVariableCounters
Maps variables to the number of their occurrences.
Private Types
using VarScheduler = typename Settings::VarScheduler
typedef carl::FastMap< FormulaT, std::vector< Minisat::Lit > > ConstraintLiteralsMap
Maps the constraints occurring in the SAT module to their abstractions.
typedef carl::FastMap< carl::Variable, Minisat::Var > BooleanVarMap
Maps the Boolean variables to their corresponding Minisat variable.
typedef std::unordered_map< int, FormulaT > MinisatVarMap
Maps the Minisat variables to their corresponding boolean variable.
typedef Minisat::vec< std::pair< Abstraction *, Abstraction * > > BooleanConstraintMap
Maps each Minisat variable to a pair of Abstractions, one contains the abstraction information of the literal being the variable and one contains the abstraction information of the literal being the variables negation.
typedef carl::FastMap< FormulaT, CNFInfos > FormulaCNFInfosMap
Maps the clauses in the received formula to the corresponding Minisat clause.
typedef std::map< Minisat::Var, FormulasT > VarLemmaMap
Maps the minisat variable to the formulas which influence its value.
typedef std::vector< std::vector< Minisat::Lit > > ClauseVector
A vector of vectors of literals representing a vector of clauses.
typedef std::set< std::vector< int > > ClauseSet
A set of vectors of integer representing a set of clauses.
typedef carl::FastMap< signed, std::vector< signed > > TseitinVarShadows
Private Member Functions
Minisat::Var newVar (bool polarity=true, bool dvar=true, double _activity=0, bool insertIntoHeap=true)
Creates a new SAT variable in the solver.
void simplify ()
Removes already satisfied clauses and performs simplifications on all clauses.
bool addClause (const Minisat::vec< Minisat::Lit > &_clause, unsigned _type=0)
Adds the clause of the given type with the given literals to the clauses managed by Minisat.
void removeLiteralOrigin (Minisat::Lit _litToRemove, const FormulaT &_origin)
bool okay () const
void setPolarity (Minisat::Var v, bool b)
Declare which polarity the decision heuristic should use for a variable.
void setDecisionVar (Minisat::Var v, bool b, bool insertIntoHeap=true)
Declare if a variable should be eligible for selection in the decision heuristic.
Minisat::lbool bool_value (Minisat::Var x) const
Minisat::lbool value (Minisat::Var x) const
Minisat::lbool theoryValue (Minisat::Var x) const
bool addClauseIfNew (const FormulasT &clause)
void handleTheoryConflict (const mcsat::Explanation &explanation)
Minisat::lbool bool_value (Minisat::Lit p) const
Minisat::lbool value (Minisat::Lit p) const
Minisat::lbool theoryValue (Minisat::Lit p) const
int nAssigns () const
int nClauses () const
int nLearnts () const
int nVars () const
int nFreeVars () const
void setConfBudget (int64_t x)
[Minisat related code]
void setPropBudget (int64_t x)
[Minisat related code]
void budgetOff ()
[Minisat related code]
void interrupt ()
Trigger a (potentially asynchronous) interruption of the solver.
void clearInterrupt ()
Clear interrupt indicator flag.
void garbageCollect ()
[Minisat related code]
void checkGarbage (double gf)
[Minisat related code]
void checkGarbage (void)
[Minisat related code]
void printSatState (std::ostream &=std::cout, const std::string="")
[Minisat related code]
void insertVarOrder (Minisat::Var x)
Insert a variable in the decision order priority queue.
void decrementLearntSizeAdjustCnt ()
[Minisat related code]
bool fullAssignment ()
Minisat::Lit pickBranchLit ()
void checkAbstractionsConsistency ()
Minisat::Lit bestBranchLit ()
void newDecisionLevel ()
Begins a new decision level.
void decrementTseitinShadowOccurrences (signed _var)
void incrementTseitinShadowOccurrences (signed _var)
void uncheckedEnqueue (Minisat::Lit p, Minisat::CRef from=Minisat::CRef_Undef)
Enqueue a literal.
bool enqueue (Minisat::Lit p, Minisat::CRef from=Minisat::CRef_Undef)
Test if fact 'p' contradicts current state, enqueue otherwise.
Minisat::CRef propagate ()
propagate : [void] -> [Clause*]
void cancelUntil (int level, bool force=false)
Revert to the state at given level (keeping all assignments at 'level' but not beyond).
void cancelIncludingLiteral (Minisat::Lit lit)
void cancelAssignmentUntil (int level)
Revert the variables assignment until a given level (keeping all assignments at 'level')
void resetVariableAssignment (Minisat::Var _var)
bool analyze (Minisat::CRef confl, Minisat::vec< Minisat::Lit > &out_learnt, int &out_btlevel)
analyze : (confl : Clause*) (out_learnt : vec<Lit>&) (out_btlevel : int&) -> [void]
bool litRedundant (Minisat::Lit p, uint32_t abstract_levels)
Check if 'p' can be removed.
bool processLemmas ()
Adds clauses representing the lemmas which should be added to this SATModule.
void learnTheoryConflicts ()
Adds the clauses representing all conflicts generated by all backends.
void adaptConflictEvaluation (size_t &_clauseEvaluation, Minisat::Lit _lit, bool _firstLiteral)
Minisat::CRef propagateConsistently (bool _checkWithTheory=true)
Propagate and check the consistency of the constraints, whose abstraction literals have been assigned to true.
void propagateTheory ()
void theoryCall ()
void constructLemmas ()
bool expPositionsCorrect () const
Minisat::lbool checkFormula ()
Checks the received formula for consistency.
void computeAdvancedLemmas ()
Minisat::lbool search (int nof_conflicts=100)
search : (nof_conflicts : int) (params : const SearchParams&) -> [lbool]
void handleConflict (Minisat::CRef _confl)
Handles conflict.
void reduceDB ()
reduceDB : () -> [void]
void clearLearnts (int n)
void removeSatisfied (Minisat::vec< Minisat::CRef > &cs)
Removes all satisfied clauses from the given vector of clauses, which should only be performed in decision level 0.
void rebuildOrderHeap ()
[Minisat related code]
double maxActivity () const
void varDecayActivity ()
Decay all variables with the specified factor.
void varBumpActivity (Minisat::Var v, double inc)
Increase a variable with the current 'bump' value.
void varBumpActivity (Minisat::Var v)
Increase a variable with the current 'bump' value.
void claDecayActivity ()
Decay all clauses with the specified factor.
void claBumpActivity (Minisat::Clause &c)
Increase a clause with the current 'bump' value.
void attachClause (Minisat::CRef cr)
Attach a clause to watcher lists.
void detachClause (Minisat::CRef cr, bool strict=false)
Detach a clause to watcher lists.
void removeClause (Minisat::CRef cr)
Detach and free a clause.
Minisat::Clause & getClause (Minisat::CRef cr)
bool locked (const Minisat::Clause &c)
bool satisfied (const Minisat::Clause &c) const
bool bool_satisfied (const Minisat::Clause &c) const
void relocAll (Minisat::ClauseAllocator &to)
[Minisat related code]
int decisionLevel () const
uint32_t abstractLevel (Minisat::Var x) const
Used to represent an abstraction of sets of decision levels.
Minisat::CRef reason (Minisat::Var x)
void removeTheoryPropagation (int _position)
int level (Minisat::Var x) const
int theory_level (Minisat::Var x) const
int min_theory_level (Minisat::Var x) const
int trailIndex (Minisat::Var _var) const
int level (const Minisat::vec< Minisat::Lit > &) const
Minisat::CRef storeLemmas ()
double progressEstimate () const
bool withinBudget () const
void updateCNFInfoCounter (typename FormulaCNFInfosMap::iterator _iter, const FormulaT &_origin, bool _increment)
void addClause_ (const Minisat::vec< Minisat::Lit > &_clause, unsigned _type, const FormulaT &_original, typename FormulaCNFInfosMap::iterator _formulaCNFInfoIter)
Minisat::Lit addClauses (const FormulaT &_formula, unsigned _type, unsigned _depth=0, const FormulaT &_original=FormulaT(carl::FormulaType::TRUE))
void addXorClauses (const Minisat::vec< Minisat::Lit > &_literals, const Minisat::vec< Minisat::Lit > &_negLiterals, int _from, bool _numOfNegatedLitsEven, unsigned _type, Minisat::vec< Minisat::Lit > &_clause, const FormulaT &_original, typename FormulaCNFInfosMap::iterator _formulaCNFInfoIter)
bool supportedConstraintType (const FormulaT &_formula) const
Minisat::Lit createLiteral (const FormulaT &_formula, const FormulaT &_origin=FormulaT(carl::FormulaType::TRUE), bool _decisionRelevant=true)
Creates or simply returns the literal belonging to the formula being the first argument.
Minisat::Lit getLiteral (const FormulaT &_formula) const
void adaptPassedFormula ()
Adapts the passed formula according to the current assignment within the SAT solver.
void adaptPassedFormula (Abstraction &_abstr)
Adapts the passed formula according to the given abstraction information.
bool passedFormulaCorrect () const
void updateModel (Model &model, bool only_relevant_variables=false) const
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
Static Private Member Functions
static Minisat::Var mapVar (Minisat::Var x, Minisat::vec< Minisat::Var > &map, Minisat::Var &max)
[Minisat related code]
static double luby (double y, int x)
Finite subsequences of the Luby-sequence:
static double drand (double &seed)
static int irand (double &seed, int size)
Private Attributes
int verbosity
[Minisat related code]
double var_decay
[Minisat related code]
double clause_decay
[Minisat related code]
double random_var_freq
[Minisat related code]
double random_seed
[Minisat related code]
bool luby_restart
[Minisat related code]
int ccmin_mode
Controls conflict clause minimization (0=none, 1=basic, 2=deep).
int phase_saving
Controls the level of phase saving (0=none, 1=limited, 2=full).
bool rnd_pol
Use random polarities for branching heuristics.
bool rnd_init_act
Initialize variable activities with a small random value.
double garbage_frac
The fraction of wasted memory allowed before a garbage collection is triggered.
int restart_first
The initial restart limit. (default 100)
double restart_inc
The factor with which the restart limit is multiplied in each restart. (default 1.5)
double learntsize_factor
The initial limit for learned clauses is a factor of the original clauses.(default 1 / 3)
double learntsize_inc
The limit for learned clauses is multiplied with this factor each restart.(default 1.1)
int learntsize_adjust_start_confl
[Minisat related code]
double learntsize_adjust_inc
[Minisat related code]
uint64_t solves
[Minisat related code]
uint64_t starts
uint64_t decisions
uint64_t rnd_decisions
uint64_t propagations
uint64_t conflicts
uint64_t dec_vars
[Minisat related code]
uint64_t clauses_literals
uint64_t learnts_literals
uint64_t max_literals
uint64_t tot_literals
bool ok
If FALSE, the constraints are already unsatisfiable. No part of the solver state may be used!
Minisat::vec< Minisat::CRef > clauses
List of problem clauses.
Minisat::vec< Minisat::CRef > satisfiedClauses
List of problem clauses.
Minisat::vec< Minisat::CRef > learnts
List of learned clauses.
Minisat::vec< Minisat::CRef > unknown_excludes
List of clauses which exclude a call resulted in unknown.
double cla_inc
Amount to bump next clause with.
Minisat::vec< double > activity
A heuristic measurement of the activity of a variable.
double var_inc
Amount to bump next variable with.
Minisat::OccLists< Minisat::Lit, Minisat::vec< Minisat::Watcher >, WatcherDeleted > watches
'watches[lit]' is a list of constraints watching 'lit' (will go there if literal becomes true).
Minisat::vec< Minisat::lbool > assigns
The current assignments.
Minisat::vec< char > polarity
The preferred polarity of each variable.
Minisat::vec< char > decision
Declares if a variable is eligible for selection in the decision heuristic.
Minisat::vec< Minisat::Lit > trail
Assignment stack; stores all assignments made in the order they were made.
Minisat::vec< int > trail_lim
Separator indices for different decision levels in 'trail'.
Minisat::vec< VarData > vardata
Stores reason and level for each variable.
int qhead
Head of queue (as index into the trail – no more explicit propagation queue in MiniSat).
int simpDB_assigns
Number of top-level assignments since last execution of 'simplify()'.
int64_t simpDB_props
Remaining number of propagations that must be made before next execution of 'simplify()'.
Minisat::vec< Minisat::Lit > assumptions
Current set of assumptions provided to solve by the user.
Minisat::Heap< VarOrderLt > order_heap
A priority queue of variables ordered with respect to the variable activity.
VarScheduler var_scheduler
Alternative approach to order_heap.
double progress_estimate
Set by 'search()'.
bool remove_satisfied
Indicates whether possibly inefficient linear scan for satisfied clauses should be performed in 'simplify'.
Minisat::ClauseAllocator ca
[Minisat related code]
Minisat::vec< char > seen
Each variable is prefixed by the method in which it is used, except 'seen' which is used in several places.
Minisat::vec< Minisat::Lit > analyze_stack
[Minisat related code]
Minisat::vec< Minisat::Lit > analyze_toclear
[Minisat related code]
Minisat::vec< Minisat::Lit > add_tmp
[Minisat related code]
double max_learnts
[Minisat related code]
double learntsize_adjust_confl
[Minisat related code]
int learntsize_adjust_cnt
[Minisat related code]
int64_t conflict_budget
-1 means no budget.
int64_t propagation_budget
-1 means no budget.
bool asynch_interrupt
[Minisat related code]
Minisat::vec< Minisat::Lit > learnt_clause
For temporary usage.
Minisat::Var mTrueVar
Variable representing true.
bool mChangedPassedFormula
A flag, which is set to true, if anything has been changed in the passed formula between now and the last consistency check.
bool mComputeAllSAT
A flag, which is set to true, if all satisfying assignments should be computed.
bool mFullAssignmentCheckedForConsistency
bool mOptimumComputed
bool mBusy
bool mExcludedAssignments
Answer mCurrentAssignmentConsistent
Stores gained information about the current assignment's consistency.
size_t mNumberOfFullLazyCalls
The number of full laze calls made.
int mCurr_Restarts
The number of restarts made.
unsigned mNumberOfTheoryCalls
The number of theory calls made.
bool mReceivedFormulaPurelyPropositional
BooleanConstraintMap mBooleanConstraintMap
Maps each Minisat variable to a pair of Abstractions, one contains the abstraction information of the literal being the variable and one contains the abstraction information of the literal being the variables negation.
ConstraintLiteralsMap mConstraintLiteralMap
Maps the constraints occurring in the SAT module to their abstractions.
BooleanVarMap mBooleanVarMap
Maps the Boolean variables to their corresponding Minisat variable.
MinisatVarMap mMinisatVarMap
Maps the Minisat variables to their corresponding boolean variable.
carl::FastMap< FormulaT, Minisat::Lit > mFormulaAssumptionMap
FormulaCNFInfosMap mFormulaCNFInfosMap
Maps the clauses in the received formula to the corresponding Minisat clause and Minisat literal.
ClauseSet mLearntDeductions
If problem is unsatisfiable (possibly under assumptions), this vector represent the final conflict clause expressed in the assumptions.
carl::FastMap< Minisat::CRef, ClauseInformation > mClauseInformation
std::unordered_map< int, std::unordered_set< Minisat::CRef > > mLiteralClausesMap
size_t mNumberOfSatisfiedClauses
std::vector< signed > mChangedBooleans
Stores all Literals for which the abstraction information might be changed.
bool mAllActivitiesChanged
Is true, if we have to communicate all activities to the backends. (This might be the case after rescaling the activities.)
std::vector< signed > mChangedActivities
Stores all clauses in which the activities have been changed.
VarLemmaMap mPropagatedLemmas
Stores for each variable the corresponding formulas which control its value.
std::vector< int > mRelevantVariables
Stores Minisat indexes of all relevant variables.
Minisat::vec< unsigned > mNonTseitinShadowedOccurrences
TseitinVarShadows mTseitinVarShadows
carl::FastMap< int, FormulaT > mTseitinVarFormulaMap
carl::Bitset mTseitinVariable
Stores whether a given variable is a tseitin variable.
carl::Bitset mAssumedTseitinVariable
Stores whether a given tseitin variable was already added to the assumptions.
carl::Bitset mNonassumedTseitinVariable
Stores whether a given tseitin variable was not yet added to the assumptions, but represents a top-level clause.
std::vector< Minisat::vec< Minisat::Lit > > mCurrentTheoryConflicts
std::vector< unsigned > mCurrentTheoryConflictTypes
std::map< std::pair< size_t, size_t >, size_t > mCurrentTheoryConflictEvaluations
std::unordered_set< int > mLevelCounter
size_t mTheoryConflictIdCounter
ModuleInput::iterator mUpperBoundOnMinimal
std::vector< LiteralClauses > mLiteralsClausesMap
std::vector< std::pair< size_t, size_t > > mLiteralsActivOccurrences
std::vector< Minisat::Lit > mPropagationFreeDecisions
Minisat::vec< Minisat::vec< Minisat::Lit > > mLemmas
literals propagated by lemmas
Minisat::vec< bool > mLemmasRemovable
is the lemma removable
mcsat::MCSATMixin< typename Settings::MCSATSettings > mMCSAT
std::map< carl::Variable, std::vector< signed > > mFutureChangedBooleans
UnorderedClauseLookup mUnorderedClauseLookup
Friends
class VarSchedulerBase
class VarSchedulerMcsatBase
Detailed Description
template<class Settings>
class smtrat::SATModule< Settings >
Implements a module performing DPLL style SAT checking.
It is mainly based on Minisat 2.0 and extends it by enabling the SMT-RAT module interfaces and some optimizations.
Definition at line 60 of file SATModule.h.
Member Typedef Documentation
ConstraintLiteralsMap
template<class Settings > typedef carl::FastMap<FormulaT, std::vector<Minisat::Lit> > smtrat::SATModule< Settings >::ConstraintLiteralsMap private
Maps the constraints occurring in the SAT module to their abstractions.
We store a vector of literals for each constraints, which is only used in the optimization, which applies valid substitutions.
Definition at line 308 of file SATModule.h.
Constructor & Destructor Documentation
SATModule()
template<class Settings > smtrat::SATModule< Settings >::SATModule (const ModuleInput * _formula, Conditionals & _foundAnswer, Manager *const _manager = nullptr)
Constructs a SATModule.
Parameters
_type The type of this module being SATModule.
_formula The formula passed to this module, called received formula.
_settings [Not yet used.]
_foundAnswer Vector of Booleans: If any of them is true, we have to terminate a running check procedure.
_manager A reference to the manager of the solver using this module.
Definition at line 62 of file SATModule.cpp.
Member Function Documentation
abstractLevel()
template<class Settings > uint32_t smtrat::SATModule< Settings >::abstractLevel (Minisat::Var x) const inline private
Used to represent an abstraction of sets of decision levels.
Parameters
x [Minisat related code]
Returns
[Minisat related code]
Definition at line 1609 of file SATModule.h.
adaptPassedFormula() [1/2]
template<class Settings > void smtrat::SATModule< Settings >::adaptPassedFormula () private
Adapts the passed formula according to the current assignment within the SAT solver.
Returns
true, if the passed formula has been changed; false, otherwise.
Definition at line 1531 of file SATModule.cpp.
adaptPassedFormula() [2/2]
template<class Settings > void smtrat::SATModule< Settings >::adaptPassedFormula (Abstraction & _abstr) private
Adapts the passed formula according to the given abstraction information.
Parameters
_abstr The information of a Boolean abstraction of a constraint (contains no information, if the Boolean does not correspond to a constraint's abstraction).
Definition at line 1585 of file SATModule.cpp.
add()
bool smtrat::Module::add (ModuleInput::const_iterator _subformula) inherited
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Definition at line 153 of file Module.cpp.
Referenced by smtrat::PModule::add(), smtrat::Manager::add(), smtrat::LRAModule< smtrat::LRASettingsICP >::addCore(), smtrat::Manager::getBackends(), and smtrat::EQModule< smtrat::EQSettingsForPreprocessing >::P_add_implicit_edge().
addAssumptionToCheck() [1/4]
void smtrat::Module::addAssumptionToCheck (const FormulaT & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_formula The formula which should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1019 of file Module.cpp.
Referenced by smtrat::Module::addLemma(), smtrat::Module::checkCore(), smtrat::Module::getInfeasibleSubsets(), smtrat::VSModule< Settings >::logConditions(), smtrat::vs::State::passConflictToFather(), and smtrat::VSModule< Settings >::runBackendSolvers().
addAssumptionToCheck() [2/4]
void smtrat::Module::addAssumptionToCheck (const ModuleInput & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_subformulas The sub-formulas whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1032 of file Module.cpp.
addAssumptionToCheck() [3/4]
void smtrat::Module::addAssumptionToCheck (const FormulasT & _formulas, bool _consistent, const std::string & _label) static inherited
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
Parameters
_formulas The formulas, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1058 of file Module.cpp.
addAssumptionToCheck() [4/4]
void smtrat::Module::addAssumptionToCheck (const ConstraintsT & _constraints, bool _consistent, const std::string & _label) static inherited
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
Parameters
_constraints The constraints, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 1079 of file Module.cpp.
addBooleanAssignments()
template<class Settings > void smtrat::SATModule< Settings >::addBooleanAssignments (EvalRationalMap & _rationalAssignment) const
Adds the Boolean assignments to the given assignments, which were determined by the Minisat procedure.
Note: Assignments in the given map are not overwritten.
Parameters
_rationalAssignment The assignments to add the Boolean assignments to.
Definition at line 879 of file SATModule.cpp.
addClause()
template<class Settings > bool smtrat::SATModule< Settings >::addClause (const Minisat::vec< Minisat::Lit > & _clause, unsigned _type = 0) private
Adds the clause of the given type with the given literals to the clauses managed by Minisat.
Parameters
_clause The clause to add.
_type The type of the clause (NORMAL_CLAUSE, LEMMA_CLAUSE or CONFLICT_CLAUSE).
_force If true backtracking won't stop at the first assumption-decision-level.
Returns
true, if a clause has been added; false, otherwise.
Definition at line 1679 of file SATModule.cpp.
addConstraintToInform()
template<class Settings > void smtrat::SATModule< Settings >::addConstraintToInform (const FormulaT & _constraint) inline virtual
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
Parameters
_constraint The constraint to add.
Reimplemented from smtrat::Module.
Definition at line 736 of file SATModule.h.
addCore()
template<class Settings > bool smtrat::SATModule< Settings >::addCore (ModuleInput::const_iterator _subformula) virtual
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Reimplemented from smtrat::Module.
Definition at line 199 of file SATModule.cpp.
addInformationRelevantFormula()
void smtrat::Module::addInformationRelevantFormula (const FormulaT & formula) protected inherited
Adds a formula to the InformationRelevantFormula.
Parameters
formula Formula to add
Definition at line 1197 of file Module.cpp.
addLemma()
void smtrat::Module::addLemma (const FormulaT & _lemma, const LemmaType & _lt = LemmaType::NORMAL, const FormulaT & _preferredFormula = FormulaT(carl::FormulaType::TRUE)) inline inherited
Stores a lemma being a valid formula.
Parameters
_lemma The eduction/lemma to store.
_lt The type of the lemma.
Definition at line 535 of file Module.h.
addOrigin()
void smtrat::Module::addOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Adds the given set of formulas in the received formula to the origins of the given passed formula.
Parameters
_formula The passed formula to set the origins for.
_origins A set of formulas in the received formula of this module.
Definition at line 867 of file Module.h.
addReceivedSubformulaToPassedFormula()
std::pair<ModuleInput::iterator,bool> smtrat::Module::addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula) inline protected inherited
Copies the given sub-formula of the received formula to the passed formula.
Note, that there is always a link between sub-formulas of the passed formulas to sub-formulas of the received formulas, which are responsible for its occurrence.
Parameters
_subformula The sub-formula of the received formula to copy.
Definition at line 926 of file Module.h.
Referenced by smtrat::Module::checkCore().
addSubformulaToPassedFormula() [1/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula) inline protected inherited
Adds the given formula to the passed formula with no origin.
Note that in the next call of this module's removeSubformula, all formulas in the passed formula without origins will be removed.
Parameters
_formula The formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 942 of file Module.h.
Referenced by smtrat::Module::addReceivedSubformulaToPassedFormula(), smtrat::Module::addSubformulaToPassedFormula(), and smtrat::CNFerModule::checkCore().
addSubformulaToPassedFormula() [2/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origins The link of the formula to add to the passed formula to sub-formulas of the received formulas, which are responsible for its occurrence
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 956 of file Module.h.
addSubformulaToPassedFormula() [3/3]
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const FormulaT & _origin) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origin The sub-formula of the received formula being responsible for the occurrence of the formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 970 of file Module.h.
allModels()
const std::vector<Model>& smtrat::Module::allModels () const inline inherited
Returns
All satisfying assignments, if existent.
Definition at line 486 of file Module.h.
Referenced by smtrat::Manager::allModels().
analyze()
template<class Settings > bool smtrat::SATModule< Settings >::analyze (Minisat::CRef confl, Minisat::vec< Minisat::Lit > & out_learnt, int & out_btlevel) private
analyze : (confl : Clause*) (out_learnt : vec<Lit>&) (out_btlevel : int&) -> [void]
Description: Analyze conflict and produce a reason clause.
Pre-conditions:
'out_learnt' is assumed to be cleared.
Current decision level must be greater than root level.
Post-conditions:
'out_learnt[0]' is the asserting literal at level 'out_btlevel'.
If out_learnt.size() > 1 then 'out_learnt[1]' has the greatest decision level of the rest of literals. There may be others from the same level though.
Parameters
confl A reference to the conflicting clause.
out_learnt The asserting clause derived by this method.
out_btlevel The level to backtrack to according the analysis of this method.
Returns
true, if the asserting clause does not equal the conflict clause given by confl
Definition at line 3353 of file SATModule.cpp.
anAnswerFound()
bool smtrat::Module::anAnswerFound () const inline protected inherited
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
Returns
True, if one of them has determined a result.
Definition at line 806 of file Module.h.
Referenced by smtrat::Module::foundAnswer(), and smtrat::Module::runBackends().
answerFound()
const smtrat::Conditionals& smtrat::Module::answerFound () const inline inherited
Returns
A vector of Booleans: If any of them is true, we have to terminate a running check procedure.
Definition at line 613 of file Module.h.
Referenced by smtrat::Manager::getBackends().
attachClause()
template<class Settings > void smtrat::SATModule< Settings >::attachClause (Minisat::CRef cr) private
Attach a clause to watcher lists.
Parameters
cr [Minisat related code]
mReceivedFormulaPurelyPropositional &&
Definition at line 2081 of file SATModule.cpp.
bestBranchLit()
template<class Settings > Lit smtrat::SATModule< Settings >::bestBranchLit () private
Returns
The best decision variable under consideration of the decision heuristic.
Definition at line 3234 of file SATModule.cpp.
branchAt()
bool smtrat::Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true, bool _useReceivedFormulaAsPremise = false) protected inherited
Adds a lemmas which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
Note that the given value is rounded down and up, if the given variable is integer-valued.
Parameters
_polynomial The variable to branch for. _integral A flag being true, if all variables in the polynomial to branch for are integral.
_value The value to branch at.
_premise The sub-formulas of the received formula from which the branch is followed. Note, that a premise is not necessary, as every branch is a valid formula. But a premise can prevent from branching unnecessarily.
_leftCaseWeak true, if a branching in the form of (or (<= p b) (> p b)) is desired. false, if a branching in the form of (or (< p b) (>= p b)) is desired.
_preferLeftCase true, if the left case (polynomial less(or equal) 0 shall be chosen first. false, otherwise.
_useReceivedFormulaAsPremise true, if the whole received formula should be used as premise
Definition at line 498 of file Module.cpp.
cancelAssignmentUntil()
template<class Settings > void smtrat::SATModule< Settings >::cancelAssignmentUntil (int level) private
Revert the variables assignment until a given level (keeping all assignments at 'level')
Parameters
level The level to backtrack to
Definition at line 2262 of file SATModule.cpp.
cancelUntil()
template<class Settings > void smtrat::SATModule< Settings >::cancelUntil (int level, bool force = false) private
Revert to the state at given level (keeping all assignments at 'level' but not beyond).
Parameters
level The level to backtrack to.
Definition at line 2209 of file SATModule.cpp.
check()
Answer smtrat::Module::check (bool _final = false, bool _full = true, carl::Variable _objective = carl::Variable::NO_VARIABLE) virtual inherited
Checks the received formula for consistency.
Note, that this is an implementation of the satisfiability check of the conjunction of the so far received formulas, which does actually nothing but passing the problem to its backends. This implementation is only used internally and must be overwritten by any derived module.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
True, if the received formula is satisfiable; False, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented in smtrat::PModule.
Definition at line 92 of file Module.cpp.
Referenced by smtrat::PModule::check(), and smtrat::Manager::check().
checkCore()
template<class Settings > Answer smtrat::SATModule< Settings >::checkCore () virtual
Checks the received formula for consistency.
Returns
SAT, if the received formula is satisfiable; UNSAT, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented from smtrat::Module.
Definition at line 364 of file SATModule.cpp.
checkFormula()
template<class Settings > Minisat::lbool smtrat::SATModule< Settings >::checkFormula () private
Checks the received formula for consistency.
Returns
l_True, if the received formula is satisfiable; l_False, if the received formula is not satisfiable; l_Undef, otherwise.
Definition at line 567 of file SATModule.cpp.
checkGarbage()
template<class Settings > void smtrat::SATModule< Settings >::checkGarbage (double gf) inline private
[Minisat related code]
Parameters
gf [Minisat related code]
Definition at line 1136 of file SATModule.h.
checkInfSubsetForMinimality()
void smtrat::Module::checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string & _filename = "smaller_muses", unsigned _maxSizeDifference = 1) const inherited
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
Parameters
_infsubset The infeasible subset to check for minimality.
_filename The name of the file to store the infeasible subsets in order to be able to check their infeasibility.
_maxSizeDifference The maximal difference between the sizes of the subsets compared to the size of the infeasible subset.
Definition at line 1147 of file Module.cpp.
Referenced by smtrat::GBModule< Settings >::checkCore().
checkModel()
unsigned smtrat::Module::checkModel () const protected inherited
Returns
false, if the current model of this module does not satisfy the current given formula; true, if it cannot be said whether the model satisfies the given formula.
Definition at line 611 of file Module.cpp.
claBumpActivity()
template<class Settings > void smtrat::SATModule< Settings >::claBumpActivity (Minisat::Clause & c) inline private
Increase a clause with the current 'bump' value.
Parameters
c [Minisat related code]
Definition at line 1509 of file SATModule.h.
claDecayActivity()
template<class Settings > void smtrat::SATModule< Settings >::claDecayActivity () inline private
Decay all clauses with the specified factor.
Implemented by increasing the 'bump' value instead.
Definition at line 1500 of file SATModule.h.
collectOrigins()
void smtrat::Module::collectOrigins (const FormulaT & _formula, FormulasT & _origins) const inherited
Collects the formulas in the given formula, which are part of the received formula.
If the given formula directly occurs in the received formula, it is inserted into the given set. Otherwise, the given formula must be of type AND and all its sub-formulas part of the received formula. Hence, they will be added to the given set.
Parameters
_formula The formula from which to collect the formulas being sub-formulas of the received formula (origins).
_origins The set in which to store the origins.
Definition at line 985 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
constraintsToInform()
const carl::FastSet<FormulaT>& smtrat::Module::constraintsToInform () const inline inherited
Returns
The constraints which the backends must be informed about.
Definition at line 511 of file Module.h.
createLiteral()
template<class Settings > Lit smtrat::SATModule< Settings >::createLiteral (const FormulaT & _formula, const FormulaT & _origin = FormulaT(carl::FormulaType::TRUE), bool _decisionRelevant = true) private
Creates or simply returns the literal belonging to the formula being the first argument.
Parameters
_formula The formula to get the literal for.
_origin The origin of the formula to get the literal for.
_decisionRelevant true, if the variable of the literal needs to be involved in the decision process of the SAT solving.
Returns
The corresponding literal.
Definition at line 1343 of file SATModule.cpp.
currentlySatisfied()
virtual unsigned smtrat::Module::currentlySatisfied (const FormulaT &) const inline virtual inherited
Returns
0, if the given formula is conflicted by the current model; 1, if the given formula is satisfied by the current model; 2, otherwise; 3, if we do not know anything (default)
Reimplemented in smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, and smtrat::LRAModule< smtrat::LRASettingsICP >.
Definition at line 387 of file Module.h.
currentlySatisfiedByBackend()
unsigned smtrat::Module::currentlySatisfiedByBackend (const FormulaT & _formula) const inherited
Returns
0, if the given formula is conflicted by the current model; 1, if the given formula is satisfied by the current model; 2, otherwise 3, if we do not know anything (default)
Definition at line 316 of file Module.cpp.
decisionLevel()
template<class Settings > int smtrat::SATModule< Settings >::decisionLevel () const inline private
Returns
The current decision level.
Definition at line 1599 of file SATModule.h.
deinform()
void smtrat::Module::deinform (const FormulaT & _constraint) inherited
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Definition at line 139 of file Module.cpp.
Referenced by smtrat::Manager::deinform().
deinformCore()
virtual void smtrat::Module::deinformCore (const FormulaT &) inline protected virtual inherited
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Reimplemented in smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, and smtrat::LRAModule< smtrat::LRASettingsICP >.
Definition at line 766 of file Module.h.
detachClause()
template<class Settings > void smtrat::SATModule< Settings >::detachClause (Minisat::CRef cr, bool strict = false) private
Detach a clause to watcher lists.
Parameters
cr [Minisat related code]
strict [Minisat related code]
mReceivedFormulaPurelyPropositional &&
Definition at line 2122 of file SATModule.cpp.
determine_smallest_origin()
size_t smtrat::Module::determine_smallest_origin (const std::vector< FormulaT > & origins) const protected inherited
Parameters
origins A vector of sets of origins.
Returns
The index of the smallest (regarding the size of the sets) element of origins
Definition at line 423 of file Module.cpp.
drand()
template<class Settings > static double smtrat::SATModule< Settings >::drand (double & seed) inline static private
Parameters
seed [Minisat related code]
Returns
A random float 0 <= x < 1. Seed must never be 0.
Definition at line 1684 of file SATModule.h.
Referenced by smtrat::SATModule< Settings >::irand().
enqueue()
template<class Settings > bool smtrat::SATModule< Settings >::enqueue (Minisat::Lit p, Minisat::CRef from = Minisat::CRef_Undef) inline private
Test if fact 'p' contradicts current state, enqueue otherwise.
NOTE: enqueue does not set the ok flag! (only public methods do)
Parameters
p [Minisat related code]
from [Minisat related code]
Returns
[Minisat related code]
Definition at line 1266 of file SATModule.h.
eraseSubformulaFromPassedFormula()
ModuleInput::iterator smtrat::Module::eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins = false) protected virtual inherited
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
Afterwards the sub-formula is removed from the passed formula.
Parameters
_subformula The sub-formula to remove from the passed formula.
_ignoreOrigins True, if the sub-formula shall be removed regardless of its origins (should only be applied with expertise).
Returns
Reimplemented in smtrat::ICPModule< Settings >, smtrat::ICPModule< smtrat::ICPSettings1 >, and smtrat::ICPModule< smtrat::ICPSettings4 >.
Definition at line 832 of file Module.cpp.
findBestOrigin()
std::vector< FormulaT >::const_iterator smtrat::Module::findBestOrigin (const std::vector< FormulaT > & _origins) const protected inherited
Parameters
_origins
Returns
Definition at line 714 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
firstSubformulaToPass()
ModuleInput::const_iterator smtrat::Module::firstSubformulaToPass () const inline inherited
Returns
The position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
Definition at line 597 of file Module.h.
Referenced by smtrat::Manager::getBackends().
firstUncheckedReceivedSubformula()
ModuleInput::const_iterator smtrat::Module::firstUncheckedReceivedSubformula () const inline inherited
Returns
The position of the first (by this module) unchecked sub-formula of the received formula.
Definition at line 589 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore().
fullAssignment()
template<class Settings > bool smtrat::SATModule< Settings >::fullAssignment () private
Returns
true, if the current assignment is a full one.
Definition at line 3173 of file SATModule.cpp.
getInfeasibleSubsets()
std::vector< FormulaSetT > smtrat::Module::getInfeasibleSubsets (const Module & _backend) const protected inherited
Get the infeasible subsets the given backend provides.
Note, that an infeasible subset in a backend contains sub formulas of the passed formula and an infeasible subset of this module contains sub formulas of the received formula. In this method the LATTER is returned.
Parameters
_backend The backend from which to obtain the infeasible subsets.
Returns
The infeasible subsets the given backend provides.
Definition at line 732 of file Module.cpp.
getInformationRelevantFormulas()
const std::set< FormulaT > & smtrat::Module::getInformationRelevantFormulas () protected inherited
Gets all InformationRelevantFormulas.
Returns
Set of all formulas
Definition at line 1203 of file Module.cpp.
getModelEqualities()
std::list< std::vector< carl::Variable > > smtrat::Module::getModelEqualities () const virtual inherited
Partition the variables from the current model into equivalence classes according to their assigned value.
The result is a set of equivalence classes of variables where all variables within one class are assigned the same value. Note that the number of classes may not be minimal, i.e. two classes may actually be equivalent.
Returns
Equivalence classes.
Definition at line 328 of file Module.cpp.
Referenced by smtrat::Manager::getModelEqualities().
getOrigins() [1/3]
const FormulaT& smtrat::Module::getOrigins (ModuleInput::const_iterator _formula) const inline protected inherited
Gets the origins of the passed formula at the given position.
Parameters
_formula The position of a formula in the passed formulas.
Returns
The origins of the passed formula at the given position.
Definition at line 877 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets().
getOrigins() [2/3]
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulasT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 1024 of file Module.h.
getOrigins() [3/3]
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulaSetT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 1037 of file Module.h.
getReceivedFormulaSimplified()
std::pair< bool, FormulaT > smtrat::Module::getReceivedFormulaSimplified () virtual inherited
Returns
A pair of a Boolean and a formula, where the Boolean is true, if the received formula could be simplified to an equisatisfiable formula. The formula is equisatisfiable to this module's reveived formula, if the Boolean is true.
Reimplemented in smtrat::PModule.
Definition at line 970 of file Module.cpp.
Referenced by smtrat::Manager::getInputSimplified().
handleConflict()
template<class Settings > void smtrat::SATModule< Settings >::handleConflict (Minisat::CRef _confl) private
Handles conflict.
Parameters
conf conflict clause
Returns
if return is not l_True, search can be aborted
Definition at line 3036 of file SATModule.cpp.
hasValidInfeasibleSubset()
bool smtrat::Module::hasValidInfeasibleSubset () const inherited
Returns
true, if the module has at least one valid infeasible subset, that is all its elements are sub-formulas of the received formula (pointer must be equal).
Definition at line 1129 of file Module.cpp.
id()
std::size_t smtrat::Module::id () const inline inherited
Returns
A unique ID to identify this module instance.
Definition at line 411 of file Module.h.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::addCandidateToRelevant(), smtrat::ICPModule< smtrat::ICPSettings4 >::removeCandidateFromRelevant(), and smtrat::ICPModule< smtrat::ICPSettings4 >::updateRelevantCandidates().
infeasibleSubsets()
const std::vector<FormulaSetT>& smtrat::Module::infeasibleSubsets () const inline inherited
Returns
The infeasible subsets of the set of received formulas (empty, if this module has not detected unsatisfiability of the conjunction of received formulas.
Definition at line 495 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets(), smtrat::Manager::infeasibleSubsets(), smtrat::Manager::printInfeasibleSubset(), and smtrat::ICPModule< smtrat::ICPSettings4 >::remapAndSetLraInfeasibleSubsets().
inform()
bool smtrat::Module::inform (const FormulaT & _constraint) inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Definition at line 132 of file Module.cpp.
Referenced by smtrat::Manager::add(), smtrat::Manager::getBackends(), smtrat::Manager::inform(), and smtrat::Manager::Manager().
informBackends()
void smtrat::Module::informBackends (const FormulaT & _constraint) inline protected inherited
Informs all backends of this module about the given constraint.
Parameters
_constraint The constraint to inform about.
Definition at line 905 of file Module.h.
informCore()
virtual bool smtrat::Module::informCore (const FormulaT &) inline protected virtual inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Reimplemented in smtrat::EQModule< Settings >, smtrat::EQModule< smtrat::EQSettingsForPreprocessing >, smtrat::IntBlastModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::LRAModule< smtrat::LRASettingsICP >, smtrat::ICPModule< Settings >, smtrat::ICPModule< smtrat::ICPSettings1 >, smtrat::ICPModule< smtrat::ICPSettings4 >, smtrat::PBPPModule< Settings >, smtrat::NewCADModule< Settings >, smtrat::BVModule< Settings >, smtrat::UnionFindModule< Settings >, smtrat::CurryModule< Settings >, smtrat::PBGaussModule< Settings >, smtrat::NRAILModule< Settings >, and smtrat::FPPModule< Settings >.
Definition at line 755 of file Module.h.
informedConstraints()
const carl::FastSet<FormulaT>& smtrat::Module::informedConstraints () const inline inherited
Returns
The position of the first constraint of which no backend has been informed about.
Definition at line 519 of file Module.h.
Referenced by smtrat::Manager::getBackends().
init()
void smtrat::Module::init () virtual inherited
Informs all backends about the so far encountered constraints, which have not yet been communicated.
This method must not be called twice and only before the first runBackends call.
Reimplemented in smtrat::EQModule< Settings >, smtrat::EQModule< smtrat::EQSettingsForPreprocessing >, smtrat::IntBlastModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::LRAModule< smtrat::LRASettingsICP >, smtrat::PBPPModule< Settings >, smtrat::NewCADModule< Settings >, smtrat::BVModule< Settings >, smtrat::CurryModule< Settings >, smtrat::PBGaussModule< Settings >, smtrat::NRAILModule< Settings >, and smtrat::FPPModule< Settings >.
Definition at line 254 of file Module.cpp.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::addCore(), and smtrat::SATModule< Settings >::checkCore().
insertVarOrder()
template<class Settings > void smtrat::SATModule< Settings >::insertVarOrder (Minisat::Var x) inline private
Insert a variable in the decision order priority queue.
Parameters
x [Minisat related code]
Definition at line 1163 of file SATModule.h.
Referenced by smtrat::SATModule< Settings >::setDecisionVar().
irand()
template<class Settings > static int smtrat::SATModule< Settings >::irand (double & seed, int size) inline static private
Parameters
seed [Minisat related code]
size [Minisat related code]
Returns
A random integer 0 <= x < size. Seed must never be 0.
Definition at line 1697 of file SATModule.h.
isLemmaLevel()
bool smtrat::Module::isLemmaLevel (LemmaLevel level) protected inherited
Checks if current lemma level is greater or equal to given level.
Parameters
level Level to check.
Definition at line 1208 of file Module.cpp.
isPreprocessor()
bool smtrat::Module::isPreprocessor () const inline inherited
Returns
true, if this module is a preprocessor that is a module, which simplifies its received formula to an equisatisfiable formula being passed to its backends. The simplified formula can be obtained with getReceivedFormulaSimplified().
Definition at line 623 of file Module.h.
learnTheoryConflicts()
template<class Settings > void smtrat::SATModule< Settings >::learnTheoryConflicts () private
Adds the clauses representing all conflicts generated by all backends.
Returns
A reference to the clause representing the best infeasible subset.
Definition at line 4069 of file SATModule.cpp.
lemmas()
const std::vector<Lemma>& smtrat::Module::lemmas () const inline inherited
Returns
A constant reference to the lemmas being valid formulas this module or its backends made.
Definition at line 581 of file Module.h.
Referenced by smtrat::Manager::lemmas().
level() [1/2]
template<class Settings > int smtrat::SATModule< Settings >::level (Minisat::Var x) const inline private
Parameters
x The variable for which we to get the level in which it has been assigned to a value.
Returns
The level in which the variable has been assigned, if it is not unassigned.
Definition at line 1628 of file SATModule.h.
Referenced by smtrat::SATModule< Settings >::abstractLevel().
level() [2/2]
template<class Settings > int smtrat::SATModule< Settings >::level (const Minisat::vec< Minisat::Lit > & _clause) const private
Parameters
_clause The clause to get the highest decision level in which assigned one of its literals has been assigned.
Returns
The highest decision level which assigned a literal of the given clause.
Definition at line 1786 of file SATModule.cpp.
litRedundant()
template<class Settings > bool smtrat::SATModule< Settings >::litRedundant (Minisat::Lit p, uint32_t abstract_levels) private
Check if 'p' can be removed.
'abstract_levels' is used to abort early if the algorithm is visiting literals at levels that cannot be removed later.
Parameters
p [Minisat related code]
abstract_levels [Minisat related code]
Returns
[Minisat related code]
Definition at line 3627 of file SATModule.cpp.
locked()
template<class Settings > bool smtrat::SATModule< Settings >::locked (const Minisat::Clause & c) inline private
Parameters
c [Minisat related code]
Returns
TRUE if a clause is a reason for some implication in the current state.
Definition at line 1551 of file SATModule.h.
luby()
template<class Settings > double smtrat::SATModule< Settings >::luby (double y, int x) static private
Finite subsequences of the Luby-sequence:
0: 1 1: 1 1 2 2: 1 1 2 1 1 2 4 3: 1 1 2 1 1 2 4 1 1 2 1 1 2 4 8 ...
Parameters
y
x
Returns
Definition at line 346 of file SATModule.cpp.
mapVar()
template<class Settings > Var smtrat::SATModule< Settings >::mapVar (Minisat::Var x, Minisat::vec< Minisat::Var > & map, Minisat::Var & max) static private
[Minisat related code]
Parameters
x [Minisat related code]
map [Minisat related code]
max [Minisat related code]
Returns
[Minisat related code]
Definition at line 4275 of file SATModule.cpp.
maxActivity()
template<class Settings > double smtrat::SATModule< Settings >::maxActivity () const inline private
Returns
The maximum of all activities of the occurring literals.
Definition at line 1424 of file SATModule.h.
merge()
std::vector< FormulaT > smtrat::Module::merge (const std::vector< FormulaT > & _vecSetA, const std::vector< FormulaT > & _vecSetB) const protected inherited
Merges the two vectors of sets into the first one.
({a,b},{a,c}) and ({b,d},{b}) -> ({a,b,d},{a,b},{a,b,c,d},{a,b,c})
Parameters
_vecSetA A vector of sets of constraints.
_vecSetB A vector of sets of constraints.
Returns
The vector being the two given vectors merged.
Definition at line 397 of file Module.cpp.
model()
const Model& smtrat::Module::model () const inline inherited
Returns
The assignment of the current satisfiable result, if existent.
Definition at line 478 of file Module.h.
Referenced by smtrat::Module::backendsModel(), smtrat::Module::clearModels(), smtrat::Module::getBackendsAllModels(), and smtrat::Manager::model().
modelsDisjoint()
bool smtrat::Module::modelsDisjoint (const Model & _modelA, const Model & _modelB) static protected inherited
Checks whether there is no variable assigned by both models.
Parameters
_modelA The first model to check for.
_modelB The second model to check for.
Returns
true, if there is no variable assigned by both models; false, otherwise.
Definition at line 634 of file Module.cpp.
moduleName()
virtual std::string smtrat::Module::moduleName () const inline virtual inherited
Returns
The name of the given module type as name.
Reimplemented in smtrat::EQModule< Settings >, smtrat::EQModule< smtrat::EQSettingsForPreprocessing >, smtrat::IntBlastModule< Settings >, smtrat::CSplitModule< Settings >, smtrat::ICPModule< Settings >, smtrat::ICPModule< smtrat::ICPSettings1 >, smtrat::ICPModule< smtrat::ICPSettings4 >, smtrat::STropModule< Settings >, smtrat::FouMoModule< Settings >, smtrat::EQPreprocessingModule< Settings >, smtrat::CADModule< Settings >, smtrat::PBPPModule< Settings >, smtrat::VSModule< Settings >, smtrat::NewCADModule< Settings >, smtrat::UFCegarModule< Settings >, smtrat::BVModule< Settings >, smtrat::UnionFindModule< Settings >, smtrat::GBModule< Settings >, smtrat::IntEqModule< Settings >, smtrat::CubeLIAModule< Settings >, smtrat::CurryModule< Settings >, smtrat::LVEModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::LRAModule< smtrat::LRASettingsICP >, smtrat::IncWidthModule< Settings >, smtrat::PBGaussModule< Settings >, smtrat::BEModule< Settings >, smtrat::NRAILModule< Settings >, and smtrat::SplitSOSModule< Settings >.
Definition at line 631 of file Module.h.
Referenced by smtrat::Module::addLemma(), smtrat::Module::checkCore(), smtrat::Module::checkInfSubsetForMinimality(), and smtrat::Module::getInfeasibleSubsets().
nAssigns()
template<class Settings > int smtrat::SATModule< Settings >::nAssigns () const inline private
Returns
The current number of assigned literals.
Definition at line 1044 of file SATModule.h.
nClauses()
template<class Settings > int smtrat::SATModule< Settings >::nClauses () const inline private
Returns
The current number of original clauses.
Definition at line 1052 of file SATModule.h.
newVar()
template<class Settings > Var smtrat::SATModule< Settings >::newVar (bool polarity = true, bool dvar = true, double _activity = 0, bool insertIntoHeap = true) private
Creates a new SAT variable in the solver.
If 'decision' is cleared, variable will not be used as a decision variable (NOTE! This has effects on the meaning of a SATISFIABLE result).
Parameters
polarity A flag, which is true, if the variable preferably is assigned to false.
dvar A flag, which is true, if the variable to create needs to considered in the solving.
_activity The initial activity of the variable to create.
_tseitinShadowed A flag, which is true, if the variable to create is a sub-formula of a formula represented by a Tseitin variable.
Returns
The created Minisat variable.
mReceivedFormulaPurelyPropositional &&
Definition at line 1652 of file SATModule.cpp.
Referenced by smtrat::SATModule< Settings >::SATModule().
nFreeVars()
template<class Settings > int smtrat::SATModule< Settings >::nFreeVars () const inline private
Returns
[Minisat related code]
Definition at line 1076 of file SATModule.h.
nLearnts()
template<class Settings > int smtrat::SATModule< Settings >::nLearnts () const inline private
Returns
The current number of learned clauses.
Definition at line 1060 of file SATModule.h.
nVars()
template<class Settings > int smtrat::SATModule< Settings >::nVars () const inline private
Returns
The current number of variables.
Definition at line 1068 of file SATModule.h.
Referenced by smtrat::SATModule< Settings >::varBumpActivity().
okay()
template<class Settings > bool smtrat::SATModule< Settings >::okay () const inline private
Returns
FALSE means solver is in a conflicting state
Definition at line 889 of file SATModule.h.
passedFormulaBegin()
ModuleInput::iterator smtrat::Module::passedFormulaBegin () inline protected inherited
Returns
An iterator to the end of the passed formula. TODO: disable this method
Definition at line 849 of file Module.h.
passedFormulaCorrect()
template<class Settings > bool smtrat::SATModule< Settings >::passedFormulaCorrect () const private
Returns
true, if the passed formula coincides with the constraints whose abstractions (literals) are assigned to true.
Definition at line 1619 of file SATModule.cpp.
passedFormulaEnd()
ModuleInput::iterator smtrat::Module::passedFormulaEnd () inline protected inherited
Returns
An iterator to the end of the passed formula.
Definition at line 857 of file Module.h.
pickBranchLit()
template<class Settings > Lit smtrat::SATModule< Settings >::pickBranchLit () private
Returns
The next decision variable.
mReceivedFormulaPurelyPropositional &&
Definition at line 3186 of file SATModule.cpp.
pPassedFormula()
const ModuleInput* smtrat::Module::pPassedFormula () const inline inherited
Returns
A pointer to the formula passed to the backends of this module.
Definition at line 462 of file Module.h.
Referenced by smtrat::Manager::getBackends().
pReceivedFormula()
const ModuleInput* smtrat::Module::pReceivedFormula () const inline inherited
Returns
A pointer to the formula passed to this module.
Definition at line 446 of file Module.h.
print() [1/2]
template<class Settings > void smtrat::SATModule< Settings >::print (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints everything.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4286 of file SATModule.cpp.
print() [2/2]
void smtrat::Module::print (const std::string & _initiation = "***") const inherited
Prints everything relevant of the solver.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1214 of file Module.cpp.
Referenced by smtrat::ICPModule< smtrat::ICPSettings4 >::activateNonlinearConstraint().
printAllModels()
void smtrat::Module::printAllModels (std::ostream & _out = std::cout) inherited
Prints all assignments of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1290 of file Module.cpp.
Referenced by smtrat::Manager::printAllAssignments().
printBooleanConstraintMap()
template<class Settings > void smtrat::SATModule< Settings >::printBooleanConstraintMap (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the literal to constraint map.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4372 of file SATModule.cpp.
printBooleanVarMap()
template<class Settings > void smtrat::SATModule< Settings >::printBooleanVarMap (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints map of the Boolean within the SAT solver to the given Booleans.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4358 of file SATModule.cpp.
printClause() [1/2]
template<class Settings > void smtrat::SATModule< Settings >::printClause (Minisat::CRef _clause, bool _withAssignment = false, std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the clause at the given reference.
Parameters
_clause The reference of the clause.
_withAssignment A flag indicating if true, that the assignments should be printed too.
_out The output stream where the answer should be printed.
_init The prefix of each printed line.
Definition at line 4407 of file SATModule.cpp.
printClause() [2/2]
template<class Settings > void smtrat::SATModule< Settings >::printClause (const Minisat::vec< Minisat::Lit > & _clause, bool _withAssignment = false, std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the clause resulting from the given vector of literals.
Parameters
_clause The reference of the clause.
_withAssignment A flag indicating if true, that the assignments should be printed too.
_out The output stream where the answer should be printed.
_init The prefix of each printed line.
Definition at line 4394 of file SATModule.cpp.
printClauseInformation()
template<class Settings > void smtrat::SATModule< Settings >::printClauseInformation (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the clause information.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4348 of file SATModule.cpp.
printClauses()
template<class Settings > void smtrat::SATModule< Settings >::printClauses (const Minisat::vec< Minisat::CRef > & _clauses, const std::string _name, std::ostream & _out = std::cout, const std::string & _init = "", int _from = 0, bool _withAssignment = false, bool _onlyNotSatisfied = false) const
Prints all given clauses.
Parameters
_clauses The clauses to print.
_name The name of the clauses to print. (e.g. learnts, clauses, ..)
_out The output stream where the answer should be printed.
_init The prefix of each printed line.
_from The position of the first clause to print within the given vector of clauses.
_withAssignment A flag indicating if true, that the assignments should be printed too.
Definition at line 4428 of file SATModule.cpp.
printConstraintLiteralMap()
template<class Settings > void smtrat::SATModule< Settings >::printConstraintLiteralMap (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the constraints to literal map.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4311 of file SATModule.cpp.
printCurrentAssignment()
template<class Settings > void smtrat::SATModule< Settings >::printCurrentAssignment (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the current assignment of the SAT solver.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4488 of file SATModule.cpp.
printDecisions()
template<class Settings > void smtrat::SATModule< Settings >::printDecisions (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the decisions the SAT solver has made.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4535 of file SATModule.cpp.
printFormulaCNFInfosMap()
template<class Settings > void smtrat::SATModule< Settings >::printFormulaCNFInfosMap (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the formulas to clauses map.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4331 of file SATModule.cpp.
printInfeasibleSubsets()
void smtrat::Module::printInfeasibleSubsets (const std::string & _initiation = "***") const inherited
Prints the infeasible subsets.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1265 of file Module.cpp.
printLiteralsActiveOccurrences()
template<class Settings > void smtrat::SATModule< Settings >::printLiteralsActiveOccurrences (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the literals' active occurrences in all clauses.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4601 of file SATModule.cpp.
printModel()
void smtrat::Module::printModel (std::ostream & _out = std::cout) const inherited
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1280 of file Module.cpp.
Referenced by smtrat::Manager::printAssignment().
printPassedFormula()
void smtrat::Module::printPassedFormula (const std::string & _initiation = "***") const inherited
Prints the vector of passed formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1247 of file Module.cpp.
printPropagatedLemmas()
template<class Settings > void smtrat::SATModule< Settings >::printPropagatedLemmas (std::ostream & _out = std::cout, const std::string & _init = "") const
Prints the propagated lemmas for each variables which influence its value.
Parameters
_out The output stream where the answer should be printed.
_init The line initiation.
Definition at line 4579 of file SATModule.cpp.
printReceivedFormula()
void smtrat::Module::printReceivedFormula (const std::string & _initiation = "***") const inherited
Prints the vector of the received formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1234 of file Module.cpp.
printSatState()
template<class Settings > void smtrat::SATModule< Settings >::printSatState (std::ostream & = std::cout, const std::string = "") private
[Minisat related code]
Parameters
std::cout [Minisat related code]
[Minisat related code]
probablyLooping()
bool smtrat::Module::probablyLooping (const typename Poly::PolyType & _branchingPolynomial, const Rational & _branchingValue) const protected inherited
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
Parameters
_branchingPolynomial The polynomial to branch at (in most branching strategies this is just a variable).
_branchingValue The value to branch at.
Returns
true, if this branching is probably part of an infinite loop of branchings; false, otherwise.
Definition at line 446 of file Module.cpp.
processLemmas()
template<class Settings > bool smtrat::SATModule< Settings >::processLemmas () private
Adds clauses representing the lemmas which should be added to this SATModule.
This may provoke backtracking.
Returns
true, if any clause has been added.
Definition at line 4030 of file SATModule.cpp.
progressEstimate()
template<class Settings > double smtrat::SATModule< Settings >::progressEstimate () const private
Returns
An estimation of the progress the SAT solver has been made, depending on how many assignments have been excluded and how many assignments are in general possible. The calculated value is between 0 and 1.
Definition at line 4158 of file SATModule.cpp.
propagate()
template<class Settings > CRef smtrat::SATModule< Settings >::propagate () private
propagate : [void] -> [Clause*]
Description: Propagates all enqueued facts. If a conflict arises, the conflicting clause is returned, otherwise CRef_Undef.
Post-conditions:
the propagation queue is empty, even if there was a conflict.
Returns
A reference to the conflicting clause, if a conflict has been detected.
Definition at line 3814 of file SATModule.cpp.
propagateConsistently()
template<class Settings > CRef smtrat::SATModule< Settings >::propagateConsistently (bool _checkWithTheory = true) private
Propagate and check the consistency of the constraints, whose abstraction literals have been assigned to true.
Parameters
_madeTheoryCall A flag which is set to true, if at least one theory call has been made within this method.
Returns
A reference to a conflicting clause, if a clause has been added.
Definition at line 2396 of file SATModule.cpp.
reason()
template<class Settings > CRef smtrat::SATModule< Settings >::reason (Minisat::Var x) private
Parameters
x The variable to get the reason for it's assignment.
Returns
A reference to the clause, which implied the current assignment of this variable. It is not defined, if the assignment of the variable follows from a clause of size 0 or if the variable is unassigned.
Definition at line 2515 of file SATModule.cpp.
Referenced by smtrat::SATModule< Settings >::locked().
reduceDB()
template<class Settings > void smtrat::SATModule< Settings >::reduceDB () private
reduceDB : () -> [void]
Description: Remove half of the learnt clauses, minus the clauses locked by the current assignment. Locked clauses are clauses that are reason to some assignment. Binary clauses are never removed.
Definition at line 3933 of file SATModule.cpp.
relocAll()
template<class Settings > void smtrat::SATModule< Settings >::relocAll (Minisat::ClauseAllocator & to) private
[Minisat related code]
Parameters
to [Minisat related code]
mReceivedFormulaPurelyPropositional &&
Definition at line 4174 of file SATModule.cpp.
remove()
void smtrat::Module::remove (ModuleInput::const_iterator _subformula) virtual inherited
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
_subformula The sub formula of the received formula to remove.
Reimplemented in smtrat::PModule.
Definition at line 174 of file Module.cpp.
Referenced by smtrat::PModule::remove(), smtrat::Manager::remove(), and smtrat::LRAModule< smtrat::LRASettingsICP >::removeCore().
removeClause()
template<class Settings > void smtrat::SATModule< Settings >::removeClause (Minisat::CRef cr) private
Detach and free a clause.
Parameters
cr [Minisat related code]
Definition at line 2175 of file SATModule.cpp.
removeCore()
template<class Settings > void smtrat::SATModule< Settings >::removeCore (ModuleInput::const_iterator _subformula) virtual
Removes everything related to the given sub-formula of the received formula.
Parameters
_subformula The sub formula of the received formula to remove.
Reimplemented from smtrat::Module.
Definition at line 251 of file SATModule.cpp.
removeSatisfied()
template<class Settings > void smtrat::SATModule< Settings >::removeSatisfied (Minisat::vec< Minisat::CRef > & cs) private
Removes all satisfied clauses from the given vector of clauses, which should only be performed in decision level 0.
Parameters
cs The vector of clauses wherein to remove all satisfied clauses.
Definition at line 3967 of file SATModule.cpp.
resetVariableAssignment()
template<class Settings > void smtrat::SATModule< Settings >::resetVariableAssignment (Minisat::Var _var) private
mReceivedFormulaPurelyPropositional &&
Definition at line 2290 of file SATModule.cpp.
rPassedFormula()
const ModuleInput& smtrat::Module::rPassedFormula () const inline inherited
Returns
A reference to the formula passed to the backends of this module.
Definition at line 470 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Manager::getBackends().
rReceivedFormula()
const ModuleInput& smtrat::Module::rReceivedFormula () const inline inherited
Returns
A reference to the formula passed to this module.
Definition at line 454 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Module::generateTrivialInfeasibleSubset().
runBackends()
Answer smtrat::Module::runBackends (bool _final, bool _full, carl::Variable _objective) protected virtual inherited
Runs the backend solvers on the passed formula.
Parameters
_final true, if this satisfiability check will be the last one (for a global sat-check), if its result is SAT
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
_objective if not set to NO_VARIABLE, the module should find an assignment minimizing this objective variable; otherwise any assignment is good.
Returns
True, if the passed formula is consistent; False, if the passed formula is inconsistent; Unknown, otherwise.
Reimplemented in smtrat::PModule.
Definition at line 752 of file Module.cpp.
Referenced by smtrat::Module::checkCore().
satisfied()
template<class Settings > bool smtrat::SATModule< Settings >::satisfied (const Minisat::Clause & c) const private
Parameters
c [Minisat related code]
Returns
TRUE if a clause is satisfied in the current state.
Definition at line 2187 of file SATModule.cpp.
search()
template<class Settings > Minisat::lbool smtrat::SATModule< Settings >::search (int nof_conflicts = 100) private
search : (nof_conflicts : int) (params : const SearchParams&) -> [lbool]
Description: Search for a model the specified number of conflicts. NOTE! Use negative value for 'nof_conflicts' indicate infinity.
Output: 'l_True' if a partial assignment that is consistent with respect to the clause set is found. If all variables are decision variables, this means that the clause set is satisfiable. 'l_False' if the clause set is unsatisfiable. 'l_Undef' if the bound on number of conflicts is reached.
Parameters
nof_conflicts The number of conflicts after which a restart is forced.
Returns
l_True, if the considered clauses are satisfiable; l_False, if the considered clauses are unsatisfiable; l_Undef, if it could not been detected whether the given set of clauses is satisfiable or not.
Look for literals that are
fully assigned in the theory
unassigned in boolean
Definition at line 2680 of file SATModule.cpp.
setConfBudget()
template<class Settings > void smtrat::SATModule< Settings >::setConfBudget (int64_t x) inline private
[Minisat related code]
Parameters
x [Minisat related code]
Definition at line 1087 of file SATModule.h.
setDecisionVar()
template<class Settings > void smtrat::SATModule< Settings >::setDecisionVar (Minisat::Var v, bool b, bool insertIntoHeap = true) inline private
Declare if a variable should be eligible for selection in the decision heuristic.
Parameters
v The variable to change the eligibility for selection in the decision heuristic.
b true, if the variable should be eligible for selection in the decision heuristic.
Definition at line 911 of file SATModule.h.
setId()
void smtrat::Module::setId (std::size_t _id) inline inherited
Sets this modules unique ID to identify itself.
Parameters
_id The id to set this module's id to.
Definition at line 420 of file Module.h.
Referenced by smtrat::Manager::getBackends().
setPolarity()
template<class Settings > void smtrat::SATModule< Settings >::setPolarity (Minisat::Var v, bool b) inline private
Declare which polarity the decision heuristic should use for a variable.
Requires mode 'polarity_user'.
Parameters
v The variable to set the polarity for.
b true, if the variables should be preferably assigned to false.
Definition at line 901 of file SATModule.h.
setPropBudget()
template<class Settings > void smtrat::SATModule< Settings >::setPropBudget (int64_t x) inline private
[Minisat related code]
Parameters
x [Minisat related code]
Definition at line 1096 of file SATModule.h.
setThreadPriority()
void smtrat::Module::setThreadPriority (thread_priority _threadPriority) inline inherited
Sets the priority of this module to get a thread for running its check procedure.
Parameters
_threadPriority The priority to set this module's thread priority to.
Definition at line 438 of file Module.h.
Referenced by smtrat::Manager::getBackends().
solverState()
Answer smtrat::Module::solverState () const inline inherited
Returns
True, if this module is in a state, such that it has found a solution for its received formula; False, if this module is in a state, such that it has determined that there is no solution for its received formula; Unknown, otherwise.
Definition at line 403 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), smtrat::Module::getReceivedFormulaSimplified(), and smtrat::Module::updateAllModels().
splitUnequalConstraint()
void smtrat::Module::splitUnequalConstraint (const FormulaT & _unequalConstraint) protected inherited
Adds the following lemmas for the given constraint p!=0.
(p!=0 <-> (p<0 or p>0)) and not(p<0 and p>0)
Parameters
_unequalConstraint A constraint having the relation symbol !=.
Definition at line 588 of file Module.cpp.
storeAssumptionsToCheck()
void smtrat::Module::storeAssumptionsToCheck (const Manager & _manager) static inherited
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Parameters
_manager The manager object of this solver to store the assumptions for.
Definition at line 1099 of file Module.cpp.
Referenced by smtrat::Manager::~Manager().
threadPriority()
thread_priority smtrat::Module::threadPriority () const inline inherited
Returns
The priority of this module to get a thread for running its check procedure.
Definition at line 429 of file Module.h.
Referenced by smtrat::Manager::getBackends().
uncheckedEnqueue()
template<class Settings > void smtrat::SATModule< Settings >::uncheckedEnqueue (Minisat::Lit p, Minisat::CRef from = Minisat::CRef_Undef) private
Enqueue a literal.
Assumes value of literal is undefined.
Parameters
p The literal to enqueue. (The variable in the literal is set to true, if the literal is positive, and to false, if the literal is negative).s
from A reference to the clause, which implied this assignment.
mReceivedFormulaPurelyPropositional &&
Definition at line 3666 of file SATModule.cpp.
Referenced by smtrat::SATModule< Settings >::enqueue(), and smtrat::SATModule< Settings >::SATModule().
updateModel()
template<class Settings > void smtrat::SATModule< Settings >::updateModel (Model & model, bool only_relevant_variables = false) const private
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
Parameters
model The model to update with the current assignment
only_relevant_variables If true, only variables in mRelevantVariables are part of the model
Definition at line 706 of file SATModule.cpp.
usedBackends()
const std::vector<Module*>& smtrat::Module::usedBackends () const inline inherited
Returns
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
Definition at line 503 of file Module.h.
Referenced by smtrat::Module::getReceivedFormulaSimplified().
value() [1/2]
template<class Settings > Minisat::lbool smtrat::SATModule< Settings >::value (Minisat::Var x) const inline private
Parameters
x The variable to get its value for.
Returns
The current value of a variable.
Definition at line 930 of file SATModule.h.
Referenced by smtrat::SATModule< Settings >::enqueue(), smtrat::SATModule< Settings >::locked(), and smtrat::SATModule< Settings >::value().
value() [2/2]
template<class Settings > Minisat::lbool smtrat::SATModule< Settings >::value (Minisat::Lit p) const inline private
Parameters
p The literal to get its value for.
Returns
The current value of a literal.
Definition at line 1033 of file SATModule.h.
varBumpActivity() [1/2]
template<class Settings > void smtrat::SATModule< Settings >::varBumpActivity (Minisat::Var v, double inc) inline private
Increase a variable with the current 'bump' value.
Parameters
v [Minisat related code]
inc [Minisat related code]
Definition at line 1448 of file SATModule.h.
Referenced by smtrat::SATModule< Settings >::varBumpActivity().
varBumpActivity() [2/2]
template<class Settings > void smtrat::SATModule< Settings >::varBumpActivity (Minisat::Var v) inline private
Increase a variable with the current 'bump' value.
Parameters
v [Minisat related code]
Definition at line 1492 of file SATModule.h.
varDecayActivity()
template<class Settings > void smtrat::SATModule< Settings >::varDecayActivity () inline private
Decay all variables with the specified factor.
Implemented by increasing the 'bump' value instead.
Definition at line 1438 of file SATModule.h.
withinBudget()
template<class Settings > bool smtrat::SATModule< Settings >::withinBudget () const inline private
Returns
[Minisat related code]
Definition at line 1672 of file SATModule.h.
Field Documentation
mConstraintLiteralMap
template<class Settings > ConstraintLiteralsMap smtrat::SATModule< Settings >::mConstraintLiteralMap private
Maps the constraints occurring in the SAT module to their abstractions.
We store a vector of literals for each constraints, which is only used in the optimization, which applies valid substitutions.
Definition at line 570 of file SATModule.h.
mCurrentAssignmentConsistent
template<class Settings > Answer smtrat::SATModule< Settings >::mCurrentAssignmentConsistent private
Stores gained information about the current assignment's consistency.
If we know from the last consistency check, whether the current assignment is consistent, this member is SAT, if we know that it is inconsistent it is UNSAT, otherwise Unknown.
Definition at line 552 of file SATModule.h.
mNonassumedTseitinVariable
template<class Settings > carl::Bitset smtrat::SATModule< Settings >::mNonassumedTseitinVariable private
Stores whether a given tseitin variable was not yet added to the assumptions, but represents a top-level clause.
Tseitin variables for top-level clauses are only assumed lazily if they occur in another clause.
Definition at line 610 of file SATModule.h.
The documentation for this class was generated from the following files:
smtrat-modules/SATModule/SATModule.h
smtrat-modules/SATModule/SATModule.cpp