SMT-RAT: smtrat::UFModel Class Reference
smtrat::UFModel Class Reference
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
#include <UFModel.h>
Public Member Functions
UFModel (const carl::UninterpretedFunction &uf)
UFModel (const UFModel &_ufm)
Constructs a model of an uninterpreted function by copying the given one.
bool extend (const std::vector< SortValue > &_args, const SortValue &_value)
SortValue get (const std::vector< SortValue > &_args) const
std::size_t getHash () const
bool operator== (const UFModel &_ufm) const
bool operator< (const UFModel &_ufm) const
Private Attributes
carl::UninterpretedFunction uf
K keys
STL member.
T elements
STL member.
Friends
std::ostream & operator<< (std::ostream &_os, const UFModel &_ufm)
Prints the given uninterpreted function model on the given output stream.
Detailed Description
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
Definition at line 21 of file UFModel.h.
Constructor & Destructor Documentation
smtrat::UFModel::UFModel (const carl::UninterpretedFunction & uf) inline
Definition at line 27 of file UFModel.h.
smtrat::UFModel::UFModel (const UFModel & _ufm) inline
Constructs a model of an uninterpreted function by copying the given one.
Parameters
_sortValue The mode of an uninterpreted function to copy.
Definition at line 35 of file UFModel.h.
Member Function Documentation
bool smtrat::UFModel::extend (const std::vector< SortValue > & _args, const SortValue & _value)
Definition at line 14 of file UFModel.cpp.
Referenced by smtrat::EQPreprocessingModule< Settings >::P_update_model(), and smtrat::EQModule< Settings >::P_update_model_function().
SortValue smtrat::UFModel::get (const std::vector< SortValue > & _args) const
Definition at line 20 of file UFModel.cpp.
Referenced by smtrat::EQModule< Settings >::P_check_model_extension().
size_t smtrat::UFModel::getHash () const
Definition at line 30 of file UFModel.cpp.
Referenced by std::hash< smtrat::UFModel >::operator()().
bool smtrat::UFModel::operator< (const UFModel & _ufm) const
Parameters
_ufm The uninterpreted function model to compare with.
Returns
true, if this uninterpreted function model is less than the given one.
Definition at line 59 of file UFModel.cpp.
bool smtrat::UFModel::operator== (const UFModel & _ufm) const
Parameters
_ufm The uninterpreted function model to compare with.
Returns
true, if this uninterpreted function model equals the given one.
Definition at line 43 of file UFModel.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & _os, const UFModel & _ufm) friend
Prints the given uninterpreted function model on the given output stream.
Parameters
_os The output stream to print on.
_ufm The uninterpreted function model to print.
Returns
The output stream after printing the given uninterpreted function model on it.
Definition at line 79 of file UFModel.cpp.
Field Documentation
T std::map< K, T >::elements inherited
STL member.
K std::map< K, T >::keys inherited
STL member.
carl::UninterpretedFunction smtrat::UFModel::uf private
Definition at line 24 of file UFModel.h.
Referenced by get(), and smtrat::operator<<().
The documentation for this class was generated from the following files:
lib/datastructures/UFModel.h
lib/datastructures/UFModel.cpp