SMT-RAT: delta::Settings Class Reference
delta::Settings Class Reference
This class loads and checks the command line options with help of boost::program_options.
#include <Settings.h>
Public Member Functions
Settings (const std::string &executable)
Constructor.
bool load (int argc, char *argv[])
Load options from command line.
template<typename T >
const T & as (const std::string &s) const
Get option with given name as a given type.
template<typename T >
void set (const std::string &s, const T &t)
Set option with given name as a given type.
bool has (const std::string &s) const
Checks if there is an option with this name.
bool isDefault (const std::string &s) const
Check if the option with the given name was set due to its default value.
Private Attributes
std::string executable
Name of this executable.
bpo::variables_map vm
Parsed options.
bpo::options_description desc
Options description.
bpo::positional_options_description pd
Positional options description.
Friends
std::ostream & operator<< (std::ostream &os, const Settings &s)
Streaming operator.
Detailed Description
This class loads and checks the command line options with help of boost::program_options.
Definition at line 27 of file Settings.h.
Constructor & Destructor Documentation
Settings()
delta::Settings::Settings (const std::string & executable) inline
Constructor.
Parameters
executable Name of this binary.
Definition at line 41 of file Settings.h.
Member Function Documentation
as()
template<typename T > const T& delta::Settings::as (const std::string & s) const inline
Get option with given name as a given type.
If there is no such option of it has a different type, exceptions may be thrown.
Parameters
s Name of the option.
Returns
Value of the option as type T.
Definition at line 112 of file Settings.h.
Referenced by delta::Producer::operator()().
has()
bool delta::Settings::has (const std::string & s) const inline
Checks if there is an option with this name.
Parameters
s Name of the option.
Returns
If option was set.
Definition at line 132 of file Settings.h.
Referenced by as(), isDefault(), delta::Producer::operator()(), delta::Producer::process(), delta::Producer::Producer(), and set().
isDefault()
bool delta::Settings::isDefault (const std::string & s) const inline
Check if the option with the given name was set due to its default value.
If there is no such option exceptions may be thrown.
Parameters
s Name of the option.
Returns
Whether it's value was set as the default.
Definition at line 141 of file Settings.h.
load()
bool delta::Settings::load (int argc, char * argv[]) inline
Load options from command line.
Parameters
argc Number of arguments.
argv Content of arguments.
Definition at line 88 of file Settings.h.
set()
template<typename T > void delta::Settings::set (const std::string & s, const T & t) inline
Set option with given name as a given type.
If there is no such option exceptions may be thrown.
Parameters
s Name of the option.
t New value.
Definition at line 123 of file Settings.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Settings & s) friend
Streaming operator.
Parameters
os Output stream.
s Settings.
Returns
os.
Definition at line 79 of file Settings.h.
The documentation for this class was generated from the following file:
delta/Settings.h