SMT-RAT: smtrat::vrw::VariableConstraintGraph Class Reference
smtrat::vrw::VariableConstraintGraph Class Reference
#include <VariableConstraintGraph.h>
Public Member Functions
VariableConstraintGraph ()
std::list< ConstraintNode * > addConstraint (const ConstraintT *constraint, FormulaT::const_iterator origin, FormulaT::iterator pos)
Add a constraint to the graph.
std::list< ConstraintNode * > updateConstraintNode (ConstraintNode *node, FormulaT::iterator pos)
A given constraint was removed before but now has to be reconsidered.
bool removeConstraint (std::list< ConstraintNode * >::iterator, FormulaT::const_iterator end)
Removing a constraint from the graph.
void assertConstraints ()
Set all constraints to "asserted".
std::list< ConstraintNode * >::iterator last ()
std::list< std::pair< FormulaT::iterator, bool > > findIrrelevantConstraints (FormulaT::iterator end)
Searching for variables which appear with odd degree in a constraint, as the corresponding constraint can be eliminated.
std::list< std::pair< FormulaT::iterator, bool > > findPurelyLinearComponents (FormulaT::iterator end)
void print ()
Print the graph.
virtual ~VariableConstraintGraph ()
Protected Attributes
std::map< std::string, VariableNode * > mVariableNodes
identifier -> node
std::list< ConstraintNode * > mConstraintNodes
std::set< VariableNode * > mSingleAppearingVariables
Detailed Description
Definition at line 44 of file VariableConstraintGraph.h.
Constructor & Destructor Documentation
smtrat::vrw::VariableConstraintGraph::VariableConstraintGraph ()
Definition at line 17 of file VariableConstraintGraph.cpp.
virtual smtrat::vrw::VariableConstraintGraph::~VariableConstraintGraph () inline virtual
Definition at line 65 of file VariableConstraintGraph.h.
Member Function Documentation
std::list< ConstraintNode * > smtrat::vrw::VariableConstraintGraph::addConstraint (const ConstraintT * constraint, FormulaT::const_iterator origin, FormulaT::iterator pos)
Add a constraint to the graph.
Parameters
constraint The constraint to be added
origin The iterator in the received formula
pos The iterator in the passed formula
Returns
A list of constraints which have to be reconsidered, as they have a variable which is not "single" anymore.
Definition at line 28 of file VariableConstraintGraph.cpp.
Referenced by smtrat::VRWModule::assertSubformula().
void smtrat::vrw::VariableConstraintGraph::assertConstraints ()
Set all constraints to "asserted".
Definition at line 181 of file VariableConstraintGraph.cpp.
Referenced by smtrat::VRWModule::isConsistent().
std::list< std::pair< FormulaT::iterator, bool > > smtrat::vrw::VariableConstraintGraph::findIrrelevantConstraints (FormulaT::iterator end)
Searching for variables which appear with odd degree in a constraint, as the corresponding constraint can be eliminated.
Parameters
end An iterator to passedFormula->end
Returns
Definition at line 137 of file VariableConstraintGraph.cpp.
Referenced by smtrat::VRWModule::isConsistent().
std::list<std::pair<FormulaT::iterator, bool> > smtrat::vrw::VariableConstraintGraph::findPurelyLinearComponents (FormulaT::iterator end)
std::list<ConstraintNode*>::iterator smtrat::vrw::VariableConstraintGraph::last (void) inline
Definition at line 60 of file VariableConstraintGraph.h.
Referenced by smtrat::VRWModule::assertSubformula().
void smtrat::vrw::VariableConstraintGraph::print ()
Print the graph.
You find a list of constraint nodes with outgoing edges and then a list of variable nodes with outgoing edges.
Definition at line 192 of file VariableConstraintGraph.cpp.
bool smtrat::vrw::VariableConstraintGraph::removeConstraint (std::list< ConstraintNode * >::iterator constraintNode, FormulaT::const_iterator end)
Removing a constraint from the graph.
Parameters
constraintNode The node to be removed.
end An iterator to passedFormula->end
Returns
Whether the formula has to be removed.
Definition at line 107 of file VariableConstraintGraph.cpp.
Referenced by smtrat::VRWModule::removeSubformula().
std::list< ConstraintNode * > smtrat::vrw::VariableConstraintGraph::updateConstraintNode (ConstraintNode * node, FormulaT::iterator pos)
A given constraint was removed before but now has to be reconsidered.
Parameters
node The node of the constraint.
pos The position in the passed formula where it can be found now.
Returns
A list of constraints which have to be reconsidered, as they have a variable which is not "single" anymore.
Definition at line 73 of file VariableConstraintGraph.cpp.
Referenced by smtrat::VRWModule::assertSubformula().
Field Documentation
std::list<ConstraintNode*> smtrat::vrw::VariableConstraintGraph::mConstraintNodes protected
Definition at line 49 of file VariableConstraintGraph.h.
Referenced by addConstraint(), assertConstraints(), print(), and removeConstraint().
std::set<VariableNode*> smtrat::vrw::VariableConstraintGraph::mSingleAppearingVariables protected
Definition at line 50 of file VariableConstraintGraph.h.
Referenced by addConstraint(), findIrrelevantConstraints(), removeConstraint(), and updateConstraintNode().
std::map<std::string,VariableNode*> smtrat::vrw::VariableConstraintGraph::mVariableNodes protected
identifier -> node
Definition at line 48 of file VariableConstraintGraph.h.
Referenced by addConstraint(), findIrrelevantConstraints(), print(), and updateConstraintNode().
The documentation for this class was generated from the following files:
lib/modules/VRWModule/VariableConstraintGraph.h
lib/modules/VRWModule/VariableConstraintGraph.cpp