SMT-RAT: StrategyGraph Class Reference
StrategyGraph Class Reference
Data Structures
class UnsupportedStrategyGraphOperationException
Public Member Functions
StrategyGraph ()
boolean addEdge (Edge edge, Vertex fromVertex, Vertex toVertex)
boolean addEdge (Edge edge, Vertex fromVertex, Vertex toVertex, EdgeType type) throws UnsupportedStrategyGraphOperationException
Edge getEdge (Point2D point)
Vertex getRoot ()
Edge getPredecesssorEdge (Edge edge)
Edge getPredecesssorEdge (Vertex vertex)
void pushPriority (Edge edge1, Edge edge2) throws UnsupportedStrategyGraphOperationException
void removeEdge (Edge edge)
void removeVertex (Vertex vertex)
Static Public Attributes
static final String ROOT_VERTEX_MODULE_NAME
static int priorityAllocator
Private Member Functions
void clearUpPriorities ()
void collectHigherPriorityEdges (ArrayList< Edge > edgeList, Edge edge, int lowerBound, int upperBound)
boolean hasPath (Vertex fromVertex, Vertex toVertex)
void removeNotConnectedVertices (Vertex vertex)
Private Attributes
final Vertex rootVertex
Detailed Description
Definition at line 16 of file StrategyGraph.java.
Constructor & Destructor Documentation
StrategyGraph.StrategyGraph () inline
Definition at line 24 of file StrategyGraph.java.
Member Function Documentation
boolean StrategyGraph.addEdge (Edge edge, Vertex fromVertex, Vertex toVertex) inline
Definition at line 32 of file StrategyGraph.java.
Referenced by EditingGraphMousePlugin.mouseReleased().
boolean StrategyGraph.addEdge (Edge edge, Vertex fromVertex, Vertex toVertex, EdgeType type) throws UnsupportedStrategyGraphOperationException inline
Definition at line 42 of file StrategyGraph.java.
void StrategyGraph.clearUpPriorities () inline private
Definition at line 171 of file StrategyGraph.java.
Referenced by removeEdge(), and removeVertex().
void StrategyGraph.collectHigherPriorityEdges (ArrayList< Edge > edgeList, Edge edge, int lowerBound, int upperBound) inline private
Definition at line 183 of file StrategyGraph.java.
Referenced by pushPriority().
Edge StrategyGraph.getEdge (Point2D point) inline
Definition at line 59 of file StrategyGraph.java.
Referenced by GUI.GUI(), and EditingGraphMousePlugin.mouseReleased().
Edge StrategyGraph.getPredecesssorEdge (Edge edge) inline
Definition at line 76 of file StrategyGraph.java.
Edge StrategyGraph.getPredecesssorEdge (Vertex vertex) inline
Definition at line 81 of file StrategyGraph.java.
Vertex StrategyGraph.getRoot () inline
Definition at line 71 of file StrategyGraph.java.
Referenced by IOTools.manageSolvers(), and EditingGraphMousePlugin.mouseReleased().
boolean StrategyGraph.hasPath (Vertex fromVertex, Vertex toVertex) inline private
Definition at line 193 of file StrategyGraph.java.
Referenced by addEdge(), pushPriority(), removeEdge(), and removeNotConnectedVertices().
void StrategyGraph.pushPriority (Edge edge1, Edge edge2) throws UnsupportedStrategyGraphOperationException inline
Definition at line 93 of file StrategyGraph.java.
void StrategyGraph.removeEdge (Edge edge) inline
Definition at line 150 of file StrategyGraph.java.
void StrategyGraph.removeNotConnectedVertices (Vertex vertex) inline private
Definition at line 213 of file StrategyGraph.java.
Referenced by removeEdge(), and removeVertex().
void StrategyGraph.removeVertex (Vertex vertex) inline
Definition at line 165 of file StrategyGraph.java.
Field Documentation
int StrategyGraph.priorityAllocator static
Definition at line 22 of file StrategyGraph.java.
Referenced by addEdge(), clearUpPriorities(), Edge.Edge(), and StrategyGraph().
final String StrategyGraph.ROOT_VERTEX_MODULE_NAME static
Definition at line 18 of file StrategyGraph.java.
Referenced by IOTools.createGraph(), and StrategyGraph().
final Vertex StrategyGraph.rootVertex private
Definition at line 20 of file StrategyGraph.java.
Referenced by getRoot(), removeEdge(), removeNotConnectedVertices(), and StrategyGraph().
The documentation for this class was generated from the following file:
gui/StrategyGraph.java