SMT-RAT: smtrat::LRAModuleStatistics Class Reference
smtrat::LRAModuleStatistics Class Reference
#include <LRAModuleStatistics.h>
Public Member Functions
void collect ()
void pivotStep ()
void check (const ModuleInput &_formula)
void add (const ConstraintT &)
void remove (const ConstraintT &)
void addConflict (const std::vector< FormulasT > &_infSubSets)
void addDeduction ()
void addRefinement ()
void setTableauSize (size_t _size)
void setNumberOfTableauxEntries (size_t _num)
LRAModuleStatistics (const std::string &_name)
~LRAModuleStatistics ()
void print (std::ostream &_out=std::cout, bool _smtlib=false, size_t _maxNameLength=0, size_t _maxKeyLength=0)
void generateXML (std::stringstream &filestream)
size_t maxKeyLength () const
const std::string & name () const
Protected Member Functions
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
Private Attributes
size_t mPivotingSteps
size_t mCurrentPivotingSteps
size_t mMostPivotingStepsInACheck
size_t mChecksWithPivoting
size_t mTableauxSize
size_t mTableauEntries
size_t mRefinements
size_t mConflicts
size_t mAllConflictsSizes
size_t mDeductions
size_t mChecks
size_t mAllChecksSizes
Detailed Description
Definition at line 32 of file LRAModuleStatistics.h.
Constructor & Destructor Documentation
smtrat::LRAModuleStatistics::LRAModuleStatistics (const std::string & _name) inline
Definition at line 123 of file LRAModuleStatistics.h.
smtrat::LRAModuleStatistics::~LRAModuleStatistics () inline
Definition at line 139 of file LRAModuleStatistics.h.
Member Function Documentation
void smtrat::LRAModuleStatistics::add (const ConstraintT &) inline
Definition at line 86 of file LRAModuleStatistics.h.
void smtrat::LRAModuleStatistics::addConflict (const std::vector< FormulasT > & _infSubSets) inline
Definition at line 94 of file LRAModuleStatistics.h.
void smtrat::LRAModuleStatistics::addDeduction () inline
Definition at line 103 of file LRAModuleStatistics.h.
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 97 of file Statistics.h.
Referenced by smtrat::Statistics::addKeyValuePair(), smtrat::CADStatistics::collect(), smtrat::GBCalculationStats::collect(), smtrat::GeneralStatistics::collect(), smtrat::SATModuleStatistics::collect(), smtrat::GroebnerModuleStats::collect(), smtrat::FouMoStatistics::collect(), smtrat::BVStatistics::collect(), smtrat::ReduceCNFStatistics::collect(), smtrat::IntEqStatistics::collect(), and collect().
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 104 of file Statistics.h.
void smtrat::LRAModuleStatistics::addRefinement () inline
Definition at line 108 of file LRAModuleStatistics.h.
void smtrat::LRAModuleStatistics::check (const ModuleInput & _formula) inline
Definition at line 73 of file LRAModuleStatistics.h.
void smtrat::LRAModuleStatistics::collect () inline virtual
Reimplemented from smtrat::Statistics.
Definition at line 50 of file LRAModuleStatistics.h.
void smtrat::Statistics::generateXML (std::stringstream & filestream) inline inherited
Definition at line 70 of file Statistics.h.
size_t smtrat::Statistics::maxKeyLength () const inline inherited
Definition at line 80 of file Statistics.h.
const std::string& smtrat::Statistics::name () const inline inherited
Definition at line 85 of file Statistics.h.
void smtrat::LRAModuleStatistics::pivotStep () inline
Definition at line 67 of file LRAModuleStatistics.h.
void smtrat::Statistics::print (std::ostream & _out = std::cout, bool _smtlib = false, size_t _maxNameLength = 0, size_t _maxKeyLength = 0) inline inherited
Definition at line 36 of file Statistics.h.
void smtrat::LRAModuleStatistics::remove (const ConstraintT &) inline
Definition at line 90 of file LRAModuleStatistics.h.
void smtrat::LRAModuleStatistics::setNumberOfTableauxEntries (size_t _num) inline
Definition at line 118 of file LRAModuleStatistics.h.
void smtrat::LRAModuleStatistics::setTableauSize (size_t _size) inline
Definition at line 113 of file LRAModuleStatistics.h.
Field Documentation
size_t smtrat::LRAModuleStatistics::mAllChecksSizes private
Definition at line 47 of file LRAModuleStatistics.h.
size_t smtrat::LRAModuleStatistics::mAllConflictsSizes private
Definition at line 44 of file LRAModuleStatistics.h.
size_t smtrat::LRAModuleStatistics::mChecks private
Definition at line 46 of file LRAModuleStatistics.h.
Referenced by check().
size_t smtrat::LRAModuleStatistics::mChecksWithPivoting private
Definition at line 39 of file LRAModuleStatistics.h.
Referenced by check().
size_t smtrat::LRAModuleStatistics::mConflicts private
Definition at line 43 of file LRAModuleStatistics.h.
Referenced by addConflict().
size_t smtrat::LRAModuleStatistics::mCurrentPivotingSteps private
Definition at line 37 of file LRAModuleStatistics.h.
Referenced by check(), and pivotStep().
size_t smtrat::LRAModuleStatistics::mDeductions private
Definition at line 45 of file LRAModuleStatistics.h.
Referenced by addDeduction().
size_t smtrat::LRAModuleStatistics::mMostPivotingStepsInACheck private
Definition at line 38 of file LRAModuleStatistics.h.
size_t smtrat::LRAModuleStatistics::mPivotingSteps private
Definition at line 36 of file LRAModuleStatistics.h.
Referenced by pivotStep().
size_t smtrat::LRAModuleStatistics::mRefinements private
Definition at line 42 of file LRAModuleStatistics.h.
Referenced by addRefinement().
size_t smtrat::LRAModuleStatistics::mTableauEntries private
Definition at line 41 of file LRAModuleStatistics.h.
size_t smtrat::LRAModuleStatistics::mTableauxSize private
Definition at line 40 of file LRAModuleStatistics.h.
The documentation for this class was generated from the following file:
lib/modules/LRAModule/LRAModuleStatistics.h