SMT-RAT: smtrat::SATModuleStatistics Class Reference
smtrat::SATModuleStatistics Class Reference
#include <SATModuleStatistics.h>
Public Member Functions
SATModuleStatistics (const std::string &_name)
~SATModuleStatistics ()
void collect ()
void lemmaLearned ()
void initialTrue ()
void propagate ()
void decide ()
void restart ()
size_t & rNrClauses ()
size_t & rNrTotalVariables ()
void print (std::ostream &_out=std::cout, bool _smtlib=false, size_t _maxNameLength=0, size_t _maxKeyLength=0)
void generateXML (std::stringstream &filestream)
size_t maxKeyLength () const
const std::string & name () const
Protected Member Functions
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
Private Attributes
size_t mNrTotalVariables
size_t mNrClauses
size_t mNrLearnedLemmas
size_t mVarsWithPolarityTrue
size_t mPropagations
size_t mRestarts
size_t mDecisions
Detailed Description
Definition at line 17 of file SATModuleStatistics.h.
Constructor & Destructor Documentation
smtrat::SATModuleStatistics::SATModuleStatistics (const std::string & _name) inline
Definition at line 30 of file SATModuleStatistics.h.
smtrat::SATModuleStatistics::~SATModuleStatistics () inline
Definition at line 41 of file SATModuleStatistics.h.
Member Function Documentation
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 97 of file Statistics.h.
Referenced by smtrat::Statistics::addKeyValuePair(), smtrat::CADStatistics::collect(), smtrat::GBCalculationStats::collect(), smtrat::GeneralStatistics::collect(), collect(), smtrat::GroebnerModuleStats::collect(), smtrat::FouMoStatistics::collect(), smtrat::BVStatistics::collect(), smtrat::ReduceCNFStatistics::collect(), smtrat::IntEqStatistics::collect(), and smtrat::LRAModuleStatistics::collect().
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 104 of file Statistics.h.
void smtrat::SATModuleStatistics::collect () inline virtual
Reimplemented from smtrat::Statistics.
Definition at line 43 of file SATModuleStatistics.h.
void smtrat::SATModuleStatistics::decide () inline
Definition at line 69 of file SATModuleStatistics.h.
void smtrat::Statistics::generateXML (std::stringstream & filestream) inline inherited
Definition at line 70 of file Statistics.h.
void smtrat::SATModuleStatistics::initialTrue () inline
Definition at line 59 of file SATModuleStatistics.h.
void smtrat::SATModuleStatistics::lemmaLearned () inline
Definition at line 54 of file SATModuleStatistics.h.
size_t smtrat::Statistics::maxKeyLength () const inline inherited
Definition at line 80 of file Statistics.h.
const std::string& smtrat::Statistics::name () const inline inherited
Definition at line 85 of file Statistics.h.
void smtrat::Statistics::print (std::ostream & _out = std::cout, bool _smtlib = false, size_t _maxNameLength = 0, size_t _maxKeyLength = 0) inline inherited
Definition at line 36 of file Statistics.h.
void smtrat::SATModuleStatistics::propagate () inline
Definition at line 64 of file SATModuleStatistics.h.
void smtrat::SATModuleStatistics::restart () inline
Definition at line 74 of file SATModuleStatistics.h.
size_t& smtrat::SATModuleStatistics::rNrClauses () inline
Definition at line 79 of file SATModuleStatistics.h.
size_t& smtrat::SATModuleStatistics::rNrTotalVariables () inline
Definition at line 84 of file SATModuleStatistics.h.
Field Documentation
size_t smtrat::SATModuleStatistics::mDecisions private
Definition at line 27 of file SATModuleStatistics.h.
Referenced by decide().
size_t smtrat::SATModuleStatistics::mNrClauses private
Definition at line 22 of file SATModuleStatistics.h.
Referenced by rNrClauses().
size_t smtrat::SATModuleStatistics::mNrLearnedLemmas private
Definition at line 23 of file SATModuleStatistics.h.
Referenced by lemmaLearned().
size_t smtrat::SATModuleStatistics::mNrTotalVariables private
Definition at line 21 of file SATModuleStatistics.h.
Referenced by rNrTotalVariables().
size_t smtrat::SATModuleStatistics::mPropagations private
Definition at line 25 of file SATModuleStatistics.h.
Referenced by propagate().
size_t smtrat::SATModuleStatistics::mRestarts private
Definition at line 26 of file SATModuleStatistics.h.
Referenced by restart().
size_t smtrat::SATModuleStatistics::mVarsWithPolarityTrue private
Definition at line 24 of file SATModuleStatistics.h.
Referenced by initialTrue().
The documentation for this class was generated from the following file:
lib/modules/SATModule/SATModuleStatistics.h