SMT-RAT: smtrat::vs::State Class Reference
smtrat::vs::State Class Reference
Public Types
enum Type { TEST_CANDIDATE_TO_GENERATE, SUBSTITUTION_TO_APPLY, COMBINE_SUBRESULTS }
typedef carl::FastPointerMapB< Substitution, ConditionSetSetSet > ConflictSets
typedef std::vector< std::pair< ConditionList, bool > > SubstitutionResult
typedef std::vector< SubstitutionResult > SubstitutionResults
typedef std::vector< std::pair< unsigned, unsigned > > SubResultCombination
typedef smtrat::vb::VariableBounds< const Condition * > VariableBoundsCond
Public Member Functions
State (carl::IDPool *_conditionIdAllocator, bool _withVariableBounds)
Constructs an empty state (no conditions yet) being the root (hence neither a substitution) of the state tree which is going to be formed when applying the satisfiability check based on virtual substitution.
State (State *const _father, const Substitution &_substitution, carl::IDPool *_conditionIdAllocator, bool _withVariableBounds)
Constructs a state being a child of the given state and containing the given substitution, which maps from the index variable of the given state.
State (const State &)=delete
~State ()
Destructor.
bool isRoot () const
bool cannotBeSolved (bool _lazy) const
bool & rCannotBeSolved ()
bool & rCannotBeSolvedLazy ()
bool markedAsDeleted () const
bool & rMarkedAsDeleted ()
bool hasChildrenToInsert () const
bool & rHasChildrenToInsert ()
carl::Variable::Arg index () const
size_t valuation () const
size_t backendCallValuation () const
size_t id () const
size_t & rID ()
std::list< State * > & rChildren ()
const std::list< State * > & children () const
State * pFather () const
const State & father () const
State & rFather ()
ConflictSets & rConflictSets ()
const ConflictSets & conflictSets () const
bool & rHasRecentlyAddedConditions ()
bool hasRecentlyAddedConditions () const
bool & rInconsistent ()
bool isInconsistent () const
ConditionList & rConditions ()
const ConditionList & conditions () const
Substitution & rSubstitution ()
const Substitution & substitution () const
SubstitutionResults & rSubstitutionResults ()
const SubstitutionResults & substitutionResults () const
SubResultCombination & rSubResultCombination ()
const SubResultCombination & subResultCombination () const
const Substitution * pSubstitution () const
bool conditionsSimplified () const
bool subResultsSimplified () const
bool & rSubResultsSimplified ()
bool takeSubResultCombAgain () const
bool & rTakeSubResultCombAgain ()
bool tryToRefreshIndex () const
bool hasSubResultsCombination () const
bool hasSubstitutionResults () const
bool unfinished () const
Type type () const
Type & rType ()
const Condition * pOriginalCondition () const
const Condition & originalCondition () const
const carl::PointerSet< Condition > & tooHighDegreeConditions () const
carl::PointerSet< Condition > & rTooHighDegreeConditions ()
const VariableBoundsCond & variableBounds () const
VariableBoundsCond & rVariableBounds ()
void setOriginalCondition (const Condition *_pOCondition)
Sets the pointer of the original condition of this state to the given pointer to a condition.
size_t currentRangeSize () const
void resetCurrentRangeSize ()
const smtrat::Rational & minIntTestCandidate () const
const smtrat::Rational & maxIntTestCandidate () const
bool hasInfinityChild () const
void resetInfinityChild (const State *_state)
void setInfinityChild (State *_state)
void resetCannotBeSolvedLazyFlags ()
unsigned treeDepth () const
bool substitutionApplicable () const
Checks if a substitution can be applied.
bool substitutionApplicable (const smtrat::ConstraintT &_constraint) const
Checks if the substitution of this state can be applied to the given constraint.
bool hasNoninvolvedCondition () const
Checks whether a condition exists, which was not involved in an elimination step.
bool allTestCandidatesInvalidated (const Condition *_condition) const
bool hasChildWithID () const
Checks whether a child exists, which has no ID (!=0).
bool containsState (const State *_state) const
bool hasOnlyInconsistentChildren () const
Checks whether a child exists, which is not yet marked as inconsistent.
bool occursInEquation (const carl::Variable &) const
Checks whether the given variable occurs in a equation.
bool hasFurtherUncheckedTestCandidates () const
Checks whether there exist more than one test candidate, which has still not been checked.
void variables (carl::Variables &_variables) const
Finds the variables, which occur in this state.
unsigned numberOfNodes () const
Determines the number of nodes in the tree with this state as root.
State & root ()
bool getNextIntTestCandidate (smtrat::Rational &_nextIntTestCandidate, size_t _maxIntRange)
bool updateIntTestCandidates ()
bool unfinishedAncestor (State *&_unfinAnt)
Determines (if it exists) a ancestor node, which is unfinished, that is it has still substitution results to consider.
bool bestCondition (const Condition *&_bestCondition, size_t _numberOfAllVariables, bool _preferEquation)
Determines the most adequate condition and in it the most adequate variable in the state to generate test candidates for.
ConditionList::iterator constraintExists (const smtrat::ConstraintT &_constraint)
Checks if the given constraint already exists as condition in the state.
void simplify (ValuationMap &_ranking)
Cleans up all conditions in this state according to comparison between the corresponding constraints.
bool simplify (ConditionList &_conditionVectorToSimplify, ConditionSetSet &_conflictSet, ValuationMap &_ranking, bool _stateConditions=false)
Simplifies the given conditions according to comparison between the corresponding constraints.
void setIndex (const carl::Variable &_index)
Sets the index of this state.
void addConflictSet (const Substitution *_substitution, ConditionSetSet &&_condSetSet)
Adds a conflict set to the map of substitutions to conflict sets.
void addConflicts (const Substitution *_substitution, ConditionSetSet &&_condSetSet)
Adds all conflicts to all sets of the conflict set of the given substitution.
void resetConflictSets ()
Clears the conflict sets.
bool updateOCondsOfSubstitutions (const Substitution &_substitution, std::vector< State *> &_reactivatedStates)
Updates the original conditions of substitutions having the same test candidate as the given.
void addSubstitutionResults (std::vector< DisjunctionOfConditionConjunctions > &&_disjunctionsOfCondConj)
Adds the given substitution results to this state.
bool extendSubResultCombination ()
Extends the currently considered combination of conjunctions in the substitution results.
bool nextSubResultCombination ()
If the state contains a substitution result, which is a conjunction of disjunctions of conjunctions of conditions, this method sets the current combination to the disjunctions to the next combination.
size_t getNumberOfCurrentSubresultCombination () const
ConditionList getCurrentSubresultCombination () const
Gets the current substitution result combination as condition vector.
bool refreshConditions (ValuationMap &_ranking)
Determines the condition vector corresponding to the current combination of the conjunctions of conditions.
void initConditionFlags ()
Sets all flags of the conditions to true, if it contains the variable given by the states index.
bool initIndex (const carl::Variables &_allVariables, const smtrat::VariableValuationStrategy &_vvstrat, bool _preferEquation, bool _tryDifferentVarOrder=false, bool _useFixedVariableOrder=false)
Sets, if it has not already happened, the index of the state to the name of the most adequate variable.
void bestConstraintValuation (const std::vector< std::pair< carl::Variable, std::multiset< double >>> &_varVals)
void averageConstraintValuation (const std::vector< std::pair< carl::Variable, std::multiset< double >>> &_varVals)
void worstConstraintValuation (const std::vector< std::pair< carl::Variable, std::multiset< double >>> &_varVals)
void addCondition (const smtrat::ConstraintT &_constraint, const carl::PointerSet< Condition > &_originalConditions, size_t _valutation, bool _recentlyAdded, ValuationMap &_ranking)
Adds a constraint to the conditions of this state.
bool checkSubresultCombinations () const
This is just for debug purpose.
int deleteOrigins (carl::PointerSet< Condition > &_originsToDelete, ValuationMap &_ranking)
Removes everything in this state originated by the given vector of conditions.
void deleteOriginsFromChildren (carl::PointerSet< Condition > &_originsToDelete, ValuationMap &_ranking)
Deletes everything originated by the given conditions in the children of this state.
void deleteOriginsFromConflictSets (carl::PointerSet< Condition > &_originsToDelete, bool _originsAreCurrentConditions)
Deletes everything originated by the given conditions in the conflict sets of this state.
void deleteOriginsFromSubstitutionResults (carl::PointerSet< Condition > &_originsToDelete)
Deletes everything originated by the given conditions in the substitution results of this state.
void deleteConditions (carl::PointerSet< Condition > &_conditionsToDelete, ValuationMap &_ranking)
Delete everything originated by the given conditions from the entire subtree with this state as root.
std::vector< State * > addChild (const Substitution &_substitution)
Adds a state as child to this state with the given substitution.
void updateValuation (bool _lazy)
Updates the valuation of this state.
void updateBackendCallValuation ()
Valuates the state's currently considered conditions according to a backend call.
void passConflictToFather (bool _checkConflictForSideCondition, bool _useBackjumping=true, bool _includeInconsistentTestCandidates=false)
Passes the original conditions of the covering set of the conflicts of this state to its father.
bool hasLocalConflict ()
Checks whether the currently considered conditions, which have been considered for test candidate construction, form already a conflict.
bool checkTestCandidatesForBounds ()
Checks whether the test candidate of this state is valid against the variable intervals in the father of this state.
std::vector< smtrat::DoubleInterval > solutionSpace (carl::PointerSet< Condition > &_conflictReason) const
Determines the solution space of the test candidate of this state regarding to the variable bounds of the father.
bool hasRootsInVariableBounds (const Condition *_condition, bool _useSturmSequence)
Checks whether there are no zeros for the left-hand side of the constraint of the given condition.
void print (const std::string _initiation="***", std::ostream &_out=std::cout) const
Prints the conditions, the substitution and the substitution results of this state and all its children.
void printAlone (const std::string="***", std::ostream &_out=std::cout) const
Prints the conditions, the substitution and the substitution results of this state.
void printConditions (const std::string _initiation="***", std::ostream &_out=std::cout, bool=false) const
Prints the conditions of this state.
void printSubstitutionResults (const std::string _initiation="***", std::ostream &_out=std::cout) const
Prints the substitution results of this state.
void printSubstitutionResultCombination (const std::string _initiation="***", std::ostream &_out=std::cout) const
Prints the combination of substitution results used in this state.
void printSubstitutionResultCombinationAsNumbers (const std::string _initiation="***", std::ostream &_out=std::cout) const
Prints the combination of substitution results, expressed in numbers, used in this state.
void printConflictSets (const std::string _initiation="***", std::ostream &_out=std::cout) const
Prints the conflict sets of this state.
Static Public Member Functions
static void removeStatesFromRanking (const State &toRemove, ValuationMap &_ranking)
static size_t coveringSet (const ConditionSetSetSet &_conflictSets, carl::PointerSet< Condition > &_minCovSet, unsigned _currentTreeDepth)
Finds a covering set of a vector of sets of sets due to some heuristics.
Private Attributes
bool mConditionsSimplified
A flag indicating whether the conditions this state considers are simplified.
bool mHasChildrenToInsert
A flag indicating whether there are states that are children of this state and must be still considered in the further progress of finding a solution.
bool mHasRecentlyAddedConditions
A flag that indicates whether this state has conditions in its considered list of conditions, which were recently added and, hence, must be propagated further.
bool mInconsistent
A flag that indicates whether this state is already inconsistent.
bool mMarkedAsDeleted
A flag indicating whether this state has already marked as deleted, which means that there is no need to consider it in the further progress of finding a solution.
bool mSubResultsSimplified
A flag indicating whether the substitution results this state are simplified.
bool mTakeSubResultCombAgain
A flag indicating whether to take the current combination of substitution results once again.
bool mTestCandidateCheckedForBounds
A flag indicating whether the test candidate contained by this state has already been check for the bounds of the variables.
bool mCannotBeSolved
A flag indicating whether this state has been progressed until a point where a condition must be involved having a too high degree to tackle with virtual substitution.
bool mCannotBeSolvedLazy
bool mTryToRefreshIndex
A flag indicating whether the index (the variable to eliminate in this state) should be reconsidered and maybe changed.
size_t mBackendCallValuation
A heuristically determined value stating the expected difficulty of this state's considered conditions to be solved by a backend.
size_t mID
A unique id identifying this state.
size_t mValuation
A heuristically determined value stating the expected difficulty of this state's considered conditions to be solved by virtual substitution.
Type mType
The type of this state, which states whether this state has still a substitution to apply or either test candidates shall be generated or a new combination of the substitution results must be found in order to consider it next.
carl::Variable mIndex
The variable which is going to be eliminated from this state's considered conditions.
const Condition * mpOriginalCondition
If the test candidate considered by this state stems from a condition for which it is enough to consider it only for test candidate generation for finding the satisfiability of the conditions it occurs in, this member stores that condition.
State * mpFather
The father state of this state.
Substitution * mpSubstitution
The substitution this state considers. Note that it is NULL if this state is the root.
SubstitutionResults * mpSubstitutionResults
The vector storing the substitution results, that is for each application of the substitution in this state to one of its considered conditions a disjunction of conjunctions of constraints.
SubResultCombination * mpSubResultCombination
The currently considered combination of conjunctions of constraints in the substitution result vector, which form the currently considered conditions of this state (store in mpConditions).
ConditionList * mpConditions
The currently considered conditions of this state, for which the satisfiability must be checked.
ConflictSets * mpConflictSets
Stores for each already considered and failed test candidate all conflicts which have been found for it.
std::list< State *> * mpChildren
The children states of this state.
carl::PointerSet< Condition > * mpTooHighDegreeConditions
The conditions of this state, which cannot be solved by the virtual substitution.
VariableBoundsCond * mpVariableBounds
A pointer to an object which manages and stores the bounds on the variables occurring in this state.
State * mpInfinityChild
smtrat::Rational mMinIntTestCanidate
smtrat::Rational mMaxIntTestCanidate
size_t mCurrentIntRange
carl::IDPool * mpConditionIdAllocator
std::vector< std::pair< carl::Variable, std::multiset< double > > > mRealVarVals
std::vector< std::pair< carl::Variable, std::multiset< double > > > mIntVarVals
std::vector< size_t > mBestVarVals
Detailed Description
Definition at line 65 of file State.h.
Constructor & Destructor Documentation
State() [1/2]
smtrat::vs::State::State (carl::IDPool * _conditionIdAllocator, bool _withVariableBounds)
Constructs an empty state (no conditions yet) being the root (hence neither a substitution) of the state tree which is going to be formed when applying the satisfiability check based on virtual substitution.
Parameters
_withVariableBounds A flag that indicates whether to use optimizations based on variable bounds.
Definition at line 26 of file State.cpp.
Referenced by addChild().
State() [2/2]
smtrat::vs::State::State (State *const _father, const Substitution & _substitution, carl::IDPool * _conditionIdAllocator, bool _withVariableBounds)
Constructs a state being a child of the given state and containing the given substitution, which maps from the index variable of the given state.
Parameters
_father The father of the state to be constructed.
_substitution The substitution of the state to be constructed.
_withVariableBounds A flag that indicates whether to use optimizations based on variable bounds.
Definition at line 66 of file State.cpp.
Member Function Documentation
addChild()
std::vector< State * > smtrat::vs::State::addChild (const Substitution & _substitution)
Adds a state as child to this state with the given substitution.
Parameters
_substitution The substitution to generate the state for.
Returns
true, if a state has been added as child to this state; false, otherwise.
Definition at line 1953 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::eliminate().
addCondition()
void smtrat::vs::State::addCondition (const smtrat::ConstraintT & _constraint, const carl::PointerSet< Condition > & _originalConditions, size_t _valutation, bool _recentlyAdded, ValuationMap & _ranking)
Adds a constraint to the conditions of this state.
Parameters
_constraint The constraint of the condition to add.
_originalConditions The original conditions of the condition to add.
_valutation The valuation of the condition to add.
_recentlyAdded Is the condition a recently added one. The state can obtain a new condition.
Definition at line 1434 of file State.cpp.
Referenced by refreshConditions(), and simplify().
addConflicts()
void smtrat::vs::State::addConflicts (const Substitution * _substitution, ConditionSetSet && _condSetSet)
Adds all conflicts to all sets of the conflict set of the given substitution.
Parameters
_substitution The corresponding substitution generated the conflict. (NULL in the case a detected conflict without substitution)
_condSetSet The conflicts to add.
Definition at line 835 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::eliminate(), and smtrat::VSModule< Settings >::substituteAll().
addConflictSet()
void smtrat::vs::State::addConflictSet (const Substitution * _substitution, ConditionSetSet && _condSetSet)
Adds a conflict set to the map of substitutions to conflict sets.
Parameters
_substitution The corresponding substitution generated the conflict. (NULL in the case a detected conflict without substitution)
_condSetSet The conflicts to add.
Definition at line 814 of file State.cpp.
Referenced by checkTestCandidatesForBounds(), hasLocalConflict(), hasRootsInVariableBounds(), passConflictToFather(), smtrat::VSModule< Settings >::runBackendSolvers(), and simplify().
addSubstitutionResults()
void smtrat::vs::State::addSubstitutionResults (std::vector< DisjunctionOfConditionConjunctions > && _disjunctionsOfCondConj)
Adds the given substitution results to this state.
Parameters
_disjunctionsOfCondConj The substitution results given by a vector of disjunctions of conjunctions of conditions.
Definition at line 911 of file State.cpp.
Referenced by addChild(), and smtrat::VSModule< Settings >::substituteAll().
allTestCandidatesInvalidated()
bool smtrat::vs::State::allTestCandidatesInvalidated (const Condition * _condition) const
Parameters
A condition, which is one of the currently considered constraints to check for satisfiability.
Returns
true, if all test candidates provided by the given condition are no solution of the currently considered conjunction of constraints to check for satisfiability.
Definition at line 226 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::adaptPassedFormula().
backendCallValuation()
size_t smtrat::vs::State::backendCallValuation () const inline
Returns
The valuation of the state's considered conditions for a possible backend call.
Definition at line 300 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), and smtrat::VSModule< Settings >::removeStateFromRanking().
bestCondition()
bool smtrat::vs::State::bestCondition (const Condition *& _bestCondition, size_t _numberOfAllVariables, bool _preferEquation)
Determines the most adequate condition and in it the most adequate variable in the state to generate test candidates for.
Parameters
_bestCondition The most adequate condition to be the next test candidate provider.
_numberOfAllVariables The number of all globally known variables.
_preferEquation A flag that indicates to prefer equations in the heuristics of this method.
Returns
true, if it has a condition and a variable in it to generate test candidates for; false, otherwise.
Definition at line 394 of file State.cpp.
cannotBeSolved()
bool smtrat::vs::State::cannotBeSolved (bool _lazy) const inline
Returns
A constant reference to the flag indicating whether a condition with too high degree for the virtual substitution method must be considered.
Definition at line 219 of file State.h.
Referenced by smtrat::VSModule< Settings >::insertTooHighDegreeStatesInRanking(), and printAlone().
checkSubresultCombinations()
bool smtrat::vs::State::checkSubresultCombinations () const
This is just for debug purpose.
Returns
true, if no subresult combination is illegal.
Definition at line 1491 of file State.cpp.
checkTestCandidatesForBounds()
bool smtrat::vs::State::checkTestCandidatesForBounds ()
Checks whether the test candidate of this state is valid against the variable intervals in the father of this state.
Returns
true, if the test candidate of this state is valid against the variable intervals; false, otherwise.
Definition at line 2293 of file State.cpp.
children()
const std::list<State*>& smtrat::vs::State::children () const inline
Returns
A constant reference to the vector of the children of this state.
Definition at line 332 of file State.h.
Referenced by addCondition(), allTestCandidatesInvalidated(), containsState(), deleteOriginsFromChildren(), deleteOriginsFromConflictSets(), smtrat::VSModule< Settings >::eliminate(), hasChildWithID(), hasFurtherUncheckedTestCandidates(), hasOnlyInconsistentChildren(), numberOfNodes(), passConflictToFather(), print(), smtrat::VSModule< Settings >::propagateNewConditions(), smtrat::VSModule< Settings >::removeStatesFromRanking(), smtrat::VSModule< Settings >::substituteAll(), updateOCondsOfSubstitutions(), and ~State().
conditions()
const ConditionList& smtrat::vs::State::conditions () const inline
Returns
A constant reference to the currently considered conditions of this state.
Definition at line 423 of file State.h.
Referenced by smtrat::VSModule< Settings >::adaptPassedFormula(), bestCondition(), constraintExists(), deleteConditions(), deleteOrigins(), smtrat::VSModule< Settings >::eliminate(), hasFurtherUncheckedTestCandidates(), hasLocalConflict(), hasNoninvolvedCondition(), initConditionFlags(), initIndex(), smtrat::VSModule< Settings >::logConditions(), occursInEquation(), passConflictToFather(), printConditions(), smtrat::VSModule< Settings >::propagateNewConditions(), refreshConditions(), smtrat::VSModule< Settings >::substituteAll(), substitutionApplicable(), updateBackendCallValuation(), updateValuation(), variables(), and ~State().
conditionsSimplified()
bool smtrat::vs::State::conditionsSimplified () const inline
Returns
true, if the considered conditions of this state are already simplified.
Definition at line 495 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStatesToRanking(), smtrat::VSModule< Settings >::addStateToRanking(), printAlone(), and simplify().
conflictSets()
const ConflictSets& smtrat::vs::State::conflictSets () const inline
Returns
A constant reference to the conflict sets of this state.
Definition at line 372 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), deleteOriginsFromChildren(), hasLocalConflict(), passConflictToFather(), and printConflictSets().
constraintExists()
ConditionList::iterator smtrat::vs::State::constraintExists (const smtrat::ConstraintT & _constraint)
Checks if the given constraint already exists as condition in the state.
Parameters
_constraint The constraint, for which we want to know, if it already exists as condition in the state.
Returns
An iterator to the condition, which involves the constraint or an iterator to the end of the vector of conditions of this state.
Definition at line 431 of file State.cpp.
containsState()
bool smtrat::vs::State::containsState (const State * _state) const
Returns
true, if the given state is a node in the state tree starting at this node; false, otherwise.
Definition at line 251 of file State.cpp.
coveringSet()
size_t smtrat::vs::State::coveringSet (const ConditionSetSetSet & _conflictSets, carl::PointerSet< Condition > & _minCovSet, unsigned _currentTreeDepth) static
Finds a covering set of a vector of sets of sets due to some heuristics.
Parameters
_conflictSets The vector of sets of sets, for which the method finds all minimum covering sets.
_minCovSet The found mininum covering set.
_currentTreeDepth The tree depth of the state from which this method is invoked.
Returns
The greatest level, where a condition of the covering set has been created.
Definition at line 2813 of file State.cpp.
Referenced by passConflictToFather().
deleteConditions()
void smtrat::vs::State::deleteConditions (carl::PointerSet< Condition > & _conditionsToDelete, ValuationMap & _ranking)
Delete everything originated by the given conditions from the entire subtree with this state as root.
Parameters
_conditionsToDelete The conditions to delete.
Definition at line 1606 of file State.cpp.
Referenced by refreshConditions(), and simplify().
deleteOrigins()
int smtrat::vs::State::deleteOrigins (carl::PointerSet< Condition > & _originsToDelete, ValuationMap & _ranking)
Removes everything in this state originated by the given vector of conditions.
Parameters
_originsToDelete The conditions for which everything in this state which has been originated by them must be removed.
Returns
0, if this state got invalid and must be deleted afterwards; -1, if this state got invalid and must be deleted afterwards and made other states unnecessary to consider; 1, otherwise.
Definition at line 1506 of file State.cpp.
deleteOriginsFromChildren()
void smtrat::vs::State::deleteOriginsFromChildren (carl::PointerSet< Condition > & _originsToDelete, ValuationMap & _ranking)
Deletes everything originated by the given conditions in the children of this state.
Parameters
_originsToDelete The condition for which to delete everything originated by them.
Definition at line 1678 of file State.cpp.
Referenced by deleteConditions(), and deleteOrigins().
deleteOriginsFromConflictSets()
void smtrat::vs::State::deleteOriginsFromConflictSets (carl::PointerSet< Condition > & _originsToDelete, bool _originsAreCurrentConditions)
Deletes everything originated by the given conditions in the conflict sets of this state.
Parameters
_originsToDelete The condition for which to delete everything originated by them.
_originsAreCurrentConditions A flag indicating whether the origins to remove stem from conditions of the currently considered condition vector of the father of this state and not, e.g., from somewhere in its substitution results.
Definition at line 1710 of file State.cpp.
Referenced by deleteConditions(), and deleteOrigins().
deleteOriginsFromSubstitutionResults()
void smtrat::vs::State::deleteOriginsFromSubstitutionResults (carl::PointerSet< Condition > & _originsToDelete)
Deletes everything originated by the given conditions in the substitution results of this state.
Parameters
_originsToDelete The conditions for which to delete everything originated by them.
Definition at line 1842 of file State.cpp.
Referenced by deleteOrigins().
father()
const State& smtrat::vs::State::father () const inline
Returns
A constant reference to the father of this state. This method fails if this state is the root.
Definition at line 348 of file State.h.
Referenced by checkTestCandidatesForBounds(), passConflictToFather(), solutionSpace(), and smtrat::VSModule< Settings >::substituteAll().
getCurrentSubresultCombination()
ConditionList smtrat::vs::State::getCurrentSubresultCombination () const
Gets the current substitution result combination as condition vector.
Returns
The current substitution result combination as condition vector.
Definition at line 1075 of file State.cpp.
Referenced by refreshConditions().
getNumberOfCurrentSubresultCombination()
size_t smtrat::vs::State::getNumberOfCurrentSubresultCombination () const
Returns
The number of the current substitution result combination.
Definition at line 1048 of file State.cpp.
hasChildrenToInsert()
bool smtrat::vs::State::hasChildrenToInsert () const inline
Returns
A constant reference to the flag indicating whether there are states that are children of this state and must be still considered in the further progress of finding a solution.
Definition at line 264 of file State.h.
hasChildWithID()
bool smtrat::vs::State::hasChildWithID () const
Checks whether a child exists, which has no ID (!=0).
Returns
true, if there exists a child with ID (!=0); false, otherwise.
Definition at line 238 of file State.cpp.
hasFurtherUncheckedTestCandidates()
bool smtrat::vs::State::hasFurtherUncheckedTestCandidates () const
Checks whether there exist more than one test candidate, which has still not been checked.
Returns
true, if there exist more than one test candidate, which has still not been checked; false, otherwise.
Definition at line 281 of file State.cpp.
hasLocalConflict()
bool smtrat::vs::State::hasLocalConflict ()
Checks whether the currently considered conditions, which have been considered for test candidate construction, form already a conflict.
Returns
true, if they form a conflict; false, otherwise.
Definition at line 2197 of file State.cpp.
hasNoninvolvedCondition()
bool smtrat::vs::State::hasNoninvolvedCondition () const
Checks whether a condition exists, which was not involved in an elimination step.
Returns
true, if there exists a condition in the state, which was not already involved in an elimination step; false, otherwise.
Definition at line 213 of file State.cpp.
hasOnlyInconsistentChildren()
bool smtrat::vs::State::hasOnlyInconsistentChildren () const
Checks whether a child exists, which is not yet marked as inconsistent.
Returns
true, if there exists such a child; false, otherwise.
Definition at line 260 of file State.cpp.
Referenced by hasLocalConflict().
hasRecentlyAddedConditions()
bool smtrat::vs::State::hasRecentlyAddedConditions () const inline
Returns
true, if this state has a recently added condition in its considered conditions.
Definition at line 389 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStatesToRanking(), printAlone(), and updateValuation().
hasRootsInVariableBounds()
bool smtrat::vs::State::hasRootsInVariableBounds (const Condition * _condition, bool _useSturmSequence)
Checks whether there are no zeros for the left-hand side of the constraint of the given condition.
Parameters
_condition The condition to check.
A flag that indicates whether to include Sturm's sequences and root counting in this method.
Returns
true, if the constraint of the left-hand side of the given condition has no roots in the variable bounds of this state; false, otherwise.
Definition at line 2419 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::eliminate().
hasSubResultsCombination()
bool smtrat::vs::State::hasSubResultsCombination () const inline
Returns
true, if this state has a substitution result combination.
Definition at line 545 of file State.h.
Referenced by checkSubresultCombinations(), deleteOriginsFromSubstitutionResults(), getCurrentSubresultCombination(), getNumberOfCurrentSubresultCombination(), nextSubResultCombination(), passConflictToFather(), printSubstitutionResultCombination(), and simplify().
hasSubstitutionResults()
bool smtrat::vs::State::hasSubstitutionResults () const inline
Returns
true, if this state has substitution results.
Definition at line 553 of file State.h.
Referenced by checkSubresultCombinations(), deleteOriginsFromSubstitutionResults(), printSubstitutionResultCombination(), printSubstitutionResultCombinationAsNumbers(), printSubstitutionResults(), and simplify().
id()
size_t smtrat::vs::State::id () const inline
Returns
The id of this state.
Definition at line 308 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), and smtrat::VSModule< Settings >::removeStateFromRanking().
index()
carl::Variable::Arg smtrat::vs::State::index () const inline
Returns
A constant reference to the variable which is going to be eliminated from this state's considered conditions. Note, if there is no variable decided to be eliminated, this method will fail.
Definition at line 283 of file State.h.
Referenced by addChild(), addCondition(), bestCondition(), deleteConditions(), deleteOrigins(), deleteOriginsFromChildren(), hasRootsInVariableBounds(), initConditionFlags(), initIndex(), passConflictToFather(), printAlone(), smtrat::VSModule< Settings >::propagateNewConditions(), and updateOCondsOfSubstitutions().
initIndex()
bool smtrat::vs::State::initIndex (const carl::Variables & _allVariables, const smtrat::VariableValuationStrategy & _vvstrat, bool _preferEquation, bool _tryDifferentVarOrder = false, bool _useFixedVariableOrder = false)
Sets, if it has not already happened, the index of the state to the name of the most adequate variable.
Which variable is taken depends on heuristics.
Parameters
_allVariables All globally known variables.
_vvstrat The strategy according which we choose the variable.
_preferEquation A flag that indicates to prefer equations in the heuristics of this method.
_tryDifferentVarOrder
Definition at line 1187 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::propagateNewConditions().
isInconsistent()
bool smtrat::vs::State::isInconsistent () const inline
Returns
true if this state's considered conditions are inconsistent; false, otherwise, which does not necessarily mean that this state is consistent.
Definition at line 407 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), smtrat::VSModule< Settings >::eliminate(), passConflictToFather(), printAlone(), smtrat::VSModule< Settings >::substituteAll(), and updateValuation().
isRoot()
bool smtrat::vs::State::isRoot () const inline
Returns
The root of the state tree where this state is part from.
Definition at line 210 of file State.h.
Referenced by checkTestCandidatesForBounds(), deleteOrigins(), printAlone(), smtrat::VSModule< Settings >::runBackendSolvers(), solutionSpace(), smtrat::VSModule< Settings >::substituteAll(), substitutionApplicable(), unfinishedAncestor(), smtrat::VSModule< Settings >::updateModel(), and updateValuation().
markedAsDeleted()
bool smtrat::vs::State::markedAsDeleted () const inline
Returns
A constant reference to the flag indicating whether this state is marked as deleted, which means that there is no need to consider it in the further progress of finding a solution.
Definition at line 246 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), and printAlone().
nextSubResultCombination()
bool smtrat::vs::State::nextSubResultCombination ()
If the state contains a substitution result, which is a conjunction of disjunctions of conjunctions of conditions, this method sets the current combination to the disjunctions to the next combination.
Returns
true, if there is a next combination; false, otherwise.
Definition at line 988 of file State.cpp.
numberOfNodes()
unsigned smtrat::vs::State::numberOfNodes () const
Determines the number of nodes in the tree with this state as root.
Returns
The number of nodes in the tree with this state as root.
Definition at line 302 of file State.cpp.
occursInEquation()
bool smtrat::vs::State::occursInEquation (const carl::Variable & _variable) const
Checks whether the given variable occurs in a equation.
Returns
true, if the given variable occurs in a equation; false, otherwise.
Definition at line 273 of file State.cpp.
originalCondition()
const Condition& smtrat::vs::State::originalCondition () const inline
Returns
A reference to the original conditions of this state. Note that if there is no such condition, this method fails. For further information see the description of the corresponding member.
Definition at line 600 of file State.h.
Referenced by passConflictToFather(), and printAlone().
passConflictToFather()
void smtrat::vs::State::passConflictToFather (bool _checkConflictForSideCondition, bool _useBackjumping = true, bool _includeInconsistentTestCandidates = false)
Passes the original conditions of the covering set of the conflicts of this state to its father.
Parameters
_checkConflictForSideCondition If this flag is set to false it might save some computations but leads to an over-approximative behavior. Recommendation: set it to true.
_includeInconsistentTestCandidates If this flag is set to true the conflict analysis takes also the invalid test candidates' conflict sets into account. Recommendation: set it to false.
_useBackjumping If true, we use the backjumping technique.
Definition at line 2078 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::runBackendSolvers().
pFather()
State* smtrat::vs::State::pFather () const inline
Returns
A pointer to the father of this state. It is NULL if this state is the root.
Definition at line 340 of file State.h.
Referenced by smtrat::VSModule< Settings >::checkAnswer(), checkTestCandidatesForBounds(), root(), smtrat::VSModule< Settings >::runBackendSolvers(), smtrat::VSModule< Settings >::substituteAll(), treeDepth(), unfinishedAncestor(), and smtrat::VSModule< Settings >::updateModel().
pOriginalCondition()
const Condition* smtrat::vs::State::pOriginalCondition () const inline
Returns
A pointer to the original condition of this state or NULL, if there is no such condition. For further information see the description of the corresponding member.
Definition at line 591 of file State.h.
Referenced by deleteOrigins(), passConflictToFather(), printAlone(), smtrat::VSModule< Settings >::propagateNewConditions(), and smtrat::VSModule< Settings >::substituteAll().
print()
void smtrat::vs::State::print (const std::string _initiation = "***", std::ostream & _out = std::cout) const
Prints the conditions, the substitution and the substitution results of this state and all its children.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2566 of file State.cpp.
Referenced by smtrat::VSModule< Settings >::substituteAll().
printAlone()
void smtrat::vs::State::printAlone (const std::string _initiation = "***", std::ostream & _out = std::cout) const
Prints the conditions, the substitution and the substitution results of this state.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2576 of file State.cpp.
Referenced by hasLocalConflict(), and print().
printConditions()
void smtrat::vs::State::printConditions (const std::string _initiation = "***", std::ostream & _out = std::cout, bool _onlyAsConstraints = false) const
Prints the conditions of this state.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2662 of file State.cpp.
Referenced by printAlone().
printConflictSets()
void smtrat::vs::State::printConflictSets (const std::string _initiation = "***", std::ostream & _out = std::cout) const
Prints the conflict sets of this state.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2745 of file State.cpp.
Referenced by printAlone().
printSubstitutionResultCombination()
void smtrat::vs::State::printSubstitutionResultCombination (const std::string _initiation = "***", std::ostream & _out = std::cout) const
Prints the combination of substitution results used in this state.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2708 of file State.cpp.
Referenced by printAlone().
printSubstitutionResultCombinationAsNumbers()
void smtrat::vs::State::printSubstitutionResultCombinationAsNumbers (const std::string _initiation = "***", std::ostream & _out = std::cout) const
Prints the combination of substitution results, expressed in numbers, used in this state.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2731 of file State.cpp.
printSubstitutionResults()
void smtrat::vs::State::printSubstitutionResults (const std::string _initiation = "***", std::ostream & _out = std::cout) const
Prints the substitution results of this state.
Parameters
_initiation A string which is printed in the beginning of every row.
_out The stream to print on.
Definition at line 2676 of file State.cpp.
Referenced by printAlone(), and smtrat::VSModule< Settings >::substituteAll().
pSubstitution()
const Substitution* smtrat::vs::State::pSubstitution () const inline
Returns
A pointer to the substitution of this state, which is NULL, if this state is the root.
Definition at line 487 of file State.h.
Referenced by addCondition(), checkTestCandidatesForBounds(), passConflictToFather(), and smtrat::VSModule< Settings >::substituteAll().
rCannotBeSolved()
bool& smtrat::vs::State::rCannotBeSolved () inline
Returns
A reference to the flag indicating whether a condition with too high degree for the virtual substitution method must be considered.
Definition at line 228 of file State.h.
Referenced by smtrat::VSModule< Settings >::substituteAll().
rCannotBeSolvedLazy()
bool& smtrat::vs::State::rCannotBeSolvedLazy () inline
Returns
A reference to the flag indicating whether a condition with too high degree for the virtual substitution method must be considered.
Definition at line 237 of file State.h.
rChildren()
std::list<State*>& smtrat::vs::State::rChildren () inline
Returns
A reference to the vector of the children of this state.
Definition at line 324 of file State.h.
Referenced by addChild(), deleteOriginsFromChildren(), deleteOriginsFromConflictSets(), smtrat::VSModule< Settings >::eliminate(), passConflictToFather(), smtrat::VSModule< Settings >::removeStatesFromRanking(), smtrat::VSModule< Settings >::substituteAll(), updateOCondsOfSubstitutions(), and ~State().
rConditions()
ConditionList& smtrat::vs::State::rConditions () inline
Returns
A reference to the currently considered conditions of this state.
Definition at line 415 of file State.h.
Referenced by addCondition(), bestCondition(), constraintExists(), deleteConditions(), deleteOrigins(), smtrat::VSModule< Settings >::eliminate(), initConditionFlags(), passConflictToFather(), smtrat::VSModule< Settings >::propagateNewConditions(), refreshConditions(), simplify(), smtrat::VSModule< Settings >::substituteAll(), and ~State().
rConflictSets()
ConflictSets& smtrat::vs::State::rConflictSets () inline
Returns
A reference to the conflict sets of this state.
Definition at line 364 of file State.h.
Referenced by deleteOriginsFromChildren(), passConflictToFather(), and smtrat::VSModule< Settings >::substituteAll().
refreshConditions()
bool smtrat::vs::State::refreshConditions (ValuationMap & _ranking)
Determines the condition vector corresponding to the current combination of the conjunctions of conditions.
Returns
true, if there has been a change in the currently considered condition vector. false, otherwise.
Definition at line 1092 of file State.cpp.
rFather()
State& smtrat::vs::State::rFather () inline
Returns
A reference to the father of this state. This method fails if this state is the root.
Definition at line 356 of file State.h.
Referenced by passConflictToFather(), smtrat::VSModule< Settings >::runBackendSolvers(), and smtrat::VSModule< Settings >::substituteAll().
rHasChildrenToInsert()
bool& smtrat::vs::State::rHasChildrenToInsert () inline
Returns
A reference to the flag indicating whether there are states that are children of this state and must be still considered in the further progress of finding a solution.
Definition at line 273 of file State.h.
rHasRecentlyAddedConditions()
bool& smtrat::vs::State::rHasRecentlyAddedConditions () inline
Returns
A reference to the flag indicating that this state has a recently added condition in its considered conditions.
Definition at line 381 of file State.h.
Referenced by passConflictToFather().
rID()
size_t& smtrat::vs::State::rID () inline
Returns
A reference to the id of this state.
Definition at line 316 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), and smtrat::VSModule< Settings >::removeStateFromRanking().
rInconsistent()
bool& smtrat::vs::State::rInconsistent () inline
Returns
A reference to the flag indicating whether this state's considered conditions are inconsistent. Note that if it is false, it does not necessarily mean that this state is consistent.
Definition at line 398 of file State.h.
Referenced by addConflictSet(), deleteOriginsFromConflictSets(), smtrat::VSModule< Settings >::eliminate(), hasRootsInVariableBounds(), passConflictToFather(), refreshConditions(), simplify(), and smtrat::VSModule< Settings >::substituteAll().
rMarkedAsDeleted()
bool& smtrat::vs::State::rMarkedAsDeleted () inline
Returns
A reference to the flag indicating whether this state is marked as deleted, which means that there is no need to consider it in the further progress of finding a solution.
Definition at line 255 of file State.h.
Referenced by passConflictToFather(), and smtrat::VSModule< Settings >::substituteAll().
root()
State & smtrat::vs::State::root ()
Returns
The root of the tree, in which this state is located.
Definition at line 310 of file State.cpp.
rSubResultCombination()
SubResultCombination& smtrat::vs::State::rSubResultCombination () inline
Returns
A reference to the current combination of conjunction of constraints within the substitution results of this state. Make sure that a substitution result combination exists when calling this method. (using, e.g., hasSubResultsCombination())
Definition at line 469 of file State.h.
Referenced by deleteOriginsFromSubstitutionResults(), and simplify().
rSubResultsSimplified()
bool& smtrat::vs::State::rSubResultsSimplified () inline
Returns
A reference to the flag indicating whether the substitution results of this state are already simplified.
Definition at line 511 of file State.h.
Referenced by deleteOriginsFromSubstitutionResults().
rSubstitution()
Substitution& smtrat::vs::State::rSubstitution () inline
Returns
A reference to the substitution this state considers. Note that this method fails, if this state is the root.
Definition at line 432 of file State.h.
Referenced by deleteOrigins().
rSubstitutionResults()
SubstitutionResults& smtrat::vs::State::rSubstitutionResults () inline
Returns
A reference to the substitution results of this state. Make sure that the substitution results exist when calling this method. (using, e.g., hasSubstitutionResults())
Definition at line 450 of file State.h.
Referenced by deleteOriginsFromSubstitutionResults().
rTakeSubResultCombAgain()
bool& smtrat::vs::State::rTakeSubResultCombAgain () inline
Returns
A reference to the flag indicating whether the current substitution result combination has to be consider once again before considering the next one.
Definition at line 529 of file State.h.
Referenced by passConflictToFather().
rTooHighDegreeConditions()
carl::PointerSet<Condition>& smtrat::vs::State::rTooHighDegreeConditions () inline
Returns
A reference to the conditions of those this state currently considers, which have a too high degree to be tackled of the virtual substitution method.
Definition at line 618 of file State.h.
Referenced by smtrat::VSModule< Settings >::eliminate().
rType()
Type& smtrat::vs::State::rType () inline
Returns
A constant reference to the type of this state: This state has still a substitution to apply or either test candidates shall be generated or a new combination of the substitution results must be found in order to consider it next.
Definition at line 582 of file State.h.
Referenced by addChild(), and passConflictToFather().
rVariableBounds()
VariableBoundsCond& smtrat::vs::State::rVariableBounds () inline
Returns
A reference to the object managing and storing the variable's bounds which were extracted from the currently considered conditions of this state.
Definition at line 637 of file State.h.
Referenced by smtrat::VSModule< Settings >::substituteAll().
setIndex()
void smtrat::vs::State::setIndex (const carl::Variable & _index)
Sets the index of this state.
Parameters
_index The string to which the index should be set.
Definition at line 808 of file State.cpp.
Referenced by initIndex().
setOriginalCondition()
void smtrat::vs::State::setOriginalCondition (const Condition * _pOCondition) inline
Sets the pointer of the original condition of this state to the given pointer to a condition.
Parameters
_pOCondition The pointer to set the original condition to.
Definition at line 647 of file State.h.
simplify()
bool smtrat::vs::State::simplify (ConditionList & _conditionVectorToSimplify, ConditionSetSet & _conflictSet, ValuationMap & _ranking, bool _stateConditions = false)
Simplifies the given conditions according to comparison between the corresponding constraints.
Parameters
_conditionVectorToSimplify The conditions to simplify. Note, that this method can change these conditions.
_conflictSet All conflicts this method detects in the given conditions are stored in here.
_stateConditions A flag indicating whether the conditions to simplify are from the considered condition vector of this state and not, e.g., from somewhere in its substitution results.
Returns
true, if the conditions are not obviously conflicting; false, otherwise.
Definition at line 582 of file State.cpp.
solutionSpace()
std::vector< smtrat::DoubleInterval > smtrat::vs::State::solutionSpace (carl::PointerSet< Condition > & _conflictReason) const
Determines the solution space of the test candidate of this state regarding to the variable bounds of the father.
The solution space consists of one or two disjoint intervals.
Parameters
_conflictReason If the solution space is empty, the conditions being responsible for this conflict are stored in here.
Returns
The disjoint intervals representing the solution space.
Definition at line 2320 of file State.cpp.
Referenced by checkTestCandidatesForBounds(), and hasRootsInVariableBounds().
subResultCombination()
const SubResultCombination& smtrat::vs::State::subResultCombination () const inline
Returns
A constant reference to the current combination of conjunction of constraints within the substitution results of this state. Make sure that a substitution result combination exists when calling this method. (using, e.g., hasSubResultsCombination())
Definition at line 479 of file State.h.
Referenced by deleteOriginsFromSubstitutionResults(), passConflictToFather(), and simplify().
subResultsSimplified()
bool smtrat::vs::State::subResultsSimplified () const inline
Returns
true, if the substitution results of this state are already simplified.
Definition at line 503 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStatesToRanking(), extendSubResultCombination(), printAlone(), and simplify().
substitution()
const Substitution& smtrat::vs::State::substitution () const inline
Returns
A constant reference to the substitution this state considers. Note that this method fails, if this state is the root.
Definition at line 441 of file State.h.
Referenced by checkTestCandidatesForBounds(), deleteOrigins(), passConflictToFather(), printAlone(), solutionSpace(), smtrat::VSModule< Settings >::substituteAll(), substitutionApplicable(), smtrat::VSModule< Settings >::updateModel(), and updateValuation().
substitutionApplicable() [1/2]
bool smtrat::vs::State::substitutionApplicable () const
Checks if a substitution can be applied.
Returns
true, if a substitution can be applied. false, else.
Definition at line 193 of file State.cpp.
substitutionApplicable() [2/2]
bool smtrat::vs::State::substitutionApplicable (const smtrat::ConstraintT & _constraint) const
Checks if the substitution of this state can be applied to the given constraint.
Parameters
_constraint The constraint, for which we want to know, if the substitution is applicable.
Returns
true, if the substitution can be applied; false, otherwise.
Definition at line 205 of file State.cpp.
substitutionResults()
const SubstitutionResults& smtrat::vs::State::substitutionResults () const inline
Returns
A constant reference to the substitution results of this state. Make sure that the substitution results exist when calling this method. (using, e.g., hasSubstitutionResults())
Definition at line 459 of file State.h.
Referenced by deleteOriginsFromSubstitutionResults(), and passConflictToFather().
takeSubResultCombAgain()
bool smtrat::vs::State::takeSubResultCombAgain () const inline
Returns
true, if the current substitution result combination has to be consider once again before considering the next one.
Definition at line 520 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStatesToRanking(), nextSubResultCombination(), and printAlone().
tooHighDegreeConditions()
const carl::PointerSet<Condition>& smtrat::vs::State::tooHighDegreeConditions () const inline
Returns
A constant reference to the conditions of those this state currently considers, which have a too high degree to be tackled of the virtual substitution method.
Definition at line 609 of file State.h.
Referenced by allTestCandidatesInvalidated(), and hasLocalConflict().
treeDepth()
unsigned smtrat::vs::State::treeDepth () const
Returns
The depth of the subtree with this state as root node.
Definition at line 181 of file State.cpp.
Referenced by addChild(), passConflictToFather(), smtrat::VSModule< Settings >::substituteAll(), smtrat::VSModule< Settings >::updateModel(), and updateValuation().
tryToRefreshIndex()
bool smtrat::vs::State::tryToRefreshIndex () const inline
Returns
true, if the index variable of this state shall be recalculated.
Definition at line 537 of file State.h.
Referenced by printAlone().
type()
Type smtrat::vs::State::type () const inline
Returns
The type of this state: This state has still a substitution to apply or either test candidates shall be generated or a new combination of the substitution results must be found in order to consider it next.
Definition at line 572 of file State.h.
Referenced by addChild(), checkTestCandidatesForBounds(), deleteOriginsFromChildren(), nextSubResultCombination(), passConflictToFather(), printAlone(), refreshConditions(), solutionSpace(), and updateValuation().
unfinished()
bool smtrat::vs::State::unfinished () const inline
Returns
true, if the currently considered substitution result combination can be extended by taking further substitution results into account.
Definition at line 562 of file State.h.
Referenced by unfinishedAncestor().
unfinishedAncestor()
bool smtrat::vs::State::unfinishedAncestor (State *& _unfinAnt)
Determines (if it exists) a ancestor node, which is unfinished, that is it has still substitution results to consider.
Parameters
_unfinAnt The unfinished ancestor node.
Returns
true, if it has a unfinished ancestor; false, otherwise.
Definition at line 382 of file State.cpp.
updateBackendCallValuation()
void smtrat::vs::State::updateBackendCallValuation ()
Valuates the state's currently considered conditions according to a backend call.
Note: The settings are currently optimized for CAD backend calls.
Definition at line 2056 of file State.cpp.
Referenced by updateValuation().
updateOCondsOfSubstitutions()
bool smtrat::vs::State::updateOCondsOfSubstitutions (const Substitution & _substitution, std::vector< State *> & _reactivatedStates)
Updates the original conditions of substitutions having the same test candidate as the given.
Parameters
_substitution The substitution containing the test candidate to check for.
_reactivatedStates
Returns
true, if the test candidate of the given substitution was already generated; false, otherwise.
Definition at line 869 of file State.cpp.
Referenced by addChild().
valuation()
size_t smtrat::vs::State::valuation () const inline
Returns
The heuristically determined valuation of this state (see for the description of the corresponding member).
Definition at line 292 of file State.h.
Referenced by smtrat::VSModule< Settings >::addStateToRanking(), printAlone(), and smtrat::VSModule< Settings >::removeStateFromRanking().
variableBounds()
const VariableBoundsCond& smtrat::vs::State::variableBounds () const inline
Returns
A constant reference to the object managing and storing the variable's bounds which were extracted from the currently considered conditions of this state.
Definition at line 627 of file State.h.
Referenced by checkTestCandidatesForBounds(), hasRootsInVariableBounds(), solutionSpace(), and smtrat::VSModule< Settings >::substituteAll().
variables()
void smtrat::vs::State::variables (carl::Variables & _variables) const
Finds the variables, which occur in this state.
Parameters
_variables The variables which occur in this state.
Definition at line 294 of file State.cpp.
Field Documentation
mBackendCallValuation
size_t smtrat::vs::State::mBackendCallValuation private
A heuristically determined value stating the expected difficulty of this state's considered conditions to be solved by a backend.
The higher this value, the easier it should be to solve this state's considered conditions.
Definition at line 117 of file State.h.
Referenced by backendCallValuation(), and updateBackendCallValuation().
mCannotBeSolved
bool smtrat::vs::State::mCannotBeSolved private
A flag indicating whether this state has been progressed until a point where a condition must be involved having a too high degree to tackle with virtual substitution.
Note, that this flag is also set to true if heuristics decide that the combinatorial blow up using virtual substitution for the considered list of conditions of this state is too high. If this flag is set to true, it the state is delayed until a point where only such state remain and a backend must be involved.
Definition at line 108 of file State.h.
Referenced by addCondition(), addSubstitutionResults(), cannotBeSolved(), deleteConditions(), deleteOrigins(), printAlone(), rCannotBeSolved(), and updateValuation().
mHasChildrenToInsert
bool smtrat::vs::State::mHasChildrenToInsert private
A flag indicating whether there are states that are children of this state and must be still considered in the further progress of finding a solution.
Definition at line 84 of file State.h.
Referenced by hasChildrenToInsert(), and rHasChildrenToInsert().
mHasRecentlyAddedConditions
bool smtrat::vs::State::mHasRecentlyAddedConditions private
A flag that indicates whether this state has conditions in its considered list of conditions, which were recently added and, hence, must be propagated further.
Definition at line 87 of file State.h.
Referenced by addCondition(), deleteConditions(), deleteOrigins(), hasRecentlyAddedConditions(), and rHasRecentlyAddedConditions().
mInconsistent
bool smtrat::vs::State::mInconsistent private
A flag that indicates whether this state is already inconsistent.
Note that if it is set to false, it does not necessarily mean that this state is consistent.
Definition at line 90 of file State.h.
Referenced by deleteConditions(), deleteOrigins(), isInconsistent(), and rInconsistent().
mIndex
carl::Variable smtrat::vs::State::mIndex private
The variable which is going to be eliminated from this state's considered conditions.
That means, this variable won't occur in the children of this state.
Definition at line 131 of file State.h.
Referenced by index(), and setIndex().
mMarkedAsDeleted
bool smtrat::vs::State::mMarkedAsDeleted private
A flag indicating whether this state has already marked as deleted, which means that there is no need to consider it in the further progress of finding a solution.
Definition at line 93 of file State.h.
Referenced by addCondition(), addSubstitutionResults(), deleteConditions(), deleteOrigins(), markedAsDeleted(), and rMarkedAsDeleted().
mpChildren
std::list< State* >* smtrat::vs::State::mpChildren private
The children states of this state.
For each test candidate we generate for the conditions this state considers such a child is created.
Definition at line 153 of file State.h.
Referenced by addCondition(), children(), rChildren(), and ~State().
mpOriginalCondition
const Condition* smtrat::vs::State::mpOriginalCondition private
If the test candidate considered by this state stems from a condition for which it is enough to consider it only for test candidate generation for finding the satisfiability of the conditions it occurs in, this member stores that condition.
It is necessary, as it must be part of the origins (conditions in the father of this state) of any conflict found in this state.
Definition at line 136 of file State.h.
Referenced by originalCondition(), pOriginalCondition(), and setOriginalCondition().
mpSubResultCombination
SubResultCombination* smtrat::vs::State::mpSubResultCombination private
The currently considered combination of conjunctions of constraints in the substitution result vector, which form the currently considered conditions of this state (store in mpConditions).
Definition at line 146 of file State.h.
Referenced by checkSubresultCombinations(), extendSubResultCombination(), getCurrentSubresultCombination(), getNumberOfCurrentSubresultCombination(), hasSubResultsCombination(), nextSubResultCombination(), printSubstitutionResultCombination(), printSubstitutionResultCombinationAsNumbers(), rSubResultCombination(), simplify(), subResultCombination(), unfinished(), and ~State().
mpSubstitutionResults
SubstitutionResults* smtrat::vs::State::mpSubstitutionResults private
The vector storing the substitution results, that is for each application of the substitution in this state to one of its considered conditions a disjunction of conjunctions of constraints.
Definition at line 143 of file State.h.
Referenced by addSubstitutionResults(), checkSubresultCombinations(), extendSubResultCombination(), getCurrentSubresultCombination(), getNumberOfCurrentSubresultCombination(), hasSubstitutionResults(), nextSubResultCombination(), printSubstitutionResultCombination(), printSubstitutionResults(), refreshConditions(), rSubstitutionResults(), simplify(), substitutionResults(), unfinished(), and ~State().
mpVariableBounds
VariableBoundsCond* smtrat::vs::State::mpVariableBounds private
A pointer to an object which manages and stores the bounds on the variables occurring in this state.
These bounds are filtered from the conditions this state considers. Note that if we do not use optimizations based on variable bounds.
Definition at line 159 of file State.h.
Referenced by addChild(), addCondition(), deleteConditions(), deleteOrigins(), deleteOriginsFromConflictSets(), passConflictToFather(), printAlone(), rVariableBounds(), simplify(), variableBounds(), and ~State().
mTakeSubResultCombAgain
bool smtrat::vs::State::mTakeSubResultCombAgain private
A flag indicating whether to take the current combination of substitution results once again.
Definition at line 98 of file State.h.
Referenced by deleteOriginsFromSubstitutionResults(), nextSubResultCombination(), rTakeSubResultCombAgain(), simplify(), and takeSubResultCombAgain().
mTestCandidateCheckedForBounds
bool smtrat::vs::State::mTestCandidateCheckedForBounds private
A flag indicating whether the test candidate contained by this state has already been check for the bounds of the variables.
Definition at line 101 of file State.h.
Referenced by addCondition(), and checkTestCandidatesForBounds().
mTryToRefreshIndex
bool smtrat::vs::State::mTryToRefreshIndex private
A flag indicating whether the index (the variable to eliminate in this state) should be reconsidered and maybe changed.
Definition at line 113 of file State.h.
Referenced by deleteConditions(), deleteOrigins(), initIndex(), refreshConditions(), and tryToRefreshIndex().
mType
Type smtrat::vs::State::mType private
The type of this state, which states whether this state has still a substitution to apply or either test candidates shall be generated or a new combination of the substitution results must be found in order to consider it next.
Definition at line 128 of file State.h.
Referenced by addSubstitutionResults(), refreshConditions(), rType(), and type().
mValuation
size_t smtrat::vs::State::mValuation private
A heuristically determined value stating the expected difficulty of this state's considered conditions to be solved by virtual substitution.
The higher this value, the easier it should be to solve this state's considered conditions. Furthermore, this value enforces currently a depth first search, as a child has always a higher valuation than its father.
Definition at line 124 of file State.h.
Referenced by updateValuation(), and valuation().
The documentation for this class was generated from the following files:
smtrat-modules/VSModule/State.h
smtrat-modules/VSModule/State.cpp