SMT-RAT: smtrat::lra::Numeric Class Reference
smtrat::lra::Numeric Class Reference
Public Member Functions
Numeric ()
Default constructor.
Numeric (const Rational &)
Constructing from a Rational.
Numeric (int)
Constructing from an integer.
Numeric (unsigned int)
Constructing from an unsigned integer.
Numeric (long)
Constructing from a long integer.
Numeric (unsigned long)
Constructing from an unsigned long integer.
Numeric (const char *)
Constructing from a char array.
Numeric (const Numeric &)
Copy constructor.
const Rational & content () const
Rational & rContent ()
Numeric & operator= (int)
Cast from an integer.
Numeric & operator= (unsigned int)
Cast from an unsigned inteeger.
Numeric & operator= (long)
Cast from a long integer.
Numeric & operator= (unsigned long)
Cast from an unsigned long integer.
Numeric & operator= (const char *)
Cast from a char array.
Numeric & operator= (const Numeric &)
Cast from a char array.
bool operator== (const Numeric &) const
Compares whether this Numeric and the given one are equal.
bool operator!= (const Numeric &) const
Compares whether this Numeric and the given one are not equal.
bool operator< (const Numeric &) const
Compares whether this Numeric is less than the given one.
bool operator<= (const Numeric &) const
Compares whether this Numeric is less or equal than the given one.
bool operator> (const Numeric &) const
Compares whether this Numeric is greater than the given one.
bool operator>= (const Numeric &) const
Compares whether this Numeric is greater or equal than the given one.
Numeric numer () const
Numeric denom () const
Numeric floor () const
bool isPositive () const
Checks whether this Numeric corresponds to a positive rational number.
bool isNegative () const
bool isZero () const
bool isInteger () const
Private Attributes
Rational * mContent
Detailed Description
Definition at line 21 of file Numeric.h.
Constructor & Destructor Documentation
Numeric() [1/7]
smtrat::lra::Numeric::Numeric (const Rational & _value)
Constructing from a Rational.
Parameters
The Rational.
Definition at line 26 of file Numeric.cpp.
Numeric() [2/7]
smtrat::lra::Numeric::Numeric (int _value)
Constructing from an integer.
Parameters
_value The integer.
Definition at line 34 of file Numeric.cpp.
Numeric() [3/7]
smtrat::lra::Numeric::Numeric (unsigned int _value)
Constructing from an unsigned integer.
Parameters
_value The unsigned integer
Definition at line 42 of file Numeric.cpp.
Numeric() [4/7]
smtrat::lra::Numeric::Numeric (long _value)
Constructing from a long integer.
Parameters
_value The unsigned long integer.
Definition at line 50 of file Numeric.cpp.
Numeric() [5/7]
smtrat::lra::Numeric::Numeric (unsigned long _value)
Constructing from an unsigned long integer.
Parameters
_value The unsigned long integer.
Definition at line 58 of file Numeric.cpp.
Numeric() [6/7]
smtrat::lra::Numeric::Numeric (const char * _value)
Constructing from a char array.
Parameters
_value The char array.
Definition at line 66 of file Numeric.cpp.
Numeric() [7/7]
smtrat::lra::Numeric::Numeric (const Numeric & _value)
Copy constructor.
Parameters
_value The Numeric to copy.
Definition at line 74 of file Numeric.cpp.
Member Function Documentation
denom()
Numeric smtrat::lra::Numeric::denom () const
Returns
The denominator of this Numeric.
Definition at line 221 of file Numeric.cpp.
Referenced by isInteger().
floor()
Numeric smtrat::lra::Numeric::floor () const
Returns
The next smaller integer to this Numeric.
Definition at line 229 of file Numeric.cpp.
isInteger()
bool smtrat::lra::Numeric::isInteger () const
Returns
true, if this Numeric is integer; false, otherwise.
Definition at line 266 of file Numeric.cpp.
Referenced by smtrat::lra::gcd(), smtrat::lra::lcm(), and smtrat::lra::mod().
isNegative()
bool smtrat::lra::Numeric::isNegative () const
Returns
true, if this Numeric corresponds to a positive rational number; false, otherwise.
Definition at line 248 of file Numeric.cpp.
isPositive()
bool smtrat::lra::Numeric::isPositive () const
Checks whether this Numeric corresponds to a positive rational number.
Returns
True, if this Numeric corresponds to a positive rational number; False, otherwise.
Definition at line 239 of file Numeric.cpp.
isZero()
bool smtrat::lra::Numeric::isZero () const
Returns
true, if this Numeric corresponds to zero; false, otherwise.
Definition at line 257 of file Numeric.cpp.
Referenced by smtrat::lra::gcd(), smtrat::lra::lcm(), and smtrat::lra::mod().
numer()
Numeric smtrat::lra::Numeric::numer () const
Returns
The enumerator of this Numeric.
Definition at line 213 of file Numeric.cpp.
operator!=()
bool smtrat::lra::Numeric::operator!= (const Numeric & _value) const
Compares whether this Numeric and the given one are not equal.
Parameters
_value The Numeric to compare with.
Returns
True, if the two Numerics are not equal; False, otherwise.
Definition at line 161 of file Numeric.cpp.
operator<()
bool smtrat::lra::Numeric::operator< (const Numeric & _value) const
Compares whether this Numeric is less than the given one.
Parameters
_value The Numeric to compare with.
Returns
True, if this Numeric is less than the given one; False, otherwise.
Definition at line 172 of file Numeric.cpp.
operator<=()
bool smtrat::lra::Numeric::operator<= (const Numeric & _value) const
Compares whether this Numeric is less or equal than the given one.
Parameters
_value The Numeric to compare with.
Returns
True, if this Numeric is less or equal than the given one; False, otherwise.
Definition at line 183 of file Numeric.cpp.
operator=() [1/6]
Numeric & smtrat::lra::Numeric::operator= (int _value)
Cast from an integer.
Parameters
_value The integer.
Returns
The corresponding Numeric.
Definition at line 88 of file Numeric.cpp.
Referenced by operator=().
operator=() [2/6]
Numeric & smtrat::lra::Numeric::operator= (unsigned int _value)
Cast from an unsigned inteeger.
Parameters
_value The unsigned integer.
Returns
The corresponding Numeric.
Definition at line 98 of file Numeric.cpp.
operator=() [3/6]
Numeric & smtrat::lra::Numeric::operator= (long _value)
Cast from a long integer.
Parameters
_value The long integer.
Returns
The corresponding Numeric.
Definition at line 108 of file Numeric.cpp.
operator=() [4/6]
Numeric & smtrat::lra::Numeric::operator= (unsigned long _value)
Cast from an unsigned long integer.
Parameters
_value The unsigned long integer.
Returns
The corresponding Numeric.
Definition at line 118 of file Numeric.cpp.
operator=() [5/6]
Numeric & smtrat::lra::Numeric::operator= (const char * _value)
Cast from a char array.
Parameters
_value The char array.
Returns
The corresponding Numeric.
Definition at line 128 of file Numeric.cpp.
operator=() [6/6]
Numeric & smtrat::lra::Numeric::operator= (const Numeric & _value)
Cast from a char array.
Parameters
_value The char array.
Returns
The corresponding Numeric.
Definition at line 138 of file Numeric.cpp.
operator==()
bool smtrat::lra::Numeric::operator== (const Numeric & _value) const
Compares whether this Numeric and the given one are equal.
Parameters
_value The Numeric to compare with.
Returns
True, if the two Numerics are equal; False, otherwise.
Definition at line 150 of file Numeric.cpp.
operator>()
bool smtrat::lra::Numeric::operator> (const Numeric & _value) const
Compares whether this Numeric is greater than the given one.
Parameters
_value The Numeric to compare with.
Returns
True, if this Numeric is greater than the given one; False, otherwise.
Definition at line 194 of file Numeric.cpp.
operator>=()
bool smtrat::lra::Numeric::operator>= (const Numeric & _value) const
Compares whether this Numeric is greater or equal than the given one.
Parameters
_value The Numeric to compare with.
Returns
True, if this Numeric is greater or equal than the given one; False, otherwise.
Definition at line 205 of file Numeric.cpp.
The documentation for this class was generated from the following files:
smtrat-modules/LRAModule/tableau/Numeric.h
smtrat-modules/LRAModule/tableau/Numeric.cpp