SMT-RAT: smtrat::cad::Projection< Incrementality::SIMPLE, backtracking, Settings > Class Template Reference
smtrat::cad::Projection< Incrementality::SIMPLE, backtracking, Settings > Class Template Reference abstract
#include <Projection.h>
Public Types
using PolynomialSelection = Bitset
Public Member Functions
void addPolynomial (const UPoly &p)
void removePolynomial (const UPoly &p)
const Variables & vars () const
void reset (const Variables &vars)
void addPolynomial (const Poly &p)
void removePolynomial (const Poly &p, const std::function< void(std::size_t, SampleLiftedWith)> &callback)
virtual void removePolynomial (const UPoly &p, const std::function< void(std::size_t, SampleLiftedWith)> &callback)=0
void cleanLiftedWith (std::size_t level, SampleLiftedWith &slw) const
virtual const UPoly & getPolynomialById (std::size_t level, std::size_t id) const =0
Protected Member Functions
std::size_t dim () const
std::size_t getID (std::size_t level)
void freeID (std::size_t level, std::size_t id)
carl::Variable var (std::size_t level) const
Protected Attributes
Variables mVariables
std::vector< IDPool > mIDPools
std::vector
< PolynomialLiftingQueue
< BaseProjection > > mLiftingQueues
ProjectionOperator mOperator
Private Attributes
std::list< UPoly > mQueue
Detailed Description
template<Backtracking backtracking, typename Settings>
class smtrat::cad::Projection< Incrementality::SIMPLE, backtracking, Settings >
Definition at line 33 of file Projection.h.
Member Typedef Documentation
using smtrat::cad::BaseProjection::PolynomialSelection = Bitset inherited
Definition at line 16 of file BaseProjection.h.
Member Function Documentation
template<Backtracking backtracking, typename Settings > void smtrat::cad::Projection< Incrementality::SIMPLE, backtracking, Settings >::addPolynomial (const UPoly & p) inline virtual
Implements smtrat::cad::BaseProjection.
Definition at line 37 of file Projection.h.
void smtrat::cad::BaseProjection::addPolynomial (const Poly & p) inline inherited
Definition at line 52 of file BaseProjection.h.
void smtrat::cad::BaseProjection::cleanLiftedWith (std::size_t level, SampleLiftedWith & slw) const inline inherited
Definition at line 61 of file BaseProjection.h.
std::size_t smtrat::cad::BaseProjection::dim () const inline protected inherited
Definition at line 23 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection(), smtrat::cad::BaseProjection::freeID(), smtrat::cad::BaseProjection::getID(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::removePolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::reset(), and smtrat::cad::BaseProjection::var().
void smtrat::cad::BaseProjection::freeID (std::size_t level, std::size_t id) inline protected inherited
Definition at line 32 of file BaseProjection.h.
std::size_t smtrat::cad::BaseProjection::getID (std::size_t level) inline protected inherited
Definition at line 28 of file BaseProjection.h.
virtual const UPoly& smtrat::cad::BaseProjection::getPolynomialById (std::size_t level, std::size_t id) const pure virtual inherited
Implemented in smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >.
template<Backtracking backtracking, typename Settings > void smtrat::cad::Projection< Incrementality::SIMPLE, backtracking, Settings >::removePolynomial (const UPoly & p) inline
Definition at line 40 of file Projection.h.
void smtrat::cad::BaseProjection::removePolynomial (const Poly & p, const std::function< void(std::size_t, SampleLiftedWith)> & callback) inline inherited
Definition at line 56 of file BaseProjection.h.
virtual void smtrat::cad::BaseProjection::removePolynomial (const UPoly & p, const std::function< void(std::size_t, SampleLiftedWith)> & callback) pure virtual inherited
Implemented in smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >, smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >, smtrat::cad::Projection< incrementality, backtracking, Settings >, and smtrat::cad::Projection< Settings >.
void smtrat::cad::BaseProjection::reset (const Variables & vars) inline inherited
Definition at line 44 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::reset().
carl::Variable smtrat::cad::BaseProjection::var (std::size_t level) const inline protected inherited
Definition at line 36 of file BaseProjection.h.
Referenced by smtrat::cad::BaseProjection::addPolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addPolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection(), and smtrat::cad::BaseProjection::removePolynomial().
const Variables& smtrat::cad::BaseProjection::vars () const inline inherited
Definition at line 41 of file BaseProjection.h.
Referenced by smtrat::cad::BaseProjection::reset().
Field Documentation
std::vector<IDPool> smtrat::cad::BaseProjection::mIDPools protected inherited
Definition at line 19 of file BaseProjection.h.
Referenced by smtrat::cad::BaseProjection::cleanLiftedWith(), smtrat::cad::BaseProjection::dim(), smtrat::cad::BaseProjection::freeID(), smtrat::cad::BaseProjection::getID(), and smtrat::cad::BaseProjection::reset().
std::vector<PolynomialLiftingQueue<BaseProjection> > smtrat::cad::BaseProjection::mLiftingQueues protected inherited
Definition at line 20 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection(), smtrat::cad::BaseProjection::dim(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::getPolyForLifting(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::removePolynomial(), and smtrat::cad::BaseProjection::reset().
ProjectionOperator smtrat::cad::BaseProjection::mOperator protected inherited
Definition at line 21 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection().
template<Backtracking backtracking, typename Settings > std::list<UPoly> smtrat::cad::Projection< Incrementality::SIMPLE, backtracking, Settings >::mQueue private
Definition at line 35 of file Projection.h.
Variables smtrat::cad::BaseProjection::mVariables protected inherited
Definition at line 18 of file BaseProjection.h.
Referenced by smtrat::cad::BaseProjection::dim(), smtrat::cad::BaseProjection::reset(), smtrat::cad::BaseProjection::var(), and smtrat::cad::BaseProjection::vars().
The documentation for this class was generated from the following file:
lib/datastructures/cad/projection/Projection.h