SMT-RAT: Config Class Reference
Config Class Reference
Public Member Functions
Config ()
String getCarlSourcePath ()
String getManualPath ()
String getModulesPath ()
Private Attributes
String carlSourcePath
String manualPath
String modulesPath
Detailed Description
Definition at line 8 of file Config.java.
Constructor & Destructor Documentation
Config.Config () inline
Definition at line 14 of file Config.java.
Member Function Documentation
String Config.getCarlSourcePath () inline
Definition at line 21 of file Config.java.
String Config.getManualPath () inline
Definition at line 26 of file Config.java.
Referenced by GUI.MenuBarAction.actionPerformed().
String Config.getModulesPath () inline
Definition at line 31 of file Config.java.
Referenced by EditStrategyGraphDialog.ModuleInfoAction.actionPerformed(), and EditStrategyGraphDialog.SettingsInfoAction.actionPerformed().
Field Documentation
String Config.carlSourcePath private
Definition at line 10 of file Config.java.
String Config.manualPath private
Definition at line 11 of file Config.java.
String Config.modulesPath private
Definition at line 12 of file Config.java.
The documentation for this class was generated from the following file:
gui/Config.java