SMT-RAT: smtrat::ModelValue Class Reference
smtrat::ModelValue Class Reference
This class represents some value that is assigned to some variable.
#include <ModelValue.h>
Public Member Functions
ModelValue ()
Default constructor.
template<typename T >
ModelValue (const T &_t)
Initializes the Assignment from some valid type of the underlying variant.
template<typename T >
ModelValue & operator= (const T &_t)
Assign some value to the underlying variant.
bool operator== (const ModelValue &_mval) const
Check if two Assignments are equal.
bool isBool () const
bool isRational () const
bool isPoly () const
bool isSqrtEx () const
bool isRAN () const
bool isBVValue () const
bool isSortValue () const
bool isUFModel () const
bool isPlusInfinity () const
bool isMinusInfinity () const
bool isSubstitution () const
bool asBool () const
const Rational & asRational () const
const Poly & asPoly () const
const vs::SqrtEx & asSqrtEx () const
carl::RealAlgebraicNumber
< smtrat::Rational > asRAN () const
const carl::BVValue & asBVValue () const
const SortValue & asSortValue () const
const UFModel & asUFModel () const
const InfinityValue & asInfinity () const
const ModelSubstitutionPtr & asSubstitution () const
ModelSubstitutionPtr & asSubstitution ()
Private Types
using Super = boost::variant< bool, Rational, Poly, vs::SqrtEx, carl::RealAlgebraicNumber< smtrat::Rational >, carl::BVValue, SortValue, UFModel, InfinityValue, ModelSubstitutionPtr >
Base type we are deriving from.
Detailed Description
This class represents some value that is assigned to some variable.
It is implemented as subclass of a boost::variant. Possible value types are bool, vs::SqrtEx and carl::RealAlgebraicNumberPtr.
Definition at line 48 of file ModelValue.h.
Member Typedef Documentation
using smtrat::ModelValue::Super = boost::variant<bool, Rational, Poly, vs::SqrtEx, carl::RealAlgebraicNumber<smtrat::Rational>, carl::BVValue, SortValue, UFModel, InfinityValue, ModelSubstitutionPtr> private
Base type we are deriving from.
Definition at line 53 of file ModelValue.h.
Constructor & Destructor Documentation
smtrat::ModelValue::ModelValue () inline
Default constructor.
Definition at line 59 of file ModelValue.h.
template<typename T > smtrat::ModelValue::ModelValue (const T & _t) inline
Initializes the Assignment from some valid type of the underlying variant.
Definition at line 66 of file ModelValue.h.
Member Function Documentation
bool smtrat::ModelValue::asBool () const inline
Returns
The stored value as a bool.
Definition at line 212 of file ModelValue.h.
Referenced by smtrat::MCBModelSubstitution::evaluate(), and operator==().
const carl::BVValue& smtrat::ModelValue::asBVValue () const inline
Returns
The stored value as a real algebraic number.
Definition at line 254 of file ModelValue.h.
Referenced by operator==().
const InfinityValue& smtrat::ModelValue::asInfinity () const inline
Returns
The stored value as a infinity value.
Definition at line 280 of file ModelValue.h.
Referenced by Executor::check().
const Poly& smtrat::ModelValue::asPoly () const inline
Definition at line 227 of file ModelValue.h.
Referenced by smtrat::ModelPolynomialSubstitution::evaluate(), and operator==().
carl::RealAlgebraicNumber<smtrat::Rational> smtrat::ModelValue::asRAN () const inline
Returns
The stored value as a real algebraic number.
Definition at line 245 of file ModelValue.h.
Referenced by smtrat::ModelPolynomialSubstitution::evaluate(), and operator==().
const Rational& smtrat::ModelValue::asRational () const inline
Returns
The stored value as a rational.
Definition at line 221 of file ModelValue.h.
Referenced by Executor::check(), smtrat::ModelPolynomialSubstitution::evaluate(), operator==(), and smtrat::VSModule< Settings >::updateModel().
const SortValue& smtrat::ModelValue::asSortValue () const inline
Returns
The stored value as a sort value.
Definition at line 263 of file ModelValue.h.
Referenced by operator==().
const vs::SqrtEx& smtrat::ModelValue::asSqrtEx () const inline
Returns
The stored value as a square root expression.
Definition at line 236 of file ModelValue.h.
Referenced by operator==().
const ModelSubstitutionPtr& smtrat::ModelValue::asSubstitution () const inline
Definition at line 286 of file ModelValue.h.
Referenced by smtrat::ModelSubstitution::getModelValue().
ModelSubstitutionPtr& smtrat::ModelValue::asSubstitution () inline
Definition at line 290 of file ModelValue.h.
const UFModel& smtrat::ModelValue::asUFModel () const inline
Returns
The stored value as a uninterpreted function model.
Definition at line 272 of file ModelValue.h.
Referenced by operator==().
bool smtrat::ModelValue::isBool () const inline
Returns
true, if the stored value is a bool.
Definition at line 136 of file ModelValue.h.
Referenced by asBool(), smtrat::MCBModelSubstitution::evaluate(), and operator==().
bool smtrat::ModelValue::isBVValue () const inline
Returns
true, if the stored value is a bitvector literal.
Definition at line 172 of file ModelValue.h.
Referenced by asBVValue(), and operator==().
bool smtrat::ModelValue::isMinusInfinity () const inline
Returns
true, if the stored value is -infinity.
Definition at line 201 of file ModelValue.h.
Referenced by asInfinity(), and Executor::check().
bool smtrat::ModelValue::isPlusInfinity () const inline
Returns
true, if the stored value is +infinity.
Definition at line 195 of file ModelValue.h.
Referenced by asInfinity(), and Executor::check().
bool smtrat::ModelValue::isPoly () const inline
Definition at line 149 of file ModelValue.h.
Referenced by asPoly(), smtrat::ModelPolynomialSubstitution::evaluate(), and operator==().
bool smtrat::ModelValue::isRAN () const inline
Returns
true, if the stored value is a real algebraic number.
Definition at line 164 of file ModelValue.h.
Referenced by asRAN(), smtrat::ModelPolynomialSubstitution::evaluate(), and operator==().
bool smtrat::ModelValue::isRational () const inline
Returns
true, if the stored value is a rational.
Definition at line 144 of file ModelValue.h.
Referenced by asRational(), Executor::check(), smtrat::ModelPolynomialSubstitution::evaluate(), and operator==().
bool smtrat::ModelValue::isSortValue () const inline
Returns
true, if the stored value is a sort value.
Definition at line 180 of file ModelValue.h.
Referenced by asSortValue(), and operator==().
bool smtrat::ModelValue::isSqrtEx () const inline
Returns
true, if the stored value is a square root expression.
Definition at line 156 of file ModelValue.h.
Referenced by asSqrtEx(), and operator==().
bool smtrat::ModelValue::isSubstitution () const inline
Definition at line 205 of file ModelValue.h.
Referenced by asSubstitution(), smtrat::ModelPolynomialSubstitution::evaluate(), and smtrat::ModelSubstitution::getModelValue().
bool smtrat::ModelValue::isUFModel () const inline
Returns
true, if the stored value is a uninterpreted function model.
Definition at line 188 of file ModelValue.h.
Referenced by asUFModel(), and operator==().
template<typename T > ModelValue& smtrat::ModelValue::operator= (const T & _t) inline
Assign some value to the underlying variant.
Parameters
t Some value.
Returns
*this.
Definition at line 80 of file ModelValue.h.
bool smtrat::ModelValue::operator== (const ModelValue & _mval) const inline
Check if two Assignments are equal.
Two Assignments are considered equal, if both are either bool or not bool and their value is the same.
If both Assignments are not bools, the check may return false although they represent the same value. If both are numbers in different representations, this comparison is only done as a "best effort".
Parameters
_ass Another Assignment.
Returns
*this == a.
Definition at line 96 of file ModelValue.h.
The documentation for this class was generated from the following file:
lib/datastructures/model/ModelValue.h