SMT-RAT: smtrat::CADStatistics Class Reference
smtrat::CADStatistics Class Reference
#include <CADStatistics.h>
Public Member Functions
CADStatistics ()
void addMIS (std::size_t baseSize, std::size_t size)
void print (std::ostream &_out=std::cout, bool _smtlib=false, size_t _maxNameLength=0, size_t _maxKeyLength=0)
void generateXML (std::stringstream &filestream)
size_t maxKeyLength () const
const std::string & name () const
Protected Member Functions
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
Private Member Functions
void collect ()
Private Attributes
std::size_t mMISCount
std::size_t mMISBaseSize
std::size_t mMISSize
Detailed Description
Definition at line 20 of file CADStatistics.h.
Constructor & Destructor Documentation
smtrat::CADStatistics::CADStatistics () inline
Definition at line 33 of file CADStatistics.h.
Member Function Documentation
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 97 of file Statistics.h.
Referenced by smtrat::Statistics::addKeyValuePair(), collect(), smtrat::GBCalculationStats::collect(), smtrat::GeneralStatistics::collect(), smtrat::SATModuleStatistics::collect(), smtrat::GroebnerModuleStats::collect(), smtrat::FouMoStatistics::collect(), smtrat::BVStatistics::collect(), smtrat::ReduceCNFStatistics::collect(), smtrat::IntEqStatistics::collect(), and smtrat::LRAModuleStatistics::collect().
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 104 of file Statistics.h.
void smtrat::CADStatistics::addMIS (std::size_t baseSize, std::size_t size) inline
Definition at line 39 of file CADStatistics.h.
Referenced by smtrat::CADModule::checkCore().
void smtrat::CADStatistics::collect () inline private virtual
Reimplemented from smtrat::Statistics.
Definition at line 27 of file CADStatistics.h.
void smtrat::Statistics::generateXML (std::stringstream & filestream) inline inherited
Definition at line 70 of file Statistics.h.
size_t smtrat::Statistics::maxKeyLength () const inline inherited
Definition at line 80 of file Statistics.h.
const std::string& smtrat::Statistics::name () const inline inherited
Definition at line 85 of file Statistics.h.
void smtrat::Statistics::print (std::ostream & _out = std::cout, bool _smtlib = false, size_t _maxNameLength = 0, size_t _maxKeyLength = 0) inline inherited
Definition at line 36 of file Statistics.h.
Field Documentation
std::size_t smtrat::CADStatistics::mMISBaseSize private
Definition at line 24 of file CADStatistics.h.
std::size_t smtrat::CADStatistics::mMISCount private
Definition at line 23 of file CADStatistics.h.
std::size_t smtrat::CADStatistics::mMISSize private
Definition at line 25 of file CADStatistics.h.
The documentation for this class was generated from the following file:
lib/modules/CADModule/CADStatistics.h