SMT-RAT: ManageSolverDialog Class Reference
ManageSolverDialog Class Reference
Data Structures
class DeleteSolverAction
class ExportSolverAction
class OkAction
class SolverNameDocumentListener
class TakeOverSolverNameAction
Public Member Functions
ManageSolverDialog (GUI gui, String solverNameSuggestion)
Static Public Member Functions
static String showDialog (GUI gui, String solverNameSuggestion)
Private Member Functions
void checkSolverName ()
String findCorrespondingSolverName (ArrayList< String > list, String value)
void updateAvailableSolvers (String solverName, boolean add)
Static Private Attributes
static final int DIALOG_PADDING
static final int LIST_HEIGHT
static ArrayList< String > existingSolverNames
static String notAllowedSolverName
static boolean existingSolverNameEntered
static String solverName
static JTextField solverNameTextField
static JButton exportButton
static JScrollPane availableSolversScrollPane
Detailed Description
Definition at line 35 of file ManageSolverDialog.java.
Constructor & Destructor Documentation
ManageSolverDialog.ManageSolverDialog (GUI gui, String solverNameSuggestion) inline
Definition at line 49 of file ManageSolverDialog.java.
Referenced by showDialog().
Member Function Documentation
void ManageSolverDialog.checkSolverName () inline private
Definition at line 125 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog.SolverNameDocumentListener.changedUpdate(), ManageSolverDialog.SolverNameDocumentListener.insertUpdate(), ManageSolverDialog(), and ManageSolverDialog.SolverNameDocumentListener.removeUpdate().
String ManageSolverDialog.findCorrespondingSolverName (ArrayList< String > list, String value) inline private
Definition at line 151 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog.ExportSolverAction.actionPerformed(), and checkSolverName().
static String ManageSolverDialog.showDialog (GUI gui, String solverNameSuggestion) inline static
Definition at line 119 of file ManageSolverDialog.java.
void ManageSolverDialog.updateAvailableSolvers (String solverName, boolean add) inline private
Definition at line 165 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog.DeleteSolverAction.actionPerformed(), ManageSolverDialog.ExportSolverAction.actionPerformed(), and ManageSolverDialog().
Field Documentation
JScrollPane ManageSolverDialog.availableSolversScrollPane static private
Definition at line 47 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog().
final int ManageSolverDialog.DIALOG_PADDING static private
Definition at line 37 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog().
boolean ManageSolverDialog.existingSolverNameEntered static private
Definition at line 42 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog.ExportSolverAction.actionPerformed(), and checkSolverName().
ArrayList<String> ManageSolverDialog.existingSolverNames static private
Definition at line 40 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog.ExportSolverAction.actionPerformed(), checkSolverName(), ManageSolverDialog(), and updateAvailableSolvers().
JButton ManageSolverDialog.exportButton static private
Definition at line 46 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog().
final int ManageSolverDialog.LIST_HEIGHT static private
Definition at line 38 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog().
String ManageSolverDialog.notAllowedSolverName static private
Definition at line 41 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog().
String ManageSolverDialog.solverName static private
Definition at line 43 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog.ExportSolverAction.actionPerformed(), showDialog(), and updateAvailableSolvers().
JTextField ManageSolverDialog.solverNameTextField static private
Definition at line 45 of file ManageSolverDialog.java.
Referenced by ManageSolverDialog().
The documentation for this class was generated from the following file:
gui/ManageSolverDialog.java