SMT-RAT: smtrat::GroebnerModule< Settings > Singleton Reference
smtrat::GroebnerModule< Settings > Singleton Reference
A solver module based on Groebner basis.
#include <GroebnerModule.h>
Public Types
typedef Settings::Order Order
typedef
Settings::PolynomialWithReasons GBPolynomial
typedef Settings::MultivariateIdeal Ideal
enum DeductionType : unsigned { DeductionType::NORMAL, DeductionType::PERMANENT }
typedef
std::chrono::high_resolution_clock clock
For time measuring purposes.
typedef std::chrono::microseconds timeunit
For time measuring purposes.
Public Member Functions
GroebnerModule (ModuleType _type, const ModuleInput *const, RuntimeSettings *, Conditionals &, Manager *const =NULL)
virtual ~GroebnerModule ()
bool addCore (ModuleInput::const_iterator _formula)
The module has to take the given sub-formula of the received formula into account.
virtual Answer checkCore (bool _full=true)
Checks the received formula for consistency.
void removeCore (ModuleInput::const_iterator _formula)
Removes everything related to the given sub-formula of the received formula.
void printStateHistory ()
void printRewriteRules ()
bool inform (const FormulaT &)
Informs the module about the given constraint.
virtual void init ()
Informs all backends about the so far encountered constraints, which have not yet been communicated.
bool add (ModuleInput::const_iterator _subformula)
The module has to take the given sub-formula of the received formula into account.
Answer check (bool _full=true)
Checks the received formula for consistency.
void remove (ModuleInput::const_iterator _subformula)
Removes everything related to the given sub-formula of the received formula.
virtual void updateModel () const
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
virtual std::list< std::vector
< carl::Variable > > getModelEqualities () const
Partition the variables from the current model into equivalence classes according to their assigned value.
Answer solverState () const
unsigned id () const
void setId (unsigned _id)
Sets this modules unique ID to identify itself.
thread_priority threadPriority () const
void setThreadPriority (thread_priority _threadPriority)
Sets the priority of this module to get a thread for running its check procedure.
const ModuleInput * pReceivedFormula () const
const ModuleInput & rReceivedFormula () const
const ModuleInput * pPassedFormula () const
const ModuleInput & rPassedFormula () const
const Model & model () const
const std::vector< FormulasT > & infeasibleSubsets () const
const ModuleType & type () const
const std::vector< Module * > & usedBackends () const
const FormulasT & constraintsToInform () const
const FormulasT & informedConstraints () const
void addDeduction (const FormulaT &_deduction, const DeductionType &_dt=DeductionType::NORMAL)
Stores a deduction/lemma being a valid formula.
void clearDeductions ()
Deletes all yet found deductions/lemmas.
const std::vector< Splitting > & splittings () const
const std::vector< std::pair
< FormulaT, DeductionType > > & deductions () const
ModuleInput::const_iterator firstUncheckedReceivedSubformula () const
ModuleInput::const_iterator firstSubformulaToPass () const
void receivedFormulaChecked ()
Notifies that the received formulas has been checked.
const std::vector
< std::atomic_bool * > & answerFound () const
void updateDeductions ()
Stores all deductions of any backend of this module in its own deduction vector.
void collectOrigins (const FormulaT &_formula, FormulasT &_origins) const
Collects the formulas in the given formula, which are part of the received formula.
void collectOrigins (const FormulaT &_formula, std::vector< FormulaT > &_origins) const
bool hasValidInfeasibleSubset () const
void checkInfSubsetForMinimality (std::vector< FormulasT >::const_iterator _infsubset, const std::string &_filename="smaller_muses", unsigned _maxSizeDifference=1) const
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
void print (std::ostream &_out=std::cout, const std::string _initiation="***") const
Prints everything relevant of the solver.
void printReceivedFormula (std::ostream &_out=std::cout, const std::string _initiation="***") const
Prints the vector of the received formula.
void printPassedFormula (std::ostream &_out=std::cout, const std::string _initiation="***") const
Prints the vector of passed formula.
void printInfeasibleSubsets (std::ostream &_out=std::cout, const std::string _initiation="***") const
Prints the infeasible subsets.
void printModel (std::ostream &=std::cout) const
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
void startAddTimer ()
Starts the timer to stop the timing for adding formulas performed by this module.
void stopAddTimer ()
Stops the timer to stop the timing for adding formulas performed by this module.
void startCheckTimer ()
Starts the timer to stop the timing for checking formulas performed by this module.
void stopCheckTimer ()
Stops the timer to stop the timing for checking formulas performed by this module.
void startRemoveTimer ()
Starts the timer to stop the timing for removing formulas performed by this module.
void stopRemoveTimer ()
Stops the timer to stop the timing for removing formulas performed by this module.
void startTimers (int timers)
Starts the timers according to the given integer of this module: If its first bit is set, the timer for adding formulas is started.
int stopAllTimers ()
Stops all timers of this module.
double getAddTimerMS () const
double getCheckTimerMS () const
double getRemoveTimerMS () const
unsigned getNrConsistencyChecks () const
Static Public Member Functions
static const std::string moduleName (const ModuleType _moduleType)
static void addAssumptionToCheck (const FormulaT &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const FormulasT &_formulas, bool _consistent, const std::string &_label)
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ConstraintsT &_constraints, bool _consistent, const std::string &_label)
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
static void storeAssumptionsToCheck (const Manager &_manager)
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Static Public Attributes
static std::vector< std::string > mAssumptionToCheck
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static std::set< std::string > mVariablesInAssumptionToCheck
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static size_t mNumOfBranchVarsToStore
The number of different variables to consider for a probable infinite loop of branchings.
static std::vector< Branching > mLastBranches
Stores the last branches in a cycle buffer.
static size_t mFirstPosInLastBranches
The beginning of the cylcic buffer storing the last branches.
Protected Member Functions
bool constraintByGB (carl::Relation cr)
void pushBacktrackPoint (ModuleInput::const_iterator btpoint)
void popBacktrackPoint (ModuleInput::const_iterator btpoint)
bool saveState ()
FormulasT generateReasons (const carl::BitVector &reasons)
void passGB ()
void knownConstraintDeduction (const std::list< std::pair< carl::BitVector, carl::BitVector > > &deductions)
void newConstraintDeduction ()
void factorisedConstraintDeduction (const std::list< GBPolynomial > &factorisation, const carl::BitVector &reasons)
GBPolynomial transformIntoEquality (ModuleInput::const_iterator constraint)
GBPolynomial callGroebnerToSDP (const Ideal &gb)
bool iterativeVariableRewriting ()
bool findTrivialFactorisations ()
void processNewConstraint (ModuleInput::const_iterator _formula)
void handleConstraintToGBQueue (ModuleInput::const_iterator _formula)
void handleConstraintNotToGB (ModuleInput::const_iterator _formula)
void removeReceivedFormulaFromNewInequalities (ModuleInput::const_iterator _formula)
void removeSubformulaFromPassedFormula (ModuleInput::iterator _formula)
GBPolynomial rewriteVariable (const GBPolynomial &, const carl::Variable &, const TermT &, const BitVector &)
bool validityCheck ()
virtual bool informCore (const FormulaT &)
Informs the module about the given constraint.
bool anAnswerFound () const
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
void clearModel () const
Clears the assignment, if any was found.
ModuleInput::iterator passedFormulaBegin ()
ModuleInput::iterator passedFormulaEnd ()
void addOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
Adds the given set of formulas in the received formula to the origins of the given passed formula.
const FormulaT & getOrigins (ModuleInput::const_iterator _formula) const
Gets the origins of the passed formula at the given position.
std::pair
< ModuleInput::iterator, bool > removeOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
std::pair
< ModuleInput::iterator, bool > removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
void informBackends (const FormulaT &_constraint)
Informs all backends of this module about the given constraint.
void addConstraintToInform (const FormulaT &_constraint)
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
std::pair
< ModuleInput::iterator, bool > addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula)
Copies the given sub-formula of the received formula to the passed formula.
bool originInReceivedFormula (const FormulaT &_origin) const
std::pair
< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula)
Adds the given formula to the passed formula with no origin.
std::pair
< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
Adds the given formula to the passed formula.
std::pair
< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const FormulaT &_origin)
Adds the given formula to the passed formula.
void getInfeasibleSubsets ()
Copies the infeasible subsets of the passed formula.
std::vector< FormulasT > getInfeasibleSubsets (const Module &_backend) const
Get the infeasible subsets the given backend provides.
void getBackendsModel () const
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
Answer runBackends (bool _full=true)
Runs the backend solvers on the passed formula.
virtual ModuleInput::iterator eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins=false)
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
std::vector< FormulaT > merge (const std::vector< FormulaT > &, const std::vector< FormulaT > &) const
Merges the two vectors of sets into the first one.
size_t determine_smallest_origin (const std::vector< FormulaT > &origins) const
void branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true)
Adds a deductions which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
void branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
void branchAt (carl::Variable::Arg _var, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true)
void branchAt (carl::Variable::Arg _var, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
void branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true)
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
void branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
void splitUnequalConstraint (const FormulaT &)
Adds the following lemmas for the given constraint p!=0.
unsigned checkModel () const
Static Protected Member Functions
static bool modelsDisjoint (const Model &_modelA, const Model &_modelB)
Checks whether there is no variable assigned by both models.
static bool probablyLooping (const typename Poly::PolyType &_branchingPolynomial, const Rational &_branchingValue)
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
Protected Attributes
Settings::Groebner mBasis
The current Groebner basis.
InequalitiesTable< Settings > mInequalities
The inequalities table for handling inequalities.
std::vector
< ModuleInput::const_iterator > mBacktrackPoints
The vector of backtrack points, which has pointers to received constraints.
std::list< GroebnerModuleState
< Settings > > mStateHistory
Saves the relevant history to support backtracking.
bool mRecalculateGB
After popping in the history, it might be necessary to recalculate. This flag indicates this.
std::list< typename
InequalitiesTable< Settings >
::Rows::iterator > mNewInequalities
A list of inequalities which were added after the last consistency check.
GBRuntimeSettings * mRuntimeSettings
An reference to the RuntimeSettings.
groebner::RewriteRules mRewriteRules
The rewrite rules for the variables.
std::map< size_t, carl::Variable > mAdditionalVarMap
FormulasT mGbEqualities
A workaround to associate equalities in the passed formula originating from the gb (in contrast to those which originate from simplified formulae)
std::vector< FormulasT > mInfeasibleSubsets
Stores the infeasible subsets.
Manager *const mpManager
A reference to the manager.
Model mModel
Stores the assignment of the current satisfiable result, if existent.
Private Types
typedef Module super
Friends
class InequalitiesTable< Settings >
Detailed Description
template<class Settings>
singleton smtrat::GroebnerModule< Settings >
A solver module based on Groebner basis.
Details can be found in my Bachelor Thesis "On Groebner Bases in SMT-Compliant Decision Procedures"
Author
Sebastian Junges
Definition at line 47 of file GroebnerModule.h.
Member Typedef Documentation
typedef std::chrono::high_resolution_clock smtrat::Module::clock inherited
For time measuring purposes.
Definition at line 112 of file Module.h.
template<class Settings> typedef Settings::PolynomialWithReasons smtrat::GroebnerModule< Settings >::GBPolynomial
Definition at line 52 of file GroebnerModule.h.
template<class Settings> typedef Settings::MultivariateIdeal smtrat::GroebnerModule< Settings >::Ideal
Definition at line 53 of file GroebnerModule.h.
template<class Settings> typedef Settings::Order smtrat::GroebnerModule< Settings >::Order
Definition at line 51 of file GroebnerModule.h.
template<class Settings> typedef Module smtrat::GroebnerModule< Settings >::super private
Definition at line 130 of file GroebnerModule.h.
typedef std::chrono::microseconds smtrat::Module::timeunit inherited
For time measuring purposes.
Definition at line 114 of file Module.h.
Member Enumeration Documentation
enum smtrat::Module::DeductionType : unsigned strong inherited
Enumerator
NORMAL
PERMANENT
Definition at line 119 of file Module.h.
Constructor & Destructor Documentation
template<class Settings> smtrat::GroebnerModule< Settings >::GroebnerModule (ModuleType _type, const ModuleInput * const, RuntimeSettings * , Conditionals & , Manager * const = NULL)
template<class Settings> virtual smtrat::GroebnerModule< Settings >::~GroebnerModule () virtual
Member Function Documentation
bool Module::add (ModuleInput::const_iterator _subformula) inherited
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Definition at line 132 of file Module.cpp.
Referenced by smtrat::Manager::add().
void Module::addAssumptionToCheck (const FormulaT & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_formula The formula which should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 834 of file Module.cpp.
Referenced by smtrat::Module::check(), smtrat::ICPModule::checkBoxAgainstLinearFeasibleRegion(), smtrat::CADModule::checkCore(), smtrat::Module::checkCore(), smtrat::Module::getInfeasibleSubsets(), vs::State::passConflictToFather(), and smtrat::Module::updateDeductions().
void Module::addAssumptionToCheck (const ModuleInput & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_subformulas The sub-formulas whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 849 of file Module.cpp.
void Module::addAssumptionToCheck (const FormulasT & _formulas, bool _consistent, const std::string & _label) static inherited
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
Parameters
_formulas The formulas, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 864 of file Module.cpp.
void Module::addAssumptionToCheck (const ConstraintsT & _constraints, bool _consistent, const std::string & _label) static inherited
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
Parameters
_constraints The constraints, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See also
Module::storeAssumptionsToCheck
Definition at line 879 of file Module.cpp.
void Module::addConstraintToInform (const FormulaT & _constraint) protected inherited
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
Parameters
_constraint The constraint to add.
Definition at line 774 of file Module.cpp.
Referenced by smtrat::Module::inform(), and smtrat::ICPModule::pushBoundsToPassedFormula().
template<class Settings> bool smtrat::GroebnerModule< Settings >::addCore (ModuleInput::const_iterator) virtual
The module has to take the given sub-formula of the received formula into account.
Parameters
The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Reimplemented from smtrat::Module.
void smtrat::Module::addDeduction (const FormulaT & _deduction, const DeductionType & _dt = DeductionType::NORMAL) inline inherited
Stores a deduction/lemma being a valid formula.
Parameters
_deduction The eduction/lemma to store.
_dt The type of the deduction.
Definition at line 395 of file Module.h.
Referenced by smtrat::ICPModule::addCore(), smtrat::ICPModule::checkAndPerformSplit(), smtrat::ICPModule::contraction(), smtrat::ICPModule::initialLinearCheck(), and smtrat::Module::splitUnequalConstraint().
void smtrat::Module::addOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Adds the given set of formulas in the received formula to the origins of the given passed formula.
Parameters
_formula The passed formula to set the origins for.
_origins A set of formulas in the received formula of this module.
Definition at line 647 of file Module.h.
pair< ModuleInput::iterator, bool > Module::addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula) protected inherited
Copies the given sub-formula of the received formula to the passed formula.
Note, that there is always a link between sub-formulas of the passed formulas to sub-formulas of the received formulas, which are responsible for its occurrence.
Parameters
_subformula The sub-formula of the received formula to copy.
Definition at line 276 of file Module.cpp.
Referenced by smtrat::ICPModule::addCore(), and smtrat::Module::checkCore().
std::pair< ModuleInput::iterator, bool > Module::addSubformulaToPassedFormula (const FormulaT & _formula) protected inherited
Adds the given formula to the passed formula with no origin.
Note that in the next call of this module's removeSubformula, all formulas in the passed formula without origins will be removed.
Parameters
_formula The formula to add to the passed formula.
Definition at line 282 of file Module.cpp.
Referenced by smtrat::ICPModule::addCore(), smtrat::Module::addReceivedSubformulaToPassedFormula(), smtrat::CNFerModule::checkCore(), and smtrat::ICPModule::pushBoundsToPassedFormula().
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origins The link of the formula to add to the passed formula to sub-formulas of the received formulas, which are responsible for its occurrence
pair< ModuleInput::iterator, bool > Module::addSubformulaToPassedFormula (const FormulaT & _formula, const FormulaT & _origin) protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origin The sub-formula of the received formula being responsible for the occurrence of the formula to add to the passed formula.
Definition at line 333 of file Module.cpp.
bool smtrat::Module::anAnswerFound () const inline protected inherited
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
Returns
True, if one of them has determined a result.
Definition at line 607 of file Module.h.
Referenced by smtrat::CADModule::checkCore(), smtrat::Module::foundAnswer(), and smtrat::Module::runBackends().
const std::vector< std::atomic_bool* >& smtrat::Module::answerFound () const inline inherited
Returns
A vector of Booleans: If any of them is true, we have to terminate a running check procedure.
Definition at line 452 of file Module.h.
Referenced by smtrat::Manager::getBackends().
void Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true) protected inherited
Adds a deductions which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
Note that the given value is rounded down and up, if the given variable is integer-valued.
Parameters
_polynomial The variable to branch for. _integral A flag being true, if all variables in the polynomial to branch for are integral.
_value The value to branch at.
_premise The sub-formulas of the received formula from which the branch is followed. Note, that a premise is not necessary, as every branch is a valid formula. But a premise can prevent from branching unnecessarily.
_leftCaseWeak true, if a branching in the form of (or (<= p b) (> p b)) is desired. false, if a branching in the form of (or (< p b) (>= p b)) is desired.
_preferLeftCase true, if the left case (polynomial less(or equal) 0 shall be chosen first. false, otherwise.
_isolateBranchValue true, if a branching in the form of (or (= p b) (< p b) (> p b)) is desired. (Currently only supported for reals)
Definition at line 447 of file Module.cpp.
Referenced by smtrat::Module::branchAt(), smtrat::ICPModule::checkAndPerformSplit(), smtrat::CADModule::checkCore(), and smtrat::ICPModule::contraction().
void smtrat::Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, bool _leftCaseWeak = true, bool _preferLeftCase = true, const std::vector< FormulaT > & _premise = std::vector<FormulaT>()) inline protected inherited
Definition at line 827 of file Module.h.
void smtrat::Module::branchAt (carl::Variable::Arg _var, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true) inline protected inherited
Definition at line 832 of file Module.h.
void smtrat::Module::branchAt (carl::Variable::Arg _var, const Rational & _value, bool _leftCaseWeak = true, bool _preferLeftCase = true, const std::vector< FormulaT > & _premise = std::vector<FormulaT>()) inline protected inherited
Definition at line 837 of file Module.h.
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy> void smtrat::Module::branchAt (const typename P::PolyType & _poly, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true) inline protected inherited
Definition at line 843 of file Module.h.
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy> void smtrat::Module::branchAt (const typename P::PolyType & _poly, bool _integral, const Rational & _value, bool _leftCaseWeak = true, bool _preferLeftCase = true, const std::vector< FormulaT > & _premise = std::vector<FormulaT>()) inline protected inherited
Definition at line 849 of file Module.h.
template<class Settings> GBPolynomial smtrat::GroebnerModule< Settings >::callGroebnerToSDP (const Ideal & gb) protected
Answer Module::check (bool _full = true) inherited
Checks the received formula for consistency.
Note, that this is an implementation of the satisfiability check of the conjunction of the so far received formulas, which does actually nothing but passing the problem to its backends. This implementation is only used internally and must be overwritten by any derived module.
Parameters
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
Returns
True, if the received formula is satisfiable; False, if the received formula is not satisfiable; Unknown, otherwise.
Definition at line 91 of file Module.cpp.
Referenced by smtrat::Manager::check(), and smtrat::ThreadPool::submitBackend().
template<class Settings> virtual Answer smtrat::GroebnerModule< Settings >::checkCore (bool _full = true) virtual
Checks the received formula for consistency.
Note, that this is an implementation of the satisfiability check of the conjunction of the so far received formulas, which does actually nothing but passing the problem to its backends. This implementation is only used internally and must be overwritten by any derived module.
Parameters
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
Returns
True, if the received formula is satisfiable; False, if the received formula is not satisfiable; Unknown, otherwise.
Reimplemented from smtrat::Module.
void Module::checkInfSubsetForMinimality (std::vector< FormulasT >::const_iterator _infsubset, const std::string & _filename = "smaller_muses", unsigned _maxSizeDifference = 1) const inherited
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
Parameters
_infsubset The infeasible subset to check for minimality.
_filename The name of the file to store the infeasible subsets in order to be able to check their infeasibility.
_maxSizeDifference The maximal difference between the sizes of the subsets compared to the size of the infeasible subset.
Definition at line 949 of file Module.cpp.
Referenced by smtrat::CADModule::checkCore().
unsigned Module::checkModel () const protected inherited
Returns
false, if the current model of this module does not satisfy the current given formula; true, if it cannot be said whether the model satisfies the given formula.
Definition at line 501 of file Module.cpp.
Referenced by smtrat::Module::foundAnswer().
void smtrat::Module::clearDeductions () inline inherited
Deletes all yet found deductions/lemmas.
Definition at line 403 of file Module.h.
Referenced by smtrat::Module::~Module().
void smtrat::Module::clearModel () const inline protected inherited
Clears the assignment, if any was found.
Definition at line 619 of file Module.h.
Referenced by smtrat::CADModule::updateModel(), smtrat::ICPModule::updateModel(), smtrat::Module::updateModel(), and smtrat::Module::~Module().
void Module::collectOrigins (const FormulaT & _formula, FormulasT & _origins) const inherited
Collects the formulas in the given formula, which are part of the received formula.
If the given formula directly occurs in the received formula, it is inserted into the given set. Otherwise, the given formula must be of type AND and all its sub-formulas part of the received formula. Hence, they will be added to the given set.
Parameters
_formula The formula from which to collect the formulas being sub-formulas of the received formula (origins).
_origins The set in which to store the origins.
Definition at line 800 of file Module.cpp.
Referenced by smtrat::Module::getInfeasibleSubsets(), and smtrat::ICPModule::variableReasonHull().
void Module::collectOrigins (const FormulaT & _formula, std::vector< FormulaT > & _origins) const inherited
Definition at line 817 of file Module.cpp.
template<class Settings> bool smtrat::GroebnerModule< Settings >::constraintByGB (carl::Relation cr) protected
const FormulasT& smtrat::Module::constraintsToInform () const inline inherited
Returns
The constraints which the backends must be informed about.
Definition at line 377 of file Module.h.
const std::vector<std::pair<FormulaT,DeductionType> >& smtrat::Module::deductions () const inline inherited
Returns
A constant reference to the deductions/lemmas being valid formulas this module or its backends made.
Definition at line 420 of file Module.h.
Referenced by smtrat::Manager::lemmas().
size_t Module::determine_smallest_origin (const std::vector< FormulaT > & origins) const protected inherited
Parameters
origins A vector of sets of origins.
Returns
The index of the smallest (regarding the size of the sets) element of origins
Definition at line 377 of file Module.cpp.
ModuleInput::iterator Module::eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins = false) protected virtual inherited
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
Afterwards the sub-formula is removed from the passed formula.
Parameters
_subformula The sub-formula to remove from the passed formula.
_ignoreOrigins True, if the sub-formula shall be removed regardless of its origins (should only be applied with expertise).
Returns
Reimplemented in smtrat::ICPModule.
Definition at line 704 of file Module.cpp.
Referenced by smtrat::ICPModule::eraseSubformulaFromPassedFormula(), smtrat::ICPModule::pushBoundsToPassedFormula(), smtrat::Module::remove(), smtrat::Module::removeOrigin(), and smtrat::Module::removeOrigins().
template<class Settings> void smtrat::GroebnerModule< Settings >::factorisedConstraintDeduction (const std::list< GBPolynomial > & factorisation, const carl::BitVector & reasons) protected
template<class Settings> bool smtrat::GroebnerModule< Settings >::findTrivialFactorisations () protected
ModuleInput::const_iterator smtrat::Module::firstSubformulaToPass () const inline inherited
Returns
The position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
Definition at line 436 of file Module.h.
ModuleInput::const_iterator smtrat::Module::firstUncheckedReceivedSubformula () const inline inherited
Returns
The position of the first (by this module) unchecked sub-formula of the received formula.
Definition at line 428 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore().
template<class Settings> FormulasT smtrat::GroebnerModule< Settings >::generateReasons (const carl::BitVector & reasons) protected
double smtrat::Module::getAddTimerMS () const inline inherited
Returns
The total time of adding formulas performed by this module.
Definition at line 1045 of file Module.h.
void Module::getBackendsModel () const protected inherited
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
Definition at line 539 of file Module.cpp.
Referenced by smtrat::ICPModule::updateModel(), and smtrat::Module::updateModel().
double smtrat::Module::getCheckTimerMS () const inline inherited
Returns
The total time of checking formulas performed by this module.
Definition at line 1053 of file Module.h.
void Module::getInfeasibleSubsets () protected inherited
Copies the infeasible subsets of the passed formula.
Definition at line 507 of file Module.cpp.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Module::checkCore().
std::vector< FormulasT > Module::getInfeasibleSubsets (const Module & _backend) const protected inherited
Get the infeasible subsets the given backend provides.
Note, that an infeasible subset in a backend contains sub formulas of the passed formula and an infeasible subset of this module contains sub formulas of the received formula. In this method the LATTER is returned.
Parameters
_backend The backend from which to obtain the infeasible subsets.
Returns
The infeasible subsets the given backend provides.
Definition at line 560 of file Module.cpp.
list< std::vector< carl::Variable > > Module::getModelEqualities () const virtual inherited
Partition the variables from the current model into equivalence classes according to their assigned value.
The result is a set of equivalence classes of variables where all variables within one class are assigned the same value. Note that the number of classes may not be minimal, i.e. two classes may actually be equivalent.
Returns
Equivalence classes.
Definition at line 243 of file Module.cpp.
Referenced by smtrat::Manager::getModelEqualities().
unsigned smtrat::Module::getNrConsistencyChecks () const inline inherited
Returns
The number of consistency checks performed by this module.
Definition at line 1069 of file Module.h.
const FormulaT& smtrat::Module::getOrigins (ModuleInput::const_iterator _formula) const inline protected inherited
Gets the origins of the passed formula at the given position.
Parameters
_formula The position of a formula in the passed formulas.
Returns
The origins of the passed formula at the given position.
Definition at line 657 of file Module.h.
double smtrat::Module::getRemoveTimerMS () const inline inherited
Returns
The total time of removing formulas performed by this module.
Definition at line 1061 of file Module.h.
template<class Settings> void smtrat::GroebnerModule< Settings >::handleConstraintNotToGB (ModuleInput::const_iterator _formula) protected
template<class Settings> void smtrat::GroebnerModule< Settings >::handleConstraintToGBQueue (ModuleInput::const_iterator _formula) protected
bool Module::hasValidInfeasibleSubset () const inherited
Returns
true, if the module has at least one valid infeasible subset, that is all its elements are sub-formulas of the received formula (pointer must be equal).
Definition at line 933 of file Module.cpp.
Referenced by smtrat::Module::check().
unsigned smtrat::Module::id () const inline inherited
Returns
A unique ID to identify this module instance.
Definition at line 277 of file Module.h.
const std::vector<FormulasT>& smtrat::Module::infeasibleSubsets () const inline inherited
Returns
The infeasible subsets of the set of received formulas (empty, if this module has not detected unsatisfiability of the conjunction of received formulas.
Definition at line 353 of file Module.h.
Referenced by smtrat::ICPModule::callBackends(), smtrat::CADModule::checkCore(), smtrat::Module::getInfeasibleSubsets(), smtrat::Manager::infeasibleSubsets(), and smtrat::Manager::printInfeasibleSubset().
bool Module::inform (const FormulaT & _constraint) inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Definition at line 123 of file Module.cpp.
Referenced by smtrat::Manager::getBackends(), smtrat::Manager::inform(), and smtrat::Manager::Manager().
void smtrat::Module::informBackends (const FormulaT & _constraint) inline protected inherited
Informs all backends of this module about the given constraint.
Parameters
_constraint The constraint to inform about.
Definition at line 685 of file Module.h.
virtual bool smtrat::Module::informCore (const FormulaT &) inline protected virtual inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Reimplemented in smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, and smtrat::ICPModule.
Definition at line 563 of file Module.h.
Referenced by smtrat::Module::inform().
const FormulasT& smtrat::Module::informedConstraints () const inline inherited
Returns
The position of the first constraint of which no backend has been informed about.
Definition at line 385 of file Module.h.
Referenced by smtrat::Manager::getBackends().
void Module::init () virtual inherited
Informs all backends about the so far encountered constraints, which have not yet been communicated.
This method must not be called twice and only before the first runBackends call.
Reimplemented in smtrat::LRAModule< Settings >, and smtrat::LRAModule< smtrat::LRASettings1 >.
Definition at line 218 of file Module.cpp.
template<class Settings> bool smtrat::GroebnerModule< Settings >::iterativeVariableRewriting () protected
template<class Settings> void smtrat::GroebnerModule< Settings >::knownConstraintDeduction (const std::list< std::pair< carl::BitVector, carl::BitVector > > & deductions) protected
std::vector< FormulaT > Module::merge (const std::vector< FormulaT > & _vecSetA, const std::vector< FormulaT > & _vecSetB) const protected inherited
Merges the two vectors of sets into the first one.
({a,b},{a,c}) and ({b,d},{b}) -> ({a,b,d},{a,b},{a,b,c,d},{a,b,c})
Parameters
_vecSetA A vector of sets of constraints.
_vecSetB A vector of sets of constraints.
Returns
The vector being the two given vectors merged.
Definition at line 351 of file Module.cpp.
const Model& smtrat::Module::model () const inline inherited
Returns
The assignment of the current satisfiable result, if existent.
Definition at line 344 of file Module.h.
Referenced by smtrat::Manager::model(), and smtrat::Module::printModel().
bool Module::modelsDisjoint (const Model & _modelA, const Model & _modelB) static protected inherited
Checks whether there is no variable assigned by both models.
Parameters
_modelA The first model to check for.
_modelB The second model to check for.
Returns
true, if there is no variable assigned by both models; false, otherwise.
Definition at line 522 of file Module.cpp.
static const std::string smtrat::Module::moduleName (const ModuleType _moduleType) inline static inherited
Parameters
_moduleType The module type to return the name as string for.
Returns
The name of the given module type as name.
Definition at line 461 of file Module.h.
Referenced by smtrat::Module::add(), smtrat::Module::branchAt(), smtrat::Module::check(), smtrat::Module::checkCore(), smtrat::Module::checkInfSubsetForMinimality(), smtrat::Module::getInfeasibleSubsets(), smtrat::Module::inform(), smtrat::Module::print(), smtrat::Module::remove(), smtrat::Module::runBackends(), and smtrat::Module::updateDeductions().
template<class Settings> void smtrat::GroebnerModule< Settings >::newConstraintDeduction () protected
bool Module::originInReceivedFormula (const FormulaT & _origin) const protected inherited
Definition at line 308 of file Module.cpp.
Referenced by smtrat::Module::addSubformulaToPassedFormula().
ModuleInput::iterator smtrat::Module::passedFormulaBegin () inline protected inherited
Returns
An iterator to the end of the passed formula. TODO: disable this method
Definition at line 629 of file Module.h.
ModuleInput::iterator smtrat::Module::passedFormulaEnd () inline protected inherited
Returns
An iterator to the end of the passed formula.
Definition at line 637 of file Module.h.
Referenced by smtrat::ICPModule::eraseSubformulaFromPassedFormula(), smtrat::ICPModule::getIcpVariable(), and smtrat::ICPModule::pushBoundsToPassedFormula().
template<class Settings> void smtrat::GroebnerModule< Settings >::passGB () protected
template<class Settings> void smtrat::GroebnerModule< Settings >::popBacktrackPoint (ModuleInput::const_iterator btpoint) protected
const ModuleInput* smtrat::Module::pPassedFormula () const inline inherited
Returns
A pointer to the formula passed to the backends of this module.
Definition at line 328 of file Module.h.
Referenced by smtrat::Manager::getBackends().
const ModuleInput* smtrat::Module::pReceivedFormula () const inline inherited
Returns
A pointer to the formula passed to this module.
Definition at line 312 of file Module.h.
void Module::print (std::ostream & _out = std::cout, const std::string _initiation = "***") const inherited
Prints everything relevant of the solver.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 997 of file Module.cpp.
Referenced by smtrat::Module::addSubformulaToPassedFormula(), and smtrat::Module::check().
void Module::printInfeasibleSubsets (std::ostream & _out = std::cout, const std::string _initiation = "***") const inherited
Prints the infeasible subsets.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1044 of file Module.cpp.
Referenced by smtrat::Module::print().
void Module::printModel (std::ostream & _out = std::cout) const inherited
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1060 of file Module.cpp.
Referenced by smtrat::Manager::printAssignment().
void Module::printPassedFormula (std::ostream & _out = std::cout, const std::string _initiation = "***") const inherited
Prints the vector of passed formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1026 of file Module.cpp.
Referenced by smtrat::Module::print().
void Module::printReceivedFormula (std::ostream & _out = std::cout, const std::string _initiation = "***") const inherited
Prints the vector of the received formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1013 of file Module.cpp.
Referenced by smtrat::Module::print().
template<class Settings> void smtrat::GroebnerModule< Settings >::printRewriteRules ()
template<class Settings> void smtrat::GroebnerModule< Settings >::printStateHistory ()
bool Module::probablyLooping (const typename Poly::PolyType & _branchingPolynomial, const Rational & _branchingValue) static protected inherited
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
Parameters
_branchingPolynomial The polynomial to branch at (in most branching strategies this is just a variable).
_branchingValue The value to branch at.
Returns
true, if this branching is probably part of an infinite loop of branchings; false, otherwise.
Definition at line 397 of file Module.cpp.
template<class Settings> void smtrat::GroebnerModule< Settings >::processNewConstraint (ModuleInput::const_iterator _formula) protected
template<class Settings> void smtrat::GroebnerModule< Settings >::pushBacktrackPoint (ModuleInput::const_iterator btpoint) protected
void smtrat::Module::receivedFormulaChecked () inline inherited
Notifies that the received formulas has been checked.
Definition at line 444 of file Module.h.
void Module::remove (ModuleInput::const_iterator _subformula) inherited
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
_subformula The sub formula of the received formula to remove.
Definition at line 148 of file Module.cpp.
Referenced by smtrat::Manager::remove().
template<class Settings> void smtrat::GroebnerModule< Settings >::removeCore (ModuleInput::const_iterator) virtual
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
The sub formula of the received formula to remove.
Reimplemented from smtrat::Module.
std::pair<ModuleInput::iterator,bool> smtrat::Module::removeOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Definition at line 663 of file Module.h.
std::pair<ModuleInput::iterator,bool> smtrat::Module::removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) inline protected inherited
Definition at line 672 of file Module.h.
template<class Settings> void smtrat::GroebnerModule< Settings >::removeReceivedFormulaFromNewInequalities (ModuleInput::const_iterator _formula) protected
template<class Settings> void smtrat::GroebnerModule< Settings >::removeSubformulaFromPassedFormula (ModuleInput::iterator _formula) protected
template<class Settings> GBPolynomial smtrat::GroebnerModule< Settings >::rewriteVariable (const GBPolynomial & , const carl::Variable & , const TermT & , const BitVector &) protected
const ModuleInput& smtrat::Module::rPassedFormula () const inline inherited
Returns
A reference to the formula passed to the backends of this module.
Definition at line 336 of file Module.h.
Referenced by smtrat::ICPModule::callBackends(), and smtrat::CNFerModule::checkCore().
const ModuleInput& smtrat::Module::rReceivedFormula () const inline inherited
Returns
A reference to the formula passed to this module.
Definition at line 320 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), smtrat::CADModule::checkCore(), smtrat::ICPModule::checkCore(), smtrat::ICPModule::constraintReasonHull(), smtrat::ICPModule::contractCurrentBox(), smtrat::ICPModule::contractionCandidateHasLegalOrigins(), smtrat::ICPModule::createBoxFormula(), smtrat::ICPModule::pushBoundsToPassedFormula(), smtrat::ICPModule::remapAndSetLraInfeasibleSubsets(), smtrat::ICPModule::tryTestPoints(), and smtrat::ICPModule::variableReasonHull().
Answer Module::runBackends (bool _full = true) protected inherited
Runs the backend solvers on the passed formula.
Parameters
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
Returns
True, if the passed formula is consistent; False, if the passed formula is inconsistent; Unknown, otherwise.
Definition at line 605 of file Module.cpp.
Referenced by smtrat::ICPModule::callBackends(), smtrat::CNFerModule::checkCore(), and smtrat::Module::checkCore().
template<class Settings> bool smtrat::GroebnerModule< Settings >::saveState () protected
void smtrat::Module::setId (unsigned _id) inline inherited
Sets this modules unique ID to identify itself.
Parameters
_id The id to set this module's id to.
Definition at line 286 of file Module.h.
Referenced by smtrat::Manager::getBackends().
void smtrat::Module::setThreadPriority (thread_priority _threadPriority) inline inherited
Sets the priority of this module to get a thread for running its check procedure.
Parameters
_threadPriority The priority to set this module's thread priority to.
Definition at line 304 of file Module.h.
Referenced by smtrat::Manager::getBackends().
Answer smtrat::Module::solverState () const inline inherited
Returns
True, if this module is in a state, such that it has found a solution for its received formula; False, if this module is in a state, such that it has determined that there is no solution for its received formula; Unknown, otherwise.
Definition at line 269 of file Module.h.
Referenced by smtrat::CADModule::addConstraintFormula(), smtrat::CADModule::updateModel(), and smtrat::ICPModule::updateModel().
const std::vector<Splitting>& smtrat::Module::splittings () const inline inherited
Returns
A constant reference to the splitting decisions this module or its backends made.
Definition at line 412 of file Module.h.
Referenced by smtrat::ICPModule::checkCore().
void Module::splitUnequalConstraint (const FormulaT & _unequalConstraint) protected inherited
Adds the following lemmas for the given constraint p!=0.
(p!=0 <-> (p<0 or p>0)) and not(p<0 and p>0)
Parameters
_unequalConstraint A constraint having the relation symbol !=.
Definition at line 478 of file Module.cpp.
Referenced by smtrat::ICPModule::checkNotEqualConstraints().
void smtrat::Module::startAddTimer () inline inherited
Starts the timer to stop the timing for adding formulas performed by this module.
Definition at line 939 of file Module.h.
Referenced by smtrat::Module::startTimers().
void smtrat::Module::startCheckTimer () inline inherited
Starts the timer to stop the timing for checking formulas performed by this module.
Definition at line 959 of file Module.h.
Referenced by smtrat::Module::check(), and smtrat::Module::startTimers().
void smtrat::Module::startRemoveTimer () inline inherited
Starts the timer to stop the timing for removing formulas performed by this module.
Definition at line 979 of file Module.h.
Referenced by smtrat::Module::startTimers().
void smtrat::Module::startTimers (int timers) inline inherited
Starts the timers according to the given integer of this module: If its first bit is set, the timer for adding formulas is started.
If its second bit is set, the timer for checking formulas is started. If its third bit is set, the timer for removing formulas is started.
Parameters
timers The integer specifying which timers to start.
Definition at line 1004 of file Module.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula().
void smtrat::Module::stopAddTimer () inline inherited
Stops the timer to stop the timing for adding formulas performed by this module.
Definition at line 949 of file Module.h.
Referenced by smtrat::Module::stopAllTimers().
int smtrat::Module::stopAllTimers () inline inherited
Stops all timers of this module.
Returns
An integer showing which timers were stopped: If its first bit is set, the timer for adding formulas was stopped. If its second bit is set, the timer for checking formulas was stopped. If its third bit is set, the timer for removing formulas was stopped.
Definition at line 1021 of file Module.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula().
void smtrat::Module::stopCheckTimer () inline inherited
Stops the timer to stop the timing for checking formulas performed by this module.
Definition at line 969 of file Module.h.
Referenced by smtrat::Module::check(), and smtrat::Module::stopAllTimers().
void smtrat::Module::stopRemoveTimer () inline inherited
Stops the timer to stop the timing for removing formulas performed by this module.
Definition at line 990 of file Module.h.
Referenced by smtrat::Module::stopAllTimers().
void Module::storeAssumptionsToCheck (const Manager & _manager) static inherited
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Parameters
_manager The managaer object of this solver to store the assumptions for.
Definition at line 903 of file Module.cpp.
Referenced by smtrat::CADModule::checkCore(), and smtrat::Manager::~Manager().
thread_priority smtrat::Module::threadPriority () const inline inherited
Returns
The priority of this module to get a thread for running its check procedure.
Definition at line 295 of file Module.h.
Referenced by smtrat::ThreadPool::checkBackendPriority(), smtrat::Manager::getBackends(), and smtrat::ThreadPool::submitBackend().
template<class Settings> GBPolynomial smtrat::GroebnerModule< Settings >::transformIntoEquality (ModuleInput::const_iterator constraint) protected
const ModuleType& smtrat::Module::type () const inline inherited
Returns
The type of this module.
Definition at line 361 of file Module.h.
Referenced by smtrat::Module::branchAt(), smtrat::Module::check(), smtrat::Module::checkCore(), smtrat::Manager::getBackends(), smtrat::Module::getInfeasibleSubsets(), smtrat::Module::print(), and smtrat::Module::runBackends().
void Module::updateDeductions () inherited
Stores all deductions of any backend of this module in its own deduction vector.
Definition at line 781 of file Module.cpp.
void Module::updateModel () const virtual inherited
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
Reimplemented in smtrat::SATModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::ICPModule, smtrat::CADModule, smtrat::VSModule< Settings >, smtrat::IntEqModule< Settings >, and smtrat::PreprocessingModule< Settings >.
Definition at line 234 of file Module.cpp.
Referenced by smtrat::Module::checkModel(), smtrat::Manager::model(), and smtrat::Module::printModel().
const std::vector<Module*>& smtrat::Module::usedBackends () const inline inherited
Returns
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
Definition at line 369 of file Module.h.
Referenced by smtrat::ICPModule::callBackends().
template<class Settings> bool smtrat::GroebnerModule< Settings >::validityCheck () protected
Friends And Related Function Documentation
template<class Settings> friend class InequalitiesTable< Settings > friend
Definition at line 49 of file GroebnerModule.h.
Field Documentation
template<class Settings> std::map<size_t, carl::Variable> smtrat::GroebnerModule< Settings >::mAdditionalVarMap protected
Definition at line 72 of file GroebnerModule.h.
vector< string > Module::mAssumptionToCheck static inherited
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
Definition at line 184 of file Module.h.
Referenced by smtrat::Module::addAssumptionToCheck().
template<class Settings> std::vector<ModuleInput::const_iterator> smtrat::GroebnerModule< Settings >::mBacktrackPoints protected
The vector of backtrack points, which has pointers to received constraints.
Definition at line 60 of file GroebnerModule.h.
template<class Settings> Settings::Groebner smtrat::GroebnerModule< Settings >::mBasis protected
The current Groebner basis.
Definition at line 56 of file GroebnerModule.h.
size_t Module::mFirstPosInLastBranches static inherited
The beginning of the cylcic buffer storing the last branches.
Definition at line 192 of file Module.h.
Referenced by smtrat::Module::probablyLooping().
template<class Settings> FormulasT smtrat::GroebnerModule< Settings >::mGbEqualities protected
A workaround to associate equalities in the passed formula originating from the gb (in contrast to those which originate from simplified formulae)
Definition at line 77 of file GroebnerModule.h.
template<class Settings> InequalitiesTable<Settings> smtrat::GroebnerModule< Settings >::mInequalities protected
The inequalities table for handling inequalities.
Definition at line 58 of file GroebnerModule.h.
std::vector<FormulasT> smtrat::Module::mInfeasibleSubsets protected inherited
Stores the infeasible subsets.
Definition at line 135 of file Module.h.
Referenced by smtrat::CADModule::addCore(), smtrat::ICPModule::addCore(), smtrat::CADModule::CADModule(), smtrat::ICPModule::callBackends(), smtrat::CNFerModule::checkCore(), smtrat::CADModule::checkCore(), smtrat::ICPModule::checkCore(), smtrat::Module::checkCore(), smtrat::Module::getInfeasibleSubsets(), smtrat::Module::hasValidInfeasibleSubset(), smtrat::Module::infeasibleSubsets(), smtrat::Module::printInfeasibleSubsets(), smtrat::ICPModule::remapAndSetLraInfeasibleSubsets(), and smtrat::Module::remove().
vector< Branching > Module::mLastBranches static inherited
Stores the last branches in a cycle buffer.
Definition at line 190 of file Module.h.
Referenced by smtrat::Module::probablyLooping().
Model smtrat::Module::mModel mutable protected inherited
Stores the assignment of the current satisfiable result, if existent.
Definition at line 139 of file Module.h.
Referenced by smtrat::Module::checkModel(), smtrat::Module::getBackendsModel(), smtrat::Module::getModelEqualities(), smtrat::Module::model(), smtrat::CADModule::updateModel(), and smtrat::ICPModule::updateModel().
template<class Settings> std::list<typename InequalitiesTable<Settings>::Rows::iterator> smtrat::GroebnerModule< Settings >::mNewInequalities protected
A list of inequalities which were added after the last consistency check.
Definition at line 66 of file GroebnerModule.h.
size_t Module::mNumOfBranchVarsToStore static inherited
The number of different variables to consider for a probable infinite loop of branchings.
Definition at line 188 of file Module.h.
Manager* const smtrat::Module::mpManager protected inherited
A reference to the manager.
Definition at line 137 of file Module.h.
Referenced by smtrat::CADModule::checkCore(), smtrat::Module::checkInfSubsetForMinimality(), smtrat::Module::eraseSubformulaFromPassedFormula(), smtrat::Module::foundAnswer(), smtrat::Module::init(), and smtrat::Module::runBackends().
template<class Settings> bool smtrat::GroebnerModule< Settings >::mRecalculateGB protected
After popping in the history, it might be necessary to recalculate. This flag indicates this.
Definition at line 64 of file GroebnerModule.h.
template<class Settings> groebner::RewriteRules smtrat::GroebnerModule< Settings >::mRewriteRules protected
The rewrite rules for the variables.
Definition at line 70 of file GroebnerModule.h.
template<class Settings> GBRuntimeSettings* smtrat::GroebnerModule< Settings >::mRuntimeSettings protected
An reference to the RuntimeSettings.
Definition at line 68 of file GroebnerModule.h.
template<class Settings> std::list<GroebnerModuleState<Settings> > smtrat::GroebnerModule< Settings >::mStateHistory protected
Saves the relevant history to support backtracking.
Definition at line 62 of file GroebnerModule.h.
set< string > Module::mVariablesInAssumptionToCheck static inherited
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
Definition at line 186 of file Module.h.
Referenced by smtrat::Module::addAssumptionToCheck().
The documentation for this singleton was generated from the following file:
lib/modules/GBModule/GroebnerModule.h