SMT-RAT: smtrat::ExplanationGenerator Class Reference
smtrat::ExplanationGenerator Class Reference
#include <ExplanationGenerator.h>
Data Structures
struct ProjectionSettings
Public Member Functions
ExplanationGenerator (const std::vector< ConstraintT > &constraints, const std::vector< carl::Variable > &vars, const Model &model)
mProjection (mCADConstraints)
mModel (model)
FormulaT generateExplanation (const ConstraintT &reason)
Data Fields
const auto & p
const auto std::size_t cid
const auto std::size_t bool isBound
Private Types
using RAN = carl::RealAlgebraicNumber< Rational >
Private Member Functions
bool isEqual (const RAN &ran, const ModelValue &mv) const
bool isGreater (const RAN &ran, const ModelValue &mv) const
template<typename MV >
FormulaT buildEquality (carl::Variable v, const MV &mv) const
template<typename MV >
FormulaT buildBelow (carl::Variable v, const MV &right) const
template<typename MV >
FormulaT buildBetween (carl::Variable v, const MV &left, const MV &right) const
template<typename MV >
FormulaT buildAbove (carl::Variable v, const MV &left) const
FormulaT generateBoundsFor (carl::Variable var, std::size_t level, const Model &model)
Private Attributes
std::vector< ConstraintT > mConstraints
cad::CADConstraints
< ProjectionSettings::backtracking > mCADConstraints
cad::ProjectionT
< ProjectionSettings > mProjection
Model mModel
carl::Variable mTmpVar
Detailed Description
Definition at line 11 of file ExplanationGenerator.h.
Member Typedef Documentation
using smtrat::ExplanationGenerator::RAN = carl::RealAlgebraicNumber<Rational> private
Definition at line 13 of file ExplanationGenerator.h.
Constructor & Destructor Documentation
smtrat::ExplanationGenerator::ExplanationGenerator (const std::vector< ConstraintT > & constraints, const std::vector< carl::Variable > & vars, const Model & model) inline
Definition at line 85 of file ExplanationGenerator.h.
Member Function Documentation
template<typename MV > FormulaT smtrat::ExplanationGenerator::buildAbove (carl::Variable v, const MV & left) const inline private
Definition at line 50 of file ExplanationGenerator.h.
Referenced by buildBetween(), and generateBoundsFor().
template<typename MV > FormulaT smtrat::ExplanationGenerator::buildBelow (carl::Variable v, const MV & right) const inline private
Definition at line 42 of file ExplanationGenerator.h.
Referenced by buildBetween(), and generateBoundsFor().
template<typename MV > FormulaT smtrat::ExplanationGenerator::buildBetween (carl::Variable v, const MV & left, const MV & right) const inline private
Definition at line 46 of file ExplanationGenerator.h.
Referenced by generateBoundsFor().
template<typename MV > FormulaT smtrat::ExplanationGenerator::buildEquality (carl::Variable v, const MV & mv) const inline private
Definition at line 38 of file ExplanationGenerator.h.
Referenced by generateBoundsFor().
FormulaT smtrat::ExplanationGenerator::generateBoundsFor (carl::Variable var, std::size_t level, const Model & model) inline private
Definition at line 54 of file ExplanationGenerator.h.
Referenced by generateExplanation().
FormulaT smtrat::ExplanationGenerator::generateExplanation (const ConstraintT & reason) inline
Definition at line 103 of file ExplanationGenerator.h.
bool smtrat::ExplanationGenerator::isEqual (const RAN & ran, const ModelValue & mv) const inline private
Definition at line 25 of file ExplanationGenerator.h.
Referenced by generateBoundsFor().
bool smtrat::ExplanationGenerator::isGreater (const RAN & ran, const ModelValue & mv) const inline private
Definition at line 31 of file ExplanationGenerator.h.
Referenced by generateBoundsFor().
smtrat::ExplanationGenerator::mModel (model) inline
Definition at line 92 of file ExplanationGenerator.h.
smtrat::ExplanationGenerator::mProjection (mCADConstraints)
Field Documentation
const auto std::size_t smtrat::ExplanationGenerator::cid
Definition at line 88 of file ExplanationGenerator.h.
const auto std::size_t bool smtrat::ExplanationGenerator::isBound
Definition at line 89 of file ExplanationGenerator.h.
cad::CADConstraints<ProjectionSettings::backtracking> smtrat::ExplanationGenerator::mCADConstraints private
Definition at line 20 of file ExplanationGenerator.h.
Referenced by generateExplanation(), and mModel().
std::vector<ConstraintT> smtrat::ExplanationGenerator::mConstraints private
Definition at line 19 of file ExplanationGenerator.h.
Referenced by mModel().
Model smtrat::ExplanationGenerator::mModel private
Definition at line 22 of file ExplanationGenerator.h.
Referenced by generateBoundsFor(), and generateExplanation().
cad::ProjectionT<ProjectionSettings> smtrat::ExplanationGenerator::mProjection private
Definition at line 21 of file ExplanationGenerator.h.
Referenced by generateBoundsFor(), and mModel().
carl::Variable smtrat::ExplanationGenerator::mTmpVar private
Definition at line 23 of file ExplanationGenerator.h.
Referenced by buildAbove(), buildBelow(), buildEquality(), and generateBoundsFor().
const auto& smtrat::ExplanationGenerator::p
Definition at line 88 of file ExplanationGenerator.h.
The documentation for this class was generated from the following file:
lib/datastructures/ExplanationGenerator.h