SMT-RAT: vs::SqrtEx Class Reference
vs::SqrtEx Class Reference
#include <SqrtEx.h>
Public Member Functions
SqrtEx ()
Default Constructor.
SqrtEx (smtrat::Poly &&_poly)
Constructs a square root expression from a polynomial p leading to (p + 0 * sqrt(0)) / 1.
SqrtEx (const smtrat::Poly &_poly)
SqrtEx (carl::Variable::Arg _var)
template<typename P = smtrat::Poly, typename = typename std::enable_if<carl::needs_cache<P>::value>::type>
SqrtEx (typename P::PolyType &&_poly)
SqrtEx (const smtrat::Poly &_constantPart, const smtrat::Poly &_factor, const smtrat::Poly &_denominator, const smtrat::Poly &_radicand)
Constructs a square root expression from given constant part, factor, denominator and radicand.
SqrtEx (smtrat::Poly &&_constantPart, smtrat::Poly &&_factor, smtrat::Poly &&_denominator, smtrat::Poly &&_radicand)
const smtrat::Poly & constantPart () const
const smtrat::Poly & factor () const
const smtrat::Poly & denominator () const
const smtrat::Poly & radicand () const
bool hasSqrt () const
bool isPolynomial () const
smtrat::Poly asPolynomial () const
bool isConstant () const
smtrat::Rational asConstant () const
bool isRational () const
smtrat::Rational asRational () const
bool isInteger () const
bool operator== (const SqrtEx &_toCompareWith) const
SqrtEx & operator= (const SqrtEx &_sqrtEx)
SqrtEx & operator= (const smtrat::Poly &_poly)
std::string toString (bool _infix=false, bool _friendlyNames=true) const
bool evaluate (smtrat::Rational &_result, const smtrat::EvalRationalMap &_evalMap, int _rounding=0) const
SqrtEx substitute (const smtrat::EvalRationalMap &_evalMap) const
Static Public Member Functions
static SqrtEx subBySqrtEx (const smtrat::Poly &_substituteIn, const carl::Variable &_varToSubstitute, const SqrtEx &_substituteBy)
Substitutes a variable in an expression by a square root expression, which results in a square root expression.
Private Member Functions
void normalize ()
Normalizes this object, that is extracts as much as possible from the radicand into the factor and cancels the enumerator and denominator afterwards.
Private Attributes
smtrat::Poly mConstantPart
The constant part c of this square root expression (c + f * sqrt(r))/d.
smtrat::Poly mFactor
The factor f of this square root expression (c + f * sqrt(r))/d.
smtrat::Poly mDenominator
The denominator d of this square root expression (c + f * sqrt(r))/d.
smtrat::Poly mRadicand
The radicand r of this square root expression (c + f * sqrt(r))/d.
Friends
SqrtEx operator+ (const SqrtEx &_summandA, const SqrtEx &_summandB)
SqrtEx operator- (const SqrtEx &_minuend, const SqrtEx &_subtrahend)
SqrtEx operator* (const SqrtEx &_factorA, const SqrtEx &_factorB)
SqrtEx operator/ (const SqrtEx &_dividend, const SqrtEx &_divisor)
std::ostream & operator<< (std::ostream &_out, const SqrtEx &_sqrtEx)
Prints the given square root expression on the given stream.
Detailed Description
Definition at line 16 of file SqrtEx.h.
Constructor & Destructor Documentation
vs::SqrtEx::SqrtEx ()
Default Constructor.
(constructs (0 + 0 * sqrt(0)) / 1)
Definition at line 14 of file SqrtEx.cpp.
Referenced by subBySqrtEx(), and substitute().
vs::SqrtEx::SqrtEx (smtrat::Poly && _poly)
Constructs a square root expression from a polynomial p leading to (p + 0 * sqrt(0)) / 1.
Parameters
_poly The polynomial to construct a square root expression for.
Definition at line 21 of file SqrtEx.cpp.
vs::SqrtEx::SqrtEx (const smtrat::Poly & _poly) inline
Definition at line 39 of file SqrtEx.h.
vs::SqrtEx::SqrtEx (carl::Variable::Arg _var) inline
Definition at line 43 of file SqrtEx.h.
template<typename P = smtrat::Poly, typename = typename std::enable_if<carl::needs_cache<P>::value>::type> vs::SqrtEx::SqrtEx (typename P::PolyType && _poly) inline
Definition at line 48 of file SqrtEx.h.
vs::SqrtEx::SqrtEx (const smtrat::Poly & _constantPart, const smtrat::Poly & _factor, const smtrat::Poly & _denominator, const smtrat::Poly & _radicand) inline
Constructs a square root expression from given constant part, factor, denominator and radicand.
Parameters
_constantPart The constant part of the square root expression to construct.
_factor The factor of the square root expression to construct.
_denominator The denominator of the square root expression to construct.
_radicand The radicand of the square root expression to construct.
Definition at line 58 of file SqrtEx.h.
vs::SqrtEx::SqrtEx (smtrat::Poly && _constantPart, smtrat::Poly && _factor, smtrat::Poly && _denominator, smtrat::Poly && _radicand)
Definition at line 30 of file SqrtEx.cpp.
Member Function Documentation
smtrat::Rational vs::SqrtEx::asConstant () const inline
Returns
This sqrtEx as an integer (note, that it must actually represent an integer then).
Definition at line 136 of file SqrtEx.h.
Referenced by asRational().
smtrat::Poly vs::SqrtEx::asPolynomial () const inline
Returns
The square root expression as a polynomial (note that there must be no square root nor denominator
Definition at line 117 of file SqrtEx.h.
smtrat::Rational vs::SqrtEx::asRational () const inline
Returns
This sqrtEx as a rational (note, that it must actually represent a rational then).
Definition at line 154 of file SqrtEx.h.
const smtrat::Poly& vs::SqrtEx::constantPart () const inline
Returns
A constant reference to the constant part of this square root expression.
Definition at line 67 of file SqrtEx.h.
Referenced by vs::State::addChild(), evaluate(), isInteger(), normalize(), std::hash< vs::SqrtEx >::operator()(), vs::operator*(), vs::operator+(), vs::operator-(), vs::operator/(), operator=(), operator==(), subBySqrtEx(), substitute(), vs::substituteNormal(), vs::Substitution::termVariables(), vs::State::updateIntTestCandidates(), and vs::State::updateOCondsOfSubstitutions().
const smtrat::Poly& vs::SqrtEx::denominator () const inline
Returns
A constant reference to the denominator of this square root expression.
Definition at line 83 of file SqrtEx.h.
Referenced by evaluate(), isInteger(), normalize(), std::hash< vs::SqrtEx >::operator()(), vs::operator*(), vs::operator+(), vs::operator-(), vs::operator/(), operator=(), operator==(), smtrat::VSModule< Settings >::solutionInDomain(), subBySqrtEx(), substitute(), vs::substituteNormal(), and vs::Substitution::termVariables().
bool vs::SqrtEx::evaluate (smtrat::Rational & _result, const smtrat::EvalRationalMap & _evalMap, int _rounding = 0) const
Definition at line 281 of file SqrtEx.cpp.
Referenced by smtrat::VSModule< Settings >::solutionInDomain().
const smtrat::Poly& vs::SqrtEx::factor () const inline
Returns
A constant reference to the factor of this square root expression.
Definition at line 75 of file SqrtEx.h.
Referenced by evaluate(), normalize(), std::hash< vs::SqrtEx >::operator()(), vs::operator*(), vs::operator+(), vs::operator-(), vs::operator/(), operator=(), operator==(), subBySqrtEx(), substitute(), vs::substituteNormal(), and vs::Substitution::termVariables().
bool vs::SqrtEx::hasSqrt () const inline
Returns
true, if the square root expression has a non trivial radicand; false, otherwise.
Definition at line 100 of file SqrtEx.h.
Referenced by vs::operator*(), vs::operator+(), vs::operator-(), vs::operator/(), vs::substituteNormal(), and toString().
bool vs::SqrtEx::isConstant () const inline
Returns
true, if there is no variable in this square root expression; false, otherwise.
Definition at line 128 of file SqrtEx.h.
Referenced by asConstant(), and asRational().
bool vs::SqrtEx::isInteger () const inline
Returns
true, if the this square root expression corresponds to an integer value; false, otherwise.
Definition at line 176 of file SqrtEx.h.
Referenced by vs::State::addChild(), and vs::State::updateOCondsOfSubstitutions().
bool vs::SqrtEx::isPolynomial () const inline
Returns
true, if the square root expression can be expressed as a polynomial; false, otherwise.
Definition at line 109 of file SqrtEx.h.
Referenced by asPolynomial().
bool vs::SqrtEx::isRational () const inline
Returns
true, if there is no variable in this square root expression; false, otherwise.
Definition at line 146 of file SqrtEx.h.
Referenced by asRational().
void vs::SqrtEx::normalize () private
Normalizes this object, that is extracts as much as possible from the radicand into the factor and cancels the enumerator and denominator afterwards.
Definition at line 43 of file SqrtEx.cpp.
Referenced by SqrtEx().
SqrtEx & vs::SqrtEx::operator= (const SqrtEx & _sqrtEx)
Parameters
_sqrtEx A square root expression, which gets the new content of this square root expression.
Returns
A reference to this object.
Definition at line 161 of file SqrtEx.cpp.
SqrtEx & vs::SqrtEx::operator= (const smtrat::Poly & _poly)
Parameters
_poly A polynomial, which gets the new content of this square root expression.
Returns
A reference to this object.
Definition at line 176 of file SqrtEx.cpp.
bool vs::SqrtEx::operator== (const SqrtEx & _toCompareWith) const
Parameters
_sqrtEx Square root expression to compare with.
Returns
true, if this square root expression and the given one are equal; false, otherwise.
Definition at line 155 of file SqrtEx.cpp.
const smtrat::Poly& vs::SqrtEx::radicand () const inline
Returns
A constant reference to the radicand of this square root expression.
Definition at line 91 of file SqrtEx.h.
Referenced by evaluate(), isInteger(), normalize(), std::hash< vs::SqrtEx >::operator()(), vs::operator*(), vs::operator+(), vs::operator-(), vs::operator/(), operator=(), operator==(), subBySqrtEx(), substitute(), vs::substituteNormal(), and vs::Substitution::termVariables().
SqrtEx vs::SqrtEx::subBySqrtEx (const smtrat::Poly & _substituteIn, const carl::Variable & _varToSubstitute, const SqrtEx & _substituteBy) static
Substitutes a variable in an expression by a square root expression, which results in a square root expression.
Parameters
_substituteIn The polynomial to substitute in.
_varToSubstitute The variable to substitute.
_substituteBy The square root expression by which the variable gets substituted.
Returns
The resulting square root expression.
Definition at line 365 of file SqrtEx.cpp.
SqrtEx vs::SqrtEx::substitute (const smtrat::EvalRationalMap & _evalMap) const
Definition at line 347 of file SqrtEx.cpp.
Referenced by smtrat::VSModule< Settings >::updateModel().
string vs::SqrtEx::toString (bool _infix = false, bool _friendlyNames = true) const
Parameters
_infix A string which is printed in the beginning of each row.
_friendlyNames A flag that indicates whether to print the variables with their internal representation (false) or with their dedicated names.
Returns
The string representation of this square root expression.
Definition at line 225 of file SqrtEx.cpp.
Referenced by vs::operator<<(), and vs::Substitution::toString().
Friends And Related Function Documentation
SqrtEx operator* (const SqrtEx & _factorA, const SqrtEx & _factorB) friend
Parameters
_factorA First factor.
_factorB Second factor.
Returns
The product of the given square root expressions.
Definition at line 203 of file SqrtEx.cpp.
SqrtEx operator+ (const SqrtEx & _summandA, const SqrtEx & _summandB) friend
Parameters
_summandA First summand.
_summandB Second summand.
Returns
The sum of the given square root expressions.
Definition at line 185 of file SqrtEx.cpp.
SqrtEx operator- (const SqrtEx & _minuend, const SqrtEx & _subtrahend) friend
Parameters
_minuend Minuend.
_subtrahend Subtrahend.
Returns
The difference of the given square root expressions.
Definition at line 194 of file SqrtEx.cpp.
SqrtEx operator/ (const SqrtEx & _dividend, const SqrtEx & _divisor) friend
Parameters
_dividend Dividend.
_divisor Divisor.
Returns
The result of the first given square root expression divided by the second one Note that the second argument is not allowed to contain a square root.
Definition at line 212 of file SqrtEx.cpp.
std::ostream& operator<< (std::ostream & _out, const SqrtEx & _sqrtEx) friend
Prints the given square root expression on the given stream.
Parameters
_out The stream to print on.
_sqrtEx The square root expression to print.
Returns
The stream after printing the square root expression on it.
Definition at line 220 of file SqrtEx.cpp.
Field Documentation
smtrat::Poly vs::SqrtEx::mConstantPart private
The constant part c of this square root expression (c + f * sqrt(r))/d.
Definition at line 20 of file SqrtEx.h.
Referenced by asConstant(), asPolynomial(), asRational(), constantPart(), isConstant(), isRational(), normalize(), operator=(), operator==(), and toString().
smtrat::Poly vs::SqrtEx::mDenominator private
The denominator d of this square root expression (c + f * sqrt(r))/d.
Definition at line 24 of file SqrtEx.h.
Referenced by asPolynomial(), denominator(), isConstant(), isPolynomial(), isRational(), normalize(), operator=(), operator==(), SqrtEx(), and toString().
smtrat::Poly vs::SqrtEx::mFactor private
The factor f of this square root expression (c + f * sqrt(r))/d.
Definition at line 22 of file SqrtEx.h.
Referenced by asRational(), factor(), hasSqrt(), isConstant(), isPolynomial(), normalize(), operator=(), operator==(), and toString().
smtrat::Poly vs::SqrtEx::mRadicand private
The radicand r of this square root expression (c + f * sqrt(r))/d.
Definition at line 26 of file SqrtEx.h.
Referenced by isConstant(), isRational(), normalize(), operator=(), operator==(), radicand(), SqrtEx(), and toString().
The documentation for this class was generated from the following files:
lib/datastructures/vs/SqrtEx.h
lib/datastructures/vs/SqrtEx.cpp