SMT-RAT: smtrat::FouMoStatistics Class Reference
smtrat::FouMoStatistics Class Reference
#include <FouMoStatistics.h>
Public Member Functions
void collect ()
void foo ()
FouMoStatistics (const std::string &_statisticName)
~FouMoStatistics ()
void print (std::ostream &_out=std::cout, bool _smtlib=false, size_t _maxNameLength=0, size_t _maxKeyLength=0)
void generateXML (std::stringstream &filestream)
size_t maxKeyLength () const
const std::string & name () const
Protected Member Functions
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
Private Attributes
size_t mExampleStatistic
Example for a statistic.
Detailed Description
Definition at line 38 of file FouMoStatistics.h.
Constructor & Destructor Documentation
smtrat::FouMoStatistics::FouMoStatistics (const std::string & _statisticName) inline
Definition at line 59 of file FouMoStatistics.h.
smtrat::FouMoStatistics::~FouMoStatistics () inline
Definition at line 64 of file FouMoStatistics.h.
Member Function Documentation
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 97 of file Statistics.h.
Referenced by smtrat::Statistics::addKeyValuePair(), smtrat::CADStatistics::collect(), smtrat::GBCalculationStats::collect(), smtrat::GeneralStatistics::collect(), smtrat::SATModuleStatistics::collect(), smtrat::GroebnerModuleStats::collect(), smtrat::IntEqStatistics::collect(), smtrat::ReduceCNFStatistics::collect(), smtrat::BVStatistics::collect(), collect(), and smtrat::LRAModuleStatistics::collect().
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 104 of file Statistics.h.
void smtrat::FouMoStatistics::collect () inline virtual
Reimplemented from smtrat::Statistics.
Definition at line 49 of file FouMoStatistics.h.
void smtrat::FouMoStatistics::foo () inline
Definition at line 54 of file FouMoStatistics.h.
void smtrat::Statistics::generateXML (std::stringstream & filestream) inline inherited
Definition at line 70 of file Statistics.h.
size_t smtrat::Statistics::maxKeyLength () const inline inherited
Definition at line 80 of file Statistics.h.
const std::string& smtrat::Statistics::name () const inline inherited
Definition at line 85 of file Statistics.h.
void smtrat::Statistics::print (std::ostream & _out = std::cout, bool _smtlib = false, size_t _maxNameLength = 0, size_t _maxKeyLength = 0) inline inherited
Definition at line 36 of file Statistics.h.
Field Documentation
size_t smtrat::FouMoStatistics::mExampleStatistic private
Example for a statistic.
Definition at line 45 of file FouMoStatistics.h.
Referenced by foo().
The documentation for this class was generated from the following file:
lib/modules/FouMoModule/FouMoStatistics.h