SMT-RAT: smtrat::formula_rewriter< RewriterType > Class Template Reference
smtrat::formula_rewriter< RewriterType > Class Template Reference
#include <FormulaVisitor.hpp>
Public Types
typedef FormulaT result_type
typedef FormulaSetT::value_compare compare_type
typedef FormulaSetT::allocator_type allocator_type
Public Member Functions
template<typename... Args>
formula_rewriter (Args &&...args)
RewriterType & get () noexcept
const RewriterType & get () const noexcept
FormulaT apply (const FormulaT &formula)
Private Types
typedef formula_visitor
< formula_rewriter
< RewriterType >, FormulaT,
typename
FormulaSetT::value_compare,
typename
FormulaSetT::allocator_type > super_type
typedef super_type::set_type set_type
typedef super_type::multiset_type multiset_type
Private Member Functions
SMTRAT_HAS_DECL (rewrite_default)
SMTRAT_HAS_DECL (rewrite_or)
SMTRAT_HAS_DECL (rewrite_and)
SMTRAT_HAS_DECL (rewrite_iff)
SMTRAT_HAS_DECL (rewrite_xor)
SMTRAT_HAS_DECL (rewrite_not)
SMTRAT_HAS_DECL (rewrite_exists)
SMTRAT_HAS_DECL (rewrite_forall)
SMTRAT_HAS_DECL (rewrite_implication)
SMTRAT_HAS_DECL (rewrite_ite)
SMTRAT_HAS_DECL (rewrite_true)
SMTRAT_HAS_DECL (rewrite_false)
SMTRAT_HAS_DECL (rewrite_bool)
SMTRAT_HAS_DECL (rewrite_ueq)
SMTRAT_HAS_DECL (rewrite_constraint)
SMTRAT_HAS_DECL (rewrite_quantified)
SMTRAT_HAS_DECL (rewrite_leaf)
SMTRAT_HAS_DECL (enter_default)
SMTRAT_HAS_DECL (enter_or)
SMTRAT_HAS_DECL (enter_and)
SMTRAT_HAS_DECL (enter_iff)
SMTRAT_HAS_DECL (enter_xor)
SMTRAT_HAS_DECL (enter_not)
SMTRAT_HAS_DECL (enter_exists)
SMTRAT_HAS_DECL (enter_forall)
SMTRAT_HAS_DECL (enter_implication)
SMTRAT_HAS_DECL (enter_ite)
SMTRAT_HAS_DECL (enter_true)
SMTRAT_HAS_DECL (enter_false)
SMTRAT_HAS_DECL (enter_bool)
SMTRAT_HAS_DECL (enter_ueq)
SMTRAT_HAS_DECL (enter_constraint)
SMTRAT_HAS_DECL (enter_quantified)
SMTRAT_HAS_DECL (enter_leaf)
template<typename = void>
FormulaT P_visit_or (const FormulaT &formula, set_type &&subformulas, std::true_type)
template<typename = void>
FormulaT P_visit_or (const FormulaT &formula, set_type &&subformulas, std::false_type)
FormulaT visit_or (const FormulaT &formula, set_type &&subformulas)
template<typename = void>
FormulaT P_visit_and (const FormulaT &formula, set_type &&subformulas, std::true_type)
template<typename = void>
FormulaT P_visit_and (const FormulaT &formula, set_type &&subformulas, std::false_type)
FormulaT visit_and (const FormulaT &formula, set_type &&subformulas)
template<typename = void>
FormulaT P_visit_iff (const FormulaT &formula, set_type &&subformulas, std::true_type)
template<typename = void>
FormulaT P_visit_iff (const FormulaT &formula, set_type &&subformulas, std::false_type)
FormulaT visit_iff (const FormulaT &formula, set_type &&subformulas)
template<typename = void>
FormulaT P_visit_xor (const FormulaT &formula, multiset_type &&subformulas, std::true_type)
template<typename = void>
FormulaT P_visit_xor (const FormulaT &formula, multiset_type &&subformulas, std::false_type)
FormulaT visit_xor (const FormulaT &formula, multiset_type &&subformulas)
template<typename = void>
FormulaT P_visit_not (const FormulaT &formula, FormulaT &&subformula, std::true_type)
template<typename = void>
FormulaT P_visit_not (const FormulaT &formula, FormulaT &&subformula, std::false_type)
FormulaT visit_not (const FormulaT &formula, FormulaT &&subformula)
template<typename = void>
FormulaT P_visit_quantified (const FormulaT &formula, FormulaT &&subformula, std::true_type)
template<typename = void>
FormulaT P_visit_quantified (const FormulaT &formula, FormulaT &&subformula, std::false_type)
FormulaT P_visit_quantified (const FormulaT &formula, FormulaT &&subformula)
template<typename = void>
FormulaT P_visit_exists (const FormulaT &formula, FormulaT &&subformula, std::true_type)
template<typename = void>
FormulaT P_visit_exists (const FormulaT &formula, FormulaT &&subformula, std::false_type)
FormulaT visit_exists (const FormulaT &formula, FormulaT &&subformula)
template<typename = void>
FormulaT P_visit_forall (const FormulaT &formula, FormulaT &&subformula, std::true_type)
template<typename = void>
FormulaT P_visit_forall (const FormulaT &formula, FormulaT &&subformula, std::false_type)
FormulaT visit_forall (const FormulaT &formula, FormulaT &&subformula)
template<typename = void>
FormulaT P_visit_implication (const FormulaT &formula, FormulaT &&premise, FormulaT &&conclusion, std::true_type)
template<typename = void>
FormulaT P_visit_implication (const FormulaT &formula, FormulaT &&premise, FormulaT &&conclusion, std::false_type)
FormulaT visit_implication (const FormulaT &formula, FormulaT &&premise, FormulaT &&conclusion)
template<typename = void>
FormulaT P_visit_ite (const FormulaT &formula, FormulaT &&condition, FormulaT &&then, FormulaT &&else_, std::true_type)
template<typename = void>
FormulaT P_visit_ite (const FormulaT &formula, FormulaT &&condition, FormulaT &&then, FormulaT &&else_, std::false_type)
FormulaT visit_ite (const FormulaT &formula, FormulaT &&condition, FormulaT &&trueCase, FormulaT &&falseCase)
template<typename = void>
FormulaT P_visit_leaf (const FormulaT &formula, std::true_type)
template<typename = void>
FormulaT P_visit_leaf (const FormulaT &formula, std::false_type)
FormulaT P_visit_leaf (const FormulaT &formula)
template<typename = void>
FormulaT P_visit_true (const FormulaT &formula, std::true_type)
template<typename = void>
FormulaT P_visit_true (const FormulaT &formula, std::false_type)
FormulaT visit_true (const FormulaT &formula)
template<typename = void>
FormulaT P_visit_false (const FormulaT &formula, std::true_type)
template<typename = void>
FormulaT P_visit_false (const FormulaT &formula, std::false_type)
FormulaT visit_false (const FormulaT &formula)
template<typename = void>
FormulaT P_visit_bool (const FormulaT &formula, std::true_type)
template<typename = void>
FormulaT P_visit_bool (const FormulaT &formula, std::false_type)
FormulaT visit_bool (const FormulaT &formula)
template<typename = void>
FormulaT P_visit_ueq (const FormulaT &formula, std::true_type)
template<typename = void>
FormulaT P_visit_ueq (const FormulaT &formula, std::false_type)
FormulaT visit_ueq (const FormulaT &formula)
template<typename = void>
FormulaT P_visit_constraint (const FormulaT &formula, std::true_type)
template<typename = void>
FormulaT P_visit_constraint (const FormulaT &formula, std::false_type)
FormulaT visit_constraint (const FormulaT &formula)
template<typename = void>
void P_enter_default (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_default (const FormulaT &, std::false_type)
void P_enter_default (const FormulaT &formula)
template<typename = void>
void P_enter_or (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_or (const FormulaT &formula, std::false_type)
void enter_or (const FormulaT &formula)
template<typename = void>
void P_enter_and (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_and (const FormulaT &formula, std::false_type)
void enter_and (const FormulaT &formula)
template<typename = void>
void P_enter_iff (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_iff (const FormulaT &formula, std::false_type)
void enter_iff (const FormulaT &formula)
template<typename = void>
void P_enter_xor (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_xor (const FormulaT &formula, std::false_type)
void enter_xor (const FormulaT &formula)
template<typename = void>
void P_enter_not (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_not (const FormulaT &formula, std::false_type)
void enter_not (const FormulaT &formula)
template<typename = void>
void P_enter_quantified (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_quantified (const FormulaT &formula, std::false_type)
void P_enter_quantified (const FormulaT &formula)
template<typename = void>
void P_enter_exists (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_exists (const FormulaT &formula, std::false_type)
void enter_exists (const FormulaT &formula)
template<typename = void>
void P_enter_forall (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_forall (const FormulaT &formula, std::false_type)
void enter_forall (const FormulaT &formula)
template<typename = void>
void P_enter_implication (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_implication (const FormulaT &formula, std::false_type)
void enter_implication (const FormulaT &formula)
template<typename = void>
void P_enter_ite (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_ite (const FormulaT &formula, std::false_type)
void enter_ite (const FormulaT &formula)
template<typename = void>
void P_enter_leaf (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_leaf (const FormulaT &formula, std::false_type)
void P_enter_leaf (const FormulaT &formula)
template<typename = void>
void P_enter_true (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_true (const FormulaT &formula, std::false_type)
void enter_true (const FormulaT &formula)
template<typename = void>
void P_enter_false (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_false (const FormulaT &formula, std::false_type)
void enter_false (const FormulaT &formula)
template<typename = void>
void P_enter_bool (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_bool (const FormulaT &formula, std::false_type)
void enter_bool (const FormulaT &formula)
template<typename = void>
void P_enter_ueq (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_ueq (const FormulaT &formula, std::false_type)
void enter_ueq (const FormulaT &formula)
template<typename = void>
void P_enter_constraint (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_constraint (const FormulaT &formula, std::false_type)
void enter_constraint (const FormulaT &formula)
template<template< typename, typename, typename > class SetTemplate, typename C , typename A >
FormulaT P_rewrite_default (const FormulaT &formula, SetTemplate< FormulaT, C, A > &&subformulas)
FormulaT P_rewrite_default (const FormulaT &formula, const FormulaT &default_result)
template<typename = void>
FormulaT P_rewrite_default (const FormulaT &formula, const FormulaT &default_result, std::true_type)
template<typename = void>
FormulaT P_rewrite_default (const FormulaT &, const FormulaT &default_result, std::false_type)
Private Attributes
RewriterType mRewriter
Friends
class formula_visitor< formula_rewriter< RewriterType >, FormulaT, typename FormulaSetT::value_compare, typename FormulaSetT::allocator_type >
Detailed Description
template<typename RewriterType>
class smtrat::formula_rewriter< RewriterType >
Definition at line 961 of file FormulaVisitor.hpp.
Member Typedef Documentation
typedef FormulaSetT::allocator_type smtrat::formula_visitor< formula_rewriter< RewriterType > , FormulaT , FormulaSetT::value_compare , FormulaSetT::allocator_type >::allocator_type inherited
Definition at line 48 of file FormulaVisitor.hpp.
typedef FormulaSetT::value_compare smtrat::formula_visitor< formula_rewriter< RewriterType > , FormulaT , FormulaSetT::value_compare , FormulaSetT::allocator_type >::compare_type inherited
Definition at line 47 of file FormulaVisitor.hpp.
template<typename RewriterType> typedef super_type::multiset_type smtrat::formula_rewriter< RewriterType >::multiset_type private
Definition at line 995 of file FormulaVisitor.hpp.
typedef FormulaT smtrat::formula_visitor< formula_rewriter< RewriterType > , FormulaT , FormulaSetT::value_compare , FormulaSetT::allocator_type >::result_type inherited
Definition at line 46 of file FormulaVisitor.hpp.
template<typename RewriterType> typedef super_type::set_type smtrat::formula_rewriter< RewriterType >::set_type private
Definition at line 994 of file FormulaVisitor.hpp.
template<typename RewriterType> typedef formula_visitor< formula_rewriter<RewriterType>, FormulaT, typename FormulaSetT::value_compare, typename FormulaSetT::allocator_type > smtrat::formula_rewriter< RewriterType >::super_type private
Definition at line 992 of file FormulaVisitor.hpp.
Constructor & Destructor Documentation
template<typename RewriterType> template<typename... Args> smtrat::formula_rewriter< RewriterType >::formula_rewriter (Args &&... args) inline
Definition at line 970 of file FormulaVisitor.hpp.
Member Function Documentation
FormulaT smtrat::formula_visitor< formula_rewriter< RewriterType > , FormulaT , FormulaSetT::value_compare , FormulaSetT::allocator_type >::apply (const FormulaT & formula) inline inherited
Definition at line 54 of file FormulaVisitor.hpp.
Referenced by smtrat::EQPreprocessingModule< Settings >::apply_to_formula().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_and (const FormulaT & formula) inline private
Definition at line 1255 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_and().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_bool (const FormulaT & formula) inline private
Definition at line 1399 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_bool().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_constraint (const FormulaT & formula) inline private
Definition at line 1423 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_constraint().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_exists (const FormulaT & formula) inline private
Definition at line 1315 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_exists().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_false (const FormulaT & formula) inline private
Definition at line 1387 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_false().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_forall (const FormulaT & formula) inline private
Definition at line 1327 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_forall().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_iff (const FormulaT & formula) inline private
Definition at line 1267 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_iff().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_implication (const FormulaT & formula) inline private
Definition at line 1339 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_implication().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_ite (const FormulaT & formula) inline private
Definition at line 1351 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_ite().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_not (const FormulaT & formula) inline private
Definition at line 1291 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_not().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_or (const FormulaT & formula) inline private
Definition at line 1243 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_or().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_true (const FormulaT & formula) inline private
Definition at line 1375 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_true().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_ueq (const FormulaT & formula) inline private
Definition at line 1411 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_ueq().
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::enter_xor (const FormulaT & formula) inline private
Definition at line 1279 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_xor().
template<typename RewriterType> RewriterType& smtrat::formula_rewriter< RewriterType >::get () inline noexcept
Definition at line 974 of file FormulaVisitor.hpp.
Referenced by smtrat::EQPreprocessingModule< Settings >::P_rewrite_bool_domain().
template<typename RewriterType> const RewriterType& smtrat::formula_rewriter< RewriterType >::get () const inline noexcept
Definition at line 975 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_and (const FormulaT & formula, std::true_type) inline private
Definition at line 1247 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_and().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_and (const FormulaT & formula, std::false_type) inline private
Definition at line 1251 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_bool (const FormulaT & formula, std::true_type) inline private
Definition at line 1391 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_bool().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_bool (const FormulaT & formula, std::false_type) inline private
Definition at line 1395 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_constraint (const FormulaT & formula, std::true_type) inline private
Definition at line 1415 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_constraint().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_constraint (const FormulaT & formula, std::false_type) inline private
Definition at line 1419 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_default (const FormulaT & formula, std::true_type) inline private
Definition at line 1225 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_and(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_default(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_iff(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_implication(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_ite(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_leaf(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_not(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_or(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_quantified(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_xor().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_default (const FormulaT & , std::false_type) inline private
Definition at line 1229 of file FormulaVisitor.hpp.
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::P_enter_default (const FormulaT & formula) inline private
Definition at line 1231 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_exists (const FormulaT & formula, std::true_type) inline private
Definition at line 1307 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_exists().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_exists (const FormulaT & formula, std::false_type) inline private
Definition at line 1311 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_false (const FormulaT & formula, std::true_type) inline private
Definition at line 1379 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_false().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_false (const FormulaT & formula, std::false_type) inline private
Definition at line 1383 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_forall (const FormulaT & formula, std::true_type) inline private
Definition at line 1319 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_forall().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_forall (const FormulaT & formula, std::false_type) inline private
Definition at line 1323 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_iff (const FormulaT & formula, std::true_type) inline private
Definition at line 1259 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_iff().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_iff (const FormulaT & formula, std::false_type) inline private
Definition at line 1263 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_implication (const FormulaT & formula, std::true_type) inline private
Definition at line 1331 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_implication().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_implication (const FormulaT & formula, std::false_type) inline private
Definition at line 1335 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_ite (const FormulaT & formula, std::true_type) inline private
Definition at line 1343 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_ite().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_ite (const FormulaT & formula, std::false_type) inline private
Definition at line 1347 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_leaf (const FormulaT & formula, std::true_type) inline private
Definition at line 1355 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_bool(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_constraint(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_false(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_leaf(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_true(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_ueq().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_leaf (const FormulaT & formula, std::false_type) inline private
Definition at line 1359 of file FormulaVisitor.hpp.
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::P_enter_leaf (const FormulaT & formula) inline private
Definition at line 1363 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_not (const FormulaT & formula, std::true_type) inline private
Definition at line 1283 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_not().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_not (const FormulaT & formula, std::false_type) inline private
Definition at line 1287 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_or (const FormulaT & formula, std::true_type) inline private
Definition at line 1235 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_or().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_or (const FormulaT & formula, std::false_type) inline private
Definition at line 1239 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_quantified (const FormulaT & formula, std::true_type) inline private
Definition at line 1295 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_exists(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_forall(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_quantified().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_quantified (const FormulaT & formula, std::false_type) inline private
Definition at line 1299 of file FormulaVisitor.hpp.
template<typename RewriterType> void smtrat::formula_rewriter< RewriterType >::P_enter_quantified (const FormulaT & formula) inline private
Definition at line 1303 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_true (const FormulaT & formula, std::true_type) inline private
Definition at line 1367 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_true().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_true (const FormulaT & formula, std::false_type) inline private
Definition at line 1371 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_ueq (const FormulaT & formula, std::true_type) inline private
Definition at line 1403 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_ueq().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_ueq (const FormulaT & formula, std::false_type) inline private
Definition at line 1407 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_xor (const FormulaT & formula, std::true_type) inline private
Definition at line 1271 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::enter_xor().
template<typename RewriterType> template<typename = void> void smtrat::formula_rewriter< RewriterType >::P_enter_xor (const FormulaT & formula, std::false_type) inline private
Definition at line 1275 of file FormulaVisitor.hpp.
template<typename RewriterType> template<template< typename, typename, typename > class SetTemplate, typename C , typename A > FormulaT smtrat::formula_rewriter< RewriterType >::P_rewrite_default (const FormulaT & formula, SetTemplate< FormulaT, C, A > && subformulas) inline private
Definition at line 1428 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::P_rewrite_default(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_and(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_iff(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_implication(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_ite(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_leaf(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_not(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_or(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_quantified(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_xor().
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::P_rewrite_default (const FormulaT & formula, const FormulaT & default_result) inline private
Definition at line 1433 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_rewrite_default (const FormulaT & formula, const FormulaT & default_result, std::true_type) inline private
Definition at line 1437 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_rewrite_default (const FormulaT & , const FormulaT & default_result, std::false_type) inline private
Definition at line 1441 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_and (const FormulaT & formula, set_type && subformulas, std::true_type) inline private
Definition at line 1045 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_and().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_and (const FormulaT & formula, set_type && subformulas, std::false_type) inline private
Definition at line 1049 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_bool (const FormulaT & formula, std::true_type) inline private
Definition at line 1189 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_bool().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_bool (const FormulaT & formula, std::false_type) inline private
Definition at line 1193 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_constraint (const FormulaT & formula, std::true_type) inline private
Definition at line 1213 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_constraint().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_constraint (const FormulaT & formula, std::false_type) inline private
Definition at line 1217 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_exists (const FormulaT & formula, FormulaT && subformula, std::true_type) inline private
Definition at line 1105 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_exists().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_exists (const FormulaT & formula, FormulaT && subformula, std::false_type) inline private
Definition at line 1109 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_false (const FormulaT & formula, std::true_type) inline private
Definition at line 1177 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_false().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_false (const FormulaT & formula, std::false_type) inline private
Definition at line 1181 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_forall (const FormulaT & formula, FormulaT && subformula, std::true_type) inline private
Definition at line 1117 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_forall().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_forall (const FormulaT & formula, FormulaT && subformula, std::false_type) inline private
Definition at line 1121 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_iff (const FormulaT & formula, set_type && subformulas, std::true_type) inline private
Definition at line 1057 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_iff().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_iff (const FormulaT & formula, set_type && subformulas, std::false_type) inline private
Definition at line 1061 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_implication (const FormulaT & formula, FormulaT && premise, FormulaT && conclusion, std::true_type) inline private
Definition at line 1129 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_implication().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_implication (const FormulaT & formula, FormulaT && premise, FormulaT && conclusion, std::false_type) inline private
Definition at line 1133 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_ite (const FormulaT & formula, FormulaT && condition, FormulaT && then, FormulaT && else_, std::true_type) inline private
Definition at line 1141 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_ite().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_ite (const FormulaT & formula, FormulaT && condition, FormulaT && then, FormulaT && else_, std::false_type) inline private
Definition at line 1145 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_leaf (const FormulaT & formula, std::true_type) inline private
Definition at line 1153 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_bool(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_constraint(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_false(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_leaf(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_true(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_ueq().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_leaf (const FormulaT & formula, std::false_type) inline private
Definition at line 1157 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_leaf (const FormulaT & formula) inline private
Definition at line 1161 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_not (const FormulaT & formula, FormulaT && subformula, std::true_type) inline private
Definition at line 1081 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_not().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_not (const FormulaT & formula, FormulaT && subformula, std::false_type) inline private
Definition at line 1085 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_or (const FormulaT & formula, set_type && subformulas, std::true_type) inline private
Definition at line 1033 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_or().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_or (const FormulaT & formula, set_type && subformulas, std::false_type) inline private
Definition at line 1037 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_quantified (const FormulaT & formula, FormulaT && subformula, std::true_type) inline private
Definition at line 1093 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_exists(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_forall(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_quantified().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_quantified (const FormulaT & formula, FormulaT && subformula, std::false_type) inline private
Definition at line 1097 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_quantified (const FormulaT & formula, FormulaT && subformula) inline private
Definition at line 1101 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_true (const FormulaT & formula, std::true_type) inline private
Definition at line 1165 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_true().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_true (const FormulaT & formula, std::false_type) inline private
Definition at line 1169 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_ueq (const FormulaT & formula, std::true_type) inline private
Definition at line 1201 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_ueq().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_ueq (const FormulaT & formula, std::false_type) inline private
Definition at line 1205 of file FormulaVisitor.hpp.
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_xor (const FormulaT & formula, multiset_type && subformulas, std::true_type) inline private
Definition at line 1069 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::visit_xor().
template<typename RewriterType> template<typename = void> FormulaT smtrat::formula_rewriter< RewriterType >::P_visit_xor (const FormulaT & formula, multiset_type && subformulas, std::false_type) inline private
Definition at line 1073 of file FormulaVisitor.hpp.
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_default) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_or) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_and) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_iff) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_xor) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_not) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_exists) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_forall) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_implication) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_ite) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_true) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_false) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_bool) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_ueq) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_constraint) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_quantified) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (rewrite_leaf) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_default) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_or) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_and) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_iff) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_xor) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_not) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_exists) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_forall) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_implication) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_ite) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_true) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_false) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_bool) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_ueq) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_constraint) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_quantified) private
template<typename RewriterType> smtrat::formula_rewriter< RewriterType >::SMTRAT_HAS_DECL (enter_leaf) private
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_and (const FormulaT & formula, set_type && subformulas) inline private
Definition at line 1053 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_bool (const FormulaT & formula) inline private
Definition at line 1197 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_constraint (const FormulaT & formula) inline private
Definition at line 1221 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_exists (const FormulaT & formula, FormulaT && subformula) inline private
Definition at line 1113 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_false (const FormulaT & formula) inline private
Definition at line 1185 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_forall (const FormulaT & formula, FormulaT && subformula) inline private
Definition at line 1125 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_iff (const FormulaT & formula, set_type && subformulas) inline private
Definition at line 1065 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_implication (const FormulaT & formula, FormulaT && premise, FormulaT && conclusion) inline private
Definition at line 1137 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_ite (const FormulaT & formula, FormulaT && condition, FormulaT && trueCase, FormulaT && falseCase) inline private
Definition at line 1149 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_not (const FormulaT & formula, FormulaT && subformula) inline private
Definition at line 1089 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_or (const FormulaT & formula, set_type && subformulas) inline private
Definition at line 1041 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_true (const FormulaT & formula) inline private
Definition at line 1173 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_ueq (const FormulaT & formula) inline private
Definition at line 1209 of file FormulaVisitor.hpp.
template<typename RewriterType> FormulaT smtrat::formula_rewriter< RewriterType >::visit_xor (const FormulaT & formula, multiset_type && subformulas) inline private
Definition at line 1077 of file FormulaVisitor.hpp.
Friends And Related Function Documentation
template<typename RewriterType> friend class formula_visitor< formula_rewriter< RewriterType >,FormulaT,typename FormulaSetT::value_compare,typename FormulaSetT::allocator_type > friend
Definition at line 985 of file FormulaVisitor.hpp.
Field Documentation
template<typename RewriterType> RewriterType smtrat::formula_rewriter< RewriterType >::mRewriter private
Definition at line 1445 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_rewriter< smtrat::UFRewriter >::get(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_and(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_bool(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_constraint(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_default(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_exists(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_false(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_forall(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_iff(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_implication(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_ite(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_leaf(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_not(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_or(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_quantified(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_true(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_ueq(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_enter_xor(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_rewrite_default(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_and(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_bool(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_constraint(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_exists(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_false(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_forall(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_iff(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_implication(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_ite(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_leaf(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_not(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_or(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_quantified(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_true(), smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_ueq(), and smtrat::formula_rewriter< smtrat::UFRewriter >::P_visit_xor().
The documentation for this class was generated from the following file:
lib/modules/EQPreprocessingModule/FormulaVisitor.hpp