SMT-RAT: smtrat::PreprocessingModule< Settings > Class Template Reference
smtrat::PreprocessingModule< Settings > Class Template Reference
#include <PreprocessingModule.h>
Public Types
typedef Settings SettingsType
enum DeductionType : unsigned { DeductionType::NORMAL, DeductionType::PERMANENT }
typedef
std::chrono::high_resolution_clock clock
For time measuring purposes.
typedef std::chrono::microseconds timeunit
For time measuring purposes.
Public Member Functions
std::string moduleName () const
PreprocessingModule (const ModuleInput *, RuntimeSettings *, Conditionals &, Manager *const =nullptr)
virtual ~PreprocessingModule ()
Destructor:
bool addCore (ModuleInput::const_iterator)
Methods:
Answer checkCore (bool _full)
Checks the so far received constraints for consistency.
void removeCore (ModuleInput::const_iterator)
Removes a everything related to a sub formula of the received formula.
void updateModel () const
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
bool isPreprocessor () const
bool appliedPreprocessing () const
bool add (ModuleInput::const_iterator _subformula)
The module has to take the given sub-formula of the received formula into account.
void remove (ModuleInput::const_iterator _subformula)
Removes everything related to the given sub-formula of the received formula.
Answer runBackends (bool _full=true)
Runs the backend solvers on the passed formula.
std::pair< bool, FormulaT > getReceivedFormulaSimplified ()
bool inform (const FormulaT &)
Informs the module about the given constraint.
virtual void init ()
Informs all backends about the so far encountered constraints, which have not yet been communicated.
Answer check (bool _full=true)
Checks the received formula for consistency.
virtual std::list< std::vector
< carl::Variable > > getModelEqualities () const
Partition the variables from the current model into equivalence classes according to their assigned value.
Answer solverState () const
std::size_t id () const
void setId (std::size_t _id)
Sets this modules unique ID to identify itself.
thread_priority threadPriority () const
void setThreadPriority (thread_priority _threadPriority)
Sets the priority of this module to get a thread for running its check procedure.
const ModuleInput * pReceivedFormula () const
const ModuleInput & rReceivedFormula () const
const ModuleInput * pPassedFormula () const
const ModuleInput & rPassedFormula () const
const Model & model () const
const std::vector< FormulaSetT > & infeasibleSubsets () const
const std::vector< Module * > & usedBackends () const
const FormulasT & constraintsToInform () const
const FormulasT & informedConstraints () const
void addDeduction (const FormulaT &_deduction, const DeductionType &_dt=DeductionType::NORMAL)
Stores a deduction/lemma being a valid formula.
bool hasDeductions ()
Checks whether this module or any of its backends provides any lemmas or splitting decisions.
void clearDeductions ()
Deletes all yet found deductions/lemmas.
void clearSplittings ()
Deletes all yet found deductions/lemmas.
const std::vector< Splitting > & splittings () const
void addSplitting (const FormulaT &_leftCase, const FormulaT &_rightCase, std::vector< FormulaT > &&_premise, bool _preferLeftCase)
void addSplittings (const std::vector< Splitting > &_splittings)
const std::vector< std::pair
< FormulaT, DeductionType > > & deductions () const
ModuleInput::const_iterator firstUncheckedReceivedSubformula () const
ModuleInput::const_iterator firstSubformulaToPass () const
void receivedFormulaChecked ()
Notifies that the received formulas has been checked.
const std::vector
< std::atomic_bool * > & answerFound () const
carl::Variable::Arg objective () const
void setObjective (carl::Variable::Arg _objective)
void excludeNotReceivedVariablesFromModel () const
Excludes all variables from the current model, which do not occur in the received formula.
void updateDeductions ()
Stores all deductions of any backend of this module in its own deduction vector.
void collectOrigins (const FormulaT &_formula, FormulasT &_origins) const
Collects the formulas in the given formula, which are part of the received formula.
void collectOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
bool hasValidInfeasibleSubset () const
void checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string &_filename="smaller_muses", unsigned _maxSizeDifference=1) const
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
void print (const std::string _initiation="***") const
Prints everything relevant of the solver.
void printReceivedFormula (const std::string _initiation="***") const
Prints the vector of the received formula.
void printPassedFormula (const std::string _initiation="***") const
Prints the vector of passed formula.
void printInfeasibleSubsets (const std::string _initiation="***") const
Prints the infeasible subsets.
void printModel () const
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
void startAddTimer ()
Starts the timer to stop the timing for adding formulas performed by this module.
void stopAddTimer ()
Stops the timer to stop the timing for adding formulas performed by this module.
void startCheckTimer ()
Starts the timer to stop the timing for checking formulas performed by this module.
void stopCheckTimer ()
Stops the timer to stop the timing for checking formulas performed by this module.
void startRemoveTimer ()
Starts the timer to stop the timing for removing formulas performed by this module.
void stopRemoveTimer ()
Stops the timer to stop the timing for removing formulas performed by this module.
void startTimers (int timers)
Starts the timers according to the given integer of this module: If its first bit is set, the timer for adding formulas is started.
int stopAllTimers ()
Stops all timers of this module.
double getAddTimerMS () const
double getCheckTimerMS () const
double getRemoveTimerMS () const
unsigned getNrConsistencyChecks () const
Static Public Member Functions
static void addAssumptionToCheck (const FormulaT &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const ModuleInput &_formula, bool _consistent, const std::string &_label)
Add a formula to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const FormulasT &_formulas, bool _consistent, const std::string &_label)
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
static void addAssumptionToCheck (const FormulaSetT &_formulas, bool _consistent, const std::string &_label)
static void addAssumptionToCheck (const ConstraintsT &_constraints, bool _consistent, const std::string &_label)
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
static void storeAssumptionsToCheck (const Manager &_manager)
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Static Public Attributes
static std::vector< std::string > mAssumptionToCheck
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static std::set< std::string > mVariablesInAssumptionToCheck
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
static size_t mNumOfBranchVarsToStore
The number of different variables to consider for a probable infinite loop of branchings.
static std::vector< Branching > mLastBranches
Stores the last branches in a cycle buffer.
static size_t mFirstPosInLastBranches
The beginning of the cylcic buffer storing the last branches.
Protected Member Functions
void addBounds (const FormulaT &formula, const FormulaT &_origin)
void removeBounds (const FormulaT &formula, const FormulaT &_origin)
FormulaT removeFactors (const FormulaT &formula)
Removes redundant or obsolete factors of polynomials from the formula.
FormulaT eliminateMonomialEquation (const FormulaT &formula)
FormulaT splitSOS (const FormulaT &formula)
Splits the sum-of-squares (sos) decomposition, if the given formula is a constraint with a sos as left-hand side.
void collectUnboundedVars (const FormulaT &formula)
Collect the upper and lower bounds of all variables x which only appear as monomial x^i.
FormulaT removeUnboundedVars (const FormulaT &formula)
FormulaT checkBounds (const FormulaT &formula)
Checks if constraints vanish using the variable bounds.
FormulaT extractBounds (const FormulaT &formula)
Extracts the bounds of a polynomial if it is the only polynomial occurring in a disjunction of constraints.
FormulaT elimSubstitutions (const FormulaT &_formula, bool _elimSubstitutions=false)
Eliminates all equation forming a substitution of the form x = p with p not containing x.
void enumerateIntegers ()
virtual bool informCore (const FormulaT &)
Informs the module about the given constraint.
bool anAnswerFound () const
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
void clearModel () const
Clears the assignment, if any was found.
ModuleInput::iterator passedFormulaBegin ()
ModuleInput::iterator passedFormulaEnd ()
void addOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
Adds the given set of formulas in the received formula to the origins of the given passed formula.
const FormulaT & getOrigins (ModuleInput::const_iterator _formula) const
Gets the origins of the passed formula at the given position.
void getOrigins (const FormulaT &_formula, FormulasT &_origins) const
void getOrigins (const FormulaT &_formula, FormulaSetT &_origins) const
std::pair
< ModuleInput::iterator, bool > removeOrigin (ModuleInput::iterator _formula, const FormulaT &_origin)
std::pair
< ModuleInput::iterator, bool > removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
void informBackends (const FormulaT &_constraint)
Informs all backends of this module about the given constraint.
void addConstraintToInform (const FormulaT &_constraint)
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
std::pair
< ModuleInput::iterator, bool > addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula)
Copies the given sub-formula of the received formula to the passed formula.
bool originInReceivedFormula (const FormulaT &_origin) const
std::pair
< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula)
Adds the given formula to the passed formula with no origin.
std::pair
< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const std::shared_ptr< std::vector< FormulaT >> &_origins)
Adds the given formula to the passed formula.
std::pair
< ModuleInput::iterator, bool > addSubformulaToPassedFormula (const FormulaT &_formula, const FormulaT &_origin)
Adds the given formula to the passed formula.
void generateTrivialInfeasibleSubset ()
Stores the trivial infeasible subset being the set of received formulas.
void receivedFormulasAsInfeasibleSubset (ModuleInput::const_iterator _subformula)
Stores an infeasible subset consisting only of the given received formula.
std::vector< FormulaT >
::const_iterator findBestOrigin (const std::vector< FormulaT > &_origins) const
void getInfeasibleSubsets ()
Copies the infeasible subsets of the passed formula.
std::vector< FormulaSetT > getInfeasibleSubsets (const Module &_backend) const
Get the infeasible subsets the given backend provides.
Model backendsModel () const
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
void getBackendsModel () const
virtual ModuleInput::iterator eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins=false)
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
void clearPassedFormula ()
std::vector< FormulaT > merge (const std::vector< FormulaT > &, const std::vector< FormulaT > &) const
Merges the two vectors of sets into the first one.
size_t determine_smallest_origin (const std::vector< FormulaT > &origins) const
bool probablyLooping (const typename Poly::PolyType &_branchingPolynomial, const Rational &_branchingValue) const
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true)
Adds a deductions which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
bool branchAt (const Poly &_polynomial, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
bool branchAt (carl::Variable::Arg _var, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true)
bool branchAt (carl::Variable::Arg _var, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, std::vector< FormulaT > &&_premise, bool _leftCaseWeak=true, bool _preferLeftCase=true)
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy>
bool branchAt (const typename P::PolyType &_poly, bool _integral, const Rational &_value, bool _leftCaseWeak=true, bool _preferLeftCase=true, const std::vector< FormulaT > &_premise=std::vector< FormulaT >())
void splitUnequalConstraint (const FormulaT &)
Adds the following lemmas for the given constraint p!=0.
unsigned checkModel () const
Static Protected Member Functions
static bool modelsDisjoint (const Model &_modelA, const Model &_modelB)
Checks whether there is no variable assigned by both models.
Protected Attributes
std::function< FormulaT(FormulaT)> removeFactorsFunction
std::function< FormulaT(FormulaT)> eliminateMonomialEquationFunction
std::function< FormulaT(FormulaT)> splitSOSFunction
std::function< void(FormulaT)> collectUnboundedVarsFunction
std::function< FormulaT(FormulaT)> removeUnboundedVarsFunction
std::function< FormulaT(FormulaT)> checkBoundsFunction
std::function< FormulaT(FormulaT)> extractBoundsFunction
std::vector< FormulaSetT > mInfeasibleSubsets
Stores the infeasible subsets.
Manager *const mpManager
A reference to the manager.
Model mModel
Stores the assignment of the current satisfiable result, if existent.
Private Member Functions
void accumulateBoundOrigins (const ConstraintT &constraint)
EvalRationalIntervalMap completeBounds (const Poly &p) const
EvalRationalIntervalMap completeBounds (const ConstraintT &c) const
Private Attributes
carl::FormulaVisitor< FormulaT > visitor
std::unordered_set< FormulaT > newBounds
Bounds that have been added since the last call to isConsistent().
vb::VariableBounds< FormulaT > varbounds
Collection of bounds of all received formulas.
std::unordered_map< FormulaT,
bool > boolSubs
std::map< carl::Variable, Poly > arithSubs
std::map< carl::Variable, int > mVariablesBounded
FormulaSetT tmpOrigins
Detailed Description
template<typename Settings>
class smtrat::PreprocessingModule< Settings >
Definition at line 21 of file PreprocessingModule.h.
Member Typedef Documentation
typedef std::chrono::high_resolution_clock smtrat::Module::clock inherited
For time measuring purposes.
Definition at line 111 of file Module.h.
template<typename Settings > typedef Settings smtrat::PreprocessingModule< Settings >::SettingsType
Definition at line 61 of file PreprocessingModule.h.
typedef std::chrono::microseconds smtrat::Module::timeunit inherited
For time measuring purposes.
Definition at line 113 of file Module.h.
Member Enumeration Documentation
enum smtrat::Module::DeductionType : unsigned strong inherited
Enumerator
NORMAL
PERMANENT
Definition at line 118 of file Module.h.
Constructor & Destructor Documentation
template<typename Settings > smtrat::PreprocessingModule< Settings >::PreprocessingModule (const ModuleInput * _formula, RuntimeSettings * , Conditionals & _conditionals, Manager * const _manager = nullptr)
Definition at line 15 of file PreprocessingModule.cpp.
template<typename Settings > smtrat::PreprocessingModule< Settings >::~PreprocessingModule () virtual
Destructor:
Definition at line 34 of file PreprocessingModule.cpp.
Member Function Documentation
template<typename Settings > void smtrat::PreprocessingModule< Settings >::accumulateBoundOrigins (const ConstraintT & constraint) inline private
Definition at line 37 of file PreprocessingModule.h.
bool smtrat::PModule::add (ModuleInput::const_iterator _subformula) inherited
The module has to take the given sub-formula of the received formula into account.
Parameters
_subformula The sub-formula to take additionally into account.
Returns
false, if it can be easily decided that this sub-formula causes a conflict with the already considered sub-formulas; true, otherwise.
Definition at line 22 of file PModule.cpp.
void Module::addAssumptionToCheck (const FormulaT & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_formula The formula which should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See Also
Module::storeAssumptionsToCheck
Definition at line 931 of file Module.cpp.
Referenced by smtrat::Module::addAssumptionToCheck(), smtrat::Module::check(), smtrat::ICPModule< Settings >::checkBoxAgainstLinearFeasibleRegion(), smtrat::Module::checkCore(), smtrat::Module::getInfeasibleSubsets(), smtrat::VSModule< Settings >::logConditions(), smtrat::EQModule< Settings >::P_add_implicit_edge_deduction(), smtrat::EQModule< Settings >::P_check_for_unassigned_literals(), vs::State::passConflictToFather(), smtrat::VSModule< Settings >::runBackendSolvers(), and smtrat::Module::updateDeductions().
void Module::addAssumptionToCheck (const ModuleInput & _formula, bool _consistent, const std::string & _label) static inherited
Add a formula to the assumption vector and its predetermined consistency status.
Parameters
_subformulas The sub-formulas whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See Also
Module::storeAssumptionsToCheck
Definition at line 944 of file Module.cpp.
void Module::addAssumptionToCheck (const FormulasT & _formulas, bool _consistent, const std::string & _label) static inherited
Add a conjunction of formulas to the assumption vector and its predetermined consistency status.
Parameters
_formulas The formulas, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See Also
Module::storeAssumptionsToCheck
Definition at line 957 of file Module.cpp.
void Module::addAssumptionToCheck (const FormulaSetT & _formulas, bool _consistent, const std::string & _label) static inherited
Definition at line 970 of file Module.cpp.
void Module::addAssumptionToCheck (const ConstraintsT & _constraints, bool _consistent, const std::string & _label) static inherited
Add a conjunction of _constraints to the assumption vector and its predetermined consistency status.
Parameters
_constraints The constraints, whose conjunction should be consistent/inconsistent.
_consistent A flag indicating whether the conjunction of the given constraints should be consistent or inconsistent.
_label A label which will be encoded as a Boolean variable into the formula to represent the assumption, while keeping it equisatisfiable (the label could, e.g., be the name of the module or its sub-procedure).
See Also
Module::storeAssumptionsToCheck
Definition at line 978 of file Module.cpp.
template<typename Settings > void smtrat::PreprocessingModule< Settings >::addBounds (const FormulaT & formula, const FormulaT & _origin) protected
Definition at line 223 of file PreprocessingModule.cpp.
void Module::addConstraintToInform (const FormulaT & _constraint) protected inherited
Adds a constraint to the collection of constraints of this module, which are informed to a freshly generated backend.
Parameters
_constraint The constraint to add.
Definition at line 780 of file Module.cpp.
Referenced by smtrat::Module::inform().
template<typename Settings > bool smtrat::PreprocessingModule< Settings >::addCore (ModuleInput::const_iterator _subformula) virtual
Methods:
Adds a constraint to this module.
Parameters
_constraint The constraint to add to the already added constraints.
Returns
true
Reimplemented from smtrat::Module.
Definition at line 48 of file PreprocessingModule.cpp.
void smtrat::Module::addDeduction (const FormulaT & _deduction, const DeductionType & _dt = DeductionType::NORMAL) inline inherited
Stores a deduction/lemma being a valid formula.
Parameters
_deduction The eduction/lemma to store.
_dt The type of the deduction.
Definition at line 387 of file Module.h.
Referenced by smtrat::EQModule< Settings >::P_add_implicit_edge_deduction(), smtrat::EQModule< Settings >::P_check_for_unassigned_literals(), and smtrat::Module::splitUnequalConstraint().
void smtrat::Module::addOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Adds the given set of formulas in the received formula to the origins of the given passed formula.
Parameters
_formula The passed formula to set the origins for.
_origins A set of formulas in the received formula of this module.
Definition at line 713 of file Module.h.
std::pair<ModuleInput::iterator,bool> smtrat::Module::addReceivedSubformulaToPassedFormula (ModuleInput::const_iterator _subformula) inline protected inherited
Copies the given sub-formula of the received formula to the passed formula.
Note, that there is always a link between sub-formulas of the passed formulas to sub-formulas of the received formulas, which are responsible for its occurrence.
Parameters
_subformula The sub-formula of the received formula to copy.
Definition at line 772 of file Module.h.
Referenced by smtrat::Module::checkCore().
void smtrat::Module::addSplitting (const FormulaT & _leftCase, const FormulaT & _rightCase, std::vector< FormulaT > && _premise, bool _preferLeftCase) inline inherited
Definition at line 442 of file Module.h.
Referenced by smtrat::Module::updateDeductions().
void smtrat::Module::addSplittings (const std::vector< Splitting > & _splittings) inline inherited
Definition at line 447 of file Module.h.
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula) inline protected inherited
Adds the given formula to the passed formula with no origin.
Note that in the next call of this module's removeSubformula, all formulas in the passed formula without origins will be removed.
Parameters
_formula The formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 788 of file Module.h.
Referenced by smtrat::Module::addReceivedSubformulaToPassedFormula(), smtrat::Module::addSubformulaToPassedFormula(), smtrat::CNFerModule::checkCore(), and smtrat::PFEModule< Settings >::generateVariableAssignments().
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origins The link of the formula to add to the passed formula to sub-formulas of the received formulas, which are responsible for its occurrence
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 802 of file Module.h.
std::pair<ModuleInput::iterator,bool> smtrat::Module::addSubformulaToPassedFormula (const FormulaT & _formula, const FormulaT & _origin) inline protected inherited
Adds the given formula to the passed formula.
Parameters
_formula The formula to add to the passed formula.
_origin The sub-formula of the received formula being responsible for the occurrence of the formula to add to the passed formula.
Returns
A pair to the position where the formula to add has been inserted (or its first sub-formula which has not yet been in the passed formula, in case the formula to add is a conjunction), and a Boolean stating whether anything has been added to the passed formula.
Definition at line 816 of file Module.h.
bool smtrat::Module::anAnswerFound () const inline protected inherited
Checks for all antecedent modules and those which run in parallel with the same antecedent modules, whether one of them has determined a result.
Returns
True, if one of them has determined a result.
Definition at line 673 of file Module.h.
Referenced by smtrat::Module::foundAnswer(), and smtrat::Module::runBackends().
const std::vector< std::atomic_bool* >& smtrat::Module::answerFound () const inline inherited
Returns
A vector of Booleans: If any of them is true, we have to terminate a running check procedure.
Definition at line 487 of file Module.h.
Referenced by smtrat::Manager::getBackends().
bool smtrat::PModule::appliedPreprocessing () const inline inherited
Returns
true, if the current received formula has been simplified and the result of this simplification is stored in the passed formula.
Definition at line 40 of file PModule.h.
Model Module::backendsModel () const protected inherited
Stores the model of a backend which determined satisfiability of the passed formula in the model of this module.
Definition at line 524 of file Module.cpp.
bool Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true) protected inherited
Adds a deductions which provoke a branching for the given variable at the given value, if this module returns Unknown and there exists a preceding SATModule.
Note that the given value is rounded down and up, if the given variable is integer-valued.
Parameters
_polynomial The variable to branch for. _integral A flag being true, if all variables in the polynomial to branch for are integral.
_value The value to branch at.
_premise The sub-formulas of the received formula from which the branch is followed. Note, that a premise is not necessary, as every branch is a valid formula. But a premise can prevent from branching unnecessarily.
_leftCaseWeak true, if a branching in the form of (or (<= p b) (> p b)) is desired. false, if a branching in the form of (or (< p b) (>= p b)) is desired.
_preferLeftCase true, if the left case (polynomial less(or equal) 0 shall be chosen first. false, otherwise.
_isolateBranchValue true, if a branching in the form of (or (= p b) (< p b) (> p b)) is desired. (Currently only supported for reals)
Definition at line 416 of file Module.cpp.
Referenced by smtrat::Module::branchAt(), smtrat::CADModule< Settings >::checkIntegerAssignment(), smtrat::ICPModule< Settings >::contraction(), and smtrat::ICPModule< Settings >::performSplit().
bool smtrat::Module::branchAt (const Poly & _polynomial, bool _integral, const Rational & _value, bool _leftCaseWeak = true, bool _preferLeftCase = true, const std::vector< FormulaT > & _premise = std::vector<FormulaT>()) inline protected inherited
Definition at line 988 of file Module.h.
bool smtrat::Module::branchAt (carl::Variable::Arg _var, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true) inline protected inherited
Definition at line 993 of file Module.h.
bool smtrat::Module::branchAt (carl::Variable::Arg _var, const Rational & _value, bool _leftCaseWeak = true, bool _preferLeftCase = true, const std::vector< FormulaT > & _premise = std::vector<FormulaT>()) inline protected inherited
Definition at line 998 of file Module.h.
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy> bool smtrat::Module::branchAt (const typename P::PolyType & _poly, bool _integral, const Rational & _value, std::vector< FormulaT > && _premise, bool _leftCaseWeak = true, bool _preferLeftCase = true) inline protected inherited
Definition at line 1004 of file Module.h.
template<typename P = Poly, carl::EnableIf< carl::needs_cache< P >> = carl::dummy> bool smtrat::Module::branchAt (const typename P::PolyType & _poly, bool _integral, const Rational & _value, bool _leftCaseWeak = true, bool _preferLeftCase = true, const std::vector< FormulaT > & _premise = std::vector<FormulaT>()) inline protected inherited
Definition at line 1010 of file Module.h.
Answer Module::check (bool _full = true) inherited
Checks the received formula for consistency.
Note, that this is an implementation of the satisfiability check of the conjunction of the so far received formulas, which does actually nothing but passing the problem to its backends. This implementation is only used internally and must be overwritten by any derived module.
Parameters
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
Returns
True, if the received formula is satisfiable; False, if the received formula is not satisfiable; Unknown, otherwise.
Definition at line 91 of file Module.cpp.
Referenced by smtrat::Manager::check(), and smtrat::ThreadPool::submitBackend().
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::checkBounds (const FormulaT & formula) protected
Checks if constraints vanish using the variable bounds.
Definition at line 436 of file PreprocessingModule.cpp.
template<typename Settings > Answer smtrat::PreprocessingModule< Settings >::checkCore (bool _full) virtual
Checks the so far received constraints for consistency.
Reimplemented from smtrat::Module.
Definition at line 64 of file PreprocessingModule.cpp.
void Module::checkInfSubsetForMinimality (std::vector< FormulaSetT >::const_iterator _infsubset, const std::string & _filename = "smaller_muses", unsigned _maxSizeDifference = 1) const inherited
Checks the given infeasible subset for minimality by storing all subsets of it, which have a smaller size which differs from the size of the infeasible subset not more than the given threshold.
Parameters
_infsubset The infeasible subset to check for minimality.
_filename The name of the file to store the infeasible subsets in order to be able to check their infeasibility.
_maxSizeDifference The maximal difference between the sizes of the subsets compared to the size of the infeasible subset.
Definition at line 1048 of file Module.cpp.
Referenced by smtrat::GBModule< Settings >::checkCore(), and smtrat::CADModule< Settings >::checkCore().
unsigned Module::checkModel () const protected inherited
Returns
false, if the current model of this module does not satisfy the current given formula; true, if it cannot be said whether the model satisfies the given formula.
Definition at line 484 of file Module.cpp.
Referenced by smtrat::Module::foundAnswer().
void smtrat::Module::clearDeductions () inline inherited
Deletes all yet found deductions/lemmas.
Definition at line 413 of file Module.h.
Referenced by smtrat::Module::check().
void smtrat::Module::clearModel () const inline protected inherited
Clears the assignment, if any was found.
Definition at line 685 of file Module.h.
Referenced by smtrat::Module::updateModel(), and smtrat::Module::~Module().
void Module::clearPassedFormula () protected inherited
Definition at line 760 of file Module.cpp.
void smtrat::Module::clearSplittings () inline inherited
Deletes all yet found deductions/lemmas.
Definition at line 429 of file Module.h.
void Module::collectOrigins (const FormulaT & _formula, FormulasT & _origins) const inherited
Collects the formulas in the given formula, which are part of the received formula.
If the given formula directly occurs in the received formula, it is inserted into the given set. Otherwise, the given formula must be of type AND and all its sub-formulas part of the received formula. Hence, they will be added to the given set.
Parameters
_formula The formula from which to collect the formulas being sub-formulas of the received formula (origins).
_origins The set in which to store the origins.
Definition at line 897 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
void Module::collectOrigins (const FormulaT & _formula, FormulaSetT & _origins) const inherited
Definition at line 914 of file Module.cpp.
template<typename Settings > void smtrat::PreprocessingModule< Settings >::collectUnboundedVars (const FormulaT & formula) protected
Collect the upper and lower bounds of all variables x which only appear as monomial x^i.
Definition at line 409 of file PreprocessingModule.cpp.
template<typename Settings > EvalRationalIntervalMap smtrat::PreprocessingModule< Settings >::completeBounds (const Poly & p) const inline private
Definition at line 41 of file PreprocessingModule.h.
template<typename Settings > EvalRationalIntervalMap smtrat::PreprocessingModule< Settings >::completeBounds (const ConstraintT & c) const inline private
Definition at line 50 of file PreprocessingModule.h.
const FormulasT& smtrat::Module::constraintsToInform () const inline inherited
Returns
The constraints which the backends must be informed about.
Definition at line 369 of file Module.h.
const std::vector<std::pair<FormulaT,DeductionType> >& smtrat::Module::deductions () const inline inherited
Returns
A constant reference to the deductions/lemmas being valid formulas this module or its backends made.
Definition at line 455 of file Module.h.
Referenced by smtrat::Manager::lemmas().
size_t Module::determine_smallest_origin (const std::vector< FormulaT > & origins) const protected inherited
Parameters
origins A vector of sets of origins.
Returns
The index of the smallest (regarding the size of the sets) element of origins
Definition at line 345 of file Module.cpp.
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::eliminateMonomialEquation (const FormulaT & formula) protected
Definition at line 323 of file PreprocessingModule.cpp.
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::elimSubstitutions (const FormulaT & _formula, bool _elimSubstitutions = false) protected
Eliminates all equation forming a substitution of the form x = p with p not containing x.
Definition at line 653 of file PreprocessingModule.cpp.
template<typename Settings > void smtrat::PreprocessingModule< Settings >::enumerateIntegers () protected
Definition at line 941 of file PreprocessingModule.cpp.
ModuleInput::iterator Module::eraseSubformulaFromPassedFormula (ModuleInput::iterator _subformula, bool _ignoreOrigins = false) protected virtual inherited
Removes everything related to the sub-formula to remove from the passed formula in the backends of this module.
Afterwards the sub-formula is removed from the passed formula.
Parameters
_subformula The sub-formula to remove from the passed formula.
_ignoreOrigins True, if the sub-formula shall be removed regardless of its origins (should only be applied with expertise).
Returns
Reimplemented in smtrat::ICPModule< Settings >, and smtrat::ICPModule< smtrat::ICPSettings1 >.
Definition at line 704 of file Module.cpp.
Referenced by smtrat::Module::clearPassedFormula(), smtrat::ICPModule< Settings >::eraseSubformulaFromPassedFormula(), smtrat::ICPModule< Settings >::pushBoundsToPassedFormula(), smtrat::Module::remove(), smtrat::Module::removeOrigin(), and smtrat::Module::removeOrigins().
void Module::excludeNotReceivedVariablesFromModel () const inherited
Excludes all variables from the current model, which do not occur in the received formula.
Definition at line 787 of file Module.cpp.
Referenced by smtrat::Module::updateModel().
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::extractBounds (const FormulaT & formula) protected
Extracts the bounds of a polynomial if it is the only polynomial occurring in a disjunction of constraints.
Definition at line 471 of file PreprocessingModule.cpp.
vector< FormulaT >::const_iterator Module::findBestOrigin (const std::vector< FormulaT > & _origins) const protected inherited
Parameters
_origins
Returns
Definition at line 563 of file Module.cpp.
Referenced by smtrat::Module::getOrigins().
ModuleInput::const_iterator smtrat::Module::firstSubformulaToPass () const inline inherited
Returns
The position of the first sub-formula in the passed formula, which has not yet been considered for a consistency check of the backends.
Definition at line 471 of file Module.h.
Referenced by smtrat::Manager::getBackends().
ModuleInput::const_iterator smtrat::Module::firstUncheckedReceivedSubformula () const inline inherited
Returns
The position of the first (by this module) unchecked sub-formula of the received formula.
Definition at line 463 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore().
void smtrat::Module::generateTrivialInfeasibleSubset () inline protected inherited
Stores the trivial infeasible subset being the set of received formulas.
Definition at line 824 of file Module.h.
double smtrat::Module::getAddTimerMS () const inline inherited
Returns
The total time of adding formulas performed by this module.
Definition at line 1206 of file Module.h.
void Module::getBackendsModel () const protected inherited
Definition at line 542 of file Module.cpp.
Referenced by smtrat::IntEqModule< Settings >::constructSolution(), smtrat::VSModule< Settings >::updateModel(), smtrat::FouMoModule< Settings >::updateModel(), smtrat::ICPModule< Settings >::updateModel(), smtrat::LRAModule< Settings >::updateModel(), smtrat::Module::updateModel(), and smtrat::SATModule< Settings >::updateModel().
double smtrat::Module::getCheckTimerMS () const inline inherited
Returns
The total time of checking formulas performed by this module.
Definition at line 1214 of file Module.h.
void Module::getInfeasibleSubsets () protected inherited
Copies the infeasible subsets of the passed formula.
Definition at line 490 of file Module.cpp.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::Module::checkCore().
std::vector< FormulaSetT > Module::getInfeasibleSubsets (const Module & _backend) const protected inherited
Get the infeasible subsets the given backend provides.
Note, that an infeasible subset in a backend contains sub formulas of the passed formula and an infeasible subset of this module contains sub formulas of the received formula. In this method the LATTER is returned.
Parameters
_backend The backend from which to obtain the infeasible subsets.
Returns
The infeasible subsets the given backend provides.
Definition at line 581 of file Module.cpp.
list< std::vector< carl::Variable > > Module::getModelEqualities () const virtual inherited
Partition the variables from the current model into equivalence classes according to their assigned value.
The result is a set of equivalence classes of variables where all variables within one class are assigned the same value. Note that the number of classes may not be minimal, i.e. two classes may actually be equivalent.
Returns
Equivalence classes.
Definition at line 250 of file Module.cpp.
Referenced by smtrat::Manager::getModelEqualities().
unsigned smtrat::Module::getNrConsistencyChecks () const inline inherited
Returns
The number of consistency checks performed by this module.
Definition at line 1230 of file Module.h.
const FormulaT& smtrat::Module::getOrigins (ModuleInput::const_iterator _formula) const inline protected inherited
Gets the origins of the passed formula at the given position.
Parameters
_formula The position of a formula in the passed formulas.
Returns
The origins of the passed formula at the given position.
Definition at line 723 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets(), and smtrat::Module::updateDeductions().
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulasT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 870 of file Module.h.
void smtrat::Module::getOrigins (const FormulaT & _formula, FormulaSetT & _origins) const inline protected inherited
Parameters
_formula
_origins
Definition at line 883 of file Module.h.
pair< bool, FormulaT > smtrat::PModule::getReceivedFormulaSimplified () virtual inherited
Returns
A pair of a Boolean and a formula, where the Boolean is true, if the received formula could be simplified to an equisatisfiable formula. The formula is equisatisfiable to this module's reveived formula, if the Boolean is true.
Reimplemented from smtrat::Module.
Definition at line 40 of file PModule.cpp.
double smtrat::Module::getRemoveTimerMS () const inline inherited
Returns
The total time of removing formulas performed by this module.
Definition at line 1222 of file Module.h.
bool smtrat::Module::hasDeductions () inline inherited
Checks whether this module or any of its backends provides any lemmas or splitting decisions.
Definition at line 395 of file Module.h.
bool Module::hasValidInfeasibleSubset () const inherited
Returns
true, if the module has at least one valid infeasible subset, that is all its elements are sub-formulas of the received formula (pointer must be equal).
Definition at line 1032 of file Module.cpp.
Referenced by smtrat::Module::check().
std::size_t smtrat::Module::id () const inline inherited
Returns
A unique ID to identify this module instance.
Definition at line 277 of file Module.h.
Referenced by smtrat::CNFerModule::CNFerModule(), smtrat::LRAModule< Settings >::LRAModule(), and smtrat::SATModule< Settings >::SATModule().
const std::vector<FormulaSetT>& smtrat::Module::infeasibleSubsets () const inline inherited
Returns
The infeasible subsets of the set of received formulas (empty, if this module has not detected unsatisfiability of the conjunction of received formulas.
Definition at line 353 of file Module.h.
Referenced by smtrat::Module::getInfeasibleSubsets(), smtrat::Manager::infeasibleSubsets(), and smtrat::Manager::printInfeasibleSubset().
bool Module::inform (const FormulaT & _constraint) inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Definition at line 131 of file Module.cpp.
Referenced by smtrat::Manager::add(), smtrat::Manager::getBackends(), smtrat::Manager::inform(), and smtrat::Manager::Manager().
void smtrat::Module::informBackends (const FormulaT & _constraint) inline protected inherited
Informs all backends of this module about the given constraint.
Parameters
_constraint The constraint to inform about.
Definition at line 751 of file Module.h.
virtual bool smtrat::Module::informCore (const FormulaT &) inline protected virtual inherited
Informs the module about the given constraint.
It should be tried to inform this module about any constraint it could receive eventually before assertSubformula is called (preferably for the first time, but at least before adding a formula containing that constraint).
Parameters
_constraint The constraint to inform about.
Returns
false, if it can be easily decided whether the given constraint is inconsistent; true, otherwise.
Reimplemented in smtrat::EQModule< Settings >, smtrat::EQModule< smtrat::EQSettingsForPreprocessing >, smtrat::IntBlastModule< Settings >, smtrat::ICEModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::ICPModule< Settings >, smtrat::ICPModule< smtrat::ICPSettings1 >, smtrat::LICModule< Settings >, smtrat::BVModule< Settings >, and smtrat::FPPModule< Settings >.
Definition at line 629 of file Module.h.
Referenced by smtrat::Module::inform().
const FormulasT& smtrat::Module::informedConstraints () const inline inherited
Returns
The position of the first constraint of which no backend has been informed about.
Definition at line 377 of file Module.h.
Referenced by smtrat::Manager::getBackends().
void Module::init () virtual inherited
Informs all backends about the so far encountered constraints, which have not yet been communicated.
This method must not be called twice and only before the first runBackends call.
Reimplemented in smtrat::EQModule< Settings >, smtrat::EQModule< smtrat::EQSettingsForPreprocessing >, smtrat::IntBlastModule< Settings >, smtrat::ICEModule< Settings >, smtrat::LRAModule< Settings >, smtrat::LRAModule< smtrat::LRASettings1 >, smtrat::LICModule< Settings >, smtrat::BVModule< Settings >, and smtrat::FPPModule< Settings >.
Definition at line 224 of file Module.cpp.
Referenced by smtrat::SATModule< Settings >::checkCore().
bool smtrat::PModule::isPreprocessor () const inline inherited
Returns
true, if this module is a preprocessor that is a module, which simplifies its received formula to an equisatisfiable formula being passed to its backends. The simplified formula can be obtained with getReceivedFormulaSimplified().
Definition at line 31 of file PModule.h.
std::vector< FormulaT > Module::merge (const std::vector< FormulaT > & _vecSetA, const std::vector< FormulaT > & _vecSetB) const protected inherited
Merges the two vectors of sets into the first one.
({a,b},{a,c}) and ({b,d},{b}) -> ({a,b,d},{a,b},{a,b,c,d},{a,b,c})
Parameters
_vecSetA A vector of sets of constraints.
_vecSetB A vector of sets of constraints.
Returns
The vector being the two given vectors merged.
Definition at line 319 of file Module.cpp.
const Model& smtrat::Module::model () const inline inherited
Returns
The assignment of the current satisfiable result, if existent.
Definition at line 344 of file Module.h.
Referenced by smtrat::Manager::model(), and smtrat::Module::printModel().
bool Module::modelsDisjoint (const Model & _modelA, const Model & _modelB) static protected inherited
Checks whether there is no variable assigned by both models.
Parameters
_modelA The first model to check for.
_modelB The second model to check for.
Returns
true, if there is no variable assigned by both models; false, otherwise.
Definition at line 505 of file Module.cpp.
template<typename Settings > std::string smtrat::PreprocessingModule< Settings >::moduleName () const inline virtual
Returns
The name of the given module type as name.
Reimplemented from smtrat::Module.
Definition at line 62 of file PreprocessingModule.h.
carl::Variable::Arg smtrat::Module::objective () const inline inherited
Definition at line 509 of file Module.h.
Referenced by smtrat::Manager::getBackends().
bool Module::originInReceivedFormula (const FormulaT & _origin) const protected inherited
Definition at line 294 of file Module.cpp.
ModuleInput::iterator smtrat::Module::passedFormulaBegin () inline protected inherited
Returns
An iterator to the end of the passed formula. TODO: disable this method
Definition at line 695 of file Module.h.
ModuleInput::iterator smtrat::Module::passedFormulaEnd () inline protected inherited
Returns
An iterator to the end of the passed formula.
Definition at line 703 of file Module.h.
const ModuleInput* smtrat::Module::pPassedFormula () const inline inherited
Returns
A pointer to the formula passed to the backends of this module.
Definition at line 328 of file Module.h.
Referenced by smtrat::Manager::getBackends().
const ModuleInput* smtrat::Module::pReceivedFormula () const inline inherited
Returns
A pointer to the formula passed to this module.
Definition at line 312 of file Module.h.
Referenced by smtrat::EQModule< Settings >::P_add_explicit_path_to_infeasible(), and smtrat::EQModule< Settings >::P_add_explicit_path_to_infeasible_neg().
void Module::print (const std::string _initiation = "***") const inherited
Prints everything relevant of the solver.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1096 of file Module.cpp.
Referenced by smtrat::Module::check().
void Module::printInfeasibleSubsets (const std::string _initiation = "***") const inherited
Prints the infeasible subsets.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1141 of file Module.cpp.
Referenced by smtrat::Module::print().
void Module::printModel () const inherited
Prints the assignment of this module satisfying its received formula if it satisfiable and this module could find an assignment.
Parameters
_out The stream to print the assignment on.
Definition at line 1155 of file Module.cpp.
Referenced by smtrat::Manager::printAssignment().
void Module::printPassedFormula (const std::string _initiation = "***") const inherited
Prints the vector of passed formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1123 of file Module.cpp.
Referenced by smtrat::Module::print().
void Module::printReceivedFormula (const std::string _initiation = "***") const inherited
Prints the vector of the received formula.
Parameters
_out The output stream where the answer should be printed.
_initiation The line initiation.
Definition at line 1110 of file Module.cpp.
Referenced by smtrat::Module::print().
bool Module::probablyLooping (const typename Poly::PolyType & _branchingPolynomial, const Rational & _branchingValue) const protected inherited
Checks whether given the current branching value and branching variable/polynomial it is (highly) probable that this branching is part of an infinite loop of branchings.
Parameters
_branchingPolynomial The polynomial to branch at (in most branching strategies this is just a variable).
_branchingValue The value to branch at.
Returns
true, if this branching is probably part of an infinite loop of branchings; false, otherwise.
Definition at line 365 of file Module.cpp.
void smtrat::Module::receivedFormulaChecked () inline inherited
Notifies that the received formulas has been checked.
Definition at line 479 of file Module.h.
void smtrat::Module::receivedFormulasAsInfeasibleSubset (ModuleInput::const_iterator _subformula) inline protected inherited
Stores an infeasible subset consisting only of the given received formula.
Definition at line 835 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore().
void smtrat::PModule::remove (ModuleInput::const_iterator _subformula) inherited
Removes everything related to the given sub-formula of the received formula.
However, it is desired not to lose track of search spaces where no satisfying assignment can be found for the remaining sub-formulas.
Parameters
_subformula The sub formula of the received formula to remove.
Definition at line 28 of file PModule.cpp.
template<typename Settings > void smtrat::PreprocessingModule< Settings >::removeBounds (const FormulaT & formula, const FormulaT & _origin) protected
Definition at line 257 of file PreprocessingModule.cpp.
template<typename Settings > void smtrat::PreprocessingModule< Settings >::removeCore (ModuleInput::const_iterator _subformula) virtual
Removes a everything related to a sub formula of the received formula.
Parameters
_subformula The sub formula of the received formula to remove.
Reimplemented from smtrat::Module.
Definition at line 193 of file PreprocessingModule.cpp.
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::removeFactors (const FormulaT & formula) protected
Removes redundant or obsolete factors of polynomials from the formula.
Definition at line 288 of file PreprocessingModule.cpp.
std::pair<ModuleInput::iterator,bool> smtrat::Module::removeOrigin (ModuleInput::iterator _formula, const FormulaT & _origin) inline protected inherited
Definition at line 729 of file Module.h.
std::pair<ModuleInput::iterator,bool> smtrat::Module::removeOrigins (ModuleInput::iterator _formula, const std::shared_ptr< std::vector< FormulaT >> & _origins) inline protected inherited
Definition at line 738 of file Module.h.
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::removeUnboundedVars (const FormulaT & formula) protected
const ModuleInput& smtrat::Module::rPassedFormula () const inline inherited
Returns
A reference to the formula passed to the backends of this module.
Definition at line 336 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), smtrat::Manager::getBackends(), and smtrat::PModule::getReceivedFormulaSimplified().
const ModuleInput& smtrat::Module::rReceivedFormula () const inline inherited
Returns
A reference to the formula passed to this module.
Definition at line 320 of file Module.h.
Referenced by smtrat::Module::check(), smtrat::CNFerModule::checkCore(), smtrat::ICPModule< smtrat::ICPSettings1 >::contractionCandidateHasLegalOrigins(), smtrat::GBModule< Settings >::GBModule(), and smtrat::Module::generateTrivialInfeasibleSubset().
Answer smtrat::PModule::runBackends (bool _full = true) inherited
Runs the backend solvers on the passed formula.
Parameters
_full false, if this module should avoid too expensive procedures and rather return unknown instead.
Returns
True, if the passed formula is consistent; False, if the passed formula is inconsistent; Unknown, otherwise.
Definition at line 34 of file PModule.cpp.
Referenced by smtrat::CNFerModule::checkCore().
void smtrat::Module::setId (std::size_t _id) inline inherited
Sets this modules unique ID to identify itself.
Parameters
_id The id to set this module's id to.
Definition at line 286 of file Module.h.
Referenced by smtrat::Manager::getBackends().
void smtrat::Module::setObjective (carl::Variable::Arg _objective) inline inherited
Definition at line 514 of file Module.h.
Referenced by smtrat::Manager::check(), and smtrat::Manager::getBackends().
void smtrat::Module::setThreadPriority (thread_priority _threadPriority) inline inherited
Sets the priority of this module to get a thread for running its check procedure.
Parameters
_threadPriority The priority to set this module's thread priority to.
Definition at line 304 of file Module.h.
Referenced by smtrat::Manager::getBackends(), and smtrat::Manager::setStrategy().
Answer smtrat::Module::solverState () const inline inherited
Returns
True, if this module is in a state, such that it has found a solution for its received formula; False, if this module is in a state, such that it has determined that there is no solution for its received formula; Unknown, otherwise.
Definition at line 269 of file Module.h.
Referenced by smtrat::CNFerModule::checkCore(), and smtrat::PModule::getReceivedFormulaSimplified().
template<typename Settings > FormulaT smtrat::PreprocessingModule< Settings >::splitSOS (const FormulaT & formula) protected
Splits the sum-of-squares (sos) decomposition, if the given formula is a constraint with a sos as left-hand side.
Definition at line 340 of file PreprocessingModule.cpp.
const std::vector<Splitting>& smtrat::Module::splittings () const inline inherited
Returns
A constant reference to the splitting decisions this module or its backends made.
Definition at line 437 of file Module.h.
void Module::splitUnequalConstraint (const FormulaT & _unequalConstraint) protected inherited
Adds the following lemmas for the given constraint p!=0.
(p!=0 <-> (p<0 or p>0)) and not(p<0 and p>0)
Parameters
_unequalConstraint A constraint having the relation symbol !=.
Definition at line 461 of file Module.cpp.
void smtrat::Module::startAddTimer () inline inherited
Starts the timer to stop the timing for adding formulas performed by this module.
Definition at line 1100 of file Module.h.
Referenced by smtrat::Module::startTimers().
void smtrat::Module::startCheckTimer () inline inherited
Starts the timer to stop the timing for checking formulas performed by this module.
Definition at line 1120 of file Module.h.
Referenced by smtrat::Module::check(), and smtrat::Module::startTimers().
void smtrat::Module::startRemoveTimer () inline inherited
Starts the timer to stop the timing for removing formulas performed by this module.
Definition at line 1140 of file Module.h.
Referenced by smtrat::Module::startTimers().
void smtrat::Module::startTimers (int timers) inline inherited
Starts the timers according to the given integer of this module: If its first bit is set, the timer for adding formulas is started.
If its second bit is set, the timer for checking formulas is started. If its third bit is set, the timer for removing formulas is started.
Parameters
timers The integer specifying which timers to start.
Definition at line 1165 of file Module.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula().
void smtrat::Module::stopAddTimer () inline inherited
Stops the timer to stop the timing for adding formulas performed by this module.
Definition at line 1110 of file Module.h.
Referenced by smtrat::Module::stopAllTimers().
int smtrat::Module::stopAllTimers () inline inherited
Stops all timers of this module.
Returns
An integer showing which timers were stopped: If its first bit is set, the timer for adding formulas was stopped. If its second bit is set, the timer for checking formulas was stopped. If its third bit is set, the timer for removing formulas was stopped.
Definition at line 1182 of file Module.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula().
void smtrat::Module::stopCheckTimer () inline inherited
Stops the timer to stop the timing for checking formulas performed by this module.
Definition at line 1130 of file Module.h.
Referenced by smtrat::Module::check(), and smtrat::Module::stopAllTimers().
void smtrat::Module::stopRemoveTimer () inline inherited
Stops the timer to stop the timing for removing formulas performed by this module.
Definition at line 1151 of file Module.h.
Referenced by smtrat::Module::stopAllTimers().
void Module::storeAssumptionsToCheck (const Manager & _manager) static inherited
Prints the collected assumptions in the assumption vector into _filename with an appropriate smt2 header including all variables used.
Parameters
_manager The managaer object of this solver to store the assumptions for.
Definition at line 1002 of file Module.cpp.
Referenced by smtrat::SATModule< Settings >::search(), and smtrat::Manager::~Manager().
thread_priority smtrat::Module::threadPriority () const inline inherited
Returns
The priority of this module to get a thread for running its check procedure.
Definition at line 295 of file Module.h.
Referenced by smtrat::ThreadPool::checkBackendPriority(), smtrat::Manager::getBackends(), smtrat::Manager::setStrategy(), and smtrat::ThreadPool::submitBackend().
void Module::updateDeductions () inherited
Stores all deductions of any backend of this module in its own deduction vector.
Definition at line 857 of file Module.cpp.
Referenced by smtrat::Manager::lemmas().
template<typename Settings > void smtrat::PreprocessingModule< Settings >::updateModel () const virtual
Updates the model, if the solver has detected the consistency of the received formula, beforehand.
Reimplemented from smtrat::Module.
Definition at line 200 of file PreprocessingModule.cpp.
const std::vector<Module*>& smtrat::Module::usedBackends () const inline inherited
Returns
The backends of this module which are currently used (conditions to use this module are fulfilled for the passed formula).
Definition at line 361 of file Module.h.
Referenced by smtrat::PModule::getReceivedFormulaSimplified(), and smtrat::Module::getReceivedFormulaSimplified().
Field Documentation
template<typename Settings > std::map<carl::Variable,Poly> smtrat::PreprocessingModule< Settings >::arithSubs private
Definition at line 32 of file PreprocessingModule.h.
template<typename Settings > std::unordered_map<FormulaT, bool> smtrat::PreprocessingModule< Settings >::boolSubs private
Definition at line 31 of file PreprocessingModule.h.
template<typename Settings > std::function<FormulaT(FormulaT)> smtrat::PreprocessingModule< Settings >::checkBoundsFunction protected
Definition at line 114 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::PreprocessingModule().
template<typename Settings > std::function<void(FormulaT)> smtrat::PreprocessingModule< Settings >::collectUnboundedVarsFunction protected
Definition at line 106 of file PreprocessingModule.h.
template<typename Settings > std::function<FormulaT(FormulaT)> smtrat::PreprocessingModule< Settings >::eliminateMonomialEquationFunction protected
Definition at line 94 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::PreprocessingModule().
template<typename Settings > std::function<FormulaT(FormulaT)> smtrat::PreprocessingModule< Settings >::extractBoundsFunction protected
Definition at line 120 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::PreprocessingModule().
vector< string > Module::mAssumptionToCheck static inherited
Contains the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
Definition at line 184 of file Module.h.
Referenced by smtrat::Module::addAssumptionToCheck(), and smtrat::Module::storeAssumptionsToCheck().
size_t Module::mFirstPosInLastBranches static inherited
The beginning of the cylcic buffer storing the last branches.
Definition at line 192 of file Module.h.
Referenced by smtrat::Module::probablyLooping().
std::vector<FormulaSetT> smtrat::Module::mInfeasibleSubsets protected inherited
Stores the infeasible subsets.
Definition at line 132 of file Module.h.
Referenced by smtrat::CADModule< Settings >::CADModule(), smtrat::Module::checkCore(), smtrat::Module::generateTrivialInfeasibleSubset(), smtrat::Module::getInfeasibleSubsets(), smtrat::Module::hasValidInfeasibleSubset(), smtrat::Module::infeasibleSubsets(), smtrat::EQModule< Settings >::P_construct_infeasible_subset(), smtrat::Module::printInfeasibleSubsets(), smtrat::Module::receivedFormulasAsInfeasibleSubset(), and smtrat::Module::remove().
vector< Branching > Module::mLastBranches static inherited
Stores the last branches in a cycle buffer.
Definition at line 190 of file Module.h.
Referenced by smtrat::Module::probablyLooping().
Model smtrat::Module::mModel mutable protected inherited
Stores the assignment of the current satisfiable result, if existent.
Definition at line 136 of file Module.h.
Referenced by smtrat::Module::checkModel(), smtrat::Module::clearModel(), smtrat::Module::excludeNotReceivedVariablesFromModel(), smtrat::Module::getBackendsModel(), smtrat::Module::getModelEqualities(), and smtrat::Module::model().
size_t Module::mNumOfBranchVarsToStore static inherited
The number of different variables to consider for a probable infinite loop of branchings.
Definition at line 188 of file Module.h.
Referenced by smtrat::Module::probablyLooping().
Manager* const smtrat::Module::mpManager protected inherited
A reference to the manager.
Definition at line 134 of file Module.h.
Referenced by smtrat::Module::checkInfSubsetForMinimality(), smtrat::Module::clearDeductions(), smtrat::Module::eraseSubformulaFromPassedFormula(), smtrat::Module::foundAnswer(), smtrat::Module::hasDeductions(), smtrat::ICPModule< Settings >::ICPModule(), smtrat::Module::init(), smtrat::Module::probablyLooping(), and smtrat::Module::runBackends().
template<typename Settings > std::map<carl::Variable,int> smtrat::PreprocessingModule< Settings >::mVariablesBounded private
Definition at line 34 of file PreprocessingModule.h.
set< string > Module::mVariablesInAssumptionToCheck static inherited
All variables occurring in the assumptions made, which can be stored in an smtlib-file and be verified later by an external tool.
Definition at line 186 of file Module.h.
Referenced by smtrat::Module::addAssumptionToCheck().
template<typename Settings > std::unordered_set<FormulaT> smtrat::PreprocessingModule< Settings >::newBounds private
Bounds that have been added since the last call to isConsistent().
Definition at line 27 of file PreprocessingModule.h.
template<typename Settings > std::function<FormulaT(FormulaT)> smtrat::PreprocessingModule< Settings >::removeFactorsFunction protected
Definition at line 91 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::PreprocessingModule().
template<typename Settings > std::function<FormulaT(FormulaT)> smtrat::PreprocessingModule< Settings >::removeUnboundedVarsFunction protected
Definition at line 108 of file PreprocessingModule.h.
template<typename Settings > std::function<FormulaT(FormulaT)> smtrat::PreprocessingModule< Settings >::splitSOSFunction protected
Definition at line 100 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::PreprocessingModule().
template<typename Settings > FormulaSetT smtrat::PreprocessingModule< Settings >::tmpOrigins private
Definition at line 36 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::accumulateBoundOrigins().
template<typename Settings > vb::VariableBounds<FormulaT> smtrat::PreprocessingModule< Settings >::varbounds private
Collection of bounds of all received formulas.
Definition at line 29 of file PreprocessingModule.h.
Referenced by smtrat::PreprocessingModule< Settings >::accumulateBoundOrigins(), and smtrat::PreprocessingModule< Settings >::completeBounds().
template<typename Settings > carl::FormulaVisitor<FormulaT> smtrat::PreprocessingModule< Settings >::visitor private
Definition at line 24 of file PreprocessingModule.h.
The documentation for this class was generated from the following files:
lib/modules/PreprocessingModule/PreprocessingModule.h
lib/modules/PreprocessingModule/PreprocessingModule.cpp