SMT-RAT: smtrat::ModelVariable Class Reference
smtrat::ModelVariable Class Reference
#include <ModelVariable.h>
Public Member Functions
ModelVariable ()
Default constructor.
template<typename T >
ModelVariable (const T &_t)
Initializes the ModelVariable from some valid type of the underlying variant.
template<typename T >
ModelVariable & operator= (const T &_t)
Assign some value to the underlying variant.
bool isVariable () const
bool isBVVariable () const
bool isUVariable () const
bool isFunction () const
carl::Variable::Arg asVariable () const
const carl::BVVariable & asBVVariable () const
const carl::UVariable & asUVariable () const
const carl::UninterpretedFunction & asFunction () const
bool operator< (const ModelVariable &_mvar) const
bool operator== (const ModelVariable &_mvar) const
Private Types
typedef boost::variant
< carl::Variable,
carl::BVVariable,
carl::UVariable,
carl::UninterpretedFunction > Super
Base type we are deriving from.
Friends
struct std::hash< smtrat::ModelVariable >
Detailed Description
Definition at line 10 of file ModelVariable.h.
Member Typedef Documentation
typedef boost::variant<carl::Variable,carl::BVVariable,carl::UVariable,carl::UninterpretedFunction> smtrat::ModelVariable::Super private
Base type we are deriving from.
Definition at line 15 of file ModelVariable.h.
Constructor & Destructor Documentation
smtrat::ModelVariable::ModelVariable () inline
Default constructor.
Definition at line 22 of file ModelVariable.h.
template<typename T > smtrat::ModelVariable::ModelVariable (const T & _t) inline
Initializes the ModelVariable from some valid type of the underlying variant.
Definition at line 29 of file ModelVariable.h.
Member Function Documentation
const carl::BVVariable& smtrat::ModelVariable::asBVVariable () const inline
Returns
The stored value as a bitvector variable.
Definition at line 88 of file ModelVariable.h.
Referenced by operator<(), smtrat::operator<(), and operator==().
const carl::UninterpretedFunction& smtrat::ModelVariable::asFunction () const inline
Returns
The stored value as a function.
Definition at line 106 of file ModelVariable.h.
Referenced by operator<(), smtrat::operator<(), and operator==().
const carl::UVariable& smtrat::ModelVariable::asUVariable () const inline
Returns
The stored value as an uninterpreted variable.
Definition at line 97 of file ModelVariable.h.
Referenced by operator<(), smtrat::operator<(), and operator==().
carl::Variable::Arg smtrat::ModelVariable::asVariable () const inline
Returns
The stored value as a variable.
Definition at line 79 of file ModelVariable.h.
Referenced by smtrat::MCBModelSubstitution::dependsOn(), smtrat::ModelPolynomialSubstitution::dependsOn(), operator<(), smtrat::operator<(), and operator==().
bool smtrat::ModelVariable::isBVVariable () const inline
Returns
true, if the stored value is a bitvector variable.
Definition at line 55 of file ModelVariable.h.
Referenced by asBVVariable(), operator<(), smtrat::operator<(), and operator==().
bool smtrat::ModelVariable::isFunction () const inline
Returns
true, if the stored value is a function.
Definition at line 71 of file ModelVariable.h.
Referenced by asFunction(), operator<(), smtrat::operator<(), and operator==().
bool smtrat::ModelVariable::isUVariable () const inline
Returns
true, if the stored value is an uninterpreted variable.
Definition at line 63 of file ModelVariable.h.
Referenced by asUVariable(), operator<(), smtrat::operator<(), and operator==().
bool smtrat::ModelVariable::isVariable () const inline
Returns
true, if the stored value is a variable.
Definition at line 47 of file ModelVariable.h.
Referenced by asVariable(), smtrat::MCBModelSubstitution::dependsOn(), smtrat::ModelPolynomialSubstitution::dependsOn(), operator<(), smtrat::operator<(), and operator==().
bool smtrat::ModelVariable::operator< (const ModelVariable & _mvar) const inline
Returns
true, if the first argument is a variable and the second is a function or if both are variables and the first is smaller (lower id) or if both are function and the first smaller (lower id).
Definition at line 117 of file ModelVariable.h.
template<typename T > ModelVariable& smtrat::ModelVariable::operator= (const T & _t) inline
Assign some value to the underlying variant.
Parameters
t Some value.
Returns
*this.
Definition at line 38 of file ModelVariable.h.
bool smtrat::ModelVariable::operator== (const ModelVariable & _mvar) const inline
Returns
true, if the first and the second are either both variables or both functions and in the first case the variables are equal (equal ids) or in the second case the functions are equal (equal ids).
Definition at line 153 of file ModelVariable.h.
Friends And Related Function Documentation
friend struct std::hash< smtrat::ModelVariable > friend
Definition at line 18 of file ModelVariable.h.
The documentation for this class was generated from the following file:
lib/datastructures/model/ModelVariable.h