SMT-RAT: smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator > Class Template Reference
smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator > Class Template Reference
#include <FormulaVisitor.hpp>
Public Types
typedef ResultType result_type
typedef Compare compare_type
typedef Allocator allocator_type
typedef std::set< result_type,
compare_type, allocator_type > set_type
typedef FormulasMultiT multiset_type
Public Member Functions
ResultType apply (const FormulaT &formula)
Protected Member Functions
formula_visitor ()=default
~formula_visitor ()=default
Private Member Functions
SMTRAT_HAS_DECL (visit_default)
SMTRAT_HAS_DECL (visit_or)
SMTRAT_HAS_DECL (visit_and)
SMTRAT_HAS_DECL (visit_xor)
SMTRAT_HAS_DECL (visit_iff)
SMTRAT_HAS_DECL (visit_ite)
SMTRAT_HAS_DECL (visit_implication)
SMTRAT_HAS_DECL (visit_not)
SMTRAT_HAS_DECL (visit_bool)
SMTRAT_HAS_DECL (visit_constraint)
SMTRAT_HAS_DECL (visit_true)
SMTRAT_HAS_DECL (visit_false)
SMTRAT_HAS_DECL (visit_ueq)
SMTRAT_HAS_DECL (visit_forall)
SMTRAT_HAS_DECL (visit_exists)
SMTRAT_HAS_DECL (visit_quantified)
SMTRAT_HAS_DECL (visit_leaf)
SMTRAT_HAS_DECL (enter_default)
SMTRAT_HAS_DECL (enter_or)
SMTRAT_HAS_DECL (enter_and)
SMTRAT_HAS_DECL (enter_xor)
SMTRAT_HAS_DECL (enter_iff)
SMTRAT_HAS_DECL (enter_ite)
SMTRAT_HAS_DECL (enter_implication)
SMTRAT_HAS_DECL (enter_not)
SMTRAT_HAS_DECL (enter_bool)
SMTRAT_HAS_DECL (enter_constraint)
SMTRAT_HAS_DECL (enter_true)
SMTRAT_HAS_DECL (enter_false)
SMTRAT_HAS_DECL (enter_ueq)
SMTRAT_HAS_DECL (enter_forall)
SMTRAT_HAS_DECL (enter_exists)
SMTRAT_HAS_DECL (enter_quantified)
SMTRAT_HAS_DECL (enter_leaf)
template<typename = void>
result_type P_visit_default (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_default (const FormulaT &, std::false_type)
result_type P_visit_default (const FormulaT &formula)
template<typename = void>
result_type P_visit_or (const FormulaT &formula, set_type &&child_results, std::true_type)
template<typename = void>
result_type P_visit_or (const FormulaT &formula, set_type &&, std::false_type)
template<typename = void>
result_type P_visit_xor (const FormulaT &formula, multiset_type &&child_results, std::true_type)
template<typename = void>
result_type P_visit_xor (const FormulaT &formula, multiset_type &&, std::false_type)
template<typename = void>
result_type P_visit_and (const FormulaT &formula, set_type &&child_results, std::true_type)
template<typename = void>
result_type P_visit_and (const FormulaT &formula, set_type &&, std::false_type)
template<typename = void>
result_type P_visit_iff (const FormulaT &formula, set_type &&child_results, std::true_type)
template<typename = void>
result_type P_visit_iff (const FormulaT &formula, set_type &&, std::false_type)
template<typename = void>
result_type P_visit_not (const FormulaT &formula, result_type &&child_result, std::true_type)
template<typename = void>
result_type P_visit_not (const FormulaT &formula, result_type &&, std::false_type)
template<typename = void>
result_type P_visit_exists (const FormulaT &formula, result_type &&child_result, std::true_type)
template<typename = void>
result_type P_visit_exists (const FormulaT &formula, result_type &&child_result, std::false_type)
template<typename = void>
result_type P_visit_forall (const FormulaT &formula, result_type &&child_result, std::true_type)
template<typename = void>
result_type P_visit_forall (const FormulaT &formula, result_type &&child_result, std::false_type)
template<typename = void>
result_type P_visit_quantified (const FormulaT &formula, result_type &&child_result, std::true_type)
template<typename = void>
result_type P_visit_quantified (const FormulaT &formula, result_type &&, std::false_type)
template<typename = void>
result_type P_visit_leaf (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_leaf (const FormulaT &formula, std::false_type)
result_type P_visit_leaf (const FormulaT &formula)
template<typename = void>
result_type P_visit_true (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_true (const FormulaT &formula, std::false_type)
template<typename = void>
result_type P_visit_false (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_false (const FormulaT &formula, std::false_type)
template<typename = void>
result_type P_visit_ueq (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_ueq (const FormulaT &formula, std::false_type)
template<typename = void>
result_type P_visit_constraint (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_constraint (const FormulaT &formula, std::false_type)
template<typename = void>
result_type P_visit_bool (const FormulaT &formula, std::true_type)
template<typename = void>
result_type P_visit_bool (const FormulaT &formula, std::false_type)
template<typename = void>
result_type P_visit_implication (const FormulaT &formula, result_type &&premise_result, result_type &&conclusion_result, std::true_type)
template<typename = void>
result_type P_visit_implication (const FormulaT &formula, result_type &&, result_type &&, std::false_type)
template<typename = void>
result_type P_visit_ite (const FormulaT &formula, result_type &&condition_result, result_type &&true_case_result, result_type &&false_case_result, std::true_type)
template<typename = void>
result_type P_visit_ite (const FormulaT &formula, result_type &&, result_type &&, result_type &&, std::false_type)
template<typename = void>
void P_enter_default (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_default (const FormulaT &, std::false_type)
void P_enter_default (const FormulaT &formula)
template<typename = void>
void P_enter_or (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_or (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_and (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_and (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_xor (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_xor (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_iff (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_iff (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_not (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_not (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_ite (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_ite (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_implication (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_implication (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_quantified (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_quantified (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_exists (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_exists (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_forall (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_forall (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_leaf (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_leaf (const FormulaT &formula, std::false_type)
void P_enter_leaf (const FormulaT &formula)
template<typename = void>
void P_enter_true (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_true (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_false (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_false (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_ueq (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_ueq (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_constraint (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_constraint (const FormulaT &formula, std::false_type)
template<typename = void>
void P_enter_bool (const FormulaT &formula, std::true_type)
template<typename = void>
void P_enter_bool (const FormulaT &formula, std::false_type)
result_type P_dispatch (const FormulaT &formula)
Detailed Description
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type>
class smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >
Definition at line 44 of file FormulaVisitor.hpp.
Member Typedef Documentation
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> typedef Allocator smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::allocator_type
Definition at line 48 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> typedef Compare smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::compare_type
Definition at line 47 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> typedef FormulasMultiT smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::multiset_type
Definition at line 52 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> typedef ResultType smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::result_type
Definition at line 46 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> typedef std::set<result_type, compare_type, allocator_type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::set_type
Definition at line 50 of file FormulaVisitor.hpp.
Constructor & Destructor Documentation
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::formula_visitor () protected default
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::~formula_visitor () protected default
Member Function Documentation
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> ResultType smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::apply (const FormulaT & formula) inline
Definition at line 54 of file FormulaVisitor.hpp.
Referenced by smtrat::EQPreprocessingModule< Settings >::P_rewrite_bool_domain().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_dispatch (const FormulaT & formula) inline private
Definition at line 384 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::apply(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::apply(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_and (const FormulaT & formula, std::true_type) inline private
Definition at line 274 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_and (const FormulaT & formula, std::false_type) inline private
Definition at line 278 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_bool (const FormulaT & formula, std::true_type) inline private
Definition at line 376 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_bool (const FormulaT & formula, std::false_type) inline private
Definition at line 380 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_constraint (const FormulaT & formula, std::true_type) inline private
Definition at line 368 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_constraint (const FormulaT & formula, std::false_type) inline private
Definition at line 372 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_default (const FormulaT & formula, std::true_type) inline private
Definition at line 258 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_and(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_and(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_default(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_default(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_iff(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_iff(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_implication(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_implication(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_ite(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_ite(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_leaf(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_leaf(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_not(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_not(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_or(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_or(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_quantified(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_quantified(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_xor(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_xor().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_default (const FormulaT & , std::false_type) inline private
Definition at line 262 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_default (const FormulaT & formula) inline private
Definition at line 264 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_exists (const FormulaT & formula, std::true_type) inline private
Definition at line 316 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_exists (const FormulaT & formula, std::false_type) inline private
Definition at line 320 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_false (const FormulaT & formula, std::true_type) inline private
Definition at line 352 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_false (const FormulaT & formula, std::false_type) inline private
Definition at line 356 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_forall (const FormulaT & formula, std::true_type) inline private
Definition at line 324 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_forall (const FormulaT & formula, std::false_type) inline private
Definition at line 328 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_iff (const FormulaT & formula, std::true_type) inline private
Definition at line 286 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_iff (const FormulaT & formula, std::false_type) inline private
Definition at line 290 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_implication (const FormulaT & formula, std::true_type) inline private
Definition at line 304 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_implication (const FormulaT & formula, std::false_type) inline private
Definition at line 308 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_ite (const FormulaT & formula, std::true_type) inline private
Definition at line 298 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_ite (const FormulaT & formula, std::false_type) inline private
Definition at line 302 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_leaf (const FormulaT & formula, std::true_type) inline private
Definition at line 332 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_bool(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_bool(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_constraint(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_constraint(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_false(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_false(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_leaf(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_leaf(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_true(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_true(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_ueq(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_ueq().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_leaf (const FormulaT & formula, std::false_type) inline private
Definition at line 336 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_leaf (const FormulaT & formula) inline private
Definition at line 340 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_not (const FormulaT & formula, std::true_type) inline private
Definition at line 292 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_not (const FormulaT & formula, std::false_type) inline private
Definition at line 296 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_or (const FormulaT & formula, std::true_type) inline private
Definition at line 268 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_or (const FormulaT & formula, std::false_type) inline private
Definition at line 272 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_quantified (const FormulaT & formula, std::true_type) inline private
Definition at line 310 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_exists(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_exists(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_enter_forall(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_enter_forall().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_quantified (const FormulaT & formula, std::false_type) inline private
Definition at line 314 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_true (const FormulaT & formula, std::true_type) inline private
Definition at line 344 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_true (const FormulaT & formula, std::false_type) inline private
Definition at line 348 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_ueq (const FormulaT & formula, std::true_type) inline private
Definition at line 360 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_ueq (const FormulaT & formula, std::false_type) inline private
Definition at line 364 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_xor (const FormulaT & formula, std::true_type) inline private
Definition at line 280 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> void smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_enter_xor (const FormulaT & formula, std::false_type) inline private
Definition at line 284 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_and (const FormulaT & formula, set_type && child_results, std::true_type) inline private
Definition at line 142 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_and (const FormulaT & formula, set_type && , std::false_type) inline private
Definition at line 146 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_bool (const FormulaT & formula, std::true_type) inline private
Definition at line 234 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_bool (const FormulaT & formula, std::false_type) inline private
Definition at line 238 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_constraint (const FormulaT & formula, std::true_type) inline private
Definition at line 226 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_constraint (const FormulaT & formula, std::false_type) inline private
Definition at line 230 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_default (const FormulaT & formula, std::true_type) inline private
Definition at line 114 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_and(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_and(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_default(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_default(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_iff(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_iff(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_implication(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_implication(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_ite(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_ite(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_leaf(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_leaf(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_not(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_not(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_or(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_or(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_quantified(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_quantified(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_xor(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_xor().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_default (const FormulaT & , std::false_type) inline private
Definition at line 118 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_default (const FormulaT & formula) inline private
Definition at line 122 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_exists (const FormulaT & formula, result_type && child_result, std::true_type) inline private
Definition at line 166 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_exists (const FormulaT & formula, result_type && child_result, std::false_type) inline private
Definition at line 170 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_false (const FormulaT & formula, std::true_type) inline private
Definition at line 210 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_false (const FormulaT & formula, std::false_type) inline private
Definition at line 214 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_forall (const FormulaT & formula, result_type && child_result, std::true_type) inline private
Definition at line 174 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_forall (const FormulaT & formula, result_type && child_result, std::false_type) inline private
Definition at line 178 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_iff (const FormulaT & formula, set_type && child_results, std::true_type) inline private
Definition at line 150 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_iff (const FormulaT & formula, set_type && , std::false_type) inline private
Definition at line 154 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_implication (const FormulaT & formula, result_type && premise_result, result_type && conclusion_result, std::true_type) inline private
Definition at line 242 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_implication (const FormulaT & formula, result_type && , result_type && , std::false_type) inline private
Definition at line 246 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_ite (const FormulaT & formula, result_type && condition_result, result_type && true_case_result, result_type && false_case_result, std::true_type) inline private
Definition at line 250 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_ite (const FormulaT & formula, result_type && , result_type && , result_type && , std::false_type) inline private
Definition at line 254 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_leaf (const FormulaT & formula, std::true_type) inline private
Definition at line 190 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_bool(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_bool(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_constraint(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_constraint(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_false(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_false(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_leaf(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_leaf(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_true(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_true(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_ueq(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_ueq().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_leaf (const FormulaT & formula, std::false_type) inline private
Definition at line 194 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_leaf (const FormulaT & formula) inline private
Definition at line 198 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_not (const FormulaT & formula, result_type && child_result, std::true_type) inline private
Definition at line 158 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_not (const FormulaT & formula, result_type && , std::false_type) inline private
Definition at line 162 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_or (const FormulaT & formula, set_type && child_results, std::true_type) inline private
Definition at line 126 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_or (const FormulaT & formula, set_type && , std::false_type) inline private
Definition at line 130 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_quantified (const FormulaT & formula, result_type && child_result, std::true_type) inline private
Definition at line 182 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_exists(), smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_exists(), smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_visit_forall(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_visit_forall().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_quantified (const FormulaT & formula, result_type && , std::false_type) inline private
Definition at line 186 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_true (const FormulaT & formula, std::true_type) inline private
Definition at line 202 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_true (const FormulaT & formula, std::false_type) inline private
Definition at line 206 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_ueq (const FormulaT & formula, std::true_type) inline private
Definition at line 218 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_ueq (const FormulaT & formula, std::false_type) inline private
Definition at line 222 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_xor (const FormulaT & formula, multiset_type && child_results, std::true_type) inline private
Definition at line 134 of file FormulaVisitor.hpp.
Referenced by smtrat::formula_visitor< CollectBoolsInUEQs, void >::P_dispatch(), and smtrat::formula_visitor< ConcreteType, void, Compare, Allocator >::P_dispatch().
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> template<typename = void> result_type smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::P_visit_xor (const FormulaT & formula, multiset_type && , std::false_type) inline private
Definition at line 138 of file FormulaVisitor.hpp.
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_default) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_or) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_and) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_xor) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_iff) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_ite) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_implication) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_not) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_bool) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_constraint) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_true) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_false) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_ueq) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_forall) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_exists) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_quantified) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (visit_leaf) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_default) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_or) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_and) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_xor) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_iff) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_ite) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_implication) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_not) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_bool) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_constraint) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_true) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_false) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_ueq) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_forall) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_exists) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_quantified) private
template<typename ConcreteType, typename ResultType, typename Compare = typename default_compare<ResultType>::type, typename Allocator = typename default_allocator<ResultType>::type> smtrat::formula_visitor< ConcreteType, ResultType, Compare, Allocator >::SMTRAT_HAS_DECL (enter_leaf) private
The documentation for this class was generated from the following file:
lib/modules/EQPreprocessingModule/FormulaVisitor.hpp