SMT-RAT: smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings > Class Template Reference
smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings > Class Template Reference
#include <Projection_SO.h>
Data Structures
struct PolynomialComparator
Public Types
using PolynomialSelection = Bitset
Public Member Functions
void reset (const std::vector< carl::Variable > &vars)
void addPolynomial (const UPoly &p, std::size_t cid)
Adds the given polynomial to the projection.
void removePolynomial (const UPoly &p, std::size_t cid, const std::function< void(std::size_t, SampleLiftedWith)> &callback)
Removes the given polynomial from the projection.
bool projectNewPolynomial (std::size_t level, const ConstraintSelection &ps=Bitset(true))
void addPolynomial (const Poly &p, std::size_t cid)
Adds the given polynomial to the projection. Converts to a UPoly and calls the appropriate overload.
void removePolynomial (const Poly &p, std::size_t cid, const std::function< void(std::size_t, SampleLiftedWith)> &callback)
Removes the given polynomial from the projection. Converts to a UPoly and calls the appropriate overload.
std::size_t size (std::size_t level) const
bool empty (std::size_t level) const
OptionalPoly getPolyForLifting (std::size_t level, SampleLiftedWith &slw)
OptionalPoly getPolyForLifting (std::size_t level, SampleLiftedWith &slw, const ConstraintSelection &cs)
const UPoly & getPolynomialById (std::size_t level, std::size_t id) const
Retrieves a polynomial from its id.
const Variables & vars () const
Returns the variables used for projection.
void cleanLiftedWith (std::size_t level, SampleLiftedWith &slw) const
Cleans up the given list of polynomial ids a sample was lifted with from polynomials that got removed in the meantime.
Protected Member Functions
std::size_t dim () const
Returns the dimension of the projection.
std::size_t getID (std::size_t level)
Returns a fresh polynomial id for the given level.
void freeID (std::size_t level, std::size_t id)
Frees a currently used polynomial id for the given level.
carl::Variable var (std::size_t level) const
Returns the variable that corresponds to the given level, that is the variable eliminated in this level.
bool canBePurged (const UPoly &p) const
Checks whether a polynomial can safely be ignored.
bool canBeForwarded (std::size_t level, const UPoly &p) const
Checks whether a polynomial can safely be forwarded to the next level.
Protected Attributes
Variables mVariables
List of variables.
std::vector< IDPool > mIDPools
Lift of id pools to generate fresh IDs for polynomials.
std::vector
< PolynomialLiftingQueue
< BaseProjection > > mLiftingQueues
List of lifting queues that can be used for incremental projection.
ProjectionOperator mOperator
The projection operator.
Private Types
using Super = Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >
using QueueEntry = std::pair< UPoly, std::size_t >
Private Attributes
PriorityQueue< QueueEntry,
PolynomialComparator > mQueue
Friends
template<typename S >
std::ostream & operator<< (std::ostream &os, const Projection< Incrementality::SIMPLE, Backtracking::ORDERED, S > &p)
Detailed Description
template<typename Settings>
class smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >
Definition at line 15 of file Projection_SO.h.
Member Typedef Documentation
using smtrat::cad::BaseProjection::PolynomialSelection = Bitset inherited
Definition at line 15 of file BaseProjection.h.
template<typename Settings > using smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::QueueEntry = std::pair<UPoly,std::size_t> private
Definition at line 18 of file Projection_SO.h.
template<typename Settings > using smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::Super = Projection<Incrementality::NONE, Backtracking::UNORDERED, Settings> private
Definition at line 17 of file Projection_SO.h.
Member Function Documentation
template<typename Settings > void smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::addPolynomial (const UPoly & p, std::size_t cid) inline virtual
Adds the given polynomial to the projection.
Reimplemented from smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >.
Definition at line 32 of file Projection_SO.h.
void smtrat::cad::BaseProjection::addPolynomial (const Poly & p, std::size_t cid) inline inherited
Adds the given polynomial to the projection. Converts to a UPoly and calls the appropriate overload.
Definition at line 70 of file BaseProjection.h.
bool smtrat::cad::BaseProjection::canBeForwarded (std::size_t level, const UPoly & p) const inline protected inherited
Checks whether a polynomial can safely be forwarded to the next level.
Definition at line 52 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection().
bool smtrat::cad::BaseProjection::canBePurged (const UPoly & p) const inline protected inherited
Checks whether a polynomial can safely be ignored.
Definition at line 48 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection().
void smtrat::cad::BaseProjection::cleanLiftedWith (std::size_t level, SampleLiftedWith & slw) const inline inherited
Cleans up the given list of polynomial ids a sample was lifted with from polynomials that got removed in the meantime.
Definition at line 83 of file BaseProjection.h.
std::size_t smtrat::cad::BaseProjection::dim () const inline protected inherited
Returns the dimension of the projection.
Definition at line 27 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addToProjection(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection(), smtrat::cad::BaseProjection::freeID(), smtrat::cad::BaseProjection::getID(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::removePolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::removePolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::reset(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::reset(), and smtrat::cad::BaseProjection::var().
template<typename Settings > bool smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::empty (std::size_t level) const inline inherited
Definition at line 97 of file Projection_NU.h.
void smtrat::cad::BaseProjection::freeID (std::size_t level, std::size_t id) inline protected inherited
Frees a currently used polynomial id for the given level.
Definition at line 38 of file BaseProjection.h.
std::size_t smtrat::cad::BaseProjection::getID (std::size_t level) inline protected inherited
Returns a fresh polynomial id for the given level.
Definition at line 33 of file BaseProjection.h.
template<typename Settings > OptionalPoly smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::getPolyForLifting (std::size_t level, SampleLiftedWith & slw) inline inherited
Definition at line 105 of file Projection_NU.h.
template<typename Settings > OptionalPoly smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::getPolyForLifting (std::size_t level, SampleLiftedWith & slw, const ConstraintSelection & cs) inline inherited
Definition at line 119 of file Projection_NU.h.
template<typename Settings > const UPoly& smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::getPolynomialById (std::size_t level, std::size_t id) const inline virtual inherited
Retrieves a polynomial from its id.
Implements smtrat::cad::BaseProjection.
Definition at line 131 of file Projection_NU.h.
template<typename Settings > bool smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::projectNewPolynomial (std::size_t level, const ConstraintSelection & ps = Bitset(true)) inline
Definition at line 44 of file Projection_SO.h.
template<typename Settings > void smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::removePolynomial (const UPoly & p, std::size_t cid, const std::function< void(std::size_t, SampleLiftedWith)> & callback) inline virtual
Removes the given polynomial from the projection.
Reimplemented from smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >.
Definition at line 35 of file Projection_SO.h.
void smtrat::cad::BaseProjection::removePolynomial (const Poly & p, std::size_t cid, const std::function< void(std::size_t, SampleLiftedWith)> & callback) inline inherited
Removes the given polynomial from the projection. Converts to a UPoly and calls the appropriate overload.
Definition at line 76 of file BaseProjection.h.
template<typename Settings > void smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::reset (const std::vector< carl::Variable > & vars) inline
Definition at line 28 of file Projection_SO.h.
template<typename Settings > std::size_t smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::size (std::size_t level) const inline inherited
Definition at line 94 of file Projection_NU.h.
carl::Variable smtrat::cad::BaseProjection::var (std::size_t level) const inline protected inherited
Returns the variable that corresponds to the given level, that is the variable eliminated in this level.
Definition at line 43 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addPolynomial(), smtrat::cad::BaseProjection::addPolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addPolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addToProjection(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection(), and smtrat::cad::BaseProjection::removePolynomial().
const Variables& smtrat::cad::BaseProjection::vars () const inline inherited
Returns the variables used for projection.
Definition at line 57 of file BaseProjection.h.
Referenced by smtrat::cad::BaseProjection::reset().
Friends And Related Function Documentation
template<typename Settings > template<typename S > std::ostream& operator<< (std::ostream & os, const Projection< Incrementality::SIMPLE, Backtracking::ORDERED, S > & p) friend
Definition at line 56 of file Projection_SO.h.
Field Documentation
std::vector<IDPool> smtrat::cad::BaseProjection::mIDPools protected inherited
Lift of id pools to generate fresh IDs for polynomials.
Definition at line 20 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addToProjection(), smtrat::cad::BaseProjection::cleanLiftedWith(), smtrat::cad::BaseProjection::dim(), smtrat::cad::BaseProjection::freeID(), smtrat::cad::BaseProjection::getID(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::removePolynomial(), and smtrat::cad::BaseProjection::reset().
std::vector<PolynomialLiftingQueue<BaseProjection> > smtrat::cad::BaseProjection::mLiftingQueues protected inherited
List of lifting queues that can be used for incremental projection.
Definition at line 22 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addToProjection(), smtrat::cad::BaseProjection::dim(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::getPolyForLifting(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::getPolyForLifting(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::insertPolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::removePolynomial(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::removePolynomial(), and smtrat::cad::BaseProjection::reset().
ProjectionOperator smtrat::cad::BaseProjection::mOperator protected inherited
The projection operator.
Definition at line 24 of file BaseProjection.h.
Referenced by smtrat::cad::Projection< Incrementality::NONE, Backtracking::UNORDERED, Settings >::addToProjection(), and smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::addToProjection().
template<typename Settings > PriorityQueue<QueueEntry, PolynomialComparator> smtrat::cad::Projection< Incrementality::SIMPLE, Backtracking::ORDERED, Settings >::mQueue private
Definition at line 26 of file Projection_SO.h.
Variables smtrat::cad::BaseProjection::mVariables protected inherited
List of variables.
Definition at line 18 of file BaseProjection.h.
Referenced by smtrat::cad::BaseProjection::dim(), smtrat::cad::BaseProjection::reset(), smtrat::cad::BaseProjection::var(), and smtrat::cad::BaseProjection::vars().
The documentation for this class was generated from the following file:
lib/datastructures/cad/projection/Projection_SO.h