SMT-RAT: smtrat::Manager Class Reference
smtrat::Manager Class Reference
Base class for solvers.
#include <Manager.h>
Public Member Functions
Manager ()
Constructs a manager.
~Manager ()
Destructs a manager.
bool inform (const FormulaT &_constraint)
Informs the solver about a constraint.
void deinform (const FormulaT &_constraint)
The inverse of informing about a constraint.
bool add (const FormulaT &_subformula, bool _containsUnknownConstraints=true)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Answer check (bool _full=true)
Checks the so far added formulas for satisfiability.
void push ()
Pushes a backtrack point to the stack of backtrack points.
bool pop ()
Pops a backtrack point from the stack of backtrack points.
void pop (size_t _levels)
void clear ()
void setObjectiveVariable (carl::Variable var)
const carl::Variable & objectiveVariable () const
void reset ()
const std::vector< FormulaSetT > & infeasibleSubsets () const
std::list< std::vector< carl::Variable > > getModelEqualities () const
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
const Model & model () const
const std::vector< Model > & allModels () const
std::vector< FormulaT > lemmas ()
Returns the lemmas/tautologies which were made during the last solving provoked by check().
const ModuleInput & formula () const
ModuleInput::iterator formulaBegin ()
ModuleInput::iterator formulaEnd ()
void printAssignment () const
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
void printAllAssignments (std::ostream &_out=std::cout)
Prints all assignments of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
void printInfeasibleSubset (std::ostream &=std::cout) const
Prints the first found infeasible subset of the set of received formulas.
void printBackTrackStack (std::ostream &=std::cout) const
Prints the stack of backtrack points.
void printStrategyGraph (std::ostream &_os=std::cout) const
Prints the strategy of the solver maintained by this manager.
const std::vector< Module * > & getAllGeneratedModules () const
std::ostream & rDebugOutputChannel ()
auto logic () const
auto & rLogic ()
void addInformationRelevantFormula (const FormulaT &formula)
Adds formula to InformationRelevantFormula.
void clearInformationRelevantFormula ()
Deletes all InformationRelevantFormula.
void setLemmaLevel (LemmaLevel level)
Sets the current level for lemma generation.
bool isLemmaLevel (LemmaLevel level)
Checks if current lemma level is greater or equal to given level.
std::pair< bool, FormulaT > getInputSimplified ()
ModuleInput::iterator remove (ModuleInput::iterator _subformula)
Removes the formula at the given position in the conjunction of formulas, which will be considered for the next satisfiability check.
ModuleInput::iterator remove (const FormulaT &_subformula)
Temporarily added: (TODO: Discuss with Gereon) Removes the given formula in the conjunction of formulas, which will be considered for the next satisfiability check.
Protected Member Functions
void setStrategy (const std::initializer_list< BackendLink > &backends)
void setStrategy (const BackendLink &backend)
template<typename Module >
BackendLink addBackend (const std::initializer_list< BackendLink > &backends={})
template<typename Module >
BackendLink addBackend (const BackendLink &backend)
BackendLink & addEdge (std::size_t from, std::size_t to)
std::vector< Module * > getAllBackends (Module *_module) const
Gets all backends so far instantiated according the strategy and all previous enquiries of the given module.
std::vector< Module * > getBackends (Module *, std::atomic_bool *)
Get the backends to call for the given problem instance required by the given module.
const std::set< FormulaT > & getInformationRelevantFormulas ()
Gets all InformationRelevantFormulas.
Private Attributes
smtrat::Conditionals mPrimaryBackendFoundAnswer
a vector of flags, which indicate that an answer has been found of an antecessor module of the primary module
ModuleInput * mpPassedFormula
the constraints so far passed to the primary backend
carl::Condition mPropositions
The propositions of the passed formula.
std::vector< ModuleInput::iterator > mBacktrackPoints
Contains the backtrack points, that are iterators to the last formula to be kept when backtracking to the respective point.
std::vector< Module * > mGeneratedModules
all generated instances of modules
std::map< const Module *const, std::vector< Module * > > mBackendsOfModules
a mapping of each module to its backends
Module * mpPrimaryBackend
the primary backends
bool mBackendsUptodate
a Boolean showing whether the manager has received new constraint after the last consistency check
StrategyGraph mStrategyGraph
primary strategy
std::ostream mDebugOutputChannel
channel to write debug output
carl::Logic mLogic
the logic this solver considers
std::set< FormulaT > mInformationRelevantFormula
List of formula which are relevant for certain tasks.
LemmaLevel mLemmaLevel
Level of lemma generation.
carl::Variable mObjectiveVariable
objective variable
Friends
class Module
Detailed Description
Base class for solvers.
This is the interface to the user.
Definition at line 34 of file Manager.h.
Member Function Documentation
add()
bool smtrat::Manager::add (const FormulaT & _subformula, bool _containsUnknownConstraints = true)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The formula to add.
_containsUnknownConstraints true, if the formula to add contains constraints, about which this solver was not yet informed.
Returns
false, if it is easy to decide whether adding this formula creates a conflict; true, otherwise.
Definition at line 95 of file Manager.cpp.
addInformationRelevantFormula()
void smtrat::Manager::addInformationRelevantFormula (const FormulaT & formula) inline
Adds formula to InformationRelevantFormula.
Parameters
formula Formula to add
Definition at line 325 of file Manager.h.
Referenced by smtrat::Module::addInformationRelevantFormula().
allModels()
const std::vector<Model>& smtrat::Manager::allModels () const inline
Returns
A list of all assignments, such that they satisfy the conjunction of the so far added formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 218 of file Manager.h.
check()
Answer smtrat::Manager::check (bool _full = true)
Checks the so far added formulas for satisfiability.
Returns
True, if the conjunction of the so far added formulas is satisfiable; False, if it not satisfiable; Unknown, if this solver cannot decide whether it is satisfiable or not.
Definition at line 125 of file Manager.cpp.
deinform()
void smtrat::Manager::deinform (const FormulaT & _constraint)
The inverse of informing about a constraint.
All data structures which were kept regarding this constraint are going to be removed. Note, that this makes only sense if it is not likely enough that a formula with this constraint must be solved again.
Parameters
_constraint The constraint to remove from internal data structures.
Definition at line 90 of file Manager.cpp.
formula()
const ModuleInput& smtrat::Manager::formula () const inline
Returns
The conjunction of so far added formulas.
Definition at line 234 of file Manager.h.
Referenced by addInformationRelevantFormula().
getAllBackends()
std::vector<Module*> smtrat::Manager::getAllBackends (Module * _module) const inline protected
Gets all backends so far instantiated according the strategy and all previous enquiries of the given module.
Parameters
_module The module to get all backends so far instantiated according the strategy and all previous enquiries of this module.
Returns
All backends so far instantiated according the strategy and all previous enquiries of the given module.
Definition at line 417 of file Manager.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula(), smtrat::Module::init(), and smtrat::Module::runBackends().
getAllGeneratedModules()
const std::vector<Module*>& smtrat::Manager::getAllGeneratedModules () const inline
Returns
All instantiated modules of the solver belonging to this manager.
Definition at line 294 of file Manager.h.
getBackends()
std::vector< Module * > smtrat::Manager::getBackends (Module * _requiredBy, std::atomic_bool * _foundAnswer) protected
Get the backends to call for the given problem instance required by the given module.
Parameters
_formula The problem instance.
_requiredBy The module asking for a backend.
_foundAnswer A conditional
Returns
A vector of modules, which the module defined by _requiredBy calls in parallel to achieve an answer to the given instance.
Definition at line 286 of file Manager.cpp.
Referenced by smtrat::Module::init(), and smtrat::Module::runBackends().
getInformationRelevantFormulas()
const std::set<FormulaT>& smtrat::Manager::getInformationRelevantFormulas () inline protected
Gets all InformationRelevantFormulas.
Returns
Set of all formulas
Definition at line 471 of file Manager.h.
Referenced by smtrat::Module::getInformationRelevantFormulas().
getInputSimplified()
std::pair< bool, FormulaT > smtrat::Manager::getInputSimplified ()
Returns
A pair of a Boolean and a formula, where the Boolean is true, if the input formula could be simplified to an equisatisfiable formula. The formula is equisatisfiable to this solver's input formula, if the Boolean is true.
Definition at line 159 of file Manager.cpp.
getModelEqualities()
std::list< std::vector< carl::Variable > > smtrat::Manager::getModelEqualities () const
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
Returns
A list of vectors of variables, stating that the variables in one vector are assigned to equal values.
Definition at line 137 of file Manager.cpp.
infeasibleSubsets()
const std::vector< FormulaSetT > & smtrat::Manager::infeasibleSubsets () const
Returns
All infeasible subsets of the set so far added formulas.
Note, that the conjunction of the so far added formulas must be inconsistent to receive an infeasible subset.
Definition at line 132 of file Manager.cpp.
inform()
bool smtrat::Manager::inform (const FormulaT & _constraint)
Informs the solver about a constraint.
Optimally, it should be informed about all constraints, which it will receive eventually, before any of them is added as part of a formula with the interface add(..).
Parameters
_constraint The constraint to inform about.
Returns
false, if it is easy to decide (for any module used of this solver), whether the constraint itself is inconsistent; true, otherwise.
Definition at line 85 of file Manager.cpp.
isLemmaLevel()
bool smtrat::Manager::isLemmaLevel (LemmaLevel level) inline
Checks if current lemma level is greater or equal to given level.
Parameters
level Level to check.
Definition at line 351 of file Manager.h.
Referenced by smtrat::Module::isLemmaLevel().
lemmas()
std::vector< FormulaT > smtrat::Manager::lemmas ()
Returns the lemmas/tautologies which were made during the last solving provoked by check().
These lemmas can be used in the same manner as infeasible subsets are used.
Returns
The lemmas/tautologies made during solving.
Definition at line 148 of file Manager.cpp.
logic()
auto smtrat::Manager::logic () const inline
Returns
A constant reference to the logic this solver considers.
Definition at line 310 of file Manager.h.
Referenced by smtrat::Module::checkInfSubsetForMinimality().
model()
const Model & smtrat::Manager::model () const
Returns
An assignment of the variables, which occur in the so far added formulas, to values of their domains, such that it satisfies the conjunction of these formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 142 of file Manager.cpp.
pop()
bool smtrat::Manager::pop (void)
Pops a backtrack point from the stack of backtrack points.
This provokes, that all formulas which have been added after that backtrack point are removed.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 176 of file Manager.cpp.
printAllAssignments()
void smtrat::Manager::printAllAssignments (std::ostream & _out = std::cout) inline
Prints all assignments of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
Parameters
The stream to print on.
Definition at line 263 of file Manager.h.
printAssignment()
void smtrat::Manager::printAssignment () const
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
Parameters
The stream to print on.
Definition at line 164 of file Manager.cpp.
printBackTrackStack()
void smtrat::Manager::printBackTrackStack (std::ostream & _out = std::cout) const
Prints the stack of backtrack points.
Parameters
_out The stream to print on.
Definition at line 262 of file Manager.cpp.
printInfeasibleSubset()
void smtrat::Manager::printInfeasibleSubset (std::ostream & _out = std::cout) const
Prints the first found infeasible subset of the set of received formulas.
Parameters
_out The stream to print on.
Definition at line 241 of file Manager.cpp.
printStrategyGraph()
void smtrat::Manager::printStrategyGraph (std::ostream & _os = std::cout) const inline
Prints the strategy of the solver maintained by this manager.
Parameters
_out The stream to print on.
Definition at line 284 of file Manager.h.
push()
void smtrat::Manager::push (void) inline
Pushes a backtrack point to the stack of backtrack points.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 147 of file Manager.h.
rDebugOutputChannel()
std::ostream& smtrat::Manager::rDebugOutputChannel () inline
Returns
The stream to print the debug information on.
Definition at line 302 of file Manager.h.
remove() [1/2]
ModuleInput::iterator smtrat::Manager::remove (ModuleInput::iterator _subformula)
Removes the formula at the given position in the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The position of the formula to remove.
Returns
An iterator to the formula after the position of the just removed formula. If the removed formula has been the last element, the end of the conjunction of formulas, which will be considered for the next satisfiability check is returned.
Definition at line 169 of file Manager.cpp.
remove() [2/2]
ModuleInput::iterator smtrat::Manager::remove (const FormulaT & _subformula) inline
Temporarily added: (TODO: Discuss with Gereon) Removes the given formula in the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters
_subformula The formula to remove.
Returns
An iterator to the formula after the position of the just removed formula. If the removed formula has been the last element, the end of the conjunction of formulas, which will be considered for the next satisfiability check is returned.
Definition at line 384 of file Manager.h.
rLogic()
auto& smtrat::Manager::rLogic () inline
Returns
A reference to the logic this solver considers.
Definition at line 317 of file Manager.h.
setLemmaLevel()
void smtrat::Manager::setLemmaLevel (LemmaLevel level) inline
Sets the current level for lemma generation.
Parameters
level Level
Definition at line 342 of file Manager.h.
The documentation for this class was generated from the following files:
smtrat-solver/Manager.h
smtrat-solver/Manager.cpp