SMT-RAT: smtrat::vb::VariableBounds< T > Class Template Reference
smtrat::vb::VariableBounds< T > Class Template Reference
Class to manage the bounds of a variable.
#include <VariableBounds.h>
Public Types
typedef std::map< ConstraintT, const Bound< T > * > ConstraintBoundMap
A map from Constraint pointers to Bound pointers.
typedef carl::FastMap< carl::Variable, Variable< T > * > VariableMap
A hash-map from arithmetic variables to variables managing the bounds.
Public Member Functions
VariableBounds ()
Constructs a variable bounds manager.
~VariableBounds ()
Destructs a variable bounds manager.
void clear ()
bool empty () const
bool addBound (const ConstraintT &_constraint, const T &_origin)
Updates the variable bounds by the given constraint.
bool addBound (const FormulaT &_formula, const T &_origin)
unsigned removeBound (const ConstraintT &_constraint, const T &_origin)
Removes all effects the given constraint has on the variable bounds.
unsigned removeBound (const FormulaT &_formula, const T &_origin)
unsigned removeBound (const ConstraintT &_constraint, const T &_origin, carl::Variable *&_changedVariable)
Removes all effects the given constraint has on the variable bounds.
const EvalRationalIntervalMap & getEvalIntervalMap () const
Creates an evalintervalmap corresponding to the variable bounds.
const RationalInterval & getInterval (const carl::Variable &_var) const
Creates an interval corresponding to the variable bounds of the given variable.
RationalInterval getInterval (carl::Monomial::Arg _mon) const
Creates an interval corresponding to the bounds of the given monomial.
RationalInterval getInterval (const TermT &_term) const
Creates an interval corresponding to the bounds of the given term.
const smtrat::EvalDoubleIntervalMap & getIntervalMap () const
Creates an interval map corresponding to the variable bounds.
const carl::Interval< double > & getDoubleInterval (const carl::Variable &_var) const
Creates a double interval corresponding to the variable bounds of the given variable.
std::vector< T > getOriginsOfBounds (const carl::Variable &_var) const
std::set< T > getOriginSetOfBounds (const carl::Variable &_var) const
std::vector< T > getOriginsOfBounds (const carl::Variables &_variables) const
std::set< T > getOriginSetOfBounds (const carl::Variables &_variables) const
std::vector< T > getOriginsOfBounds () const
Collect the origins to the supremums and infimums of all variables.
std::set< T > getOriginSetOfBounds () const
std::vector< std::pair< std::vector< ConstraintT >, ConstraintT > > getBoundDeductions () const
void print (std::ostream &_out=std::cout, const std::string _init="", bool _printAllBounds=false) const
Prints the variable bounds.
bool isConflicting () const
std::set< T > getConflict () const
Private Attributes
Variable< T > * mpConflictingVariable
A pointer to one of the conflicting variables (its supremum is smaller than its infimum) or NULL if there is no conflict.
VariableMap * mpVariableMap
A mapping from arithmetic variables to the variable objects storing the bounds.
ConstraintBoundMap * mpConstraintBoundMap
A mapping from constraint pointer to the corresponding bounds.
EvalRationalIntervalMap mEvalIntervalMap
The stored exact interval map representing the currently tightest bounds.
EvalDoubleIntervalMap mDoubleIntervalMap
The stored double interval map representing the currently tightest bounds.
ConstraintsT mNonBoundConstraints
Stores the constraints which cannot be used to infer a bound for a variable.
std::unordered_set< std::vector< ConstraintT > > mBoundDeductions
Stores deductions which this variable bounds manager has detected.
Detailed Description
template<typename T>
class smtrat::vb::VariableBounds< T >
Class to manage the bounds of a variable.
Definition at line 356 of file VariableBounds.h.
Member Function Documentation
addBound()
template<typename T> bool smtrat::vb::VariableBounds< T >::addBound (const ConstraintT & _constraint, const T & _origin)
Updates the variable bounds by the given constraint.
Parameters
_constraint The constraint to consider.
_origin The origin of the given constraint.
Returns
true, if the variable bounds have been changed; false, otherwise.
Referenced by smtrat::vs::State::addCondition().
getBoundDeductions()
template<typename T> std::vector<std::pair<std::vector<ConstraintT>, ConstraintT> > smtrat::vb::VariableBounds< T >::getBoundDeductions () const
Returns
The deductions which this variable bounds manager has detected.
getConflict()
template<typename T> std::set<T> smtrat::vb::VariableBounds< T >::getConflict () const inline
Returns
The origins which cause the conflict. This method can only be called, if there is a conflict.
Definition at line 518 of file VariableBounds.h.
getDoubleInterval()
template<typename T> const carl::Interval<double>& smtrat::vb::VariableBounds< T >::getDoubleInterval (const carl::Variable & _var) const
Creates a double interval corresponding to the variable bounds of the given variable.
Parameters
_var The variable to compute the variable bounds as double interval for.
Returns
The variable bounds as a double interval.
Referenced by smtrat::vs::State::hasRootsInVariableBounds(), and smtrat::vs::State::solutionSpace().
getEvalIntervalMap()
template<typename T> const EvalRationalIntervalMap& smtrat::vb::VariableBounds< T >::getEvalIntervalMap () const
Creates an evalintervalmap corresponding to the variable bounds.
Returns
The variable bounds as an evalintervalmap.
getInterval() [1/3]
template<typename T> const RationalInterval& smtrat::vb::VariableBounds< T >::getInterval (const carl::Variable & _var) const
Creates an interval corresponding to the variable bounds of the given variable.
Parameters
_var The variable to compute the variable bounds as interval for.
Returns
The variable bounds as an interval.
getInterval() [2/3]
template<typename T> RationalInterval smtrat::vb::VariableBounds< T >::getInterval (carl::Monomial::Arg _mon) const
Creates an interval corresponding to the bounds of the given monomial.
Parameters
_mon The monomial to compute the bounds as interval for.
Returns
The monomial bounds as an interval.
getInterval() [3/3]
template<typename T> RationalInterval smtrat::vb::VariableBounds< T >::getInterval (const TermT & _term) const
Creates an interval corresponding to the bounds of the given term.
Parameters
_term The term to compute the bounds as interval for.
Returns
The term bounds as an interval.
getIntervalMap()
template<typename T> const smtrat::EvalDoubleIntervalMap& smtrat::vb::VariableBounds< T >::getIntervalMap () const
Creates an interval map corresponding to the variable bounds.
Returns
The variable bounds as an interval map.
Referenced by smtrat::vs::State::hasRootsInVariableBounds(), smtrat::vs::State::simplify(), smtrat::vs::State::solutionSpace(), and smtrat::VSModule< Settings >::substituteAll().
getOriginsOfBounds() [1/3]
template<typename T> std::vector<T> smtrat::vb::VariableBounds< T >::getOriginsOfBounds (const carl::Variable & _var) const
Parameters
_var The variable to get origins of the bounds for.
Returns
The origin constraints of the supremum and infimum of the given variable.
Referenced by smtrat::vs::State::hasRootsInVariableBounds(), smtrat::vs::State::simplify(), smtrat::vs::State::solutionSpace(), and smtrat::VSModule< Settings >::substituteAll().
getOriginsOfBounds() [2/3]
template<typename T> std::vector<T> smtrat::vb::VariableBounds< T >::getOriginsOfBounds (const carl::Variables & _variables) const
Parameters
_variables The variables to get origins of the bounds for.
Returns
The origin constraints of the supremum and infimum of the given variables.
getOriginsOfBounds() [3/3]
template<typename T> std::vector<T> smtrat::vb::VariableBounds< T >::getOriginsOfBounds () const
Collect the origins to the supremums and infimums of all variables.
Returns
A set of origins corresponding to the supremums and infimums of all variables.
isConflicting()
template<typename T> bool smtrat::vb::VariableBounds< T >::isConflicting () const inline
Returns
true, if there is a conflicting variable; false, otherwise.
Definition at line 510 of file VariableBounds.h.
Referenced by smtrat::vb::VariableBounds< ConstraintT >::getConflict(), and smtrat::vs::State::simplify().
print()
template<typename T> void smtrat::vb::VariableBounds< T >::print (std::ostream & _out = std::cout, const std::string _init = "", bool _printAllBounds = false) const
Prints the variable bounds.
Parameters
_out The output stream to print on.
_init A string which is displayed at the beginning of every row.
_printAllBounds A flag that indicates whether to print also the bounds of each variable (=true).
Referenced by smtrat::vs::State::checkTestCandidatesForBounds(), and smtrat::vs::State::printAlone().
removeBound() [1/2]
template<typename T> unsigned smtrat::vb::VariableBounds< T >::removeBound (const ConstraintT & _constraint, const T & _origin)
Removes all effects the given constraint has on the variable bounds.
Parameters
_constraint The constraint, which effects shall be undone for the variable bounds.
_origin The origin of the given constraint.
Returns
2, if the variables supremum or infimum have been changed; 1, if the constraint was a (not the strictest) bound; 0, otherwise.
Referenced by smtrat::vs::State::deleteConditions(), smtrat::vs::State::deleteOrigins(), smtrat::vs::State::passConflictToFather(), smtrat::VSModule< Settings >::substituteAll(), and smtrat::vs::State::~State().
removeBound() [2/2]
template<typename T> unsigned smtrat::vb::VariableBounds< T >::removeBound (const ConstraintT & _constraint, const T & _origin, carl::Variable *& _changedVariable)
Removes all effects the given constraint has on the variable bounds.
Parameters
_constraint The constraint, which effects shall be undone for the variable bounds.
_origin The origin of the given constraint.
_changedVariable The variable whose interval domain has been changed, if the return value is 2.
Returns
2, if the variables supremum or infimum have been changed; 1, if the constraint was a (not the strictest) bound; 0, otherwise.
Field Documentation
mDoubleIntervalMap
template<typename T> EvalDoubleIntervalMap smtrat::vb::VariableBounds< T >::mDoubleIntervalMap mutable private
The stored double interval map representing the currently tightest bounds.
Note, that it is updated on demand.
Definition at line 376 of file VariableBounds.h.
mEvalIntervalMap
template<typename T> EvalRationalIntervalMap smtrat::vb::VariableBounds< T >::mEvalIntervalMap mutable private
The stored exact interval map representing the currently tightest bounds.
Note, that it is updated on demand.
Definition at line 373 of file VariableBounds.h.
mpConflictingVariable
template<typename T> Variable<T>* smtrat::vb::VariableBounds< T >::mpConflictingVariable private
A pointer to one of the conflicting variables (its supremum is smaller than its infimum) or NULL if there is no conflict.
Definition at line 366 of file VariableBounds.h.
Referenced by smtrat::vb::VariableBounds< ConstraintT >::getConflict(), and smtrat::vb::VariableBounds< ConstraintT >::isConflicting().
The documentation for this class was generated from the following file:
lib/datastructures/VariableBounds.h