SMT-RAT: smtrat::ModuleInput Class Reference
smtrat::ModuleInput Class Reference
The input formula a module has to consider for it's satisfiability check.
#include <ModuleInput.h>
Data Structures
struct IteratorCompare
Public Types
typedef super::iterator iterator
Passing through the list::iterator.
typedef super::const_iterator const_iterator
Passing through the list::const_iterator.
Public Member Functions
ModuleInput ()
Constructs a module input.
carl::Condition properties () const
bool isConstraintConjunction () const
bool isConstraintLiteralConjunction () const
bool isRealConstraintConjunction () const
bool isRealConstraintLiteralConjunction () const
bool isIntegerConstraintConjunction () const
bool isIntegerConstraintLiteralConjunction () const
bool containsBitVectorConstraints () const
bool containsBooleanVariables () const
bool containsRealVariables () const
bool containsIntegerVariables () const
bool containsUninterpretedEquations () const
bool isOnlyPropositional () const
unsigned satisfiedBy (const Model &_assignment) const
unsigned satisfiedBy (const EvalRationalMap &_assignment) const
const auto & back () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
auto rbegin () const
auto rend () const
bool empty () const
size_t size () const
iterator find (const FormulaT &_formula)
const_iterator find (const FormulaT &_formula) const
iterator find (const_iterator _hint, const FormulaT &_formula)
const_iterator find (const_iterator _hint, const FormulaT &_formula) const
bool contains (const FormulaT &_subformula) const
void updateProperties ()
Updates all properties of the formula underlying this module input.
void gatherVariables (carl::carlVariables &vars) const
void vars (carl::Variables &_vars) const
Collects all variables occurring in this formula.
void realValuedVars (carl::Variables &_realVars) const
Collects all real valued variables occurring in this formula.
void integerValuedVars (carl::Variables &_intVars) const
Collects all integer valued variables occurring in this formula.
void arithmeticVars (carl::Variables &_arithmeticVars) const
Collects all arithmetic variables occurring in this formula.
void booleanVars (carl::Variables &_booleanVars) const
Collects all Boolean variables occurring in this formula.
operator FormulaT () const
void addOrigin (iterator _formula, const FormulaT &_origin)
iterator erase (iterator _formula)
void clearOrigins (iterator _formula)
bool removeOrigin (iterator _formula, const FormulaT &_origin)
bool removeOrigins (iterator _formula, const std::shared_ptr< FormulasT > &_origins)
std::pair< iterator, bool > add (const FormulaT &_formula, bool _mightBeConjunction=true)
std::pair< iterator, bool > add (const FormulaT &_formula, const FormulaT &_origins, bool _mightBeConjunction=true)
std::pair< iterator, bool > add (const FormulaT &_formula, const std::shared_ptr< FormulasT > &_origins, bool _mightBeConjunction=true)
std::pair< iterator, bool > add (const FormulaT &_formula, bool _hasSingleOrigin, const FormulaT &_origin, const std::shared_ptr< FormulasT > &_origins, bool _mightBeConjunction=true)
Private Types
typedef std::list< FormulaWithOrigins > super
Private Attributes
carl::Condition mProperties
Store some properties about the conjunction of the stored formulas.
bool mPropertiesUpdated
A flag indicating whether the properties of this module input are updated.
carl::FastMap< FormulaT, iterator > mFormulaPositionMap
Maps all formulas occurring (in the origins) at pos i in this module input to i. This is for a faster access.
T elements
STL member.
Friends
class Module
class Manager
Detailed Description
The input formula a module has to consider for it's satisfiability check.
It is a list of formulas and semantically considered as their conjunction.
Definition at line 130 of file ModuleInput.h.
Member Function Documentation
arithmeticVars()
void smtrat::ModuleInput::arithmeticVars (carl::Variables & _arithmeticVars) const inline
Collects all arithmetic variables occurring in this formula.
Parameters
_arithmeticVars The container to collect the arithmetic variables in.
Definition at line 426 of file ModuleInput.h.
Referenced by smtrat::CNFerModule::checkCore().
booleanVars()
void smtrat::ModuleInput::booleanVars (carl::Variables & _booleanVars) const inline
Collects all Boolean variables occurring in this formula.
Parameters
_booleanVars The container to collect the Boolean variables in.
Definition at line 437 of file ModuleInput.h.
Referenced by smtrat::CNFerModule::checkCore().
contains()
bool smtrat::ModuleInput::contains (const FormulaT & _subformula) const inline
Parameters
_subformula The formula for which to check whether it is one of the stored formulas.
Returns
true, if the given formula is one of the stored formulas; false, otherwise.
Definition at line 372 of file ModuleInput.h.
Referenced by smtrat::Module::collectOrigins().
containsBitVectorConstraints()
bool smtrat::ModuleInput::containsBitVectorConstraints () const inline
Returns
true, if this formula contains bit vector constraints; false, otherwise.
Definition at line 245 of file ModuleInput.h.
containsBooleanVariables()
bool smtrat::ModuleInput::containsBooleanVariables () const inline
Returns
true, if this formula contains Boolean variables; false, otherwise.
Definition at line 254 of file ModuleInput.h.
containsIntegerVariables()
bool smtrat::ModuleInput::containsIntegerVariables () const inline
Returns
true, if this formula contains Boolean variables; false, otherwise.
Definition at line 272 of file ModuleInput.h.
containsRealVariables()
bool smtrat::ModuleInput::containsRealVariables () const inline
Returns
true, if this formula contains Boolean variables; false, otherwise.
Definition at line 263 of file ModuleInput.h.
containsUninterpretedEquations()
bool smtrat::ModuleInput::containsUninterpretedEquations () const inline
Returns
true, if this formula contains uninterpreted equations; false, otherwise.
Definition at line 281 of file ModuleInput.h.
integerValuedVars()
void smtrat::ModuleInput::integerValuedVars (carl::Variables & _intVars) const inline
Collects all integer valued variables occurring in this formula.
Parameters
_intVars The container to collect the integer valued variables in.
Definition at line 415 of file ModuleInput.h.
isConstraintConjunction()
bool smtrat::ModuleInput::isConstraintConjunction () const inline
Returns
true, if this formula is a conjunction of constraints; false, otherwise.
Definition at line 185 of file ModuleInput.h.
Referenced by isIntegerConstraintConjunction(), and isRealConstraintConjunction().
isConstraintLiteralConjunction()
bool smtrat::ModuleInput::isConstraintLiteralConjunction () const inline
Returns
true, if this formula is a conjunction of literals of constraints; false, otherwise.
Definition at line 197 of file ModuleInput.h.
Referenced by isIntegerConstraintLiteralConjunction(), and isRealConstraintLiteralConjunction().
isIntegerConstraintConjunction()
bool smtrat::ModuleInput::isIntegerConstraintConjunction () const inline
Returns
true, if this formula is a conjunction of integer constraints; false, otherwise.
Definition at line 227 of file ModuleInput.h.
isIntegerConstraintLiteralConjunction()
bool smtrat::ModuleInput::isIntegerConstraintLiteralConjunction () const inline
Returns
true, if this formula is a conjunction of literals of integer constraints; false, otherwise.
Definition at line 236 of file ModuleInput.h.
isOnlyPropositional()
bool smtrat::ModuleInput::isOnlyPropositional () const inline
Returns
true, if this formula is propositional; false, otherwise.
Definition at line 290 of file ModuleInput.h.
isRealConstraintConjunction()
bool smtrat::ModuleInput::isRealConstraintConjunction () const inline
Returns
true, if this formula is a conjunction of real constraints; false, otherwise.
Definition at line 209 of file ModuleInput.h.
isRealConstraintLiteralConjunction()
bool smtrat::ModuleInput::isRealConstraintLiteralConjunction () const inline
Returns
true, if this formula is a conjunction of literals of real constraints; false, otherwise.
Definition at line 218 of file ModuleInput.h.
properties()
carl::Condition smtrat::ModuleInput::properties () const inline
Returns
All known properties of the underlying formula of this module input.
Definition at line 175 of file ModuleInput.h.
Referenced by smtrat::Manager::getBackends(), and isOnlyPropositional().
realValuedVars()
void smtrat::ModuleInput::realValuedVars (carl::Variables & _realVars) const inline
Collects all real valued variables occurring in this formula.
Parameters
_realVars The container to collect the real valued variables in.
Definition at line 404 of file ModuleInput.h.
satisfiedBy() [1/2]
unsigned smtrat::ModuleInput::satisfiedBy (const Model & _assignment) const
Parameters
_assignment The model to check conjunction of the stored formulas against.
Returns
1, if the conjunction of the stored formulas is satisfied by the given model; 0, if the given model conflicts the conjunction of the stored formulas; 2, if it cannot be determined cheaply, whether the given model conflicts or satisfies the conjunction of the stored formulas.
Definition at line 33 of file ModuleInput.cpp.
Referenced by smtrat::isNRASatisfied().
satisfiedBy() [2/2]
unsigned smtrat::ModuleInput::satisfiedBy (const EvalRationalMap & _assignment) const
Parameters
_assignment The assignment to check conjunction of the stored formulas against.
Returns
1, if the conjunction of the stored formulas is satisfied by the given assignment; 0, if the given assignment conflicts the conjunction of the stored formulas; 2, if it cannot be determined cheaply, whether the given assignment conflicts or satisfies the conjunction of the stored formulas.
Definition at line 15 of file ModuleInput.cpp.
vars()
void smtrat::ModuleInput::vars (carl::Variables & _vars) const inline
Collects all variables occurring in this formula.
Parameters
_vars The container to collect the variables in.
Definition at line 393 of file ModuleInput.h.
Referenced by smtrat::createEstimatedAssignment().
The documentation for this class was generated from the following files:
smtrat-solver/ModuleInput.h
smtrat-solver/ModuleInput.cpp