SMT-RAT: smtrat::SortValue Class Reference
smtrat::SortValue Class Reference
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
#include <SortValue.h>
Public Types
typedef size_t IDType
The type if the unique id to identify a sort in the sort manager.
Public Member Functions
SortValue ()
SortValue (const SortValue &_sortValue)
Constructs a sort value by copying the given sort value.
const carl::Sort & sort () const
IDType id () const
bool operator== (const SortValue &_sortValue) const
bool operator< (const SortValue &_sortValue) const
Private Member Functions
SortValue (const carl::Sort &_sort, IDType _id)
Constructs a sort value.
Private Attributes
carl::Sort mSort
The sort defining the domain in which this value is.
IDType mId
A unique id to identify this sort in the sort value manager.
Friends
class SortValueManager
std::ostream & operator<< (std::ostream &_os, const SortValue &_sortValue)
Prints the given sort value on the given output stream.
Detailed Description
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
Definition at line 20 of file SortValue.h.
Member Typedef Documentation
typedef size_t smtrat::SortValue::IDType
The type if the unique id to identify a sort in the sort manager.
Definition at line 24 of file SortValue.h.
Constructor & Destructor Documentation
smtrat::SortValue::SortValue (const carl::Sort & _sort, IDType _id) inline explicit private
Constructs a sort value.
Parameters
_id The id of the sort value to construct.
Definition at line 40 of file SortValue.h.
smtrat::SortValue::SortValue () inline
Definition at line 47 of file SortValue.h.
smtrat::SortValue::SortValue (const SortValue & _sortValue) inline
Constructs a sort value by copying the given sort value.
Parameters
_sortValue The sort value to copy.
Definition at line 56 of file SortValue.h.
Member Function Documentation
IDType smtrat::SortValue::id () const inline
Returns
The id of this sort value.
Definition at line 72 of file SortValue.h.
Referenced by std::hash< smtrat::SortValue >::operator()(), operator<(), smtrat::operator<<(), operator==(), and smtrat::satisfies().
bool smtrat::SortValue::operator< (const SortValue & _sortValue) const
Parameters
_sortValue The sort value to compare with.
Returns
true, if this sort value is less than the given one.
Definition at line 21 of file SortValue.cpp.
bool smtrat::SortValue::operator== (const SortValue & _sortValue) const
Parameters
_sortValue The sort value to compare with.
Returns
true, if this sort value equals the given one.
Definition at line 15 of file SortValue.cpp.
const carl::Sort& smtrat::SortValue::sort () const inline
Returns
The sort of this value.
Definition at line 64 of file SortValue.h.
Referenced by std::hash< smtrat::SortValue >::operator()(), operator<(), smtrat::operator<<(), operator==(), and smtrat::satisfies().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & _os, const SortValue & _sortValue) friend
Prints the given sort value on the given output stream.
Parameters
_os The output stream to print on.
_sortValue The sort value to print.
Returns
The output stream after printing the given sort value on it.
Definition at line 27 of file SortValue.cpp.
friend class SortValueManager friend
Definition at line 26 of file SortValue.h.
Field Documentation
IDType smtrat::SortValue::mId private
A unique id to identify this sort in the sort value manager.
Definition at line 34 of file SortValue.h.
Referenced by id().
carl::Sort smtrat::SortValue::mSort private
The sort defining the domain in which this value is.
Definition at line 32 of file SortValue.h.
Referenced by sort().
The documentation for this class was generated from the following files:
lib/datastructures/SortValue.h
lib/datastructures/SortValue.cpp