SMT-RAT: smtrat::GBCalculationStats Class Reference
smtrat::GBCalculationStats Class Reference
#include <GBCalculationStatistics.h>
Public Member Functions
void collect ()
Override Statistics::collect.
void print (std::ostream &os=std::cout)
void exportKeyValue (std::ostream &os=std::cout)
void print (std::ostream &_out=std::cout, bool _smtlib=false, size_t _maxNameLength=0, size_t _maxKeyLength=0)
void generateXML (std::stringstream &filestream)
size_t maxKeyLength () const
const std::string & name () const
Static Public Member Functions
static GBCalculationStats * getInstance (unsigned key)
static void printAll (std::ostream &=std::cout)
Protected Member Functions
GBCalculationStats ()
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy>
void addKeyValuePair (const std::string &key, const T &value)
Protected Attributes
carl::BuchbergerStats * mBuchbergerStats
Static Private Attributes
static std::map< unsigned, GBCalculationStats * > instances
Detailed Description
Definition at line 23 of file GBCalculationStatistics.h.
Constructor & Destructor Documentation
smtrat::GBCalculationStats::GBCalculationStats () inline protected
Definition at line 38 of file GBCalculationStatistics.h.
Referenced by getInstance().
Member Function Documentation
template<typename T , carl::EnableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 97 of file Statistics.h.
Referenced by smtrat::Statistics::addKeyValuePair(), smtrat::CADStatistics::collect(), collect(), smtrat::GeneralStatistics::collect(), smtrat::SATModuleStatistics::collect(), smtrat::GroebnerModuleStats::collect(), smtrat::FouMoStatistics::collect(), smtrat::BVStatistics::collect(), smtrat::ReduceCNFStatistics::collect(), smtrat::IntEqStatistics::collect(), and smtrat::LRAModuleStatistics::collect().
template<typename T , carl::DisableIf< std::is_same< T, std::string >> = carl::dummy> void smtrat::Statistics::addKeyValuePair (const std::string & key, const T & value) inline protected inherited
Definition at line 104 of file Statistics.h.
void smtrat::GBCalculationStats::collect () virtual
Override Statistics::collect.
Reimplemented from smtrat::Statistics.
Definition at line 50 of file GBCalculationStatistics.cpp.
void smtrat::GBCalculationStats::exportKeyValue (std::ostream & os = std::cout)
void smtrat::Statistics::generateXML (std::stringstream & filestream) inline inherited
Definition at line 70 of file Statistics.h.
GBCalculationStats * smtrat::GBCalculationStats::getInstance (unsigned key) static
Definition at line 33 of file GBCalculationStatistics.cpp.
size_t smtrat::Statistics::maxKeyLength () const inline inherited
Definition at line 80 of file Statistics.h.
const std::string& smtrat::Statistics::name () const inline inherited
Definition at line 85 of file Statistics.h.
void smtrat::GBCalculationStats::print (std::ostream & os = std::cout)
Definition at line 46 of file GBCalculationStatistics.cpp.
void smtrat::Statistics::print (std::ostream & _out = std::cout, bool _smtlib = false, size_t _maxNameLength = 0, size_t _maxKeyLength = 0) inline inherited
Definition at line 36 of file Statistics.h.
void smtrat::GBCalculationStats::printAll (std::ostream & os = std::cout) static
Definition at line 40 of file GBCalculationStatistics.cpp.
Field Documentation
std::map< unsigned, GBCalculationStats * > smtrat::GBCalculationStats::instances static private
Definition at line 44 of file GBCalculationStatistics.h.
Referenced by getInstance(), and printAll().
carl::BuchbergerStats* smtrat::GBCalculationStats::mBuchbergerStats protected
Definition at line 41 of file GBCalculationStatistics.h.
Referenced by collect().
The documentation for this class was generated from the following files:
lib/modules/GBModule/GBCalculationStatistics.h
lib/modules/GBModule/GBCalculationStatistics.cpp