SMT-RAT: Condition Class Reference
Condition Class Reference
Public Member Functions
Condition ()
String addElement (String element)
String addElement (int index, String element)
String addElementAtTextPosition (int textPosition, String element)
int calculateIndexPosition (int textPosition)
int calculateTextPosition (int oldTextPosition, int currentTextPosition)
int getLength (int index)
String getValue (int index)
String getValueXML (int index)
boolean isEmpty ()
boolean isTrueCondition ()
void removeElement (int index)
int size ()
String toString ()
String toStringCPP ()
String toStringCPP (String condition)
Static Public Attributes
static final String TRUE_CONDITION
Private Attributes
final ArrayList
< AllowedConditionValue > values
Detailed Description
Definition at line 10 of file Condition.java.
Constructor & Destructor Documentation
Condition.Condition () inline
Definition at line 16 of file Condition.java.
Member Function Documentation
String Condition.addElement (String element) inline
Definition at line 21 of file Condition.java.
Referenced by addElementAtTextPosition(), and IOTools.createGraph().
String Condition.addElement (int index, String element) inline
Definition at line 26 of file Condition.java.
String Condition.addElementAtTextPosition (int textPosition, String element) inline
Definition at line 79 of file Condition.java.
int Condition.calculateIndexPosition (int textPosition) inline
Definition at line 91 of file Condition.java.
Referenced by addElementAtTextPosition().
int Condition.calculateTextPosition (int oldTextPosition, int currentTextPosition) inline
Definition at line 101 of file Condition.java.
int Condition.getLength (int index) inline
Definition at line 115 of file Condition.java.
Referenced by calculateIndexPosition(), and calculateTextPosition().
String Condition.getValue (int index) inline
Definition at line 120 of file Condition.java.
String Condition.getValueXML (int index) inline
Definition at line 125 of file Condition.java.
boolean Condition.isEmpty () inline
Definition at line 130 of file Condition.java.
boolean Condition.isTrueCondition () inline
Definition at line 135 of file Condition.java.
Referenced by IOTools.getGraphInformation(), and IOTools.getGraphString().
void Condition.removeElement (int index) inline
Definition at line 140 of file Condition.java.
int Condition.size () inline
Definition at line 145 of file Condition.java.
String Condition.toString () inline
Definition at line 151 of file Condition.java.
Referenced by EditStrategyGraphDialog.ClosingOkAction.actionPerformed().
String Condition.toStringCPP () inline
Definition at line 161 of file Condition.java.
Referenced by IOTools.getGraphInformation().
String Condition.toStringCPP (String condition) inline
Definition at line 171 of file Condition.java.
Field Documentation
final String Condition.TRUE_CONDITION static
Definition at line 12 of file Condition.java.
Referenced by EditStrategyGraphDialog.AddPropositionAction.actionPerformed(), EditStrategyGraphDialog.EditStrategyGraphDialog(), EditStrategyGraphDialog.ConditionFocusListener.focusGained(), EditStrategyGraphDialog.ConditionFocusListener.focusLost(), and isTrueCondition().
final ArrayList<AllowedConditionValue> Condition.values private
Definition at line 14 of file Condition.java.
Referenced by addElement(), addElementAtTextPosition(), Condition(), isTrueCondition(), toString(), and toStringCPP().
The documentation for this class was generated from the following file:
gui/Condition.java