SMT-RAT: SshChannel Class Reference
SshChannel Class Reference
#include <SshChannel.h>
Public Member Functions
SshChannel (int socket)
void openChannel (LIBSSH2_SESSION *session)
void setBlocking (bool blocking)
bool executeCommand (const std::string &command)
bool readResponse ()
int closeChannel ()
Private Attributes
LIBSSH2_CHANNEL * mChannel
std::stringstream response_stream
int mSocket
LIBSSH2_SESSION * mSession
int mId
Static Private Attributes
static int IdCounter
Detailed Description
Definition at line 19 of file SshChannel.h.
Constructor & Destructor Documentation
SshChannel::SshChannel (int socket) inline
Definition at line 30 of file SshChannel.h.
Member Function Documentation
int SshChannel::closeChannel () inline
Returns
exit code
Definition at line 151 of file SshChannel.h.
Referenced by SshConnection::cancel(), SshConnection::remoteCall(), and SshConnection::restartActiveCalls().
bool SshChannel::executeCommand (const std::string & command) inline
Parameters
command
Returns
true if the command is executing on the channel.
Definition at line 73 of file SshChannel.h.
Referenced by SshConnection::cancel(), SshConnection::remoteCall(), and SshConnection::restartActiveCalls().
void SshChannel::openChannel (LIBSSH2_SESSION * session) inline
Parameters
session
Definition at line 40 of file SshChannel.h.
Referenced by SshConnection::cancel(), SshConnection::remoteCall(), and SshConnection::restartActiveCalls().
bool SshChannel::readResponse () inline
Returns
Definition at line 95 of file SshChannel.h.
void SshChannel::setBlocking (bool blocking) inline
Parameters
blocking
Definition at line 63 of file SshChannel.h.
Referenced by SshConnection::cancel(), SshConnection::remoteCall(), and SshConnection::restartActiveCalls().
Field Documentation
int SshChannel::IdCounter static private
Definition at line 26 of file SshChannel.h.
LIBSSH2_CHANNEL* SshChannel::mChannel private
Definition at line 21 of file SshChannel.h.
Referenced by closeChannel(), executeCommand(), openChannel(), readResponse(), and setBlocking().
int SshChannel::mId private
Definition at line 25 of file SshChannel.h.
LIBSSH2_SESSION* SshChannel::mSession private
Definition at line 24 of file SshChannel.h.
Referenced by closeChannel(), executeCommand(), and openChannel().
int SshChannel::mSocket private
Definition at line 23 of file SshChannel.h.
Referenced by closeChannel(), executeCommand(), and openChannel().
std::stringstream SshChannel::response_stream private
Definition at line 22 of file SshChannel.h.
Referenced by closeChannel(), and readResponse().
The documentation for this class was generated from the following files:
benchmax/ssh/SshChannel.h
benchmax/ssh/SshChannel.cpp