SMT-RAT: delta::Producer Class Reference
delta::Producer Class Reference
This class iteratively applies the operators to a smtlib file until no further simplifications can be performed.
#include <Producer.h>
Public Member Functions
Producer (const Checker &checker, const Settings &settings)
Create a new manager that uses the given checker.
void interrupt () const
std::size_t operator() (Node &root)
Apply simplifications to the given node.
Private Member Functions
void dfs (const Node &root, const Node *n, std::size_t &num, std::size_t skip)
Iterate over nodes using DFS.
void bfs (const Node &root, std::size_t &num, std::size_t skip)
Iterate over nodes using BFS.
void process (const Node &root, const Node &n, std::size_t num)
Performs the actual simplifications.
Private Attributes
std::vector< std::tuple< NodeOperator, std::string, std::string, std::string > > operators
Registered operators.
Consumer consumer
ProgressBar progress
Progress.
Settings settings
Settings.
bool verbose
Verbose flag.
bool delayDeclareFun
bool interrupted
Interrupt flat.
Detailed Description
This class iteratively applies the operators to a smtlib file until no further simplifications can be performed.
Definition at line 24 of file Producer.h.
Constructor & Destructor Documentation
Producer()
delta::Producer::Producer (const Checker & checker, const Settings & settings) inline
Create a new manager that uses the given checker.
Parameters
checker Checker to call the solver.
settings Settings object.
Definition at line 44 of file Producer.h.
Member Function Documentation
bfs()
void delta::Producer::bfs (const Node & root, std::size_t & num, std::size_t skip) inline private
Iterate over nodes using BFS.
Parameters
root Root of nodes.
num Internal counter of node.
skip Number of nodes to skip.
Definition at line 132 of file Producer.h.
Referenced by operator()().
dfs()
void delta::Producer::dfs (const Node & root, const Node * n, std::size_t & num, std::size_t skip) inline private
Iterate over nodes using DFS.
Parameters
root Root of nodes.
n Current node.
num Internal counter of node.
skip Number of nodes to skip.
Definition at line 116 of file Producer.h.
Referenced by operator()().
operator()()
std::size_t delta::Producer::operator() (Node & root) inline
Apply simplifications to the given node.
Parameters
n Node to simplify.
Definition at line 67 of file Producer.h.
process()
void delta::Producer::process (const Node & root, const Node & n, std::size_t num) inline private
Performs the actual simplifications.
Parameters
root Root of the current smtlib file.
n Node that is currently processed.
progress Current progress.
Definition at line 157 of file Producer.h.
Referenced by bfs(), and dfs().
The documentation for this class was generated from the following file:
delta/Producer.h