SMT-RAT: smtrat::NRATSolver Class Reference
smtrat::NRATSolver Class Reference
Strategy description.
#include <NRATSolver.h>
Public Member Functions
NRATSolver ()
~NRATSolver ()
bool inform (const FormulaT &_constraint)
Informs the solver about a constraint.
bool add (const FormulaT &_subformula)
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Answer check ()
Checks the so far added formulas for satisfiability.
void push ()
Pushes a backtrack point to the stack of backtrack points.
bool pop ()
Pops a backtrack point from the stack of backtrack points.
const std::vector< FormulasT > & infeasibleSubsets () const
std::list< std::vector
< carl::Variable > > getModelEqualities () const
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
const Model model () const
std::vector< FormulaT > lemmas () const
Returns the lemmas/tautologies which were made during the last solving provoked by check().
const ModuleInput & formula () const
void printAssignment (std::ostream &_out) const
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
void printAssertions (std::ostream &=std::cout) const
Prints the so far added formulas.
void printInfeasibleSubset (std::ostream &=std::cout) const
Prints the first found infeasible subset of the set of received formulas.
void addModuleType (const ModuleType _moduleType, ModuleFactory *_factory)
Adds a module type to this manager, for which modules can be instantiated in order to be part of the solving procedure.
const std::vector< Module * > & getAllGeneratedModules () const
const std::map< const
ModuleType, ModuleFactory * > & rModuleFactories () const
std::ostream & rDebugOutputChannel ()
const QuantifierManager & quantifierManager () const
QuantifierManager & quantifierManager ()
const carl::QuantifiedVariables & quantifiedVariables () const
carl::QuantifiedVariables & quantifiedVariables ()
const Logic & logic () const
Logic & rLogic ()
std::string logicToString () const
Protected Member Functions
ModuleInput::iterator remove (ModuleInput::iterator _subformula)
Removes the formula at the given position in the conjunction of formulas, which will be considered for the next satisfiability check.
StrategyGraph & rStrategyGraph ()
std::vector< Module * > getAllBackends (Module *_module) const
Gets all backends so far instantiated according the strategy and all previous enquiries of the given module.
size_t addBackendIntoStrategyGraph (size_t _at, ModuleType _moduleType, ConditionEvaluation _conditionEvaluation=isCondition)
Adds the module type of a backend for the module of the type given by the given position in the manager's strategy graph.
void addBacklinkIntoStrategyGraph (size_t _from, size_t _to, ConditionEvaluation _conditionEvaluation=isCondition)
Extends the strategy graph of this manager such that if a module corresponding to the first given position in the strategy graph asks for backends for a formula whose properties satisfy the conditions checked by the given function pointer, the this manager instantiates (if not yet instantiated) a backend corresponding to the second given position in the strategy graph.
std::vector< Module * > getBackends (Module *, std::atomic_bool *)
Get the backends to call for the given problem instance required by the given module.
Detailed Description
Strategy description.
Author:
Since:
Version:
Definition at line 18 of file NRATSolver.h.
Constructor & Destructor Documentation
smtrat::NRATSolver::NRATSolver ()
Definition at line 11 of file NRATSolver.cpp.
smtrat::NRATSolver::~NRATSolver ()
Definition at line 45 of file NRATSolver.cpp.
Member Function Documentation
bool smtrat::Manager::add (const FormulaT & _subformula) [inline, inherited]
Adds the given formula to the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters:
_subformula The formula to add.
Returns:
false, if it is easy to decide whether adding this formula creates a conflict; true, otherwise.
Definition at line 117 of file Manager.h.
size_t smtrat::Manager::addBackendIntoStrategyGraph (size_t _at, ModuleType _moduleType, ConditionEvaluation _conditionEvaluation = isCondition) [inline, protected, inherited]
Adds the module type of a backend for the module of the type given by the given position in the manager's strategy graph.
Backends of the given type will be instantiated if a module corresponding to the given position in the strategy graph asks for backends with a formula fulfilling the given conditions.
Parameters:
_at The position in the strategy graph to add a backend's module type.
_moduleType The module type of the backend to instantiate for modules corresponding to the given position in the managers strategy graph.
_conditionEvaluation A function which evaluates whether the properties of a given formula fulfill certain conditions.
Returns:
The position in this managers strategy graph corresponding to the added module type.
Definition at line 415 of file Manager.h.
Referenced by NRATSolver(), smtrat::NRATSolverCAD::NRATSolverCAD(), smtrat::StrategyOne::StrategyOne(), smtrat::strategyTwo::strategyTwo(), and smtrat::Verit_Backend::Verit_Backend().
void smtrat::Manager::addBacklinkIntoStrategyGraph (size_t _from, size_t _to, ConditionEvaluation _conditionEvaluation = isCondition) [inline, protected, inherited]
Extends the strategy graph of this manager such that if a module corresponding to the first given position in the strategy graph asks for backends for a formula whose properties satisfy the conditions checked by the given function pointer, the this manager instantiates (if not yet instantiated) a backend corresponding to the second given position in the strategy graph.
Parameters:
_from The position in the strategy graph to which the enquiring module corresponds to.
_to The position in the strategy graph to which the instantiated backend for this enquiry corresponds to.
_conditionEvaluation A function which evaluates whether the properties of a given formula fulfill certain conditions.
Definition at line 429 of file Manager.h.
void smtrat::Manager::addModuleType (const ModuleType _moduleType, ModuleFactory * _factory) [inline, inherited]
Adds a module type to this manager, for which modules can be instantiated in order to be part of the solving procedure.
Parameters:
_moduleType The module type to add to the module types for which modules can be instantiated in order to be part of the solving procedure.
_factory The factory to instantiate modules of this type.
Definition at line 272 of file Manager.h.
Referenced by smtrat::addModules().
Answer smtrat::Manager::check () [inline, inherited]
Checks the so far added formulas for satisfiability.
Returns:
True, if the conjunction of the so far added formulas is satisfiable; False, if it not satisfiable; Unknown, if this solver cannot decide whether it is satisfiable or not.
Definition at line 142 of file Manager.h.
const ModuleInput& smtrat::Manager::formula () const [inline, inherited]
Returns:
The conjunction of so far added formulas.
Definition at line 236 of file Manager.h.
std::vector<Module*> smtrat::Manager::getAllBackends (Module * _module) const [inline, protected, inherited]
Gets all backends so far instantiated according the strategy and all previous enquiries of the given module.
Parameters:
_module The module to get all backends so far instantiated according the strategy and all previous enquiries of this module.
Returns:
All backends so far instantiated according the strategy and all previous enquiries of the given module.
Definition at line 394 of file Manager.h.
Referenced by smtrat::Module::eraseSubformulaFromPassedFormula(), smtrat::Module::init(), and smtrat::Module::runBackends().
const std::vector<Module*>& smtrat::Manager::getAllGeneratedModules () const [inline, inherited]
Returns:
All instantiated modules of the solver belonging to this manager.
Definition at line 280 of file Manager.h.
Referenced by printTimings().
vector< Module * > smtrat::Manager::getBackends (Module * , std::atomic_bool *) [protected, inherited]
Get the backends to call for the given problem instance required by the given module.
Parameters:
_formula The problem instance.
_requiredBy The module asking for a backend.
_foundAnswer A conditional
Returns:
A vector of modules, which the module defined by _requiredBy calls in parallel to achieve an answer to the given instance.
Definition at line 149 of file Manager.cpp.
Referenced by smtrat::Module::init(), and smtrat::Module::runBackends().
std::list<std::vector<carl::Variable> > smtrat::Manager::getModelEqualities () const [inline, inherited]
Determines variables assigned by the currently found satisfying assignment to an equal value in their domain.
Returns:
A list of vectors of variables, stating that the variables in one vector are assigned to equal values.
Definition at line 197 of file Manager.h.
const std::vector<FormulasT>& smtrat::Manager::infeasibleSubsets () const [inline, inherited]
Returns:
All infeasible subsets of the set so far added formulas.
Note, that the conjunction of the so far added formulas must be inconsistent to receive an infeasible subset.
Definition at line 188 of file Manager.h.
bool smtrat::Manager::inform (const FormulaT & _constraint) [inline, inherited]
Informs the solver about a constraint.
Optimally, it should be informed about all constraints, which it will receive eventually, before any of them is added as part of a formula with the interface add(..).
Parameters:
_constraint The constraint to inform about.
Returns:
false, if it is easy to decide (for any module used of this solver), whether the constraint itself is inconsistent; true, otherwise.
Definition at line 105 of file Manager.h.
std::vector<FormulaT> smtrat::Manager::lemmas () const [inline, inherited]
Returns the lemmas/tautologies which were made during the last solving provoked by check().
These lemmas can be used in the same manner as infeasible subsets are used.
Returns:
The lemmas/tautologies made during solving.
Definition at line 223 of file Manager.h.
const Logic& smtrat::Manager::logic () const [inline, inherited]
Returns:
A constant reference to the logic this solver considers.
Definition at line 332 of file Manager.h.
std::string smtrat::Manager::logicToString () const [inline, inherited]
Returns:
The string naming the logic this solver considers.
Definition at line 348 of file Manager.h.
Referenced by smtrat::Module::checkInfSubsetForMinimality().
const Model smtrat::Manager::model () const [inline, inherited]
Returns:
An assignment of the variables, which occur in the so far added formulas, to values of their domains, such that it satisfies the conjunction of these formulas.
Note, that an assignment is only provided if the conjunction of so far added formulas is satisfiable. Furthermore, when solving non-linear real arithmetic formulas the assignment could contain other variables or freshly introduced variables.
Definition at line 212 of file Manager.h.
bool smtrat::Manager::pop (void) [inline, inherited]
Pops a backtrack point from the stack of backtrack points.
This provokes, that all formulas which have been added after that backtrack point are removed.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 172 of file Manager.h.
void smtrat::Manager::printAssertions (std::ostream & _out = std::cout) const [inherited]
Prints the so far added formulas.
Parameters:
_out The stream to print on.
Definition at line 111 of file Manager.cpp.
void smtrat::Manager::printAssignment (std::ostream & _out) const [inline, inherited]
Prints the currently found assignment of variables occurring in the so far added formulas to values of their domains, if the conjunction of these formulas is satisfiable.
Parameters:
The stream to print on.
Definition at line 247 of file Manager.h.
void smtrat::Manager::printInfeasibleSubset (std::ostream & _out = std::cout) const [inherited]
Prints the first found infeasible subset of the set of received formulas.
Parameters:
_out The stream to print on.
Definition at line 128 of file Manager.cpp.
void smtrat::Manager::push (void) [inline, inherited]
Pushes a backtrack point to the stack of backtrack points.
Note, that this interface has not necessarily be used to apply a solver constructed with SMT-RAT, but is often required by state-of-the-art SMT solvers when embedding a theory solver constructed with SMT-RAT into them.
Definition at line 159 of file Manager.h.
const carl::QuantifiedVariables& smtrat::Manager::quantifiedVariables () const [inline, inherited]
Returns:
A constant reference to the variables, which are bound by a quantifier.
Definition at line 318 of file Manager.h.
carl::QuantifiedVariables& smtrat::Manager::quantifiedVariables () [inline, inherited]
Returns:
A reference to the variables, which are bound by a quantifier.
Definition at line 325 of file Manager.h.
const QuantifierManager& smtrat::Manager::quantifierManager () const [inline, inherited]
Returns:
A constant reference to the managing unit for the quantifiers occurring in the formulas to solve.
Definition at line 304 of file Manager.h.
QuantifierManager& smtrat::Manager::quantifierManager () [inline, inherited]
Returns:
A reference to the managing unit for the quantifiers occurring in the formulas to solve.
Definition at line 311 of file Manager.h.
std::ostream& smtrat::Manager::rDebugOutputChannel () [inline, inherited]
Returns:
The stream to print the debug information on.
Definition at line 296 of file Manager.h.
ModuleInput::iterator smtrat::Manager::remove (ModuleInput::iterator _subformula) [inline, protected, inherited]
Removes the formula at the given position in the conjunction of formulas, which will be considered for the next satisfiability check.
Parameters:
_subformula The position of the formula to remove.
Returns:
An iterator to the formula after the position of the just removed formula. If the removed formula has been the last element, the end of the conjunction of formulas, which will be considered for the next satisfiability check is returned.
Definition at line 374 of file Manager.h.
Logic& smtrat::Manager::rLogic () [inline, inherited]
Returns:
A reference to the logic this solver considers.
Definition at line 340 of file Manager.h.
const std::map<const ModuleType, ModuleFactory*>& smtrat::Manager::rModuleFactories () const [inline, inherited]
Returns:
A constant reference to the mapping of module types to the factories to instantiate the modules of this type.
Definition at line 288 of file Manager.h.
StrategyGraph& smtrat::Manager::rStrategyGraph () [inline, protected, inherited]
Returns:
A reference to the graph representing the solving strategy.
Definition at line 384 of file Manager.h.
The documentation for this class was generated from the following files:
lib/strategies/NRATSolver.h
lib/strategies/NRATSolver.cpp