SMT-RAT: smtrat::icp Namespace Reference
smtrat::icp Namespace Reference
Data Structures
class ContractionCandidate
struct contractionCandidateComp
class ContractionCandidateManager
class HistoryNode
class IcpVariable
struct icpVariableComp
Typedefs
typedef LRAModule
< LRASettings1 >::LRAVariable LRAVariable
typedef std::set< const
IcpVariable *, icpVariableComp > set_icpVariable
Enumerations
enum Updated { Updated::LEFT, Updated::RIGHT, Updated::BOTH, Updated::NONE }
Functions
std::vector< Poly > getNonlinearMonomials (const Poly &_expr)
Obtains the non-linear monomials of the given polynomial.
std::pair< ConstraintT,
ConstraintT > intervalToConstraint (const Poly &_lhs, const smtrat::DoubleInterval _interval)
Creates a new constraint from an existing interval.
bool intervalBoxContainsEmptyInterval (const EvalDoubleIntervalMap &_intervals)
Checks mIntervals if it contains an empty interval.
const LRAModule< LRASettings1 >
::LRAVariable * getOriginalLraVar (carl::Variable::Arg _var, const LRAModule< LRASettings1 > &_lra)
Typedef Documentation
typedef LRAModule<LRASettings1>::LRAVariable smtrat::icp::LRAVariable
Definition at line 33 of file IcpVariable.h.
typedef std::set<const IcpVariable*, icpVariableComp> smtrat::icp::set_icpVariable
Definition at line 336 of file IcpVariable.h.
Enumeration Type Documentation
enum smtrat::icp::Updated strong
Enumerator
LEFT
RIGHT
BOTH
NONE
Definition at line 22 of file IcpVariable.h.
Function Documentation
std::vector< Poly > smtrat::icp::getNonlinearMonomials (const Poly & _expr)
Obtains the non-linear monomials of the given polynomial.
Parameters
_expr The polynomial to obtain the non-linear monomials for.
Returns
The non-linear monomials.
Definition at line 16 of file utils.cpp.
Referenced by smtrat::ICPModule< Settings >::addConstraint().
const LRAModule< LRASettings1 >::LRAVariable * smtrat::icp::getOriginalLraVar (carl::Variable::Arg _var, const LRAModule< LRASettings1 > & _lra)
Definition at line 86 of file utils.cpp.
bool smtrat::icp::intervalBoxContainsEmptyInterval (const EvalDoubleIntervalMap & _intervals)
Checks mIntervals if it contains an empty interval.
Returns
Definition at line 76 of file utils.cpp.
std::pair< ConstraintT, ConstraintT > smtrat::icp::intervalToConstraint (const Poly & _lhs, const smtrat::DoubleInterval _interval)
Creates a new constraint from an existing interval.
Parameters
_interval
Returns
pair <lowerBoundConstraint*, upperBoundConstraint*>
Definition at line 36 of file utils.cpp.
Referenced by smtrat::ICPModule< Settings >::createBoxFormula(), and smtrat::ICPModule< Settings >::createConstraintsFromBounds().