SMT-RAT: vs Namespace Reference
vs Namespace Reference
Class to create a condition object.
Data Structures
class Condition
class State
class Substitution
struct substitutionPointerEqual
struct substitutionPointerHash
struct unsignedTripleCmp
Typedefs
typedef std::set< carl::PointerSet< Condition > > ConditionSetSet
typedef std::set< ConditionSetSet > ConditionSetSetSet
typedef std::list< const Condition *> ConditionList
typedef std::vector< ConditionList > DisjunctionOfConditionConjunctions
typedef std::pair< size_t, std::pair< size_t, size_t > > UnsignedTriple
typedef std::pair< UnsignedTriple, vs::State * > ValStatePair
typedef std::map< UnsignedTriple, vs::State *, unsignedTripleCmp > ValuationMap
typedef std::vector< smtrat::ConstraintT > ConstraintVector
a vector of constraints
typedef std::vector< ConstraintVector > DisjunctionOfConstraintConjunctions
a vector of vectors of constraints
template<typename T >
using SubstitutionFastPointerMap = std::unordered_map< const smtrat::Poly *, T, substitutionPointerHash, substitutionPointerEqual >
Functions
std::ostream & operator<< (std::ostream &_out, const Condition &_condition)
void simplify (DisjunctionOfConstraintConjunctions &)
Simplifies a disjunction of conjunctions of constraints by deleting consistent constraint and inconsistent conjunctions of constraints.
void simplify (DisjunctionOfConstraintConjunctions &_toSimplify, Variables &_conflictingVars, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
bool splitProducts (DisjunctionOfConstraintConjunctions &, bool=false)
Splits all constraints in the given disjunction of conjunctions of constraints having a non-trivial factorization into a set of constraints which compare the factors instead.
bool splitProducts (const ConstraintVector &, DisjunctionOfConstraintConjunctions &, bool=false)
Splits all constraints in the given conjunction of constraints having a non-trivial factorization into a set of constraints which compare the factors instead.
DisjunctionOfConstraintConjunctions splitProducts (const smtrat::ConstraintT &, bool=false)
Splits the given constraint into a set of constraints which compare the factors of the factorization of the constraints considered polynomial.
void splitSosDecompositions (DisjunctionOfConstraintConjunctions &_toSimplify)
DisjunctionOfConstraintConjunctions getSignCombinations (const smtrat::ConstraintT &)
For a given constraint f_1*...*f_n ~ 0 this method computes all combinations of constraints f_1 ~_1 0 ...
void getOddBitStrings (std::size_t _length, std::vector< std::bitset< MAX_PRODUCT_SPLIT_NUMBER > > &_strings)
void getEvenBitStrings (std::size_t _length, std::vector< std::bitset< MAX_PRODUCT_SPLIT_NUMBER > > &_strings)
void print (DisjunctionOfConstraintConjunctions &_substitutionResults)
Prints the given disjunction of conjunction of constraints.
bool substitute (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper, Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
bool substituteNormal (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper, Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
bool substituteNormalSqrtEq (const smtrat::Poly &_radicand, const smtrat::Poly &_q, const smtrat::Poly &_r, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
bool substituteNormalSqrtNeq (const smtrat::Poly &_radicand, const smtrat::Poly &_q, const smtrat::Poly &_r, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
bool substituteNormalSqrtLess (const smtrat::Poly &_radicand, const smtrat::Poly &_q, const smtrat::Poly &_r, const smtrat::Poly &_s, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
bool substituteNormalSqrtLeq (const smtrat::Poly &_radicand, const smtrat::Poly &_q, const smtrat::Poly &_r, const smtrat::Poly &_s, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
bool substitutePlusEps (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper, Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
bool substituteEpsGradients (const smtrat::ConstraintT &_cons, const Substitution &_subs, const Relation _relation, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper, Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
void substituteInf (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
void substituteInfLessGreater (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result)
Applies the given substitution to the given constraint, where the substitution is of the form [x -> +/-infinity] with x as the variable and c and b polynomials in the real theory excluding x.
void substituteTrivialCase (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result)
Deals with the case, that the left hand side of the constraint to substitute is a trivial polynomial in the variable to substitute.
void substituteNotTrivialCase (const smtrat::ConstraintT &, const Substitution &, DisjunctionOfConstraintConjunctions &)
Deals with the case, that the left hand side of the constraint to substitute is not a trivial polynomial in the variable to substitute.
template<class combineType >
bool combine (const std::vector< std::vector< std::vector< combineType > > > &_toCombine, std::vector< std::vector< combineType > > &_combination)
Combines vectors.
void simplify (DisjunctionOfConstraintConjunctions &, carl::Variables &, const smtrat::EvalDoubleIntervalMap &)
Simplifies a disjunction of conjunctions of constraints by deleting consistent constraint and inconsistent conjunctions of constraints.
void getOddBitStrings (size_t _length, std::vector< std::bitset< MAX_PRODUCT_SPLIT_NUMBER > > &_strings)
void getEvenBitStrings (size_t _length, std::vector< std::bitset< MAX_PRODUCT_SPLIT_NUMBER > > &_strings)
bool substitute (const smtrat::ConstraintT &, const Substitution &, DisjunctionOfConstraintConjunctions &, bool _accordingPaper, carl::Variables &, const smtrat::EvalDoubleIntervalMap &)
Applies a substitution to a constraint and stores the results in the given vector.
bool substituteNormal (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper, carl::Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
Applies a substitution of a variable to a term, which is not minus infinity nor a to an square root expression plus an infinitesimal.
bool substitutePlusEps (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, bool _accordingPaper, carl::Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
Applies the given substitution to the given constraint, where the substitution is of the form [x -> t+epsilon] with x as the variable and c and b polynomials in the real theory excluding x.
bool substituteEpsGradients (const smtrat::ConstraintT &_cons, const Substitution &_subs, const carl::Relation _relation, DisjunctionOfConstraintConjunctions &, bool _accordingPaper, carl::Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
Sub-method of substituteEps, where one of the gradients in the point represented by the substitution must be negative if the given relation is less or positive if the given relation is greater.
void substituteInf (const smtrat::ConstraintT &_cons, const Substitution &_subs, DisjunctionOfConstraintConjunctions &_result, carl::Variables &_conflictingVariables, const smtrat::EvalDoubleIntervalMap &_solutionSpace)
Applies the given substitution to the given constraint, where the substitution is of the form [x -> -infinity] with x as the variable and c and b polynomials in the real theory excluding x.
ostream & operator<< (std::ostream &os, const Substitution &s)
Prints the given substitution on the given output stream.
Detailed Description
Class to create a condition object.
Class to create a substitution object.
Class to create a state object.
Author
Florian Corzilius
Since
2010-07-26
Version
2011-12-05
Author
Florian Corzilius
Since
2010-05-11
Version
2013-10-24
Author
Florian Corzilius
Since
2010-05-11
Version
2013-10-23
Function Documentation
combine()
template<class combineType > bool vs::combine (const std::vector< std::vector< std::vector< combineType > > > & _toCombine, std::vector< std::vector< combineType > > & _combination)
Combines vectors.
Parameters
_toCombine The vectors to combine.
_combination The resulting combination.
Returns
false, if the upper limit in the number of combinations resulting by this method is exceeded. Note, that this hinders a combinatorial blow up. true, otherwise.
Definition at line 43 of file Substitute.h.
Referenced by splitProducts().
getEvenBitStrings()
void vs::getEvenBitStrings (size_t _length, std::vector< std::bitset< MAX_PRODUCT_SPLIT_NUMBER > > & _strings)
Parameters
_length The maximal length of the bit strings with even parity to compute.
_strings All bit strings of length less or equal the given length with even parity.
getOddBitStrings()
void vs::getOddBitStrings (size_t _length, std::vector< std::bitset< MAX_PRODUCT_SPLIT_NUMBER > > & _strings)
Parameters
_length The maximal length of the bit strings with odd parity to compute.
_strings All bit strings of length less or equal the given length with odd parity.
getSignCombinations()
DisjunctionOfConstraintConjunctions vs::getSignCombinations (const smtrat::ConstraintT &)
For a given constraint f_1*...*f_n ~ 0 this method computes all combinations of constraints f_1 ~_1 0 ...
f_n ~_n 0 such that
    f_1 ~_1 0 and ... and f_n ~_n 0   iff   f_1*...*f_n ~ 0
holds.
Parameters
_constraint A pointer to the constraint to split this way.
Returns
The resulting combinations.
Definition at line 383 of file Substitute.cpp.
Referenced by getSignCombinations(), and splitProducts().
operator<<()
std::ostream & vs::operator<< (std::ostream & os, const Substitution & s)
Prints the given substitution on the given output stream.
Parameters
_out The output stream, on which to write.
_substitution The substitution to print.
Returns
The output stream after printing the substitution on it.
Definition at line 165 of file Substitution.cpp.
print()
void vs::print (DisjunctionOfConstraintConjunctions & _substitutionResults)
Prints the given disjunction of conjunction of constraints.
Parameters
_substitutionResults The disjunction of conjunction of constraints to print.
Definition at line 516 of file Substitute.cpp.
Referenced by print().
simplify() [1/2]
void vs::simplify (DisjunctionOfConstraintConjunctions &)
Simplifies a disjunction of conjunctions of constraints by deleting consistent constraint and inconsistent conjunctions of constraints.
If a conjunction of only consistent constraints exists, the simplified disjunction contains one empty conjunction.
Parameters
_toSimplify The disjunction of conjunctions to simplify.
Definition at line 21 of file Substitute.cpp.
Referenced by simplify(), and splitProducts().
simplify() [2/2]
void vs::simplify (DisjunctionOfConstraintConjunctions & , carl::Variables & , const smtrat::EvalDoubleIntervalMap &)
Simplifies a disjunction of conjunctions of constraints by deleting consistent constraint and inconsistent conjunctions of constraints.
If a conjunction of only consistent constraints exists, the simplified disjunction contains one empty conjunction.
Parameters
_toSimplify The disjunction of conjunctions to simplify.
_conflictingVars
_solutionSpace
splitProducts() [1/3]
bool vs::splitProducts (DisjunctionOfConstraintConjunctions & , bool = false)
Splits all constraints in the given disjunction of conjunctions of constraints having a non-trivial factorization into a set of constraints which compare the factors instead.
Parameters
_toSimplify The disjunction of conjunctions of the constraints to split.
_onlyNeq A flag indicating that only constraints with the relation symbol != are split.
Returns
false, if the upper limit in the number of combinations resulting by this method is exceeded. Note, that this hinders a combinatorial blow up. true, otherwise.
Definition at line 109 of file Substitute.cpp.
Referenced by splitProducts().
splitProducts() [2/3]
bool vs::splitProducts (const ConstraintVector & , DisjunctionOfConstraintConjunctions & , bool = false)
Splits all constraints in the given conjunction of constraints having a non-trivial factorization into a set of constraints which compare the factors instead.
Parameters
_toSimplify The conjunction of the constraints to split.
_result The result, being a disjunction of conjunctions of constraints.
_onlyNeq A flag indicating that only constraints with the relation symbol != are split.
Returns
false, if the upper limit in the number of combinations resulting by this method is exceeded. Note, that this hinders a combinatorial blow up. true, otherwise.
Definition at line 130 of file Substitute.cpp.
splitProducts() [3/3]
DisjunctionOfConstraintConjunctions vs::splitProducts (const smtrat::ConstraintT & , bool = false)
Splits the given constraint into a set of constraints which compare the factors of the factorization of the constraints considered polynomial.
Parameters
_constraint A pointer to the constraint to split.
_onlyNeq A flag indicating that only constraints with the relation symbol != are split.
Returns
The resulting disjunction of conjunctions of constraints, which is semantically equivalent to the given constraint.
Definition at line 200 of file Substitute.cpp.
substitute()
bool vs::substitute (const smtrat::ConstraintT & , const Substitution & , DisjunctionOfConstraintConjunctions & , bool _accordingPaper, carl::Variables & , const smtrat::EvalDoubleIntervalMap &)
Applies a substitution to a constraint and stores the results in the given vector.
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution.
Returns
false, if the upper limit in the number of combinations in the result of the substitution is exceeded. Note, that this hinders a combinatorial blow up. true, otherwise.
substituteEpsGradients()
bool vs::substituteEpsGradients (const smtrat::ConstraintT & _cons, const Substitution & _subs, const carl::Relation _relation, DisjunctionOfConstraintConjunctions & , bool _accordingPaper, carl::Variables & _conflictingVariables, const smtrat::EvalDoubleIntervalMap & _solutionSpace)
Sub-method of substituteEps, where one of the gradients in the point represented by the substitution must be negative if the given relation is less or positive if the given relation is greater.
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_relation The relation symbol, deciding whether the substitution result must be negative or positive.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
_conflictingVariables If a conflict with the given solution space occurs, the variables being part of this conflict are stored in this container.
_solutionSpace The solution space in form of double intervals of the variables occurring in the given constraint.
substituteInf()
void vs::substituteInf (const smtrat::ConstraintT & _cons, const Substitution & _subs, DisjunctionOfConstraintConjunctions & _result, carl::Variables & _conflictingVariables, const smtrat::EvalDoubleIntervalMap & _solutionSpace)
Applies the given substitution to the given constraint, where the substitution is of the form [x -> -infinity] with x as the variable and c and b polynomials in the real theory excluding x.
The constraint is of the form "f(x) \rho 0" with element of {=,!=,<,>,<=,>=} and k as the maximum degree of x in f.
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_conflictingVariables If a conflict with the given solution space occurs, the variables being part of this conflict are stored in this container.
_solutionSpace The solution space in form of double intervals of the variables occurring in the given constraint.
substituteInfLessGreater()
void vs::substituteInfLessGreater (const smtrat::ConstraintT & _cons, const Substitution & _subs, DisjunctionOfConstraintConjunctions & _result)
Applies the given substitution to the given constraint, where the substitution is of the form [x -> +/-infinity] with x as the variable and c and b polynomials in the real theory excluding x.
The constraint is of the form "a*x^2+bx+c \rho 0", where is less or greater.
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
Definition at line 1053 of file Substitute.cpp.
Referenced by substituteInfLessGreater().
substituteNormal()
bool vs::substituteNormal (const smtrat::ConstraintT & _cons, const Substitution & _subs, DisjunctionOfConstraintConjunctions & _result, bool _accordingPaper, carl::Variables & _conflictingVariables, const smtrat::EvalDoubleIntervalMap & _solutionSpace)
Applies a substitution of a variable to a term, which is not minus infinity nor a to an square root expression plus an infinitesimal.
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
_conflictingVariables If a conflict with the given solution space occurs, the variables being part of this conflict are stored in this container.
_solutionSpace The solution space in form of double intervals of the variables occurring in the given constraint.
substituteNormalSqrtEq()
bool vs::substituteNormalSqrtEq (const smtrat::Poly & _radicand, const smtrat::Poly & _q, const smtrat::Poly & _r, DisjunctionOfConstraintConjunctions & _result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
The relation symbol of the constraint to substitute is "=".
                        (_q+_r*sqrt(_radicand))
The term then looks like: ---------------— _s
Parameters
_radicand The radicand of the square root.
_q The summand not containing the square root.
_r The coefficient of the radicand.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
Definition at line 718 of file Substitute.cpp.
Referenced by substituteNormalSqrtEq().
substituteNormalSqrtLeq()
bool vs::substituteNormalSqrtLeq (const smtrat::Poly & _radicand, const smtrat::Poly & _q, const smtrat::Poly & _r, const smtrat::Poly & _s, DisjunctionOfConstraintConjunctions & _result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
The relation symbol of the constraint to substitute is less or equal.
                        (_q+_r*sqrt(_radicand))
The term then looks like: -------------------— _s
Parameters
_radicand The radicand of the square root.
_q The summand not containing the square root.
_r The coefficient of the radicand.
_s The denominator of the expression containing the square root.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
Definition at line 856 of file Substitute.cpp.
Referenced by substituteNormalSqrtLeq().
substituteNormalSqrtLess()
bool vs::substituteNormalSqrtLess (const smtrat::Poly & _radicand, const smtrat::Poly & _q, const smtrat::Poly & _r, const smtrat::Poly & _s, DisjunctionOfConstraintConjunctions & _result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
The relation symbol of the constraint to substitute is less.
                        (_q+_r*sqrt(_radicand))
The term then looks like: -------------------— _s
Parameters
_radicand The radicand of the square root.
_q The summand not containing the square root.
_r The coefficient of the radicand.
_s The denominator of the expression containing the square root.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
Definition at line 793 of file Substitute.cpp.
Referenced by substituteNormalSqrtLess().
substituteNormalSqrtNeq()
bool vs::substituteNormalSqrtNeq (const smtrat::Poly & _radicand, const smtrat::Poly & _q, const smtrat::Poly & _r, DisjunctionOfConstraintConjunctions & _result, bool _accordingPaper)
Sub-method of substituteNormalSqrt, where applying the substitution led to a term containing a square root.
The relation symbol of the constraint to substitute is "!=".
                        (_q+_r*sqrt(_radicand))
The term then looks like: --------------------— _s
Parameters
_radicand The radicand of the square root.
_q The summand not containing the square root.
_r The coefficient of the radicand.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
Definition at line 759 of file Substitute.cpp.
Referenced by substituteNormalSqrtNeq().
substituteNotTrivialCase()
void vs::substituteNotTrivialCase (const smtrat::ConstraintT & , const Substitution & , DisjunctionOfConstraintConjunctions &)
Deals with the case, that the left hand side of the constraint to substitute is not a trivial polynomial in the variable to substitute.
The constraints left hand side then should looks like: ax^2+bx+c
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
Definition at line 1108 of file Substitute.cpp.
Referenced by substituteNotTrivialCase().
substitutePlusEps()
bool vs::substitutePlusEps (const smtrat::ConstraintT & _cons, const Substitution & _subs, DisjunctionOfConstraintConjunctions & _result, bool _accordingPaper, carl::Variables & _conflictingVariables, const smtrat::EvalDoubleIntervalMap & _solutionSpace)
Applies the given substitution to the given constraint, where the substitution is of the form [x -> t+epsilon] with x as the variable and c and b polynomials in the real theory excluding x.
The constraint is of the form "f(x) \rho 0" with element of {=,!=,<,>,<=,>=} and k as the maximum degree of x in f.
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
_accordingPaper A flag that indicates whether to apply the virtual substitution rules according to the paper "Quantifier elimination for real algebra - the quadratic case and beyond." by Volker Weispfenning (true) or in an adapted way which omits a higher degree in the result by splitting the result in more cases (false).
_conflictingVariables If a conflict with the given solution space occurs, the variables being part of this conflict are stored in this container.
_solutionSpace The solution space in form of double intervals of the variables occurring in the given constraint.
substituteTrivialCase()
void vs::substituteTrivialCase (const smtrat::ConstraintT & _cons, const Substitution & _subs, DisjunctionOfConstraintConjunctions & _result)
Deals with the case, that the left hand side of the constraint to substitute is a trivial polynomial in the variable to substitute.
The constraints left hand side then should look like: ax^2+bx+c
Parameters
_cons The constraint to substitute in.
_subs The substitution to apply.
_result The vector, in which to store the results of this substitution. It is semantically a disjunction of conjunctions of constraints.
Definition at line 1098 of file Substitute.cpp.
Referenced by substituteTrivialCase().