SMT-RAT: smtrat Namespace Reference
smtrat Namespace Reference
smtrat is the main namespace for the library.
Namespaces
compile_information
Compile time generated information about compiler and system version.
maxsmt
Contains strategy implementations for max SMT computations.
parser
Contains the parser for smtlib files and everything related.
unsatcore
Contains strategy implementations for unsat core computations.
Data Structures
struct AbstractModuleFactory
class ActaNRA
Strategy description.
class AllModulesStrategy
class AnnotatedBVTerm
class AxiomFactory
class BackendLink
class Backends
class BackendSynchronisation
struct Backtrackable
struct BaseSATSettings_MCSAT
class BEModule
struct BESettings1
class Bimap
Container that stores expensive to construct objects and allows the fast lookup with respect to two independent keys within the objects.
class BlastedConstr
class BlastedPoly
struct BoolUEQRewriter
struct Branching
Stores all necessary information of an branch, which can be used to detect probable infinite loop of branchings.
class BVAnnotation
class BVDirectEncoder
class BVModule
class BVPreprocessing
Strategy description.
struct BVSettings1
class BVSolver
Strategy description.
struct by_address_hasher
Hash an iterator by the pointed-to address.
class CADModule
Module invoking a CAD solver of the GiNaCRA library.
class CADOnly
class CADOnlyAssignment
class CADOnlyPath
struct CADSettingsNoRoots
struct CADSettingsReal
struct CADSettingsSplitFirst
struct CADSettingsSplitLast
struct CADSettingsSplitPath
class CardinalityEncoder
struct CMakeOptionPrinter
class CNFerModule
class CoCoAGBModule
struct CoCoAGBSettings1
struct CoCoAGBSettings2
struct CollectBoolsInUEQs
class CollectionWithOrigins
class ConstrTree
class CSplitFull
class CSplitModule
class CSplitOnly
struct CSplitSettings1
class CubeLIAModule
struct CubeLIASettings1
class CurryModule
struct CurrySettings1
struct CycleEnumerator
This class encapsulates an algorithm for enumerating all cycles.
struct decidePassingPolynomial
class DynamicPriorityQueue
class dynarray
dynarray is similar to std::vector, but has only a reduced interface.
class dynarray_allocator
class ElementWithOrigins
class EMModule
struct EMSettings1
struct EQGraph
class EQModule
class EQPreprocessingModule
struct EQPreprocessingSettings1
struct EQPreprocessingSettings2
struct EQSettings1
struct EQSettingsForPreprocessing
class ESModule
struct ESSettings1
class ExactlyOneCommanderEncoder
class Executor
class fixedsize_allocator
An allocator meant to be used for containers that typically allocate single objects or nodes, such as sets, maps and linked lists.
class fixedsize_allocator< void >
I do not know where an allocator for void would be of any use; but in order to mimic std::allocator (where this is explicitly mentioned) as good as possible, we do this for the void case.
class fixedsize_freelist
Implements a fixed-(at-compile-time)-size allocator based on a free list embedded in the space of currently unused objects.
struct FormulaIteratorHasher
Hash function for use of Input::const_iterator in unordered data structures.
class FormulaWithOrigins
Stores a formula along with its origins.
class ForwardHyperGraph
This class implements a forward hypergraph.
class FouMoModule
A module which applies the Fourier-Motzkin algorithm.
struct FouMoSettings1
class FPPModule
struct FPPSettings1
struct FPPSettings2
struct FPPSettings3
struct FPPSettingsOptimization
struct FPPSettingsPB
struct FPPSettingsPBGroebner
class freelist
Implements a fixed-(at-runtime)-size allocator based on a free list embedded in the space of currently unused objects.
class FullStrategy
class FullStrategy2
class FullStrategy3
class GBModule
A solver module based on Groebner basis.
class GBModuleState
A class to save the current state of a GBModule.
class GBOnly
class GBPPModule
struct GBPPSettings1
struct GBSettings1
struct GBSettings3
struct GBSettings4
struct GBSettings41
struct GBSettings43
struct GBSettings5
struct GBSettings51
struct GBSettings51A
struct GBSettings6
struct GBSettings61
struct GBSettings61A
struct GBSettings63
class ICEModule
struct ICESettings1
class ICPModule
struct ICPSettings1
struct ICPSettings2
struct ICPSettings3
struct ICPSettings4
class IncWidthModule
struct IncWidthSettings1
struct IncWidthSettings2
struct IncWidthSettings3
class InequalitiesTable
Datastructure for the GBModule.
class IntBlastModule
struct IntBlastSettings1
struct IntBlastSettings2
class IntEqModule
A module which checks whether the equations contained in the received (linear integer) formula have a solution.
struct IntEqSettings1
struct is_variant
States whether a given type is a boost::variant.
struct is_variant< boost::variant< BOOST_VARIANT_ENUM_PARAMS(U)> >
States that boost::variant is indeed a boost::variant.
struct is_variant< const boost::variant< BOOST_VARIANT_ENUM_PARAMS(U)> >
States that const boost::variant is indeed a boost::variant.
struct JunctorMerger
class JustVS
Strategy description.
class LIASolver
Strategy description.
class LOG
class LongFormulaEncoder
class LRAModule
A module which performs the Simplex method on the linear part of it's received formula.
struct LRASettings1
struct LRASettings2
struct LRASettingsICP
class LRASolver
Strategy description.
class LVEModule
struct LVESettings1
class Manager
Base class for solvers.
class MAXSATBackendStrategy
This strategy is used as a artificial backend in the MaxSMT Module.
class MaxSMT
class MCBModelSubstitution
class MCBModule
struct MCBSettings1
class MCSATFMNL
class MCSATFMVSNL
class MCSATFMVSOC
class MCSATICPNL
class MCSATNL
class MCSATOC
class MCSATPPNL
class MCSATPPOC
class MCSATVSNL
class MISExact
class MISGreedy
class MISGreedyPre
class MISGreedyWeighted
class MISHybrid
class MISTrivial
class MixedSignEncoder
class Module
A base class for all kind of theory solving methods.
struct ModuleFactory
class ModuleInput
The input formula a module has to consider for it's satisfiability check.
class ModuleWrapper
class MonomialMappingByVariablePool
class NewCAD_Brown
class NewCAD_Collins
class NewCAD_Hong
class NewCAD_LOLS
class NewCAD_LOLT
class NewCAD_LOLTA
class NewCAD_LOLTS
class NewCAD_LOLTSA
class NewCAD_LOS
class NewCAD_LOT
class NewCAD_LOTLSA
class NewCAD_LOTS
class NewCAD_LOTSA
class NewCAD_McCallum
class NewCAD_McCallumPartial
class NewCAD_POD
class NewCAD_POLD
class NewCAD_POPD
class NewCAD_POSD
class NewCAD_PP
class NewCAD_PPRR
class NewCAD_PPVE
class NewCAD_PPVERR
struct NewCADBasePPSettings
struct NewCADBaseProjectionSettings
struct NewCADBaseSettings
struct NewCADBaseSettingsLO
struct NewCADBaseSettingsPO
class NewCADEQ_B
class NewCADEQ_BD
class NewCADEQ_BR
class NewCADEQ_BRD
class NewCADEQ_BRI
class NewCADEQ_BRID
class NewCADEQ_BS
class NewCADEQ_BSD
class NewCADEQ_BSI
class NewCADEQ_BSID
class NewCADEQ_R
class NewCADEQ_RD
class NewCADEQ_RI
class NewCADEQ_RID
class NewCADEQ_S
class NewCADEQ_SD
class NewCADEQ_SI
class NewCADEQ_SID
class NewCADFOS
class NewCADFU
class NewCADFU_SC
class NewCADFU_SI
class NewCADFU_SInf
class NewCADFU_SL
class NewCADFU_SR
class NewCADFU_SZ
class NewCADModule
class NewCADNaive
class NewCADNO
class NewCADNU
class NewCADOnly
class NewCADSAT
struct NewCADSettings_LOLS
struct NewCADSettings_LOLT
struct NewCADSettings_LOLTA
struct NewCADSettings_LOLTS
struct NewCADSettings_LOLTSA
struct NewCADSettings_LOS
struct NewCADSettings_LOT
struct NewCADSettings_LOTLSA
struct NewCADSettings_LOTS
struct NewCADSettings_LOTSA
struct NewCADSettings_LOType
struct NewCADSettings_POD
struct NewCADSettings_POlD
struct NewCADSettings_POLD
struct NewCADSettings_POPD
struct NewCADSettings_POSD
struct NewCADSettingsBrown
struct NewCADSettingsCollins
struct NewCADSettingsEnumerateAll
struct NewCADSettingsEQ_B
struct NewCADSettingsEQ_BD
struct NewCADSettingsEQ_BR
struct NewCADSettingsEQ_BRD
struct NewCADSettingsEQ_BRI
struct NewCADSettingsEQ_BRID
struct NewCADSettingsEQ_BS
struct NewCADSettingsEQ_BSD
struct NewCADSettingsEQ_BSI
struct NewCADSettingsEQ_BSID
struct NewCADSettingsEQ_R
struct NewCADSettingsEQ_RD
struct NewCADSettingsEQ_RI
struct NewCADSettingsEQ_RID
struct NewCADSettingsEQ_S
struct NewCADSettingsEQ_SD
struct NewCADSettingsEQ_SI
struct NewCADSettingsEQ_SID
struct NewCADSettingsF1
struct NewCADSettingsFO1
struct NewCADSettingsFOS
struct NewCADSettingsFOV
struct NewCADSettingsFU
struct NewCADSettingsFU_SC
struct NewCADSettingsFU_SI
struct NewCADSettingsFU_SInf
struct NewCADSettingsFU_SL
struct NewCADSettingsFU_SR
struct NewCADSettingsFU_SZ
struct NewCADSettingsFV
struct NewCADSettingsHong
struct NewCADSettingsInterleave
struct NewCADSettingsLazard
struct NewCADSettingsMcCallum
struct NewCADSettingsMcCallumPartial
struct NewCADSettingsMISBase
struct NewCADSettingsMISExact
struct NewCADSettingsMISGreedy
struct NewCADSettingsMISGreedyPre
struct NewCADSettingsMISGreedyWeighted
struct NewCADSettingsMISHybrid
struct NewCADSettingsMISTrivial
struct NewCADSettingsNaive
struct NewCADSettingsNO
struct NewCADSettingsNU
struct NewCADSettingsPP
struct NewCADSettingsPPRR
struct NewCADSettingsPPVE
struct NewCADSettingsPPVERR
struct NewCADSettingsSO
struct NewCADSettingsSU
class NewCADSO
class NewCADSU
class NIABB
Strategy description.
class NIABlast
Strategy description.
class NIASolver
Strategy description.
class NLSAT
struct NNFPreparation
class NNFRewriter
class NRA_CAD
Strategy description.
class NRA_ICPVSCAD
Strategy description.
class NRA_LRAVSCAD
Strategy description.
class NRA_VSCAD
Strategy description.
class NRAILModule
struct NRAILSettings1
struct NRAILSettings10
struct NRAILSettings11
struct NRAILSettings12
struct NRAILSettings13
struct NRAILSettings14
struct NRAILSettings15
struct NRAILSettings16
struct NRAILSettings17
struct NRAILSettings18
struct NRAILSettings19
struct NRAILSettings2
struct NRAILSettings20
struct NRAILSettings21
struct NRAILSettings22
struct NRAILSettings23
struct NRAILSettings24
struct NRAILSettings25
struct NRAILSettings3
struct NRAILSettings4
struct NRAILSettings5
struct NRAILSettings6
struct NRAILSettings7
struct NRAILSettings8
struct NRAILSettings9
class NRARefinementSolver
Strategy description.
class NRARefinementSolver1
Strategy description.
class NRARefinementSolver10
Strategy description.
class NRARefinementSolver11
Strategy description.
class NRARefinementSolver12
Strategy description.
class NRARefinementSolver13
Strategy description.
class NRARefinementSolver14
Strategy description.
class NRARefinementSolver15
Strategy description.
class NRARefinementSolver16
Strategy description.
class NRARefinementSolver17
Strategy description.
class NRARefinementSolver18
Strategy description.
class NRARefinementSolver19
Strategy description.
class NRARefinementSolver2
Strategy description.
class NRARefinementSolver20
Strategy description.
class NRARefinementSolver21
Strategy description.
class NRARefinementSolver22
Strategy description.
class NRARefinementSolver23
Strategy description.
class NRARefinementSolver24
Strategy description.
class NRARefinementSolver25
Strategy description.
class NRARefinementSolver3
Strategy description.
class NRARefinementSolver4
Strategy description.
class NRARefinementSolver5
Strategy description.
class NRARefinementSolver6
Strategy description.
class NRARefinementSolver7
Strategy description.
class NRARefinementSolver8
Strategy description.
class NRARefinementSolver9
Strategy description.
class NRASolver
Strategy description.
class Optimization
class OptimizationPreprocessing
class OptimizationStrategy
A backend compatible with optimization.
class OptRatOne
Strategy description.
struct OrPathShortener
A rewriter that checks every (X)OR that only contains ANDs and UEQs as children for equalities that hold for every alternative, and adds such equalities explicitly.
struct pairhash
Note that this may NOT be a specialization of std::hash for std::pair, this is not allowed by the standard as it does not involve a user-defined type.
class PBGaussModule
struct PBGaussSettings1
class PBPPModule
struct PBPPSettings1
struct PBPPSettingsBase
struct PBPPSettingsBasic
struct PBPPSettingsCardinalityOnly05
struct PBPPSettingsCardinalityOnly05Normalize
struct PBPPSettingsCardinalityOnly20
struct PBPPSettingsCardinalityOnly20Normalize
struct PBPPSettingsFull05
struct PBPPSettingsFull20
struct PBPPSettingsLIAOnly
struct PBPPSettingsLIAOnlyWithNormalize
struct PBPPSettingsMaxSMT
struct PBPPSettingsWithCardConstr
struct PBPPSettingsWithMixedConstr
struct PBPPSettingsWithNormalize
struct PBPPSettingsWithRNS
class PBPPStrategy
class PBPPStrategy2
class PBPPStrategyBasic
class PBPPStrategyGauss
class PBPPStrategyGroe_Norm_PB_LIA
class PBPPStrategyGroe_PB_LIA
class PBPPStrategyGroebner
class PBPPStrategyLIA
class PBPPStrategyLIA_ICP
class PBPPStrategyLIA_VS
class PBPPStrategyLIAOnly
class PBPPStrategyNorm_LIA
class PBPPStrategyNorm_LIA_ICP
class PBPPStrategyNorm_LIA_VS
class PBPPStrategyNorm_PB_LIA
class PBPPStrategyPB_LIA
class PBPPStrategyRNS
class PBPPStrategyWithCardConstr
class PBPPStrategyWithMixedConstr
class PBPreprocessing
Strategy description.
class PBPreprocessingGroebner
struct PersistentUnionFind
class PFEModule
struct PFESettings1
class PModule
class PolyTree
class PolyTreeContent
class PolyTreePool
class PreprocessingOne
Strategy description.
class PriorityQueue
class PseudoBoolEncoder
Base class for a PseudoBoolean Encoder.
class PseudoBoolNormalizer
class PureSAT
Strategy description.
class ratComp16
Strategy description.
class RatComp2016
Strategy description.
class RatComp2016PL
Strategy description.
class RatFour
Strategy description.
class RatICP
Strategy description.
class RatICPVS
Strategy description.
class RatIntBlast
Strategy description.
class RationalCapsule
class RatNIA
Strategy description.
class RatNIAnoBB
Strategy description.
class RatNIAOne
Strategy description.
class RatNIATwo
Strategy description.
class RatNRAPl
Strategy description.
class RatOne
Strategy description.
class RatOneAndIntBlast
Strategy description.
class RatOneNoBB
Strategy description.
class RATSolver
Strategy description.
class RatThree
Strategy description.
class RatTwo
Strategy description.
class RatTwoNoBB
Strategy description.
class RatVSOnlyVB
Strategy description.
class RatVSPlain
Strategy description.
class RDLSolver
Strategy description.
struct reduceDB_lt
struct ReplaceVariablesRewriter
class RNSEncoder
class RuntimeSettings
A base class for settings which can be passed to the modules.
class SATModule
Implements a module performing DPLL style SAT checking.
struct SATSettings1
struct SATSettings3
struct SATSettings_MCSAT_AF_FMICPOCNL_TF
struct SATSettings_MCSAT_AF_FMICPVSOCNL_TF
struct SATSettings_MCSAT_AF_FMOCNL_BF
struct SATSettings_MCSAT_AF_FMOCNL_NLSAT
struct SATSettings_MCSAT_AF_FMOCNL_RND
struct SATSettings_MCSAT_AF_FMOCNL_TF
struct SATSettings_MCSAT_AF_FMOCNL_TFDYN
struct SATSettings_MCSAT_AF_FMOCNL_UNIFORM
struct SATSettings_MCSAT_AF_FMOCNL_UNIFORMTF
struct SATSettings_MCSAT_AF_FMOCNL_UV
struct SATSettings_MCSAT_AF_FMOCNL_UVactive
struct SATSettings_MCSAT_AF_FMVSOCNL_TF
struct SATSettings_MCSAT_AF_NL_TF
struct SATSettings_MCSAT_AF_OCNL_TF
struct SATSettings_MCSAT_SMT_FMOCNL_TF
struct SATSettingsMCSAT
struct SATSettingsMCSATFMNL
struct SATSettingsMCSATFMVSNL
struct SATSettingsMCSATFMVSOC
struct SATSettingsMCSATICPNL
struct SATSettingsMCSATNL
struct SATSettingsMCSATOC
struct SATSettingsMCSATVSNL
struct SATSettingsStopAfterUnknown
class ScopedBool
class SettingsComponents
class SettingsParser
class ShortFormulaEncoder
class SMTCOMP
Strategy description.
class SplitSOSModule
struct SplitSOSSettings1
struct StaticUnionFind
class Statistics
class StatisticsCollector
struct StatisticsPrinter
class StrategyGraph
class STropFull
class STropModule
class STropOnly
struct STropSettings1
class SymmetryModule
struct SymmetrySettings1
class Task
class TheoryVarSchedulerStatic
Schedules theory variables statically.
class ThreadPool
class TotalizerEncoder
TotalizerEncoder implements the Totalizer encoding as described in "Incremental Cardinality Constraints for MaxSAT" by Martins et al https://doi.org/10.1007/978-3-319-10428-7_39.
class TotalizerTree
class UFCegarModule
struct UFCegarSettings1
struct UFRewriter
class UFStrategy
Strategy description.
class union_find
Implements a union-find datastructure, a datastructure containing an array of entries.
struct UnionFindInterface
class UnionFindModule
struct UnionFindSettings1
class UnsatCore
class VariableCapsule
class VariableRewriteRule
struct variant_hash_visitor
class VariantMap
This class is a specialization of std::map where the keys are of arbitrary type and the values are of type boost::variant.
class VarSchedulerBase
Base class for variable schedulers.
class VarSchedulerFixedRandom
class VarSchedulerMcsatActivityPreferTheory
Activity-based scheduler preferring initially theory variables.
class VarSchedulerMcsatBase
Base class for all MCSAT variable scheduler.
class VarSchedulerMcsatBooleanFirst
Variable scheduling that all decides Boolean variables first before deciding any theory variable.
class VarSchedulerMcsatTheoryFirst
Variable scheduling that all decides theory variables first before deciding any Boolean variable.
class VarSchedulerMcsatUnivariateClausesOnly
Decides only Constraints occuring in clauses that are univariate in the current theory variable while the theory ordering is static.
class VarSchedulerMcsatUnivariateConstraintsOnly
Decides only Constraints univariate in the current theory variable while the theory ordering is static.
class VarSchedulerMinisat
Minisat's activity-based variable scheduling.
class VarSchedulerRandom
Random scheduler.
class VarSchedulerSMTTheoryGuided
Scheduler for SMT, implementing theory guided heuristics.
class VSModule
struct VSSettings1
struct VSSettings2
struct VSSettings23
struct VSSettings234
struct VSSettings2345
struct VSSettings2346
struct VSSettings234a
struct VSSettings235
struct VSSettings24
struct VSSettings245
struct VSSettings25
struct VSSettings3
struct VSSettings34
struct VSSettings345
struct VSSettings35
struct VSSettings4
struct VSSettings45
struct VSSettings5
struct VSSettingsNotSMTCompliant
struct VSSettingsOnlyBJ
struct VSSettingsOnlyInc
struct VSSettingsOnlyIS
struct VSSettingsOnlyLC
struct VSSettingsOnlyVB
struct VSSettingsPlain
Typedefs
using Logic = carl::Logic
using Integer = carl::IntegralType< Rational >::type
using TermT = carl::Term< Rational >
template<typename Coeff >
using UPoly = carl::UnivariatePolynomial< Coeff >
using RANPoint = carl::RealAlgebraicPoint< Rational >
using MultivariateRootT = carl::MultivariateRoot< Poly >
using RootExpr = carl::MultivariateRoot< Poly >
typedef carl::VarInfoMap< Poly > VarPolyInfoMap
using ModelMVRootSubstitution = carl::ModelMVRootSubstitution< Rational, Poly >
using SqrtEx = carl::SqrtEx< smtrat::Poly >
typedef expression::Expression Expression
typedef expression::Expressions Expressions
using ModelVariable = carl::ModelVariable
using ModelValue = carl::ModelValue< Rational, Poly >
using Model = carl::Model< Rational, Poly >
using ModelSubstitution = carl::ModelSubstitution< Rational, Poly >
using ModelPolynomialSubstitution = carl::ModelPolynomialSubstitution< Rational, Poly >
using InfinityValue = carl::InfinityValue
using DoubleInterval = carl::Interval< double >
using RationalInterval = carl::Interval< Rational >
using EvalDoubleIntervalMap = std::map< carl::Variable, DoubleInterval >
using EvalRationalIntervalMap = std::map< carl::Variable, RationalInterval >
using ObjectiveValues = std::vector< std::pair< std::variant< Poly, std::string >, Model::mapped_type > >
using Conditionals = std::vector< std::atomic_bool * >
A vector of atomic bool pointers.
using Rational = mpq_class
using Poly = carl::MultivariatePolynomial< Rational >
using Factorization = std::map< Poly, carl::uint >
using ConstraintT = carl::Constraint< Poly >
using ConstraintsT = carl::Constraints< Poly >
using VariableAssignmentT = carl::VariableAssignment< Poly >
using VariableComparisonT = carl::VariableComparison< Poly >
using FormulaT = carl::Formula< Poly >
using FormulasT = carl::Formulas< Poly >
using FormulaSetT = carl::FormulaSet< Poly >
using FormulasMultiT = std::multiset< FormulaT >
using EvalRationalMap = std::map< carl::Variable, Rational >
using VarPolyInfo = carl::VariableInformation< true, Poly >
using thread_priority = std::pair< std::size_t, std::size_t >
typedef std::pair< FormulaT, std::shared_ptr< std::vector< FormulaT > > > SingleFormulaOrigins
typedef std::map< FormulaT, std::shared_ptr< std::vector< FormulaT > > > FormulaOrigins
typedef std::map< carl::Variable, std::pair< std::vector< SingleFormulaOrigins >, std::vector< SingleFormulaOrigins > > > VariableUpperLower
typedef carl::StdMultivariatePolynomialPolicies< carl::BVReasons > ReasonPolicy
typedef std::set< icp::ContractionCandidate *, icp::contractionCandidateComp > ContractionCandidates
typedef std::map< FormulaT, std::shared_ptr< std::vector< FormulaT > > > Formula_Origins
typedef std::unordered_map< carl::Variable, carl::Monomial::Arg >::iterator MonomialMapIterator
typedef std::unordered_map< carl::Variable, carl::Monomial::Arg > MonomialMap
using Type = carl::UVariable
template<typename Impl >
using EQClasses = UnionFindInterface< Type, Impl >
using StaticClasses = EQClasses< StaticUnionFind >
using BacktrackableClasses = EQClasses< Backtrackable< PersistentUnionFind > >
using Classes = BacktrackableClasses
typedef bool(* ConditionEvaluation) (carl::Condition)
typedef std::function< bool(carl::Condition)> ConditionFunction
using Priority = std::vector< std::size_t >
Enumerations
enum LemmaLevel { NONE = 0, NORMAL = 1, ADVANCED = 2 }
enum Answer {
SAT = 0, UNSAT = 1, UNKNOWN = 2, ABORTED = 3,
OPTIMAL = 4
}
An enum with the possible answers a Module can give.
enum StatisticsOutputFormat { SMTLIB, XML }
enum MaxSMTStrategy { FU_MALIK_INCREMENTAL, MSU3, LINEAR_SEARCH }
enum MISHeuristic { TRIVIAL, GREEDY }
enum SplitHeuristic { FIRST, LAST }
enum pass_inequalities { AS_RECEIVED, FULL_REDUCED, FULL_REDUCED_IF }
Only active if we check inequalities.
enum after_firstInfeasibleSubset { RETURN_DIRECTLY, PROCEED_INFEASIBLEANDDEDUCTION, PROCEED_ALLINEQUALITIES }
enum theory_deductions { NO_CONSTRAINTS, ONLY_INEQUALITIES, ALL_CONSTRAINTS }
enum check_inequalities { ALWAYS, AFTER_NEW_GB, NEVER }
enum transform_inequalities { ALL_INEQUALITIES, ONLY_NONSTRICT, NO_INEQUALITIES }
enum backtracking_mode { CHRONOLOGICAL, NON_CHRONOLOGICAL }
enum SplittingHeuristic : unsigned { SIZE, UNSATISFIABILITY, SATISFIABILITY }
enum UNSATFormulaSelectionStrategy { ALL = 0, FIRST = 1, RANDOM = 2 }
enum CCES : unsigned { SECOND_LEVEL_MINIMIZER, LITERALS_BLOCKS_DISTANCE, SECOND_LEVEL_MINIMIZER_PLUS_LBD }
enum VARIABLE_ACTIVITY_STRATEGY : unsigned { NONE, MIN_COMPLEXITY_MAX_OCCURRENCES }
enum MCSAT_BOOLEAN_DOMAIN_PROPAGATION : unsigned { NONE, PARTIAL_CONFLICT, PARTIAL, FULL }
enum TheoryGuidedDecisionHeuristicLevel : unsigned { CONFLICT_FIRST, SATISFIED_FIRST, DISABLED }
enum SeparatorType { STRICT = 0, WEAK = 1 }
enum VariableValuationStrategy : unsigned { OPTIMIZE_BEST, OPTIMIZE_AVERAGE, OPTIMIZE_WORST }
enum UnsatCoreStrategy { ModelExclusion }
Functions
int handle_basic_options (const SettingsParser &parser)
const auto & settings_parser ()
bool parseSMT2File (parser::InstructionHandler &handler, bool queueInstructions, std::istream &input)
std::ostream & operator<< (std::ostream &os, CMakeOptionPrinter cmop)
constexpr CMakeOptionPrinter CMakeOptions (bool advanced=false) noexcept
template<typename Executor >
bool parseInput (const std::string &pathToInputFile, Executor &e, bool &queueInstructions)
template<typename Executor >
int executeFile (const std::string &pathToInputFile, Executor &e)
Parse the file and save it in formula.
int analyze_file (const std::string &filename)
template<typename Strategy >
int run_dimacs_file (Strategy &strategy, const std::string &filename)
template<typename Strategy >
int run_opb_file (Strategy &, const std::string &)
FormulaT parse_smtlib (const std::string &)
FormulaT parse_formula (const std::string &filename)
Loads the smt2 file specified in filename and returns the formula.
int preprocess_file (const std::string &filename, const std::string &outfile)
Loads the smt2 file specified in filename and runs the preprocessing strategy.
void visiting (const Expression &expr)
void testExpression ()
const auto & settings_analyzer ()
analyzer::AnalyzerStatistics & analyze_formula (const FormulaT &f)
template<typename TT , typename C >
std::ostream & operator<< (std::ostream &os, const PriorityQueue< TT, C > &pq)
const settings::Settings & Settings ()
const auto & settings_core ()
const auto & settings_solver ()
const auto & settings_validation ()
bool is_sat (Answer a)
std::ostream & operator<< (std::ostream &os, Answer a)
template<typename T >
auto & statistics_get (const std::string &name)
template<StatisticsOutputFormat SOF>
std::ostream & operator<< (std::ostream &os, StatisticsPrinter< SOF >)
template<>
std::ostream & operator<< (std::ostream &os, StatisticsPrinter< StatisticsOutputFormat::SMTLIB >)
template<>
std::ostream & operator<< (std::ostream &os, StatisticsPrinter< StatisticsOutputFormat::XML >)
auto statistics_as_smtlib ()
auto statistics_as_xml ()
void statistics_to_xml_file (const std::string &filename)
const auto & settings_statistics ()
std::ostream & operator<< (std::ostream &os, MaxSMTStrategy ucs)
template<std::size_t N, class RandomAccessIterator , class Comparator >
static void select_best (typename std::iterator_traits< RandomAccessIterator >::value_type *result, RandomAccessIterator begin, RandomAccessIterator end, Comparator &&compare)
static void hash_combine (std::size_t &seed, std::size_t hash_value) noexcept
carl::Sign sign_of (carl::Relation rel, bool invert)
FormulaT createZeroOne (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable)
FormulaT createZeroTwo (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable)
FormulaT createZeroThree (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable)
FormulasT createZero (smtrat::VariableCapsule variableCapsule)
FormulaT createTangentPlaneNEQOne (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable, Rational aRational)
FormulaT createTangentPlaneNEQTwo (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable, Rational bRational)
FormulaT createTangentPlaneNEQThree (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable, Rational aRational, Rational bRational)
FormulaT createTangentPlaneNEQFour (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable, Rational aRational, Rational bRational)
FormulasT createTangentPlaneNEQ (VariableCapsule variableCapsule, RationalCapsule rationalCapsule)
FormulaT createTangentPlaneEQOne (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable, Rational aRational)
FormulaT createTangentPlaneEQTwo (carl::Variable xVariable, carl::Variable yVariable, carl::Variable zVariable, Rational aRational)
FormulasT createTangentPlaneEQ (VariableCapsule variableCapsule, RationalCapsule rationalCapsule)
const smtrat::VariableCapsule extractVariables (MonomialMapIterator monomialIterator)
Model createAbsoluteValuedModel (Model linearizedModel)
carl::Variable createAuxiliaryVariable (carl::Variable variable)
create an auxiliary variable e.g.
FormulaT generateAbsFormula (carl::Variable variable, carl::Variable aux_variable)
| x1 | = (and (=> (x1 >= 0) (y1 = x1)) (=> (x1 < 0) (y1 = -x1)))
FormulaT generateAbsFormula (carl::Variable variableLeft, carl::Variable variableRight, carl::Relation relation)
| x1 | <= | x1 | = (and (=> (x1 >= 0) (y1 = x1)) (=> (x1 < 0) (y1 = -x1)) (=> (x2 >= 0) (y2 = x2)) (=> (x2 < 0) (y2 = -x2)) (y1 <= y2))
FormulaT createEquivalentToOriginalMonotonicityOne (smtrat::VariableCapsule variableCapsule, smtrat::VariableCapsule variableCapsuleInner)
FormulaT createEquivalentToOriginalMonotonicityTwo (smtrat::VariableCapsule variableCapsule, smtrat::VariableCapsule variableCapsuleInner)
FormulaT createEquivalentToOriginalMonotonicityThree (smtrat::VariableCapsule variableCapsule, smtrat::VariableCapsule variableCapsuleInner)
RationalCapsule extractRationalCapsule (VariableCapsule variableCapsule, Model linearizedModel)
FormulaT createOriginalMonotonicityOne (smtrat::VariableCapsule variableCapsule, smtrat::VariableCapsule variableCapsuleInner)
FormulaT createOriginalMonotonicityTwo (smtrat::VariableCapsule variableCapsule, smtrat::VariableCapsule variableCapsuleInner)
FormulaT createOriginalMonotonicityThree (smtrat::VariableCapsule variableCapsule, smtrat::VariableCapsule variableCapsuleInner)
FormulasT createMonotonicity (VariableCapsule variableCapsuleOuter, VariableCapsule variableCapsuleInner, Model absoluteValuedModel)
FormulaT createCongruence (smtrat::VariableCapsule variableCapsuleOuter, smtrat::VariableCapsule variableCapsuleInner)
FormulaT createICPGreaterOne (VariableCapsule variableCapsule, RationalCapsule rationalCapsule)
FormulaT createICPGreaterTwo (VariableCapsule variableCapsule, RationalCapsule rationalCapsule)
FormulasT createICPGreater (VariableCapsule variableCapsule, RationalCapsule rationalCapsule)
FormulaT createICPLess (VariableCapsule variableCapsule, RationalCapsule rationalCapsule)
bool abEqualcCheck (VariableCapsule variableCapsuleOuter, Model linearizedModel)
bool abGreatercCheck (RationalCapsule rationalCapsule)
bool abLesscCheck (RationalCapsule rationalCapsule)
RationalCapsule generateAbcPrimeForICP (RationalCapsule rationalCapsule, bool isGreater)
bool isAnyRationalIsZero (RationalCapsule rationalCapsule)
ModuleInput * originalFormula (new ModuleInput())
carl::Variable createZVariable ()
create variables and each time increment the suffix e.g., z_0, z_1, etc.
carl::Monomial::Arg createSquareOfVariable (carl::Variable Variable)
create a square of the variable
void insertIntoMap (carl::Variable GeneratedVariable, carl::Monomial::Arg monomial)
Insert the variable as key with monomial as value into the map The map is singeltone.
int divisionOfExponentByTwo (int exponent)
carl::Variable insertIntoMapOrRetrieveExistingVariable (carl::Monomial::Arg monomial)
Check if the monomial is alreday inserted imto the map, If yes, returned the key which is a variable otherwise create new variable and insert the monomial into the map against this new variable.
carl::Monomial::Arg abstractUnivariateMonomialForEvenExponent (carl::Variable Variable, int exponent)
Replace square of variable (x_0^2) of a monomial (x_0^6) by a variable (z_0), create a new monomial (z_0^3) and insert this variable as key with monomial (x_0^2) as value in the map.
carl::Variable abstractProductRecursively (std::list< carl::Variable > variables)
It creates monomial by taking and popping first two items from the list, Insert this new monomial as value into the map against a newly generated variable, Each time the newly generated variable is insterted at the front of the list.
carl::Monomial::Arg abstractUnivariateMonomialForOddExponent (carl::Variable Variable, int exponent)
Replace square of variable (x_0^2) of a monomial (x_0^7) by a variable (z_0), create a linear monomial (z_1) and insert the variable as key with monomial as value in the map.
carl::Monomial::Arg abstractUnivariateMonomial (carl::Variable Variable, int exponent)
create monomial which is linear
carl::Variable abstractMonomial (carl::Monomial::Arg monomial)
It linearizes a non-linear monomial.
FormulaT linearization (FormulaT formula)
Answer toAnswer (int value)
Answer isNRASatisfied (Model estimatedModel)
Chekcs if the estimated Assignment satisfies the input NRA formula.
Model createEstimatedAssignment (Model linearizedModel)
Creates the estimated model.
Model extendLinearizedModel (Model mModel, Model estimatedModel)
create a model combining mModel, estimatedModel and rest of the variables are guessed.
int rand (int min, int max)
FormulasT unsatisfiedFormulas (AxiomFactory::AxiomType axiomType, FormulasT formulas, Model model, UNSATFormulaSelectionStrategy formulaSelectionStrategy)
FormulasT refinement (AxiomFactory::AxiomType axiomType, Model linearizedModel, UNSATFormulaSelectionStrategy formulaSelectionStrategy)
Rational factorial (Rational n)
Rational factorial (std::size_t)
std::string flatten_name (const carl::UTerm &term)
std::string flatten_name_impl (const carl::UVariable &var)
std::string flatten_name_impl (const carl::UFInstance &ufi)
template<typename Instances >
bool flattened_function_calls (const Instances &instances) noexcept
std::ostream & operator<< (std::ostream &os, Module::LemmaType lt)
template<typename AnnotationType >
void annotateFormula (const FormulaT &, const std::vector< AnnotationType > &)
std::ostream & operator<< (std::ostream &os, const ModuleInput &mi)
bool isCondition (carl::Condition _condition)
template<typename Module >
std::ostream & operator<< (std::ostream &os, const ModuleFactory< Module > &mf)
void load_configured_strategy (Manager &m)
std::ostream & operator<< (std::ostream &os, UnsatCoreStrategy ucs)
Variables
static const Rational ZERO_RATIONAL = Rational(0)
static const Rational ONE_RATIONAL = Rational(1)
static const Rational MINUS_ONE_RATIONAL = Rational(-1)
static const Poly ZERO_POLYNOMIAL = Poly(ZERO_RATIONAL)
static const Poly ONE_POLYNOMIAL = Poly(ONE_RATIONAL)
static const Poly MINUS_ONE_POLYNOMIAL = Poly(MINUS_ONE_RATIONAL)
static const unsigned MAX_DEGREE_FOR_FACTORIZATION = 6
static const unsigned MIN_DEGREE_FOR_FACTORIZATION = 2
static const unsigned MAX_DIMENSION_FOR_FACTORIZATION = 6
static const unsigned MAX_NUMBER_OF_MONOMIALS_FOR_FACTORIZATION = 7
static const Model EMPTY_MODEL = Model()
int zVariableCounter = 0
std::string VariableName = "z_"
static constexpr int COMMANDER_GROUP_SIZE = 4
static const char * _cat = "CORE"
static DoubleOption opt_var_decay (_cat, "var-decay", "The variable activity decay factor", 0.95, DoubleRange(0, false, 1, false))
static DoubleOption opt_clause_decay (_cat, "cla-decay", "The clause activity decay factor", 0.999, DoubleRange(0, false, 1, false))
static DoubleOption opt_random_var_freq (_cat, "rnd-freq", "The frequency with which the decision heuristic tries to choose a random variable", 0, DoubleRange(0, true, 1, true))
static DoubleOption opt_random_seed (_cat, "rnd-seed", "Used by the random variable selection", 91648253, DoubleRange(0, false, HUGE_VAL, false))
static IntOption opt_ccmin_mode (_cat, "ccmin-mode", "Controls conflict clause minimization (0=none, 1=basic, 2=deep)", 2, IntRange(0, 2))
static IntOption opt_phase_saving (_cat, "phase-saving", "Controls the level of phase saving (0=none, 1=limited, 2=full)", 2, IntRange(0, 2))
static BoolOption opt_rnd_init_act (_cat, "rnd-init", "Randomize the initial activity", false)
static BoolOption opt_luby_restart (_cat, "luby", "Use the Luby restart sequence", true)
static IntOption opt_restart_first (_cat, "rfirst", "The base restart interval", 25, IntRange(1, INT32_MAX))
static DoubleOption opt_restart_inc (_cat, "rinc", "Restart interval increase factor", 3, DoubleRange(1, false, HUGE_VAL, false))
static DoubleOption opt_garbage_frac (_cat, "gc-frac", "The fraction of wasted memory allowed before a garbage collection is triggered", 0.20, DoubleRange(0, false, HUGE_VAL, false))
Detailed Description
smtrat is the main namespace for the library.
Flag activating some informative and not exaggerated output about module calls.
Class to create a settings object for the VSModule.
File: VSModule.cpp.
Class to create a substitution object.
Class to create a state object.
Class to create a condition object.
Class to create the formulas for axioms.
Implements a specialization of std::hash for any boost::variant.
Everything included in this library is found in this namespace.
This only works if the types of the variant are std::hash-enabled (have a std::hash specialization of their own).
Author
Aklima Zaman
Since
2018-09-24
Version
2018-09-24
Author
Florian Corzilius
Since
2010-07-26
Version
2011-06-20
Author
Florian Corzilius
Since
2010-07-26
Version
2011-12-05
Author
Florian Corzilius
Since
2010-05-11
Version
2013-10-24
Author
Florian Corzilius
Since
2010-05-11
Version
2013-10-23
Author
Florian Corzilius corzi.nosp@m.lius.nosp@m.@cs.r.nosp@m.wth-.nosp@m.aache.nosp@m.n.de
Since
2010-05-11
Version
2014-11-27
Author
Florian Corzilius
Since
2013-07-02
Version
2014-09-18
Enumeration Type Documentation
pass_inequalities
enum smtrat::pass_inequalities
Only active if we check inequalities.
AS_RECEIVED: Do not change the received inequalities. FULL_REDUCED: Pass the fully reduced received inequalities. REDUCED: Pass the reduced received inequalities. REDUCED_ONLYSTRICT: Pass the nonstrict inequalities reduced, the others unchanged FULL_REDUCED_ONLYNEW: Do only a full reduce on the newly added received inequalities.
Definition at line 23 of file GBSettings.h.
Function Documentation
abstractMonomial()
carl::Variable smtrat::abstractMonomial (carl::Monomial::Arg monomial)
It linearizes a non-linear monomial.
Parameters
monomial a monomoal object
Returns
a linear variable
Definition at line 316 of file NRAILModule.cpp.
abstractProductRecursively()
carl::Variable smtrat::abstractProductRecursively (std::list< carl::Variable > variables)
It creates monomial by taking and popping first two items from the list, Insert this new monomial as value into the map against a newly generated variable, Each time the newly generated variable is insterted at the front of the list.
Parameters
variables List of carl variables
Returns
created new linear variable
Definition at line 161 of file NRAILModule.cpp.
Referenced by abstractMonomial(), and abstractUnivariateMonomialForOddExponent().
abstractUnivariateMonomial()
carl::Monomial::Arg smtrat::abstractUnivariateMonomial (carl::Variable Variable, int exponent)
create monomial which is linear
Parameters
Variable a carl Variable object
exponent even or odd exponent of the variable
Returns
a linear monomial
Definition at line 279 of file NRAILModule.cpp.
Referenced by abstractMonomial().
abstractUnivariateMonomialForEvenExponent()
carl::Monomial::Arg smtrat::abstractUnivariateMonomialForEvenExponent (carl::Variable Variable, int exponent)
Replace square of variable (x_0^2) of a monomial (x_0^6) by a variable (z_0), create a new monomial (z_0^3) and insert this variable as key with monomial (x_0^2) as value in the map.
Parameters
Variable a carl::Variable object
exponent an even exponent
Returns
new monomial
Definition at line 128 of file NRAILModule.cpp.
Referenced by abstractUnivariateMonomial(), and abstractUnivariateMonomialForOddExponent().
abstractUnivariateMonomialForOddExponent()
carl::Monomial::Arg smtrat::abstractUnivariateMonomialForOddExponent (carl::Variable Variable, int exponent)
Replace square of variable (x_0^2) of a monomial (x_0^7) by a variable (z_0), create a linear monomial (z_1) and insert the variable as key with monomial as value in the map.
Parameters
Variable a carl::Variable object
exponent an odd exponent
Returns
new linear monomial
Definition at line 213 of file NRAILModule.cpp.
Referenced by abstractUnivariateMonomial().
createAuxiliaryVariable()
carl::Variable smtrat::createAuxiliaryVariable (carl::Variable variable)
create an auxiliary variable e.g.
aux_<Variable Name>
Parameters
variable the variable for which auxiliary variable to be created
Returns
created auxiliary variable
Definition at line 354 of file AxiomFactory.cpp.
Referenced by generateAbsFormula().
createEstimatedAssignment()
Model smtrat::createEstimatedAssignment (Model linearizedModel)
Creates the estimated model.
estimated model takes the solution from mModel or randomly chosen.
Parameters
linearizedModel Model of linearized formula.
Definition at line 526 of file NRAILModule.cpp.
Referenced by smtrat::NRAILModule< Settings >::checkCore().
createSquareOfVariable()
carl::Monomial::Arg smtrat::createSquareOfVariable (carl::Variable Variable)
create a square of the variable
Parameters
Variable a carl Variable object e.g., x_0
Returns
a monomial object e.g., x_0^2
Definition at line 66 of file NRAILModule.cpp.
Referenced by abstractUnivariateMonomialForEvenExponent(), and abstractUnivariateMonomialForOddExponent().
createZVariable()
carl::Variable smtrat::createZVariable ()
create variables and each time increment the suffix e.g., z_0, z_1, etc.
Returns
a carl Variable object
Definition at line 56 of file NRAILModule.cpp.
Referenced by insertIntoMapOrRetrieveExistingVariable().
executeFile()
template<typename Executor > int smtrat::executeFile (const std::string & pathToInputFile, Executor & e)
Parse the file and save it in formula.
Parameters
pathToInputFile The path to the input smt2 file.
formula A pointer to the formula object which holds the parsed input afterwards.
options Save options from the smt2 file here.
Definition at line 36 of file execute_smtlib.h.
Referenced by preprocess_file().
extendLinearizedModel()
Model smtrat::extendLinearizedModel (Model mModel, Model estimatedModel)
create a model combining mModel, estimatedModel and rest of the variables are guessed.
This model checks the satifiability of the axioms.
Parameters
mModel Model of linearized formula.
estimatedModel the estimated model for original formula.
Returns
the Abstract Model
Definition at line 576 of file NRAILModule.cpp.
Referenced by smtrat::NRAILModule< Settings >::checkCore().
generateAbsFormula() [1/2]
FormulaT smtrat::generateAbsFormula (carl::Variable variable, carl::Variable aux_variable)
| x1 | = (and (=> (x1 >= 0) (y1 = x1)) (=> (x1 < 0) (y1 = -x1)))
Parameters
variable
Returns
Definition at line 367 of file AxiomFactory.cpp.
Referenced by generateAbsFormula().
generateAbsFormula() [2/2]
FormulaT smtrat::generateAbsFormula (carl::Variable variableLeft, carl::Variable variableRight, carl::Relation relation)
| x1 | <= | x1 | = (and (=> (x1 >= 0) (y1 = x1)) (=> (x1 < 0) (y1 = -x1)) (=> (x2 >= 0) (y2 = x2)) (=> (x2 < 0) (y2 = -x2)) (y1 <= y2))
Parameters
variableLeft
variableRight
relation
Returns
Definition at line 405 of file AxiomFactory.cpp.
insertIntoMap()
void smtrat::insertIntoMap (carl::Variable GeneratedVariable, carl::Monomial::Arg monomial)
Insert the variable as key with monomial as value into the map The map is singeltone.
Parameters
GeneratedVariable
monomial
Definition at line 76 of file NRAILModule.cpp.
Referenced by insertIntoMapOrRetrieveExistingVariable().
insertIntoMapOrRetrieveExistingVariable()
carl::Variable smtrat::insertIntoMapOrRetrieveExistingVariable (carl::Monomial::Arg monomial)
Check if the monomial is alreday inserted imto the map, If yes, returned the key which is a variable otherwise create new variable and insert the monomial into the map against this new variable.
Parameters
monomial a monomoal object
Returns
a carl::Variable object
Definition at line 97 of file NRAILModule.cpp.
Referenced by abstractProductRecursively(), abstractUnivariateMonomialForEvenExponent(), and abstractUnivariateMonomialForOddExponent().
isNRASatisfied()
Answer smtrat::isNRASatisfied (Model estimatedModel)
Chekcs if the estimated Assignment satisfies the input NRA formula.
Parameters
estimatedModel The estimated model.
Definition at line 511 of file NRAILModule.cpp.
Referenced by smtrat::NRAILModule< Settings >::checkCore().
parse_formula()
FormulaT smtrat::parse_formula (const std::string & filename)
Loads the smt2 file specified in filename and returns the formula.
This function ignores most SMT-LIB commands but simply accumulated all asserted formulas.
preprocess_file()
int smtrat::preprocess_file (const std::string & filename, const std::string & outfile)
Loads the smt2 file specified in filename and runs the preprocessing strategy.
The resulting (simplified) problem is written to outfile (or stdout if outfile is empty).
Definition at line 97 of file preprocessor.cpp.
Variable Documentation
ZERO_RATIONAL
const Rational smtrat::ZERO_RATIONAL = Rational(0) static
Todo:
move static variables to own cpp
Definition at line 85 of file Common.h.
Referenced by createEstimatedAssignment(), and extendLinearizedModel().