SMT-RAT: delta Namespace Reference
delta Namespace Reference
Data Structures
class Checker
This class takes care of calling the actual solver.
class Consumer
This class takes care of asynchronous execution of calls to the solver.
struct Node
This class represents a node in a SMTLIB file.
struct Skipper
This class is a boost::spirit::qi grammar that matches whitespaces and smtlib comments.
struct SymbolParser
This class is a boost::spirit::qi grammar that matches all kinds of smtlib symbols, numbers etc.
struct ErrorHandler
class Parser
This class parses a whole smtlib file into a hierarchy of Node objects.
class Producer
This class iteratively applies the operators to a smtlib file until no further simplifications can be performed.
class Settings
This class loads and checks the command line options with help of boost::program_options.
class TempFilenameGenerator
This class generates and reuses temporary filenames with a common prefix.
class ProgressBar
This class provides a simple way to show progress bars on the command line.
class String
This class can be used to create std::string objects using streaming operators.
Typedefs
typedef std::vector< Node > NodeChangeSet
Set of new nodes.
typedef std::function
< NodeChangeSet(const Node &)> NodeOperator
Type of an node operator.
typedef
boost::spirit::istream_iterator BaseIteratorType
typedef
boost::spirit::line_pos_iterator
< BaseIteratorType > PositionIteratorType
typedef PositionIteratorType Iterator
Functions
NodeChangeSet children (const Node &n)
Node operator that returns all children of a node.
NodeChangeSet mergeChild (const Node &n)
Node operator that merges nodes with one of its own children.
NodeChangeSet number (const Node &n)
Node operator that provides meaningful replacements for numbers.
NodeChangeSet constant (const Node &n)
Node operator that provides meaningful replacements for variables.
NodeChangeSet letExpression (const Node &n)
Node operator that eliminated let expressions.
NodeChangeSet BV_zeroExtend (const Node &n)
NodeChangeSet BV_mergeShift (const Node &n)
(bvlshr (bvlshr x (_ bv1 8)) (_ bv1 8))
Typedef Documentation
typedef boost::spirit::istream_iterator delta::BaseIteratorType
Definition at line 47 of file Parser.h.
typedef PositionIteratorType delta::Iterator
Definition at line 49 of file Parser.h.
typedef std::vector<Node> delta::NodeChangeSet
Set of new nodes.
Definition at line 40 of file operators.h.
typedef std::function<NodeChangeSet(const Node&)> delta::NodeOperator
Type of an node operator.
A NodeOperator is called on a node and shall return a set of new nodes. These new nodes are supposed to be a simplifying replacement for the given node.
Definition at line 46 of file operators.h.
typedef boost::spirit::line_pos_iterator<BaseIteratorType> delta::PositionIteratorType
Definition at line 48 of file Parser.h.
Function Documentation
NodeChangeSet delta::BV_mergeShift (const Node & n)
(bvlshr (bvlshr x (_ bv1 8)) (_ bv1 8))
Definition at line 189 of file operators.h.
Referenced by delta::Producer::Producer().
NodeChangeSet delta::BV_zeroExtend (const Node & n)
Definition at line 164 of file operators.h.
Referenced by delta::Producer::Producer().
NodeChangeSet delta::children (const Node & n)
Node operator that returns all children of a node.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 53 of file operators.h.
Referenced by smtrat::VSModule< Settings >::eliminate(), delta::Producer::Producer(), and smtrat::cad::debug::TikzTreePrinter::reorderTree().
NodeChangeSet delta::constant (const Node & n)
Node operator that provides meaningful replacements for variables.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 133 of file operators.h.
Referenced by smtrat::IntBlastModule< Settings >::blastConstrTree(), and delta::Producer::Producer().
NodeChangeSet delta::letExpression (const Node & n)
Node operator that eliminated let expressions.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 152 of file operators.h.
Referenced by delta::Producer::Producer().
NodeChangeSet delta::mergeChild (const Node & n)
Node operator that merges nodes with one of its own children.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 63 of file operators.h.
Referenced by delta::Producer::Producer().
NodeChangeSet delta::number (const Node & n)
Node operator that provides meaningful replacements for numbers.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 87 of file operators.h.
Referenced by delta::Producer::Producer().