SMT-RAT: Minisat Namespace Reference
Minisat Namespace Reference
Data Structures
class RegionAllocator
class Heap
struct Hash
struct Equal
struct DeepHash
struct DeepEqual
class Map
class Option
struct IntRange
struct Int64Range
struct DoubleRange
class DoubleOption
class IntOption
class StringOption
class BoolOption
class Queue
struct Lit
class lbool
class Clause
class ClauseAllocator
class OccLists
class CMap
struct LessThan_default
class vec
class OutOfMemoryException
Typedefs
typedef int Var
typedef RegionAllocator
< uint32_t >::Ref CRef
Functions
template<class V , class T >
static void remove (V &ts, const T &t)
template<class V , class T >
static bool find (V &ts, const T &t)
template<class T >
static void copy (const T &from, T &to)
template<class T >
static void copy (const vec< T > &from, vec< T > &to, bool append=false)
template<class T >
static void append (const vec< T > &from, vec< T > &to)
static uint32_t hash (uint32_t x)
static uint32_t hash (uint64_t x)
static uint32_t hash (int32_t x)
static uint32_t hash (int64_t x)
void printUsageAndExit (int argc, char **argv, bool verbose=false)
void setUsageHelp (const char *str)
void setHelpPrefixStr (const char *str)
Lit mkLit (Var var, bool sign=false)
Lit operator~ (Lit p)
Lit operator^ (Lit p, bool b)
bool sign (Lit p)
int var (Lit p)
Lit neg (Lit p)
int toInt (Var v)
int toInt (Lit p)
Lit toLit (int i)
int toInt (lbool l)
lbool toLbool (int v)
template<class T , class LessThan >
void selectionSort (T *array, int size, LessThan lt)
template<class T >
static void selectionSort (T *array, int size)
template<class T , class LessThan >
void sort (T *array, int size, LessThan lt)
template<class T >
static void sort (T *array, int size)
template<class T , class LessThan >
void sort (vec< T > &v, LessThan lt)
template<class T >
void sort (vec< T > &v)
static void * xrealloc (void *ptr, size_t size)
Variables
static const int nprimes
static const int primes [nprimes]
const Lit lit_Undef
const Lit lit_Error
static const unsigned NORMAL_CLAUSE
static const unsigned LEMMA_CLAUSE
static const unsigned CONFLICT_CLAUSE
static const unsigned PERMANENT_CLAUSE
const CRef CRef_Undef
const CRef CRef_Lazy
Typedef Documentation
typedef RegionAllocator<uint32_t>::Ref Minisat::CRef
Definition at line 123 of file SolverTypes.h.
typedef int Minisat::Var
Definition at line 42 of file SolverTypes.h.
Function Documentation
template<class T > static void Minisat::append (const vec< T > & from, vec< T > & to) inline static
Definition at line 79 of file Alg.h.
Referenced by copy().
template<class T > static void Minisat::copy (const T & from, T & to) inline static
Definition at line 60 of file Alg.h.
Referenced by append(), copy(), smtrat::JunctorMerger::P_merge(), and smtrat::select_best().
template<class T > static void Minisat::copy (const vec< T > & from, vec< T > & to, bool append = false) inline static
Definition at line 67 of file Alg.h.
template<class V , class T > static bool Minisat::find (V & ts, const T & t) inline static
Definition at line 47 of file Alg.h.
Referenced by smtrat::VariantMap< std::string, Value >::assertType(), smtrat::Module::excludeNotReceivedVariablesFromModel(), smtrat::PriorityQueue< QueueEntry, ProjectionCandidateComparator >::find(), smtrat::VariantMap< std::string, Value >::get(), smtrat::VariantMap< std::string, Value >::has(), smtrat::cad::Projection< Incrementality::NONE, Backtracking::ORDERED, Settings >::insertPolynomial(), smtrat::parser::ErrorHandler::operator()(), rewriter::ErrorHandler::operator()(), delta::ErrorHandler::operator()(), smtrat::Module::originInReceivedFormula(), smtrat::EQModule< Settings >::P_remove_ineq_edge(), smtrat::dynarray< smtrat::EQModule::implicit_edge_info * >::remove(), smtrat::CADModule< Settings >::removeCore(), smtrat::SATModule< Settings >::LiteralClauses::removeNegative(), smtrat::SATModule< Settings >::ClauseInformation::removeOrigin(), smtrat::ModuleInput::removeOrigins(), smtrat::SATModule< Settings >::LiteralClauses::removePositive(), smtrat::SATModule< Settings >::resetVariableAssignment(), smtrat::ReplaceVariablesRewriter::rewrite_ueq(), smtrat::CADModule< Settings >::updateModel(), and smtrat::IncWidthModule< Settings >::useInfSubsetIfNoAddedBoundsAreContained().
static uint32_t Minisat::hash (uint32_t x) inline static
Definition at line 32 of file Map.h.
Referenced by Minisat::Hash< K >::operator()(), and Minisat::DeepHash< K >::operator()().
static uint32_t Minisat::hash (uint64_t x) inline static
Definition at line 33 of file Map.h.
static uint32_t Minisat::hash (int32_t x) inline static
Definition at line 34 of file Map.h.
static uint32_t Minisat::hash (int64_t x) inline static
Definition at line 35 of file Map.h.
Lit Minisat::mkLit (Var var, bool sign = false) inline
Definition at line 60 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::bestBranchLit(), smtrat::SATModule< Settings >::checkCore(), smtrat::SATModule< Settings >::computeAdvancedLemmas(), smtrat::SATModule< Settings >::createLiteral(), smtrat::SATModule< Settings >::getLiteral(), neg(), smtrat::SATModule< Settings >::newVar(), smtrat::SATModule< Settings >::pickBranchLit(), smtrat::SATModule< Settings >::reason(), smtrat::SATModule< Settings >::relocAll(), smtrat::SATModule< Settings >::resetVariableAssignment(), smtrat::SATModule< Settings >::SATModule(), smtrat::SATModule< Settings >::uncheckedEnqueue(), and smtrat::SATModule< Settings >::updateAllModels().
Lit Minisat::neg (Lit p) inline
Definition at line 65 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::addClauses(), smtrat::SATModule< Settings >::getLiteral(), smtrat::SATModule< Settings >::learnTheoryConflicts(), smtrat::SATModule< Settings >::propagateTheory(), smtrat::SATModule< Settings >::reason(), and smtrat::SATModule< Settings >::search().
Lit Minisat::operator^ (Lit p, bool b) inline
Definition at line 62 of file SolverTypes.h.
Lit Minisat::operator~ (Lit p) inline
Definition at line 61 of file SolverTypes.h.
void Minisat::printUsageAndExit (int argc, char ** argv, bool verbose = false)
Definition at line 35 of file Options.cpp.
template<class V , class T > static void Minisat::remove (V & ts, const T & t) inline static
Definition at line 36 of file Alg.h.
Referenced by benchmax::Stats::callComposeProcessor(), benchmax::Stats::composeStats(), smtrat::SATModule< Settings >::detachClause(), initApplication(), and delta::TempFilenameGenerator::~TempFilenameGenerator().
template<class T , class LessThan > void Minisat::selectionSort (T * array, int size, LessThan lt)
Definition at line 41 of file Sort.h.
Referenced by selectionSort(), and sort().
template<class T > static void Minisat::selectionSort (T * array, int size) inline static
Definition at line 61 of file Sort.h.
void Minisat::setHelpPrefixStr (const char * str)
Definition at line 30 of file Options.cpp.
void Minisat::setUsageHelp (const char * str)
Definition at line 25 of file Options.cpp.
bool Minisat::sign (Lit p) inline
Definition at line 63 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::attachClause(), smtrat::SATModule< Settings >::cancelAssignmentUntil(), smtrat::IntEqModule< Settings >::checkCore(), smtrat::SATModule< Settings >::createLiteral(), smtrat::SATModule< Settings >::detachClause(), neg(), smtrat::SATModule< Settings >::removeLiteralOrigin(), smtrat::SATModule< Settings >::resetVariableAssignment(), smtrat::SATModule< Settings >::search(), smtrat::SATModule< Settings >::toString(), smtrat::SATModule< Settings >::uncheckedEnqueue(), and smtrat::SATModule< Settings >::value().
template<class T , class LessThan > void Minisat::sort (T * array, int size, LessThan lt)
Definition at line 67 of file Sort.h.
Referenced by smtrat::SATModule< Settings >::addClause(), smtrat::cad::LiftingTree< Settings >::insertRootSamples(), smtrat::cad::Origin::makeUnique(), smtrat::expression::NaryExpression::normalize(), printUsageAndExit(), smtrat::RootIndexer::process(), smtrat::SATModule< Settings >::reason(), smtrat::SATModule< Settings >::reduceDB(), smtrat::cad::debug::TikzTreePrinter::reorderTree(), smtrat::select_best(), sort(), and smtrat::SATModule< Settings >::storeLemmas().
template<class T > static void Minisat::sort (T * array, int size) inline static
Definition at line 102 of file Sort.h.
template<class T , class LessThan > void Minisat::sort (vec< T > & v, LessThan lt)
Definition at line 111 of file Sort.h.
template<class T > void Minisat::sort (vec< T > & v)
Definition at line 117 of file Sort.h.
int Minisat::toInt (Var v) inline
Definition at line 68 of file SolverTypes.h.
Referenced by Minisat::OccLists< Idx, Vec, Deleted >::clean(), Minisat::OccLists< Idx, Vec, Deleted >::cleanAll(), Minisat::OccLists< Minisat::Lit, Minisat::vec< smtrat::SATModule::Watcher >, smtrat::SATModule::WatcherDeleted >::init(), Minisat::OccLists< Minisat::Lit, Minisat::vec< smtrat::SATModule::Watcher >, smtrat::SATModule::WatcherDeleted >::lookup(), Minisat::OccLists< Minisat::Lit, Minisat::vec< smtrat::SATModule::Watcher >, smtrat::SATModule::WatcherDeleted >::operator[](), Minisat::OccLists< Minisat::Lit, Minisat::vec< smtrat::SATModule::Watcher >, smtrat::SATModule::WatcherDeleted >::smudge(), smtrat::SATModule< Settings >::uncheckedEnqueue(), and smtrat::SATModule< Settings >::updateCNFInfoCounter().
int Minisat::toInt (Lit p) inline
Definition at line 69 of file SolverTypes.h.
int Minisat::toInt (lbool l) inline
Definition at line 117 of file SolverTypes.h.
lbool Minisat::toLbool (int v) inline
Definition at line 118 of file SolverTypes.h.
Lit Minisat::toLit (int i) inline
Definition at line 70 of file SolverTypes.h.
int Minisat::var (Lit p) inline
Definition at line 64 of file SolverTypes.h.
Referenced by smtrat::LRAModule< Settings >::activateBound(), smtrat::SATModule< Settings >::adaptConflictEvaluation(), smtrat::Module::add(), smtrat::Module::addAssumptionToCheck(), smtrat::SATModule< Settings >::addClause(), smtrat::SATModule< Settings >::addClauses(), smtrat::ICPModule< Settings >::addConstraint(), smtrat::CubeLIAModule< Settings >::addCore(), smtrat::VSModule< Settings >::addCore(), smtrat::ICPModule< Settings >::addCore(), smtrat::SATModule< Settings >::addCore(), smtrat::BoolUEQRewriter::addDomainConstraints(), smtrat::SATModule< Settings >::analyze(), smtrat::AnnotatedBVTerm::AnnotatedBVTerm(), smtrat::MCBModule< Settings >::applyReplacements(), smtrat::SATModule< Settings >::attachClause(), vs::State::averageConstraintValuation(), vs::State::bestConstraintValuation(), Minisat::Clause::calcAbstraction(), smtrat::SATModule< Settings >::cancelAssignmentUntil(), smtrat::ICPModule< Settings >::checkBoxAgainstLinearFeasibleRegion(), smtrat::IncWidthModule< Settings >::checkCore(), smtrat::IntEqModule< Settings >::checkCore(), smtrat::MCBModule< Settings >::collectChoices(), smtrat::PFEModule< Settings >::completeBounds(), smtrat::BVDirectEncoder::createBits(), smtrat::ICPModule< Settings >::createLinearCCs(), smtrat::SATModule< Settings >::createLiteral(), smtrat::ICPModule< Settings >::createNonlinearCCs(), smtrat::BVDirectEncoder::createVariable(), smtrat::parser::ArithmeticTheory::declareVariable(), smtrat::parser::CoreTheory::declareVariable(), smtrat::parser::Theories::declareVariable(), smtrat::SATModule< Settings >::detachClause(), smtrat::ExplanationGenerator::generateExplanation(), smtrat::WrapperExternal::getModelEqualities(), smtrat::LRAModule< Settings >::getVariableBounds(), smtrat::parser::UninterpretedTheory::handleFunctionInstantiation(), smtrat::parser::BitvectorTheory::handleITE(), vs::State::initIndex(), smtrat::SATModule< Settings >::level(), smtrat::SATModule< Settings >::litRedundant(), smtrat::SATModule< Settings >::locked(), smtrat::LRAModule< Settings >::mostInfeasibleVar(), neg(), std::hash< boost::variant< BOOST_VARIANT_ENUM_PARAMS(Args)> >::operator()(), std::hash< const boost::variant< BOOST_VARIANT_ENUM_PARAMS(Args)> >::operator()(), smtrat::SATModule< Settings >::lemma_lt::operator()(), smtrat::EQModule< Settings >::P_add_function_instance(), smtrat::CollectBoolsInUEQs::P_handle_arg(), smtrat::EQPreprocessingModule< Settings >::P_update_model(), smtrat::EQModule< Settings >::P_update_model_function(), smtrat::SATModule< Settings >::pickBranchLit(), smtrat::SATModule< Settings >::propagateTheory(), smtrat::SATModule< Settings >::reason(), smtrat::SATModule< Settings >::relocAll(), smtrat::Module::remove(), smtrat::SATModule< Settings >::removeClause(), smtrat::ICPModule< Settings >::removeCore(), smtrat::LRAModule< Settings >::removeCore(), smtrat::SATModule< Settings >::removeLiteralOrigin(), smtrat::SATModule< Settings >::removeTheoryPropagation(), smtrat::SATModule< Settings >::resetVariableAssignment(), smtrat::SATModule< Settings >::search(), smtrat::VSModule< Settings >::solutionInDomain(), smtrat::SATModule< Settings >::storeLemmas(), smtrat::VSModule< Settings >::substituteAll(), smtrat::SATModule< Settings >::toString(), smtrat::SATModule< Settings >::trailIndex(), smtrat::BVModule< Settings >::transferBackendModel(), smtrat::GBModule< Settings >::transformIntoEquality(), smtrat::IncWidthModule< Settings >::tryToAddBounds(), smtrat::SATModule< Settings >::uncheckedEnqueue(), smtrat::ESModule< Settings >::updateModel(), smtrat::VSModule< Settings >::updateModel(), smtrat::SATModule< Settings >::updateModel(), smtrat::SATModule< Settings >::value(), and vs::State::worstConstraintValuation().
static void* Minisat::xrealloc (void * ptr, size_t size) inline static
Definition at line 32 of file XAlloc.h.
Referenced by Minisat::RegionAllocator< T >::capacity().
Variable Documentation
const unsigned Minisat::CONFLICT_CLAUSE static
Definition at line 128 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::handleConflict(), and smtrat::SATModule< Settings >::learnTheoryConflicts().
const CRef Minisat::CRef_Lazy
Definition at line 218 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::expPositionsCorrect(), smtrat::SATModule< Settings >::propagateTheory(), and smtrat::SATModule< Settings >::reason().
const CRef Minisat::CRef_Undef
Definition at line 217 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::addClause(), smtrat::SATModule< Settings >::analyze(), smtrat::SATModule< Settings >::cancelAssignmentUntil(), smtrat::SATModule< Settings >::checkCore(), smtrat::SATModule< Settings >::handleConflict(), smtrat::SATModule< Settings >::litRedundant(), smtrat::SATModule< Settings >::locked(), smtrat::SATModule< Settings >::newVar(), smtrat::SATModule< Settings >::propagate(), smtrat::SATModule< Settings >::propagateConsistently(), smtrat::SATModule< Settings >::relocAll(), smtrat::SATModule< Settings >::removeClause(), smtrat::SATModule< Settings >::removeCore(), smtrat::SATModule< Settings >::search(), smtrat::SATModule< Settings >::simplify(), smtrat::SATModule< Settings >::storeLemmas(), smtrat::SATModule< Settings >::uncheckedEnqueue(), and smtrat::SATModule< Settings >::updateCNFInfoCounter().
const unsigned Minisat::LEMMA_CLAUSE static
Definition at line 127 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::processLemmas(), smtrat::SATModule< Settings >::propagateTheory(), smtrat::SATModule< Settings >::reason(), and smtrat::SATModule< Settings >::search().
const Lit Minisat::lit_Error
Definition at line 76 of file SolverTypes.h.
Referenced by Minisat::Clause::subsumes().
const Lit Minisat::lit_Undef
Definition at line 75 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::addClause(), smtrat::SATModule< Settings >::addClauses(), smtrat::SATModule< Settings >::analyze(), smtrat::SATModule< Settings >::bestBranchLit(), smtrat::SATModule< Settings >::createLiteral(), smtrat::SATModule< Settings >::pickBranchLit(), smtrat::SATModule< Settings >::reason(), smtrat::SATModule< Settings >::search(), and Minisat::Clause::subsumes().
const unsigned Minisat::NORMAL_CLAUSE static
Definition at line 126 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::addClause(), smtrat::SATModule< Settings >::addClause_(), smtrat::SATModule< Settings >::addClauses(), smtrat::SATModule< Settings >::addCore(), Minisat::ClauseAllocator::alloc(), Minisat::Clause::learnt(), and Minisat::Clause::subsumes().
const int Minisat::nprimes static
Definition at line 49 of file Map.h.
Referenced by Minisat::Map< CRef, T, CRefHash >::rehash().
const unsigned Minisat::PERMANENT_CLAUSE static
Definition at line 129 of file SolverTypes.h.
Referenced by smtrat::SATModule< Settings >::checkCore(), smtrat::SATModule< Settings >::learnTheoryConflicts(), smtrat::SATModule< Settings >::processLemmas(), smtrat::SATModule< Settings >::reduceDB(), and smtrat::SATModule< Settings >::updateAllModels().
const int Minisat::primes[nprimes] static
Definition at line 50 of file Map.h.
Referenced by Minisat::Map< CRef, T, CRefHash >::rehash().