SMT-RAT: smtrat::lra Namespace Reference
smtrat::lra Namespace Reference
Data Structures
class Variable
class Bound
Stores a bound, which could be an upper "<= b" or a lower bound ">= b" for a bound value b.
class Numeric
class TableauEntry
class Tableau
struct TableauSettings1
struct TableauSettings2
struct TableauSettings3
class Value
Typedefs
typedef size_t EntryID
Enumerations
enum NBCS : unsigned { NBCS::LESS_BOUNDED_VARIABLES, NBCS::LESS_COLUMN_ENTRIES }
Functions
Numeric abs (const Numeric &_value)
Calculates the absolute value of the given Numeric.
Numeric mod (const Numeric &_valueA, const Numeric &_valueB)
Calculates the result of the first argument modulo the second argument.
Numeric lcm (const Numeric &_valueA, const Numeric &_valueB)
Calculates the least common multiple of the two arguments.
Numeric gcd (const Numeric &_valueA, const Numeric &_valueB)
Calculates the greatest common divisor of the two arguments.
Numeric operator+ (const Numeric &_valueA, const Numeric &_valueB)
Calculates the sum of the two given Numerics.
Numeric operator- (const Numeric &_valueA, const Numeric &_valueB)
Calculates the difference between the two given Numerics.
Numeric operator* (const Numeric &_valueA, const Numeric &_valueB)
Calculates the product of the two given Numerics.
Numeric operator/ (const Numeric &_valueA, const Numeric &_valueB)
Calculates the division of the two given Numerics.
Numeric & operator+= (Numeric &_valueA, const Numeric &_valueB)
Adds the value of the second given Numeric to the second given Numeric.
Numeric & operator-= (Numeric &_valueA, const Numeric &_valueB)
Subtracts the second given Numeric to the first given Numeric.
Numeric & operator*= (Numeric &_valueA, const Numeric &_valueB)
Multiplies the second given Numeric to the first given Numeric.
Numeric & operator/= (Numeric &_valueA, const Numeric &_valueB)
Divides the first given Numeric by the second given Numeric.
Numeric operator- (const Numeric &_value)
Calculates the additive inverse of the given Numeric.
Numeric & operator++ (Numeric &_value)
Increments the given Numeric by one.
Numeric & operator-- (Numeric &_value)
Decrements the given Numeric by one.
ostream & operator<< (ostream &_out, const Numeric &_value)
Prints the given Numerics representation on the given output stream.
Variables
static EntryID LAST_ENTRY_ID
Typedef Documentation
typedef size_t smtrat::lra::EntryID
Definition at line 23 of file Variable.h.
Enumeration Type Documentation
enum smtrat::lra::NBCS : unsigned strong
Enumerator
LESS_BOUNDED_VARIABLES
LESS_COLUMN_ENTRIES
Definition at line 16 of file TableauSettings.h.
Function Documentation
Numeric smtrat::lra::abs (const Numeric & _value)
Calculates the absolute value of the given Numeric.
Parameters
_value The Numeric to calculate the Numeric for.
Returns
The absolute value of the given Numeric.
Definition at line 279 of file Numeric.cpp.
Referenced by smtrat::CubeLIAModule< Settings >::addCore(), smtrat::IntEqModule< Settings >::checkCore(), smtrat::LRAModule< Settings >::mostInfeasibleVar(), and smtrat::LRAModule< Settings >::optimize().
Numeric smtrat::lra::gcd (const Numeric & _valueA, const Numeric & _valueB)
Calculates the greatest common divisor of the two arguments.
Note, that this method can only be applied to integers.
Parameters
_valueA An integer.
_valueB An integer.
Returns
The least common divisor of the two arguments.
Definition at line 320 of file Numeric.cpp.
Numeric smtrat::lra::lcm (const Numeric & _valueA, const Numeric & _valueB)
Calculates the least common multiple of the two arguments.
Note, that this method can only be applied to integers.
Parameters
_valueA An integer.
_valueB An integer.
Returns
The least common multiple of the two arguments.
Definition at line 305 of file Numeric.cpp.
Numeric smtrat::lra::mod (const Numeric & _valueA, const Numeric & _valueB)
Calculates the result of the first argument modulo the second argument.
Note, that this method can only be applied to integers.
Parameters
_valueA An integer.
_valueB An integer != 0.
Returns
The first argument modulo the second argument.
Definition at line 291 of file Numeric.cpp.
Referenced by smtrat::parser::ArithmeticTheory::functionCall(), smtrat::parser::conversion::Converter< types::BVTerm >::operator()(), and smtrat::VSModule< Settings >::solutionInDomain().
Numeric smtrat::lra::operator* (const Numeric & _valueA, const Numeric & _valueB)
Calculates the product of the two given Numerics.
Parameters
_valueA The first factor.
_valueB The second factor.
Returns
The product of the two given Numerics.
Definition at line 356 of file Numeric.cpp.
Numeric & smtrat::lra::operator*= (Numeric & _valueA, const Numeric & _valueB)
Multiplies the second given Numeric to the first given Numeric.
Parameters
_valueA The Numeric to multiply.
_valueB The Numeric to multiply by.
Returns
The first given Numeric multiplied by the second given Numeric.
Definition at line 402 of file Numeric.cpp.
Numeric smtrat::lra::operator+ (const Numeric & _valueA, const Numeric & _valueB)
Calculates the sum of the two given Numerics.
Parameters
_valueA The first summand.
_valueB The second summand.
Returns
The sum of the two given Numerics.
Definition at line 334 of file Numeric.cpp.
Numeric & smtrat::lra::operator++ (Numeric & _value)
Increments the given Numeric by one.
Parameters
_value The Numeric to increment.
Returns
The given Numeric incremented by one.
Definition at line 435 of file Numeric.cpp.
Numeric & smtrat::lra::operator+= (Numeric & _valueA, const Numeric & _valueB)
Adds the value of the second given Numeric to the second given Numeric.
Parameters
_valueA The Numeric to add to.
_valueB The Numeric to add.
Returns
The first given Numeric increased by the second given Numeric.
Definition at line 378 of file Numeric.cpp.
Numeric smtrat::lra::operator- (const Numeric & _valueA, const Numeric & _valueB)
Calculates the difference between the two given Numerics.
Parameters
_valueA The minuend.
_valueB The subtrahend.
Returns
The difference between the two given Numerics.
Definition at line 345 of file Numeric.cpp.
Numeric smtrat::lra::operator- (const Numeric & _value)
Calculates the additive inverse of the given Numeric.
Parameters
_value The Numeric to calculate the additive inverse for.
Returns
The additive inverse of the given Numeric.
Definition at line 425 of file Numeric.cpp.
Numeric & smtrat::lra::operator-- (Numeric & _value)
Decrements the given Numeric by one.
Parameters
_value The Numeric to decrement.
Returns
The given Numeric decremented by one.
Definition at line 446 of file Numeric.cpp.
Numeric & smtrat::lra::operator-= (Numeric & _valueA, const Numeric & _valueB)
Subtracts the second given Numeric to the first given Numeric.
Parameters
_valueA The Numeric to subtract from.
_valueB The Numeric to subtract.
Returns
The first given Numeric subtracted by the second given Numeric.
Definition at line 390 of file Numeric.cpp.
Numeric smtrat::lra::operator/ (const Numeric & _valueA, const Numeric & _valueB)
Calculates the division of the two given Numerics.
Parameters
_valueA The dividend.
_valueB The divisor.
Returns
The difference of the two given Numerics.
Definition at line 367 of file Numeric.cpp.
Numeric & smtrat::lra::operator/= (Numeric & _valueA, const Numeric & _valueB)
Divides the first given Numeric by the second given Numeric.
Parameters
_valueA The Numeric to divide.
_valueB The Numeric to divide by.
Returns
The first given Numeric divided by the second given Numeric.
Definition at line 414 of file Numeric.cpp.
std::ostream & smtrat::lra::operator<< (ostream & _out, const Numeric & _value)
Prints the given Numerics representation on the given output stream.
Parameters
_out The output stream to print on.
_value The Numeric to print.
Returns
The output stream after printing the given Numerics representation on it.
Definition at line 458 of file Numeric.cpp.
Variable Documentation
EntryID smtrat::lra::LAST_ENTRY_ID static
Definition at line 25 of file Variable.h.
Referenced by smtrat::LRAModule< Settings >::checkCore(), smtrat::lra::Tableau< Settings, T1, T2 >::Iterator::hEnd(), smtrat::LRAModule< Settings >::optimize(), and smtrat::lra::Tableau< Settings, T1, T2 >::Iterator::vEnd().