SMT-RAT: smtrat-modules/LRAModule/tableau/Numeric.h File Reference
Numeric.h File Reference
#include <iostream>
#include <cassert>
#include <smtrat-common/smtrat-common.h>
Data Structures
class smtrat::lra::Numeric
Namespaces
smtrat
smtrat is the main namespace for the library.
Functions
Numeric smtrat::lra::abs (const Numeric &_value)
Calculates the absolute value of the given Numeric.
Numeric smtrat::lra::mod (const Numeric &_valueA, const Numeric &_valueB)
Calculates the result of the first argument modulo the second argument.
Numeric smtrat::lra::lcm (const Numeric &_valueA, const Numeric &_valueB)
Calculates the least common multiple of the two arguments.
Numeric smtrat::lra::gcd (const Numeric &_valueA, const Numeric &_valueB)
Calculates the greatest common divisor of the two arguments.
Numeric smtrat::lra::operator+ (const Numeric &_valueA, const Numeric &_valueB)
Calculates the sum of the two given Numerics.
Numeric smtrat::lra::operator- (const Numeric &_valueA, const Numeric &_valueB)
Calculates the difference between the two given Numerics.
Numeric smtrat::lra::operator* (const Numeric &_valueA, const Numeric &_valueB)
Calculates the product of the two given Numerics.
Numeric smtrat::lra::operator/ (const Numeric &_valueA, const Numeric &_valueB)
Calculates the division of the two given Numerics.
Numeric & smtrat::lra::operator+= (Numeric &_valueA, const Numeric &_valueB)
Adds the value of the second given Numeric to the second given Numeric.
Numeric & smtrat::lra::operator-= (Numeric &_valueA, const Numeric &_valueB)
Subtracts the second given Numeric to the first given Numeric.
Numeric & smtrat::lra::operator*= (Numeric &_valueA, const Numeric &_valueB)
Multiplies the second given Numeric to the first given Numeric.
Numeric & smtrat::lra::operator/= (Numeric &_valueA, const Numeric &_valueB)
Divides the first given Numeric by the second given Numeric.
Numeric smtrat::lra::operator- (const Numeric &_value)
Calculates the additive inverse of the given Numeric.
Numeric & smtrat::lra::operator++ (Numeric &_value)
Increments the given Numeric by one.
Numeric & smtrat::lra::operator-- (Numeric &_value)
Decrements the given Numeric by one.
std::ostream & smtrat::lra::operator<< (std::ostream &_out, const Numeric &_value)
Prints the given Numerics representation on the given output stream.
Detailed Description
Author
Florian Corzilius corzi.nosp@m.lius.nosp@m.@cs.r.nosp@m.wth-.nosp@m.aache.nosp@m.n.de
Version
2013-04-15 Created on April 15th, 2013
Definition in file Numeric.h.
Function Documentation
abs()
Numeric smtrat::lra::abs (const Numeric & _value)
Calculates the absolute value of the given Numeric.
Parameters
_value The Numeric to calculate the Numeric for.
Returns
The absolute value of the given Numeric.
Definition at line 276 of file Numeric.cpp.
Referenced by smtrat::lra::abs().
gcd()
Numeric smtrat::lra::gcd (const Numeric & _valueA, const Numeric & _valueB)
Calculates the greatest common divisor of the two arguments.
Note, that this method can only be applied to integers.
Parameters
_valueA An integer.
_valueB An integer.
Returns
The least common divisor of the two arguments.
Definition at line 317 of file Numeric.cpp.
Referenced by smtrat::lra::gcd().
lcm()
Numeric smtrat::lra::lcm (const Numeric & _valueA, const Numeric & _valueB)
Calculates the least common multiple of the two arguments.
Note, that this method can only be applied to integers.
Parameters
_valueA An integer.
_valueB An integer.
Returns
The least common multiple of the two arguments.
Definition at line 302 of file Numeric.cpp.
Referenced by smtrat::lra::lcm().
mod()
Numeric smtrat::lra::mod (const Numeric & _valueA, const Numeric & _valueB)
Calculates the result of the first argument modulo the second argument.
Note, that this method can only be applied to integers.
Parameters
_valueA An integer.
_valueB An integer != 0.
Returns
The first argument modulo the second argument.
Definition at line 288 of file Numeric.cpp.
Referenced by smtrat::lra::mod().
operator*()
Numeric smtrat::lra::operator* (const Numeric & _valueA, const Numeric & _valueB)
Calculates the product of the two given Numerics.
Parameters
_valueA The first factor.
_valueB The second factor.
Returns
The product of the two given Numerics.
Definition at line 353 of file Numeric.cpp.
Referenced by smtrat::lra::operator*().
operator*=()
Numeric & smtrat::lra::operator*= (Numeric & _valueA, const Numeric & _valueB)
Multiplies the second given Numeric to the first given Numeric.
Parameters
_valueA The Numeric to multiply.
_valueB The Numeric to multiply by.
Returns
The first given Numeric multiplied by the second given Numeric.
Definition at line 399 of file Numeric.cpp.
Referenced by smtrat::lra::operator*=().
operator+()
Numeric smtrat::lra::operator+ (const Numeric & _valueA, const Numeric & _valueB)
Calculates the sum of the two given Numerics.
Parameters
_valueA The first summand.
_valueB The second summand.
Returns
The sum of the two given Numerics.
Definition at line 331 of file Numeric.cpp.
Referenced by smtrat::lra::operator+().
operator++()
Numeric & smtrat::lra::operator++ (Numeric & _value)
Increments the given Numeric by one.
Parameters
_value The Numeric to increment.
Returns
The given Numeric incremented by one.
Definition at line 432 of file Numeric.cpp.
Referenced by smtrat::lra::operator++().
operator+=()
Numeric & smtrat::lra::operator+= (Numeric & _valueA, const Numeric & _valueB)
Adds the value of the second given Numeric to the second given Numeric.
Parameters
_valueA The Numeric to add to.
_valueB The Numeric to add.
Returns
The first given Numeric increased by the second given Numeric.
Definition at line 375 of file Numeric.cpp.
Referenced by smtrat::lra::operator+=().
operator-() [1/2]
Numeric smtrat::lra::operator- (const Numeric & _valueA, const Numeric & _valueB)
Calculates the difference between the two given Numerics.
Parameters
_valueA The minuend.
_valueB The subtrahend.
Returns
The difference between the two given Numerics.
Definition at line 342 of file Numeric.cpp.
Referenced by smtrat::lra::operator-().
operator-() [2/2]
Numeric smtrat::lra::operator- (const Numeric & _value)
Calculates the additive inverse of the given Numeric.
Parameters
_value The Numeric to calculate the additive inverse for.
Returns
The additive inverse of the given Numeric.
Definition at line 422 of file Numeric.cpp.
operator--()
Numeric & smtrat::lra::operator-- (Numeric & _value)
Decrements the given Numeric by one.
Parameters
_value The Numeric to decrement.
Returns
The given Numeric decremented by one.
Definition at line 443 of file Numeric.cpp.
Referenced by smtrat::lra::operator--().
operator-=()
Numeric & smtrat::lra::operator-= (Numeric & _valueA, const Numeric & _valueB)
Subtracts the second given Numeric to the first given Numeric.
Parameters
_valueA The Numeric to subtract from.
_valueB The Numeric to subtract.
Returns
The first given Numeric subtracted by the second given Numeric.
Definition at line 387 of file Numeric.cpp.
Referenced by smtrat::lra::operator-=().
operator/()
Numeric smtrat::lra::operator/ (const Numeric & _valueA, const Numeric & _valueB)
Calculates the division of the two given Numerics.
Parameters
_valueA The dividend.
_valueB The divisor.
Returns
The difference of the two given Numerics.
Definition at line 364 of file Numeric.cpp.
Referenced by smtrat::lra::operator/().
operator/=()
Numeric & smtrat::lra::operator/= (Numeric & _valueA, const Numeric & _valueB)
Divides the first given Numeric by the second given Numeric.
Parameters
_valueA The Numeric to divide.
_valueB The Numeric to divide by.
Returns
The first given Numeric divided by the second given Numeric.
Definition at line 411 of file Numeric.cpp.
Referenced by smtrat::lra::operator/=().
operator<<()
std::ostream & smtrat::lra::operator<< (std::ostream & _out, const Numeric & _value)
Prints the given Numerics representation on the given output stream.
Parameters
_out The output stream to print on.
_value The Numeric to print.
Returns
The output stream after printing the given Numerics representation on it.
Definition at line 455 of file Numeric.cpp.