SMT-RAT: smtrat-mcsat/explanations/onecellcad/OneCellCAD.h File Reference
OneCellCAD.h File Reference
Construct a single open CAD Cell around a given point that is sign-invariant on a given set of polynomials.
#include <carl/core/polynomialfunctions/Derivative.h>
#include <carl/core/polynomialfunctions/Factorization.h>
#include <carl/core/polynomialfunctions/Resultant.h>
#include <smtrat-common/smtrat-common.h>
#include <smtrat-common/model.h>
#include <smtrat-cad/projectionoperator/utils.h>
#include "Assertables.h"
#include <algorithm>
#include <optional>
#include <set>
#include <unordered_map>
#include <variant>
#include <vector>
#include <carl/formula/model/ran/RealAlgebraicNumberIntervalExtra.h>
Data Structures
struct smtrat::mcsat::onecellcad::TagPoly2
struct smtrat::mcsat::onecellcad::TagPoly
struct smtrat::mcsat::onecellcad::Section
Represent a cell's (closed-interval-boundary) component along th k-th axis.
struct smtrat::mcsat::onecellcad::Sector
Represent a cell's open-interval boundary object along one single axis by two irreducible, multivariate polynomials of level k.
class smtrat::mcsat::onecellcad::OneCellCAD
Namespaces
smtrat
smtrat is the main namespace for the library.
Typedefs
using smtrat::mcsat::onecellcad::RAN = carl::RealAlgebraicNumber< smtrat::Rational >
using smtrat::mcsat::onecellcad::RANMap = std::map< carl::Variable, RAN >
using smtrat::mcsat::onecellcad::CADCell = std::vector< std::variant< Sector, Section > >
Represent a single cell [brown15].
Enumerations
enum InvarianceType { ORD_INV, SIGN_INV }
enum ShrinkResult { SUCCESS, FAIL }
Functions
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const InvarianceType &inv)
bool smtrat::mcsat::onecellcad::operator< (const InvarianceType &l, const InvarianceType &r)
SIGN_INV < ORD_INV, since order invariance is a "stronger" property.
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const ShrinkResult &s)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const TagPoly2 &p)
bool smtrat::mcsat::onecellcad::operator== (const TagPoly2 &lhs, const TagPoly2 &rhs)
bool smtrat::mcsat::onecellcad::operator== (const TagPoly &lhs, const TagPoly &rhs)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const TagPoly &p)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const std::vector< TagPoly > &polys)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const std::vector< TagPoly2 > &polys)
std::vector< Poly > smtrat::mcsat::onecellcad::asMultiPolys (const std::vector< TagPoly2 > polys)
std::vector< Poly > smtrat::mcsat::onecellcad::asMultiPolys (const std::vector< TagPoly > polys)
bool smtrat::mcsat::onecellcad::contains (const std::vector< TagPoly2 > &polys, const Poly &poly)
bool smtrat::mcsat::onecellcad::contains (const std::vector< TagPoly > &polys, const Poly &poly)
template<typename T >
bool smtrat::mcsat::onecellcad::contains (const std::vector< T > &list, const T &elem)
MultivariateRootT smtrat::mcsat::onecellcad::asRootExpr (carl::Variable rootVariable, Poly poly, std::size_t rootIdx)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const Section &s)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const Sector &s)
std::ostream & smtrat::mcsat::onecellcad::operator<< (std::ostream &os, const CADCell &cell)
std::size_t smtrat::mcsat::onecellcad::cellDimension (const CADCell &cell, const std::size_t uptoLevel)
std::optional< std::size_t > smtrat::mcsat::onecellcad::levelOf (const std::vector< carl::Variable > &variableOrder, const Poly &poly)
Find the index of the highest variable (wrt.
CADCell smtrat::mcsat::onecellcad::fullSpaceCell (std::size_t cellComponentCount)
std::vector< TagPoly > smtrat::mcsat::onecellcad::singleLevelFullProjection (carl::Variable mainVar, carl::Variable sndMainVar, std::vector< TagPoly > polys)
std::vector< TagPoly > smtrat::mcsat::onecellcad::nonConstIrreducibleFactors (std::vector< TagPoly > polys)
void smtrat::mcsat::onecellcad::categorizeByLevel (std::vector< std::vector< TagPoly >> &projectionLevels, const std::vector< carl::Variable > &varOrder, const std::vector< TagPoly > &polys)
Detailed Description
Construct a single open CAD Cell around a given point that is sign-invariant on a given set of polynomials.
References: [brown15] Brown, Christopher W., and Marek Košta. "Constructing a single cell in cylindrical algebraic decomposition." Journal of Symbolic Computation 70 (2015): 14-48. [mccallum84] Scott McCallum. "An Improved Projection Operation for Cylindrical Algebraic Decomposition" Ph.D. Dissertation. 1984. The University of Wisconsin - Madison
Definition in file OneCellCAD.h.
Typedef Documentation
CADCell
using smtrat::mcsat::onecellcad::CADCell = typedef std::vector<std::variant<Sector, Section> >
Represent a single cell [brown15].
A cell is a collection of boundary objects along each axis, called cell-components based on math. vectors and their components.
Definition at line 229 of file OneCellCAD.h.
Function Documentation
asRootExpr()
MultivariateRootT smtrat::mcsat::onecellcad::asRootExpr (carl::Variable rootVariable, Poly poly, std::size_t rootIdx) inline
Parameters
rootVariable The variable with respect to which the roots are computed in the end. It will be replaced by the special unique root-variable "_z" common in root-expressions.
Definition at line 167 of file OneCellCAD.h.
Referenced by smtrat::mcsat::onecellcad::asRootExpr().
cellDimension()
std::size_t smtrat::mcsat::onecellcad::cellDimension (const CADCell & cell, const std::size_t uptoLevel) inline
Returns
Dimension of a hybercube to which the given cell is homeomorphic, i.e., count the number of sectors of the given Cell restricted to its first components (with index 0 to 'uptoLevel').
Definition at line 261 of file OneCellCAD.h.
Referenced by smtrat::mcsat::onecellcad::cellDimension().
levelOf()
std::optional<std::size_t> smtrat::mcsat::onecellcad::levelOf (const std::vector< carl::Variable > & variableOrder, const Poly & poly) inline
Find the index of the highest variable (wrt.
the ordering in 'variableOrder') that occurs with positive degree in 'poly'. Although 'level' is a math concept that starts counting at 1 we start counting at 0 and represent "no level/variable" as std::nullopt because it simplifies using the level directly as an index into arrays or vectors. Examples:
polyLevel(2) == nullopt wrt. any variable order
polyLevel(0*x+2) == nullopt wrt. any variable order
polyLevel(x+2) == 0 wrt. [x < y < z]
polyLevel(x+2) == 1 wrt. [y < x < z]
polyLevel(x+2) == 2 wrt. [y < z < x]
polyLevel(x*y+2) == 1 wrt. [x < y < z] because of y
polyLevel(x*y+2) == 1 wrt. [y < x < z] because of x
polyLevel(x*y+2) == 2 wrt. [x < z < y] because of y Preconditions:
'poly.gatherVariables()' must be a subset of 'variableOrder'.
Definition at line 288 of file OneCellCAD.h.
Referenced by smtrat::mcsat::onecellcad::levelOf(), and smtrat::mcsat::onecellcad::OneCellCAD::pointEnclosingCADCell().