SMT-RAT: delta/operators.h File Reference
operators.h File Reference
#include <algorithm>
#include <cctype>
#include <functional>
#include <regex>
#include <sstream>
#include <utility>
#include <vector>
#include "Node.h"
#include "utils.h"
Typedefs
using delta::NodeChangeSet = std::vector< Node >
Set of new nodes.
using delta::NodeOperator = std::function< NodeChangeSet(const Node &)>
Type of an node operator.
Functions
NodeChangeSet delta::children (const Node &n)
Node operator that returns all children of a node.
NodeChangeSet delta::reorderChildren (const Node &n)
Node operator that reorders children of a node.
NodeChangeSet delta::mergeChild (const Node &n)
Node operator that merges nodes with one of its own children.
NodeChangeSet delta::number (const Node &n)
Node operator that provides meaningful replacements for numbers.
NodeChangeSet delta::constant (const Node &n)
Node operator that provides meaningful replacements for variables.
NodeChangeSet delta::letExpression (const Node &n)
Node operator that eliminated let expressions.
NodeChangeSet delta::BV_zeroExtend (const Node &n)
NodeChangeSet delta::BV_mergeShift (const Node &n)
(bvlshr (bvlshr x (_ bv1 8)) (_ bv1 8))
Detailed Description
Author
Gereon Kremer gereo.nosp@m.n.kr.nosp@m.emer@.nosp@m.cs.r.nosp@m.wth-a.nosp@m.ache.nosp@m.n.de
Definition in file operators.h.
Typedef Documentation
NodeOperator
using delta::NodeOperator = typedef std::function<NodeChangeSet(const Node&)>
Type of an node operator.
A NodeOperator is called on a node and shall return a set of new nodes. These new nodes are supposed to be a simplifying replacement for the given node.
Definition at line 28 of file operators.h.
Function Documentation
children()
NodeChangeSet delta::children (const Node & n)
Node operator that returns all children of a node.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 35 of file operators.h.
Referenced by delta::children(), and delta::Producer::Producer().
constant()
NodeChangeSet delta::constant (const Node & n)
Node operator that provides meaningful replacements for variables.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 132 of file operators.h.
Referenced by delta::constant(), and delta::Producer::Producer().
letExpression()
NodeChangeSet delta::letExpression (const Node & n)
Node operator that eliminated let expressions.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 151 of file operators.h.
Referenced by delta::letExpression(), and delta::Producer::Producer().
mergeChild()
NodeChangeSet delta::mergeChild (const Node & n)
Node operator that merges nodes with one of its own children.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 62 of file operators.h.
Referenced by delta::mergeChild(), and delta::Producer::Producer().
number()
NodeChangeSet delta::number (const Node & n)
Node operator that provides meaningful replacements for numbers.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 86 of file operators.h.
Referenced by delta::number(), and delta::Producer::Producer().
reorderChildren()
NodeChangeSet delta::reorderChildren (const Node & n)
Node operator that reorders children of a node.
Parameters
n Node.
Returns
A set of replacements.
Definition at line 45 of file operators.h.
Referenced by delta::Producer::Producer(), and delta::reorderChildren().