SMT-RAT: lib/modules/ReduceModule/libreduce/src/RedAns.h File Reference
RedAns.h File Reference
Functions
void RedAns_loadInitFile (RedProc)
RedAns RedAns_new (RedProc, const char *)
void RedAns_sendReduce (RedProc, const char *)
RedAns RedAns_readUntilPrompt (RedProc)
void RedAns_dfa (RedProc, StrBuf *, int *, StrBuf *, StrBuf *, StrBuf *, StrBuf *)
void RedAns_dfaLog (RedProc, const int)
void RedAns_delete (RedAns)
void RedAns_cfprint (FILE *stream, RedAns ans)
Function Documentation
void RedAns_cfprint (FILE * stream, RedAns ans)
Definition at line 244 of file RedAns.c.
void RedAns_delete (RedAns)
Definition at line 236 of file RedAns.c.
void RedAns_dfa (RedProc , StrBuf * , int * , StrBuf * , StrBuf * , StrBuf * , StrBuf *)
Definition at line 178 of file RedAns.c.
Referenced by RedAns_readUntilPrompt().
void RedAns_dfaLog (RedProc , const int)
Definition at line 227 of file RedAns.c.
Referenced by RedAns_dfa().
void RedAns_loadInitFile (RedProc)
Definition at line 66 of file RedAns.c.
Referenced by RedProc_parent().
RedAns RedAns_new (RedProc , const char *)
Definition at line 74 of file RedAns.c.
RedAns RedAns_readUntilPrompt (RedProc)
Definition at line 135 of file RedAns.c.
Referenced by RedAns_new(), and RedAns_sendReduce().
void RedAns_sendReduce (RedProc , const char *)
Definition at line 100 of file RedAns.c.
Referenced by RedAns_new().