SMT-RAT: lib/modules/ReduceModule/libreduce/src/RedAns.c File Reference
RedAns.c File Reference
#include <stdlib.h>
#include <string.h>
#include "reduce.h"
#include "RedMsg.h"
#include "StrBuf.h"
#include "RedAns.h"
Macros
#define READBUFSIZE
#define PRETEXT
#define PROMPT
#define FINISHED
#define RESULT
#define STATCOUNTER
#define MODE
#define POSTTEXT
#define ISCOLOR(c)
#define COLORTAB
#define EOT
#define LF
Functions
void RedAns_loadInitFile (RedProc process)
RedAns RedAns_new (RedProc process, const char *command)
void RedAns_sendReduce (RedProc process, const char *command)
RedAns RedAns_readUntilPrompt (RedProc process)
void RedAns_dfa (RedProc process, StrBuf *pstatcbuf, int *psymbolic, StrBuf *ppretext, StrBuf *presult, StrBuf *pposttext, StrBuf *pnextprompt)
void RedAns_dfaLog (RedProc process, const int st)
void RedAns_delete (RedAns ans)
void RedAns_cfprint (FILE *stream, RedAns ans)
Variables
FILE * debugfile
FILE * logfile
Macro Definition Documentation
#define COLORTAB
Definition at line 59 of file RedAns.c.
Referenced by RedAns_dfaLog().
#define EOT
Definition at line 61 of file RedAns.c.
Referenced by RedAns_sendReduce().
#define FINISHED
Definition at line 51 of file RedAns.c.
Referenced by RedAns_dfa().
#define ISCOLOR (c)
Definition at line 57 of file RedAns.c.
Referenced by RedAns_dfa().
#define LF
Definition at line 62 of file RedAns.c.
Referenced by RedAns_sendReduce().
#define MODE
Definition at line 54 of file RedAns.c.
Referenced by RedAns_dfa().
#define POSTTEXT
Definition at line 55 of file RedAns.c.
Referenced by RedAns_dfa().
#define PRETEXT
Definition at line 49 of file RedAns.c.
Referenced by RedAns_dfa().
#define PROMPT
Definition at line 50 of file RedAns.c.
Referenced by RedAns_dfa().
#define READBUFSIZE
Definition at line 47 of file RedAns.c.
Referenced by RedAns_dfa().
#define RESULT
Definition at line 52 of file RedAns.c.
Referenced by RedAns_dfa().
#define STATCOUNTER
Definition at line 53 of file RedAns.c.
Referenced by RedAns_dfa().
Function Documentation
void RedAns_cfprint (FILE * stream, RedAns ans)
Definition at line 244 of file RedAns.c.
Referenced by RedAns_new(), and RedProc_error().
void RedAns_delete (RedAns ans)
Definition at line 236 of file RedAns.c.
Referenced by smtrat::ReduceModule::isConsistent(), main(), RedAns_loadInitFile(), RedAns_sendReduce(), RedPy_ansDelete(), and smtrat::ReduceModule::ReduceModule().
void RedAns_dfa (RedProc process, StrBuf * pstatcbuf, int * psymbolic, StrBuf * ppretext, StrBuf * presult, StrBuf * pposttext, StrBuf * pnextprompt)
Definition at line 178 of file RedAns.c.
Referenced by RedAns_readUntilPrompt().
void RedAns_dfaLog (RedProc process, const int st)
Definition at line 227 of file RedAns.c.
Referenced by RedAns_dfa().
void RedAns_loadInitFile (RedProc process)
Definition at line 66 of file RedAns.c.
Referenced by RedProc_parent().
RedAns RedAns_new (RedProc process, const char * command)
Definition at line 74 of file RedAns.c.
Referenced by smtrat::ReduceModule::isConsistent(), main(), RedAns_loadInitFile(), RedPy_ansNew(), and smtrat::ReduceModule::ReduceModule().
RedAns RedAns_readUntilPrompt (RedProc process)
Definition at line 135 of file RedAns.c.
Referenced by RedAns_new(), and RedAns_sendReduce().
void RedAns_sendReduce (RedProc process, const char * command)
Definition at line 100 of file RedAns.c.
Referenced by RedAns_new().
Variable Documentation
FILE* debugfile
Definition at line 62 of file RedProc.c.
Referenced by RedAns_dfa(), RedAns_dfaLog(), RedAns_loadInitFile(), RedAns_new(), RedAns_readUntilPrompt(), and RedAns_sendReduce().
FILE * logfile
Definition at line 61 of file RedProc.c.
Referenced by RedAns_new(), RedProc_delete(), RedProc_new(), and RedProc_parent().