SMT-RAT: lib/modules/ReduceModule/libreduce/src/RedMsg.c File Reference
RedMsg.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <errno.h>
#include "RedMsg.h"
Functions
FILE * RedMsg_openLogfile (const char *filename, FILE *handle)
int RedMsg_cfprintf (FILE *file, const char *msg,...)
Function Documentation
int RedMsg_cfprintf (FILE * file, const char * msg, ...)
Definition at line 55 of file RedMsg.c.
Referenced by RedAns_dfa(), RedAns_dfaLog(), RedAns_loadInitFile(), RedAns_new(), RedAns_readUntilPrompt(), RedAns_sendReduce(), RedProc_child(), RedProc_delete(), RedProc_kill(), RedProc_new(), RedProc_parent(), and RedPy_procNew().
FILE* RedMsg_openLogfile (const char * filename, FILE * handle)
Definition at line 38 of file RedMsg.c.
Referenced by RedProc_new(), and RedProc_parent().