SMT-RAT: lib/modules/ReduceModule/libreduce/src/RedMsg.h File Reference
RedMsg.h File Reference
Functions
FILE * RedMsg_openLogfile (const char *, FILE *)
int RedMsg_cfprintf (FILE *stream, const char *msg,...)
Function Documentation
int RedMsg_cfprintf (FILE * stream, const char * msg, ...)
Definition at line 55 of file RedMsg.c.
Referenced by RedAns_dfa(), RedAns_dfaLog(), RedAns_loadInitFile(), RedAns_new(), RedAns_readUntilPrompt(), RedAns_sendReduce(), RedProc_child(), RedProc_delete(), RedProc_kill(), RedProc_new(), RedProc_parent(), and RedPy_procNew().
FILE* RedMsg_openLogfile (const char * , FILE *)
Definition at line 38 of file RedMsg.c.
Referenced by RedProc_new(), and RedProc_parent().