SMT-RAT: lib/modules/ReduceModule/libreduce/src/RedProc.c File Reference
RedProc.c File Reference
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sys/socket.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <signal.h>
#include "reduce.h"
#include "StrBuf.h"
#include "RedAns.h"
#include "RedMsg.h"
#include "RedProc.h"
Functions
RedProc RedProc_new (const char *reduce)
void RedProc_initSockets (RedProc process)
RedProc RedProc_parent (RedProc process)
void RedProc_child (RedProc process, const char *reduce)
void RedProc_delete (RedProc process)
void RedProc_kill (pid_t pid)
void RedProc_cfprint (FILE *stream, RedProc proc)
RETSIGTYPE RedProc_SigChld (int arg)
void RedProc_removeSignalHandlers (void)
pid_t RedProc_waitPid (pid_t pid, int *status)
void RedProc_error (RedProc process, const char *command, RedAns answer)
Variables
FILE * logfile
FILE * debugfile
static RedProc process
Function Documentation
void RedProc_cfprint (FILE * stream, RedProc proc)
Definition at line 220 of file RedProc.c.
Referenced by RedProc_delete(), RedProc_parent(), and RedPy_procNew().
void RedProc_child (RedProc process, const char * reduce)
Definition at line 161 of file RedProc.c.
Referenced by RedProc_new().
void RedProc_delete (RedProc process)
Definition at line 186 of file RedProc.c.
Referenced by main(), RedPy_procDelete(), and smtrat::ReduceModule::~ReduceModule().
void RedProc_error (RedProc process, const char * command, RedAns answer)
Definition at line 273 of file RedProc.c.
Referenced by smtrat::ReduceModule::isConsistent().
void RedProc_initSockets (RedProc process)
Definition at line 114 of file RedProc.c.
Referenced by RedProc_new().
void RedProc_kill (pid_t pid)
Definition at line 200 of file RedProc.c.
Referenced by RedProc_delete().
RedProc RedProc_new (const char * reduce)
Definition at line 66 of file RedProc.c.
Referenced by main(), RedPy_procNew(), and smtrat::ReduceModule::ReduceModule().
RedProc RedProc_parent (RedProc process)
Definition at line 140 of file RedProc.c.
Referenced by RedProc_new().
void RedProc_removeSignalHandlers (void)
Definition at line 242 of file RedProc.c.
Referenced by RedProc_child().
RETSIGTYPE RedProc_SigChld (int arg)
Definition at line 231 of file RedProc.c.
Referenced by RedProc_kill(), and RedProc_new().
pid_t RedProc_waitPid (pid_t pid, int * status)
Definition at line 255 of file RedProc.c.
Referenced by RedProc_kill().
Variable Documentation
FILE* debugfile
Definition at line 62 of file RedProc.c.
Referenced by RedAns_dfa(), RedAns_dfaLog(), RedAns_loadInitFile(), RedAns_new(), RedAns_readUntilPrompt(), RedAns_sendReduce(), RedProc_child(), RedProc_kill(), RedProc_new(), and RedPy_procNew().
FILE* logfile
Definition at line 61 of file RedProc.c.
Referenced by RedAns_new(), RedProc_delete(), RedProc_new(), and RedProc_parent().
RedProc process static
Definition at line 64 of file RedProc.c.
Referenced by main(), and RedProc_parent().