SMT-RAT: lib/modules/ReduceModule/libreduce/src/RedProc.h File Reference
RedProc.h File Reference
Functions
RedProc RedProc_new (const char *)
void RedProc_initSockets (RedProc)
RedProc RedProc_parent (RedProc)
void RedProc_child (RedProc, const char *)
void RedProc_delete (RedProc)
void RedProc_kill (int)
void RedProc_cfprint (FILE *stream, RedProc process)
RETSIGTYPE RedProc_SigChld (int)
void RedProc_removeSignalHandlers (void)
pid_t RedProc_waitPid (pid_t, int *)
void RedProc_error (RedProc, const char *, RedAns)
Function Documentation
void RedProc_cfprint (FILE * stream, RedProc process)
Definition at line 220 of file RedProc.c.
void RedProc_child (RedProc , const char *)
Definition at line 161 of file RedProc.c.
Referenced by RedProc_new().
void RedProc_delete (RedProc)
Definition at line 186 of file RedProc.c.
void RedProc_error (RedProc , const char * , RedAns)
Definition at line 273 of file RedProc.c.
void RedProc_initSockets (RedProc)
Definition at line 114 of file RedProc.c.
Referenced by RedProc_new().
void RedProc_kill (int)
RedProc RedProc_new (const char *)
Definition at line 66 of file RedProc.c.
RedProc RedProc_parent (RedProc)
Definition at line 140 of file RedProc.c.
Referenced by RedProc_new().
void RedProc_removeSignalHandlers (void)
Definition at line 242 of file RedProc.c.
Referenced by RedProc_child().
RETSIGTYPE RedProc_SigChld (int)
Definition at line 231 of file RedProc.c.
Referenced by RedProc_kill(), and RedProc_new().
pid_t RedProc_waitPid (pid_t , int *)
Definition at line 255 of file RedProc.c.
Referenced by RedProc_kill().