SMT-RAT: lib/modules/ReduceModule/libreduce/src/reduce.h File Reference
reduce.h File Reference
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
Data Structures
struct oRedProc
struct oRedAns
Macros
#define reduce_init
#define reduce_finish
#define reduce_command
Typedefs
typedef struct oRedProc * RedProc
typedef struct oRedAns * RedAns
Functions
RedProc RedProc_new (const char *reduce)
void RedProc_delete (RedProc process)
void RedProc_error (RedProc process, const char *command, RedAns answer)
void RedProc_cfprint (FILE *stream, RedProc process)
RedAns RedAns_new (RedProc process, const char *command)
void RedAns_delete (RedAns answer)
void RedAns_cfprint (FILE *stream, RedAns ans)
Macro Definition Documentation
#define reduce_command
Definition at line 124 of file reduce.h.
#define reduce_finish
Definition at line 123 of file reduce.h.
#define reduce_init
Definition at line 122 of file reduce.h.
Typedef Documentation
typedef struct oRedAns* RedAns
Definition at line 95 of file reduce.h.
typedef struct oRedProc* RedProc
Definition at line 50 of file reduce.h.
Function Documentation
void RedAns_cfprint (FILE * stream, RedAns ans)
Definition at line 244 of file RedAns.c.
Referenced by RedAns_new(), and RedProc_error().
void RedAns_delete (RedAns answer)
Definition at line 236 of file RedAns.c.
Referenced by smtrat::ReduceModule::isConsistent(), main(), RedAns_loadInitFile(), RedAns_sendReduce(), RedPy_ansDelete(), and smtrat::ReduceModule::ReduceModule().
RedAns RedAns_new (RedProc process, const char * command)
Definition at line 74 of file RedAns.c.
Referenced by smtrat::ReduceModule::isConsistent(), main(), RedAns_loadInitFile(), RedPy_ansNew(), and smtrat::ReduceModule::ReduceModule().
void RedProc_cfprint (FILE * stream, RedProc process)
Definition at line 220 of file RedProc.c.
Referenced by RedProc_delete(), RedProc_parent(), and RedPy_procNew().
void RedProc_delete (RedProc process)
Definition at line 186 of file RedProc.c.
Referenced by main(), RedPy_procDelete(), and smtrat::ReduceModule::~ReduceModule().
void RedProc_error (RedProc process, const char * command, RedAns answer)
Definition at line 273 of file RedProc.c.
Referenced by smtrat::ReduceModule::isConsistent().
RedProc RedProc_new (const char * reduce)
Definition at line 66 of file RedProc.c.
Referenced by main(), RedPy_procNew(), and smtrat::ReduceModule::ReduceModule().