SMT-RAT: smtrat::lra::Bound< T1, T2 > Class Template Reference
smtrat::lra::Bound< T1, T2 > Class Template Reference
Stores a bound, which could be an upper "<= b" or a lower bound ">= b" for a bound value b.
#include <Bound.h>
Data Structures
struct Info
Stores some additional information for a bound.
Public Types
enum Type { LOWER, UPPER, EQUAL }
The type of the bound: LOWER = ">=", UPPER = "<=", EQUAL "==".
typedef carl::PointerSet
< Bound< T1, T2 > > BoundSet
A set of pointer to bounds.
Public Member Functions
Bound ()=delete
Bound (const Value< T1 > *const _limit, Variable< T1, T2 > *const _var, Type _type, const FormulaT &_constraint, Bound< T1, T2 >::Info *_boundInfo=NULL, bool _deduced=false)
~Bound ()
bool operator> (const Value< T1 > &_value) const
bool operator== (const Value< T1 > &_value) const
bool operator< (const Value< T1 > &_value) const
bool operator< (const Bound &_bound) const
bool operator> (const Bound &_bound) const
bool operator== (const T1 &_a) const
bool operator> (const T1 &_a) const
bool operator< (const T1 &_a) const
bool operator>= (const T1 &_a) const
bool operator<= (const T1 &_a) const
const std::string toString () const
void print (bool _withOrigins=false, std::ostream &_out=std::cout, bool _printTypebool=false) const
bool deduced () const
const Value< T1 > & limit () const
const Value< T1 > * pLimit () const
bool isInfinite () const
Variable< T1, T2 > * pVariable () const
const Variable< T1, T2 > & variable () const
Type type () const
bool isWeak () const
bool isUpperBound () const
bool isLowerBound () const
const FormulaT & asConstraint () const
const FormulaT & neqRepresentation () const
void setNeqRepresentation (const FormulaT &_constraint) const
void boundExists () const
const std::shared_ptr
< std::vector< FormulaT > > & pOrigins () const
const std::vector< FormulaT > & origins () const
bool isActive () const
Info * pInfo () const
bool operator>= (const Value< T1 > &v) const
bool operator<= (const Value< T1 > &v) const
Private Attributes
bool mDeduced
Type mType
const Value< T1 > * mLimit
Variable< T1, T2 > *const mVar
FormulaT mAsConstraint
std::shared_ptr< std::vector
< FormulaT > > mpOrigins
Info * mpInfo
Friends
template<typename T3 , typename T4 >
std::ostream & operator<< (std::ostream &_ostream, const Bound< T3, T4 > &_bound)
Detailed Description
template<typename T1, typename T2>
class smtrat::lra::Bound< T1, T2 >
Stores a bound, which could be an upper "<= b" or a lower bound ">= b" for a bound value b.
In the case that "<= b" and ">= b" hold this bound is a so called equal bound represented by "==b".
Definition at line 26 of file Bound.h.
Member Typedef Documentation
template<typename T1, typename T2> typedef carl::PointerSet<Bound<T1, T2> > smtrat::lra::Bound< T1, T2 >::BoundSet
A set of pointer to bounds.
Definition at line 40 of file Bound.h.
Member Enumeration Documentation
template<typename T1, typename T2> enum smtrat::lra::Bound::Type
The type of the bound: LOWER = ">=", UPPER = "<=", EQUAL "==".
Enumerator
LOWER
UPPER
EQUAL
Definition at line 37 of file Bound.h.
Constructor & Destructor Documentation
template<typename T1, typename T2> smtrat::lra::Bound< T1, T2 >::Bound () delete
template<typename T1, typename T2> smtrat::lra::Bound< T1, T2 >::Bound (const Value< T1 > *const _limit, Variable< T1, T2 > *const _var, Type _type, const FormulaT & _constraint, Bound< T1, T2 >::Info * _boundInfo = NULL, bool _deduced = false)
Parameters
_limit
_var
_type
_constraint
_boundInfo
_deduced
template<typename T1, typename T2> smtrat::lra::Bound< T1, T2 >::~Bound ()
Member Function Documentation
template<typename T1, typename T2> const FormulaT& smtrat::lra::Bound< T1, T2 >::asConstraint () const inline
Returns
Definition at line 280 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::inConflictWith().
template<typename T1, typename T2> void smtrat::lra::Bound< T1, T2 >::boundExists () const inline
Definition at line 309 of file Bound.h.
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::deduced () const inline
Returns
Definition at line 200 of file Bound.h.
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::isActive () const inline
Returns
Definition at line 333 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::setInfimum(), and smtrat::lra::Variable< LRABoundType, LRAEntryType >::setSupremum().
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::isInfinite () const inline
Returns
Definition at line 224 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::involvesEquation(), smtrat::lra::Variable< LRABoundType, LRAEntryType >::isActive(), smtrat::lra::Variable< LRABoundType, LRAEntryType >::setInfimum(), smtrat::lra::Variable< LRABoundType, LRAEntryType >::setSupremum(), and smtrat::lra::Variable< LRABoundType, LRAEntryType >::updateConflictActivity().
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::isLowerBound () const inline
Returns
Definition at line 272 of file Bound.h.
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::isUpperBound () const inline
Returns
Definition at line 264 of file Bound.h.
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::isWeak () const inline
Returns
Definition at line 256 of file Bound.h.
template<typename T1, typename T2> const Value<T1>& smtrat::lra::Bound< T1, T2 >::limit () const inline
Returns
Definition at line 208 of file Bound.h.
template<typename T1, typename T2> const FormulaT& smtrat::lra::Bound< T1, T2 >::neqRepresentation () const inline
Returns
Definition at line 288 of file Bound.h.
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator< (const Value< T1 > & _value) const
Parameters
_value
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator< (const Bound< T1, T2 > & _bound) const
Parameters
_bound
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator< (const T1 & _a) const
Parameters
_a
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator<= (const T1 & _a) const
Parameters
_a
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator<= (const Value< T1 > & v) const inline
Returns
Definition at line 357 of file Bound.h.
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator== (const Value< T1 > & _value) const
Parameters
_value
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator== (const T1 & _a) const
Parameters
_a
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator> (const Value< T1 > & _value) const
Parameters
_value
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator> (const Bound< T1, T2 > & _bound) const
Parameters
_bound
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator> (const T1 & _a) const
Parameters
_a
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator>= (const T1 & _a) const
Parameters
_a
Returns
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::operator>= (const Value< T1 > & v) const inline
Returns
Definition at line 349 of file Bound.h.
template<typename T1, typename T2> const std::vector<FormulaT>& smtrat::lra::Bound< T1, T2 >::origins () const inline
Returns
Definition at line 325 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::infimum(), smtrat::lra::Variable< LRABoundType, LRAEntryType >::pInfimum(), smtrat::lra::Variable< LRABoundType, LRAEntryType >::pSupremum(), and smtrat::lra::Variable< LRABoundType, LRAEntryType >::supremum().
template<typename T1, typename T2> Info* smtrat::lra::Bound< T1, T2 >::pInfo () const inline
Returns
Definition at line 341 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::setInfimum(), and smtrat::lra::Variable< LRABoundType, LRAEntryType >::setSupremum().
template<typename T1, typename T2> const Value<T1>* smtrat::lra::Bound< T1, T2 >::pLimit () const inline
Returns
Definition at line 216 of file Bound.h.
template<typename T1, typename T2> const std::shared_ptr<std::vector<FormulaT> >& smtrat::lra::Bound< T1, T2 >::pOrigins () const inline
Returns
Definition at line 317 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::updateConflictActivity().
template<typename T1, typename T2> void smtrat::lra::Bound< T1, T2 >::print (bool _withOrigins = false, std::ostream & _out = std::cout, bool _printTypebool = false) const
Parameters
_withOrigins
_out
_printTypebool
template<typename T1, typename T2> Variable<T1, T2>* smtrat::lra::Bound< T1, T2 >::pVariable () const inline
Returns
Definition at line 232 of file Bound.h.
template<typename T1, typename T2> void smtrat::lra::Bound< T1, T2 >::setNeqRepresentation (const FormulaT & _constraint) const inline
Parameters
_constraint
Definition at line 297 of file Bound.h.
template<typename T1, typename T2> const std::string smtrat::lra::Bound< T1, T2 >::toString () const
Returns
template<typename T1, typename T2> Type smtrat::lra::Bound< T1, T2 >::type () const inline
Returns
Definition at line 248 of file Bound.h.
Referenced by smtrat::lra::Variable< LRABoundType, LRAEntryType >::involvesEquation().
template<typename T1, typename T2> const Variable<T1, T2>& smtrat::lra::Bound< T1, T2 >::variable () const inline
Returns
Definition at line 240 of file Bound.h.
Friends And Related Function Documentation
template<typename T1, typename T2> template<typename T3 , typename T4 > std::ostream& operator<< (std::ostream & _ostream, const Bound< T3, T4 > & _bound) friend
Parameters
_withOrigins
_out
_printTypebool
Field Documentation
template<typename T1, typename T2> FormulaT smtrat::lra::Bound< T1, T2 >::mAsConstraint private
Definition at line 77 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::asConstraint().
template<typename T1, typename T2> bool smtrat::lra::Bound< T1, T2 >::mDeduced private
Definition at line 69 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::deduced().
template<typename T1, typename T2> const Value<T1>* smtrat::lra::Bound< T1, T2 >::mLimit private
Definition at line 73 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::limit(), and smtrat::lra::Bound< LRABoundType, LRAEntryType >::pLimit().
template<typename T1, typename T2> Info* smtrat::lra::Bound< T1, T2 >::mpInfo private
Definition at line 81 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::pInfo().
template<typename T1, typename T2> std::shared_ptr<std::vector<FormulaT> > smtrat::lra::Bound< T1, T2 >::mpOrigins private
Definition at line 79 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::origins(), and smtrat::lra::Bound< LRABoundType, LRAEntryType >::pOrigins().
template<typename T1, typename T2> Type smtrat::lra::Bound< T1, T2 >::mType private
Definition at line 71 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::type().
template<typename T1, typename T2> Variable<T1, T2>* const smtrat::lra::Bound< T1, T2 >::mVar private
Definition at line 75 of file Bound.h.
Referenced by smtrat::lra::Bound< LRABoundType, LRAEntryType >::pVariable(), and smtrat::lra::Bound< LRABoundType, LRAEntryType >::variable().
The documentation for this class was generated from the following file:
lib/datastructures/lra/Bound.h