SMT-RAT: benchmax/ssh/SshWaitSocket.h File Reference
SshWaitSocket.h File Reference
Functions
static int waitsocket (int socket_fd, LIBSSH2_SESSION *session)
Function Documentation
static int waitsocket (int socket_fd, LIBSSH2_SESSION * session) static
Definition at line 11 of file SshWaitSocket.h.
Referenced by SshChannel::closeChannel(), SFTPDownloader::download(), SshChannel::executeCommand(), SFTPDownloader::initDownload(), and SshChannel::openChannel().