SMT-RAT: lib/modules/ReduceModule/libreduce/src/StrBuf.c File Reference
StrBuf.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "StrBuf.h"
Functions
StrBuf StrBuf_addChar (StrBuf b, char c)
StrBuf StrBuf_pruneNl (StrBuf b)
char * StrBuf_string (StrBuf b)
StrBuf StrBuf_remTail (StrBuf b, StrBuf t)
int StrBuf_tailIs (StrBuf b, StrBuf t)
void StrBuf_fprint (FILE *file, StrBuf b)
Function Documentation
StrBuf StrBuf_addChar (StrBuf b, char c)
Definition at line 35 of file StrBuf.c.
Referenced by RedAns_dfa().
void StrBuf_fprint (FILE * file, StrBuf b)
Definition at line 139 of file StrBuf.c.
StrBuf StrBuf_pruneNl (StrBuf b)
Definition at line 48 of file StrBuf.c.
Referenced by RedAns_readUntilPrompt().
StrBuf StrBuf_remTail (StrBuf b, StrBuf t)
Definition at line 112 of file StrBuf.c.
char* StrBuf_string (StrBuf b)
Definition at line 80 of file StrBuf.c.
Referenced by RedAns_readUntilPrompt().
int StrBuf_tailIs (StrBuf b, StrBuf t)
Definition at line 128 of file StrBuf.c.
Referenced by StrBuf_remTail().