SMT-RAT: lib/modules/ReduceModule/libreduce/src/StrBuf.h File Reference
StrBuf.h File Reference
Data Structures
struct oStrBuf
Typedefs
typedef struct oStrBuf * StrBuf
Functions
StrBuf StrBuf_addChar (StrBuf, char)
StrBuf StrBuf_pruneNl (StrBuf)
char * StrBuf_string (StrBuf)
StrBuf StrBuf_remTail (StrBuf, StrBuf)
int StrBuf_tailIs (StrBuf, StrBuf)
void StrBuf_fprint (FILE *file, StrBuf)
Typedef Documentation
typedef struct oStrBuf* StrBuf
Definition at line 36 of file StrBuf.h.
Function Documentation
StrBuf StrBuf_addChar (StrBuf , char)
Definition at line 35 of file StrBuf.c.
Referenced by RedAns_dfa().
void StrBuf_fprint (FILE * file, StrBuf)
Definition at line 139 of file StrBuf.c.
StrBuf StrBuf_pruneNl (StrBuf)
Definition at line 48 of file StrBuf.c.
Referenced by RedAns_readUntilPrompt().
StrBuf StrBuf_remTail (StrBuf , StrBuf)
Definition at line 112 of file StrBuf.c.
char* StrBuf_string (StrBuf)
Definition at line 80 of file StrBuf.c.
Referenced by RedAns_readUntilPrompt().
int StrBuf_tailIs (StrBuf , StrBuf)
Definition at line 128 of file StrBuf.c.
Referenced by StrBuf_remTail().