SMT-RAT: smtrat::parser::TypeOfTerm Struct Reference
smtrat::parser::TypeOfTerm Struct Reference
#include <ParserUtils.h>
Public Member Functions
ExpressionType operator() (const FormulaT &) const
ExpressionType operator() (const carl::UFInstance &) const
ExpressionType operator() (const carl::UVariable &) const
ExpressionType operator() (const UninterpretedType &) const
ExpressionType operator() (const Poly &) const
ExpressionType operator() (const carl::Variable &v) const
ExpressionType operator() (const carl::VariableType &v) const
ExpressionType operator() (const carl::Sort &v) const
Static Public Member Functions
template<typename T >
static ExpressionType get (const T &t)
template<BOOST_VARIANT_ENUM_PARAMS(typename T) >
static ExpressionType get (const boost::variant< BOOST_VARIANT_ENUM_PARAMS(T)> &var)
Detailed Description
Definition at line 49 of file ParserUtils.h.
Member Function Documentation
template<typename T > static ExpressionType smtrat::parser::TypeOfTerm::get (const T & t) inline static
Definition at line 72 of file ParserUtils.h.
Referenced by smtrat::parser::ParserState::addQuantifiedVariable(), smtrat::parser::ParserState::addVariableBinding(), smtrat::parser::ParserState::checkArguments(), and smtrat::parser::SMTLIBParser::defineFun().
template<BOOST_VARIANT_ENUM_PARAMS(typename T) > static ExpressionType smtrat::parser::TypeOfTerm::get (const boost::variant< BOOST_VARIANT_ENUM_PARAMS(T)> & var) inline static
Definition at line 76 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const FormulaT &) const inline
Definition at line 50 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const carl::UFInstance &) const inline
Definition at line 51 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const carl::UVariable &) const inline
Definition at line 52 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const UninterpretedType &) const inline
Definition at line 53 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const Poly &) const inline
Definition at line 54 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const carl::Variable & v) const inline
Definition at line 55 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const carl::VariableType & v) const inline
Definition at line 56 of file ParserUtils.h.
ExpressionType smtrat::parser::TypeOfTerm::operator() (const carl::Sort & v) const inline
Definition at line 67 of file ParserUtils.h.
The documentation for this struct was generated from the following file:
cli/parser/ParserUtils.h