SMT-RAT: delta::Node Struct Reference
delta::Node Struct Reference
This class represents a node in a SMTLIB file.
#include <Node.h>
Public Member Functions
Node ()
Create an empty node.
Node (const std::string &name, bool brackets=true)
Create a node with a name.
Node (const std::tuple< std::string, bool > &data)
Create a node with a name.
Node (const std::tuple< std::vector< Node >, bool > &data)
Create a node with children.
Node (const std::tuple< std::string, std::vector< Node >, bool > &data)
Create a node with a name and children.
Node (const std::string &name, const std::initializer_list< Node > &children, bool brackets=true)
void recalculateSize ()
std::size_t complexity () const
Calculates the number of nodes.
bool immutable () const
Checks if this node is immutable.
std::string repr (bool longRepr=false) const
Returns a string representation of this node.
Node clone (const Node *from, const Node *to) const
Clone this node recursively.
Node clone (const std::string &from, const Node *to) const
Clone this node recursively.
void collectNames (std::set< std::string > &names) const
void eliminateDefineFuns ()
Data Fields
std::string name
Name of the node.
std::vector< Node > children
Children of the node.
bool brackets
Flag if the node was contained in brackets.
std::size_t size
Detailed Description
This class represents a node in a SMTLIB file.
Every syntactical constructor is represented by a node. A node may have a name and may have several children. In a file, this corresponds to (<name> <child> <child>...).
Note that these nodes are constructed by a parser that has no semantic knowledge of the smtlib format. Hence, the data representable by these nodes is only a very rough overapproximation of the actual smtlib format.
Definition at line 28 of file Node.h.
Constructor & Destructor Documentation
Node() [1/4]
delta::Node::Node (const std::string & name, bool brackets = true) inline explicit
Create a node with a name.
Parameters
name Name of the node.
brackets If not is contained in brackets.
Definition at line 46 of file Node.h.
Node() [2/4]
delta::Node::Node (const std::tuple< std::string, bool > & data) inline explicit
Create a node with a name.
Parameters
data Tuple containing the name and the brackets flag.
Definition at line 51 of file Node.h.
Node() [3/4]
delta::Node::Node (const std::tuple< std::vector< Node >, bool > & data) inline explicit
Create a node with children.
Parameters
data Tuple containing the children and the brackets flag.
Definition at line 56 of file Node.h.
Node() [4/4]
delta::Node::Node (const std::tuple< std::string, std::vector< Node >, bool > & data) inline explicit
Create a node with a name and children.
Parameters
data Tuple containing the name, the children and the brackets flag.
Definition at line 63 of file Node.h.
Member Function Documentation
clone() [1/2]
Node delta::Node::clone (const Node * from, const Node * to) const inline
Clone this node recursively.
If the node from is encountered, replace it with to. If to is a nullptr, remove it instead.
Parameters
from Node to replace.
to Node to replace with.
Returns
Cloned node.
Definition at line 112 of file Node.h.
Referenced by delta::letExpression(), and delta::Producer::process().
clone() [2/2]
Node delta::Node::clone (const std::string & from, const Node * to) const inline
Clone this node recursively.
If a node with name from without children is enountered, replace it with to.
Parameters
from Node name to replace.
to Node to replace with.
Returns
Cloned node.
Definition at line 132 of file Node.h.
complexity()
std::size_t delta::Node::complexity () const inline
Calculates the number of nodes.
Returns
Number of nodes.
Definition at line 79 of file Node.h.
Referenced by delta::Producer::operator()().
immutable()
bool delta::Node::immutable () const inline
Checks if this node is immutable.
This method implements simple checks to prevent unnecessary solver errors if essential parts of the smtlib file are removed, for example the set-logic statement.
Returns
If node may be removed.
Definition at line 87 of file Node.h.
Referenced by delta::Producer::process().
repr()
std::string delta::Node::repr (bool longRepr = false) const inline
Returns a string representation of this node.
Returns
String of the node.
Definition at line 95 of file Node.h.
Referenced by delta::Producer::process().
The documentation for this struct was generated from the following file:
delta/Node.h