SMT-RAT: smtrat::parser::PolynomialParser Struct Reference
smtrat::parser::PolynomialParser Struct Reference
#include <PolynomialParser.h>
Public Member Functions
PolynomialParser (ParserState *state, FormulaParser *formulaPtr, UninterpretedParser *uninterpreted)
Private Member Functions
Poly mkIteInExpr (const FormulaT &_condition, Poly &_then, Poly &_else)
Poly var2Poly (carl::Variable::Arg var) const
Poly createPoly (const std::pair< Poly::ConstructorOperation, std::vector< Poly >> &p) const
Poly rationalToPoly (const smtrat::Rational &rat) const
Private Attributes
ParserState * state
BoundaryParser boundary
TheoryOpParser op_theory
IntegralParser integral
DecimalParser decimal
qi::rule< Iterator, Poly(),
Skipper > polynomial
qi::rule< Iterator, std::pair
< Poly::ConstructorOperation,
std::vector< Poly >
>), Skipper > polynomial_op
qi::rule< Iterator, Poly(),
Skipper > polynomial_ite
qi::rule< Iterator, Poly(),
Skipper > polynomial_fun
qi::rule< Iterator, Poly(),
Skipper > polynomial_uf
BitvectorParser bitvector
FunctionArgumentParser fun_argument
Detailed Description
Definition at line 25 of file PolynomialParser.h.
Constructor & Destructor Documentation
smtrat::parser::PolynomialParser::PolynomialParser (ParserState * state, FormulaParser * formulaPtr, UninterpretedParser * uninterpreted)
Definition at line 14 of file PolynomialParser.cpp.
Member Function Documentation
Poly smtrat::parser::PolynomialParser::createPoly (const std::pair< Poly::ConstructorOperation, std::vector< Poly >> & p) const inline private
Definition at line 34 of file PolynomialParser.h.
Referenced by PolynomialParser().
Poly smtrat::parser::PolynomialParser::mkIteInExpr (const FormulaT & _condition, Poly & _then, Poly & _else) private
Definition at line 42 of file PolynomialParser.cpp.
Referenced by PolynomialParser().
Poly smtrat::parser::PolynomialParser::rationalToPoly (const smtrat::Rational & rat) const inline private
Definition at line 37 of file PolynomialParser.h.
Referenced by PolynomialParser().
Poly smtrat::parser::PolynomialParser::var2Poly (carl::Variable::Arg var) const inline private
Definition at line 31 of file PolynomialParser.h.
Referenced by PolynomialParser().
Field Documentation
BitvectorParser smtrat::parser::PolynomialParser::bitvector private
Definition at line 52 of file PolynomialParser.h.
BoundaryParser smtrat::parser::PolynomialParser::boundary private
Definition at line 41 of file PolynomialParser.h.
Referenced by PolynomialParser().
DecimalParser smtrat::parser::PolynomialParser::decimal private
Definition at line 44 of file PolynomialParser.h.
Referenced by PolynomialParser().
FunctionArgumentParser smtrat::parser::PolynomialParser::fun_argument private
Definition at line 53 of file PolynomialParser.h.
Referenced by PolynomialParser().
IntegralParser smtrat::parser::PolynomialParser::integral private
Definition at line 43 of file PolynomialParser.h.
Referenced by PolynomialParser().
TheoryOpParser smtrat::parser::PolynomialParser::op_theory private
Definition at line 42 of file PolynomialParser.h.
Referenced by PolynomialParser().
qi::rule<Iterator, Poly(), Skipper> smtrat::parser::PolynomialParser::polynomial private
Definition at line 46 of file PolynomialParser.h.
Referenced by PolynomialParser().
qi::rule<Iterator, Poly(), Skipper> smtrat::parser::PolynomialParser::polynomial_fun private
Definition at line 49 of file PolynomialParser.h.
Referenced by PolynomialParser().
qi::rule<Iterator, Poly(), Skipper> smtrat::parser::PolynomialParser::polynomial_ite private
Definition at line 48 of file PolynomialParser.h.
Referenced by PolynomialParser().
qi::rule<Iterator, std::pair<Poly::ConstructorOperation, std::vector<Poly> >), Skipper> smtrat::parser::PolynomialParser::polynomial_op private
Definition at line 47 of file PolynomialParser.h.
Referenced by PolynomialParser().
qi::rule<Iterator, Poly(), Skipper> smtrat::parser::PolynomialParser::polynomial_uf private
Definition at line 50 of file PolynomialParser.h.
Referenced by PolynomialParser().
ParserState* smtrat::parser::PolynomialParser::state private
Definition at line 28 of file PolynomialParser.h.
Referenced by mkIteInExpr(), and PolynomialParser().
The documentation for this struct was generated from the following files:
cli/parser/PolynomialParser.h
cli/parser/PolynomialParser.cpp