SMT-RAT: smtrat::parser::FormulaParser Struct Reference
smtrat::parser::FormulaParser Struct Reference
#include <FormulaParser.h>
Public Member Functions
FormulaParser (ParserState *state)
Private Member Functions
FormulaT mkFormula (carl::FormulaType _type, FormulasT &_subformulas)
FormulaT mkConstraint (const Poly &, const Poly &, carl::Relation)
FormulaT mkEquality (const Arguments &args)
FormulaT mkDistinct (const Arguments &args)
Private Attributes
ParserState * state
BoundaryParser boundary
SymbolParser symbol
BooleanOpParser op_bool
RelationParser relation
DomainParser domain
AttributeParser attribute
BitvectorParser bitvector
UninterpretedParser uninterpreted
PolynomialParser polynomial
FunctionArgumentParser fun_argument
qi::rule< Iterator,
qi::unused_type, Skipper,
qi::locals< std::string > > binding
qi::rule< Iterator,
qi::unused_type, Skipper > bindlist
qi::rule< Iterator,
carl::Variable(), Skipper > quantifiedVar
qi::rule< Iterator, FormulaT(),
Skipper > formula
qi::rule< Iterator, FormulaT(),
Skipper > formula_op
qi::rule< Iterator, FormulasT(),
Skipper > formula_list
Friends
class EqualityGenerator
Detailed Description
Definition at line 22 of file FormulaParser.h.
Constructor & Destructor Documentation
smtrat::parser::FormulaParser::FormulaParser (ParserState * state)
Definition at line 14 of file FormulaParser.cpp.
Member Function Documentation
FormulaT smtrat::parser::FormulaParser::mkConstraint (const Poly & lhs, const Poly & rhs, carl::Relation rel) private
Definition at line 71 of file FormulaParser.cpp.
Referenced by FormulaParser(), and smtrat::parser::EqualityGenerator::operator()().
FormulaT smtrat::parser::FormulaParser::mkDistinct (const Arguments & args) private
Definition at line 176 of file FormulaParser.cpp.
Referenced by FormulaParser().
FormulaT smtrat::parser::FormulaParser::mkEquality (const Arguments & args) private
Definition at line 167 of file FormulaParser.cpp.
Referenced by FormulaParser().
FormulaT smtrat::parser::FormulaParser::mkFormula (carl::FormulaType _type, FormulasT & _subformulas) private
Definition at line 65 of file FormulaParser.cpp.
Referenced by FormulaParser().
Friends And Related Function Documentation
friend class EqualityGenerator friend
Definition at line 24 of file FormulaParser.h.
Field Documentation
AttributeParser smtrat::parser::FormulaParser::attribute private
Definition at line 38 of file FormulaParser.h.
Referenced by FormulaParser().
qi::rule<Iterator, qi::unused_type, Skipper, qi::locals<std::string> > smtrat::parser::FormulaParser::binding private
Definition at line 44 of file FormulaParser.h.
Referenced by FormulaParser().
qi::rule<Iterator, qi::unused_type, Skipper> smtrat::parser::FormulaParser::bindlist private
Definition at line 45 of file FormulaParser.h.
Referenced by FormulaParser().
BitvectorParser smtrat::parser::FormulaParser::bitvector private
Definition at line 39 of file FormulaParser.h.
BoundaryParser smtrat::parser::FormulaParser::boundary private
Definition at line 33 of file FormulaParser.h.
Referenced by FormulaParser().
DomainParser smtrat::parser::FormulaParser::domain private
Definition at line 37 of file FormulaParser.h.
Referenced by FormulaParser().
qi::rule<Iterator, FormulaT(), Skipper> smtrat::parser::FormulaParser::formula private
Definition at line 48 of file FormulaParser.h.
Referenced by FormulaParser().
qi::rule<Iterator, FormulasT(), Skipper> smtrat::parser::FormulaParser::formula_list private
Definition at line 50 of file FormulaParser.h.
Referenced by FormulaParser().
qi::rule<Iterator, FormulaT(), Skipper> smtrat::parser::FormulaParser::formula_op private
Definition at line 49 of file FormulaParser.h.
Referenced by FormulaParser().
FunctionArgumentParser smtrat::parser::FormulaParser::fun_argument private
Definition at line 42 of file FormulaParser.h.
Referenced by FormulaParser().
BooleanOpParser smtrat::parser::FormulaParser::op_bool private
Definition at line 35 of file FormulaParser.h.
Referenced by FormulaParser().
PolynomialParser smtrat::parser::FormulaParser::polynomial private
Definition at line 41 of file FormulaParser.h.
Referenced by FormulaParser().
qi::rule<Iterator, carl::Variable(), Skipper> smtrat::parser::FormulaParser::quantifiedVar private
Definition at line 46 of file FormulaParser.h.
Referenced by FormulaParser().
RelationParser smtrat::parser::FormulaParser::relation private
Definition at line 36 of file FormulaParser.h.
Referenced by FormulaParser().
ParserState* smtrat::parser::FormulaParser::state private
Definition at line 26 of file FormulaParser.h.
Referenced by FormulaParser(), and mkConstraint().
SymbolParser smtrat::parser::FormulaParser::symbol private
Definition at line 34 of file FormulaParser.h.
Referenced by FormulaParser().
UninterpretedParser smtrat::parser::FormulaParser::uninterpreted private
Definition at line 40 of file FormulaParser.h.
Referenced by FormulaParser().
The documentation for this struct was generated from the following files:
cli/parser/FormulaParser.h
cli/parser/FormulaParser.cpp