SMT-RAT: smtrat::parser::BitvectorParser Struct Reference
smtrat::parser::BitvectorParser Struct Reference
#include <BitvectorParser.h>
Public Member Functions
BitvectorParser (ParserState *state)
Private Member Functions
BitvectorType createVariable (const carl::BVVariable &bvv) const
BitvectorType createUnary (carl::BVTermType type, const BitvectorType &a) const
BitvectorType createBinary (carl::BVTermType type, const BitvectorType &a, const BitvectorType &b) const
Private Attributes
ParserState * state
BitvectorUnaryOpParser buop
BitvectorBinaryOpParser bbop
qi::rule< Iterator,
BitvectorType(), Skipper > bitvector
Detailed Description
Definition at line 22 of file BitvectorParser.h.
Constructor & Destructor Documentation
smtrat::parser::BitvectorParser::BitvectorParser (ParserState * state)
Definition at line 8 of file BitvectorParser.cpp.
Member Function Documentation
BitvectorType smtrat::parser::BitvectorParser::createBinary (carl::BVTermType type, const BitvectorType & a, const BitvectorType & b) const inline private
Definition at line 33 of file BitvectorParser.h.
Referenced by BitvectorParser().
BitvectorType smtrat::parser::BitvectorParser::createUnary (carl::BVTermType type, const BitvectorType & a) const inline private
Definition at line 30 of file BitvectorParser.h.
Referenced by BitvectorParser().
BitvectorType smtrat::parser::BitvectorParser::createVariable (const carl::BVVariable & bvv) const inline private
Definition at line 27 of file BitvectorParser.h.
Referenced by BitvectorParser().
Field Documentation
BitvectorBinaryOpParser smtrat::parser::BitvectorParser::bbop private
Definition at line 38 of file BitvectorParser.h.
Referenced by BitvectorParser().
qi::rule<Iterator, BitvectorType(), Skipper> smtrat::parser::BitvectorParser::bitvector private
Definition at line 39 of file BitvectorParser.h.
Referenced by BitvectorParser().
BitvectorUnaryOpParser smtrat::parser::BitvectorParser::buop private
Definition at line 37 of file BitvectorParser.h.
Referenced by BitvectorParser().
ParserState* smtrat::parser::BitvectorParser::state private
Definition at line 25 of file BitvectorParser.h.
Referenced by BitvectorParser().
The documentation for this struct was generated from the following files:
cli/parser/BitvectorParser.h
cli/parser/BitvectorParser.cpp