carl: carl::UnivariatePolynomial< Coefficient > Class Template Reference
carl::UnivariatePolynomial< Coefficient > Class Template Reference
Polynomials » Univariate Represented Polynomials
This class represents a univariate polynomial with coefficients of an arbitrary type.
#include <MultivariateGCD.h>
Public Types
using NumberType = typename UnderlyingNumberType< Coefficient >::type
The number type that is ultimately used for the coefficients.
using IntNumberType = typename IntegralType< NumberType >::type
The integral type that belongs to the number type.
using CACHE = void
using CoeffType = Coefficient
using PolyType = UnivariatePolynomial< Coefficient >
Public Member Functions
UnivariatePolynomial ()=delete
Default constructor shall not exist.
UnivariatePolynomial (const UnivariatePolynomial &p)
Copy constructor.
UnivariatePolynomial (UnivariatePolynomial &&p) noexcept
Move constructor.
UnivariatePolynomial & operator= (const UnivariatePolynomial &p)
Copy assignment operator.
UnivariatePolynomial & operator= (UnivariatePolynomial &&p) noexcept
Move assignment operator.
UnivariatePolynomial (Variable mainVar)
Construct a zero polynomial with the given main variable.
UnivariatePolynomial (Variable mainVar, const Coefficient &coeff, std::size_t degree=0)
Construct .
UnivariatePolynomial (Variable mainVar, std::initializer_list< Coefficient > coefficients)
Construct polynomial with the given coefficients.
template<typename C = Coefficient, DisableIf< std::is_same< C, typename UnderlyingNumberType< C >::type >> = dummy>
UnivariatePolynomial (Variable mainVar, std::initializer_list< typename UnderlyingNumberType< C >::type > coefficients)
Construct polynomial with the given coefficients from the underlying number type of the coefficient type.
UnivariatePolynomial (Variable mainVar, const std::vector< Coefficient > &coefficients)
Construct polynomial with the given coefficients.
UnivariatePolynomial (Variable mainVar, std::vector< Coefficient > &&coefficients)
Construct polynomial with the given coefficients, moving the coefficients.
UnivariatePolynomial (Variable mainVar, const std::map< uint, Coefficient > &coefficients)
Construct polynomial with the given coefficients.
~UnivariatePolynomial () override=default
Destructor.
bool isUnivariateRepresented () const override
Checks if the polynomial is represented univariately.
bool isMultivariateRepresented () const override
Checks if the polynomial is represented multivariately.
bool isZero () const
Checks if the polynomial is equal to zero.
bool isOne () const
Checks if the polynomial is equal to one.
template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial one () const
Creates a polynomial of value one with the same main variable.
template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial one () const
Creates a polynomial of value one with the same main variable.
const Coefficient & lcoeff () const
Returns the leading coefficient.
const Coefficient & tcoeff () const
Returns the trailing coefficient.
bool isConstant () const
Checks whether the polynomial is constant with respect to the main variable.
bool isLinearInMainVar () const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool isNumber () const
Checks whether the polynomial is only a number.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool isNumber () const
Checks whether the polynomial is only a number.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
NumberType constantPart () const
Returns the constant part of this polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
NumberType constantPart () const
Returns the constant part of this polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool isUnivariate () const
Checks if the polynomial is univariate, that means if only one variable occurs.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool isUnivariate () const
Checks if the polynomial is univariate, that means if only one variable occurs.
uint degree () const
Get the maximal exponent of the main variable.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
uint totalDegree () const
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
uint totalDegree () const
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
std::size_t complexity () const
void truncate ()
Removes the leading term from the polynomial.
const std::vector< Coefficient > & coefficients () const
Retrieves the coefficients defining this polynomial.
Variable mainVar () const
Retrieves the main variable of this polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial< MultivariatePolynomial< NumberType > > switchVariable (Variable newVar) const
Switches the main variable using a purely syntactical restructuring.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial switchVariable (Variable newVar) const
Switches the main variable using a purely syntactical restructuring.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial replaceVariable (Variable newVar) const
Replaces the main variable.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial replaceVariable (Variable newVar) const
Replaces the main variable.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
std::set< Variable > gatherVariables () const
Gathers all variables that occur in the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
std::set< Variable > gatherVariables () const
Gathers all variables that occur in the polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
void gatherVariables (std::set< Variable > &vars) const
Gathers all variables that occur in the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
void gatherVariables (std::set< Variable > &set) const
Gathers all variables that occur in the polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool has (Variable v) const
Checks if the given variable occurs in the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool has (Variable v) const
Checks if the given variable occurs in the polynomial.
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
Coefficient coprimeFactor () const
Calculates a factor that would make the coefficients of this polynomial coprime integers.
template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy>
UnderlyingNumberType< Coefficient >::type coprimeFactor () const
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
UnivariatePolynomial< typename IntegralType< Coefficient >::type > coprimeCoefficients () const
Constructs a new polynomial that is scaled such that the coefficients are coprime.
template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy>
UnivariatePolynomial< Coefficient > coprimeCoefficients () const
bool isNormal () const
Checks whether the polynomial is unit normal.
UnivariatePolynomial normalized () const
The normal part of a polynomial is the polynomial divided by the unit part.
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
const Coefficient & unitPart () const
The unit part of a polynomial over a field is its leading coefficient for nonzero polynomials, and one for zero polynomials.
template<typename C = Coefficient, EnableIf< Not< is_number< C >> > = dummy>
Coefficient unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
template<typename C = Coefficient, EnableIf< Not< is_field< C >>, is_number< C >> = dummy>
Coefficient unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
Coefficient content () const
The content of a polynomial is the gcd of the coefficients of the normal part of a polynomial.
UnivariatePolynomial primitivePart () const
The primitive part of p is the normal part of p divided by the content of p.
UnivariatePolynomial derivative (uint nth=1) const
The n'th derivative of the polynomial in its main variable.
UnivariatePolynomial remainder (const UnivariatePolynomial &divisor, const Coefficient &prefactor) const
UnivariatePolynomial remainder (const UnivariatePolynomial &divisor) const
UnivariatePolynomial prem_old (const UnivariatePolynomial &divisor) const
Calculates the pseudo-remainder.
UnivariatePolynomial prem (const UnivariatePolynomial &divisor) const
UnivariatePolynomial sprem (const UnivariatePolynomial &divisor) const
UnivariatePolynomial negateVariable () const
Constructs a new polynomial q such that where p is this polynomial.
template<typename C = Coefficient, EnableIf< is_integer< C >> = dummy>
DivisionResult< UnivariatePolynomial > divideBy (const UnivariatePolynomial &divisor) const
Divides the polynomial by another polynomial.
template<typename C = Coefficient, DisableIf< is_integer< C >> = dummy, EnableIf< is_field< C >> = dummy>
DivisionResult< UnivariatePolynomial > divideBy (const UnivariatePolynomial &divisor) const
Divides the polynomial by another polynomial.
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
DivisionResult< UnivariatePolynomial > divideBy (const Coefficient &divisor) const
Divides the polynomial by a coefficient.
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy>
bool divideBy (const Coefficient &divisor, UnivariatePolynomial &quotient) const
Divides the polynomial by a coefficient.
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy, EnableIf< is_field< typename UnderlyingNumberType< C >::type >> = dummy>
DivisionResult< UnivariatePolynomial > divideBy (const NumberType &divisor) const
Divides the polynomial by a number.
bool divides (const UnivariatePolynomial &divisor) const
Checks if this polynomial is divisible by the given divisor, that is if the remainder is zero.
UnivariatePolynomial & mod (const Coefficient &modulus)
Replaces every coefficient c by c mod modulus.
UnivariatePolynomial mod (const Coefficient &modulus) const
Constructs a new polynomial where every coefficient c is replaced by c mod modulus.
UnivariatePolynomial pow (std::size_t exp) const
Returns this polynomial to the given power.
Coefficient evaluate (const Coefficient &value) const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
void substituteIn (Variable var, const Coefficient &value)
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
void substituteIn (Variable var, const Coefficient &value)
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial substitute (Variable var, const Coefficient &value) const
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial substitute (Variable var, const Coefficient &value) const
carl::Sign sgn (const Coefficient &value) const
Calculates the sign of the polynomial at some point.
bool isRoot (const Coefficient &value) const
template<typename SubstitutionType , typename C = Coefficient, EnableIf< is_instantiation_of< MultivariatePolynomial, C >> = dummy>
UnivariatePolynomial< Coefficient > evaluateCoefficient (const std::map< Variable, SubstitutionType > &) const
template<typename SubstitutionType , typename C = Coefficient, DisableIf< is_instantiation_of< MultivariatePolynomial, C >> = dummy>
UnivariatePolynomial< Coefficient > evaluateCoefficient (const std::map< Variable, SubstitutionType > &) const
template<typename T = Coefficient, EnableIf< has_normalize< T >> = dummy>
UnivariatePolynomial & normalizeCoefficients ()
template<typename T = Coefficient, DisableIf< has_normalize< T >> = dummy>
UnivariatePolynomial & normalizeCoefficients ()
template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial< typename IntegralType< Coefficient >::type > toIntegerDomain () const
Works only from rationals, if the numbers are already integers.
template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial< typename IntegralType< Coefficient >::type > toIntegerDomain () const
UnivariatePolynomial< GFNumber< typename IntegralType< Coefficient >::type > > toFiniteDomain (const GaloisField< typename IntegralType< Coefficient >::type > *galoisField) const
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial< NumberType > toNumberCoefficients (bool check=true) const
template<typename NewCoeff >
UnivariatePolynomial< NewCoeff > convert () const
template<typename NewCoeff >
UnivariatePolynomial< NewCoeff > convert (const std::function< NewCoeff(const Coefficient &)> &f) const
Coefficient cauchyBound () const
Notice, Cauchy bounds are only defined for polynomials over fields.
Coefficient modifiedCauchyBound () const
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
IntNumberType maximumNorm () const
The maximum norm of a polynomial is the maximum absolute value of the coefficients of the corresponding integral polynomial (as calculated by coprimeCoefficients()).
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
NumberType numericContent (std::size_t i) const
Returns the numeric content part of the i'th coefficient.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
NumberType numericContent (std::size_t i) const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
NumberType numericUnit () const
Returns the numeric unit part of the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
NumberType numericUnit () const
template<typename N = NumberType, EnableIf< is_subset_of_rationals< N >> = dummy>
UnderlyingNumberType< Coefficient >::type numericContent () const
Obtains the numeric content part of this polynomial.
UnivariatePolynomial pseudoPrimpart () const
Returns this/divisor where divisor is the numeric content of this polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
IntNumberType mainDenom () const
Compute the main denominator of all numeric coefficients of this polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
IntNumberType mainDenom () const
FactorMap< Coefficient > factorization () const
Coefficient syntheticDivision (const Coefficient &zeroOfDivisor)
std::map< uint, UnivariatePolynomial > squareFreeFactorization () const
bool zeroIsRoot () const
Checks if zero is a real root of this polynomial.
void eliminateZeroRoots ()
Reduces the polynomial such that zero is not a root anymore.
void eliminateRoot (const Coefficient &root)
Reduces the polynomial such that the given root is not a root anymore.
std::list< UnivariatePolynomial > standardSturmSequence () const
std::list< UnivariatePolynomial > standardSturmSequence (const UnivariatePolynomial &polynomial) const
uint signVariations (const Interval< Coefficient > &interval) const
Counts the sign variations (i.e.
int countRealRoots (const Interval< Coefficient > &interval) const
Count the number of real roots within the given interval using Sturm sequences.
UnivariatePolynomial< Coefficient > resultant (const UnivariatePolynomial< Coefficient > &p, SubresultantStrategy strategy=SubresultantStrategy::Default) const
UnivariatePolynomial< Coefficient > discriminant (SubresultantStrategy strategy=SubresultantStrategy::Default) const
bool less (const UnivariatePolynomial< Coefficient > &rhs, const PolynomialComparisonOrder &order=PolynomialComparisonOrder::Default) const
UnivariatePolynomial operator- () const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool isConsistent () const
Asserts that this polynomial over numeric coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool isConsistent () const
Asserts that this polynomial over polynomial coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
In-place addition operators
UnivariatePolynomial & operator+= (const Coefficient &rhs)
Add something to this polynomial and return the changed polynomial.
UnivariatePolynomial & operator+= (const UnivariatePolynomial &rhs)
Add something to this polynomial and return the changed polynomial.
In-place subtraction operators
UnivariatePolynomial & operator-= (const Coefficient &rhs)
Subtract something from this polynomial and return the changed polynomial.
UnivariatePolynomial & operator-= (const UnivariatePolynomial &rhs)
Subtract something from this polynomial and return the changed polynomial.
In-place multiplication operators
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial & operator*= (Variable rhs)
Multiply this polynomial with something and return the changed polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial & operator*= (Variable rhs)
Multiply this polynomial with something and return the changed polynomial.
UnivariatePolynomial & operator*= (const Coefficient &rhs)
Multiply this polynomial with something and return the changed polynomial.
template<typename I = Coefficient, DisableIf< std::is_same< Coefficient, I >> ...>
UnivariatePolynomial & operator*= (const typename IntegralType< Coefficient >::type &rhs)
Multiply this polynomial with something and return the changed polynomial.
UnivariatePolynomial & operator*= (const UnivariatePolynomial &rhs)
Multiply this polynomial with something and return the changed polynomial.
In-place division operators
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
UnivariatePolynomial & operator/= (const Coefficient &rhs)
Divide this polynomial by something and return the changed polynomial.
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy>
UnivariatePolynomial & operator/= (const Coefficient &rhs)
Divide this polynomial by something and return the changed polynomial.
Static Public Member Functions
static UnivariatePolynomial gcd (const UnivariatePolynomial &a, const UnivariatePolynomial &b)
Calculates the greatest common divisor of two polynomials.
static UnivariatePolynomial extended_gcd (const UnivariatePolynomial &a, const UnivariatePolynomial &b, UnivariatePolynomial &s, UnivariatePolynomial &t)
Calculates the extended greatest common divisor g of two polynomials.
template<typename Integer >
static UnivariatePolynomial excludeLinearFactors (const UnivariatePolynomial &poly, FactorMap< Coefficient > &linearFactors, const Integer &maxInt=0)
template<typename C = Coefficient, typename Number = typename UnderlyingNumberType<C>::type>
static int countRealRoots (const std::list< UnivariatePolynomial< Coefficient >> &seq, const Interval< Number > &interval)
Calculate the number of real roots of a polynomial within a given interval based on a sturm sequence of this polynomial.
static std::list< UnivariatePolynomial > subresultants (const UnivariatePolynomial &p, const UnivariatePolynomial &q, SubresultantStrategy strategy=SubresultantStrategy::Default)
Implements subresultants algorithm with optimizations described in [2] .
static const std::vector< UnivariatePolynomial > principalSubresultantsCoefficients (const UnivariatePolynomial &p, const UnivariatePolynomial &q, SubresultantStrategy strategy=SubresultantStrategy::Default)
Private Member Functions
void reverse ()
Reverses the order of the coefficients of this polynomial.
void scale (const Coefficient &factor)
Scale the variable, i.e.
void shift (const Coefficient &a)
Shift the variable by a, i.e.
UnivariatePolynomial remainder_helper (const UnivariatePolynomial &divisor, const Coefficient *prefactor=nullptr) const
Calculates the remainder of polynomial division.
void stripLeadingZeroes ()
Static Private Member Functions
static UnivariatePolynomial gcd_recursive (const UnivariatePolynomial &a, const UnivariatePolynomial &b)
Private Attributes
Variable mMainVar
The main variable.
std::vector< Coefficient > mCoefficients
The coefficients.
Friends
template<class T >
class UnivariatePolynomial
Declare all instantiations of univariate polynomials as friends.
template<typename C >
bool operator< (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
template<typename C >
std::ostream & operator<< (std::ostream &os, const UnivariatePolynomial< C > &rhs)
Streaming operator for univariate polynomials.
Equality comparison operators
template<typename C >
bool operator== (const C &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are equal.
template<typename C >
bool operator== (const UnivariatePolynomial< C > &lhs, const C &rhs)
Checks if the two arguments are equal.
template<typename C >
bool operator== (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are equal.
template<typename C >
bool operator== (const UnivariatePolynomialPtr< C > &lhs, const UnivariatePolynomialPtr< C > &rhs)
Checks if the two arguments are equal.
Inequality comparison operators
template<typename C >
bool operator!= (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are not equal.
template<typename C >
bool operator!= (const UnivariatePolynomialPtr< C > &lhs, const UnivariatePolynomialPtr< C > &rhs)
Checks if the two arguments are not equal.
Addition operators
template<typename C >
UnivariatePolynomial< C > operator+ (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Performs an addition involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator+ (const C &lhs, const UnivariatePolynomial< C > &rhs)
Performs an addition involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator+ (const UnivariatePolynomial< C > &lhs, const C &rhs)
Performs an addition involving a polynomial.
Subtraction operators
template<typename C >
UnivariatePolynomial< C > operator- (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Performs a subtraction involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator- (const C &lhs, const UnivariatePolynomial< C > &rhs)
Performs a subtraction involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator- (const UnivariatePolynomial< C > &lhs, const C &rhs)
Performs a subtraction involving a polynomial.
Multiplication operators
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, Variable rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (Variable lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const C &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, const C &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const IntegralTypeIfDifferent< C > &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, const IntegralTypeIfDifferent< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
UnivariatePolynomial< MultivariatePolynomial< C, O, P > > operator* (const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> &lhs, const C &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
UnivariatePolynomial< MultivariatePolynomial< C, O, P > > operator* (const C &lhs, const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> &rhs)
Perform a multiplication involving a polynomial.
Division operators
template<typename C >
UnivariatePolynomial< C > operator/ (const UnivariatePolynomial< C > &lhs, const C &rhs)
Perform a division involving a polynomial.
Detailed Description
template<typename Coefficient>
class carl::UnivariatePolynomial< Coefficient >
This class represents a univariate polynomial with coefficients of an arbitrary type.
A univariate polynomial is defined by a variable (the main variable) and the coefficients. The coefficients may be of any type. The intention is to use a numbers or polynomials as coefficients. If polynomials are used as coefficients, this can be seen as a multivariate polynomial with a distinguished main variable.
Most methods are specifically adapted for polynomial coefficients, if necessary.
Definition at line 21 of file MultivariateGCD.h.
Member Typedef Documentation
CACHE
template<typename Coefficient> using carl::UnivariatePolynomial< Coefficient >::CACHE = void
Definition at line 83 of file UnivariatePolynomial.h.
CoeffType
template<typename Coefficient> using carl::UnivariatePolynomial< Coefficient >::CoeffType = Coefficient
Definition at line 84 of file UnivariatePolynomial.h.
IntNumberType
template<typename Coefficient> using carl::UnivariatePolynomial< Coefficient >::IntNumberType = typename IntegralType<NumberType>::type
The integral type that belongs to the number type.
Definition at line 81 of file UnivariatePolynomial.h.
NumberType
template<typename Coefficient> using carl::UnivariatePolynomial< Coefficient >::NumberType = typename UnderlyingNumberType<Coefficient>::type
The number type that is ultimately used for the coefficients.
Definition at line 77 of file UnivariatePolynomial.h.
PolyType
template<typename Coefficient> using carl::UnivariatePolynomial< Coefficient >::PolyType = UnivariatePolynomial<Coefficient>
Definition at line 85 of file UnivariatePolynomial.h.
Constructor & Destructor Documentation
UnivariatePolynomial() [1/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial () delete
Default constructor shall not exist.
Use UnivariatePolynomial(Variable) instead.
Referenced by carl::UnivariatePolynomial< Coeff >::one().
UnivariatePolynomial() [2/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (const UnivariatePolynomial< Coefficient > & p)
Copy constructor.
UnivariatePolynomial() [3/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (UnivariatePolynomial< Coefficient > && p) noexcept
Move constructor.
UnivariatePolynomial() [4/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar) explicit
Construct a zero polynomial with the given main variable.
Parameters
mainVar New main variable.
UnivariatePolynomial() [5/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar, const Coefficient & coeff, std::size_t degree = 0)
Construct .
Parameters
mainVar New main variable.
coeff Leading coefficient.
degree Degree.
UnivariatePolynomial() [6/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar, std::initializer_list< Coefficient > coefficients)
Construct polynomial with the given coefficients.
Parameters
mainVar New main variable.
coefficients List of coefficients.
UnivariatePolynomial() [7/10]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< std::is_same< C, typename UnderlyingNumberType< C >::type >> = dummy> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar, std::initializer_list< typename UnderlyingNumberType< C >::type > coefficients)
Construct polynomial with the given coefficients from the underlying number type of the coefficient type.
Parameters
mainVar New main variable.
coefficients List of coefficients.
UnivariatePolynomial() [8/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar, const std::vector< Coefficient > & coefficients)
Construct polynomial with the given coefficients.
Parameters
mainVar New main variable.
coefficients Vector of coefficients.
UnivariatePolynomial() [9/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar, std::vector< Coefficient > && coefficients)
Construct polynomial with the given coefficients, moving the coefficients.
Parameters
mainVar New main variable.
coefficients Vector of coefficients.
UnivariatePolynomial() [10/10]
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable mainVar, const std::map< uint, Coefficient > & coefficients)
Construct polynomial with the given coefficients.
Parameters
mainVar New main variable.
coefficients Assignment of degree to coefficients.
~UnivariatePolynomial()
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::~UnivariatePolynomial () override default
Destructor.
Member Function Documentation
cauchyBound()
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::cauchyBound () const
Notice, Cauchy bounds are only defined for polynomials over fields.
This is
Returns
coefficients()
template<typename Coefficient> const std::vector<Coefficient>& carl::UnivariatePolynomial< Coefficient >::coefficients () const inline
Retrieves the coefficients defining this polynomial.
Returns
Coefficients.
Definition at line 396 of file UnivariatePolynomial.h.
Referenced by carl::cauchyBound(), carl::IntervalEvaluation::evaluate(), carl::hirstMaceyBound(), carl::UnivariatePolynomial< Coeff >::isUnivariate(), carl::lagrangeBound(), carl::ThomEncoding< Number >::makesPolynomialZero(), carl::GiNaCConverter::operator()(), std::hash< carl::UnivariatePolynomial< Coefficient > >::operator()(), carl::subresultants(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
complexity()
template<typename Coefficient> std::size_t carl::UnivariatePolynomial< Coefficient >::complexity () const inline
Returns
An approximation of the complexity of this polynomial.
Definition at line 374 of file UnivariatePolynomial.h.
constantPart() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::constantPart () const inline
Returns the constant part of this polynomial.
Applies, if the coefficients are numbers.
Returns
Constant part.
Definition at line 287 of file UnivariatePolynomial.h.
Referenced by carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
constantPart() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::constantPart () const inline
Returns the constant part of this polynomial.
Applies, if the coefficients are not numbers. Calls constantPart() on the trailing coefficient recursively.
Returns
Constant part.
Definition at line 299 of file UnivariatePolynomial.h.
content()
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::content () const
The content of a polynomial is the gcd of the coefficients of the normal part of a polynomial.
The content of zero is zero.
See also
[3], page 52
Returns
The content of the polynomial.
Referenced by carl::resultant_debug::resultant_z3().
convert() [1/2]
template<typename Coefficient> template<typename NewCoeff > UnivariatePolynomial<NewCoeff> carl::UnivariatePolynomial< Coefficient >::convert () const
Referenced by carl::rootfinder::realRoots(), and carl::realRootsThom().
convert() [2/2]
template<typename Coefficient> template<typename NewCoeff > UnivariatePolynomial<NewCoeff> carl::UnivariatePolynomial< Coefficient >::convert (const std::function< NewCoeff(const Coefficient &)> & f) const
coprimeCoefficients() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy> UnivariatePolynomial<typename IntegralType<Coefficient>::type> carl::UnivariatePolynomial< Coefficient >::coprimeCoefficients () const
Constructs a new polynomial that is scaled such that the coefficients are coprime.
It is calculated by multiplying it with the coprime factor. By definition, this results in a polynomial with integral coefficients.
Returns
This polynomial multiplied with the coprime factor.
Referenced by carl::squareFreePart().
coprimeCoefficients() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy> UnivariatePolynomial<Coefficient> carl::UnivariatePolynomial< Coefficient >::coprimeCoefficients () const
coprimeFactor() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy> Coefficient carl::UnivariatePolynomial< Coefficient >::coprimeFactor () const
Calculates a factor that would make the coefficients of this polynomial coprime integers.
We consider a set of integers coprime, if they share no common factor. Technically, the coprime factor is where N is the set of the numerators and D is the set of the denominators of all coefficients.
Returns
Coprime factor of this polynomial.
coprimeFactor() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy> UnderlyingNumberType<Coefficient>::type carl::UnivariatePolynomial< Coefficient >::coprimeFactor () const
countRealRoots() [1/2]
template<typename Coefficient> int carl::UnivariatePolynomial< Coefficient >::countRealRoots (const Interval< Coefficient > & interval) const
Count the number of real roots within the given interval using Sturm sequences.
Parameters
interval Count roots within this interval.
Returns
Number of real roots within the interval.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluateIR(), carl::RealAlgebraicNumber< carl::Number >::isRootOf(), carl::ran::IntervalContent< Number >::refine(), and carl::ran::IntervalContent< Number >::refineAvoiding().
countRealRoots() [2/2]
template<typename Coefficient> template<typename C = Coefficient, typename Number = typename UnderlyingNumberType<C>::type> static int carl::UnivariatePolynomial< Coefficient >::countRealRoots (const std::list< UnivariatePolynomial< Coefficient >> & seq, const Interval< Number > & interval) static
Calculate the number of real roots of a polynomial within a given interval based on a sturm sequence of this polynomial.
Parameters
seq Sturm sequence.
interval Interval.
Returns
Number of real roots in the interval.
degree()
template<typename Coefficient> uint carl::UnivariatePolynomial< Coefficient >::degree () const inline
Get the maximal exponent of the main variable.
As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[3], page 38
Returns
Degree.
Definition at line 333 of file UnivariatePolynomial.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::discriminant(), carl::resultant_debug::eliminate(), carl::IntervalEvaluation::evaluate(), carl::lagrangeBound(), carl::resultant_debug::resultant_det(), carl::resultant_debug::resultant_z3(), carl::signAtMinusInf(), carl::subresultants(), and carl::UnivariatePolynomial< Coeff >::totalDegree().
derivative()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::derivative (uint nth = 1) const
The n'th derivative of the polynomial in its main variable.
Parameters
nth how many times the derivative should be applied.
Returns
A polynomial where is the input polynomial.
Referenced by carl::discriminant(), carl::ran::IntervalContent< Number >::sgn(), carl::squareFreePart(), carl::TarskiQueryManager< carl::Number >::TarskiQueryManager(), and carl::univariateTarskiQuery().
discriminant()
template<typename Coefficient> UnivariatePolynomial<Coefficient> carl::UnivariatePolynomial< Coefficient >::discriminant (SubresultantStrategy strategy = SubresultantStrategy::Default) const inline
Definition at line 995 of file UnivariatePolynomial.h.
divideBy() [1/5]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_integer< C >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const UnivariatePolynomial< Coefficient > & divisor) const
Divides the polynomial by another polynomial.
Applies if the polynomial both have integer coefficients.
Parameters
divisor Divisor.
Returns
this / divisor.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::discriminant(), carl::DiophantineEquations< Integer >::EEAlift(), carl::UnivariatePolynomial< Coeff >::pseudoPrimpart(), carl::squareFreePart(), and carl::subresultants().
divideBy() [2/5]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_integer< C >> = dummy, EnableIf< is_field< C >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const UnivariatePolynomial< Coefficient > & divisor) const
Divides the polynomial by another polynomial.
Applies if the polynomial both have coefficients over a field.
Parameters
divisor Divisor.
Returns
this / divisor.
divideBy() [3/5]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const Coefficient & divisor) const
Divides the polynomial by a coefficient.
Applies if the polynomial has coefficients from a field.
Parameters
divisor Divisor.
Returns
this / divisor.
divideBy() [4/5]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::divideBy (const Coefficient & divisor, UnivariatePolynomial< Coefficient > & quotient) const
Divides the polynomial by a coefficient.
If the divisor divides this polynomial, quotient contains the result of the division and true is returned. Otherwise, false is returned and the content of quotient is undefined. Applies if the polynomial has coefficients that are neither numeric nor from a field.
Parameters
divisor Divisor.
quotient Resulting quotient.
Returns
If remainder was zero.
divideBy() [5/5]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy, EnableIf< is_field< typename UnderlyingNumberType< C >::type >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const NumberType & divisor) const
Divides the polynomial by a number.
Applies if the polynomial has coefficients that are polynomials with coefficients from a field.
Parameters
divisor Divisor.
Returns
Quotient and remainder.
divides()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::divides (const UnivariatePolynomial< Coefficient > & divisor) const
Checks if this polynomial is divisible by the given divisor, that is if the remainder is zero.
Parameters
divisor Polynomial.
Returns
If divisor divides this polynomial.
eliminateRoot()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::eliminateRoot (const Coefficient & root)
Reduces the polynomial such that the given root is not a root anymore.
The reduction is achieved by removing the linear factor (mainVar - root) from the polynomial, possibly multiple times.
This method assumes that the given root is an actual real root of this polynomial. If this is not the case, i.e. evaluate(root) != 0, the polynomial will contain meaningless garbage.
Parameters
root Root to be eliminated.
eliminateZeroRoots()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::eliminateZeroRoots ()
Reduces the polynomial such that zero is not a root anymore.
Is functionally equivalent to eliminateRoot(0), but much faster.
evaluate()
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::evaluate (const Coefficient & value) const
Referenced by carl::UnivariatePolynomial< Coeff >::sgn().
evaluateCoefficient() [1/2]
template<typename Coefficient> template<typename SubstitutionType , typename C = Coefficient, EnableIf< is_instantiation_of< MultivariatePolynomial, C >> = dummy> UnivariatePolynomial<Coefficient> carl::UnivariatePolynomial< Coefficient >::evaluateCoefficient (const std::map< Variable, SubstitutionType > &) const inline
Definition at line 765 of file UnivariatePolynomial.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
evaluateCoefficient() [2/2]
template<typename Coefficient> template<typename SubstitutionType , typename C = Coefficient, DisableIf< is_instantiation_of< MultivariatePolynomial, C >> = dummy> UnivariatePolynomial<Coefficient> carl::UnivariatePolynomial< Coefficient >::evaluateCoefficient (const std::map< Variable, SubstitutionType > &) const inline
Definition at line 770 of file UnivariatePolynomial.h.
excludeLinearFactors()
template<typename Coefficient> template<typename Integer > static UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::excludeLinearFactors (const UnivariatePolynomial< Coefficient > & poly, FactorMap< Coefficient > & linearFactors, const Integer & maxInt = 0) static
extended_gcd()
template<typename Coefficient> static UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::extended_gcd (const UnivariatePolynomial< Coefficient > & a, const UnivariatePolynomial< Coefficient > & b, UnivariatePolynomial< Coefficient > & s, UnivariatePolynomial< Coefficient > & t) static
Calculates the extended greatest common divisor g of two polynomials.
The output polynomials s and t are computed such that .
Parameters
a First polynomial.
b Second polynomial.
s First output polynomial.
t Second output polynomial.
See also
[3], Algorithm 2.2
Returns
gcd(a,b)
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
factorization()
template<typename Coefficient> FactorMap<Coefficient> carl::UnivariatePolynomial< Coefficient >::factorization () const
gatherVariables() [1/4]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> std::set<Variable> carl::UnivariatePolynomial< Coefficient >::gatherVariables () const inline
Gathers all variables that occur in the polynomial.
Applies, if the coefficients are numbers.
Returns
Set of variables.
Definition at line 460 of file UnivariatePolynomial.h.
Referenced by carl::model::realRoots(), and carl::realRootsThom().
gatherVariables() [2/4]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> std::set<Variable> carl::UnivariatePolynomial< Coefficient >::gatherVariables () const inline
Gathers all variables that occur in the polynomial.
Applies, if the coefficients are not numbers.
Returns
Set of variables.
Definition at line 469 of file UnivariatePolynomial.h.
gatherVariables() [3/4]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> void carl::UnivariatePolynomial< Coefficient >::gatherVariables (std::set< Variable > & vars) const inline
Gathers all variables that occur in the polynomial.
Applies, if the coefficients are numbers.
Returns
Set of variables.
Definition at line 484 of file UnivariatePolynomial.h.
gatherVariables() [4/4]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> void carl::UnivariatePolynomial< Coefficient >::gatherVariables (std::set< Variable > & set) const inline
Gathers all variables that occur in the polynomial.
Applies, if the coefficients are not numbers.
Returns
Set of variables.
Definition at line 493 of file UnivariatePolynomial.h.
gcd()
template<typename Coefficient> static UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::gcd (const UnivariatePolynomial< Coefficient > & a, const UnivariatePolynomial< Coefficient > & b) static
Calculates the greatest common divisor of two polynomials.
Parameters
a First polynomial.
b Second polynomial.
Returns
gcd(a,b)
gcd_recursive()
template<typename Coefficient> static UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::gcd_recursive (const UnivariatePolynomial< Coefficient > & a, const UnivariatePolynomial< Coefficient > & b) static private
has() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::has (Variable v) const inline
Checks if the given variable occurs in the polynomial.
Applies, if the coefficients are numbers.
Parameters
v Variable.
Returns
If v occurs in the polynomial.
Definition at line 508 of file UnivariatePolynomial.h.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluatePolynomial().
has() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::has (Variable v) const inline
Checks if the given variable occurs in the polynomial.
Applies, if the coefficients are not numbers.
Parameters
v Variable.
Returns
If v occurs in the polynomial.
Definition at line 518 of file UnivariatePolynomial.h.
isConsistent() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isConsistent () const
Asserts that this polynomial over numeric coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
The leading term is not zero.
Referenced by carl::UnivariatePolynomial< Coeff >::isConstant(), carl::UnivariatePolynomial< Coeff >::isLinearInMainVar(), and carl::UnivariatePolynomial< Coeff >::switchVariable().
isConsistent() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isConsistent () const
Asserts that this polynomial over polynomial coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
The leading term is not zero.
The main variable does not occur in any coefficient.
isConstant()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isConstant () const inline
Checks whether the polynomial is constant with respect to the main variable.
Returns
If polynomial is constant.
Definition at line 246 of file UnivariatePolynomial.h.
Referenced by carl::cauchyBound(), carl::hirstMaceyBound(), carl::UnivariatePolynomial< Coeff >::isNumber(), carl::lagrangeBound(), carl::resultant(), carl::resultant_debug::resultant_det(), carl::resultant_debug::resultant_z3(), carl::subresultants(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
isLinearInMainVar()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isLinearInMainVar () const inline
Definition at line 252 of file UnivariatePolynomial.h.
Referenced by carl::discriminant(), and carl::squareFreePart().
isMultivariateRepresented()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isMultivariateRepresented () const inline override virtual
Checks if the polynomial is represented multivariately.
See also
Polynomial::isMultivariateRepresented
Returns
false.
Implements carl::Polynomial.
Definition at line 178 of file UnivariatePolynomial.h.
isNormal()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isNormal () const
Checks whether the polynomial is unit normal.
A polynomial is unit normal, if the leading coefficient is unit normal, that is if it is either one or minus one.
See also
[3], page 39
Returns
If polynomial is normal.
isNumber() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isNumber () const inline
Checks whether the polynomial is only a number.
Applies if the coefficients are numbers.
Returns
If polynomial is a number.
Definition at line 264 of file UnivariatePolynomial.h.
isNumber() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isNumber () const inline
Checks whether the polynomial is only a number.
Applies if the coefficients are not numbers. Calls isNumber() on the constant coefficient recursively.
Returns
If polynomial is a number.
Definition at line 275 of file UnivariatePolynomial.h.
isOne()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isOne () const inline
Checks if the polynomial is equal to one.
Returns
If polynomial is one.
Definition at line 196 of file UnivariatePolynomial.h.
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
isRoot()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isRoot (const Coefficient & value) const inline
Definition at line 760 of file UnivariatePolynomial.h.
Referenced by carl::ran::IntervalContent< Number >::refine(), and carl::ran::IntervalContent< Number >::refineAvoiding().
isUnivariate() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isUnivariate () const inline
Checks if the polynomial is univariate, that means if only one variable occurs.
Applies, if the coefficients are numbers.
Returns
true.
Definition at line 311 of file UnivariatePolynomial.h.
Referenced by carl::rootfinder::realRoots().
isUnivariate() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isUnivariate () const inline
Checks if the polynomial is univariate, that means if only one variable occurs.
Applies, if the coefficients are not numbers.
Returns
If polynomial is univariate.
Definition at line 320 of file UnivariatePolynomial.h.
isUnivariateRepresented()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isUnivariateRepresented () const inline override virtual
Checks if the polynomial is represented univariately.
See also
Polynomial::isUnivariateRepresented
Returns
true.
Implements carl::Polynomial.
Definition at line 168 of file UnivariatePolynomial.h.
isZero()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isZero () const inline
Checks if the polynomial is equal to zero.
Returns
If polynomial is zero.
Definition at line 187 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::complexity(), carl::UnivariatePolynomial< Coeff >::constantPart(), carl::UnivariatePolynomial< Coeff >::degree(), carl::RealAlgebraicNumberEvaluation::evaluateIR(), carl::UnivariatePolynomial< Coeff >::isNumber(), carl::TarskiQueryManager< carl::Number >::isUnivariateManager(), carl::realRootsThom(), carl::resultant(), carl::resultant_debug::resultant_det(), carl::resultant_debug::resultant_z3(), carl::signAtMinusInf(), carl::signAtPlusInf(), carl::squareFreePart(), carl::UnivariatePolynomial< Coeff >::stripLeadingZeroes(), carl::subresultants(), carl::TarskiQueryManager< carl::Number >::TarskiQueryManager(), carl::UnivariatePolynomial< Coeff >::totalDegree(), carl::univariateTarskiQuery(), and carl::UnivariatePolynomial< Coeff >::zeroIsRoot().
lcoeff()
template<typename Coefficient> const Coefficient& carl::UnivariatePolynomial< Coefficient >::lcoeff () const inline
Returns the leading coefficient.
Asserts, that the polynomial is not empty.
Returns
The leading coefficient.
Definition at line 227 of file UnivariatePolynomial.h.
Referenced by carl::cauchyBound(), carl::discriminant(), carl::resultant_debug::eliminate(), carl::hirstMaceyBound(), carl::UnivariatePolynomial< Coeff >::isNumber(), carl::lagrangeBound(), carl::UnivariatePolynomial< Coeff >::numericUnit(), carl::UnivariatePolynomial< Coeff >::one(), carl::resultant_debug::resultant_det(), carl::signAtMinusInf(), carl::signAtPlusInf(), carl::UnivariatePolynomial< Coeff >::stripLeadingZeroes(), and carl::subresultants().
less()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::less (const UnivariatePolynomial< Coefficient > & rhs, const PolynomialComparisonOrder & order = PolynomialComparisonOrder::Default) const
Referenced by std::less< carl::UnivariatePolynomial< Coefficient > >::operator()().
mainDenom() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> IntNumberType carl::UnivariatePolynomial< Coefficient >::mainDenom () const
Compute the main denominator of all numeric coefficients of this polynomial.
This method only applies if the Coefficient type is a number.
Returns
the main denominator of all coefficients of this polynomial.
mainDenom() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> IntNumberType carl::UnivariatePolynomial< Coefficient >::mainDenom () const
mainVar()
template<typename Coefficient> Variable carl::UnivariatePolynomial< Coefficient >::mainVar () const inline
Retrieves the main variable of this polynomial.
Returns
Main variable.
Definition at line 404 of file UnivariatePolynomial.h.
Referenced by carl::DiophantineEquations< Integer >::EEAlift(), carl::resultant_debug::eliminate(), carl::IntervalEvaluation::evaluate(), carl::RealAlgebraicNumberEvaluation::evaluateCoefficients(), carl::RealAlgebraicNumberEvaluation::evaluatePolynomial(), carl::UnivariatePolynomial< Coeff >::gatherVariables(), carl::UnivariatePolynomial< Coeff >::has(), carl::GiNaCConverter::operator()(), carl::TarskiQueryManager< carl::Number >::operator()(), carl::principalSubresultantsCoefficients(), carl::realRootsThom(), carl::UnivariatePolynomial< Coeff >::replaceVariable(), carl::resultant(), carl::resultant_debug::resultant_det(), carl::resultant_debug::resultant_z3(), carl::subresultants(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
maximumNorm()
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy> IntNumberType carl::UnivariatePolynomial< Coefficient >::maximumNorm () const
The maximum norm of a polynomial is the maximum absolute value of the coefficients of the corresponding integral polynomial (as calculated by coprimeCoefficients()).
Returns
Maximum-norm of the polynomial in case it has numeric coefficients.
mod() [1/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::mod (const Coefficient & modulus)
Replaces every coefficient c by c mod modulus.
Parameters
modulus Modulus.
Returns
This.
mod() [2/2]
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::mod (const Coefficient & modulus) const
Constructs a new polynomial where every coefficient c is replaced by c mod modulus.
Parameters
modulus Modulus.
Returns
New polynomial.
modifiedCauchyBound()
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::modifiedCauchyBound () const
negateVariable()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::negateVariable () const inline
Constructs a new polynomial q such that where p is this polynomial.
Returns
New polynomial with negated variable.
Definition at line 636 of file UnivariatePolynomial.h.
normalizeCoefficients() [1/2]
template<typename Coefficient> template<typename T = Coefficient, EnableIf< has_normalize< T >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::normalizeCoefficients () inline
Definition at line 777 of file UnivariatePolynomial.h.
Referenced by carl::DiophantineEquations< Integer >::EEAlift(), and carl::DiophantineEquations< Integer >::univariateDiophantine().
normalizeCoefficients() [2/2]
template<typename Coefficient> template<typename T = Coefficient, DisableIf< has_normalize< T >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::normalizeCoefficients () inline
Definition at line 787 of file UnivariatePolynomial.h.
normalized()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::normalized () const
The normal part of a polynomial is the polynomial divided by the unit part.
See also
[3], page 42.
Returns
This polynomial divided by the unit part.
Referenced by carl::resultant(), and carl::resultant_debug::resultant_z3().
numericContent() [1/3]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::numericContent (std::size_t i) const inline
Returns the numeric content part of the i'th coefficient.
If the coefficients are numbers, this is simply the i'th coefficient. If the coefficients are polynomials, this is the numeric content part of the i'th coefficient.
Parameters
i number of the coefficient
Returns
numeric content part of i'th coefficient.
Definition at line 839 of file UnivariatePolynomial.h.
numericContent() [2/3]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::numericContent (std::size_t i) const inline
Definition at line 844 of file UnivariatePolynomial.h.
numericContent() [3/3]
template<typename Coefficient> template<typename N = NumberType, EnableIf< is_subset_of_rationals< N >> = dummy> UnderlyingNumberType<Coefficient>::type carl::UnivariatePolynomial< Coefficient >::numericContent () const
Obtains the numeric content part of this polynomial.
The numeric content part of a polynomial is defined as the gcd() of the numeric content parts of all coefficients. This is only possible if the underlying number type is either integral or fractional.
As for fractional numbers, we consider the following definition: gcd(a/b, c/d) = gcd(a/b*l, c/d*l) / l where l = lcm(b,d).
Returns
numeric content part of the polynomial.
See also
UnivariatePolynomials::numericContent(std::size_t)
Referenced by carl::UnivariatePolynomial< Coeff >::pseudoPrimpart().
numericUnit() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::numericUnit () const inline
Returns the numeric unit part of the polynomial.
If the coefficients are numbers, this is the sign of the leading coefficient. If the coefficients are polynomials, this is the unit part of the leading coefficient.s
Returns
unit part of the polynomial.
Definition at line 857 of file UnivariatePolynomial.h.
numericUnit() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::numericUnit () const inline
Definition at line 862 of file UnivariatePolynomial.h.
one() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::one () const inline
Creates a polynomial of value one with the same main variable.
Applies if the Coefficient are GFNumber values.
Returns
One.
Definition at line 207 of file UnivariatePolynomial.h.
one() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::one () const inline
Creates a polynomial of value one with the same main variable.
Applies if the Coefficient are not GFNumber values.
Returns
One.
Definition at line 217 of file UnivariatePolynomial.h.
operator*=() [1/5]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (Variable rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [2/5]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (Variable rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [3/5]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (const Coefficient & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [4/5]
template<typename Coefficient> template<typename I = Coefficient, DisableIf< std::is_same< Coefficient, I >> ...> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (const typename IntegralType< Coefficient >::type & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [5/5]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (const UnivariatePolynomial< Coefficient > & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [1/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator+= (const Coefficient & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [2/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator+= (const UnivariatePolynomial< Coefficient > & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::operator- () const
operator-=() [1/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator-= (const Coefficient & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-=() [2/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator-= (const UnivariatePolynomial< Coefficient > & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator/= (const Coefficient & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator/= (const Coefficient & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator=() [1/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator= (const UnivariatePolynomial< Coefficient > & p)
Copy assignment operator.
operator=() [2/2]
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator= (UnivariatePolynomial< Coefficient > && p) noexcept
Move assignment operator.
pow()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::pow (std::size_t exp) const
Returns this polynomial to the given power.
Parameters
exp Exponent.
Returns
This to the power of exp.
Referenced by carl::resultant_debug::resultant_det(), and carl::resultant_debug::resultant_z3().
prem()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::prem (const UnivariatePolynomial< Coefficient > & divisor) const
Referenced by carl::subresultants().
prem_old()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::prem_old (const UnivariatePolynomial< Coefficient > & divisor) const
Calculates the pseudo-remainder.
See also
[3], page 55, Pseudo-Division Property
primitivePart()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::primitivePart () const
The primitive part of p is the normal part of p divided by the content of p.
The primitive part of zero is zero.
See also
[3], page 53
Returns
The primitive part of the polynomial.
principalSubresultantsCoefficients()
template<typename Coefficient> static const std::vector<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::principalSubresultantsCoefficients (const UnivariatePolynomial< Coefficient > & p, const UnivariatePolynomial< Coefficient > & q, SubresultantStrategy strategy = SubresultantStrategy::Default) inline static
Definition at line 978 of file UnivariatePolynomial.h.
pseudoPrimpart()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::pseudoPrimpart () const inline
Returns this/divisor where divisor is the numeric content of this polynomial.
Returns
Definition at line 886 of file UnivariatePolynomial.h.
remainder() [1/2]
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::remainder (const UnivariatePolynomial< Coefficient > & divisor, const Coefficient & prefactor) const
Referenced by carl::DiophantineEquations< Integer >::univariateDiophantine().
remainder() [2/2]
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::remainder (const UnivariatePolynomial< Coefficient > & divisor) const
remainder_helper()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::remainder_helper (const UnivariatePolynomial< Coefficient > & divisor, const Coefficient * prefactor = nullptr) const private
Calculates the remainder of polynomial division.
Parameters
divisor
prefactor
See also
[3], page 55, Pseudo-Division Property
Returns
replaceVariable() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::replaceVariable (Variable newVar) const inline
Replaces the main variable.
Applies, if the coefficients are numbers.
Parameters
newVar New main variable.
Returns
New polynomial.
Definition at line 440 of file UnivariatePolynomial.h.
Referenced by carl::ran::IntervalContent< Number >::replaceVariable().
replaceVariable() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::replaceVariable (Variable newVar) const inline
Replaces the main variable.
Applies, if the coefficients are not numbers.
Parameters
newVar New main variable.
Returns
New polynomial.
Definition at line 450 of file UnivariatePolynomial.h.
resultant()
template<typename Coefficient> UnivariatePolynomial<Coefficient> carl::UnivariatePolynomial< Coefficient >::resultant (const UnivariatePolynomial< Coefficient > & p, SubresultantStrategy strategy = SubresultantStrategy::Default) const inline
Definition at line 987 of file UnivariatePolynomial.h.
reverse()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::reverse () private
Reverses the order of the coefficients of this polynomial.
This method is meant to be called by signVariations only.
Runtime complexity:
O(n)
scale()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::scale (const Coefficient & factor) private
Scale the variable, i.e.
apply This method is meant to be called by signVariations only.
Parameters
factor Factor to scale x.
Runtime complexity:
O(n)
sgn()
template<typename Coefficient> carl::Sign carl::UnivariatePolynomial< Coefficient >::sgn (const Coefficient & value) const inline
Calculates the sign of the polynomial at some point.
Parameters
value Point to evaluate.
Returns
Sign at value.
Definition at line 757 of file UnivariatePolynomial.h.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluateIR(), and carl::UnivariatePolynomial< Coeff >::isRoot().
shift()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::shift (const Coefficient & a) private
Shift the variable by a, i.e.
apply This method is meant to be called by signVariations only.
Parameters
a Offset to shift x.
Runtime complexity:
O(n^2)
signVariations()
template<typename Coefficient> uint carl::UnivariatePolynomial< Coefficient >::signVariations (const Interval< Coefficient > & interval) const
Counts the sign variations (i.e.
an upper bound for the number of real roots) via Descarte's rule of signs. This is an upper bound for countRealRoots().
Parameters
interval Count roots within this interval.
Returns
Upper bound for number of real roots within the interval.
sprem()
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::sprem (const UnivariatePolynomial< Coefficient > & divisor) const
squareFreeFactorization()
template<typename Coefficient> std::map<uint, UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::squareFreeFactorization () const
standardSturmSequence() [1/2]
template<typename Coefficient> std::list<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::standardSturmSequence () const
Referenced by carl::RealAlgebraicNumberEvaluation::evaluateIR(), carl::ran::IntervalContent< Number >::setPolynomial(), carl::ran::IntervalContent< Number >::sgn(), and carl::univariateTarskiQuery().
standardSturmSequence() [2/2]
template<typename Coefficient> std::list<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::standardSturmSequence (const UnivariatePolynomial< Coefficient > & polynomial) const
stripLeadingZeroes()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::stripLeadingZeroes () inline private
Definition at line 1224 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::truncate().
subresultants()
template<typename Coefficient> static std::list<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::subresultants (const UnivariatePolynomial< Coefficient > & p, const UnivariatePolynomial< Coefficient > & q, SubresultantStrategy strategy = SubresultantStrategy::Default) inline static
Implements subresultants algorithm with optimizations described in [2] .
Parameters
p First polynomial.
q First polynomial.
strategy Strategy.
Returns
Subresultants of p and q.
Definition at line 969 of file UnivariatePolynomial.h.
substitute() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::substitute (Variable var, const Coefficient & value) const
substitute() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::substitute (Variable var, const Coefficient & value) const
substituteIn() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> void carl::UnivariatePolynomial< Coefficient >::substituteIn (Variable var, const Coefficient & value)
Referenced by carl::RealAlgebraicNumberEvaluation::evaluatePolynomial(), carl::realRootsThom(), and carl::model::substituteIn().
substituteIn() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> void carl::UnivariatePolynomial< Coefficient >::substituteIn (Variable var, const Coefficient & value)
switchVariable() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial<MultivariatePolynomial<NumberType> > carl::UnivariatePolynomial< Coefficient >::switchVariable (Variable newVar) const inline
Switches the main variable using a purely syntactical restructuring.
The resulting polynomial will be algebraicly identical, but have the given variable as its main variable. Applies, if the coefficients are numbers.
Parameters
newVar New main variable.
Returns
Restructured polynomial.
Definition at line 416 of file UnivariatePolynomial.h.
Referenced by carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::Brown(), carl::RealAlgebraicNumberEvaluation::evaluatePolynomial(), and carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::McCallum().
switchVariable() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::switchVariable (Variable newVar) const inline
Switches the main variable using a purely syntactical restructuring.
The resulting polynomial will be algebraicly identical, but have the given variable as its main variable. Applies, if the coefficients are not numbers.
Parameters
newVar New main variable.
Returns
Restructured polynomial.
Definition at line 428 of file UnivariatePolynomial.h.
syntheticDivision()
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::syntheticDivision (const Coefficient & zeroOfDivisor)
tcoeff()
template<typename Coefficient> const Coefficient& carl::UnivariatePolynomial< Coefficient >::tcoeff () const inline
Returns the trailing coefficient.
Asserts, that the polynomial is not empty.
Returns
The trailing coefficient.
Definition at line 237 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::constantPart().
toFiniteDomain()
template<typename Coefficient> UnivariatePolynomial<GFNumber<typename IntegralType<Coefficient>::type> > carl::UnivariatePolynomial< Coefficient >::toFiniteDomain (const GaloisField< typename IntegralType< Coefficient >::type > * galoisField) const
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
toIntegerDomain() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial<typename IntegralType<Coefficient>::type> carl::UnivariatePolynomial< Coefficient >::toIntegerDomain () const
Works only from rationals, if the numbers are already integers.
Returns
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
toIntegerDomain() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial<typename IntegralType<Coefficient>::type> carl::UnivariatePolynomial< Coefficient >::toIntegerDomain () const
toNumberCoefficients()
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial<NumberType> carl::UnivariatePolynomial< Coefficient >::toNumberCoefficients (bool check = true) const
totalDegree() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> uint carl::UnivariatePolynomial< Coefficient >::totalDegree () const inline
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
Applies, if the coefficients are numbers. In this case, the total degree is the degree. As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[3], page 38
Returns
Total degree.
Definition at line 346 of file UnivariatePolynomial.h.
totalDegree() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> uint carl::UnivariatePolynomial< Coefficient >::totalDegree () const inline
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
Applies, if the coefficients are not numbers. In this case, the total degree of all coefficients must be considered. As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[3], page 48
Returns
Total degree.
Definition at line 358 of file UnivariatePolynomial.h.
truncate()
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::truncate () inline
Removes the leading term from the polynomial.
Definition at line 386 of file UnivariatePolynomial.h.
unitPart() [1/3]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> const Coefficient& carl::UnivariatePolynomial< Coefficient >::unitPart () const
The unit part of a polynomial over a field is its leading coefficient for nonzero polynomials, and one for zero polynomials.
See also
[3], page 42.
Returns
The unit part of the polynomial.
unitPart() [2/3]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< Not< is_number< C >> > = dummy> Coefficient carl::UnivariatePolynomial< Coefficient >::unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
See also
[3], page 42.
Returns
The unit part of the polynomial.
unitPart() [3/3]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< Not< is_field< C >>, is_number< C >> = dummy> Coefficient carl::UnivariatePolynomial< Coefficient >::unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
See also
[3], page 42.
Returns
The unit part of the polynomial.
zeroIsRoot()
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::zeroIsRoot () const inline
Checks if zero is a real root of this polynomial.
Returns
True if zero is a root.
Definition at line 914 of file UnivariatePolynomial.h.
Friends And Related Function Documentation
operator!= [1/2]
template<typename Coefficient> template<typename C > bool operator!= (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
operator!= [2/2]
template<typename Coefficient> template<typename C > bool operator!= (const UnivariatePolynomialPtr< C > & lhs, const UnivariatePolynomialPtr< C > & rhs) friend
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
operator* [1/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [2/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, Variable rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [3/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (Variable lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [4/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [5/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [6/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const IntegralTypeIfDifferent< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [7/9]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, const IntegralTypeIfDifferent< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [8/9]
template<typename Coefficient> template<typename C , typename O , typename P > UnivariatePolynomial<MultivariatePolynomial<C,O,P> > operator* (const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> & lhs, const C & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator* [9/9]
template<typename Coefficient> template<typename C , typename O , typename P > UnivariatePolynomial<MultivariatePolynomial<C,O,P> > operator* (const C & lhs, const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator+ [1/3]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator+ (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator+ [2/3]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator+ (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator+ [3/3]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator+ (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator- [1/3]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator- (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs a subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
operator- [2/3]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator- (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs a subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
operator- [3/3]
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator- (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Performs a subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
operator/
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator/ (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
operator<
template<typename Coefficient> template<typename C > bool operator< (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
operator<<
template<typename Coefficient> template<typename C > std::ostream& operator<< (std::ostream & os, const UnivariatePolynomial< C > & rhs) friend
Streaming operator for univariate polynomials.
Parameters
os Output stream.
rhs Polynomial.
Returns
os
operator== [1/4]
template<typename Coefficient> template<typename C > bool operator== (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator== [2/4]
template<typename Coefficient> template<typename C > bool operator== (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator== [3/4]
template<typename Coefficient> template<typename C > bool operator== (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator== [4/4]
template<typename Coefficient> template<typename C > bool operator== (const UnivariatePolynomialPtr< C > & lhs, const UnivariatePolynomialPtr< C > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
UnivariatePolynomial
template<typename Coefficient> template<class T > friend class UnivariatePolynomial friend
Declare all instantiations of univariate polynomials as friends.
Definition at line 66 of file UnivariatePolynomial.h.
Field Documentation
mCoefficients
template<typename Coefficient> std::vector<Coefficient> carl::UnivariatePolynomial< Coefficient >::mCoefficients private
The coefficients.
Definition at line 71 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::coefficients(), carl::UnivariatePolynomial< Coeff >::complexity(), carl::UnivariatePolynomial< Coeff >::isOne(), carl::UnivariatePolynomial< Coeff >::isZero(), carl::UnivariatePolynomial< Coeff >::normalizeCoefficients(), carl::UnivariatePolynomial< Coeff >::replaceVariable(), and carl::UnivariatePolynomial< Coeff >::stripLeadingZeroes().
mMainVar
template<typename Coefficient> Variable carl::UnivariatePolynomial< Coefficient >::mMainVar private
The main variable.
Definition at line 69 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::mainVar(), and carl::UnivariatePolynomial< Coeff >::one().
The documentation for this class was generated from the following files:
carl/core/MultivariateGCD.h
carl/core/UnivariatePolynomial.h