carl: carl::BVTerm Class Reference
carl::BVTerm Class Reference
#include <BVTerm.h>
Public Member Functions
BVTerm ()
BVTerm (BVTermType _type, BVValue _value)
BVTerm (BVTermType _type, const BVVariable &_variable)
BVTerm (BVTermType _type, const BVTerm &_operand, std::size_t _index=0)
BVTerm (BVTermType _type, const BVTerm &_first, const BVTerm &_second)
BVTerm (BVTermType _type, const BVTerm &_operand, std::size_t _first, std::size_t _last)
std::string toString (const std::string &_init="", bool _oneline=true, bool _infix=false, bool _friendlyNames=true) const
std::size_t hash () const
std::size_t width () const
BVTermType type () const
bool isConstant () const
size_t complexity () const
void collectVariables (std::set< BVVariable > &vars) const
bool isInvalid () const
bool operator== (const BVTerm &rhs) const
bool operator< (const BVTerm &rhs) const
const BVTerm & operand () const
std::size_t index () const
const BVTerm & first () const
const BVTerm & second () const
std::size_t highest () const
std::size_t lowest () const
const BVVariable & variable () const
const BVValue & value () const
BVTerm substitute (const std::map< BVVariable, BVTerm > &) const
Private Attributes
friend BVTermPool
const BVTermContent * mpContent
Friends
std::ostream & operator<< (std::ostream &_out, const BVTerm &_term)
Detailed Description
Definition at line 106 of file BVTerm.h.
Constructor & Destructor Documentation
BVTerm() [1/6]
carl::BVTerm::BVTerm ()
Definition at line 11 of file BVTerm.cpp.
Referenced by substitute().
BVTerm() [2/6]
carl::BVTerm::BVTerm (BVTermType _type, BVValue _value)
Definition at line 16 of file BVTerm.cpp.
BVTerm() [3/6]
carl::BVTerm::BVTerm (BVTermType _type, const BVVariable & _variable)
Definition at line 21 of file BVTerm.cpp.
BVTerm() [4/6]
carl::BVTerm::BVTerm (BVTermType _type, const BVTerm & _operand, std::size_t _index = 0)
Definition at line 26 of file BVTerm.cpp.
BVTerm() [5/6]
carl::BVTerm::BVTerm (BVTermType _type, const BVTerm & _first, const BVTerm & _second)
Definition at line 31 of file BVTerm.cpp.
BVTerm() [6/6]
carl::BVTerm::BVTerm (BVTermType _type, const BVTerm & _operand, std::size_t _first, std::size_t _last)
Definition at line 36 of file BVTerm.cpp.
Member Function Documentation
collectVariables()
void carl::BVTerm::collectVariables (std::set< BVVariable > & vars) const
Definition at line 61 of file BVTerm.cpp.
Referenced by carl::BVConstraint::collectVariables(), and carl::BVTermContent::collectVariables().
complexity()
size_t carl::BVTerm::complexity () const
Returns
An approximation of the complexity of this bit vector term.
Definition at line 115 of file BVTerm.cpp.
Referenced by complexity(), and carl::BVConstraint::complexity().
first()
const BVTerm & carl::BVTerm::first () const
Definition at line 85 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
hash()
std::size_t carl::BVTerm::hash () const
Definition at line 46 of file BVTerm.cpp.
Referenced by std::hash< carl::BVTerm >::operator()().
highest()
std::size_t carl::BVTerm::highest () const
Definition at line 95 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
index()
std::size_t carl::BVTerm::index () const
Definition at line 80 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
isConstant()
bool carl::BVTerm::isConstant () const inline
Definition at line 139 of file BVTerm.h.
Referenced by carl::BVConstraintPool::create(), carl::BVTermPool::create(), and carl::model::evaluate().
isInvalid()
bool carl::BVTerm::isInvalid () const
Definition at line 65 of file BVTerm.cpp.
Referenced by carl::BVConstraint::isConstant().
lowest()
std::size_t carl::BVTerm::lowest () const
Definition at line 100 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
operand()
const BVTerm & carl::BVTerm::operand () const
Definition at line 70 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
operator<()
bool carl::BVTerm::operator< (const BVTerm & rhs) const
Definition at line 162 of file BVTerm.cpp.
operator==()
bool carl::BVTerm::operator== (const BVTerm & rhs) const inline
Definition at line 152 of file BVTerm.h.
second()
const BVTerm & carl::BVTerm::second () const
Definition at line 90 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
substitute()
BVTerm carl::BVTerm::substitute (const std::map< BVVariable, BVTerm > & _substitutions) const
Definition at line 129 of file BVTerm.cpp.
Referenced by carl::FormulaSubstitutor< Formula >::BitvectorSubstitutor::operator()(), and substitute().
toString()
std::string carl::BVTerm::toString (const std::string & _init = "", bool _oneline = true, bool _infix = false, bool _friendlyNames = true) const
Definition at line 41 of file BVTerm.cpp.
Referenced by carl::BVConstraint::toString(), and carl::BVTermContent::toString().
type()
BVTermType carl::BVTerm::type () const
Definition at line 56 of file BVTerm.cpp.
Referenced by complexity(), carl::model::evaluate(), isConstant(), substitute(), and carl::model::substituteIn().
value()
const BVValue & carl::BVTerm::value () const
Definition at line 110 of file BVTerm.cpp.
Referenced by carl::BVConstraintPool::create(), carl::BVTermPool::create(), and carl::model::evaluate().
variable()
const BVVariable & carl::BVTerm::variable () const
Definition at line 105 of file BVTerm.cpp.
Referenced by substitute(), and carl::model::substituteIn().
width()
std::size_t carl::BVTerm::width () const
Definition at line 51 of file BVTerm.cpp.
Referenced by carl::BVConstraint::BVConstraint(), carl::BVTermContent::BVTermContent(), carl::BVConstraintPool::create(), and carl::BVTermPool::create().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & _out, const BVTerm & _term) friend
Definition at line 128 of file BVTerm.h.
Field Documentation
BVTermPool
friend carl::BVTerm::BVTermPool private
Definition at line 108 of file BVTerm.h.
mpContent
const BVTermContent* carl::BVTerm::mpContent private
Definition at line 110 of file BVTerm.h.
Referenced by collectVariables(), complexity(), carl::BVTermPool::create(), first(), hash(), highest(), index(), isInvalid(), lowest(), operand(), operator<(), operator==(), second(), toString(), type(), value(), variable(), and width().
The documentation for this class was generated from the following files:
carl/formula/bitvector/BVTerm.h
carl/formula/bitvector/BVTerm.cpp