carl: carl::cad::SampleSet< Number > Class Template Reference
carl::cad::SampleSet< Number > Class Template Reference
#include <SampleSet.h>
Data Structures
struct SampleComparator
A functor compatible to std::less<RealAlgebraicNumber<Number>> that compares two samples according to a given order.
Public Types
typedef std::set< RealAlgebraicNumber< Number > >::iterator Iterator
typedef std::unordered_map< RealAlgebraicNumber< Number >, RealAlgebraicNumber< Number > > SampleSimplification
Public Member Functions
void restoreOrdering ()
Restore the ordering.
void restoreOrdering (SampleOrdering ordering)
Reset the ordering.
SampleSet (SampleOrdering ordering=SampleOrdering::Default)
const std::vector< RealAlgebraicNumber< Number > > & getHeap () const
SampleOrdering ordering () const
Returns the current ordering.
const std::set< RealAlgebraicNumber< Number > > & samples () const
Retrieves the set of samples stored.
std::tuple< Iterator, bool, bool > insert (const RealAlgebraicNumber< Number > &r)
Insert a new sample into this sample set.
template<class InputIterator >
void insert (InputIterator first, InputIterator last)
Inserts a range of samples.
void insert (const SampleSet &l)
Inserts another SampleSet.
SampleSet::Iterator remove (SampleSet::Iterator position)
Remove the sample at this position.
SampleSet::Iterator begin ()
Returns an iterator to the first sample in this sample set.
const SampleSet::Iterator begin () const
Returns an iterator to the first sample in this sample set.
SampleSet::Iterator end ()
Returns an iterator to the element after the last sample in this sample set.
const SampleSet::Iterator end () const
Returns an iterator to the element after the last sample in this sample set.
RealAlgebraicNumber< Number > next () const
Retrieves the next sample according to the configured ordering.
bool hasOptimal () const
Checks if the best sample remaining is optimal with respect to the configured ordering.
RealAlgebraicNumber< Number > next (SampleOrdering ordering)
Changes the ordering and retrieves the next sample according to this ordering.
void pop ()
Removes the element returned by next() from the list.
bool simplify (const RealAlgebraicNumber< Number > &from, RealAlgebraicNumber< Number > &to)
Replaces the interval-represented element from (if existing) by the numeric element to while maintaining the internal data structures.
std::pair< SampleSimplification, bool > simplify (bool fast=false)
Traverse all interval-represented samples and determine whether they could be simplified by numeric representations.
bool contains (const RealAlgebraicNumber< Number > r) const
Determines containment of r in the list.
bool empty () const
Checks if there are any samples left.
Data Fields
std::set< RealAlgebraicNumber< Number > > mSamples
Contains all samples in the order of their value.
SampleComparator mComp
std::vector< RealAlgebraicNumber< Number > > mHeap
Private Member Functions
bool isConsistent () const
Checks if this sample set fulfills the following conditions:
Friends
template<typename Num >
std::ostream & operator<< (std::ostream &os, const SampleSet< Num > &s)
Output operator for SampleSet.
template<typename Num >
void std::swap (SampleSet< Num > &lhs, SampleSet< Num > &rhs)
Swaps the contents (all attributes) of the two SampleSets.
Detailed Description
template<typename Number>
class carl::cad::SampleSet< Number >
Definition at line 26 of file SampleSet.h.
Member Typedef Documentation
Iterator
template<typename Number> typedef std::set<RealAlgebraicNumber<Number> >::iterator carl::cad::SampleSet< Number >::Iterator
Definition at line 28 of file SampleSet.h.
SampleSimplification
template<typename Number> typedef std::unordered_map<RealAlgebraicNumber<Number>, RealAlgebraicNumber<Number> > carl::cad::SampleSet< Number >::SampleSimplification
Definition at line 29 of file SampleSet.h.
Constructor & Destructor Documentation
SampleSet()
template<typename Number> carl::cad::SampleSet< Number >::SampleSet (SampleOrdering ordering = SampleOrdering::Default) inline
Definition at line 155 of file SampleSet.h.
Member Function Documentation
begin() [1/2]
template<typename Number> SampleSet::Iterator carl::cad::SampleSet< Number >::begin () inline
Returns an iterator to the first sample in this sample set.
Returns
Iterator to first sample.
Definition at line 237 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::insert().
begin() [2/2]
template<typename Number> const SampleSet::Iterator carl::cad::SampleSet< Number >::begin () const inline
Returns an iterator to the first sample in this sample set.
Returns
Iterator to first sample.
Definition at line 248 of file SampleSet.h.
contains()
template<typename Number> bool carl::cad::SampleSet< Number >::contains (const RealAlgebraicNumber< Number > r) const inline
Determines containment of r in the list.
Returns
true if r is contained in the list, false otherwise
Definition at line 334 of file SampleSet.h.
empty()
template<typename Number> bool carl::cad::SampleSet< Number >::empty () const inline
Checks if there are any samples left.
Returns
True, if no sample is left.
Definition at line 342 of file SampleSet.h.
end() [1/2]
template<typename Number> SampleSet::Iterator carl::cad::SampleSet< Number >::end () inline
Returns an iterator to the element after the last sample in this sample set.
Returns
Iterator to end.
Definition at line 260 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::insert().
end() [2/2]
template<typename Number> const SampleSet::Iterator carl::cad::SampleSet< Number >::end () const inline
Returns an iterator to the element after the last sample in this sample set.
Returns
Iterator to end.
Definition at line 271 of file SampleSet.h.
getHeap()
template<typename Number> const std::vector<RealAlgebraicNumber<Number> >& carl::cad::SampleSet< Number >::getHeap () const inline
Definition at line 161 of file SampleSet.h.
hasOptimal()
template<typename Number> bool carl::cad::SampleSet< Number >::hasOptimal () const inline
Checks if the best sample remaining is optimal with respect to the configured ordering.
Returns
True, if next sample is optimal.
Definition at line 289 of file SampleSet.h.
insert() [1/3]
template<typename Number> std::tuple<Iterator, bool, bool> carl::cad::SampleSet< Number >::insert (const RealAlgebraicNumber< Number > & r)
Insert a new sample into this sample set.
If a sample of this value was already present, it takes care of updating the sample (in case the new one is numeric or a root).
Parameters
r Sample to insert.
Returns
An iterator to the inserted sample, a flag that indicates if the insertion changed something and a flag that indicates if a value has been replaced or was new altogether.
Referenced by carl::cad::SampleSet< Number >::insert().
insert() [2/3]
template<typename Number> template<class InputIterator > void carl::cad::SampleSet< Number >::insert (InputIterator first, InputIterator last) inline
Inserts a range of samples.
Actually calls insert(s) for each sample s in the range.
Parameters
first Start of range.
last End of range.
Definition at line 195 of file SampleSet.h.
insert() [3/3]
template<typename Number> void carl::cad::SampleSet< Number >::insert (const SampleSet< Number > & l) inline
Inserts another SampleSet.
Parameters
l Other SampleSet.
Definition at line 205 of file SampleSet.h.
isConsistent()
template<typename Number> bool carl::cad::SampleSet< Number >::isConsistent () const private
Checks if this sample set fulfills the following conditions:
mSamples and mQueue contain the same samples.
The samples in mSamples are ordered by their value.
Returns
True, if this SampleSet is consistent.
Referenced by carl::cad::SampleSet< Number >::remove().
next() [1/2]
template<typename Number> RealAlgebraicNumber<Number> carl::cad::SampleSet< Number >::next () const inline
Retrieves the next sample according to the configured ordering.
Returns
Next sample.
Definition at line 280 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::hasOptimal(), and carl::cad::SampleSet< Number >::next().
next() [2/2]
template<typename Number> RealAlgebraicNumber<Number> carl::cad::SampleSet< Number >::next (SampleOrdering ordering) inline
Changes the ordering and retrieves the next sample according to this ordering.
Parameters
ordering New ordering.
Returns
Next sample.
Definition at line 299 of file SampleSet.h.
ordering()
template<typename Number> SampleOrdering carl::cad::SampleSet< Number >::ordering () const inline
Returns the current ordering.
Returns
Ordering.
Definition at line 169 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::restoreOrdering(), and carl::cad::SampleSet< Number >::SampleSet().
pop()
template<typename Number> void carl::cad::SampleSet< Number >::pop ()
Removes the element returned by next() from the list.
Runtime complexity:
at most linear in the size of the list
remove()
template<typename Number> SampleSet::Iterator carl::cad::SampleSet< Number >::remove (SampleSet< Number >::Iterator position) inline
Remove the sample at this position.
Parameters
position Valid iterator to a sample.
Returns
Iterator to the next position in the container.
Definition at line 217 of file SampleSet.h.
restoreOrdering() [1/2]
template<typename Number> void carl::cad::SampleSet< Number >::restoreOrdering () inline
Restore the ordering.
Definition at line 141 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::next(), carl::cad::SampleSet< Number >::remove(), and carl::cad::SampleSet< Number >::restoreOrdering().
restoreOrdering() [2/2]
template<typename Number> void carl::cad::SampleSet< Number >::restoreOrdering (SampleOrdering ordering) inline
Reset the ordering.
Parameters
ordering The new ordering.
Definition at line 148 of file SampleSet.h.
samples()
template<typename Number> const std::set<RealAlgebraicNumber<Number> >& carl::cad::SampleSet< Number >::samples () const inline
Retrieves the set of samples stored.
Returns
Sample set.
Definition at line 177 of file SampleSet.h.
simplify() [1/2]
template<typename Number> bool carl::cad::SampleSet< Number >::simplify (const RealAlgebraicNumber< Number > & from, RealAlgebraicNumber< Number > & to)
Replaces the interval-represented element from (if existing) by the numeric element to while maintaining the internal data structures.
It is assumed that from->isRoot() == to->isRoot().
Parameters
from
to
Returns
true if the element was replaced, false otherwise
Runtime complexity:
logarithmic in the elements stored
simplify() [2/2]
template<typename Number> std::pair<SampleSimplification, bool> carl::cad::SampleSet< Number >::simplify (bool fast = false)
Traverse all interval-represented samples and determine whether they could be simplified by numeric representations.
If so, move these samples to the NRs.
Parameters
fast If fast is set to true, no refined is performed. Only samples that have already been refined are simplified.
Returns
pair whose first component is a map from unsimplified real algebraic number pointers to real algebraic number pointers which were simplified; the second component is true if there were samples found which could be simplified.
Runtime complexity:
logarithmic in the number
Friends And Related Function Documentation
operator<<
template<typename Number> template<typename Num > std::ostream& operator<< (std::ostream & os, const SampleSet< Num > & s) friend
Output operator for SampleSet.
Parameters
os output stream
s sample set
std::swap
template<typename Number> template<typename Num > void std::swap (SampleSet< Num > & lhs, SampleSet< Num > & rhs) friend
Swaps the contents (all attributes) of the two SampleSets.
See also
std::set::swap
Field Documentation
mComp
template<typename Number> SampleComparator carl::cad::SampleSet< Number >::mComp
Definition at line 135 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::hasOptimal(), carl::cad::SampleSet< Number >::ordering(), and carl::cad::SampleSet< Number >::restoreOrdering().
mHeap
template<typename Number> std::vector<RealAlgebraicNumber<Number> > carl::cad::SampleSet< Number >::mHeap
Definition at line 136 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::empty(), carl::cad::SampleSet< Number >::getHeap(), carl::cad::SampleSet< Number >::hasOptimal(), carl::cad::SampleSet< Number >::next(), carl::cad::SampleSet< Number >::remove(), and carl::cad::SampleSet< Number >::restoreOrdering().
mSamples
template<typename Number> std::set<RealAlgebraicNumber<Number> > carl::cad::SampleSet< Number >::mSamples
Contains all samples in the order of their value.
Definition at line 133 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::contains(), carl::cad::SampleSet< Number >::remove(), and carl::cad::SampleSet< Number >::samples().
The documentation for this class was generated from the following file:
carl/cad/SampleSet.h