carl: carl::UFInstanceManager Class Reference
carl::UFInstanceManager Class Reference
Implements a manager for uninterpreted function instances, containing their actual contents and allocating their ids.
#include <UFInstanceManager.h>
Public Member Functions
const UninterpretedFunction & getUninterpretedFunction (const UFInstance &_ufi) const
const std::vector< UVariable > & getArgs (const UFInstance &_ufi) const
std::ostream & print (std::ostream &_out, const UFInstance &_ufi, bool _infix=false, bool _friendlyNames=true) const
Prints the given uninterpreted function instance on the given output stream.
UFInstance newUFInstance (const UninterpretedFunction &_uf, std::vector< UVariable > &&_args)
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
UFInstance newUFInstance (const UninterpretedFunction &_uf, const std::vector< UVariable > &_args)
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
Static Public Member Functions
static bool argsCorrect (const UFInstanceContent &_ufic)
static UFInstanceManager & getInstance ()
Returns the single instance of this class by reference.
Private Member Functions
UFInstanceManager ()
Constructs an uninterpreted function instances manager.
~UFInstanceManager () override
UFInstance newUFInstance (const UFInstanceContent *_ufic)
Tries to add the given uninterpreted function instance's content to the so far stored uninterpreted function instance's contents.
Private Attributes
friend Singleton< UFInstanceManager >
FastPointerMap< UFInstanceContent, std::size_t > mUFInstanceIdMap
Stores all instantiated uninterpreted function instance's contents and maps them to their unique id.
std::vector< const UFInstanceContent * > mUFInstances
Maps the unique ids to the instantiated uninterpreted function instance's content.
Detailed Description
Implements a manager for uninterpreted function instances, containing their actual contents and allocating their ids.
Definition at line 158 of file UFInstanceManager.h.
Constructor & Destructor Documentation
UFInstanceManager()
carl::UFInstanceManager::UFInstanceManager () inline private
Constructs an uninterpreted function instances manager.
Definition at line 174 of file UFInstanceManager.h.
~UFInstanceManager()
carl::UFInstanceManager::~UFInstanceManager () inline override private
Definition at line 180 of file UFInstanceManager.h.
Member Function Documentation
argsCorrect()
bool carl::UFInstanceManager::argsCorrect (const UFInstanceContent & _ufic) static
Returns
true, if the arguments domains coincide with those of the domain.
Definition at line 61 of file UFInstanceManager.cpp.
Referenced by newUFInstance().
getArgs()
const std::vector<UVariable>& carl::UFInstanceManager::getArgs (const UFInstance & _ufi) const inline
Parameters
_ufi An uninterpreted function instance.
Returns
The arguments of the given uninterpreted function instance.
Definition at line 212 of file UFInstanceManager.h.
Referenced by carl::UFInstance::args().
getInstance()
static UFInstanceManager & carl::Singleton< UFInstanceManager >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::UFInstance::args(), carl::newUFInstance(), carl::operator<<(), carl::UFInstance::toString(), and carl::UFInstance::uninterpretedFunction().
getUninterpretedFunction()
const UninterpretedFunction& carl::UFInstanceManager::getUninterpretedFunction (const UFInstance & _ufi) const inline
Parameters
_ufi An uninterpreted function instance.
Returns
The underlying uninterpreted function of the uninterpreted function of the given uninterpreted function instance.
Definition at line 201 of file UFInstanceManager.h.
Referenced by carl::UFInstance::uninterpretedFunction().
newUFInstance() [1/3]
UFInstance carl::UFInstanceManager::newUFInstance (const UFInstanceContent * _ufic) private
Tries to add the given uninterpreted function instance's content to the so far stored uninterpreted function instance's contents.
If it has already been stored, if will be deleted and the id of the already existing uninterpreted function instance's content will be used to create the returned uninterpreted function instance.
Parameters
_sc The uninterpreted function instance's content to store.
Returns
The uninterpreted function instance corresponding to the given content.
Definition at line 45 of file UFInstanceManager.cpp.
Referenced by newUFInstance(), and carl::newUFInstance().
newUFInstance() [2/3]
UFInstance carl::UFInstanceManager::newUFInstance (const UninterpretedFunction & _uf, std::vector< UVariable > && _args) inline
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
Parameters
_uf The underlying function of the uninterpreted function instance to get.
_args The arguments of the uninterpreted function instance to get.
Returns
The resulting uninterpreted function instance.
Definition at line 235 of file UFInstanceManager.h.
newUFInstance() [3/3]
UFInstance carl::UFInstanceManager::newUFInstance (const UninterpretedFunction & _uf, const std::vector< UVariable > & _args) inline
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
Parameters
_uf The underlying function of the uninterpreted function instance to get.
_args The arguments of the uninterpreted function instance to get.
Returns
The resulting uninterpreted function instance.
Definition at line 248 of file UFInstanceManager.h.
print()
std::ostream & carl::UFInstanceManager::print (std::ostream & _out, const UFInstance & _ufi, bool _infix = false, bool _friendlyNames = true) const
Prints the given uninterpreted function instance on the given output stream.
Parameters
_out The output stream to print the given uninterpreted function instance on.
_ufi The uninterpreted function instance to print.
_infix If infix notation shall be used.
_friendlyNames Whether to use the friendly names for printing.
Returns
The output stream after printing the given uninterpreted function instance on it.
Definition at line 13 of file UFInstanceManager.cpp.
Referenced by carl::operator<<(), and carl::UFInstance::toString().
Field Documentation
mUFInstanceIdMap
FastPointerMap<UFInstanceContent, std::size_t> carl::UFInstanceManager::mUFInstanceIdMap private
Stores all instantiated uninterpreted function instance's contents and maps them to their unique id.
Definition at line 167 of file UFInstanceManager.h.
Referenced by newUFInstance(), and ~UFInstanceManager().
mUFInstances
std::vector<const UFInstanceContent*> carl::UFInstanceManager::mUFInstances private
Maps the unique ids to the instantiated uninterpreted function instance's content.
Definition at line 169 of file UFInstanceManager.h.
Referenced by getArgs(), getUninterpretedFunction(), newUFInstance(), print(), UFInstanceManager(), and ~UFInstanceManager().
Singleton< UFInstanceManager >
friend carl::UFInstanceManager::Singleton< UFInstanceManager > private
Definition at line 161 of file UFInstanceManager.h.
The documentation for this class was generated from the following files:
carl/formula/uninterpreted/UFInstanceManager.h
carl/formula/uninterpreted/UFInstanceManager.cpp