carl: carl::StringParser Class Reference
carl::StringParser Class Reference
#include <stringparser.h>
Public Member Functions
StringParser ()
const std::map< std::string, Variable > & variables () const
void setVariables (std::list< std::string > variables)
bool setImplicitMultiplicationMode (bool to)
void setSumOfTermsForm (bool to)
In SumOfTermsForm, input strings are expected to be of the form "c_1 * m_1 + ... + c_n * m_n", where c_i are coefficients and m_i are monomials.
template<typename C , typename O = typename MultivariatePolynomial<C>::OrderedBy, typename P = typename MultivariatePolynomial<C>::Policy>
RationalFunction< MultivariatePolynomial< C, O, P > > parseRationalFunction (const std::string &inputString) const
template<typename C , typename O = typename MultivariatePolynomial<C>::OrderedBy, typename P = typename MultivariatePolynomial<C>::Policy>
MultivariatePolynomial< C, O, P > parseMultivariatePolynomial (const std::string &inputString) const
template<typename C >
Term< C > parseTerm (const std::string &inputStr) const
Protected Member Functions
template<typename C >
C constructCoefficient (const std::string &inputString) const
Protected Attributes
bool mSingleSymbVariables
bool mImplicitMultiplicationMode = false
bool mSumOfTermsForm = true
std::map< std::string, Variable > mVars
Detailed Description
Definition at line 69 of file stringparser.h.
Constructor & Destructor Documentation
StringParser()
carl::StringParser::StringParser () inline
Definition at line 78 of file stringparser.h.
Member Function Documentation
constructCoefficient()
template<typename C > C carl::StringParser::constructCoefficient (const std::string & inputString) const inline protected
Definition at line 270 of file stringparser.h.
parseMultivariatePolynomial()
template<typename C , typename O = typename MultivariatePolynomial<C>::OrderedBy, typename P = typename MultivariatePolynomial<C>::Policy> MultivariatePolynomial<C, O, P> carl::StringParser::parseMultivariatePolynomial (const std::string & inputString) const inline
Definition at line 160 of file stringparser.h.
Referenced by carl::benchmarks::cyclic2(), carl::benchmarks::cyclic3(), carl::benchmarks::katsura2(), carl::benchmarks::katsura3(), carl::benchmarks::katsura4(), carl::benchmarks::katsura5(), and main().
parseRationalFunction()
template<typename C , typename O = typename MultivariatePolynomial<C>::OrderedBy, typename P = typename MultivariatePolynomial<C>::Policy> RationalFunction<MultivariatePolynomial<C,O,P> > carl::StringParser::parseRationalFunction (const std::string & inputString) const inline
Definition at line 132 of file stringparser.h.
parseTerm()
template<typename C > Term<C> carl::StringParser::parseTerm (const std::string & inputStr) const inline
Definition at line 190 of file stringparser.h.
setImplicitMultiplicationMode()
bool carl::StringParser::setImplicitMultiplicationMode (bool to) inline
Definition at line 106 of file stringparser.h.
setSumOfTermsForm()
void carl::StringParser::setSumOfTermsForm (bool to) inline
In SumOfTermsForm, input strings are expected to be of the form "c_1 * m_1 + ... + c_n * m_n", where c_i are coefficients and m_i are monomials.
Parameters
to value to set
Returns
Definition at line 125 of file stringparser.h.
setVariables()
void carl::StringParser::setVariables (std::list< std::string > variables) inline
Definition at line 90 of file stringparser.h.
Referenced by carl::benchmarks::cyclic2(), carl::benchmarks::cyclic3(), carl::benchmarks::katsura2(), carl::benchmarks::katsura3(), carl::benchmarks::katsura4(), carl::benchmarks::katsura5(), and main().
variables()
const std::map<std::string, Variable>& carl::StringParser::variables () const inline
Definition at line 86 of file stringparser.h.
Referenced by setVariables().
Field Documentation
mImplicitMultiplicationMode
bool carl::StringParser::mImplicitMultiplicationMode = false protected
Definition at line 73 of file stringparser.h.
Referenced by parseTerm(), setImplicitMultiplicationMode(), and setVariables().
mSingleSymbVariables
bool carl::StringParser::mSingleSymbVariables protected
Definition at line 72 of file stringparser.h.
Referenced by parseTerm(), setImplicitMultiplicationMode(), and setVariables().
mSumOfTermsForm
bool carl::StringParser::mSumOfTermsForm = true protected
Definition at line 74 of file stringparser.h.
Referenced by parseMultivariatePolynomial(), and setSumOfTermsForm().
mVars
std::map<std::string, Variable> carl::StringParser::mVars protected
Definition at line 75 of file stringparser.h.
Referenced by parseTerm(), setVariables(), and variables().
The documentation for this class was generated from the following file:
carl/util/stringparser.h