carl: carl::VariablePool Class Reference
carl::VariablePool Class Reference
This class generates new variables and stores human-readable names for them.
#include <VariablePool.h>
Public Member Functions
Variable getFreshPersistentVariable (VariableType type=VariableType::VT_REAL) noexcept
Variable getFreshPersistentVariable (const std::string &name, VariableType type=VariableType::VT_REAL)
void clear () noexcept
Clears everything already created in this pool.
Variable findVariableWithName (const std::string &name) const noexcept
Searches in the friendly names list for a variable with the given name.
std::string getName (Variable v, bool variableName=true) const
Get a human-readable name for the given variable.
void setName (Variable v, const std::string &name)
Add a name for a given Variable.
void setPrefix (std::string prefix="_") noexcept
Sets the prefix used when printing anonymous variables.
std::size_t nrVariables (VariableType type=VariableType::VT_REAL) const noexcept
Returns the number of variables initialized by the pool.
void printVariableNamesToStream (std::ostream &os=std::cout)
Print variable names to the stream.
Static Public Member Functions
static VariablePool & getInstance ()
Returns the single instance of this class by reference.
Protected Member Functions
VariablePool () noexcept
Private default constructor.
Variable getFreshVariable (VariableType type=VariableType::VT_REAL) noexcept
Get a variable which was not used before.
Variable getFreshVariable (const std::string &name, VariableType type=VariableType::VT_REAL)
Get a variable with was not used before and set a name for it.
Private Member Functions
std::size_t & nextID (VariableType vt) noexcept
std::size_t nextID (VariableType vt) const noexcept
Private Attributes
friend Singleton< VariablePool >
std::array< std::size_t, static_cast< std::size_t >VariableType::TYPE_SIZE)> mNextIDs
Contains the id of the next variable to be created for each type.
std::mutex freshVarMutex
Mutex for calling getFreshVariable().
std::mutex setNameMutex
Mutex for calling setVariableName().
std::vector< std::pair< Variable, std::string > > mPersistentVariables
Contains persistent variables that are restored after clear was called.
std::map< Variable, std::string > mVariableNames
Stores human-readable names for variables that can be set via setVariableName().
std::string mVariablePrefix
Stores a prefix for printing variables that have no human-readable name.
Friends
Variable freshVariable (VariableType vt) noexcept
Variable freshVariable (const std::string &name, VariableType vt)
Detailed Description
This class generates new variables and stores human-readable names for them.
As we want only a single unique VariablePool and need global access to it, it is implemented as a singleton.
All methods that modify the pool, that are getInstance(), getFreshVariable() and setName(), are thread-safe.
Definition at line 30 of file VariablePool.h.
Constructor & Destructor Documentation
VariablePool()
carl::VariablePool::VariablePool () protected noexcept
Private default constructor.
Definition at line 15 of file VariablePool.cpp.
Member Function Documentation
clear()
void carl::VariablePool::clear () inline noexcept
Clears everything already created in this pool.
Definition at line 114 of file VariablePool.h.
Referenced by VariablePool().
findVariableWithName()
Variable carl::VariablePool::findVariableWithName (const std::string & name) const noexcept
Searches in the friendly names list for a variable with the given name.
Parameters
name The friendly variable name to look for.
Returns
The first variable with that friendly name.
Definition at line 56 of file VariablePool.cpp.
Referenced by carl::parser::ExpressionParser< Pol >::newVariable().
getFreshPersistentVariable() [1/2]
Variable carl::VariablePool::getFreshPersistentVariable (VariableType type = VariableType::VT_REAL) noexcept
Definition at line 40 of file VariablePool.cpp.
Referenced by getFreshPersistentVariable().
getFreshPersistentVariable() [2/2]
Variable carl::VariablePool::getFreshPersistentVariable (const std::string & name, VariableType type = VariableType::VT_REAL)
Definition at line 49 of file VariablePool.cpp.
getFreshVariable() [1/2]
Variable carl::VariablePool::getFreshVariable (VariableType type = VariableType::VT_REAL) protected noexcept
Get a variable which was not used before.
This method is thread-safe.
Parameters
type Type for the new variable.
Returns
A new variable.
Definition at line 21 of file VariablePool.cpp.
Referenced by clear(), carl::freshVariable(), and getFreshVariable().
getFreshVariable() [2/2]
Variable carl::VariablePool::getFreshVariable (const std::string & name, VariableType type = VariableType::VT_REAL) protected
Get a variable with was not used before and set a name for it.
This method is thread-safe.
Parameters
name Name for the new variable.
type Type for the new variable.
Returns
A new variable.
Definition at line 31 of file VariablePool.cpp.
getInstance()
static VariablePool & carl::Singleton< VariablePool >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::parser::FormulaParser< Pol >::addVariable(), carl::parser::PolynomialParser< Pol >::addVariable(), carl::parser::ExpressionParser< Pol >::addVariable(), carl::freshVariable(), carl::MonomialPool::MonomialPool(), carl::Variable::name(), carl::parser::ExpressionParser< Pol >::newVariable(), carl::GiNaCConverter::operator()(), carl::ToGiNaC::operator()(), carl::printRegisteredVariableNames(), carl::BVVariable::toString(), carl::UVariable::toString(), and carl::Monomial::toString().
getName()
std::string carl::VariablePool::getName (Variable v, bool variableName = true) const
Get a human-readable name for the given variable.
If the given Variable is Variable::NO_VARIABLE, "NO_VARIABLE" is returned. If friendlyVarName is true, the name that was set via setVariableName() for this Variable, if there is any, is returned. Otherwise "x_<id>" is returned, id being the internal id of the Variable.
Parameters
v Variable.
variableName Flag, if a name set via setVariableName shall be considered.
Returns
Some name for the Variable.
Definition at line 63 of file VariablePool.cpp.
Referenced by carl::parser::ExpressionParser< Pol >::addVariable(), carl::Variable::name(), carl::BVVariable::toString(), carl::UVariable::toString(), and carl::Monomial::toString().
nextID() [1/2]
std::size_t& carl::VariablePool::nextID (VariableType vt) inline private noexcept
Definition at line 50 of file VariablePool.h.
Referenced by clear(), and nrVariables().
nextID() [2/2]
std::size_t carl::VariablePool::nextID (VariableType vt) const inline private noexcept
Definition at line 54 of file VariablePool.h.
nrVariables()
std::size_t carl::VariablePool::nrVariables (VariableType type = VariableType::VT_REAL) const inline noexcept
Returns the number of variables initialized by the pool.
Returns
Number of variables.
Definition at line 169 of file VariablePool.h.
printVariableNamesToStream()
void carl::VariablePool::printVariableNamesToStream (std::ostream & os = std::cout) inline
Print variable names to the stream.
Definition at line 176 of file VariablePool.h.
Referenced by carl::printRegisteredVariableNames().
setName()
void carl::VariablePool::setName (Variable v, const std::string & name)
Add a name for a given Variable.
This method is thread-safe.
Parameters
v Variable.
name Some string naming the variable.
Definition at line 90 of file VariablePool.cpp.
Referenced by getFreshPersistentVariable(), and getFreshVariable().
setPrefix()
void carl::VariablePool::setPrefix (std::string prefix = "_") inline noexcept
Sets the prefix used when printing anonymous variables.
The default is "_", hence they look like "_x_5".
Parameters
prefix Prefix for anonymous variable names.
Definition at line 161 of file VariablePool.h.
Referenced by VariablePool().
Friends And Related Function Documentation
freshVariable [1/2]
Variable freshVariable (VariableType vt) friend
Definition at line 187 of file VariablePool.h.
freshVariable [2/2]
Variable freshVariable (const std::string & name, VariableType vt) friend
Definition at line 190 of file VariablePool.h.
Field Documentation
freshVarMutex
std::mutex carl::VariablePool::freshVarMutex mutable private
Mutex for calling getFreshVariable().
Definition at line 43 of file VariablePool.h.
mNextIDs
std::array<std::size_t, static_cast<std::size_t>VariableType::TYPE_SIZE)> carl::VariablePool::mNextIDs private
Contains the id of the next variable to be created for each type.
As such, is also a counter of the variables that exist.
Definition at line 38 of file VariablePool.h.
Referenced by clear(), and nextID().
mPersistentVariables
std::vector<std::pair<Variable,std::string> > carl::VariablePool::mPersistentVariables private
Contains persistent variables that are restored after clear was called.
Definition at line 62 of file VariablePool.h.
Referenced by clear(), and getFreshPersistentVariable().
mVariableNames
std::map<Variable, std::string> carl::VariablePool::mVariableNames private
Stores human-readable names for variables that can be set via setVariableName().
Definition at line 67 of file VariablePool.h.
Referenced by clear(), getName(), printVariableNamesToStream(), and setName().
mVariablePrefix
std::string carl::VariablePool::mVariablePrefix private
Stores a prefix for printing variables that have no human-readable name.
Definition at line 72 of file VariablePool.h.
Referenced by getFreshVariable(), getName(), and setPrefix().
setNameMutex
std::mutex carl::VariablePool::setNameMutex mutable private
Mutex for calling setVariableName().
Definition at line 48 of file VariablePool.h.
Singleton< VariablePool >
friend carl::VariablePool::Singleton< VariablePool > private
Definition at line 32 of file VariablePool.h.
The documentation for this class was generated from the following files:
carl/core/VariablePool.h
carl/core/VariablePool.cpp