carl: carl::BVConstraintPool Class Reference
carl::BVConstraintPool Class Reference
#include <BVConstraintPool.h>
Public Member Functions
ConstConstraintPtr create (bool _consistent=true)
ConstConstraintPtr create (const BVCompareRelation &_relation, const BVTerm &_lhs, const BVTerm &_rhs)
void assignId (ConstraintPtr _constraint, std::size_t _id) override
Assigns a unique id to the generated element.
void print () const
std::pair< typename FastPointerSet< BVConstraint >::iterator, bool > insert (ElementPtr _element, bool _assertFreshness=false)
Inserts the given element into the pool, if it does not yet occur in there.
ConstElementPtr add (ElementPtr _element)
Adds the given element to the pool, if it does not yet occur in there.
Static Public Member Functions
static BVConstraintPool & getInstance ()
Returns the single instance of this class by reference.
Private Types
using Constraint = BVConstraint
using ConstraintPtr = Constraint *
using ConstConstraintPtr = const Constraint *
Private Attributes
friend Singleton< BVConstraintPool >
Detailed Description
Definition at line 17 of file BVConstraintPool.h.
Member Typedef Documentation
ConstConstraintPtr
using carl::BVConstraintPool::ConstConstraintPtr = const Constraint* private
Definition at line 23 of file BVConstraintPool.h.
Constraint
using carl::BVConstraintPool::Constraint = BVConstraint private
Definition at line 21 of file BVConstraintPool.h.
ConstraintPtr
using carl::BVConstraintPool::ConstraintPtr = Constraint* private
Definition at line 22 of file BVConstraintPool.h.
Member Function Documentation
add()
ConstElementPtr carl::Pool< BVConstraint >::add (ElementPtr _element) inline inherited
Adds the given element to the pool, if it does not yet occur in there.
Note, that this method uses the allocator which is locked before calling.
Parameters
_element The element to add to the pool.
Returns
The given element, if it did not yet occur in the pool; The equivalent element already occurring in the pool, otherwise.
Definition at line 112 of file Pool.h.
Referenced by create().
assignId()
void carl::BVConstraintPool::assignId (ConstraintPtr , std::size_t) override virtual
Assigns a unique id to the generated element.
Note that this method serves as a callback for subclasses. The actual assignment of the id is done there.
Parameters
_element The element for which to add the id.
_id A unique id.
Reimplemented from carl::Pool< BVConstraint >.
Definition at line 62 of file BVConstraintPool.cpp.
create() [1/2]
BVConstraintPool::ConstConstraintPtr carl::BVConstraintPool::create (bool _consistent = true)
Definition at line 12 of file BVConstraintPool.cpp.
Referenced by create(), and carl::BVConstraint::create().
create() [2/2]
BVConstraintPool::ConstConstraintPtr carl::BVConstraintPool::create (const BVCompareRelation & _relation, const BVTerm & _lhs, const BVTerm & _rhs)
Definition at line 17 of file BVConstraintPool.cpp.
getInstance()
static BVConstraintPool & carl::Singleton< BVConstraintPool >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::BVConstraint::create().
insert()
std::pair<typename FastPointerSet<BVConstraint >::iterator, bool> carl::Pool< BVConstraint >::insert (ElementPtr _element, bool _assertFreshness = false) inline inherited
Inserts the given element into the pool, if it does not yet occur in there.
Parameters
_element The element to add to the pool.
_assertFreshness When true, an assertion fails if the element is not fresh (i.e., if it already occurs in the pool).
Returns
The position of the given element in the pool and true, if it did not yet occur in the pool; The position of the equivalent element in the pool and false, otherwise.
Definition at line 88 of file Pool.h.
print()
void carl::Pool< BVConstraint >::print () const inline inherited
Definition at line 71 of file Pool.h.
Field Documentation
Singleton< BVConstraintPool >
friend carl::BVConstraintPool::Singleton< BVConstraintPool > private
Definition at line 19 of file BVConstraintPool.h.
The documentation for this class was generated from the following files:
carl/formula/bitvector/BVConstraintPool.h
carl/formula/bitvector/BVConstraintPool.cpp