carl: carl::UninterpretedFunction Class Reference
carl::UninterpretedFunction Class Reference
Implements an uninterpreted function.
#include <UninterpretedFunction.h>
Public Types
using IDType = std::size_t
A unique id to identify this uninterpreted function in it's manager.
Public Member Functions
UninterpretedFunction () noexcept=default
Default constructor.
IDType id () const
const std::string & name () const
const std::vector< Sort > & domain () const
const Sort & codomain () const
bool operator== (const UninterpretedFunction &_ufun) const
bool operator< (const UninterpretedFunction &_ufun) const
Private Member Functions
UninterpretedFunction (IDType _id)
Constructs an uninterpreted function.
Private Attributes
IDType mId = 0
A unique id.
Friends
class UFManager
std::ostream & operator<< (std::ostream &_os, const UninterpretedFunction &_ufun)
Prints the given uninterpreted function on the given output stream.
Detailed Description
Implements an uninterpreted function.
Definition at line 22 of file UninterpretedFunction.h.
Member Typedef Documentation
IDType
using carl::UninterpretedFunction::IDType = std::size_t
A unique id to identify this uninterpreted function in it's manager.
Definition at line 27 of file UninterpretedFunction.h.
Constructor & Destructor Documentation
UninterpretedFunction() [1/2]
carl::UninterpretedFunction::UninterpretedFunction (IDType _id) inline explicit private
Constructs an uninterpreted function.
Parameters
_id
Definition at line 38 of file UninterpretedFunction.h.
UninterpretedFunction() [2/2]
carl::UninterpretedFunction::UninterpretedFunction () default noexcept
Default constructor.
Member Function Documentation
codomain()
const Sort & carl::UninterpretedFunction::codomain () const
Returns
The codomain of this uninterpreted function.
Definition at line 28 of file UninterpretedFunction.cpp.
Referenced by carl::operator<<(), and carl::UEquality::UEquality().
domain()
const std::vector< Sort > & carl::UninterpretedFunction::domain () const
Returns
The domain of this uninterpreted function.
Definition at line 23 of file UninterpretedFunction.cpp.
Referenced by carl::UFInstanceManager::argsCorrect(), and carl::operator<<().
id()
IDType carl::UninterpretedFunction::id () const inline
Returns
The unique id of this uninterpreted function instance.
Definition at line 52 of file UninterpretedFunction.h.
Referenced by carl::UFManager::getCodomain(), carl::UFManager::getDomain(), carl::UFManager::getName(), std::hash< carl::UninterpretedFunction >::operator()(), operator<(), operator==(), and carl::UFManager::print().
name()
const std::string & carl::UninterpretedFunction::name () const
Returns
The name of this uninterpreted function.
Definition at line 18 of file UninterpretedFunction.cpp.
Referenced by carl::operator<<(), and carl::UFInstanceManager::print().
operator<()
bool carl::UninterpretedFunction::operator< (const UninterpretedFunction & _ufun) const inline
Parameters
_ufun The uninterpreted function to compare with.
Returns
true, if this uninterpreted function is less than the given one.
Definition at line 85 of file UninterpretedFunction.h.
operator==()
bool carl::UninterpretedFunction::operator== (const UninterpretedFunction & _ufun) const inline
Parameters
_ufun The uninterpreted function to compare with.
Returns
true, if this and the given uninterpreted function are equal.
Definition at line 76 of file UninterpretedFunction.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & _os, const UninterpretedFunction & _ufun) friend
Prints the given uninterpreted function on the given output stream.
Parameters
_os The output stream to print on.
_ufun The uninterpreted function to print.
Returns
The output stream after printing the given uninterpreted function on it.
Definition at line 33 of file UninterpretedFunction.cpp.
UFManager
friend class UFManager friend
Definition at line 25 of file UninterpretedFunction.h.
Field Documentation
mId
IDType carl::UninterpretedFunction::mId = 0 private
A unique id.
Definition at line 32 of file UninterpretedFunction.h.
Referenced by id(), operator<(), and operator==().
The documentation for this class was generated from the following files:
carl/formula/uninterpreted/UninterpretedFunction.h
carl/formula/uninterpreted/UninterpretedFunction.cpp