carl: carl::CoCoAAdaptor< Poly > Class Template Reference
carl::CoCoAAdaptor< Poly > Class Template Reference
#include <CoCoAAdaptor.h>
Public Member Functions
CoCoA::BigInt convert (const mpz_class &n) const
mpz_class convert (const CoCoA::BigInt &n) const
CoCoA::BigRat convert (const mpq_class &n) const
mpq_class convert (const CoCoA::BigRat &n) const
void convert (mpz_class &res, const CoCoA::RingElem &n) const
void convert (mpq_class &res, const CoCoA::RingElem &n) const
CoCoA::RingElem convert (const Poly &p) const
Poly convert (const CoCoA::RingElem &p) const
std::vector< CoCoA::RingElem > convert (const std::vector< Poly > &p) const
std::vector< Poly > convert (const std::vector< CoCoA::RingElem > &p) const
const auto & variables () const
CoCoAAdaptor (const std::vector< Variable > &vars)
CoCoAAdaptor (const std::vector< Poly > &polys)
CoCoAAdaptor (const std::initializer_list< Poly > &polys)
void resetVariableOrdering (const std::vector< Variable > &ordering)
Poly gcd (const Poly &p1, const Poly &p2) const
Poly makeCoprimeWith (const Poly &p1, const Poly &p2) const
Factors< Poly > factorize (const Poly &p, bool includeConstants=true) const
Break down a polynomial into its irreducible factors together with their exponents/multiplicities.
std::vector< Poly > irreducibleFactorsOf (const Poly &p) const
Break down a polynomial into its unique, non-constant,irreducible factors without their exponents/multiplicities.
Poly squareFreePart (const Poly &p) const
auto GBasis (const std::vector< Poly > &p) const
Static Public Member Functions
static std::vector< Variable > collectVariables (const std::vector< Poly > &polys)
Private Attributes
std::map< Variable, CoCoA::RingElem > mSymbolThere
std::vector< Variable > mSymbolBack
CoCoA::ring mQ = CoCoA::RingQQ()
CoCoA::SparsePolyRing mRing
Detailed Description
template<typename Poly>
class carl::CoCoAAdaptor< Poly >
Definition at line 44 of file CoCoAAdaptor.h.
Constructor & Destructor Documentation
CoCoAAdaptor() [1/3]
template<typename Poly > carl::CoCoAAdaptor< Poly >::CoCoAAdaptor (const std::vector< Variable > & vars) inline explicit
Definition at line 143 of file CoCoAAdaptor.h.
CoCoAAdaptor() [2/3]
template<typename Poly > carl::CoCoAAdaptor< Poly >::CoCoAAdaptor (const std::vector< Poly > & polys) inline
Definition at line 153 of file CoCoAAdaptor.h.
CoCoAAdaptor() [3/3]
template<typename Poly > carl::CoCoAAdaptor< Poly >::CoCoAAdaptor (const std::initializer_list< Poly > & polys) inline
Definition at line 156 of file CoCoAAdaptor.h.
Member Function Documentation
collectVariables()
template<typename Poly > static std::vector<Variable> carl::CoCoAAdaptor< Poly >::collectVariables (const std::vector< Poly > & polys) inline static
Definition at line 75 of file CoCoAAdaptor.h.
convert() [1/10]
template<typename Poly > CoCoA::BigInt carl::CoCoAAdaptor< Poly >::convert (const mpz_class & n) const inline
Definition at line 51 of file CoCoAAdaptor.h.
Referenced by carl::CoCoAAdaptor< Poly >::convert(), carl::CoCoAAdaptor< Poly >::factorize(), carl::CoCoAAdaptor< Poly >::GBasis(), carl::CoCoAAdaptor< Poly >::gcd(), carl::CoCoAAdaptor< Poly >::irreducibleFactorsOf(), carl::CoCoAAdaptor< Poly >::makeCoprimeWith(), and carl::CoCoAAdaptor< Poly >::squareFreePart().
convert() [2/10]
template<typename Poly > mpz_class carl::CoCoAAdaptor< Poly >::convert (const CoCoA::BigInt & n) const inline
Definition at line 54 of file CoCoAAdaptor.h.
convert() [3/10]
template<typename Poly > CoCoA::BigRat carl::CoCoAAdaptor< Poly >::convert (const mpq_class & n) const inline
Definition at line 57 of file CoCoAAdaptor.h.
convert() [4/10]
template<typename Poly > mpq_class carl::CoCoAAdaptor< Poly >::convert (const CoCoA::BigRat & n) const inline
Definition at line 60 of file CoCoAAdaptor.h.
convert() [5/10]
template<typename Poly > void carl::CoCoAAdaptor< Poly >::convert (mpz_class & res, const CoCoA::RingElem & n) const inline
Definition at line 64 of file CoCoAAdaptor.h.
convert() [6/10]
template<typename Poly > void carl::CoCoAAdaptor< Poly >::convert (mpq_class & res, const CoCoA::RingElem & n) const inline
Definition at line 69 of file CoCoAAdaptor.h.
convert() [7/10]
template<typename Poly > CoCoA::RingElem carl::CoCoAAdaptor< Poly >::convert (const Poly & p) const inline
Definition at line 81 of file CoCoAAdaptor.h.
convert() [8/10]
template<typename Poly > Poly carl::CoCoAAdaptor< Poly >::convert (const CoCoA::RingElem & p) const inline
Definition at line 104 of file CoCoAAdaptor.h.
convert() [9/10]
template<typename Poly > std::vector<CoCoA::RingElem> carl::CoCoAAdaptor< Poly >::convert (const std::vector< Poly > & p) const inline
Definition at line 127 of file CoCoAAdaptor.h.
convert() [10/10]
template<typename Poly > std::vector<Poly> carl::CoCoAAdaptor< Poly >::convert (const std::vector< CoCoA::RingElem > & p) const inline
Definition at line 132 of file CoCoAAdaptor.h.
factorize()
template<typename Poly > Factors<Poly> carl::CoCoAAdaptor< Poly >::factorize (const Poly & p, bool includeConstants = true) const inline
Break down a polynomial into its irreducible factors together with their exponents/multiplicities.
E.g. "x^3 + 4 x^2 + 5 x + 2" factorizes into "(x+1)^2 * (x+2)^1" where "(x+1)", "(x+2)" are the irreducible factors and "2" and "1" are their exponents.
Parameters
includeConstants One of those factors is a constant-polynomial (degree 0), which is included by default but can be left out by setting the flag 'includeConstantFlag' to false, e.g., for root computations.
Returns
A map whose keys are the irreducible factors and whose values are the exponents.
Definition at line 197 of file CoCoAAdaptor.h.
Referenced by carl::factorization().
GBasis()
template<typename Poly > auto carl::CoCoAAdaptor< Poly >::GBasis (const std::vector< Poly > & p) const inline
Definition at line 235 of file CoCoAAdaptor.h.
gcd()
template<typename Poly > Poly carl::CoCoAAdaptor< Poly >::gcd (const Poly & p1, const Poly & p2) const inline
Definition at line 171 of file CoCoAAdaptor.h.
irreducibleFactorsOf()
template<typename Poly > std::vector<Poly> carl::CoCoAAdaptor< Poly >::irreducibleFactorsOf (const Poly & p) const inline
Break down a polynomial into its unique, non-constant,irreducible factors without their exponents/multiplicities.
E.g. "3*x^3 + 12*x^2 + 15*x + 6" has the unique, non-constant, irreducible factors "(x+1)", "(x+2)", and a constant factor "3" that is omited.
Definition at line 217 of file CoCoAAdaptor.h.
makeCoprimeWith()
template<typename Poly > Poly carl::CoCoAAdaptor< Poly >::makeCoprimeWith (const Poly & p1, const Poly & p2) const inline
Definition at line 178 of file CoCoAAdaptor.h.
Referenced by carl::coprimePart().
resetVariableOrdering()
template<typename Poly > void carl::CoCoAAdaptor< Poly >::resetVariableOrdering (const std::vector< Variable > & ordering) inline
Definition at line 160 of file CoCoAAdaptor.h.
squareFreePart()
template<typename Poly > Poly carl::CoCoAAdaptor< Poly >::squareFreePart (const Poly & p) const inline
Definition at line 226 of file CoCoAAdaptor.h.
Referenced by carl::squareFreePart().
variables()
template<typename Poly > const auto& carl::CoCoAAdaptor< Poly >::variables () const inline
Definition at line 138 of file CoCoAAdaptor.h.
Field Documentation
mQ
template<typename Poly > CoCoA::ring carl::CoCoAAdaptor< Poly >::mQ = CoCoA::RingQQ() private
Definition at line 48 of file CoCoAAdaptor.h.
mRing
template<typename Poly > CoCoA::SparsePolyRing carl::CoCoAAdaptor< Poly >::mRing private
Definition at line 49 of file CoCoAAdaptor.h.
Referenced by carl::CoCoAAdaptor< Poly >::CoCoAAdaptor(), carl::CoCoAAdaptor< Poly >::convert(), and carl::CoCoAAdaptor< Poly >::resetVariableOrdering().
mSymbolBack
template<typename Poly > std::vector<Variable> carl::CoCoAAdaptor< Poly >::mSymbolBack private
Definition at line 47 of file CoCoAAdaptor.h.
Referenced by carl::CoCoAAdaptor< Poly >::CoCoAAdaptor(), carl::CoCoAAdaptor< Poly >::convert(), carl::CoCoAAdaptor< Poly >::resetVariableOrdering(), and carl::CoCoAAdaptor< Poly >::variables().
mSymbolThere
template<typename Poly > std::map<Variable, CoCoA::RingElem> carl::CoCoAAdaptor< Poly >::mSymbolThere private
Definition at line 46 of file CoCoAAdaptor.h.
Referenced by carl::CoCoAAdaptor< Poly >::CoCoAAdaptor(), carl::CoCoAAdaptor< Poly >::convert(), and carl::CoCoAAdaptor< Poly >::resetVariableOrdering().
The documentation for this class was generated from the following file:
carl/converter/CoCoAAdaptor.h