carl: carl::QEPCADStream Class Reference
carl::QEPCADStream Class Reference
#include <QEPCADStream.h>
Public Member Functions
QEPCADStream ()
void initialize (const Variables &vars)
template<typename Pol >
void initialize (std::initializer_list< Formula< Pol >> formulas)
template<typename Pol >
void assertFormula (const Formula< Pol > &formula)
template<typename T >
QEPCADStream & operator<< (T &&t)
QEPCADStream & operator<< (std::ostream &(*os)(std::ostream &))
auto content () const
Private Member Functions
void declare (Variable v)
template<typename Pol >
void write (const Constraint< Pol > &c)
template<typename Pol >
void write (const Formulas< Pol > &f, const std::string &op)
template<typename Pol >
void write (const Formula< Pol > &f)
void write (const Monomial::Arg &m)
void write (const Monomial::Content::value_type &m)
void write (const Monomial &m)
template<typename Coeff >
void write (const MultivariatePolynomial< Coeff > &mp)
void write (Relation r)
template<typename Coeff >
void write (const Term< Coeff > &t)
template<typename Coeff >
void write (const UnivariatePolynomial< Coeff > &up)
void write (const Variable &v)
void write (const VariableType &vt)
template<typename T >
void write (T &&t)
Private Attributes
std::stringstream mStream
Detailed Description
Definition at line 20 of file QEPCADStream.h.
Constructor & Destructor Documentation
QEPCADStream()
carl::QEPCADStream::QEPCADStream () inline
Definition at line 189 of file QEPCADStream.h.
Member Function Documentation
assertFormula()
template<typename Pol > void carl::QEPCADStream::assertFormula (const Formula< Pol > & formula) inline
Definition at line 208 of file QEPCADStream.h.
content()
auto carl::QEPCADStream::content () const inline
Definition at line 223 of file QEPCADStream.h.
Referenced by carl::operator<<().
declare()
void carl::QEPCADStream::declare (Variable v) inline private
Definition at line 24 of file QEPCADStream.h.
Referenced by initialize().
initialize() [1/2]
void carl::QEPCADStream::initialize (const Variables & vars) inline
Definition at line 192 of file QEPCADStream.h.
Referenced by initialize().
initialize() [2/2]
template<typename Pol > void carl::QEPCADStream::initialize (std::initializer_list< Formula< Pol >> formulas) inline
Definition at line 199 of file QEPCADStream.h.
operator<<() [1/2]
template<typename T > QEPCADStream& carl::QEPCADStream::operator<< (T && t) inline
Definition at line 213 of file QEPCADStream.h.
operator<<() [2/2]
QEPCADStream& carl::QEPCADStream::operator<< (std::ostream &(*)(std::ostream &) os) inline
Definition at line 218 of file QEPCADStream.h.
write() [1/13]
template<typename Pol > void carl::QEPCADStream::write (const Constraint< Pol > & c) inline private
Definition at line 29 of file QEPCADStream.h.
Referenced by operator<<(), and write().
write() [2/13]
template<typename Pol > void carl::QEPCADStream::write (const Formulas< Pol > & f, const std::string & op) inline private
Definition at line 34 of file QEPCADStream.h.
write() [3/13]
template<typename Pol > void carl::QEPCADStream::write (const Formula< Pol > & f) inline private
Definition at line 46 of file QEPCADStream.h.
write() [4/13]
void carl::QEPCADStream::write (const Monomial::Arg & m) inline private
Definition at line 101 of file QEPCADStream.h.
write() [5/13]
void carl::QEPCADStream::write (const Monomial::Content::value_type & m) inline private
Definition at line 105 of file QEPCADStream.h.
write() [6/13]
void carl::QEPCADStream::write (const Monomial & m) inline private
Definition at line 112 of file QEPCADStream.h.
write() [7/13]
template<typename Coeff > void carl::QEPCADStream::write (const MultivariatePolynomial< Coeff > & mp) inline private
Definition at line 121 of file QEPCADStream.h.
write() [8/13]
void carl::QEPCADStream::write (Relation r) inline private
Definition at line 132 of file QEPCADStream.h.
write() [9/13]
template<typename Coeff > void carl::QEPCADStream::write (const Term< Coeff > & t) inline private
Definition at line 144 of file QEPCADStream.h.
write() [10/13]
template<typename Coeff > void carl::QEPCADStream::write (const UnivariatePolynomial< Coeff > & up) inline private
Definition at line 156 of file QEPCADStream.h.
write() [11/13]
void carl::QEPCADStream::write (const Variable & v) inline private
Definition at line 169 of file QEPCADStream.h.
write() [12/13]
void carl::QEPCADStream::write (const VariableType & vt) inline private
Definition at line 172 of file QEPCADStream.h.
write() [13/13]
template<typename T > void carl::QEPCADStream::write (T && t) inline private
Definition at line 184 of file QEPCADStream.h.
Field Documentation
mStream
std::stringstream carl::QEPCADStream::mStream private
Definition at line 22 of file QEPCADStream.h.
Referenced by content(), and write().
The documentation for this class was generated from the following file:
carl/io/QEPCADStream.h