carl: carl::TarskiQueryManager< Number > Class Template Reference
carl::TarskiQueryManager< Number > Class Template Reference
#include <TarskiQueryManager.h>
Public Types
using QueryResultType = int
Public Member Functions
TarskiQueryManager ()=default
template<typename InputIt >
TarskiQueryManager (InputIt first, InputIt last)
QueryResultType operator() (const Polynomial &p) const
QueryResultType operator() (const Number &c) const
Polynomial reduceProduct (const Polynomial &a, const Polynomial &b) const
Private Types
using Polynomial = MultivariatePolynomial< Number >
Private Member Functions
bool isUnivariateManager () const
bool getCached (const Polynomial &p, QueryResultType &res) const
void cache (const Polynomial &p, const QueryResultType res) const
Private Attributes
UnivariatePolynomial< Number > mZ = UnivariatePolynomial<Number>(Variable::NO_VARIABLE)
UnivariatePolynomial< Number > mDer = UnivariatePolynomial<Number>(Variable::NO_VARIABLE)
MultiplicationTable< Number > mTab
bool mTrivialGb = false
std::map< Polynomial, QueryResultType > mCache
Detailed Description
template<typename Number>
class carl::TarskiQueryManager< Number >
Definition at line 24 of file TarskiQueryManager.h.
Member Typedef Documentation
Polynomial
template<typename Number> using carl::TarskiQueryManager< Number >::Polynomial = MultivariatePolynomial<Number> private
Definition at line 30 of file TarskiQueryManager.h.
QueryResultType
template<typename Number> using carl::TarskiQueryManager< Number >::QueryResultType = int
Definition at line 27 of file TarskiQueryManager.h.
Constructor & Destructor Documentation
TarskiQueryManager() [1/2]
template<typename Number> carl::TarskiQueryManager< Number >::TarskiQueryManager () default
TarskiQueryManager() [2/2]
template<typename Number> template<typename InputIt > carl::TarskiQueryManager< Number >::TarskiQueryManager (InputIt first, InputIt last) inline
Definition at line 46 of file TarskiQueryManager.h.
Member Function Documentation
cache()
template<typename Number> void carl::TarskiQueryManager< Number >::cache (const Polynomial & p, const QueryResultType res) const inline private
Definition at line 148 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()().
getCached()
template<typename Number> bool carl::TarskiQueryManager< Number >::getCached (const Polynomial & p, QueryResultType & res) const inline private
Definition at line 136 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()().
isUnivariateManager()
template<typename Number> bool carl::TarskiQueryManager< Number >::isUnivariateManager () const inline private
Definition at line 129 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()(), carl::TarskiQueryManager< carl::Number >::reduceProduct(), and carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
operator()() [1/2]
template<typename Number> QueryResultType carl::TarskiQueryManager< Number >::operator() (const Polynomial & p) const inline
Definition at line 75 of file TarskiQueryManager.h.
operator()() [2/2]
template<typename Number> QueryResultType carl::TarskiQueryManager< Number >::operator() (const Number & c) const inline
Definition at line 110 of file TarskiQueryManager.h.
reduceProduct()
template<typename Number> Polynomial carl::TarskiQueryManager< Number >::reduceProduct (const Polynomial & a, const Polynomial & b) const inline
Definition at line 114 of file TarskiQueryManager.h.
Field Documentation
mCache
template<typename Number> std::map<Polynomial, QueryResultType> carl::TarskiQueryManager< Number >::mCache mutable private
Definition at line 40 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::cache(), and carl::TarskiQueryManager< carl::Number >::getCached().
mDer
template<typename Number> UnivariatePolynomial<Number> carl::TarskiQueryManager< Number >::mDer = UnivariatePolynomial<Number>(Variable::NO_VARIABLE) private
Definition at line 34 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()(), and carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
mTab
template<typename Number> MultiplicationTable<Number> carl::TarskiQueryManager< Number >::mTab private
Definition at line 37 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()(), carl::TarskiQueryManager< carl::Number >::reduceProduct(), and carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
mTrivialGb
template<typename Number> bool carl::TarskiQueryManager< Number >::mTrivialGb = false private
Definition at line 38 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()(), and carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
mZ
template<typename Number> UnivariatePolynomial<Number> carl::TarskiQueryManager< Number >::mZ = UnivariatePolynomial<Number>(Variable::NO_VARIABLE) private
Definition at line 33 of file TarskiQueryManager.h.
Referenced by carl::TarskiQueryManager< carl::Number >::isUnivariateManager(), carl::TarskiQueryManager< carl::Number >::operator()(), and carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
The documentation for this class was generated from the following file:
carl/thom/TarskiQuery/TarskiQueryManager.h