carl: carl::UFContent Class Reference
carl::UFContent Class Reference
The actual content of an uninterpreted function instance.
#include <UFManager.h>
Public Member Functions
UFContent ()=delete
UFContent (const UFContent &)=delete
UFContent (UFContent &&)=delete
const std::string & name () const
const std::vector< Sort > & domain () const
const Sort & codomain () const
bool operator== (const UFContent &_ufc) const
bool operator< (const UFContent &_ufc) const
Private Member Functions
UFContent (std::string &&_name, std::vector< Sort > &&_domain, Sort _codomain)
Constructs the content of an uninterpreted function.
Private Attributes
std::string mName
The uninterpreted function's name.
std::vector< Sort > mDomain
The uninterpreted function's domain.
Sort mCodomain
The uninterpreted function's codomain.
Friends
class UFManager
Detailed Description
The actual content of an uninterpreted function instance.
Definition at line 33 of file UFManager.h.
Constructor & Destructor Documentation
UFContent() [1/4]
carl::UFContent::UFContent (std::string && _name, std::vector< Sort > && _domain, Sort _codomain) inline explicit private
Constructs the content of an uninterpreted function.
Parameters
_name The name of the uninterpreted function to construct.
_domain The domain of the uninterpreted function to construct.
_codomain The codomain of the uninterpreted function to construct.
Definition at line 51 of file UFManager.h.
UFContent() [2/4]
carl::UFContent::UFContent () delete
UFContent() [3/4]
carl::UFContent::UFContent (const UFContent &) delete
UFContent() [4/4]
carl::UFContent::UFContent (UFContent &&) delete
Member Function Documentation
codomain()
const Sort& carl::UFContent::codomain () const inline
Returns
The codomain of the uninterpreted function.
Definition at line 80 of file UFManager.h.
domain()
const std::vector<Sort>& carl::UFContent::domain () const inline
Returns
The domain of the uninterpreted function.
Definition at line 72 of file UFManager.h.
Referenced by std::hash< carl::UFContent >::operator()(), operator<(), and operator==().
name()
const std::string& carl::UFContent::name () const inline
Returns
The name of the uninterpreted function.
Definition at line 64 of file UFManager.h.
Referenced by std::hash< carl::UFContent >::operator()(), operator<(), and operator==().
operator<()
bool carl::UFContent::operator< (const UFContent & _ufc) const inline
Parameters
_ufc The uninterpreted function's content to compare with.
Returns
true, if this uninterpreted function's content is less than the given one.
Definition at line 98 of file UFManager.h.
operator==()
bool carl::UFContent::operator== (const UFContent & _ufc) const inline
Parameters
_ufc The uninterpreted function's content to compare with.
Returns
true, if this uninterpreted function's content is less than the given one.
Definition at line 89 of file UFManager.h.
Friends And Related Function Documentation
UFManager
friend class UFManager friend
Definition at line 35 of file UFManager.h.
Field Documentation
mCodomain
Sort carl::UFContent::mCodomain private
The uninterpreted function's codomain.
Definition at line 43 of file UFManager.h.
Referenced by codomain().
mDomain
std::vector<Sort> carl::UFContent::mDomain private
The uninterpreted function's domain.
Definition at line 41 of file UFManager.h.
Referenced by domain(), operator<(), and operator==().
mName
std::string carl::UFContent::mName private
The uninterpreted function's name.
Definition at line 39 of file UFManager.h.
Referenced by name(), operator<(), and operator==().
The documentation for this class was generated from the following file:
carl/formula/uninterpreted/UFManager.h