carl: carl::IntervalEvaluation Class Reference
carl::IntervalEvaluation Class Reference
#include <IntervalEvaluation.h>
Static Public Member Functions
template<typename Numeric >
static Interval< Numeric > evaluate (const Monomial &m, const std::map< Variable, Interval< Numeric >> &)
template<typename Coeff , typename Numeric , EnableIf< std::is_same< Numeric, Coeff >> = dummy>
static Interval< Numeric > evaluate (const Term< Coeff > &t, const std::map< Variable, Interval< Numeric >> &)
template<typename Coeff , typename Numeric , DisableIf< std::is_same< Numeric, Coeff >> = dummy>
static Interval< Numeric > evaluate (const Term< Coeff > &t, const std::map< Variable, Interval< Numeric >> &)
template<typename Coeff , typename Policy , typename Ordering , typename Numeric >
static Interval< Numeric > evaluate (const MultivariatePolynomial< Coeff, Policy, Ordering > &p, const std::map< Variable, Interval< Numeric >> &)
template<typename P , typename Numeric >
static Interval< Numeric > evaluate (const FactorizedPolynomial< P > &p, const std::map< Variable, Interval< Numeric >> &)
template<typename Numeric , typename Coeff , EnableIf< std::is_same< Numeric, Coeff >> = dummy>
static Interval< Numeric > evaluate (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, Interval< Numeric >> &map)
template<typename Numeric , typename Coeff , DisableIf< std::is_same< Numeric, Coeff >> = dummy>
static Interval< Numeric > evaluate (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, Interval< Numeric >> &map)
template<typename PolynomialType , typename Number , class strategy >
static Interval< Number > evaluate (const MultivariateHorner< PolynomialType, strategy > &mvH, const std::map< Variable, Interval< Number >> &map)
Detailed Description
Definition at line 24 of file IntervalEvaluation.h.
Member Function Documentation
evaluate() [1/8]
template<typename Numeric > Interval< Numeric > carl::IntervalEvaluation::evaluate (const Monomial & m, const std::map< Variable, Interval< Numeric >> & map) inline static
Definition at line 57 of file IntervalEvaluation.h.
Referenced by carl::SimpleNewton< Polynomial >::contract(), evaluate(), carl::VarSolutionFormula< carl::Polynomial >::evaluate(), carl::RealAlgebraicNumberEvaluation::evaluateIR(), and main().
evaluate() [2/8]
template<typename Coeff , typename Numeric , DisableIf< std::is_same< Numeric, Coeff >> > Interval< Numeric > carl::IntervalEvaluation::evaluate (const Term< Coeff > & t, const std::map< Variable, Interval< Numeric >> & map) inline static
Definition at line 75 of file IntervalEvaluation.h.
evaluate() [3/8]
template<typename Coeff , typename Numeric , DisableIf< std::is_same< Numeric, Coeff >> = dummy> static Interval<Numeric> carl::IntervalEvaluation::evaluate (const Term< Coeff > & t, const std::map< Variable, Interval< Numeric >> &) static
evaluate() [4/8]
template<typename Coeff , typename Policy , typename Ordering , typename Numeric > Interval< Numeric > carl::IntervalEvaluation::evaluate (const MultivariatePolynomial< Coeff, Policy, Ordering > & p, const std::map< Variable, Interval< Numeric >> & map) inline static
Definition at line 93 of file IntervalEvaluation.h.
evaluate() [5/8]
template<typename P , typename Numeric > Interval< Numeric > carl::IntervalEvaluation::evaluate (const FactorizedPolynomial< P > & p, const std::map< Variable, Interval< Numeric >> & map) inline static
Definition at line 110 of file IntervalEvaluation.h.
evaluate() [6/8]
template<typename Numeric , typename Coeff , DisableIf< std::is_same< Numeric, Coeff >> > Interval< Numeric > carl::IntervalEvaluation::evaluate (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, Interval< Numeric >> & map) inline static
Definition at line 133 of file IntervalEvaluation.h.
evaluate() [7/8]
template<typename Numeric , typename Coeff , DisableIf< std::is_same< Numeric, Coeff >> = dummy> static Interval<Numeric> carl::IntervalEvaluation::evaluate (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, Interval< Numeric >> & map) static
evaluate() [8/8]
template<typename PolynomialType , typename Number , class strategy > Interval< Number > carl::IntervalEvaluation::evaluate (const MultivariateHorner< PolynomialType, strategy > & mvH, const std::map< Variable, Interval< Number >> & map) inline static
Definition at line 166 of file IntervalEvaluation.h.
The documentation for this class was generated from the following file:
carl/interval/IntervalEvaluation.h