carl: carl::covering::SetCover Class Reference
carl::covering::SetCover Class Reference
Represents a set cover problem.
#include <SetCover.h>
Public Member Functions
void set (std::size_t set, std::size_t element)
States that s covers the given element.
void set (std::size_t set, const Bitset &elements)
States that s covers the given elements.
const auto & get_set (std::size_t set) const
Returns the given set.
std::size_t element_count () const
Returns the number of elements.
void prune_sets ()
Removes empty sets.
std::size_t set_count () const
Returns the number of sets.
std::size_t active_set_count () const
Returns the number of active sets (that still cover uncovered elements).
std::size_t largest_set () const
Returns the id of the largest set.
std::size_t largest_set (const std::vector< double > &weights) const
Returns the id of the largest set with respect to given weights.
Bitset get_uncovered () const
Returns the uncovered elements.
void select_set (std::size_t s)
Selects the given set and purges the covered elements from all other sets.
Private Attributes
std::vector< Bitset > mSets
The actual sets.
Friends
std::ostream & operator<< (std::ostream &os, const SetCover &sc)
Print the set cover to os.
Detailed Description
Represents a set cover problem.
Allows to state which sets cover which elements and offers some helper methods to work with this set cover for the heuristics.
Definition at line 13 of file SetCover.h.
Member Function Documentation
active_set_count()
std::size_t carl::covering::SetCover::active_set_count () const
Returns the number of active sets (that still cover uncovered elements).
Definition at line 42 of file SetCover.cpp.
Referenced by carl::covering::heuristic::exact(), get_set(), carl::covering::heuristic::greedy_bounded(), and carl::covering::heuristic::greedy_weighted().
element_count()
std::size_t carl::covering::SetCover::element_count () const
Returns the number of elements.
Definition at line 22 of file SetCover.cpp.
Referenced by get_set(), carl::covering::operator<<(), and carl::covering::heuristic::select_essential().
get_set()
const auto& carl::covering::SetCover::get_set (std::size_t set) const inline
Returns the given set.
Definition at line 25 of file SetCover.h.
Referenced by carl::covering::heuristic::exact(), carl::covering::heuristic::exact_of_size(), carl::covering::heuristic::greedy(), carl::covering::heuristic::remove_duplicates(), and carl::covering::heuristic::select_essential().
get_uncovered()
Bitset carl::covering::SetCover::get_uncovered () const
Returns the uncovered elements.
Definition at line 76 of file SetCover.cpp.
Referenced by carl::covering::heuristic::exact(), get_set(), carl::covering::heuristic::greedy(), carl::covering::heuristic::greedy_bounded(), and carl::covering::heuristic::greedy_weighted().
largest_set() [1/2]
std::size_t carl::covering::SetCover::largest_set () const
Returns the id of the largest set.
Definition at line 48 of file SetCover.cpp.
Referenced by get_set(), carl::covering::heuristic::greedy(), carl::covering::heuristic::greedy_bounded(), and carl::covering::heuristic::greedy_weighted().
largest_set() [2/2]
std::size_t carl::covering::SetCover::largest_set (const std::vector< double > & weights) const
Returns the id of the largest set with respect to given weights.
Definition at line 62 of file SetCover.cpp.
prune_sets()
void carl::covering::SetCover::prune_sets ()
Removes empty sets.
Definition at line 30 of file SetCover.cpp.
Referenced by get_set(), carl::covering::heuristic::greedy_bounded(), and carl::covering::heuristic::greedy_weighted().
select_set()
void carl::covering::SetCover::select_set (std::size_t s)
Selects the given set and purges the covered elements from all other sets.
Definition at line 84 of file SetCover.cpp.
Referenced by carl::covering::heuristic::exact(), get_set(), carl::covering::heuristic::greedy(), carl::covering::heuristic::greedy_bounded(), carl::covering::heuristic::greedy_weighted(), and carl::covering::heuristic::select_essential().
set() [1/2]
void carl::covering::SetCover::set (std::size_t set, std::size_t element)
States that s covers the given element.
Definition at line 8 of file SetCover.cpp.
Referenced by carl::covering::heuristic::remove_duplicates(), and carl::covering::TypedSetCover< Set >::set().
set() [2/2]
void carl::covering::SetCover::set (std::size_t set, const Bitset & elements)
States that s covers the given elements.
Definition at line 15 of file SetCover.cpp.
set_count()
std::size_t carl::covering::SetCover::set_count () const
Returns the number of sets.
Definition at line 38 of file SetCover.cpp.
Referenced by carl::covering::heuristic::exact(), get_set(), carl::covering::heuristic::remove_duplicates(), carl::covering::heuristic::select_essential(), and carl::covering::heuristic::trivial().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SetCover & sc) friend
Print the set cover to os.
Definition at line 92 of file SetCover.cpp.
Referenced by get_set().
Field Documentation
mSets
std::vector<Bitset> carl::covering::SetCover::mSets private
The actual sets.
Definition at line 18 of file SetCover.h.
Referenced by active_set_count(), element_count(), get_uncovered(), largest_set(), carl::covering::operator<<(), prune_sets(), select_set(), set(), and set_count().
The documentation for this class was generated from the following files:
carl-covering/SetCover.h
carl-covering/SetCover.cpp