carl: carl::FormulaPool< Pol > Class Template Reference
carl::FormulaPool< Pol > Class Template Reference
#include <Formula.h>
Public Member Functions
std::size_t size () const
void print () const
Formula< Pol > getTseitinVar (const Formula< Pol > &_formula)
Formula< Pol > createTseitinVar (const Formula< Pol > &_formula)
template<typename ArgType >
void forallDo (void(*_func)(ArgType *, const Formula< Pol > &), ArgType *_arg) const
template<typename ReturnType , typename ArgType >
std::map< const Formula< Pol >, ReturnType > forallDo (ReturnType(*_func)(ArgType *, const Formula< Pol > &), ArgType *_arg) const
bool formulasInverse (const Formula< Pol > &_subformulaA, const Formula< Pol > &_subformulaB)
Static Public Member Functions
static FormulaPool< Pol > & getInstance ()
Returns the single instance of this class by reference.
Protected Member Functions
FormulaPool (unsigned _capacity=10000)
Constructor of the formula pool.
~FormulaPool ()
const FormulaContent< Pol > * trueFormula () const
const FormulaContent< Pol > * falseFormula () const
Private Member Functions
bool isBaseFormula (const Constraint< Pol > &c) const
bool isBaseFormula (const VariableComparison< Pol > &vc) const
bool isBaseFormula (const VariableAssignment< Pol > &va) const
bool isBaseFormula (const FormulaContent< Pol > *f) const
const FormulaContent< Pol > * getBaseFormula (const FormulaContent< Pol > *f) const
FormulaContent< Pol > * createNegatedContent (const FormulaContent< Pol > *f) const
const FormulaContent< Pol > * create (FormulaType _type)
Create formula representing a boolean value.
const FormulaContent< Pol > * create (Variable::Arg _variable)
Create formula representing a boolean variable.
const FormulaContent< Pol > * create (Constraint< Pol > &&_constraint)
const FormulaContent< Pol > * create (const Constraint< Pol > &_constraint)
const FormulaContent< Pol > * create (VariableComparison< Pol > &&_variableComparison)
const FormulaContent< Pol > * create (const VariableComparison< Pol > &_variableComparison)
const FormulaContent< Pol > * create (VariableAssignment< Pol > &&_variableAssignment)
const FormulaContent< Pol > * create (const VariableAssignment< Pol > &_variableAssignment)
const FormulaContent< Pol > * create (BVConstraint &&_constraint)
const FormulaContent< Pol > * create (const BVConstraint &_constraint)
const FormulaContent< Pol > * create (const PBConstraint< Pol > &_constraint)
const FormulaContent< Pol > * create (FormulaType _type, Formula< Pol > &&_subFormula)
Create formula representing a unary function.
const FormulaContent< Pol > * create (FormulaType _type, const Formulas< Pol > &_subformulas)
Create formula representing a nary function.
const FormulaContent< Pol > * create (FormulaType _type, const std::initializer_list< Formula< Pol >> &_subformulas)
const FormulaContent< Pol > * create (FormulaType _type, Formulas< Pol > &&_subformulas)
const FormulaContent< Pol > * createImplication (Formulas< Pol > &&_subformulas)
Create formula representing an implication.
const FormulaContent< Pol > * createNAry (FormulaType _type, Formulas< Pol > &&_subformulas)
const FormulaContent< Pol > * createITE (Formulas< Pol > &&_subformulas)
const FormulaContent< Pol > * create (FormulaType _type, std::vector< Variable > &&_vars, const Formula< Pol > &_term)
const FormulaContent< Pol > * create (const FormulasMulti< Pol > &_subformulas)
const FormulaContent< Pol > * create (const UEquality::Arg &_lhs, const UEquality::Arg &_rhs, bool _negated)
const FormulaContent< Pol > * create (UEquality &&eq)
const FormulaContent< Pol > * create (PBConstraint< Pol > &&pbc)
void free (const FormulaContent< Pol > *_elem)
bool freeTseitinVariable (const FormulaContent< Pol > *_toDelete)
void reg (const FormulaContent< Pol > *_elem) const
std::pair< typename FastPointerSet< FormulaContent< Pol > >::iterator, bool > insert (FormulaContent< Pol > *_formula)
Inserts the given formula to the pool, if it does not yet occur in there.
const FormulaContent< Pol > * add (FormulaContent< Pol > *_formula)
Adds the given formula to the pool, if it does not yet occur in there.
Private Attributes
friend Singleton< FormulaPool >
friend Formula< Pol >
unsigned mIdAllocator
id allocator
FormulaContent< Pol > * mpTrue
The unique formula representing true.
FormulaContent< Pol > * mpFalse
The unique formula representing false.
FastPointerSet< FormulaContent< Pol > > mPool
The formula pool.
std::recursive_mutex mMutexPool
Mutex to avoid multiple access to the pool.
FastPointerMap< FormulaContent< Pol >, const FormulaContent< Pol > * > mTseitinVars
FastPointerMap< FormulaContent< Pol >, typename FastPointerMap< FormulaContent< Pol >, const FormulaContent< Pol > * >::iterator > mTseitinVarToFormula
Detailed Description
template<typename Pol>
class carl::FormulaPool< Pol >
Definition at line 37 of file Formula.h.
Constructor & Destructor Documentation
FormulaPool()
template<typename Pol > carl::FormulaPool< Pol >::FormulaPool (unsigned _capacity = 10000) protected
Constructor of the formula pool.
Parameters
_capacity Expected necessary capacity of the pool.
~FormulaPool()
template<typename Pol > carl::FormulaPool< Pol >::~FormulaPool () protected
Member Function Documentation
add()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::add (FormulaContent< Pol > * _formula) private
Adds the given formula to the pool, if it does not yet occur in there.
Note, that this method uses the allocator which is locked before calling.
Parameters
_formula The formula to add to the pool.
Returns
The given formula, if it did not yet occur in the pool; The equivalent formula already occurring in the pool, otherwise.
Referenced by carl::FormulaPool< Pol >::create().
create() [1/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (FormulaType _type) inline private
Create formula representing a boolean value.
Parameters
_type Formula type, may be either TRUE or FALSE.
Returns
A formula representing the given bool.
Definition at line 234 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::create(), and carl::FormulaPool< Pol >::createTseitinVar().
create() [2/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (Variable::Arg _variable) inline private
Create formula representing a boolean variable.
Parameters
_booleanVar The Boolean variable wrapped by this formula.
Returns
A formula with wrapping the given Boolean variable.
Definition at line 244 of file FormulaPool.h.
create() [3/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (Constraint< Pol > && _constraint) inline private
Parameters
_constraint The constraint wrapped by this formula.
Returns
A formula with wrapping the given constraint.
Definition at line 252 of file FormulaPool.h.
create() [4/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const Constraint< Pol > & _constraint) inline private
Definition at line 266 of file FormulaPool.h.
create() [5/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (VariableComparison< Pol > && _variableComparison) inline private
Definition at line 269 of file FormulaPool.h.
create() [6/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const VariableComparison< Pol > & _variableComparison) inline private
Definition at line 276 of file FormulaPool.h.
create() [7/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (VariableAssignment< Pol > && _variableAssignment) inline private
Definition at line 281 of file FormulaPool.h.
create() [8/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const VariableAssignment< Pol > & _variableAssignment) inline private
Definition at line 288 of file FormulaPool.h.
create() [9/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (BVConstraint && _constraint) inline private
Definition at line 292 of file FormulaPool.h.
create() [10/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const BVConstraint & _constraint) inline private
Definition at line 299 of file FormulaPool.h.
create() [11/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const PBConstraint< Pol > & _constraint) inline private
Definition at line 302 of file FormulaPool.h.
create() [12/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (FormulaType _type, Formula< Pol > && _subFormula) inline private
Create formula representing a unary function.
Parameters
_type Formula type specifying the function.
_subFormula Formula representing the function argument.
Returns
A formula representing the given function call.
Definition at line 313 of file FormulaPool.h.
create() [13/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (FormulaType _type, const Formulas< Pol > & _subformulas) inline private
Create formula representing a nary function.
Parameters
_type Formula type specifying the function.
_subformulas Formula representing the function arguments.
Returns
A formula representing the given function call.
Definition at line 356 of file FormulaPool.h.
create() [14/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (FormulaType _type, const std::initializer_list< Formula< Pol >> & _subformulas) inline private
Definition at line 359 of file FormulaPool.h.
create() [15/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (FormulaType _type, Formulas< Pol > && _subformulas) inline private
Definition at line 362 of file FormulaPool.h.
create() [16/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (FormulaType _type, std::vector< Variable > && _vars, const Formula< Pol > & _term) inline private
Parameters
_type
_vars
_term
Returns
Definition at line 415 of file FormulaPool.h.
create() [17/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const FormulasMulti< Pol > & _subformulas) inline private
Parameters
_subformulas The sub-formulas of the formula to create.
Returns
A formula with the given operator and sub-formulas.
Definition at line 428 of file FormulaPool.h.
create() [18/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (const UEquality::Arg & _lhs, const UEquality::Arg & _rhs, bool _negated) inline private
Definition at line 464 of file FormulaPool.h.
create() [19/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (UEquality && eq) inline private
Definition at line 503 of file FormulaPool.h.
create() [20/20]
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::create (PBConstraint< Pol > && pbc) inline private
Definition at line 508 of file FormulaPool.h.
createImplication()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::createImplication (Formulas< Pol > && _subformulas) private
Create formula representing an implication.
Parameters
_subformulas
Returns
Referenced by carl::FormulaPool< Pol >::create().
createITE()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::createITE (Formulas< Pol > && _subformulas) private
Referenced by carl::FormulaPool< Pol >::create().
createNAry()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::createNAry (FormulaType _type, Formulas< Pol > && _subformulas) private
Referenced by carl::FormulaPool< Pol >::create().
createNegatedContent()
template<typename Pol > FormulaContent<Pol>* carl::FormulaPool< Pol >::createNegatedContent (const FormulaContent< Pol > * f) const inline private
Definition at line 197 of file FormulaPool.h.
createTseitinVar()
template<typename Pol > Formula<Pol> carl::FormulaPool< Pol >::createTseitinVar (const Formula< Pol > & _formula) inline
Definition at line 121 of file FormulaPool.h.
falseFormula()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::falseFormula () const inline protected
Definition at line 74 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::create().
forallDo() [1/2]
template<typename Pol > template<typename ArgType > void carl::FormulaPool< Pol >::forallDo (void(*)(ArgType *, const Formula< Pol > &) _func, ArgType * _arg) const inline
Definition at line 606 of file FormulaPool.h.
forallDo() [2/2]
template<typename Pol > template<typename ReturnType , typename ArgType > std::map<const Formula<Pol>,ReturnType> carl::FormulaPool< Pol >::forallDo (ReturnType(*)(ArgType *, const Formula< Pol > &) _func, ArgType * _arg) const inline
Definition at line 620 of file FormulaPool.h.
formulasInverse()
template<typename Pol > bool carl::FormulaPool< Pol >::formulasInverse (const Formula< Pol > & _subformulaA, const Formula< Pol > & _subformulaB)
free()
template<typename Pol > void carl::FormulaPool< Pol >::free (const FormulaContent< Pol > * _elem) inline private
Definition at line 513 of file FormulaPool.h.
freeTseitinVariable()
template<typename Pol > bool carl::FormulaPool< Pol >::freeTseitinVariable (const FormulaContent< Pol > * _toDelete) inline private
Definition at line 541 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::free().
getBaseFormula()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::getBaseFormula (const FormulaContent< Pol > * f) const inline private
Definition at line 178 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::free(), carl::FormulaPool< Pol >::freeTseitinVariable(), and carl::FormulaPool< Pol >::reg().
getInstance()
static FormulaPool< Pol > & carl::Singleton< FormulaPool< Pol > >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::Formula< Poly >::Formula(), carl::Formula< Poly >::operator=(), and carl::Formula< Poly >::~Formula().
getTseitinVar()
template<typename Pol > Formula<Pol> carl::FormulaPool< Pol >::getTseitinVar (const Formula< Pol > & _formula) inline
Definition at line 111 of file FormulaPool.h.
insert()
template<typename Pol > std::pair<typename FastPointerSet<FormulaContent<Pol> >::iterator,bool> carl::FormulaPool< Pol >::insert (FormulaContent< Pol > * _formula) private
Inserts the given formula to the pool, if it does not yet occur in there.
Parameters
_type The type of the n-ary operator (n>1) of the formula to create.
_subformulas The sub-formulas of the formula to create.
Returns
A formula with the given operator and sub-formulas. Note, that if you use this method to create a formula with the operator XOR and you have collected the sub-formulas in a set, multiple occurrences of a sub-formula are condensed. You should only use it, if you can exlcude this possibility. Otherwise use the method newExclusiveDisjunction.
Parameters
_formula The formula to add to the pool.
Returns
The position of the given formula in the pool and true, if it did not yet occur in the pool; The position of the equivalent formula in the pool and false, otherwise.
isBaseFormula() [1/4]
template<typename Pol > bool carl::FormulaPool< Pol >::isBaseFormula (const Constraint< Pol > & c) const inline private
Definition at line 135 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::create(), carl::FormulaPool< Pol >::free(), and carl::FormulaPool< Pol >::getBaseFormula().
isBaseFormula() [2/4]
template<typename Pol > bool carl::FormulaPool< Pol >::isBaseFormula (const VariableComparison< Pol > & vc) const inline private
Definition at line 138 of file FormulaPool.h.
isBaseFormula() [3/4]
template<typename Pol > bool carl::FormulaPool< Pol >::isBaseFormula (const VariableAssignment< Pol > & va) const inline private
Definition at line 141 of file FormulaPool.h.
isBaseFormula() [4/4]
template<typename Pol > bool carl::FormulaPool< Pol >::isBaseFormula (const FormulaContent< Pol > * f) const inline private
Definition at line 144 of file FormulaPool.h.
print()
template<typename Pol > void carl::FormulaPool< Pol >::print () const inline
Definition at line 84 of file FormulaPool.h.
reg()
template<typename Pol > void carl::FormulaPool< Pol >::reg (const FormulaContent< Pol > * _elem) const inline private
Definition at line 589 of file FormulaPool.h.
size()
template<typename Pol > std::size_t carl::FormulaPool< Pol >::size () const inline
Definition at line 80 of file FormulaPool.h.
trueFormula()
template<typename Pol > const FormulaContent<Pol>* carl::FormulaPool< Pol >::trueFormula () const inline protected
Definition at line 69 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::create(), and carl::FormulaPool< Pol >::getTseitinVar().
Field Documentation
Formula< Pol >
template<typename Pol > friend carl::FormulaPool< Pol >::Formula< Pol > private
Definition at line 29 of file FormulaPool.h.
mIdAllocator
template<typename Pol > unsigned carl::FormulaPool< Pol >::mIdAllocator private
id allocator
Definition at line 35 of file FormulaPool.h.
mMutexPool
template<typename Pol > std::recursive_mutex carl::FormulaPool< Pol >::mMutexPool mutable private
Mutex to avoid multiple access to the pool.
Definition at line 43 of file FormulaPool.h.
mpFalse
template<typename Pol > FormulaContent<Pol>* carl::FormulaPool< Pol >::mpFalse private
The unique formula representing false.
Definition at line 39 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::falseFormula(), and carl::FormulaPool< Pol >::forallDo().
mPool
template<typename Pol > FastPointerSet<FormulaContent<Pol> > carl::FormulaPool< Pol >::mPool private
The formula pool.
Definition at line 41 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::forallDo(), carl::FormulaPool< Pol >::free(), carl::FormulaPool< Pol >::freeTseitinVariable(), carl::FormulaPool< Pol >::print(), and carl::FormulaPool< Pol >::size().
mpTrue
template<typename Pol > FormulaContent<Pol>* carl::FormulaPool< Pol >::mpTrue private
The unique formula representing true.
Definition at line 37 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::trueFormula().
mTseitinVars
template<typename Pol > FastPointerMap<FormulaContent<Pol>,const FormulaContent<Pol>*> carl::FormulaPool< Pol >::mTseitinVars private
Definition at line 45 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::createTseitinVar(), carl::FormulaPool< Pol >::freeTseitinVariable(), carl::FormulaPool< Pol >::getTseitinVar(), and carl::FormulaPool< Pol >::print().
mTseitinVarToFormula
template<typename Pol > FastPointerMap<FormulaContent<Pol>,typename FastPointerMap<FormulaContent<Pol>,const FormulaContent<Pol>*>::iterator> carl::FormulaPool< Pol >::mTseitinVarToFormula private
Definition at line 47 of file FormulaPool.h.
Referenced by carl::FormulaPool< Pol >::createTseitinVar(), carl::FormulaPool< Pol >::freeTseitinVariable(), and carl::FormulaPool< Pol >::print().
Singleton< FormulaPool >
template<typename Pol > friend carl::FormulaPool< Pol >::Singleton< FormulaPool > private
Definition at line 28 of file FormulaPool.h.
The documentation for this class was generated from the following files:
carl/formula/Formula.h
carl/formula/FormulaPool.h