carl: carl::RationalFunction< Pol, AutoSimplify > Class Template Reference
carl::RationalFunction< Pol, AutoSimplify > Class Template Reference
#include <RationalFunction.h>
Public Types
using PolyType = Pol
using CoeffType = typename Pol::CoeffType
using NumberType = typename Pol::NumberType
Public Member Functions
RationalFunction ()
RationalFunction (int v)
RationalFunction (const CoeffType &c)
template<typename P = Pol, DisableIf< needs_cache< P >> = dummy>
RationalFunction (Variable v)
RationalFunction (const Pol &p)
RationalFunction (Pol &&p)
RationalFunction (const Pol &nom, const Pol &denom)
RationalFunction (Pol &&nom, Pol &&denom)
RationalFunction (boost::optional< std::pair< Pol, Pol >> &&quotient, const CoeffType &num, bool simplified)
RationalFunction (const RationalFunction &_rf)=default
RationalFunction (RationalFunction &&_rf)=default
~RationalFunction () noexcept=default
RationalFunction & operator= (const RationalFunction &_rf)=default
RationalFunction & operator= (RationalFunction &&_rf)=default
Pol nominator () const
Pol denominator () const
const Pol & nominatorAsPolynomial () const
const Pol & denominatorAsPolynomial () const
CoeffType nominatorAsNumber () const
CoeffType denominatorAsNumber () const
bool isSimplified () const
Checks if this rational function has been simplified since it's last modification.
void simplify ()
RationalFunction inverse () const
Returns the inverse of this rational function.
bool isZero () const
Check whether the rational function is zero.
bool isOne () const
bool isConstant () const
CoeffType constantPart () const
std::set< Variable > gatherVariables () const
Collect all occurring variables.
void gatherVariables (std::set< Variable > &vars) const
Add all occurring variables to the set vars.
CoeffType evaluate (const std::map< Variable, CoeffType > &substitutions) const
Evaluate the polynomial at the point described by substitutions.
RationalFunction substitute (const std::map< Variable, CoeffType > &substitutions) const
RationalFunction derivative (const Variable &x, unsigned nth=1) const
Derivative of the rational function with respect to variable x.
std::string toString (bool infix=true, bool friendlyNames=true) const
RationalFunction & operator/= (const RationalFunction &rhs)
Divide this rational function by something and return the changed rational function.
RationalFunction & operator/= (const Pol &rhs)
RationalFunction & operator/= (const Term< CoeffType > &rhs)
RationalFunction & operator/= (const Monomial::Arg &rhs)
template<typename P = Pol, DisableIf< needs_cache< P >> = dummy>
RationalFunction & operator/= (Variable rhs)
RationalFunction & operator/= (const CoeffType &rhs)
RationalFunction & operator/= (unsigned long rhs)
In-place addition operators
RationalFunction & operator+= (const RationalFunction &rhs)
Add something to this rational function and return the changed rational function.
RationalFunction & operator+= (const Pol &rhs)
Add something to this rational function and return the changed rational function.
RationalFunction & operator+= (const Term< CoeffType > &rhs)
Add something to this rational function and return the changed rational function.
RationalFunction & operator+= (const Monomial::Arg &rhs)
Add something to this rational function and return the changed rational function.
template<typename P = Pol, DisableIf< needs_cache< P >> = dummy>
RationalFunction & operator+= (Variable rhs)
Add something to this rational function and return the changed rational function.
RationalFunction & operator+= (const CoeffType &rhs)
Add something to this rational function and return the changed rational function.
In-place subtraction operators
RationalFunction & operator-= (const RationalFunction &rhs)
Subtract something from this rational function and return the changed rational function.
RationalFunction & operator-= (const Pol &rhs)
Subtract something from this rational function and return the changed rational function.
RationalFunction & operator-= (const Term< CoeffType > &rhs)
Subtract something from this rational function and return the changed rational function.
RationalFunction & operator-= (const Monomial::Arg &rhs)
Subtract something from this rational function and return the changed rational function.
template<typename P = Pol, DisableIf< needs_cache< P >> = dummy>
RationalFunction & operator-= (Variable rhs)
Subtract something from this rational function and return the changed rational function.
RationalFunction & operator-= (const CoeffType &rhs)
Subtract something from this rational function and return the changed rational function.
In-place multiplication operators
RationalFunction & operator*= (const RationalFunction &rhs)
Multiply something with this rational function and return the changed rational function.
RationalFunction & operator*= (const Pol &rhs)
Multiply something with this rational function and return the changed rational function.
RationalFunction & operator*= (const Term< CoeffType > &rhs)
Multiply something with this rational function and return the changed rational function.
RationalFunction & operator*= (const Monomial::Arg &rhs)
Multiply something with this rational function and return the changed rational function.
template<typename P = Pol, DisableIf< needs_cache< P >> = dummy>
RationalFunction & operator*= (Variable rhs)
Multiply something with this rational function and return the changed rational function.
RationalFunction & operator*= (const CoeffType &rhs)
Multiply something with this rational function and return the changed rational function.
RationalFunction & operator*= (carl::sint rhs)
Multiply something with this rational function and return the changed rational function.
Private Member Functions
void eliminateCommonFactor (bool _justNormalize)
Helper function for simplify which eliminates the common factor.
template<bool byInverse = false>
RationalFunction & add (const RationalFunction &rhs)
template<bool byInverse = false>
RationalFunction & add (const Pol &rhs)
template<bool byInverse = false, typename P = Pol, DisableIf< needs_cache< P >> = dummy>
RationalFunction & add (Variable rhs)
template<bool byInverse = false>
RationalFunction & add (const CoeffType &rhs)
Private Attributes
boost::optional< std::pair< Pol, Pol > > mPolynomialQuotient
CoeffType mNumberQuotient
bool mIsSimplified
Friends
template<typename PolA , bool ASA>
bool operator== (const RationalFunction< PolA, ASA > &lhs, const RationalFunction< PolA, ASA > &rhs)
template<typename PolA , bool ASA>
bool operator< (const RationalFunction< PolA, ASA > &lhs, const RationalFunction< PolA, ASA > &rhs)
template<typename PolA , bool ASA>
std::ostream & operator<< (std::ostream &os, const RationalFunction< PolA, ASA > &rhs)
Detailed Description
template<typename Pol, bool AutoSimplify = false>
class carl::RationalFunction< Pol, AutoSimplify >
Definition at line 18 of file RationalFunction.h.
Member Typedef Documentation
CoeffType
template<typename Pol, bool AutoSimplify = false> using carl::RationalFunction< Pol, AutoSimplify >::CoeffType = typename Pol::CoeffType
Definition at line 21 of file RationalFunction.h.
NumberType
template<typename Pol, bool AutoSimplify = false> using carl::RationalFunction< Pol, AutoSimplify >::NumberType = typename Pol::NumberType
Definition at line 22 of file RationalFunction.h.
PolyType
template<typename Pol, bool AutoSimplify = false> using carl::RationalFunction< Pol, AutoSimplify >::PolyType = Pol
Definition at line 20 of file RationalFunction.h.
Constructor & Destructor Documentation
RationalFunction() [1/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction () inline
Definition at line 30 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::inverse(), and carl::RationalFunction< Pol, AutoSimplify >::substitute().
RationalFunction() [2/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (int v) inline explicit
Definition at line 34 of file RationalFunction.h.
RationalFunction() [3/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (const CoeffType & c) inline explicit
Definition at line 38 of file RationalFunction.h.
RationalFunction() [4/11]
template<typename Pol, bool AutoSimplify = false> template<typename P = Pol, DisableIf< needs_cache< P >> = dummy> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (Variable v) inline explicit
Definition at line 43 of file RationalFunction.h.
RationalFunction() [5/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (const Pol & p) inline explicit
Definition at line 48 of file RationalFunction.h.
RationalFunction() [6/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (Pol && p) inline explicit
Definition at line 57 of file RationalFunction.h.
RationalFunction() [7/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (const Pol & nom, const Pol & denom) inline explicit
Definition at line 66 of file RationalFunction.h.
RationalFunction() [8/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (Pol && nom, Pol && denom) inline explicit
Definition at line 79 of file RationalFunction.h.
RationalFunction() [9/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (boost::optional< std::pair< Pol, Pol >> && quotient, const CoeffType & num, bool simplified) inline explicit
Definition at line 87 of file RationalFunction.h.
RationalFunction() [10/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (const RationalFunction< Pol, AutoSimplify > & _rf) default
RationalFunction() [11/11]
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::RationalFunction (RationalFunction< Pol, AutoSimplify > && _rf) default
~RationalFunction()
template<typename Pol, bool AutoSimplify = false> carl::RationalFunction< Pol, AutoSimplify >::~RationalFunction () default noexcept
Member Function Documentation
add() [1/4]
template<typename Pol, bool AutoSimplify = false> template<bool byInverse = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::add (const RationalFunction< Pol, AutoSimplify > & rhs) private
add() [2/4]
template<typename Pol, bool AutoSimplify = false> template<bool byInverse = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::add (const Pol & rhs) private
add() [3/4]
template<typename Pol, bool AutoSimplify = false> template<bool byInverse = false, typename P = Pol, DisableIf< needs_cache< P >> = dummy> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::add (Variable rhs) private
add() [4/4]
template<typename Pol, bool AutoSimplify = false> template<bool byInverse = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::add (const CoeffType & rhs) private
constantPart()
template<typename Pol, bool AutoSimplify = false> CoeffType carl::RationalFunction< Pol, AutoSimplify >::constantPart () const inline
Definition at line 204 of file RationalFunction.h.
denominator()
template<typename Pol, bool AutoSimplify = false> Pol carl::RationalFunction< Pol, AutoSimplify >::denominator () const inline
Returns
The denominator
Definition at line 115 of file RationalFunction.h.
Referenced by carl::parser::ExpressionParser< Pol >::perform_division::operator()(), and carl::parser::ExpressionParser< Pol >::perform_power::operator()().
denominatorAsNumber()
template<typename Pol, bool AutoSimplify = false> CoeffType carl::RationalFunction< Pol, AutoSimplify >::denominatorAsNumber () const inline
Returns
The denominator as a polynomial.
Definition at line 148 of file RationalFunction.h.
Referenced by std::hash< carl::RationalFunction< Pol, AS > >::operator()().
denominatorAsPolynomial()
template<typename Pol, bool AutoSimplify = false> const Pol& carl::RationalFunction< Pol, AutoSimplify >::denominatorAsPolynomial () const inline
Returns
The denominator as a polynomial.
Definition at line 132 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::constantPart(), carl::RationalFunction< Pol, AutoSimplify >::evaluate(), carl::RationalFunction< Pol, AutoSimplify >::gatherVariables(), carl::RationalFunction< Pol, AutoSimplify >::isOne(), carl::RationalFunction< Pol, AutoSimplify >::isZero(), std::hash< carl::RationalFunction< Pol, AS > >::operator()(), carl::RationalFunction< Pol, AutoSimplify >::RationalFunction(), and carl::RationalFunction< Pol, AutoSimplify >::substitute().
derivative()
template<typename Pol, bool AutoSimplify = false> RationalFunction carl::RationalFunction< Pol, AutoSimplify >::derivative (const Variable & x, unsigned nth = 1) const
Derivative of the rational function with respect to variable x.
Parameters
x the main variable
nth which derivative one should take
Returns
Todo:
Currently only nth = 1 is supported
Curretnly only factorized polynomials are supported
eliminateCommonFactor()
template<typename Pol, bool AutoSimplify = false> void carl::RationalFunction< Pol, AutoSimplify >::eliminateCommonFactor (bool _justNormalize) private
Helper function for simplify which eliminates the common factor.
Parameters
_justNormalize
Referenced by carl::RationalFunction< Pol, AutoSimplify >::RationalFunction(), and carl::RationalFunction< Pol, AutoSimplify >::simplify().
evaluate()
template<typename Pol, bool AutoSimplify = false> CoeffType carl::RationalFunction< Pol, AutoSimplify >::evaluate (const std::map< Variable, CoeffType > & substitutions) const inline
Evaluate the polynomial at the point described by substitutions.
Parameters
substitutions A mapping from variable to constant values.
Returns
The result of the substitution
Definition at line 236 of file RationalFunction.h.
gatherVariables() [1/2]
template<typename Pol, bool AutoSimplify = false> std::set<Variable> carl::RationalFunction< Pol, AutoSimplify >::gatherVariables () const inline
Collect all occurring variables.
Returns
All occcurring variables
Definition at line 214 of file RationalFunction.h.
gatherVariables() [2/2]
template<typename Pol, bool AutoSimplify = false> void carl::RationalFunction< Pol, AutoSimplify >::gatherVariables (std::set< Variable > & vars) const inline
Add all occurring variables to the set vars.
Parameters
vars
Definition at line 224 of file RationalFunction.h.
inverse()
template<typename Pol, bool AutoSimplify = false> RationalFunction carl::RationalFunction< Pol, AutoSimplify >::inverse () const inline
Returns the inverse of this rational function.
Returns
Inverse of this.
Definition at line 173 of file RationalFunction.h.
isConstant()
template<typename Pol, bool AutoSimplify = false> bool carl::RationalFunction< Pol, AutoSimplify >::isConstant () const inline
Definition at line 200 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::constantPart(), carl::RationalFunction< Pol, AutoSimplify >::denominator(), carl::RationalFunction< Pol, AutoSimplify >::denominatorAsNumber(), carl::RationalFunction< Pol, AutoSimplify >::denominatorAsPolynomial(), carl::RationalFunction< Pol, AutoSimplify >::evaluate(), carl::RationalFunction< Pol, AutoSimplify >::gatherVariables(), carl::RationalFunction< Pol, AutoSimplify >::inverse(), carl::RationalFunction< Pol, AutoSimplify >::isOne(), carl::RationalFunction< Pol, AutoSimplify >::isZero(), carl::RationalFunction< Pol, AutoSimplify >::nominator(), carl::RationalFunction< Pol, AutoSimplify >::nominatorAsNumber(), carl::RationalFunction< Pol, AutoSimplify >::nominatorAsPolynomial(), std::hash< carl::RationalFunction< Pol, AS > >::operator()(), carl::RationalFunction< Pol, AutoSimplify >::RationalFunction(), and carl::RationalFunction< Pol, AutoSimplify >::substitute().
isOne()
template<typename Pol, bool AutoSimplify = false> bool carl::RationalFunction< Pol, AutoSimplify >::isOne () const inline
Definition at line 193 of file RationalFunction.h.
isSimplified()
template<typename Pol, bool AutoSimplify = false> bool carl::RationalFunction< Pol, AutoSimplify >::isSimplified () const inline
Checks if this rational function has been simplified since it's last modification.
Note that if AutoSimplify is true, this should always return true.
Returns
If this is simplified.
Definition at line 158 of file RationalFunction.h.
isZero()
template<typename Pol, bool AutoSimplify = false> bool carl::RationalFunction< Pol, AutoSimplify >::isZero () const inline
Check whether the rational function is zero.
Returns
true if it is
Definition at line 186 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::inverse(), carl::RationalFunction< Pol, AutoSimplify >::isOne(), and carl::RationalFunction< Pol, AutoSimplify >::RationalFunction().
nominator()
template<typename Pol, bool AutoSimplify = false> Pol carl::RationalFunction< Pol, AutoSimplify >::nominator () const inline
Returns
The nominator
Definition at line 105 of file RationalFunction.h.
Referenced by carl::parser::ExpressionParser< Pol >::perform_division::operator()(), and carl::parser::ExpressionParser< Pol >::perform_power::operator()().
nominatorAsNumber()
template<typename Pol, bool AutoSimplify = false> CoeffType carl::RationalFunction< Pol, AutoSimplify >::nominatorAsNumber () const inline
Returns
The nominator as a polynomial.
Definition at line 140 of file RationalFunction.h.
Referenced by std::hash< carl::RationalFunction< Pol, AS > >::operator()().
nominatorAsPolynomial()
template<typename Pol, bool AutoSimplify = false> const Pol& carl::RationalFunction< Pol, AutoSimplify >::nominatorAsPolynomial () const inline
Returns
The nominator as a polynomial.
Definition at line 124 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::constantPart(), carl::RationalFunction< Pol, AutoSimplify >::evaluate(), carl::RationalFunction< Pol, AutoSimplify >::gatherVariables(), carl::RationalFunction< Pol, AutoSimplify >::isOne(), carl::RationalFunction< Pol, AutoSimplify >::isZero(), std::hash< carl::RationalFunction< Pol, AS > >::operator()(), and carl::RationalFunction< Pol, AutoSimplify >::substitute().
operator*=() [1/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (const RationalFunction< Pol, AutoSimplify > & rhs)
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
operator*=() [2/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (const Pol & rhs)
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
operator*=() [3/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (const Term< CoeffType > & rhs) inline
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 362 of file RationalFunction.h.
operator*=() [4/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (const Monomial::Arg & rhs) inline
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 365 of file RationalFunction.h.
operator*=() [5/7]
template<typename Pol, bool AutoSimplify = false> template<typename P = Pol, DisableIf< needs_cache< P >> = dummy> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (Variable rhs)
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
operator*=() [6/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (const CoeffType & rhs)
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
operator*=() [7/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator*= (carl::sint rhs)
Multiply something with this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
operator+=() [1/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator+= (const RationalFunction< Pol, AutoSimplify > & rhs) inline
Add something to this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 292 of file RationalFunction.h.
operator+=() [2/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator+= (const Pol & rhs) inline
Add something to this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 296 of file RationalFunction.h.
operator+=() [3/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator+= (const Term< CoeffType > & rhs) inline
Add something to this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 300 of file RationalFunction.h.
operator+=() [4/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator+= (const Monomial::Arg & rhs) inline
Add something to this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 305 of file RationalFunction.h.
operator+=() [5/6]
template<typename Pol, bool AutoSimplify = false> template<typename P = Pol, DisableIf< needs_cache< P >> = dummy> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator+= (Variable rhs) inline
Add something to this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 311 of file RationalFunction.h.
operator+=() [6/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator+= (const CoeffType & rhs) inline
Add something to this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 315 of file RationalFunction.h.
operator-=() [1/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator-= (const RationalFunction< Pol, AutoSimplify > & rhs) inline
Subtract something from this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 327 of file RationalFunction.h.
operator-=() [2/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator-= (const Pol & rhs) inline
Subtract something from this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 331 of file RationalFunction.h.
operator-=() [3/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator-= (const Term< CoeffType > & rhs) inline
Subtract something from this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 335 of file RationalFunction.h.
operator-=() [4/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator-= (const Monomial::Arg & rhs) inline
Subtract something from this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 339 of file RationalFunction.h.
operator-=() [5/6]
template<typename Pol, bool AutoSimplify = false> template<typename P = Pol, DisableIf< needs_cache< P >> = dummy> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator-= (Variable rhs) inline
Subtract something from this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 344 of file RationalFunction.h.
operator-=() [6/6]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator-= (const CoeffType & rhs) inline
Subtract something from this rational function and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
Definition at line 348 of file RationalFunction.h.
operator/=() [1/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (const RationalFunction< Pol, AutoSimplify > & rhs)
Divide this rational function by something and return the changed rational function.
Parameters
rhs Right hand side.
Returns
Changed rational function.
operator/=() [2/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (const Pol & rhs)
operator/=() [3/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (const Term< CoeffType > & rhs) inline
Definition at line 381 of file RationalFunction.h.
operator/=() [4/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (const Monomial::Arg & rhs) inline
Definition at line 384 of file RationalFunction.h.
operator/=() [5/7]
template<typename Pol, bool AutoSimplify = false> template<typename P = Pol, DisableIf< needs_cache< P >> = dummy> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (Variable rhs)
operator/=() [6/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (const CoeffType & rhs)
operator/=() [7/7]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator/= (unsigned long rhs)
operator=() [1/2]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator= (const RationalFunction< Pol, AutoSimplify > & _rf) default
operator=() [2/2]
template<typename Pol, bool AutoSimplify = false> RationalFunction& carl::RationalFunction< Pol, AutoSimplify >::operator= (RationalFunction< Pol, AutoSimplify > && _rf) default
simplify()
template<typename Pol, bool AutoSimplify = false> void carl::RationalFunction< Pol, AutoSimplify >::simplify () inline
Definition at line 162 of file RationalFunction.h.
substitute()
template<typename Pol, bool AutoSimplify = false> RationalFunction carl::RationalFunction< Pol, AutoSimplify >::substitute (const std::map< Variable, CoeffType > & substitutions) const inline
Definition at line 244 of file RationalFunction.h.
toString()
template<typename Pol, bool AutoSimplify = false> std::string carl::RationalFunction< Pol, AutoSimplify >::toString (bool infix = true, bool friendlyNames = true) const
Friends And Related Function Documentation
operator<
template<typename Pol, bool AutoSimplify = false> template<typename PolA , bool ASA> bool operator< (const RationalFunction< PolA, ASA > & lhs, const RationalFunction< PolA, ASA > & rhs) friend
operator<<
template<typename Pol, bool AutoSimplify = false> template<typename PolA , bool ASA> std::ostream& operator<< (std::ostream & os, const RationalFunction< PolA, ASA > & rhs) friend
operator==
template<typename Pol, bool AutoSimplify = false> template<typename PolA , bool ASA> bool operator== (const RationalFunction< PolA, ASA > & lhs, const RationalFunction< PolA, ASA > & rhs) friend
Field Documentation
mIsSimplified
template<typename Pol, bool AutoSimplify = false> bool carl::RationalFunction< Pol, AutoSimplify >::mIsSimplified private
Definition at line 27 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::inverse(), carl::RationalFunction< Pol, AutoSimplify >::isSimplified(), and carl::RationalFunction< Pol, AutoSimplify >::RationalFunction().
mNumberQuotient
template<typename Pol, bool AutoSimplify = false> CoeffType carl::RationalFunction< Pol, AutoSimplify >::mNumberQuotient private
Definition at line 26 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::constantPart(), carl::RationalFunction< Pol, AutoSimplify >::denominator(), carl::RationalFunction< Pol, AutoSimplify >::denominatorAsNumber(), carl::RationalFunction< Pol, AutoSimplify >::evaluate(), carl::RationalFunction< Pol, AutoSimplify >::inverse(), carl::RationalFunction< Pol, AutoSimplify >::isOne(), carl::RationalFunction< Pol, AutoSimplify >::isZero(), carl::RationalFunction< Pol, AutoSimplify >::nominator(), carl::RationalFunction< Pol, AutoSimplify >::nominatorAsNumber(), and carl::RationalFunction< Pol, AutoSimplify >::RationalFunction().
mPolynomialQuotient
template<typename Pol, bool AutoSimplify = false> boost::optional<std::pair<Pol, Pol> > carl::RationalFunction< Pol, AutoSimplify >::mPolynomialQuotient private
Definition at line 25 of file RationalFunction.h.
Referenced by carl::RationalFunction< Pol, AutoSimplify >::denominator(), carl::RationalFunction< Pol, AutoSimplify >::denominatorAsPolynomial(), carl::RationalFunction< Pol, AutoSimplify >::inverse(), carl::RationalFunction< Pol, AutoSimplify >::isConstant(), carl::RationalFunction< Pol, AutoSimplify >::nominator(), carl::RationalFunction< Pol, AutoSimplify >::nominatorAsPolynomial(), and carl::RationalFunction< Pol, AutoSimplify >::RationalFunction().
The documentation for this class was generated from the following file:
carl/core/RationalFunction.h