carl: carl::MultivariateRoot< Poly > Class Template Reference
carl::MultivariateRoot< Poly > Class Template Reference
#include <MultivariateRoot.h>
Public Types
using Number = typename UnderlyingNumberType< Poly >::type
using RAN = RealAlgebraicNumber< Number >
using EvalMap = RealAlgebraicNumberEvaluation::RANMap< Number >
Public Member Functions
MultivariateRoot (const Poly &poly, std::size_t rootIdx)
std::size_t k () const noexcept
Return the rootIndex, also know as k, rootNumber, rootId.
const Poly & poly () const noexcept
Poly poly (Variable var) const
Create of copy of the underlying polynomial with the main/substitution variable replaced by the given variable.
bool isUnivariate () const
std::set< Variable > gatherVariables () const
void substituteIn (Variable var, const Poly &poly)
Create a copy of the underlying polynomial with the given variable replaced by the given polynomial.
boost::optional< RAN > evaluate (const EvalMap &m) const
Return the emerging algebraic real after pluggin in a subpoint, i.e., replacing all non-main/substitution variables with algebraic reals.
Static Public Member Functions
static Variable var () noexcept
Private Attributes
Poly mPoly
std::size_t mK
Static Private Attributes
static const Variable sVar = carl::VariablePool::getInstance().getFreshPersistentVariable("__z")
Distinguished main/substitution variable, intended to be SMTRAT/globally unique.
Detailed Description
template<typename Poly>
class carl::MultivariateRoot< Poly >
Definition at line 30 of file MultivariateRoot.h.
Member Typedef Documentation
EvalMap
template<typename Poly> using carl::MultivariateRoot< Poly >::EvalMap = RealAlgebraicNumberEvaluation::RANMap<Number>
Definition at line 34 of file MultivariateRoot.h.
Number
template<typename Poly> using carl::MultivariateRoot< Poly >::Number = typename UnderlyingNumberType<Poly>::type
Definition at line 32 of file MultivariateRoot.h.
RAN
template<typename Poly> using carl::MultivariateRoot< Poly >::RAN = RealAlgebraicNumber<Number>
Definition at line 33 of file MultivariateRoot.h.
Constructor & Destructor Documentation
MultivariateRoot()
template<typename Poly> carl::MultivariateRoot< Poly >::MultivariateRoot (const Poly & poly, std::size_t rootIdx) inline
Parameters
poly Must mention the main/substituion variable and should have a at least 'rootIdx'-many roots at each subpoint where it is intended to be evaluated. We have no way to ensure/check that.
rootIdx Must be a positive number, because we count from 1, i.e., first root has index 1.
Definition at line 51 of file MultivariateRoot.h.
Member Function Documentation
evaluate()
template<typename Poly> boost::optional<RAN> carl::MultivariateRoot< Poly >::evaluate (const EvalMap & m) const inline
Return the emerging algebraic real after pluggin in a subpoint, i.e., replacing all non-main/substitution variables with algebraic reals.
Parameters
m must contain algebraic real assignments for all non-main variables.
Returns
boost::none if the underlying polynomial has no 'rootIdx'th at the given subpoint.
Definition at line 109 of file MultivariateRoot.h.
Referenced by carl::model::evaluate().
gatherVariables()
template<typename Poly> std::set<Variable> carl::MultivariateRoot< Poly >::gatherVariables () const inline
Definition at line 87 of file MultivariateRoot.h.
Referenced by carl::model::evaluate(), carl::VariableComparison< Poly >::VariableCollector::operator()(), and carl::model::substituteIn().
isUnivariate()
template<typename Poly> bool carl::MultivariateRoot< Poly >::isUnivariate () const inline
Definition at line 83 of file MultivariateRoot.h.
k()
template<typename Poly> std::size_t carl::MultivariateRoot< Poly >::k () const inline noexcept
Return the rootIndex, also know as k, rootNumber, rootId.
Definition at line 59 of file MultivariateRoot.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), std::hash< carl::MultivariateRoot< Pol > >::operator()(), and carl::operator==().
poly() [1/2]
template<typename Poly> const Poly& carl::MultivariateRoot< Poly >::poly () const inline noexcept
Definition at line 63 of file MultivariateRoot.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::ModelMVRootSubstitution< Rational, Poly >::dependsOn(), carl::MultivariateRoot< Poly >::evaluate(), std::hash< carl::MultivariateRoot< Pol > >::operator()(), carl::operator<<(), carl::operator==(), and carl::MultivariateRoot< Poly >::substituteIn().
poly() [2/2]
template<typename Poly> Poly carl::MultivariateRoot< Poly >::poly (Variable var) const inline
Create of copy of the underlying polynomial with the main/substitution variable replaced by the given variable.
Definition at line 71 of file MultivariateRoot.h.
substituteIn()
template<typename Poly> void carl::MultivariateRoot< Poly >::substituteIn (Variable var, const Poly & poly) inline
Create a copy of the underlying polynomial with the given variable replaced by the given polynomial.
Definition at line 97 of file MultivariateRoot.h.
Referenced by carl::model::substituteIn().
var()
template<typename Poly> static Variable carl::MultivariateRoot< Poly >::var () inline static noexcept
Returns
The globally unique distinguished main/substitution variable to allow you to build a polynomial with this variable yourself.
Definition at line 79 of file MultivariateRoot.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::MultivariateRoot< Poly >::gatherVariables(), carl::operator<<(), carl::MultivariateRoot< Poly >::poly(), and carl::MultivariateRoot< Poly >::substituteIn().
Field Documentation
mK
template<typename Poly> std::size_t carl::MultivariateRoot< Poly >::mK private
Definition at line 42 of file MultivariateRoot.h.
Referenced by carl::MultivariateRoot< Poly >::evaluate(), and carl::MultivariateRoot< Poly >::k().
mPoly
template<typename Poly> Poly carl::MultivariateRoot< Poly >::mPoly private
Definition at line 41 of file MultivariateRoot.h.
Referenced by carl::MultivariateRoot< Poly >::evaluate(), carl::MultivariateRoot< Poly >::gatherVariables(), carl::MultivariateRoot< Poly >::isUnivariate(), carl::MultivariateRoot< Poly >::poly(), and carl::MultivariateRoot< Poly >::substituteIn().
sVar
template<typename Poly> const Variable carl::MultivariateRoot< Poly >::sVar = carl::VariablePool::getInstance().getFreshPersistentVariable("__z") static private
Distinguished main/substitution variable, intended to be SMTRAT/globally unique.
Definition at line 40 of file MultivariateRoot.h.
Referenced by carl::MultivariateRoot< Poly >::evaluate(), carl::MultivariateRoot< Poly >::gatherVariables(), carl::MultivariateRoot< Poly >::poly(), and carl::MultivariateRoot< Poly >::var().
The documentation for this class was generated from the following file:
carl/formula/model/mvroot/MultivariateRoot.h