carl: carl::rootfinder::AbstractRootFinder< Number > Class Template Reference
carl::rootfinder::AbstractRootFinder< Number > Class Template Reference abstract
Base class for a root finding algorithm for a single univariate polynomial.
#include <AbstractRootFinder.h>
Public Member Functions
AbstractRootFinder (const UnivariatePolynomial< Number > &_polynomial, const Interval< Number > &_interval=Interval< Number >(), bool tryTrivialSolver=true)
Constructor of an AbstractRootFinder.
virtual ~AbstractRootFinder () noexcept=default
const UnivariatePolynomial< Number > & getPolynomial () const noexcept
Returns the polynomial that is currently processed.
const UnivariatePolynomial< Number > & getOriginalPolynomial () const noexcept
Returns the polynomial that was given to the RootFinder.
const auto & getInterval () const noexcept
const std::vector< RealAlgebraicNumber< Number > > & getAllRoots ()
Convenience method to obtain all roots at once in a sorted order.
Protected Member Functions
void addRoot (const RealAlgebraicNumber< Number > &root, bool reducePolynomial=true)
Adds a new root to the internal root list.
void addRoot (const Interval< Number > &interval)
Adds a new root to the internal root list from an interval.
uint solveTrivialMaxDegree () const
Informational method for subclasses specifying the maximum degree of the polynomial that solveTrivial() can handle.
bool solveTrivial ()
Find roots for polynomials of degree at most two and adds them to roots.
virtual void findRoots ()=0
Find all roots of the polynomial.
bool isFinished () const
Indicates if the root finding process has finished.
void setFinished ()
Set status to finished.
Private Attributes
UnivariatePolynomial< Number > mOriginalPolynomial
Original polynomial to solve.
UnivariatePolynomial< Number > mPolynomial
Polynomial to solve.
Interval< Number > mInterval
Interval to be searched.
std::vector< RealAlgebraicNumber< Number > > mRoots
Roots that have been found.
bool mFinished
Flag that indicates if the search has finished.
Detailed Description
template<typename Number>
class carl::rootfinder::AbstractRootFinder< Number >
Base class for a root finding algorithm for a single univariate polynomial.
This class provides some generic routines and an interface for finding the real roots of a univariate polynomial. Whenever a root is found exactly, the polynomial is reduced, that is the linear factor (x - root) is removed from the polynomial.
The basic usage works like this:
Create RootFinder with a polynomial and an optional interval
The RootFinder immediately performs some basic checks:
If 0 is a root, it is added to the set of roots and the polynomial is reduced accordingly
If the degree of the polynomial is at most two, the roots are obtained using a closed formula.
Call getAllRoots() to obtain all real roots.
Definition at line 37 of file AbstractRootFinder.h.
Constructor & Destructor Documentation
AbstractRootFinder()
template<typename Number > carl::rootfinder::AbstractRootFinder< Number >::AbstractRootFinder (const UnivariatePolynomial< Number > & _polynomial, const Interval< Number > & _interval = Interval< Number >(), bool tryTrivialSolver = true) explicit
Constructor of an AbstractRootFinder.
This constructor already does some preprocessing on the given polynomial. At first, the polynomial is tested for a root at zero. If there is such a root, it is added to the root list and removed from the polynomial. If tryTrivialSolver is true, it will then try to solve the polynomial directly using solveTrivial(). If the interval is unbounded (in either direction), the cauchyBound() method is used to the polynomial to construct a bounded interval.
Parameters
polynomial Polynomial to solve.
interval Interval bounding the range of the roots we are looking for.
tryTrivialSolver Flag indicating if the trivialSolve() method should be used.
~AbstractRootFinder()
template<typename Number > virtual carl::rootfinder::AbstractRootFinder< Number >::~AbstractRootFinder () virtual default noexcept
Member Function Documentation
addRoot() [1/2]
template<typename Number > void carl::rootfinder::AbstractRootFinder< Number >::addRoot (const RealAlgebraicNumber< Number > & root, bool reducePolynomial = true) protected
Adds a new root to the internal root list.
If the root is in numeric representation, it will eliminate the root from the polynomial unless reducePolynomial is false.
Parameters
root Pointer to new root.
reducePolynomial Indicates if the polynomial should be reduced.
Referenced by carl::rootfinder::IncrementalRootFinder< Number, Comparator >::addRoot().
addRoot() [2/2]
template<typename Number > void carl::rootfinder::AbstractRootFinder< Number >::addRoot (const Interval< Number > & interval) protected
Adds a new root to the internal root list from an interval.
Parameters
interval Isolating interval.
findRoots()
template<typename Number > virtual void carl::rootfinder::AbstractRootFinder< Number >::findRoots () protected pure virtual
Find all roots of the polynomial.
This method must be implemented by each subclass. All subclasses can safely assume the following about the given polynomial:
It has no root at zero.
It has degree at least three.
Implemented in carl::rootfinder::IncrementalRootFinder< Number, Comparator >.
getAllRoots()
template<typename Number > const std::vector<RealAlgebraicNumber<Number> >& carl::rootfinder::AbstractRootFinder< Number >::getAllRoots ()
Convenience method to obtain all roots at once in a sorted order.
Additional calls will not recompute all roots but only return the cached result.
Returns
List of roots.
getInterval()
template<typename Number > const auto& carl::rootfinder::AbstractRootFinder< Number >::getInterval () const inline noexcept
Definition at line 102 of file AbstractRootFinder.h.
getOriginalPolynomial()
template<typename Number > const UnivariatePolynomial<Number>& carl::rootfinder::AbstractRootFinder< Number >::getOriginalPolynomial () const inline noexcept
Returns the polynomial that was given to the RootFinder.
Returns
Polynomial given to the RootFinder.
Definition at line 98 of file AbstractRootFinder.h.
getPolynomial()
template<typename Number > const UnivariatePolynomial<Number>& carl::rootfinder::AbstractRootFinder< Number >::getPolynomial () const inline noexcept
Returns the polynomial that is currently processed.
This might not be the polynomial that was given to the RootFinder as linear factors are removed from the polynomial if an exact root is found. However, it is a factor of the original polynomial.
Returns
Current polynomial.
Definition at line 91 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::IncrementalRootFinder< Number, Comparator >::getPolynomial().
isFinished()
template<typename Number > bool carl::rootfinder::AbstractRootFinder< Number >::isFinished () const inline protected
Indicates if the root finding process has finished.
Definition at line 156 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::AbstractRootFinder< Number >::setFinished().
setFinished()
template<typename Number > void carl::rootfinder::AbstractRootFinder< Number >::setFinished () inline protected
Set status to finished.
Sorts roots that have been found.
Definition at line 164 of file AbstractRootFinder.h.
solveTrivial()
template<typename Number > bool carl::rootfinder::AbstractRootFinder< Number >::solveTrivial () protected
Find roots for polynomials of degree at most two and adds them to roots.
The resulting roots will always be in sorted order. Assumes that the polynomial is not zero.
Returns
true, if polynomial has degree at most two.
solveTrivialMaxDegree()
template<typename Number > uint carl::rootfinder::AbstractRootFinder< Number >::solveTrivialMaxDegree () const inline protected
Informational method for subclasses specifying the maximum degree of the polynomial that solveTrivial() can handle.
Returns
Maximum degree that solveTrivial() can handle.
Definition at line 132 of file AbstractRootFinder.h.
Field Documentation
mFinished
template<typename Number > bool carl::rootfinder::AbstractRootFinder< Number >::mFinished private
Flag that indicates if the search has finished.
Definition at line 61 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::AbstractRootFinder< Number >::isFinished(), and carl::rootfinder::AbstractRootFinder< Number >::setFinished().
mInterval
template<typename Number > Interval<Number> carl::rootfinder::AbstractRootFinder< Number >::mInterval private
Interval to be searched.
Definition at line 52 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::AbstractRootFinder< Number >::getInterval().
mOriginalPolynomial
template<typename Number > UnivariatePolynomial<Number> carl::rootfinder::AbstractRootFinder< Number >::mOriginalPolynomial private
Original polynomial to solve.
Stored for informational purposes.
Definition at line 43 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::AbstractRootFinder< Number >::getOriginalPolynomial().
mPolynomial
template<typename Number > UnivariatePolynomial<Number> carl::rootfinder::AbstractRootFinder< Number >::mPolynomial private
Polynomial to solve.
This polynomial may be changed during the solving process.
Definition at line 48 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::AbstractRootFinder< Number >::getPolynomial().
mRoots
template<typename Number > std::vector<RealAlgebraicNumber<Number> > carl::rootfinder::AbstractRootFinder< Number >::mRoots private
Roots that have been found.
If the instantiated root finder works in an incremental manner, this list may not contain all roots, if it is called before the root finder has indicated that it is finished.
Definition at line 57 of file AbstractRootFinder.h.
Referenced by carl::rootfinder::AbstractRootFinder< Number >::setFinished().
The documentation for this class was generated from the following file:
carl/core/rootfinder/AbstractRootFinder.h