carl: carl::OldGinacConverter< Poly > Class Template Reference
carl::OldGinacConverter< Poly > Class Template Reference
#include <OldGinacConverter.h>
Public Member Functions
~OldGinacConverter ()=default
void setPolynomialCache (const std::shared_ptr< typename Poly::CACHE > &_cache)
template<typename P = Poly, EnableIf< needs_cache< P >> = dummy>
P createPolynomial (typename P::PolyType &&_poly)
template<typename P = Poly, EnableIf< needs_cache< P >> = dummy>
P createPolynomial (Variable::Arg _var)
template<typename P = Poly, EnableIf< needs_cache< P >> = dummy>
P createPolynomial (const typename P::PolyType &_poly)
template<typename P = Poly, DisableIf< needs_cache< P >> = dummy>
P createPolynomial (Variable::Arg _var)
bool similar (const GiNaC::ex &a, const GiNaC::ex &b)
GiNaC::ex convertToGinac (const typename Poly::PolyType &poly, const std::map< carl::Variable, GiNaC::ex > &vars)
template<typename P = Poly, EnableIf< is_factorized< P >> = dummy>
GiNaC::ex convertToGinac (const P &poly, const std::map< carl::Variable, GiNaC::ex > &vars)
Poly convertToCarl (const GiNaC::ex &_toConvert, const std::map< GiNaC::ex, carl::Variable, GiNaC::ex_is_less > &vars)
void gatherVariables (const Poly &poly, std::map< Variable, GiNaC::ex > &carlToGinacVarMap, std::map< GiNaC::ex, Variable, GiNaC::ex_is_less > &ginacToCarlVarMap)
Poly ginacGcd (const Poly &polyA, const Poly &polyB)
bool ginacDivide (const Poly &polyA, const Poly &polyB, Poly &result)
Factors< Poly > ginacFactorization (const Poly &poly)
bool checkConversion (const Poly &polyA)
Static Public Member Functions
static OldGinacConverter< Poly > & getInstance ()
Returns the single instance of this class by reference.
Private Attributes
friend Singleton< OldGinacConverter >
std::recursive_mutex mMutex
std::shared_ptr< typename Poly::CACHE > mpPolynomialCache
Detailed Description
template<typename Poly>
class carl::OldGinacConverter< Poly >
Definition at line 27 of file OldGinacConverter.h.
Constructor & Destructor Documentation
~OldGinacConverter()
template<typename Poly > carl::OldGinacConverter< Poly >::~OldGinacConverter () default
Member Function Documentation
checkConversion()
template<typename Poly > bool carl::OldGinacConverter< Poly >::checkConversion (const Poly & polyA)
convertToCarl()
template<typename Poly > Poly carl::OldGinacConverter< Poly >::convertToCarl (const GiNaC::ex & _toConvert, const std::map< GiNaC::ex, carl::Variable, GiNaC::ex_is_less > & vars)
convertToGinac() [1/2]
template<typename Poly > GiNaC::ex carl::OldGinacConverter< Poly >::convertToGinac (const typename Poly::PolyType & poly, const std::map< carl::Variable, GiNaC::ex > & vars) inline
Definition at line 67 of file OldGinacConverter.h.
Referenced by carl::OldGinacConverter< Poly >::convertToGinac().
convertToGinac() [2/2]
template<typename Poly > template<typename P = Poly, EnableIf< is_factorized< P >> = dummy> GiNaC::ex carl::OldGinacConverter< Poly >::convertToGinac (const P & poly, const std::map< carl::Variable, GiNaC::ex > & vars) inline
Definition at line 88 of file OldGinacConverter.h.
createPolynomial() [1/4]
template<typename Poly > template<typename P = Poly, EnableIf< needs_cache< P >> = dummy> P carl::OldGinacConverter< Poly >::createPolynomial (typename P::PolyType && _poly) inline
Definition at line 42 of file OldGinacConverter.h.
Referenced by carl::OldGinacConverter< Poly >::createPolynomial().
createPolynomial() [2/4]
template<typename Poly > template<typename P = Poly, EnableIf< needs_cache< P >> = dummy> P carl::OldGinacConverter< Poly >::createPolynomial (Variable::Arg _var) inline
Definition at line 48 of file OldGinacConverter.h.
createPolynomial() [3/4]
template<typename Poly > template<typename P = Poly, EnableIf< needs_cache< P >> = dummy> P carl::OldGinacConverter< Poly >::createPolynomial (const typename P::PolyType & _poly) inline
Definition at line 54 of file OldGinacConverter.h.
createPolynomial() [4/4]
template<typename Poly > template<typename P = Poly, DisableIf< needs_cache< P >> = dummy> P carl::OldGinacConverter< Poly >::createPolynomial (Variable::Arg _var) inline
Definition at line 60 of file OldGinacConverter.h.
gatherVariables()
template<typename Poly > void carl::OldGinacConverter< Poly >::gatherVariables (const Poly & poly, std::map< Variable, GiNaC::ex > & carlToGinacVarMap, std::map< GiNaC::ex, Variable, GiNaC::ex_is_less > & ginacToCarlVarMap) inline
Definition at line 107 of file OldGinacConverter.h.
getInstance()
static OldGinacConverter< Poly > & carl::Singleton< OldGinacConverter< Poly > >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::checkConversion(), carl::convertToCarl(), carl::convertToGinac(), carl::gatherVariables(), carl::ginacDivide(), carl::ginacFactorization(), carl::ginacGcd(), carl::setGinacConverterPolynomialCache(), and carl::similar().
ginacDivide()
template<typename Poly > bool carl::OldGinacConverter< Poly >::ginacDivide (const Poly & polyA, const Poly & polyB, Poly & result)
ginacFactorization()
template<typename Poly > Factors<Poly> carl::OldGinacConverter< Poly >::ginacFactorization (const Poly & poly)
ginacGcd()
template<typename Poly > Poly carl::OldGinacConverter< Poly >::ginacGcd (const Poly & polyA, const Poly & polyB)
setPolynomialCache()
template<typename Poly > void carl::OldGinacConverter< Poly >::setPolynomialCache (const std::shared_ptr< typename Poly::CACHE > & _cache) inline
Definition at line 36 of file OldGinacConverter.h.
similar()
template<typename Poly > bool carl::OldGinacConverter< Poly >::similar (const GiNaC::ex & a, const GiNaC::ex & b)
Definition at line 7 of file OldGinacConverter.cpp.
Field Documentation
mMutex
template<typename Poly > std::recursive_mutex carl::OldGinacConverter< Poly >::mMutex private
Definition at line 31 of file OldGinacConverter.h.
Referenced by carl::OldGinacConverter< Poly >::convertToGinac(), and carl::OldGinacConverter< Poly >::gatherVariables().
mpPolynomialCache
template<typename Poly > std::shared_ptr<typename Poly::CACHE> carl::OldGinacConverter< Poly >::mpPolynomialCache private
Definition at line 32 of file OldGinacConverter.h.
Referenced by carl::OldGinacConverter< Poly >::createPolynomial(), and carl::OldGinacConverter< Poly >::setPolynomialCache().
Singleton< OldGinacConverter >
template<typename Poly > friend carl::OldGinacConverter< Poly >::Singleton< OldGinacConverter > private
Definition at line 29 of file OldGinacConverter.h.
The documentation for this class was generated from the following files:
carl/converter/OldGinacConverter.h
carl/converter/OldGinacConverter.cpp