carl: carl::BVTermContent Class Reference
carl::BVTermContent Class Reference
#include <BVTerm.h>
Public Member Functions
BVTermContent ()
BVTermContent (BVTermType _type, BVValue &&_value)
BVTermContent (BVTermType _type, const BVVariable &_variable)
BVTermContent (BVTermType _type, const BVTerm &_operand, const size_t _index=0)
BVTermContent (BVTermType _type, const BVTerm &_first, const BVTerm &_second)
BVTermContent (BVTermType _type, const BVTerm &_operand, const size_t _highest, const size_t _lowest)
std::size_t width () const
BVTermType type () const
bool isInvalid () const
void collectVariables (std::set< BVVariable > &vars) const
std::string toString (const std::string &_init="", bool _oneline=true, bool _infix=false, bool _friendlyNames=true) const
Gives the string representation of this bit vector term.
std::size_t hash () const
bool operator== (const BVTermContent &rhs) const
bool operator< (const BVTermContent &rhs) const
Private Member Functions
template<typename T >
T & getContent ()
template<typename T >
const T & getContent () const
BVVariable & getVariable ()
const BVVariable & getVariable () const
BVValue & getValue ()
const BVValue & getValue () const
BVUnaryContent & getUnary ()
const BVUnaryContent & getUnary () const
BVBinaryContent & getBinary ()
const BVBinaryContent & getBinary () const
BVExtractContent & getExtract ()
const BVExtractContent & getExtract () const
Private Attributes
BVTermType mType = BVTermType::CONSTANT
boost::variant< BVVariable, BVValue, BVUnaryContent, BVBinaryContent, BVExtractContent > mContent = BVValue()
std::size_t mWidth = 0
std::size_t mId = 0
std::size_t mHash
Friends
class BVTermPool
class BVTerm
std::ostream & operator<< (std::ostream &os, const BVTermContent &_term)
The output operator of a term.
Detailed Description
Definition at line 223 of file BVTerm.h.
Constructor & Destructor Documentation
BVTermContent() [1/6]
carl::BVTermContent::BVTermContent () inline
Definition at line 261 of file BVTerm.h.
BVTermContent() [2/6]
carl::BVTermContent::BVTermContent (BVTermType _type, BVValue && _value) inline
Definition at line 266 of file BVTerm.h.
BVTermContent() [3/6]
carl::BVTermContent::BVTermContent (BVTermType _type, const BVVariable & _variable) inline
Definition at line 273 of file BVTerm.h.
BVTermContent() [4/6]
carl::BVTermContent::BVTermContent (BVTermType _type, const BVTerm & _operand, const size_t _index = 0) inline
Definition at line 280 of file BVTerm.h.
BVTermContent() [5/6]
carl::BVTermContent::BVTermContent (BVTermType _type, const BVTerm & _first, const BVTerm & _second) inline
Definition at line 300 of file BVTerm.h.
BVTermContent() [6/6]
carl::BVTermContent::BVTermContent (BVTermType _type, const BVTerm & _operand, const size_t _highest, const size_t _lowest) inline
Definition at line 315 of file BVTerm.h.
Member Function Documentation
collectVariables()
void carl::BVTermContent::collectVariables (std::set< BVVariable > & vars) const inline
Definition at line 335 of file BVTerm.h.
Referenced by carl::BVTerm::collectVariables().
getBinary() [1/2]
BVBinaryContent& carl::BVTermContent::getBinary () inline private
Definition at line 250 of file BVTerm.h.
Referenced by collectVariables(), carl::BVTerm::complexity(), carl::BVTerm::first(), carl::BVTerm::second(), and toString().
getBinary() [2/2]
const BVBinaryContent& carl::BVTermContent::getBinary () const inline private
Definition at line 251 of file BVTerm.h.
getContent() [1/2]
template<typename T > T& carl::BVTermContent::getContent () inline private
Definition at line 234 of file BVTerm.h.
getContent() [2/2]
template<typename T > const T& carl::BVTermContent::getContent () const inline private
Definition at line 239 of file BVTerm.h.
getExtract() [1/2]
BVExtractContent& carl::BVTermContent::getExtract () inline private
Definition at line 252 of file BVTerm.h.
Referenced by collectVariables(), carl::BVTerm::complexity(), carl::BVTerm::highest(), carl::BVTerm::lowest(), carl::BVTerm::operand(), and toString().
getExtract() [2/2]
const BVExtractContent& carl::BVTermContent::getExtract () const inline private
Definition at line 253 of file BVTerm.h.
getUnary() [1/2]
BVUnaryContent& carl::BVTermContent::getUnary () inline private
Definition at line 248 of file BVTerm.h.
Referenced by collectVariables(), carl::BVTerm::complexity(), carl::BVTerm::index(), carl::BVTerm::operand(), and toString().
getUnary() [2/2]
const BVUnaryContent& carl::BVTermContent::getUnary () const inline private
Definition at line 249 of file BVTerm.h.
getValue() [1/2]
BVValue& carl::BVTermContent::getValue () inline private
Definition at line 246 of file BVTerm.h.
Referenced by toString(), and carl::BVTerm::value().
getValue() [2/2]
const BVValue& carl::BVTermContent::getValue () const inline private
Definition at line 247 of file BVTerm.h.
getVariable() [1/2]
BVVariable& carl::BVTermContent::getVariable () inline private
Definition at line 244 of file BVTerm.h.
Referenced by collectVariables(), toString(), and carl::BVTerm::variable().
getVariable() [2/2]
const BVVariable& carl::BVTermContent::getVariable () const inline private
Definition at line 245 of file BVTerm.h.
hash()
std::size_t carl::BVTermContent::hash () const inline
Definition at line 433 of file BVTerm.h.
Referenced by carl::BVTerm::hash(), and std::hash< carl::BVTermContent >::operator()().
isInvalid()
bool carl::BVTermContent::isInvalid () const inline
Definition at line 331 of file BVTerm.h.
Referenced by carl::BVTerm::isInvalid(), and toString().
operator<()
bool carl::BVTermContent::operator< (const BVTermContent & rhs) const inline
Definition at line 442 of file BVTerm.h.
operator==()
bool carl::BVTermContent::operator== (const BVTermContent & rhs) const inline
Definition at line 438 of file BVTerm.h.
toString()
std::string carl::BVTermContent::toString (const std::string & _init = "", bool _oneline = true, bool _infix = false, bool _friendlyNames = true) const inline
Gives the string representation of this bit vector term.
Parameters
_init The initial string of every row of the result.
_oneline A flag indicating whether the term shall be printed on one line.
_infix A flag indicating whether to print the term in infix or prefix notation.
_friendlyNames A flag that indicates whether to print the variables with their internal representation (false) or with their dedicated names.
Returns
The resulting string representation of this term.
Definition at line 366 of file BVTerm.h.
Referenced by carl::BVTerm::toString().
type()
BVTermType carl::BVTermContent::type () const inline
Definition at line 327 of file BVTerm.h.
Referenced by carl::BVTerm::operand(), and carl::BVTerm::type().
width()
std::size_t carl::BVTermContent::width () const inline
Definition at line 323 of file BVTerm.h.
Referenced by carl::BVTerm::width().
Friends And Related Function Documentation
BVTerm
friend class BVTerm friend
Definition at line 226 of file BVTerm.h.
BVTermPool
friend class BVTermPool friend
Definition at line 225 of file BVTerm.h.
operator<<
std::ostream& operator<< (std::ostream & os, const BVTermContent & _term) friend
The output operator of a term.
Parameters
_out The stream to print on.
_term The term to be printed.
Definition at line 452 of file BVTerm.h.
Field Documentation
mContent
boost::variant<BVVariable,BVValue,BVUnaryContent,BVBinaryContent,BVExtractContent> carl::BVTermContent::mContent = BVValue() private
Definition at line 231 of file BVTerm.h.
Referenced by getContent(), operator<(), and operator==().
mHash
std::size_t carl::BVTermContent::mHash private
Definition at line 257 of file BVTerm.h.
Referenced by hash(), operator<(), and operator==().
mId
std::size_t carl::BVTermContent::mId = 0 private
Definition at line 256 of file BVTerm.h.
Referenced by carl::BVTermPool::assignId(), operator<(), and operator==().
mType
BVTermType carl::BVTermContent::mType = BVTermType::CONSTANT private
Definition at line 229 of file BVTerm.h.
Referenced by collectVariables(), isInvalid(), operator<(), operator==(), toString(), and type().
mWidth
std::size_t carl::BVTermContent::mWidth = 0 private
Definition at line 255 of file BVTerm.h.
Referenced by BVTermContent(), carl::BVTerm::complexity(), isInvalid(), operator<(), operator==(), and width().
The documentation for this class was generated from the following file:
carl/formula/bitvector/BVTerm.h