carl: carl::rootfinder::RealRootIsolation< Number > Class Template Reference
carl::rootfinder::RealRootIsolation< Number > Class Template Reference
Compact class to isolate real roots from a univariate polynomial using bisection.
#include <RealRootIsolation.h>
Public Member Functions
RealRootIsolation (const UnivariatePolynomial< Number > &polynomial, const Interval< Number > &interval)
std::vector< RealAlgebraicNumber< Number > > get_roots ()
Compute and sort the roots of mPolynomial within mInterval.
Private Member Functions
const auto & sturm_sequence ()
Return the sturm sequence for mPolynomial, create it if necessary.
void reset_sturm_sequence ()
Reset the sturm sequence, used if the polynomial was modified.
void eliminate_zero_roots ()
Handle zero roots (p(0) == 0)
bool isolate_roots_trivially ()
Directly solve low-degree polynomials.
void add_trivial_root (const Number &n)
void add_trivial_root (const Interval< Number > &i)
void update_root_bounds ()
Use root bounds to shrink mInterval.
void add_root (const Number &n)
Add a root to mRoots and simplify polynomial accordingly (essentially divide by x-n)
void add_root (const Interval< Number > &i)
Add a root to mRoots, based on an isolating interval.
bool check_interval_bounds ()
Check whether the interval bounds are roots.
void bisect_by_approximation (std::deque< Interval< Number >> &queue)
Initialize the bisection queue using approximations.
void isolate_by_bisection ()
Perform bisection.
void compute_roots ()
Do actual root isolation.
Private Attributes
UnivariatePolynomial< Number > mPolynomial
The polynomial.
std::vector< RealAlgebraicNumber< Number > > mRoots
The list of roots.
Interval< Number > mInterval
The bounding interval.
std::optional< std::vector< UnivariatePolynomial< Number > > > mSturmSequence
The sturm sequence for mPolynomial.
Static Private Attributes
static constexpr bool initialize_bisection_by_approximation = true
Initialize bisection intervals using approximations.
static constexpr bool simplify_by_factorization = false
Factorize polynomial and handle factors individually.
Detailed Description
template<typename Number>
class carl::rootfinder::RealRootIsolation< Number >
Compact class to isolate real roots from a univariate polynomial using bisection.
After some rather easy preprocessing (make polynomial square-free, eliminate zero roots, solve low-degree polynomial trivially, use root bounds to shrink the interval) we employ bisection which can optionally be initialized by approximations.
Definition at line 25 of file RealRootIsolation.h.
Constructor & Destructor Documentation
RealRootIsolation()
template<typename Number > carl::rootfinder::RealRootIsolation< Number >::RealRootIsolation (const UnivariatePolynomial< Number > & polynomial, const Interval< Number > & interval) inline
Definition at line 294 of file RealRootIsolation.h.
Member Function Documentation
add_root() [1/2]
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::add_root (const Number & n) inline private
Add a root to mRoots and simplify polynomial accordingly (essentially divide by x-n)
Definition at line 132 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::bisect_by_approximation(), carl::rootfinder::RealRootIsolation< Number >::check_interval_bounds(), and carl::rootfinder::RealRootIsolation< Number >::isolate_by_bisection().
add_root() [2/2]
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::add_root (const Interval< Number > & i) inline private
Add a root to mRoots, based on an isolating interval.
Definition at line 140 of file RealRootIsolation.h.
add_trivial_root() [1/2]
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::add_trivial_root (const Number & n) inline private
Definition at line 113 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::isolate_roots_trivially().
add_trivial_root() [2/2]
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::add_trivial_root (const Interval< Number > & i) inline private
Definition at line 119 of file RealRootIsolation.h.
bisect_by_approximation()
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::bisect_by_approximation (std::deque< Interval< Number >> & queue) inline private
Initialize the bisection queue using approximations.
The main idea is that the eigenvalues of the companion matrix are the root of a polynomial. This is implemented in eigen::root_approximation. We do:
convert coefficients to doubles
call eigen::root_approximation
make approximations smaller, sort them, remove duplicates
convert approximations to rationals
create interval endpoints so that each interval contains a single approximation
initialize queue from these endpoints
Definition at line 176 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::isolate_by_bisection().
check_interval_bounds()
template<typename Number > bool carl::rootfinder::RealRootIsolation< Number >::check_interval_bounds () inline private
Check whether the interval bounds are roots.
Definition at line 146 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::compute_roots().
compute_roots()
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::compute_roots () inline private
Do actual root isolation.
Definition at line 268 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::get_roots().
eliminate_zero_roots()
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::eliminate_zero_roots () inline private
Handle zero roots (p(0) == 0)
Definition at line 53 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::compute_roots().
get_roots()
template<typename Number > std::vector<RealAlgebraicNumber<Number> > carl::rootfinder::RealRootIsolation< Number >::get_roots () inline
Compute and sort the roots of mPolynomial within mInterval.
Definition at line 299 of file RealRootIsolation.h.
Referenced by carl::rootfinder::realRoots().
isolate_by_bisection()
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::isolate_by_bisection () inline private
Perform bisection.
Definition at line 230 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::compute_roots().
isolate_roots_trivially()
template<typename Number > bool carl::rootfinder::RealRootIsolation< Number >::isolate_roots_trivially () inline private
Directly solve low-degree polynomials.
Definition at line 63 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::compute_roots().
reset_sturm_sequence()
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::reset_sturm_sequence () inline private
Reset the sturm sequence, used if the polynomial was modified.
Definition at line 48 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::add_root(), and carl::rootfinder::RealRootIsolation< Number >::get_roots().
sturm_sequence()
template<typename Number > const auto& carl::rootfinder::RealRootIsolation< Number >::sturm_sequence () inline private
Return the sturm sequence for mPolynomial, create it if necessary.
Definition at line 41 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::add_root(), and carl::rootfinder::RealRootIsolation< Number >::add_trivial_root().
update_root_bounds()
template<typename Number > void carl::rootfinder::RealRootIsolation< Number >::update_root_bounds () inline private
Use root bounds to shrink mInterval.
Definition at line 125 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::compute_roots().
Field Documentation
initialize_bisection_by_approximation
template<typename Number > constexpr bool carl::rootfinder::RealRootIsolation< Number >::initialize_bisection_by_approximation = true static private
Initialize bisection intervals using approximations.
Definition at line 27 of file RealRootIsolation.h.
mInterval
template<typename Number > Interval<Number> carl::rootfinder::RealRootIsolation< Number >::mInterval private
The bounding interval.
Definition at line 36 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::get_roots().
mPolynomial
template<typename Number > UnivariatePolynomial<Number> carl::rootfinder::RealRootIsolation< Number >::mPolynomial private
The polynomial.
Definition at line 32 of file RealRootIsolation.h.
mRoots
template<typename Number > std::vector<RealAlgebraicNumber<Number> > carl::rootfinder::RealRootIsolation< Number >::mRoots private
The list of roots.
Definition at line 34 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::get_roots().
mSturmSequence
template<typename Number > std::optional<std::vector<UnivariatePolynomial<Number> > > carl::rootfinder::RealRootIsolation< Number >::mSturmSequence private
The sturm sequence for mPolynomial.
Definition at line 38 of file RealRootIsolation.h.
Referenced by carl::rootfinder::RealRootIsolation< Number >::sturm_sequence().
simplify_by_factorization
template<typename Number > constexpr bool carl::rootfinder::RealRootIsolation< Number >::simplify_by_factorization = false static private
Factorize polynomial and handle factors individually.
Definition at line 29 of file RealRootIsolation.h.
The documentation for this class was generated from the following file:
carl/core/polynomialfunctions/RealRootIsolation.h