carl: carl::PBConstraint< Pol > Class Template Reference
carl::PBConstraint< Pol > Class Template Reference
#include <PBConstraint.h>
Public Member Functions
PBConstraint ()=default
PBConstraint (std::vector< std::pair< Number, Variable >> ls, Relation rel, Number rs)
PBConstraint (std::vector< std::pair< Number, Variable >> &&ls, Relation rel, Number rs)
std::vector< Variable > gatherVariables () const
PBConstraint negate ()
void setLHS (const std::vector< std::pair< Number, Variable >> &l)
void setRelation (Relation r)
void setRHS (Number r)
const std::vector< std::pair< Number, Variable > > & getLHS () const
Relation getRelation () const
Number getRHS () const
bool hasVariable (Variable v) const
const Number & getCoefficient (Variable v) const
void collectVariables (Variables &vars) const
void normalize ()
std::string toString (bool, bool, bool) const
bool isTrue () const
bool isFalse () const
Private Types
using Number = typename UnderlyingNumberType< Pol >::type
Private Attributes
Relation relation = Relation::EQ
Number rhs
std::vector< std::pair< Number, Variable > > lhs
Friends
template<typename Poly >
std::ostream & operator<< (std::ostream &os, const PBConstraint< Poly > &pbc)
Detailed Description
template<typename Pol>
class carl::PBConstraint< Pol >
Definition at line 13 of file PBConstraint.h.
Member Typedef Documentation
Number
template<typename Pol> using carl::PBConstraint< Pol >::Number = typename UnderlyingNumberType<Pol>::type private
Definition at line 14 of file PBConstraint.h.
Constructor & Destructor Documentation
PBConstraint() [1/3]
template<typename Pol> carl::PBConstraint< Pol >::PBConstraint () default
PBConstraint() [2/3]
template<typename Pol> carl::PBConstraint< Pol >::PBConstraint (std::vector< std::pair< Number, Variable >> ls, Relation rel, Number rs) inline
Definition at line 23 of file PBConstraint.h.
PBConstraint() [3/3]
template<typename Pol> carl::PBConstraint< Pol >::PBConstraint (std::vector< std::pair< Number, Variable >> && ls, Relation rel, Number rs) inline
Definition at line 30 of file PBConstraint.h.
Member Function Documentation
collectVariables()
template<typename Pol> void carl::PBConstraint< Pol >::collectVariables (Variables & vars) const inline
Definition at line 80 of file PBConstraint.h.
gatherVariables()
template<typename Pol> std::vector<Variable> carl::PBConstraint< Pol >::gatherVariables () const inline
Definition at line 37 of file PBConstraint.h.
getCoefficient()
template<typename Pol> const Number& carl::PBConstraint< Pol >::getCoefficient (Variable v) const inline
Definition at line 73 of file PBConstraint.h.
getLHS()
template<typename Pol> const std::vector<std::pair<Number, Variable> >& carl::PBConstraint< Pol >::getLHS () const inline
Definition at line 58 of file PBConstraint.h.
Referenced by carl::PBConstraint< Poly >::collectVariables(), std::hash< carl::PBConstraint< Pol > >::operator()(), carl::operator==(), and carl::model::substituteIn().
getRelation()
template<typename Pol> Relation carl::PBConstraint< Pol >::getRelation () const inline
Definition at line 61 of file PBConstraint.h.
Referenced by carl::model::evaluate(), std::hash< carl::PBConstraint< Pol > >::operator()(), carl::operator<(), and carl::operator==().
getRHS()
template<typename Pol> Number carl::PBConstraint< Pol >::getRHS () const inline
Definition at line 64 of file PBConstraint.h.
Referenced by carl::model::evaluate(), std::hash< carl::PBConstraint< Pol > >::operator()(), carl::operator==(), and carl::model::substituteIn().
hasVariable()
template<typename Pol> bool carl::PBConstraint< Pol >::hasVariable (Variable v) const inline
Definition at line 67 of file PBConstraint.h.
isFalse()
template<typename Pol> bool carl::PBConstraint< Pol >::isFalse () const inline
Definition at line 121 of file PBConstraint.h.
isTrue()
template<typename Pol> bool carl::PBConstraint< Pol >::isTrue () const inline
Definition at line 111 of file PBConstraint.h.
negate()
template<typename Pol> PBConstraint carl::PBConstraint< Pol >::negate () inline
Definition at line 44 of file PBConstraint.h.
normalize()
template<typename Pol> void carl::PBConstraint< Pol >::normalize () inline
Definition at line 86 of file PBConstraint.h.
Referenced by carl::PBConstraint< Poly >::PBConstraint().
setLHS()
template<typename Pol> void carl::PBConstraint< Pol >::setLHS (const std::vector< std::pair< Number, Variable >> & l) inline
Definition at line 49 of file PBConstraint.h.
Referenced by carl::model::substituteIn().
setRelation()
template<typename Pol> void carl::PBConstraint< Pol >::setRelation (Relation r) inline
Definition at line 52 of file PBConstraint.h.
setRHS()
template<typename Pol> void carl::PBConstraint< Pol >::setRHS (Number r) inline
Definition at line 55 of file PBConstraint.h.
Referenced by carl::model::substituteIn().
toString()
template<typename Pol> std::string carl::PBConstraint< Pol >::toString (bool , bool , bool) const inline
Definition at line 105 of file PBConstraint.h.
Friends And Related Function Documentation
operator<<
template<typename Pol> template<typename Poly > std::ostream& operator<< (std::ostream & os, const PBConstraint< Poly > & pbc) friend
Field Documentation
lhs
template<typename Pol> std::vector<std::pair<Number,Variable> > carl::PBConstraint< Pol >::lhs private
Definition at line 20 of file PBConstraint.h.
Referenced by carl::PBConstraint< Poly >::gatherVariables(), carl::PBConstraint< Poly >::getCoefficient(), carl::PBConstraint< Poly >::getLHS(), carl::PBConstraint< Poly >::hasVariable(), carl::PBConstraint< Poly >::isFalse(), carl::PBConstraint< Poly >::isTrue(), carl::PBConstraint< Poly >::normalize(), and carl::PBConstraint< Poly >::setLHS().
relation
template<typename Pol> Relation carl::PBConstraint< Pol >::relation = Relation::EQ private
Definition at line 18 of file PBConstraint.h.
Referenced by carl::PBConstraint< Poly >::getRelation(), carl::PBConstraint< Poly >::isFalse(), carl::PBConstraint< Poly >::isTrue(), carl::PBConstraint< Poly >::normalize(), and carl::PBConstraint< Poly >::setRelation().
rhs
template<typename Pol> Number carl::PBConstraint< Pol >::rhs private
Definition at line 19 of file PBConstraint.h.
Referenced by carl::PBConstraint< Poly >::getRHS(), carl::PBConstraint< Poly >::isFalse(), carl::PBConstraint< Poly >::isTrue(), carl::PBConstraint< Poly >::normalize(), and carl::PBConstraint< Poly >::setRHS().
The documentation for this class was generated from the following file:
carl/formula/pseudoboolean/PBConstraint.h