carl: carl::Model< Rational, Poly > Class Template Reference
carl::Model< Rational, Poly > Class Template Reference
Represent a collection of assignments/mappings from variables to values.
#include <Model.h>
Public Types
using key_type = ModelVariable
using mapped_type = ModelValue< Rational, Poly >
using Map = std::map< key_type, mapped_type >
Public Member Functions
const auto & at (const key_type &key) const
auto begin () const
auto end () const
auto empty () const
auto size () const
void clear ()
template<typename P >
auto insert (const P &pair)
template<typename P >
auto insert (typename Map::const_iterator it, const P &pair)
template<typename... Args>
auto emplace (const key_type &key, Args &&...args)
template<typename... Args>
auto emplace_hint (typename Map::const_iterator it, const key_type &key, Args &&...args)
Map::iterator erase (const ModelVariable &variable)
Map::iterator erase (const typename Map::iterator &it)
Map::iterator erase (const typename Map::const_iterator &it)
void clean ()
auto find (const typename Map::key_type &key) const
auto find (const typename Map::key_type &key)
Model ()=default
Model (const std::map< Variable, Rational > &assignment)
template<typename Container >
bool contains (const Container &c) const
template<typename T >
void assign (const typename Map::key_type &key, const T &t)
void update (const Model &model, bool disjoint=true)
const ModelValue< Rational, Poly > & evaluated (const typename Map::key_type &key) const
Return the ModelValue for the given key, evaluated if it's a ModelSubstitution and evaluatable, otherwise return it raw.
void print (std::ostream &os, bool simple=true) const
void printOneline (std::ostream &os, bool simple=false) const
Private Member Functions
void resetCaches () const
Private Attributes
Map mData
std::map< key_type, std::size_t > mUsedInSubstitution
Detailed Description
template<typename Rational, typename Poly>
class carl::Model< Rational, Poly >
Represent a collection of assignments/mappings from variables to values.
We use a ModelVariable to abstract over the different kinds of variables in CARL, and a ModelValue to abstract over the different kinds of values for these variables. Most notably, a value can be a "carl::ModelSubstitution" whose value depends on the values of other variables in the Model. If such other variables are erased from the model, this substitution is evaluated and replaced by the result.
Definition at line 20 of file Model.h.
Member Typedef Documentation
key_type
template<typename Rational, typename Poly> using carl::Model< Rational, Poly >::key_type = ModelVariable
Definition at line 22 of file Model.h.
Map
template<typename Rational, typename Poly> using carl::Model< Rational, Poly >::Map = std::map<key_type,mapped_type>
Definition at line 24 of file Model.h.
mapped_type
template<typename Rational, typename Poly> using carl::Model< Rational, Poly >::mapped_type = ModelValue<Rational,Poly>
Definition at line 23 of file Model.h.
Constructor & Destructor Documentation
Model() [1/2]
template<typename Rational, typename Poly> carl::Model< Rational, Poly >::Model () default
Model() [2/2]
template<typename Rational, typename Poly> carl::Model< Rational, Poly >::Model (const std::map< Variable, Rational > & assignment) inline
Definition at line 123 of file Model.h.
Member Function Documentation
assign()
template<typename Rational, typename Poly> template<typename T > void carl::Model< Rational, Poly >::assign (const typename Map::key_type & key, const T & t) inline
Definition at line 136 of file Model.h.
at()
template<typename Rational, typename Poly> const auto& carl::Model< Rational, Poly >::at (const key_type & key) const inline
Definition at line 39 of file Model.h.
Referenced by carl::Model< Rational, Poly >::evaluated().
begin()
template<typename Rational, typename Poly> auto carl::Model< Rational, Poly >::begin () const inline
Definition at line 44 of file Model.h.
clean()
template<typename Rational, typename Poly> void carl::Model< Rational, Poly >::clean () inline
Definition at line 104 of file Model.h.
clear()
template<typename Rational, typename Poly> void carl::Model< Rational, Poly >::clear () inline
Definition at line 58 of file Model.h.
contains()
template<typename Rational, typename Poly> template<typename Container > bool carl::Model< Rational, Poly >::contains (const Container & c) const inline
Definition at line 129 of file Model.h.
Referenced by carl::model::substituteIn().
emplace()
template<typename Rational, typename Poly> template<typename... Args> auto carl::Model< Rational, Poly >::emplace (const key_type & key, Args &&... args) inline
Definition at line 72 of file Model.h.
emplace_hint()
template<typename Rational, typename Poly> template<typename... Args> auto carl::Model< Rational, Poly >::emplace_hint (typename Map::const_iterator it, const key_type & key, Args &&... args) inline
Definition at line 77 of file Model.h.
empty()
template<typename Rational, typename Poly> auto carl::Model< Rational, Poly >::empty () const inline
Definition at line 51 of file Model.h.
end()
template<typename Rational, typename Poly> auto carl::Model< Rational, Poly >::end () const inline
Definition at line 47 of file Model.h.
Referenced by carl::model::collectRANIR(), carl::model::evaluate(), carl::model::evaluateVarAssign(), carl::model::evaluateVarCompare(), and carl::model::substituteIn().
erase() [1/3]
template<typename Rational, typename Poly> Map::iterator carl::Model< Rational, Poly >::erase (const ModelVariable & variable) inline
Definition at line 81 of file Model.h.
Referenced by carl::Model< Rational, Poly >::erase().
erase() [2/3]
template<typename Rational, typename Poly> Map::iterator carl::Model< Rational, Poly >::erase (const typename Map::iterator & it) inline
Definition at line 85 of file Model.h.
erase() [3/3]
template<typename Rational, typename Poly> Map::iterator carl::Model< Rational, Poly >::erase (const typename Map::const_iterator & it) inline
Definition at line 89 of file Model.h.
evaluated()
template<typename Rational, typename Poly> const ModelValue<Rational,Poly>& carl::Model< Rational, Poly >::evaluated (const typename Map::key_type & key) const inline
Return the ModelValue for the given key, evaluated if it's a ModelSubstitution and evaluatable, otherwise return it raw.
Parameters
key The model must contain an assignment with the given key.
Definition at line 158 of file Model.h.
Referenced by carl::model::collectRANIR(), carl::model::evaluate(), carl::model::evaluateVarAssign(), carl::model::evaluateVarCompare(), carl::Model< Rational, Poly >::print(), carl::Model< Rational, Poly >::printOneline(), and carl::model::substituteIn().
find() [1/2]
template<typename Rational, typename Poly> auto carl::Model< Rational, Poly >::find (const typename Map::key_type & key) const inline
Definition at line 114 of file Model.h.
Referenced by carl::model::collectRANIR(), carl::model::evaluate(), carl::model::evaluateVarAssign(), carl::model::evaluateVarCompare(), and carl::model::substituteIn().
find() [2/2]
template<typename Rational, typename Poly> auto carl::Model< Rational, Poly >::find (const typename Map::key_type & key) inline
Definition at line 117 of file Model.h.
insert() [1/2]
template<typename Rational, typename Poly> template<typename P > auto carl::Model< Rational, Poly >::insert (const P & pair) inline
Definition at line 62 of file Model.h.
insert() [2/2]
template<typename Rational, typename Poly> template<typename P > auto carl::Model< Rational, Poly >::insert (typename Map::const_iterator it, const P & pair) inline
Definition at line 67 of file Model.h.
print()
template<typename Rational, typename Poly> void carl::Model< Rational, Poly >::print (std::ostream & os, bool simple = true) const inline
Definition at line 163 of file Model.h.
printOneline()
template<typename Rational, typename Poly> void carl::Model< Rational, Poly >::printOneline (std::ostream & os, bool simple = false) const inline
Definition at line 187 of file Model.h.
resetCaches()
template<typename Rational, typename Poly> void carl::Model< Rational, Poly >::resetCaches () const inline private
Definition at line 30 of file Model.h.
Referenced by carl::Model< Rational, Poly >::emplace(), carl::Model< Rational, Poly >::emplace_hint(), carl::Model< Rational, Poly >::erase(), and carl::Model< Rational, Poly >::insert().
size()
template<typename Rational, typename Poly> auto carl::Model< Rational, Poly >::size () const inline
Definition at line 54 of file Model.h.
update()
template<typename Rational, typename Poly> void carl::Model< Rational, Poly >::update (const Model< Rational, Poly > & model, bool disjoint = true) inline
Definition at line 141 of file Model.h.
Field Documentation
mData
template<typename Rational, typename Poly> Map carl::Model< Rational, Poly >::mData private
Definition at line 25 of file Model.h.
Referenced by carl::Model< Rational, Poly >::assign(), carl::Model< Rational, Poly >::at(), carl::Model< Rational, Poly >::begin(), carl::Model< Rational, Poly >::clean(), carl::Model< Rational, Poly >::clear(), carl::Model< Rational, Poly >::contains(), carl::Model< Rational, Poly >::emplace(), carl::Model< Rational, Poly >::emplace_hint(), carl::Model< Rational, Poly >::empty(), carl::Model< Rational, Poly >::end(), carl::Model< Rational, Poly >::erase(), carl::Model< Rational, Poly >::find(), carl::Model< Rational, Poly >::insert(), carl::Model< Rational, Poly >::Model(), carl::Model< Rational, Poly >::print(), carl::Model< Rational, Poly >::printOneline(), carl::Model< Rational, Poly >::resetCaches(), carl::Model< Rational, Poly >::size(), and carl::Model< Rational, Poly >::update().
mUsedInSubstitution
template<typename Rational, typename Poly> std::map<key_type, std::size_t> carl::Model< Rational, Poly >::mUsedInSubstitution private
Definition at line 29 of file Model.h.
The documentation for this class was generated from the following file:
carl/formula/model/Model.h