carl: carl::RealAlgebraicNumber< Number > Class Template Reference
carl::RealAlgebraicNumber< Number > Class Template Reference
#include <RealAlgebraicNumber.h>
Public Member Functions
RealAlgebraicNumber ()=default
RealAlgebraicNumber (const Number &n, bool isRoot=true)
RealAlgebraicNumber (Variable var, bool isRoot=true)
RealAlgebraicNumber (const Polynomial &p, const Interval< Number > &i, bool isRoot=true)
RealAlgebraicNumber (const Polynomial &p, const Interval< Number > &i, const std::list< UnivariatePolynomial< Number >> &sturmSequence, bool isRoot=true)
RealAlgebraicNumber (const ThomEncoding< Number > &te, bool isRoot=true)
RealAlgebraicNumber (const RealAlgebraicNumber &ran)=default
RealAlgebraicNumber (RealAlgebraicNumber &&ran)=default
RealAlgebraicNumber & operator= (const RealAlgebraicNumber &n)=default
RealAlgebraicNumber & operator= (RealAlgebraicNumber &&n)=default
std::size_t size () const
Return the size of this representation in memory in number of bits.
bool isRoot () const
Check if this number stems from an outside root computation.
void setIsRoot (bool isRoot) noexcept
Set the flag marking whether the number stems from an outside root computation.
bool isZero () const
bool isNumeric () const
Check if the underlying representation is an explicit number.
bool isInterval () const
Check if the underlying representation is an implict number (encoded by a polynomial and an interval).
bool isThom () const noexcept
Check if the underlying representation is an implicit number that uses the Thom encoding.
const ThomEncoding< Number > & getThomEncoding () const
bool isIntegral () const
Number integerBelow () const
Number branchingPoint () const
const Number & value () const noexcept
std::size_t getRefinementCount () const
const Interval< Number > & getInterval () const
const Number & lower () const
const Number & upper () const
const Polynomial & getIRPolynomial () const
const auto & getIRSturmSequence () const
RealAlgebraicNumber changeVariable (Variable v) const
Sign sgn () const
Sign sgn (const Polynomial &p) const
bool isRootOf (const UnivariatePolynomial< Number > &p) const
bool containedIn (const Interval< Number > &i) const
Check if this (possibly implicitly represented) number lies within the bounds of interval 'i'.
bool refineAvoiding (const Number &n) const
void refineToIntegrality () const
Refines until the number is either numeric or the interval does not contain any integer.
void refine () const
void simplifyByPolynomial (Variable var, const MultivariatePolynomial< Number > &poly) const
RealAlgebraicNumber< Number > abs () const
bool equal (const RealAlgebraicNumber< Number > &n) const
bool less (const RealAlgebraicNumber< Number > &n) const
std::pair< bool, bool > checkOrder (const RealAlgebraicNumber< Number > &n) const
Private Types
using IntervalContent = ran::IntervalContent< Number >
using Polynomial = typename IntervalContent::Polynomial
Private Member Functions
void checkForSimplification () const
void switchToNR (const Number &n) const
bool lessWhileUnequal (const RealAlgebraicNumber< Number > &n) const
Private Attributes
Number mValue = carl::constant_zero<Number>::get()
bool mIsRoot = true
std::shared_ptr< IntervalContent > mIR
std::shared_ptr< ThomEncoding< Number > > mTE
Friends
template<typename Num >
RealAlgebraicNumber< Num > sampleBelow (const RealAlgebraicNumber< Num > &)
template<typename Num >
RealAlgebraicNumber< Num > sampleBetween (const RealAlgebraicNumber< Num > &, const RealAlgebraicNumber< Num > &, RANSampleHeuristic heuristic)
template<typename Num >
RealAlgebraicNumber< Num > sampleAbove (const RealAlgebraicNumber< Num > &)
Detailed Description
template<typename Number>
class carl::RealAlgebraicNumber< Number >
Definition at line 47 of file RealAlgebraicNumber.h.
Member Typedef Documentation
IntervalContent
template<typename Number> using carl::RealAlgebraicNumber< Number >::IntervalContent = ran::IntervalContent<Number> private
Definition at line 56 of file RealAlgebraicNumber.h.
Polynomial
template<typename Number> using carl::RealAlgebraicNumber< Number >::Polynomial = typename IntervalContent::Polynomial private
Definition at line 57 of file RealAlgebraicNumber.h.
Constructor & Destructor Documentation
RealAlgebraicNumber() [1/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber () default
RealAlgebraicNumber() [2/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (const Number & n, bool isRoot = true) inline explicit
Definition at line 85 of file RealAlgebraicNumber.h.
RealAlgebraicNumber() [3/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (Variable var, bool isRoot = true) inline explicit
Definition at line 89 of file RealAlgebraicNumber.h.
RealAlgebraicNumber() [4/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (const Polynomial & p, const Interval< Number > & i, bool isRoot = true) inline explicit
Definition at line 93 of file RealAlgebraicNumber.h.
RealAlgebraicNumber() [5/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (const Polynomial & p, const Interval< Number > & i, const std::list< UnivariatePolynomial< Number >> & sturmSequence, bool isRoot = true) inline explicit
Definition at line 109 of file RealAlgebraicNumber.h.
RealAlgebraicNumber() [6/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (const ThomEncoding< Number > & te, bool isRoot = true) inline explicit
Definition at line 126 of file RealAlgebraicNumber.h.
RealAlgebraicNumber() [7/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (const RealAlgebraicNumber< Number > & ran) default
RealAlgebraicNumber() [8/8]
template<typename Number> carl::RealAlgebraicNumber< Number >::RealAlgebraicNumber (RealAlgebraicNumber< Number > && ran) default
Member Function Documentation
abs()
template<typename Number> RealAlgebraicNumber<Number> carl::RealAlgebraicNumber< Number >::abs () const inline
Definition at line 347 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::abs().
branchingPoint()
template<typename Number> Number carl::RealAlgebraicNumber< Number >::branchingPoint () const inline
Definition at line 210 of file RealAlgebraicNumber.h.
changeVariable()
template<typename Number> RealAlgebraicNumber carl::RealAlgebraicNumber< Number >::changeVariable (Variable v) const inline
Definition at line 247 of file RealAlgebraicNumber.h.
checkForSimplification()
template<typename Number> void carl::RealAlgebraicNumber< Number >::checkForSimplification () const inline private
Definition at line 68 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::isInterval(), carl::RealAlgebraicNumber< carl::Number >::isNumeric(), carl::RealAlgebraicNumber< carl::Number >::refine(), carl::RealAlgebraicNumber< carl::Number >::refineAvoiding(), and carl::RealAlgebraicNumber< carl::Number >::refineToIntegrality().
checkOrder()
template<typename Number> std::pair<bool,bool> carl::RealAlgebraicNumber< Number >::checkOrder (const RealAlgebraicNumber< Number > & n) const
containedIn()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::containedIn (const Interval< Number > & i) const inline
Check if this (possibly implicitly represented) number lies within the bounds of interval 'i'.
Definition at line 288 of file RealAlgebraicNumber.h.
equal()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::equal (const RealAlgebraicNumber< Number > & n) const
Referenced by carl::operator==().
getInterval()
template<typename Number> const Interval<Number>& carl::RealAlgebraicNumber< Number >::getInterval () const inline
Definition at line 226 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::lower(), and carl::RealAlgebraicNumber< carl::Number >::upper().
getIRPolynomial()
template<typename Number> const Polynomial& carl::RealAlgebraicNumber< Number >::getIRPolynomial () const inline
Definition at line 236 of file RealAlgebraicNumber.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getSubstitution(), and carl::RealAlgebraicNumber< carl::Number >::simplifyByPolynomial().
getIRSturmSequence()
template<typename Number> const auto& carl::RealAlgebraicNumber< Number >::getIRSturmSequence () const inline
Definition at line 241 of file RealAlgebraicNumber.h.
getRefinementCount()
template<typename Number> std::size_t carl::RealAlgebraicNumber< Number >::getRefinementCount () const inline
Definition at line 221 of file RealAlgebraicNumber.h.
getThomEncoding()
template<typename Number> const ThomEncoding<Number>& carl::RealAlgebraicNumber< Number >::getThomEncoding () const inline
Definition at line 190 of file RealAlgebraicNumber.h.
integerBelow()
template<typename Number> Number carl::RealAlgebraicNumber< Number >::integerBelow () const inline
Definition at line 203 of file RealAlgebraicNumber.h.
Referenced by std::hash< carl::RealAlgebraicNumber< Number > >::operator()().
isIntegral()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isIntegral () const inline
Definition at line 196 of file RealAlgebraicNumber.h.
Referenced by carl::isInteger().
isInterval()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isInterval () const inline
Check if the underlying representation is an implict number (encoded by a polynomial and an interval).
Definition at line 178 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::abs(), carl::RealAlgebraicNumber< carl::Number >::branchingPoint(), carl::RealAlgebraicNumber< carl::Number >::changeVariable(), carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumber< carl::Number >::getInterval(), carl::RealAlgebraicNumber< carl::Number >::getIRPolynomial(), carl::RealAlgebraicNumber< carl::Number >::getIRSturmSequence(), carl::RealAlgebraicNumber< carl::Number >::getRefinementCount(), carl::RealAlgebraicNumber< carl::Number >::integerBelow(), carl::RealAlgebraicNumber< carl::Number >::isIntegral(), carl::RealAlgebraicNumber< carl::Number >::isRootOf(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::RealAlgebraicNumber< carl::Number >::refine(), carl::RealAlgebraicNumber< carl::Number >::refineToIntegrality(), carl::sampleAbove(), carl::sampleBelow(), carl::RealAlgebraicNumber< carl::Number >::sgn(), and carl::RealAlgebraicNumber< carl::Number >::size().
isNumeric()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isNumeric () const inline
Check if the underlying representation is an explicit number.
Definition at line 170 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::abs(), carl::RealAlgebraicNumber< carl::Number >::branchingPoint(), carl::ceil_fast(), carl::RealAlgebraicNumber< carl::Number >::changeVariable(), carl::cad::SampleSet< Number >::SampleComparator::compareInt(), carl::cad::SampleSet< Number >::SampleComparator::compareRat(), carl::cad::SampleSet< Number >::SampleComparator::compareSize(), carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::floor_fast(), carl::RealAlgebraicNumber< carl::Number >::getIRPolynomial(), carl::RealAlgebraicNumber< carl::Number >::getIRSturmSequence(), carl::RealAlgebraicNumber< carl::Number >::getRefinementCount(), carl::LazardEvaluation< Rational, Poly >::getSubstitution(), carl::RealAlgebraicNumber< carl::Number >::integerBelow(), carl::RealAlgebraicNumber< carl::Number >::isIntegral(), carl::RealAlgebraicNumber< carl::Number >::isRootOf(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::RealAlgebraicNumber< carl::Number >::refineAvoiding(), carl::sampleAbove(), carl::sampleBelow(), carl::sampleBetween(), carl::RealAlgebraicNumber< carl::Number >::sgn(), carl::RealAlgebraicNumber< carl::Number >::size(), carl::model::substituteIn(), and carl::RealAlgebraicNumber< carl::Number >::value().
isRoot()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isRoot () const inline
Check if this number stems from an outside root computation.
Definition at line 149 of file RealAlgebraicNumber.h.
Referenced by carl::cad::SampleSet< Number >::SampleComparator::compareRoot(), std::hash< carl::RealAlgebraicNumber< Number > >::operator()(), and carl::RealAlgebraicNumber< carl::Number >::setIsRoot().
isRootOf()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isRootOf (const UnivariatePolynomial< Number > & p) const inline
Definition at line 277 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::simplifyByPolynomial().
isThom()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isThom () const inline noexcept
Check if the underlying representation is an implicit number that uses the Thom encoding.
Definition at line 187 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumber< carl::Number >::getRefinementCount(), carl::RealAlgebraicNumber< carl::Number >::getThomEncoding(), carl::RealAlgebraicNumber< carl::Number >::isRootOf(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::sampleAbove(), carl::sampleBelow(), carl::sampleBetween(), and carl::RealAlgebraicNumber< carl::Number >::sgn().
isZero()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isZero () const inline
Definition at line 160 of file RealAlgebraicNumber.h.
Referenced by carl::isZero().
less()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::less (const RealAlgebraicNumber< Number > & n) const
Referenced by carl::operator<().
lessWhileUnequal()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::lessWhileUnequal (const RealAlgebraicNumber< Number > & n) const private
lower()
template<typename Number> const Number& carl::RealAlgebraicNumber< Number >::lower () const inline
Definition at line 230 of file RealAlgebraicNumber.h.
Referenced by carl::floor_fast(), carl::sampleBelow(), and carl::sampleBetween().
operator=() [1/2]
template<typename Number> RealAlgebraicNumber& carl::RealAlgebraicNumber< Number >::operator= (const RealAlgebraicNumber< Number > & n) default
operator=() [2/2]
template<typename Number> RealAlgebraicNumber& carl::RealAlgebraicNumber< Number >::operator= (RealAlgebraicNumber< Number > && n) default
refine()
template<typename Number> void carl::RealAlgebraicNumber< Number >::refine () const inline
Definition at line 325 of file RealAlgebraicNumber.h.
Referenced by carl::sampleBetween().
refineAvoiding()
template<typename Number> bool carl::RealAlgebraicNumber< Number >::refineAvoiding (const Number & n) const inline
Definition at line 314 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), and carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber().
refineToIntegrality()
template<typename Number> void carl::RealAlgebraicNumber< Number >::refineToIntegrality () const inline
Refines until the number is either numeric or the interval does not contain any integer.
Definition at line 321 of file RealAlgebraicNumber.h.
Referenced by carl::ceil(), carl::floor(), carl::RealAlgebraicNumber< carl::Number >::integerBelow(), carl::RealAlgebraicNumber< carl::Number >::isIntegral(), and carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber().
setIsRoot()
template<typename Number> void carl::RealAlgebraicNumber< Number >::setIsRoot (bool isRoot) inline noexcept
Set the flag marking whether the number stems from an outside root computation.
Definition at line 156 of file RealAlgebraicNumber.h.
sgn() [1/2]
template<typename Number> Sign carl::RealAlgebraicNumber< Number >::sgn () const inline
Definition at line 253 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::isRootOf().
sgn() [2/2]
template<typename Number> Sign carl::RealAlgebraicNumber< Number >::sgn (const Polynomial & p) const inline
Definition at line 266 of file RealAlgebraicNumber.h.
simplifyByPolynomial()
template<typename Number> void carl::RealAlgebraicNumber< Number >::simplifyByPolynomial (Variable var, const MultivariatePolynomial< Number > & poly) const inline
Definition at line 330 of file RealAlgebraicNumber.h.
size()
template<typename Number> std::size_t carl::RealAlgebraicNumber< Number >::size () const inline
Return the size of this representation in memory in number of bits.
Definition at line 140 of file RealAlgebraicNumber.h.
switchToNR()
template<typename Number> void carl::RealAlgebraicNumber< Number >::switchToNR (const Number & n) const inline private
Definition at line 75 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::checkForSimplification(), and carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber().
upper()
template<typename Number> const Number& carl::RealAlgebraicNumber< Number >::upper () const inline
Definition at line 233 of file RealAlgebraicNumber.h.
Referenced by carl::ceil_fast(), carl::sampleAbove(), and carl::sampleBetween().
value()
template<typename Number> const Number& carl::RealAlgebraicNumber< Number >::value () const inline noexcept
Definition at line 216 of file RealAlgebraicNumber.h.
Referenced by carl::ceil_fast(), carl::cad::SampleSet< Number >::SampleComparator::compareInt(), carl::cad::SampleSet< Number >::SampleComparator::compareSize(), carl::floor_fast(), carl::LazardEvaluation< Rational, Poly >::getSubstitution(), carl::RealAlgebraicNumber< carl::Number >::isRootOf(), carl::sampleAbove(), carl::sampleBelow(), carl::sampleBetween(), and carl::model::substituteIn().
Friends And Related Function Documentation
sampleAbove
template<typename Number> template<typename Num > RealAlgebraicNumber<Num> sampleAbove (const RealAlgebraicNumber< Num > &) friend
sampleBelow
template<typename Number> template<typename Num > RealAlgebraicNumber<Num> sampleBelow (const RealAlgebraicNumber< Num > &) friend
sampleBetween
template<typename Number> template<typename Num > RealAlgebraicNumber<Num> sampleBetween (const RealAlgebraicNumber< Num > & , const RealAlgebraicNumber< Num > & , RANSampleHeuristic heuristic) friend
Field Documentation
mIR
template<typename Number> std::shared_ptr<IntervalContent> carl::RealAlgebraicNumber< Number >::mIR mutable private
Definition at line 64 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::abs(), carl::RealAlgebraicNumber< carl::Number >::branchingPoint(), carl::RealAlgebraicNumber< carl::Number >::changeVariable(), carl::RealAlgebraicNumber< carl::Number >::checkForSimplification(), carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumber< carl::Number >::getInterval(), carl::RealAlgebraicNumber< carl::Number >::getIRPolynomial(), carl::RealAlgebraicNumber< carl::Number >::getIRSturmSequence(), carl::RealAlgebraicNumber< carl::Number >::getRefinementCount(), carl::RealAlgebraicNumber< carl::Number >::integerBelow(), carl::RealAlgebraicNumber< carl::Number >::isIntegral(), carl::RealAlgebraicNumber< carl::Number >::isInterval(), carl::RealAlgebraicNumber< carl::Number >::isNumeric(), carl::RealAlgebraicNumber< carl::Number >::isRootOf(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber(), carl::RealAlgebraicNumber< carl::Number >::refine(), carl::RealAlgebraicNumber< carl::Number >::refineAvoiding(), carl::RealAlgebraicNumber< carl::Number >::refineToIntegrality(), carl::RealAlgebraicNumber< carl::Number >::sgn(), carl::RealAlgebraicNumber< carl::Number >::simplifyByPolynomial(), carl::RealAlgebraicNumber< carl::Number >::size(), and carl::RealAlgebraicNumber< carl::Number >::switchToNR().
mIsRoot
template<typename Number> bool carl::RealAlgebraicNumber< Number >::mIsRoot = true private
Definition at line 62 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::abs(), carl::RealAlgebraicNumber< carl::Number >::changeVariable(), carl::RealAlgebraicNumber< carl::Number >::isRoot(), and carl::RealAlgebraicNumber< carl::Number >::setIsRoot().
mTE
template<typename Number> std::shared_ptr<ThomEncoding<Number> > carl::RealAlgebraicNumber< Number >::mTE private
Definition at line 66 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumber< carl::Number >::getThomEncoding(), carl::RealAlgebraicNumber< carl::Number >::isNumeric(), carl::RealAlgebraicNumber< carl::Number >::isThom(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::sampleAbove(), carl::sampleBelow(), carl::sampleBetween(), and carl::RealAlgebraicNumber< carl::Number >::sgn().
mValue
template<typename Number> Number carl::RealAlgebraicNumber< Number >::mValue = carl::constant_zero<Number>::get() mutable private
Definition at line 59 of file RealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::abs(), carl::RealAlgebraicNumber< carl::Number >::branchingPoint(), carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumber< carl::Number >::integerBelow(), carl::RealAlgebraicNumber< carl::Number >::isIntegral(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::RealAlgebraicNumber< carl::Number >::sgn(), carl::RealAlgebraicNumber< carl::Number >::size(), carl::RealAlgebraicNumber< carl::Number >::switchToNR(), and carl::RealAlgebraicNumber< carl::Number >::value().
The documentation for this class was generated from the following file:
carl/formula/model/ran/RealAlgebraicNumber.h