carl: carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy > Class Template Reference
carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy > Class Template Reference
Algorithms » Groebner Bases
A general class for Groebner Basis calculation.
#include <GBProcedure.h>
Public Member Functions
GBProcedure ()
GBProcedure (const GBProcedure &old)
virtual ~GBProcedure ()=default
GBProcedure & operator= (const GBProcedure &rhs)
bool inputEmpty () const
Check whether a polynomial is scheduled to be added to the Groebner basis.
size_t nrOrigGenerators () const
The number of polynomials which were originally added to the GB.
void addPolynomial (const Polynomial &p)
Add a polynmomial which is added to the groebner basis during the next calculate call.
bool basisIsConstant () const
Checks whether the current representants of the GB contain a constant polynomial.
std::list< Polynomial > listBasisPolynomials () const
const std::vector< Polynomial > & getBasisPolynomials () const
void printScheduledPolynomials (bool breakLines=true, bool printReasons=true, std::ostream &os=std::cout) const
void reset ()
Remove all polynomials from the Groebner basis.
const Ideal< Polynomial > & getIdeal () const
Get the ideal which encodes the GB.
void calculate ()
Calculate the Groebner basis of the current GB union the scheduled polynomials.
std::list< std::pair< BitVector, BitVector > > reduceInput ()
Reduce the input polynomials using the other input polynomials and the current Groebner basis.
Private Member Functions
void reduceGB ()
Private Attributes
std::shared_ptr< Ideal< Polynomial > > mGb
The ideal represented by the current elements of the Groebner basis.
std::list< Polynomial > mInputScheduled
The polynomials which are added during the next call for calculate.
std::vector< Polynomial > mOrigGenerators
The input polynomials.
std::vector< size_t > mOrigGeneratorsIndices
Indices of the input polynomials.
Detailed Description
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy>
class carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >
A general class for Groebner Basis calculation.
It is parameterized not only in the type of polynomial to be used, but also in the concrete procedure to be used, and the way polynomials should be added to this procedure.
Please notice that this class is designed to support incremental calls. Therefore, it holds a queue with the polynomials which are added. Only upon calling the calculate method, these polynoimials are added to the actual groebner basis.
Moreover, we can
Definition at line 45 of file GBProcedure.h.
Constructor & Destructor Documentation
GBProcedure() [1/2]
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::GBProcedure () inline
Definition at line 59 of file GBProcedure.h.
GBProcedure() [2/2]
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::GBProcedure (const GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy > & old) inline
Definition at line 70 of file GBProcedure.h.
~GBProcedure()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> virtual carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::~GBProcedure () virtual default
Member Function Documentation
addPolynomial()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> void carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::addPolynomial (const Polynomial & p) inline virtual
Add a polynmomial which is added to the groebner basis during the next calculate call.
Parameters
p The polynomial to be added.
Implements carl::AbstractGBProcedure< Polynomial >.
Definition at line 116 of file GBProcedure.h.
Referenced by carl::GroebnerBase< carl::Number >::GroebnerBase().
basisIsConstant()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> bool carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::basisIsConstant () const inline
Checks whether the current representants of the GB contain a constant polynomial.
Returns
Definition at line 126 of file GBProcedure.h.
calculate()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> void carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::calculate () inline virtual
Calculate the Groebner basis of the current GB union the scheduled polynomials.
Implements carl::AbstractGBProcedure< Polynomial >.
Definition at line 194 of file GBProcedure.h.
Referenced by carl::GroebnerBase< carl::Number >::GroebnerBase().
getBasisPolynomials()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> const std::vector<Polynomial>& carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::getBasisPolynomials () const inline
Returns
Definition at line 144 of file GBProcedure.h.
getIdeal()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> const Ideal<Polynomial>& carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::getIdeal () const inline virtual
Get the ideal which encodes the GB.
Returns
Implements carl::AbstractGBProcedure< Polynomial >.
Definition at line 186 of file GBProcedure.h.
Referenced by carl::GroebnerBase< carl::Number >::GroebnerBase().
inputEmpty()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> bool carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::inputEmpty () const inline
Check whether a polynomial is scheduled to be added to the Groebner basis.
Returns
whether the input is empty.
Definition at line 98 of file GBProcedure.h.
listBasisPolynomials()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> std::list<Polynomial> carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::listBasisPolynomials () const inline
Returns
Definition at line 135 of file GBProcedure.h.
nrOrigGenerators()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> size_t carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::nrOrigGenerators () const inline
The number of polynomials which were originally added to the GB.
Returns
number of polynomials added.
Definition at line 107 of file GBProcedure.h.
operator=()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> GBProcedure& carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::operator= (const GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy > & rhs) inline
Definition at line 82 of file GBProcedure.h.
printScheduledPolynomials()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> void carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::printScheduledPolynomials (bool breakLines = true, bool printReasons = true, std::ostream & os = std::cout) const inline
Definition at line 149 of file GBProcedure.h.
reduceGB()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> void carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::reduceGB () inline private
Definition at line 261 of file GBProcedure.h.
reduceInput()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> std::list<std::pair<BitVector, BitVector> > carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::reduceInput () inline virtual
Reduce the input polynomials using the other input polynomials and the current Groebner basis.
Returns
Implements carl::AbstractGBProcedure< Polynomial >.
Definition at line 216 of file GBProcedure.h.
Referenced by carl::GroebnerBase< carl::Number >::GroebnerBase().
reset()
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> void carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::reset () inline virtual
Remove all polynomials from the Groebner basis.
Implements carl::AbstractGBProcedure< Polynomial >.
Definition at line 176 of file GBProcedure.h.
Referenced by carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::operator=().
Field Documentation
mGb
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> std::shared_ptr<Ideal<Polynomial> > carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::mGb private
The ideal represented by the current elements of the Groebner basis.
Definition at line 49 of file GBProcedure.h.
Referenced by carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::operator=().
mInputScheduled
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> std::list<Polynomial> carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::mInputScheduled private
The polynomials which are added during the next call for calculate.
Definition at line 51 of file GBProcedure.h.
Referenced by carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::operator=().
mOrigGenerators
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> std::vector<Polynomial> carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::mOrigGenerators private
The input polynomials.
Definition at line 53 of file GBProcedure.h.
Referenced by carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::operator=().
mOrigGeneratorsIndices
template<typename Polynomial, template< typename, template< typename > class > class Procedure, template< typename > class AddingPolynomialPolicy> std::vector<size_t> carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::mOrigGeneratorsIndices private
Indices of the input polynomials.
Definition at line 55 of file GBProcedure.h.
Referenced by carl::GBProcedure< Polynomial, Procedure, AddingPolynomialPolicy >::operator=().
The documentation for this class was generated from the following file:
carl/groebner/GBProcedure.h