carl: carl::ModelVariable Class Reference
carl::ModelVariable Class Reference
Represent a sum type/variant over the different kinds of variables that exist in CARL to use them in a more uniform way, e.g.
#include <ModelVariable.h>
Public Member Functions
template<typename T , typename T2 = typename std::enable_if<convertible_to_variant<T, Base>::value, T>::type>
ModelVariable (const T &_t)
Initialize the ModelVariable from some valid type of the underlying variant.
std::size_t hash () const
bool isVariable () const
bool isBVVariable () const
bool isUVariable () const
bool isFunction () const
carl::Variable::Arg asVariable () const
const carl::BVVariable & asBVVariable () const
const carl::UVariable & asUVariable () const
const carl::UninterpretedFunction & asFunction () const
Private Types
using Base = boost::variant< Variable, BVVariable, UVariable, UninterpretedFunction >
Base type we are deriving from.
Private Attributes
Base mData
Friends
bool operator== (const ModelVariable &lhs, const ModelVariable &rhs)
Detailed Description
Represent a sum type/variant over the different kinds of variables that exist in CARL to use them in a more uniform way, e.g.
an (algebraic) "carl::Variable", an (uninterpreted) "carl::UVariable", an "carl::UninterpretedFunction" etc.
Definition at line 20 of file ModelVariable.h.
Member Typedef Documentation
Base
using carl::ModelVariable::Base = boost::variant<Variable,BVVariable,UVariable,UninterpretedFunction> private
Base type we are deriving from.
Definition at line 24 of file ModelVariable.h.
Constructor & Destructor Documentation
ModelVariable()
template<typename T , typename T2 = typename std::enable_if<convertible_to_variant<T, Base>::value, T>::type> carl::ModelVariable::ModelVariable (const T & _t) inline
Initialize the ModelVariable from some valid type of the underlying variant.
Definition at line 35 of file ModelVariable.h.
Member Function Documentation
asBVVariable()
const carl::BVVariable& carl::ModelVariable::asBVVariable () const inline
Returns
The stored value as a bitvector variable.
Definition at line 86 of file ModelVariable.h.
Referenced by carl::operator<(), carl::operator<<(), and carl::operator==().
asFunction()
const carl::UninterpretedFunction& carl::ModelVariable::asFunction () const inline
Returns
The stored value as a function.
Definition at line 104 of file ModelVariable.h.
Referenced by carl::operator<(), carl::operator<<(), and carl::operator==().
asUVariable()
const carl::UVariable& carl::ModelVariable::asUVariable () const inline
Returns
The stored value as an uninterpreted variable.
Definition at line 95 of file ModelVariable.h.
Referenced by carl::operator<(), carl::operator<<(), and carl::operator==().
asVariable()
carl::Variable::Arg carl::ModelVariable::asVariable () const inline
Returns
The stored value as a variable.
Definition at line 77 of file ModelVariable.h.
Referenced by carl::ModelFormulaSubstitution< Rational, Poly >::dependsOn(), carl::ModelMVRootSubstitution< Rational, Poly >::dependsOn(), carl::ModelPolynomialSubstitution< Rational, Poly >::dependsOn(), carl::operator<(), carl::operator<<(), carl::operator==(), carl::ModelFormulaSubstitution< Rational, Poly >::representingFormula(), carl::ModelMVRootSubstitution< Rational, Poly >::representingFormula(), and carl::ModelPolynomialSubstitution< Rational, Poly >::representingFormula().
hash()
std::size_t carl::ModelVariable::hash () const inline
Definition at line 38 of file ModelVariable.h.
Referenced by std::hash< carl::ModelVariable >::operator()().
isBVVariable()
bool carl::ModelVariable::isBVVariable () const inline
Returns
true, if the stored value is a bitvector variable.
Definition at line 53 of file ModelVariable.h.
Referenced by asBVVariable(), carl::ModelFormulaSubstitution< Rational, Poly >::dependsOn(), carl::operator<(), carl::operator<<(), and carl::operator==().
isFunction()
bool carl::ModelVariable::isFunction () const inline
Returns
true, if the stored value is a function.
Definition at line 69 of file ModelVariable.h.
Referenced by asFunction(), carl::ModelFormulaSubstitution< Rational, Poly >::dependsOn(), carl::operator<(), carl::operator<<(), and carl::operator==().
isUVariable()
bool carl::ModelVariable::isUVariable () const inline
Returns
true, if the stored value is an uninterpreted variable.
Definition at line 61 of file ModelVariable.h.
Referenced by asUVariable(), carl::ModelFormulaSubstitution< Rational, Poly >::dependsOn(), carl::operator<(), carl::operator<<(), and carl::operator==().
isVariable()
bool carl::ModelVariable::isVariable () const inline
Returns
true, if the stored value is a variable.
Definition at line 45 of file ModelVariable.h.
Referenced by asVariable(), carl::ModelFormulaSubstitution< Rational, Poly >::dependsOn(), carl::ModelMVRootSubstitution< Rational, Poly >::dependsOn(), carl::ModelPolynomialSubstitution< Rational, Poly >::dependsOn(), carl::operator<(), carl::operator<<(), carl::operator==(), carl::ModelFormulaSubstitution< Rational, Poly >::representingFormula(), carl::ModelMVRootSubstitution< Rational, Poly >::representingFormula(), and carl::ModelPolynomialSubstitution< Rational, Poly >::representingFormula().
Friends And Related Function Documentation
operator==
bool operator== (const ModelVariable & lhs, const ModelVariable & rhs) friend
Returns
true, if the first and the second are either both variables or both functions and in the first case the variables are equal (equal ids) or in the second case the functions are equal (equal ids).
Definition at line 118 of file ModelVariable.h.
Field Documentation
mData
Base carl::ModelVariable::mData private
Definition at line 26 of file ModelVariable.h.
Referenced by asBVVariable(), asFunction(), asUVariable(), asVariable(), hash(), isBVVariable(), isFunction(), isUVariable(), isVariable(), and carl::operator==().
The documentation for this class was generated from the following file:
carl/formula/model/ModelVariable.h