carl: carl::SMTLIBStream Class Reference
carl::SMTLIBStream Class Reference
#include <SMTLIBStream.h>
Public Member Functions
void initialize (Logic l, const Variables &vars)
template<typename Pol >
void initialize (Logic l, std::initializer_list< Formula< Pol >> formulas)
template<typename Pol >
void assertFormula (const Formula< Pol > &formula)
template<typename Pol >
void minimize (const Pol &objective)
void checkSat ()
void getModel ()
template<typename T >
SMTLIBStream & operator<< (T &&t)
SMTLIBStream & operator<< (std::ostream &(*os)(std::ostream &))
auto content () const
Private Member Functions
void declare (Logic l)
void declare (Sort s)
void declare (Variable v)
void write (const mpz_class &n)
void write (const mpq_class &n)
void write (const cln::cl_I &n)
void write (const cln::cl_RA &n)
template<typename Pol >
void write (const Constraint< Pol > &c)
template<typename Pol >
void write (const Formula< Pol > &f)
template<typename Rational , typename Poly >
void write (const Model< Rational, Poly > &model)
template<typename Rational , typename Poly >
void write (const ModelValue< Rational, Poly > &mv)
void write (const Monomial::Arg &m)
void write (const Monomial::Content::value_type &m)
void write (const Monomial &m)
template<typename Coeff >
void write (const MultivariatePolynomial< Coeff > &mp)
void write (Relation r)
template<typename Coeff >
void write (const Term< Coeff > &t)
template<typename Coeff >
void write (const UnivariatePolynomial< Coeff > &up)
void write (const Variable &v)
void write (const VariableType &vt)
template<typename T >
void write (T &&t)
Private Attributes
std::stringstream mStream
Detailed Description
Definition at line 23 of file SMTLIBStream.h.
Member Function Documentation
assertFormula()
template<typename Pol > void carl::SMTLIBStream::assertFormula (const Formula< Pol > & formula) inline
Definition at line 251 of file SMTLIBStream.h.
Referenced by carl::detail::operator<<().
checkSat()
void carl::SMTLIBStream::checkSat () inline
Definition at line 260 of file SMTLIBStream.h.
Referenced by carl::detail::operator<<().
content()
auto carl::SMTLIBStream::content () const inline
Definition at line 279 of file SMTLIBStream.h.
Referenced by carl::operator<<().
declare() [1/3]
void carl::SMTLIBStream::declare (Logic l) inline private
Definition at line 27 of file SMTLIBStream.h.
Referenced by initialize().
declare() [2/3]
void carl::SMTLIBStream::declare (Sort s) inline private
Definition at line 30 of file SMTLIBStream.h.
declare() [3/3]
void carl::SMTLIBStream::declare (Variable v) inline private
Definition at line 33 of file SMTLIBStream.h.
getModel()
void carl::SMTLIBStream::getModel () inline
Definition at line 264 of file SMTLIBStream.h.
Referenced by carl::detail::operator<<().
initialize() [1/2]
void carl::SMTLIBStream::initialize (Logic l, const Variables & vars) inline
Definition at line 234 of file SMTLIBStream.h.
Referenced by initialize(), and carl::detail::operator<<().
initialize() [2/2]
template<typename Pol > void carl::SMTLIBStream::initialize (Logic l, std::initializer_list< Formula< Pol >> formulas) inline
Definition at line 242 of file SMTLIBStream.h.
minimize()
template<typename Pol > void carl::SMTLIBStream::minimize (const Pol & objective) inline
Definition at line 256 of file SMTLIBStream.h.
Referenced by carl::detail::operator<<().
operator<<() [1/2]
template<typename T > SMTLIBStream& carl::SMTLIBStream::operator<< (T && t) inline
Definition at line 269 of file SMTLIBStream.h.
operator<<() [2/2]
SMTLIBStream& carl::SMTLIBStream::operator<< (std::ostream &(*)(std::ostream &) os) inline
Definition at line 274 of file SMTLIBStream.h.
write() [1/18]
void carl::SMTLIBStream::write (const mpz_class & n) inline private
Definition at line 37 of file SMTLIBStream.h.
Referenced by operator<<(), and write().
write() [2/18]
void carl::SMTLIBStream::write (const mpq_class & n) inline private
Definition at line 38 of file SMTLIBStream.h.
write() [3/18]
void carl::SMTLIBStream::write (const cln::cl_I & n) inline private
Definition at line 40 of file SMTLIBStream.h.
write() [4/18]
void carl::SMTLIBStream::write (const cln::cl_RA & n) inline private
Definition at line 41 of file SMTLIBStream.h.
write() [5/18]
template<typename Pol > void carl::SMTLIBStream::write (const Constraint< Pol > & c) inline private
Definition at line 45 of file SMTLIBStream.h.
write() [6/18]
template<typename Pol > void carl::SMTLIBStream::write (const Formula< Pol > & f) inline private
Definition at line 54 of file SMTLIBStream.h.
write() [7/18]
template<typename Rational , typename Poly > void carl::SMTLIBStream::write (const Model< Rational, Poly > & model) inline private
Definition at line 106 of file SMTLIBStream.h.
write() [8/18]
template<typename Rational , typename Poly > void carl::SMTLIBStream::write (const ModelValue< Rational, Poly > & mv) inline private
Definition at line 132 of file SMTLIBStream.h.
write() [9/18]
void carl::SMTLIBStream::write (const Monomial::Arg & m) inline private
Definition at line 140 of file SMTLIBStream.h.
write() [10/18]
void carl::SMTLIBStream::write (const Monomial::Content::value_type & m) inline private
Definition at line 144 of file SMTLIBStream.h.
write() [11/18]
void carl::SMTLIBStream::write (const Monomial & m) inline private
Definition at line 153 of file SMTLIBStream.h.
write() [12/18]
template<typename Coeff > void carl::SMTLIBStream::write (const MultivariatePolynomial< Coeff > & mp) inline private
Definition at line 164 of file SMTLIBStream.h.
write() [13/18]
void carl::SMTLIBStream::write (Relation r) inline private
Definition at line 176 of file SMTLIBStream.h.
write() [14/18]
template<typename Coeff > void carl::SMTLIBStream::write (const Term< Coeff > & t) inline private
Definition at line 188 of file SMTLIBStream.h.
write() [15/18]
template<typename Coeff > void carl::SMTLIBStream::write (const UnivariatePolynomial< Coeff > & up) inline private
Definition at line 200 of file SMTLIBStream.h.
write() [16/18]
void carl::SMTLIBStream::write (const Variable & v) inline private
Definition at line 214 of file SMTLIBStream.h.
write() [17/18]
void carl::SMTLIBStream::write (const VariableType & vt) inline private
Definition at line 217 of file SMTLIBStream.h.
write() [18/18]
template<typename T > void carl::SMTLIBStream::write (T && t) inline private
Definition at line 229 of file SMTLIBStream.h.
Field Documentation
mStream
std::stringstream carl::SMTLIBStream::mStream private
Definition at line 25 of file SMTLIBStream.h.
Referenced by content(), and write().
The documentation for this class was generated from the following file:
carl/io/SMTLIBStream.h