carl: carl::SimpleConstraint< LhsType > Class Template Reference
carl::SimpleConstraint< LhsType > Class Template Reference
#include <SimpleConstraint.h>
Public Member Functions
SimpleConstraint (bool v)
SimpleConstraint (const LhsType &lhs, Relation rel)
const LhsType & lhs () const
const Relation & rel () const
bool isTrivialTrue () const
bool isTrivialFalse () const
Private Attributes
LhsType mLhs
Relation mRelation
Detailed Description
template<typename LhsType>
class carl::SimpleConstraint< LhsType >
Definition at line 14 of file SimpleConstraint.h.
Constructor & Destructor Documentation
SimpleConstraint() [1/2]
template<typename LhsType> carl::SimpleConstraint< LhsType >::SimpleConstraint (bool v) inline
Definition at line 17 of file SimpleConstraint.h.
SimpleConstraint() [2/2]
template<typename LhsType> carl::SimpleConstraint< LhsType >::SimpleConstraint (const LhsType & lhs, Relation rel) inline
Definition at line 18 of file SimpleConstraint.h.
Member Function Documentation
isTrivialFalse()
template<typename LhsType> bool carl::SimpleConstraint< LhsType >::isTrivialFalse () const inline
Definition at line 40 of file SimpleConstraint.h.
isTrivialTrue()
template<typename LhsType> bool carl::SimpleConstraint< LhsType >::isTrivialTrue () const inline
Definition at line 24 of file SimpleConstraint.h.
lhs()
template<typename LhsType> const LhsType& carl::SimpleConstraint< LhsType >::lhs () const inline
Definition at line 21 of file SimpleConstraint.h.
Referenced by std::hash< carl::SimpleConstraint< LhsType > >::operator()(), carl::operator==(), and carl::to_string().
rel()
template<typename LhsType> const Relation& carl::SimpleConstraint< LhsType >::rel () const inline
Definition at line 22 of file SimpleConstraint.h.
Referenced by std::hash< carl::SimpleConstraint< LhsType > >::operator()(), carl::operator==(), and carl::to_string().
Field Documentation
mLhs
template<typename LhsType> LhsType carl::SimpleConstraint< LhsType >::mLhs private
Definition at line 57 of file SimpleConstraint.h.
Referenced by carl::SimpleConstraint< LhsType >::isTrivialFalse(), carl::SimpleConstraint< LhsType >::isTrivialTrue(), and carl::SimpleConstraint< LhsType >::lhs().
mRelation
template<typename LhsType> Relation carl::SimpleConstraint< LhsType >::mRelation private
Definition at line 58 of file SimpleConstraint.h.
Referenced by carl::SimpleConstraint< LhsType >::isTrivialFalse(), carl::SimpleConstraint< LhsType >::isTrivialTrue(), and carl::SimpleConstraint< LhsType >::rel().
The documentation for this class was generated from the following file:
carl/core/SimpleConstraint.h