carl: carl::SortValue Class Reference
carl::SortValue Class Reference
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
#include <SortValue.h>
Public Member Functions
SortValue () noexcept=default
const carl::Sort & sort () const noexcept
std::size_t id () const noexcept
bool operator== (const SortValue &_sortValue) const noexcept
bool operator< (const SortValue &_sortValue) const noexcept
Private Member Functions
SortValue (Sort _sort, std::size_t _id)
Constructs a sort value.
Private Attributes
carl::Sort mSort
The sort defining the domain in which this value is.
std::size_t mId = 0
A unique id to identify this sort in the sort value manager.
Friends
class SortValueManager
std::ostream & operator<< (std::ostream &os, const SortValue &sv)
Prints the given sort value on the given output stream.
Detailed Description
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
Definition at line 22 of file SortValue.h.
Constructor & Destructor Documentation
SortValue() [1/2]
carl::SortValue::SortValue (Sort _sort, std::size_t _id) inline explicit private
Constructs a sort value.
Parameters
_id The id of the sort value to construct.
Definition at line 39 of file SortValue.h.
SortValue() [2/2]
carl::SortValue::SortValue () default noexcept
Member Function Documentation
id()
std::size_t carl::SortValue::id () const inline noexcept
Returns
The id of this sort value.
Definition at line 59 of file SortValue.h.
Referenced by std::hash< carl::SortValue >::operator()(), and carl::operator<<().
operator<()
bool carl::SortValue::operator< (const SortValue & _sortValue) const noexcept
Parameters
_sortValue The sort value to compare with.
Returns
true, if this sort value is less than the given one.
Definition at line 19 of file SortValue.cpp.
operator==()
bool carl::SortValue::operator== (const SortValue & _sortValue) const noexcept
Parameters
_sortValue The sort value to compare with.
Returns
true, if this sort value equals the given one.
Definition at line 13 of file SortValue.cpp.
sort()
const carl::Sort& carl::SortValue::sort () const inline noexcept
Returns
The sort of this value.
Definition at line 51 of file SortValue.h.
Referenced by std::hash< carl::SortValue >::operator()(), and carl::operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SortValue & sv) friend
Prints the given sort value on the given output stream.
Parameters
_os The output stream to print on.
_sortValue The sort value to print.
Returns
The output stream after printing the given sort value on it.
Definition at line 25 of file SortValue.cpp.
SortValueManager
friend class SortValueManager friend
Definition at line 25 of file SortValue.h.
Field Documentation
mId
std::size_t carl::SortValue::mId = 0 private
A unique id to identify this sort in the sort value manager.
Definition at line 33 of file SortValue.h.
Referenced by id().
mSort
carl::Sort carl::SortValue::mSort private
The sort defining the domain in which this value is.
Definition at line 31 of file SortValue.h.
Referenced by sort().
The documentation for this class was generated from the following files:
carl/formula/model/uninterpreted/SortValue.h
carl/formula/model/uninterpreted/SortValue.cpp