carl: carl::BVConstraint Class Reference
carl::BVConstraint Class Reference
#include <BVConstraint.h>
Public Member Functions
const BVTerm & lhs () const
const BVTerm & rhs () const
BVCompareRelation relation () const
std::size_t id () const
void collectVariables (std::set< BVVariable > &vars) const
std::size_t getHash () const
bool isConstant () const
bool isAlwaysConsistent () const
bool isAlwaysInconsistent () const
std::string toString (const std::string &_init="", bool _oneline=true, bool _infix=false, bool _friendlyNames=true) const
Gives the string representation of this bit vector constraint.
bool operator== (const BVConstraint &_other) const
bool operator< (const BVConstraint &_other) const
std::size_t hash () const
size_t complexity () const
Static Public Member Functions
static BVConstraint create (bool _consistent=true)
static BVConstraint create (const BVCompareRelation &_relation, const BVTerm &_lhs, const BVTerm &_rhs)
Private Member Functions
BVConstraint (bool _consistent=true)
BVConstraint (const BVCompareRelation &_relation, const BVTerm &_lhs, const BVTerm &_rhs)
Constructs the constraint: _lhs _relation _rhs.
Private Attributes
std::size_t mHash = 0
The hash value.
std::size_t mId = 0
The unique id.
BVCompareRelation mRelation
The relation for comparing left- and right-hand side.
BVTerm mLhs
The left-hand side of the (in)equality.
BVTerm mRhs
The right-hand size of the (in)equality.
Friends
class BVConstraintPool
std::ostream & operator<< (std::ostream &_out, const BVConstraint &_constraint)
The output operator of a constraint.
Detailed Description
Definition at line 17 of file BVConstraint.h.
Constructor & Destructor Documentation
BVConstraint() [1/2]
carl::BVConstraint::BVConstraint (bool _consistent = true) inline explicit private
Definition at line 35 of file BVConstraint.h.
BVConstraint() [2/2]
carl::BVConstraint::BVConstraint (const BVCompareRelation & _relation, const BVTerm & _lhs, const BVTerm & _rhs) inline private
Constructs the constraint: _lhs _relation _rhs.
Parameters
_lhs The bit-vector term to be used as left-hand side of the constraint.
_rhs The bit-vector term to be used as right-hand side of the constraint.
_relation The relation symbol to be used for the constraint.
Definition at line 45 of file BVConstraint.h.
Member Function Documentation
collectVariables()
void carl::BVConstraint::collectVariables (std::set< BVVariable > & vars) const inline
Definition at line 92 of file BVConstraint.h.
complexity()
size_t carl::BVConstraint::complexity () const inline
Returns
An approximation of the complexity of this bit vector constraint.
Definition at line 197 of file BVConstraint.h.
create() [1/2]
BVConstraint carl::BVConstraint::create (bool _consistent = true) static
Definition at line 11 of file BVConstraint.cpp.
Referenced by carl::FormulaSubstitutor< Formula >::BitvectorSubstitutor::operator()(), and carl::model::substituteIn().
create() [2/2]
BVConstraint carl::BVConstraint::create (const BVCompareRelation & _relation, const BVTerm & _lhs, const BVTerm & _rhs) static
Definition at line 16 of file BVConstraint.cpp.
getHash()
std::size_t carl::BVConstraint::getHash () const inline
Returns
A hash value for this constraint.
Definition at line 100 of file BVConstraint.h.
hash()
std::size_t carl::BVConstraint::hash () const inline
Definition at line 189 of file BVConstraint.h.
Referenced by std::hash< carl::BVConstraint >::operator()().
id()
std::size_t carl::BVConstraint::id () const inline
Returns
The unique id of this constraint.
Definition at line 87 of file BVConstraint.h.
isAlwaysConsistent()
bool carl::BVConstraint::isAlwaysConsistent () const inline
Definition at line 110 of file BVConstraint.h.
Referenced by carl::model::evaluate(), carl::model::substituteIn(), and toString().
isAlwaysInconsistent()
bool carl::BVConstraint::isAlwaysInconsistent () const inline
Definition at line 115 of file BVConstraint.h.
Referenced by carl::model::evaluate(), carl::model::substituteIn(), and toString().
isConstant()
bool carl::BVConstraint::isConstant () const inline
Definition at line 105 of file BVConstraint.h.
Referenced by isAlwaysConsistent(), and isAlwaysInconsistent().
lhs()
const BVTerm& carl::BVConstraint::lhs () const inline
Returns
The bit-vector term being the left-hand side of this constraint.
Definition at line 63 of file BVConstraint.h.
Referenced by carl::FormulaSubstitutor< Formula >::BitvectorSubstitutor::operator()(), and carl::model::substituteIn().
operator<()
bool carl::BVConstraint::operator< (const BVConstraint & _other) const inline
Definition at line 178 of file BVConstraint.h.
operator==()
bool carl::BVConstraint::operator== (const BVConstraint & _other) const inline
Definition at line 167 of file BVConstraint.h.
relation()
BVCompareRelation carl::BVConstraint::relation () const inline
Returns
The relation symbol of this constraint.
Definition at line 79 of file BVConstraint.h.
Referenced by carl::FormulaSubstitutor< Formula >::BitvectorSubstitutor::operator()(), and carl::model::substituteIn().
rhs()
const BVTerm& carl::BVConstraint::rhs () const inline
Returns
The bit-vector term being the right-hand side of this constraint.
Definition at line 71 of file BVConstraint.h.
Referenced by carl::FormulaSubstitutor< Formula >::BitvectorSubstitutor::operator()(), and carl::model::substituteIn().
toString()
std::string carl::BVConstraint::toString (const std::string & _init = "", bool _oneline = true, bool _infix = false, bool _friendlyNames = true) const inline
Gives the string representation of this bit vector constraint.
Parameters
_init The initial string of every row of the result.
_oneline A flag indicating whether the constraint shall be printed on one line.
_infix A flag indicating whether to print the constraint in infix or prefix notation.
_friendlyNames A flag that indicates whether to print the variables with their internal representation (false) or with their dedicated names.
Returns
The resulting string representation of this constraint.
Definition at line 129 of file BVConstraint.h.
Friends And Related Function Documentation
BVConstraintPool
friend class BVConstraintPool friend
Definition at line 19 of file BVConstraint.h.
operator<<
std::ostream& operator<< (std::ostream & _out, const BVConstraint & _constraint) friend
The output operator of a constraint.
Parameters
_out The stream to print on.
_constraint The constraint to be printed.
Definition at line 162 of file BVConstraint.h.
Field Documentation
mHash
std::size_t carl::BVConstraint::mHash = 0 private
The hash value.
Definition at line 23 of file BVConstraint.h.
Referenced by getHash(), and hash().
mId
std::size_t carl::BVConstraint::mId = 0 private
The unique id.
Definition at line 25 of file BVConstraint.h.
Referenced by carl::BVConstraintPool::assignId(), id(), operator<(), and operator==().
mLhs
BVTerm carl::BVConstraint::mLhs private
The left-hand side of the (in)equality.
Definition at line 30 of file BVConstraint.h.
Referenced by collectVariables(), complexity(), isConstant(), lhs(), operator<(), operator==(), and toString().
mRelation
BVCompareRelation carl::BVConstraint::mRelation private
The relation for comparing left- and right-hand side.
Definition at line 28 of file BVConstraint.h.
Referenced by isAlwaysConsistent(), isAlwaysInconsistent(), operator<(), operator==(), relation(), and toString().
mRhs
BVTerm carl::BVConstraint::mRhs private
The right-hand size of the (in)equality.
Definition at line 32 of file BVConstraint.h.
Referenced by collectVariables(), complexity(), isConstant(), operator<(), operator==(), rhs(), and toString().
The documentation for this class was generated from the following files:
carl/formula/bitvector/BVConstraint.h
carl/formula/bitvector/BVConstraint.cpp