carl: carl::SortManager Class Reference
carl::SortManager Class Reference
Implements a manager for sorts, containing the actual contents of these sort and allocating their ids.
#include <SortManager.h>
Public Types
using SortTemplate = std::pair< std::vector< std::string >, Sort >
The type of a sort template, define by define-sort.
Public Member Functions
~SortManager () noexcept override=default
void clear ()
const std::string & getName (const Sort &sort) const
const std::vector< Sort > * getParameters (const Sort &sort) const
const std::vector< std::size_t > * getIndices (const Sort &sort) const
VariableType getType (const Sort &sort) const
std::ostream & print (std::ostream &os, const Sort &sort) const
Prints the given sort on the given output stream.
void exportDefinitions (std::ostream &os) const
Sort getInterpreted (VariableType type) const
Sort replace (const Sort &sort, const std::map< std::string, Sort > &parameters)
Recursively replaces sorts within the given sort according to the mapping of sort names to sorts as declared by the given map.
bool declare (const std::string &name, std::size_t arity)
Adds a sort declaration.
bool define (const std::string &name, const std::vector< std::string > &params, const Sort &sort)
Adds a sort template definitions.
std::size_t getArity (const Sort &sort) const
Sort addInterpretedMapping (const Sort &sort, VariableType type)
Sort addInterpretedSort (const std::string &name, VariableType type)
Sort addInterpretedSort (const std::string &name, const std::vector< Sort > &parameters, VariableType type)
Sort addSort (const std::string &name, VariableType type=VariableType::VT_UNINTERPRETED)
Sort addSort (const std::string &name, const std::vector< Sort > &parameters, VariableType type=VariableType::VT_UNINTERPRETED)
void makeSortIndexable (const Sort &sort, std::size_t indices, VariableType type)
bool isInterpreted (const Sort &sort) const
Sort index (const Sort &sort, const std::vector< std::size_t > &indices)
Sort getSort (const std::string &name)
Gets the sort with arity zero (thus it is maybe interpreted) corresponding the given name.
Sort getSort (const std::string &name, const std::vector< Sort > &params)
Gets the sort with arity greater than zero corresponding the given name and having the arguments of the given sorts.
Sort getSort (const std::string &name, const std::vector< std::size_t > &indices)
Sort getSort (const std::string &name, const std::vector< std::size_t > &indices, const std::vector< Sort > &params)
Static Public Member Functions
static SortManager & getInstance ()
Returns the single instance of this class by reference.
Private Member Functions
SortManager ()
Constructs a sort manager.
const SortContent & getContent (const Sort &sort) const
bool isSymbolFree (const std::string &name) const
Sort getSort (std::unique_ptr< SortContent > &&content, VariableType type)
std::size_t addSortContent (std::unique_ptr< SortContent > &&content, VariableType type)
VariableType checkIndices (const SortContent &content, std::size_t count) const
Private Attributes
friend Singleton< SortManager >
std::vector< std::unique_ptr< SortContent > > mSorts
Maps the unique ids to the sort content.
std::vector< VariableType > mSortTypes
Maps the unique ids to the sort types.
std::map< const SortContent *, std::size_t, carl::less< const SortContent * > > mSortMap
Maps the sort contents to unique ids.
std::map< std::string, std::size_t > mDeclarations
Stores all sort declarations invoked by a declare-sort.
std::map< std::string, SortTemplate > mDefinitions
Stores all sort definitions invoked by a define-sort.
std::map< Sort, std::pair< std::size_t, VariableType > > mIndexable
Stores all sorts that may become interpreted when indexed.
std::map< VariableType, Sort > mInterpreted
Maps variable types to actual sorts.
Detailed Description
Implements a manager for sorts, containing the actual contents of these sort and allocating their ids.
Definition at line 107 of file SortManager.h.
Member Typedef Documentation
SortTemplate
using carl::SortManager::SortTemplate = std::pair<std::vector<std::string>, Sort>
The type of a sort template, define by define-sort.
Definition at line 112 of file SortManager.h.
Constructor & Destructor Documentation
SortManager()
carl::SortManager::SortManager () inline private
Constructs a sort manager.
Definition at line 135 of file SortManager.h.
~SortManager()
carl::SortManager::~SortManager () override default noexcept
Member Function Documentation
addInterpretedMapping()
Sort carl::SortManager::addInterpretedMapping (const Sort & sort, VariableType type) inline
Definition at line 260 of file SortManager.h.
Referenced by addInterpretedSort().
addInterpretedSort() [1/2]
Sort carl::SortManager::addInterpretedSort (const std::string & name, VariableType type) inline
Definition at line 265 of file SortManager.h.
addInterpretedSort() [2/2]
Sort carl::SortManager::addInterpretedSort (const std::string & name, const std::vector< Sort > & parameters, VariableType type) inline
Definition at line 268 of file SortManager.h.
addSort() [1/2]
Sort carl::SortManager::addSort (const std::string & name, VariableType type = VariableType::VT_UNINTERPRETED)
Definition at line 73 of file SortManager.cpp.
Referenced by addInterpretedSort().
addSort() [2/2]
Sort carl::SortManager::addSort (const std::string & name, const std::vector< Sort > & parameters, VariableType type = VariableType::VT_UNINTERPRETED)
Definition at line 77 of file SortManager.cpp.
addSortContent()
std::size_t carl::SortManager::addSortContent (std::unique_ptr< SortContent > && content, VariableType type) inline private
Definition at line 161 of file SortManager.h.
Referenced by addSort(), declare(), and getSort().
checkIndices()
VariableType carl::SortManager::checkIndices (const SortContent & content, std::size_t count) const inline private
Definition at line 168 of file SortManager.h.
Referenced by index().
clear()
void carl::SortManager::clear () inline
Definition at line 181 of file SortManager.h.
Referenced by SortManager().
declare()
bool carl::SortManager::declare (const std::string & name, std::size_t arity)
Adds a sort declaration.
Parameters
name The name of the declared sort.
arity The arity of the declared sort.
Returns
true, if the given sort declaration has not been added before; false, otherwise.
Definition at line 54 of file SortManager.cpp.
define()
bool carl::SortManager::define (const std::string & name, const std::vector< std::string > & params, const Sort & sort)
Adds a sort template definitions.
Parameters
name The name of the defined sort template.
params The template parameter of the defined sort.
sort The sort to instantiate into.
Returns
true, if the given sort template definition has not been added before; false, otherwise.
Definition at line 61 of file SortManager.cpp.
exportDefinitions()
void carl::SortManager::exportDefinitions (std::ostream & os) const
Todo:
fix this
Definition at line 31 of file SortManager.cpp.
getArity()
size_t carl::SortManager::getArity (const Sort & sort) const
Parameters
sort The sort to get the arity for.
Returns
The arity of the given sort.
Definition at line 67 of file SortManager.cpp.
Referenced by carl::Sort::arity().
getContent()
const SortContent& carl::SortManager::getContent (const Sort & sort) const inline private
Definition at line 139 of file SortManager.h.
Referenced by getArity(), getIndices(), getName(), getParameters(), index(), print(), and replace().
getIndices()
const std::vector<std::size_t>* carl::SortManager::getIndices (const Sort & sort) const inline
Definition at line 203 of file SortManager.h.
Referenced by carl::BVVariable::BVVariable().
getInstance()
static SortManager & carl::Singleton< SortManager >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::Sort::arity(), carl::BVVariable::BVVariable(), carl::getSort(), and carl::operator<<().
getInterpreted()
Sort carl::SortManager::getInterpreted (VariableType type) const inline
Definition at line 222 of file SortManager.h.
getName()
const std::string& carl::SortManager::getName (const Sort & sort) const inline
Parameters
sort A sort.
Returns
The name if the given sort.
Definition at line 197 of file SortManager.h.
getParameters()
const std::vector<Sort>* carl::SortManager::getParameters (const Sort & sort) const inline
Definition at line 200 of file SortManager.h.
getSort() [1/5]
Sort carl::SortManager::getSort (std::unique_ptr< SortContent > && content, VariableType type) inline private
Definition at line 153 of file SortManager.h.
Referenced by getSort(), carl::getSort(), index(), and replace().
getSort() [2/5]
Sort carl::SortManager::getSort (const std::string & name)
Gets the sort with arity zero (thus it is maybe interpreted) corresponding the given name.
Parameters
name The name of the sort to get.
Returns
The resulting sort.
Definition at line 96 of file SortManager.cpp.
getSort() [3/5]
Sort carl::SortManager::getSort (const std::string & name, const std::vector< Sort > & params)
Gets the sort with arity greater than zero corresponding the given name and having the arguments of the given sorts.
Parameters
name The name of the sort to get.
params The sort of the arguments of the sort to get.
Returns
The resulting sort.
Definition at line 107 of file SortManager.cpp.
getSort() [4/5]
Sort carl::SortManager::getSort (const std::string & name, const std::vector< std::size_t > & indices)
Definition at line 135 of file SortManager.cpp.
getSort() [5/5]
Sort carl::SortManager::getSort (const std::string & name, const std::vector< std::size_t > & indices, const std::vector< Sort > & params)
Definition at line 139 of file SortManager.cpp.
getType()
VariableType carl::SortManager::getType (const Sort & sort) const inline
Definition at line 206 of file SortManager.h.
Referenced by isInterpreted().
index()
Sort carl::SortManager::index (const Sort & sort, const std::vector< std::size_t > & indices)
Definition at line 85 of file SortManager.cpp.
Referenced by getSort().
isInterpreted()
bool carl::SortManager::isInterpreted (const Sort & sort) const inline
Parameters
sort A sort.
Returns
true, if the given sort is interpreted.
Definition at line 279 of file SortManager.h.
isSymbolFree()
bool carl::SortManager::isSymbolFree (const std::string & name) const inline private
Definition at line 144 of file SortManager.h.
Referenced by addSort(), declare(), and define().
makeSortIndexable()
void carl::SortManager::makeSortIndexable (const Sort & sort, std::size_t indices, VariableType type)
Definition at line 81 of file SortManager.cpp.
print()
std::ostream & carl::SortManager::print (std::ostream & os, const Sort & sort) const
Prints the given sort on the given output stream.
Parameters
os The output stream to print the given sort on.
sort The sort to print.
Returns
The output stream after printing the given sort on it.
Definition at line 13 of file SortManager.cpp.
Referenced by carl::operator<<().
replace()
Sort carl::SortManager::replace (const Sort & sort, const std::map< std::string, Sort > & parameters)
Recursively replaces sorts within the given sort according to the mapping of sort names to sorts as declared by the given map.
Parameters
_sort The sort to replace sorts by sorts in.
_parameters The map of sort names to sorts.
Returns
The resulting sort.
Definition at line 41 of file SortManager.cpp.
Referenced by getSort().
Field Documentation
mDeclarations
std::map<std::string, std::size_t> carl::SortManager::mDeclarations private
Stores all sort declarations invoked by a declare-sort.
Definition at line 124 of file SortManager.h.
Referenced by clear(), declare(), exportDefinitions(), getSort(), and isSymbolFree().
mDefinitions
std::map<std::string, SortTemplate> carl::SortManager::mDefinitions private
Stores all sort definitions invoked by a define-sort.
Definition at line 126 of file SortManager.h.
Referenced by clear(), define(), getSort(), and isSymbolFree().
mIndexable
std::map<Sort, std::pair<std::size_t, VariableType> > carl::SortManager::mIndexable private
Stores all sorts that may become interpreted when indexed.
Definition at line 128 of file SortManager.h.
Referenced by checkIndices(), clear(), and makeSortIndexable().
mInterpreted
std::map<VariableType, Sort> carl::SortManager::mInterpreted private
Maps variable types to actual sorts.
Definition at line 130 of file SortManager.h.
Referenced by addInterpretedMapping(), clear(), and getInterpreted().
mSortMap
std::map<const SortContent*, std::size_t, carl::less<const SortContent*> > carl::SortManager::mSortMap private
Maps the sort contents to unique ids.
Definition at line 122 of file SortManager.h.
Referenced by addSortContent(), checkIndices(), clear(), and getSort().
mSorts
std::vector<std::unique_ptr<SortContent> > carl::SortManager::mSorts private
Maps the unique ids to the sort content.
Definition at line 118 of file SortManager.h.
Referenced by addSortContent(), clear(), getContent(), and isSymbolFree().
mSortTypes
std::vector<VariableType> carl::SortManager::mSortTypes private
Maps the unique ids to the sort types.
Definition at line 120 of file SortManager.h.
Referenced by addSortContent(), clear(), and getType().
Singleton< SortManager >
friend carl::SortManager::Singleton< SortManager > private
Definition at line 108 of file SortManager.h.
The documentation for this class was generated from the following files:
carl/formula/SortManager.h
carl/formula/SortManager.cpp