carl: carl::UFInstance Class Reference
carl::UFInstance Class Reference
Implements an uninterpreted function instance.
#include <UFInstance.h>
Public Member Functions
UFInstance ()
Default constructor.
std::size_t id () const
const UninterpretedFunction & uninterpretedFunction () const
const std::vector< UVariable > & args () const
bool operator== (const UFInstance &_ufun) const
bool operator< (const UFInstance &_ufun) const
std::string toString (bool _infix, bool _friendlyNames) const
Private Member Functions
UFInstance (std::size_t id) noexcept
Constructs an uninterpreted function instance.
Private Attributes
std::size_t mId
A unique id.
Friends
class UFInstanceManager
std::ostream & operator<< (std::ostream &_os, const UFInstance &_ufun)
Prints the given uninterpreted function instance on the given output stream.
Detailed Description
Implements an uninterpreted function instance.
Definition at line 23 of file UFInstance.h.
Constructor & Destructor Documentation
UFInstance() [1/2]
carl::UFInstance::UFInstance (std::size_t id) inline explicit private noexcept
Constructs an uninterpreted function instance.
Parameters
_id
Definition at line 36 of file UFInstance.h.
UFInstance() [2/2]
carl::UFInstance::UFInstance () inline
Default constructor.
Definition at line 43 of file UFInstance.h.
Member Function Documentation
args()
const std::vector< UVariable > & carl::UFInstance::args () const
Returns
The arguments of this uninterpreted function instance.
Definition at line 25 of file UFInstance.cpp.
Referenced by carl::UEquality::complexity(), carl::model::evaluate(), and carl::UFInstanceManager::print().
id()
std::size_t carl::UFInstance::id () const inline
Returns
The unique id of this uninterpreted function instance.
Definition at line 50 of file UFInstance.h.
Referenced by carl::UFInstanceManager::getArgs(), carl::UFInstanceManager::getUninterpretedFunction(), std::hash< carl::UFInstance >::operator()(), operator<(), operator==(), and carl::UFInstanceManager::print().
operator<()
bool carl::UFInstance::operator< (const UFInstance & _ufun) const inline
Parameters
_ufun The uninterpreted function instance to compare with.
Returns
true, if this uninterpreted function instance is less than the given one.
Definition at line 78 of file UFInstance.h.
operator==()
bool carl::UFInstance::operator== (const UFInstance & _ufun) const inline
Parameters
_ufun The uninterpreted function instance to compare with.
Returns
true, if this and the given uninterpreted function instance are equal.
Definition at line 69 of file UFInstance.h.
toString()
std::string carl::UFInstance::toString (bool _infix, bool _friendlyNames) const
Returns
The string representation of this uninterpreted function instance.
Definition at line 30 of file UFInstance.cpp.
Referenced by carl::UEquality::toString().
uninterpretedFunction()
const UninterpretedFunction & carl::UFInstance::uninterpretedFunction () const
Returns
The underlying uninterpreted function of this instance.
Definition at line 20 of file UFInstance.cpp.
Referenced by carl::model::evaluate(), carl::UFInstanceManager::print(), and carl::UEquality::UEquality().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & _os, const UFInstance & _ufun) friend
Prints the given uninterpreted function instance on the given output stream.
Parameters
_os The output stream to print on.
_ufun The uninterpreted function instance to print.
Returns
The output stream after printing the given uninterpreted function instance on it.
Definition at line 37 of file UFInstance.cpp.
UFInstanceManager
friend class UFInstanceManager friend
Definition at line 26 of file UFInstance.h.
Field Documentation
mId
std::size_t carl::UFInstance::mId private
A unique id.
Definition at line 30 of file UFInstance.h.
Referenced by id(), operator<(), and operator==().
The documentation for this class was generated from the following files:
carl/formula/uninterpreted/UFInstance.h
carl/formula/uninterpreted/UFInstance.cpp