carl: carl::ThomEncoding< Number > Class Template Reference
carl::ThomEncoding< Number > Class Template Reference
#include <ThomEncoding.h>
Public Member Functions
ThomEncoding (SignCondition sc, const Polynomial &p, Variable mainVar, std::shared_ptr< ThomEncoding< Number >> point, std::shared_ptr< SignDetermination< Number >> sd, uint mRelevant)
ThomEncoding (const Number &n, Variable mainVar, std::shared_ptr< ThomEncoding< Number >> point=nullptr)
ThomEncoding (const ThomEncoding< Number > &te, std::shared_ptr< ThomEncoding< Number >> point)
SignCondition signCondition () const
SignCondition relevantSignCondition () const
Variable::Arg mainVar () const
const Polynomial & polynomial () const
const ThomEncoding< Number > & point () const
SignDetermination< Number > sd () const
std::list< Polynomial > relevantDerivatives () const
ThomEncoding< Number > lowestInChain () const
uint dimension () const
std::list< Polynomial > accumulatePolynomials () const
std::list< Variable > accumulateVariables () const
SignCondition accumulateSigns () const
SignCondition accumulateRelevantSigns () const
Sign signOnPolynomial (const Polynomial &p) const
bool makesPolynomialZero (const Polynomial &pol, Variable::Arg pol_mainVar) const
void extendSignCondition () const
Sign sgnReprNum () const
bool isZero () const
ThomEncoding< Number > concat (const ThomEncoding< Number > &other) const
bool equals (const ThomEncoding< Number > &other) const
ThomEncoding< Number > operator+ (const Number &rhs) const
void print (std::ostream &os) const
Static Public Member Functions
static ThomEncoding< Number > analyzeTEMap (const std::map< Variable, ThomEncoding< Number >> &m)
static ThomComparisonResult compare (const ThomEncoding< Number > &lhs, const ThomEncoding< Number > &rhs)
static ThomComparisonResult compareRational (const ThomEncoding< Number > &lhs, const Number &rhs)
static ThomComparisonResult compareDifferentPoly (const ThomEncoding< Number > &lhs, const ThomEncoding< Number > &rhs)
static ThomEncoding< Number > intermediatePoint (const ThomEncoding< Number > &lhs, const ThomEncoding< Number > &rhs)
static Number intermediatePoint (const ThomEncoding< Number > &lhs, const Number &rhs)
static Number intermediatePoint (const Number &lhs, const ThomEncoding< Number > &rhs)
Private Types
using Polynomial = MultivariatePolynomial< Number >
Static Private Member Functions
static bool areComparable (const ThomEncoding< Number > &lhs, const ThomEncoding< Number > &rhs)
static ThomComparisonResult compareDifferentLevels (const ThomEncoding< Number > &lhs, const ThomEncoding< Number > &rhs)
Private Attributes
SignCondition mSc
Polynomial mP
Variable mMainVar
std::shared_ptr< ThomEncoding< Number > > mPoint
std::shared_ptr< SignDetermination< Number > > mSd
uint mRelevant
Detailed Description
template<typename Number>
class carl::ThomEncoding< Number >
Definition at line 20 of file ThomEncoding.h.
Member Typedef Documentation
Polynomial
template<typename Number> using carl::ThomEncoding< Number >::Polynomial = MultivariatePolynomial<Number> private
Definition at line 22 of file ThomEncoding.h.
Constructor & Destructor Documentation
ThomEncoding() [1/3]
template<typename Number> carl::ThomEncoding< Number >::ThomEncoding (SignCondition sc, const Polynomial & p, Variable mainVar, std::shared_ptr< ThomEncoding< Number >> point, std::shared_ptr< SignDetermination< Number >> sd, uint mRelevant) inline
Definition at line 35 of file ThomEncoding.h.
ThomEncoding() [2/3]
template<typename Number> carl::ThomEncoding< Number >::ThomEncoding (const Number & n, Variable mainVar, std::shared_ptr< ThomEncoding< Number >> point = nullptr) inline
Definition at line 51 of file ThomEncoding.h.
ThomEncoding() [3/3]
template<typename Number> carl::ThomEncoding< Number >::ThomEncoding (const ThomEncoding< Number > & te, std::shared_ptr< ThomEncoding< Number >> point) inline
Definition at line 67 of file ThomEncoding.h.
Member Function Documentation
accumulatePolynomials()
template<typename Number> std::list<Polynomial> carl::ThomEncoding< Number >::accumulatePolynomials () const inline
Definition at line 116 of file ThomEncoding.h.
Referenced by carl::realRootsThom().
accumulateRelevantSigns()
template<typename Number> SignCondition carl::ThomEncoding< Number >::accumulateRelevantSigns () const inline
Definition at line 137 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::concat(), and carl::ThomEncoding< Number >::signOnPolynomial().
accumulateSigns()
template<typename Number> SignCondition carl::ThomEncoding< Number >::accumulateSigns () const inline
Definition at line 130 of file ThomEncoding.h.
accumulateVariables()
template<typename Number> std::list<Variable> carl::ThomEncoding< Number >::accumulateVariables () const inline
Definition at line 123 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::concat().
analyzeTEMap()
template<typename Number> static ThomEncoding<Number> carl::ThomEncoding< Number >::analyzeTEMap (const std::map< Variable, ThomEncoding< Number >> & m) inline static
Definition at line 256 of file ThomEncoding.h.
Referenced by carl::evaluateTE().
areComparable()
template<typename Number> static bool carl::ThomEncoding< Number >::areComparable (const ThomEncoding< Number > & lhs, const ThomEncoding< Number > & rhs) inline static private
Definition at line 368 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::compare().
compare()
template<typename Number> static ThomComparisonResult carl::ThomEncoding< Number >::compare (const ThomEncoding< Number > & lhs, const ThomEncoding< Number > & rhs) inline static
Definition at line 323 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::compareRational().
compareDifferentLevels()
template<typename Number> static ThomComparisonResult carl::ThomEncoding< Number >::compareDifferentLevels (const ThomEncoding< Number > & lhs, const ThomEncoding< Number > & rhs) inline static private
Definition at line 384 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::compare().
compareDifferentPoly()
template<typename Number> static ThomComparisonResult carl::ThomEncoding< Number >::compareDifferentPoly (const ThomEncoding< Number > & lhs, const ThomEncoding< Number > & rhs) static
Referenced by carl::ThomEncoding< Number >::compare().
compareRational()
template<typename Number> static ThomComparisonResult carl::ThomEncoding< Number >::compareRational (const ThomEncoding< Number > & lhs, const Number & rhs) inline static
Definition at line 396 of file ThomEncoding.h.
concat()
template<typename Number> ThomEncoding<Number> carl::ThomEncoding< Number >::concat (const ThomEncoding< Number > & other) const inline
Definition at line 190 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::analyzeTEMap().
dimension()
template<typename Number> uint carl::ThomEncoding< Number >::dimension () const inline
Definition at line 111 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::analyzeTEMap(), carl::ThomEncoding< Number >::concat(), carl::ThomEncoding< Number >::equals(), carl::ThomEncoding< Number >::makesPolynomialZero(), and carl::ThomEncoding< Number >::signOnPolynomial().
equals()
template<typename Number> bool carl::ThomEncoding< Number >::equals (const ThomEncoding< Number > & other) const inline
Definition at line 404 of file ThomEncoding.h.
extendSignCondition()
template<typename Number> void carl::ThomEncoding< Number >::extendSignCondition () const inline
Definition at line 172 of file ThomEncoding.h.
intermediatePoint() [1/3]
template<typename Number> static ThomEncoding<Number> carl::ThomEncoding< Number >::intermediatePoint (const ThomEncoding< Number > & lhs, const ThomEncoding< Number > & rhs) inline static
Definition at line 434 of file ThomEncoding.h.
Referenced by carl::sampleBetween().
intermediatePoint() [2/3]
template<typename Number> static Number carl::ThomEncoding< Number >::intermediatePoint (const ThomEncoding< Number > & lhs, const Number & rhs) inline static
Definition at line 468 of file ThomEncoding.h.
intermediatePoint() [3/3]
template<typename Number> static Number carl::ThomEncoding< Number >::intermediatePoint (const Number & lhs, const ThomEncoding< Number > & rhs) inline static
Definition at line 482 of file ThomEncoding.h.
isZero()
template<typename Number> bool carl::ThomEncoding< Number >::isZero () const inline
Definition at line 186 of file ThomEncoding.h.
lowestInChain()
template<typename Number> ThomEncoding<Number> carl::ThomEncoding< Number >::lowestInChain () const inline
Definition at line 106 of file ThomEncoding.h.
mainVar()
template<typename Number> Variable::Arg carl::ThomEncoding< Number >::mainVar () const inline
Definition at line 92 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulateVariables(), carl::ThomEncoding< Number >::areComparable(), carl::ThomEncoding< Number >::compare(), carl::ThomEncoding< Number >::compareRational(), and carl::ThomEncoding< Number >::ThomEncoding().
makesPolynomialZero()
template<typename Number> bool carl::ThomEncoding< Number >::makesPolynomialZero (const Polynomial & pol, Variable::Arg pol_mainVar) const inline
Definition at line 159 of file ThomEncoding.h.
operator+()
template<typename Number> ThomEncoding<Number> carl::ThomEncoding< Number >::operator+ (const Number & rhs) const inline
Definition at line 419 of file ThomEncoding.h.
point()
template<typename Number> const ThomEncoding<Number>& carl::ThomEncoding< Number >::point () const inline
Definition at line 94 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulatePolynomials(), carl::ThomEncoding< Number >::accumulateRelevantSigns(), carl::ThomEncoding< Number >::accumulateSigns(), carl::ThomEncoding< Number >::accumulateVariables(), carl::ThomEncoding< Number >::areComparable(), carl::ThomEncoding< Number >::compareDifferentLevels(), carl::ThomEncoding< Number >::dimension(), carl::ThomEncoding< Number >::equals(), and carl::ThomEncoding< Number >::ThomEncoding().
polynomial()
template<typename Number> const Polynomial& carl::ThomEncoding< Number >::polynomial () const inline
Definition at line 93 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulatePolynomials(), carl::ThomEncoding< Number >::compare(), carl::ThomEncoding< Number >::compareDifferentLevels(), carl::ThomEncoding< Number >::equals(), and carl::ThomEncoding< Number >::extendSignCondition().
print()
template<typename Number> void carl::ThomEncoding< Number >::print (std::ostream & os) const inline
Definition at line 499 of file ThomEncoding.h.
relevantDerivatives()
template<typename Number> std::list<Polynomial> carl::ThomEncoding< Number >::relevantDerivatives () const inline
Definition at line 97 of file ThomEncoding.h.
relevantSignCondition()
template<typename Number> SignCondition carl::ThomEncoding< Number >::relevantSignCondition () const inline
Definition at line 91 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulateRelevantSigns(), carl::ThomEncoding< Number >::compare(), carl::ThomEncoding< Number >::compareDifferentLevels(), carl::ThomEncoding< Number >::equals(), carl::ThomEncoding< Number >::operator+(), and carl::ThomEncoding< Number >::ThomEncoding().
sd()
template<typename Number> SignDetermination<Number> carl::ThomEncoding< Number >::sd () const inline
Definition at line 95 of file ThomEncoding.h.
sgnReprNum()
template<typename Number> Sign carl::ThomEncoding< Number >::sgnReprNum () const inline
Definition at line 182 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::isZero().
signCondition()
template<typename Number> SignCondition carl::ThomEncoding< Number >::signCondition () const inline
Definition at line 90 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulateSigns(), carl::ThomEncoding< Number >::concat(), and carl::ThomEncoding< Number >::extendSignCondition().
signOnPolynomial()
template<typename Number> Sign carl::ThomEncoding< Number >::signOnPolynomial (const Polynomial & p) const inline
Definition at line 145 of file ThomEncoding.h.
Referenced by carl::evaluateTE(), carl::ThomEncoding< Number >::extendSignCondition(), carl::ThomEncoding< Number >::makesPolynomialZero(), and carl::ThomEncoding< Number >::sgnReprNum().
Field Documentation
mMainVar
template<typename Number> Variable carl::ThomEncoding< Number >::mMainVar private
Definition at line 26 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::extendSignCondition(), carl::ThomEncoding< Number >::intermediatePoint(), carl::ThomEncoding< Number >::mainVar(), carl::ThomEncoding< Number >::makesPolynomialZero(), carl::ThomEncoding< Number >::operator+(), carl::ThomEncoding< Number >::relevantDerivatives(), carl::ThomEncoding< Number >::sgnReprNum(), and carl::ThomEncoding< Number >::ThomEncoding().
mP
template<typename Number> Polynomial carl::ThomEncoding< Number >::mP private
Definition at line 25 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::extendSignCondition(), carl::ThomEncoding< Number >::operator+(), carl::ThomEncoding< Number >::polynomial(), carl::ThomEncoding< Number >::relevantDerivatives(), and carl::ThomEncoding< Number >::ThomEncoding().
mPoint
template<typename Number> std::shared_ptr<ThomEncoding<Number> > carl::ThomEncoding< Number >::mPoint private
Definition at line 28 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulatePolynomials(), carl::ThomEncoding< Number >::accumulateRelevantSigns(), carl::ThomEncoding< Number >::accumulateSigns(), carl::ThomEncoding< Number >::accumulateVariables(), carl::ThomEncoding< Number >::areComparable(), carl::ThomEncoding< Number >::compare(), carl::ThomEncoding< Number >::compareDifferentLevels(), carl::ThomEncoding< Number >::compareRational(), carl::ThomEncoding< Number >::concat(), carl::ThomEncoding< Number >::dimension(), carl::ThomEncoding< Number >::equals(), carl::ThomEncoding< Number >::lowestInChain(), carl::ThomEncoding< Number >::operator+(), carl::ThomEncoding< Number >::point(), and carl::ThomEncoding< Number >::ThomEncoding().
mRelevant
template<typename Number> uint carl::ThomEncoding< Number >::mRelevant private
Definition at line 31 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::relevantDerivatives(), carl::ThomEncoding< Number >::relevantSignCondition(), and carl::ThomEncoding< Number >::ThomEncoding().
mSc
template<typename Number> SignCondition carl::ThomEncoding< Number >::mSc mutable private
Definition at line 24 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::accumulateSigns(), carl::ThomEncoding< Number >::extendSignCondition(), carl::ThomEncoding< Number >::relevantSignCondition(), carl::ThomEncoding< Number >::signCondition(), and carl::ThomEncoding< Number >::ThomEncoding().
mSd
template<typename Number> std::shared_ptr<SignDetermination<Number> > carl::ThomEncoding< Number >::mSd mutable private
Definition at line 29 of file ThomEncoding.h.
Referenced by carl::ThomEncoding< Number >::sd(), carl::ThomEncoding< Number >::signOnPolynomial(), and carl::ThomEncoding< Number >::ThomEncoding().
The documentation for this class was generated from the following file:
carl/thom/ThomEncoding.h