carl: carl::UFInstanceContent Class Reference
carl::UFInstanceContent Class Reference
The actual content of an uninterpreted function instance.
#include <UFInstanceManager.h>
Public Member Functions
const UninterpretedFunction & uninterpretedFunction () const
const std::vector< UVariable > & args () const
bool operator== (const UFInstanceContent &_ufic) const
bool operator< (const UFInstanceContent &_ufic) const
Private Member Functions
UFInstanceContent ()
UFInstanceContent (const UninterpretedFunction &_uf, std::vector< UVariable > &&_args)
Constructs the content of an uninterpreted function instance.
UFInstanceContent (const UninterpretedFunction &_uf, const std::vector< UVariable > &_args)
Constructs the content of an uninterpreted function instance.
UFInstanceContent (const UFInstanceContent &)
Private Attributes
UninterpretedFunction mUninterpretedFunction
The underlying uninterpreted function of theinstance.
std::vector< UVariable > mArgs
The uninterpreted function instance's arguments.
Friends
class UFInstanceManager
Detailed Description
The actual content of an uninterpreted function instance.
Definition at line 34 of file UFInstanceManager.h.
Constructor & Destructor Documentation
UFInstanceContent() [1/4]
carl::UFInstanceContent::UFInstanceContent () private
UFInstanceContent() [2/4]
carl::UFInstanceContent::UFInstanceContent (const UninterpretedFunction & _uf, std::vector< UVariable > && _args) inline explicit private
Constructs the content of an uninterpreted function instance.
Parameters
_uf The underlying function of the uninterpreted function instance to construct.
_args The arguments of the uninterpreted function instance to construct.
Definition at line 51 of file UFInstanceManager.h.
UFInstanceContent() [3/4]
carl::UFInstanceContent::UFInstanceContent (const UninterpretedFunction & _uf, const std::vector< UVariable > & _args) inline explicit private
Constructs the content of an uninterpreted function instance.
Parameters
_uf The underlying function of the uninterpreted function instance to construct.
_args The arguments of the uninterpreted function instance to construct.
Definition at line 61 of file UFInstanceManager.h.
UFInstanceContent() [4/4]
carl::UFInstanceContent::UFInstanceContent (const UFInstanceContent &) private
Member Function Documentation
args()
const std::vector<UVariable>& carl::UFInstanceContent::args () const inline
Returns
The arguments of the uninterpreted function instance.
Definition at line 81 of file UFInstanceManager.h.
Referenced by carl::UFInstanceManager::argsCorrect(), std::hash< carl::UFInstanceContent >::operator()(), operator<(), and operator==().
operator<()
bool carl::UFInstanceContent::operator< (const UFInstanceContent & _ufic) const inline
Parameters
_ufic The uninterpreted function instance's content to compare with.
Returns
true, if this uninterpreted function instance's content is less than the given one.
Definition at line 99 of file UFInstanceManager.h.
operator==()
bool carl::UFInstanceContent::operator== (const UFInstanceContent & _ufic) const inline
Parameters
_ufic The uninterpreted function instance's content to compare with.
Returns
true, if this uninterpreted function instance's content is less than the given one.
Definition at line 90 of file UFInstanceManager.h.
uninterpretedFunction()
const UninterpretedFunction& carl::UFInstanceContent::uninterpretedFunction () const inline
Returns
The underlying function of the uninterpreted function instance
Definition at line 73 of file UFInstanceManager.h.
Referenced by carl::UFInstanceManager::argsCorrect(), std::hash< carl::UFInstanceContent >::operator()(), operator<(), and operator==().
Friends And Related Function Documentation
UFInstanceManager
friend class UFInstanceManager friend
Definition at line 36 of file UFInstanceManager.h.
Field Documentation
mArgs
std::vector<UVariable> carl::UFInstanceContent::mArgs private
The uninterpreted function instance's arguments.
Definition at line 42 of file UFInstanceManager.h.
Referenced by args(), operator<(), and operator==().
mUninterpretedFunction
UninterpretedFunction carl::UFInstanceContent::mUninterpretedFunction private
The underlying uninterpreted function of theinstance.
Definition at line 40 of file UFInstanceManager.h.
Referenced by operator<(), operator==(), and uninterpretedFunction().
The documentation for this class was generated from the following file:
carl/formula/uninterpreted/UFInstanceManager.h