carl: carl::VariableAssignment< Poly > Class Template Reference
carl::VariableAssignment< Poly > Class Template Reference
#include <VariableAssignment.h>
Public Types
using Number = typename Base::Number
using MR = typename Base::MR
using RAN = typename Base::RAN
Public Member Functions
VariableAssignment (Variable::Arg v, const RAN &value, bool negated=false)
VariableAssignment (Variable::Arg v, const Number &value, bool negated=false)
Variable var () const
const RAN & value () const
bool negated () const
VariableAssignment negation () const
operator const VariableComparison< Poly > & () const
void collectVariables (Variables &vars) const
std::string toString (unsigned=0, bool=false, bool=true) const
Private Types
using Base = VariableComparison< Poly >
Private Attributes
Base mComparison
Detailed Description
template<typename Poly>
class carl::VariableAssignment< Poly >
Definition at line 10 of file VariableAssignment.h.
Member Typedef Documentation
Base
template<typename Poly> using carl::VariableAssignment< Poly >::Base = VariableComparison<Poly> private
Definition at line 12 of file VariableAssignment.h.
MR
template<typename Poly> using carl::VariableAssignment< Poly >::MR = typename Base::MR
Definition at line 15 of file VariableAssignment.h.
Number
template<typename Poly> using carl::VariableAssignment< Poly >::Number = typename Base::Number
Definition at line 14 of file VariableAssignment.h.
RAN
template<typename Poly> using carl::VariableAssignment< Poly >::RAN = typename Base::RAN
Definition at line 16 of file VariableAssignment.h.
Constructor & Destructor Documentation
VariableAssignment() [1/2]
template<typename Poly> carl::VariableAssignment< Poly >::VariableAssignment (Variable::Arg v, const RAN & value, bool negated = false) inline
Definition at line 20 of file VariableAssignment.h.
Referenced by carl::VariableAssignment< Pol >::negation().
VariableAssignment() [2/2]
template<typename Poly> carl::VariableAssignment< Poly >::VariableAssignment (Variable::Arg v, const Number & value, bool negated = false) inline
Definition at line 21 of file VariableAssignment.h.
Member Function Documentation
collectVariables()
template<typename Poly> void carl::VariableAssignment< Poly >::collectVariables (Variables & vars) const inline
Definition at line 40 of file VariableAssignment.h.
negated()
template<typename Poly> bool carl::VariableAssignment< Poly >::negated () const inline
Definition at line 31 of file VariableAssignment.h.
Referenced by carl::VariableAssignment< Pol >::negation(), and carl::VariableAssignment< Pol >::toString().
negation()
template<typename Poly> VariableAssignment carl::VariableAssignment< Poly >::negation () const inline
Definition at line 34 of file VariableAssignment.h.
Referenced by carl::FormulaPool< Pol >::createNegatedContent(), and carl::FormulaPool< Pol >::isBaseFormula().
operator const VariableComparison< Poly > &()
template<typename Poly> carl::VariableAssignment< Poly >::operator const VariableComparison< Poly > & () const inline
Definition at line 37 of file VariableAssignment.h.
toString()
template<typename Poly> std::string carl::VariableAssignment< Poly >::toString (unsigned = 0, bool = false, bool = true) const inline
Definition at line 44 of file VariableAssignment.h.
value()
template<typename Poly> const RAN& carl::VariableAssignment< Poly >::value () const inline
Definition at line 26 of file VariableAssignment.h.
Referenced by carl::VariableAssignment< Pol >::negation(), and carl::VariableAssignment< Pol >::toString().
var()
template<typename Poly> Variable carl::VariableAssignment< Poly >::var () const inline
Definition at line 23 of file VariableAssignment.h.
Referenced by carl::VariableAssignment< Pol >::negation(), and carl::VariableAssignment< Pol >::toString().
Field Documentation
mComparison
template<typename Poly> Base carl::VariableAssignment< Poly >::mComparison private
Definition at line 18 of file VariableAssignment.h.
Referenced by carl::VariableAssignment< Pol >::collectVariables(), carl::VariableAssignment< Pol >::negated(), carl::VariableAssignment< Poly >::operator const VariableComparison< Poly > &(), carl::VariableAssignment< Pol >::value(), and carl::VariableAssignment< Pol >::var().
The documentation for this class was generated from the following file:
carl/formula/VariableAssignment.h