carl: carl::carlVariables Class Reference
carl::carlVariables Class Reference
#include <Variables.h>
Public Member Functions
carlVariables ()=default
carlVariables (std::initializer_list< VariableVariant > i)
template<typename Iterator >
carlVariables (const Iterator &b, const Iterator &e)
template<typename Iterator , typename F >
carlVariables (const Iterator &b, const Iterator &e, F &&f)
auto begin () const
auto end () const
auto begin ()
auto end ()
bool empty () const
std::size_t size () const
bool has (Variable var) const
void add (VariableVariant v)
void add (std::initializer_list< VariableVariant > i)
template<typename Iterator >
void add (const Iterator &b, const Iterator &e)
template<typename Iterator , typename F >
void add (const Iterator &b, const Iterator &e, F &&f)
void erase (VariableVariant v)
template<typename F >
carlVariables filter (F &&f) const
std::vector< Variable > underlyingVariables () const
std::set< Variable > underlyingVariableSet () const
template<typename T >
auto filter_type () const
auto filter_type (VariableType vt) const
auto boolean () const
auto integer () const
auto real () const
auto bitvector () const
auto uninterpreted () const
Private Member Functions
void compact (bool force=false) const
Private Attributes
std::vector< VariableVariant > mVariables
std::size_t mAddedSinceCompact = 0
Friends
bool operator== (const carlVariables &lhs, const carlVariables &rhs)
std::ostream & operator<< (std::ostream &os, const carlVariables &vars)
Detailed Description
Definition at line 22 of file Variables.h.
Constructor & Destructor Documentation
carlVariables() [1/4]
carl::carlVariables::carlVariables () default
Referenced by compact().
carlVariables() [2/4]
carl::carlVariables::carlVariables (std::initializer_list< VariableVariant > i) inline explicit
Definition at line 39 of file Variables.h.
carlVariables() [3/4]
template<typename Iterator > carl::carlVariables::carlVariables (const Iterator & b, const Iterator & e) inline explicit
Definition at line 43 of file Variables.h.
carlVariables() [4/4]
template<typename Iterator , typename F > carl::carlVariables::carlVariables (const Iterator & b, const Iterator & e, F && f) inline
Definition at line 47 of file Variables.h.
Member Function Documentation
add() [1/4]
void carl::carlVariables::add (VariableVariant v) inline
Definition at line 85 of file Variables.h.
Referenced by add(), carlVariables(), carl::UTerm::gatherVariables(), carl::VariableComparison< Pol >::gatherVariables(), carl::BVTermContent::gatherVariables(), carl::Constraint< Poly >::gatherVariables(), carl::Monomial::gatherVariables(), and carl::variables().
add() [2/4]
void carl::carlVariables::add (std::initializer_list< VariableVariant > i) inline
Definition at line 90 of file Variables.h.
add() [3/4]
template<typename Iterator > void carl::carlVariables::add (const Iterator & b, const Iterator & e) inline
Definition at line 96 of file Variables.h.
add() [4/4]
template<typename Iterator , typename F > void carl::carlVariables::add (const Iterator & b, const Iterator & e, F && f) inline
Definition at line 102 of file Variables.h.
begin() [1/2]
auto carl::carlVariables::begin () const inline
Definition at line 51 of file Variables.h.
Referenced by filter(), has(), underlyingVariables(), and underlyingVariableSet().
begin() [2/2]
auto carl::carlVariables::begin () inline
Definition at line 58 of file Variables.h.
bitvector()
auto carl::carlVariables::bitvector () const inline
Definition at line 161 of file Variables.h.
boolean()
auto carl::carlVariables::boolean () const inline
Definition at line 152 of file Variables.h.
compact()
void carl::carlVariables::compact (bool force = false) const inline private
Definition at line 30 of file Variables.h.
Referenced by add(), begin(), carl::operator==(), size(), underlyingVariables(), and underlyingVariableSet().
empty()
bool carl::carlVariables::empty () const inline
Definition at line 66 of file Variables.h.
end() [1/2]
auto carl::carlVariables::end () const inline
Definition at line 55 of file Variables.h.
Referenced by add(), filter(), has(), underlyingVariables(), and underlyingVariableSet().
end() [2/2]
auto carl::carlVariables::end () inline
Definition at line 62 of file Variables.h.
erase()
void carl::carlVariables::erase (VariableVariant v) inline
Definition at line 108 of file Variables.h.
Referenced by carl::MultivariateRoot< Poly >::gatherVariables(), and carl::variables().
filter()
template<typename F > carlVariables carl::carlVariables::filter (F && f) const inline
Definition at line 113 of file Variables.h.
Referenced by filter_type().
filter_type() [1/2]
template<typename T > auto carl::carlVariables::filter_type () const inline
Definition at line 141 of file Variables.h.
Referenced by boolean(), integer(), and real().
filter_type() [2/2]
auto carl::carlVariables::filter_type (VariableType vt) const inline
Definition at line 146 of file Variables.h.
has()
bool carl::carlVariables::has (Variable var) const inline
Definition at line 73 of file Variables.h.
integer()
auto carl::carlVariables::integer () const inline
Definition at line 155 of file Variables.h.
Referenced by carl::ConstraintContent< Poly >::hasIntegerValuedVariable().
real()
auto carl::carlVariables::real () const inline
Definition at line 158 of file Variables.h.
Referenced by carl::ConstraintContent< Poly >::hasRealValuedVariable().
size()
std::size_t carl::carlVariables::size () const inline
Definition at line 69 of file Variables.h.
underlyingVariables()
std::vector<Variable> carl::carlVariables::underlyingVariables () const inline
Definition at line 118 of file Variables.h.
Referenced by carl::contractor::Evaluation< carl::Polynomial >::Evaluation(), carl::ConstraintContent< Poly >::maxDegree(), and carl::Formula< Poly >::variables().
underlyingVariableSet()
std::set<Variable> carl::carlVariables::underlyingVariableSet () const inline
Definition at line 127 of file Variables.h.
uninterpreted()
auto carl::carlVariables::uninterpreted () const inline
Definition at line 164 of file Variables.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const carlVariables & vars) friend
Definition at line 180 of file Variables.h.
operator==
bool operator== (const carlVariables & lhs, const carlVariables & rhs) friend
Definition at line 175 of file Variables.h.
Field Documentation
mAddedSinceCompact
std::size_t carl::carlVariables::mAddedSinceCompact = 0 mutable private
Definition at line 28 of file Variables.h.
Referenced by add().
mVariables
std::vector<VariableVariant> carl::carlVariables::mVariables mutable private
Definition at line 27 of file Variables.h.
Referenced by filter(), carl::operator<<(), and carl::operator==().
The documentation for this class was generated from the following file:
carl/core/Variables.h