carl: carl::RealAlgebraicNumberNR< Number > Class Template Reference
carl::RealAlgebraicNumberNR< Number > Class Template Reference
RealAlgebraicNumberNR is a specialization of RealAlgebraicNumber.
#include <RealAlgebraicNumberNR.h>
Public Member Functions
virtual std::shared_ptr
< RealAlgebraicNumber< Number > > clone () const
bool equal (const RealAlgebraicNumberNR< Number > *n)
bool less (const RealAlgebraicNumberNR< Number > *n)
bool isRoot () const
void setIsRoot (bool isRoot)
Set the flag marking whether the real algebraic number stems from a root computation or not.
bool isZero () const
bool isNumeric () const
bool isIntegral () const
Number branchingPoint () const
const Number & value () const
std::size_t getRefinementCount () const
const Interval< Number > & getInterval () const
const Number & lower () const
const Number & upper () const
const Polynomial & getPolynomial () const
Sign sgn () const
Sign sgn (const Polynomial &p) const
bool isRootOf (const UnivariatePolynomial< Number > &p) const
bool containedIn (const Interval< Number > &i) const
bool refineAvoiding (const Number &n) const
void refine (RealAlgebraicNumberSettings::RefinementStrategy strategy=RealAlgebraicNumberSettings::RefinementStrategy::DEFAULT) const
bool equal (const RealAlgebraicNumber< Number > &n) const
bool less (const RealAlgebraicNumber< Number > &n) const
std::pair< bool, bool > checkOrder (const RealAlgebraicNumber< Number > &n) const
bool lessWhileUnequal (const RealAlgebraicNumber< Number > &n) const
Static Public Member Functions
static std::shared_ptr
< RealAlgebraicNumber< Number > > create (const Number &n, bool isRoot=true)
Private Member Functions
std::shared_ptr
< RealAlgebraicNumberNR > thisPtr () const
RealAlgebraicNumberNR (const Number &n, bool isRoot=true)
Construct a real algebraic number from a numeric n.
Private Attributes
std::weak_ptr
< RealAlgebraicNumberNR > pThis
Friends
template<typename Num >
std::ostream & operator<< (std::ostream &os, const RealAlgebraicNumberNR< Num > *n)
Detailed Description
template<typename Number>
class carl::RealAlgebraicNumberNR< Number >
RealAlgebraicNumberNR is a specialization of RealAlgebraicNumber.
RealAlgebraicNumberNR always represents an exact number.
Todo:
Add EnableIf<is_fraction<Number>> such that gcc does not crash.
Definition at line 18 of file RealAlgebraicNumberNR.h.
Constructor & Destructor Documentation
template<typename Number > carl::RealAlgebraicNumberNR< Number >::RealAlgebraicNumberNR (const Number & n, bool isRoot = true) inline private
Construct a real algebraic number from a numeric n.
Parameters
n
isRoot true marks this real algebraic number to stem from a root computation
Definition at line 30 of file RealAlgebraicNumberNR.h.
Member Function Documentation
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isRoot () const inline inherited
Returns
the flag marking whether the real algebraic number stems from a root computation or not
Definition at line 130 of file NewRealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumberIR< Number >::clone(), carl::cad::SampleSet< Number >::SampleComparator::compareRoot(), carl::cad::SampleSet< Number >::insert(), carl::cad::SampleSet< Number >::SampleComparator::isOptimal(), carl::RealAlgebraicNumber< carl::Number >::setIsRoot(), and carl::CAD< Number >::storeSampleInTree().
template<typename Number> void carl::RealAlgebraicNumber< Number >::setIsRoot (bool isRoot) inline inherited
Set the flag marking whether the real algebraic number stems from a root computation or not.
Parameters
isRoot
Definition at line 138 of file NewRealAlgebraicNumber.h.
The documentation for this class was generated from the following file:
carl/core/RealAlgebraicNumberNR.h