carl: carl::checkpointverifier::CheckpointVector Class Reference
carl::checkpointverifier::CheckpointVector Class Reference
#include <CheckpointVerifier.h>
Public Member Functions
CheckpointVector ()
const std::string & description () const
bool forced () const
template<typename T >
const T & data () const
template<typename T >
const T * try_data () const
bool valid () const
void next ()
template<typename... Args>
void add (const std::string &description, bool forced, Args &&... args)
void clear ()
Data Fields
bool mayExceed = true
bool printDebug = true
Private Types
template<typename... Args>
using Tuple = std::tuple< std::decay_t< Args >... >
using Checkpoint = std::tuple< std::string, bool, std::any >
Private Member Functions
const Checkpoint & cur () const
Private Attributes
std::vector< Checkpoint > mData
std::size_t mCurrent = 0
Detailed Description
Definition at line 18 of file CheckpointVerifier.h.
Member Typedef Documentation
Checkpoint
using carl::checkpointverifier::CheckpointVector::Checkpoint = std::tuple<std::string,bool,std::any> private
Definition at line 21 of file CheckpointVerifier.h.
Tuple
template<typename... Args> using carl::checkpointverifier::CheckpointVector::Tuple = std::tuple<std::decay_t<Args>...> private
Definition at line 20 of file CheckpointVerifier.h.
Constructor & Destructor Documentation
CheckpointVector()
carl::checkpointverifier::CheckpointVector::CheckpointVector () inline
Definition at line 31 of file CheckpointVerifier.h.
Member Function Documentation
add()
template<typename... Args> void carl::checkpointverifier::CheckpointVector::add (const std::string & description, bool forced, Args &&... args) inline
Definition at line 56 of file CheckpointVerifier.h.
clear()
void carl::checkpointverifier::CheckpointVector::clear () inline
Definition at line 59 of file CheckpointVerifier.h.
cur()
const Checkpoint& carl::checkpointverifier::CheckpointVector::cur () const inline private
Definition at line 26 of file CheckpointVerifier.h.
Referenced by data(), description(), forced(), and try_data().
data()
template<typename T > const T& carl::checkpointverifier::CheckpointVector::data () const inline
Definition at line 41 of file CheckpointVerifier.h.
description()
const std::string& carl::checkpointverifier::CheckpointVector::description () const inline
Definition at line 34 of file CheckpointVerifier.h.
Referenced by carl::CheckpointVerifier::check().
forced()
bool carl::checkpointverifier::CheckpointVector::forced () const inline
Definition at line 37 of file CheckpointVerifier.h.
next()
void carl::checkpointverifier::CheckpointVector::next () inline
Definition at line 51 of file CheckpointVerifier.h.
try_data()
template<typename T > const T* carl::checkpointverifier::CheckpointVector::try_data () const inline
Definition at line 45 of file CheckpointVerifier.h.
valid()
bool carl::checkpointverifier::CheckpointVector::valid () const inline
Definition at line 48 of file CheckpointVerifier.h.
Referenced by carl::CheckpointVerifier::check(), and cur().
Field Documentation
mayExceed
bool carl::checkpointverifier::CheckpointVector::mayExceed = true
Definition at line 64 of file CheckpointVerifier.h.
mCurrent
std::size_t carl::checkpointverifier::CheckpointVector::mCurrent = 0 private
Definition at line 24 of file CheckpointVerifier.h.
Referenced by cur(), and valid().
mData
std::vector<Checkpoint> carl::checkpointverifier::CheckpointVector::mData private
Definition at line 23 of file CheckpointVerifier.h.
printDebug
bool carl::checkpointverifier::CheckpointVector::printDebug = true
Definition at line 65 of file CheckpointVerifier.h.
Referenced by carl::CheckpointVerifier::check(), and carl::CheckpointVerifier::expect().
The documentation for this class was generated from the following file:
carl/util/CheckpointVerifier.h