carl: carl::contractor::Contraction< Polynomial > Class Template Reference
carl::contractor::Contraction< Polynomial > Class Template Reference
Represents a contraction operation of the form.
#include <Contractor.h>
Public Member Functions
template<typename Number >
void normalize (std::vector< Interval< Number >> &intervals) const
Contraction (const Polynomial &p, Variable v)
auto var () const
const auto & numerator () const
const auto & denominator () const
auto root () const
template<typename Number >
std::vector< Interval< Number > > evaluate (const std::map< Variable, Interval< Number >> &assignment) const
Evaluate this contraction over the given assignment.
Private Member Functions
bool make_integer () const
template<typename Number >
void add_root (const Interval< Number > &i, std::vector< Interval< Number >> &result) const
Private Attributes
Variable mVar
Polynomial mNumerator
Polynomial mDenominator
std::size_t mRoot
Detailed Description
template<typename Polynomial>
class carl::contractor::Contraction< Polynomial >
Represents a contraction operation of the form.
mRoot'th root of (mNumerator / mDenominator)
Definition at line 20 of file Contractor.h.
Constructor & Destructor Documentation
Contraction()
template<typename Polynomial > carl::contractor::Contraction< Polynomial >::Contraction (const Polynomial & p, Variable v) inline
Definition at line 89 of file Contractor.h.
Member Function Documentation
add_root()
template<typename Polynomial > template<typename Number > void carl::contractor::Contraction< Polynomial >::add_root (const Interval< Number > & i, std::vector< Interval< Number >> & result) const inline private
Definition at line 32 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::evaluate().
denominator()
template<typename Polynomial > const auto& carl::contractor::Contraction< Polynomial >::denominator () const inline
Definition at line 114 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::evaluate().
evaluate()
template<typename Polynomial > template<typename Number > std::vector<Interval<Number> > carl::contractor::Contraction< Polynomial >::evaluate (const std::map< Variable, Interval< Number >> & assignment) const inline
Evaluate this contraction over the given assignment.
Returns a list of resulting intervals.
Definition at line 126 of file Contractor.h.
make_integer()
template<typename Polynomial > bool carl::contractor::Contraction< Polynomial >::make_integer () const inline private
Definition at line 27 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::add_root().
normalize()
template<typename Polynomial > template<typename Number > void carl::contractor::Contraction< Polynomial >::normalize (std::vector< Interval< Number >> & intervals) const inline
Definition at line 66 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::evaluate().
numerator()
template<typename Polynomial > const auto& carl::contractor::Contraction< Polynomial >::numerator () const inline
Definition at line 111 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::evaluate().
root()
template<typename Polynomial > auto carl::contractor::Contraction< Polynomial >::root () const inline
Definition at line 117 of file Contractor.h.
var()
template<typename Polynomial > auto carl::contractor::Contraction< Polynomial >::var () const inline
Definition at line 108 of file Contractor.h.
Field Documentation
mDenominator
template<typename Polynomial > Polynomial carl::contractor::Contraction< Polynomial >::mDenominator private
Definition at line 24 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::Contraction(), and carl::contractor::Contraction< Polynomial >::denominator().
mNumerator
template<typename Polynomial > Polynomial carl::contractor::Contraction< Polynomial >::mNumerator private
Definition at line 23 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::Contraction(), and carl::contractor::Contraction< Polynomial >::numerator().
mRoot
template<typename Polynomial > std::size_t carl::contractor::Contraction< Polynomial >::mRoot private
Definition at line 25 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::add_root(), carl::contractor::Contraction< Polynomial >::Contraction(), and carl::contractor::Contraction< Polynomial >::root().
mVar
template<typename Polynomial > Variable carl::contractor::Contraction< Polynomial >::mVar private
Definition at line 22 of file Contractor.h.
Referenced by carl::contractor::Contraction< Polynomial >::make_integer(), and carl::contractor::Contraction< Polynomial >::var().
The documentation for this class was generated from the following file:
carl/interval/Contractor.h