carl: carl::GroebnerBase< Number > Class Template Reference
carl::GroebnerBase< Number > Class Template Reference
#include <GroebnerBase.h>
Public Types
using Monomial = Term< Number >
Public Member Functions
GroebnerBase ()
template<typename InputIt >
GroebnerBase (InputIt first, InputIt last)
Polynomial reduce (const Polynomial &p) const
const std::vector< Polynomial > & get () const
bool isTrivialBase () const
bool hasFiniteMon () const
std::vector< Monomial > cor () const
std::vector< Monomial > mon () const
std::vector< Monomial > bor () const
std::set< Variable > gatherVariables () const
Private Types
using Polynomial = MultivariatePolynomial< Number >
Private Attributes
std::shared_ptr< Ideal< Polynomial > > mBase
Detailed Description
template<typename Number>
class carl::GroebnerBase< Number >
Definition at line 21 of file GroebnerBase.h.
Member Typedef Documentation
Monomial
template<typename Number> using carl::GroebnerBase< Number >::Monomial = Term<Number>
Definition at line 24 of file GroebnerBase.h.
Polynomial
template<typename Number> using carl::GroebnerBase< Number >::Polynomial = MultivariatePolynomial<Number> private
Definition at line 27 of file GroebnerBase.h.
Constructor & Destructor Documentation
GroebnerBase() [1/2]
template<typename Number> carl::GroebnerBase< Number >::GroebnerBase () inline
Definition at line 32 of file GroebnerBase.h.
GroebnerBase() [2/2]
template<typename Number> template<typename InputIt > carl::GroebnerBase< Number >::GroebnerBase (InputIt first, InputIt last) inline
Definition at line 35 of file GroebnerBase.h.
Member Function Documentation
bor()
template<typename Number> std::vector<Monomial> carl::GroebnerBase< Number >::bor () const
Referenced by carl::MultiplicationTable< carl::Number >::init().
cor()
template<typename Number> std::vector<Monomial> carl::GroebnerBase< Number >::cor () const
Referenced by carl::MultiplicationTable< carl::Number >::init().
gatherVariables()
template<typename Number> std::set<Variable> carl::GroebnerBase< Number >::gatherVariables () const
Referenced by carl::MultiplicationTable< carl::Number >::init().
get()
template<typename Number> const std::vector<Polynomial>& carl::GroebnerBase< Number >::get () const inline
Definition at line 51 of file GroebnerBase.h.
Referenced by carl::MultiplicationTable< carl::Number >::init().
hasFiniteMon()
template<typename Number> bool carl::GroebnerBase< Number >::hasFiniteMon () const
Referenced by carl::MultiplicationTable< carl::Number >::MultiplicationTable(), and carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
isTrivialBase()
template<typename Number> bool carl::GroebnerBase< Number >::isTrivialBase () const inline
Definition at line 56 of file GroebnerBase.h.
Referenced by carl::TarskiQueryManager< carl::Number >::TarskiQueryManager().
mon()
template<typename Number> std::vector<Monomial> carl::GroebnerBase< Number >::mon () const
Referenced by carl::MultiplicationTable< carl::Number >::init().
reduce()
template<typename Number> Polynomial carl::GroebnerBase< Number >::reduce (const Polynomial & p) const inline
Definition at line 46 of file GroebnerBase.h.
Field Documentation
mBase
template<typename Number> std::shared_ptr<Ideal<Polynomial> > carl::GroebnerBase< Number >::mBase private
Definition at line 29 of file GroebnerBase.h.
Referenced by carl::GroebnerBase< carl::Number >::get(), carl::GroebnerBase< carl::Number >::GroebnerBase(), and carl::GroebnerBase< carl::Number >::reduce().
The documentation for this class was generated from the following file:
carl/thom/TarskiQuery/GroebnerBase.h