carl: carl::Numeric< T > Class Template Reference
carl::Numeric< T > Class Template Reference
#include <Numeric.h>
Public Member Functions
Numeric ()=default
Default constructor.
Numeric (const T &)
Numeric (ContentType, bool=false)
Numeric (const Numeric< T > &)
~Numeric ()
ContentType content () const
Numeric< T > & operator= (const T &)
Numeric< T > & operator= (ContentType)
Numeric< T > & operator= (const Numeric< T > &)
bool operator== (const Numeric< T > &) const
bool operator!= (const Numeric< T > &) const
bool operator< (const Numeric< T > &) const
bool operator<= (const Numeric< T > &) const
bool operator> (const Numeric< T > &) const
bool operator>= (const Numeric< T > &) const
T toRational () const
operator T () const
operator typename IntegralType< T >::type () const
Static Public Member Functions
static ContentType allocate (const T &)
static ContentType allocate (ContentType)
static void gcd_ (ContentType &, ContentType)
static bool withinNativeRange (const T &t)
Static Public Attributes
static std::vector< T > mRationalPool
static std::vector< ContentType > mFreeRationalIds
Private Member Functions
const T & rational () const
T & rRational ()
void maybeRationalize ()
void maybeRationalize (const T &_rat)
void maybeIntegralize ()
void maybeIntegralize (const T &_rat)
Private Attributes
ContentType mContent = 0
Friends
template<typename T1 >
Numeric< T1 > & div_assign (Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & gcd_assign (Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & operator+= (Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & operator-= (Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & operator*= (Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & operator/= (Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & operator++ (Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > & operator-- (Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > operator- (const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > div (const Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > abs (const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > lcm (const Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
Numeric< T1 > gcd (const Numeric< T1 > &, const Numeric< T1 > &)
template<typename T1 >
std::ostream & operator<< (std::ostream &, const Numeric< T1 > &)
Detailed Description
template<typename T>
class carl::Numeric< T >
Definition at line 25 of file Numeric.h.
Constructor & Destructor Documentation
Numeric() [1/4]
template<typename T> carl::Numeric< T >::Numeric () default
Default constructor.
Numeric() [2/4]
template<typename T> carl::Numeric< T >::Numeric (const T &)
Numeric() [3/4]
template<typename T> carl::Numeric< T >::Numeric (ContentType , bool = false)
Numeric() [4/4]
template<typename T> carl::Numeric< T >::Numeric (const Numeric< T > &)
~Numeric()
template<typename T> carl::Numeric< T >::~Numeric ()
Member Function Documentation
allocate() [1/2]
template<typename T> static ContentType carl::Numeric< T >::allocate (const T &) static
Referenced by carl::Numeric< T >::maybeRationalize().
allocate() [2/2]
template<typename T> static ContentType carl::Numeric< T >::allocate (ContentType) static
content()
template<typename T> ContentType carl::Numeric< T >::content () const inline
Definition at line 47 of file Numeric.h.
Referenced by carl::isInteger().
gcd_()
template<typename T> static void carl::Numeric< T >::gcd_ (ContentType & , ContentType) static
maybeIntegralize() [1/2]
template<typename T> void carl::Numeric< T >::maybeIntegralize () inline private
Definition at line 164 of file Numeric.h.
maybeIntegralize() [2/2]
template<typename T> void carl::Numeric< T >::maybeIntegralize (const T & _rat) inline private
Definition at line 174 of file Numeric.h.
maybeRationalize() [1/2]
template<typename T> void carl::Numeric< T >::maybeRationalize () inline private
Definition at line 146 of file Numeric.h.
maybeRationalize() [2/2]
template<typename T> void carl::Numeric< T >::maybeRationalize (const T & _rat) inline private
Definition at line 152 of file Numeric.h.
operator T()
template<typename T> carl::Numeric< T >::operator T () const inline
Definition at line 111 of file Numeric.h.
operator typename IntegralType< T >::type()
template<typename T> carl::Numeric< T >::operator typename IntegralType< T >::type () const inline explicit
Definition at line 116 of file Numeric.h.
operator!=()
template<typename T> bool carl::Numeric< T >::operator!= (const Numeric< T > &) const
operator<()
template<typename T> bool carl::Numeric< T >::operator< (const Numeric< T > &) const
operator<=()
template<typename T> bool carl::Numeric< T >::operator<= (const Numeric< T > &) const
operator=() [1/3]
template<typename T> Numeric<T>& carl::Numeric< T >::operator= (const T &)
operator=() [2/3]
template<typename T> Numeric<T>& carl::Numeric< T >::operator= (ContentType)
operator=() [3/3]
template<typename T> Numeric<T>& carl::Numeric< T >::operator= (const Numeric< T > &)
operator==()
template<typename T> bool carl::Numeric< T >::operator== (const Numeric< T > &) const
operator>()
template<typename T> bool carl::Numeric< T >::operator> (const Numeric< T > &) const
operator>=()
template<typename T> bool carl::Numeric< T >::operator>= (const Numeric< T > &) const
rational()
template<typename T> const T& carl::Numeric< T >::rational () const inline private
Definition at line 134 of file Numeric.h.
Referenced by carl::Numeric< T >::maybeIntegralize().
rRational()
template<typename T> T& carl::Numeric< T >::rRational () inline private
Definition at line 140 of file Numeric.h.
Referenced by carl::Numeric< T >::maybeIntegralize().
toRational()
template<typename T> T carl::Numeric< T >::toRational () const inline
Definition at line 103 of file Numeric.h.
Referenced by carl::Numeric< T >::operator T().
withinNativeRange()
template<typename T> static bool carl::Numeric< T >::withinNativeRange (const T & t) inline static
Definition at line 128 of file Numeric.h.
Referenced by carl::Numeric< T >::maybeIntegralize(), and carl::Numeric< T >::maybeRationalize().
Friends And Related Function Documentation
abs
template<typename T> template<typename T1 > Numeric<T1> abs (const Numeric< T1 > &) friend
div
template<typename T> template<typename T1 > Numeric<T1> div (const Numeric< T1 > & , const Numeric< T1 > &) friend
div_assign
template<typename T> template<typename T1 > Numeric<T1>& div_assign (Numeric< T1 > & , const Numeric< T1 > &) friend
gcd
template<typename T> template<typename T1 > Numeric<T1> gcd (const Numeric< T1 > & , const Numeric< T1 > &) friend
gcd_assign
template<typename T> template<typename T1 > Numeric<T1>& gcd_assign (Numeric< T1 > & , const Numeric< T1 > &) friend
lcm
template<typename T> template<typename T1 > Numeric<T1> lcm (const Numeric< T1 > & , const Numeric< T1 > &) friend
operator*=
template<typename T> template<typename T1 > Numeric<T1>& operator*= (Numeric< T1 > & , const Numeric< T1 > &) friend
operator++
template<typename T> template<typename T1 > Numeric<T1>& operator++ (Numeric< T1 > &) friend
operator+=
template<typename T> template<typename T1 > Numeric<T1>& operator+= (Numeric< T1 > & , const Numeric< T1 > &) friend
operator-
template<typename T> template<typename T1 > Numeric<T1> operator- (const Numeric< T1 > &) friend
operator--
template<typename T> template<typename T1 > Numeric<T1>& operator-- (Numeric< T1 > &) friend
operator-=
template<typename T> template<typename T1 > Numeric<T1>& operator-= (Numeric< T1 > & , const Numeric< T1 > &) friend
operator/=
template<typename T> template<typename T1 > Numeric<T1>& operator/= (Numeric< T1 > & , const Numeric< T1 > &) friend
operator<<
template<typename T> template<typename T1 > std::ostream& operator<< (std::ostream & , const Numeric< T1 > &) friend
Field Documentation
mContent
template<typename T> ContentType carl::Numeric< T >::mContent = 0 private
Definition at line 29 of file Numeric.h.
Referenced by carl::Numeric< T >::content(), and carl::Numeric< T >::toRational().
mFreeRationalIds
template<typename T> std::vector<ContentType> carl::Numeric< T >::mFreeRationalIds static
Definition at line 34 of file Numeric.h.
Referenced by carl::Numeric< T >::maybeIntegralize().
mRationalPool
template<typename T> std::vector<T> carl::Numeric< T >::mRationalPool static
Definition at line 33 of file Numeric.h.
Referenced by carl::Numeric< T >::operator typename IntegralType< T >::type(), carl::Numeric< T >::rational(), and carl::Numeric< T >::rRational().
The documentation for this class was generated from the following file:
carl/numbers/Numeric.h