carl: carl::UEquality Class Reference
carl::UEquality Class Reference
Implements an uninterpreted equality, that is an equality of either two uninterpreted function instances, two uninterpreted variables, or an uninterpreted function instance and an uninterpreted variable.
#include <UEquality.h>
Data Structures
struct IsUFInstance
Checks whether the given argument is an uninterpreted function instance.
struct IsUVariable
Checks whether the given argument is an uninterpreted variable.
Public Types
using Arg = boost::variant< UVariable, UFInstance >
The type of the left and right-hand side of an uninterpreted equality.
Public Member Functions
UEquality ()=default
UEquality (Arg _uvarA, Arg _uvarB, bool _negated)
Constructs an uninterpreted equality.
UEquality (const UVariable &_uvarA, const UVariable &_uvarB, bool _negated, bool _orderCorrect=false)
Constructs an uninterpreted equality.
UEquality (const UVariable &_uvar, const UFInstance &_ufun, bool _negated)
Constructs an uninterpreted equality.
UEquality (const UFInstance &_ufun, const UVariable &_uvar, bool _negated)
Constructs an uninterpreted equality.
UEquality (const UFInstance &_ufunA, const UFInstance &_ufunB, bool _negated, bool _orderCorrect=false)
Constructs an uninterpreted equality.
UEquality (const UEquality &_ueq, bool _invert=false)
Copies the given uninterpreted equality.
bool negated () const
const Arg & lhs () const
const Arg & rhs () const
bool lhsIsUV () const
bool rhsIsUV () const
bool lhsIsUF () const
bool rhsIsUF () const
const UVariable & lhsAsUV () const
const UVariable & rhsAsUV () const
const UFInstance & lhsAsUF () const
const UFInstance & rhsAsUF () const
std::size_t complexity () const
UEquality negation () const
bool operator== (const UEquality &_ueq) const
bool operator< (const UEquality &_ueq) const
std::string toString (unsigned _unequalSwitch, bool _infix, bool _friendlyNames) const
void collectUVariables (std::set< UVariable > &_uvars) const
Private Attributes
bool mNegated = false
A flag indicating whether this equality shall hold (if being false) or its negation (if being true), hence the inequality, shall hold.
Arg mLhs = UVariable(Variable::NO_VARIABLE, Sort())
The left-hand side of this uninterpreted equality.
Arg mRhs = UVariable(Variable::NO_VARIABLE, Sort())
The right-hand side of this uninterpreted equality.
Friends
std::ostream & operator<< (std::ostream &_os, const UEquality &_ueq)
Prints the given uninterpreted equality on the given output stream.
Detailed Description
Implements an uninterpreted equality, that is an equality of either two uninterpreted function instances, two uninterpreted variables, or an uninterpreted function instance and an uninterpreted variable.
Definition at line 23 of file UEquality.h.
Member Typedef Documentation
Arg
using carl::UEquality::Arg = boost::variant<UVariable, UFInstance>
The type of the left and right-hand side of an uninterpreted equality.
Definition at line 27 of file UEquality.h.
Constructor & Destructor Documentation
UEquality() [1/7]
carl::UEquality::UEquality () default
Referenced by negation().
UEquality() [2/7]
carl::UEquality::UEquality (Arg _uvarA, Arg _uvarB, bool _negated) inline
Constructs an uninterpreted equality.
Parameters
_negated true, if the negation of this equality shall hold, which means that it is actually an inequality.
_uvarA An uninterpreted variable, which is going to be the left-hand side of this uninterpreted equality.
_uvarB An uninterpreted variable, which is going to be the right-hand side of this uninterpreted equality.
Definition at line 108 of file UEquality.h.
UEquality() [3/7]
carl::UEquality::UEquality (const UVariable & _uvarA, const UVariable & _uvarB, bool _negated, bool _orderCorrect = false) inline
Constructs an uninterpreted equality.
Parameters
_negated true, if the negation of this equality shall hold, which means that it is actually an inequality.
_uvarA An uninterpreted variable, which is going to be the left-hand side of this uninterpreted equality.
_uvarB An uninterpreted variable, which is going to be the right-hand side of this uninterpreted equality.
Definition at line 143 of file UEquality.h.
UEquality() [4/7]
carl::UEquality::UEquality (const UVariable & _uvar, const UFInstance & _ufun, bool _negated) inline
Constructs an uninterpreted equality.
Parameters
_negated true, if the negation of this equality shall hold, which means that it is actually an inequality.
_uvar An uninterpreted variable, which is going to be the left-hand side of this uninterpreted equality.
_ufun An uninterpreted function instance, which is going to be the right-hand side of this uninterpreted equality.
Definition at line 159 of file UEquality.h.
UEquality() [5/7]
carl::UEquality::UEquality (const UFInstance & _ufun, const UVariable & _uvar, bool _negated) inline
Constructs an uninterpreted equality.
Parameters
_negated true, if the negation of this equality shall hold, which means that it is actually an inequality.
_ufun An uninterpreted function instance, which is going to be the left-hand side of this uninterpreted equality.
_uvar An uninterpreted variable, which is going to be the right-hand side of this uninterpreted equality.
Definition at line 173 of file UEquality.h.
UEquality() [6/7]
carl::UEquality::UEquality (const UFInstance & _ufunA, const UFInstance & _ufunB, bool _negated, bool _orderCorrect = false) inline
Constructs an uninterpreted equality.
Parameters
_negated true, if the negation of this equality shall hold, which means that it is actually an inequality.
_ufunA An uninterpreted function instance, which is going to be the left-hand side of this uninterpreted equality.
_ufunB An uninterpreted function instance, which is going to be the right-hand side of this uninterpreted equality.
Definition at line 187 of file UEquality.h.
UEquality() [7/7]
carl::UEquality::UEquality (const UEquality & _ueq, bool _invert = false) inline
Copies the given uninterpreted equality.
Parameters
_ueq The uninterpreted equality to copy.
_invert true, if the inverse of the given uninterpreted equality shall be constructed. (== -> != resp. != -> ==)
Definition at line 202 of file UEquality.h.
Member Function Documentation
collectUVariables()
void carl::UEquality::collectUVariables (std::set< UVariable > & _uvars) const
Definition at line 160 of file UEquality.cpp.
Referenced by carl::model::substituteIn().
complexity()
std::size_t carl::UEquality::complexity () const
Returns
An approximation of the complexity of this uninterpreted equality.
Definition at line 12 of file UEquality.cpp.
lhs()
const Arg& carl::UEquality::lhs () const inline
Returns
The left-hand side of this equality.
Definition at line 219 of file UEquality.h.
Referenced by negation().
lhsAsUF()
const UFInstance& carl::UEquality::lhsAsUF () const inline
Returns
The left-hand side, which must be an uninterpreted function instance.
Definition at line 283 of file UEquality.h.
Referenced by collectUVariables(), complexity(), carl::model::evaluate(), std::hash< carl::UEquality >::operator()(), operator<(), carl::operator<<(), operator==(), toString(), and UEquality().
lhsAsUV()
const UVariable& carl::UEquality::lhsAsUV () const inline
Returns
The left-hand side, which must be an uninterpreted variable.
Definition at line 267 of file UEquality.h.
Referenced by collectUVariables(), carl::model::evaluate(), std::hash< carl::UEquality >::operator()(), operator<(), carl::operator<<(), operator==(), toString(), and UEquality().
lhsIsUF()
bool carl::UEquality::lhsIsUF () const inline
Returns
true, if the left-hand side is an uninterpreted function instance.
Definition at line 251 of file UEquality.h.
Referenced by carl::model::evaluate(), operator<(), and UEquality().
lhsIsUV()
bool carl::UEquality::lhsIsUV () const inline
Returns
true, if the left-hand side is an uninterpreted variable.
Definition at line 235 of file UEquality.h.
Referenced by collectUVariables(), complexity(), carl::model::evaluate(), std::hash< carl::UEquality >::operator()(), operator<(), carl::operator<<(), operator==(), toString(), and UEquality().
negated()
bool carl::UEquality::negated () const inline
Returns
true, if the negation of this equation shall hold, that is, it is actually an inequality.
Definition at line 211 of file UEquality.h.
Referenced by negation(), operator<(), carl::operator<<(), operator==(), and toString().
negation()
UEquality carl::UEquality::negation () const inline
Definition at line 301 of file UEquality.h.
operator<()
bool carl::UEquality::operator< (const UEquality & _ueq) const
Parameters
_ueq The uninterpreted equality to compare with.
Returns
true, if this uninterpreted equality is less than the given one.
Definition at line 62 of file UEquality.cpp.
operator==()
bool carl::UEquality::operator== (const UEquality & _ueq) const
Parameters
_ueq The uninterpreted equality to compare with.
Returns
true, if this and the given equality instance are equal.
Definition at line 26 of file UEquality.cpp.
rhs()
const Arg& carl::UEquality::rhs () const inline
Returns
The right-hand side of this equality.
Definition at line 227 of file UEquality.h.
Referenced by negation().
rhsAsUF()
const UFInstance& carl::UEquality::rhsAsUF () const inline
Returns
The right-hand side, which must be an uninterpreted function instance.
Definition at line 291 of file UEquality.h.
Referenced by collectUVariables(), complexity(), carl::model::evaluate(), std::hash< carl::UEquality >::operator()(), operator<(), carl::operator<<(), operator==(), toString(), and UEquality().
rhsAsUV()
const UVariable& carl::UEquality::rhsAsUV () const inline
Returns
The right-hand side, which must be an uninterpreted variable.
Definition at line 275 of file UEquality.h.
Referenced by collectUVariables(), carl::model::evaluate(), std::hash< carl::UEquality >::operator()(), operator<(), carl::operator<<(), operator==(), toString(), and UEquality().
rhsIsUF()
bool carl::UEquality::rhsIsUF () const inline
Returns
true, if the right-hand side is an uninterpreted function instance.
Definition at line 259 of file UEquality.h.
Referenced by carl::model::evaluate(), and UEquality().
rhsIsUV()
bool carl::UEquality::rhsIsUV () const inline
Returns
true, if the right-hand side is an uninterpreted variable.
Definition at line 243 of file UEquality.h.
Referenced by collectUVariables(), complexity(), carl::model::evaluate(), std::hash< carl::UEquality >::operator()(), operator<(), carl::operator<<(), operator==(), toString(), and UEquality().
toString()
std::string carl::UEquality::toString (unsigned _unequalSwitch, bool _infix, bool _friendlyNames) const
Definition at line 118 of file UEquality.cpp.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & _os, const UEquality & _ueq) friend
Prints the given uninterpreted equality on the given output stream.
Parameters
_os The output stream to print on.
_ueq The uninterpreted equality to print.
Returns
The output stream after printing the given uninterpreted equality on it.
Definition at line 182 of file UEquality.cpp.
Field Documentation
mLhs
Arg carl::UEquality::mLhs = UVariable(Variable::NO_VARIABLE, Sort()) private
The left-hand side of this uninterpreted equality.
Definition at line 94 of file UEquality.h.
Referenced by lhs(), lhsAsUF(), lhsAsUV(), lhsIsUF(), lhsIsUV(), and UEquality().
mNegated
bool carl::UEquality::mNegated = false private
A flag indicating whether this equality shall hold (if being false) or its negation (if being true), hence the inequality, shall hold.
Definition at line 92 of file UEquality.h.
Referenced by negated(), operator<(), and operator==().
mRhs
Arg carl::UEquality::mRhs = UVariable(Variable::NO_VARIABLE, Sort()) private
The right-hand side of this uninterpreted equality.
Definition at line 96 of file UEquality.h.
Referenced by rhs(), rhsAsUF(), rhsAsUV(), rhsIsUF(), rhsIsUV(), and UEquality().
The documentation for this class was generated from the following files:
carl/formula/uninterpreted/UEquality.h
carl/formula/uninterpreted/UEquality.cpp