carl: carl::Interval< Number > Class Template Reference
carl::Interval< Number > Class Template Reference
The class which contains the interval arithmetic including trigonometric functions.
#include <Interval.h>
Public Types
using Policy = policies< Number, Interval< Number > >
using BoostIntervalPolicies = boost::numeric::interval_lib::policies< typename Policy::roundingP, typename Policy::checkingP >
using BoostInterval = boost::numeric::interval< Number, BoostIntervalPolicies >
using evalintervalmap = std::map< Variable, Interval< Number > >
using roundingP = carl::rounding< Number >
using checkingP = carl::checking< Number >
Public Member Functions
Interval ()
Default constructor which constructs the empty interval at point 0.
Interval (const Number &n)
Constructor which constructs the pointinterval at n.
Interval (const Number &lower, const Number &upper)
Constructor which constructs the weak-bounded interval between lower and upper.
Interval (const BoostInterval &content, BoundType lowerBoundType=BoundType::WEAK, BoundType upperBoundType=BoundType::WEAK)
Constructor which constructs the interval according to the passed boost interval with the passed bound types.
Interval (const Number &lower, BoundType lowerBoundType, const Number &upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed bounds with the passed bound types.
Interval (const Interval< Number > &o)
Copy constructor.
template<typename N = Number, DisableIf< std::is_same< N, double >> = dummy, DisableIf< is_rational< N >> = dummy>
Interval (const double &n)
Constructor which constructs a pointinterval from a passed double.
template<typename N = Number, DisableIf< std::is_same< N, double >> = dummy, DisableIf< is_rational< N >> = dummy>
Interval (double lower, double upper)
Constructor which constructs an interval from the passed double bounds.
template<typename N = Number, DisableIf< std::is_same< N, double >> = dummy, DisableIf< is_rational< N >> = dummy>
Interval (double lower, BoundType lowerBoundType, double upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed double bounds with the passed bound types.
template<typename N = Number, DisableIf< std::is_same< N, int >> = dummy>
Interval (const int &n)
Constructor which constructs a pointinterval from a passed int.
template<typename N = Number, DisableIf< std::is_same< N, int >> = dummy>
Interval (int lower, int upper)
Constructor which constructs an interval from the passed int bounds.
template<typename N = Number, DisableIf< std::is_same< N, int >> = dummy>
Interval (int lower, BoundType lowerBoundType, int upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed int bounds with the passed bound types.
template<typename N = Number, DisableIf< std::is_same< N, unsigned int >> = dummy>
Interval (const unsigned int &n)
Constructor which constructs a pointinterval from a passed unsigned int.
template<typename N = Number, DisableIf< std::is_same< N, unsigned int >> = dummy>
Interval (unsigned int lower, unsigned int upper)
Constructor which constructs an interval from the passed unsigned int bounds.
template<typename N = Number, DisableIf< std::is_same< N, unsigned int >> = dummy>
Interval (unsigned int lower, BoundType lowerBoundType, unsigned int upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed unsigned int bounds with the passed bound types.
template<typename Num = Number, typename Rational , EnableIf< std::is_floating_point< Num >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy>
Interval (Rational n)
Constructor which constructs a pointinterval from a passed general rational number.
template<typename Num = Number, typename Rational , EnableIf< std::is_floating_point< Num >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy>
Interval (Rational lower, Rational upper)
Constructor which constructs an interval from the passed general rational bounds.
template<typename Num = Number, typename Rational , EnableIf< std::is_floating_point< Num >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy>
Interval (Rational lower, BoundType lowerBoundType, Rational upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed general rational bounds with the passed bound types.
template<typename Num = Number, typename Float , EnableIf< is_rational< Num >> = dummy, EnableIf< std::is_floating_point< Float >> = dummy, DisableIf< std::is_same< Num, Float >> = dummy>
Interval (Float n)
Constructor which constructs a pointinterval from a passed general float number (e.g.
template<typename Num = Number, typename Float , EnableIf< is_rational< Num >> = dummy, EnableIf< std::is_floating_point< Float >> = dummy, DisableIf< std::is_same< Num, Float >> = dummy>
Interval (Float lower, Float upper)
Constructor which constructs an interval from the passed general float bounds (e.g.
template<typename Num = Number, typename Float , EnableIf< is_rational< Num >> = dummy, EnableIf< std::is_floating_point< Float >> = dummy, DisableIf< std::is_same< Num, Float >> = dummy, DisableIf< std::is_floating_point< Num >> = dummy>
Interval (Float lower, BoundType lowerBoundType, Float upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed general float bounds (e.g.
template<typename Num = Number, typename Rational , EnableIf< is_rational< Num >> = dummy, EnableIf< is_rational< Rational >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy>
Interval (Rational n)
Constructor which constructs a pointinterval from a passed general float number (e.g.
template<typename Num = Number, typename Rational , EnableIf< is_rational< Num >> = dummy, EnableIf< is_rational< Rational >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy>
Interval (Rational lower, Rational upper)
Constructor which constructs an interval from the passed general float bounds (e.g.
template<typename Num = Number, typename Rational , EnableIf< is_rational< Num >> = dummy, EnableIf< is_rational< Rational >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy>
Interval (Rational lower, BoundType lowerBoundType, Rational upper, BoundType upperBoundType)
Constructor which constructs the interval according to the passed general float bounds (e.g.
~Interval ()=default
Destructor.
const Number & lower () const
The getter for the lower boundary of the interval.
const Number & upper () const
The getter for the upper boundary of the interval.
BoostInterval & rContent ()
Returns a reference to the included boost interval.
BoostInterval content () const
Returns a copy of the included boost interval.
BoundType lowerBoundType () const
The getter for the lower bound type of the interval.
BoundType upperBoundType () const
The getter for the upper bound type of the interval.
void setLower (const Number &n)
The setter for the lower boundary of the interval.
void setUpper (const Number &n)
The setter for the upper boundary of the interval.
void setLowerBound (const Number &n, BoundType b)
The setter for the lower boundary of the interval.
void setUpperBound (const Number &n, BoundType b)
The setter for the upper boundary of the interval.
void setLowerBoundType (BoundType b)
The setter for the lower bound type of the interval.
void setUpperBoundType (BoundType b)
The setter for the upper bound type of the interval.
Interval< Number > & operator= (const Interval< Number > &rhs)
The assignment operator.
void set (const BoostInterval &content)
Advanced setter to modify both boundaries at once.
void set (const Number &lower, const Number &upper)
Advanced setter to modify both boundaries at once by passing a boost interval.
bool isInfinite () const
Function which determines, if the interval is (-oo,oo).
bool isUnbounded () const
Function which determines, if the interval is unbounded.
bool isHalfBounded () const
Function which determines, if the interval is half-bounded.
bool isEmpty () const
Function which determines, if the interval is empty.
bool isPointInterval () const
Function which determines, if the interval is a pointinterval.
bool isOpenInterval () const
Function which determines, if the interval is open.
bool isClosedInterval () const
Function which determines, if the interval is closed.
bool isZero () const
Function which determines, if the interval is the zero interval.
bool isOne () const
Function which determines, if the interval is the one interval.
bool isPositive () const
bool isNegative () const
bool isSemiPositive () const
bool isSemiNegative () const
Sign sgn () const
Determine whether the interval lays entirely left of 0 (NEGATIVE_SIGN), right of 0 (POSITIVE_SIGN) or contains 0 (ZERO_SIGN).
Interval< Number > integralPart () const
Computes the integral part of the given interval.
void integralPart_assign ()
Computes and assigns the integral part of the given interval.
bool containsInteger () const
Checks if the interval contains at least one integer value.
Number diameter () const
Returns the diameter of the interval.
void diameter_assign ()
Computes and assigns the diameter of the interval.
Number diameterRatio (const Interval< Number > &rhs) const
Returns the ratio of the diameters of the given intervals.
void diameterRatio_assign (const Interval< Number > &rhs)
Computes and assigns the ratio of the diameters of the given intervals.
Number magnitude () const
Returns the magnitude of the interval.
void magnitude_assign ()
Computes and assigns the magnitude of the interval.
template<typename N = Number, DisableIf< std::is_floating_point< N >> = dummy>
N center () const
Returns the center point of the interval.
template<typename N = Number, EnableIf< std::is_floating_point< N >> = dummy>
N center () const
void center_assign ()
Computes and assigns the center point of the interval.
Number sample (bool _includingBounds=true) const
Searches for some point in this interval, preferably near the midpoint and with a small representation.
Number sampleSB (bool _includingBounds=true) const
Searches for some point in this interval, preferably near the midpoint and with a small representation.
Number sampleLeft () const
Searches for some point in this interval, preferably near the left endpoint and with a small representation.
Number sampleRight () const
Searches for some point in this interval, preferably near the right endpoint and with a small representation.
Number sampleZero () const
Searches for some point in this interval, preferably near zero and with a small representation.
Number sampleInfty () const
Searches for some point in this interval, preferably far aways from zero and with a small representation.
void sample_assign ()
Searches for some point in this interval, preferably near the midpoint and with a small representation and assigns this interval the calculated point.
bool contains (const Number &val) const
Checks if the interval contains the given value.
template<typename Num = Number, DisableIf< std::is_same< Num, int >> = dummy>
bool contains (int val) const
bool contains (const Interval< Number > &rhs) const
Checks if the interval contains the given interval.
bool meets (const Number &n) const
Checks if the interval meets the given value, that is if the given value is contained in the closed interval defined by the bounds.
bool isSubset (const Interval< Number > &rhs) const
Checks if the given interval is a subset of the calling interval.
bool isProperSubset (const Interval< Number > &rhs) const
Checks if the given interval is a proper subset of the calling interval.
void bloat_by (const Number &width)
Bloats the interval by the given value.
void bloat_times (const Number &factor)
Bloats the interval times the factor (multiplies the overall width).
void shrink_by (const Number &width)
Shrinks the interval by the given value.
void shrink_times (const Number &factor)
Shrinks the interval by a multiple of its width.
std::pair< Interval< Number >, Interval< Number > > split () const
Splits the interval into 2 equally sized parts (strict-weak-cut).
std::list< Interval< Number > > split (unsigned n) const
Splits the interval into n equally sized parts (strict-weak-cut).
std::string toString () const
Creates a string representation of the interval.
Interval< Number > add (const Interval< Number > &rhs) const
Adds two intervals according to natural interval arithmetic.
void add_assign (const Interval< Number > &rhs)
Interval< Number > sub (const Interval< Number > &rhs) const
Subtracts two intervals according to natural interval arithmetic.
void sub_assign (const Interval< Number > &rhs)
Interval< Number > mul (const Interval< Number > &rhs) const
Multiplies two intervals according to natural interval arithmetic.
void mul_assign (const Interval< Number > &rhs)
Interval< Number > div (const Interval< Number > &rhs) const
Divides two intervals according to natural interval arithmetic.
void div_assign (const Interval< Number > &rhs)
bool div_ext (const Interval< Number > &rhs, Interval< Number > &a, Interval< Number > &b) const
Implements extended interval division with intervals containting zero.
Interval< Number > inverse () const
Calculates the additive inverse of an interval with respect to natural interval arithmetic.
Interval< Number > abs () const
Calculates the absolute value of the interval.
void abs_assign ()
Calculates and assigns the absolute value of the interval.
void inverse_assign ()
Calculates and assigns the additive inverse of an interval with respect to natural interval arithmetic.
bool reciprocal (Interval< Number > &a, Interval< Number > &b) const
Calculates the multiplicative inverse of an interval with respect to natural interval arithmetic.
Interval< Number > pow (uint exp) const
Calculates the power of the interval with respect to natural interval arithmetic.
void pow_assign (uint exp)
Calculates and assigns the power of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > sqrt () const
Calculates the square root of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void sqrt_assign ()
Calculates and assigns the square root of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > root (int deg) const
Calculates the nth root of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void root_assign (unsigned deg)
Calculates and assigns the nth root of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > log () const
Calculates the logarithm of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void log_assign ()
Calculates and assigns the logarithm of the interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > sin () const
Calculates the sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void sin_assign ()
Calculates and assigns the sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > cos () const
Calculates the cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void cos_assign ()
Calculates and assigns the cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > tan () const
Calculates the tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void tan_assign ()
Calculates and assigns the tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > asin () const
Calculates the arcus sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void asin_assign ()
Calculates and assigns the arcus sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > acos () const
Calculates the arcus cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void acos_assign ()
Calculates and assigns the arcus cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > atan () const
Calculates the arcus tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void atan_assign ()
Calculates and assigns the arcus tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > sinh () const
Calculates the hyperbolic sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void sinh_assign ()
Calculates and assigns the hyperbolic sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > cosh () const
Calculates the hyperbolic cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void cosh_assign ()
Calculates and assigns the hyperbolic cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > tanh () const
Calculates the hyperbolic tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void tanh_assign ()
Calculates and assigns the hyperbolic tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > asinh () const
Calculates the hyperbolic arcus sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void asinh_assign ()
Calculates and assigns the hyperbolic arcus sine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > acosh () const
Calculates the hyperbolic arcus cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void acosh_assign ()
Calculates and assigns the hyperbolic arcus cosine of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
Interval< Number > atanh () const
Calculates the hyperbolic arcus tangent of the given interval with respect to natural interval arithmetic.
template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy>
void atanh_assign ()
Calculates and assigns the hyperbolic arcus tangent of the given interval with respect to natural interval arithmetic.
bool intersectsWith (const Interval< Number > &rhs) const
Interval< Number > intersect (const Interval< Number > &rhs) const
Intersects two intervals in a set-theoretic manner.
Interval< Number > & intersect_assign (const Interval< Number > &rhs)
Intersects and assigns two intervals in a set-theoretic manner.
bool unite (const Interval< Number > &rhs, Interval< Number > &resultA, Interval< Number > &resultB) const
Unites two intervals in a set-theoretic manner (can result in two distinct intervals).
bool difference (const Interval< Number > &rhs, Interval< Number > &resultA, Interval< Number > &resultB) const
Calculates the difference of two intervals in a set-theoretic manner: lhs - rhs (can result in two distinct intervals).
bool complement (Interval< Number > &resultA, Interval< Number > &resultB) const
Calculates the complement in a set-theoretic manner (can result in two distinct intervals).
bool symmetricDifference (const Interval< Number > &rhs, Interval< Number > &resultA, Interval< Number > &resultB) const
Calculates the symmetric difference of two intervals in a set-theoretic manner (can result in two distinct intervals).
bool isConsistent () const
A quick check for the bound values.
Number distance (const Interval< Number > &intervalA)
Calculates the distance between two Intervals.
Interval< Number > convexHull (const Interval< Number > &interval) const
Static Public Member Functions
static Interval< Number > unboundedInterval ()
Method which returns the unbounded interval rooted at 0.
static Interval< Number > emptyInterval ()
Method which returns the empty interval rooted at 0.
static Interval< Number > zeroInterval ()
Method which returns the pointinterval rooted at 0.
static void sanitize (Interval< Number > &)
Protected Attributes
BoostInterval mContent
BoundType mLowerBoundType = BoundType::STRICT
BoundType mUpperBoundType = BoundType::STRICT
Friends
std::ostream & operator<< (std::ostream &str, const Interval< Number > &i)
Operator which passes a string representation of this to the given ostream.
Detailed Description
template<typename Number>
class carl::Interval< Number >
The class which contains the interval arithmetic including trigonometric functions.
The template parameter contains the number type used for the boundaries. It is necessary to implement the rounding and checking policies for any non-primitive type such that the desired inclusion property can be maintained.
Requirements for the NumberType:
Operators +,-,*,/ with the expected functionality
Operators +=,-=,*=,/= with the expected functionality
Operators <,>,<=,>=,==,!= with the expected functionality
Operations abs, min, max, log, exp, power, sqrt
Trigonometric functions sin, cos, tan, asin, acos, atan, sinh, cosh, tanh, asinh, acosh, atanh (these functions are needed for the specialization of the rounding modes.
Operator <<
Definition at line 54 of file Interval.h.
Member Typedef Documentation
BoostInterval
template<typename Number> using carl::Interval< Number >::BoostInterval = boost::numeric::interval< Number, BoostIntervalPolicies >
Definition at line 145 of file Interval.h.
BoostIntervalPolicies
template<typename Number> using carl::Interval< Number >::BoostIntervalPolicies = boost::numeric::interval_lib::policies< typename Policy::roundingP, typename Policy::checkingP >
Definition at line 144 of file Interval.h.
checkingP
using carl::policies< Number, Interval< Number > >::checkingP = carl::checking<Number> inherited
Definition at line 92 of file Interval.h.
evalintervalmap
template<typename Number> using carl::Interval< Number >::evalintervalmap = std::map<Variable, Interval<Number> >
Definition at line 146 of file Interval.h.
Policy
template<typename Number> using carl::Interval< Number >::Policy = policies<Number, Interval<Number> >
Definition at line 138 of file Interval.h.
roundingP
using carl::policies< Number, Interval< Number > >::roundingP = carl::rounding<Number> inherited
Definition at line 91 of file Interval.h.
Constructor & Destructor Documentation
Interval() [1/24]
template<typename Number> carl::Interval< Number >::Interval () inline
Default constructor which constructs the empty interval at point 0.
Definition at line 178 of file Interval.h.
Interval() [2/24]
template<typename Number> carl::Interval< Number >::Interval (const Number & n) inline
Constructor which constructs the pointinterval at n.
Parameters
n Location of the pointinterval.
Definition at line 186 of file Interval.h.
Interval() [3/24]
template<typename Number> carl::Interval< Number >::Interval (const Number & lower, const Number & upper) inline
Constructor which constructs the weak-bounded interval between lower and upper.
If the bounds are invalid an empty interval at point 0 is constructed.
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 201 of file Interval.h.
Interval() [4/24]
template<typename Number> carl::Interval< Number >::Interval (const BoostInterval< Number > & content, BoundType lowerBoundType = BoundType::WEAK, BoundType upperBoundType = BoundType::WEAK) inline explicit
Constructor which constructs the interval according to the passed boost interval with the passed bound types.
Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constructed and if both bounds are infty the unbounded interval is constructed.
Parameters
content The passed boost interval.
lowerBoundType The desired lower bound type, defaults to WEAK.
upperBoundType The desired upper bound type, defaults to WEAK.
Definition at line 229 of file Interval.h.
Interval() [5/24]
template<typename Number> carl::Interval< Number >::Interval (const Number & lower, BoundType lowerBoundType, const Number & upper, BoundType upperBoundType) inline
Constructor which constructs the interval according to the passed bounds with the passed bound types.
Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired lower bound.
lowerBoundType The desired lower bound type.
upper The desired upper bound.
upperBoundType The desired upper bound type.
Definition at line 279 of file Interval.h.
Interval() [6/24]
template<typename Number> carl::Interval< Number >::Interval (const Interval< Number > & o) inline
Copy constructor.
Parameters
o The original interval.
Definition at line 322 of file Interval.h.
Interval() [7/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, double >> = dummy, DisableIf< is_rational< N >> = dummy> carl::Interval< Number >::Interval (const double & n) inline explicit
Constructor which constructs a pointinterval from a passed double.
Parameters
n The passed double.
Definition at line 332 of file Interval.h.
Interval() [8/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, double >> = dummy, DisableIf< is_rational< N >> = dummy> carl::Interval< Number >::Interval (double lower, double upper) inline
Constructor which constructs an interval from the passed double bounds.
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 345 of file Interval.h.
Interval() [9/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, double >> = dummy, DisableIf< is_rational< N >> = dummy> carl::Interval< Number >::Interval (double lower, BoundType lowerBoundType, double upper, BoundType upperBoundType) inline
Constructor which constructs the interval according to the passed double bounds with the passed bound types.
Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired double lower bound.
lowerBoundType The desired lower bound type.
upper The desired double upper bound.
upperBoundType The desired upper bound type.
Definition at line 373 of file Interval.h.
Interval() [10/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, int >> = dummy> carl::Interval< Number >::Interval (const int & n) inline explicit
Constructor which constructs a pointinterval from a passed int.
Parameters
n The passed double.
Definition at line 416 of file Interval.h.
Interval() [11/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, int >> = dummy> carl::Interval< Number >::Interval (int lower, int upper) inline
Constructor which constructs an interval from the passed int bounds.
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 427 of file Interval.h.
Interval() [12/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, int >> = dummy> carl::Interval< Number >::Interval (int lower, BoundType lowerBoundType, int upper, BoundType upperBoundType) inline
Constructor which constructs the interval according to the passed int bounds with the passed bound types.
Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired lower bound.
lowerBoundType The desired lower bound type.
upper The desired upper bound.
upperBoundType The desired upper bound type.
Definition at line 454 of file Interval.h.
Interval() [13/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, unsigned int >> = dummy> carl::Interval< Number >::Interval (const unsigned int & n) inline explicit
Constructor which constructs a pointinterval from a passed unsigned int.
Parameters
n The passed double.
Definition at line 496 of file Interval.h.
Interval() [14/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, unsigned int >> = dummy> carl::Interval< Number >::Interval (unsigned int lower, unsigned int upper) inline explicit
Constructor which constructs an interval from the passed unsigned int bounds.
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 507 of file Interval.h.
Interval() [15/24]
template<typename Number> template<typename N = Number, DisableIf< std::is_same< N, unsigned int >> = dummy> carl::Interval< Number >::Interval (unsigned int lower, BoundType lowerBoundType, unsigned int upper, BoundType upperBoundType) inline explicit
Constructor which constructs the interval according to the passed unsigned int bounds with the passed bound types.
Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired lower bound.
lowerBoundType The desired lower bound type.
upper The desired upper bound.
upperBoundType The desired upper bound type.
Definition at line 534 of file Interval.h.
Interval() [16/24]
template<typename Number> template<typename Num = Number, typename Rational , EnableIf< std::is_floating_point< Num >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy> carl::Interval< Number >::Interval (Rational n) inline explicit
Constructor which constructs a pointinterval from a passed general rational number.
Parameters
n The passed double.
Definition at line 577 of file Interval.h.
Interval() [17/24]
template<typename Number> template<typename Num = Number, typename Rational , EnableIf< std::is_floating_point< Num >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy> carl::Interval< Number >::Interval (Rational lower, Rational upper) inline
Constructor which constructs an interval from the passed general rational bounds.
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 591 of file Interval.h.
Interval() [18/24]
template<typename Number> template<typename Num = Number, typename Rational , EnableIf< std::is_floating_point< Num >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy> carl::Interval< Number >::Interval (Rational lower, BoundType lowerBoundType, Rational upper, BoundType upperBoundType) inline
Constructor which constructs the interval according to the passed general rational bounds with the passed bound types.
Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired lower bound.
lowerBoundType The desired lower bound type.
upper The desired upper bound.
upperBoundType The desired upper bound type.
Definition at line 609 of file Interval.h.
Interval() [19/24]
template<typename Number> template<typename Num = Number, typename Float , EnableIf< is_rational< Num >> = dummy, EnableIf< std::is_floating_point< Float >> = dummy, DisableIf< std::is_same< Num, Float >> = dummy> carl::Interval< Number >::Interval (Float n) inline explicit
Constructor which constructs a pointinterval from a passed general float number (e.g.
FLOAT_T).
Parameters
n The passed double.
Definition at line 648 of file Interval.h.
Interval() [20/24]
template<typename Number> template<typename Num = Number, typename Float , EnableIf< is_rational< Num >> = dummy, EnableIf< std::is_floating_point< Float >> = dummy, DisableIf< std::is_same< Num, Float >> = dummy> carl::Interval< Number >::Interval (Float lower, Float upper) inline
Constructor which constructs an interval from the passed general float bounds (e.g.
FLOAT_T).
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 662 of file Interval.h.
Interval() [21/24]
template<typename Number> template<typename Num = Number, typename Float , EnableIf< is_rational< Num >> = dummy, EnableIf< std::is_floating_point< Float >> = dummy, DisableIf< std::is_same< Num, Float >> = dummy, DisableIf< std::is_floating_point< Num >> = dummy> carl::Interval< Number >::Interval (Float lower, BoundType lowerBoundType, Float upper, BoundType upperBoundType) inline
Constructor which constructs the interval according to the passed general float bounds (e.g.
FLOAT_T) with the passed bound types. Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired lower bound.
lowerBoundType The desired lower bound type.
upper The desired upper bound.
upperBoundType The desired upper bound type.
Definition at line 680 of file Interval.h.
Interval() [22/24]
template<typename Number> template<typename Num = Number, typename Rational , EnableIf< is_rational< Num >> = dummy, EnableIf< is_rational< Rational >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy> carl::Interval< Number >::Interval (Rational n) inline explicit
Constructor which constructs a pointinterval from a passed general float number (e.g.
FLOAT_T).
Parameters
n The passed double.
Definition at line 718 of file Interval.h.
Interval() [23/24]
template<typename Number> template<typename Num = Number, typename Rational , EnableIf< is_rational< Num >> = dummy, EnableIf< is_rational< Rational >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy> carl::Interval< Number >::Interval (Rational lower, Rational upper) inline
Constructor which constructs an interval from the passed general float bounds (e.g.
FLOAT_T).
Parameters
lower The desired lower bound.
upper The desired upper bound.
Definition at line 732 of file Interval.h.
Interval() [24/24]
template<typename Number> template<typename Num = Number, typename Rational , EnableIf< is_rational< Num >> = dummy, EnableIf< is_rational< Rational >> = dummy, DisableIf< std::is_same< Num, Rational >> = dummy> carl::Interval< Number >::Interval (Rational lower, BoundType lowerBoundType, Rational upper, BoundType upperBoundType) inline
Constructor which constructs the interval according to the passed general float bounds (e.g.
FLOAT_T) with the passed bound types. Note that if the interval is a pointinterval with both strict bounds or the content is invalid the empty interval is constru
Parameters
lower The desired lower bound.
lowerBoundType The desired lower bound type.
upper The desired upper bound.
upperBoundType The desired upper bound type.
Definition at line 750 of file Interval.h.
~Interval()
template<typename Number> carl::Interval< Number >::~Interval () default
Destructor.
Member Function Documentation
abs()
template<typename Number> Interval<Number> carl::Interval< Number >::abs () const
Calculates the absolute value of the interval.
Returns
Interval.
abs_assign()
template<typename Number> void carl::Interval< Number >::abs_assign ()
Calculates and assigns the absolute value of the interval.
acos()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::acos () const
Calculates the arcus cosine of the given interval with respect to natural interval arithmetic.
Returns
Result.
acos_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::acos_assign ()
Calculates and assigns the arcus cosine of the given interval with respect to natural interval arithmetic.
acosh()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::acosh () const
Calculates the hyperbolic arcus cosine of the given interval with respect to natural interval arithmetic.
Returns
Result.
acosh_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::acosh_assign ()
Calculates and assigns the hyperbolic arcus cosine of the given interval with respect to natural interval arithmetic.
add()
template<typename Number> Interval<Number> carl::Interval< Number >::add (const Interval< Number > & rhs) const
Adds two intervals according to natural interval arithmetic.
Parameters
rhs Interval.
Returns
Result.
add_assign()
template<typename Number> void carl::Interval< Number >::add_assign (const Interval< Number > & rhs)
asin()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::asin () const
Calculates the arcus sine of the given interval with respect to natural interval arithmetic.
Returns
Result.
asin_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::asin_assign ()
Calculates and assigns the arcus sine of the given interval with respect to natural interval arithmetic.
asinh()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::asinh () const
Calculates the hyperbolic arcus sine of the given interval with respect to natural interval arithmetic.
Returns
Result.
asinh_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::asinh_assign ()
Calculates and assigns the hyperbolic arcus sine of the given interval with respect to natural interval arithmetic.
atan()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::atan () const
Calculates the arcus tangent of the given interval with respect to natural interval arithmetic.
Returns
Result.
atan_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::atan_assign ()
Calculates and assigns the arcus tangent of the given interval with respect to natural interval arithmetic.
atanh()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::atanh () const
Calculates the hyperbolic arcus tangent of the given interval with respect to natural interval arithmetic.
Returns
Result.
atanh_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::atanh_assign ()
Calculates and assigns the hyperbolic arcus tangent of the given interval with respect to natural interval arithmetic.
bloat_by()
template<typename Number> void carl::Interval< Number >::bloat_by (const Number & width)
Bloats the interval by the given value.
Parameters
width Width.
bloat_times()
template<typename Number> void carl::Interval< Number >::bloat_times (const Number & factor)
Bloats the interval times the factor (multiplies the overall width).
Parameters
factor Factor.
center() [1/2]
template<typename Number> template<typename N = Number, DisableIf< std::is_floating_point< N >> = dummy> N carl::Interval< Number >::center () const inline
Returns the center point of the interval.
Returns
Center.
Definition at line 1203 of file Interval.h.
Referenced by carl::SimpleNewton< Polynomial >::contract(), carl::sampleBetween(), carl::Interval< mpq_class >::sampleLeft(), and carl::Interval< mpq_class >::sampleRight().
center() [2/2]
template<typename Number> template<typename N = Number, EnableIf< std::is_floating_point< N >> = dummy> N carl::Interval< Number >::center () const inline
Definition at line 1215 of file Interval.h.
center_assign()
template<typename Number> void carl::Interval< Number >::center_assign ()
Computes and assigns the center point of the interval.
complement()
template<typename Number> bool carl::Interval< Number >::complement (Interval< Number > & resultA, Interval< Number > & resultB) const
Calculates the complement in a set-theoretic manner (can result in two distinct intervals).
Parameters
resultA Result a.
resultB Result b.
Returns
True, if the result is twofold.
contains() [1/3]
template<typename Number> bool carl::Interval< Number >::contains (const Number & val) const
Checks if the interval contains the given value.
Parameters
val Value to be checked.
Returns
True if the value is contained in this.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::Interval< mpq_class >::contains(), carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber(), carl::Interval< mpq_class >::sampleLeft(), and carl::Interval< mpq_class >::sampleRight().
contains() [2/3]
template<typename Number> template<typename Num = Number, DisableIf< std::is_same< Num, int >> = dummy> bool carl::Interval< Number >::contains (int val) const inline
Definition at line 1310 of file Interval.h.
contains() [3/3]
template<typename Number> bool carl::Interval< Number >::contains (const Interval< Number > & rhs) const
Checks if the interval contains the given interval.
Parameters
rhs Interval to be checked.
Returns
True if rhs is contained in this.
containsInteger()
template<typename Number> bool carl::Interval< Number >::containsInteger () const
Checks if the interval contains at least one integer value.
Returns
true, if the interval contains an integer.
content()
template<typename Number> BoostInterval carl::Interval< Number >::content () const inline
Returns a copy of the included boost interval.
Returns
Boost interval.
Definition at line 848 of file Interval.h.
Referenced by carl::Interval< mpq_class >::Interval(), and carl::Interval< mpq_class >::set().
convexHull()
template<typename Number> Interval<Number> carl::Interval< Number >::convexHull (const Interval< Number > & interval) const
cos()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::cos () const
Calculates the cosine of the given interval with respect to natural interval arithmetic.
Returns
Result.
cos_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::cos_assign ()
Calculates and assigns the cosine of the given interval with respect to natural interval arithmetic.
cosh()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::cosh () const
Calculates the hyperbolic cosine of the given interval with respect to natural interval arithmetic.
Returns
Result.
cosh_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::cosh_assign ()
Calculates and assigns the hyperbolic cosine of the given interval with respect to natural interval arithmetic.
diameter()
template<typename Number> Number carl::Interval< Number >::diameter () const
Returns the diameter of the interval.
Returns
Diameter.
diameter_assign()
template<typename Number> void carl::Interval< Number >::diameter_assign ()
Computes and assigns the diameter of the interval.
diameterRatio()
template<typename Number> Number carl::Interval< Number >::diameterRatio (const Interval< Number > & rhs) const
Returns the ratio of the diameters of the given intervals.
Parameters
rhs Other interval.
Returns
Ratio.
diameterRatio_assign()
template<typename Number> void carl::Interval< Number >::diameterRatio_assign (const Interval< Number > & rhs)
Computes and assigns the ratio of the diameters of the given intervals.
Parameters
rhs Other interval.
difference()
template<typename Number> bool carl::Interval< Number >::difference (const Interval< Number > & rhs, Interval< Number > & resultA, Interval< Number > & resultB) const
Calculates the difference of two intervals in a set-theoretic manner: lhs - rhs (can result in two distinct intervals).
Parameters
rhs Righthand side.
resultA Result a.
resultB Result b.
Returns
True, if the result is twofold.
distance()
template<typename Number> Number carl::Interval< Number >::distance (const Interval< Number > & intervalA)
Calculates the distance between two Intervals.
Parameters
intervalA Interval to wich we want to know the distance.
Returns
distance to intervalA
div()
template<typename Number> Interval<Number> carl::Interval< Number >::div (const Interval< Number > & rhs) const
Divides two intervals according to natural interval arithmetic.
Parameters
rhs Interval.
Returns
Result.
div_assign()
template<typename Number> void carl::Interval< Number >::div_assign (const Interval< Number > & rhs)
div_ext()
template<typename Number> bool carl::Interval< Number >::div_ext (const Interval< Number > & rhs, Interval< Number > & a, Interval< Number > & b) const
Implements extended interval division with intervals containting zero.
Parameters
rhs Interval.
a Result a.
b Result b.
Returns
True if split occurred.
Referenced by carl::SimpleNewton< Polynomial >::contract(), and carl::VarSolutionFormula< carl::Polynomial >::evaluate().
emptyInterval()
template<typename Number> static Interval<Number> carl::Interval< Number >::emptyInterval () inline static
Method which returns the empty interval rooted at 0.
Returns
Empty interval.
Definition at line 794 of file Interval.h.
Referenced by carl::SimpleNewton< Polynomial >::contract(), carl::IntervalEvaluation::evaluate(), and carl::Contraction< Operator, Polynomial >::operator()().
integralPart()
template<typename Number> Interval<Number> carl::Interval< Number >::integralPart () const
Computes the integral part of the given interval.
Returns
Interval.
Referenced by carl::VarSolutionFormula< carl::Polynomial >::addRoot(), and carl::SimpleNewton< Polynomial >::contract().
integralPart_assign()
template<typename Number> void carl::Interval< Number >::integralPart_assign ()
Computes and assigns the integral part of the given interval.
Returns
Interval.
intersect()
template<typename Number> Interval<Number> carl::Interval< Number >::intersect (const Interval< Number > & rhs) const
Intersects two intervals in a set-theoretic manner.
Parameters
rhs Righthand side.
Returns
Result.
Referenced by carl::SimpleNewton< Polynomial >::contract(), and carl::Contraction< Operator, Polynomial >::operator()().
intersect_assign()
template<typename Number> Interval<Number>& carl::Interval< Number >::intersect_assign (const Interval< Number > & rhs)
Intersects and assigns two intervals in a set-theoretic manner.
Parameters
rhs Righthand side.
Returns
Reference to this.
Referenced by carl::VarSolutionFormula< carl::Polynomial >::addRoot().
intersectsWith()
template<typename Number> bool carl::Interval< Number >::intersectsWith (const Interval< Number > & rhs) const
inverse()
template<typename Number> Interval<Number> carl::Interval< Number >::inverse () const
Calculates the additive inverse of an interval with respect to natural interval arithmetic.
Returns
Interval.
inverse_assign()
template<typename Number> void carl::Interval< Number >::inverse_assign ()
Calculates and assigns the additive inverse of an interval with respect to natural interval arithmetic.
isClosedInterval()
template<typename Number> bool carl::Interval< Number >::isClosedInterval () const inline
Function which determines, if the interval is closed.
Returns
True if both bounds are WEAK.
Definition at line 1065 of file Interval.h.
Referenced by carl::Interval< mpq_class >::isPointInterval().
isConsistent()
template<typename Number> bool carl::Interval< Number >::isConsistent () const inline
A quick check for the bound values.
Returns
True if the lower bound is less or equal to the upper bound.
Definition at line 1770 of file Interval.h.
Referenced by carl::Interval< mpq_class >::center(), carl::Interval< mpq_class >::Interval(), carl::Interval< mpq_class >::isClosedInterval(), carl::Interval< mpq_class >::isEmpty(), carl::Interval< mpq_class >::isHalfBounded(), carl::Interval< mpq_class >::isInfinite(), carl::Interval< mpq_class >::isNegative(), carl::Interval< mpq_class >::isOne(), carl::Interval< mpq_class >::isOpenInterval(), carl::Interval< mpq_class >::isPointInterval(), carl::Interval< mpq_class >::isPositive(), carl::Interval< mpq_class >::isSemiNegative(), carl::Interval< mpq_class >::isSemiPositive(), carl::Interval< mpq_class >::isUnbounded(), and carl::Interval< mpq_class >::isZero().
isEmpty()
template<typename Number> bool carl::Interval< Number >::isEmpty () const inline
Function which determines, if the interval is empty.
Returns
True if the interval is empty.
Definition at line 1030 of file Interval.h.
Referenced by carl::VarSolutionFormula< carl::Polynomial >::addRoot(), carl::SimpleNewton< Polynomial >::contract(), carl::Contraction< Operator, Polynomial >::operator()(), and carl::sampleBetween().
isHalfBounded()
template<typename Number> bool carl::Interval< Number >::isHalfBounded () const inline
Function which determines, if the interval is half-bounded.
Returns
True if exactly one bound is INFTY.
Definition at line 1020 of file Interval.h.
isInfinite()
template<typename Number> bool carl::Interval< Number >::isInfinite () const inline
Function which determines, if the interval is (-oo,oo).
Returns
True if both bounds are INFTY.
Definition at line 1000 of file Interval.h.
Referenced by carl::Interval< mpq_class >::center(), and carl::IntervalEvaluation::evaluate().
isNegative()
template<typename Number> bool carl::Interval< Number >::isNegative () const inline
Returns
true, if it this interval contains only negative values.
Definition at line 1107 of file Interval.h.
isOne()
template<typename Number> bool carl::Interval< Number >::isOne () const inline
Function which determines, if the interval is the one interval.
Returns
True if it is a pointinterval rooted at 1.
Definition at line 1085 of file Interval.h.
Referenced by carl::isOne().
isOpenInterval()
template<typename Number> bool carl::Interval< Number >::isOpenInterval () const inline
Function which determines, if the interval is open.
Returns
True if both bounds are STRICT.
Definition at line 1055 of file Interval.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber().
isPointInterval()
template<typename Number> bool carl::Interval< Number >::isPointInterval () const inline
Function which determines, if the interval is a pointinterval.
Returns
True if this is a pointinterval.
Definition at line 1045 of file Interval.h.
Referenced by carl::Interval< mpq_class >::isOne(), carl::Interval< mpq_class >::isZero(), and carl::RealAlgebraicNumber< carl::Number >::RealAlgebraicNumber().
isPositive()
template<typename Number> bool carl::Interval< Number >::isPositive () const inline
Returns
true, if it this interval contains only positive values.
Definition at line 1094 of file Interval.h.
isProperSubset()
template<typename Number> bool carl::Interval< Number >::isProperSubset (const Interval< Number > & rhs) const
Checks if the given interval is a proper subset of the calling interval.
Parameters
rhs Interval to be checked.
Returns
True if rhs is fully contained in this.
isSemiNegative()
template<typename Number> bool carl::Interval< Number >::isSemiNegative () const inline
Returns
true, if it this interval contains only negative values or 0.
Definition at line 1131 of file Interval.h.
Referenced by carl::Interval< mpq_class >::sampleInfty(), and carl::Interval< mpq_class >::sampleZero().
isSemiPositive()
template<typename Number> bool carl::Interval< Number >::isSemiPositive () const inline
Returns
true, if it this interval contains only positive values or 0.
Definition at line 1120 of file Interval.h.
Referenced by carl::Interval< mpq_class >::sampleInfty(), and carl::Interval< mpq_class >::sampleZero().
isSubset()
template<typename Number> bool carl::Interval< Number >::isSubset (const Interval< Number > & rhs) const
Checks if the given interval is a subset of the calling interval.
Parameters
rhs Interval to be checked.
Returns
True if rhs is contained in this.
isUnbounded()
template<typename Number> bool carl::Interval< Number >::isUnbounded () const inline
Function which determines, if the interval is unbounded.
Returns
True if at least one bound is INFTY.
Definition at line 1010 of file Interval.h.
isZero()
template<typename Number> bool carl::Interval< Number >::isZero () const inline
Function which determines, if the interval is the zero interval.
Returns
True if it is a pointinterval rooted at 0.
Definition at line 1075 of file Interval.h.
Referenced by carl::IntervalEvaluation::evaluate(), and carl::isZero().
log()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::log () const
Calculates the logarithm of the interval with respect to natural interval arithmetic.
Returns
Result.
Referenced by main().
log_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::log_assign ()
Calculates and assigns the logarithm of the interval with respect to natural interval arithmetic.
Referenced by main().
lower()
template<typename Number> const Number& carl::Interval< Number >::lower () const inline
The getter for the lower boundary of the interval.
Returns
Lower interval boundary.
Definition at line 821 of file Interval.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumberEvaluation::evaluateIR(), carl::Interval< mpq_class >::Interval(), carl::Interval< mpq_class >::isConsistent(), std::hash< carl::Interval< Number > >::operator()(), carl::realRootsThom(), carl::Interval< mpq_class >::sampleLeft(), carl::Interval< mpq_class >::sampleRight(), carl::policies< double, Interval >::sanitize(), carl::Interval< mpq_class >::set(), and carl::Interval< mpq_class >::setUpperBoundType().
lowerBoundType()
template<typename Number> BoundType carl::Interval< Number >::lowerBoundType () const inline
The getter for the lower bound type of the interval.
Returns
Lower bound type.
Definition at line 857 of file Interval.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::Interval< mpq_class >::Interval(), std::hash< carl::Interval< Number > >::operator()(), carl::realRootsThom(), and carl::Interval< mpq_class >::sampleLeft().
magnitude()
template<typename Number> Number carl::Interval< Number >::magnitude () const
Returns the magnitude of the interval.
Returns
Magnitude.
Referenced by main().
magnitude_assign()
template<typename Number> void carl::Interval< Number >::magnitude_assign ()
Computes and assigns the magnitude of the interval.
meets()
template<typename Number> bool carl::Interval< Number >::meets (const Number & n) const
Checks if the interval meets the given value, that is if the given value is contained in the closed interval defined by the bounds.
Parameters
val Value to be checked.
Returns
True if val is fully contained in this.
mul()
template<typename Number> Interval<Number> carl::Interval< Number >::mul (const Interval< Number > & rhs) const
Multiplies two intervals according to natural interval arithmetic.
Parameters
rhs Interval.
Returns
Result.
mul_assign()
template<typename Number> void carl::Interval< Number >::mul_assign (const Interval< Number > & rhs)
operator=()
template<typename Number> Interval<Number>& carl::Interval< Number >::operator= (const Interval< Number > & rhs) inline
The assignment operator.
Parameters
rhs Source interval.
Returns
Definition at line 964 of file Interval.h.
pow()
template<typename Number> Interval<Number> carl::Interval< Number >::pow (uint exp) const
Calculates the power of the interval with respect to natural interval arithmetic.
Parameters
exp Exponent.
Returns
Result.
Referenced by carl::IntervalEvaluation::evaluate().
pow_assign()
template<typename Number> void carl::Interval< Number >::pow_assign (uint exp)
Calculates and assigns the power of the interval with respect to natural interval arithmetic.
Parameters
exp Exponent.
rContent()
template<typename Number> BoostInterval& carl::Interval< Number >::rContent () inline
Returns a reference to the included boost interval.
Returns
Boost interval reference.
Definition at line 839 of file Interval.h.
reciprocal()
template<typename Number> bool carl::Interval< Number >::reciprocal (Interval< Number > & a, Interval< Number > & b) const
Calculates the multiplicative inverse of an interval with respect to natural interval arithmetic.
Parameters
a Result a.
b Result b.
Returns
True, if split occured.
root()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::root (int deg) const
Calculates the nth root of the interval with respect to natural interval arithmetic.
Parameters
deg Degree.
Returns
Result.
Referenced by carl::VarSolutionFormula< carl::Polynomial >::addRoot().
root_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::root_assign (unsigned deg)
Calculates and assigns the nth root of the interval with respect to natural interval arithmetic.
Parameters
deg Degree.
sample()
template<typename Number> Number carl::Interval< Number >::sample (bool _includingBounds = true) const
Searches for some point in this interval, preferably near the midpoint and with a small representation.
Checks the integers next to the midpoint, uses the midpoint if both are outside.
Returns
Some point within this interval.
Referenced by carl::SimpleNewton< Polynomial >::contract(), and carl::sampleBetween().
sample_assign()
template<typename Number> void carl::Interval< Number >::sample_assign ()
Searches for some point in this interval, preferably near the midpoint and with a small representation and assigns this interval the calculated point.
sampleInfty()
template<typename Number> Number carl::Interval< Number >::sampleInfty () const inline
Searches for some point in this interval, preferably far aways from zero and with a small representation.
Checks the integer next to the right endpoint if the interval is semi-positive. Checks the integer next to the left endpoint if the interval is semi-negative. Uses zero otherwise.
Returns
Some point within this interval.
Definition at line 1290 of file Interval.h.
Referenced by carl::sampleBetween().
sampleLeft()
template<typename Number> Number carl::Interval< Number >::sampleLeft () const inline
Searches for some point in this interval, preferably near the left endpoint and with a small representation.
Checks the integer next to the left endpoint, uses the midpoint if it is outside.
Returns
Some point within this interval.
Definition at line 1250 of file Interval.h.
Referenced by carl::sampleBetween(), carl::Interval< mpq_class >::sampleInfty(), and carl::Interval< mpq_class >::sampleZero().
sampleRight()
template<typename Number> Number carl::Interval< Number >::sampleRight () const inline
Searches for some point in this interval, preferably near the right endpoint and with a small representation.
Checks the integer next to the right endpoint, uses the midpoint if it is outside.
Returns
Some point within this interval.
Definition at line 1263 of file Interval.h.
Referenced by carl::sampleBetween(), carl::Interval< mpq_class >::sampleInfty(), and carl::Interval< mpq_class >::sampleZero().
sampleSB()
template<typename Number> Number carl::Interval< Number >::sampleSB (bool _includingBounds = true) const
Searches for some point in this interval, preferably near the midpoint and with a small representation.
Uses a binary search based on the Stern-Brocot tree starting from the integer below the midpoint.
Returns
Some point within this interval.
sampleZero()
template<typename Number> Number carl::Interval< Number >::sampleZero () const inline
Searches for some point in this interval, preferably near zero and with a small representation.
Checks the integer next to the left endpoint if the interval is semi-positive. Checks the integer next to the right endpoint if the interval is semi-negative. Uses zero otherwise.
Returns
Some point within this interval.
Definition at line 1278 of file Interval.h.
Referenced by carl::sampleBetween().
sanitize()
static void carl::policies< Number, Interval< Number > >::sanitize (Interval< Number > &) inline static inherited
Definition at line 93 of file Interval.h.
Referenced by carl::Interval< mpq_class >::Interval().
set() [1/2]
template<typename Number> void carl::Interval< Number >::set (const BoostInterval< Number > & content) inline
Advanced setter to modify both boundaries at once.
Parameters
lower Lower boundary.
upper Upper boundary.
Definition at line 981 of file Interval.h.
Referenced by carl::sampleBetween().
set() [2/2]
template<typename Number> void carl::Interval< Number >::set (const Number & lower, const Number & upper) inline
Advanced setter to modify both boundaries at once by passing a boost interval.
Parameters
content Boost interval.
Definition at line 991 of file Interval.h.
setLower()
template<typename Number> void carl::Interval< Number >::setLower (const Number & n) inline
The setter for the lower boundary of the interval.
Parameters
n Lower boundary.
Definition at line 875 of file Interval.h.
Referenced by carl::sampleBetween(), and carl::Interval< mpq_class >::setLowerBoundType().
setLowerBound()
template<typename Number> void carl::Interval< Number >::setLowerBound (const Number & n, BoundType b) inline
The setter for the lower boundary of the interval.
Parameters
n Lower boundary.
TODO: Fix this.
Definition at line 893 of file Interval.h.
setLowerBoundType()
template<typename Number> void carl::Interval< Number >::setLowerBoundType (BoundType b) inline
The setter for the lower bound type of the interval.
Parameters
b Lower bound type.
Definition at line 937 of file Interval.h.
Referenced by carl::policies< double, Interval >::sanitize().
setUpper()
template<typename Number> void carl::Interval< Number >::setUpper (const Number & n) inline
The setter for the upper boundary of the interval.
Parameters
n Upper boundary.
Definition at line 884 of file Interval.h.
Referenced by carl::sampleBetween(), and carl::Interval< mpq_class >::setUpperBoundType().
setUpperBound()
template<typename Number> void carl::Interval< Number >::setUpperBound (const Number & n, BoundType b) inline
The setter for the upper boundary of the interval.
Parameters
n Upper boundary.
TODO: Fix this.
Definition at line 915 of file Interval.h.
setUpperBoundType()
template<typename Number> void carl::Interval< Number >::setUpperBoundType (BoundType b) inline
The setter for the upper bound type of the interval.
Parameters
b Upper bound type.
Definition at line 950 of file Interval.h.
Referenced by carl::policies< double, Interval >::sanitize().
sgn()
template<typename Number> Sign carl::Interval< Number >::sgn () const inline
Determine whether the interval lays entirely left of 0 (NEGATIVE_SIGN), right of 0 (POSITIVE_SIGN) or contains 0 (ZERO_SIGN).
Returns
NEGATIVE_SIGN, if the interval lays entirely left of 0; POSITIVE_SIGN, if right of 0; or ZERO_SIGN, if contains 0.
shrink_by()
template<typename Number> void carl::Interval< Number >::shrink_by (const Number & width)
Shrinks the interval by the given value.
Parameters
width Width.
shrink_times()
template<typename Number> void carl::Interval< Number >::shrink_times (const Number & factor)
Shrinks the interval by a multiple of its width.
Parameters
factor Factor.
sin()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::sin () const
Calculates the sine of the given interval with respect to natural interval arithmetic.
Returns
Result.
sin_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::sin_assign ()
Calculates and assigns the sine of the given interval with respect to natural interval arithmetic.
sinh()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::sinh () const
Calculates the hyperbolic sine of the given interval with respect to natural interval arithmetic.
Returns
Result.
sinh_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::sinh_assign ()
Calculates and assigns the hyperbolic sine of the given interval with respect to natural interval arithmetic.
split() [1/2]
template<typename Number> std::pair<Interval<Number>, Interval<Number > > carl::Interval< Number >::split () const
Splits the interval into 2 equally sized parts (strict-weak-cut).
Returns
pair<interval, interval>.
split() [2/2]
template<typename Number> std::list<Interval<Number > > carl::Interval< Number >::split (unsigned n) const
Splits the interval into n equally sized parts (strict-weak-cut).
Returns
list<interval>.
sqrt()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::sqrt () const
Calculates the square root of the interval with respect to natural interval arithmetic.
Returns
Result.
sqrt_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::sqrt_assign ()
Calculates and assigns the square root of the interval with respect to natural interval arithmetic.
sub()
template<typename Number> Interval<Number> carl::Interval< Number >::sub (const Interval< Number > & rhs) const
Subtracts two intervals according to natural interval arithmetic.
Parameters
rhs Interval.
Returns
Result.
Referenced by carl::SimpleNewton< Polynomial >::contract().
sub_assign()
template<typename Number> void carl::Interval< Number >::sub_assign (const Interval< Number > & rhs)
symmetricDifference()
template<typename Number> bool carl::Interval< Number >::symmetricDifference (const Interval< Number > & rhs, Interval< Number > & resultA, Interval< Number > & resultB) const
Calculates the symmetric difference of two intervals in a set-theoretic manner (can result in two distinct intervals).
Parameters
rhs Righthand side.
resultA Result a.
resultB Result b.
Returns
True, if the result is twofold.
tan()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::tan () const
Calculates the tangent of the given interval with respect to natural interval arithmetic.
Returns
Result.
tan_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::tan_assign ()
Calculates and assigns the tangent of the given interval with respect to natural interval arithmetic.
tanh()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> Interval<Number> carl::Interval< Number >::tanh () const
Calculates the hyperbolic tangent of the given interval with respect to natural interval arithmetic.
Returns
Result.
tanh_assign()
template<typename Number> template<typename Num = Number, EnableIf< std::is_floating_point< Num >> = dummy> void carl::Interval< Number >::tanh_assign ()
Calculates and assigns the hyperbolic tangent of the given interval with respect to natural interval arithmetic.
toString()
template<typename Number> std::string carl::Interval< Number >::toString () const
Creates a string representation of the interval.
Returns
String representation of this.
unboundedInterval()
template<typename Number> static Interval<Number> carl::Interval< Number >::unboundedInterval () inline static
Method which returns the unbounded interval rooted at 0.
Returns
Unbounded interval.
Definition at line 785 of file Interval.h.
unite()
template<typename Number> bool carl::Interval< Number >::unite (const Interval< Number > & rhs, Interval< Number > & resultA, Interval< Number > & resultB) const
Unites two intervals in a set-theoretic manner (can result in two distinct intervals).
Parameters
rhs Righthand side.
resultA Result a.
resultB Result b.
Returns
True, if the result is twofold.
Referenced by carl::VarSolutionFormula< carl::Polynomial >::addRoot(), carl::SimpleNewton< Polynomial >::contract(), and carl::VarSolutionFormula< carl::Polynomial >::evaluate().
upper()
template<typename Number> const Number& carl::Interval< Number >::upper () const inline
The getter for the upper boundary of the interval.
Returns
Upper interval boundary.
Definition at line 830 of file Interval.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::RealAlgebraicNumberEvaluation::evaluateIR(), carl::Interval< mpq_class >::Interval(), carl::Interval< mpq_class >::isConsistent(), std::hash< carl::Interval< Number > >::operator()(), carl::realRootsThom(), carl::Interval< mpq_class >::sampleLeft(), carl::Interval< mpq_class >::sampleRight(), carl::policies< double, Interval >::sanitize(), carl::Interval< mpq_class >::set(), and carl::Interval< mpq_class >::setLowerBoundType().
upperBoundType()
template<typename Number> BoundType carl::Interval< Number >::upperBoundType () const inline
The getter for the upper bound type of the interval.
Returns
Upper bound type.
Definition at line 866 of file Interval.h.
Referenced by carl::RealAlgebraicNumber< carl::Number >::containedIn(), carl::Interval< mpq_class >::Interval(), std::hash< carl::Interval< Number > >::operator()(), carl::realRootsThom(), and carl::Interval< mpq_class >::sampleRight().
zeroInterval()
template<typename Number> static Interval<Number> carl::Interval< Number >::zeroInterval () inline static
Method which returns the pointinterval rooted at 0.
Returns
Pointinterval(0).
Definition at line 803 of file Interval.h.
Friends And Related Function Documentation
operator<<
template<typename Number> std::ostream& operator<< (std::ostream & str, const Interval< Number > & i) friend
Operator which passes a string representation of this to the given ostream.
Parameters
str The ostream.
i The interval.
Returns
A reference to ostream.
Definition at line 1391 of file Interval.h.
Field Documentation
mContent
template<typename Number> BoostInterval carl::Interval< Number >::mContent protected
Definition at line 165 of file Interval.h.
Referenced by carl::Interval< mpq_class >::center(), carl::Interval< mpq_class >::content(), carl::Interval< mpq_class >::Interval(), carl::Interval< mpq_class >::isEmpty(), carl::Interval< mpq_class >::isNegative(), carl::Interval< mpq_class >::isPointInterval(), carl::Interval< mpq_class >::isPositive(), carl::Interval< mpq_class >::isSemiNegative(), carl::Interval< mpq_class >::isSemiPositive(), carl::Interval< mpq_class >::lower(), carl::Interval< mpq_class >::operator=(), carl::Interval< mpq_class >::rContent(), carl::Interval< mpq_class >::set(), carl::Interval< mpq_class >::setLower(), carl::Interval< mpq_class >::setLowerBound(), carl::Interval< mpq_class >::setUpperBound(), and carl::Interval< mpq_class >::upper().
mLowerBoundType
template<typename Number> BoundType carl::Interval< Number >::mLowerBoundType = BoundType::STRICT protected
Definition at line 166 of file Interval.h.
Referenced by carl::Interval< mpq_class >::Interval(), carl::Interval< mpq_class >::isEmpty(), carl::Interval< mpq_class >::isPositive(), carl::Interval< mpq_class >::lowerBoundType(), carl::Interval< mpq_class >::operator=(), carl::Interval< mpq_class >::setLowerBound(), carl::Interval< mpq_class >::setLowerBoundType(), and carl::Interval< mpq_class >::setUpperBound().
mUpperBoundType
template<typename Number> BoundType carl::Interval< Number >::mUpperBoundType = BoundType::STRICT protected
Definition at line 167 of file Interval.h.
Referenced by carl::Interval< mpq_class >::Interval(), carl::Interval< mpq_class >::isClosedInterval(), carl::Interval< mpq_class >::isEmpty(), carl::Interval< mpq_class >::isHalfBounded(), carl::Interval< mpq_class >::isInfinite(), carl::Interval< mpq_class >::isNegative(), carl::Interval< mpq_class >::isOpenInterval(), carl::Interval< mpq_class >::isUnbounded(), carl::Interval< mpq_class >::operator=(), carl::Interval< mpq_class >::setLowerBound(), carl::Interval< mpq_class >::setUpperBound(), carl::Interval< mpq_class >::setUpperBoundType(), and carl::Interval< mpq_class >::upperBoundType().
The documentation for this class was generated from the following file:
carl/interval/Interval.h