carl: carl::ModelValue< Rational, Poly > Class Template Reference
carl::ModelValue< Rational, Poly > Class Template Reference
Represent a sum type/variant over the different kinds of values that can be assigned to the different kinds of variables that exist in CARL and to use them in a more uniform way, e.g.
#include <ModelValue.h>
Data Structures
struct VariantCaller
struct VariantExtractor
Public Member Functions
ModelValue ()=default
Default constructor.
template<typename T , typename T2 = typename std::enable_if<convertible_to_variant<T, Super>::value, T>::type>
ModelValue (const T &_t)
Initialize the Assignment from some valid type of the underlying variant.
template<typename ... Args>
ModelValue (const boost::variant< Args... > &variant)
ModelValue (const MultivariateRoot< Poly > &mr)
template<typename T >
ModelValue & operator= (const T &_t)
Assign some value to the underlying variant.
template<typename ... Args>
ModelValue & operator= (const boost::variant< Args... > &variant)
ModelValue & operator= (const MultivariateRoot< Poly > &mr)
template<typename F , typename Return = void>
Return visit (F &&f) const
bool isBool () const
bool isRational () const
bool isSqrtEx () const
bool isRAN () const
bool isBVValue () const
bool isSortValue () const
bool isUFModel () const
bool isPlusInfinity () const
bool isMinusInfinity () const
bool isSubstitution () const
bool asBool () const
const Rational & asRational () const
const SqrtEx< Poly > & asSqrtEx () const
const RealAlgebraicNumber< Rational > & asRAN () const
const carl::BVValue & asBVValue () const
const SortValue & asSortValue () const
const UFModel & asUFModel () const
UFModel & asUFModel ()
const InfinityValue & asInfinity () const
const ModelSubstitutionPtr< Rational, Poly > & asSubstitution () const
ModelSubstitutionPtr< Rational, Poly > & asSubstitution ()
Private Types
using Super = boost::variant< bool, Rational, SqrtEx< Poly >, RealAlgebraicNumber< Rational >, BVValue, SortValue, UFModel, InfinityValue, ModelSubstitutionPtr< Rational, Poly > >
Base type we are deriving from.
Private Attributes
Super mData
Friends
template<typename R , typename P >
std::ostream & operator<< (std::ostream &os, const ModelValue< R, P > &mv)
Detailed Description
template<typename Rational, typename Poly>
class carl::ModelValue< Rational, Poly >
Represent a sum type/variant over the different kinds of values that can be assigned to the different kinds of variables that exist in CARL and to use them in a more uniform way, e.g.
a plain "bool", "infinity", a "carl::RealAlgebraicNumber", a (bitvector) "carl::BVValue" etc.
Definition at line 19 of file ModelValue.h.
Member Typedef Documentation
Super
template<typename Rational, typename Poly> using carl::ModelValue< Rational, Poly >::Super = boost::variant<bool, Rational, SqrtEx<Poly>, RealAlgebraicNumber<Rational>, BVValue, SortValue, UFModel, InfinityValue, ModelSubstitutionPtr<Rational,Poly> > private
Base type we are deriving from.
Definition at line 69 of file ModelValue.h.
Constructor & Destructor Documentation
ModelValue() [1/4]
template<typename Rational, typename Poly> carl::ModelValue< Rational, Poly >::ModelValue () default
Default constructor.
ModelValue() [2/4]
template<typename Rational, typename Poly> template<typename T , typename T2 = typename std::enable_if<convertible_to_variant<T, Super>::value, T>::type> carl::ModelValue< Rational, Poly >::ModelValue (const T & _t) inline
Initialize the Assignment from some valid type of the underlying variant.
Definition at line 103 of file ModelValue.h.
ModelValue() [3/4]
template<typename Rational, typename Poly> template<typename ... Args> carl::ModelValue< Rational, Poly >::ModelValue (const boost::variant< Args... > & variant) inline
Definition at line 106 of file ModelValue.h.
ModelValue() [4/4]
template<typename Rational, typename Poly> carl::ModelValue< Rational, Poly >::ModelValue (const MultivariateRoot< Poly > & mr) inline
Definition at line 108 of file ModelValue.h.
Member Function Documentation
asBool()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::asBool () const inline
Returns
The stored value as a bool.
Definition at line 204 of file ModelValue.h.
Referenced by carl::SMTLIBStream::write().
asBVValue()
template<typename Rational, typename Poly> const carl::BVValue& carl::ModelValue< Rational, Poly >::asBVValue () const inline
Returns
The stored value as a real algebraic number.
Definition at line 236 of file ModelValue.h.
asInfinity()
template<typename Rational, typename Poly> const InfinityValue& carl::ModelValue< Rational, Poly >::asInfinity () const inline
Returns
The stored value as a infinity value.
Definition at line 263 of file ModelValue.h.
asRAN()
template<typename Rational, typename Poly> const RealAlgebraicNumber<Rational>& carl::ModelValue< Rational, Poly >::asRAN () const inline
Returns
The stored value as a real algebraic number.
Definition at line 228 of file ModelValue.h.
Referenced by carl::model::collectRANIR(), carl::model::evaluate(), carl::model::evaluateVarCompare(), and carl::model::substituteIn().
asRational()
template<typename Rational, typename Poly> const Rational& carl::ModelValue< Rational, Poly >::asRational () const inline
Returns
The stored value as a rational.
Definition at line 212 of file ModelValue.h.
Referenced by carl::model::evaluate(), carl::model::evaluateVarCompare(), carl::model::substituteIn(), and carl::SMTLIBStream::write().
asSortValue()
template<typename Rational, typename Poly> const SortValue& carl::ModelValue< Rational, Poly >::asSortValue () const inline
Returns
The stored value as a sort value.
Definition at line 244 of file ModelValue.h.
Referenced by carl::model::evaluate().
asSqrtEx()
template<typename Rational, typename Poly> const SqrtEx<Poly>& carl::ModelValue< Rational, Poly >::asSqrtEx () const inline
Returns
The stored value as a square root expression.
Definition at line 220 of file ModelValue.h.
asSubstitution() [1/2]
template<typename Rational, typename Poly> const ModelSubstitutionPtr<Rational,Poly>& carl::ModelValue< Rational, Poly >::asSubstitution () const inline
Definition at line 268 of file ModelValue.h.
Referenced by carl::model::evaluateVarCompare(), carl::ModelSubstitution< Rational, Poly >::getModelValue(), carl::ModelValue< Rational, Poly >::VariantExtractor::operator()(), and carl::ModelValue< Rational, Poly >::operator=().
asSubstitution() [2/2]
template<typename Rational, typename Poly> ModelSubstitutionPtr<Rational,Poly>& carl::ModelValue< Rational, Poly >::asSubstitution () inline
Definition at line 272 of file ModelValue.h.
asUFModel() [1/2]
template<typename Rational, typename Poly> const UFModel& carl::ModelValue< Rational, Poly >::asUFModel () const inline
Returns
The stored value as a uninterpreted function model.
Definition at line 252 of file ModelValue.h.
Referenced by carl::model::evaluate().
asUFModel() [2/2]
template<typename Rational, typename Poly> UFModel& carl::ModelValue< Rational, Poly >::asUFModel () inline
Definition at line 256 of file ModelValue.h.
isBool()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isBool () const inline
Returns
true, if the stored value is a bool.
Definition at line 138 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asBool(), and carl::SMTLIBStream::write().
isBVValue()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isBVValue () const inline
Returns
true, if the stored value is a bitvector literal.
Definition at line 166 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asBVValue().
isMinusInfinity()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isMinusInfinity () const inline
Returns
true, if the stored value is -infinity.
Definition at line 193 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asInfinity().
isPlusInfinity()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isPlusInfinity () const inline
Returns
true, if the stored value is +infinity.
Definition at line 187 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asInfinity().
isRAN()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isRAN () const inline
Returns
true, if the stored value is a real algebraic number.
Definition at line 159 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asRAN(), carl::model::collectRANIR(), carl::model::evaluate(), carl::model::evaluateVarCompare(), and carl::model::substituteIn().
isRational()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isRational () const inline
Returns
true, if the stored value is a rational.
Definition at line 145 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asRational(), carl::model::evaluate(), carl::model::evaluateVarCompare(), carl::model::substituteIn(), and carl::SMTLIBStream::write().
isSortValue()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isSortValue () const inline
Returns
true, if the stored value is a sort value.
Definition at line 173 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asSortValue(), and carl::model::evaluate().
isSqrtEx()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isSqrtEx () const inline
Returns
true, if the stored value is a square root expression.
Definition at line 152 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asSqrtEx().
isSubstitution()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isSubstitution () const inline
Definition at line 197 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asSubstitution(), carl::model::evaluateVarCompare(), and carl::ModelSubstitution< Rational, Poly >::getModelValue().
isUFModel()
template<typename Rational, typename Poly> bool carl::ModelValue< Rational, Poly >::isUFModel () const inline
Returns
true, if the stored value is a uninterpreted function model.
Definition at line 180 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asUFModel().
operator=() [1/3]
template<typename Rational, typename Poly> template<typename T > ModelValue& carl::ModelValue< Rational, Poly >::operator= (const T & _t) inline
Assign some value to the underlying variant.
Parameters
t Some value.
Returns
*this.
Definition at line 116 of file ModelValue.h.
operator=() [2/3]
template<typename Rational, typename Poly> template<typename ... Args> ModelValue& carl::ModelValue< Rational, Poly >::operator= (const boost::variant< Args... > & variant) inline
Definition at line 121 of file ModelValue.h.
operator=() [3/3]
template<typename Rational, typename Poly> ModelValue& carl::ModelValue< Rational, Poly >::operator= (const MultivariateRoot< Poly > & mr) inline
Definition at line 125 of file ModelValue.h.
visit()
template<typename Rational, typename Poly> template<typename F , typename Return = void> Return carl::ModelValue< Rational, Poly >::visit (F && f) const inline
Definition at line 131 of file ModelValue.h.
Friends And Related Function Documentation
operator<<
template<typename Rational, typename Poly> template<typename R , typename P > std::ostream& operator<< (std::ostream & os, const ModelValue< R, P > & mv) friend
Definition at line 311 of file ModelValue.h.
Field Documentation
mData
template<typename Rational, typename Poly> Super carl::ModelValue< Rational, Poly >::mData private
Definition at line 71 of file ModelValue.h.
Referenced by carl::ModelValue< Rational, Poly >::asBool(), carl::ModelValue< Rational, Poly >::asBVValue(), carl::ModelValue< Rational, Poly >::asInfinity(), carl::ModelValue< Rational, Poly >::asRAN(), carl::ModelValue< Rational, Poly >::asRational(), carl::ModelValue< Rational, Poly >::asSortValue(), carl::ModelValue< Rational, Poly >::asSqrtEx(), carl::ModelValue< Rational, Poly >::asSubstitution(), carl::ModelValue< Rational, Poly >::asUFModel(), carl::ModelValue< Rational, Poly >::isBool(), carl::ModelValue< Rational, Poly >::isBVValue(), carl::ModelValue< Rational, Poly >::isMinusInfinity(), carl::ModelValue< Rational, Poly >::isPlusInfinity(), carl::ModelValue< Rational, Poly >::isRAN(), carl::ModelValue< Rational, Poly >::isRational(), carl::ModelValue< Rational, Poly >::isSortValue(), carl::ModelValue< Rational, Poly >::isSqrtEx(), carl::ModelValue< Rational, Poly >::isSubstitution(), carl::ModelValue< Rational, Poly >::isUFModel(), carl::ModelValue< Rational, Poly >::operator=(), and carl::ModelValue< Rational, Poly >::visit().
The documentation for this class was generated from the following file:
carl/formula/model/ModelValue.h