carl: carl::Term< Coefficient > Class Template Reference
carl::Term< Coefficient > Class Template Reference
Polynomials » Multivariate Represented Polynomials
Represents a single term, that is a numeric coefficient and a monomial.
#include <Term.h>
Public Member Functions
Term ()=default
Default constructor.
Term (const Coefficient &c)
Constructs a term of value .
Term (Variable v)
Constructs a term of value .
Term (Monomial::Arg m)
Constructs a term of value .
Term (Monomial::Arg &&m)
Constructs a term of value .
Term (const Coefficient &c, Monomial::Arg m)
Constructs a term of value .
Term (Coefficient &&c, Monomial::Arg &&m)
Constructs a term of value .
Term (const Coefficient &c, Variable v, uint e)
Constructs a term of value .
Coefficient & coeff ()
Get the coefficient.
const Coefficient & coeff () const
Monomial::Arg & monomial ()
Get the monomial.
const Monomial::Arg & monomial () const
uint tdeg () const
Gives the total degree, i.e.
bool isZero () const
Checks whether the term is zero.
bool isOne () const
Checks whether the term equals one.
bool isConstant () const
Checks whether the monomial is a constant.
bool integerValued () const
bool isLinear () const
Checks whether the monomial has exactly the degree one.
std::size_t getNrVariables () const
std::size_t complexity () const
bool has (Variable v) const
bool hasNoOtherVariable (Variable v) const
Checks if the monomial is either a constant or the only variable occuring is the variable v.
bool isSingleVariable () const
Variable getSingleVariable () const
For terms with exactly one variable, get this variable.
bool isSquare () const
Checks if the term is a square.
void clear ()
Set the term to zero with the canonical representation.
void negate ()
Negates the term by negating the coefficient.
Term divide (const Coefficient &c) const
bool divide (const Coefficient &c, Term &res) const
bool divide (Variable v, Term &res) const
bool divide (const Monomial::Arg &m, Term &res) const
bool divide (const Term &t, Term &res) const
Term calcLcmAndDivideBy (const Monomial::Arg &m) const
bool sqrt (Term &res) const
Calculates the square root of this term.
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
bool divisible (const Term &t) const
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy>
bool divisible (const Term &t) const
Term derivative (Variable v) const
Definiteness definiteness () const
Term substitute (const std::map< Variable, Coefficient > &substitutions) const
Term substitute (const std::map< Variable, Term< Coefficient >> &substitutions) const
Coefficient evaluate (const std::map< Variable, Coefficient > &map) const
template<bool gatherCoeff, typename CoeffType >
void gatherVarInfo (Variable var, VariableInformation< gatherCoeff, CoeffType > &varinfo) const
template<bool gatherCoeff, typename CoeffType >
void gatherVarInfo (VariablesInformation< gatherCoeff, CoeffType > &varinfo) const
void gatherVariables (std::set< Variable > &variables) const
Term pow (uint exp) const
template<typename C = Coefficient, DisableIf< is_interval< C >> = dummy>
std::string toString (bool infix=true, bool friendlyVarNames=true) const
template<typename C = Coefficient, EnableIf< is_interval< C >> = dummy>
std::string toString (bool infix=true, bool friendlyVarNames=true) const
bool isConsistent () const
Static Public Member Functions
static bool monomialEqual (const Term &lhs, const Term &rhs)
Checks if two terms have the same monomial.
static bool monomialEqual (const std::shared_ptr< const Term > &lhs, const std::shared_ptr< const Term > &rhs)
static bool monomialLess (const Term &lhs, const Term &rhs)
static bool monomialLess (const std::shared_ptr< const Term > &lhs, const std::shared_ptr< const Term > &rhs)
static Term gcd (const std::shared_ptr< const Term > &t1, const std::shared_ptr< const Term > &t2)
Calculates the gcd of (t1, t2).
static Term gcd (const Term &t1, const Term &t2)
Calculates the gcd of (t1, t2).
Private Types
using CoefficientType = Coefficient
Private Attributes
CoefficientType mCoeff = CoefficientType(constant_zero<Coefficient>::get())
Monomial::Arg mMonomial
Friends
template<typename Coeff >
std::ostream & operator<< (std::ostream &os, const Term< Coeff > &rhs)
Streaming operator for Term.
Division operators
template<typename Coeff >
const Term< Coeff > operator/ (const Term< Coeff > &lhs, uint rhs)
Perform a division involving a term.
Detailed Description
template<typename Coefficient>
class carl::Term< Coefficient >
Represents a single term, that is a numeric coefficient and a monomial.
Definition at line 32 of file Term.h.
Member Typedef Documentation
CoefficientType
template<typename Coefficient> using carl::Term< Coefficient >::CoefficientType = Coefficient private
Definition at line 34 of file Term.h.
Constructor & Destructor Documentation
Term() [1/8]
template<typename Coefficient> carl::Term< Coefficient >::Term () default
Default constructor.
Constructs a term of value zero.
Referenced by carl::Term< typename Polynomial::CoeffType >::pow().
Term() [2/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (const Coefficient & c) explicit
Constructs a term of value .
Parameters
c Coefficient.
Term() [3/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (Variable v) explicit
Constructs a term of value .
Parameters
v Variable.
Term() [4/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (Monomial::Arg m) explicit
Constructs a term of value .
Parameters
m Monomial pointer.
Term() [5/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (Monomial::Arg && m) explicit
Constructs a term of value .
Parameters
m Monomial pointer.
Term() [6/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (const Coefficient & c, Monomial::Arg m)
Constructs a term of value .
Parameters
c Coefficient.
m Monomial pointer.
Term() [7/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (Coefficient && c, Monomial::Arg && m)
Constructs a term of value .
Parameters
c Coefficient.
m Monomial pointer.
Term() [8/8]
template<typename Coefficient> carl::Term< Coefficient >::Term (const Coefficient & c, Variable v, uint e)
Constructs a term of value .
Parameters
c Coefficient.
v Variable.
e Exponent.
Member Function Documentation
calcLcmAndDivideBy()
template<typename Coefficient> Term carl::Term< Coefficient >::calcLcmAndDivideBy (const Monomial::Arg & m) const
clear()
template<typename Coefficient> void carl::Term< Coefficient >::clear () inline
Set the term to zero with the canonical representation.
Definition at line 214 of file Term.h.
Referenced by carl::operator*=().
coeff() [1/2]
template<typename Coefficient> Coefficient& carl::Term< Coefficient >::coeff () inline
Get the coefficient.
Returns
Coefficient.
Definition at line 89 of file Term.h.
Referenced by carl::ReductorEntry< Polynomial >::addCoefficient(), carl::formula::symmetry::GraphBuilder< Poly >::addTerm(), carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::addTerm(), carl::IntervalEvaluation::evaluate(), carl::GiNaCConverter::operator()(), carl::ConstructorPrinter::operator()(), std::hash< carl::Term< Coefficient > >::operator()(), carl::operator*=(), carl::operator-(), carl::Term< typename Polynomial::CoeffType >::pow(), carl::ConvertTo< C >::term(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
coeff() [2/2]
template<typename Coefficient> const Coefficient& carl::Term< Coefficient >::coeff () const inline
Definition at line 92 of file Term.h.
complexity()
template<typename Coefficient> std::size_t carl::Term< Coefficient >::complexity () const inline
Returns
An approximation of the complexity of this monomial.
Definition at line 166 of file Term.h.
definiteness()
template<typename Coefficient> Definiteness carl::Term< Coefficient >::definiteness () const
derivative()
template<typename Coefficient> Term carl::Term< Coefficient >::derivative (Variable v) const
divide() [1/5]
template<typename Coefficient> Term carl::Term< Coefficient >::divide (const Coefficient & c) const
Parameters
c a non-zero coefficient.
Returns
Referenced by carl::IdealDatastructureVector< PolynomialInIdeal >::getDivisor().
divide() [2/5]
template<typename Coefficient> bool carl::Term< Coefficient >::divide (const Coefficient & c, Term< Coefficient > & res) const
divide() [3/5]
template<typename Coefficient> bool carl::Term< Coefficient >::divide (Variable v, Term< Coefficient > & res) const
divide() [4/5]
template<typename Coefficient> bool carl::Term< Coefficient >::divide (const Monomial::Arg & m, Term< Coefficient > & res) const
divide() [5/5]
template<typename Coefficient> bool carl::Term< Coefficient >::divide (const Term< Coefficient > & t, Term< Coefficient > & res) const
divisible() [1/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> bool carl::Term< Coefficient >::divisible (const Term< Coefficient > & t) const
divisible() [2/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy> bool carl::Term< Coefficient >::divisible (const Term< Coefficient > & t) const
evaluate()
template<typename Coefficient> Coefficient carl::Term< Coefficient >::evaluate (const std::map< Variable, Coefficient > & map) const
gatherVariables()
template<typename Coefficient> void carl::Term< Coefficient >::gatherVariables (std::set< Variable > & variables) const inline
Definition at line 274 of file Term.h.
gatherVarInfo() [1/2]
template<typename Coefficient> template<bool gatherCoeff, typename CoeffType > void carl::Term< Coefficient >::gatherVarInfo (Variable var, VariableInformation< gatherCoeff, CoeffType > & varinfo) const
gatherVarInfo() [2/2]
template<typename Coefficient> template<bool gatherCoeff, typename CoeffType > void carl::Term< Coefficient >::gatherVarInfo (VariablesInformation< gatherCoeff, CoeffType > & varinfo) const
gcd() [1/2]
template<typename Coefficient> static Term carl::Term< Coefficient >::gcd (const std::shared_ptr< const Term< Coefficient > > & t1, const std::shared_ptr< const Term< Coefficient > > & t2) static
Calculates the gcd of (t1, t2).
If t1 or t2 are not set, undefined. If t1 or t2 is zero, undefined.
Parameters
t1 first term
t2 second term
Returns
gcd(t1,t2);
gcd() [2/2]
template<typename Coefficient> static Term carl::Term< Coefficient >::gcd (const Term< Coefficient > & t1, const Term< Coefficient > & t2) static
Calculates the gcd of (t1, t2).
If t1 or t2 is zero, undefined.
Parameters
t1 first term
t2 second term
Returns
gcd(t1,t2)
getNrVariables()
template<typename Coefficient> std::size_t carl::Term< Coefficient >::getNrVariables () const inline
Returns
Definition at line 158 of file Term.h.
Referenced by carl::Term< typename Polynomial::CoeffType >::getSingleVariable().
getSingleVariable()
template<typename Coefficient> Variable carl::Term< Coefficient >::getSingleVariable () const inline
For terms with exactly one variable, get this variable.
Returns
The only variable occuring in the term.
Definition at line 198 of file Term.h.
Referenced by carl::MultivariatePolynomial< Rational >::getSingleVariable().
has()
template<typename Coefficient> bool carl::Term< Coefficient >::has (Variable v) const inline
Parameters
v The variable to check for its occurrence.
Returns
true, if the variable occurs in this term.
Definition at line 175 of file Term.h.
hasNoOtherVariable()
template<typename Coefficient> bool carl::Term< Coefficient >::hasNoOtherVariable (Variable v) const inline
Checks if the monomial is either a constant or the only variable occuring is the variable v.
Parameters
v The variable which may occur.
Returns
true if no variable occurs, or just v occurs.
Definition at line 185 of file Term.h.
integerValued()
template<typename Coefficient> bool carl::Term< Coefficient >::integerValued () const inline
Returns
true, if the image of this term is integer-valued.
Definition at line 141 of file Term.h.
isConsistent()
template<typename Coefficient> bool carl::Term< Coefficient >::isConsistent () const
isConstant()
template<typename Coefficient> bool carl::Term< Coefficient >::isConstant () const inline
Checks whether the monomial is a constant.
Returns
Definition at line 134 of file Term.h.
Referenced by carl::Term< typename Polynomial::CoeffType >::isOne(), and std::hash< carl::Term< Coefficient > >::operator()().
isLinear()
template<typename Coefficient> bool carl::Term< Coefficient >::isLinear () const inline
Checks whether the monomial has exactly the degree one.
Returns
Definition at line 150 of file Term.h.
isOne()
template<typename Coefficient> bool carl::Term< Coefficient >::isOne () const inline
Checks whether the term equals one.
Returns
Definition at line 127 of file Term.h.
isSingleVariable()
template<typename Coefficient> bool carl::Term< Coefficient >::isSingleVariable () const inline
Definition at line 190 of file Term.h.
isSquare()
template<typename Coefficient> bool carl::Term< Coefficient >::isSquare () const inline
Checks if the term is a square.
Returns
If this is square.
Definition at line 207 of file Term.h.
isZero()
template<typename Coefficient> bool carl::Term< Coefficient >::isZero () const inline
Checks whether the term is zero.
Returns
Definition at line 119 of file Term.h.
Referenced by carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::addTerm(), carl::ReductorEntry< Polynomial >::empty(), carl::Reductor< InputPolynomial, PolynomialInIdeal, Datastructure, Configuration >::reduce(), carl::ReductorEntry< Polynomial >::ReductorEntry(), and carl::ReductorEntry< Polynomial >::removeLeadingTerm().
monomial() [1/2]
template<typename Coefficient> Monomial::Arg& carl::Term< Coefficient >::monomial () inline
Get the monomial.
Returns
Monomial.
Definition at line 100 of file Term.h.
Referenced by carl::ReductorEntry< Polynomial >::addCoefficient(), carl::formula::symmetry::GraphBuilder< Poly >::addTerm(), carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::addTerm(), carl::MonomialComparator< f, degreeOrdered >::compare(), carl::IntervalEvaluation::evaluate(), carl::GiNaCConverter::operator()(), carl::ConstructorPrinter::operator()(), std::hash< carl::Term< Coefficient > >::operator()(), carl::operator*=(), carl::operator-(), carl::ConvertTo< C >::term(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
monomial() [2/2]
template<typename Coefficient> const Monomial::Arg& carl::Term< Coefficient >::monomial () const inline
Definition at line 103 of file Term.h.
monomialEqual() [1/2]
template<typename Coefficient> static bool carl::Term< Coefficient >::monomialEqual (const Term< Coefficient > & lhs, const Term< Coefficient > & rhs) inline static
Checks if two terms have the same monomial.
Parameters
lhs First term.
rhs Second term.
Returns
If both terms have the same monomial.
Definition at line 330 of file Term.h.
Referenced by carl::Term< typename Polynomial::CoeffType >::monomialEqual().
monomialEqual() [2/2]
template<typename Coefficient> static bool carl::Term< Coefficient >::monomialEqual (const std::shared_ptr< const Term< Coefficient > > & lhs, const std::shared_ptr< const Term< Coefficient > > & rhs) inline static
Definition at line 334 of file Term.h.
monomialLess() [1/2]
template<typename Coefficient> static bool carl::Term< Coefficient >::monomialLess (const Term< Coefficient > & lhs, const Term< Coefficient > & rhs) inline static
Definition at line 340 of file Term.h.
Referenced by carl::Term< typename Polynomial::CoeffType >::monomialLess().
monomialLess() [2/2]
template<typename Coefficient> static bool carl::Term< Coefficient >::monomialLess (const std::shared_ptr< const Term< Coefficient > > & lhs, const std::shared_ptr< const Term< Coefficient > > & rhs) inline static
Definition at line 344 of file Term.h.
negate()
template<typename Coefficient> void carl::Term< Coefficient >::negate () inline
Negates the term by negating the coefficient.
Definition at line 223 of file Term.h.
Referenced by carl::IdealDatastructureVector< PolynomialInIdeal >::getDivisor().
pow()
template<typename Coefficient> Term carl::Term< Coefficient >::pow (uint exp) const inline
Definition at line 282 of file Term.h.
sqrt()
template<typename Coefficient> bool carl::Term< Coefficient >::sqrt (Term< Coefficient > & res) const
Calculates the square root of this term.
Returns true, iff the term is a square as checked by isSquare(). In that case, res will changed to be the square root. Otherwise, res is undefined.
Parameters
res Square root of this term.
Returns
If square root could be calculated.
substitute() [1/2]
template<typename Coefficient> Term carl::Term< Coefficient >::substitute (const std::map< Variable, Coefficient > & substitutions) const
substitute() [2/2]
template<typename Coefficient> Term carl::Term< Coefficient >::substitute (const std::map< Variable, Term< Coefficient >> & substitutions) const
tdeg()
template<typename Coefficient> uint carl::Term< Coefficient >::tdeg () const inline
Gives the total degree, i.e.
the sum of all exponents.
Returns
Total degree.
Definition at line 110 of file Term.h.
toString() [1/2]
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_interval< C >> = dummy> std::string carl::Term< Coefficient >::toString (bool infix = true, bool friendlyVarNames = true) const
toString() [2/2]
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_interval< C >> = dummy> std::string carl::Term< Coefficient >::toString (bool infix = true, bool friendlyVarNames = true) const
Friends And Related Function Documentation
operator/
template<typename Coefficient> template<typename Coeff > const Term<Coeff> operator/ (const Term< Coeff > & lhs, uint rhs) friend
Perform a division involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
operator<<
template<typename Coefficient> template<typename Coeff > std::ostream& operator<< (std::ostream & os, const Term< Coeff > & rhs) friend
Streaming operator for Term.
Parameters
os Output stream.
rhs Term.
Returns
os
Field Documentation
mCoeff
template<typename Coefficient> CoefficientType carl::Term< Coefficient >::mCoeff = CoefficientType(constant_zero<Coefficient>::get()) private
Definition at line 35 of file Term.h.
Referenced by carl::Term< typename Polynomial::CoeffType >::clear(), carl::Term< typename Polynomial::CoeffType >::coeff(), carl::Term< typename Polynomial::CoeffType >::integerValued(), carl::Term< typename Polynomial::CoeffType >::isOne(), carl::Term< typename Polynomial::CoeffType >::isSquare(), carl::Term< typename Polynomial::CoeffType >::isZero(), and carl::Term< typename Polynomial::CoeffType >::negate().
mMonomial
template<typename Coefficient> Monomial::Arg carl::Term< Coefficient >::mMonomial private
Definition at line 36 of file Term.h.
Referenced by carl::Term< typename Polynomial::CoeffType >::clear(), carl::Term< typename Polynomial::CoeffType >::complexity(), carl::Term< typename Polynomial::CoeffType >::gatherVariables(), carl::Term< typename Polynomial::CoeffType >::getNrVariables(), carl::Term< typename Polynomial::CoeffType >::getSingleVariable(), carl::Term< typename Polynomial::CoeffType >::has(), carl::Term< typename Polynomial::CoeffType >::hasNoOtherVariable(), carl::Term< typename Polynomial::CoeffType >::integerValued(), carl::Term< typename Polynomial::CoeffType >::isConstant(), carl::Term< typename Polynomial::CoeffType >::isLinear(), carl::Term< typename Polynomial::CoeffType >::isSingleVariable(), carl::Term< typename Polynomial::CoeffType >::isSquare(), carl::Term< typename Polynomial::CoeffType >::monomial(), carl::Term< typename Polynomial::CoeffType >::monomialEqual(), carl::Term< typename Polynomial::CoeffType >::monomialLess(), carl::Term< typename Polynomial::CoeffType >::pow(), and carl::Term< typename Polynomial::CoeffType >::tdeg().
The documentation for this class was generated from the following file:
carl/core/Term.h