carl: carl::logging::Logger Class Reference
carl::logging::Logger Class Reference
Main logger class.
#include <carlLogging.h>
Public Member Functions
bool has (const std::string &id) const noexcept
Check if a Sink with the given id has been installed.
void configure (const std::string &id, std::shared_ptr< Sink > sink)
Installs the given sink.
void configure (const std::string &id, const std::string &filename)
Installs a FileSink.
void configure (const std::string &id, std::ostream &os)
Installs a StreamSink.
Filter & filter (const std::string &id) noexcept
Retrieves the Filter for some Sink.
const std::shared_ptr< Formatter > & formatter (const std::string &id) noexcept
Retrieves the Formatter for some Sink.
void formatter (const std::string &id, std::shared_ptr< Formatter > fmt) noexcept
Overwrites the Formatter for some Sink.
void resetFormatter () noexcept
Reconfigures all Formatter objects.
void log (LogLevel level, const std::string &channel, const std::stringstream &ss, const RecordInfo &info)
Logs a message.
Static Public Member Functions
static Logger & getInstance ()
Returns the single instance of this class by reference.
Private Attributes
std::map< std::string, std::tuple< std::shared_ptr< Sink >, Filter, std::shared_ptr< Formatter > > > mData
Mapping from channels to associated logging classes.
std::mutex mMutex
Logging mutex to ensure thread-safe logging.
carl::Timer mTimer
Timer to track program runtime.
Detailed Description
Main logger class.
Definition at line 301 of file carlLogging.h.
Member Function Documentation
configure() [1/3]
void carl::logging::Logger::configure (const std::string & id, std::shared_ptr< Sink > sink) inline
Installs the given sink.
If a Sink with this name is already present, it is overwritten.
Parameters
id Sink identifier.
sink Sink.
Definition at line 325 of file carlLogging.h.
Referenced by configure(), formatter(), resetFormatter(), and carl::logging::setInitialLogLevel().
configure() [2/3]
void carl::logging::Logger::configure (const std::string & id, const std::string & filename) inline
Installs a FileSink.
Parameters
id Sink identifier.
filename Filename passed to the FileSink.
Definition at line 334 of file carlLogging.h.
configure() [3/3]
void carl::logging::Logger::configure (const std::string & id, std::ostream & os) inline
Installs a StreamSink.
Parameters
id Sink identifier.
os Output stream passed to the StreamSink.
Definition at line 342 of file carlLogging.h.
filter()
Filter& carl::logging::Logger::filter (const std::string & id) inline noexcept
Retrieves the Filter for some Sink.
Parameters
id Sink identifier.
Returns
Filter.
Definition at line 350 of file carlLogging.h.
Referenced by carl::logging::setInitialLogLevel().
formatter() [1/2]
const std::shared_ptr<Formatter>& carl::logging::Logger::formatter (const std::string & id) inline noexcept
Retrieves the Formatter for some Sink.
Parameters
id Sink identifier.
Returns
Formatter.
Definition at line 360 of file carlLogging.h.
formatter() [2/2]
void carl::logging::Logger::formatter (const std::string & id, std::shared_ptr< Formatter > fmt) inline noexcept
Overwrites the Formatter for some Sink.
Parameters
id Sink identifier.
fmt New Formatter.
Definition at line 370 of file carlLogging.h.
getInstance()
static Logger & carl::Singleton< Logger >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::logging::logger().
has()
bool carl::logging::Logger::has (const std::string & id) const inline noexcept
Check if a Sink with the given id has been installed.
Parameters
id Sink identifier.
Returns
If a Sink with this id is present.
Definition at line 316 of file carlLogging.h.
log()
void carl::logging::Logger::log (LogLevel level, const std::string & channel, const std::stringstream & ss, const RecordInfo & info) inline
Logs a message.
Parameters
level LogLevel.
channel Channel name.
ss Message to be logged.
info Auxiliary information.
Definition at line 392 of file carlLogging.h.
resetFormatter()
void carl::logging::Logger::resetFormatter () inline noexcept
Reconfigures all Formatter objects.
This should be done once after all configuration is finished.
Definition at line 380 of file carlLogging.h.
Referenced by carl::logging::setInitialLogLevel().
Field Documentation
mData
std::map<std::string, std::tuple<std::shared_ptr<Sink>, Filter, std::shared_ptr<Formatter> > > carl::logging::Logger::mData private
Mapping from channels to associated logging classes.
Definition at line 304 of file carlLogging.h.
Referenced by configure(), filter(), formatter(), has(), log(), and resetFormatter().
mMutex
std::mutex carl::logging::Logger::mMutex private
Logging mutex to ensure thread-safe logging.
Definition at line 306 of file carlLogging.h.
Referenced by configure(), and log().
mTimer
carl::Timer carl::logging::Logger::mTimer private
Timer to track program runtime.
Definition at line 308 of file carlLogging.h.
Referenced by log().
The documentation for this class was generated from the following file:
carl/core/carlLogging.h