carl: carl::MultivariatePolynomial< Coeff, Ordering, Policies > Class Template Reference
carl::MultivariatePolynomial< Coeff, Ordering, Policies > Class Template Reference
Polynomials » Multivariate Represented Polynomials
The general-purpose multivariate polynomial class.
#include <MultivariateGCD.h>
Public Types
enum ConstructorOperation { ConstructorOperation::ADD, ConstructorOperation::SUB, ConstructorOperation::MUL, ConstructorOperation::DIV }
using OrderedBy = Ordering
The ordering of the terms.
using TermType = Term< Coeff >
Type of the terms.
using MonomType = Monomial
Type of the monomials within the terms.
using CoeffType = Coeff
Type of the coefficients.
using Policy = Policies
Policies for this monomial.
using NumberType = typename UnderlyingNumberType< Coeff >::type
Number type within the coefficients.
using IntNumberType = typename IntegralType< NumberType >::type
Integer type associated with the number type.
using PolyType = MultivariatePolynomial< Coeff, Ordering, Policies >
using CACHE = std::vector< int >
The type of the cache. Multivariate polynomials do not need a cache, we set it to something.
using TermsType = std::vector< Term< Coeff > >
Type our terms vector.f.
template<typename C , typename T >
using EnableIfNotSame = typename std::enable_if<!std::is_same< C, T >::value, T >::type
template<bool gatherCoeff>
using VarInfo = VariableInformation< gatherCoeff, MultivariatePolynomial >
Public Member Functions
~MultivariatePolynomial () noexcept override=default
bool isUnivariateRepresented () const override
bool isMultivariateRepresented () const override
bool isOrdered () const
Check if the terms are ordered.
void makeOrdered () const
Ensure that the terms are ordered.
const Monomial::Arg & lmon () const
The leading monomial.
const Term< Coeff > & lterm () const
The leading term.
Term< Coeff > & lterm ()
const Coeff & lcoeff () const
Returns the coefficient of the leading term.
MultivariatePolynomial lcoeff (Variable::Arg var) const
Returns the leading coefficient with respect to the given variable.
std::size_t totalDegree () const
Calculates the max.
std::size_t degree (Variable::Arg var) const
Calculates the degree of this polynomial with respect to the given variable.
MultivariatePolynomial coeff (Variable::Arg var, std::size_t exp) const
Calculates the coefficient of var^exp.
bool isZero () const
Check if the polynomial is zero.
bool isOne () const
bool isConstant () const
Check if the polynomial is constant.
bool isLinear () const
Check if the polynomial is linear.
bool isNumber () const
Check if the polynomial is a number, i.e., a constant.
Definiteness definiteness (bool _fullEffort=true) const
Retrieves information about the definiteness of the polynomial.
auto sosDecomposition (bool not_trivial=false) const
size_t nrTerms () const
Calculate the number of terms.
size_t size () const
size_t complexity () const
const Term< Coeff > & trailingTerm () const
Give the last term according to Ordering.
Term< Coeff > & trailingTerm ()
bool hasConstantTerm () const
Check if the polynomial has a constant term that is not zero.
bool integerValued () const
const Coeff & constantPart () const
Retrieve the constant term of this polynomial or zero, if there is no constant term.
TermsType::const_iterator begin () const
TermsType::const_iterator end () const
TermsType::const_reverse_iterator rbegin () const
TermsType::const_reverse_iterator rend () const
TermsType::iterator eraseTerm (typename TermsType::iterator pos)
TermsType & getTerms ()
MultivariatePolynomial tail (bool makeFullyOrdered=false) const
For the polynomial p, the function calculates a polynomial p - lt(p).
MultivariatePolynomial & stripLT ()
Drops the leading term.
bool isVariable () const
Variable getSingleVariable () const
For terms with exactly one variable, get this variable.
const CoeffType & coefficient () const
const PolyType & polynomial () const
bool isUnivariate () const
Checks whether only one variable occurs.
bool isTsos () const
Checks whether the polynomial is a trivial sum of squares.
void gatherVariables (std::set< Variable > &vars) const
Iterates through all terms to find variables occuring in this polynomial.
std::set< Variable > gatherVariables () const
bool has (Variable::Arg v) const
bool isReducibleIdentity () const
void subtractProduct (const Term< Coeff > &factor, const MultivariatePolynomial &p)
Subtract a term times a polynomial from this polynomial.
void addTerm (const Term< Coeff > &term)
Adds a single term without using a TermAdditionManager or changing the ordering status.
template<typename C = Coeff, EnableIf< is_field< C >> = dummy>
MultivariatePolynomial divideBy (const Coeff &divisor) const
Divides the polynomial by the given coefficient.
template<typename C = Coeff, EnableIf< is_field< C >> = dummy>
bool divideBy (const MultivariatePolynomial &divisor, MultivariatePolynomial &quotient) const
Divides the polynomial by another polynomial.
DivisionResult< MultivariatePolynomial > divideBy (const MultivariatePolynomial &divisor) const
Calculating the quotient and the remainder, such that for a given polynomial p we have p = divisor * quotient + remainder.
MultivariatePolynomial quotient (const MultivariatePolynomial &divisor) const
Calculates the quotient.
MultivariatePolynomial remainder (const MultivariatePolynomial &divisor) const
Calculates the remainder.
MultivariatePolynomial prem (const MultivariatePolynomial &divisor, Variable::Arg var) const
MultivariatePolynomial derivative (Variable::Arg v, unsigned nth=1) const
bool sqrt (MultivariatePolynomial &res) const
Calculates the square of this multivariate polynomial if it is a square.
template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy>
Coeff coprimeFactor () const
template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy>
Coeff coprimeFactorWithoutConstant () const
MultivariatePolynomial coprimeCoefficients () const
MultivariatePolynomial normalize () const
For a polynomial p, returns p/lc(p)
void substituteIn (Variable::Arg var, const MultivariatePolynomial &value)
Replace the given variable by the given polynomial within this multivariate polynomial.
MultivariatePolynomial substitute (Variable::Arg var, const MultivariatePolynomial &value) const
Replace the given variable by the given value.
MultivariatePolynomial substitute (const std::map< Variable, MultivariatePolynomial > &substitutions) const
Replace all variables by a value given in their map.
template<typename SubstitutionType = Coeff>
MultivariatePolynomial substitute (const std::map< Variable, SubstitutionType > &substitutions) const
Replace all variables by a value given in their map.
MultivariatePolynomial substitute (const std::map< Variable, Term< Coeff >> &substitutions) const
Replace all variables by a Term in which the variable does not occur.
template<typename SubstitutionType = Coeff>
SubstitutionType evaluate (const std::map< Variable, SubstitutionType > &substitutions) const
Like substitute, but expects substitutions for all variables.
bool divides (const MultivariatePolynomial &b) const
MultivariatePolynomial coprimePart (const MultivariatePolynomial &q) const
Calculates the part ofthe Polynomial, that is coprime to q.
void square ()
MultivariatePolynomial pow (std::size_t exp) const
MultivariatePolynomial naive_pow (unsigned exp) const
std::string toString (bool infix=true, bool friendlyVarNames=true) const
MultivariatePolynomial< typename IntegralType< Coeff >::type, Ordering, Policies > toIntegerDomain () const
UnivariatePolynomial< Coeff > toUnivariatePolynomial () const
Convert a univariate polynomial that is currently (mis)represented by a 'MultivariatePolynomial' into a more appropiate 'UnivariatePolynomial' representation.
UnivariatePolynomial< MultivariatePolynomial > toUnivariatePolynomial (Variable::Arg mainVar) const
const Term< Coeff > & operator[] (unsigned index) const
MultivariatePolynomial mod (const typename IntegralType< Coeff >::type &modulo) const
template<bool gatherCoeff>
VariableInformation< gatherCoeff, MultivariatePolynomial > getVarInfo (Variable::Arg v) const
template<bool gatherCoeff>
VariablesInformation< gatherCoeff, MultivariatePolynomial > getVarInfo () const
template<typename C = Coeff, EnableIf< is_number< C >> = dummy>
Coeff numericContent () const
template<typename C = Coeff, DisableIf< is_number< C >> = dummy>
UnderlyingNumberType< C >::type numericContent () const
template<typename C = Coeff, EnableIf< is_number< C >> = dummy>
IntNumberType mainDenom () const
MultivariatePolynomial operator- () const
template<bool findConstantTerm = true, bool findLeadingTerm = true>
void makeMinimallyOrdered () const
Make sure that the terms are at least minimally ordered.
bool isConsistent () const
Asserts that this polynomial complies with the requirements and assumptions for MultivariatePolynomial objects.
Constructors
MultivariatePolynomial ()
MultivariatePolynomial (const MultivariatePolynomial< Coeff, Ordering, Policies > &p)
MultivariatePolynomial (MultivariatePolynomial< Coeff, Ordering, Policies > &&p)
MultivariatePolynomial & operator= (const MultivariatePolynomial &p)
MultivariatePolynomial & operator= (MultivariatePolynomial &&p) noexcept
MultivariatePolynomial (int c)
template<typename C = Coeff>
MultivariatePolynomial (EnableIfNotSame< C, sint > c)
template<typename C = Coeff>
MultivariatePolynomial (EnableIfNotSame< C, uint > c)
MultivariatePolynomial (const Coeff &c)
MultivariatePolynomial (Variable::Arg v)
MultivariatePolynomial (const Term< Coeff > &t)
MultivariatePolynomial (const std::shared_ptr< const Monomial > &m)
MultivariatePolynomial (const UnivariatePolynomial< MultivariatePolynomial< Coeff, Ordering, Policy >> &pol)
MultivariatePolynomial (const UnivariatePolynomial< Coeff > &p)
template<class OtherPolicies , DisableIf< std::is_same< Policies, OtherPolicies >> = dummy>
MultivariatePolynomial (const MultivariatePolynomial< Coeff, Ordering, OtherPolicies > &p)
MultivariatePolynomial (TermsType &&terms, bool duplicates=true, bool ordered=false)
MultivariatePolynomial (const TermsType &terms, bool duplicates=true, bool ordered=false)
MultivariatePolynomial (const std::initializer_list< Term< Coeff >> &terms)
MultivariatePolynomial (const std::initializer_list< Variable > &terms)
MultivariatePolynomial (const std::pair< ConstructorOperation, std::vector< MultivariatePolynomial >> &p)
MultivariatePolynomial (ConstructorOperation op, const std::vector< MultivariatePolynomial > &operands)
In-place addition operators
MultivariatePolynomial & operator+= (const MultivariatePolynomial &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const TermType &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const std::shared_ptr< const TermType > &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const Monomial::Arg &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (Variable::Arg rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const Coeff &rhs)
Add something to this polynomial and return the changed polynomial.
In-place subtraction operators
MultivariatePolynomial & operator-= (const MultivariatePolynomial &rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (const Term< Coeff > &rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (const Monomial::Arg &rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (Variable::Arg rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (const Coeff &rhs)
Subtract something from this polynomial and return the changed polynomial.
In-place multiplication operators
MultivariatePolynomial & operator*= (const MultivariatePolynomial &rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (const Term< Coeff > &rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (const Monomial::Arg &rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (const Coeff &rhs)
Multiply this polynomial with something and return the changed polynomial.
In-place division operators
MultivariatePolynomial & operator/= (const MultivariatePolynomial &rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (const Term< Coeff > &rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (const Monomial::Arg &rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (Variable::Arg rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (const Coeff &rhs)
Divide this polynomial by something and return the changed polynomial.
Static Public Member Functions
static MultivariatePolynomial SPolynomial (const MultivariatePolynomial &p, const MultivariatePolynomial &q)
Calculates the S-Polynomial.
static bool compareByLeadingTerm (const MultivariatePolynomial &p1, const MultivariatePolynomial &p2)
static bool compareByNrTerms (const MultivariatePolynomial &p1, const MultivariatePolynomial &p2)
Static Public Attributes
static TermAdditionManager< MultivariatePolynomial, Ordering > mTermAdditionManager
Private Member Functions
void makeMinimallyOrdered (typename TermsType::iterator &lterm, typename TermsType::iterator &cterm) const
Make sure that the terms are at least minimally ordered.
Private Attributes
TermsType mTerms
A vector of all terms.
bool mOrdered
Flag that indicates if the terms are ordered.
Friends
template<typename Polynomial , typename Order >
class TermAdditionManager
std::ostream & operator<< (std::ostream &os, ConstructorOperation op)
template<typename C , typename O , typename P >
std::ostream & operator<< (std::ostream &os, const MultivariatePolynomial< C, O, P > &rhs)
Streaming operator for multivariate polynomials.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
Division operators
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator/ (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a division involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator/ (const MultivariatePolynomial< C, O, P > &lhs, unsigned long rhs)
Perform a division involving a polynomial.
Detailed Description
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>>
class carl::MultivariatePolynomial< Coeff, Ordering, Policies >
The general-purpose multivariate polynomial class.
It is represented as a sum of terms, being a coefficient and a monomial.
A polynomial is always minimally ordered. By that, we mean that the leading term and the constant term (if there is any) are at the correct positions. For some operations, the terms may be fully ordered. isOrdered() checks if the polynomial is fully ordered while makeOrdered() makes the polynomial fully ordered.
Definition at line 19 of file MultivariateGCD.h.
Member Typedef Documentation
CACHE
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::CACHE = std::vector<int>
The type of the cache. Multivariate polynomials do not need a cache, we set it to something.
Definition at line 67 of file MultivariatePolynomial.h.
CoeffType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::CoeffType = Coeff
Type of the coefficients.
Definition at line 57 of file MultivariatePolynomial.h.
EnableIfNotSame
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename T > using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::EnableIfNotSame = typename std::enable_if<!std::is_same<C,T>::value,T>::type
Definition at line 72 of file MultivariatePolynomial.h.
IntNumberType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::IntNumberType = typename IntegralType<NumberType>::type
Integer type associated with the number type.
Definition at line 63 of file MultivariatePolynomial.h.
MonomType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MonomType = Monomial
Type of the monomials within the terms.
Definition at line 55 of file MultivariatePolynomial.h.
NumberType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::NumberType = typename UnderlyingNumberType<Coeff>::type
Number type within the coefficients.
Definition at line 61 of file MultivariatePolynomial.h.
OrderedBy
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::OrderedBy = Ordering
The ordering of the terms.
Definition at line 51 of file MultivariatePolynomial.h.
Policy
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::Policy = Policies
Policies for this monomial.
Definition at line 59 of file MultivariatePolynomial.h.
PolyType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::PolyType = MultivariatePolynomial<Coeff, Ordering, Policies>
Definition at line 65 of file MultivariatePolynomial.h.
TermsType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::TermsType = std::vector<Term<Coeff> >
Type our terms vector.f.
Definition at line 69 of file MultivariatePolynomial.h.
TermType
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::TermType = Term<Coeff>
Type of the terms.
Definition at line 53 of file MultivariatePolynomial.h.
VarInfo
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<bool gatherCoeff> using carl::MultivariatePolynomial< Coeff, Ordering, Policies >::VarInfo = VariableInformation<gatherCoeff, MultivariatePolynomial>
Definition at line 75 of file MultivariatePolynomial.h.
Member Enumeration Documentation
ConstructorOperation
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> enum carl::MultivariatePolynomial::ConstructorOperation strong
Enumerator
ADD
SUB
MUL
DIV
Definition at line 85 of file MultivariatePolynomial.h.
Constructor & Destructor Documentation
MultivariatePolynomial() [1/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial ()
MultivariatePolynomial() [2/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const MultivariatePolynomial< Coeff, Ordering, Policies > & p)
MultivariatePolynomial() [3/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (MultivariatePolynomial< Coeff, Ordering, Policies > && p)
MultivariatePolynomial() [4/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (int c) inline explicit
Definition at line 103 of file MultivariatePolynomial.h.
MultivariatePolynomial() [5/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (EnableIfNotSame< C, sint > c) explicit
MultivariatePolynomial() [6/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (EnableIfNotSame< C, uint > c) explicit
MultivariatePolynomial() [7/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const Coeff & c) explicit
MultivariatePolynomial() [8/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (Variable::Arg v) explicit
MultivariatePolynomial() [9/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const Term< Coeff > & t) explicit
MultivariatePolynomial() [10/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const std::shared_ptr< const Monomial > & m) explicit
MultivariatePolynomial() [11/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const UnivariatePolynomial< MultivariatePolynomial< Coeff, Ordering, Policy >> & pol) explicit
MultivariatePolynomial() [12/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const UnivariatePolynomial< Coeff > & p) explicit
MultivariatePolynomial() [13/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<class OtherPolicies , DisableIf< std::is_same< Policies, OtherPolicies >> = dummy> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const MultivariatePolynomial< Coeff, Ordering, OtherPolicies > & p) explicit
MultivariatePolynomial() [14/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (TermsType && terms, bool duplicates = true, bool ordered = false) explicit
MultivariatePolynomial() [15/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const TermsType & terms, bool duplicates = true, bool ordered = false) explicit
MultivariatePolynomial() [16/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const std::initializer_list< Term< Coeff >> & terms)
MultivariatePolynomial() [17/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const std::initializer_list< Variable > & terms)
MultivariatePolynomial() [18/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (const std::pair< ConstructorOperation, std::vector< MultivariatePolynomial< Coeff, Ordering, Policies > >> & p) explicit
MultivariatePolynomial() [19/19]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::MultivariatePolynomial (ConstructorOperation op, const std::vector< MultivariatePolynomial< Coeff, Ordering, Policies > > & operands) explicit
~MultivariatePolynomial()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::~MultivariatePolynomial () override default noexcept
Member Function Documentation
addTerm()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::addTerm (const Term< Coeff > & term)
Adds a single term without using a TermAdditionManager or changing the ordering status.
Parameters
term Term.
begin()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType::const_iterator carl::MultivariatePolynomial< Coeff, Ordering, Policies >::begin () const inline
Definition at line 316 of file MultivariatePolynomial.h.
Referenced by std::hash< carl::MultivariatePolynomial< C, O, P > >::operator()().
coeff()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coeff (Variable::Arg var, std::size_t exp) const inline
Calculates the coefficient of var^exp.
Parameters
var Variable.
exp Exponent.
Returns
Coefficient of var^exp.
Definition at line 213 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::lcoeff().
coefficient()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const CoeffType& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coefficient () const inline
Returns
Coefficient of the polynomial (this makes only sense for polynomials storing the gcd of all coefficients separately)
Definition at line 387 of file MultivariatePolynomial.h.
compareByLeadingTerm()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> static bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::compareByLeadingTerm (const MultivariatePolynomial< Coeff, Ordering, Policies > & p1, const MultivariatePolynomial< Coeff, Ordering, Policies > & p2) inline static
Definition at line 707 of file MultivariatePolynomial.h.
compareByNrTerms()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> static bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::compareByNrTerms (const MultivariatePolynomial< Coeff, Ordering, Policies > & p1, const MultivariatePolynomial< Coeff, Ordering, Policies > & p2) inline static
Definition at line 712 of file MultivariatePolynomial.h.
complexity()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::complexity () const inline
Returns
An approximation of the complexity of this polynomial.
Definition at line 288 of file MultivariatePolynomial.h.
constantPart()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Coeff& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::constantPart () const
Retrieve the constant term of this polynomial or zero, if there is no constant term.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluate(), and carl::SoSDecomposition().
coprimeCoefficients()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimeCoefficients () const
Returns
p * p.coprimeFactor()
See also
coprimeFactor()
coprimeFactor()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy> Coeff carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimeFactor () const
Returns
The lcm of the denominators of the coefficients in p divided by the gcd of numerators of the coefficients in p.
coprimeFactorWithoutConstant()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy> Coeff carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimeFactorWithoutConstant () const
Returns
The lcm of the denominators of the coefficients (without the constant one) in p divided by the gcd of numerators of the coefficients in p.
coprimePart()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimePart (const MultivariatePolynomial< Coeff, Ordering, Policies > & q) const inline
Calculates the part ofthe Polynomial, that is coprime to q.
Only works with CoCoA.
Parameters
q
Returns
Definition at line 581 of file MultivariatePolynomial.h.
definiteness()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> Definiteness carl::MultivariatePolynomial< Coeff, Ordering, Policies >::definiteness (bool _fullEffort = true) const
Retrieves information about the definiteness of the polynomial.
Returns
Definiteness of this.
degree()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::degree (Variable::Arg var) const inline
Calculates the degree of this polynomial with respect to the given variable.
Parameters
var Variable.
Returns
Degree w.r.t. var.
Definition at line 197 of file MultivariatePolynomial.h.
Referenced by carl::der(), carl::ThomEncoding< Number >::extendSignCondition(), carl::TaylorExpansion< Integer >::ideal_adic_coeff(), carl::MultivariatePolynomial< Rational >::lcoeff(), carl::realRootsThom(), and carl::ThomEncoding< Number >::relevantDerivatives().
derivative()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::derivative (Variable::Arg v, unsigned nth = 1) const
Referenced by carl::der().
divideBy() [1/3]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_field< C >> = dummy> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divideBy (const Coeff & divisor) const
Divides the polynomial by the given coefficient.
Applies if the coefficients are from a field.
Parameters
divisor
Returns
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
divideBy() [2/3]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_field< C >> = dummy> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divideBy (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor, MultivariatePolynomial< Coeff, Ordering, Policies > & quotient) const
Divides the polynomial by another polynomial.
If the divisor divides this polynomial, quotient contains the result of the division and true is returned. Otherwise, false is returned and the content of quotient remains unchanged. Applies if the coefficients are from a field. Note that the quotient must not be *this.
Parameters
divisor
quotient
Returns
divideBy() [3/3]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> DivisionResult<MultivariatePolynomial> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divideBy (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor) const
Calculating the quotient and the remainder, such that for a given polynomial p we have p = divisor * quotient + remainder.
Parameters
divisor Another polynomial
Returns
A divisionresult, holding the quotient and the remainder.
See also
Note
Division is only defined on fields
divides()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divides (const MultivariatePolynomial< Coeff, Ordering, Policies > & b) const
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
end()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType::const_iterator carl::MultivariatePolynomial< Coeff, Ordering, Policies >::end () const inline
Definition at line 321 of file MultivariatePolynomial.h.
Referenced by std::hash< carl::MultivariatePolynomial< C, O, P > >::operator()().
eraseTerm()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType::iterator carl::MultivariatePolynomial< Coeff, Ordering, Policies >::eraseTerm (typename TermsType::iterator pos) inline
Todo:
find new lterm or constant term
Definition at line 336 of file MultivariatePolynomial.h.
evaluate()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename SubstitutionType = Coeff> SubstitutionType carl::MultivariatePolynomial< Coeff, Ordering, Policies >::evaluate (const std::map< Variable, SubstitutionType > & substitutions) const
Like substitute, but expects substitutions for all variables.
Returns
For a polynomial p, the function value p(x_1,...,x_n).
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
gatherVariables() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::gatherVariables (std::set< Variable > & vars) const
Iterates through all terms to find variables occuring in this polynomial.
Parameters
vars Holds the variables occuring in the polynomial at return.
Referenced by carl::cad::Constraint< carl::Number >::checkVariables(), carl::evaluateTE(), carl::MultivariateGCD< GCDCalculation, Coeff, Ordering, Policies >::getMainVar(), carl::EZGCD< Coeff, Ordering, Policies >::getMainVar(), main(), and carl::ThomEncoding< Number >::signOnPolynomial().
gatherVariables() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::set<Variable> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::gatherVariables () const
getSingleVariable()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> Variable carl::MultivariatePolynomial< Coeff, Ordering, Policies >::getSingleVariable () const inline
For terms with exactly one variable, get this variable.
Returns
The only variable occuring in the term.
Definition at line 378 of file MultivariatePolynomial.h.
getTerms()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::getTerms () inline
Definition at line 348 of file MultivariatePolynomial.h.
Referenced by carl::DiophantineEquations< Integer >::solveMultivariateDiophantine().
getVarInfo() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<bool gatherCoeff> VariableInformation<gatherCoeff, MultivariatePolynomial> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::getVarInfo (Variable::Arg v) const
getVarInfo() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<bool gatherCoeff> VariablesInformation<gatherCoeff, MultivariatePolynomial> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::getVarInfo () const
has()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::has (Variable::Arg v) const
Parameters
v The variable to check for its occurrence.
Returns
true, if the variable occurs in this term.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluate(), carl::evaluateTE(), and carl::TaylorExpansion< Integer >::ideal_adic_coeff().
hasConstantTerm()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::hasConstantTerm () const
Check if the polynomial has a constant term that is not zero.
integerValued()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::integerValued () const
Returns
true, if the image of this polynomial is integer-valued.
isConsistent()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isConsistent () const
Asserts that this polynomial complies with the requirements and assumptions for MultivariatePolynomial objects.
All terms are actually valid and not nullptr or alike
Only the trailing term may be constant.
Referenced by carl::cad::Constraint< carl::Number >::Constraint(), carl::MultivariatePolynomial< Rational >::makeOrdered(), std::hash< carl::MultivariatePolynomial< C, O, P > >::operator()(), and carl::SPolynomial().
isConstant()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isConstant () const
Check if the polynomial is constant.
Referenced by carl::coprimePart(), carl::MultivariatePolynomial< Rational >::getSingleVariable(), carl::MultivariatePolynomial< Rational >::isNumber(), carl::TarskiQueryManager< carl::Number >::operator()(), carl::ThomEncoding< Number >::signOnPolynomial(), and carl::squareFreePart().
isLinear()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isLinear () const
Check if the polynomial is linear.
Referenced by carl::squareFreePart().
isMultivariateRepresented()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isMultivariateRepresented () const inline override virtual
See also
class Polynomial
Returns
Implements carl::Polynomial.
Definition at line 138 of file MultivariatePolynomial.h.
isNumber()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isNumber () const inline
Check if the polynomial is a number, i.e., a constant.
Definition at line 248 of file MultivariatePolynomial.h.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluate().
isOne()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isOne () const
Returns
isOrdered()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isOrdered () const inline
Check if the terms are ordered.
Returns
If terms are ordered.
Definition at line 146 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::makeOrdered().
isReducibleIdentity()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isReducibleIdentity () const
isTsos()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isTsos () const
Checks whether the polynomial is a trivial sum of squares.
Returns
true if polynomial is of the form \sum a_im_i^2 with a_i > 0 for all i.
isUnivariate()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isUnivariate () const
Checks whether only one variable occurs.
Returns
Notice that it might be better to use the variable information if several pieces of information are requested.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()(), and carl::ThomEncoding< Number >::ThomEncoding().
isUnivariateRepresented()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isUnivariateRepresented () const inline override virtual
See also
class Polynomial
Returns
Implements carl::Polynomial.
Definition at line 131 of file MultivariatePolynomial.h.
isVariable()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isVariable () const inline
Returns
true, if this polynomial consists just of one variable (with coefficient 1).
Definition at line 369 of file MultivariatePolynomial.h.
isZero()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isZero () const
Check if the polynomial is zero.
Referenced by carl::IntervalEvaluation::evaluate(), carl::ThomEncoding< Number >::makesPolynomialZero(), carl::TarskiQueryManager< carl::Number >::operator()(), carl::ThomEncoding< Number >::signOnPolynomial(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
lcoeff() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Coeff& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lcoeff () const
Returns the coefficient of the leading term.
Notice that this is not defined for zero polynomials.
Returns
Leading coefficient.
Referenced by carl::TarskiQueryManager< carl::Number >::cache(), carl::TarskiQueryManager< carl::Number >::getCached(), carl::MultivariatePolynomial< Rational >::isVariable(), carl::TarskiQueryManager< carl::Number >::operator()(), carl::ThomEncoding< Number >::signOnPolynomial(), and carl::SoSDecomposition().
lcoeff() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lcoeff (Variable::Arg var) const inline
Returns the leading coefficient with respect to the given variable.
Parameters
var Variable.
Returns
Leading coefficient.
Definition at line 181 of file MultivariatePolynomial.h.
lmon()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Monomial::Arg& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lmon () const
The leading monomial.
Returns
Referenced by carl::SPolynomial().
lterm() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lterm () const
The leading term.
Returns
Referenced by carl::MultivariatePolynomial< Rational >::getSingleVariable(), carl::SPolynomial(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
lterm() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lterm ()
mainDenom()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_number< C >> = dummy> IntNumberType carl::MultivariatePolynomial< Coeff, Ordering, Policies >::mainDenom () const
makeMinimallyOrdered() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<bool findConstantTerm = true, bool findLeadingTerm = true> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::makeMinimallyOrdered () const
Make sure that the terms are at least minimally ordered.
makeMinimallyOrdered() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::makeMinimallyOrdered (typename TermsType::iterator & lterm, typename TermsType::iterator & cterm) const private
Make sure that the terms are at least minimally ordered.
Iterators to the important terms are given as arguments, so that we don't need to scan the whole vector.
Parameters
lterm Iterator to leading term.
cterm Iterator to constant term.
makeOrdered()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::makeOrdered () const inline
Ensure that the terms are ordered.
Definition at line 152 of file MultivariatePolynomial.h.
mod()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::mod (const typename IntegralType< Coeff >::type & modulo) const
naive_pow()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::naive_pow (unsigned exp) const
normalize()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::normalize () const
For a polynomial p, returns p/lc(p)
Returns
Referenced by carl::TarskiQueryManager< carl::Number >::cache(), carl::MultivariateGCD< GCDCalculation, Coeff, Ordering, Policies >::checkCorrectnessWithGinac(), and carl::TarskiQueryManager< carl::Number >::getCached().
nrTerms()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::nrTerms () const inline
Calculate the number of terms.
Definition at line 271 of file MultivariatePolynomial.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::IntervalEvaluation::evaluate(), carl::MultivariatePolynomial< Rational >::isVariable(), carl::SPolynomial(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
numericContent() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_number< C >> = dummy> Coeff carl::MultivariatePolynomial< Coeff, Ordering, Policies >::numericContent () const
numericContent() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, DisableIf< is_number< C >> = dummy> UnderlyingNumberType<C>::type carl::MultivariatePolynomial< Coeff, Ordering, Policies >::numericContent () const
operator*=() [1/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [2/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const Term< Coeff > & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [3/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const Monomial::Arg & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [4/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator*=() [5/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const Coeff & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [1/6]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [2/6]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const TermType & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [3/6]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const std::shared_ptr< const TermType > & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [4/6]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const Monomial::Arg & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [5/6]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (Variable::Arg rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator+=() [6/6]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const Coeff & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator- () const
operator-=() [1/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-=() [2/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const Term< Coeff > & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-=() [3/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const Monomial::Arg & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-=() [4/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (Variable::Arg rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator-=() [5/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const Coeff & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [1/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [2/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const Term< Coeff > & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [3/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const Monomial::Arg & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [4/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (Variable::Arg rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator/=() [5/5]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const Coeff & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
operator=() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator= (const MultivariatePolynomial< Coeff, Ordering, Policies > & p)
operator=() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator= (MultivariatePolynomial< Coeff, Ordering, Policies > && p) noexcept
operator[]()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator[] (unsigned index) const
polynomial()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const PolyType& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::polynomial () const inline
Returns
The coprimeCoefficients of this polyomial, if this is stored internally, otherwise this polynomial.
Definition at line 395 of file MultivariatePolynomial.h.
Referenced by carl::cad::Constraint< carl::Number >::operator<().
pow()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::pow (std::size_t exp) const
Referenced by carl::TaylorExpansion< Integer >::ideal_adic_coeff(), carl::helper::sanitizeFactors(), and carl::SoSDecomposition().
prem()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::prem (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor, Variable::Arg var) const
quotient()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::quotient (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor) const
Calculates the quotient.
Parameters
divisor
Returns
See also
MultivariatePolynomial::divideBy
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
rbegin()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType::const_reverse_iterator carl::MultivariatePolynomial< Coeff, Ordering, Policies >::rbegin () const inline
Definition at line 326 of file MultivariatePolynomial.h.
Referenced by carl::SoSDecomposition(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
remainder()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::remainder (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor) const
Calculates the remainder.
Parameters
divisor
Returns
See also
MultivariatePolynomial::divideBy
rend()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType::const_reverse_iterator carl::MultivariatePolynomial< Coeff, Ordering, Policies >::rend () const inline
Definition at line 331 of file MultivariatePolynomial.h.
Referenced by carl::SoSDecomposition(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
size()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::size () const inline
Returns
A rough estimation of the size of this polynomial being the number of its terms. (Note, that this method is required, as it is provided of other polynomials not necessarily being straightforward.)
Definition at line 280 of file MultivariatePolynomial.h.
Referenced by carl::BaseRepresentation< carl::Number >::BaseRepresentation().
sosDecomposition()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> auto carl::MultivariatePolynomial< Coeff, Ordering, Policies >::sosDecomposition (bool not_trivial = false) const inline
Parameters
_notTrivial If this flag is true, this polynomial is not yet in form of a sos (the method than avoids checking this).
Returns
The sum-of-squares (sos) decomposition ((q1,p1), .., (qn,pn)) with this = q1*p1^2+..+qn*pn^2, qi being positive rational numbers and pi being polynomials. If the result is empty, no sos could be found (which does not mean, that there exists no one).
Definition at line 264 of file MultivariatePolynomial.h.
SPolynomial()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> static MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::SPolynomial (const MultivariatePolynomial< Coeff, Ordering, Policies > & p, const MultivariatePolynomial< Coeff, Ordering, Policies > & q) inline static
Calculates the S-Polynomial.
Parameters
p
q
Returns
Definition at line 571 of file MultivariatePolynomial.h.
sqrt()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::sqrt (MultivariatePolynomial< Coeff, Ordering, Policies > & res) const
Calculates the square of this multivariate polynomial if it is a square.
Parameters
res Used to store the result in.
Returns
true, if this multivariate polynomial is a square; false, otherwise.
square()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::square ()
stripLT()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::stripLT ()
Drops the leading term.
The function assumes the polynomial to be nonzero, otherwise the leading term is not defined.
Returns
A reference to this.
Todo:
find new lterm
Referenced by carl::MultiplicationTable< carl::Number >::init().
substitute() [1/4]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (Variable::Arg var, const MultivariatePolynomial< Coeff, Ordering, Policies > & value) const
Replace the given variable by the given value.
Returns
A new polynomial without resulting from this substitution.
Referenced by carl::TaylorExpansion< Integer >::ideal_adic_coeff(), carl::ThomEncoding< Number >::operator+(), carl::UnivariatePolynomial< Coeff >::replaceVariable(), and carl::DiophantineEquations< Integer >::solveMultivariateDiophantine().
substitute() [2/4]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (const std::map< Variable, MultivariatePolynomial< Coeff, Ordering, Policies > > & substitutions) const
Replace all variables by a value given in their map.
Returns
A new polynomial without the variables in map.
substitute() [3/4]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename SubstitutionType = Coeff> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (const std::map< Variable, SubstitutionType > & substitutions) const
Replace all variables by a value given in their map.
Returns
A new polynomial without the variables in map.
substitute() [4/4]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (const std::map< Variable, Term< Coeff >> & substitutions) const
Replace all variables by a Term in which the variable does not occur.
Parameters
substitutions
Returns
substituteIn()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substituteIn (Variable::Arg var, const MultivariatePolynomial< Coeff, Ordering, Policies > & value)
Replace the given variable by the given polynomial within this multivariate polynomial.
Todo:
find new lterm
Referenced by carl::RealAlgebraicNumberEvaluation::evaluate(), and carl::model::substituteIn().
subtractProduct()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::subtractProduct (const Term< Coeff > & factor, const MultivariatePolynomial< Coeff, Ordering, Policies > & p)
Subtract a term times a polynomial from this polynomial.
Parameters
factor Term.
p Polynomial.
tail()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::tail (bool makeFullyOrdered = false) const
For the polynomial p, the function calculates a polynomial p - lt(p).
The function assumes the polynomial to be nonzero, otherwise, lt(p) is not defined.
Returns
A new polynomial p - lt(p).
Referenced by carl::SPolynomial().
toIntegerDomain()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial<typename IntegralType<Coeff>::type, Ordering, Policies> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::toIntegerDomain () const
toString()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::string carl::MultivariatePolynomial< Coeff, Ordering, Policies >::toString (bool infix = true, bool friendlyVarNames = true) const
totalDegree()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::totalDegree () const
Calculates the max.
degree over all monomials occurring in the polynomial. As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[3], page 48
Returns
Total degree.
Referenced by carl::factorization(), carl::MultivariatePolynomial< Rational >::isVariable(), and carl::SoSDecomposition().
toUnivariatePolynomial() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> UnivariatePolynomial<Coeff> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::toUnivariatePolynomial () const
Convert a univariate polynomial that is currently (mis)represented by a 'MultivariatePolynomial' into a more appropiate 'UnivariatePolynomial' representation.
Note that the current polynomial must mention one and only one variable, i.e., be indeed univariate.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::RealAlgebraicNumberEvaluation::evaluateIR(), carl::ThomEncoding< Number >::makesPolynomialZero(), carl::TarskiQueryManager< carl::Number >::operator()(), carl::UnivariatePolynomial< Coeff >::replaceVariable(), and carl::UnivariatePolynomial< Coeff >::switchVariable().
toUnivariatePolynomial() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> UnivariatePolynomial<MultivariatePolynomial> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::toUnivariatePolynomial (Variable::Arg mainVar) const
trailingTerm() [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::trailingTerm () const
Give the last term according to Ordering.
Notice that if there is a constant part, it is always trailing.
trailingTerm() [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::trailingTerm ()
Friends And Related Function Documentation
operator/ [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> operator/ (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) friend
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
operator/ [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> operator/ (const MultivariatePolynomial< C, O, P > & lhs, unsigned long rhs) friend
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
operator<< [1/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::ostream& operator<< (std::ostream & os, ConstructorOperation op) friend
Definition at line 86 of file MultivariatePolynomial.h.
operator<< [2/2]
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > std::ostream& operator<< (std::ostream & os, const MultivariatePolynomial< C, O, P > & rhs) friend
Streaming operator for multivariate polynomials.
Parameters
os Output stream.
rhs Polynomial.
Returns
os.
operator==
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > bool operator== (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
TermAdditionManager
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename Polynomial , typename Order > friend class TermAdditionManager friend
Definition at line 48 of file MultivariatePolynomial.h.
Field Documentation
mOrdered
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::mOrdered mutable private
Flag that indicates if the terms are ordered.
Definition at line 80 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::isOrdered(), and carl::MultivariatePolynomial< Rational >::makeOrdered().
mTermAdditionManager
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermAdditionManager<MultivariatePolynomial,Ordering> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::mTermAdditionManager static
Definition at line 83 of file MultivariatePolynomial.h.
mTerms
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType carl::MultivariatePolynomial< Coeff, Ordering, Policies >::mTerms mutable private
A vector of all terms.
Definition at line 78 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::begin(), carl::MultivariatePolynomial< Rational >::coeff(), carl::MultivariatePolynomial< Rational >::complexity(), carl::MultivariatePolynomial< Rational >::degree(), carl::MultivariatePolynomial< Rational >::end(), carl::MultivariatePolynomial< Rational >::eraseTerm(), carl::MultivariatePolynomial< Rational >::getTerms(), carl::MultivariatePolynomial< Rational >::isVariable(), carl::MultivariatePolynomial< Rational >::makeOrdered(), carl::MultivariatePolynomial< Rational >::nrTerms(), carl::MultivariatePolynomial< Rational >::rbegin(), carl::MultivariatePolynomial< Rational >::rend(), and carl::MultivariatePolynomial< Rational >::size().
The documentation for this class was generated from the following files:
carl/core/MultivariateGCD.h
carl/core/MultivariatePolynomial.h