carl: carl::Bitset Class Reference
carl::Bitset Class Reference
This class is a simple wrapper around boost::dynamic_bitset.
#include <Bitset.h>
Data Structures
struct iterator
Iterate for iterate over all bits of a Bitset that are set to true.
Public Types
using BaseType = boost::dynamic_bitset<>
Underlying storage type.
Public Member Functions
Bitset (bool defaultValue=false)
Create an empty bitset.
Bitset (BaseType &&base, bool defaultValue)
Create a bitset from a BaseType object.
Bitset (const std::initializer_list< std::size_t > &bits, bool defaultValue=false)
Create a bitset from a list of bits indices that shall be set to true.
auto resize (std::size_t num_bits, bool value) const
Resize the Bitset to hold at least num_bits bits. New bits are set to the given value.
auto resize (std::size_t num_bits) const
Resize the Bitset to hold at least num_bits bits. New bits are set to mDefault.
Bitset & operator-= (const Bitset &rhs)
Sets all bits to false that are true in rhs.
Bitset & operator &= (const Bitset &rhs)
Computes the bitwise and with rhs.
Bitset & operator|= (const Bitset &rhs)
Computes the bitwise or with rhs.
Bitset & set (std::size_t n, bool value=true)
Sets the given bit to a value, true by default.
Bitset & set_interval (std::size_t start, std::size_t end, bool value=true)
Sets the a range of bits to a value, true by default.
Bitset & reset (std::size_t n)
Resets a bit to false.
bool test (std::size_t n) const
Retrieves the value of the given bit.
bool any () const
Checks if any bits are set to true. Asserts that mDefault is false.
bool none () const
Checks if no bits are set to true. Asserts that mDefault is false.
auto count () const noexcept
Counts the number of bits that are set to true. Asserts that mDefault is false.
auto size () const
Retrieves the size of mData.
auto num_blocks () const
Retrieves the number of blocks used to store mData.
auto is_subset_of (const Bitset &rhs) const
Checks wether the bits set is a subset of the bits set in rhs.
std::size_t find_first () const
Retrieves the index of the first bit that is set to true.
std::size_t find_next (std::size_t pos) const
Retrieves the index of the first bit set to true after the given position.
iterator begin () const
Returns an iterator to the first bits that is set to true.
iterator end () const
Returns an past-the-end iterator.
Static Public Attributes
static auto constexpr npos = BaseType::npos
Sentinel element for iteration.
static auto constexpr bits_per_block = BaseType::bits_per_block
Number of bits in each storage block.
Private Member Functions
void ensureSize (std::size_t pos)
Resize mData to hold at least pos bits.
Private Attributes
BaseType mData
The actual data.
bool mDefault
The default value for bits beyond mData.
Friends
void alignSize (const Bitset &lhs, const Bitset &rhs)
Ensures that the explicitly stored bits of lhs and rhs have the same size.
bool operator== (const Bitset &lhs, const Bitset &rhs)
Compares lhs and rhs.
bool operator< (const Bitset &lhs, const Bitset &rhs)
Compares lhs and rhs according to some order.
Bitset operator~ (const Bitset &lhs)
Returns the bitwise negation of lhs.
Bitset operator & (const Bitset &lhs, const Bitset &rhs)
Returns the bitwise and of lhs and rhs.
Bitset operator| (const Bitset &lhs, const Bitset &rhs)
Returns the bitwise or of lhs and rhs.
std::ostream & operator<< (std::ostream &os, const Bitset &b)
Outputs b to os using the format <explicit bits>[<default>].
Detailed Description
This class is a simple wrapper around boost::dynamic_bitset.
Its purpose is to allow for on-the-fly resizing of the bitset. Formally, a Bitset object represents an infinite bitset that starts with the bits stored in mData extended by mDefault. Whenever a bit is written that is not yet stored explicitly in mData or two Bitset objects with different mData sizes are involved, the size of mData is expanded transparently.
Note that some operations only make sense for a certain value of mDefault. For example, any() or none() require mDefault to be false.
Definition at line 18 of file Bitset.h.
Member Typedef Documentation
BaseType
using carl::Bitset::BaseType = boost::dynamic_bitset<>
Underlying storage type.
Definition at line 21 of file Bitset.h.
Constructor & Destructor Documentation
Bitset() [1/3]
carl::Bitset::Bitset (bool defaultValue = false) inline
Create an empty bitset.
Definition at line 96 of file Bitset.h.
Bitset() [2/3]
carl::Bitset::Bitset (BaseType && base, bool defaultValue) inline
Create a bitset from a BaseType object.
Definition at line 98 of file Bitset.h.
Bitset() [3/3]
carl::Bitset::Bitset (const std::initializer_list< std::size_t > & bits, bool defaultValue = false) inline
Create a bitset from a list of bits indices that shall be set to true.
Definition at line 100 of file Bitset.h.
Member Function Documentation
any()
bool carl::Bitset::any () const inline
Checks if any bits are set to true. Asserts that mDefault is false.
Definition at line 157 of file Bitset.h.
Referenced by carl::Covering< T >::buildConflictingCore().
begin()
iterator carl::Bitset::begin () const inline
Returns an iterator to the first bits that is set to true.
Definition at line 196 of file Bitset.h.
count()
auto carl::Bitset::count () const inline noexcept
Counts the number of bits that are set to true. Asserts that mDefault is false.
Definition at line 168 of file Bitset.h.
end()
iterator carl::Bitset::end () const inline
Returns an past-the-end iterator.
Definition at line 200 of file Bitset.h.
Referenced by set_interval().
ensureSize()
void carl::Bitset::ensureSize (std::size_t pos) inline private
Resize mData to hold at least pos bits.
Definition at line 89 of file Bitset.h.
Referenced by reset(), set(), and set_interval().
find_first()
std::size_t carl::Bitset::find_first () const inline
Retrieves the index of the first bit that is set to true.
Definition at line 188 of file Bitset.h.
Referenced by begin(), carl::IDPool::get(), and carl::Covering< T >::satisfyingInterval().
find_next()
std::size_t carl::Bitset::find_next (std::size_t pos) const inline
Retrieves the index of the first bit set to true after the given position.
Definition at line 192 of file Bitset.h.
Referenced by carl::Bitset::iterator::operator++().
is_subset_of()
auto carl::Bitset::is_subset_of (const Bitset & rhs) const inline
Checks wether the bits set is a subset of the bits set in rhs.
Definition at line 182 of file Bitset.h.
none()
bool carl::Bitset::none () const inline
Checks if no bits are set to true. Asserts that mDefault is false.
Definition at line 162 of file Bitset.h.
Referenced by carl::Covering< T >::conflicts().
num_blocks()
auto carl::Bitset::num_blocks () const inline
Retrieves the number of blocks used to store mData.
Definition at line 178 of file Bitset.h.
Referenced by carl::IDPool::get().
operator &=()
Bitset& carl::Bitset::operator&= (const Bitset & rhs) inline
Computes the bitwise and with rhs.
Definition at line 121 of file Bitset.h.
operator-=()
Bitset& carl::Bitset::operator-= (const Bitset & rhs) inline
Sets all bits to false that are true in rhs.
Definition at line 114 of file Bitset.h.
operator|=()
Bitset& carl::Bitset::operator|= (const Bitset & rhs) inline
Computes the bitwise or with rhs.
Definition at line 127 of file Bitset.h.
reset()
Bitset& carl::Bitset::reset (std::size_t n) inline
Resets a bit to false.
Definition at line 146 of file Bitset.h.
Referenced by carl::IDPool::get().
resize() [1/2]
auto carl::Bitset::resize (std::size_t num_bits, bool value) const inline
Resize the Bitset to hold at least num_bits bits. New bits are set to the given value.
Definition at line 105 of file Bitset.h.
Referenced by carl::Covering< T >::buildConflictingCore(), carl::Covering< T >::Covering(), and carl::IDPool::get().
resize() [2/2]
auto carl::Bitset::resize (std::size_t num_bits) const inline
Resize the Bitset to hold at least num_bits bits. New bits are set to mDefault.
Definition at line 109 of file Bitset.h.
set()
Bitset& carl::Bitset::set (std::size_t n, bool value = true) inline
Sets the given bit to a value, true by default.
Definition at line 134 of file Bitset.h.
Referenced by carl::IDPool::free().
set_interval()
Bitset& carl::Bitset::set_interval (std::size_t start, std::size_t end, bool value = true) inline
Sets the a range of bits to a value, true by default.
Definition at line 140 of file Bitset.h.
size()
auto carl::Bitset::size () const inline
Retrieves the size of mData.
Definition at line 174 of file Bitset.h.
Referenced by carl::Covering< T >::buildConflictingCore(), carl::IDPool::free(), carl::IDPool::get(), and carl::IDPool::size().
test()
bool carl::Bitset::test (std::size_t n) const inline
Retrieves the value of the given bit.
Definition at line 152 of file Bitset.h.
Friends And Related Function Documentation
alignSize
void alignSize (const Bitset & lhs, const Bitset & rhs) friend
Ensures that the explicitly stored bits of lhs and rhs have the same size.
Definition at line 205 of file Bitset.h.
Referenced by is_subset_of(), operator &=(), operator-=(), and operator|=().
operator &
Bitset operator& (const Bitset & lhs, const Bitset & rhs) friend
Returns the bitwise and of lhs and rhs.
Definition at line 227 of file Bitset.h.
operator<
bool operator< (const Bitset & lhs, const Bitset & rhs) friend
Compares lhs and rhs according to some order.
Definition at line 216 of file Bitset.h.
operator<<
std::ostream& operator<< (std::ostream & os, const Bitset & b) friend
Outputs b to os using the format <explicit bits>[<default>].
Definition at line 238 of file Bitset.h.
operator==
bool operator== (const Bitset & lhs, const Bitset & rhs) friend
Compares lhs and rhs.
Definition at line 211 of file Bitset.h.
operator|
Bitset operator| (const Bitset & lhs, const Bitset & rhs) friend
Returns the bitwise or of lhs and rhs.
Definition at line 232 of file Bitset.h.
operator~
Bitset operator~ (const Bitset & lhs) friend
Returns the bitwise negation of lhs.
Definition at line 223 of file Bitset.h.
Field Documentation
bits_per_block
auto constexpr carl::Bitset::bits_per_block = BaseType::bits_per_block static
Number of bits in each storage block.
Definition at line 25 of file Bitset.h.
Referenced by carl::IDPool::get().
mData
BaseType carl::Bitset::mData mutable private
The actual data.
Definition at line 85 of file Bitset.h.
Referenced by any(), count(), ensureSize(), find_first(), find_next(), is_subset_of(), none(), num_blocks(), operator &=(), operator-=(), operator|=(), reset(), resize(), set(), set_interval(), size(), and test().
mDefault
bool carl::Bitset::mDefault private
The default value for bits beyond mData.
Definition at line 87 of file Bitset.h.
Referenced by any(), count(), is_subset_of(), none(), operator-=(), resize(), and test().
npos
auto constexpr carl::Bitset::npos = BaseType::npos static
Sentinel element for iteration.
Definition at line 23 of file Bitset.h.
Referenced by end(), and carl::IDPool::get().
The documentation for this class was generated from the following file:
carl/util/Bitset.h