carl: carl::BVValue Class Reference
carl::BVValue Class Reference
#include <BVValue.h>
Public Types
using Base = boost::dynamic_bitset< uint >
Public Member Functions
BVValue ()=default
BVValue (std::size_t _width, uint _value=0)
BVValue (std::size_t _width, const cln::cl_I &_value)
BVValue (std::size_t _width, const mpz_class &_value)
template<typename BlockInputIterator >
BVValue (BlockInputIterator _first, BlockInputIterator _last)
template<typename Char , typename Traits , typename Alloc >
BVValue (const std::basic_string< Char, Traits, Alloc > &_s, typename std::basic_string< Char, Traits, Alloc >::size_type _pos=0, typename std::basic_string< Char, Traits, Alloc >::size_type _n=std::basic_string< Char, Traits, Alloc >::npos)
operator const Base & () const
std::size_t width () const
std::string toString () const
bool isZero () const
BVValue operator- () const
BVValue operator~ () const
BVValue rotateLeft (std::size_t _n) const
BVValue rotateRight (std::size_t _n) const
BVValue repeat (std::size_t _n) const
BVValue extendUnsignedBy (std::size_t _n) const
BVValue extendSignedBy (std::size_t _n) const
bool operator== (const BVValue &_other) const
bool operator< (const BVValue &_other) const
Base::reference operator[] (std::size_t _index)
bool operator[] (std::size_t _index) const
BVValue operator+ (const BVValue &_other) const
BVValue operator- (const BVValue &_other) const
BVValue operator & (const BVValue &_other) const
BVValue operator| (const BVValue &_other) const
BVValue operator^ (const BVValue &_other) const
BVValue concat (const BVValue &_other) const
BVValue operator* (const BVValue &_other) const
BVValue operator% (const BVValue &_other) const
BVValue operator/ (const BVValue &_other) const
BVValue divideSigned (const BVValue &_other) const
BVValue remSigned (const BVValue &_other) const
BVValue modSigned (const BVValue &_other) const
BVValue operator<< (const BVValue &_other) const
BVValue operator>> (const BVValue &_other) const
BVValue rightShiftArithmetic (const BVValue &_other) const
BVValue extract (std::size_t _highest, std::size_t _lowest) const
Private Member Functions
template<std::size_t len>
BVValue (const std::array< uint, len > &a)
BVValue (Base &&value)
BVValue shift (const BVValue &_other, bool _left, bool _arithmetic=false) const
BVValue divideUnsigned (const BVValue &_other, bool _returnRemainder=false) const
Private Attributes
Base mValue
Friends
std::ostream & operator<< (std::ostream &_out, const BVValue &_value)
Detailed Description
Definition at line 17 of file BVValue.h.
Member Typedef Documentation
Base
using carl::BVValue::Base = boost::dynamic_bitset<uint>
Definition at line 20 of file BVValue.h.
Constructor & Destructor Documentation
BVValue() [1/8]
template<std::size_t len> carl::BVValue::BVValue (const std::array< uint, len > & a) inline explicit private
Definition at line 25 of file BVValue.h.
BVValue() [2/8]
carl::BVValue::BVValue (Base && value) inline explicit private
Definition at line 26 of file BVValue.h.
BVValue() [3/8]
carl::BVValue::BVValue () default
Referenced by concat(), divideUnsigned(), extendSignedBy(), extendUnsignedBy(), operator &(), operator*(), operator+(), operator-(), operator^(), operator|(), operator~(), rotateLeft(), and shift().
BVValue() [4/8]
carl::BVValue::BVValue (std::size_t _width, uint _value = 0) inline explicit
Definition at line 31 of file BVValue.h.
BVValue() [5/8]
carl::BVValue::BVValue (std::size_t _width, const cln::cl_I & _value) inline explicit
Definition at line 37 of file BVValue.h.
BVValue() [6/8]
carl::BVValue::BVValue (std::size_t _width, const mpz_class & _value) inline
Definition at line 45 of file BVValue.h.
BVValue() [7/8]
template<typename BlockInputIterator > carl::BVValue::BVValue (BlockInputIterator _first, BlockInputIterator _last) inline explicit
Definition at line 88 of file BVValue.h.
BVValue() [8/8]
template<typename Char , typename Traits , typename Alloc > carl::BVValue::BVValue (const std::basic_string< Char, Traits, Alloc > & _s, typename std::basic_string< Char, Traits, Alloc >::size_type _pos = 0, typename std::basic_string< Char, Traits, Alloc >::size_type _n = std::basic_string<Char,Traits,Alloc>::npos) inline explicit
Definition at line 94 of file BVValue.h.
Member Function Documentation
concat()
BVValue carl::BVValue::concat (const BVValue & _other) const inline
Definition at line 240 of file BVValue.h.
Referenced by carl::BVTermPool::create().
divideSigned()
BVValue carl::BVValue::divideSigned (const BVValue & _other) const inline
Definition at line 276 of file BVValue.h.
Referenced by carl::BVTermPool::create().
divideUnsigned()
BVValue carl::BVValue::divideUnsigned (const BVValue & _other, bool _returnRemainder = false) const inline private
Definition at line 399 of file BVValue.h.
Referenced by operator%(), and operator/().
extendSignedBy()
BVValue carl::BVValue::extendSignedBy (std::size_t _n) const inline
Definition at line 167 of file BVValue.h.
Referenced by carl::BVTermPool::create().
extendUnsignedBy()
BVValue carl::BVValue::extendUnsignedBy (std::size_t _n) const inline
Definition at line 160 of file BVValue.h.
Referenced by carl::BVTermPool::create().
extract()
BVValue carl::BVValue::extract (std::size_t _highest, std::size_t _lowest) const inline
Definition at line 352 of file BVValue.h.
Referenced by carl::BVTermPool::create().
isZero()
bool carl::BVValue::isZero () const inline
Definition at line 118 of file BVValue.h.
Referenced by carl::BVTermPool::create(), and modSigned().
modSigned()
BVValue carl::BVValue::modSigned (const BVValue & _other) const inline
Definition at line 312 of file BVValue.h.
Referenced by carl::BVTermPool::create().
operator &()
BVValue carl::BVValue::operator& (const BVValue & _other) const inline
Definition at line 222 of file BVValue.h.
operator const Base &()
carl::BVValue::operator const Base & () const inline explicit
Definition at line 101 of file BVValue.h.
operator%()
BVValue carl::BVValue::operator% (const BVValue & _other) const inline
Definition at line 266 of file BVValue.h.
operator*()
BVValue carl::BVValue::operator* (const BVValue & _other) const inline
Definition at line 251 of file BVValue.h.
operator+()
BVValue carl::BVValue::operator+ (const BVValue & _other) const inline
Definition at line 201 of file BVValue.h.
operator-() [1/2]
BVValue carl::BVValue::operator- () const inline
Definition at line 123 of file BVValue.h.
operator-() [2/2]
BVValue carl::BVValue::operator- (const BVValue & _other) const inline
Definition at line 216 of file BVValue.h.
operator/()
BVValue carl::BVValue::operator/ (const BVValue & _other) const inline
Definition at line 271 of file BVValue.h.
operator<()
bool carl::BVValue::operator< (const BVValue & _other) const inline
Definition at line 184 of file BVValue.h.
operator<<()
BVValue carl::BVValue::operator<< (const BVValue & _other) const inline
Definition at line 337 of file BVValue.h.
operator==()
bool carl::BVValue::operator== (const BVValue & _other) const inline
Definition at line 179 of file BVValue.h.
operator>>()
BVValue carl::BVValue::operator>> (const BVValue & _other) const inline
Definition at line 342 of file BVValue.h.
operator[]() [1/2]
Base::reference carl::BVValue::operator[] (std::size_t _index) inline
Definition at line 189 of file BVValue.h.
operator[]() [2/2]
bool carl::BVValue::operator[] (std::size_t _index) const inline
Definition at line 195 of file BVValue.h.
operator^()
BVValue carl::BVValue::operator^ (const BVValue & _other) const inline
Definition at line 234 of file BVValue.h.
operator|()
BVValue carl::BVValue::operator| (const BVValue & _other) const inline
Definition at line 228 of file BVValue.h.
operator~()
BVValue carl::BVValue::operator~ () const inline
Definition at line 128 of file BVValue.h.
remSigned()
BVValue carl::BVValue::remSigned (const BVValue & _other) const inline
Definition at line 294 of file BVValue.h.
Referenced by carl::BVTermPool::create().
repeat()
BVValue carl::BVValue::repeat (std::size_t _n) const inline
Definition at line 149 of file BVValue.h.
Referenced by carl::BVTermPool::create().
rightShiftArithmetic()
BVValue carl::BVValue::rightShiftArithmetic (const BVValue & _other) const inline
Definition at line 347 of file BVValue.h.
Referenced by carl::BVTermPool::create().
rotateLeft()
BVValue carl::BVValue::rotateLeft (std::size_t _n) const inline
Definition at line 133 of file BVValue.h.
Referenced by carl::BVTermPool::create(), and rotateRight().
rotateRight()
BVValue carl::BVValue::rotateRight (std::size_t _n) const inline
Definition at line 144 of file BVValue.h.
Referenced by carl::BVTermPool::create().
shift()
BVValue carl::BVValue::shift (const BVValue & _other, bool _left, bool _arithmetic = false) const inline private
Definition at line 365 of file BVValue.h.
Referenced by operator<<(), operator>>(), and rightShiftArithmetic().
toString()
std::string carl::BVValue::toString () const inline
Definition at line 111 of file BVValue.h.
Referenced by std::hash< carl::BVValue >::operator()(), and carl::BVTermContent::toString().
width()
std::size_t carl::BVValue::width () const inline
Definition at line 106 of file BVValue.h.
Referenced by concat(), divideSigned(), divideUnsigned(), extendSignedBy(), extendUnsignedBy(), extract(), modSigned(), operator &(), operator*(), operator+(), operator-(), operator[](), operator^(), operator|(), remSigned(), repeat(), rotateLeft(), rotateRight(), and shift().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & _out, const BVValue & _value) friend
Definition at line 174 of file BVValue.h.
Field Documentation
mValue
Base carl::BVValue::mValue private
Definition at line 22 of file BVValue.h.
Referenced by BVValue(), concat(), divideUnsigned(), extendSignedBy(), extendUnsignedBy(), isZero(), operator &(), operator const Base &(), operator*(), operator<(), operator==(), operator[](), operator^(), operator|(), operator~(), rotateLeft(), shift(), toString(), and width().
The documentation for this class was generated from the following file:
carl/formula/bitvector/BVValue.h