carl: carl::DIMACSExporter< Pol > Class Template Reference
carl::DIMACSExporter< Pol > Class Template Reference
#include <DIMACSExporter.h>
Public Member Functions
bool operator() (const Formula< Pol > &formula)
void clear ()
Private Member Functions
std::size_t id (carl::Variable::Arg v)
long long getLiteral (const Formula< Pol > &f)
bool addDisjunction (const Formula< Pol > &f)
Private Attributes
std::map< carl::Variable, std::size_t > mVariables
std::vector< std::vector< long long > > mClauses
Friends
template<typename P >
std::ostream & operator<< (std::ostream &os, const DIMACSExporter< P > &de)
Detailed Description
template<typename Pol>
class carl::DIMACSExporter< Pol >
Definition at line 15 of file DIMACSExporter.h.
Member Function Documentation
addDisjunction()
template<typename Pol > bool carl::DIMACSExporter< Pol >::addDisjunction (const Formula< Pol > & f) inline private
Definition at line 39 of file DIMACSExporter.h.
Referenced by carl::DIMACSExporter< Pol >::operator()().
clear()
template<typename Pol > void carl::DIMACSExporter< Pol >::clear () inline
Definition at line 88 of file DIMACSExporter.h.
getLiteral()
template<typename Pol > long long carl::DIMACSExporter< Pol >::getLiteral (const Formula< Pol > & f) inline private
Definition at line 28 of file DIMACSExporter.h.
Referenced by carl::DIMACSExporter< Pol >::addDisjunction().
id()
template<typename Pol > std::size_t carl::DIMACSExporter< Pol >::id (carl::Variable::Arg v) inline private
Definition at line 20 of file DIMACSExporter.h.
Referenced by carl::DIMACSExporter< Pol >::getLiteral().
operator()()
template<typename Pol > bool carl::DIMACSExporter< Pol >::operator() (const Formula< Pol > & formula) inline
Definition at line 66 of file DIMACSExporter.h.
Friends And Related Function Documentation
operator<<
template<typename Pol > template<typename P > std::ostream& operator<< (std::ostream & os, const DIMACSExporter< P > & de) friend
Definition at line 93 of file DIMACSExporter.h.
Field Documentation
mClauses
template<typename Pol > std::vector<std::vector<long long> > carl::DIMACSExporter< Pol >::mClauses private
Definition at line 18 of file DIMACSExporter.h.
Referenced by carl::DIMACSExporter< Pol >::addDisjunction(), and carl::DIMACSExporter< Pol >::clear().
mVariables
template<typename Pol > std::map<carl::Variable, std::size_t> carl::DIMACSExporter< Pol >::mVariables private
Definition at line 17 of file DIMACSExporter.h.
Referenced by carl::DIMACSExporter< Pol >::clear(), and carl::DIMACSExporter< Pol >::id().
The documentation for this class was generated from the following file:
carl/formula/parser/DIMACSExporter.h