carl: carl::MapleStream Class Reference
carl::MapleStream Class Reference
#include <MapleStream.h>
Public Member Functions
MapleStream ()
template<typename Pol >
void assertFormula (const Formula< Pol > &formula)
template<typename T >
MapleStream & operator<< (T &&t)
MapleStream & operator<< (std::ostream &(*os)(std::ostream &))
auto content () const
Private Member Functions
template<typename Pol >
void write (const Constraint< Pol > &c)
template<typename Pol >
void write (const Formulas< Pol > &f, const std::string &op)
template<typename Pol >
void write (const Formula< Pol > &f)
void write (const Monomial::Arg &m)
void write (const Monomial::Content::value_type &m)
void write (const Monomial &m)
template<typename Coeff >
void write (const MultivariatePolynomial< Coeff > &mp)
void write (Relation r)
template<typename Coeff >
void write (const Term< Coeff > &t)
template<typename Coeff >
void write (const UnivariatePolynomial< Coeff > &up)
void write (const Variable &v)
void write (const VariableType &vt)
template<typename T >
void write (T &&t)
Private Attributes
std::stringstream mStream
Detailed Description
Definition at line 20 of file MapleStream.h.
Constructor & Destructor Documentation
MapleStream()
carl::MapleStream::MapleStream () inline
Definition at line 188 of file MapleStream.h.
Member Function Documentation
assertFormula()
template<typename Pol > void carl::MapleStream::assertFormula (const Formula< Pol > & formula) inline
Definition at line 192 of file MapleStream.h.
content()
auto carl::MapleStream::content () const inline
Definition at line 207 of file MapleStream.h.
Referenced by carl::operator<<().
operator<<() [1/2]
template<typename T > MapleStream& carl::MapleStream::operator<< (T && t) inline
Definition at line 197 of file MapleStream.h.
operator<<() [2/2]
MapleStream& carl::MapleStream::operator<< (std::ostream &(*)(std::ostream &) os) inline
Definition at line 202 of file MapleStream.h.
write() [1/13]
template<typename Pol > void carl::MapleStream::write (const Constraint< Pol > & c) inline private
Definition at line 25 of file MapleStream.h.
Referenced by operator<<(), and write().
write() [2/13]
template<typename Pol > void carl::MapleStream::write (const Formulas< Pol > & f, const std::string & op) inline private
Definition at line 30 of file MapleStream.h.
write() [3/13]
template<typename Pol > void carl::MapleStream::write (const Formula< Pol > & f) inline private
Definition at line 42 of file MapleStream.h.
write() [4/13]
void carl::MapleStream::write (const Monomial::Arg & m) inline private
Definition at line 97 of file MapleStream.h.
write() [5/13]
void carl::MapleStream::write (const Monomial::Content::value_type & m) inline private
Definition at line 101 of file MapleStream.h.
write() [6/13]
void carl::MapleStream::write (const Monomial & m) inline private
Definition at line 106 of file MapleStream.h.
write() [7/13]
template<typename Coeff > void carl::MapleStream::write (const MultivariatePolynomial< Coeff > & mp) inline private
Definition at line 120 of file MapleStream.h.
write() [8/13]
void carl::MapleStream::write (Relation r) inline private
Definition at line 131 of file MapleStream.h.
write() [9/13]
template<typename Coeff > void carl::MapleStream::write (const Term< Coeff > & t) inline private
Definition at line 143 of file MapleStream.h.
write() [10/13]
template<typename Coeff > void carl::MapleStream::write (const UnivariatePolynomial< Coeff > & up) inline private
Definition at line 155 of file MapleStream.h.
write() [11/13]
void carl::MapleStream::write (const Variable & v) inline private
Definition at line 168 of file MapleStream.h.
write() [12/13]
void carl::MapleStream::write (const VariableType & vt) inline private
Definition at line 171 of file MapleStream.h.
write() [13/13]
template<typename T > void carl::MapleStream::write (T && t) inline private
Definition at line 183 of file MapleStream.h.
Field Documentation
mStream
std::stringstream carl::MapleStream::mStream private
Definition at line 22 of file MapleStream.h.
Referenced by content(), and write().
The documentation for this class was generated from the following file:
carl/io/MapleStream.h