carl: carl::MonomialPool Class Reference
carl::MonomialPool Class Reference
#include <MonomialPool.h>
Data Structures
struct equal
struct hash
struct PoolEntry
Public Member Functions
Monomial::Arg add (const Monomial::Arg &_monomial)
Try to add the given monomial to the pool.
Monomial::Arg add (Monomial::Content &&c, exponent totalDegree=0)
Monomial::Arg create ()
Monomial::Arg create (Variable _var, exponent _exp)
template<typename Number >
Monomial::Arg create (Variable _var, Number &&_exp)
Monomial::Arg create (std::vector< std::pair< Variable, exponent >> &&_exponents, exponent _totalDegree)
Monomial::Arg create (const std::initializer_list< std::pair< Variable, exponent >> &_exponents)
Monomial::Arg create (std::vector< std::pair< Variable, exponent >> &&_exponents)
void free (const Monomial *m)
void clear ()
Clears everything already created in this pool.
std::size_t size () const
std::size_t largestID () const
Static Public Member Functions
static MonomialPool & getInstance ()
Returns the single instance of this class by reference.
Protected Member Functions
MonomialPool (std::size_t _capacity=10000)
Constructor of the pool.
~MonomialPool ()
Monomial::Arg add (MonomialPool::PoolEntry &&pe, exponent totalDegree=0)
Private Attributes
IDPool mIDs
id allocator
std::unordered_set< PoolEntry, MonomialPool::hash, MonomialPool::equal > mPool
The pool.
std::recursive_mutex mMutex
Mutex to avoid multiple access to the pool.
Friends
class Singleton< MonomialPool >
std::ostream & operator<< (std::ostream &os, const MonomialPool &mp)
Detailed Description
Definition at line 21 of file MonomialPool.h.
Constructor & Destructor Documentation
MonomialPool()
carl::MonomialPool::MonomialPool (std::size_t _capacity = 10000) inline explicit protected
Constructor of the pool.
Parameters
_capacity Expected necessary capacity of the pool.
Definition at line 79 of file MonomialPool.h.
~MonomialPool()
carl::MonomialPool::~MonomialPool () inline protected
Definition at line 88 of file MonomialPool.h.
Member Function Documentation
add() [1/3]
Monomial::Arg carl::MonomialPool::add (MonomialPool::PoolEntry && pe, exponent totalDegree = 0) protected
Definition at line 13 of file MonomialPool.cpp.
Referenced by add(), and create().
add() [2/3]
Monomial::Arg carl::MonomialPool::add (const Monomial::Arg & _monomial)
Try to add the given monomial to the pool.
Parameters
_monomial The monomial to add.
Returns
The corresponding monomial in the pool.
Definition at line 36 of file MonomialPool.cpp.
add() [3/3]
Monomial::Arg carl::MonomialPool::add (Monomial::Content && c, exponent totalDegree = 0)
Definition at line 71 of file MonomialPool.cpp.
clear()
void carl::MonomialPool::clear () inline
Clears everything already created in this pool.
Definition at line 131 of file MonomialPool.h.
create() [1/6]
Monomial::Arg carl::MonomialPool::create ()
Definition at line 75 of file MonomialPool.cpp.
Referenced by create(), carl::createMonomial(), carl::Monomial::divide(), carl::Monomial::dropVariable(), carl::Monomial::lcm(), carl::operator*(), and carl::Monomial::separablePart().
create() [2/6]
Monomial::Arg carl::MonomialPool::create (Variable _var, exponent _exp)
Definition at line 80 of file MonomialPool.cpp.
create() [3/6]
template<typename Number > Monomial::Arg carl::MonomialPool::create (Variable _var, Number && _exp) inline
Definition at line 106 of file MonomialPool.h.
create() [4/6]
Monomial::Arg carl::MonomialPool::create (std::vector< std::pair< Variable, exponent >> && _exponents, exponent _totalDegree)
Definition at line 85 of file MonomialPool.cpp.
create() [5/6]
Monomial::Arg carl::MonomialPool::create (const std::initializer_list< std::pair< Variable, exponent >> & _exponents)
Definition at line 90 of file MonomialPool.cpp.
create() [6/6]
Monomial::Arg carl::MonomialPool::create (std::vector< std::pair< Variable, exponent >> && _exponents)
Definition at line 95 of file MonomialPool.cpp.
free()
void carl::MonomialPool::free (const Monomial * m) inline
Definition at line 116 of file MonomialPool.h.
Referenced by carl::Monomial::~Monomial().
getInstance()
static MonomialPool & carl::Singleton< MonomialPool >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::createMonomial(), carl::Monomial::divide(), carl::Monomial::dropVariable(), carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::getId(), carl::init(), carl::Monomial::lcm(), carl::operator*(), carl::Monomial::separablePart(), carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::TermAdditionManager(), and carl::Monomial::~Monomial().
largestID()
std::size_t carl::MonomialPool::largestID () const inline
Definition at line 139 of file MonomialPool.h.
Referenced by carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::getId().
size()
std::size_t carl::MonomialPool::size () const inline
Definition at line 136 of file MonomialPool.h.
Referenced by carl::operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const MonomialPool & mp) friend
Definition at line 144 of file MonomialPool.h.
Singleton< MonomialPool >
friend class Singleton< MonomialPool > friend
Definition at line 23 of file MonomialPool.h.
Field Documentation
mIDs
IDPool carl::MonomialPool::mIDs private
id allocator
Definition at line 55 of file MonomialPool.h.
Referenced by add(), clear(), free(), largestID(), and MonomialPool().
mMutex
std::recursive_mutex carl::MonomialPool::mMutex mutable private
Mutex to avoid multiple access to the pool.
Definition at line 60 of file MonomialPool.h.
mPool
std::unordered_set<PoolEntry, MonomialPool::hash, MonomialPool::equal> carl::MonomialPool::mPool private
The pool.
Definition at line 58 of file MonomialPool.h.
Referenced by add(), clear(), free(), carl::operator<<(), and size().
The documentation for this class was generated from the following files:
carl/core/MonomialPool.h
carl/core/MonomialPool.cpp