carl: carl::UFManager Class Reference
carl::UFManager Class Reference
Implements a manager for uninterpreted functions, containing their actual contents and allocating their ids.
#include <UFManager.h>
Public Member Functions
const std::vector< const UFContent * > & ufContents () const
const FastPointerMap< UFContent, UninterpretedFunction::IDType > & ufIDMap () const
const std::string & getName (const UninterpretedFunction &_uf) const
const std::vector< Sort > & getDomain (const UninterpretedFunction &_uf) const
const Sort & getCodomain (const UninterpretedFunction &_uf) const
std::ostream & print (std::ostream &_out, const UninterpretedFunction &_uf) const
Prints the given uninterpreted function on the given output stream.
UninterpretedFunction newUninterpretedFunction (std::string &&_name, std::vector< Sort > &&_domain, Sort _codomain)
Gets the uninterpreted function with the given name, domain, arguments and codomain.
Static Public Member Functions
static UFManager & getInstance ()
Returns the single instance of this class by reference.
Private Member Functions
UFManager ()
Constructs an uninterpreted functions manager.
~UFManager () override
UninterpretedFunction newUF (const UFContent *_sc)
Tries to add the given uninterpreted function's content to the so far stored uninterpreted function's contents.
Private Attributes
friend Singleton< UFManager >
FastPointerMap< UFContent, UninterpretedFunction::IDType > mUFIdMap
Stores all instantiated uninterpreted function's contents and maps them to their unique id.
std::vector< const UFContent * > mUFs
Maps the unique ids to the instantiated uninterpreted function's content.
Detailed Description
Implements a manager for uninterpreted functions, containing their actual contents and allocating their ids.
Definition at line 157 of file UFManager.h.
Constructor & Destructor Documentation
UFManager()
carl::UFManager::UFManager () inline private
Constructs an uninterpreted functions manager.
Definition at line 173 of file UFManager.h.
~UFManager()
carl::UFManager::~UFManager () inline override private
Definition at line 176 of file UFManager.h.
Member Function Documentation
getCodomain()
const Sort& carl::UFManager::getCodomain (const UninterpretedFunction & _uf) const inline
Parameters
_uf An uninterpreted function.
Returns
The codomain of the uninterpreted function of the given uninterpreted function.
Definition at line 226 of file UFManager.h.
Referenced by carl::UninterpretedFunction::codomain().
getDomain()
const std::vector<Sort>& carl::UFManager::getDomain (const UninterpretedFunction & _uf) const inline
Parameters
_uf An uninterpreted function.
Returns
The domain of the uninterpreted function of the given uninterpreted function.
Definition at line 215 of file UFManager.h.
Referenced by carl::UninterpretedFunction::domain().
getInstance()
static UFManager & carl::Singleton< UFManager >::getInstance () inline static inherited
Returns the single instance of this class by reference.
If there is no instance yet, a new one is created.
Definition at line 48 of file Singleton.h.
Referenced by carl::UninterpretedFunction::codomain(), carl::UninterpretedFunction::domain(), carl::UFModel::get(), carl::UninterpretedFunction::name(), carl::newUninterpretedFunction(), and carl::operator<<().
getName()
const std::string& carl::UFManager::getName (const UninterpretedFunction & _uf) const inline
Parameters
_uf An uninterpreted function.
Returns
The name of the uninterpreted function of the given uninterpreted function.
Definition at line 204 of file UFManager.h.
Referenced by carl::UninterpretedFunction::name().
newUF()
UninterpretedFunction carl::UFManager::newUF (const UFContent * _sc) private
Tries to add the given uninterpreted function's content to the so far stored uninterpreted function's contents.
If it has already been stored, if will be deleted and the id of the already existing uninterpreted function's content will be used to create the returned uninterpreted function.
Parameters
_sc The uninterpreted function's content to store.
Returns
The uninterpreted function corresponding to the given content.
Definition at line 29 of file UFManager.cpp.
Referenced by newUninterpretedFunction().
newUninterpretedFunction()
UninterpretedFunction carl::UFManager::newUninterpretedFunction (std::string && _name, std::vector< Sort > && _domain, Sort _codomain) inline
Gets the uninterpreted function with the given name, domain, arguments and codomain.
Parameters
_name The name of the uninterpreted function of the uninterpreted function to get.
_domain The domain of the uninterpreted function of the uninterpreted function to get.
_codomain The codomain of the uninterpreted function of the uninterpreted function to get.
Returns
The resulting uninterpreted function.
Definition at line 248 of file UFManager.h.
Referenced by carl::newUninterpretedFunction().
print()
std::ostream & carl::UFManager::print (std::ostream & _out, const UninterpretedFunction & _uf) const
Prints the given uninterpreted function on the given output stream.
Parameters
_out The output stream to print the given uninterpreted function on.
_uf The uninterpreted function to print.
Returns
The output stream after printing the given uninterpreted function on it.
Definition at line 12 of file UFManager.cpp.
Referenced by carl::operator<<().
ufContents()
const std::vector<const UFContent*>& carl::UFManager::ufContents () const inline
Definition at line 193 of file UFManager.h.
ufIDMap()
const FastPointerMap<UFContent, UninterpretedFunction::IDType>& carl::UFManager::ufIDMap () const inline
Definition at line 196 of file UFManager.h.
Field Documentation
mUFIdMap
FastPointerMap<UFContent, UninterpretedFunction::IDType> carl::UFManager::mUFIdMap private
Stores all instantiated uninterpreted function's contents and maps them to their unique id.
Definition at line 166 of file UFManager.h.
Referenced by newUF(), ufIDMap(), and ~UFManager().
mUFs
std::vector<const UFContent*> carl::UFManager::mUFs private
Maps the unique ids to the instantiated uninterpreted function's content.
Definition at line 168 of file UFManager.h.
Referenced by getCodomain(), getDomain(), getName(), newUF(), print(), ufContents(), UFManager(), and ~UFManager().
Singleton< UFManager >
friend carl::UFManager::Singleton< UFManager > private
Definition at line 160 of file UFManager.h.
The documentation for this class was generated from the following files:
carl/formula/uninterpreted/UFManager.h
carl/formula/uninterpreted/UFManager.cpp