carl: carl::BaseNumber< T, N > Class Template Reference
carl::BaseNumber< T, N > Class Template Reference
#include <Number.h>
Public Member Functions
BaseNumber ()=default
BaseNumber (const BaseNumber &n)=default
BaseNumber (BaseNumber &&n)=default
BaseNumber & operator= (const BaseNumber &n)=default
BaseNumber & operator= (BaseNumber &&n)=default
~BaseNumber ()=default
BaseNumber (const T &t)
BaseNumber (T &&t)
BaseNumber (long long int n)
BaseNumber (unsigned long long int n)
BaseNumber (int i)
BaseNumber (const std::string &s)
const T & getValue () const noexcept
bool isZero () const
bool isOne () const
bool isPositive () const
bool isNegative () const
operator const T & () const noexcept
operator T & () noexcept
template<typename Other >
BaseNumber & operator= (const Other &n)
bool operator== (const BaseNumber &rhs) const
bool operator!= (const BaseNumber< T, N > &rhs) const
bool operator< (const BaseNumber< T, N > &rhs) const
bool operator<= (const BaseNumber< T, N > &rhs) const
bool operator>= (const BaseNumber< T, N > &rhs) const
bool operator> (const BaseNumber< T, N > &rhs) const
N operator+ (const BaseNumber< T, N > &rhs) const
N operator- (const BaseNumber< T, N > &rhs) const
N operator* (const BaseNumber< T, N > &rhs) const
N operator/ (const BaseNumber< T, N > &rhs) const
N operator- () const
N operator+= (const BaseNumber< T, N > &rhs)
N operator-= (const BaseNumber< T, N > &rhs)
N operator*= (const BaseNumber< T, N > &rhs)
N operator/= (const BaseNumber< T, N > &rhs)
Protected Attributes
T mData = carl::constant_zero<T>::get()
Detailed Description
template<typename T, typename N>
class carl::BaseNumber< T, N >
Definition at line 14 of file Number.h.
Constructor & Destructor Documentation
BaseNumber() [1/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber () default
BaseNumber() [2/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (const BaseNumber< T, N > & n) default
BaseNumber() [3/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (BaseNumber< T, N > && n) default
~BaseNumber()
template<typename T, typename N> carl::BaseNumber< T, N >::~BaseNumber () default
BaseNumber() [4/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (const T & t) inline explicit
Definition at line 25 of file Number.h.
BaseNumber() [5/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (T && t) inline explicit
Definition at line 26 of file Number.h.
BaseNumber() [6/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (long long int n) inline
Definition at line 27 of file Number.h.
BaseNumber() [7/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (unsigned long long int n) inline
Definition at line 28 of file Number.h.
BaseNumber() [8/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (int i) inline
Definition at line 29 of file Number.h.
BaseNumber() [9/9]
template<typename T, typename N> carl::BaseNumber< T, N >::BaseNumber (const std::string & s) inline explicit
Definition at line 30 of file Number.h.
Member Function Documentation
getValue()
template<typename T, typename N> const T& carl::BaseNumber< T, N >::getValue () const inline noexcept
Definition at line 33 of file Number.h.
Referenced by carl::Number< mpq_class >::Number(), and carl::operator<<().
isNegative()
template<typename T, typename N> bool carl::BaseNumber< T, N >::isNegative () const inline
Definition at line 50 of file Number.h.
Referenced by carl::Number< mpz_class >::quotient().
isOne()
template<typename T, typename N> bool carl::BaseNumber< T, N >::isOne () const inline
Definition at line 41 of file Number.h.
isPositive()
template<typename T, typename N> bool carl::BaseNumber< T, N >::isPositive () const inline
Definition at line 46 of file Number.h.
isZero()
template<typename T, typename N> bool carl::BaseNumber< T, N >::isZero () const inline
Definition at line 37 of file Number.h.
Referenced by carl::Number< mpq_class >::ceil(), carl::Number< mpq_class >::floor(), carl::Number< mpq_class >::round(), and carl::Number< mpq_class >::sqrt_exact().
operator const T &()
template<typename T, typename N> carl::BaseNumber< T, N >::operator const T & () const inline noexcept
Definition at line 54 of file Number.h.
operator T &()
template<typename T, typename N> carl::BaseNumber< T, N >::operator T& () inline noexcept
Definition at line 58 of file Number.h.
operator!=()
template<typename T, typename N> bool carl::BaseNumber< T, N >::operator!= (const BaseNumber< T, N > & rhs) const inline
Definition at line 73 of file Number.h.
operator*()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator* (const BaseNumber< T, N > & rhs) const inline
Definition at line 102 of file Number.h.
operator*=()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator*= (const BaseNumber< T, N > & rhs) inline
Definition at line 124 of file Number.h.
operator+()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator+ (const BaseNumber< T, N > & rhs) const inline
Definition at line 94 of file Number.h.
operator+=()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator+= (const BaseNumber< T, N > & rhs) inline
Definition at line 115 of file Number.h.
operator-() [1/2]
template<typename T, typename N> N carl::BaseNumber< T, N >::operator- (const BaseNumber< T, N > & rhs) const inline
Definition at line 98 of file Number.h.
operator-() [2/2]
template<typename T, typename N> N carl::BaseNumber< T, N >::operator- () const inline
Definition at line 110 of file Number.h.
operator-=()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator-= (const BaseNumber< T, N > & rhs) inline
Definition at line 119 of file Number.h.
operator/()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator/ (const BaseNumber< T, N > & rhs) const inline
Definition at line 106 of file Number.h.
operator/=()
template<typename T, typename N> N carl::BaseNumber< T, N >::operator/= (const BaseNumber< T, N > & rhs) inline
Definition at line 129 of file Number.h.
operator<()
template<typename T, typename N> bool carl::BaseNumber< T, N >::operator< (const BaseNumber< T, N > & rhs) const inline
Definition at line 77 of file Number.h.
operator<=()
template<typename T, typename N> bool carl::BaseNumber< T, N >::operator<= (const BaseNumber< T, N > & rhs) const inline
Definition at line 81 of file Number.h.
operator=() [1/3]
template<typename T, typename N> BaseNumber& carl::BaseNumber< T, N >::operator= (const BaseNumber< T, N > & n) default
operator=() [2/3]
template<typename T, typename N> BaseNumber& carl::BaseNumber< T, N >::operator= (BaseNumber< T, N > && n) default
operator=() [3/3]
template<typename T, typename N> template<typename Other > BaseNumber& carl::BaseNumber< T, N >::operator= (const Other & n) inline
Definition at line 63 of file Number.h.
operator==()
template<typename T, typename N> bool carl::BaseNumber< T, N >::operator== (const BaseNumber< T, N > & rhs) const inline
Definition at line 69 of file Number.h.
operator>()
template<typename T, typename N> bool carl::BaseNumber< T, N >::operator> (const BaseNumber< T, N > & rhs) const inline
Definition at line 89 of file Number.h.
operator>=()
template<typename T, typename N> bool carl::BaseNumber< T, N >::operator>= (const BaseNumber< T, N > & rhs) const inline
Definition at line 85 of file Number.h.
Field Documentation
mData
template<typename T, typename N> T carl::BaseNumber< T, N >::mData = carl::constant_zero<T>::get() protected
Definition at line 16 of file Number.h.
Referenced by carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::BaseNumber(), carl::Number< cln::cl_I >::div(), carl::Number< cln::cl_RA >::div(), carl::Number< mpz_class >::gcd(), carl::Number< cln::cl_I >::gcd(), carl::Number< mpq_class >::gcd(), carl::Number< cln::cl_RA >::gcd(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::getValue(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::isOne(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::isPositive(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::isZero(), carl::Number< mpz_class >::lcm(), carl::Number< cln::cl_I >::lcm(), carl::Number< mpq_class >::lcm(), carl::Number< cln::cl_RA >::lcm(), carl::Number< mpz_class >::mod(), carl::Number< cln::cl_I >::mod(), carl::BaseNumber< T, Number< T > >::operator const T &(), carl::BaseNumber< T, Number< T > >::operator T&(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator!=(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator*(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator*=(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator+(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator+=(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator-(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator-=(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator/(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator/=(), carl::Number< mpq_class >::operator=(), carl::Number< cln::cl_RA >::operator=(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator=(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator==(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator>(), carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::operator>=(), carl::Number< mpz_class >::quotient(), carl::Number< cln::cl_I >::quotient(), carl::Number< mpq_class >::quotient(), carl::Number< cln::cl_RA >::quotient(), and carl::Number< cln::cl_I >::remainder().
The documentation for this class was generated from the following file:
carl/numbers/number/Number.h