carl: carl::Sort Class Reference
carl::Sort Class Reference
Implements a sort (for defining types of variables and functions).
#include <Sort.h>
Public Types
using IDType = std::size_t
The type if the unique id to identify a sort in the sort manager.
Public Member Functions
Sort () noexcept=default
std::size_t arity () const
IDType id () const
Private Member Functions
Sort (IDType id)
Constructs a sort.
Private Attributes
IDType mId = 0
A unique id to identify this sort in the sort manager.
Friends
class SortManager
std::ostream & operator<< (std::ostream &_os, const Sort &_sort)
Prints the given sort on the given output stream.
Detailed Description
Implements a sort (for defining types of variables and functions).
Definition at line 20 of file Sort.h.
Member Typedef Documentation
IDType
using carl::Sort::IDType = std::size_t
The type if the unique id to identify a sort in the sort manager.
Definition at line 23 of file Sort.h.
Constructor & Destructor Documentation
Sort() [1/2]
carl::Sort::Sort (IDType id) inline explicit private
Constructs a sort.
Parameters
_id The id of the sort to construct.
Definition at line 37 of file Sort.h.
Sort() [2/2]
carl::Sort::Sort () default noexcept
Member Function Documentation
arity()
std::size_t carl::Sort::arity () const
Returns
The aritiy of this sort.
Definition at line 14 of file Sort.cpp.
Referenced by carl::SMTLIBStream::declare().
id()
IDType carl::Sort::id () const inline
Returns
The id of this sort.
Definition at line 51 of file Sort.h.
Referenced by carl::SortManager::getContent(), carl::SortManager::getType(), std::hash< carl::Sort >::operator()(), carl::operator<(), and carl::operator==().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & _os, const Sort & _sort) friend
Prints the given sort on the given output stream.
Parameters
_os The output stream to print on.
_sort The sort to print.
Returns
The output stream after printing the given sort on it.
Definition at line 18 of file Sort.cpp.
SortManager
friend class SortManager friend
Definition at line 25 of file Sort.h.
Field Documentation
mId
IDType carl::Sort::mId = 0 private
A unique id to identify this sort in the sort manager.
Definition at line 31 of file Sort.h.
Referenced by id().
The documentation for this class was generated from the following files:
carl/formula/Sort.h
carl/formula/Sort.cpp