carl: carl::IDPool Class Reference
carl::IDPool Class Reference
#include <IDPool.h>
Public Member Functions
std::size_t size () const
std::size_t largestID () const
std::size_t get ()
void free (std::size_t id)
void clear ()
Private Attributes
Bitset mFreeIDs = Bitset(true)
std::size_t mLargestID = 0
std::mutex mMutex
Friends
std::ostream & operator<< (std::ostream &os, const IDPool &p)
Detailed Description
Definition at line 11 of file IDPool.h.
Member Function Documentation
clear()
void carl::IDPool::clear () inline
Definition at line 48 of file IDPool.h.
Referenced by carl::MonomialPool::clear().
free()
void carl::IDPool::free (std::size_t id) inline
Definition at line 42 of file IDPool.h.
Referenced by carl::MonomialPool::free().
get()
std::size_t carl::IDPool::get () inline
Definition at line 30 of file IDPool.h.
Referenced by carl::MonomialPool::add(), and carl::MonomialPool::MonomialPool().
largestID()
std::size_t carl::IDPool::largestID () const inline
Definition at line 26 of file IDPool.h.
Referenced by carl::MonomialPool::largestID(), and carl::MonomialPool::MonomialPool().
size()
std::size_t carl::IDPool::size () const inline
Definition at line 22 of file IDPool.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const IDPool & p) friend
Definition at line 52 of file IDPool.h.
Field Documentation
mFreeIDs
Bitset carl::IDPool::mFreeIDs = Bitset(true) private
Definition at line 13 of file IDPool.h.
Referenced by clear(), free(), get(), and size().
mLargestID
std::size_t carl::IDPool::mLargestID = 0 private
Definition at line 14 of file IDPool.h.
Referenced by get(), and largestID().
mMutex
std::mutex carl::IDPool::mMutex mutable private
Definition at line 16 of file IDPool.h.
The documentation for this class was generated from the following file:
carl/util/IDPool.h