carl: carl::cad::ConflictGraph< Number > Class Template Reference
carl::cad::ConflictGraph< Number > Class Template Reference
Representation of a bipartite graph (U+W, E) of vertices U, representing the constraints, stored as their unsigned index in a vector; and W, representing the sample points, stored as a long index so that each index corresponds to exactly one sample point but a sample point must not neccessarily refer to one index (indices over-approximate the sample points).
#include <ConflictGraph.h>
Public Member Functions
ConflictGraph ()
Constructs an empty graph.
ConflictGraph (const ConflictGraph &g)
Copy constructor.
std::size_t getConstraint (const cad::Constraint< Number > &c)
Returns the constraint ID for the given constraint.
const cad::Constraint< Number > & getConstraint (std::size_t id) const
Returns the constraint for the given constraint ID.
std::size_t newSample ()
Registers a new sample point and returns its ID.
void set (std::size_t constraint, std::size_t sample, bool value)
std::size_t getMaxDegreeConstraint () const
Retrieves the constraint that covers the most samples.
void selectConstraint (std::size_t id)
Removes the given constraint and disable all sample points covered by this constraint.
bool hasRemainingSamples () const
Checks if there are samples still uncovered.
void removeConstraint (const cad::Constraint< Number > &c)
Remove the specified constraint vertex by removing the respective index.
Private Attributes
std::map< Constraint< Number >, std::size_t > mConstraints
Maps constraints to IDs used in mData.
std::vector< boost::dynamic_bitset<> > mData
Stores for each constraints, which sample points violate the constraint.
std::size_t mSampleCount = 0
Stores the number of samples that have been registered.
Friends
template<typename T >
std::ostream & operator<< (std::ostream &os, const ConflictGraph< T > &cg)
Detailed Description
template<typename Number>
class carl::cad::ConflictGraph< Number >
Representation of a bipartite graph (U+W, E) of vertices U, representing the constraints, stored as their unsigned index in a vector; and W, representing the sample points, stored as a long index so that each index corresponds to exactly one sample point but a sample point must not neccessarily refer to one index (indices over-approximate the sample points).
A vertex from U and a vertex from W are connected by an edge E iff the corresponding constraint is satisfied by the corresponding sample point. This information is fixed, however, we can invert the reading behavior by using invert().
There is no explicit storage of sample point information. Thus, the graph cannot be used for memoaization of satisfiability results.
Definition at line 46 of file ConflictGraph.h.
Constructor & Destructor Documentation
ConflictGraph() [1/2]
template<typename Number> carl::cad::ConflictGraph< Number >::ConflictGraph () inline
Constructs an empty graph.
Definition at line 59 of file ConflictGraph.h.
ConflictGraph() [2/2]
template<typename Number> carl::cad::ConflictGraph< Number >::ConflictGraph (const ConflictGraph< Number > & g) inline
Copy constructor.
Definition at line 64 of file ConflictGraph.h.
Member Function Documentation
getConstraint() [1/2]
template<typename Number> std::size_t carl::cad::ConflictGraph< Number >::getConstraint (const cad::Constraint< Number > & c) inline
Returns the constraint ID for the given constraint.
Definition at line 74 of file ConflictGraph.h.
Referenced by carl::cad::CADConstraints< carl::Number >::satisfiedBy(), and carl::cad::CADConstraints< carl::Number >::satisfiedPartiallyBy().
getConstraint() [2/2]
template<typename Number> const cad::Constraint<Number>& carl::cad::ConflictGraph< Number >::getConstraint (std::size_t id) const inline
Returns the constraint for the given constraint ID.
Definition at line 85 of file ConflictGraph.h.
getMaxDegreeConstraint()
template<typename Number> std::size_t carl::cad::ConflictGraph< Number >::getMaxDegreeConstraint () const inline
Retrieves the constraint that covers the most samples.
Definition at line 111 of file ConflictGraph.h.
hasRemainingSamples()
template<typename Number> bool carl::cad::ConflictGraph< Number >::hasRemainingSamples () const inline
Checks if there are samples still uncovered.
Definition at line 149 of file ConflictGraph.h.
newSample()
template<typename Number> std::size_t carl::cad::ConflictGraph< Number >::newSample () inline
Registers a new sample point and returns its ID.
Definition at line 95 of file ConflictGraph.h.
Referenced by carl::cad::CADConstraints< carl::Number >::satisfiedBy(), and carl::cad::CADConstraints< carl::Number >::satisfiedPartiallyBy().
removeConstraint()
template<typename Number> void carl::cad::ConflictGraph< Number >::removeConstraint (const cad::Constraint< Number > & c) inline
Remove the specified constraint vertex by removing the respective index.
All other constraint indices are decreased by one.
Parameters
i constraint vertex index
Runtime complexity:
constant
Definition at line 163 of file ConflictGraph.h.
selectConstraint()
template<typename Number> void carl::cad::ConflictGraph< Number >::selectConstraint (std::size_t id) inline
Removes the given constraint and disable all sample points covered by this constraint.
Definition at line 127 of file ConflictGraph.h.
set()
template<typename Number> void carl::cad::ConflictGraph< Number >::set (std::size_t constraint, std::size_t sample, bool value) inline
Definition at line 98 of file ConflictGraph.h.
Referenced by carl::cad::CADConstraints< carl::Number >::satisfiedBy(), and carl::cad::CADConstraints< carl::Number >::satisfiedPartiallyBy().
Friends And Related Function Documentation
operator<<
template<typename Number> template<typename T > std::ostream& operator<< (std::ostream & os, const ConflictGraph< T > & cg) friend
Definition at line 178 of file ConflictGraph.h.
Field Documentation
mConstraints
template<typename Number> std::map<Constraint<Number>, std::size_t> carl::cad::ConflictGraph< Number >::mConstraints private
Maps constraints to IDs used in mData.
Definition at line 49 of file ConflictGraph.h.
Referenced by carl::cad::ConflictGraph< Number >::getConstraint(), and carl::cad::ConflictGraph< Number >::removeConstraint().
mData
template<typename Number> std::vector<boost::dynamic_bitset<> > carl::cad::ConflictGraph< Number >::mData private
Stores for each constraints, which sample points violate the constraint.
Definition at line 51 of file ConflictGraph.h.
Referenced by carl::cad::ConflictGraph< Number >::getMaxDegreeConstraint(), carl::cad::ConflictGraph< Number >::hasRemainingSamples(), carl::cad::ConflictGraph< Number >::removeConstraint(), carl::cad::ConflictGraph< Number >::selectConstraint(), and carl::cad::ConflictGraph< Number >::set().
mSampleCount
template<typename Number> std::size_t carl::cad::ConflictGraph< Number >::mSampleCount = 0 private
Stores the number of samples that have been registered.
Definition at line 53 of file ConflictGraph.h.
Referenced by carl::cad::ConflictGraph< Number >::newSample().
The documentation for this class was generated from the following file:
carl/cad/ConflictGraph.h