carl: carl::VariableComparison< Poly > Class Template Reference
carl::VariableComparison< Poly > Class Template Reference
Represent a sum type/variant of an (in)equality between a variable on the left-hand side and multivariateRoot or algebraic real on the right-hand side.
#include <VariableComparison.h>
Data Structures
struct VariableCollector
Public Types
using Number = typename UnderlyingNumberType< Poly >::type
using MR = MultivariateRoot< Poly >
using RAN = RealAlgebraicNumber< Number >
Public Member Functions
VariableComparison (Variable v, const boost::variant< MR, RAN > &value, Relation rel, bool neg)
VariableComparison (Variable v, const MR &value, Relation rel)
VariableComparison (Variable v, const RAN &value, Relation rel)
Variable var () const
Relation relation () const
bool negated () const
const boost::variant< MR, RAN > & value () const
bool isEquality () const
boost::optional< Constraint< Poly > > asConstraint () const
Convert this variable comparison "v < root(..)" into a simpler polynomial (in)equality against zero "p(..) < 0" if that is possible.
Poly definingPolynomial () const
VariableComparison negation () const
VariableComparison invertRelation () const
void collectVariables (Variables &vars) const
std::string toString (unsigned=0, bool=false, bool=true) const
Private Attributes
Variable mVar
boost::variant< MR, RAN > mValue
Relation mRelation
bool mNegated
Detailed Description
template<typename Poly>
class carl::VariableComparison< Poly >
Represent a sum type/variant of an (in)equality between a variable on the left-hand side and multivariateRoot or algebraic real on the right-hand side.
This is basically a special purpose atomic SMT formula. The lhs-variable must does not appear on the rhs.
Definition at line 25 of file VariableComparison.h.
Member Typedef Documentation
MR
template<typename Poly> using carl::VariableComparison< Poly >::MR = MultivariateRoot<Poly>
Definition at line 28 of file VariableComparison.h.
Number
template<typename Poly> using carl::VariableComparison< Poly >::Number = typename UnderlyingNumberType<Poly>::type
Definition at line 27 of file VariableComparison.h.
RAN
template<typename Poly> using carl::VariableComparison< Poly >::RAN = RealAlgebraicNumber<Number>
Definition at line 29 of file VariableComparison.h.
Constructor & Destructor Documentation
VariableComparison() [1/3]
template<typename Poly> carl::VariableComparison< Poly >::VariableComparison (Variable v, const boost::variant< MR, RAN > & value, Relation rel, bool neg) inline
Definition at line 52 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::invertRelation(), and carl::VariableComparison< Pol >::negation().
VariableComparison() [2/3]
template<typename Poly> carl::VariableComparison< Poly >::VariableComparison (Variable v, const MR & value, Relation rel) inline
Definition at line 53 of file VariableComparison.h.
VariableComparison() [3/3]
template<typename Poly> carl::VariableComparison< Poly >::VariableComparison (Variable v, const RAN & value, Relation rel) inline
Definition at line 63 of file VariableComparison.h.
Member Function Documentation
asConstraint()
template<typename Poly> boost::optional<Constraint<Poly> > carl::VariableComparison< Poly >::asConstraint () const inline
Convert this variable comparison "v < root(..)" into a simpler polynomial (in)equality against zero "p(..) < 0" if that is possible.
Returns
boost::none if conversion impossible.
Definition at line 86 of file VariableComparison.h.
Referenced by carl::FormulaPool< Pol >::create().
collectVariables()
template<typename Poly> void carl::VariableComparison< Poly >::collectVariables (Variables & vars) const inline
Definition at line 116 of file VariableComparison.h.
Referenced by carl::VariableAssignment< Pol >::collectVariables().
definingPolynomial()
template<typename Poly> Poly carl::VariableComparison< Poly >::definingPolynomial () const inline
Definition at line 100 of file VariableComparison.h.
invertRelation()
template<typename Poly> VariableComparison carl::VariableComparison< Poly >::invertRelation () const inline
Definition at line 113 of file VariableComparison.h.
isEquality()
template<typename Poly> bool carl::VariableComparison< Poly >::isEquality () const inline
Definition at line 77 of file VariableComparison.h.
negated()
template<typename Poly> bool carl::VariableComparison< Poly >::negated () const inline
Definition at line 71 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::VariableComparison< Pol >::isEquality(), carl::VariableAssignment< Pol >::negated(), std::hash< carl::VariableComparison< Pol > >::operator()(), carl::operator<(), carl::operator==(), and carl::VariableComparison< Pol >::toString().
negation()
template<typename Poly> VariableComparison carl::VariableComparison< Poly >::negation () const inline
Definition at line 110 of file VariableComparison.h.
Referenced by carl::FormulaPool< Pol >::createNegatedContent(), and carl::FormulaPool< Pol >::isBaseFormula().
relation()
template<typename Poly> Relation carl::VariableComparison< Poly >::relation () const inline
Definition at line 68 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::isEquality(), std::hash< carl::VariableComparison< Pol > >::operator()(), carl::operator==(), and carl::VariableComparison< Pol >::toString().
toString()
template<typename Poly> std::string carl::VariableComparison< Poly >::toString (unsigned = 0, bool = false, bool = true) const inline
Definition at line 122 of file VariableComparison.h.
value()
template<typename Poly> const boost::variant<MR, RAN>& carl::VariableComparison< Poly >::value () const inline
Definition at line 74 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), std::hash< carl::VariableComparison< Pol > >::operator()(), carl::operator==(), carl::VariableAssignment< Pol >::value(), and carl::VariableComparison< Pol >::VariableComparison().
var()
template<typename Poly> Variable carl::VariableComparison< Poly >::var () const inline
Definition at line 65 of file VariableComparison.h.
Referenced by std::hash< carl::VariableComparison< Pol > >::operator()(), carl::operator==(), carl::VariableComparison< Pol >::toString(), and carl::VariableAssignment< Pol >::var().
Field Documentation
mNegated
template<typename Poly> bool carl::VariableComparison< Poly >::mNegated private
Definition at line 34 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::invertRelation(), carl::VariableComparison< Pol >::negated(), and carl::VariableComparison< Pol >::negation().
mRelation
template<typename Poly> Relation carl::VariableComparison< Poly >::mRelation private
Definition at line 33 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::VariableComparison< Pol >::invertRelation(), carl::VariableComparison< Pol >::negation(), and carl::VariableComparison< Pol >::relation().
mValue
template<typename Poly> boost::variant<MR, RAN> carl::VariableComparison< Poly >::mValue private
Definition at line 32 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::VariableComparison< Pol >::collectVariables(), carl::VariableComparison< Pol >::definingPolynomial(), carl::VariableComparison< Pol >::invertRelation(), carl::VariableComparison< Pol >::negation(), carl::VariableComparison< Pol >::toString(), carl::VariableComparison< Pol >::value(), and carl::VariableComparison< Pol >::VariableComparison().
mVar
template<typename Poly> Variable carl::VariableComparison< Poly >::mVar private
Definition at line 31 of file VariableComparison.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::VariableComparison< Pol >::collectVariables(), carl::VariableComparison< Pol >::definingPolynomial(), carl::VariableComparison< Pol >::invertRelation(), carl::VariableComparison< Pol >::negation(), and carl::VariableComparison< Pol >::var().
The documentation for this class was generated from the following file:
carl/formula/VariableComparison.h