carl: carl::RealAlgebraicNumberIR< Number > Class Template Reference
carl::RealAlgebraicNumberIR< Number > Class Template Reference
#include <RealAlgebraicNumberIR.h>
Public Member Functions
virtual std::shared_ptr
< RealAlgebraicNumber< Number > > clone () const
Creates a copy of this RealAlgebraicNumberIR.
virtual ~RealAlgebraicNumberIR ()
Destructor.
bool isZero () const
Checks if the value of this RealAlgebraicNumberIR is zero.
virtual bool isNumericRepresentation () const
Checks if this RealAlgebraicNumberIR is in numeric representation.
virtual Number branchingPoint ()
Computes a point that can be used for branching.
virtual bool isIntegral ()
Checks if the represented value is integral.
const UnivariatePolynomial
< Number > & getPolynomial () const
Selects the polynomial having this real algebraic number as one of its roots.
const Interval< Number > & getInterval () const
Selects the open interval ]l, r[ containing the real algebraic number.
const Number & lower () const
Retrieves the lower bound of the interval.
const Number & upper () const
Retrieves the upper bound of the interval.
void setLower (const Number &n) const
Sets the lower bound of the interval.
void setUpper (const Number &n) const
Sets the upper bound of the interval.
const std::list
< UnivariatePolynomial< Number > > & getSturmSequence () const
Returns a pre-computed standard Sturm sequence of the polynomial and its derivative.
unsigned getRefinementCount () const
Returns how often one of the refine methods was called before.
std::shared_ptr
< RealAlgebraicNumber< Number > > add (const RealAlgebraicNumberNRPtr< Number > &n)
Creates a new real algebraic number that is the sum of this and n.
std::shared_ptr
< RealAlgebraicNumber< Number > > add (const RealAlgebraicNumberIRPtr< Number > &n)
std::shared_ptr
< RealAlgebraicNumber< Number > > minus () const
Creates the negation of this RealAlgebraicNumberIR.
virtual bool containedIn (const Interval< Number > &i)
Checks if the interval that defines this number is contained in the given interval.
bool equal (std::shared_ptr< RealAlgebraicNumberIR > &n)
Checks if this RealAlgebraicNumberIR is equal to the given RealAlgebraicNumberIR.
bool lessWhileUnequal (std::shared_ptr< RealAlgebraicNumberIR > n)
Checks if the represented number is less than the given one, assuming that they are not equal.
void normalizeInterval ()
Normalizes the interval of an real algebraic number to not contain zero, in case the number is non-zero.
void coarsen (const Interval< Number > &interval) const
Coarsen the given isolating interval as much as possible while staying in the given interval.
void refine (RealAlgebraicNumberSettings::RefinementStrategy strategy=RealAlgebraicNumberSettings::RefinementStrategy::DEFAULT)
Refines the interval i of this real algebraic number yielding the interval j such that 2*(j.Right()-j.Left()) <= i.Right()-i.Left().
void refine (const Number &eps)
Refines the interval i of this real algebraic number yielding the interval j such that (j.Right()-j.Left()) <= eps.
bool refineAvoiding (const Number &n)
Refines the interval i of this real algebraic number yielding the interval j such that !j.meets(n).
Sign sgn () const
Retrieves the sign of the represented number.
Sign sgn (const UnivariatePolynomial< Number > &p) const
Given a univariate polynomial, calculates the sign of the evaluation of this polynomial at the point represented by this number.
bool isRoot () const
void setIsRoot (bool isRoot)
Set the flag marking whether the real algebraic number stems from a root computation or not.
bool isNumeric () const
bool isIntegral () const
Number branchingPoint () const
const Number & value () const
Sign sgn (const Polynomial &p) const
bool containedIn (const Interval< Number > &i) const
bool refineAvoiding (const Number &n) const
void refine (RealAlgebraicNumberSettings::RefinementStrategy strategy=RealAlgebraicNumberSettings::RefinementStrategy::DEFAULT) const
bool equal (const RealAlgebraicNumber< Number > &n) const
bool less (const RealAlgebraicNumber< Number > &n) const
std::pair< bool, bool > checkOrder (const RealAlgebraicNumber< Number > &n) const
bool lessWhileUnequal (const RealAlgebraicNumber< Number > &n) const
Static Public Member Functions
static std::shared_ptr
< RealAlgebraicNumber< Number > > create (Variable::Arg var)
Creates a new RealAlgebraicNumberIR with value zero.
static std::shared_ptr
< RealAlgebraicNumber< Number > > create (const UnivariatePolynomial< Number > &p, const Interval< Number > &i, const bool normalize=true, const bool isRoot=true)
static std::shared_ptr
< RealAlgebraicNumber< Number > > create (const UnivariatePolynomial< Number > &p, const std::list< UnivariatePolynomial< Number >> &seq, const Interval< Number > &i, const bool normalize=true, const bool isRoot=true)
Protected Attributes
UnivariatePolynomial< Number > polynomial
Pointer to the polynomial of this interval representation.
std::list
< UnivariatePolynomial< Number > > sturmSequence
Interval< Number > interval
Isolating interval of this interval representation.
unsigned int refinementCount
Number of refinements executed to the isolating interval.
Private Member Functions
std::shared_ptr
< RealAlgebraicNumberIR > thisPtr () const
RealAlgebraicNumberIR (Variable::Arg var)
RealAlgebraicNumberIR (const UnivariatePolynomial< Number > &p, const std::list< UnivariatePolynomial< Number >> &seq, const Interval< Number > &i, const bool normalize=true, const bool isRoot=true)
Constructs a real algebraic number in interval and order representation (p, l, r, o) with a normalized interval w.r.t.
std::pair< bool, bool > checkOrder (std::shared_ptr< RealAlgebraicNumberIR > n)
Checks if this < n.
std::pair< bool, bool > intervalContained (std::shared_ptr< RealAlgebraicNumberIR > n, bool twisted)
Checks if the interval of the given number is contained in the interval of this.
bool checkIntersection (std::shared_ptr< RealAlgebraicNumberIR > n, const Interval< Number > i)
Check if the intersection i of this and n can be used for refinements.
bool isRootOf (const UnivariatePolynomial< Number > &p) const
Private Attributes
std::weak_ptr
< RealAlgebraicNumberIR > pThis
Friends
template<typename Num >
std::ostream & operator<< (std::ostream &os, const RealAlgebraicNumberIR< Num > *n)
Streaming operator for a RealAlgebraicNumberIR.
Detailed Description
template<typename Number>
class carl::RealAlgebraicNumberIR< Number >
Todo:
Add EnableIf<is_fraction<Number>> such that gcc does not crash.
Definition at line 18 of file RealAlgebraicNumberIR.h.
Constructor & Destructor Documentation
template<typename Number > carl::RealAlgebraicNumberIR< Number >::RealAlgebraicNumberIR (const UnivariatePolynomial< Number > & p, const std::list< UnivariatePolynomial< Number >> & seq, const Interval< Number > & i, const bool normalize = true, const bool isRoot = true) private
Constructs a real algebraic number in interval and order representation (p, l, r, o) with a normalized interval w.r.t.
normalizeInterval.
p can be changed within the constructor, but is later constant.
i can be changed later by refine(), but is only normalized within the constructor in case not normalized before.
Parameters
p polynomial having the real algebraic number as one of its roots
i open interval ]l, r[ containing the real algebraic number (should be normalized)
s standard Sturm sequence
normalize if set to false, the interval will not be normalized in the constructor (default is true)
isRoot true marks this real algebraic number to stem from a root computation
Definition at line 29 of file RealAlgebraicNumberIR.tpp.
Member Function Documentation
template<typename Number > std::shared_ptr<RealAlgebraicNumber<Number> > carl::RealAlgebraicNumberIR< Number >::add (const RealAlgebraicNumberNRPtr< Number > & n)
Creates a new real algebraic number that is the sum of this and n.
Implemented following Mishra93 page 332.
Parameters
n Other number.
Returns
this + n.
template<typename Number > virtual Number carl::RealAlgebraicNumberIR< Number >::branchingPoint () inline virtual
Computes a point that can be used for branching.
The interval may be refined in the process. If the represented value is an integer, zero is returned.
Definition at line 148 of file RealAlgebraicNumberIR.h.
template<typename Number > bool carl::RealAlgebraicNumberIR< Number >::checkIntersection (std::shared_ptr< RealAlgebraicNumberIR< Number > > n, const Interval< Number > i) private
Check if the intersection i of this and n can be used for refinements.
Parameters
n RealAlgebraicNumberIR.
i Intersection.
Returns
If a refinement was done.
Definition at line 205 of file RealAlgebraicNumberIR.tpp.
template<typename Number > std::pair< bool, bool > carl::RealAlgebraicNumberIR< Number >::checkOrder (std::shared_ptr< RealAlgebraicNumberIR< Number > > n) private
Checks if this < n.
If the method could not decide the order, it returns (false, false) Otherwise, it returns (true, X), X being the value of *this < *n
Parameters
n Another RealAlgebraicNumberIR
Returns
Definition at line 134 of file RealAlgebraicNumberIR.tpp.
template<typename Number > virtual std::shared_ptr<RealAlgebraicNumber<Number> > carl::RealAlgebraicNumberIR< Number >::clone () const inline virtual
Creates a copy of this RealAlgebraicNumberIR.
Returns
Copy of this.
Definition at line 118 of file RealAlgebraicNumberIR.h.
template<typename Number > void carl::RealAlgebraicNumberIR< Number >::coarsen (const Interval< Number > & interval) const
Coarsen the given isolating interval as much as possible while staying in the given interval.
If interval is no over-approximation of the current isolating interval, do nothing.
Parameters
interval
Definition at line 323 of file RealAlgebraicNumberIR.tpp.
template<typename Number > virtual bool carl::RealAlgebraicNumberIR< Number >::containedIn (const Interval< Number > & i) inline virtual
Checks if the interval that defines this number is contained in the given interval.
Parameters
i Interval.
Returns
If the interval of this number is contained in i.
Definition at line 263 of file RealAlgebraicNumberIR.h.
template<typename Number > static std::shared_ptr<RealAlgebraicNumber<Number> > carl::RealAlgebraicNumberIR< Number >::create (Variable::Arg var) inline static
Creates a new RealAlgebraicNumberIR with value zero.
Parameters
var Variable.
Returns
New RealAlgebraicNumberIR of value zero.
Definition at line 82 of file RealAlgebraicNumberIR.h.
Referenced by carl::RealAlgebraicNumberIR< Number >::clone(), and carl::RealAlgebraicNumberIR< Number >::minus().
template<typename Number > bool carl::RealAlgebraicNumberIR< Number >::equal (std::shared_ptr< RealAlgebraicNumberIR< Number > > & n)
Checks if this RealAlgebraicNumberIR is equal to the given RealAlgebraicNumberIR.
Parameters
n RealAlgebraicNumberIR.
Returns
this == n.
Definition at line 92 of file RealAlgebraicNumberIR.tpp.
Referenced by carl::equal_to< std::shared_ptr< carl::RealAlgebraicNumber< Number > > >::operator()().
template<typename Number > const Interval<Number>& carl::RealAlgebraicNumberIR< Number >::getInterval () const inline
Selects the open interval ]l, r[ containing the real algebraic number.
Returns
open interval ]l, r[ containing the real algebraic number
Definition at line 179 of file RealAlgebraicNumberIR.h.
Referenced by carl::RealAlgebraicNumberIR< Number >::containedIn(), carl::RealAlgebraicNumberIR< Number >::lower(), carl::RealAlgebraicNumberIR< Number >::refine(), and carl::RealAlgebraicNumberIR< Number >::upper().
template<typename Number > const UnivariatePolynomial<Number>& carl::RealAlgebraicNumberIR< Number >::getPolynomial () const inline
Selects the polynomial having this real algebraic number as one of its roots.
Returns
polynomial having the number as one of its roots
Definition at line 171 of file RealAlgebraicNumberIR.h.
template<typename Number > unsigned carl::RealAlgebraicNumberIR< Number >::getRefinementCount () const inline
Returns how often one of the refine methods was called before.
Returns
number of refinement steps executed on this real algebraic number
Definition at line 226 of file RealAlgebraicNumberIR.h.
template<typename Number > const std::list<UnivariatePolynomial<Number> >& carl::RealAlgebraicNumberIR< Number >::getSturmSequence () const inline
Returns a pre-computed standard Sturm sequence of the polynomial and its derivative.
Returns
standard Sturm sequence of the polynomial and its derivative.
Definition at line 218 of file RealAlgebraicNumberIR.h.
template<typename Number > std::pair< bool, bool > carl::RealAlgebraicNumberIR< Number >::intervalContained (std::shared_ptr< RealAlgebraicNumberIR< Number > > n, bool twisted) private
Checks if the interval of the given number is contained in the interval of this.
Also checks, if the interval of n can be used to refinde this number.
Parameters
n RealAlgebraicNumberIR.
twisted Flag whether this is larger or smaller than n.
Returns
Definition at line 173 of file RealAlgebraicNumberIR.tpp.
template<typename Number > virtual bool carl::RealAlgebraicNumberIR< Number >::isIntegral () inline virtual
Checks if the represented value is integral.
The interval may be refined in the process.
Returns
If this is integral.
Definition at line 159 of file RealAlgebraicNumberIR.h.
Referenced by carl::RealAlgebraicNumberIR< Number >::branchingPoint().
template<typename Number > virtual bool carl::RealAlgebraicNumberIR< Number >::isNumericRepresentation () const inline virtual
Checks if this RealAlgebraicNumberIR is in numeric representation.
Returns
false.
Definition at line 140 of file RealAlgebraicNumberIR.h.
template<typename Number> bool carl::RealAlgebraicNumber< Number >::isRoot () const inline inherited
Returns
the flag marking whether the real algebraic number stems from a root computation or not
Definition at line 130 of file NewRealAlgebraicNumber.h.
Referenced by carl::RealAlgebraicNumberIR< Number >::clone(), carl::cad::SampleSet< Number >::SampleComparator::compareRoot(), carl::cad::SampleSet< Number >::insert(), carl::cad::SampleSet< Number >::SampleComparator::isOptimal(), carl::RealAlgebraicNumber< carl::Number >::setIsRoot(), and carl::CAD< Number >::storeSampleInTree().
template<typename Number > bool carl::RealAlgebraicNumberIR< Number >::isZero () const inline
Checks if the value of this RealAlgebraicNumberIR is zero.
Returns
If this is zero.
Definition at line 132 of file RealAlgebraicNumberIR.h.
template<typename Number > bool carl::RealAlgebraicNumberIR< Number >::lessWhileUnequal (std::shared_ptr< RealAlgebraicNumberIR< Number > > n)
Checks if the represented number is less than the given one, assuming that they are not equal.
While checking, both numbers are refined until the intervals of the numbers are disjoint.
Parameters
n RealAlgebraicNumberIR.
Returns
this < n.
Definition at line 243 of file RealAlgebraicNumberIR.tpp.
template<typename Number > const Number& carl::RealAlgebraicNumberIR< Number >::lower () const inline
Retrieves the lower bound of the interval.
Returns
Lower bound.
Definition at line 188 of file RealAlgebraicNumberIR.h.
template<typename Number > RealAlgebraicNumberPtr< Number > carl::RealAlgebraicNumberIR< Number >::minus () const
Creates the negation of this RealAlgebraicNumberIR.
Returns
-this.
Definition at line 84 of file RealAlgebraicNumberIR.tpp.
template<typename Number > void carl::RealAlgebraicNumberIR< Number >::refine (RealAlgebraicNumberSettings::RefinementStrategy strategy = RealAlgebraicNumberSettings::RefinementStrategy::DEFAULT)
Refines the interval i of this real algebraic number yielding the interval j such that 2*(j.Right()-j.Left()) <= i.Right()-i.Left().
This is cutting the interval in the middle and choosing the half where the root lays in.
Parameters
strategy strategy selection according to RealAlgebraicNumberFactory::searchRealRootsStrategy
Runtime complexity:
constant
Space complexity:
constant
Definition at line 341 of file RealAlgebraicNumberIR.tpp.
Referenced by carl::RealAlgebraicNumberIR< Number >::isIntegral(), and carl::RealAlgebraicNumberIR< Number >::refine().
template<typename Number > void carl::RealAlgebraicNumberIR< Number >::refine (const Number & eps) inline
Refines the interval i of this real algebraic number yielding the interval j such that (j.Right()-j.Left()) <= eps.
Parameters
eps
Definition at line 344 of file RealAlgebraicNumberIR.h.
template<typename Number > bool carl::RealAlgebraicNumberIR< Number >::refineAvoiding (const Number & n)
Refines the interval i of this real algebraic number yielding the interval j such that !j.meets(n).
If true is returned, n is the exact numeric representation of this root. Otherwise not.
Parameters
n
Runtime complexity:
constant
Space complexity:
constant
Returns
true, if n is the exact numeric representation of this root, otherwise false
Definition at line 382 of file RealAlgebraicNumberIR.tpp.
Referenced by carl::RealAlgebraicNumberIR< Number >::containedIn(), and carl::less< std::shared_ptr< carl::RealAlgebraicNumber< Number > > >::operator()().
template<typename Number> void carl::RealAlgebraicNumber< Number >::setIsRoot (bool isRoot) inline inherited
Set the flag marking whether the real algebraic number stems from a root computation or not.
Parameters
isRoot
Definition at line 138 of file NewRealAlgebraicNumber.h.
template<typename Number > void carl::RealAlgebraicNumberIR< Number >::setLower (const Number & n) const inline
Sets the lower bound of the interval.
Parameters
n Lower bound.
Definition at line 203 of file RealAlgebraicNumberIR.h.
template<typename Number > void carl::RealAlgebraicNumberIR< Number >::setUpper (const Number & n) const inline
Sets the upper bound of the interval.
Parameters
n Upper bound.
Definition at line 210 of file RealAlgebraicNumberIR.h.
template<typename Number > Sign carl::RealAlgebraicNumberIR< Number >::sgn () const
Retrieves the sign of the represented number.
Returns
Sign of this number.
Definition at line 460 of file RealAlgebraicNumberIR.tpp.
template<typename Number > Sign carl::RealAlgebraicNumberIR< Number >::sgn (const UnivariatePolynomial< Number > & p) const
Given a univariate polynomial, calculates the sign of the evaluation of this polynomial at the point represented by this number.
Parameters
p UnivariatePolynomial.
Returns
sgn(p(this)).
Definition at line 467 of file RealAlgebraicNumberIR.tpp.
template<typename Number > const Number& carl::RealAlgebraicNumberIR< Number >::upper () const inline
Retrieves the upper bound of the interval.
Returns
Upper bound.
Definition at line 195 of file RealAlgebraicNumberIR.h.
Friends And Related Function Documentation
template<typename Number > template<typename Num > std::ostream& operator<< (std::ostream & os, const RealAlgebraicNumberIR< Num > * n) friend
Streaming operator for a RealAlgebraicNumberIR.
Parameters
os Output stream.
n Number.
Returns
os.
Field Documentation
template<typename Number > Interval<Number> carl::RealAlgebraicNumberIR< Number >::interval mutable protected
Isolating interval of this interval representation.
The interval is mutable, that means it may be changed by const methods, as the actual data is the represented root. However, all methods must make sure, that the interval always includes the same root.
Definition at line 34 of file RealAlgebraicNumberIR.h.
Referenced by carl::RealAlgebraicNumberIR< Number >::branchingPoint(), carl::RealAlgebraicNumberIR< Number >::clone(), carl::RealAlgebraicNumberIR< Number >::getInterval(), carl::RealAlgebraicNumberIR< Number >::isIntegral(), carl::RealAlgebraicNumberIR< Number >::isZero(), carl::RealAlgebraicNumberIR< Number >::RealAlgebraicNumberIR(), carl::RealAlgebraicNumberIR< Number >::setLower(), and carl::RealAlgebraicNumberIR< Number >::setUpper().
The documentation for this class was generated from the following files:
carl/core/RealAlgebraicNumberIR.h
carl/core/RealAlgebraicNumberIR.tpp