carl: carl::UTerm Class Reference
carl::UTerm Class Reference
Implements an uninterpreted term, that is either an uninterpreted variable or an uninterpreted function instance.
#include <UTerm.h>
Public Member Functions
UTerm ()=default
Default constructor.
UTerm (UVariable v)
UTerm (UFInstance ufi)
UTerm (const Super &term)
Constructs an uninterpreted term.
const auto & asVariant () const
bool isUVariable () const
bool isUFInstance () const
UVariable asUVariable () const
UFInstance asUFInstance () const
Sort domain () const
std::size_t complexity () const
void gatherVariables (carlVariables &vars) const
void gatherUFs (std::set< UninterpretedFunction > &ufs) const
Private Types
using Super = std::variant< UVariable, UFInstance >
Private Attributes
Super mTerm
Detailed Description
Implements an uninterpreted term, that is either an uninterpreted variable or an uninterpreted function instance.
Definition at line 22 of file UTerm.h.
Member Typedef Documentation
Super
using carl::UTerm::Super = std::variant<UVariable, UFInstance> private
Definition at line 23 of file UTerm.h.
Constructor & Destructor Documentation
UTerm() [1/4]
carl::UTerm::UTerm () default
Default constructor.
UTerm() [2/4]
carl::UTerm::UTerm (UVariable v) inline
Definition at line 32 of file UTerm.h.
UTerm() [3/4]
carl::UTerm::UTerm (UFInstance ufi) inline
Definition at line 33 of file UTerm.h.
UTerm() [4/4]
carl::UTerm::UTerm (const Super & term) inline explicit
Constructs an uninterpreted term.
Parameters
term
Definition at line 39 of file UTerm.h.
Member Function Documentation
asUFInstance()
UFInstance carl::UTerm::asUFInstance () const inline
Returns
The stored term as UFInstance.
Definition at line 69 of file UTerm.h.
Referenced by carl::UEquality::collectUVariables(), and carl::model::evaluate().
asUVariable()
UVariable carl::UTerm::asUVariable () const inline
Returns
The stored term as UVariable.
Definition at line 62 of file UTerm.h.
Referenced by carl::UEquality::collectUVariables(), and carl::model::evaluate().
asVariant()
const auto& carl::UTerm::asVariant () const inline
Definition at line 41 of file UTerm.h.
Referenced by std::hash< carl::UTerm >::operator()(), carl::operator<(), carl::operator<<(), carl::operator==(), and carl::SMTLIBStream::write().
complexity()
std::size_t carl::UTerm::complexity () const
Definition at line 23 of file UTerm.cpp.
Referenced by asUFInstance(), and carl::UEquality::complexity().
domain()
Sort carl::UTerm::domain () const
Returns
The domain of this uninterpreted term.
Definition at line 16 of file UTerm.cpp.
Referenced by asUFInstance(), and carl::UEquality::UEquality().
gatherUFs()
void carl::UTerm::gatherUFs (std::set< UninterpretedFunction > & ufs) const
Definition at line 37 of file UTerm.cpp.
Referenced by asUFInstance(), and carl::UEquality::gatherUFs().
gatherVariables()
void carl::UTerm::gatherVariables (carlVariables & vars) const
Definition at line 30 of file UTerm.cpp.
Referenced by asUFInstance(), and carl::UEquality::gatherVariables().
isUFInstance()
bool carl::UTerm::isUFInstance () const inline
Returns
true, if the stored term is a UFInstance.
Definition at line 55 of file UTerm.h.
Referenced by asUFInstance(), and carl::model::evaluate().
isUVariable()
bool carl::UTerm::isUVariable () const inline
Returns
true, if the stored term is a UVariable.
Definition at line 48 of file UTerm.h.
Referenced by asUVariable(), carl::UEquality::collectUVariables(), and carl::model::evaluate().
Field Documentation
mTerm
Super carl::UTerm::mTerm private
Definition at line 24 of file UTerm.h.
Referenced by asUFInstance(), asUVariable(), asVariant(), complexity(), domain(), gatherUFs(), gatherVariables(), isUFInstance(), and isUVariable().
The documentation for this class was generated from the following files:
carl/formula/uninterpreted/UTerm.h
carl/formula/uninterpreted/UTerm.cpp