carl: carl::Constraint< Pol > Class Template Reference
carl::Constraint< Pol > Class Template Reference
Represent a polynomial (in)equality against zero.
#include <Constraint.h>
Public Member Functions
Constraint (bool _valid=true)
Constraint (carl::Variable::Arg _var, Relation _rel, const typename Pol::NumberType &_bound=constant_zero< typename Pol::NumberType >::get())
Constraint (const Pol &_lhs, Relation _rel)
template<typename P = Pol, EnableIf< needs_cache< P >> = dummy>
Constraint (const typename P::PolyType &_lhs, Relation _rel)
Constraint (const Constraint &_constraint)
Constraint (Constraint &&_constraint) noexcept
~Constraint ()
Constraint & operator= (const Constraint &_constraint)
Constraint & operator= (Constraint &&_constraint) noexcept
const Pol & lhs () const
const Variables & variables () const
Relation relation () const
size_t id () const
size_t getHash () const
bool hasFactorization () const
const Factors< Pol > & factorization () const
Pol::NumberType constantPart () const
uint maxDegree (const Variable &_variable) const
uint maxDegree () const
uint minDegree (const Variable &_variable) const
uint occurences (const Variable &_variable) const
const VarInfo< Pol > & varInfo (const Variable &_variable, bool _withCoefficients=false) const
bool relationIsStrict () const
bool relationIsWeak () const
bool hasVariable (const Variable &_var) const
Checks if the given variable occurs in the constraint.
bool integerValued () const
bool realValued () const
bool hasIntegerValuedVariable () const
Checks if this constraints contains an integer valued variable.
bool hasRealValuedVariable () const
Checks if this constraints contains an real valued variable.
bool isBound (bool negated=false) const
bool isLowerBound () const
bool isUpperBound () const
size_t complexity () const
unsigned satisfiedBy (const EvaluationMap< typename Pol::NumberType > &_assignment) const
Checks whether the given assignment satisfies this constraint.
unsigned isConsistent () const
Checks, whether the constraint is consistent.
unsigned consistentWith (const EvaluationMap< Interval< double >> &_solutionInterval) const
Checks whether this constraint is consistent with the given assignment from the its variables to interval domains.
unsigned consistentWith (const EvaluationMap< Interval< double >> &_solutionInterval, Relation &_stricterRelation) const
Checks whether this constraint is consistent with the given assignment from the its variables to interval domains.
unsigned evaluate (const EvaluationMap< Interval< typename carl::UnderlyingNumberType< Pol >::type >> &_assignment) const
Checks whether the given interval assignment may fulfill the constraint.
bool hasFinitelyManySolutionsIn (const Variable &_var) const
Pol coefficient (const Variable &_var, uint _degree) const
Calculates the coefficient of the given variable with the given degree.
Constraint negation () const
bool getSubstitution (Variable &_substitutionVariable, Pol &_substitutionTerm, bool _negated=false, const Variable &_exclude=carl::Variable::NO_VARIABLE) const
If this constraint represents a substitution (equation, where at least one variable occurs only linearly), this method detects a (there could be various possibilities) corresponding substitution variable and term.
bool getAssignment (Variable &_substitutionVariable, typename Pol::NumberType &_substitutionValue) const
std::string toString (unsigned _unequalSwitch=0, bool _infix=true, bool _friendlyVarNames=true) const
Gives the string representation of this constraint.
bool isPseudoBoolean () const
Determines whether the constraint is pseudo-boolean.
void printProperties (std::ostream &_out=std::cout) const
Prints the properties of this constraints on the given stream.
Private Member Functions
Constraint (const ConstraintContent< Pol > *_content)
Private Attributes
const ConstraintContent< Pol > * mpContent
The real (in)equality is stored here.
Friends
class ConstraintPool< Pol >
template<typename P >
bool operator== (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename P >
bool operator!= (const Constraint< P > &lhs, const Constraint< P > &rhs)
Detailed Description
template<typename Pol>
class carl::Constraint< Pol >
Represent a polynomial (in)equality against zero.
Such an (in)equality can be seen as an atomic formula/atom for the theory of real arithmetic. Actually, this is just a (possibly) thread-safe wrapper with convenient functions around the "ConstraintContent" class.
Definition at line 35 of file Constraint.h.
Constructor & Destructor Documentation
Constraint() [1/7]
template<typename Pol> carl::Constraint< Pol >::Constraint (const ConstraintContent< Pol > * _content) explicit private
Referenced by carl::Constraint< Poly >::negation().
Constraint() [2/7]
template<typename Pol> carl::Constraint< Pol >::Constraint (bool _valid = true) explicit
Constraint() [3/7]
template<typename Pol> carl::Constraint< Pol >::Constraint (carl::Variable::Arg _var, Relation _rel, const typename Pol::NumberType & _bound = constant_zero< typename Pol::NumberType >::get()) explicit
Constraint() [4/7]
template<typename Pol> carl::Constraint< Pol >::Constraint (const Pol & _lhs, Relation _rel) explicit
Constraint() [5/7]
template<typename Pol> template<typename P = Pol, EnableIf< needs_cache< P >> = dummy> carl::Constraint< Pol >::Constraint (const typename P::PolyType & _lhs, Relation _rel) explicit
Constraint() [6/7]
template<typename Pol> carl::Constraint< Pol >::Constraint (const Constraint< Pol > & _constraint)
Constraint() [7/7]
template<typename Pol> carl::Constraint< Pol >::Constraint (Constraint< Pol > && _constraint) noexcept
~Constraint()
template<typename Pol> carl::Constraint< Pol >::~Constraint ()
Member Function Documentation
coefficient()
template<typename Pol> Pol carl::Constraint< Pol >::coefficient (const Variable & _var, uint _degree) const
Calculates the coefficient of the given variable with the given degree.
Note, that it only computes the coefficient once and stores the result.
Parameters
_var The variable for which to calculate the coefficient.
_degree The according degree of the variable for which to calculate the coefficient.
Returns
The ith coefficient of the given variable, where i is the given degree.
complexity()
template<typename Pol> size_t carl::Constraint< Pol >::complexity () const inline
Returns
An approximation of the complexity of this constraint.
Definition at line 646 of file Constraint.h.
consistentWith() [1/2]
template<typename Pol> unsigned carl::Constraint< Pol >::consistentWith (const EvaluationMap< Interval< double >> & _solutionInterval) const
Checks whether this constraint is consistent with the given assignment from the its variables to interval domains.
Parameters
_solutionInterval The interval domains of the variables.
Returns
1, if this constraint is consistent with the given intervals; 0, if this constraint is not consistent with the given intervals; 2, if it cannot be decided whether this constraint is consistent with the given intervals.
consistentWith() [2/2]
template<typename Pol> unsigned carl::Constraint< Pol >::consistentWith (const EvaluationMap< Interval< double >> & _solutionInterval, Relation & _stricterRelation) const
Checks whether this constraint is consistent with the given assignment from the its variables to interval domains.
Parameters
_solutionInterval The interval domains of the variables.
_stricterRelation This relation is set to a relation R such that this constraint and the given variable bounds imply the constraint formed by R, comparing this constraint's left-hand side to zero.
Returns
1, if this constraint is consistent with the given intervals; 0, if this constraint is not consistent with the given intervals; 2, if it cannot be decided whether this constraint is consistent with the given intervals.
constantPart()
template<typename Pol> Pol::NumberType carl::Constraint< Pol >::constantPart () const inline
Returns
The constant part of the polynomial compared by this constraint.
Definition at line 457 of file Constraint.h.
evaluate()
template<typename Pol> unsigned carl::Constraint< Pol >::evaluate (const EvaluationMap< Interval< typename carl::UnderlyingNumberType< Pol >::type >> & _assignment) const
Checks whether the given interval assignment may fulfill the constraint.
Note that the assignment must be complete. There are three possible outcomes:
True (4), i.e. all actual assignments satisfy the constraint: $p ~_ 0 True$
Maybe (3), i.e. some actual assignments satisfy the constraint: $p ~_ 0 ?$
Not null (2), i.e. all assignments that make the constraint evaluate not to zero satisfy the constraint: $p ~_ 0 p 0$
Null (1), i.e. only assignments that make the constraint evaluate to zero satisfy the constraint: $p ~_ 0 p_ = 0$
False (0), i.e. no actual assignment satisfies the constraint: $p ~_ 0 False$
Parameters
_assignment Variable assignment.
Returns
0, 1 or 2.
factorization()
template<typename Pol> const Factors<Pol>& carl::Constraint< Pol >::factorization () const inline
Returns
The factorization of the polynomial compared by this constraint.
Definition at line 445 of file Constraint.h.
getAssignment()
template<typename Pol> bool carl::Constraint< Pol >::getAssignment (Variable & _substitutionVariable, typename Pol::NumberType & _substitutionValue) const
getHash()
template<typename Pol> size_t carl::Constraint< Pol >::getHash () const inline
Returns
A hash value for this constraint.
Definition at line 424 of file Constraint.h.
Referenced by std::hash< carl::Constraint< Pol > >::operator()().
getSubstitution()
template<typename Pol> bool carl::Constraint< Pol >::getSubstitution (Variable & _substitutionVariable, Pol & _substitutionTerm, bool _negated = false, const Variable & _exclude = carl::Variable::NO_VARIABLE) const
If this constraint represents a substitution (equation, where at least one variable occurs only linearly), this method detects a (there could be various possibilities) corresponding substitution variable and term.
Parameters
_substitutionVariable Is set to the substitution variable, if this constraint represents a substitution.
_substitutionTerm Is set to the substitution term, if this constraint represents a substitution.
Returns
true, if this constraints represents a substitution; false, otherwise.
hasFactorization()
template<typename Pol> bool carl::Constraint< Pol >::hasFactorization () const inline
Returns
true, if the polynomial p compared by this constraint has a proper factorization (!=p); false, otherwise.
Definition at line 433 of file Constraint.h.
hasFinitelyManySolutionsIn()
template<typename Pol> bool carl::Constraint< Pol >::hasFinitelyManySolutionsIn (const Variable & _var) const
Parameters
_var The variable to check the size of its solution set for.
Returns
true, if it is easy to decide whether this constraint has a finite solution set in the given variable; false, otherwise.
hasIntegerValuedVariable()
template<typename Pol> bool carl::Constraint< Pol >::hasIntegerValuedVariable () const inline
Checks if this constraints contains an integer valued variable.
Returns
true, if it does; false, otherwise.
Definition at line 575 of file Constraint.h.
hasRealValuedVariable()
template<typename Pol> bool carl::Constraint< Pol >::hasRealValuedVariable () const inline
Checks if this constraints contains an real valued variable.
Returns
true, if it does; false, otherwise.
Definition at line 585 of file Constraint.h.
hasVariable()
template<typename Pol> bool carl::Constraint< Pol >::hasVariable (const Variable & _var) const inline
Checks if the given variable occurs in the constraint.
Parameters
_var The variable to check for.
Returns
true, if the given variable occurs in the constraint; false, otherwise.
Definition at line 539 of file Constraint.h.
id()
template<typename Pol> size_t carl::Constraint< Pol >::id () const inline
Returns
The unique id of this constraint.
Definition at line 416 of file Constraint.h.
Referenced by carl::operator<(), and carl::operator<=().
integerValued()
template<typename Pol> bool carl::Constraint< Pol >::integerValued () const inline
Returns
true, if it contains only integer valued variables.
Definition at line 547 of file Constraint.h.
isBound()
template<typename Pol> bool carl::Constraint< Pol >::isBound (bool negated = false) const inline
Returns
true, if this constraint is a bound.
Definition at line 593 of file Constraint.h.
Referenced by carl::Constraint< Poly >::isLowerBound(), and carl::Constraint< Poly >::isUpperBound().
isConsistent()
template<typename Pol> unsigned carl::Constraint< Pol >::isConsistent () const inline
Checks, whether the constraint is consistent.
It differs between, containing variables, consistent, and inconsistent.
Returns
0, if the constraint is not consistent. 1, if the constraint is consistent. 2, if the constraint still contains variables.
Definition at line 668 of file Constraint.h.
isLowerBound()
template<typename Pol> bool carl::Constraint< Pol >::isLowerBound () const inline
Returns
true, if this constraint is a lower bound.
Definition at line 606 of file Constraint.h.
isPseudoBoolean()
template<typename Pol> bool carl::Constraint< Pol >::isPseudoBoolean () const
Determines whether the constraint is pseudo-boolean.
Returns
True if this constraint is pseudo-boolean. False otherwise.
isUpperBound()
template<typename Pol> bool carl::Constraint< Pol >::isUpperBound () const inline
Returns
true, if this constraint is an upper bound.
Definition at line 626 of file Constraint.h.
lhs()
template<typename Pol> const Pol& carl::Constraint< Pol >::lhs () const inline
Returns
The considered polynomial being the left-hand side of this constraint. Hence, the right-hand side of any constraint is always 0.
Definition at line 392 of file Constraint.h.
Referenced by carl::formula::symmetry::GraphBuilder< Poly >::addConstraint(), carl::model::evaluate(), carl::Constraint< Poly >::negation(), carl::model::substituteIn(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
maxDegree() [1/2]
template<typename Pol> uint carl::Constraint< Pol >::maxDegree (const Variable & _variable) const inline
Parameters
_variable The variable for which to determine the maximal degree.
Returns
The maximal degree of the given variable in this constraint. (Monomial-wise)
Definition at line 466 of file Constraint.h.
maxDegree() [2/2]
template<typename Pol> uint carl::Constraint< Pol >::maxDegree () const inline
Returns
The maximal degree of all variables in this constraint. (Monomial-wise)
Definition at line 475 of file Constraint.h.
Referenced by carl::Constraint< Poly >::isBound().
minDegree()
template<typename Pol> uint carl::Constraint< Pol >::minDegree (const Variable & _variable) const inline
Parameters
_variable The variable for which to determine the minimal degree.
Returns
The minimal degree of the given variable in this constraint. (Monomial-wise)
Definition at line 485 of file Constraint.h.
negation()
template<typename Pol> Constraint carl::Constraint< Pol >::negation () const inline
Definition at line 726 of file Constraint.h.
Referenced by carl::FormulaPool< Pol >::isBaseFormula().
occurences()
template<typename Pol> uint carl::Constraint< Pol >::occurences (const Variable & _variable) const inline
Parameters
_variable The variable for which to determine the number of occurrences.
Returns
The number of occurrences of the given variable in this constraint. (In how many monomials of the left-hand side does the given variable occur?)
Definition at line 498 of file Constraint.h.
operator=() [1/2]
template<typename Pol> Constraint& carl::Constraint< Pol >::operator= (const Constraint< Pol > & _constraint)
operator=() [2/2]
template<typename Pol> Constraint& carl::Constraint< Pol >::operator= (Constraint< Pol > && _constraint) noexcept
printProperties()
template<typename Pol> void carl::Constraint< Pol >::printProperties (std::ostream & _out = std::cout) const
Prints the properties of this constraints on the given stream.
Parameters
_out The stream to print on.
realValued()
template<typename Pol> bool carl::Constraint< Pol >::realValued () const inline
Returns
true, if it contains only real valued variables.
Definition at line 560 of file Constraint.h.
relation()
template<typename Pol> Relation carl::Constraint< Pol >::relation () const inline
Returns
The relation symbol of this constraint.
Definition at line 408 of file Constraint.h.
Referenced by carl::formula::symmetry::GraphBuilder< Poly >::addConstraint(), carl::model::evaluate(), carl::Constraint< Poly >::negation(), carl::model::substituteIn(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
relationIsStrict()
template<typename Pol> bool carl::Constraint< Pol >::relationIsStrict () const inline
Definition at line 526 of file Constraint.h.
relationIsWeak()
template<typename Pol> bool carl::Constraint< Pol >::relationIsWeak () const inline
Definition at line 529 of file Constraint.h.
satisfiedBy()
template<typename Pol> unsigned carl::Constraint< Pol >::satisfiedBy (const EvaluationMap< typename Pol::NumberType > & _assignment) const
Checks whether the given assignment satisfies this constraint.
Parameters
_assignment The assignment.
Returns
1, if the given assignment satisfies this constraint. 0, if the given assignment contradicts this constraint. 2, otherwise (possibly not defined for all variables in the constraint, even then it could be possible to obtain the first two results.)
toString()
template<typename Pol> std::string carl::Constraint< Pol >::toString (unsigned _unequalSwitch = 0, bool _infix = true, bool _friendlyVarNames = true) const inline
Gives the string representation of this constraint.
Parameters
_unequalSwitch A switch to indicate which kind of unequal should be used. For p != 0 with infix: 0: "p != 0", 1: "p <> 0", 2: "p /= 0" with prefix: 0: "(!= p 0)", 1: (or (< p 0) (> p 0)), 2: (not (= p 0))
_infix An infix string which is printed right before the constraint.
_friendlyVarNames A flag that indicates whether to print the variables with their internal representation (false) or with their dedicated names.
Returns
The string representation of this constraint.
Definition at line 753 of file Constraint.h.
variables()
template<typename Pol> const Variables& carl::Constraint< Pol >::variables () const inline
Returns
A container containing all variables occurring in the polynomial of this constraint.
Definition at line 400 of file Constraint.h.
varInfo()
template<typename Pol> const VarInfo<Pol>& carl::Constraint< Pol >::varInfo (const Variable & _variable, bool _withCoefficients = false) const inline
Parameters
_variable The variable to find variable information for.
_withCoefficients
Returns
The whole variable information object. Note, that if the given variable is not in this constraints, this method fails. Furthermore, the variable information returned do provide coefficients only, if the given flag _withCoefficients is set to true.
Definition at line 514 of file Constraint.h.
Referenced by carl::Constraint< Poly >::minDegree(), carl::Constraint< Poly >::occurences(), and carl::Constraint< Poly >::varInfo().
Friends And Related Function Documentation
ConstraintPool< Pol >
template<typename Pol> friend class ConstraintPool< Pol > friend
Definition at line 344 of file Constraint.h.
operator!=
template<typename Pol> template<typename P > bool operator!= (const Constraint< P > & lhs, const Constraint< P > & rhs) friend
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs != rhs
Definition at line 792 of file Constraint.h.
operator==
template<typename Pol> template<typename P > bool operator== (const Constraint< P > & lhs, const Constraint< P > & rhs) friend
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs == rhs
Definition at line 782 of file Constraint.h.
Field Documentation
mpContent
template<typename Pol> const ConstraintContent<Pol>* carl::Constraint< Pol >::mpContent private
The real (in)equality is stored here.
Definition at line 351 of file Constraint.h.
Referenced by carl::Constraint< Poly >::complexity(), carl::Constraint< Poly >::constantPart(), carl::Constraint< Poly >::factorization(), carl::Constraint< Poly >::getHash(), carl::Constraint< Poly >::hasFactorization(), carl::Constraint< Poly >::hasIntegerValuedVariable(), carl::Constraint< Poly >::hasRealValuedVariable(), carl::Constraint< Poly >::hasVariable(), carl::Constraint< Poly >::id(), carl::Constraint< Poly >::integerValued(), carl::Constraint< Poly >::isBound(), carl::Constraint< Poly >::isConsistent(), carl::Constraint< Poly >::isLowerBound(), carl::Constraint< Poly >::isUpperBound(), carl::Constraint< Poly >::lhs(), carl::Constraint< Poly >::maxDegree(), carl::Constraint< Poly >::minDegree(), carl::Constraint< Poly >::occurences(), carl::Constraint< Poly >::realValued(), carl::Constraint< Poly >::relation(), carl::Constraint< Poly >::relationIsStrict(), carl::Constraint< Poly >::relationIsWeak(), carl::Constraint< Poly >::toString(), carl::Constraint< Poly >::variables(), and carl::Constraint< Poly >::varInfo().
The documentation for this class was generated from the following file:
carl/formula/Constraint.h