carl: carl::LazardEvaluation< Rational, Poly > Class Template Reference
carl::LazardEvaluation< Rational, Poly > Class Template Reference
#include <LazardEvaluation.h>
Public Member Functions
LazardEvaluation (const Poly &p)
void substitute (Variable v, const RealAlgebraicNumber< Rational > &r)
const auto & getLiftingPoly () const
Private Member Functions
auto buildPolyRing (Variable v, const RealAlgebraicNumber< Rational > &r)
bool evaluatesToZero (const CoCoA::RingElem &p, const detail_lazard::CoCoAConverter::ConversionInfo &ci) const
void extendRing (const CoCoA::ring &ring, const CoCoA::RingElem &p)
std::pair< bool, Poly > getSubstitution (Variable v, const RealAlgebraicNumber< Rational > &r)
Analyzes whether we have to construct a field extension.
Private Attributes
CoCoA::ring mQ = CoCoA::RingQQ()
Model< Rational, Poly > mModel
detail_lazard::CoCoAConverter cc
std::map< Variable, CoCoA::RingElem > mSymbolsThere
std::map< std::pair< long, std::size_t >, Variable > mSymbolsBack
Poly mLiftingPoly
Detailed Description
template<typename Rational, typename Poly>
class carl::LazardEvaluation< Rational, Poly >
Definition at line 72 of file LazardEvaluation.h.
Constructor & Destructor Documentation
LazardEvaluation()
template<typename Rational , typename Poly > carl::LazardEvaluation< Rational, Poly >::LazardEvaluation (const Poly & p) inline
Definition at line 140 of file LazardEvaluation.h.
Member Function Documentation
buildPolyRing()
template<typename Rational , typename Poly > auto carl::LazardEvaluation< Rational, Poly >::buildPolyRing (Variable v, const RealAlgebraicNumber< Rational > & r) inline private
Definition at line 83 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getSubstitution().
evaluatesToZero()
template<typename Rational , typename Poly > bool carl::LazardEvaluation< Rational, Poly >::evaluatesToZero (const CoCoA::RingElem & p, const detail_lazard::CoCoAConverter::ConversionInfo & ci) const inline private
Definition at line 92 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getSubstitution().
extendRing()
template<typename Rational , typename Poly > void carl::LazardEvaluation< Rational, Poly >::extendRing (const CoCoA::ring & ring, const CoCoA::RingElem & p) inline private
Definition at line 101 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getSubstitution().
getLiftingPoly()
template<typename Rational , typename Poly > const auto& carl::LazardEvaluation< Rational, Poly >::getLiftingPoly () const inline
Definition at line 167 of file LazardEvaluation.h.
getSubstitution()
template<typename Rational , typename Poly > std::pair<bool,Poly> carl::LazardEvaluation< Rational, Poly >::getSubstitution (Variable v, const RealAlgebraicNumber< Rational > & r) inline private
Analyzes whether we have to construct a field extension.
We may have one of two cases:
We can eliminate v by substitution with some term
We create a new field extension and may have to reduce the lifting polynomial
In the first case, we return true and the term to substitute with. In the second case, we return false and the reduction polynomial.
Definition at line 114 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::substitute().
substitute()
template<typename Rational , typename Poly > void carl::LazardEvaluation< Rational, Poly >::substitute (Variable v, const RealAlgebraicNumber< Rational > & r) inline
Definition at line 142 of file LazardEvaluation.h.
Field Documentation
cc
template<typename Rational , typename Poly > detail_lazard::CoCoAConverter carl::LazardEvaluation< Rational, Poly >::cc private
Definition at line 77 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::evaluatesToZero(), and carl::LazardEvaluation< Rational, Poly >::getSubstitution().
mLiftingPoly
template<typename Rational , typename Poly > Poly carl::LazardEvaluation< Rational, Poly >::mLiftingPoly private
Definition at line 81 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getLiftingPoly(), and carl::LazardEvaluation< Rational, Poly >::substitute().
mModel
template<typename Rational , typename Poly > Model<Rational, Poly> carl::LazardEvaluation< Rational, Poly >::mModel private
Definition at line 75 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::evaluatesToZero(), and carl::LazardEvaluation< Rational, Poly >::substitute().
mQ
template<typename Rational , typename Poly > CoCoA::ring carl::LazardEvaluation< Rational, Poly >::mQ = CoCoA::RingQQ() private
Definition at line 74 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::buildPolyRing(), and carl::LazardEvaluation< Rational, Poly >::extendRing().
mSymbolsBack
template<typename Rational , typename Poly > std::map<std::pair<long,std::size_t>, Variable> carl::LazardEvaluation< Rational, Poly >::mSymbolsBack private
Definition at line 79 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::buildPolyRing().
mSymbolsThere
template<typename Rational , typename Poly > std::map<Variable, CoCoA::RingElem> carl::LazardEvaluation< Rational, Poly >::mSymbolsThere private
Definition at line 78 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::buildPolyRing().
The documentation for this class was generated from the following file:
carl/core/polynomialfunctions/LazardEvaluation.h