carl: Multivariate Represented Polynomials
Multivariate Represented Polynomials
Polynomials
Files
file EZGCD.h
file Monomial.h
file MonomialOrdering.h
file MultivariateGCD.h
file MultivariatePolynomial.h
file MultivariatePolynomialPolicy.h
file VariableInformation.h
Data Structures
class carl::EZGCD< Coeff, Ordering, Policies >
Extended Zassenhaus algorithm for multivariate GCD calculation.
class carl::Monomial
The general-purpose monomials.
struct carl::MonomialComparator< f, degreeOrdered >
A class for term orderings.
class carl::MultivariateGCD< GCDCalculation, Coeff, Ordering, Policies >
A general object for gcd calculation of multivariate gcds.
class carl::MultivariatePolynomial< Coeff, Ordering, Policies >
The general-purpose multivariate polynomial class.
struct carl::StdMultivariatePolynomialPolicies< ReasonsAdaptor, Allocator >
The default policy for polynomials.
class carl::Term< Coefficient >
Represents a single term, that is a numeric coefficient and a monomial.
Functions
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > carl::gcd (const MultivariatePolynomial< C, O, P > &a, const MultivariatePolynomial< C, O, P > &b)
Detailed Description
Function Documentation
gcd()
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::gcd (const MultivariatePolynomial< C, O, P > & a, const MultivariatePolynomial< C, O, P > & b)
Parameters
a A multivariately represented polynomial.
b A multivariately represented polynomial.
Returns
The greatest common divisor of a and b.
See also
MultivariatePolynomial
MultivariateGCD
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::gcd(), carl::gcd_assign(), carl::lazyDiv(), and carl::RealAlgebraicNumber< carl::Number >::simplifyByPolynomial().