carl: carl::detail_sign_variations Namespace Reference
carl::detail_sign_variations Namespace Reference
Functions
template<typename Coefficient >
UnivariatePolynomial< Coefficient > reverse (UnivariatePolynomial< Coefficient > &&p)
Reverses the order of the coefficients of this polynomial.
template<typename Coefficient >
UnivariatePolynomial< Coefficient > scale (UnivariatePolynomial< Coefficient > &&p, const Coefficient &factor)
Scale the variable, i.e.
template<typename Coefficient >
UnivariatePolynomial< Coefficient > shift (const UnivariatePolynomial< Coefficient > &p, const Coefficient &a)
Shift the variable by a, i.e.
Function Documentation
reverse()
template<typename Coefficient > UnivariatePolynomial<Coefficient> carl::detail_sign_variations::reverse (UnivariatePolynomial< Coefficient > && p)
Reverses the order of the coefficients of this polynomial.
This method is meant to be called by signVariations only.
Runtime complexity:
O(n)
Definition at line 17 of file SignVariations.h.
Referenced by carl::realRootsThom(), carl::ThomEncoding< carl::Number >::relevantDerivatives(), carl::UnivariatePolynomial< Coeff >::reverseCoefficients(), and carl::sign_variations().
scale()
template<typename Coefficient > UnivariatePolynomial<Coefficient> carl::detail_sign_variations::scale (UnivariatePolynomial< Coefficient > && p, const Coefficient & factor)
Scale the variable, i.e.
apply This method is meant to be called by signVariations only.
Parameters
factor Factor to scale x.
Runtime complexity:
O(n)
Definition at line 30 of file SignVariations.h.
Referenced by carl::sign_variations().
shift()
template<typename Coefficient > UnivariatePolynomial<Coefficient> carl::detail_sign_variations::shift (const UnivariatePolynomial< Coefficient > & p, const Coefficient & a)
Shift the variable by a, i.e.
apply This method is meant to be called by signVariations only.
Parameters
a Offset to shift x.
Runtime complexity:
O(n^2)
Definition at line 47 of file SignVariations.h.
Referenced by carl::sign_variations().