carl: carl::cocoawrapper Namespace Reference
carl::cocoawrapper Namespace Reference
This namespace contains wrapper for all heavy CoCoALib methods.
Functions
CoCoA::RingElem gcd (const CoCoA::RingElem &p, const CoCoA::RingElem &q)
Calls CoCoA::gcd(p,q).
CoCoA::factorization< CoCoA::RingElem > factor (const CoCoA::RingElem &p)
Calls CoCoA::factor(p).
std::vector< CoCoA::RingElem > ReducedGBasis (const std::vector< CoCoA::RingElem > &p)
Calls CoCoA::ReducedGBasis(CoCoA::ideal(p)).
CoCoA::factorization< CoCoA::RingElem > SqFreeFactor (const CoCoA::RingElem &p)
Calls CoCoA::SqFreeFactor(p).
Detailed Description
This namespace contains wrapper for all heavy CoCoALib methods.
They are implemented in a separate source file, attempting to reduce the amount of code included from CoCoALib.
Function Documentation
factor()
CoCoA::factorization< CoCoA::RingElem > carl::cocoawrapper::factor (const CoCoA::RingElem & p)
Calls CoCoA::factor(p).
Definition at line 13 of file CoCoAAdaptor.cpp.
Referenced by carl::OldGinacConverter< Poly >::convertToGinac(), carl::IntervalEvaluation::evaluate(), carl::CoCoAAdaptor< Poly >::factorize(), carl::LazardEvaluation< Rational, Poly >::getSubstitution(), carl::CoCoAAdaptor< Poly >::irreducibleFactorsOf(), carl::helper::sanitizeFactors(), SqFreeFactor(), carl::sqrt_safe(), and carl::Number< cln::cl_RA >::sqrt_safe().
gcd()
CoCoA::RingElem carl::cocoawrapper::gcd (const CoCoA::RingElem & p, const CoCoA::RingElem & q)
Calls CoCoA::gcd(p,q).
Definition at line 10 of file CoCoAAdaptor.cpp.
Referenced by carl::Number< cln::cl_I >::gcd(), carl::CoCoAAdaptor< Poly >::gcd(), carl::Number< cln::cl_RA >::gcd(), carl::CoCoAAdaptor< Poly >::makeCoprimeWith(), and carl::OldGinacConverter< Poly >::similar().
ReducedGBasis()
std::vector< CoCoA::RingElem > carl::cocoawrapper::ReducedGBasis (const std::vector< CoCoA::RingElem > & p)
Calls CoCoA::ReducedGBasis(CoCoA::ideal(p)).
Definition at line 16 of file CoCoAAdaptor.cpp.
Referenced by carl::CoCoAAdaptor< Poly >::GBasis().
SqFreeFactor()
CoCoA::factorization< CoCoA::RingElem > carl::cocoawrapper::SqFreeFactor (const CoCoA::RingElem & p)
Calls CoCoA::SqFreeFactor(p).
Definition at line 19 of file CoCoAAdaptor.cpp.
Referenced by carl::CoCoAAdaptor< Poly >::squareFreePart().