carl: carl::timing Namespace Reference
carl::timing Namespace Reference
Typedefs
using clock = std::chrono::high_resolution_clock
The clock type used here.
using duration = std::chrono::duration< std::size_t, std::milli >
The duration type used here.
using time_point = clock::time_point
The type of a time point.
Functions
auto now ()
Return the current time point.
auto since (time_point start)
Return the duration since the given start time point.
auto zero ()
Return a zero duration.
Typedef Documentation
clock
using carl::timing::clock = typedef std::chrono::high_resolution_clock
The clock type used here.
Definition at line 14 of file TimingCollector.h.
duration
using carl::timing::duration = typedef std::chrono::duration<std::size_t,std::milli>
The duration type used here.
Definition at line 16 of file TimingCollector.h.
time_point
using carl::timing::time_point = typedef clock::time_point
The type of a time point.
Definition at line 18 of file TimingCollector.h.
Function Documentation
now()
auto carl::timing::now () inline
Return the current time point.
Definition at line 21 of file TimingCollector.h.
Referenced by main(), carl::Timer::passed(), carl::Timer::reset(), since(), and carl::TimingCollector::start().
since()
auto carl::timing::since (time_point start) inline
Return the duration since the given start time point.
Definition at line 25 of file TimingCollector.h.
Referenced by carl::TimingCollector::finish().
zero()
auto carl::timing::zero () inline
Return a zero duration.
Definition at line 29 of file TimingCollector.h.