carl: carl::parser Namespace Reference
carl::parser Namespace Reference
Data Structures
struct DecimalParser
Parses decimals, including floating point and scientific notation.
struct ErrorHandler
struct ExpressionParser
struct FormulaParser
struct IntegerParser
Parses (signed) integers.
struct isDivisible
struct isDivisible< false >
struct isDivisible< true >
class Parser
struct PolynomialParser
struct RationalFunctionParser
struct RationalParser
Parses rationals, being two decimals separated by a slash.
struct RationalPolicies
Specialization of qi::real_policies for our rational types.
Typedefs
using Skipper = qi::space_type
using Iterator = std::string::const_iterator
template<typename Pol >
using RatFun = RationalFunction< Pol >
template<typename Pol >
using ExpressionType = boost::variant< typename Pol::CoeffType, carl::Variable, carl::Monomial::Arg, carl::Term< typename Pol::CoeffType >, Pol, RationalFunction< Pol >, carl::Formula< Pol > >
Functions
template<typename Parser , typename T >
bool parse_impl (const std::string &input, T &output)
template<typename Parser , typename T , typename S >
bool parse_impl (const std::string &input, T &output, const S &skipper)
template<typename T >
bool parseInteger (const std::string &input, T &output)
template<typename T >
bool parseDecimal (const std::string &input, T &output)
template<typename T >
bool parseRational (const std::string &input, T &output)
Typedef Documentation
ExpressionType
template<typename Pol > using carl::parser::ExpressionType = typedef boost::variant< typename Pol::CoeffType, carl::Variable, carl::Monomial::Arg, carl::Term<typename Pol::CoeffType>, Pol, RationalFunction<Pol>, carl::Formula<Pol> >
Definition at line 27 of file ExpressionParserResult.h.
Iterator
using carl::parser::Iterator = typedef std::string::const_iterator
Definition at line 33 of file Common.h.
RatFun
template<typename Pol > using carl::parser::RatFun = typedef RationalFunction<Pol>
Definition at line 37 of file Common.h.
Skipper
typedef boost::spirit::qi::space_type carl::parser::Skipper
Definition at line 20 of file parser.h.
Function Documentation
parse_impl() [1/2]
template<typename Parser , typename T > bool carl::parser::parse_impl (const std::string & input, T & output)
Definition at line 125 of file parser.h.
parse_impl() [2/2]
template<typename Parser , typename T , typename S > bool carl::parser::parse_impl (const std::string & input, T & output, const S & skipper)
Definition at line 133 of file parser.h.
parseDecimal()
template<typename T > bool carl::parser::parseDecimal (const std::string & input, T & output)
Definition at line 146 of file parser.h.
Referenced by carl::parse< cln::cl_I >(), carl::parse< mpz_class >(), carl::try_parse< cln::cl_I >(), and carl::try_parse< mpz_class >().
parseInteger()
template<typename T > bool carl::parser::parseInteger (const std::string & input, T & output)
Definition at line 142 of file parser.h.
parseRational()
template<typename T > bool carl::parser::parseRational (const std::string & input, T & output)
Definition at line 150 of file parser.h.
Referenced by carl::parse< cln::cl_RA >(), carl::parse< mpq_class >(), carl::try_parse< cln::cl_RA >(), and carl::try_parse< mpq_class >().