carl: carl::RealAlgebraicNumberEvaluation Namespace Reference
carl::RealAlgebraicNumberEvaluation Namespace Reference
Typedefs
template<typename Number >
using RANMap = std::map< Variable, RealAlgebraicNumber< Number > >
Functions
template<typename Number , typename Coeff >
RealAlgebraicNumber< Number > evaluate (const MultivariatePolynomial< Coeff > &p, const RealAlgebraicPoint< Number > &point, const std::vector< Variable > &variables)
Evaluate the given polynomial 'p' at the given 'point' based on the variable order given by 'variables'.
template<typename Number >
RealAlgebraicNumber< Number > evaluate (const MultivariatePolynomial< Number > &p, const RANMap< Number > &m)
Evaluate the given polynomial 'p' at the point represented by the variable-to-nummber-mapping 'm'.
template<typename Number >
RealAlgebraicNumber< Number > evaluateIR (const MultivariatePolynomial< Number > &p, const RANMap< Number > &m)
Evaluate the given polynomial with the given values for the variables.
template<typename Number , typename Coeff >
UnivariatePolynomial< Number > evaluatePolynomial (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, RealAlgebraicNumber< Number >> &m, std::map< Variable, Interval< Number >> &varToInterval)
Compute a univariate polynomial with rational coefficients that has the roots of 'p' whose coefficient variables have been substituted by the roots given in m.
template<typename Number >
MultivariatePolynomial< Number > evaluatePolynomial (const MultivariatePolynomial< Number > &p, const std::map< Variable, RealAlgebraicNumber< Number >> &m)
template<typename Number , typename Coeff >
UnivariatePolynomial< Number > evaluateCoefficients (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, RealAlgebraicNumber< Number >> &m, std::map< Variable, Interval< Number >> &varToInterval)
Evaluate the coefficients of the given polynomial p w.r.t.
template<typename Number , typename Coeff >
UnivariatePolynomial< Number > evaluatePolynomial (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, RealAlgebraicNumber< Number >> &m)
Typedef Documentation
RANMap
template<typename Number > using carl::RealAlgebraicNumberEvaluation::RANMap = typedef std::map<Variable, RealAlgebraicNumber<Number> >
Definition at line 29 of file RealAlgebraicNumberEvaluation.h.
Function Documentation
evaluate() [1/2]
template<typename Number , typename Coeff > RealAlgebraicNumber< Number > carl::RealAlgebraicNumberEvaluation::evaluate (const MultivariatePolynomial< Coeff > & p, const RealAlgebraicPoint< Number > & point, const std::vector< Variable > & variables)
Evaluate the given polynomial 'p' at the given 'point' based on the variable order given by 'variables'.
If a variable is assigned a numeric representation, the corresponding value is directly plugged in. All assignments of interval representations are passed on to evaluate(MultivariatePolynomial, RANIRMap). Note that the number of variables must match the dimension of the 'point', all variables of 'p' must appear in 'variables' and that 'variables' must not mention any additional variables.
Definition at line 99 of file RealAlgebraicNumberEvaluation.h.
Referenced by carl::model::evaluate(), evaluateIR(), and carl::cad::Constraint< carl::Number >::satisfiedBy().
evaluate() [2/2]
template<typename Number > RealAlgebraicNumber< Number > carl::RealAlgebraicNumberEvaluation::evaluate (const MultivariatePolynomial< Number > & p, const RANMap< Number > & m)
Evaluate the given polynomial 'p' at the point represented by the variable-to-nummber-mapping 'm'.
If a variable is assigned a numeric representation, the corresponding value is directly plugged in. All assignments of interval representations are passed on to evaluate(MultivariatePolynomial, RANIRMap). Note that variables of 'p' must be assigned in 'm' and that 'm' must not assign any additional variables.
Definition at line 122 of file RealAlgebraicNumberEvaluation.h.
evaluateCoefficients()
template<typename Number , typename Coeff > UnivariatePolynomial< Number > carl::RealAlgebraicNumberEvaluation::evaluateCoefficients (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, RealAlgebraicNumber< Number >> & m, std::map< Variable, Interval< Number >> & varToInterval)
Evaluate the coefficients of the given polynomial p w.r.t.
the given evaluation map m. The algorithm assumes that all variables in m are coefficient variables.
The map varToInterval gives back an assignment of variables to the isolating intervals of the roots for each variable.
Parameters
p polynomial to be evaluated in the given variables. This should be a univariate polynomial in a variable not occurring in variables.
m map assigning each variable of p an interval-represented RealAlgebraicNumber
varToInterval
Returns
rational univariate polynomial having all real roots of the polynomial whose coefficients are evaluated according to m
See also
Constraint::satisfiedBy and CAD::samples for usages of this method
Definition at line 284 of file RealAlgebraicNumberEvaluation.h.
evaluateIR()
template<typename Number > RealAlgebraicNumber< Number > carl::RealAlgebraicNumberEvaluation::evaluateIR (const MultivariatePolynomial< Number > & p, const RANMap< Number > & m)
Evaluate the given polynomial with the given values for the variables.
Asserts that all variables of p have an assignment in m and that m has no additional assignments.
Parameters
p Polynomial to be evaluated
m Variable assignment
Returns
Evaluation result
Definition at line 160 of file RealAlgebraicNumberEvaluation.h.
Referenced by evaluate().
evaluatePolynomial() [1/3]
template<typename Number , typename Coeff > UnivariatePolynomial< Number > carl::RealAlgebraicNumberEvaluation::evaluatePolynomial (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, RealAlgebraicNumber< Number >> & m, std::map< Variable, Interval< Number >> & varToInterval)
Compute a univariate polynomial with rational coefficients that has the roots of 'p' whose coefficient variables have been substituted by the roots given in m.
The map varToInterval gives back an assignment of variables to the isolating intervals of the roots for each variable. Note that the resulting polynomial has the main variable of p in the end.
Parameters
p
m
varToInterval
Returns
a univariate polynomial with rational coefficients (and p's main variable) that has the roots of p whose coefficient variables have been substituted by the roots given in m
Definition at line 210 of file RealAlgebraicNumberEvaluation.h.
Referenced by evaluateCoefficients(), and evaluateIR().
evaluatePolynomial() [2/3]
template<typename Number > MultivariatePolynomial<Number> carl::RealAlgebraicNumberEvaluation::evaluatePolynomial (const MultivariatePolynomial< Number > & p, const std::map< Variable, RealAlgebraicNumber< Number >> & m)
evaluatePolynomial() [3/3]
template<typename Number , typename Coeff > UnivariatePolynomial<Number> carl::RealAlgebraicNumberEvaluation::evaluatePolynomial (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, RealAlgebraicNumber< Number >> & m)
Definition at line 249 of file RealAlgebraicNumberEvaluation.h.