carl: carl::rootfinder Namespace Reference
carl::rootfinder Namespace Reference
Namespaces
eigen
splitting_strategies
Data Structures
class AbstractRootFinder
Base class for a root finding algorithm for a single univariate polynomial.
class IncrementalRootFinder
This class implements an AbstractRootFinder that has an interface to calculate the real roots incrementally.
struct IntervalSizeComparator
class RootFinder
Interface of a RootFinder such that the Strategies can access the IncrementalRootFinder.
Enumerations
enum SplittingStrategy {
SplittingStrategy::GENERIC, SplittingStrategy::BINARYSAMPLE, SplittingStrategy::BINARYNEWTON, SplittingStrategy::GRID,
SplittingStrategy::EIGENVALUES, SplittingStrategy::ABERTH, SplittingStrategy::DEFAULT = EIGENVALUES
}
Enum of all strategies for splitting some interval.
Functions
std::ostream & operator<< (std::ostream &os, const SplittingStrategy &s)
Streaming operator for a splitting strategy.
template<typename Coeff , typename Number , typename Finder = IncrementalRootFinder<Number>, EnableIf< std::is_same< Coeff, Number >> = dummy>
std::vector< RealAlgebraicNumber< Number > > realRoots (const UnivariatePolynomial< Coeff > &polynomial, const Interval< Number > &interval=Interval< Number >::unboundedInterval(), SplittingStrategy pivoting=SplittingStrategy::DEFAULT)
Find all real roots of a univariate 'polynomial' with numeric coefficients within a given 'interval'.
template<typename Coeff , typename Number , DisableIf< std::is_same< Coeff, Number >> = dummy>
std::vector< RealAlgebraicNumber< Number > > realRoots (const UnivariatePolynomial< Coeff > &polynomial, const Interval< Number > &interval=Interval< Number >::unboundedInterval(), SplittingStrategy pivoting=SplittingStrategy::DEFAULT)
Find all real roots of a univariate 'polynomial' with non-numeric coefficients within a given 'interval'.
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type>
std::vector< RealAlgebraicNumber< Number > > realRoots (const UnivariatePolynomial< Coeff > &polynomial, SplittingStrategy pivoting=SplittingStrategy::DEFAULT, const Interval< Number > &interval=Interval< Number >::unboundedInterval())
Find all real roots of a univariate 'polynomial' with non-numeric coefficients within a given 'interval'.
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type>
boost::optional< std::vector< RealAlgebraicNumber< Number > > > realRoots (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, RealAlgebraicNumber< Number >> &m, const Interval< Number > &interval=Interval< Number >::unboundedInterval(), SplittingStrategy pivoting=SplittingStrategy::DEFAULT)
Replace all variables except one of the multivariate polynomial 'p' by numbers as given in the mapping 'm', which creates a univariate polynomial, and return all roots of that created polynomial.
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type>
boost::optional< std::vector< RealAlgebraicNumber< Number > > > realRoots (const UnivariatePolynomial< Coeff > &p, const std::list< Variable > &variables, const std::list< RealAlgebraicNumber< Number >> &values, const Interval< Number > &interval=Interval< Number >::unboundedInterval(), SplittingStrategy pivoting=SplittingStrategy::DEFAULT)
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type>
uint countRealRoots (const UnivariatePolynomial< Coeff > &polynomial, const Interval< Number > &interval=Interval< Number >::unboundedInterval(), SplittingStrategy pivoting=SplittingStrategy::DEFAULT)
Count only the number of real roots of the 'polynomial' within the given 'interval'.
Enumeration Type Documentation
SplittingStrategy
enum carl::rootfinder::SplittingStrategy strong
Enum of all strategies for splitting some interval.
Enumerator
GENERIC
Uses GenericStrategy.
BINARYSAMPLE
Uses BinarySampleStrategy.
BINARYNEWTON
Uses BinaryNewtonStrategy.
GRID
Uses GridStrategy.
EIGENVALUES
Uses EigenValueStrategy for first step, BinarySampleStrategy afterwards.
ABERTH
Uses AberthStrategy for first step, BinarySampleStrategy afterwards.
DEFAULT
Defaults to EIGENVALUES.
Definition at line 42 of file IncrementalRootFinder.h.
Function Documentation
countRealRoots()
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type> uint carl::rootfinder::countRealRoots (const UnivariatePolynomial< Coeff > & polynomial, const Interval< Number > & interval = Interval<Number>::unboundedInterval(), SplittingStrategy pivoting = SplittingStrategy::DEFAULT)
Count only the number of real roots of the 'polynomial' within the given 'interval'.
However, this function uses realRoots() to obtain the real roots. TODO What's the point of this function? We can use realRoots(..).size().
Definition at line 114 of file RootFinder.h.
operator<<()
std::ostream& carl::rootfinder::operator<< (std::ostream & os, const SplittingStrategy & s) inline
Streaming operator for a splitting strategy.
Parameters
os Output stream.
s Splitting strategy.
Returns
os.
Definition at line 65 of file IncrementalRootFinder.h.
realRoots() [1/5]
template<typename Coeff , typename Number , typename Finder = IncrementalRootFinder<Number>, EnableIf< std::is_same< Coeff, Number >> = dummy> std::vector<RealAlgebraicNumber<Number> > carl::rootfinder::realRoots (const UnivariatePolynomial< Coeff > & polynomial, const Interval< Number > & interval = Interval<Number>::unboundedInterval(), SplittingStrategy pivoting = SplittingStrategy::DEFAULT)
Find all real roots of a univariate 'polynomial' with numeric coefficients within a given 'interval'.
Definition at line 27 of file RootFinder.h.
Referenced by countRealRoots(), carl::MultivariateRoot< Poly >::evaluate(), realRoots(), carl::model::realRoots(), and carl::model::tryRealRoots().
realRoots() [2/5]
template<typename Coeff , typename Number , DisableIf< std::is_same< Coeff, Number >> = dummy> std::vector<RealAlgebraicNumber<Number> > carl::rootfinder::realRoots (const UnivariatePolynomial< Coeff > & polynomial, const Interval< Number > & interval = Interval<Number>::unboundedInterval(), SplittingStrategy pivoting = SplittingStrategy::DEFAULT)
Find all real roots of a univariate 'polynomial' with non-numeric coefficients within a given 'interval'.
However, all coefficients must be types that contain numeric numbers that are retrievable by using .constantPart();
Definition at line 43 of file RootFinder.h.
realRoots() [3/5]
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type> std::vector<RealAlgebraicNumber<Number> > carl::rootfinder::realRoots (const UnivariatePolynomial< Coeff > & polynomial, SplittingStrategy pivoting = SplittingStrategy::DEFAULT, const Interval< Number > & interval = Interval<Number>::unboundedInterval())
Find all real roots of a univariate 'polynomial' with non-numeric coefficients within a given 'interval'.
However, all coefficients must be types that contain numeric numbers that are retrievable by using .constantPart(); Note that this is a convenience method with swapped arguments to omit the interval but give a strategy.
Definition at line 59 of file RootFinder.h.
realRoots() [4/5]
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type> boost::optional<std::vector<RealAlgebraicNumber<Number> > > carl::rootfinder::realRoots (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, RealAlgebraicNumber< Number >> & m, const Interval< Number > & interval = Interval< Number >::unboundedInterval(), SplittingStrategy pivoting = SplittingStrategy::DEFAULT)
Replace all variables except one of the multivariate polynomial 'p' by numbers as given in the mapping 'm', which creates a univariate polynomial, and return all roots of that created polynomial.
Note that 'p' is represented as a univariate polynomial with polynomial coefficients. Its main variable is not replaced and stays the main variable of the created polynomial. However, all variables in the polynomial coefficients are replaced, which is why
the main variable of 'p' must not be in 'm'
all variables from the coefficients of 'p' must be in 'm'
Note that boost::none is returned if replacing variables in 'p' already yields the zero-polynomial and no valid root computation is possible. However, if it's a non-zero-polynomial that simply has no roots, an empty vector of roots is returned.
realRoots() [5/5]
template<typename Coeff , typename Number = typename UnderlyingNumberType<Coeff>::type> boost::optional<std::vector<RealAlgebraicNumber<Number> > > carl::rootfinder::realRoots (const UnivariatePolynomial< Coeff > & p, const std::list< Variable > & variables, const std::list< RealAlgebraicNumber< Number >> & values, const Interval< Number > & interval = Interval< Number >::unboundedInterval(), SplittingStrategy pivoting = SplittingStrategy::DEFAULT)