carl: carl::detail Namespace Reference
carl::detail Namespace Reference
Data Structures
struct is_from_variant
struct is_from_variant< allowConversion, T, First, Tail... >
struct is_from_variant_wrapper
struct is_from_variant_wrapper< allowConversion, T, Variant< Args... > >
struct SMTLIBOutputContainer
struct SMTLIBScriptContainer
struct tuple_accumulate_impl
Helper functor for carl::tuple_accumulate that actually does the work.
struct variant_extend_visitor
struct variant_hash
struct variant_is_type_visitor
Functions
template<typename Pol >
std::ostream & operator<< (std::ostream &os, const SMTLIBScriptContainer< Pol > &sc)
template<typename... Args>
std::ostream & operator<< (std::ostream &os, const SMTLIBOutputContainer< Args... > &soc)
uint next_prime (const uint &n, const PrimeFactory< uint > &pf)
mpz_class next_prime (const mpz_class &n, const PrimeFactory< mpz_class > &)
cln::cl_I next_prime (const cln::cl_I &n, const PrimeFactory< cln::cl_I > &)
template<typename Tuple1 , typename Tuple2 , std::size_t... I1, std::size_t... I2>
auto tuple_cat_impl (Tuple1 &&t1, Tuple2 &&t2, std::index_sequence< I1... >, std::index_sequence< I2... >)
Helper method for carl::tuple_apply that actually performs the call.
template<typename Tuple , std::size_t... I>
auto tuple_tail_impl (Tuple &&t, std::index_sequence< I... >)
Helper method for carl::tuple_tail that actually performs the call.
template<typename F , typename Tuple , std::size_t... I>
auto tuple_apply_impl (F &&f, Tuple &&t, std::index_sequence< I... >)
Helper method for carl::tuple_apply that actually performs the call.
template<typename F , typename Tuple , std::size_t... I>
auto tuple_foreach_impl (F &&f, Tuple &&t, std::index_sequence< I... >)
Helper method for carl::tuple_foreach that actually does the work.
template<typename It >
void advance_all (It &it)
template<typename It , typename... Its>
void advance_all (It &it, Its &... its)
template<typename Result , typename It , typename... Its>
void vector_zip_tuple (Result &res, It begin, It end, Its... its)
Function Documentation
advance_all() [1/2]
template<typename It > void carl::detail::advance_all (It & it)
Definition at line 35 of file vector_util.h.
Referenced by advance_all(), and vector_zip_tuple().
advance_all() [2/2]
template<typename It , typename... Its> void carl::detail::advance_all (It & it, Its &... its)
Definition at line 39 of file vector_util.h.
next_prime() [1/3]
uint carl::detail::next_prime (const uint & n, const PrimeFactory< uint > & pf) inline
Definition at line 50 of file PrimeFactory.h.
Referenced by carl::PrimeFactory< uint >::nextPrime().
next_prime() [2/3]
mpz_class carl::detail::next_prime (const mpz_class & n, const PrimeFactory< mpz_class > &) inline
Definition at line 60 of file PrimeFactory.h.
next_prime() [3/3]
cln::cl_I carl::detail::next_prime (const cln::cl_I & n, const PrimeFactory< cln::cl_I > &) inline
Definition at line 67 of file PrimeFactory.h.
operator<<() [1/2]
template<typename Pol > std::ostream& carl::detail::operator<< (std::ostream & os, const SMTLIBScriptContainer< Pol > & sc)
Definition at line 300 of file SMTLIBStream.h.
operator<<() [2/2]
template<typename... Args> std::ostream& carl::detail::operator<< (std::ostream & os, const SMTLIBOutputContainer< Args... > & soc)
Definition at line 324 of file SMTLIBStream.h.
tuple_apply_impl()
template<typename F , typename Tuple , std::size_t... I> auto carl::detail::tuple_apply_impl (F && f, Tuple && t, std::index_sequence< I... >)
Helper method for carl::tuple_apply that actually performs the call.
Definition at line 80 of file tuple_util.h.
Referenced by carl::tuple_apply().
tuple_cat_impl()
template<typename Tuple1 , typename Tuple2 , std::size_t... I1, std::size_t... I2> auto carl::detail::tuple_cat_impl (Tuple1 && t1, Tuple2 && t2, std::index_sequence< I1... > , std::index_sequence< I2... >)
Helper method for carl::tuple_apply that actually performs the call.
Definition at line 18 of file tuple_util.h.
Referenced by carl::tuple_cat().
tuple_foreach_impl()
template<typename F , typename Tuple , std::size_t... I> auto carl::detail::tuple_foreach_impl (F && f, Tuple && t, std::index_sequence< I... >)
Helper method for carl::tuple_foreach that actually does the work.
Definition at line 100 of file tuple_util.h.
Referenced by carl::tuple_foreach().
tuple_tail_impl()
template<typename Tuple , std::size_t... I> auto carl::detail::tuple_tail_impl (Tuple && t, std::index_sequence< I... >)
Helper method for carl::tuple_tail that actually performs the call.
Definition at line 37 of file tuple_util.h.
Referenced by carl::tuple_tail().
vector_zip_tuple()
template<typename Result , typename It , typename... Its> void carl::detail::vector_zip_tuple (Result & res, It begin, It end, Its... its)
Definition at line 44 of file vector_util.h.
Referenced by carl::vector_zip_tuple().