carl: carl Namespace Reference
carl Namespace Reference
carl is the main namespace for the library.
Namespaces
benchmarks
cad
Contains everything directly related to the implementation of the cylindrical algebraic decomposition.
cmakeoptions
cocoawrapper
This namespace contains wrapper for all heavy CoCoALib methods.
constraints
detail
detail_lazard
dtl
formula
function_selector
helper
io
logging
Contains a custom logging facility.
model
parser
ran
RealAlgebraicNumberEvaluation
RealAlgebraicNumberSettings
resultant_debug
rootfinder
tree_detail
Data Structures
class AbstractGBProcedure
struct all
Meta-logical conjunction.
struct all< Head, Tail... >
struct any
Meta-logical disjunction.
struct any< Head, Tail... >
struct ArithmeticConstraintContent
class BaseNumber
struct BaseRepresentation
class Bitset
This class is a simple wrapper around boost::dynamic_bitset.
class BitVector
class Buchberger
Gebauer and Moeller style implementation of the Buchberger algorithm.
class BuchbergerStats
A little class for gathering statistics about the Buchberger algorithm calls.
struct BVBinaryContent
class BVConstraint
class BVConstraintPool
struct BVExtractContent
struct BVReasons
class BVTerm
class BVTermContent
class BVTermPool
struct BVUnaryContent
class BVValue
class BVVariable
Represent a BitVector-Variable.
class Cache
class CAD
This class implements the core of the CAD algorithm.
class CArLConverter
struct characteristic
Type trait for the characteristic of the given field (template argument).
struct Chebyshev
Implements a generator for Chebyshev polynomials.
struct checking
class CoCoAAdaptor
class CompactTree
This class packs a complete binary tree in a vector.
class Condition
struct constant_one
struct constant_zero
class Constraint
Represent a polynomial (in)equality against zero.
class ConstraintContent
Represent a polynomial (in)equality against zero.
class ConstraintPool
struct ConstructorPrinter
class Contraction
class ConvertFrom
struct convertible_to_variant
class ConvertTo
struct convRnd
class Covering
class CriticalPairConfiguration
class CriticalPairs
A data structure to store all the SPolynomial pairs which have to be checked.
class CriticalPairsEntry
A list of SPol pairs which have to be checked by the Buchberger algorithm.
struct DefaultBuchbergerSettings
Standard settings used if the Buchberger object is not instantiated with another template parameter.
struct dependent_bool_type
class DIMACSExporter
class DIMACSImporter
class DiophantineEquations
Includes the algorithms 6.2 and 6.3 from the book Algorithms for Computer Algebra by Geddes, Czaper, Labahn.
struct DivisionLookupResult
The result of.
struct DivisionResult
A strongly typed pair encoding the result of a division, being a quotient and a remainder.
struct EEA
Extended euclidean algorithm for numbers.
struct equal_to
Alternative specialization of std::equal_to for pointer types.
struct equal_to< std::shared_ptr< T >, mayBeNull >
struct equal_to< T *, mayBeNull >
class EZGCD
Extended Zassenhaus algorithm for multivariate GCD calculation.
class Factorization
class FactorizationFactory
This class provides a cached factorization for numbers.
class FactorizationFactory< uint >
This class provides a cached prime factorization for std::size_t.
class FactorizedPolynomial
class FLOAT_T
Templated wrapper class which allows universal usage of different IEEE 754 implementations.
struct FloatConv
Struct which holds the conversion operator for any two instanciations of FLOAT_T with different underlying floating point implementations.
class Formula
Represent an SMT formula, which can be an atom for some background theory or a boolean combination of (sub)formulas.
class FormulaContent
class FormulaPool
struct FormulaSubstitutor
struct FormulaVisitor
This class provides a generic visitor for the above Formula class.
class FromGiNaC
class GaloisField
A finite field.
class GaloisFieldManager
class GBProcedure
A general class for Groebner Basis calculation.
class GeneratorWriter
class GFNumber
Galois Field numbers, i.e.
class GiNaCConversion
class GiNaCConverter
struct greater
struct greater< std::shared_ptr< T >, mayBeNull >
struct greater< T *, mayBeNull >
class GroebnerBase
struct has_subtype
This template is designed to provide types that are related to other types.
struct hash
Alternative specialization of std::hash for pointer types.
struct hash< std::shared_ptr< T >, mayBeNull >
struct hash< T *, mayBeNull >
struct hashEqual
struct hashLess
class Heap
A heap priority queue.
class Ideal
class IdealDatastructureVector
class IDGenerator
class IDPool
struct InfinityValue
This class represents infinity or minus infinity, depending on its flag positive.
struct IntegerPairCompare
struct IntegralType
Gives the corresponding integral type.
struct IntegralType< carl::FLOAT_T< F > >
struct IntegralType< cln::cl_I >
States that IntegralType of cln::cl_I is cln::cl_I .
struct IntegralType< cln::cl_RA >
States that IntegralType of cln::cl_RA is cln::cl_I .
struct IntegralType< double >
States that IntegralType of double is sint .
struct IntegralType< float >
States that IntegralType of float is sint .
struct IntegralType< GFNumber< C > >
struct IntegralType< long double >
States that IntegralType of long double is sint .
struct IntegralType< mpq >
States that IntegralType of mpq is mpz .
struct IntegralType< mpq_class >
States that IntegralType of mpq_class is mpz_class .
struct IntegralType< mpz >
States that IntegralType of mpz is mpz .
struct IntegralType< mpz_class >
States that IntegralType of mpz_class is mpz_class .
struct IntegralType< Numeric< T > >
class Interval
The class which contains the interval arithmetic including trigonometric functions.
class IntervalEvaluation
class InvalidInputStringException
struct is_factorized
struct is_factorized< FactorizedPolynomial< P > >
struct is_field
States if a type is a field.
struct is_field< GFNumber< C > >
States that a Gallois field is a field.
struct is_finite
States if a type represents only a finite domain.
struct is_finite< GFNumber< C > >
Type trait is_finite_domain.
struct is_float
States if a type is a floating point type.
struct is_float< carl::FLOAT_T< C > >
struct is_from_variant
struct is_instantiation_of
struct is_instantiation_of< Template, Template< Args... > >
struct is_integer
States if a type is an integer type.
struct is_integer< cln::cl_I >
States that cln::cl_I has the trait is_integer .
struct is_integer< mpz >
States that mpz has the trait is_integer .
struct is_integer< mpz_class >
States that mpz_class has the trait is_integer .
struct is_interval
States whether a given type is an Interval.
struct is_interval< carl::Interval< Number > >
States that boost::variant is indeed a boost::variant.
struct is_interval< const carl::Interval< Number > >
States that const boost::variant is indeed a boost::variant.
struct is_number
States if a type is a number type.
struct is_number< GFNumber< C > >
struct is_number< Interval< T > >
struct is_polynomial
struct is_polynomial< carl::MultivariatePolynomial< T, O, P > >
struct is_polynomial< carl::UnivariatePolynomial< T > >
struct is_rational
States if a type is a rational type.
struct is_rational< cln::cl_RA >
States that cln::cl_RA has the trait is_rational .
struct is_rational< FLOAT_T< C > >
struct is_rational< mpq >
States that mpq has the trait is_rational .
struct is_rational< mpq_class >
States that mpq_class has the trait is_rational .
struct is_rational< rational >
States that rational has the trait is_rational .
struct is_subset_of_integers
States if a type represents a subset of all integers.
struct is_subset_of_integers< int >
States that int has the trait is_subset_of_integers .
struct is_subset_of_integers< long int >
States that long int has the trait is_subset_of_integers .
struct is_subset_of_integers< long long int >
States that long long int has the trait is_subset_of_integers .
struct is_subset_of_integers< short int >
States that short int has the trait is_subset_of_integers .
struct is_subset_of_integers< signed char >
States that signed char has the trait is_subset_of_integers .
struct is_subset_of_integers< unsigned char >
States that unsigned char has the trait is_subset_of_integers .
struct is_subset_of_integers< unsigned int >
States that unsigned int has the trait is_subset_of_integers .
struct is_subset_of_integers< unsigned long int >
States that unsigned long int has the trait is_subset_of_integers .
struct is_subset_of_integers< unsigned long long int >
States that unsigned long long int has the trait is_subset_of_integers .
struct is_subset_of_integers< unsigned short int >
States that unsigned short int has the trait is_subset_of_integers .
struct is_subset_of_rationals
States if a type represents a subset of all rationals and the representation is similar to a rational.
class LazardEvaluation
struct less
Alternative specialization of std::less for pointer types.
struct less< std::shared_ptr< T >, mayBeNull >
struct less< T *, mayBeNull >
class MapleStream
class Model
Represent a collection of assignments/mappings from variables to values.
class ModelFormulaSubstitution
class ModelMVRootSubstitution
class ModelPolynomialSubstitution
class ModelSubstitution
Represent a expression for a ModelValue with variables as placeholders, where the final expression's value depends on the bindings/values of these variables.
class ModelValue
Represent a sum type/variant over the different kinds of values that can be assigned to the different kinds of variables that exist in CARL and to use them in a more uniform way, e.g.
class ModelVariable
Represent a sum type/variant over the different kinds of variables that exist in CARL to use them in a more uniform way, e.g.
class Monomial
The general-purpose monomials.
struct MonomialComparator
A class for term orderings.
class MonomialPool
struct mpl_concatenate
struct mpl_concatenate_impl
struct mpl_concatenate_impl< 1, Front, Tail... >
struct mpl_unique
struct mpl_variant_of
struct mpl_variant_of_impl
struct mpl_variant_of_impl< true, Vector, Unpacked... >
class MultiplicationTable
class MultivariateGCD
A general object for gcd calculation of multivariate gcds.
class MultivariateHensel
class MultivariateHorner
class MultivariatePolynomial
The general-purpose multivariate polynomial class.
class MultivariateRoot
struct needs_cache
struct needs_cache< FactorizedPolynomial< P > >
struct NoAllocator
struct NoReasons
struct not_equal_to
struct not_equal_to< std::shared_ptr< T >, mayBeNull >
struct not_equal_to< T *, mayBeNull >
class Number
class Number< cln::cl_I >
class Number< cln::cl_RA >
class Number< Interval< cln::cl_I > >
class Number< Interval< cln::cl_RA > >
class Number< Interval< double > >
class Number< Interval< int > >
class Number< Interval< mpq_class > >
class Number< Interval< mpz_class > >
class Number< long int >
class Number< mpq_class >
class Number< mpz_class >
class Numeric
class OldGinacConverter
struct OPBFile
class OPBImporter
struct OPBParser
struct OptionPrinter
class PBConstraint
struct policies
Struct which holds the rounding and checking policies required for boost interval.
struct policies< double, Interval >
Template specialization for rounding and checking policies for native double.
class Polynomial
Abstract base class for polynomials.
class PolynomialFactorizationPair
class Pool
class PreventConversion
class PrimeFactory
This class provides a convenient way to enumerate primes.
struct PrimitiveEuclidean
Algorithm to compute the GCD in Unique factorization domains.
class QEPCADStream
struct QuantifierContent
Stores the variables and the formula bound by a quantifier.
struct RadicalAwareAdding
class RationalFunction
class RealAlgebraicNumber
class RealAlgebraicPoint
Represent a multidimensional point whose components are algebraic reals.
struct RealRadicalAwareAdding
class Reductor
A dedicated algorithm for calculating the remainder of a polynomial modulo a set of other polynomials.
class ReductorConfiguration
Class with the settings for the reduction algorithm.
class ReductorEntry
An entry in the reduction polynomial.
struct remove_all
struct remove_all< T, T >
struct rounding
class SignCondition
class SignDetermination
class SimpleConstraint
class SimpleNewton
class Singleton
Base class that implements a singleton.
struct Skipper
class SMTLIBStream
class Sort
Implements a sort (for defining types of variables and functions).
struct SortContent
The actual content of a sort.
class SortManager
Implements a manager for sorts, containing the actual contents of these sort and allocating their ids.
class SortValue
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
class SortValueManager
Implements a manager for sort values, containing the actual contents of these sort and allocating their ids.
struct SPolPair
Basic spol-pair.
struct SPolPairCompare
class SqrtEx
struct StdAdding
struct StdMultivariatePolynomialPolicies
The default policy for polynomials.
struct strategy
class StringParser
class TarskiQueryManager
class TaylorExpansion
class Term
Represents a single term, that is a numeric coefficient and a monomial.
class TermAdditionManager
class ThomEncoding
class Timer
This classes provides an easy way to obtain the current number of milliseconds that the program has been running.
class TimingCollector
class ToGiNaC
class tree
This class represents a tree.
class tuple_convert
class tuple_convert< Converter, Information, Out >
class UEquality
Implements an uninterpreted equality, that is an equality of either two uninterpreted function instances, two uninterpreted variables, or an uninterpreted function instance and an uninterpreted variable.
class UFContent
The actual content of an uninterpreted function instance.
class UFInstance
Implements an uninterpreted function instance.
class UFInstanceContent
The actual content of an uninterpreted function instance.
class UFInstanceManager
Implements a manager for uninterpreted function instances, containing their actual contents and allocating their ids.
class UFManager
Implements a manager for uninterpreted functions, containing their actual contents and allocating their ids.
class UFModel
Implements a sort value, being a value of the uninterpreted domain specified by this sort.
struct UnderlyingNumberType
Gives the underlying number type of a complex object.
struct UnderlyingNumberType< MultivariatePolynomial< C, O, P > >
States that UnderlyingNumberType of MultivariatePolynomial<C,O,P> is UnderlyingNumberType<C>::type.
struct UnderlyingNumberType< UnivariatePolynomial< C > >
States that UnderlyingNumberType of UnivariatePolynomial<T> is UnderlyingNumberType<C>::type.
class UninterpretedFunction
Implements an uninterpreted function.
class UnivariatePolynomial
This class represents a univariate polynomial with coefficients of an arbitrary type.
struct UpdateFnc
struct UpdateFnct
class UVariable
Implements an uninterpreted variable.
class Variable
A Variable represents an algebraic variable that can be used throughout carl.
class VariableAssignment
class VariableComparison
Represent a sum type/variant of an (in)equality between a variable on the left-hand side and multivariateRoot or algebraic real on the right-hand side.
struct VariableInformation
class VariableInformation< false, CoeffType >
class VariableInformation< true, CoeffType >
class VariablePool
This class generates new variables and stores human-readable names for them.
class VariablesInformation
class VariablesInformationInterface
class VarSolutionFormula
struct Void
Typedefs
template<typename P >
using Coeff = typename UnderlyingNumberType< P >::type
using exponent = uint
Type of an exponent.
using MonomialOrderingFunction = CompareResult(*)(const Monomial::Arg &, const Monomial::Arg &)
using LexOrdering = MonomialComparator< Monomial::compareLexical, false >
using GrLexOrdering = MonomialComparator< Monomial::compareGradedLexical, true >
template<typename Coefficient >
using UnivariatePolynomialPtr = std::shared_ptr< UnivariatePolynomial< Coefficient > >
template<typename Coefficient >
using FactorMap = std::map< UnivariatePolynomial< Coefficient >, uint >
template<typename Poly >
using Constraints = std::set< Constraint< Poly >, carl::less< Constraint< Poly >, false > >
template<typename Pol >
using VarInfo = VariableInformation< true, Pol >
template<typename Pol >
using VarInfoMap = std::map< Variable, VarInfo< Pol > >
template<typename Poly >
using Formulas = std::vector< Formula< Poly > >
template<typename Poly >
using FormulaSet = std::set< Formula< Poly > >
template<typename Poly >
using FormulasMulti = std::multiset< Formula< Poly >, carl::less< Formula< Poly > >>
template<typename Rational , typename Poly >
using ModelSubstitutionPtr = std::shared_ptr< ModelSubstitution< Rational, Poly > >
using BaseIteratorType = spirit::istream_iterator
using PositionIteratorType = spirit::line_pos_iterator< BaseIteratorType >
using Iterator = PositionIteratorType
using ErrorHandler = carl::parser::ErrorHandler
using OPBPolynomial = std::vector< std::pair< int, carl::Variable > >
using OPBConstraint = std::tuple< OPBPolynomial, Relation, int >
typedef CriticalPairs< Heap, CriticalPairConfiguration< GrLexOrdering > > CritPairs
typedef Contraction< SimpleNewton, Polynomial > SimpleNewtonContraction
using precision_t = std::size_t
using uint = std::uint64_t
using sint = std::int64_t
using ContentType = sint
template<typename C >
using IntegralTypeIfDifferent = typename std::enable_if<!std::is_same< C, typename IntegralType< C >::type >::value, typename IntegralType< C >::type >::type
template<typename Coeff >
using CoeffMatrix = Eigen::Matrix< Coeff, Eigen::Dynamic, Eigen::Dynamic >
template<typename T , class I >
using TypeInfoPair = std::pair< T *, I >
template<typename T >
using pointerEqual = carl::equal_to< const T *, false >
template<typename T >
using pointerEqualWithNull = carl::equal_to< const T *, true >
template<typename T >
using sharedPointerEqual = carl::equal_to< std::shared_ptr< const T >, false >
template<typename T >
using sharedPointerEqualWithNull = carl::equal_to< std::shared_ptr< const T >, true >
template<typename T >
using pointerLess = carl::less< const T *, false >
template<typename T >
using pointerLessWithNull = carl::less< const T *, true >
template<typename T >
using sharedPointerLess = carl::less< std::shared_ptr< const T > *, false >
template<typename T >
using sharedPointerLessWithNull = carl::less< std::shared_ptr< const T >, true >
template<typename T >
using pointerHash = carl::hash< T *, false >
template<typename T >
using pointerHashWithNull = carl::hash< T *, true >
template<typename T >
using sharedPointerHash = carl::hash< std::shared_ptr< const T > *, false >
template<typename T >
using sharedPointerHashWithNull = carl::hash< std::shared_ptr< const T > *, true >
template<typename T >
using EvaluationMap = std::map< Variable, T >
using Variables = std::set< Variable >
using QuantifiedVariables = std::vector< Variables >
template<typename T >
using PointerSet = std::set< const T *, pointerLess< T > >
template<typename T >
using PointerMultiSet = std::multiset< const T *, pointerLess< T > >
template<typename T1 , typename T2 >
using PointerMap = std::map< const T1 *, T2, pointerLess< T1 > >
template<typename T >
using SharedPointerSet = std::set< std::shared_ptr< const T >, sharedPointerLess< T > >
template<typename T >
using SharedPointerMultiSet = std::multiset< std::shared_ptr< const T >, sharedPointerLess< T > >
template<typename T1 , typename T2 >
using SharedPointerMap = std::map< std::shared_ptr< const T1 >, T2, sharedPointerLess< T1 > >
template<typename T >
using FastSet = std::unordered_set< T, std::hash< T > >
template<typename T1 , typename T2 >
using FastMap = std::unordered_map< T1, T2, std::hash< T1 > >
template<typename T >
using FastPointerSet = std::unordered_set< const T *, pointerHash< T >, pointerEqual< T > >
template<typename T1 , typename T2 >
using FastPointerMap = std::unordered_map< const T1 *, T2, pointerHash< T1 >, pointerEqual< T1 > >
template<typename T >
using FastSharedPointerSet = std::unordered_set< std::shared_ptr< const T >, sharedPointerHash< T >, sharedPointerEqual< T > >
template<typename T1 , typename T2 >
using FastSharedPointerMap = std::unordered_map< std::shared_ptr< const T1 >, T2, sharedPointerHash< T1 >, sharedPointerEqual< T1 > >
template<typename T >
using FastPointerSetB = std::unordered_set< const T *, pointerHashWithNull< T >, pointerEqualWithNull< T > >
template<typename T1 , typename T2 >
using FastPointerMapB = std::unordered_map< const T1 *, T2, pointerHashWithNull< T1 >, pointerEqualWithNull< T1 > >
template<typename T >
using FastSharedPointerSetB = std::unordered_set< std::shared_ptr< const T >, sharedPointerHashWithNull< T >, pointerEqualWithNull< T > >
template<typename T1 , typename T2 >
using FastSharedPointerMapB = std::unordered_map< std::shared_ptr< const T1 >, T2, sharedPointerHashWithNull< T1 >, pointerEqualWithNull< T1 > >
template<typename Pol >
using Factors = std::map< Pol, uint >
template<bool If, typename Then , typename Else >
using Conditional = typename std::conditional< If, Then, Else >::type
template<bool B, typename... T>
using Bool = typename dependent_bool_type< B, T... >::type
template<typename T >
using Not = Bool<!T::value >
Meta-logical negation.
template<typename... Condition>
using EnableIf = typename std::enable_if< all< Condition... >::value, dtl::enabled >::type
template<typename... Condition>
using DisableIf = typename std::enable_if< Not< any< Condition... > >::value, dtl::enabled >::type
template<bool Condition>
using EnableIfBool = typename std::enable_if< Condition, dtl::enabled >::type
Enumerations
enum CompareResult { LESS = -1, EQUAL = 0, GREATER = 1 }
enum Definiteness {
Definiteness::NEGATIVE = 0, Definiteness::NEGATIVE_SEMI = 1, Definiteness::NON = 2, Definiteness::POSITIVE_SEMI = 3,
Definiteness::POSITIVE = 4
}
Regarding a polynomial as a function , its definiteness gives information about the codomain .
enum variableSelectionHeurisics { GREEDY_I = 0, GREEDY_Is = 1, GREEDY_II = 2, GREEDY_IIs = 3 }
enum SubresultantStrategy { SubresultantStrategy::Generic, SubresultantStrategy::Lazard, SubresultantStrategy::Ducos, SubresultantStrategy::Default = Lazard }
enum Relation {
Relation::EQ = 0, Relation::NEQ = 1, LESS = 2, Relation::LEQ = 4,
GREATER = 3, Relation::GEQ = 5
}
enum Sign { Sign::NEGATIVE = -1, Sign::ZERO = 0, Sign::POSITIVE = 1 }
This class represents the sign of a number .
enum PolynomialComparisonOrder { PolynomialComparisonOrder::CauchyBound, PolynomialComparisonOrder::LowDegree, PolynomialComparisonOrder::Memory, PolynomialComparisonOrder::Default = LowDegree }
enum VariableType {
VariableType::VT_BOOL = 0, VariableType::VT_REAL = 1, VariableType::VT_INT = 2, VariableType::VT_UNINTERPRETED = 3,
VariableType::VT_BITVECTOR = 4, VariableType::MIN_TYPE = VT_BOOL, VariableType::MAX_TYPE = VT_BITVECTOR, VariableType::TYPE_SIZE = MAX_TYPE - MIN_TYPE + 1
}
Several types of variables are supported.
enum BVCompareRelation : unsigned {
BVCompareRelation::EQ, BVCompareRelation::NEQ, BVCompareRelation::ULT, BVCompareRelation::ULE,
BVCompareRelation::UGT, BVCompareRelation::UGE, BVCompareRelation::SLT, BVCompareRelation::SLE,
BVCompareRelation::SGT, BVCompareRelation::SGE
}
enum BVTermType : unsigned {
BVTermType::CONSTANT, BVTermType::VARIABLE, BVTermType::CONCAT, BVTermType::EXTRACT,
NOT, BVTermType::NEG, AND, OR,
XOR, BVTermType::NAND, BVTermType::NOR, BVTermType::XNOR,
BVTermType::ADD, BVTermType::SUB, BVTermType::MUL, BVTermType::DIV_U,
BVTermType::DIV_S, BVTermType::MOD_U, BVTermType::MOD_S1, BVTermType::MOD_S2,
BVTermType::EQ, BVTermType::LSHIFT, BVTermType::RSHIFT_LOGIC, BVTermType::RSHIFT_ARITH,
BVTermType::LROTATE, BVTermType::RROTATE, BVTermType::EXT_U, BVTermType::EXT_S,
BVTermType::REPEAT
}
enum FormulaType {
ITE, EXISTS, FORALL, TRUE,
FALSE, BOOL, NOT, NOT,
IMPLIES, AND, AND, OR,
OR, XOR, XOR, IFF,
CONSTRAINT, VARCOMPARE, VARASSIGN, BITVECTOR,
UEQ, PBCONSTRAINT
}
Represent the type of a formula to allow faster/specialized processing.
enum Logic {
Logic::QF_BV, Logic::QF_IDL, Logic::QF_LIA, Logic::QF_LIRA,
Logic::QF_LRA, Logic::QF_NIA, Logic::QF_NIRA, Logic::QF_NRA,
Logic::QF_PB, Logic::QF_RDL, Logic::QF_UF, Logic::UNDEFINED
}
enum RANSampleHeuristic {
RANSampleHeuristic::Center, RANSampleHeuristic::CenterInt, RANSampleHeuristic::LeftInt, RANSampleHeuristic::RightInt,
RANSampleHeuristic::ZeroInt, RANSampleHeuristic::InftyInt, RANSampleHeuristic::Default = RightInt
}
enum BoundType { BoundType::STRICT = 0, BoundType::WEAK = 1, BoundType::INFTY = 2 }
enum Str2Double_Error { FLOAT_SUCCESS, FLOAT_OVERFLOW, FLOAT_UNDERFLOW, FLOAT_INCONVERTIBLE }
enum CARL_RND : int {
CARL_RND::N =0, CARL_RND::Z =1, CARL_RND::U =2, CARL_RND::D =3,
CARL_RND::A =4
}
enum ThomComparisonResult {
LESS, LESS = -1, LESS = 2, EQUAL,
EQUAL = 0, GREATER, GREATER = 1, GREATER = 3
}
Functions
template<typename Poly >
bool similar (const GiNaC::ex &a, const GiNaC::ex &b)
template<typename Poly >
void gatherVariables (const Poly &poly, std::map< Variable, GiNaC::ex > &carlToGinacVarMap, std::map< GiNaC::ex, Variable, GiNaC::ex_is_less > &ginacToCarlVarMap)
template<typename Poly >
GiNaC::ex convertToGinac (const Poly &poly, const std::map< carl::Variable, GiNaC::ex > &vars)
template<typename Poly >
Poly convertToCarl (const GiNaC::ex &_toConvert, const std::map< GiNaC::ex, carl::Variable, GiNaC::ex_is_less > &vars)
template<typename Poly >
Poly ginacGcd (const Poly &polyA, const Poly &polyB)
template<typename Poly >
bool ginacDivide (const Poly &polyA, const Poly &polyB, Poly &result)
template<typename Poly >
Factors< Poly > ginacFactorization (const Poly &poly)
template<typename Poly >
bool checkConversion (const Poly &polyA)
template<typename Poly >
void setGinacConverterPolynomialCache (const std::shared_ptr< typename Poly::CACHE > &_cache)
template<typename T >
std::string binary (const T &a, const bool &spacing=true)
Return the binary representation given value as bit string.
std::string basename (const std::string &filename)
Return the basename of a given filename.
std::ostream & operator<< (std::ostream &os, CompareResult cr)
std::ostream & operator<< (std::ostream &os, Definiteness d)
template<typename T >
std::vector< T > solveDiophantine (MultivariatePolynomial< T > &p)
Diophantine Equations solver.
template<typename T >
T extended_gcd_integer (T a, T b, T &s, T &t)
template<typename P >
P computePolynomial (const FactorizedPolynomial< P > &_fpoly)
Obtains the polynomial (representation) of this factorized polynomial.
template<typename P >
std::ostream & operator<< (std::ostream &_out, const FactorizedPolynomial< P > &_fpoly)
Prints the factorization representation of the given factorized polynomial on the given output stream.
int init ()
The routine for initializing the carl library.
int initialize ()
Method to ensure that upon inclusion, init() is called exactly once.
Monomial::Arg pow (Variable v, std::size_t exp)
bool operator== (const std::pair< Variable, uint > &p, Variable v)
Compare a pair of variable and exponent with a variable.
Monomial::Arg pow (const Monomial::Arg &m, std::size_t exp)
std::ostream & operator<< (std::ostream &os, const MonomialPool &mp)
template<typename... T>
Monomial::Arg createMonomial (T &&... t)
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > gcd (const MultivariatePolynomial< C, O, P > &a, const MultivariatePolynomial< C, O, P > &b)
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > lcm (const MultivariatePolynomial< C, O, P > &a, const MultivariatePolynomial< C, O, P > &b)
template<typename C , typename O , typename P >
Term< C > gcd (const MultivariatePolynomial< C, O, P > &a, const Term< C > &b)
template<typename C , typename O , typename P >
Term< C > gcd (const Term< C > &a, const MultivariatePolynomial< C, O, P > &b)
template<typename C , typename O , typename P >
Monomial::Arg gcd (const MultivariatePolynomial< C, O, P > &a, const Monomial::Arg &b)
template<typename C , typename O , typename P >
Monomial::Arg gcd (const Monomial::Arg &a, const MultivariatePolynomial< C, O, P > &b)
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > quotient (const MultivariatePolynomial< C, O, P > &p, const MultivariatePolynomial< C, O, P > &q)
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > pow (const MultivariatePolynomial< C, O, P > &p, std::size_t exp)
template<typename C , typename O , typename P >
std::pair< MultivariatePolynomial< C, O, P >, MultivariatePolynomial< C, O, P > > lazyDiv (const MultivariatePolynomial< C, O, P > &_polyA, const MultivariatePolynomial< C, O, P > &_polyB)
template<typename P >
std::string factorizationToString (const Factorization< P > &_factorization, bool _infix=true, bool _friendlyVarNames=true)
template<typename P >
std::ostream & operator<< (std::ostream &_out, const Factorization< P > &_factorization)
template<typename P >
bool factorizationsEqual (const Factorization< P > &_factorizationA, const Factorization< P > &_factorizationB)
template<typename P >
P computePolynomial (const PolynomialFactorizationPair< P > &_pfPair)
Compute the polynomial from the given polynomial-factorization pair.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > coprimePart (const MultivariatePolynomial< C, O, P > &p, const MultivariatePolynomial< C, O, P > &q)
template<typename C , typename O , typename P >
Factors< MultivariatePolynomial< C, O, P > > factorization (const MultivariatePolynomial< C, O, P > &p, bool includeConstants=true)
Try to factorize a multivariate polynomial.
template<typename Coeff >
std::list< UnivariatePolynomial< Coeff > > subresultants (const UnivariatePolynomial< Coeff > &, const UnivariatePolynomial< Coeff > &, SubresultantStrategy=SubresultantStrategy::Default)
template<typename Coeff >
std::vector< UnivariatePolynomial< Coeff > > principalSubresultantsCoefficients (const UnivariatePolynomial< Coeff > &, const UnivariatePolynomial< Coeff > &, SubresultantStrategy=SubresultantStrategy::Default)
template<typename Coeff >
UnivariatePolynomial< Coeff > resultant (const UnivariatePolynomial< Coeff > &, const UnivariatePolynomial< Coeff > &, SubresultantStrategy=SubresultantStrategy::Default)
template<typename Coeff >
UnivariatePolynomial< Coeff > discriminant (const UnivariatePolynomial< Coeff > &, SubresultantStrategy=SubresultantStrategy::Default)
template<typename Coeff >
Coeff cauchyBound (const UnivariatePolynomial< Coeff > &p)
template<typename Coeff >
Coeff hirstMaceyBound (const UnivariatePolynomial< Coeff > &p)
template<typename Coeff >
Coeff lagrangeBound (const UnivariatePolynomial< Coeff > &p)
template<typename C , typename O , typename P >
std::vector< std::pair< C, MultivariatePolynomial< C, O, P > > > SoSDecomposition (const MultivariatePolynomial< C, O, P > &p, bool not_trivial=false)
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > SPolynomial (const MultivariatePolynomial< C, O, P > &p, const MultivariatePolynomial< C, O, P > &q)
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > squareFreePart (const MultivariatePolynomial< C, O, P > &p)
template<typename Coeff , EnableIf< is_subset_of_rationals< Coeff >> = dummy>
UnivariatePolynomial< Coeff > squareFreePart (const UnivariatePolynomial< Coeff > &p)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator+ (const RationalFunction< Pol, AS > &lhs, const RationalFunction< Pol, AS > &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator+ (const RationalFunction< Pol, AS > &lhs, const Pol &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator+ (const RationalFunction< Pol, AS > &lhs, const Term< typename Pol::CoeffType > &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator+ (const RationalFunction< Pol, AS > &lhs, const Monomial::Arg &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator+ (const RationalFunction< Pol, AS > &lhs, Variable rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator+ (const RationalFunction< Pol, AS > &lhs, const typename Pol::CoeffType &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs, const RationalFunction< Pol, AS > &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs, const Pol &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs, const Term< typename Pol::CoeffType > &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs, const Monomial::Arg &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs, Variable rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator- (const RationalFunction< Pol, AS > &lhs, const typename Pol::CoeffType &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, const RationalFunction< Pol, AS > &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, const Pol &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, const Term< typename Pol::CoeffType > &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, const Monomial::Arg &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, Variable rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, const typename Pol::CoeffType &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator* (const typename Pol::CoeffType &lhs, const RationalFunction< Pol, AS > &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator* (const RationalFunction< Pol, AS > &lhs, carl::sint rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator* (carl::sint lhs, const RationalFunction< Pol, AS > &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, const RationalFunction< Pol, AS > &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, const Pol &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, const Term< typename Pol::CoeffType > &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, const Monomial::Arg &rhs)
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, Variable rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, const typename Pol::CoeffType &rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > operator/ (const RationalFunction< Pol, AS > &lhs, unsigned long rhs)
template<typename Pol , bool AS>
RationalFunction< Pol, AS > pow (unsigned exp, const RationalFunction< Pol, AS > &rf)
template<typename Pol , bool AS>
bool operator!= (const RationalFunction< Pol, AS > &lhs, const RationalFunction< Pol, AS > &rhs)
std::ostream & operator<< (std::ostream &os, const Relation &r)
Relation inverse (Relation r)
std::string toString (Relation r)
bool isStrict (Relation r)
bool isWeak (Relation r)
bool evaluate (Sign s, Relation r)
template<typename T >
bool evaluate (const T &t, Relation r)
std::ostream & operator<< (std::ostream &os, const Sign &sign)
template<typename Number >
Sign sgn (const Number &n)
Obtain the sign of the given number.
template<typename InputIterator >
std::size_t signVariations (InputIterator begin, InputIterator end)
Counts the number of sign variations in the given object range.
template<typename InputIterator , typename Function >
std::size_t signVariations (InputIterator begin, InputIterator end, const Function &f)
Counts the number of sign variations in the given object range.
template<typename LhsT >
bool operator== (const SimpleConstraint< LhsT > &lhs, const SimpleConstraint< LhsT > &rhs)
template<typename LhsT >
bool operator!= (const SimpleConstraint< LhsT > &lhs, const SimpleConstraint< LhsT > &rhs)
template<typename LhsT >
std::ostream & operator<< (std::ostream &os, const SimpleConstraint< LhsT > &rhs)
template<typename LhsT >
std::string to_string (const SimpleConstraint< LhsT > &constraint, bool pretty=false)
template<typename Coeff >
Term< Coeff > operator- (const Term< Coeff > &rhs)
VariableType variableTypeFromString (const std::string &in)
std::string to_string (const VariableType &t)
To string conversion for variable type.
std::ostream & operator<< (std::ostream &os, const VariableType &t)
Streaming operator for VariableType.
Variable freshVariable (VariableType vt) noexcept
Variable freshVariable (const std::string &name, VariableType vt)
Variable freshBitvectorVariable () noexcept
Variable freshBitvectorVariable (const std::string &name)
Variable freshBooleanVariable () noexcept
Variable freshBooleanVariable (const std::string &name)
Variable freshRealVariable () noexcept
Variable freshRealVariable (const std::string &name)
Variable freshIntegerVariable () noexcept
Variable freshIntegerVariable (const std::string &name)
Variable freshUninterpretedVariable () noexcept
Variable freshUninterpretedVariable (const std::string &name)
void printRegisteredVariableNames ()
std::string toString (BVCompareRelation _r)
std::ostream & operator<< (std::ostream &_os, const BVCompareRelation &_r)
std::size_t toId (const BVCompareRelation _relation)
BVCompareRelation inverse (BVCompareRelation _c)
bool relationIsStrict (BVCompareRelation _r)
bool relationIsSigned (BVCompareRelation _r)
std::string toString (const BVTermType _type)
std::ostream & operator<< (std::ostream &os, BVTermType type)
std::size_t typeId (const BVTermType _type)
bool typeIsUnary (const BVTermType _type)
bool typeIsBinary (const BVTermType _type)
bool operator== (const BVVariable &lhs, const BVVariable &rhs)
bool operator== (const BVVariable &lhs, const Variable &rhs)
bool operator== (const Variable &lhs, const BVVariable &rhs)
bool operator< (const BVVariable &lhs, const BVVariable &rhs)
bool operator< (const BVVariable &lhs, const Variable &rhs)
bool operator< (const Variable &lhs, const BVVariable &rhs)
bool operator<= (const Condition &lhs, const Condition &rhs)
Check whether the bits of this condition are always set if the corresponding bit of the given condition is set.
template<typename Pol , EnableIf< needs_cache< Pol >> = dummy>
Pol makePolynomial (typename Pol::PolyType &&_poly)
template<typename Pol , EnableIf< needs_cache< Pol >> = dummy>
Pol makePolynomial (carl::Variable::Arg _var)
template<typename Pol , EnableIf< needs_cache< Pol >> = dummy>
Pol makePolynomial (const typename Pol::PolyType &_poly)
Relation turnAroundRelation (const Relation &_rel)
Turns around the given relation symbol.
template<typename Pol >
bool operator== (const ConstraintContent< Pol > &lhs, const ConstraintContent< Pol > &rhs)
template<typename P >
std::ostream & operator<< (std::ostream &_out, const ConstraintContent< P > &_cc)
Prints the representation of the given constraints on the given stream.
template<typename P >
bool operator== (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename P >
bool operator!= (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename P >
bool operator< (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename P >
bool operator> (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename P >
bool operator<= (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename P >
bool operator>= (const Constraint< P > &lhs, const Constraint< P > &rhs)
template<typename Pol >
signed compare (const Constraint< Pol > &_constraintA, const Constraint< Pol > &_constraintB)
Compares _constraintA with _constraintB.
template<typename Poly >
std::ostream & operator<< (std::ostream &_out, const Constraint< Poly > &_constraint)
Prints the given constraint on the given stream.
template<typename Pol >
const ConstraintPool< Pol > & constraintPool ()
template<typename Poly >
std::ostream & operator<< (std::ostream &_out, const Formula< Poly > &_formula)
Prints the given formula on the given stream.
std::string formulaTypeToString (FormulaType _type)
std::ostream & operator<< (std::ostream &os, FormulaType t)
template<typename P >
std::ostream & operator<< (std::ostream &_out, const FormulaContent< P > &_formula)
The output operator of a formula.
template<typename P >
std::ostream & operator<< (std::ostream &_out, const FormulaContent< P > *_formula)
std::ostream & operator<< (std::ostream &os, const Logic &l)
template<typename Rational , typename Poly >
bool getRationalAssignmentsFromModel (const Model< Rational, Poly > &_model, std::map< Variable, Rational > &_rationalAssigns)
Obtains all assignments which can be transformed to rationals and stores them in the passed map.
template<typename Rational , typename Poly >
unsigned satisfies (const Model< Rational, Poly > &_assignment, const Formula< Poly > &_formula)
template<typename Rational , typename Poly >
bool isPartOf (const std::map< Variable, Rational > &_assignment, const Model< Rational, Poly > &_model)
template<typename Rational , typename Poly >
unsigned satisfies (const Model< Rational, Poly > &_model, const std::map< Variable, Rational > &_assignment, const std::map< BVVariable, BVTerm > &bvAssigns, const Formula< Poly > &_formula)
template<typename Rational , typename Poly >
void getDefaultModel (Model< Rational, Poly > &_defaultModel, const UEquality &_constraint, bool _overwrite=true, size_t _seed=0)
template<typename Rational , typename Poly >
void getDefaultModel (Model< Rational, Poly > &_defaultModel, const BVTerm &_constraint, bool _overwrite=true, size_t _seed=0)
template<typename Rational , typename Poly >
void getDefaultModel (Model< Rational, Poly > &_defaultModel, const Constraint< Poly > &_constraint, bool _overwrite=true, size_t _seed=0)
template<typename Rational , typename Poly >
void getDefaultModel (Model< Rational, Poly > &_defaultModel, const Formula< Poly > &_formula, bool _overwrite=true, size_t _seed=0)
template<typename Rational , typename Poly >
Formula< Poly > representingFormula (const ModelVariable &mv, const Model< Rational, Poly > &model)
template<typename Rational , typename Poly >
std::ostream & operator<< (std::ostream &os, const Model< Rational, Poly > &model)
template<typename Rational , typename Poly >
std::ostream & operator<< (std::ostream &os, const ModelSubstitution< Rational, Poly > &ms)
template<typename Rational , typename Poly >
std::ostream & operator<< (std::ostream &os, const std::shared_ptr< ModelSubstitution< Rational, Poly >> &ms)
template<typename Rational , typename Poly , typename Substitution , typename... Args>
ModelValue< Rational, Poly > createSubstitution (Args &&... args)
template<typename Rational , typename Poly >
ModelValue< Rational, Poly > createSubstitution (const MultivariateRoot< Poly > &mr)
std::string toString (const InfinityValue &iv, bool _infix)
std::ostream & operator<< (std::ostream &os, const InfinityValue &iv)
template<typename Rational , typename Poly >
bool operator== (const ModelValue< Rational, Poly > &lhs, const ModelValue< Rational, Poly > &rhs)
Check if two Assignments are equal.
template<typename R , typename P >
std::ostream & operator<< (std::ostream &os, const ModelValue< R, P > &mv)
bool operator== (const ModelVariable &lhs, const ModelVariable &rhs)
bool operator< (const ModelVariable &lhs, const ModelVariable &rhs)
std::ostream & operator<< (std::ostream &os, const ModelVariable &mv)
template<typename Poly >
bool operator== (const MultivariateRoot< Poly > &lhs, const MultivariateRoot< Poly > &rhs)
template<typename Poly >
bool operator< (const MultivariateRoot< Poly > &lhs, const MultivariateRoot< Poly > &rhs)
template<typename P >
std::ostream & operator<< (std::ostream &os, const MultivariateRoot< P > &mr)
template<typename Num >
std::ostream & operator<< (std::ostream &os, const RealAlgebraicNumber< Num > &ran)
template<typename Number >
bool operator== (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs)
template<typename Number >
bool operator!= (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs)
template<typename Number >
bool operator< (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs)
template<typename Number >
bool operator<= (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs)
template<typename Number >
bool operator> (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs)
template<typename Number >
bool operator>= (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs)
template<typename Number >
bool isZero (const RealAlgebraicNumber< Number > &n)
template<typename Number >
bool isInteger (const RealAlgebraicNumber< Number > &n)
template<typename Number >
IntegralType< Number >::type floor (const RealAlgebraicNumber< Number > &n)
template<typename Number >
IntegralType< Number >::type floor_fast (const RealAlgebraicNumber< Number > &n)
template<typename Number >
IntegralType< Number >::type ceil (const RealAlgebraicNumber< Number > &n)
template<typename Number >
IntegralType< Number >::type ceil_fast (const RealAlgebraicNumber< Number > &n)
template<typename Number >
RealAlgebraicNumber< Number > sampleBelow (const RealAlgebraicNumber< Number > &n)
template<typename Number >
RealAlgebraicNumber< Number > sampleBetween (const RealAlgebraicNumber< Number > &lower, const RealAlgebraicNumber< Number > &upper, RANSampleHeuristic heuristic=RANSampleHeuristic::Default)
template<typename Number >
RealAlgebraicNumber< Number > sampleAbove (const RealAlgebraicNumber< Number > &n)
template<typename Number >
bool operator== (RealAlgebraicPoint< Number > &lhs, RealAlgebraicPoint< Number > &rhs)
Check if two RealAlgebraicPoints are equal.
template<typename Number >
std::ostream & operator<< (std::ostream &os, const RealAlgebraicPoint< Number > &r)
Streaming operator for a RealAlgebraicPoint.
std::ostream & operator<< (std::ostream &os, const SortValue &sv)
SortValue newSortValue (const Sort &_sort)
Creates a new value for the given sort.
SortValue defaultSortValue (const Sort &_sort)
Returns the default value for the given sort.
std::ostream & operator<< (std::ostream &_os, const UFModel &_ufm)
boost::optional< OPBFile > parseOPBFile (std::ifstream &in)
template<typename Pol >
std::ostream & operator<< (std::ostream &os, const PBConstraint< Pol > &pbc)
template<typename Pol >
bool operator== (const PBConstraint< Pol > &lhs, const PBConstraint< Pol > &rhs)
template<typename Pol >
bool operator< (const PBConstraint< Pol > &lhs, const PBConstraint< Pol > &rhs)
std::ostream & operator<< (std::ostream &_os, const Sort &_sort)
bool operator== (const Sort &lhs, const Sort &rhs)
bool operator< (const Sort &lhs, const Sort &rhs)
bool operator< (const SortContent &lhs, const SortContent &rhs)
template<typename... Args>
Sort getSort (Args &&... args)
Gets the sort specified by the arguments.
std::ostream & operator<< (std::ostream &_os, const UEquality &_ueq)
std::ostream & operator<< (std::ostream &_os, const UFInstance &_ufun)
UFInstance newUFInstance (const UninterpretedFunction &_uf, std::vector< UVariable > &&_args)
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
UFInstance newUFInstance (const UninterpretedFunction &_uf, const std::vector< UVariable > &_args)
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
UninterpretedFunction newUninterpretedFunction (std::string _name, std::vector< Sort > _domain, Sort _codomain)
Gets the uninterpreted function with the given name, domain, arguments and codomain.
std::ostream & operator<< (std::ostream &_os, const UninterpretedFunction &_ufun)
template<typename Poly >
bool operator== (const VariableAssignment< Poly > &lhs, const VariableAssignment< Poly > &rhs)
template<typename Poly >
bool operator< (const VariableAssignment< Poly > &lhs, const VariableAssignment< Poly > &rhs)
template<typename Poly >
std::ostream & operator<< (std::ostream &os, const VariableAssignment< Poly > &va)
template<typename Poly >
bool operator== (const VariableComparison< Poly > &lhs, const VariableComparison< Poly > &rhs)
template<typename Poly >
bool operator< (const VariableComparison< Poly > &lhs, const VariableComparison< Poly > &rhs)
template<typename Poly >
std::ostream & operator<< (std::ostream &os, const VariableComparison< Poly > &vc)
template<class C >
std::ostream & operator<< (std::ostream &os, const ReductorEntry< C > rhs)
static BoundType getWeakestBoundType (BoundType type1, BoundType type2)
static BoundType getStrictestBoundType (BoundType type1, BoundType type2)
static BoundType getOtherBoundType (BoundType type)
template<typename Number >
static bool isZero (const Interval< Number > &_in)
Check if this interval is a point-interval containing 0.
template<typename Number >
static bool isOne (const Interval< Number > &_in)
Check if this interval is a point-interval containing 1.
template<typename Number >
Interval< Number > operator+ (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the addition of two intervals.
template<typename Number >
Interval< Number > operator+ (const Number &lhs, const Interval< Number > &rhs)
Operator for the addition of an interval and a number.
template<typename Number >
Interval< Number > operator+ (const Interval< Number > &lhs, const Number &rhs)
Operator for the addition of an interval and a number.
template<typename Number >
Interval< Number > & operator+= (Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the addition of an interval and a number with assignment.
template<typename Number >
Interval< Number > & operator+= (Interval< Number > &lhs, const Number &rhs)
Operator for the addition of an interval and a number with assignment.
template<typename Number >
Interval< Number > operator- (const Interval< Number > &interval)
Unary minus.
template<typename Number >
Interval< Number > operator- (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the subtraction of two intervals.
template<typename Number >
Interval< Number > operator- (const Number &lhs, const Interval< Number > &rhs)
Operator for the subtraction of an interval and a number.
template<typename Number >
Interval< Number > operator- (const Interval< Number > &lhs, const Number &rhs)
Operator for the subtraction of an interval and a number.
template<typename Number >
Interval< Number > & operator-= (Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the subtraction of two intervals with assignment.
template<typename Number >
Interval< Number > & operator-= (Interval< Number > &lhs, const Number &rhs)
Operator for the subtraction of an interval and a number with assignment.
template<typename Number >
Interval< Number > operator* (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the multiplication of two intervals.
template<typename Number >
Interval< Number > operator* (const Number &lhs, const Interval< Number > &rhs)
Operator for the multiplication of an interval and a number.
template<typename Number >
Interval< Number > operator* (const Interval< Number > &lhs, const Number &rhs)
Operator for the multiplication of an interval and a number.
template<typename Number >
Interval< Number > & operator*= (Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the multiplication of an interval and a number with assignment.
template<typename Number >
Interval< Number > & operator*= (Interval< Number > &lhs, const Number &rhs)
Operator for the multiplication of an interval and a number with assignment.
template<typename Number >
Interval< Number > operator/ (const Interval< Number > &lhs, const Number &rhs)
Operator for the division of an interval and a number.
template<typename Number >
Interval< Number > & operator/= (Interval< Number > &lhs, const Number &rhs)
Operator for the division of an interval and a number with assignment.
template<typename Number >
bool operator== (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator!= (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator<= (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator>= (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator< (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator> (const Interval< Number > &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator<= (const Number &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator>= (const Number &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator< (const Number &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool operator> (const Number &lhs, const Interval< Number > &rhs)
Operator for the comparison of two intervals.
template<typename Number >
bool isInteger (const Interval< Number > &n)
template<typename Number >
Interval< Number > div (const Interval< Number > &_lhs, const Interval< Number > &_rhs)
Implements the division which assumes that there is no remainder.
template<typename Number >
Interval< Number > quotient (const Interval< Number > &_lhs, const Interval< Number > &_rhs)
Implements the division with remainder.
template<typename Integer , typename Number >
Integer toInt (const Interval< Number > &_floatInterval)
Casts the Interval to an arbitrary integer type which has a constructor for a native int.
template<typename Number >
Interval< Number > abs (const Interval< Number > &_in)
Method which returns the absolute value of the passed number.
template<typename Number >
Interval< Number > log (const Interval< Number > &_in)
Method which returns the logarithm of the passed number.
template<typename Number >
Interval< Number > sqrt (const Interval< Number > &_in)
Method which returns the square root of the passed number.
template<typename Number >
Interval< Number > pow (const Interval< Number > &_in, uint _exponent)
template<typename Number >
Interval< Number > floor (const Interval< Number > &_in)
Method which returns the next smaller integer of this number or the number itself, if it is already an integer.
template<typename Number >
Interval< Number > ceil (const Interval< Number > &_in)
Method which returns the next larger integer of the passed number or the number itself, if it is already an integer.
std::ostream & operator<< (std::ostream &os, const MapleStream &ms)
std::ostream & operator<< (std::ostream &os, const QEPCADStream &qs)
std::ostream & operator<< (std::ostream &os, const SMTLIBStream &ss)
template<typename Pol , typename... Args>
detail::SMTLIBScriptContainer< Pol > outputSMTLIB (Logic l, std::initializer_list< Formula< Pol >> formulas, Args &&... args)
template<typename... Args>
detail::SMTLIBOutputContainer< Args... > asSMTLIB (Args &&... args)
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::forward_list< T > &l)
Output a std::forward_list with arbitrary content.
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::list< T > &l)
Output a std::list with arbitrary content.
template<typename Key , typename Value , typename Comparator >
std::ostream & operator<< (std::ostream &os, const std::map< Key, Value, Comparator > &m)
Output a std::map with arbitrary content.
template<typename U , typename V >
std::ostream & operator<< (std::ostream &os, const std::pair< U, V > &p)
Output a std::pair with arbitrary content.
template<typename T , typename C >
std::ostream & operator<< (std::ostream &os, const std::set< T, C > &s)
Output a std::set with arbitrary content.
template<std::size_t I = 0, typename... T, typename std::enable_if< I==sizeof...(T), void >::type * = nullptr>
std::ostream & operator<< (std::ostream &os, const std::tuple< T... > &)
Output a std::tuple with arbitrary content.
template<>
cln::cl_RA rationalize< cln::cl_RA > (double n)
template<>
cln::cl_RA rationalize< cln::cl_RA > (float n)
bool sqrt_exact (const cln::cl_RA &a, cln::cl_RA &b)
Calculate the square root of a fraction if possible.
cln::cl_RA sqrt (const cln::cl_RA &a)
cln::cl_RA scaleByPowerOfTwo (const cln::cl_RA &a, int exp)
std::pair< cln::cl_RA, cln::cl_RA > sqrt_safe (const cln::cl_RA &a)
Calculate the square root of a fraction.
std::pair< cln::cl_RA, cln::cl_RA > sqrt_fast (const cln::cl_RA &a)
Compute square root in a fast but less precise way.
std::pair< cln::cl_RA, cln::cl_RA > root_safe (const cln::cl_RA &a, uint n)
template<>
cln::cl_RA rationalize< cln::cl_RA > (const std::string &n)
template<>
cln::cl_I parse< cln::cl_I > (const std::string &n)
template<>
bool try_parse< cln::cl_I > (const std::string &n, cln::cl_I &res)
template<>
cln::cl_RA parse< cln::cl_RA > (const std::string &n)
template<>
bool try_parse< cln::cl_RA > (const std::string &n, cln::cl_RA &res)
std::string toString (const cln::cl_RA &_number, bool _infix)
std::string toString (const cln::cl_I &_number, bool _infix)
bool isZero (const cln::cl_I &n)
bool isZero (const cln::cl_RA &n)
bool isOne (const cln::cl_I &n)
bool isOne (const cln::cl_RA &n)
bool isPositive (const cln::cl_I &n)
bool isPositive (const cln::cl_RA &n)
bool isNegative (const cln::cl_I &n)
bool isNegative (const cln::cl_RA &n)
cln::cl_I getNum (const cln::cl_RA &n)
Extract the numerator from a fraction.
cln::cl_I getDenom (const cln::cl_RA &n)
Extract the denominator from a fraction.
bool isInteger (const cln::cl_I &)
Check if a number is integral.
bool isInteger (const cln::cl_RA &n)
Check if a fraction is integral.
std::size_t bitsize (const cln::cl_I &n)
Get the bit size of the representation of a integer.
std::size_t bitsize (const cln::cl_RA &n)
Get the bit size of the representation of a fraction.
double toDouble (const cln::cl_RA &n)
Converts the given fraction to a double.
double toDouble (const cln::cl_I &n)
Converts the given integer to a double.
template<typename Integer >
Integer toInt (const cln::cl_I &n)
template<typename Integer >
Integer toInt (const cln::cl_RA &n)
template<>
sint toInt< sint > (const cln::cl_I &n)
template<>
uint toInt< uint > (const cln::cl_I &n)
template<typename To , typename From >
To fromInt (const From &n)
template<>
cln::cl_I fromInt (const uint &n)
template<>
cln::cl_I fromInt (const sint &n)
template<>
cln::cl_RA fromInt (const uint &n)
template<>
cln::cl_RA fromInt (const sint &n)
template<>
cln::cl_I toInt< cln::cl_I > (const cln::cl_RA &n)
Convert a fraction to an integer.
template<>
sint toInt< sint > (const cln::cl_RA &n)
template<>
uint toInt< uint > (const cln::cl_RA &n)
cln::cl_LF toLF (const cln::cl_RA &n)
Convert a cln fraction to a cln long float.
template<>
cln::cl_RA rationalize< cln::cl_RA > (int n)
template<>
cln::cl_RA rationalize< cln::cl_RA > (uint n)
template<>
cln::cl_RA rationalize< cln::cl_RA > (sint n)
cln::cl_I abs (const cln::cl_I &n)
Get absolute value of an integer.
cln::cl_RA abs (const cln::cl_RA &n)
Get absolute value of a fraction.
cln::cl_I round (const cln::cl_RA &n)
Round a fraction to next integer.
cln::cl_I round (const cln::cl_I &n)
Round an integer to next integer, that is do nothing.
cln::cl_I floor (const cln::cl_RA &n)
Round down a fraction.
cln::cl_I floor (const cln::cl_I &n)
Round down an integer.
cln::cl_I ceil (const cln::cl_RA &n)
Round up a fraction.
cln::cl_I ceil (const cln::cl_I &n)
Round up an integer.
cln::cl_I gcd (const cln::cl_I &a, const cln::cl_I &b)
Calculate the greatest common divisor of two integers.
cln::cl_I & gcd_assign (cln::cl_I &a, const cln::cl_I &b)
Calculate the greatest common divisor of two integers.
void divide (const cln::cl_I &dividend, const cln::cl_I &divisor, cln::cl_I &quotient, cln::cl_I &remainder)
cln::cl_RA & gcd_assign (cln::cl_RA &a, const cln::cl_RA &b)
Calculate the greatest common divisor of two fractions.
cln::cl_RA gcd (const cln::cl_RA &a, const cln::cl_RA &b)
Calculate the greatest common divisor of two fractions.
cln::cl_I lcm (const cln::cl_I &a, const cln::cl_I &b)
Calculate the least common multiple of two integers.
cln::cl_RA lcm (const cln::cl_RA &a, const cln::cl_RA &b)
Calculate the least common multiple of two fractions.
template<>
cln::cl_RA pow (const cln::cl_RA &basis, std::size_t exp)
Calculate the power of some fraction to some positive integer.
cln::cl_RA log (const cln::cl_RA &n)
cln::cl_RA log10 (const cln::cl_RA &n)
cln::cl_RA sin (const cln::cl_RA &n)
cln::cl_RA cos (const cln::cl_RA &n)
cln::cl_I mod (const cln::cl_I &a, const cln::cl_I &b)
Calculate the remainder of the integer division.
cln::cl_RA div (const cln::cl_RA &a, const cln::cl_RA &b)
Divide two fractions.
cln::cl_I div (const cln::cl_I &a, const cln::cl_I &b)
Divide two integers.
cln::cl_RA & div_assign (cln::cl_RA &a, const cln::cl_RA &b)
Divide two fractions.
cln::cl_I & div_assign (cln::cl_I &a, const cln::cl_I &b)
Divide two integers.
cln::cl_RA quotient (const cln::cl_RA &a, const cln::cl_RA &b)
Divide two fractions.
cln::cl_I quotient (const cln::cl_I &a, const cln::cl_I &b)
Divide two integers.
cln::cl_I remainder (const cln::cl_I &a, const cln::cl_I &b)
Calculate the remainder of the integer division.
cln::cl_I operator/ (const cln::cl_I &a, const cln::cl_I &b)
Divide two integers.
cln::cl_I operator/ (const cln::cl_I &lhs, const int &rhs)
cln::cl_RA reciprocal (const cln::cl_RA &a)
Str2Double_Error str2double (double &d, char const *s)
template<typename Number >
bool AlmostEqual2sComplement (const Number &A, const Number &B, unsigned=128)
template<>
bool AlmostEqual2sComplement< double > (const double &A, const double &B, unsigned maxUlps)
template<typename FloatType >
bool isInteger (const FLOAT_T< FloatType > &in)
template<typename FloatType >
FLOAT_T< FloatType > div (const FLOAT_T< FloatType > &_lhs, const FLOAT_T< FloatType > &_rhs)
Implements the division which assumes that there is no remainder.
template<typename FloatType >
FLOAT_T< FloatType > quotient (const FLOAT_T< FloatType > &_lhs, const FLOAT_T< FloatType > &_rhs)
Implements the division with remainder.
template<typename Integer , typename FloatType >
Integer toInt (const FLOAT_T< FloatType > &_float)
Casts the FLOAT_T to an arbitrary integer type which has a constructor for a native int.
template<typename FloatType >
double toDouble (const FLOAT_T< FloatType > &_float)
template<typename FloatType >
FLOAT_T< FloatType > abs (const FLOAT_T< FloatType > &_in)
Method which returns the absolute value of the passed number.
template<typename FloatType >
FLOAT_T< FloatType > log (const FLOAT_T< FloatType > &_in)
Method which returns the logarithm of the passed number.
template<typename FloatType >
FLOAT_T< FloatType > sqrt (const FLOAT_T< FloatType > &_in)
Method which returns the square root of the passed number.
template<typename FloatType >
std::pair< FLOAT_T< FloatType >, FLOAT_T< FloatType > > sqrt_safe (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
FLOAT_T< FloatType > pow (const FLOAT_T< FloatType > &_in, size_t _exp)
template<typename FloatType >
FLOAT_T< FloatType > sin (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
FLOAT_T< FloatType > cos (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
FLOAT_T< FloatType > asin (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
FLOAT_T< FloatType > acos (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
FLOAT_T< FloatType > atan (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
FLOAT_T< FloatType > floor (const FLOAT_T< FloatType > &_in)
Method which returns the next smaller integer of this number or the number itself, if it is already an integer.
template<typename FloatType >
FLOAT_T< FloatType > ceil (const FLOAT_T< FloatType > &_in)
Method which returns the next larger integer of the passed number or the number itself, if it is already an integer.
template<>
FLOAT_T< double > rationalize< FLOAT_T< double > > (double n)
template<>
FLOAT_T< float > rationalize< FLOAT_T< float > > (float n)
template<>
FLOAT_T< mpq_class > rationalize< FLOAT_T< mpq_class > > (double n)
mpz_class getDenom (const FLOAT_T< mpq_class > &_in)
Implicitly converts the number to a rational and returns the denominator.
mpz_class getNum (const FLOAT_T< mpq_class > &_in)
Implicitly converts the number to a rational and returns the nominator.
template<typename FloatType >
bool isZero (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
bool isInfinity (const FLOAT_T< FloatType > &_in)
template<typename FloatType >
bool isNan (const FLOAT_T< FloatType > &_in)
template<>
bool AlmostEqual2sComplement< FLOAT_T< double > > (const FLOAT_T< double > &A, const FLOAT_T< double > &B, unsigned maxUlps)
bool sqrt_exact (const mpq_class &a, mpq_class &b)
Calculate the square root of a fraction if possible.
mpq_class sqrt (const mpq_class &a)
std::pair< mpq_class, mpq_class > sqrt_safe (const mpq_class &a)
std::pair< mpq_class, mpq_class > root_safe (const mpq_class &a, uint n)
Calculate the nth root of a fraction.
std::pair< mpq_class, mpq_class > sqrt_fast (const mpq_class &a)
Compute square root in a fast but less precise way.
template<>
mpq_class rationalize< mpq_class > (const std::string &n)
template<>
mpz_class parse< mpz_class > (const std::string &n)
template<>
bool try_parse< mpz_class > (const std::string &n, mpz_class &res)
template<>
mpq_class parse< mpq_class > (const std::string &n)
template<>
bool try_parse< mpq_class > (const std::string &n, mpq_class &res)
std::string toString (const mpq_class &_number, bool _infix)
std::string toString (const mpz_class &_number, bool _infix)
bool isZero (const mpz_class &n)
Informational functions.
bool isZero (const mpq_class &n)
bool isOne (const mpz_class &n)
bool isOne (const mpq_class &n)
bool isPositive (const mpz_class &n)
bool isPositive (const mpq_class &n)
bool isNegative (const mpz_class &n)
bool isNegative (const mpq_class &n)
mpz_class getNum (const mpq_class &n)
mpz_class getNum (const mpz_class &n)
mpz_class getDenom (const mpq_class &n)
mpz_class getDenom (const mpz_class &n)
bool isInteger (const mpq_class &n)
bool isInteger (const mpz_class &)
std::size_t bitsize (const mpz_class &n)
Get the bit size of the representation of a integer.
std::size_t bitsize (const mpq_class &n)
Get the bit size of the representation of a fraction.
double toDouble (const mpq_class &n)
Conversion functions.
double toDouble (const mpz_class &n)
template<typename Integer >
Integer toInt (const mpz_class &n)
template<>
sint toInt< sint > (const mpz_class &n)
template<>
uint toInt< uint > (const mpz_class &n)
template<typename Integer >
Integer toInt (const mpq_class &n)
template<>
mpz_class toInt< mpz_class > (const mpq_class &n)
Convert a fraction to an integer.
template<>
mpz_class fromInt (const uint &n)
template<>
mpz_class fromInt (const sint &n)
template<>
mpq_class fromInt (const uint &n)
template<>
mpq_class fromInt (const sint &n)
template<>
sint toInt< sint > (const mpq_class &n)
Convert a fraction to an unsigned.
template<>
uint toInt< uint > (const mpq_class &n)
template<typename T >
T rationalize (const PreventConversion< mpq_class > &)
template<>
mpq_class rationalize< mpq_class > (float n)
template<>
mpq_class rationalize< mpq_class > (double n)
template<>
mpq_class rationalize< mpq_class > (int n)
template<>
mpq_class rationalize< mpq_class > (uint n)
template<>
mpq_class rationalize< mpq_class > (sint n)
template<>
mpq_class rationalize< mpq_class > (const PreventConversion< mpq_class > &n)
mpz_class abs (const mpz_class &n)
Basic Operators.
mpq_class abs (const mpq_class &n)
mpz_class round (const mpq_class &n)
mpz_class round (const mpz_class &n)
mpz_class floor (const mpq_class &n)
mpz_class floor (const mpz_class &n)
mpz_class ceil (const mpq_class &n)
mpz_class ceil (const mpz_class &n)
mpz_class gcd (const mpz_class &a, const mpz_class &b)
mpz_class lcm (const mpz_class &a, const mpz_class &b)
mpq_class gcd (const mpq_class &a, const mpq_class &b)
mpz_class & gcd_assign (mpz_class &a, const mpz_class &b)
Calculate the greatest common divisor of two integers.
mpq_class & gcd_assign (mpq_class &a, const mpq_class &b)
Calculate the greatest common divisor of two integers.
mpq_class lcm (const mpq_class &a, const mpq_class &b)
mpq_class log (const mpq_class &n)
mpq_class log10 (const mpq_class &n)
mpq_class sin (const mpq_class &n)
mpq_class cos (const mpq_class &n)
template<>
mpz_class pow (const mpz_class &basis, std::size_t exp)
template<>
mpq_class pow (const mpq_class &basis, std::size_t exp)
mpz_class mod (const mpz_class &n, const mpz_class &m)
mpz_class remainder (const mpz_class &n, const mpz_class &m)
mpz_class quotient (const mpz_class &n, const mpz_class &d)
mpz_class operator/ (const mpz_class &n, const mpz_class &d)
mpq_class quotient (const mpq_class &n, const mpq_class &d)
mpq_class operator/ (const mpq_class &n, const mpq_class &d)
void divide (const mpz_class &dividend, const mpz_class &divisor, mpz_class &quotient, mpz_class &remainder)
mpq_class div (const mpq_class &a, const mpq_class &b)
Divide two fractions.
mpz_class div (const mpz_class &a, const mpz_class &b)
Divide two integers.
mpz_class & div_assign (mpz_class &a, const mpz_class &b)
Divide two integers.
mpq_class & div_assign (mpq_class &a, const mpq_class &b)
Divide two integers.
mpq_class reciprocal (const mpq_class &a)
mpq_class operator* (const mpq_class &lhs, const mpq_class &rhs)
bool isZero (sint n)
Informational functions.
bool isZero (double n)
bool isOne (sint n)
bool isPositive (sint n)
bool isNegative (sint n)
bool isNaN (double d)
bool isInf (double d)
bool isNumber (double d)
bool isInteger (double d)
bool isInteger (sint)
bool isNegative (double d)
bool isPositive (double d)
std::size_t bitsize (unsigned)
double toDouble (sint n)
Conversion functions.
double toDouble (double n)
template<typename Integer >
Integer toInt (double n)
template<>
sint toInt< sint > (double n)
template<>
uint toInt< uint > (double n)
template<>
double rationalize (double n)
template<typename T >
std::enable_if< std::is_arithmetic< typename remove_all< T >::type >::value, std::string >::type toString (const T &n, bool)
double floor (double n)
Basic Operators.
double ceil (double n)
double abs (double n)
uint mod (uint n, uint m)
sint mod (sint n, sint m)
sint remainder (sint n, sint m)
sint div (sint n, sint m)
sint quotient (sint n, sint m)
void divide (sint dividend, sint divisor, sint &quo, sint &rem)
double sin (double in)
double cos (double in)
double acos (double in)
double sqrt (double in)
std::pair< double, double > sqrt_safe (double in)
double pow (double in, uint exp)
double log (double in)
double log10 (double in)
template<typename Number >
Number highestPower (const Number &n)
Returns the highest power of two below n.
mpz_manager< true > & mpzmanager ()
mpq_manager< true > & mpqmanager ()
bool isZero (const rational &n)
bool isOne (const rational &n)
std::string toString (const rational &_number, bool _infix)
template<>
cln::cl_I convert< cln::cl_I, cln::cl_I > (const cln::cl_I &n)
template<>
cln::cl_RA convert< cln::cl_RA, cln::cl_RA > (const cln::cl_RA &n)
template<>
mpz_class convert< cln::cl_I, mpz_class > (const cln::cl_I &n)
template<>
mpq_class convert< cln::cl_RA, mpq_class > (const cln::cl_RA &n)
template<>
mpz_class convert< mpz_class, mpz_class > (const mpz_class &n)
template<>
mpq_class convert< mpq_class, mpq_class > (const mpq_class &n)
template<>
cln::cl_I convert< mpz_class, cln::cl_I > (const mpz_class &n)
template<>
cln::cl_RA convert< mpq_class, cln::cl_RA > (const mpq_class &n)
template<typename From , typename To , carl::DisableIf< std::is_same< From, To > > >
To convert (const From &)
template<typename Rational >
static double roundDown (const Rational &o, bool overapproximate=false)
Returns a down-rounded representation of the given numeric.
template<typename Rational >
static double roundUp (const Rational &o, bool overapproximate=false)
Returns a up-rounded representation of the given numeric.
template<>
mpq_class convert< double, mpq_class > (const double &n)
template<>
double convert< mpq_class, double > (const mpq_class &n)
template<>
FLOAT_T< mpq_class > convert< double, FLOAT_T< mpq_class > > (const double &n)
template<>
double convert< FLOAT_T< mpq_class >, double > (const FLOAT_T< mpq_class > &n)
template<>
FLOAT_T< double > convert< mpq_class, FLOAT_T< double > > (const mpq_class &n)
template<>
mpq_class convert< FLOAT_T< double >, mpq_class > (const FLOAT_T< double > &n)
template<>
mpq_class convert< FLOAT_T< mpq_class >, mpq_class > (const FLOAT_T< mpq_class > &n)
template<>
FLOAT_T< mpq_class > convert< mpq_class, FLOAT_T< mpq_class > > (const mpq_class &n)
template<>
double convert< FLOAT_T< double >, double > (const FLOAT_T< double > &n)
template<>
FLOAT_T< double > convert< double, FLOAT_T< double > > (const double &n)
template<typename TypeSelector , typename Types , typename... Args>
auto createFunctionSelector (Args &&... args)
template<typename IntegerT >
static bool isZero (const GFNumber< IntegerT > &_in)
template<typename IntegerT >
static bool isOne (const GFNumber< IntegerT > &_in)
template<typename IntegerT >
GFNumber< IntegerT > quotient (const GFNumber< IntegerT > &lhs, const GFNumber< IntegerT > &rhs)
template<typename IntegerT >
GFNumber< IntegerT > abs (const GFNumber< IntegerT > &n)
template<typename IntegerT >
bool isInteger (const GFNumber< IntegerT > &)
template<typename IntegerType >
std::string toString (const GFNumber< IntegerType > &_number, bool)
Creates the string representation to the given galois field number.
template<typename T , typename N >
std::ostream & operator<< (std::ostream &os, const BaseNumber< T, N > &n)
template<typename T >
Numeric< T > & div_assign (Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > & gcd_assign (Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > div (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > abs (const Numeric< T > &)
template<typename T >
Numeric< T > lcm (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > gcd (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > operator+ (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > operator- (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > operator* (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > operator/ (const Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > & operator+= (Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > & operator-= (Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > & operator*= (Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > & operator/= (Numeric< T > &, const Numeric< T > &)
template<typename T >
Numeric< T > operator- (const Numeric< T > &)
template<typename T >
Numeric< T > & operator++ (Numeric< T > &)
template<typename T >
Numeric< T > & operator-- (Numeric< T > &)
template<typename T >
std::ostream & operator<< (std::ostream &, const Numeric< T > &)
template<typename T >
bool isInteger (const Numeric< T > &_value)
template<typename Integer , typename T >
Integer toInt (const Numeric< T > &n)
template<typename T , EnableIf< has_isZero< T >> >
bool isZero (const T &t)
template<typename T , EnableIf< has_isOne< T >> >
bool isOne (const T &t)
template<typename T , EnableIf< has_isPositive< T >> >
bool isPositive (const T &t)
template<typename T , EnableIf< has_isNegative< T >> >
bool isNegative (const T &t)
template<typename T >
T pow (const T &basis, std::size_t exp)
Implements a fast exponentiation on an arbitrary type T.
template<typename T >
void pow_assign (T &t, std::size_t exp)
Implements a fast exponentiation on an arbitrary type T.
template<typename T >
T rationalize (double n)
template<typename T >
T rationalize (float n)
template<typename T >
T rationalize (int n)
template<typename T >
T rationalize (sint n)
template<typename T >
T rationalize (uint n)
template<typename T >
T rationalize (const std::string &n)
template<typename Number >
int toInt (const Number &n)
template<typename T >
T parse (const std::string &n)
template<typename T >
bool try_parse (const std::string &n, T &res)
template<typename T , typename T2 >
bool fitsWithin (const T2 &t)
template<typename N >
std::ostream & operator<< (std::ostream &os, const SignDetermination< N > &rhs)
template<typename Coeff >
std::vector< Coeff > newtonSums (const std::vector< Coeff > &newtonSums)
template<typename Coeff >
void printMatrix (const CoeffMatrix< Coeff > &m)
template<typename Coeff >
std::vector< Coeff > charPol (const CoeffMatrix< Coeff > &m)
template<typename C >
std::ostream & operator<< (std::ostream &o, const MultiplicationTable< C > &table)
template<typename Number >
int multivariateTarskiQuery (const MultivariatePolynomial< Number > &Q, const MultiplicationTable< Number > &table)
template<typename Number >
Sign signAtMinusInf (const UnivariatePolynomial< Number > &p)
template<typename Number >
Sign signAtPlusInf (const UnivariatePolynomial< Number > &p)
template<typename Number >
int univariateTarskiQuery (const UnivariatePolynomial< Number > &p, const UnivariatePolynomial< Number > &q, const UnivariatePolynomial< Number > &der_q)
template<typename Number >
int univariateTarskiQuery (const UnivariatePolynomial< Number > &p, const UnivariatePolynomial< Number > &q)
template<typename N >
bool operator< (const ThomEncoding< N > &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator<= (const ThomEncoding< N > &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator> (const ThomEncoding< N > &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator>= (const ThomEncoding< N > &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator== (const ThomEncoding< N > &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator!= (const ThomEncoding< N > &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator< (const ThomEncoding< N > &lhs, const N &rhs)
template<typename N >
bool operator<= (const ThomEncoding< N > &lhs, const N &rhs)
template<typename N >
bool operator> (const ThomEncoding< N > &lhs, const N &rhs)
template<typename N >
bool operator>= (const ThomEncoding< N > &lhs, const N &rhs)
template<typename N >
bool operator== (const ThomEncoding< N > &lhs, const N &rhs)
template<typename N >
bool operator!= (const ThomEncoding< N > &lhs, const N &rhs)
template<typename N >
bool operator< (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator<= (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator> (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator>= (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator== (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
bool operator!= (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
ThomEncoding< N > operator+ (const N &lhs, const ThomEncoding< N > &rhs)
template<typename N >
std::ostream & operator<< (std::ostream &os, const ThomEncoding< N > &rhs)
template<typename Number >
RealAlgebraicNumber< Number > evaluateTE (const MultivariatePolynomial< Number > &p, std::map< Variable, RealAlgebraicNumber< Number >> &m)
template<typename Number >
std::list< ThomEncoding< Number > > realRootsThom (const MultivariatePolynomial< Number > &p, Variable::Arg mainVar, std::shared_ptr< ThomEncoding< Number >> point_ptr, const Interval< Number > &interval=Interval< Number >::unboundedInterval())
template<typename Number >
std::list< ThomEncoding< Number > > realRootsThom (const MultivariatePolynomial< Number > &p, Variable::Arg mainVar, const std::map< Variable, ThomEncoding< Number >> &m={}, const Interval< Number > &interval=Interval< Number >::unboundedInterval())
template<typename Coeff , typename Number >
std::list< RealAlgebraicNumber< Number > > realRootsThom (const UnivariatePolynomial< Coeff > &p, const std::map< Variable, RealAlgebraicNumber< Number >> &m, const Interval< Number > &interval)
template<typename Number >
std::list< MultivariatePolynomial< Number > > der (const MultivariatePolynomial< Number > &p, Variable::Arg var, uint from, uint upto)
BitVector operator| (const BitVector &lhs, const BitVector &rhs)
bool operator== (const BitVector &lhs, const BitVector &rhs)
bool operator== (const BitVector::forward_iterator &fi1, const BitVector::forward_iterator &fi2)
std::ostream & operator<< (std::ostream &os, const BitVector &bv)
template<typename T , class I >
bool operator== (const TypeInfoPair< T, I > &_tipA, const TypeInfoPair< T, I > &_tipB)
template<typename T >
bool returnFalse (const T &, const T &)
template<typename T >
void doNothing (const T &, const T &)
template<typename TT >
std::ostream & operator<< (std::ostream &os, const tree< TT > &tree)
void printCMakeOptions (std::ostream &os)
template<class E , bool FI>
std::ostream & operator<< (std::ostream &out, const CompactTree< E, FI > &tree)
template<typename TT >
std::ostream & operator<< (std::ostream &os, const Covering< TT > &ri)
void printStacktrace (bool interaction=false)
Uses GDB to print a stack trace.
std::string demangle (const char *name)
std::string callingFunction ()
static void handle_signal (int signal)
Actual signal handler.
static bool install_signal_handler () noexcept
Installs the signal handler.
template<typename T >
std::string typeString ()
void hash_combine (std::size_t &seed, std::size_t value)
Add a value to the given hash seed.
template<typename T >
void hash_add (std::size_t &seed, const T &value)
Add hash of the given value to the hash seed.
template<>
void hash_add (std::size_t &seed, const std::size_t &value)
Add hash of the given value to the hash seed.
template<typename First , typename... Tail>
void hash_add (std::size_t &seed, const First &value, Tail &&... tail)
Variadic version of hash_add to add an arbitrary number of values to the seed.
template<typename T1 , typename T2 >
void hash_add (std::size_t &seed, const std::pair< T1, T2 > &p)
Add hash of both elements of a std::pair to the seed.
template<typename T >
void hash_add (std::size_t &seed, const std::vector< T > &v)
Add hash of all elements of a std::vector to the seed.
template<typename... Args>
std::size_t hash_all (Args &&... args)
Hashes an arbitrary number of values.
has_method_struct (normalize) has_method_struct(isOne) has_method_struct(isZero) has_method_struct(isNegative) has_method_struct(isPositive) template< template< typename... > class Template
std::ostream & operator<< (std::ostream &os, const Timer &t)
Streaming operator for a Timer.
std::ostream & operator<< (std::ostream &os, const TimingCollector &tc)
template<typename Tuple1 , typename Tuple2 >
auto tuple_cat (Tuple1 &&t1, Tuple2 &&t2)
template<typename Tuple >
auto tuple_tail (Tuple &&t)
Returns a new tuple containing everything but the first element.
template<typename F , typename Tuple >
auto tuple_apply (F &&f, Tuple &&t)
Invokes a callable object f on a tuple of arguments.
template<typename F , typename Tuple >
auto tuple_foreach (F &&f, Tuple &&t)
Invokes a callable object f on every element of a tuple and returns a tuple containing the results.
template<typename Tuple , typename T , typename F >
T tuple_accumulate (Tuple &&t, T &&init, F &&f)
Implements a functional fold (similar to std::accumulate) for std::tuple.
template<typename T , typename Variant >
bool variant_is_type (const Variant &variant) noexcept
Checks whether a variant contains a value of a fiven type.
template<typename Target , typename... Args>
Target variant_extend (const boost::variant< Args... > &variant)
template<typename... T>
std::size_t variant_hash (const boost::variant< T... > &value)
template<typename T >
void vector_concat (std::vector< T > &result, const std::vector< std::vector< T >> &input)
template<typename T >
std::vector< T > vector_concat (const std::vector< std::vector< T >> &input)
template<typename T1 , typename T2 >
std::vector< std::pair< T1, T2 > > vector_zip (const std::vector< T1 > &v1, const std::vector< T2 > &v2)
template<typename Result , typename Input , typename... Inputs>
void vector_zip_tuple (Result &res, const Input &input, const Inputs &... inputs)
Equality comparison operators
template<typename P >
bool operator== (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the two arguments are equal.
template<typename P >
bool operator== (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Checks if the two arguments are equal.
template<typename P >
bool operator== (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P , DisableIf< std::is_integral< C >> = dummy>
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, int rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const UnivariatePolynomial< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const UnivariatePolynomial< MultivariatePolynomial< C >> &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< MultivariatePolynomial< C >> &rhs)
Checks if the two arguments are equal.
Inequality comparison operators
template<typename P >
bool operator!= (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the two arguments are not equal.
template<typename P >
bool operator!= (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Checks if the two arguments are not equal.
template<typename P >
bool operator!= (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const UnivariatePolynomial< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const UnivariatePolynomial< MultivariatePolynomial< C >> &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are not equal.
template<typename C , typename O , typename P >
bool operator!= (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< MultivariatePolynomial< C >> &rhs)
Checks if the two arguments are not equal.
Less than comparison operators
template<typename P >
bool operator< (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is less than the second.
template<typename P >
bool operator< (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Checks if the first arguments is less than the second.
template<typename P >
bool operator< (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less than the second.
template<typename C , typename O , typename P >
bool operator< (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less than the second.
Less or equal comparison operators
template<typename P >
bool operator<= (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is less or equal than the second.
template<typename P >
bool operator<= (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Checks if the first arguments is less or equal than the second.
template<typename P >
bool operator<= (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less or equal than the second.
template<typename C , typename O , typename P >
bool operator<= (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is less or equal than the second.
Greater than comparison operators
template<typename P >
bool operator> (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is greater than the second.
template<typename P >
bool operator> (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Checks if the first arguments is greater than the second.
template<typename P >
bool operator> (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater than the second.
template<typename C , typename O , typename P >
bool operator> (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater than the second.
Greater or equal comparison operators
template<typename P >
bool operator>= (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is greater or equal than the second.
template<typename P >
bool operator>= (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Checks if the first arguments is greater or equal than the second.
template<typename P >
bool operator>= (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater or equal than the second.
template<typename C , typename O , typename P >
bool operator>= (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the first arguments is greater or equal than the second.
Addition operators
template<typename P >
FactorizedPolynomial< P > operator+ (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Performs an addition involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator+ (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Performs an addition involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator+ (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const Term< C > &lhs, const Term< C > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const Term< C > &lhs, const Monomial::Arg &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const Term< C > &lhs, Variable::Arg rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator+ (const Term< C > &lhs, const C &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const Monomial::Arg &lhs, const Term< C > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const Monomial::Arg &lhs, Variable::Arg rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator+ (const Monomial::Arg &lhs, const C &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (Variable::Arg lhs, const Term< C > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (Variable::Arg lhs, const Monomial::Arg &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (Variable::Arg lhs, Variable::Arg rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator+ (Variable::Arg lhs, const C &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const C &lhs, const Term< C > &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator+ (const C &lhs, const Monomial::Arg &rhs)
Performs an addition involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator+ (const C &lhs, Variable::Arg rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< C > &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const UnivariatePolynomial< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< MultivariatePolynomial< C >> &rhs)
Performs an addition involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator+ (const UnivariatePolynomial< MultivariatePolynomial< C >> &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an addition involving a polynomial.
Subtraction operators
template<typename P >
FactorizedPolynomial< P > operator- (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Performs an subtraction involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator- (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Performs an subtraction involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator- (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (const Term< C > &lhs, const Term< C > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (const Term< C > &lhs, const Monomial::Arg &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (const Term< C > &lhs, Variable::Arg rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const Term< C > &lhs, const C &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (const Monomial::Arg &lhs, const Term< C > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (const Monomial::Arg &lhs, Variable::Arg rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const Monomial::Arg &lhs, const C &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator- (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (Variable::Arg lhs, const Term< C > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (Variable::Arg lhs, const Monomial::Arg &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate >
MultivariatePolynomial< C, O, P > operator- (Variable::Arg lhs, Variable::Arg rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (Variable::Arg lhs, const C &rhs)
Performs an subtraction involving a polynomial.
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const C &lhs, const Term< C > &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const C &lhs, const Monomial::Arg &rhs)
Performs an subtraction involving a polynomial.
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator- (const C &lhs, Variable::Arg rhs)
Performs an subtraction involving a polynomial.
Multiplication operators
template<typename P >
FactorizedPolynomial< P > operator* (const FactorizedPolynomial< P > &_lhs, const FactorizedPolynomial< P > &_rhs)
Perform a multiplication involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator* (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Perform a multiplication involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator* (const typename FactorizedPolynomial< P >::CoeffType &_lhs, const FactorizedPolynomial< P > &_rhs)
Perform a multiplication involving a polynomial.
template<typename P >
FactorizedPolynomial< P > operator/ (const FactorizedPolynomial< P > &_lhs, const typename FactorizedPolynomial< P >::CoeffType &_rhs)
Perform a multiplication involving a polynomial.
Monomial::Arg operator* (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Perform a multiplication involving a monomial.
Monomial::Arg operator* (const Monomial::Arg &lhs, Variable rhs)
Perform a multiplication involving a monomial.
Monomial::Arg operator* (Variable lhs, const Monomial::Arg &rhs)
Perform a multiplication involving a monomial.
Monomial::Arg operator* (Variable lhs, Variable rhs)
Perform a multiplication involving a monomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (const MultivariatePolynomial< C, O, P > &lhs, const Term< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (const MultivariatePolynomial< C, O, P > &lhs, const Monomial::Arg &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (const MultivariatePolynomial< C, O, P > &lhs, Variable::Arg rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator* (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (const Term< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (const Monomial::Arg &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator* (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator* (const C &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
const MultivariatePolynomial< C, O, P > operator* (const UnivariatePolynomial< C > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
const MultivariatePolynomial< C, O, P > operator* (const MultivariatePolynomial< C, O, P > &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename Coeff >
Term< Coeff > operator* (Term< Coeff > lhs, const Term< Coeff > &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (Term< Coeff > lhs, const Monomial::Arg &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (Term< Coeff > lhs, Variable rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (Term< Coeff > lhs, const Coeff &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Perform a multiplication involving a term.
template<typename Coeff , EnableIf< carl::is_number< Coeff >> = dummy>
Term< Coeff > operator* (const Monomial::Arg &lhs, const Coeff &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (Variable lhs, const Term< Coeff > &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (Variable lhs, const Coeff &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (const Coeff &lhs, const Term< Coeff > &rhs)
Perform a multiplication involving a term.
template<typename Coeff , EnableIf< carl::is_number< Coeff >> = dummy>
Term< Coeff > operator* (const Coeff &lhs, const Monomial::Arg &rhs)
Perform a multiplication involving a term.
template<typename Coeff >
Term< Coeff > operator* (const Coeff &lhs, Variable rhs)
Perform a multiplication involving a term.
template<typename Coeff , EnableIf< carl::is_subset_of_rationals< Coeff >> = dummy>
Term< Coeff > operator/ (const Term< Coeff > &lhs, const Coeff &rhs)
Perform a multiplication involving a term.
template<typename Coeff , EnableIf< carl::is_subset_of_rationals< Coeff >> = dummy>
Term< Coeff > operator/ (const Monomial::Arg &lhs, const Coeff &rhs)
Perform a multiplication involving a term.
template<typename Coeff , EnableIf< carl::is_subset_of_rationals< Coeff >> = dummy>
Term< Coeff > operator/ (Variable &lhs, const Coeff &rhs)
Perform a multiplication involving a term.
Comparison operators
bool operator== (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator== (const Monomial::Arg &lhs, Variable rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator== (Variable lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator!= (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator!= (const Monomial::Arg &lhs, Variable rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator!= (Variable lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator< (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator< (const Monomial::Arg &lhs, Variable rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator< (Variable lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator<= (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator<= (const Monomial::Arg &lhs, Variable rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator<= (Variable lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator> (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator> (const Monomial::Arg &lhs, Variable rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator> (Variable lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator>= (const Monomial::Arg &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator>= (const Monomial::Arg &lhs, Variable rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
bool operator>= (Variable lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
template<typename Coeff >
bool operator== (const Term< Coeff > &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator== (const Term< Coeff > &lhs, const Monomial &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator== (const Term< Coeff > &lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator== (const Term< Coeff > &lhs, const Coeff &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator== (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator== (Variable lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator== (const Coeff &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (const Term< Coeff > &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (const Term< Coeff > &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (const Term< Coeff > &lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (const Term< Coeff > &lhs, const Coeff &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (Variable lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator!= (const Coeff &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (const Term< Coeff > &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (const Term< Coeff > &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (const Term< Coeff > &lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (const Term< Coeff > &lhs, const Coeff &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (Variable lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator< (const Coeff &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (const Term< Coeff > &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (const Term< Coeff > &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (const Term< Coeff > &lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (const Term< Coeff > &lhs, const Coeff &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (Variable lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator<= (const Coeff &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (const Term< Coeff > &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (const Term< Coeff > &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (const Term< Coeff > &lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (const Term< Coeff > &lhs, const Coeff &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (Variable lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator> (const Coeff &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (const Term< Coeff > &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (const Term< Coeff > &lhs, const Monomial::Arg &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (const Term< Coeff > &lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (const Term< Coeff > &lhs, const Coeff &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (const Monomial::Arg &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (Variable lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
template<typename Coeff >
bool operator>= (const Coeff &lhs, const Term< Coeff > &rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Division operators
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy>
MultivariatePolynomial< C, O, P > operator/ (const MultivariatePolynomial< C, O, P > &lhs, const C &rhs)
Perform a division involving a polynomial.
In-place multiplication operators
template<typename Coeff >
Term< Coeff > & operator*= (Term< Coeff > &lhs, const Coeff &rhs)
Multiply a term with something and return the changed term.
template<typename Coeff >
Term< Coeff > & operator*= (Term< Coeff > &lhs, Variable rhs)
Multiply a term with something and return the changed term.
template<typename Coeff >
Term< Coeff > & operator*= (Term< Coeff > &lhs, const Monomial::Arg &rhs)
Multiply a term with something and return the changed term.
template<typename Coeff >
Term< Coeff > & operator*= (Term< Coeff > &lhs, const Term< Coeff > &rhs)
Multiply a term with something and return the changed term.
Variables
static int initvariable = initialize()
Call to initialize.
static std::map< Variable, Interval< double > > mMap = {{ Variable::NO_VARIABLE , Interval<double>(0)}}
static constexpr std::size_t CONDITION_SIZE = 64
static constexpr Condition PROP_TRUE = Condition()
static constexpr Condition PROP_IS_IN_NNF = Condition(0)
static constexpr Condition PROP_IS_IN_CNF = Condition(1)
static constexpr Condition PROP_IS_PURE_CONJUNCTION = Condition(2)
static constexpr Condition PROP_IS_A_CLAUSE = Condition(3)
static constexpr Condition PROP_IS_A_LITERAL = Condition(4)
static constexpr Condition PROP_IS_AN_ATOM = Condition(5)
static constexpr Condition PROP_IS_LITERAL_CONJUNCTION = Condition(6)
static const Condition STRONG_CONDITIONS
static constexpr Condition PROP_CONTAINS_EQUATION = Condition(16)
static constexpr Condition PROP_CONTAINS_INEQUALITY = Condition(17)
static constexpr Condition PROP_CONTAINS_STRICT_INEQUALITY = Condition(18)
static constexpr Condition PROP_CONTAINS_LINEAR_POLYNOMIAL = Condition(19)
static constexpr Condition PROP_CONTAINS_NONLINEAR_POLYNOMIAL = Condition(20)
static constexpr Condition PROP_CONTAINS_MULTIVARIATE_POLYNOMIAL = Condition(21)
static constexpr Condition PROP_CONTAINS_BOOLEAN = Condition(22)
static constexpr Condition PROP_CONTAINS_INTEGER_VALUED_VARS = Condition(23)
static constexpr Condition PROP_CONTAINS_REAL_VALUED_VARS = Condition(24)
static constexpr Condition PROP_CONTAINS_UNINTERPRETED_EQUATIONS = Condition(25)
static constexpr Condition PROP_CONTAINS_BITVECTOR = Condition(26)
static constexpr Condition PROP_CONTAINS_PSEUDOBOOLEAN = Condition(27)
static constexpr Condition PROP_VARIABLE_DEGREE_GREATER_THAN_TWO = Condition(28)
static constexpr Condition PROP_VARIABLE_DEGREE_GREATER_THAN_THREE = Condition(29)
static constexpr Condition PROP_VARIABLE_DEGREE_GREATER_THAN_FOUR = Condition(30)
static constexpr Condition PROP_CONTAINS_WEAK_INEQUALITY = Condition(31)
static const Condition WEAK_CONDITIONS
const signed A_IFF_B = 2
const signed A_IMPLIES_B = 1
const signed B_IMPLIES_A = -1
const signed NOT__A_AND_B = -2
const signed A_AND_B__IFF_C = -3
const signed A_XOR_B = -4
static const cln::cl_RA ONE_DIVIDED_BY_10_TO_THE_POWER_OF_23 = cln::cl_RA(1)/cln::expt(cln::cl_RA(10), 23)
static const cln::cl_RA ONE_DIVIDED_BY_10_TO_THE_POWER_OF_52 = cln::cl_RA(1)/cln::expt(cln::cl_RA(10), 52)
const ContentType HIGHTEST_INTEGER_VALUE = (std::numeric_limits<ContentType>::max() >> ((std::numeric_limits<ContentType>::digits/2)+1))+1
constexpr unsigned sizeOfUnsigned = sizeof(unsigned)
static constexpr uint MAX_DEGREE_FOR_FACTORIZATION = 6
static constexpr uint MIN_DEGREE_FOR_FACTORIZATION = 1
static constexpr uint MAX_DIMENSION_FOR_FACTORIZATION = 6
static constexpr uint MAX_NUMBER_OF_MONOMIALS_FOR_FACTORIZATION = 10
static constexpr bool FULL_EFFORT_FOR_DEFINITENESS_CHECK = false
std::string last_assertion_string
Stores a textual representation of the last assertion that was registered via REGISTER_ASSERT.
int last_assertion_code = 23
Stores an integer representation of the last assertion that was registered via REGISTER_ASSERT.
static bool signal_installed = install_signal_handler()
Static variable that ensures that install_signal_handler is called.
const dtl::enabled dummy = {}
Detailed Description
carl is the main namespace for the library.
Common.h.
Class to create a square root expression object.
This file provides mechanisms to substitute a model into an expression and to evaluate an expression over a model.
Condition.h.
Everything included in this library is found in this namespace.
Todo:
Fix bug in CAD concerning CAD::removePolynomial().
Author
Florian Corziliuscorzi.nosp@m.lius.nosp@m.@cs.r.nosp@m.wth-.nosp@m.aache.nosp@m.n.de
Since
2012-06-11
Version
2014-10-30
Author
Florian Corzilius
Since
2011-05-26
Version
2013-10-22
Author
Florian Corziliuscorzi.nosp@m.lius.nosp@m.@cs.r.nosp@m.wth-.nosp@m.aache.nosp@m.n.de
Since
2013-10-07
Version
2014-10-30
Typedef Documentation
BaseIteratorType
using carl::BaseIteratorType = typedef spirit::istream_iterator
Definition at line 21 of file OPBImporter.cpp.
Bool
template<bool B, typename... T> using carl::Bool = typedef typename dependent_bool_type<B, T...>::type
Definition at line 24 of file SFINAE.h.
Coeff
template<typename P > using carl::Coeff = typedef typename UnderlyingNumberType<P>::type
Definition at line 20 of file FactorizedPolynomial.h.
CoeffMatrix
template<typename Coeff > using carl::CoeffMatrix = typedef Eigen::Matrix<Coeff, Eigen::Dynamic, Eigen::Dynamic>
Definition at line 37 of file CharPol.h.
Conditional
template<bool If, typename Then , typename Else > using carl::Conditional = typedef typename std::conditional<If, Then, Else>::type
Definition at line 19 of file SFINAE.h.
Constraints
template<typename Poly > using carl::Constraints = typedef std::set<Constraint<Poly>, carl::less<Constraint<Poly>, false> >
Definition at line 38 of file Constraint.h.
ContentType
using carl::ContentType = typedef sint
Definition at line 21 of file Numeric.h.
CritPairs
typedef CriticalPairs<Heap, CriticalPairConfiguration<GrLexOrdering> > carl::CritPairs
Definition at line 134 of file CriticalPairs.h.
DisableIf
template<typename... Condition> using carl::DisableIf = typedef typename std::enable_if<Not<any<Condition...> >::value, dtl::enabled>::type
Definition at line 63 of file SFINAE.h.
EnableIf
template<typename... Condition> using carl::EnableIf = typedef typename std::enable_if<all<Condition...>::value, dtl::enabled>::type
Definition at line 61 of file SFINAE.h.
EnableIfBool
template<bool Condition> using carl::EnableIfBool = typedef typename std::enable_if<Condition, dtl::enabled>::type
Definition at line 65 of file SFINAE.h.
ErrorHandler
using carl::ErrorHandler = typedef carl::parser::ErrorHandler
Definition at line 24 of file OPBImporter.cpp.
EvaluationMap
template<typename T > using carl::EvaluationMap = typedef std::map<Variable, T>
Definition at line 56 of file Common.h.
exponent
using carl::exponent = typedef uint
Type of an exponent.
Definition at line 24 of file Monomial.h.
FactorMap
template<typename Coefficient > using carl::FactorMap = typedef std::map<UnivariatePolynomial<Coefficient>, uint>
Definition at line 35 of file UnivariatePolynomial.h.
Factors
template<typename Pol > using carl::Factors = typedef std::map<Pol,uint>
Definition at line 117 of file Common.h.
FastMap
template<typename T1 , typename T2 > using carl::FastMap = typedef std::unordered_map<T1, T2, std::hash<T1> >
Definition at line 90 of file Common.h.
FastPointerMap
template<typename T1 , typename T2 > using carl::FastPointerMap = typedef std::unordered_map<const T1*, T2, pointerHash<T1>, pointerEqual<T1> >
Definition at line 96 of file Common.h.
FastPointerMapB
template<typename T1 , typename T2 > using carl::FastPointerMapB = typedef std::unordered_map<const T1*, T2, pointerHashWithNull<T1>, pointerEqualWithNull<T1> >
Definition at line 108 of file Common.h.
FastPointerSet
template<typename T > using carl::FastPointerSet = typedef std::unordered_set<const T*, pointerHash<T>, pointerEqual<T> >
Definition at line 93 of file Common.h.
FastPointerSetB
template<typename T > using carl::FastPointerSetB = typedef std::unordered_set<const T*, pointerHashWithNull<T>, pointerEqualWithNull<T> >
Definition at line 105 of file Common.h.
FastSet
template<typename T > using carl::FastSet = typedef std::unordered_set<T, std::hash<T> >
Definition at line 87 of file Common.h.
FastSharedPointerMap
template<typename T1 , typename T2 > using carl::FastSharedPointerMap = typedef std::unordered_map<std::shared_ptr<const T1>, T2, sharedPointerHash<T1>, sharedPointerEqual<T1> >
Definition at line 102 of file Common.h.
FastSharedPointerMapB
template<typename T1 , typename T2 > using carl::FastSharedPointerMapB = typedef std::unordered_map<std::shared_ptr<const T1>, T2, sharedPointerHashWithNull<T1>, pointerEqualWithNull<T1> >
Definition at line 114 of file Common.h.
FastSharedPointerSet
template<typename T > using carl::FastSharedPointerSet = typedef std::unordered_set<std::shared_ptr<const T>, sharedPointerHash<T>, sharedPointerEqual<T> >
Definition at line 99 of file Common.h.
FastSharedPointerSetB
template<typename T > using carl::FastSharedPointerSetB = typedef std::unordered_set<std::shared_ptr<const T>, sharedPointerHashWithNull<T>, pointerEqualWithNull<T> >
Definition at line 111 of file Common.h.
Formulas
template<typename Poly > using carl::Formulas = typedef std::vector<Formula<Poly> >
Definition at line 13 of file FormulaContent.h.
FormulaSet
template<typename Poly > using carl::FormulaSet = typedef std::set<Formula<Poly> >
Definition at line 15 of file FormulaContent.h.
FormulasMulti
template<typename Poly > using carl::FormulasMulti = typedef std::multiset<Formula<Poly>, carl::less<Formula<Poly> >>
Definition at line 17 of file FormulaContent.h.
GrLexOrdering
using carl::GrLexOrdering = typedef MonomialComparator<Monomial::compareGradedLexical, true >
Definition at line 63 of file MonomialOrdering.h.
IntegralTypeIfDifferent
template<typename C > using carl::IntegralTypeIfDifferent = typedef typename std::enable_if<!std::is_same<C, typename IntegralType<C>::type>::value, typename IntegralType<C>::type>::type
Definition at line 334 of file typetraits.h.
Iterator
using carl::Iterator = typedef PositionIteratorType
Definition at line 23 of file OPBImporter.cpp.
LexOrdering
using carl::LexOrdering = typedef MonomialComparator<Monomial::compareLexical, false >
Definition at line 62 of file MonomialOrdering.h.
ModelSubstitutionPtr
template<typename Rational , typename Poly > using carl::ModelSubstitutionPtr = typedef std::shared_ptr<ModelSubstitution<Rational,Poly> >
Definition at line 25 of file ModelValue.h.
MonomialOrderingFunction
using carl::MonomialOrderingFunction = typedef CompareResult(*)(const Monomial::Arg&, const Monomial::Arg&)
Definition at line 14 of file MonomialOrdering.h.
Not
template<typename T > using carl::Not = typedef Bool<!T::value>
Meta-logical negation.
Definition at line 28 of file SFINAE.h.
OPBConstraint
using carl::OPBConstraint = typedef std::tuple<OPBPolynomial, Relation, int>
Definition at line 17 of file OPBImporter.h.
OPBPolynomial
using carl::OPBPolynomial = typedef std::vector<std::pair<int,carl::Variable> >
Definition at line 16 of file OPBImporter.h.
pointerEqual
template<typename T > using carl::pointerEqual = typedef carl::equal_to<const T*, false>
Definition at line 28 of file Common.h.
pointerEqualWithNull
template<typename T > using carl::pointerEqualWithNull = typedef carl::equal_to<const T*, true>
Definition at line 30 of file Common.h.
pointerHash
template<typename T > using carl::pointerHash = typedef carl::hash<T*, false>
Definition at line 46 of file Common.h.
pointerHashWithNull
template<typename T > using carl::pointerHashWithNull = typedef carl::hash<T*, true>
Definition at line 48 of file Common.h.
pointerLess
template<typename T > using carl::pointerLess = typedef carl::less<const T*, false>
Definition at line 37 of file Common.h.
pointerLessWithNull
template<typename T > using carl::pointerLessWithNull = typedef carl::less<const T*, true>
Definition at line 39 of file Common.h.
PointerMap
template<typename T1 , typename T2 > using carl::PointerMap = typedef std::map<const T1*, T2, pointerLess<T1> >
Definition at line 75 of file Common.h.
PointerMultiSet
template<typename T > using carl::PointerMultiSet = typedef std::multiset<const T*, pointerLess<T> >
Definition at line 72 of file Common.h.
PointerSet
template<typename T > using carl::PointerSet = typedef std::set<const T*, pointerLess<T> >
Definition at line 69 of file Common.h.
PositionIteratorType
using carl::PositionIteratorType = typedef spirit::line_pos_iterator<BaseIteratorType>
Definition at line 22 of file OPBImporter.cpp.
precision_t
using carl::precision_t = typedef std::size_t
Definition at line 31 of file FLOAT_T.h.
QuantifiedVariables
using carl::QuantifiedVariables = typedef std::vector<Variables>
Definition at line 66 of file Common.h.
sharedPointerEqual
template<typename T > using carl::sharedPointerEqual = typedef carl::equal_to<std::shared_ptr<const T>, false>
Definition at line 32 of file Common.h.
sharedPointerEqualWithNull
template<typename T > using carl::sharedPointerEqualWithNull = typedef carl::equal_to<std::shared_ptr<const T>, true>
Definition at line 34 of file Common.h.
sharedPointerHash
template<typename T > using carl::sharedPointerHash = typedef carl::hash<std::shared_ptr<const T>*, false>
Definition at line 50 of file Common.h.
sharedPointerHashWithNull
template<typename T > using carl::sharedPointerHashWithNull = typedef carl::hash<std::shared_ptr<const T>*, true>
Definition at line 52 of file Common.h.
sharedPointerLess
template<typename T > using carl::sharedPointerLess = typedef carl::less<std::shared_ptr<const T>*, false>
Definition at line 41 of file Common.h.
sharedPointerLessWithNull
template<typename T > using carl::sharedPointerLessWithNull = typedef carl::less<std::shared_ptr<const T>, true>
Definition at line 43 of file Common.h.
SharedPointerMap
template<typename T1 , typename T2 > using carl::SharedPointerMap = typedef std::map<std::shared_ptr<const T1>, T2, sharedPointerLess<T1> >
Definition at line 84 of file Common.h.
SharedPointerMultiSet
template<typename T > using carl::SharedPointerMultiSet = typedef std::multiset<std::shared_ptr<const T>, sharedPointerLess<T> >
Definition at line 81 of file Common.h.
SharedPointerSet
template<typename T > using carl::SharedPointerSet = typedef std::set<std::shared_ptr<const T>, sharedPointerLess<T> >
Definition at line 78 of file Common.h.
SimpleNewtonContraction
typedef Contraction<SimpleNewton, Polynomial> carl::SimpleNewtonContraction
Definition at line 593 of file Contraction.h.
sint
using carl::sint = typedef std::int64_t
Definition at line 17 of file numbers.h.
TypeInfoPair
template<typename T , class I > using carl::TypeInfoPair = typedef std::pair<T*,I>
Definition at line 21 of file Cache.h.
uint
using carl::uint = typedef std::uint64_t
Definition at line 16 of file numbers.h.
UnivariatePolynomialPtr
template<typename Coefficient > using carl::UnivariatePolynomialPtr = typedef std::shared_ptr<UnivariatePolynomial<Coefficient> >
Definition at line 32 of file UnivariatePolynomial.h.
Variables
using carl::Variables = typedef std::set<Variable>
Definition at line 64 of file Common.h.
VarInfo
template<typename Pol > using carl::VarInfo = typedef VariableInformation<true, Pol>
Definition at line 45 of file Constraint.h.
VarInfoMap
template<typename Pol > using carl::VarInfoMap = typedef std::map<Variable, VarInfo<Pol> >
Definition at line 48 of file Constraint.h.
Enumeration Type Documentation
BoundType
enum carl::BoundType strong
Enumerator
STRICT
the given bound is compared by a strict ordering relation
WEAK
the given bound is compared by a weak ordering relation
INFTY
the given bound is interpreted as minus or plus infinity depending on whether it is the left or the right bound
Definition at line 13 of file BoundType.h.
BVCompareRelation
enum carl::BVCompareRelation : unsigned strong
Enumerator
EQ
NEQ
ULT
ULE
UGT
UGE
SLT
SLE
SGT
SGE
Definition at line 15 of file BVCompareRelation.h.
BVTermType
enum carl::BVTermType : unsigned strong
Enumerator
CONSTANT
VARIABLE
CONCAT
EXTRACT
NOT
NEG
AND
OR
XOR
NAND
NOR
XNOR
ADD
SUB
MUL
DIV_U
DIV_S
MOD_U
MOD_S1
MOD_S2
EQ
LSHIFT
RSHIFT_LOGIC
RSHIFT_ARITH
LROTATE
RROTATE
EXT_U
EXT_S
REPEAT
Definition at line 16 of file BVTerm.h.
CARL_RND
enum carl::CARL_RND : int strong
Enumerator
N
Z
U
D
A
Definition at line 23 of file roundingConversion.h.
CompareResult
enum carl::CompareResult strong
Enumerator
LESS
EQUAL
GREATER
Definition at line 12 of file CompareResult.h.
Definiteness
enum carl::Definiteness strong
Regarding a polynomial as a function , its definiteness gives information about the codomain .
Enumerator
NEGATIVE
Indicates that .
NEGATIVE_SEMI
Indicates that .
NON
Indicates that values may be positive and negative.
POSITIVE_SEMI
Indicates that .
POSITIVE
Indicates that .
Definition at line 16 of file Definiteness.h.
FormulaType
enum carl::FormulaType
Represent the type of a formula to allow faster/specialized processing.
For each (supported) SMTLIB theory, we have
Constants
Variables
Functions
Additional functions (not specified, but used in the wild)
Enumerator
ITE
EXISTS
FORALL
TRUE
FALSE
BOOL
NOT
NOT
IMPLIES
AND
AND
OR
OR
XOR
XOR
IFF
CONSTRAINT
VARCOMPARE
VARASSIGN
BITVECTOR
UEQ
PBCONSTRAINT
Definition at line 30 of file FormulaContent.h.
Logic
enum carl::Logic strong
Enumerator
QF_BV
QF_IDL
QF_LIA
QF_LIRA
QF_LRA
QF_NIA
QF_NIRA
QF_NRA
QF_PB
QF_RDL
QF_UF
UNDEFINED
Definition at line 7 of file Logic.h.
PolynomialComparisonOrder
enum carl::PolynomialComparisonOrder strong
Enumerator
CauchyBound
LowDegree
Memory
Default
Definition at line 46 of file UnivariatePolynomial.h.
RANSampleHeuristic
enum carl::RANSampleHeuristic strong
Enumerator
Center
CenterInt
LeftInt
RightInt
ZeroInt
InftyInt
Default
Definition at line 44 of file RealAlgebraicNumber.h.
Relation
enum carl::Relation strong
Enumerator
EQ
NEQ
LESS
LEQ
GREATER
GEQ
Definition at line 19 of file Relation.h.
Sign
enum carl::Sign strong
This class represents the sign of a number .
Enumerator
NEGATIVE
Indicates that .
ZERO
Indicates that .
POSITIVE
Indicates that .
Definition at line 19 of file Sign.h.
Str2Double_Error
enum carl::Str2Double_Error
Enumerator
FLOAT_SUCCESS
FLOAT_OVERFLOW
FLOAT_UNDERFLOW
FLOAT_INCONVERTIBLE
Definition at line 61 of file FLOAT_T.h.
SubresultantStrategy
enum carl::SubresultantStrategy strong
Enumerator
Generic
Lazard
Ducos
Default
Definition at line 7 of file Resultant.h.
ThomComparisonResult
enum carl::ThomComparisonResult
Enumerator
LESS
LESS
LESS
EQUAL
EQUAL
GREATER
GREATER
GREATER
Definition at line 15 of file SignCondition.h.
variableSelectionHeurisics
enum carl::variableSelectionHeurisics
Enumerator
GREEDY_I
GREEDY_Is
GREEDY_II
GREEDY_IIs
Definition at line 3 of file MultivariateHornerSettings.h.
VariableType
enum carl::VariableType strong
Several types of variables are supported.
BOOL: the Booleans REAL: the reals INT: the integers UNINTERPRETED: all uninterpreted types BITVECTOR: bitvectors of any length
Enumerator
VT_BOOL
VT_REAL
VT_INT
VT_UNINTERPRETED
VT_BITVECTOR
MIN_TYPE
MAX_TYPE
TYPE_SIZE
Definition at line 27 of file Variable.h.
Function Documentation
abs() [1/9]
double carl::abs (double n) inline
Definition at line 137 of file operations.h.
Referenced by abs().
abs() [2/9]
template<typename IntegerT > GFNumber<IntegerT> carl::abs (const GFNumber< IntegerT > & n)
Definition at line 190 of file GFNumber.h.
abs() [3/9]
template<typename T > Numeric<T> carl::abs (const Numeric< T > &)
Referenced by isInteger(), carl::Numeric< T >::maybeRationalize(), carl::Numeric< T >::operator typename IntegralType< T >::type(), carl::Numeric< T >::rational(), carl::Numeric< T >::rRational(), and carl::Numeric< T >::toRational().
abs() [4/9]
cln::cl_I carl::abs (const cln::cl_I & n) inline
Get absolute value of an integer.
Parameters
n An integer.
Returns
.
Definition at line 246 of file operations.h.
abs() [5/9]
cln::cl_RA carl::abs (const cln::cl_RA & n) inline
Get absolute value of a fraction.
Parameters
n A fraction.
Returns
.
Definition at line 255 of file operations.h.
abs() [6/9]
mpz_class carl::abs (const mpz_class & n) inline
Basic Operators.
The following functions implement simple operations on the given numbers.
Definition at line 255 of file operations.h.
abs() [7/9]
mpq_class carl::abs (const mpq_class & n) inline
Definition at line 261 of file operations.h.
abs() [8/9]
template<typename FloatType > FLOAT_T<FloatType> carl::abs (const FLOAT_T< FloatType > & _in) inline
Method which returns the absolute value of the passed number.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 1413 of file FLOAT_T.h.
Referenced by AlmostEqual2sComplement< double >().
abs() [9/9]
template<typename Number > Interval<Number> carl::abs (const Interval< Number > & _in) inline
Method which returns the absolute value of the passed number.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 2111 of file Interval.h.
Referenced by carl::Number< cln::cl_I >::abs(), carl::Number< cln::cl_RA >::abs(), carl::RealAlgebraicNumber< carl::Number >::abs(), carl::FLOAT_T< FloatType >::abs(), carl::FLOAT_T< FloatType >::abs_assign(), cauchyBound(), compare(), carl::SignDetermination< Number >::getSigns(), hirstMaceyBound(), lagrangeBound(), carl::Number< mpz_class >::mod(), mod(), carl::DIMACSImporter< Pol >::parseLine(), carl::Number< mpz_class >::quotient(), quotient(), carl::Number< cln::cl_I >::toString(), carl::Number< mpq_class >::toString(), carl::Number< mpz_class >::toString(), toString(), and carl::Number< cln::cl_RA >::toString().
acos() [1/2]
double carl::acos (double in) inline
Definition at line 171 of file operations.h.
acos() [2/2]
template<typename FloatType > FLOAT_T<FloatType> carl::acos (const FLOAT_T< FloatType > & _in) inline
Definition at line 1485 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::acos(), carl::FLOAT_T< FloatType >::acos_assign(), carl::rounding< Number >::acos_down(), and carl::rounding< Number >::acos_up().
AlmostEqual2sComplement()
template<typename Number > bool carl::AlmostEqual2sComplement (const Number & A, const Number & B, unsigned = 128) inline
Definition at line 84 of file FLOAT_T.h.
AlmostEqual2sComplement< double >()
template<> bool carl::AlmostEqual2sComplement< double > (const double & A, const double & B, unsigned maxUlps) inline
Definition at line 90 of file FLOAT_T.h.
Referenced by AlmostEqual2sComplement< FLOAT_T< double > >().
AlmostEqual2sComplement< FLOAT_T< double > >()
template<> bool carl::AlmostEqual2sComplement< FLOAT_T< double > > (const FLOAT_T< double > & A, const FLOAT_T< double > & B, unsigned maxUlps) inline
Definition at line 1610 of file FLOAT_T.h.
asin()
template<typename FloatType > FLOAT_T<FloatType> carl::asin (const FLOAT_T< FloatType > & _in) inline
Definition at line 1477 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::asin(), carl::FLOAT_T< FloatType >::asin_assign(), carl::rounding< Number >::asin_down(), and carl::rounding< Number >::asin_up().
asSMTLIB()
template<typename... Args> detail::SMTLIBOutputContainer<Args...> carl::asSMTLIB (Args &&... args)
Definition at line 332 of file SMTLIBStream.h.
atan()
template<typename FloatType > FLOAT_T<FloatType> carl::atan (const FLOAT_T< FloatType > & _in) inline
Definition at line 1493 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::atan(), carl::FLOAT_T< FloatType >::atan_assign(), carl::rounding< Number >::atan_down(), and carl::rounding< Number >::atan_up().
basename()
std::string carl::basename (const std::string & filename) inline
Return the basename of a given filename.
Definition at line 34 of file carlLoggingHelper.h.
Referenced by carl::logging::Formatter::prefix().
binary()
template<typename T > std::string carl::binary (const T & a, const bool & spacing = true)
Return the binary representation given value as bit string.
Note that this method is tailored to little endian systems.
Parameters
a A value of any type
spacing Specifies if the bytes shall be separated by a space.
Returns
Bit string representing a.
Definition at line 18 of file carlLoggingHelper.h.
bitsize() [1/5]
std::size_t carl::bitsize (unsigned) inline
Definition at line 79 of file operations.h.
bitsize() [2/5]
std::size_t carl::bitsize (const mpz_class & n) inline
Get the bit size of the representation of a integer.
Parameters
n An integer.
Returns
Bit size of n.
Definition at line 96 of file operations.h.
bitsize() [3/5]
std::size_t carl::bitsize (const cln::cl_I & n) inline
Get the bit size of the representation of a integer.
Parameters
n An integer.
Returns
Bit size of n.
Definition at line 101 of file operations.h.
Referenced by carl::cad::SampleSet< Number >::SampleComparator::compareSize(), and carl::RealAlgebraicNumber< carl::Number >::size().
bitsize() [4/5]
std::size_t carl::bitsize (const mpq_class & n) inline
Get the bit size of the representation of a fraction.
Parameters
n A fraction.
Returns
Bit size of n.
Definition at line 104 of file operations.h.
bitsize() [5/5]
std::size_t carl::bitsize (const cln::cl_RA & n) inline
Get the bit size of the representation of a fraction.
Parameters
n A fraction.
Returns
Bit size of n.
Definition at line 109 of file operations.h.
callingFunction()
std::string carl::callingFunction ()
Definition at line 49 of file debug.cpp.
cauchyBound()
template<typename Coeff > Coeff carl::cauchyBound (const UnivariatePolynomial< Coeff > & p)
Definition at line 17 of file RootBounds.h.
ceil() [1/8]
template<typename Number > IntegralType<Number>::type carl::ceil (const RealAlgebraicNumber< Number > & n) inline
Definition at line 37 of file RealAlgebraicNumberOperations.h.
Referenced by carl::FLOAT_T< FloatType >::ceil(), ceil(), ceil_fast(), carl::Interval< mpq_class >::center(), charPol(), carl::rounding< Number >::int_up(), carl::FLOAT_T< FloatType >::operator int(), sampleBelow(), and carl::Interval< mpq_class >::sampleRight().
ceil() [2/8]
double carl::ceil (double n) inline
Definition at line 134 of file operations.h.
ceil() [3/8]
mpz_class carl::ceil (const mpq_class & n) inline
Definition at line 292 of file operations.h.
ceil() [4/8]
mpz_class carl::ceil (const mpz_class & n) inline
Definition at line 298 of file operations.h.
ceil() [5/8]
cln::cl_I carl::ceil (const cln::cl_RA & n) inline
Round up a fraction.
Parameters
n A fraction.
Returns
.
Definition at line 300 of file operations.h.
ceil() [6/8]
cln::cl_I carl::ceil (const cln::cl_I & n) inline
Round up an integer.
Parameters
n An integer.
Returns
.
Definition at line 309 of file operations.h.
ceil() [7/8]
template<typename FloatType > FLOAT_T<FloatType> carl::ceil (const FLOAT_T< FloatType > & _in) inline
Method which returns the next larger integer of the passed number or the number itself, if it is already an integer.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 1521 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::ceil_assign().
ceil() [8/8]
template<typename Number > Interval<Number> carl::ceil (const Interval< Number > & _in) inline
Method which returns the next larger integer of the passed number or the number itself, if it is already an integer.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 2164 of file Interval.h.
ceil_fast()
template<typename Number > IntegralType<Number>::type carl::ceil_fast (const RealAlgebraicNumber< Number > & n) inline
Definition at line 43 of file RealAlgebraicNumberOperations.h.
Referenced by ceil().
charPol()
template<typename Coeff > std::vector<Coeff> carl::charPol (const CoeffMatrix< Coeff > & m)
Definition at line 51 of file CharPol.h.
Referenced by multivariateTarskiQuery().
checkConversion()
template<typename Poly > bool carl::checkConversion (const Poly & polyA)
Definition at line 173 of file OldGinacConverter.h.
compare()
template<typename Pol > signed carl::compare (const Constraint< Pol > & _constraintA, const Constraint< Pol > & _constraintB)
Compares _constraintA with _constraintB.
Returns
2, if it is easy to decide that _constraintA and _constraintB have the same solutions. _constraintA = _constraintB 1, if it is easy to decide that _constraintB includes all solutions of _constraintA; _constraintA -> _constraintB -1, if it is easy to decide that _constraintA includes all solutions of _constraintB; _constraintB -> _constraintA -2, if it is easy to decide that _constraintA has no solution common with _constraintB; not(_constraintA and _constraintB) -3, if it is easy to decide that _constraintA and _constraintB can be intersected; _constraintA and _constraintB = _constraintC -4, if it is easy to decide that _constraintA is the inverse of _constraintB; _constraintA xor _constraintB 0, otherwise.
Definition at line 859 of file Constraint.h.
Referenced by carl::ReductorConfiguration< Polynomial >::compare(), carl::CriticalPairConfiguration< Compare >::compare(), and main().
computePolynomial() [1/2]
template<typename P > P carl::computePolynomial (const PolynomialFactorizationPair< P > & _pfPair)
Compute the polynomial from the given polynomial-factorization pair.
Parameters
_fpPair A polynomial-factorization pair.
Returns
The polynomial.
computePolynomial() [2/2]
template<typename P > P carl::computePolynomial (const FactorizedPolynomial< P > & _fpoly)
Obtains the polynomial (representation) of this factorized polynomial.
Note, that the result won't be stored in the factorized polynomial, hence, this method should only be called for debug purpose.
Parameters
_fpoly The factorized polynomial to get its polynomial (representation) for.
Returns
The polynomial (representation) of this factorized polynomial
constraintPool()
template<typename Pol > const ConstraintPool<Pol>& carl::constraintPool ()
Returns
A constant reference to the shared constraint pool.
convert()
template<typename From , typename To , carl::DisableIf< std::is_same< From, To > > > To carl::convert (const From &) inline
Definition at line 8 of file conversion.h.
convert< cln::cl_I, cln::cl_I >()
template<> cln::cl_I carl::convert< cln::cl_I, cln::cl_I > (const cln::cl_I & n) inline
Definition at line 9 of file cln_gmp.h.
convert< cln::cl_I, mpz_class >()
template<> mpz_class carl::convert< cln::cl_I, mpz_class > (const cln::cl_I & n) inline
Definition at line 19 of file cln_gmp.h.
convert< cln::cl_RA, cln::cl_RA >()
template<> cln::cl_RA carl::convert< cln::cl_RA, cln::cl_RA > (const cln::cl_RA & n) inline
Definition at line 14 of file cln_gmp.h.
convert< cln::cl_RA, mpq_class >()
template<> mpq_class carl::convert< cln::cl_RA, mpq_class > (const cln::cl_RA & n) inline
Definition at line 32 of file cln_gmp.h.
convert< double, FLOAT_T< double > >()
template<> FLOAT_T<double> carl::convert< double, FLOAT_T< double > > (const double & n) inline
Definition at line 50 of file native.h.
convert< double, FLOAT_T< mpq_class > >()
template<> FLOAT_T<mpq_class> carl::convert< double, FLOAT_T< mpq_class > > (const double & n) inline
Definition at line 15 of file native.h.
convert< double, mpq_class >()
template<> mpq_class carl::convert< double, mpq_class > (const double & n) inline
Definition at line 5 of file native.h.
convert< FLOAT_T< double >, double >()
template<> double carl::convert< FLOAT_T< double >, double > (const FLOAT_T< double > & n) inline
Definition at line 45 of file native.h.
convert< FLOAT_T< double >, mpq_class >()
template<> mpq_class carl::convert< FLOAT_T< double >, mpq_class > (const FLOAT_T< double > & n) inline
Definition at line 30 of file native.h.
convert< FLOAT_T< mpq_class >, double >()
template<> double carl::convert< FLOAT_T< mpq_class >, double > (const FLOAT_T< mpq_class > & n) inline
Definition at line 20 of file native.h.
convert< FLOAT_T< mpq_class >, mpq_class >()
template<> mpq_class carl::convert< FLOAT_T< mpq_class >, mpq_class > (const FLOAT_T< mpq_class > & n) inline
Definition at line 35 of file native.h.
convert< mpq_class, cln::cl_RA >()
template<> cln::cl_RA carl::convert< mpq_class, cln::cl_RA > (const mpq_class & n) inline
Definition at line 71 of file cln_gmp.h.
convert< mpq_class, double >()
template<> double carl::convert< mpq_class, double > (const mpq_class & n) inline
Definition at line 10 of file native.h.
convert< mpq_class, FLOAT_T< double > >()
template<> FLOAT_T<double> carl::convert< mpq_class, FLOAT_T< double > > (const mpq_class & n) inline
Definition at line 25 of file native.h.
convert< mpq_class, FLOAT_T< mpq_class > >()
template<> FLOAT_T<mpq_class> carl::convert< mpq_class, FLOAT_T< mpq_class > > (const mpq_class & n) inline
Definition at line 40 of file native.h.
convert< mpq_class, mpq_class >()
template<> mpq_class carl::convert< mpq_class, mpq_class > (const mpq_class & n) inline
Definition at line 54 of file cln_gmp.h.
convert< mpz_class, cln::cl_I >()
template<> cln::cl_I carl::convert< mpz_class, cln::cl_I > (const mpz_class & n) inline
Definition at line 59 of file cln_gmp.h.
convert< mpz_class, mpz_class >()
template<> mpz_class carl::convert< mpz_class, mpz_class > (const mpz_class & n) inline
Definition at line 49 of file cln_gmp.h.
convertToCarl()
template<typename Poly > Poly carl::convertToCarl (const GiNaC::ex & _toConvert, const std::map< GiNaC::ex, carl::Variable, GiNaC::ex_is_less > & vars)
Definition at line 149 of file OldGinacConverter.h.
convertToGinac()
template<typename Poly > GiNaC::ex carl::convertToGinac (const Poly & poly, const std::map< carl::Variable, GiNaC::ex > & vars)
Definition at line 143 of file OldGinacConverter.h.
coprimePart()
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::coprimePart (const MultivariatePolynomial< C, O, P > & p, const MultivariatePolynomial< C, O, P > & q)
Definition at line 13 of file CoprimePart.h.
Referenced by carl::MultivariatePolynomial< Rational >::coprimePart().
cos() [1/4]
double carl::cos (double in) inline
Definition at line 167 of file operations.h.
Referenced by cos().
cos() [2/4]
mpq_class carl::cos (const mpq_class & n) inline
Definition at line 377 of file operations.h.
cos() [3/4]
cln::cl_RA carl::cos (const cln::cl_RA & n) inline
Definition at line 410 of file operations.h.
Referenced by carl::Number< cln::cl_RA >::cos(), carl::Number< mpq_class >::cos(), carl::FLOAT_T< FloatType >::cos(), carl::FLOAT_T< FloatType >::cos_assign(), carl::rounding< Number >::cos_down(), and carl::rounding< Number >::cos_up().
cos() [4/4]
template<typename FloatType > FLOAT_T<FloatType> carl::cos (const FLOAT_T< FloatType > & _in) inline
Definition at line 1469 of file FLOAT_T.h.
createFunctionSelector()
template<typename TypeSelector , typename Types , typename... Args> auto carl::createFunctionSelector (Args &&... args)
Definition at line 90 of file FunctionSelector.h.
createMonomial()
template<typename... T> Monomial::Arg carl::createMonomial (T &&... t) inline
Definition at line 156 of file MonomialPool.h.
Referenced by carl::VariableInformation< true, CoeffType >::collect(), carl::CoCoAAdaptor< Poly >::convert(), carl::detail_lazard::CoCoAConverter::convertMV(), carl::Monomial::derivative(), carl::Monomial::divide(), carl::Monomial::gcd(), main(), carl::parser::PolynomialParser< Pol >::newMonomial(), carl::parser::ExpressionParser< Pol >::perform_power::operator()(), operator*(), operator*=(), carl::StringParser::parseTerm(), carl::Monomial::pow(), pow(), and carl::Monomial::sqrt().
createSubstitution() [1/2]
template<typename Rational , typename Poly , typename Substitution , typename... Args> ModelValue< Rational, Poly > carl::createSubstitution (Args &&... args) inline
Definition at line 86 of file ModelSubstitution.h.
createSubstitution() [2/2]
template<typename Rational , typename Poly > ModelValue< Rational, Poly > carl::createSubstitution (const MultivariateRoot< Poly > & mr) inline
Definition at line 90 of file ModelSubstitution.h.
defaultSortValue()
SortValue carl::defaultSortValue (const Sort & _sort) inline
Returns the default value for the given sort.
Parameters
_sort The sort to return the default value for.
Returns
The resulting sort value.
Definition at line 68 of file SortValueManager.h.
Referenced by carl::UFModel::get().
demangle()
std::string carl::demangle (const char * name)
Definition at line 40 of file debug.cpp.
Referenced by callingFunction(), and typeString().
der()
template<typename Number > std::list<MultivariatePolynomial<Number> > carl::der (const MultivariatePolynomial< Number > & p, Variable::Arg var, uint from, uint upto)
Definition at line 16 of file ThomUtil.h.
Referenced by carl::ThomEncoding< Number >::extendSignCondition(), realRootsThom(), and carl::ThomEncoding< Number >::relevantDerivatives().
discriminant()
template<typename Coeff > UnivariatePolynomial< Coeff > carl::discriminant (const UnivariatePolynomial< Coeff > & p, SubresultantStrategy strategy = SubresultantStrategy::Default)
Definition at line 289 of file Resultant.h.
Referenced by carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::Brown(), carl::UnivariatePolynomial< Coeff >::discriminant(), and carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::McCallum().
div() [1/8]
sint carl::div (sint n, sint m) inline
Definition at line 151 of file operations.h.
div() [2/8]
template<typename T > Numeric<T> carl::div (const Numeric< T > & , const Numeric< T > &)
div() [3/8]
cln::cl_RA carl::div (const cln::cl_RA & a, const cln::cl_RA & b) inline
Divide two fractions.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 464 of file operations.h.
div() [4/8]
cln::cl_I carl::div (const cln::cl_I & a, const cln::cl_I & b) inline
Divide two integers.
Asserts that the remainder is zero.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 475 of file operations.h.
div() [5/8]
mpq_class carl::div (const mpq_class & a, const mpq_class & b) inline
Divide two fractions.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 482 of file operations.h.
div() [6/8]
mpz_class carl::div (const mpz_class & a, const mpz_class & b) inline
Divide two integers.
Asserts that the remainder is zero.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 493 of file operations.h.
div() [7/8]
template<typename FloatType > FLOAT_T<FloatType> carl::div (const FLOAT_T< FloatType > & _lhs, const FLOAT_T< FloatType > & _rhs) inline
Implements the division which assumes that there is no remainder.
Parameters
_lhs
_rhs
Returns
Number which holds the result.
Definition at line 1366 of file FLOAT_T.h.
div() [8/8]
template<typename Number > Interval<Number> carl::div (const Interval< Number > & _lhs, const Interval< Number > & _rhs) inline
Implements the division which assumes that there is no remainder.
Parameters
_lhs
_rhs
Returns
Interval which holds the result.
Definition at line 2076 of file Interval.h.
Referenced by boost::spirit::traits::scale().
div_assign() [1/5]
template<typename T > Numeric<T>& carl::div_assign (Numeric< T > & , const Numeric< T > &)
div_assign() [2/5]
cln::cl_RA& carl::div_assign (cln::cl_RA & a, const cln::cl_RA & b) inline
Divide two fractions.
Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 487 of file operations.h.
div_assign() [3/5]
cln::cl_I& carl::div_assign (cln::cl_I & a, const cln::cl_I & b) inline
Divide two integers.
Asserts that the remainder is zero. Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 500 of file operations.h.
div_assign() [4/5]
mpz_class& carl::div_assign (mpz_class & a, const mpz_class & b) inline
Divide two integers.
Asserts that the remainder is zero. Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 506 of file operations.h.
div_assign() [5/5]
mpq_class& carl::div_assign (mpq_class & a, const mpq_class & b) inline
Divide two integers.
Asserts that the remainder is zero. Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 518 of file operations.h.
divide() [1/3]
void carl::divide (sint dividend, sint divisor, sint & quo, sint & rem) inline
Definition at line 158 of file operations.h.
divide() [2/3]
void carl::divide (const cln::cl_I & dividend, const cln::cl_I & divisor, cln::cl_I & quotient, cln::cl_I & remainder) inline
Definition at line 335 of file operations.h.
Referenced by carl::EEA< IntegerType >::calculate_recursive(), and carl::OldGinacConverter< Poly >::similar().
divide() [3/3]
void carl::divide (const mpz_class & dividend, const mpz_class & divisor, mpz_class & quotient, mpz_class & remainder) inline
Definition at line 472 of file operations.h.
doNothing()
template<typename T > void carl::doNothing (const T & , const T &)
Definition at line 44 of file Cache.h.
evaluate() [1/2]
bool carl::evaluate (Sign s, Relation r) inline
Definition at line 65 of file Relation.h.
Referenced by carl::model::evaluate(), and evaluate().
evaluate() [2/2]
template<typename T > bool carl::evaluate (const T & t, Relation r) inline
Definition at line 81 of file Relation.h.
evaluateTE()
template<typename Number > RealAlgebraicNumber<Number> carl::evaluateTE (const MultivariatePolynomial< Number > & p, std::map< Variable, RealAlgebraicNumber< Number >> & m)
Definition at line 18 of file ThomEvaluation.h.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluate().
extended_gcd_integer()
template<typename T > T carl::extended_gcd_integer (T a, T b, T & s, T & t)
factorization()
template<typename C , typename O , typename P > Factors<MultivariatePolynomial<C,O,P> > carl::factorization (const MultivariatePolynomial< C, O, P > & p, bool includeConstants = true)
Try to factorize a multivariate polynomial.
Uses CoCoALib and GiNaC, if available, depending on the coefficient type of the polynomial.
Definition at line 54 of file Factorization.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getSubstitution().
factorizationsEqual()
template<typename P > bool carl::factorizationsEqual (const Factorization< P > & _factorizationA, const Factorization< P > & _factorizationB)
factorizationToString()
template<typename P > std::string carl::factorizationToString (const Factorization< P > & _factorization, bool _infix = true, bool _friendlyVarNames = true)
fitsWithin()
template<typename T , typename T2 > bool carl::fitsWithin (const T2 & t)
Definition at line 385 of file typetraits.h.
floor() [1/8]
template<typename Number > IntegralType<Number>::type carl::floor (const RealAlgebraicNumber< Number > & n) inline
Definition at line 25 of file RealAlgebraicNumberOperations.h.
Referenced by carl::Interval< mpq_class >::center(), carl::FLOAT_T< FloatType >::floor(), floor(), carl::FLOAT_T< FloatType >::floor_assign(), floor_fast(), carl::rounding< Number >::int_down(), carl::RealAlgebraicNumber< carl::Number >::integerBelow(), carl::FLOAT_T< FloatType >::operator int(), sampleAbove(), and carl::Interval< mpq_class >::sampleLeft().
floor() [2/8]
double carl::floor (double n) inline
Basic Operators.
The following functions implement simple operations on the given numbers.
Definition at line 131 of file operations.h.
floor() [3/8]
mpz_class carl::floor (const mpq_class & n) inline
Definition at line 281 of file operations.h.
floor() [4/8]
cln::cl_I carl::floor (const cln::cl_RA & n) inline
Round down a fraction.
Parameters
n A fraction.
Returns
.
Definition at line 282 of file operations.h.
floor() [5/8]
mpz_class carl::floor (const mpz_class & n) inline
Definition at line 288 of file operations.h.
floor() [6/8]
cln::cl_I carl::floor (const cln::cl_I & n) inline
Round down an integer.
Parameters
n An integer.
Returns
.
Definition at line 291 of file operations.h.
floor() [7/8]
template<typename FloatType > FLOAT_T<FloatType> carl::floor (const FLOAT_T< FloatType > & _in) inline
Method which returns the next smaller integer of this number or the number itself, if it is already an integer.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 1507 of file FLOAT_T.h.
floor() [8/8]
template<typename Number > Interval<Number> carl::floor (const Interval< Number > & _in) inline
Method which returns the next smaller integer of this number or the number itself, if it is already an integer.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 2152 of file Interval.h.
floor_fast()
template<typename Number > IntegralType<Number>::type carl::floor_fast (const RealAlgebraicNumber< Number > & n) inline
Definition at line 31 of file RealAlgebraicNumberOperations.h.
Referenced by floor().
formulaTypeToString()
std::string carl::formulaTypeToString (FormulaType _type) inline
Parameters
_type The formula type to get the string representation for.
Returns
The string representation of the given type.
Definition at line 61 of file FormulaContent.h.
Referenced by operator<<().
freshBitvectorVariable() [1/2]
Variable carl::freshBitvectorVariable () inline noexcept
Definition at line 194 of file VariablePool.h.
freshBitvectorVariable() [2/2]
Variable carl::freshBitvectorVariable (const std::string & name) inline
Definition at line 197 of file VariablePool.h.
freshBooleanVariable() [1/2]
Variable carl::freshBooleanVariable () inline noexcept
Definition at line 200 of file VariablePool.h.
Referenced by carl::OPBImporter< Pol >::convert(), carl::FormulaPool< Pol >::createTseitinVar(), carl::parser::FormulaParser< Pol >::newVariable(), and carl::DIMACSImporter< Pol >::parseFormula().
freshBooleanVariable() [2/2]
Variable carl::freshBooleanVariable (const std::string & name) inline
Definition at line 203 of file VariablePool.h.
freshIntegerVariable() [1/2]
Variable carl::freshIntegerVariable () inline noexcept
Definition at line 212 of file VariablePool.h.
Referenced by carl::OPBParser::addVariable(), and main().
freshIntegerVariable() [2/2]
Variable carl::freshIntegerVariable (const std::string & name) inline
Definition at line 215 of file VariablePool.h.
freshRealVariable() [1/2]
Variable carl::freshRealVariable () inline noexcept
Definition at line 206 of file VariablePool.h.
Referenced by carl::RealAlgebraicNumberEvaluation::evaluateIR(), main(), carl::parser::PolynomialParser< Pol >::newVariable(), carl::parser::ExpressionParser< Pol >::newVariable(), and carl::StringParser::setVariables().
freshRealVariable() [2/2]
Variable carl::freshRealVariable (const std::string & name) inline
Definition at line 209 of file VariablePool.h.
freshUninterpretedVariable() [1/2]
Variable carl::freshUninterpretedVariable () inline noexcept
Definition at line 218 of file VariablePool.h.
freshUninterpretedVariable() [2/2]
Variable carl::freshUninterpretedVariable (const std::string & name) inline
Definition at line 221 of file VariablePool.h.
freshVariable() [1/2]
Variable carl::freshVariable (VariableType vt) inline noexcept
Definition at line 187 of file VariablePool.h.
Referenced by freshBitvectorVariable(), freshBooleanVariable(), freshIntegerVariable(), freshRealVariable(), freshUninterpretedVariable(), and carl::PBConstraint< Poly >::normalize().
freshVariable() [2/2]
Variable carl::freshVariable (const std::string & name, VariableType vt) inline
Definition at line 190 of file VariablePool.h.
fromInt() [1/9]
template<typename To , typename From > To carl::fromInt (const From & n) inline
fromInt() [2/9]
template<> cln::cl_I carl::fromInt (const uint & n) inline
Definition at line 153 of file operations.h.
fromInt() [3/9]
template<> mpz_class carl::fromInt (const uint & n) inline
Definition at line 156 of file operations.h.
fromInt() [4/9]
template<> cln::cl_I carl::fromInt (const sint & n) inline
Definition at line 158 of file operations.h.
fromInt() [5/9]
template<> cln::cl_RA carl::fromInt (const uint & n) inline
Definition at line 163 of file operations.h.
fromInt() [6/9]
template<> mpz_class carl::fromInt (const sint & n) inline
Definition at line 166 of file operations.h.
fromInt() [7/9]
template<> cln::cl_RA carl::fromInt (const sint & n) inline
Definition at line 168 of file operations.h.
fromInt() [8/9]
template<> mpq_class carl::fromInt (const uint & n) inline
Definition at line 176 of file operations.h.
fromInt() [9/9]
template<> mpq_class carl::fromInt (const sint & n) inline
Definition at line 181 of file operations.h.
gatherVariables()
template<typename Poly > void carl::gatherVariables (const Poly & poly, std::map< Variable, GiNaC::ex > & carlToGinacVarMap, std::map< GiNaC::ex, Variable, GiNaC::ex_is_less > & ginacToCarlVarMap)
Definition at line 137 of file OldGinacConverter.h.
gcd() [1/9]
template<typename C , typename O , typename P > Term<C> carl::gcd (const MultivariatePolynomial< C, O, P > & a, const Term< C > & b)
gcd() [2/9]
template<typename C , typename O , typename P > Term<C> carl::gcd (const Term< C > & a, const MultivariatePolynomial< C, O, P > & b)
Definition at line 44 of file MultivariateGCD.h.
gcd() [3/9]
template<typename C , typename O , typename P > Monomial::Arg carl::gcd (const MultivariatePolynomial< C, O, P > & a, const Monomial::Arg & b)
gcd() [4/9]
template<typename C , typename O , typename P > Monomial::Arg carl::gcd (const Monomial::Arg & a, const MultivariatePolynomial< C, O, P > & b)
Definition at line 53 of file MultivariateGCD.h.
gcd() [5/9]
template<typename T > Numeric<T> carl::gcd (const Numeric< T > & , const Numeric< T > &)
gcd() [6/9]
mpz_class carl::gcd (const mpz_class & a, const mpz_class & b) inline
Definition at line 302 of file operations.h.
gcd() [7/9]
mpq_class carl::gcd (const mpq_class & a, const mpq_class & b) inline
Definition at line 314 of file operations.h.
Referenced by gcd(), and gcd_assign().
gcd() [8/9]
cln::cl_I carl::gcd (const cln::cl_I & a, const cln::cl_I & b) inline
Calculate the greatest common divisor of two integers.
Parameters
a First argument.
b Second argument.
Returns
Gcd of a and b.
Definition at line 319 of file operations.h.
gcd() [9/9]
cln::cl_RA carl::gcd (const cln::cl_RA & a, const cln::cl_RA & b) inline
Calculate the greatest common divisor of two fractions.
Asserts that the arguments are integral.
Parameters
a First argument.
b Second argument.
Returns
Gcd of a and b.
Definition at line 361 of file operations.h.
gcd_assign() [1/5]
template<typename T > Numeric<T>& carl::gcd_assign (Numeric< T > & , const Numeric< T > &)
gcd_assign() [2/5]
cln::cl_I& carl::gcd_assign (cln::cl_I & a, const cln::cl_I & b) inline
Calculate the greatest common divisor of two integers.
Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
Updated a.
Definition at line 330 of file operations.h.
gcd_assign() [3/5]
mpz_class& carl::gcd_assign (mpz_class & a, const mpz_class & b) inline
Calculate the greatest common divisor of two integers.
Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
Updated a.
Definition at line 335 of file operations.h.
gcd_assign() [4/5]
mpq_class& carl::gcd_assign (mpq_class & a, const mpq_class & b) inline
Calculate the greatest common divisor of two integers.
Stores the result in the first argument.
Parameters
a First argument.
b Second argument.
Returns
Updated a.
Definition at line 347 of file operations.h.
gcd_assign() [5/5]
cln::cl_RA& carl::gcd_assign (cln::cl_RA & a, const cln::cl_RA & b) inline
Calculate the greatest common divisor of two fractions.
Stores the result in the first argument. Asserts that the arguments are integral.
Parameters
a First argument.
b Second argument.
Returns
Updated a.
Definition at line 349 of file operations.h.
getDefaultModel() [1/4]
template<typename Rational , typename Poly > void carl::getDefaultModel (Model< Rational, Poly > & _defaultModel, const UEquality & _constraint, bool _overwrite = true, size_t _seed = 0)
getDefaultModel() [2/4]
template<typename Rational , typename Poly > void carl::getDefaultModel (Model< Rational, Poly > & _defaultModel, const BVTerm & _constraint, bool _overwrite = true, size_t _seed = 0)
getDefaultModel() [3/4]
template<typename Rational , typename Poly > void carl::getDefaultModel (Model< Rational, Poly > & _defaultModel, const Constraint< Poly > & _constraint, bool _overwrite = true, size_t _seed = 0)
getDefaultModel() [4/4]
template<typename Rational , typename Poly > void carl::getDefaultModel (Model< Rational, Poly > & _defaultModel, const Formula< Poly > & _formula, bool _overwrite = true, size_t _seed = 0)
getDenom() [1/4]
cln::cl_I carl::getDenom (const cln::cl_RA & n) inline
Extract the denominator from a fraction.
Parameters
n Fraction.
Returns
Denominator.
Definition at line 73 of file operations.h.
Referenced by bitsize(), compare(), convert< cln::cl_RA, mpq_class >(), convert< mpq_class, cln::cl_RA >(), carl::RationalFunction< Pol, AutoSimplify >::denominator(), carl::RationalFunction< Pol, AutoSimplify >::denominatorAsNumber(), gcd(), gcd_assign(), getDenom(), isInteger(), carl::Number< cln::cl_RA >::isInteger(), lcm(), carl::ConstructorPrinter::operator()(), round(), carl::CArLConverter::toGMP(), and toString().
getDenom() [2/4]
mpz_class carl::getDenom (const mpq_class & n) inline
Definition at line 75 of file operations.h.
getDenom() [3/4]
mpz_class carl::getDenom (const mpz_class & n) inline
Definition at line 79 of file operations.h.
getDenom() [4/4]
mpz_class carl::getDenom (const FLOAT_T< mpq_class > & _in) inline
Implicitly converts the number to a rational and returns the denominator.
Parameters
_in Number.
Returns
GMP interger which holds the result.
Definition at line 1579 of file FLOAT_T.h.
getNum() [1/4]
cln::cl_I carl::getNum (const cln::cl_RA & n) inline
Extract the numerator from a fraction.
Parameters
n Fraction.
Returns
Numerator.
Definition at line 64 of file operations.h.
Referenced by bitsize(), compare(), convert< cln::cl_RA, mpq_class >(), convert< mpq_class, cln::cl_RA >(), gcd(), gcd_assign(), getNum(), lcm(), carl::Numeric< T >::maybeIntegralize(), carl::Numeric< T >::maybeRationalize(), carl::RationalFunction< Pol, AutoSimplify >::nominator(), carl::RationalFunction< Pol, AutoSimplify >::nominatorAsNumber(), carl::Numeric< T >::operator typename IntegralType< T >::type(), carl::ConstructorPrinter::operator()(), carl::CArLConverter::toGMP(), carl::Number< mpq_class >::toInt(), carl::Number< cln::cl_RA >::toInt(), toInt< cln::cl_I >(), toInt< mpz_class >(), and toString().
getNum() [2/4]
mpz_class carl::getNum (const mpq_class & n) inline
Definition at line 67 of file operations.h.
getNum() [3/4]
mpz_class carl::getNum (const mpz_class & n) inline
Definition at line 71 of file operations.h.
getNum() [4/4]
mpz_class carl::getNum (const FLOAT_T< mpq_class > & _in) inline
Implicitly converts the number to a rational and returns the nominator.
Parameters
_in Number.
Returns
GMP interger which holds the result.
Definition at line 1589 of file FLOAT_T.h.
getOtherBoundType()
static BoundType carl::getOtherBoundType (BoundType type) inline static
Definition at line 33 of file BoundType.h.
getRationalAssignmentsFromModel()
template<typename Rational , typename Poly > bool carl::getRationalAssignmentsFromModel (const Model< Rational, Poly > & _model, std::map< Variable, Rational > & _rationalAssigns)
Obtains all assignments which can be transformed to rationals and stores them in the passed map.
Parameters
_model The model from which to obtain the rational assignments.
_rationalAssigns The map to store the rational assignments in.
Returns
true, if the entire model could be transformed to rational assignments. (not possible if, e.g., sqrt is contained)
getSort()
template<typename... Args> Sort carl::getSort (Args &&... args) inline
Gets the sort specified by the arguments.
Forwards to SortManager::getSort().
Definition at line 311 of file SortManager.h.
getStrictestBoundType()
static BoundType carl::getStrictestBoundType (BoundType type1, BoundType type2) inline static
Definition at line 27 of file BoundType.h.
getWeakestBoundType()
static BoundType carl::getWeakestBoundType (BoundType type1, BoundType type2) inline static
Definition at line 22 of file BoundType.h.
ginacDivide()
template<typename Poly > bool carl::ginacDivide (const Poly & polyA, const Poly & polyB, Poly & result)
Definition at line 161 of file OldGinacConverter.h.
ginacFactorization()
template<typename Poly > Factors<Poly> carl::ginacFactorization (const Poly & poly)
Definition at line 167 of file OldGinacConverter.h.
Referenced by factorization().
ginacGcd()
template<typename Poly > Poly carl::ginacGcd (const Poly & polyA, const Poly & polyB)
Definition at line 155 of file OldGinacConverter.h.
handle_signal()
static void carl::handle_signal (int signal) static
Actual signal handler.
Definition at line 80 of file debug.cpp.
Referenced by install_signal_handler().
has_method_struct()
carl::has_method_struct (normalize)
hash_add() [1/5]
template<typename T > void carl::hash_add (std::size_t & seed, const T & value) inline
Add hash of the given value to the hash seed.
Used hash_combine with the result of std::hash<T>.
Definition at line 22 of file hash.h.
Referenced by carl::UFModel::getHash(), hash_add(), hash_all(), std::hash< carl::UFContent >::operator()(), std::hash< carl::UFInstanceContent >::operator()(), and std::hash< carl::PBConstraint< Pol > >::operator()().
hash_add() [2/5]
template<> void carl::hash_add (std::size_t & seed, const std::size_t & value) inline
Add hash of the given value to the hash seed.
Definition at line 30 of file hash.h.
hash_add() [3/5]
template<typename First , typename... Tail> void carl::hash_add (std::size_t & seed, const First & value, Tail &&... tail) inline
Variadic version of hash_add to add an arbitrary number of values to the seed.
Definition at line 38 of file hash.h.
hash_add() [4/5]
template<typename T1 , typename T2 > void carl::hash_add (std::size_t & seed, const std::pair< T1, T2 > & p) inline
Add hash of both elements of a std::pair to the seed.
Definition at line 47 of file hash.h.
hash_add() [5/5]
template<typename T > void carl::hash_add (std::size_t & seed, const std::vector< T > & v) inline
Add hash of all elements of a std::vector to the seed.
Definition at line 56 of file hash.h.
hash_all()
template<typename... Args> std::size_t carl::hash_all (Args &&... args) inline
Hashes an arbitrary number of values.
Uses hash_add with a seed of 0.
Definition at line 65 of file hash.h.
Referenced by std::hash< mpq_class >::operator()(), std::hash< carl::SortValue >::operator()(), std::hash< carl::MultivariateRoot< Pol > >::operator()(), std::hash< carl::VariableComparison< Pol > >::operator()(), std::hash< carl::PBConstraint< Pol > >::operator()(), std::hash< carl::RealAlgebraicNumber< Number > >::operator()(), std::hash< carl::BVUnaryContent >::operator()(), std::hash< carl::BVBinaryContent >::operator()(), std::hash< carl::BVExtractContent >::operator()(), std::hash< carl::RationalFunction< Pol, AS > >::operator()(), std::hash< carl::Term< Coefficient > >::operator()(), and std::hash< carl::Interval< Number > >::operator()().
hash_combine()
void carl::hash_combine (std::size_t & seed, std::size_t value) inline
Add a value to the given hash seed.
This method is a copy of boost::hash_combine(). It is reimplemented here to avoid including all of boost/functional/hash.hpp for this single line of code.
Definition at line 13 of file hash.h.
Referenced by hash_add().
highestPower()
template<typename Number > Number carl::highestPower (const Number & n) inline
Returns the highest power of two below n.
Can also be seen as the highest bit set in n.
Parameters
n
Returns
Definition at line 202 of file operations.h.
Referenced by subresultants().
hirstMaceyBound()
template<typename Coeff > Coeff carl::hirstMaceyBound (const UnivariatePolynomial< Coeff > & p)
Definition at line 33 of file RootBounds.h.
init()
int carl::init () inline
The routine for initializing the carl library.
Which is called automatically by including this header. TODO prevent outside access.
Definition at line 31 of file initialize.h.
Referenced by initialize(), and tuple_accumulate().
initialize()
int carl::initialize () inline
Method to ensure that upon inclusion, init() is called exactly once.
TODO prevent outside access.
Definition at line 49 of file initialize.h.
install_signal_handler()
static bool carl::install_signal_handler () static noexcept
Installs the signal handler.
Definition at line 93 of file debug.cpp.
inverse() [1/2]
Relation carl::inverse (Relation r) inline
Definition at line 36 of file Relation.h.
Referenced by carl::VariableComparison< Pol >::asConstraint(), carl::VariableComparison< Pol >::invertRelation(), carl::PBConstraint< Poly >::negate(), carl::Constraint< Poly >::negation(), and carl::constraints::toPolynomialConstraints().
inverse() [2/2]
BVCompareRelation carl::inverse (BVCompareRelation _c) inline
Definition at line 57 of file BVCompareRelation.h.
isInf()
bool carl::isInf (double d) inline
Definition at line 50 of file operations.h.
Referenced by isNumber().
isInfinity()
template<typename FloatType > bool carl::isInfinity (const FLOAT_T< FloatType > & _in) inline
Definition at line 1600 of file FLOAT_T.h.
isInteger() [1/11]
template<typename Number > bool carl::isInteger (const RealAlgebraicNumber< Number > & n) inline
Definition at line 20 of file RealAlgebraicNumberOperations.h.
Referenced by carl::cad::SampleSet< Number >::SampleComparator::compareInt(), carl::Term< typename Polynomial::CoeffType >::integerValued(), carl::SqrtEx< Poly >::isInteger(), isInteger(), carl::ran::IntervalContent< Number >::isIntegral(), carl::RealAlgebraicNumber< carl::Number >::isIntegral(), carl::Number< cln::cl_RA >::lcm(), lcm(), carl::Numeric< T >::maybeIntegralize(), carl::Numeric< T >::maybeRationalize(), carl::Numeric< T >::operator typename IntegralType< T >::type(), carl::Number< mpq_class >::toInt(), carl::Number< cln::cl_RA >::toInt(), toInt< cln::cl_I >(), and toInt< mpz_class >().
isInteger() [2/11]
bool carl::isInteger (double d) inline
Definition at line 62 of file operations.h.
isInteger() [3/11]
bool carl::isInteger (sint) inline
Definition at line 67 of file operations.h.
isInteger() [4/11]
bool carl::isInteger (const cln::cl_I &) inline
Check if a number is integral.
As cln::cl_I are always integral, this method returns true.
Parameters
An integer.
Returns
true.
Definition at line 83 of file operations.h.
isInteger() [5/11]
bool carl::isInteger (const mpq_class & n) inline
Definition at line 83 of file operations.h.
isInteger() [6/11]
bool carl::isInteger (const mpz_class &) inline
Definition at line 87 of file operations.h.
isInteger() [7/11]
bool carl::isInteger (const cln::cl_RA & n) inline
Check if a fraction is integral.
Parameters
n A fraction.
Returns
true.
Definition at line 92 of file operations.h.
isInteger() [8/11]
template<typename IntegerT > bool carl::isInteger (const GFNumber< IntegerT > &) inline
Todo:
Implement this
Parameters
Definition at line 200 of file GFNumber.h.
isInteger() [9/11]
template<typename T > bool carl::isInteger (const Numeric< T > & _value) inline
Definition at line 228 of file Numeric.h.
isInteger() [10/11]
template<typename FloatType > bool carl::isInteger (const FLOAT_T< FloatType > & in) inline
Definition at line 1355 of file FLOAT_T.h.
isInteger() [11/11]
template<typename Number > bool carl::isInteger (const Interval< Number > & n) inline
Definition at line 2065 of file Interval.h.
isNaN()
bool carl::isNaN (double d) inline
Definition at line 43 of file operations.h.
Referenced by isNumber().
isNan()
template<typename FloatType > bool carl::isNan (const FLOAT_T< FloatType > & _in) inline
Definition at line 1605 of file FLOAT_T.h.
isNegative() [1/7]
bool carl::isNegative (sint n) inline
Definition at line 39 of file operations.h.
isNegative() [2/7]
bool carl::isNegative (const cln::cl_I & n) inline
Definition at line 51 of file operations.h.
Referenced by mod(), quotient(), and SoSDecomposition().
isNegative() [3/7]
bool carl::isNegative (const cln::cl_RA & n) inline
Definition at line 55 of file operations.h.
isNegative() [4/7]
template<typename T , EnableIf< has_isNegative< T >> > bool carl::isNegative (const T & t) inline
Definition at line 56 of file operations_generic.h.
isNegative() [5/7]
bool carl::isNegative (const mpz_class & n) inline
Definition at line 59 of file operations.h.
isNegative() [6/7]
bool carl::isNegative (const mpq_class & n) inline
Definition at line 63 of file operations.h.
isNegative() [7/7]
bool carl::isNegative (double d) inline
Definition at line 71 of file operations.h.
isNumber()
bool carl::isNumber (double d) inline
Definition at line 58 of file operations.h.
isOne() [1/9]
bool carl::isOne (const rational & n) inline
Definition at line 29 of file operations.h.
isOne() [2/9]
template<typename T , EnableIf< has_isOne< T >> > bool carl::isOne (const T & t) inline
Definition at line 32 of file operations_generic.h.
isOne() [3/9]
bool carl::isOne (sint n) inline
Definition at line 33 of file operations.h.
isOne() [4/9]
bool carl::isOne (const cln::cl_I & n) inline
Definition at line 35 of file operations.h.
isOne() [5/9]
bool carl::isOne (const cln::cl_RA & n) inline
Definition at line 39 of file operations.h.
isOne() [6/9]
bool carl::isOne (const mpz_class & n) inline
Definition at line 43 of file operations.h.
isOne() [7/9]
bool carl::isOne (const mpq_class & n) inline
Definition at line 47 of file operations.h.
isOne() [8/9]
template<typename Number > static bool carl::isOne (const Interval< Number > & _in) static
Check if this interval is a point-interval containing 1.
Definition at line 78 of file Interval.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::Factorization< P >::checkFactorization(), compare(), carl::DiophantineEquations< Integer >::EEAlift(), boost::spirit::traits::is_equal_to_one(), isInteger(), carl::Term< typename Polynomial::CoeffType >::isOne(), carl::RationalFunction< Pol, AutoSimplify >::isOne(), carl::FactorizedPolynomial< P >::isOne(), carl::model::substituteIn(), carl::VarSolutionFormula< carl::Polynomial >::VarSolutionFormula(), carl::MapleStream::write(), carl::QEPCADStream::write(), and carl::SMTLIBStream::write().
isOne() [9/9]
template<typename IntegerT > static bool carl::isOne (const GFNumber< IntegerT > & _in) static
Definition at line 180 of file GFNumber.h.
isPartOf()
template<typename Rational , typename Poly > bool carl::isPartOf (const std::map< Variable, Rational > & _assignment, const Model< Rational, Poly > & _model)
isPositive() [1/7]
bool carl::isPositive (sint n) inline
Definition at line 36 of file operations.h.
isPositive() [2/7]
bool carl::isPositive (const cln::cl_I & n) inline
Definition at line 43 of file operations.h.
isPositive() [3/7]
template<typename T , EnableIf< has_isPositive< T >> > bool carl::isPositive (const T & t) inline
Definition at line 44 of file operations_generic.h.
isPositive() [4/7]
bool carl::isPositive (const cln::cl_RA & n) inline
Definition at line 47 of file operations.h.
isPositive() [5/7]
bool carl::isPositive (const mpz_class & n) inline
Definition at line 51 of file operations.h.
isPositive() [6/7]
bool carl::isPositive (const mpq_class & n) inline
Definition at line 55 of file operations.h.
isPositive() [7/7]
bool carl::isPositive (double d) inline
Definition at line 75 of file operations.h.
isStrict()
bool carl::isStrict (Relation r) inline
Definition at line 58 of file Relation.h.
Referenced by carl::SimpleConstraint< LhsType >::isTrivialFalse(), isWeak(), and carl::Constraint< Poly >::relationIsStrict().
isWeak()
bool carl::isWeak (Relation r) inline
Definition at line 61 of file Relation.h.
Referenced by carl::SimpleConstraint< LhsType >::isTrivialTrue(), and carl::Constraint< Poly >::relationIsWeak().
isZero() [1/12]
template<typename Number > bool carl::isZero (const RealAlgebraicNumber< Number > & n) inline
Definition at line 15 of file RealAlgebraicNumberOperations.h.
Referenced by carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::addTerm(), ceil(), carl::FLOAT_T< FloatType >::div_assign(), carl::LazardEvaluation< Rational, Poly >::evaluatesToZero(), floor(), carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::getMaxTerm(), carl::Term< typename Polynomial::CoeffType >::isZero(), carl::RealAlgebraicNumber< carl::Number >::isZero(), carl::RationalFunction< Pol, AutoSimplify >::isZero(), carl::FactorizedPolynomial< P >::isZero(), isZero(), lagrangeBound(), carl::parser::isDivisible< true >::operator()(), operator*=(), carl::parser::RationalPolicies< T >::parse_frac_n(), carl::TermAdditionManager< carl::MultivariatePolynomial, Ordering >::readTerms(), round(), SoSDecomposition(), sqrt_exact(), sqrt_fast(), and carl::model::substituteIn().
isZero() [2/12]
template<typename T , EnableIf< has_isZero< T >> > bool carl::isZero (const T & t) inline
Definition at line 20 of file operations_generic.h.
isZero() [3/12]
bool carl::isZero (const rational & n) inline
Definition at line 26 of file operations.h.
isZero() [4/12]
bool carl::isZero (const cln::cl_I & n) inline
Definition at line 27 of file operations.h.
isZero() [5/12]
bool carl::isZero (sint n) inline
Informational functions.
The following functions return informations about the given numbers.
Definition at line 27 of file operations.h.
isZero() [6/12]
bool carl::isZero (double n) inline
Definition at line 30 of file operations.h.
isZero() [7/12]
bool carl::isZero (const cln::cl_RA & n) inline
Definition at line 31 of file operations.h.
isZero() [8/12]
bool carl::isZero (const mpz_class & n) inline
Informational functions.
The following functions return informations about the given numbers.
Definition at line 35 of file operations.h.
isZero() [9/12]
bool carl::isZero (const mpq_class & n) inline
Definition at line 39 of file operations.h.
isZero() [10/12]
template<typename Number > static bool carl::isZero (const Interval< Number > & _in) static
Check if this interval is a point-interval containing 0.
Definition at line 69 of file Interval.h.
isZero() [11/12]
template<typename IntegerT > static bool carl::isZero (const GFNumber< IntegerT > & _in) static
Definition at line 175 of file GFNumber.h.
isZero() [12/12]
template<typename FloatType > bool carl::isZero (const FLOAT_T< FloatType > & _in) inline
Definition at line 1595 of file FLOAT_T.h.
lagrangeBound()
template<typename Coeff > Coeff carl::lagrangeBound (const UnivariatePolynomial< Coeff > & p)
Definition at line 53 of file RootBounds.h.
lazyDiv()
template<typename C , typename O , typename P > std::pair<MultivariatePolynomial<C,O,P>,MultivariatePolynomial<C,O,P> > carl::lazyDiv (const MultivariatePolynomial< C, O, P > & _polyA, const MultivariatePolynomial< C, O, P > & _polyB)
Definition at line 1323 of file MultivariatePolynomial.h.
lcm() [1/6]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::lcm (const MultivariatePolynomial< C, O, P > & a, const MultivariatePolynomial< C, O, P > & b)
Referenced by carl::Number< cln::cl_RA >::gcd(), carl::Number< cln::cl_I >::lcm(), and carl::Number< cln::cl_RA >::lcm().
lcm() [2/6]
template<typename T > Numeric<T> carl::lcm (const Numeric< T > & , const Numeric< T > &)
lcm() [3/6]
mpz_class carl::lcm (const mpz_class & a, const mpz_class & b) inline
Definition at line 308 of file operations.h.
lcm() [4/6]
mpq_class carl::lcm (const mpq_class & a, const mpq_class & b) inline
Definition at line 352 of file operations.h.
Referenced by gcd(), gcd_assign(), and lcm().
lcm() [5/6]
cln::cl_I carl::lcm (const cln::cl_I & a, const cln::cl_I & b) inline
Calculate the least common multiple of two integers.
Parameters
a First argument.
b Second argument.
Returns
Lcm of a and b.
Definition at line 371 of file operations.h.
lcm() [6/6]
cln::cl_RA carl::lcm (const cln::cl_RA & a, const cln::cl_RA & b) inline
Calculate the least common multiple of two fractions.
Asserts that the arguments are integral.
Parameters
a First argument.
b Second argument.
Returns
Lcm of a and b.
Definition at line 382 of file operations.h.
log() [1/5]
double carl::log (double in) inline
Definition at line 187 of file operations.h.
Referenced by log(), and log10().
log() [2/5]
mpq_class carl::log (const mpq_class & n) inline
Definition at line 366 of file operations.h.
log() [3/5]
cln::cl_RA carl::log (const cln::cl_RA & n) inline
Definition at line 399 of file operations.h.
log() [4/5]
template<typename FloatType > FLOAT_T<FloatType> carl::log (const FLOAT_T< FloatType > & _in) inline
Method which returns the logarithm of the passed number.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 1426 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::log_assign().
log() [5/5]
template<typename Number > Interval<Number> carl::log (const Interval< Number > & _in) inline
Method which returns the logarithm of the passed number.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 2122 of file Interval.h.
Referenced by carl::Number< cln::cl_RA >::log(), carl::Number< mpq_class >::log(), carl::FLOAT_T< FloatType >::log(), carl::rounding< Number >::log_down(), and carl::rounding< Number >::log_up().
log10() [1/3]
double carl::log10 (double in) inline
Definition at line 190 of file operations.h.
Referenced by log10().
log10() [2/3]
mpq_class carl::log10 (const mpq_class & n) inline
Definition at line 369 of file operations.h.
log10() [3/3]
cln::cl_RA carl::log10 (const cln::cl_RA & n) inline
Definition at line 402 of file operations.h.
makePolynomial() [1/3]
template<typename Pol , EnableIf< needs_cache< Pol >> = dummy> Pol carl::makePolynomial (typename Pol::PolyType && _poly)
makePolynomial() [2/3]
template<typename Pol , EnableIf< needs_cache< Pol >> = dummy> Pol carl::makePolynomial (carl::Variable::Arg _var)
Definition at line 63 of file Constraint.h.
makePolynomial() [3/3]
template<typename Pol , EnableIf< needs_cache< Pol >> = dummy> Pol carl::makePolynomial (const typename Pol::PolyType & _poly)
Definition at line 57 of file Constraint.h.
mod() [1/4]
uint carl::mod (uint n, uint m) inline
Definition at line 141 of file operations.h.
mod() [2/4]
sint carl::mod (sint n, sint m) inline
Definition at line 144 of file operations.h.
Referenced by div(), and div_assign().
mod() [3/4]
mpz_class carl::mod (const mpz_class & n, const mpz_class & m) inline
Definition at line 434 of file operations.h.
mod() [4/4]
cln::cl_I carl::mod (const cln::cl_I & a, const cln::cl_I & b) inline
Calculate the remainder of the integer division.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 454 of file operations.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::Number< cln::cl_I >::div(), carl::Number< mpz_class >::div(), div(), carl::parser::isDivisible< true >::operator()(), carl::Number< mpz_class >::remainder(), remainder(), and carl::GaloisField< Integer >::symmetricModulo().
mpqmanager()
mpq_manager<true>& carl::mpqmanager () inline
Definition at line 21 of file operations.h.
mpzmanager()
mpz_manager<true>& carl::mpzmanager () inline
Definition at line 17 of file operations.h.
multivariateTarskiQuery()
template<typename Number > int carl::multivariateTarskiQuery (const MultivariatePolynomial< Number > & Q, const MultiplicationTable< Number > & table)
Definition at line 18 of file MultivariateTarskiQuery.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()().
newSortValue()
SortValue carl::newSortValue (const Sort & _sort) inline
Creates a new value for the given sort.
Parameters
_sort The sort to create a new value for.
Returns
The resulting sort value.
Definition at line 60 of file SortValueManager.h.
newtonSums()
template<typename Coeff > std::vector<Coeff> carl::newtonSums (const std::vector< Coeff > & newtonSums)
Definition at line 18 of file CharPol.h.
Referenced by charPol().
newUFInstance() [1/2]
UFInstance carl::newUFInstance (const UninterpretedFunction & _uf, std::vector< UVariable > && _args) inline
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
Parameters
_uf The underlying function of the uninterpreted function instance to get.
_args The arguments of the uninterpreted function instance to get.
Returns
The resulting uninterpreted function instance.
Definition at line 267 of file UFInstanceManager.h.
newUFInstance() [2/2]
UFInstance carl::newUFInstance (const UninterpretedFunction & _uf, const std::vector< UVariable > & _args) inline
Gets the uninterpreted function instance with the given name, domain, arguments and codomain.
Parameters
_uf The underlying function of the uninterpreted function instance to get.
_args The arguments of the uninterpreted function instance to get.
Returns
The resulting uninterpreted function instance.
Definition at line 278 of file UFInstanceManager.h.
newUninterpretedFunction()
UninterpretedFunction carl::newUninterpretedFunction (std::string _name, std::vector< Sort > _domain, Sort _codomain) inline
Gets the uninterpreted function with the given name, domain, arguments and codomain.
Parameters
_name The name of the uninterpreted function of the uninterpreted function to get.
_domain The domain of the uninterpreted function of the uninterpreted function to get.
_codomain The codomain of the uninterpreted function of the uninterpreted function to get.
Returns
The resulting uninterpreted function.
Definition at line 262 of file UFManager.h.
operator!=() [1/34]
template<typename LhsT > bool carl::operator!= (const SimpleConstraint< LhsT > & lhs, const SimpleConstraint< LhsT > & rhs)
Definition at line 68 of file SimpleConstraint.h.
operator!=() [2/34]
template<typename Number > bool carl::operator!= (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) inline
Definition at line 380 of file RealAlgebraicNumber.h.
operator!=() [3/34]
template<typename Coeff > bool carl::operator!= (const Term< Coeff > & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 462 of file Term.h.
operator!=() [4/34]
template<typename Coeff > bool carl::operator!= (const Term< Coeff > & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 466 of file Term.h.
operator!=() [5/34]
template<typename Coeff > bool carl::operator!= (const Term< Coeff > & lhs, Variable rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 470 of file Term.h.
operator!=() [6/34]
template<typename Coeff > bool carl::operator!= (const Term< Coeff > & lhs, const Coeff & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 474 of file Term.h.
operator!=() [7/34]
template<typename Coeff > bool carl::operator!= (const Monomial::Arg & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 478 of file Term.h.
operator!=() [8/34]
template<typename Coeff > bool carl::operator!= (Variable lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 482 of file Term.h.
operator!=() [9/34]
template<typename Coeff > bool carl::operator!= (const Coeff & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 486 of file Term.h.
operator!=() [10/34]
template<typename N > bool carl::operator!= (const ThomEncoding< N > & lhs, const ThomEncoding< N > & rhs)
Definition at line 530 of file ThomEncoding.h.
operator!=() [11/34]
template<typename N > bool carl::operator!= (const ThomEncoding< N > & lhs, const N & rhs)
Definition at line 544 of file ThomEncoding.h.
operator!=() [12/34]
template<typename N > bool carl::operator!= (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 557 of file ThomEncoding.h.
operator!=() [13/34]
template<typename Pol , bool AS> bool carl::operator!= (const RationalFunction< Pol, AS > & lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 560 of file RationalFunction.h.
operator!=() [14/34]
bool carl::operator!= (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 641 of file Monomial.h.
operator!=() [15/34]
bool carl::operator!= (const Monomial::Arg & lhs, Variable rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 645 of file Monomial.h.
operator!=() [16/34]
bool carl::operator!= (Variable lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 649 of file Monomial.h.
operator!=() [17/34]
template<typename P > bool carl::operator!= (const Constraint< P > & lhs, const Constraint< P > & rhs)
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs != rhs
Definition at line 792 of file Constraint.h.
operator!=() [18/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 817 of file MultivariatePolynomial.h.
operator!=() [19/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 821 of file MultivariatePolynomial.h.
operator!=() [20/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 825 of file MultivariatePolynomial.h.
operator!=() [21/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 829 of file MultivariatePolynomial.h.
operator!=() [22/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 833 of file MultivariatePolynomial.h.
operator!=() [23/34]
template<typename C , typename O , typename P > bool carl::operator!= (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 837 of file MultivariatePolynomial.h.
operator!=() [24/34]
template<typename C , typename O , typename P > bool carl::operator!= (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 841 of file MultivariatePolynomial.h.
operator!=() [25/34]
template<typename P > bool carl::operator!= (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the two arguments are not equal.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs != _rhs
operator!=() [26/34]
template<typename C , typename O , typename P > bool carl::operator!= (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 845 of file MultivariatePolynomial.h.
operator!=() [27/34]
template<typename P > bool carl::operator!= (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs) inline
Checks if the two arguments are not equal.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs != _rhs
Definition at line 846 of file FactorizedPolynomial.h.
operator!=() [28/34]
template<typename C , typename O , typename P > bool carl::operator!= (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 849 of file MultivariatePolynomial.h.
operator!=() [29/34]
template<typename P > bool carl::operator!= (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the two arguments are not equal.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs != _rhs
Definition at line 852 of file FactorizedPolynomial.h.
operator!=() [30/34]
template<typename C , typename O , typename P > bool carl::operator!= (const UnivariatePolynomial< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 854 of file MultivariatePolynomial.h.
operator!=() [31/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< C > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 858 of file MultivariatePolynomial.h.
operator!=() [32/34]
template<typename C , typename O , typename P > bool carl::operator!= (const UnivariatePolynomial< MultivariatePolynomial< C >> & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 862 of file MultivariatePolynomial.h.
operator!=() [33/34]
template<typename C , typename O , typename P > bool carl::operator!= (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< MultivariatePolynomial< C >> & rhs) inline
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
Definition at line 866 of file MultivariatePolynomial.h.
operator!=() [34/34]
template<typename Number > bool carl::operator!= (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if both intervals are unequal.
operator*() [1/43]
template<typename T > Numeric<T> carl::operator* (const Numeric< T > & , const Numeric< T > &)
operator*() [2/43]
Monomial::Arg carl::operator* (const Monomial::Arg & lhs, const Monomial::Arg & rhs)
Perform a multiplication involving a monomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 392 of file Monomial.cpp.
operator*() [3/43]
Monomial::Arg carl::operator* (const Monomial::Arg & lhs, Variable rhs)
Perform a multiplication involving a monomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 441 of file Monomial.cpp.
operator*() [4/43]
Monomial::Arg carl::operator* (Variable lhs, const Monomial::Arg & rhs)
Perform a multiplication involving a monomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 465 of file Monomial.cpp.
operator*() [5/43]
Monomial::Arg carl::operator* (Variable lhs, Variable rhs)
Perform a multiplication involving a monomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 469 of file Monomial.cpp.
operator*() [6/43]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 469 of file RationalFunction.h.
operator*() [7/43]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, const Pol & rhs)
Definition at line 474 of file RationalFunction.h.
operator*() [8/43]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, const Term< typename Pol::CoeffType > & rhs)
Definition at line 479 of file RationalFunction.h.
operator*() [9/43]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, const Monomial::Arg & rhs)
Definition at line 484 of file RationalFunction.h.
operator*() [10/43]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, Variable rhs)
Definition at line 489 of file RationalFunction.h.
operator*() [11/43]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, const typename Pol::CoeffType & rhs)
Definition at line 494 of file RationalFunction.h.
operator*() [12/43]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator* (const typename Pol::CoeffType & lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 499 of file RationalFunction.h.
operator*() [13/43]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator* (const RationalFunction< Pol, AS > & lhs, carl::sint rhs)
Definition at line 504 of file RationalFunction.h.
operator*() [14/43]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator* (carl::sint lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 509 of file RationalFunction.h.
operator*() [15/43]
mpq_class carl::operator* (const mpq_class & lhs, const mpq_class & rhs) inline
Definition at line 529 of file operations.h.
operator*() [16/43]
template<typename Coeff > Term<Coeff> carl::operator* (Term< Coeff > lhs, const Term< Coeff > & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 602 of file Term.h.
operator*() [17/43]
template<typename Coeff > Term<Coeff> carl::operator* (Term< Coeff > lhs, const Monomial::Arg & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 606 of file Term.h.
operator*() [18/43]
template<typename Coeff > Term<Coeff> carl::operator* (Term< Coeff > lhs, Variable rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 610 of file Term.h.
operator*() [19/43]
template<typename Coeff > Term<Coeff> carl::operator* (Term< Coeff > lhs, const Coeff & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 614 of file Term.h.
operator*() [20/43]
template<typename Coeff > Term<Coeff> carl::operator* (const Monomial::Arg & lhs, const Term< Coeff > & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 618 of file Term.h.
operator*() [21/43]
template<typename Coeff , EnableIf< carl::is_number< Coeff >> = dummy> Term<Coeff> carl::operator* (const Monomial::Arg & lhs, const Coeff & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 622 of file Term.h.
operator*() [22/43]
template<typename Coeff > Term<Coeff> carl::operator* (Variable lhs, const Term< Coeff > & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 626 of file Term.h.
operator*() [23/43]
template<typename Coeff > Term<Coeff> carl::operator* (Variable lhs, const Coeff & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 630 of file Term.h.
operator*() [24/43]
template<typename Coeff > Term<Coeff> carl::operator* (const Coeff & lhs, const Term< Coeff > & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 634 of file Term.h.
operator*() [25/43]
template<typename Coeff , EnableIf< carl::is_number< Coeff >> = dummy> Term<Coeff> carl::operator* (const Coeff & lhs, const Monomial::Arg & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 638 of file Term.h.
operator*() [26/43]
template<typename Coeff > Term<Coeff> carl::operator* (const Coeff & lhs, Variable rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 642 of file Term.h.
operator*() [27/43]
template<typename P > FactorizedPolynomial<P> carl::operator* (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs)
Perform a multiplication involving a polynomial.
Parameters
_lhs Left hand side.
_rhs Right hand side.
Returns
_lhs * _rhs
operator*() [28/43]
template<typename P > FactorizedPolynomial<P> carl::operator* (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs)
Perform a multiplication involving a polynomial.
Parameters
_lhs Left hand side.
_rhs Right hand side.
Returns
_lhs * _rhs
operator*() [29/43]
template<typename P > FactorizedPolynomial<P> carl::operator* (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Perform a multiplication involving a polynomial.
Parameters
_lhs Left hand side.
_rhs Right hand side.
Returns
_lhs * _rhs
Definition at line 1017 of file FactorizedPolynomial.h.
operator*() [30/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1267 of file MultivariatePolynomial.h.
operator*() [31/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1271 of file MultivariatePolynomial.h.
operator*() [32/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1275 of file MultivariatePolynomial.h.
operator*() [33/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1279 of file MultivariatePolynomial.h.
operator*() [34/43]
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator* (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1283 of file MultivariatePolynomial.h.
operator*() [35/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1287 of file MultivariatePolynomial.h.
operator*() [36/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1291 of file MultivariatePolynomial.h.
operator*() [37/43]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator* (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1295 of file MultivariatePolynomial.h.
operator*() [38/43]
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator* (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 1299 of file MultivariatePolynomial.h.
operator*() [39/43]
template<typename C , typename O , typename P > const MultivariatePolynomial<C, O, P> carl::operator* (const UnivariatePolynomial< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator*() [40/43]
template<typename C , typename O , typename P > const MultivariatePolynomial<C, O, P> carl::operator* (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< C > & rhs) inline
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
operator*() [41/43]
template<typename Number > Interval<Number> carl::operator* (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the multiplication of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator*() [42/43]
template<typename Number > Interval<Number> carl::operator* (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the multiplication of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator*() [43/43]
template<typename Number > Interval<Number> carl::operator* (const Interval< Number > & lhs, const Number & rhs) inline
Operator for the multiplication of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator*=() [1/7]
template<typename T > Numeric<T>& carl::operator*= (Numeric< T > & , const Numeric< T > &)
operator*=() [2/7]
template<typename Coeff > Term<Coeff>& carl::operator*= (Term< Coeff > & lhs, const Coeff & rhs)
Multiply a term with something and return the changed term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
Changed lhs.
Definition at line 385 of file Term.h.
operator*=() [3/7]
template<typename Coeff > Term<Coeff>& carl::operator*= (Term< Coeff > & lhs, Variable rhs)
Multiply a term with something and return the changed term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
Changed lhs.
Definition at line 394 of file Term.h.
operator*=() [4/7]
template<typename Coeff > Term<Coeff>& carl::operator*= (Term< Coeff > & lhs, const Monomial::Arg & rhs)
Multiply a term with something and return the changed term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
Changed lhs.
Definition at line 406 of file Term.h.
operator*=() [5/7]
template<typename Coeff > Term<Coeff>& carl::operator*= (Term< Coeff > & lhs, const Term< Coeff > & rhs)
Multiply a term with something and return the changed term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
Changed lhs.
Definition at line 418 of file Term.h.
operator*=() [6/7]
template<typename Number > Interval<Number>& carl::operator*= (Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the multiplication of an interval and a number with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator*=() [7/7]
template<typename Number > Interval<Number>& carl::operator*= (Interval< Number > & lhs, const Number & rhs) inline
Operator for the multiplication of an interval and a number with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator+() [1/42]
template<typename T > Numeric<T> carl::operator+ (const Numeric< T > & , const Numeric< T > &)
operator+() [2/42]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator+ (const RationalFunction< Pol, AS > & lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 404 of file RationalFunction.h.
operator+() [3/42]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator+ (const RationalFunction< Pol, AS > & lhs, const Pol & rhs)
Definition at line 409 of file RationalFunction.h.
operator+() [4/42]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator+ (const RationalFunction< Pol, AS > & lhs, const Term< typename Pol::CoeffType > & rhs)
Definition at line 414 of file RationalFunction.h.
operator+() [5/42]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator+ (const RationalFunction< Pol, AS > & lhs, const Monomial::Arg & rhs)
Definition at line 419 of file RationalFunction.h.
operator+() [6/42]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator+ (const RationalFunction< Pol, AS > & lhs, Variable rhs)
Definition at line 424 of file RationalFunction.h.
operator+() [7/42]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator+ (const RationalFunction< Pol, AS > & lhs, const typename Pol::CoeffType & rhs)
Definition at line 429 of file RationalFunction.h.
operator+() [8/42]
template<typename N > ThomEncoding<N> carl::operator+ (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 560 of file ThomEncoding.h.
operator+() [9/42]
template<typename P > FactorizedPolynomial<P> carl::operator+ (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs)
Performs an addition involving a polynomial.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs + _rhs
operator+() [10/42]
template<typename P > FactorizedPolynomial<P> carl::operator+ (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs)
Performs an addition involving a polynomial.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs + _rhs
operator+() [11/42]
template<typename P > FactorizedPolynomial<P> carl::operator+ (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Performs an addition involving a polynomial.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs + _rhs
Definition at line 975 of file FactorizedPolynomial.h.
operator+() [12/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1046 of file MultivariatePolynomial.h.
operator+() [13/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1050 of file MultivariatePolynomial.h.
operator+() [14/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1054 of file MultivariatePolynomial.h.
operator+() [15/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1058 of file MultivariatePolynomial.h.
operator+() [16/42]
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1062 of file MultivariatePolynomial.h.
operator+() [17/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1066 of file MultivariatePolynomial.h.
operator+() [18/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const Term< C > & lhs, const Term< C > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1070 of file MultivariatePolynomial.h.
operator+() [19/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const Term< C > & lhs, const Monomial::Arg & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1074 of file MultivariatePolynomial.h.
operator+() [20/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const Term< C > & lhs, Variable::Arg rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1078 of file MultivariatePolynomial.h.
operator+() [21/42]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator+ (const Term< C > & lhs, const C & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1082 of file MultivariatePolynomial.h.
operator+() [22/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1086 of file MultivariatePolynomial.h.
operator+() [23/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const Monomial::Arg & lhs, const Term< C > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1090 of file MultivariatePolynomial.h.
operator+() [24/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1094 of file MultivariatePolynomial.h.
operator+() [25/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const Monomial::Arg & lhs, Variable::Arg rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1098 of file MultivariatePolynomial.h.
operator+() [26/42]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator+ (const Monomial::Arg & lhs, const C & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1102 of file MultivariatePolynomial.h.
operator+() [27/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1106 of file MultivariatePolynomial.h.
operator+() [28/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (Variable::Arg lhs, const Term< C > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1110 of file MultivariatePolynomial.h.
operator+() [29/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (Variable::Arg lhs, const Monomial::Arg & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1114 of file MultivariatePolynomial.h.
operator+() [30/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (Variable::Arg lhs, Variable::Arg rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1118 of file MultivariatePolynomial.h.
operator+() [31/42]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator+ (Variable::Arg lhs, const C & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1122 of file MultivariatePolynomial.h.
operator+() [32/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1126 of file MultivariatePolynomial.h.
operator+() [33/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const C & lhs, const Term< C > & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1130 of file MultivariatePolynomial.h.
operator+() [34/42]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator+ (const C & lhs, const Monomial::Arg & rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1134 of file MultivariatePolynomial.h.
operator+() [35/42]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator+ (const C & lhs, Variable::Arg rhs) inline
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
Definition at line 1138 of file MultivariatePolynomial.h.
operator+() [36/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< C > & rhs)
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator+() [37/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const UnivariatePolynomial< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator+() [38/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< MultivariatePolynomial< C >> & rhs)
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator+() [39/42]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator+ (const UnivariatePolynomial< MultivariatePolynomial< C >> & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
operator+() [40/42]
template<typename Number > Interval<Number> carl::operator+ (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the addition of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator+() [41/42]
template<typename Number > Interval<Number> carl::operator+ (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the addition of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator+() [42/42]
template<typename Number > Interval<Number> carl::operator+ (const Interval< Number > & lhs, const Number & rhs) inline
Operator for the addition of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator++()
template<typename T > Numeric<T>& carl::operator++ (Numeric< T > &)
operator+=() [1/3]
template<typename T > Numeric<T>& carl::operator+= (Numeric< T > & , const Numeric< T > &)
operator+=() [2/3]
template<typename Number > Interval<Number>& carl::operator+= (Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the addition of an interval and a number with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator+=() [3/3]
template<typename Number > Interval<Number>& carl::operator+= (Interval< Number > & lhs, const Number & rhs) inline
Operator for the addition of an interval and a number with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator-() [1/41]
template<typename T > Numeric<T> carl::operator- (const Numeric< T > & , const Numeric< T > &)
operator-() [2/41]
template<typename T > Numeric<T> carl::operator- (const Numeric< T > &)
operator-() [3/41]
template<typename Coeff > Term<Coeff> carl::operator- (const Term< Coeff > & rhs)
Definition at line 370 of file Term.h.
operator-() [4/41]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs)
Definition at line 434 of file RationalFunction.h.
operator-() [5/41]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 439 of file RationalFunction.h.
operator-() [6/41]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs, const Pol & rhs)
Definition at line 444 of file RationalFunction.h.
operator-() [7/41]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs, const Term< typename Pol::CoeffType > & rhs)
Definition at line 449 of file RationalFunction.h.
operator-() [8/41]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs, const Monomial::Arg & rhs)
Definition at line 454 of file RationalFunction.h.
operator-() [9/41]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs, Variable rhs)
Definition at line 459 of file RationalFunction.h.
operator-() [10/41]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator- (const RationalFunction< Pol, AS > & lhs, const typename Pol::CoeffType & rhs)
Definition at line 464 of file RationalFunction.h.
operator-() [11/41]
template<typename P > FactorizedPolynomial<P> carl::operator- (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs)
Performs an subtraction involving a polynomial.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs - _rhs
operator-() [12/41]
template<typename P > FactorizedPolynomial<P> carl::operator- (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs)
Performs an subtraction involving a polynomial.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs - _rhs
operator-() [13/41]
template<typename P > FactorizedPolynomial<P> carl::operator- (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Performs an subtraction involving a polynomial.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs - _rhs
Definition at line 996 of file FactorizedPolynomial.h.
operator-() [14/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1161 of file MultivariatePolynomial.h.
operator-() [15/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1165 of file MultivariatePolynomial.h.
operator-() [16/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1169 of file MultivariatePolynomial.h.
operator-() [17/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1173 of file MultivariatePolynomial.h.
operator-() [18/41]
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1177 of file MultivariatePolynomial.h.
operator-() [19/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1181 of file MultivariatePolynomial.h.
operator-() [20/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (const Term< C > & lhs, const Term< C > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1185 of file MultivariatePolynomial.h.
operator-() [21/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (const Term< C > & lhs, const Monomial::Arg & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1189 of file MultivariatePolynomial.h.
operator-() [22/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (const Term< C > & lhs, Variable::Arg rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1193 of file MultivariatePolynomial.h.
operator-() [23/41]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const Term< C > & lhs, const C & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1197 of file MultivariatePolynomial.h.
operator-() [24/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1201 of file MultivariatePolynomial.h.
operator-() [25/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (const Monomial::Arg & lhs, const Term< C > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1205 of file MultivariatePolynomial.h.
operator-() [26/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1209 of file MultivariatePolynomial.h.
operator-() [27/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (const Monomial::Arg & lhs, Variable::Arg rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1213 of file MultivariatePolynomial.h.
operator-() [28/41]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const Monomial::Arg & lhs, const C & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1217 of file MultivariatePolynomial.h.
operator-() [29/41]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::operator- (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1221 of file MultivariatePolynomial.h.
operator-() [30/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (Variable::Arg lhs, const Term< C > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1225 of file MultivariatePolynomial.h.
operator-() [31/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (Variable::Arg lhs, const Monomial::Arg & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1229 of file MultivariatePolynomial.h.
operator-() [32/41]
template<MPOpTemplate > MultivariatePolynomial<C,O,P> carl::operator- (Variable::Arg lhs, Variable::Arg rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1233 of file MultivariatePolynomial.h.
operator-() [33/41]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (Variable::Arg lhs, const C & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1237 of file MultivariatePolynomial.h.
operator-() [34/41]
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1241 of file MultivariatePolynomial.h.
operator-() [35/41]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const C & lhs, const Term< C > & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1245 of file MultivariatePolynomial.h.
operator-() [36/41]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const C & lhs, const Monomial::Arg & rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1249 of file MultivariatePolynomial.h.
operator-() [37/41]
template<MPOpTemplate , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator- (const C & lhs, Variable::Arg rhs) inline
Performs an subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
Definition at line 1253 of file MultivariatePolynomial.h.
operator-() [38/41]
template<typename Number > Interval<Number> carl::operator- (const Interval< Number > & interval) inline
Unary minus.
Parameters
interval The operand.
Returns
Resulting interval.
operator-() [39/41]
template<typename Number > Interval<Number> carl::operator- (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the subtraction of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator-() [40/41]
template<typename Number > Interval<Number> carl::operator- (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the subtraction of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator-() [41/41]
template<typename Number > Interval<Number> carl::operator- (const Interval< Number > & lhs, const Number & rhs) inline
Operator for the subtraction of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator--()
template<typename T > Numeric<T>& carl::operator-- (Numeric< T > &)
operator-=() [1/3]
template<typename T > Numeric<T>& carl::operator-= (Numeric< T > & , const Numeric< T > &)
operator-=() [2/3]
template<typename Number > Interval<Number>& carl::operator-= (Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the subtraction of two intervals with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator-=() [3/3]
template<typename Number > Interval<Number>& carl::operator-= (Interval< Number > & lhs, const Number & rhs) inline
Operator for the subtraction of an interval and a number with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator/() [1/18]
template<typename T > Numeric<T> carl::operator/ (const Numeric< T > & , const Numeric< T > &)
operator/() [2/18]
mpz_class carl::operator/ (const mpz_class & n, const mpz_class & d) inline
Definition at line 455 of file operations.h.
operator/() [3/18]
mpq_class carl::operator/ (const mpq_class & n, const mpq_class & d) inline
Definition at line 467 of file operations.h.
operator/() [4/18]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, const RationalFunction< Pol, AS > & rhs)
Definition at line 514 of file RationalFunction.h.
operator/() [5/18]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, const Pol & rhs)
Definition at line 519 of file RationalFunction.h.
operator/() [6/18]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, const Term< typename Pol::CoeffType > & rhs)
Definition at line 524 of file RationalFunction.h.
operator/() [7/18]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, const Monomial::Arg & rhs)
Definition at line 529 of file RationalFunction.h.
operator/() [8/18]
template<typename Pol , bool AS, DisableIf< needs_cache< Pol >> = dummy> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, Variable rhs)
Definition at line 534 of file RationalFunction.h.
operator/() [9/18]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, const typename Pol::CoeffType & rhs)
Definition at line 539 of file RationalFunction.h.
operator/() [10/18]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::operator/ (const RationalFunction< Pol, AS > & lhs, unsigned long rhs)
Definition at line 544 of file RationalFunction.h.
operator/() [11/18]
cln::cl_I carl::operator/ (const cln::cl_I & a, const cln::cl_I & b) inline
Divide two integers.
Discards the remainder of the division.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 547 of file operations.h.
operator/() [12/18]
cln::cl_I carl::operator/ (const cln::cl_I & lhs, const int & rhs) inline
Definition at line 551 of file operations.h.
operator/() [13/18]
template<typename Coeff , EnableIf< carl::is_subset_of_rationals< Coeff >> = dummy> Term<Coeff> carl::operator/ (const Term< Coeff > & lhs, const Coeff & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 646 of file Term.h.
operator/() [14/18]
template<typename Coeff , EnableIf< carl::is_subset_of_rationals< Coeff >> = dummy> Term<Coeff> carl::operator/ (const Monomial::Arg & lhs, const Coeff & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 650 of file Term.h.
operator/() [15/18]
template<typename Coeff , EnableIf< carl::is_subset_of_rationals< Coeff >> = dummy> Term<Coeff> carl::operator/ (Variable & lhs, const Coeff & rhs) inline
Perform a multiplication involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
Definition at line 654 of file Term.h.
operator/() [16/18]
template<typename P > FactorizedPolynomial<P> carl::operator/ (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs) inline
Perform a multiplication involving a polynomial.
Parameters
_lhs Left hand side.
_rhs Right hand side.
Returns
_lhs * _rhs
Definition at line 1023 of file FactorizedPolynomial.h.
operator/() [17/18]
template<typename C , typename O , typename P , EnableIf< carl::is_number< C >> = dummy> MultivariatePolynomial<C,O,P> carl::operator/ (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
Definition at line 1318 of file MultivariatePolynomial.h.
operator/() [18/18]
template<typename Number > Interval<Number> carl::operator/ (const Interval< Number > & lhs, const Number & rhs) inline
Operator for the division of an interval and a number.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator/=() [1/2]
template<typename T > Numeric<T>& carl::operator/= (Numeric< T > & , const Numeric< T > &)
operator/=() [2/2]
template<typename Number > Interval<Number>& carl::operator/= (Interval< Number > & lhs, const Number & rhs) inline
Operator for the division of an interval and a number with assignment.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
Resulting interval.
operator<() [1/39]
template<typename Poly > bool carl::operator< (const VariableAssignment< Poly > & lhs, const VariableAssignment< Poly > & rhs)
Definition at line 56 of file VariableAssignment.h.
operator<() [2/39]
bool carl::operator< (const Sort & lhs, const Sort & rhs) inline
Parameters
_sort The sort to compare with.
Returns
true, if this sort is less than the given one.
Definition at line 77 of file Sort.h.
operator<() [3/39]
bool carl::operator< (const BVVariable & lhs, const BVVariable & rhs) inline
Definition at line 78 of file BVVariable.h.
operator<() [4/39]
bool carl::operator< (const BVVariable & lhs, const Variable & rhs) inline
Definition at line 81 of file BVVariable.h.
operator<() [5/39]
bool carl::operator< (const Variable & lhs, const BVVariable & rhs) inline
Definition at line 84 of file BVVariable.h.
operator<() [6/39]
bool carl::operator< (const SortContent & lhs, const SortContent & rhs) inline
Parameters
lhs Left SortContent
rhs Right SortContent
Returns
lhs < rhs
Definition at line 88 of file SortManager.h.
operator<() [7/39]
template<typename Poly > bool carl::operator< (const MultivariateRoot< Poly > & lhs, const MultivariateRoot< Poly > & rhs) inline
Definition at line 133 of file MultivariateRoot.h.
operator<() [8/39]
template<typename Poly > bool carl::operator< (const VariableComparison< Poly > & lhs, const VariableComparison< Poly > & rhs)
Definition at line 134 of file VariableComparison.h.
operator<() [9/39]
bool carl::operator< (const ModelVariable & lhs, const ModelVariable & rhs) inline
Returns
true, if the first argument is a variable and the second is a function or if both are variables and the first is smaller (lower id) or if both are function and the first smaller (lower id).
Definition at line 138 of file ModelVariable.h.
operator<() [10/39]
template<typename Pol > bool carl::operator< (const PBConstraint< Pol > & lhs, const PBConstraint< Pol > & rhs) inline
Definition at line 144 of file PBConstraint.h.
operator<() [11/39]
template<typename Number > bool carl::operator< (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) inline
Definition at line 384 of file RealAlgebraicNumber.h.
operator<() [12/39]
template<typename Coeff > bool carl::operator< (const Term< Coeff > & lhs, const Term< Coeff > & rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [13/39]
template<typename Coeff > bool carl::operator< (const Term< Coeff > & lhs, const Monomial::Arg & rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [14/39]
template<typename Coeff > bool carl::operator< (const Term< Coeff > & lhs, Variable rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [15/39]
template<typename Coeff > bool carl::operator< (const Term< Coeff > & lhs, const Coeff & rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [16/39]
template<typename Coeff > bool carl::operator< (const Monomial::Arg & lhs, const Term< Coeff > & rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [17/39]
template<typename Coeff > bool carl::operator< (Variable lhs, const Term< Coeff > & rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [18/39]
template<typename Coeff > bool carl::operator< (const Coeff & lhs, const Term< Coeff > & rhs)
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator<() [19/39]
template<typename N > bool carl::operator< (const ThomEncoding< N > & lhs, const ThomEncoding< N > & rhs)
Definition at line 520 of file ThomEncoding.h.
operator<() [20/39]
template<typename N > bool carl::operator< (const ThomEncoding< N > & lhs, const N & rhs)
Definition at line 534 of file ThomEncoding.h.
operator<() [21/39]
template<typename N > bool carl::operator< (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 547 of file ThomEncoding.h.
operator<() [22/39]
bool carl::operator< (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 653 of file Monomial.h.
operator<() [23/39]
bool carl::operator< (const Monomial::Arg & lhs, Variable rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 666 of file Monomial.h.
operator<() [24/39]
bool carl::operator< (Variable lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 672 of file Monomial.h.
operator<() [25/39]
template<typename P > bool carl::operator< (const Constraint< P > & lhs, const Constraint< P > & rhs)
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs < rhs
Definition at line 802 of file Constraint.h.
operator<() [26/39]
template<typename P > bool carl::operator< (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs)
Checks if the first arguments is less than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs < _rhs
operator<() [27/39]
template<typename P > bool carl::operator< (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs)
Checks if the first arguments is less than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs < _rhs
operator<() [28/39]
template<typename P > bool carl::operator< (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is less than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs < _rhs
Definition at line 873 of file FactorizedPolynomial.h.
operator<() [29/39]
template<typename C , typename O , typename P > bool carl::operator< (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [30/39]
template<typename C , typename O , typename P > bool carl::operator< (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [31/39]
template<typename C , typename O , typename P > bool carl::operator< (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [32/39]
template<typename C , typename O , typename P > bool carl::operator< (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [33/39]
template<typename C , typename O , typename P > bool carl::operator< (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [34/39]
template<typename C , typename O , typename P > bool carl::operator< (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [35/39]
template<typename C , typename O , typename P > bool carl::operator< (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [36/39]
template<typename C , typename O , typename P > bool carl::operator< (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [37/39]
template<typename C , typename O , typename P > bool carl::operator< (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the first arguments is less than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs < rhs
operator<() [38/39]
template<typename Number > bool carl::operator< (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the lefthand side is smaller than the righthand side.
operator<() [39/39]
template<typename Number > bool carl::operator< (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the lefthand side is smaller than the righthand side.
Definition at line 2046 of file Interval.h.
operator<<() [1/57]
std::ostream& carl::operator<< (std::ostream & os, const Logic & l) inline
Definition at line 11 of file Logic.h.
operator<<() [2/57]
std::ostream& carl::operator<< (std::ostream & os, CompareResult cr) inline
Definition at line 14 of file CompareResult.h.
operator<<() [3/57]
std::ostream& carl::operator<< (std::ostream & _os, const Sort & _sort)
Parameters
_os The output stream to print on.
_sort The sort to print.
Returns
The output stream after printing the given sort on it.
Definition at line 18 of file Sort.cpp.
operator<<() [4/57]
std::ostream& carl::operator<< (std::ostream & os, const Relation & r) inline
Definition at line 21 of file Relation.h.
operator<<() [5/57]
std::ostream& carl::operator<< (std::ostream & os, const SortValue & sv)
Parameters
_os The output stream to print on.
_sortValue The sort value to print.
Returns
The output stream after printing the given sort value on it.
Definition at line 25 of file SortValue.cpp.
operator<<() [6/57]
std::ostream& carl::operator<< (std::ostream & os, const Sign & sign) inline
Definition at line 28 of file Sign.h.
operator<<() [7/57]
std::ostream& carl::operator<< (std::ostream & os, Definiteness d) inline
Definition at line 29 of file Definiteness.h.
operator<<() [8/57]
std::ostream& carl::operator<< (std::ostream & _os, const UninterpretedFunction & _ufun)
Parameters
_os The output stream to print on.
_ufun The uninterpreted function to print.
Returns
The output stream after printing the given uninterpreted function on it.
Definition at line 33 of file UninterpretedFunction.cpp.
operator<<() [9/57]
std::ostream& carl::operator<< (std::ostream & _os, const UFInstance & _ufun)
Parameters
_os The output stream to print on.
_ufun The uninterpreted function instance to print.
Returns
The output stream after printing the given uninterpreted function instance on it.
Definition at line 37 of file UFInstance.cpp.
operator<<() [10/57]
std::ostream& carl::operator<< (std::ostream & os, const TimingCollector & tc) inline
Definition at line 38 of file TimingCollector.h.
operator<<() [11/57]
template<typename TT > std::ostream& carl::operator<< (std::ostream & os, const Covering< TT > & ri)
Definition at line 45 of file Covering.h.
operator<<() [12/57]
std::ostream& carl::operator<< (std::ostream & _os, const BVCompareRelation & _r) inline
Definition at line 47 of file BVCompareRelation.h.
operator<<() [13/57]
std::ostream& carl::operator<< (std::ostream & os, const Timer & t) inline
Streaming operator for a Timer.
Prints the result of t.passed().
Parameters
os Output stream.
t Timer.
Returns
os.
Definition at line 51 of file Timer.h.
operator<<() [14/57]
std::ostream& carl::operator<< (std::ostream & os, const InfinityValue & iv) inline
Definition at line 51 of file ModelValue.h.
operator<<() [15/57]
template<typename T > std::ostream& carl::operator<< (std::ostream & os, const std::forward_list< T > & l) inline
Output a std::forward_list with arbitrary content.
The format is [<item>, <item>, ...]
Parameters
os Output stream.
l list to be printed.
Returns
Output stream.
Definition at line 54 of file streamingOperators.h.
operator<<() [16/57]
template<typename Poly > std::ostream& carl::operator<< (std::ostream & os, const VariableAssignment< Poly > & va)
Definition at line 60 of file VariableAssignment.h.
operator<<() [17/57]
std::ostream& carl::operator<< (std::ostream & os, BVTermType type) inline
Definition at line 69 of file BVTerm.h.
operator<<() [18/57]
std::ostream& carl::operator<< (std::ostream & os, const VariableType & t) inline
Streaming operator for VariableType.
Parameters
os Output Stream.
t VariableType.
Returns
os.
Definition at line 71 of file Variable.h.
operator<<() [19/57]
template<typename T > std::ostream& carl::operator<< (std::ostream & os, const std::list< T > & l) inline
Output a std::list with arbitrary content.
The format is [<length>: <item>, <item>, ...]
Parameters
os Output stream.
l list to be printed.
Returns
Output stream.
Definition at line 73 of file streamingOperators.h.
operator<<() [20/57]
template<typename LhsT > std::ostream& carl::operator<< (std::ostream & os, const SimpleConstraint< LhsT > & rhs)
Definition at line 74 of file SimpleConstraint.h.
operator<<() [21/57]
template<typename Rational , typename Poly > std::ostream& carl::operator<< (std::ostream & os, const ModelSubstitution< Rational, Poly > & ms) inline
Definition at line 74 of file ModelSubstitution.h.
operator<<() [22/57]
template<typename Rational , typename Poly > std::ostream& carl::operator<< (std::ostream & os, const std::shared_ptr< ModelSubstitution< Rational, Poly >> & ms) inline
Definition at line 79 of file ModelSubstitution.h.
operator<<() [23/57]
std::ostream& carl::operator<< (std::ostream & _os, const UFModel & _ufm)
Parameters
_os The output stream to print on.
_ufm The uninterpreted function model to print.
Returns
The output stream after printing the given uninterpreted function model on it.
Definition at line 79 of file UFModel.cpp.
operator<<() [24/57]
std::ostream& carl::operator<< (std::ostream & os, FormulaType t) inline
Definition at line 86 of file FormulaContent.h.
operator<<() [25/57]
template<typename P > std::ostream& carl::operator<< (std::ostream & _out, const Factorization< P > & _factorization)
operator<<() [26/57]
template<typename Key , typename Value , typename Comparator > std::ostream& carl::operator<< (std::ostream & os, const std::map< Key, Value, Comparator > & m) inline
Output a std::map with arbitrary content.
The format is {<key>:<value>, <key>:<value>, ...}
Parameters
os Output stream.
m map to be printed.
Returns
Output stream.
Definition at line 92 of file streamingOperators.h.
operator<<() [27/57]
template<typename U , typename V > std::ostream& carl::operator<< (std::ostream & os, const std::pair< U, V > & p) inline
Output a std::pair with arbitrary content.
The format is (<first>, <second>)
Parameters
os Output stream.
p pair to be printed.
Returns
Output stream.
Definition at line 111 of file streamingOperators.h.
operator<<() [28/57]
template<typename Number > std::ostream& carl::operator<< (std::ostream & os, const RealAlgebraicPoint< Number > & r)
Streaming operator for a RealAlgebraicPoint.
Definition at line 123 of file RealAlgebraicPoint.h.
operator<<() [29/57]
template<typename T , typename C > std::ostream& carl::operator<< (std::ostream & os, const std::set< T, C > & s) inline
Output a std::set with arbitrary content.
The format is {<length>: <item>, <item>, ...}
Parameters
os Output stream.
s set to be printed.
Returns
Output stream.
Definition at line 123 of file streamingOperators.h.
operator<<() [30/57]
template<typename Pol > std::ostream& carl::operator<< (std::ostream & os, const PBConstraint< Pol > & pbc) inline
Definition at line 133 of file PBConstraint.h.
operator<<() [31/57]
template<typename P > std::ostream& carl::operator<< (std::ostream & os, const MultivariateRoot< P > & mr)
Definition at line 138 of file MultivariateRoot.h.
operator<<() [32/57]
template<std::size_t I = 0, typename... T, typename std::enable_if< I==sizeof...(T), void >::type * = nullptr> std::ostream& carl::operator<< (std::ostream & os, const std::tuple< T... > &) inline
Output a std::tuple with arbitrary content.
Final case for I == 0.
Parameters
os Output stream.
Returns
Output stream.
Definition at line 141 of file streamingOperators.h.
operator<<() [33/57]
template<typename Poly > std::ostream& carl::operator<< (std::ostream & os, const VariableComparison< Poly > & vc)
Definition at line 141 of file VariableComparison.h.
operator<<() [34/57]
template<typename T , typename N > std::ostream& carl::operator<< (std::ostream & os, const BaseNumber< T, N > & n)
Definition at line 143 of file Number.h.
operator<<() [35/57]
std::ostream& carl::operator<< (std::ostream & os, const MonomialPool & mp) inline
Definition at line 144 of file MonomialPool.h.
operator<<() [36/57]
template<class C > std::ostream& carl::operator<< (std::ostream & os, const ReductorEntry< C > rhs)
Definition at line 150 of file ReductorEntry.h.
operator<<() [37/57]
std::ostream& carl::operator<< (std::ostream & os, const ModelVariable & mv) inline
Definition at line 157 of file ModelVariable.h.
operator<<() [38/57]
std::ostream& carl::operator<< (std::ostream & _os, const UEquality & _ueq)
Parameters
_os The output stream to print on.
_ueq The uninterpreted equality to print.
Returns
The output stream after printing the given uninterpreted equality on it.
Definition at line 182 of file UEquality.cpp.
operator<<() [39/57]
std::ostream& carl::operator<< (std::ostream & os, const BitVector & bv) inline
Definition at line 194 of file BitVector.h.
operator<<() [40/57]
template<class E , bool FI> std::ostream& carl::operator<< (std::ostream & out, const CompactTree< E, FI > & tree)
Definition at line 205 of file CompactTree.h.
operator<<() [41/57]
std::ostream& carl::operator<< (std::ostream & os, const MapleStream & ms) inline
Definition at line 212 of file MapleStream.h.
operator<<() [42/57]
template<typename Rational , typename Poly > std::ostream& carl::operator<< (std::ostream & os, const Model< Rational, Poly > & model)
Definition at line 214 of file Model.h.
operator<<() [43/57]
template<typename T > std::ostream& carl::operator<< (std::ostream & , const Numeric< T > &)
operator<<() [44/57]
std::ostream& carl::operator<< (std::ostream & os, const QEPCADStream & qs) inline
Definition at line 228 of file QEPCADStream.h.
operator<<() [45/57]
std::ostream& carl::operator<< (std::ostream & os, const SMTLIBStream & ss) inline
Definition at line 284 of file SMTLIBStream.h.
operator<<() [46/57]
template<typename C > std::ostream& carl::operator<< (std::ostream & o, const MultiplicationTable< C > & table)
Definition at line 297 of file MultiplicationTable.h.
operator<<() [47/57]
template<typename R , typename P > std::ostream& carl::operator<< (std::ostream & os, const ModelValue< R, P > & mv) inline
Definition at line 311 of file ModelValue.h.
operator<<() [48/57]
template<typename P > std::ostream& carl::operator<< (std::ostream & _out, const ConstraintContent< P > & _cc)
Prints the representation of the given constraints on the given stream.
Parameters
_out The stream to print on.
_constraint The constraint to print.
Returns
The given stream after printing.
Definition at line 330 of file Constraint.h.
operator<<() [49/57]
template<typename Num > std::ostream& carl::operator<< (std::ostream & os, const RealAlgebraicNumber< Num > & ran)
Definition at line 368 of file RealAlgebraicNumber.h.
operator<<() [50/57]
template<typename N > std::ostream& carl::operator<< (std::ostream & os, const SignDetermination< N > & rhs)
Definition at line 412 of file SignDetermination.h.
operator<<() [51/57]
template<typename P > std::ostream& carl::operator<< (std::ostream & _out, const FormulaContent< P > & _formula)
The output operator of a formula.
Parameters
_out The stream to print on.
_formula
Definition at line 416 of file FormulaContent.h.
operator<<() [52/57]
template<typename P > std::ostream& carl::operator<< (std::ostream & _out, const FormulaContent< P > * _formula)
Definition at line 421 of file FormulaContent.h.
operator<<() [53/57]
template<typename N > std::ostream& carl::operator<< (std::ostream & os, const ThomEncoding< N > & rhs)
Definition at line 563 of file ThomEncoding.h.
operator<<() [54/57]
template<typename P > std::ostream& carl::operator<< (std::ostream & _out, const FactorizedPolynomial< P > & _fpoly)
Prints the factorization representation of the given factorized polynomial on the given output stream.
Parameters
_out The stream to print on.
_fpoly The factorized polynomial to print.
Returns
The output stream after inserting the output.
operator<<() [55/57]
template<typename TT > std::ostream& carl::operator<< (std::ostream & os, const tree< TT > & tree)
Definition at line 985 of file carlTree.h.
operator<<() [56/57]
template<typename Poly > std::ostream& carl::operator<< (std::ostream & _out, const Constraint< Poly > & _constraint)
Prints the given constraint on the given stream.
Parameters
_out The stream to print the given constraint on.
_constraint The formula to print.
Returns
The stream after printing the given constraint on it.
operator<<() [57/57]
template<typename Poly > std::ostream& carl::operator<< (std::ostream & _out, const Formula< Poly > & _formula)
Prints the given formula on the given stream.
Parameters
_out The stream to print the given formula on.
_formula The formula to print.
Returns
The stream after printing the given formula on it.
operator<=() [1/30]
bool carl::operator<= (const Condition & lhs, const Condition & rhs) inline
Check whether the bits of this condition are always set if the corresponding bit of the given condition is set.
Parameters
_condition The condition to compare with.
Returns
true, if all bits of this condition are always set if the corresponding bit of the given condition is set; false, otherwise.
Definition at line 44 of file Condition.h.
operator<=() [2/30]
template<typename Number > bool carl::operator<= (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) inline
Definition at line 388 of file RealAlgebraicNumber.h.
operator<=() [3/30]
template<typename Coeff > bool carl::operator<= (const Term< Coeff > & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 506 of file Term.h.
operator<=() [4/30]
template<typename Coeff > bool carl::operator<= (const Term< Coeff > & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 510 of file Term.h.
operator<=() [5/30]
template<typename Coeff > bool carl::operator<= (const Term< Coeff > & lhs, Variable rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 514 of file Term.h.
operator<=() [6/30]
template<typename Coeff > bool carl::operator<= (const Term< Coeff > & lhs, const Coeff & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 518 of file Term.h.
operator<=() [7/30]
template<typename Coeff > bool carl::operator<= (const Monomial::Arg & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 522 of file Term.h.
operator<=() [8/30]
template<typename N > bool carl::operator<= (const ThomEncoding< N > & lhs, const ThomEncoding< N > & rhs)
Definition at line 522 of file ThomEncoding.h.
operator<=() [9/30]
template<typename Coeff > bool carl::operator<= (Variable lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 526 of file Term.h.
operator<=() [10/30]
template<typename Coeff > bool carl::operator<= (const Coeff & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 530 of file Term.h.
operator<=() [11/30]
template<typename N > bool carl::operator<= (const ThomEncoding< N > & lhs, const N & rhs)
Definition at line 536 of file ThomEncoding.h.
operator<=() [12/30]
template<typename N > bool carl::operator<= (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 549 of file ThomEncoding.h.
operator<=() [13/30]
bool carl::operator<= (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 678 of file Monomial.h.
operator<=() [14/30]
bool carl::operator<= (const Monomial::Arg & lhs, Variable rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 682 of file Monomial.h.
operator<=() [15/30]
bool carl::operator<= (Variable lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 686 of file Monomial.h.
operator<=() [16/30]
template<typename P > bool carl::operator<= (const Constraint< P > & lhs, const Constraint< P > & rhs)
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs <= rhs
Definition at line 824 of file Constraint.h.
operator<=() [17/30]
template<typename P > bool carl::operator<= (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs <= _rhs
Definition at line 888 of file FactorizedPolynomial.h.
operator<=() [18/30]
template<typename P > bool carl::operator<= (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs <= _rhs
Definition at line 894 of file FactorizedPolynomial.h.
operator<=() [19/30]
template<typename P > bool carl::operator<= (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs <= _rhs
Definition at line 900 of file FactorizedPolynomial.h.
operator<=() [20/30]
template<typename C , typename O , typename P > bool carl::operator<= (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 908 of file MultivariatePolynomial.h.
operator<=() [21/30]
template<typename C , typename O , typename P > bool carl::operator<= (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 912 of file MultivariatePolynomial.h.
operator<=() [22/30]
template<typename C , typename O , typename P > bool carl::operator<= (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 916 of file MultivariatePolynomial.h.
operator<=() [23/30]
template<typename C , typename O , typename P > bool carl::operator<= (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 920 of file MultivariatePolynomial.h.
operator<=() [24/30]
template<typename C , typename O , typename P > bool carl::operator<= (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 924 of file MultivariatePolynomial.h.
operator<=() [25/30]
template<typename C , typename O , typename P > bool carl::operator<= (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 928 of file MultivariatePolynomial.h.
operator<=() [26/30]
template<typename C , typename O , typename P > bool carl::operator<= (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 932 of file MultivariatePolynomial.h.
operator<=() [27/30]
template<typename C , typename O , typename P > bool carl::operator<= (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 936 of file MultivariatePolynomial.h.
operator<=() [28/30]
template<typename C , typename O , typename P > bool carl::operator<= (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is less or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs <= rhs
Definition at line 940 of file MultivariatePolynomial.h.
operator<=() [29/30]
template<typename Number > bool carl::operator<= (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the righthand side has maximal one intersection with the lefthand side at the upper bound of lhs.
operator<=() [30/30]
template<typename Number > bool carl::operator<= (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the righthand side has maximal one intersection with the lefthand side at the upper bound of lhs.
Definition at line 2021 of file Interval.h.
operator==() [1/50]
template<typename T , class I > bool carl::operator== (const TypeInfoPair< T, I > & _tipA, const TypeInfoPair< T, I > & _tipB)
Definition at line 24 of file Cache.h.
operator==() [2/50]
bool carl::operator== (const std::pair< Variable, uint > & p, Variable v) inline
Compare a pair of variable and exponent with a variable.
Returns true, if both variables are the same.
Parameters
p Pair of variable and exponent.
v Variable.
Returns
p.first == v
Definition at line 33 of file Monomial.h.
operator==() [3/50]
bool carl::operator== (const BitVector & lhs, const BitVector & rhs)
Definition at line 37 of file BitVector.cpp.
operator==() [4/50]
bool carl::operator== (const BitVector::forward_iterator & fi1, const BitVector::forward_iterator & fi2)
Definition at line 42 of file BitVector.cpp.
operator==() [5/50]
template<typename Poly > bool carl::operator== (const VariableAssignment< Poly > & lhs, const VariableAssignment< Poly > & rhs)
Definition at line 52 of file VariableAssignment.h.
operator==() [6/50]
template<typename LhsT > bool carl::operator== (const SimpleConstraint< LhsT > & lhs, const SimpleConstraint< LhsT > & rhs)
Definition at line 62 of file SimpleConstraint.h.
operator==() [7/50]
bool carl::operator== (const BVVariable & lhs, const BVVariable & rhs) inline
Definition at line 69 of file BVVariable.h.
operator==() [8/50]
bool carl::operator== (const Sort & lhs, const Sort & rhs) inline
Parameters
_sort The sort to compare with.
Returns
true, if this sort equals the given one.
Definition at line 69 of file Sort.h.
operator==() [9/50]
bool carl::operator== (const BVVariable & lhs, const Variable & rhs) inline
Definition at line 72 of file BVVariable.h.
operator==() [10/50]
bool carl::operator== (const Variable & lhs, const BVVariable & rhs) inline
Definition at line 75 of file BVVariable.h.
operator==() [11/50]
template<typename Number > bool carl::operator== (RealAlgebraicPoint< Number > & lhs, RealAlgebraicPoint< Number > & rhs)
Check if two RealAlgebraicPoints are equal.
Definition at line 110 of file RealAlgebraicPoint.h.
operator==() [12/50]
bool carl::operator== (const ModelVariable & lhs, const ModelVariable & rhs) inline
Returns
true, if the first and the second are either both variables or both functions and in the first case the variables are equal (equal ids) or in the second case the functions are equal (equal ids).
Definition at line 118 of file ModelVariable.h.
operator==() [13/50]
template<typename Poly > bool carl::operator== (const MultivariateRoot< Poly > & lhs, const MultivariateRoot< Poly > & rhs) inline
Definition at line 129 of file MultivariateRoot.h.
operator==() [14/50]
template<typename Poly > bool carl::operator== (const VariableComparison< Poly > & lhs, const VariableComparison< Poly > & rhs)
Definition at line 130 of file VariableComparison.h.
operator==() [15/50]
template<typename Pol > bool carl::operator== (const PBConstraint< Pol > & lhs, const PBConstraint< Pol > & rhs) inline
Definition at line 138 of file PBConstraint.h.
operator==() [16/50]
template<typename Rational , typename Poly > bool carl::operator== (const ModelValue< Rational, Poly > & lhs, const ModelValue< Rational, Poly > & rhs)
Check if two Assignments are equal.
Two Assignments are considered equal, if both are either bool or not bool and their value is the same.
If both Assignments are not bools, the check may return false although they represent the same value. If both are numbers in different representations, this comparison is only done as a "best effort".
Parameters
lhs First Assignment.
rhs Second Assignment.
Returns
lhs == rhs.
Definition at line 290 of file ModelValue.h.
operator==() [17/50]
template<typename Pol > bool carl::operator== (const ConstraintContent< Pol > & lhs, const ConstraintContent< Pol > & rhs)
Parameters
lhs Left ConstraintContent
rhs Right ConstraintContent
Returns
lhs == rhs
Definition at line 316 of file Constraint.h.
operator==() [18/50]
template<typename Number > bool carl::operator== (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) inline
Definition at line 376 of file RealAlgebraicNumber.h.
operator==() [19/50]
template<typename Coeff > bool carl::operator== (const Term< Coeff > & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator==() [20/50]
template<typename Coeff > bool carl::operator== (const Term< Coeff > & lhs, const Monomial & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator==() [21/50]
template<typename Coeff > bool carl::operator== (const Term< Coeff > & lhs, Variable rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator==() [22/50]
template<typename Coeff > bool carl::operator== (const Term< Coeff > & lhs, const Coeff & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
operator==() [23/50]
template<typename Coeff > bool carl::operator== (const Monomial::Arg & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 449 of file Term.h.
operator==() [24/50]
template<typename Coeff > bool carl::operator== (Variable lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 453 of file Term.h.
operator==() [25/50]
template<typename Coeff > bool carl::operator== (const Coeff & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 457 of file Term.h.
operator==() [26/50]
template<typename N > bool carl::operator== (const ThomEncoding< N > & lhs, const ThomEncoding< N > & rhs)
Definition at line 528 of file ThomEncoding.h.
operator==() [27/50]
template<typename N > bool carl::operator== (const ThomEncoding< N > & lhs, const N & rhs)
Definition at line 542 of file ThomEncoding.h.
operator==() [28/50]
template<typename N > bool carl::operator== (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 555 of file ThomEncoding.h.
operator==() [29/50]
bool carl::operator== (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 622 of file Monomial.h.
operator==() [30/50]
bool carl::operator== (const Monomial::Arg & lhs, Variable rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 631 of file Monomial.h.
operator==() [31/50]
bool carl::operator== (Variable lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 637 of file Monomial.h.
operator==() [32/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [33/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [34/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [35/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [36/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [37/50]
template<typename C , typename O , typename P , DisableIf< std::is_integral< C >> = dummy> bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, int rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [38/50]
template<typename C , typename O , typename P > bool carl::operator== (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
Definition at line 782 of file MultivariatePolynomial.h.
operator==() [39/50]
template<typename P > bool carl::operator== (const Constraint< P > & lhs, const Constraint< P > & rhs)
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs == rhs
Definition at line 782 of file Constraint.h.
operator==() [40/50]
template<typename C , typename O , typename P > bool carl::operator== (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
Definition at line 786 of file MultivariatePolynomial.h.
operator==() [41/50]
template<typename C , typename O , typename P > bool carl::operator== (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
Definition at line 790 of file MultivariatePolynomial.h.
operator==() [42/50]
template<typename C , typename O , typename P > bool carl::operator== (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
Definition at line 794 of file MultivariatePolynomial.h.
operator==() [43/50]
template<typename C , typename O , typename P > bool carl::operator== (const UnivariatePolynomial< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [44/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< C > & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [45/50]
template<typename C , typename O , typename P > bool carl::operator== (const UnivariatePolynomial< MultivariatePolynomial< C >> & lhs, const MultivariatePolynomial< C, O, P > & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [46/50]
template<typename C , typename O , typename P > bool carl::operator== (const MultivariatePolynomial< C, O, P > & lhs, const UnivariatePolynomial< MultivariatePolynomial< C >> & rhs)
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
operator==() [47/50]
template<typename P > bool carl::operator== (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs)
Checks if the two arguments are equal.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs == _rhs
operator==() [48/50]
template<typename P > bool carl::operator== (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs)
Checks if the two arguments are equal.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs == _rhs
operator==() [49/50]
template<typename P > bool carl::operator== (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the two arguments are equal.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs == _rhs
Definition at line 828 of file FactorizedPolynomial.h.
operator==() [50/50]
template<typename Number > bool carl::operator== (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if both intervals are equal.
operator>() [1/29]
template<typename Number > bool carl::operator> (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) inline
Definition at line 392 of file RealAlgebraicNumber.h.
operator>() [2/29]
template<typename N > bool carl::operator> (const ThomEncoding< N > & lhs, const ThomEncoding< N > & rhs)
Definition at line 524 of file ThomEncoding.h.
operator>() [3/29]
template<typename Coeff > bool carl::operator> (const Term< Coeff > & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 535 of file Term.h.
operator>() [4/29]
template<typename N > bool carl::operator> (const ThomEncoding< N > & lhs, const N & rhs)
Definition at line 538 of file ThomEncoding.h.
operator>() [5/29]
template<typename Coeff > bool carl::operator> (const Term< Coeff > & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 539 of file Term.h.
operator>() [6/29]
template<typename Coeff > bool carl::operator> (const Term< Coeff > & lhs, Variable rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 543 of file Term.h.
operator>() [7/29]
template<typename Coeff > bool carl::operator> (const Term< Coeff > & lhs, const Coeff & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 547 of file Term.h.
operator>() [8/29]
template<typename Coeff > bool carl::operator> (const Monomial::Arg & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 551 of file Term.h.
operator>() [9/29]
template<typename N > bool carl::operator> (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 551 of file ThomEncoding.h.
operator>() [10/29]
template<typename Coeff > bool carl::operator> (Variable lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 555 of file Term.h.
operator>() [11/29]
template<typename Coeff > bool carl::operator> (const Coeff & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 559 of file Term.h.
operator>() [12/29]
bool carl::operator> (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 690 of file Monomial.h.
operator>() [13/29]
bool carl::operator> (const Monomial::Arg & lhs, Variable rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 694 of file Monomial.h.
operator>() [14/29]
bool carl::operator> (Variable lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 698 of file Monomial.h.
operator>() [15/29]
template<typename P > bool carl::operator> (const Constraint< P > & lhs, const Constraint< P > & rhs)
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs > rhs
Definition at line 813 of file Constraint.h.
operator>() [16/29]
template<typename P > bool carl::operator> (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is greater than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs > _rhs
Definition at line 915 of file FactorizedPolynomial.h.
operator>() [17/29]
template<typename P > bool carl::operator> (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs) inline
Checks if the first arguments is greater than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs > _rhs
Definition at line 921 of file FactorizedPolynomial.h.
operator>() [18/29]
template<typename P > bool carl::operator> (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is greater than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs > _rhs
Definition at line 927 of file FactorizedPolynomial.h.
operator>() [19/29]
template<typename C , typename O , typename P > bool carl::operator> (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 954 of file MultivariatePolynomial.h.
operator>() [20/29]
template<typename C , typename O , typename P > bool carl::operator> (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 958 of file MultivariatePolynomial.h.
operator>() [21/29]
template<typename C , typename O , typename P > bool carl::operator> (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 962 of file MultivariatePolynomial.h.
operator>() [22/29]
template<typename C , typename O , typename P > bool carl::operator> (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 966 of file MultivariatePolynomial.h.
operator>() [23/29]
template<typename C , typename O , typename P > bool carl::operator> (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 970 of file MultivariatePolynomial.h.
operator>() [24/29]
template<typename C , typename O , typename P > bool carl::operator> (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 974 of file MultivariatePolynomial.h.
operator>() [25/29]
template<typename C , typename O , typename P > bool carl::operator> (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 978 of file MultivariatePolynomial.h.
operator>() [26/29]
template<typename C , typename O , typename P > bool carl::operator> (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 982 of file MultivariatePolynomial.h.
operator>() [27/29]
template<typename C , typename O , typename P > bool carl::operator> (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs > rhs
Definition at line 986 of file MultivariatePolynomial.h.
operator>() [28/29]
template<typename Number > bool carl::operator> (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the lefthand side is larger than the righthand side.
operator>() [29/29]
template<typename Number > bool carl::operator> (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the lefthand side is larger than the righthand side.
Definition at line 2058 of file Interval.h.
operator>=() [1/29]
template<typename Number > bool carl::operator>= (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) inline
Definition at line 396 of file RealAlgebraicNumber.h.
operator>=() [2/29]
template<typename N > bool carl::operator>= (const ThomEncoding< N > & lhs, const ThomEncoding< N > & rhs)
Definition at line 526 of file ThomEncoding.h.
operator>=() [3/29]
template<typename N > bool carl::operator>= (const ThomEncoding< N > & lhs, const N & rhs)
Definition at line 540 of file ThomEncoding.h.
operator>=() [4/29]
template<typename N > bool carl::operator>= (const N & lhs, const ThomEncoding< N > & rhs)
Definition at line 553 of file ThomEncoding.h.
operator>=() [5/29]
template<typename Coeff > bool carl::operator>= (const Term< Coeff > & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 564 of file Term.h.
operator>=() [6/29]
template<typename Coeff > bool carl::operator>= (const Term< Coeff > & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 568 of file Term.h.
operator>=() [7/29]
template<typename Coeff > bool carl::operator>= (const Term< Coeff > & lhs, Variable rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 572 of file Term.h.
operator>=() [8/29]
template<typename Coeff > bool carl::operator>= (const Term< Coeff > & lhs, const Coeff & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 576 of file Term.h.
operator>=() [9/29]
template<typename Coeff > bool carl::operator>= (const Monomial::Arg & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 580 of file Term.h.
operator>=() [10/29]
template<typename Coeff > bool carl::operator>= (Variable lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 584 of file Term.h.
operator>=() [11/29]
template<typename Coeff > bool carl::operator>= (const Coeff & lhs, const Term< Coeff > & rhs) inline
Compares two arguments where one is a term and the other is either a term, a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 588 of file Term.h.
operator>=() [12/29]
bool carl::operator>= (const Monomial::Arg & lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 702 of file Monomial.h.
operator>=() [13/29]
bool carl::operator>= (const Monomial::Arg & lhs, Variable rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 706 of file Monomial.h.
operator>=() [14/29]
bool carl::operator>= (Variable lhs, const Monomial::Arg & rhs) inline
Compares two arguments where one is a Monomial and the other is either a monomial or a variable.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs ~ rhs, ~ being the relation that is checked.
Definition at line 710 of file Monomial.h.
operator>=() [15/29]
template<typename P > bool carl::operator>= (const Constraint< P > & lhs, const Constraint< P > & rhs)
Parameters
lhs Left constraint
rhs Right constraint
Returns
lhs >= rhs
Definition at line 835 of file Constraint.h.
operator>=() [16/29]
template<typename P > bool carl::operator>= (const FactorizedPolynomial< P > & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs >= _rhs
Definition at line 942 of file FactorizedPolynomial.h.
operator>=() [17/29]
template<typename P > bool carl::operator>= (const FactorizedPolynomial< P > & _lhs, const typename FactorizedPolynomial< P >::CoeffType & _rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs >= _rhs
Definition at line 948 of file FactorizedPolynomial.h.
operator>=() [18/29]
template<typename P > bool carl::operator>= (const typename FactorizedPolynomial< P >::CoeffType & _lhs, const FactorizedPolynomial< P > & _rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
_lhs First argument.
_rhs Second argument.
Returns
_lhs >= _rhs
Definition at line 954 of file FactorizedPolynomial.h.
operator>=() [19/29]
template<typename C , typename O , typename P > bool carl::operator>= (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1000 of file MultivariatePolynomial.h.
operator>=() [20/29]
template<typename C , typename O , typename P > bool carl::operator>= (const MultivariatePolynomial< C, O, P > & lhs, const Term< C > & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1004 of file MultivariatePolynomial.h.
operator>=() [21/29]
template<typename C , typename O , typename P > bool carl::operator>= (const MultivariatePolynomial< C, O, P > & lhs, const Monomial::Arg & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1008 of file MultivariatePolynomial.h.
operator>=() [22/29]
template<typename C , typename O , typename P > bool carl::operator>= (const MultivariatePolynomial< C, O, P > & lhs, Variable::Arg rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1012 of file MultivariatePolynomial.h.
operator>=() [23/29]
template<typename C , typename O , typename P > bool carl::operator>= (const MultivariatePolynomial< C, O, P > & lhs, const C & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1016 of file MultivariatePolynomial.h.
operator>=() [24/29]
template<typename C , typename O , typename P > bool carl::operator>= (const Term< C > & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1020 of file MultivariatePolynomial.h.
operator>=() [25/29]
template<typename C , typename O , typename P > bool carl::operator>= (const Monomial::Arg & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1024 of file MultivariatePolynomial.h.
operator>=() [26/29]
template<typename C , typename O , typename P > bool carl::operator>= (Variable::Arg lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1028 of file MultivariatePolynomial.h.
operator>=() [27/29]
template<typename C , typename O , typename P > bool carl::operator>= (const C & lhs, const MultivariatePolynomial< C, O, P > & rhs) inline
Checks if the first arguments is greater or equal than the second.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs >= rhs
Definition at line 1032 of file MultivariatePolynomial.h.
operator>=() [28/29]
template<typename Number > bool carl::operator>= (const Interval< Number > & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the lefthand side has maximal one intersection with the righthand side at the lower bound of lhs.
operator>=() [29/29]
template<typename Number > bool carl::operator>= (const Number & lhs, const Interval< Number > & rhs) inline
Operator for the comparison of two intervals.
Parameters
lhs Lefthand side.
rhs Righthand side.
Returns
True if the lefthand side has maximal one intersection with the righthand side at the lower bound of lhs.
Definition at line 2034 of file Interval.h.
operator|()
BitVector carl::operator| (const BitVector & lhs, const BitVector & rhs)
Definition at line 6 of file BitVector.cpp.
outputSMTLIB()
template<typename Pol , typename... Args> detail::SMTLIBScriptContainer<Pol> carl::outputSMTLIB (Logic l, std::initializer_list< Formula< Pol >> formulas, Args &&... args)
Definition at line 313 of file SMTLIBStream.h.
parse()
template<typename T > T carl::parse (const std::string & n) inline
Referenced by carl::parser::parse_impl().
parse< cln::cl_I >()
template<> cln::cl_I carl::parse< cln::cl_I > (const std::string & n)
Definition at line 147 of file operations.cpp.
parse< cln::cl_RA >()
template<> cln::cl_RA carl::parse< cln::cl_RA > (const std::string & n)
Definition at line 160 of file operations.cpp.
parse< mpq_class >()
template<> mpq_class carl::parse< mpq_class > (const std::string & n)
Definition at line 167 of file operations.cpp.
Referenced by convert< cln::cl_RA, mpq_class >(), and rationalize< mpq_class >().
parse< mpz_class >()
template<> mpz_class carl::parse< mpz_class > (const std::string & n)
Definition at line 154 of file operations.cpp.
Referenced by convert< cln::cl_I, mpz_class >().
parseOPBFile()
boost::optional< OPBFile > carl::parseOPBFile (std::ifstream & in)
Definition at line 95 of file OPBImporter.cpp.
Referenced by carl::OPBImporter< Pol >::parse().
pow() [1/11]
template<typename T > T carl::pow (const T & basis, std::size_t exp)
Implements a fast exponentiation on an arbitrary type T.
To use carl::pow() on a type T, the following must be defined:
carl::constant_one<T>,
T::operator=(const T&) and
operator*(const T&, const T&). Alternatively, carl::pow() can be specialized for T explicitly.
Parameters
t A number.
exp The exponent.
Returns
t to the power of exp.
Definition at line 79 of file operations_generic.h.
pow() [2/11]
double carl::pow (double in, uint exp) inline
Definition at line 183 of file operations.h.
pow() [3/11]
template<> mpz_class carl::pow (const mpz_class & basis, std::size_t exp) inline
Definition at line 382 of file operations.h.
pow() [4/11]
template<> mpq_class carl::pow (const mpq_class & basis, std::size_t exp) inline
Definition at line 389 of file operations.h.
pow() [5/11]
template<> cln::cl_RA carl::pow (const cln::cl_RA & basis, std::size_t exp) inline
Calculate the power of some fraction to some positive integer.
Parameters
n Basis.
e Exponent.
Returns
Definition at line 395 of file operations.h.
pow() [6/11]
Monomial::Arg carl::pow (Variable v, std::size_t exp)
Definition at line 487 of file Monomial.cpp.
Referenced by carl::OldGinacConverter< Poly >::convertToGinac(), carl::Number< mpq_class >::Number(), carl::Number< cln::cl_RA >::Number(), carl::parser::isDivisible< true >::operator()(), carl::GiNaCConverter::operator()(), carl::ToGiNaC::operator()(), carl::parser::ExpressionParser< Pol >::perform_power::operator()(), carl::Term< typename Polynomial::CoeffType >::pow(), carl::FLOAT_T< FloatType >::pow(), carl::resultant_debug::resultant_z3(), boost::spirit::traits::scale(), and subresultants().
pow() [7/11]
template<typename Pol , bool AS> RationalFunction<Pol, AS> carl::pow (unsigned exp, const RationalFunction< Pol, AS > & rf)
Definition at line 550 of file RationalFunction.h.
pow() [8/11]
Monomial::Arg carl::pow (const Monomial::Arg & m, std::size_t exp) inline
Definition at line 734 of file Monomial.h.
pow() [9/11]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::pow (const MultivariatePolynomial< C, O, P > & p, std::size_t exp)
Definition at line 756 of file MultivariatePolynomial.h.
pow() [10/11]
template<typename FloatType > FLOAT_T<FloatType> carl::pow (const FLOAT_T< FloatType > & _in, size_t _exp) inline
Definition at line 1453 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::pow_assign().
pow() [11/11]
template<typename Number > Interval<Number> carl::pow (const Interval< Number > & _in, uint _exponent) inline
Definition at line 2140 of file Interval.h.
pow_assign()
template<typename T > void carl::pow_assign (T & t, std::size_t exp)
Implements a fast exponentiation on an arbitrary type T.
The result is stored in the given number. To use carl::pow_assign() on a type T, the following must be defined:
carl::constant_one<T>,
T::operator=(const T&) and
operator*(const T&, const T&). Alternatively, carl::pow() can be specialized for T explicitly.
Parameters
t A number.
exp The exponent.
Definition at line 101 of file operations_generic.h.
principalSubresultantsCoefficients()
template<typename Coeff > std::vector< UnivariatePolynomial< Coeff > > carl::principalSubresultantsCoefficients (const UnivariatePolynomial< Coeff > & p, const UnivariatePolynomial< Coeff > & q, SubresultantStrategy strategy = SubresultantStrategy::Default)
Definition at line 255 of file Resultant.h.
Referenced by carl::UnivariatePolynomial< Coeff >::principalSubresultantsCoefficients().
printCMakeOptions()
void carl::printCMakeOptions (std::ostream & os)
Definition at line 21 of file CMakeOptions.cpp.
printMatrix()
template<typename Coeff > void carl::printMatrix (const CoeffMatrix< Coeff > & m)
Definition at line 40 of file CharPol.h.
printRegisteredVariableNames()
void carl::printRegisteredVariableNames () inline
Definition at line 225 of file VariablePool.h.
printStacktrace()
void carl::printStacktrace (bool interaction)
Uses GDB to print a stack trace.
Definition at line 33 of file debug.cpp.
quotient() [1/9]
sint carl::quotient (sint n, sint m) inline
Definition at line 155 of file operations.h.
quotient() [2/9]
template<typename IntegerT > GFNumber<IntegerT> carl::quotient (const GFNumber< IntegerT > & lhs, const GFNumber< IntegerT > & rhs)
Definition at line 185 of file GFNumber.h.
quotient() [3/9]
mpz_class carl::quotient (const mpz_class & n, const mpz_class & d) inline
Definition at line 446 of file operations.h.
quotient() [4/9]
mpq_class carl::quotient (const mpq_class & n, const mpq_class & d) inline
Definition at line 460 of file operations.h.
quotient() [5/9]
cln::cl_RA carl::quotient (const cln::cl_RA & a, const cln::cl_RA & b) inline
Divide two fractions.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 512 of file operations.h.
quotient() [6/9]
cln::cl_I carl::quotient (const cln::cl_I & a, const cln::cl_I & b) inline
Divide two integers.
Discards the remainder of the division.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 523 of file operations.h.
quotient() [7/9]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::quotient (const MultivariatePolynomial< C, O, P > & p, const MultivariatePolynomial< C, O, P > & q)
Definition at line 750 of file MultivariatePolynomial.h.
Referenced by carl::EEA< IntegerType >::calculate_recursive(), carl::Number< mpz_class >::div(), carl::Number< mpq_class >::div(), div(), div_assign(), divide(), carl::BVValue::divideUnsigned(), operator/(), carl::RealAlgebraicNumber< carl::Number >::simplifyByPolynomial(), and carl::CArLConverter::toGMP().
quotient() [8/9]
template<typename FloatType > FLOAT_T<FloatType> carl::quotient (const FLOAT_T< FloatType > & _lhs, const FLOAT_T< FloatType > & _rhs) inline
Implements the division with remainder.
Parameters
_lhs
_rhs
Returns
Number which holds the result.
Definition at line 1381 of file FLOAT_T.h.
quotient() [9/9]
template<typename Number > Interval<Number> carl::quotient (const Interval< Number > & _lhs, const Interval< Number > & _rhs) inline
Implements the division with remainder.
Parameters
_lhs
_rhs
Returns
Interval which holds the result.
Definition at line 2088 of file Interval.h.
rationalize() [1/8]
template<typename T > T carl::rationalize (double n) inline
Definition at line 110 of file operations.h.
Referenced by cos(), log(), log10(), and sin().
rationalize() [2/8]
template<typename T > T carl::rationalize (float n) inline
rationalize() [3/8]
template<typename T > T carl::rationalize (int n) inline
rationalize() [4/8]
template<typename T > T carl::rationalize (sint n) inline
rationalize() [5/8]
template<typename T > T carl::rationalize (uint n) inline
rationalize() [6/8]
template<typename T > T carl::rationalize (const std::string & n) inline
rationalize() [7/8]
template<> double carl::rationalize (double n) inline
Definition at line 110 of file operations.h.
Referenced by cos(), log(), log10(), and sin().
rationalize() [8/8]
template<typename T > T carl::rationalize (const PreventConversion< mpq_class > &) inline
Referenced by carl::Number< cln::cl_RA >::log(), carl::Number< cln::cl_RA >::Number(), rationalize< cln::cl_RA >(), sqrt_safe(), and carl::Number< cln::cl_RA >::sqrt_safe().
rationalize< cln::cl_RA >() [1/6]
template<> cln::cl_RA carl::rationalize< cln::cl_RA > (double n)
Definition at line 13 of file operations.cpp.
rationalize< cln::cl_RA >() [2/6]
template<> cln::cl_RA carl::rationalize< cln::cl_RA > (float n)
Definition at line 36 of file operations.cpp.
rationalize< cln::cl_RA >() [3/6]
template<> cln::cl_RA carl::rationalize< cln::cl_RA > (const std::string & n)
Definition at line 141 of file operations.cpp.
rationalize< cln::cl_RA >() [4/6]
template<> cln::cl_RA carl::rationalize< cln::cl_RA > (int n) inline
Definition at line 211 of file operations.h.
rationalize< cln::cl_RA >() [5/6]
template<> cln::cl_RA carl::rationalize< cln::cl_RA > (uint n) inline
Definition at line 216 of file operations.h.
rationalize< cln::cl_RA >() [6/6]
template<> cln::cl_RA carl::rationalize< cln::cl_RA > (sint n) inline
Definition at line 221 of file operations.h.
rationalize< FLOAT_T< double > >()
template<> FLOAT_T<double> carl::rationalize< FLOAT_T< double > > (double n) inline
Definition at line 1529 of file FLOAT_T.h.
rationalize< FLOAT_T< float > >()
template<> FLOAT_T<float> carl::rationalize< FLOAT_T< float > > (float n) inline
Definition at line 1535 of file FLOAT_T.h.
rationalize< FLOAT_T< mpq_class > >()
template<> FLOAT_T<mpq_class> carl::rationalize< FLOAT_T< mpq_class > > (double n) inline
Definition at line 1541 of file FLOAT_T.h.
rationalize< mpq_class >() [1/7]
template<> mpq_class carl::rationalize< mpq_class > (const std::string & n)
Definition at line 149 of file operations.cpp.
Referenced by convert< double, FLOAT_T< mpq_class > >(), convert< double, mpq_class >(), convert< FLOAT_T< double >, mpq_class >(), cos(), log(), log10(), carl::FLOAT_T< FloatType >::operator mpq_class(), rationalize< FLOAT_T< mpq_class > >(), and sin().
rationalize< mpq_class >() [2/7]
template<> mpq_class carl::rationalize< mpq_class > (float n) inline
Definition at line 203 of file operations.h.
rationalize< mpq_class >() [3/7]
template<> mpq_class carl::rationalize< mpq_class > (double n) inline
Definition at line 209 of file operations.h.
rationalize< mpq_class >() [4/7]
template<> mpq_class carl::rationalize< mpq_class > (int n) inline
Definition at line 215 of file operations.h.
rationalize< mpq_class >() [5/7]
template<> mpq_class carl::rationalize< mpq_class > (uint n) inline
Definition at line 220 of file operations.h.
rationalize< mpq_class >() [6/7]
template<> mpq_class carl::rationalize< mpq_class > (sint n) inline
Definition at line 225 of file operations.h.
rationalize< mpq_class >() [7/7]
template<> mpq_class carl::rationalize< mpq_class > (const PreventConversion< mpq_class > & n) inline
Definition at line 233 of file operations.h.
realRootsThom() [1/3]
template<typename Number > std::list< ThomEncoding< Number > > carl::realRootsThom (const MultivariatePolynomial< Number > & p, Variable::Arg mainVar, std::shared_ptr< ThomEncoding< Number >> point_ptr, const Interval< Number > & interval = Interval<Number>::unboundedInterval())
Definition at line 117 of file ThomRootFinder.h.
Referenced by carl::ThomEncoding< Number >::concat(), carl::ThomEncoding< Number >::operator+(), realRootsThom(), and carl::ThomEncoding< Number >::ThomEncoding().
realRootsThom() [2/3]
template<typename Number > std::list<ThomEncoding<Number> > carl::realRootsThom (const MultivariatePolynomial< Number > & p, Variable::Arg mainVar, const std::map< Variable, ThomEncoding< Number >> & m = {}, const Interval< Number > & interval = Interval<Number>::unboundedInterval())
Definition at line 36 of file ThomRootFinder.h.
realRootsThom() [3/3]
template<typename Coeff , typename Number > std::list<RealAlgebraicNumber<Number> > carl::realRootsThom (const UnivariatePolynomial< Coeff > & p, const std::map< Variable, RealAlgebraicNumber< Number >> & m, const Interval< Number > & interval)
Definition at line 269 of file ThomRootFinder.h.
reciprocal() [1/2]
mpq_class carl::reciprocal (const mpq_class & a) inline
Definition at line 523 of file operations.h.
reciprocal() [2/2]
cln::cl_RA carl::reciprocal (const cln::cl_RA & a) inline
Definition at line 555 of file operations.h.
Referenced by carl::parser::ExpressionParser< Pol >::perform_division::operator()(), and operator/().
relationIsSigned()
bool carl::relationIsSigned (BVCompareRelation _r) inline
Definition at line 84 of file BVCompareRelation.h.
relationIsStrict()
bool carl::relationIsStrict (BVCompareRelation _r) inline
Definition at line 75 of file BVCompareRelation.h.
remainder() [1/3]
sint carl::remainder (sint n, sint m) inline
Definition at line 148 of file operations.h.
remainder() [2/3]
mpz_class carl::remainder (const mpz_class & n, const mpz_class & m) inline
Definition at line 442 of file operations.h.
remainder() [3/3]
cln::cl_I carl::remainder (const cln::cl_I & a, const cln::cl_I & b) inline
Calculate the remainder of the integer division.
Parameters
a First argument.
b Second argument.
Returns
.
Definition at line 535 of file operations.h.
Referenced by carl::RealRadicalAwareAdding< Polynomial >::addToGb(), carl::EEA< IntegerType >::calculate_recursive(), divide(), carl::BVValue::divideUnsigned(), and carl::DiophantineEquations< Integer >::univariateDiophantine().
representingFormula()
template<typename Rational , typename Poly > Formula<Poly> carl::representingFormula (const ModelVariable & mv, const Model< Rational, Poly > & model)
resultant()
template<typename Coeff > UnivariatePolynomial< Coeff > carl::resultant (const UnivariatePolynomial< Coeff > & p, const UnivariatePolynomial< Coeff > & q, SubresultantStrategy strategy = SubresultantStrategy::Default)
Definition at line 272 of file Resultant.h.
Referenced by carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::Brown(), discriminant(), carl::RealAlgebraicNumberEvaluation::evaluatePolynomial(), carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::McCallum(), and carl::UnivariatePolynomial< Coeff >::resultant().
returnFalse()
template<typename T > bool carl::returnFalse (const T & , const T &)
Definition at line 41 of file Cache.h.
root_safe() [1/2]
std::pair< mpq_class, mpq_class > carl::root_safe (const mpq_class & a, uint n)
Calculate the nth root of a fraction.
The precise result is contained in the resulting interval.
Definition at line 71 of file operations.cpp.
root_safe() [2/2]
std::pair< cln::cl_RA, cln::cl_RA > carl::root_safe (const cln::cl_RA & a, uint n)
Definition at line 135 of file operations.cpp.
Referenced by lagrangeBound().
round() [1/4]
cln::cl_I carl::round (const cln::cl_RA & n) inline
Round a fraction to next integer.
Parameters
n A fraction.
Returns
The next integer.
Definition at line 264 of file operations.h.
Referenced by carl::SignDetermination< Number >::getSigns().
round() [2/4]
mpz_class carl::round (const mpq_class & n) inline
Definition at line 267 of file operations.h.
round() [3/4]
cln::cl_I carl::round (const cln::cl_I & n) inline
Round an integer to next integer, that is do nothing.
Parameters
n An integer.
Returns
The next integer.
Definition at line 273 of file operations.h.
round() [4/4]
mpz_class carl::round (const mpz_class & n) inline
Definition at line 277 of file operations.h.
roundDown()
template<typename Rational > static double carl::roundDown (const Rational & o, bool overapproximate = false) static
Returns a down-rounded representation of the given numeric.
Parameters
o Number to round.
overapproximate Flag if overapproximation shall be guaranteed.
Returns
Double representation of o.
Definition at line 12 of file generic.h.
Referenced by carl::Interval< mpq_class >::Interval().
roundUp()
template<typename Rational > static double carl::roundUp (const Rational & o, bool overapproximate = false) static
Returns a up-rounded representation of the given numeric.
Parameters
o
overapproximate
Returns
double representation of o (overapprox) Note, that it can return the double INFINITY.
Definition at line 32 of file generic.h.
Referenced by carl::Interval< mpq_class >::Interval().
sampleAbove()
template<typename Number > RealAlgebraicNumber<Number> carl::sampleAbove (const RealAlgebraicNumber< Number > & n)
Definition at line 115 of file RealAlgebraicNumberOperations.h.
sampleBelow()
template<typename Number > RealAlgebraicNumber<Number> carl::sampleBelow (const RealAlgebraicNumber< Number > & n)
Definition at line 49 of file RealAlgebraicNumberOperations.h.
sampleBetween()
template<typename Number > RealAlgebraicNumber<Number> carl::sampleBetween (const RealAlgebraicNumber< Number > & lower, const RealAlgebraicNumber< Number > & upper, RANSampleHeuristic heuristic = RANSampleHeuristic::Default)
Definition at line 65 of file RealAlgebraicNumberOperations.h.
satisfies() [1/2]
template<typename Rational , typename Poly > unsigned carl::satisfies (const Model< Rational, Poly > & _assignment, const Formula< Poly > & _formula)
Parameters
_assignment The assignment for which to check whether the given formula is satisfied by it.
_formula The formula to be satisfied.
Returns
0, if this formula is violated by the given assignment; 1, if this formula is satisfied by the given assignment; 2, otherwise.
satisfies() [2/2]
template<typename Rational , typename Poly > unsigned carl::satisfies (const Model< Rational, Poly > & _model, const std::map< Variable, Rational > & _assignment, const std::map< BVVariable, BVTerm > & bvAssigns, const Formula< Poly > & _formula)
Parameters
_model The assignment for which to check whether the given formula is satisfied by it.
_assignment The map to store the rational assignments in.
_formula The formula to be satisfied.
Returns
0, if this formula is violated by the given assignment; 1, if this formula is satisfied by the given assignment; 2, otherwise.
scaleByPowerOfTwo()
cln::cl_RA carl::scaleByPowerOfTwo (const cln::cl_RA & a, int exp)
Definition at line 72 of file operations.cpp.
Referenced by sqrt_safe(), and carl::Number< cln::cl_RA >::sqrt_safe().
setGinacConverterPolynomialCache()
template<typename Poly > void carl::setGinacConverterPolynomialCache (const std::shared_ptr< typename Poly::CACHE > & _cache)
Definition at line 179 of file OldGinacConverter.h.
sgn()
template<typename Number > Sign carl::sgn (const Number & n)
Obtain the sign of the given number.
This method relies on the comparison operators for the type of the given number.
Parameters
n Number
Returns
Sign of n
Definition at line 53 of file Sign.h.
Referenced by carl::TarskiQueryManager< carl::Number >::cache(), evaluate(), evaluateTE(), carl::TarskiQueryManager< carl::Number >::getCached(), carl::RealAlgebraicNumber< carl::Number >::sgn(), carl::UnivariatePolynomial< Coeff >::sgn(), signAtMinusInf(), signAtPlusInf(), and carl::ThomEncoding< Number >::signOnPolynomial().
signAtMinusInf()
template<typename Number > Sign carl::signAtMinusInf (const UnivariatePolynomial< Number > & p)
Definition at line 16 of file UnivariateTarskiQuery.h.
Referenced by univariateTarskiQuery().
signAtPlusInf()
template<typename Number > Sign carl::signAtPlusInf (const UnivariatePolynomial< Number > & p)
Definition at line 27 of file UnivariateTarskiQuery.h.
Referenced by univariateTarskiQuery().
signVariations() [1/2]
template<typename InputIterator > std::size_t carl::signVariations (InputIterator begin, InputIterator end)
Counts the number of sign variations in the given object range.
The function accepts an range of Sign objects.
Parameters
begin Start of object range.
end End of object range.
Returns
Sign variations of objects.
Definition at line 68 of file Sign.h.
Referenced by multivariateTarskiQuery(), and univariateTarskiQuery().
signVariations() [2/2]
template<typename InputIterator , typename Function > std::size_t carl::signVariations (InputIterator begin, InputIterator end, const Function & f)
Counts the number of sign variations in the given object range.
The function accepts an object range and an additional function f. If the objects are not of type Sign, the function f can be used to convert the objects to a Sign on the fly. As for the number of sign variations in the evaluations of polynomials p at a position x, this might look like this: signVariations(p.begin(), p.end(), [&x](const Polynomial& p){ return sgn(p.evaluate(x)); });
Parameters
begin Start of object range.
end End of object range.
f Function object to convert objects to Sign.
Returns
Sign variations of objects.
Definition at line 96 of file Sign.h.
similar()
template<typename Poly > bool carl::similar (const GiNaC::ex & a, const GiNaC::ex & b)
Definition at line 131 of file OldGinacConverter.h.
sin() [1/4]
double carl::sin (double in) inline
Definition at line 163 of file operations.h.
Referenced by sin().
sin() [2/4]
mpq_class carl::sin (const mpq_class & n) inline
Definition at line 373 of file operations.h.
sin() [3/4]
cln::cl_RA carl::sin (const cln::cl_RA & n) inline
Definition at line 406 of file operations.h.
Referenced by carl::Number< cln::cl_RA >::sin(), carl::Number< mpq_class >::sin(), carl::FLOAT_T< FloatType >::sin(), carl::FLOAT_T< FloatType >::sin_assign(), carl::rounding< Number >::sin_down(), and carl::rounding< Number >::sin_up().
sin() [4/4]
template<typename FloatType > FLOAT_T<FloatType> carl::sin (const FLOAT_T< FloatType > & _in) inline
Definition at line 1461 of file FLOAT_T.h.
solveDiophantine()
template<typename T > std::vector<T> carl::solveDiophantine (MultivariatePolynomial< T > & p)
Diophantine Equations solver.
SoSDecomposition()
template<typename C , typename O , typename P > std::vector<std::pair<C,MultivariatePolynomial<C,O,P> > > carl::SoSDecomposition (const MultivariatePolynomial< C, O, P > & p, bool not_trivial = false)
Definition at line 8 of file SoSDecomposition.h.
Referenced by carl::MultivariatePolynomial< Rational >::sosDecomposition().
SPolynomial()
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::SPolynomial (const MultivariatePolynomial< C, O, P > & p, const MultivariatePolynomial< C, O, P > & q)
Definition at line 8 of file SPolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::SPolynomial().
sqrt() [1/5]
mpq_class carl::sqrt (const mpq_class & a)
Definition at line 34 of file operations.cpp.
Referenced by sqrt_fast(), and sqrt_safe().
sqrt() [2/5]
cln::cl_RA carl::sqrt (const cln::cl_RA & a)
Definition at line 66 of file operations.cpp.
sqrt() [3/5]
double carl::sqrt (double in) inline
Definition at line 175 of file operations.h.
Referenced by sqrt_safe().
sqrt() [4/5]
template<typename FloatType > FLOAT_T<FloatType> carl::sqrt (const FLOAT_T< FloatType > & _in) inline
Method which returns the square root of the passed number.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 1439 of file FLOAT_T.h.
Referenced by carl::FLOAT_T< FloatType >::sqrt_assign().
sqrt() [5/5]
template<typename Number > Interval<Number> carl::sqrt (const Interval< Number > & _in) inline
Method which returns the square root of the passed number.
Parameters
_in Number.
Returns
Number which holds the result.
Definition at line 2133 of file Interval.h.
Referenced by charPol(), carl::FLOAT_T< FloatType >::sqrt(), carl::rounding< Number >::sqrt_down(), sqrt_fast(), carl::Number< mpq_class >::sqrt_fast(), carl::Number< cln::cl_RA >::sqrt_fast(), carl::Number< cln::cl_RA >::sqrt_safe(), and carl::rounding< Number >::sqrt_up().
sqrt_exact() [1/2]
bool carl::sqrt_exact (const mpq_class & a, mpq_class & b)
Calculate the square root of a fraction if possible.
Parameters
a The fraction to calculate the square root for.
b A reference to the rational, in which the result is stored.
Returns
true, if the number to calculate the square root for is a square; false, otherwise.
Definition at line 9 of file operations.cpp.
sqrt_exact() [2/2]
bool carl::sqrt_exact (const cln::cl_RA & a, cln::cl_RA & b)
Calculate the square root of a fraction if possible.
Parameters
a The fraction to calculate the square root for.
b A reference to the rational, in which the result is stored.
Returns
true, if the number to calculate the square root for is a square; false, otherwise.
Definition at line 60 of file operations.cpp.
sqrt_fast() [1/2]
std::pair< mpq_class, mpq_class > carl::sqrt_fast (const mpq_class & a)
Compute square root in a fast but less precise way.
Use cln::sqrt() to obtain an approximation. If the result is rational, i.e. the result is exact, use this result. Otherwise use the nearest integers as bounds on the square root.
Parameters
a Some number.
Returns
[x,x] if sqrt(a) = x is rational, otherwise [y,z] for y,z integer and y < sqrt(a) < z.
Definition at line 100 of file operations.cpp.
sqrt_fast() [2/2]
std::pair< cln::cl_RA, cln::cl_RA > carl::sqrt_fast (const cln::cl_RA & a)
Compute square root in a fast but less precise way.
Use cln::sqrt() to obtain an approximation. If the result is rational, i.e. the result is exact, use this result. Otherwise use the nearest integers as bounds on the square root.
Parameters
a Some number.
Returns
[x,x] if sqrt(a) = x is rational, otherwise [y,z] for y,z integer and y < sqrt(a) < z.
Definition at line 116 of file operations.cpp.
sqrt_safe() [1/4]
std::pair< mpq_class, mpq_class > carl::sqrt_safe (const mpq_class & a)
Definition at line 39 of file operations.cpp.
sqrt_safe() [2/4]
std::pair< cln::cl_RA, cln::cl_RA > carl::sqrt_safe (const cln::cl_RA & a)
Calculate the square root of a fraction.
If we are able to find a an such that is the exact root of , is returned. If we can not find such a number (note that such a number might not even exist), is returned with . Note that we try to find bounds that are very close to the actual square root. If a small representation is more important than a small interval, sqrt_fast should be used.
Parameters
a A fraction.
Returns
Interval containing the square root of a.
Definition at line 81 of file operations.cpp.
Referenced by sqrt(), carl::Number< cln::cl_RA >::sqrt(), carl::Number< mpq_class >::sqrt(), carl::Number< mpq_class >::sqrt_fast(), and sqrt_safe().
sqrt_safe() [3/4]
std::pair<double,double> carl::sqrt_safe (double in) inline
Definition at line 179 of file operations.h.
sqrt_safe() [4/4]
template<typename FloatType > std::pair<FLOAT_T<FloatType>, FLOAT_T<FloatType> > carl::sqrt_safe (const FLOAT_T< FloatType > & _in) inline
Definition at line 1447 of file FLOAT_T.h.
squareFreePart() [1/2]
template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> carl::squareFreePart (const MultivariatePolynomial< C, O, P > & p)
Definition at line 12 of file SquareFreePart.h.
squareFreePart() [2/2]
template<typename Coeff , EnableIf< is_subset_of_rationals< Coeff >> = dummy> UnivariatePolynomial< Coeff > carl::squareFreePart (const UnivariatePolynomial< Coeff > & p)
Definition at line 43 of file SquareFreePart.h.
str2double()
Str2Double_Error carl::str2double (double & d, char const * s) inline
Definition at line 63 of file FLOAT_T.h.
subresultants()
template<typename Coeff > std::list< UnivariatePolynomial< Coeff > > carl::subresultants (const UnivariatePolynomial< Coeff > & pol1, const UnivariatePolynomial< Coeff > & pol2, SubresultantStrategy strategy = SubresultantStrategy::Default)
Case distinction on delta: either we choose b as next subresultant or we could reduce b (delta > 1) and add the reduced version c as next subresultant. The reduction is done by division, which depends on the internal variable order of GiNaC and might fail although for some order it would succeed. In this case, we just do not reduce b. (A relaxed reduction could also be applied.)
After the if-else block, bDeg is the degree of the front-most element of subresultants, be it c or b.
Case distinction on delta: either we choose b as next subresultant or we could reduce b (delta > 1) and add the reduced version c as next subresultant. The reduction is done by division, which depends on the internal variable order of GiNaC and might fail although for some order it would succeed. In this case, we just do not reduce b. (A relaxed reduction could also be applied.)
After the if-else block, bDeg is the degree of the front-most element of subresultants, be it c or b.
Definition at line 29 of file Resultant.h.
Referenced by principalSubresultantsCoefficients(), resultant(), and carl::UnivariatePolynomial< Coeff >::subresultants().
to_string() [1/2]
std::string carl::to_string (const VariableType & t) inline
To string conversion for variable type.
Parameters
t VariableType
Returns
String Representation
Definition at line 41 of file Variable.h.
to_string() [2/2]
template<typename LhsT > std::string carl::to_string (const SimpleConstraint< LhsT > & constraint, bool pretty = false)
Definition at line 80 of file SimpleConstraint.h.
Referenced by carl::BaseNumber< cln::cl_RA, Number< cln::cl_RA > >::BaseNumber(), carl::VariablePool::getName(), main(), operator<<(), carl::Number< long int >::toString(), carl::BVValue::toString(), toString(), and carl::BVTermContent::toString().
toDouble() [1/7]
double carl::toDouble (sint n) inline
Conversion functions.
The following function convert types to other types.
Definition at line 89 of file operations.h.
toDouble() [2/7]
double carl::toDouble (double n) inline
Definition at line 92 of file operations.h.
toDouble() [3/7]
double carl::toDouble (const mpq_class & n) inline
Conversion functions.
The following function convert types to other types.
Definition at line 114 of file operations.h.
toDouble() [4/7]
double carl::toDouble (const mpz_class & n) inline
Definition at line 117 of file operations.h.
toDouble() [5/7]
double carl::toDouble (const cln::cl_RA & n) inline
Converts the given fraction to a double.
Parameters
n A fraction.
Returns
Double.
Definition at line 118 of file operations.h.
Referenced by convert< FLOAT_T< mpq_class >, double >(), convert< mpq_class, double >(), convert< mpq_class, FLOAT_T< double > >(), carl::Number< cln::cl_RA >::cos(), carl::Number< mpq_class >::cos(), carl::Interval< mpq_class >::Interval(), carl::Number< mpq_class >::log(), carl::FLOAT_T< FloatType >::operator double(), roundDown(), roundUp(), carl::Number< cln::cl_RA >::sin(), carl::Number< mpq_class >::sin(), sqrt_safe(), and carl::FLOAT_T< FloatType >::toDouble().
toDouble() [6/7]
double carl::toDouble (const cln::cl_I & n) inline
Converts the given integer to a double.
Parameters
n An integer.
Returns
Double.
Definition at line 126 of file operations.h.
toDouble() [7/7]
template<typename FloatType > double carl::toDouble (const FLOAT_T< FloatType > & _float) inline
Definition at line 1402 of file FLOAT_T.h.
toId()
std::size_t carl::toId (const BVCompareRelation _relation) inline
Definition at line 52 of file BVCompareRelation.h.
toInt() [1/9]
template<typename Number > int carl::toInt (const Number & n) inline
toInt() [2/9]
template<typename Integer > Integer carl::toInt (double n) inline
toInt() [3/9]
template<typename Integer > Integer carl::toInt (const mpz_class & n) inline
toInt() [4/9]
template<typename Integer > Integer carl::toInt (const cln::cl_I & n) inline
toInt() [5/9]
template<typename Integer > Integer carl::toInt (const cln::cl_RA & n) inline
toInt() [6/9]
template<typename Integer > Integer carl::toInt (const mpq_class & n) inline
toInt() [7/9]
template<typename Integer , typename T > Integer carl::toInt (const Numeric< T > & n) inline
Definition at line 248 of file Numeric.h.
toInt() [8/9]
template<typename Integer , typename FloatType > Integer carl::toInt (const FLOAT_T< FloatType > & _float) inline
Casts the FLOAT_T to an arbitrary integer type which has a constructor for a native int.
Parameters
_float
Returns
Integer type which holds floor(_float).
Definition at line 1396 of file FLOAT_T.h.
toInt() [9/9]
template<typename Integer , typename Number > Integer carl::toInt (const Interval< Number > & _floatInterval) inline
Casts the Interval to an arbitrary integer type which has a constructor for a native int.
Parameters
_floatInterval
Returns
Integer type which holds floor(_float).
Definition at line 2100 of file Interval.h.
toInt< cln::cl_I >()
template<> cln::cl_I carl::toInt< cln::cl_I > (const cln::cl_RA & n) inline
Convert a fraction to an integer.
This method assert, that the given fraction is an integer, i.e. that the denominator is one.
Parameters
n A fraction.
Returns
An integer.
Definition at line 179 of file operations.h.
toInt< mpz_class >()
template<> mpz_class carl::toInt< mpz_class > (const mpq_class & n) inline
Convert a fraction to an integer.
This method assert, that the given fraction is an integer, i.e. that the denominator is one.
Parameters
n A fraction.
Returns
An integer.
Definition at line 147 of file operations.h.
Referenced by toInt< sint >(), and toInt< uint >().
toInt< sint >() [1/5]
template<> sint carl::toInt< sint > (double n) inline
Definition at line 100 of file operations.h.
toInt< sint >() [2/5]
template<> sint carl::toInt< sint > (const mpz_class & n) inline
Definition at line 125 of file operations.h.
toInt< sint >() [3/5]
template<> sint carl::toInt< sint > (const cln::cl_I & n) inline
Definition at line 136 of file operations.h.
Referenced by convert< cln::cl_I, mpz_class >(), convert< cln::cl_RA, mpq_class >(), convert< mpq_class, cln::cl_RA >(), convert< mpz_class, cln::cl_I >(), carl::Number< mpq_class >::toInt(), carl::Number< cln::cl_RA >::toInt(), and toInt< sint >().
toInt< sint >() [4/5]
template<> sint carl::toInt< sint > (const cln::cl_RA & n) inline
Definition at line 184 of file operations.h.
toInt< sint >() [5/5]
template<> sint carl::toInt< sint > (const mpq_class & n) inline
Convert a fraction to an unsigned.
Parameters
n A fraction.
Returns
n as unsigned.
Definition at line 191 of file operations.h.
toInt< uint >() [1/5]
template<> uint carl::toInt< uint > (double n) inline
Definition at line 105 of file operations.h.
toInt< uint >() [2/5]
template<> uint carl::toInt< uint > (const mpz_class & n) inline
Definition at line 131 of file operations.h.
toInt< uint >() [3/5]
template<> uint carl::toInt< uint > (const cln::cl_I & n) inline
Definition at line 142 of file operations.h.
Referenced by carl::parser::PolynomialParser< Pol >::newMonomial(), carl::Number< mpq_class >::toInt(), carl::Number< cln::cl_RA >::toInt(), and toInt< uint >().
toInt< uint >() [4/5]
template<> uint carl::toInt< uint > (const cln::cl_RA & n) inline
Definition at line 188 of file operations.h.
toInt< uint >() [5/5]
template<> uint carl::toInt< uint > (const mpq_class & n) inline
Definition at line 195 of file operations.h.
toLF()
cln::cl_LF carl::toLF (const cln::cl_RA & n) inline
Convert a cln fraction to a cln long float.
Parameters
n A fraction.
Returns
n as cln::cl_LF.
Definition at line 197 of file operations.h.
Referenced by sqrt_fast(), and carl::Number< cln::cl_RA >::sqrt_fast().
toString() [1/11]
std::string carl::toString (BVCompareRelation _r) inline
Definition at line 29 of file BVCompareRelation.h.
toString() [2/11]
std::string carl::toString (const BVTermType _type) inline
Definition at line 32 of file BVTerm.h.
toString() [3/11]
std::string carl::toString (const rational & _number, bool _infix) inline
Definition at line 33 of file operations.h.
toString() [4/11]
std::string carl::toString (const InfinityValue & iv, bool _infix) inline
Definition at line 41 of file ModelValue.h.
toString() [5/11]
std::string carl::toString (Relation r) inline
Definition at line 52 of file Relation.h.
Referenced by operator<<(), toString(), carl::BVConstraint::toString(), carl::BVTermContent::toString(), carl::FLOAT_T< FloatType >::toString(), and carl::SMTLIBStream::write().
toString() [6/11]
template<typename T > std::enable_if<std::is_arithmetic<typename remove_all<T>::type>::value, std::string>::type carl::toString (const T & n, bool) inline
Definition at line 113 of file operations.h.
toString() [7/11]
std::string carl::toString (const cln::cl_RA & _number, bool _infix)
Definition at line 172 of file operations.cpp.
toString() [8/11]
std::string carl::toString (const mpq_class & _number, bool _infix)
Definition at line 179 of file operations.cpp.
toString() [9/11]
std::string carl::toString (const cln::cl_I & _number, bool _infix)
Definition at line 189 of file operations.cpp.
toString() [10/11]
std::string carl::toString (const mpz_class & _number, bool _infix)
Definition at line 196 of file operations.cpp.
toString() [11/11]
template<typename IntegerType > std::string carl::toString (const GFNumber< IntegerType > & _number, bool)
Creates the string representation to the given galois field number.
Parameters
_number The galois field number to get its string representation for.
Returns
The string representation to the given galois field number.
Definition at line 210 of file GFNumber.h.
try_parse()
template<typename T > bool carl::try_parse (const std::string & n, T & res) inline
try_parse< cln::cl_I >()
template<> bool carl::try_parse< cln::cl_I > (const std::string & n, cln::cl_I & res)
Definition at line 155 of file operations.cpp.
try_parse< cln::cl_RA >()
template<> bool carl::try_parse< cln::cl_RA > (const std::string & n, cln::cl_RA & res)
Definition at line 168 of file operations.cpp.
try_parse< mpq_class >()
template<> bool carl::try_parse< mpq_class > (const std::string & n, mpq_class & res)
Definition at line 175 of file operations.cpp.
try_parse< mpz_class >()
template<> bool carl::try_parse< mpz_class > (const std::string & n, mpz_class & res)
Definition at line 162 of file operations.cpp.
tuple_accumulate()
template<typename Tuple , typename T , typename F > T carl::tuple_accumulate (Tuple && t, T && init, F && f)
Implements a functional fold (similar to std::accumulate) for std::tuple.
Combines all tuple elements using a combinator function f and an initial value init.
Definition at line 139 of file tuple_util.h.
Referenced by carl::detail::operator<<().
tuple_apply()
template<typename F , typename Tuple > auto carl::tuple_apply (F && f, Tuple && t)
Invokes a callable object f on a tuple of arguments.
This is basically std::apply (available with C++17).
Definition at line 90 of file tuple_util.h.
tuple_cat()
template<typename Tuple1 , typename Tuple2 > auto carl::tuple_cat (Tuple1 && t1, Tuple2 && t2)
Definition at line 23 of file tuple_util.h.
Referenced by carl::tuple_convert< Converter, Information, FOut, TOut >::operator()().
tuple_foreach()
template<typename F , typename Tuple > auto carl::tuple_foreach (F && f, Tuple && t)
Invokes a callable object f on every element of a tuple and returns a tuple containing the results.
This basically corresponds to the functional map(func, list).`
Definition at line 110 of file tuple_util.h.
tuple_tail()
template<typename Tuple > auto carl::tuple_tail (Tuple && t)
Returns a new tuple containing everything but the first element.
Definition at line 46 of file tuple_util.h.
Referenced by carl::tuple_convert< Converter, Information, FOut, TOut >::operator()().
turnAroundRelation()
Relation carl::turnAroundRelation (const Relation & _rel) inline
Turns around the given relation symbol.
Parameters
_rel The relation symbol to invert.
Returns
The resulting inverted relation symbol.
Definition at line 79 of file Constraint.h.
typeId()
std::size_t carl::typeId (const BVTermType _type) inline
Definition at line 73 of file BVTerm.h.
typeIsBinary()
bool carl::typeIsBinary (const BVTermType _type) inline
Definition at line 87 of file BVTerm.h.
Referenced by carl::BVTermContent::BVTermContent(), carl::BVTermContent::collectVariables(), carl::BVTerm::complexity(), carl::BVTerm::substitute(), carl::model::substituteIn(), and carl::BVTermContent::toString().
typeIsUnary()
bool carl::typeIsUnary (const BVTermType _type) inline
Definition at line 78 of file BVTerm.h.
Referenced by carl::BVTermContent::BVTermContent(), carl::BVTermContent::collectVariables(), carl::BVTerm::complexity(), carl::BVTerm::substitute(), carl::model::substituteIn(), and carl::BVTermContent::toString().
typeString()
template<typename T > std::string carl::typeString ()
Definition at line 38 of file debug.h.
univariateTarskiQuery() [1/2]
template<typename Number > int carl::univariateTarskiQuery (const UnivariatePolynomial< Number > & p, const UnivariatePolynomial< Number > & q, const UnivariatePolynomial< Number > & der_q)
Definition at line 38 of file UnivariateTarskiQuery.h.
Referenced by carl::TarskiQueryManager< carl::Number >::operator()(), and univariateTarskiQuery().
univariateTarskiQuery() [2/2]
template<typename Number > int carl::univariateTarskiQuery (const UnivariatePolynomial< Number > & p, const UnivariatePolynomial< Number > & q)
Definition at line 48 of file UnivariateTarskiQuery.h.
variableTypeFromString()
VariableType carl::variableTypeFromString (const std::string & in)
Parameters
in A string describing the variable type (e.g. produced by to_string)
Returns
the corresponding variable type
Definition at line 12 of file Variable.cpp.
variant_extend()
template<typename Target , typename... Args> Target carl::variant_extend (const boost::variant< Args... > & variant)
Definition at line 36 of file variant_util.h.
variant_hash()
template<typename... T> std::size_t carl::variant_hash (const boost::variant< T... > & value) inline
Definition at line 50 of file variant_util.h.
Referenced by carl::ModelVariable::hash(), and std::hash< carl::VariableComparison< Pol > >::operator()().
variant_is_type()
template<typename T , typename Variant > bool carl::variant_is_type (const Variant & variant) noexcept
Checks whether a variant contains a value of a fiven type.
Definition at line 22 of file variant_util.h.
vector_concat() [1/2]
template<typename T > void carl::vector_concat (std::vector< T > & result, const std::vector< std::vector< T >> & input)
Definition at line 9 of file vector_util.h.
Referenced by vector_concat().
vector_concat() [2/2]
template<typename T > std::vector<T> carl::vector_concat (const std::vector< std::vector< T >> & input)
Definition at line 16 of file vector_util.h.
vector_zip()
template<typename T1 , typename T2 > std::vector<std::pair<T1, T2> > carl::vector_zip (const std::vector< T1 > & v1, const std::vector< T2 > & v2)
Definition at line 23 of file vector_util.h.
vector_zip_tuple()
template<typename Result , typename Input , typename... Inputs> void carl::vector_zip_tuple (Result & res, const Input & input, const Inputs &... inputs)
Definition at line 52 of file vector_util.h.
Variable Documentation
A_AND_B__IFF_C
const signed carl::A_AND_B__IFF_C = -3
Definition at line 845 of file Constraint.h.
Referenced by compare().
A_IFF_B
const signed carl::A_IFF_B = 2
Definition at line 841 of file Constraint.h.
Referenced by compare().
A_IMPLIES_B
const signed carl::A_IMPLIES_B = 1
Definition at line 842 of file Constraint.h.
Referenced by compare().
A_XOR_B
const signed carl::A_XOR_B = -4
Definition at line 846 of file Constraint.h.
Referenced by compare().
B_IMPLIES_A
const signed carl::B_IMPLIES_A = -1
Definition at line 843 of file Constraint.h.
Referenced by compare().
CONDITION_SIZE
constexpr std::size_t carl::CONDITION_SIZE = 64 static
Definition at line 17 of file Condition.h.
dummy
const dtl::enabled carl::dummy = {}
Definition at line 50 of file SFINAE.h.
FULL_EFFORT_FOR_DEFINITENESS_CHECK
constexpr bool carl::FULL_EFFORT_FOR_DEFINITENESS_CHECK = false static
Definition at line 130 of file Common.h.
HIGHTEST_INTEGER_VALUE
const ContentType carl::HIGHTEST_INTEGER_VALUE = (std::numeric_limits<ContentType>::max() >> ((std::numeric_limits<ContentType>::digits/2)+1))+1
Definition at line 22 of file Numeric.h.
Referenced by isInteger(), carl::Numeric< T >::maybeRationalize(), carl::Numeric< T >::operator typename IntegralType< T >::type(), carl::Numeric< T >::rational(), carl::Numeric< T >::rRational(), carl::Numeric< T >::toRational(), and carl::Numeric< T >::withinNativeRange().
initvariable
int carl::initvariable = initialize() static
Call to initialize.
Definition at line 57 of file initialize.h.
Referenced by initialize().
last_assertion_code
int carl::last_assertion_code = 23
Stores an integer representation of the last assertion that was registered via REGISTER_ASSERT.
Definition at line 72 of file debug.cpp.
Referenced by handle_signal().
last_assertion_string
std::string carl::last_assertion_string
Stores a textual representation of the last assertion that was registered via REGISTER_ASSERT.
Definition at line 71 of file debug.cpp.
Referenced by handle_signal().
MAX_DEGREE_FOR_FACTORIZATION
constexpr uint carl::MAX_DEGREE_FOR_FACTORIZATION = 6 static
Todo:
move static variables to own cpp
Definition at line 122 of file Common.h.
MAX_DIMENSION_FOR_FACTORIZATION
constexpr uint carl::MAX_DIMENSION_FOR_FACTORIZATION = 6 static
Definition at line 126 of file Common.h.
MAX_NUMBER_OF_MONOMIALS_FOR_FACTORIZATION
constexpr uint carl::MAX_NUMBER_OF_MONOMIALS_FOR_FACTORIZATION = 10 static
Definition at line 128 of file Common.h.
MIN_DEGREE_FOR_FACTORIZATION
constexpr uint carl::MIN_DEGREE_FOR_FACTORIZATION = 1 static
Definition at line 124 of file Common.h.
mMap
std::map<Variable, Interval<double> > carl::mMap = {{ Variable::NO_VARIABLE , Interval<double>(0)}} static
Definition at line 20 of file MultivariateHorner.h.
NOT__A_AND_B
const signed carl::NOT__A_AND_B = -2
Definition at line 844 of file Constraint.h.
Referenced by compare().
ONE_DIVIDED_BY_10_TO_THE_POWER_OF_23
const cln::cl_RA carl::ONE_DIVIDED_BY_10_TO_THE_POWER_OF_23 = cln::cl_RA(1)/cln::expt(cln::cl_RA(10), 23) static
Definition at line 201 of file operations.h.
Referenced by rationalize< cln::cl_RA >().
ONE_DIVIDED_BY_10_TO_THE_POWER_OF_52
const cln::cl_RA carl::ONE_DIVIDED_BY_10_TO_THE_POWER_OF_52 = cln::cl_RA(1)/cln::expt(cln::cl_RA(10), 52) static
Definition at line 202 of file operations.h.
Referenced by rationalize< cln::cl_RA >().
PROP_CONTAINS_BITVECTOR
constexpr Condition carl::PROP_CONTAINS_BITVECTOR = Condition(26) static
Definition at line 72 of file Condition.h.
Referenced by carl::Formula< Poly >::isOnlyPropositional().
PROP_CONTAINS_BOOLEAN
constexpr Condition carl::PROP_CONTAINS_BOOLEAN = Condition(22) static
Definition at line 68 of file Condition.h.
Referenced by carl::Formula< Poly >::booleanVars(), carl::Formula< Poly >::isConstraintConjunction(), carl::Formula< Poly >::isIntegerConstraintConjunction(), and carl::Formula< Poly >::isRealConstraintConjunction().
PROP_CONTAINS_EQUATION
constexpr Condition carl::PROP_CONTAINS_EQUATION = Condition(16) static
Definition at line 62 of file Condition.h.
PROP_CONTAINS_INEQUALITY
constexpr Condition carl::PROP_CONTAINS_INEQUALITY = Condition(17) static
Definition at line 63 of file Condition.h.
PROP_CONTAINS_INTEGER_VALUED_VARS
constexpr Condition carl::PROP_CONTAINS_INTEGER_VALUED_VARS = Condition(23) static
Definition at line 69 of file Condition.h.
Referenced by carl::Formula< Poly >::arithmeticVars(), carl::Formula< Poly >::integerValuedVars(), carl::Formula< Poly >::isOnlyPropositional(), and carl::Formula< Poly >::isRealConstraintConjunction().
PROP_CONTAINS_LINEAR_POLYNOMIAL
constexpr Condition carl::PROP_CONTAINS_LINEAR_POLYNOMIAL = Condition(19) static
Definition at line 65 of file Condition.h.
PROP_CONTAINS_MULTIVARIATE_POLYNOMIAL
constexpr Condition carl::PROP_CONTAINS_MULTIVARIATE_POLYNOMIAL = Condition(21) static
Definition at line 67 of file Condition.h.
PROP_CONTAINS_NONLINEAR_POLYNOMIAL
constexpr Condition carl::PROP_CONTAINS_NONLINEAR_POLYNOMIAL = Condition(20) static
Definition at line 66 of file Condition.h.
PROP_CONTAINS_PSEUDOBOOLEAN
constexpr Condition carl::PROP_CONTAINS_PSEUDOBOOLEAN = Condition(27) static
Definition at line 73 of file Condition.h.
Referenced by carl::Formula< Poly >::isOnlyPropositional().
PROP_CONTAINS_REAL_VALUED_VARS
constexpr Condition carl::PROP_CONTAINS_REAL_VALUED_VARS = Condition(24) static
Definition at line 70 of file Condition.h.
Referenced by carl::Formula< Poly >::arithmeticVars(), carl::Formula< Poly >::isIntegerConstraintConjunction(), carl::Formula< Poly >::isOnlyPropositional(), and carl::Formula< Poly >::realValuedVars().
PROP_CONTAINS_STRICT_INEQUALITY
constexpr Condition carl::PROP_CONTAINS_STRICT_INEQUALITY = Condition(18) static
Definition at line 64 of file Condition.h.
PROP_CONTAINS_UNINTERPRETED_EQUATIONS
constexpr Condition carl::PROP_CONTAINS_UNINTERPRETED_EQUATIONS = Condition(25) static
Definition at line 71 of file Condition.h.
Referenced by carl::Formula< Poly >::isOnlyPropositional().
PROP_CONTAINS_WEAK_INEQUALITY
constexpr Condition carl::PROP_CONTAINS_WEAK_INEQUALITY = Condition(31) static
Definition at line 77 of file Condition.h.
PROP_IS_A_CLAUSE
constexpr Condition carl::PROP_IS_A_CLAUSE = Condition(3) static
Definition at line 54 of file Condition.h.
PROP_IS_A_LITERAL
constexpr Condition carl::PROP_IS_A_LITERAL = Condition(4) static
Definition at line 55 of file Condition.h.
Referenced by carl::Formula< Poly >::isLiteral().
PROP_IS_AN_ATOM
constexpr Condition carl::PROP_IS_AN_ATOM = Condition(5) static
Definition at line 56 of file Condition.h.
PROP_IS_IN_CNF
constexpr Condition carl::PROP_IS_IN_CNF = Condition(1) static
Definition at line 52 of file Condition.h.
PROP_IS_IN_NNF
constexpr Condition carl::PROP_IS_IN_NNF = Condition(0) static
Definition at line 51 of file Condition.h.
PROP_IS_LITERAL_CONJUNCTION
constexpr Condition carl::PROP_IS_LITERAL_CONJUNCTION = Condition(6) static
Definition at line 57 of file Condition.h.
PROP_IS_PURE_CONJUNCTION
constexpr Condition carl::PROP_IS_PURE_CONJUNCTION = Condition(2) static
Definition at line 53 of file Condition.h.
Referenced by carl::Formula< Poly >::isConstraintConjunction(), carl::Formula< Poly >::isIntegerConstraintConjunction(), and carl::Formula< Poly >::isRealConstraintConjunction().
PROP_TRUE
constexpr Condition carl::PROP_TRUE = Condition() static
Definition at line 48 of file Condition.h.
Referenced by carl::Formula< Poly >::propertyHolds().
PROP_VARIABLE_DEGREE_GREATER_THAN_FOUR
constexpr Condition carl::PROP_VARIABLE_DEGREE_GREATER_THAN_FOUR = Condition(30) static
Definition at line 76 of file Condition.h.
PROP_VARIABLE_DEGREE_GREATER_THAN_THREE
constexpr Condition carl::PROP_VARIABLE_DEGREE_GREATER_THAN_THREE = Condition(29) static
Definition at line 75 of file Condition.h.
PROP_VARIABLE_DEGREE_GREATER_THAN_TWO
constexpr Condition carl::PROP_VARIABLE_DEGREE_GREATER_THAN_TWO = Condition(28) static
Definition at line 74 of file Condition.h.
signal_installed
bool carl::signal_installed = install_signal_handler() static
Static variable that ensures that install_signal_handler is called.
Definition at line 101 of file debug.cpp.
sizeOfUnsigned
constexpr unsigned carl::sizeOfUnsigned = sizeof(unsigned)
Definition at line 17 of file BitVector.h.
Referenced by carl::BitVector::findFirstSetBit(), and carl::BitVector::size().
STRONG_CONDITIONS
const Condition carl::STRONG_CONDITIONS static
Definition at line 58 of file Condition.h.
WEAK_CONDITIONS
const Condition carl::WEAK_CONDITIONS static
Definition at line 78 of file Condition.h.