carl: carl::tree_detail Namespace Reference
carl::tree_detail Namespace Reference
Data Structures
struct BaseIterator
This is the base class for all iterators.
struct ChildrenIterator
Iterator class for iterations over all children of a given element.
struct DepthIterator
Iterator class for iterations over all elements of a certain depth.
struct LeafIterator
Iterator class for iterations over all leaf elements.
struct Node
struct PathIterator
Iterator class for iterations from a given element to the root.
struct PostorderIterator
Iterator class for post-order iterations over all elements.
struct PreorderIterator
Iterator class for pre-order iterations over all elements.
Functions
template<typename T >
bool operator== (const Node< T > &lhs, const Node< T > &rhs)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Node< T > &n)
template<typename T , typename I , bool r>
T & operator* (BaseIterator< T, I, r > &bi)
template<typename T , typename I , bool r>
const T & operator* (const BaseIterator< T, I, r > &bi)
template<typename T , typename I , bool reverse>
std::enable_if<!reverse, I >::type & operator++ (BaseIterator< T, I, reverse > &it)
template<typename T , typename I , bool reverse>
std::enable_if< reverse, I >::type & operator++ (BaseIterator< T, I, reverse > &it)
template<typename T , typename I , bool reverse>
std::enable_if<!reverse, I >::type operator++ (BaseIterator< T, I, reverse > &it, int)
template<typename T , typename I , bool reverse>
std::enable_if< reverse, I >::type operator++ (BaseIterator< T, I, reverse > &it, int)
template<typename T , typename I , bool reverse>
std::enable_if<!reverse, I >::type & operator-- (BaseIterator< T, I, reverse > &it)
template<typename T , typename I , bool reverse>
std::enable_if< reverse, I >::type & operator-- (BaseIterator< T, I, reverse > &it)
template<typename T , typename I , bool reverse>
std::enable_if<!reverse, I >::type operator-- (BaseIterator< T, I, reverse > &it, int)
template<typename T , typename I , bool reverse>
std::enable_if< reverse, I >::type operator-- (BaseIterator< T, I, reverse > &it, int)
template<typename T , typename I , bool r>
bool operator== (const BaseIterator< T, I, r > &i1, const BaseIterator< T, I, r > &i2)
template<typename T , typename I , bool r>
bool operator!= (const BaseIterator< T, I, r > &i1, const BaseIterator< T, I, r > &i2)
template<typename T , typename I , bool r>
bool operator< (const BaseIterator< T, I, r > &i1, const BaseIterator< T, I, r > &i2)
Variables
constexpr std::size_t MAXINT = std::numeric_limits<std::size_t>::max()
Function Documentation
operator!=()
template<typename T , typename I , bool r> bool carl::tree_detail::operator!= (const BaseIterator< T, I, r > & i1, const BaseIterator< T, I, r > & i2)
Definition at line 163 of file carlTree.h.
operator*() [1/2]
template<typename T , typename I , bool r> T& carl::tree_detail::operator* (BaseIterator< T, I, r > & bi)
Definition at line 116 of file carlTree.h.
operator*() [2/2]
template<typename T , typename I , bool r> const T& carl::tree_detail::operator* (const BaseIterator< T, I, r > & bi)
Definition at line 120 of file carlTree.h.
operator++() [1/4]
template<typename T , typename I , bool reverse> std::enable_if<!reverse,I>::type& carl::tree_detail::operator++ (BaseIterator< T, I, reverse > & it)
Definition at line 125 of file carlTree.h.
operator++() [2/4]
template<typename T , typename I , bool reverse> std::enable_if<reverse,I>::type& carl::tree_detail::operator++ (BaseIterator< T, I, reverse > & it)
Definition at line 129 of file carlTree.h.
operator++() [3/4]
template<typename T , typename I , bool reverse> std::enable_if<!reverse,I>::type carl::tree_detail::operator++ (BaseIterator< T, I, reverse > & it, int)
Definition at line 133 of file carlTree.h.
operator++() [4/4]
template<typename T , typename I , bool reverse> std::enable_if<reverse,I>::type carl::tree_detail::operator++ (BaseIterator< T, I, reverse > & it, int)
Definition at line 137 of file carlTree.h.
operator--() [1/4]
template<typename T , typename I , bool reverse> std::enable_if<!reverse,I>::type& carl::tree_detail::operator-- (BaseIterator< T, I, reverse > & it)
Definition at line 141 of file carlTree.h.
operator--() [2/4]
template<typename T , typename I , bool reverse> std::enable_if<reverse,I>::type& carl::tree_detail::operator-- (BaseIterator< T, I, reverse > & it)
Definition at line 145 of file carlTree.h.
operator--() [3/4]
template<typename T , typename I , bool reverse> std::enable_if<!reverse,I>::type carl::tree_detail::operator-- (BaseIterator< T, I, reverse > & it, int)
Definition at line 149 of file carlTree.h.
operator--() [4/4]
template<typename T , typename I , bool reverse> std::enable_if<reverse,I>::type carl::tree_detail::operator-- (BaseIterator< T, I, reverse > & it, int)
Definition at line 153 of file carlTree.h.
operator<()
template<typename T , typename I , bool r> bool carl::tree_detail::operator< (const BaseIterator< T, I, r > & i1, const BaseIterator< T, I, r > & i2)
Definition at line 167 of file carlTree.h.
operator<<()
template<typename T > std::ostream& carl::tree_detail::operator<< (std::ostream & os, const Node< T > & n)
Definition at line 46 of file carlTree.h.
operator==() [1/2]
template<typename T > bool carl::tree_detail::operator== (const Node< T > & lhs, const Node< T > & rhs)
Definition at line 42 of file carlTree.h.
operator==() [2/2]
template<typename T , typename I , bool r> bool carl::tree_detail::operator== (const BaseIterator< T, I, r > & i1, const BaseIterator< T, I, r > & i2)
Definition at line 159 of file carlTree.h.
Variable Documentation
MAXINT
constexpr std::size_t carl::tree_detail::MAXINT = std::numeric_limits<std::size_t>::max()
Definition at line 25 of file carlTree.h.
Referenced by carl::tree< carl::RealAlgebraicNumber< carl::Number > >::begin_leaf(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::begin_postorder(), carl::tree_detail::ChildrenIterator< T, reverse >::ChildrenIterator(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::clear(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::createNode(), carl::tree_detail::DepthIterator< T, reverse >::DepthIterator(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::end_path(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::erase(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::eraseChildren(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::eraseNode(), carl::tree_detail::BaseIterator< T, DepthIterator< T, reverse >, reverse >::id(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::insert(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_leaf(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_leftmost(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_rightmost(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_valid(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::isConsistent(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::newNode(), carl::tree_detail::PreorderIterator< T, reverse >::next(), carl::tree_detail::PostorderIterator< T, reverse >::next(), carl::tree_detail::LeafIterator< T, reverse >::next(), carl::tree_detail::DepthIterator< T, reverse >::next(), carl::tree_detail::BaseIterator< T, DepthIterator< T, reverse >, reverse >::node(), operator<<(), carl::tree_detail::PreorderIterator< T, reverse >::previous(), carl::tree_detail::PostorderIterator< T, reverse >::previous(), carl::tree_detail::LeafIterator< T, reverse >::previous(), carl::tree_detail::DepthIterator< T, reverse >::previous(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::rbegin_leaf(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::rbegin_preorder(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::setRoot(), and carl::tree_detail::PreorderIterator< T, reverse >::skipChildren().