carl: carl::model Namespace Reference
carl::model Namespace Reference
Functions
template<typename T , typename Rational , typename Poly >
T substitute (const T &t, const Model< Rational, Poly > &m)
Substitutes a model into an expression t.
template<typename T , typename Rational , typename Poly >
ModelValue< Rational, Poly > evaluate (const T &t, const Model< Rational, Poly > &m)
Evaluates a given expression t over a model.
template<typename T , typename Rational , typename Poly >
unsigned satisfiedBy (const T &t, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
void substituteIn (BVTerm &bvt, const Model< Rational, Poly > &m)
Substitutes all variables from a model within a bitvector term.
template<typename Rational , typename Poly >
void substituteIn (BVConstraint &bvc, const Model< Rational, Poly > &m)
Substitutes all variables from a model within a bitvector constraint.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, BVTerm &bvt, const Model< Rational, Poly > &m)
Evaluates a bitvector term to a ModelValue over a Model.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, BVConstraint &bvc, const Model< Rational, Poly > &m)
Evaluates a bitvector constraint to a ModelValue over a Model.
template<typename Rational , typename Poly >
void substituteIn (Constraint< Poly > &c, const Model< Rational, Poly > &m)
Substitutes all variables from a model within a constraint.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, Constraint< Poly > &c, const Model< Rational, Poly > &m)
Evaluates a constraint to a ModelValue over a Model.
template<typename Rational , typename Poly >
void substituteSubformulas (Formula< Poly > &f, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
void evaluateVarCompare (Formula< Poly > &f, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
void evaluateVarAssign (Formula< Poly > &f, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
void substituteIn (Formula< Poly > &f, const Model< Rational, Poly > &m)
Substitutes all variables from a model within a formula.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, Formula< Poly > &f, const Model< Rational, Poly > &m)
Evaluates a formula to a ModelValue over a Model.
template<typename Rational , typename Poly >
RealAlgebraicNumberEvaluation::RANMap< Rational > collectRANIR (const std::set< Variable > &vars, const Model< Rational, Poly > &model)
template<typename Rational , typename Poly >
void substituteIn (MultivariateRoot< Poly > &mvr, Variable::Arg var, const Rational &r)
Substitutes a variable with a rational within a MultivariateRoot.
template<typename Rational , typename Poly >
void substituteIn (MultivariateRoot< Poly > &mvr, Variable::Arg var, const RealAlgebraicNumber< Rational > &r)
Substitutes a variable with a real algebraic number within a MultivariateRoot.
template<typename Rational , typename Poly >
void substituteIn (MultivariateRoot< Poly > &mvr, const Model< Rational, Poly > &m)
Substitutes all variables from a model within a MultivariateRoot.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, MultivariateRoot< Poly > &mvr, const Model< Rational, Poly > &m)
Evaluates a MultivariateRoot to a ModelValue over a Model.
template<typename Rational , typename Poly >
void substituteIn (PBConstraint< Poly > &c, const Model< Rational, Poly > &m)
Substitutes all variables from a model within a constraint.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, PBConstraint< Poly > &c, const Model< Rational, Poly > &m)
Evaluates a constraint to a ModelValue over a Model.
template<typename Rational >
void substituteIn (MultivariatePolynomial< Rational > &p, Variable::Arg var, const Rational &r)
Substitutes a variable with a rational within a polynomial.
template<typename Poly , typename Rational >
void substituteIn (UnivariatePolynomial< Poly > &p, Variable::Arg var, const Rational &r)
template<typename Rational >
void substituteIn (MultivariatePolynomial< Rational > &p, Variable::Arg var, const RealAlgebraicNumber< Rational > &r)
Substitutes a variable with a real algebraic number within a polynomial.
template<typename Poly , typename Rational >
void substituteIn (UnivariatePolynomial< Poly > &p, Variable::Arg var, const RealAlgebraicNumber< Rational > &r)
template<typename Rational , typename Poly , typename ModelPoly >
void substituteIn (Poly &p, const Model< Rational, ModelPoly > &m)
Substitutes all variables from a model within a polynomial.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, Poly &p, const Model< Rational, Poly > &m)
Evaluates a polynomial to a ModelValue over a Model.
template<typename Rational , typename Poly >
std::vector< RealAlgebraicNumber< Rational > > realRoots (const MultivariatePolynomial< Rational > &p, carl::Variable v, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
boost::optional< std::vector< RealAlgebraicNumber< Rational > > > realRoots (const UnivariatePolynomial< Poly > &p, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
boost::optional< std::vector< RealAlgebraicNumber< Rational > > > tryRealRoots (const MultivariatePolynomial< Rational > &p, carl::Variable v, const Model< Rational, Poly > &m)
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, const UVariable &uv, const Model< Rational, Poly > &m)
Evaluates a uninterpreted variable to a ModelValue over a Model.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, const UFInstance &ufi, const Model< Rational, Poly > &m)
Evaluates a uninterpreted function instance to a ModelValue over a Model.
template<typename Rational , typename Poly >
void evaluate (ModelValue< Rational, Poly > &res, const UEquality &ue, const Model< Rational, Poly > &m)
Evaluates a uninterpreted variable to a ModelValue over a Model.
Function Documentation
collectRANIR()
template<typename Rational , typename Poly > RealAlgebraicNumberEvaluation::RANMap<Rational> carl::model::collectRANIR (const std::set< Variable > & vars, const Model< Rational, Poly > & model)
Definition at line 9 of file ModelEvaluation_helper.h.
Referenced by evaluate(), realRoots(), and tryRealRoots().
evaluate() [1/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, const UVariable & uv, const Model< Rational, Poly > & m)
Evaluates a uninterpreted variable to a ModelValue over a Model.
Definition at line 15 of file ModelEvaluation_Uninterpreted.h.
evaluate() [2/11]
template<typename T , typename Rational , typename Poly > ModelValue< Rational, Poly > carl::model::evaluate (const T & t, const Model< Rational, Poly > & m)
Evaluates a given expression t over a model.
The result is always a ModelValue, though it may be a ModelSubstitution in some cases.
Definition at line 50 of file ModelEvaluation.h.
Referenced by evaluate(), carl::LazardEvaluation< Rational, Poly >::evaluatesToZero(), carl::ModelFormulaSubstitution< Rational, Poly >::evaluateSubstitution(), carl::ModelMVRootSubstitution< Rational, Poly >::evaluateSubstitution(), carl::ModelPolynomialSubstitution< Rational, Poly >::evaluateSubstitution(), satisfiedBy(), and substituteIn().
evaluate() [3/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, const UFInstance & ufi, const Model< Rational, Poly > & m)
Evaluates a uninterpreted function instance to a ModelValue over a Model.
Definition at line 25 of file ModelEvaluation_Uninterpreted.h.
evaluate() [4/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, Constraint< Poly > & c, const Model< Rational, Poly > & m)
Evaluates a constraint to a ModelValue over a Model.
If evaluation can not be done for some variables, the result may actually be a Constraint again.
Definition at line 26 of file ModelEvaluation_Constraint.h.
evaluate() [5/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, PBConstraint< Poly > & c, const Model< Rational, Poly > & m)
Evaluates a constraint to a ModelValue over a Model.
If evaluation can not be done for some variables, the result may actually be a Constraint again.
Definition at line 37 of file ModelEvaluation_PBConstraint.h.
evaluate() [6/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, const UEquality & ue, const Model< Rational, Poly > & m)
Evaluates a uninterpreted variable to a ModelValue over a Model.
Definition at line 44 of file ModelEvaluation_Uninterpreted.h.
evaluate() [7/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, BVTerm & bvt, const Model< Rational, Poly > & m)
Evaluates a bitvector term to a ModelValue over a Model.
Definition at line 46 of file ModelEvaluation_Bitvector.h.
evaluate() [8/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, MultivariateRoot< Poly > & mvr, const Model< Rational, Poly > & m)
Evaluates a MultivariateRoot to a ModelValue over a Model.
If evaluation can not be done for some variables, the result may actually be a ModelMVRootSubstitution.
Definition at line 48 of file ModelEvaluation_MVRoot.h.
evaluate() [9/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, Poly & p, const Model< Rational, Poly > & m)
Evaluates a polynomial to a ModelValue over a Model.
If evaluation can not be done for some variables, the result may actually be a ModelPolynomialSubstitution.
Definition at line 58 of file ModelEvaluation_Polynomial.h.
evaluate() [10/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, BVConstraint & bvc, const Model< Rational, Poly > & m)
Evaluates a bitvector constraint to a ModelValue over a Model.
Definition at line 60 of file ModelEvaluation_Bitvector.h.
evaluate() [11/11]
template<typename Rational , typename Poly > void carl::model::evaluate (ModelValue< Rational, Poly > & res, Formula< Poly > & f, const Model< Rational, Poly > & m)
Evaluates a formula to a ModelValue over a Model.
If evaluation can not be done for some variables, the result may actually be a ModelPolynomialSubstitution.
Definition at line 207 of file ModelEvaluation_Formula.h.
evaluateVarAssign()
template<typename Rational , typename Poly > void carl::model::evaluateVarAssign (Formula< Poly > & f, const Model< Rational, Poly > & m)
Definition at line 98 of file ModelEvaluation_Formula.h.
Referenced by substituteIn().
evaluateVarCompare()
template<typename Rational , typename Poly > void carl::model::evaluateVarCompare (Formula< Poly > & f, const Model< Rational, Poly > & m)
Definition at line 28 of file ModelEvaluation_Formula.h.
Referenced by substituteIn().
realRoots() [1/2]
template<typename Rational , typename Poly > std::vector<RealAlgebraicNumber<Rational> > carl::model::realRoots (const MultivariatePolynomial< Rational > & p, carl::Variable v, const Model< Rational, Poly > & m)
Definition at line 70 of file ModelEvaluation_Polynomial.h.
realRoots() [2/2]
template<typename Rational , typename Poly > boost::optional<std::vector<RealAlgebraicNumber<Rational> > > carl::model::realRoots (const UnivariatePolynomial< Poly > & p, const Model< Rational, Poly > & m)
Definition at line 76 of file ModelEvaluation_Polynomial.h.
satisfiedBy()
template<typename T , typename Rational , typename Poly > unsigned carl::model::satisfiedBy (const T & t, const Model< Rational, Poly > & m)
Definition at line 61 of file ModelEvaluation.h.
substitute()
template<typename T , typename Rational , typename Poly > T carl::model::substitute (const T & t, const Model< Rational, Poly > & m)
Substitutes a model into an expression t.
The result is always an expression of the same type. This may not be possible for some expressions, for example for uninterpreted equalities.
Definition at line 39 of file ModelEvaluation.h.
Referenced by realRoots(), carl::DiophantineEquations< Integer >::solveMultivariateDiophantine(), substituteIn(), substituteSubformulas(), and tryRealRoots().
substituteIn() [1/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (MultivariateRoot< Poly > & mvr, Variable::Arg var, const Rational & r)
Substitutes a variable with a rational within a MultivariateRoot.
Definition at line 12 of file ModelEvaluation_MVRoot.h.
substituteIn() [2/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (BVTerm & bvt, const Model< Rational, Poly > & m)
Substitutes all variables from a model within a bitvector term.
Definition at line 14 of file ModelEvaluation_Bitvector.h.
Referenced by evaluate(), substitute(), and substituteIn().
substituteIn() [3/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (PBConstraint< Poly > & c, const Model< Rational, Poly > & m)
Substitutes all variables from a model within a constraint.
May fail to substitute some variables, for example if the values are RANs or SqrtEx.
Definition at line 14 of file ModelEvaluation_PBConstraint.h.
substituteIn() [4/13]
template<typename Rational > void carl::model::substituteIn (MultivariatePolynomial< Rational > & p, Variable::Arg var, const Rational & r)
Substitutes a variable with a rational within a polynomial.
Definition at line 14 of file ModelEvaluation_Polynomial.h.
substituteIn() [5/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (Constraint< Poly > & c, const Model< Rational, Poly > & m)
Substitutes all variables from a model within a constraint.
May fail to substitute some variables, for example if the values are RANs or SqrtEx.
Definition at line 17 of file ModelEvaluation_Constraint.h.
substituteIn() [6/13]
template<typename Poly , typename Rational > void carl::model::substituteIn (UnivariatePolynomial< Poly > & p, Variable::Arg var, const Rational & r)
Definition at line 18 of file ModelEvaluation_Polynomial.h.
substituteIn() [7/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (MultivariateRoot< Poly > & mvr, Variable::Arg var, const RealAlgebraicNumber< Rational > & r)
Substitutes a variable with a real algebraic number within a MultivariateRoot.
Only works if the real algebraic number is actually numeric.
Definition at line 21 of file ModelEvaluation_MVRoot.h.
substituteIn() [8/13]
template<typename Rational > void carl::model::substituteIn (MultivariatePolynomial< Rational > & p, Variable::Arg var, const RealAlgebraicNumber< Rational > & r)
Substitutes a variable with a real algebraic number within a polynomial.
Only works if the real algebraic number is actually numeric.
Definition at line 27 of file ModelEvaluation_Polynomial.h.
substituteIn() [9/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (MultivariateRoot< Poly > & mvr, const Model< Rational, Poly > & m)
Substitutes all variables from a model within a MultivariateRoot.
May fail to substitute some variables, for example if the values are RANs or SqrtEx.
Definition at line 30 of file ModelEvaluation_MVRoot.h.
substituteIn() [10/13]
template<typename Poly , typename Rational > void carl::model::substituteIn (UnivariatePolynomial< Poly > & p, Variable::Arg var, const RealAlgebraicNumber< Rational > & r)
Definition at line 31 of file ModelEvaluation_Polynomial.h.
substituteIn() [11/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (BVConstraint & bvc, const Model< Rational, Poly > & m)
Substitutes all variables from a model within a bitvector constraint.
Definition at line 38 of file ModelEvaluation_Bitvector.h.
substituteIn() [12/13]
template<typename Rational , typename Poly , typename ModelPoly > void carl::model::substituteIn (Poly & p, const Model< Rational, ModelPoly > & m)
Substitutes all variables from a model within a polynomial.
May fail to substitute some variables, for example if the values are RANs or SqrtEx.
Definition at line 40 of file ModelEvaluation_Polynomial.h.
substituteIn() [13/13]
template<typename Rational , typename Poly > void carl::model::substituteIn (Formula< Poly > & f, const Model< Rational, Poly > & m)
Substitutes all variables from a model within a formula.
May fail to substitute some variables, for example if the values are RANs or SqrtEx.
TODO: We should store the substitution.
Definition at line 118 of file ModelEvaluation_Formula.h.
substituteSubformulas()
template<typename Rational , typename Poly > void carl::model::substituteSubformulas (Formula< Poly > & f, const Model< Rational, Poly > & m)
Definition at line 15 of file ModelEvaluation_Formula.h.
Referenced by substituteIn().
tryRealRoots()
template<typename Rational , typename Poly > boost::optional<std::vector<RealAlgebraicNumber<Rational> > > carl::model::tryRealRoots (const MultivariatePolynomial< Rational > & p, carl::Variable v, const Model< Rational, Poly > & m)
Definition at line 83 of file ModelEvaluation_Polynomial.h.