carl: carl::Formula< Pol > Singleton Reference
carl::Formula< Pol > Singleton Reference
The formula class representing a SMT formula.
#include <Formula.h>
Public Types
typedef Formulas< Pol >
::const_iterator const_iterator
A constant iterator to a sub-formula of a formula.
typedef Formulas< Pol >
::const_reverse_iterator const_reverse_iterator
A constant reverse iterator to a sub-formula of a formula.
typedef Pol PolynomialType
A typedef for the template argument.
typedef FastMap< Pol, std::map
< typename Pol::NumberType,
std::pair< Relation, Formula > > > ConstraintBounds
A map from formula pointers to a map of rationals to a pair of a constraint relation and a formula pointer. (internally used)
Public Member Functions
Formula (FormulaType _type=FALSE)
Formula (Variable::Arg _booleanVar)
Formula (const Pol &_pol, Relation _rel)
Formula (const Constraint< Pol > &_constraint)
Formula (const BVConstraint &_constraint)
Formula (FormulaType _type, Formula &&_subformula)
Formula (FormulaType _type, const Formula &_subformula)
Formula (FormulaType _type, const Formula &_subformulaA, const Formula &_subformulaB)
Formula (FormulaType _type, const Formula &_subformulaA, const Formula &_subformulaB, const Formula &_subformulaC)
Formula (FormulaType _type, const FormulasMulti< Pol > &_subformulas)
Formula (FormulaType _type, const Formulas< Pol > &_subasts)
Formula (FormulaType _type, Formulas< Pol > &&_subasts)
Formula (FormulaType _type, const std::initializer_list< Formula< Pol >> &_subasts)
Formula (FormulaType _type, const FormulaSet< Pol > &_subasts)
Formula (FormulaType _type, FormulaSet< Pol > &&_subasts)
Formula (FormulaType _type, std::vector< Variable > &&_vars, const Formula &_term)
Formula (FormulaType _type, const std::vector< Variable > &_vars, const Formula &_term)
Formula (const UEquality::Arg &_lhs, const UEquality::Arg &_rhs, bool _negated)
Formula (UEquality &&_eq)
Formula (const UEquality &_eq)
Formula (const Formula &_formula)
Formula (Formula &&_formula)
Formula & operator= (const Formula &_formula)
Formula & operator= (Formula &&_formula)
double activity () const
void setActivity (double _activity) const
Sets the activity to the given value.
double difficulty () const
void setDifficulty (double difficulty) const
Sets the difficulty to the given value.
FormulaType getType () const
size_t getHash () const
size_t getId () const
bool isTrue () const
bool isFalse () const
const Condition & properties () const
bool isTseitinClause () const
void realValuedVars (Variables &_realVars) const
Collects all real valued variables occurring in this formula.
void integerValuedVars (Variables &_intVars) const
Collects all integer valued variables occurring in this formula.
void arithmeticVars (Variables &_arithmeticVars) const
Collects all arithmetic variables occurring in this formula.
void booleanVars (Variables &_booleanVars) const
Collects all boolean variables occurring in this formula.
void allVars (Variables &_vars) const
Collects all variables occurring in this formula.
Formula negated () const
const Formula & subformula () const
const Formula & premise () const
const Formula & conclusion () const
const Formula & condition () const
const Formula & firstCase () const
const Formula & secondCase () const
const std::vector
< carl::Variable > & quantifiedVariables () const
const Formula & quantifiedFormula () const
const Formulas< Pol > & subformulas () const
const Constraint< Pol > & constraint () const
const BVConstraint & bvConstraint () const
carl::Variable::Arg boolean () const
const UEquality & uequality () const
size_t size () const
bool empty () const
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const Formula & back () const
bool propertyHolds (const Condition &_property) const
Checks if the given property holds for this formula.
bool isAtom () const
bool isLiteral () const
bool isBooleanCombination () const
bool isNary () const
bool isConstraintConjunction () const
bool isRealConstraintConjunction () const
bool isIntegerConstraintConjunction () const
bool contains (const Formula &_formula) const
void getConstraints (std::vector< Constraint< Pol >> &_constraints) const
Collects all constraint occurring in this formula.
void getConstraints (std::vector< Formula > &_constraints) const
Collects all constraint occurring in this formula.
void collectVariables (Variables &_vars, bool _booleanVars, bool _realVars, bool _integerVars, bool _uninterpretedVars, bool _bitvectorVars) const
Collects all Boolean variables occurring in this formula.
void collectVariables_ (Variables &_vars, std::set< BVVariable > *_bvVars, std::set< UVariable > *_ueVars, bool _booleanVars, bool _realVars, bool _integerVars, bool _uninterpretedVars, bool _bitvectorVars) const
size_t complexity () const
bool operator== (const Formula &_formula) const
bool operator!= (const Formula &_formula) const
bool operator< (const Formula &_formula) const
bool operator> (const Formula &_formula) const
bool operator<= (const Formula &_formula) const
bool operator>= (const Formula &_formula) const
unsigned satisfiedBy (const EvaluationMap< typename Pol::NumberType > &_assignment) const
std::string toString (bool _withActivity=false, unsigned _resolveUnequal=0, const std::string _init="", bool _oneline=true, bool _infix=false, bool _friendlyNames=true, bool _withVariableDefinition=false) const
Gives the string representation of this formula.
void printProposition (std::ostream &_out=std::cout, const std::string _init="") const
Prints the propositions of this formula.
std::string toRedlogFormat (bool _withVariables=true) const
std::string variableListToString (std::string _separator=",", const std::unordered_map< std::string, std::string > &_variableIds=(std::unordered_map< std::string, std::string >())) const
Gets a string, which represents all variables occurring in this formula in a row, separated by the given separator.
Formula resolveNegation (bool _keepConstraints=true) const
Resolves the outermost negation of this formula.
Formula connectPrecedingSubformulas () const
[Auxiliary method]
Formula toQF (QuantifiedVariables &variables, unsigned level=0, bool negated=false) const
Transforms this formula to its quantifier free equivalent.
Formula toCNF (bool _keepConstraints=true, bool _simplifyConstraintCombinations=false, bool _tseitinWithEquivalence=true) const
Transforms this formula to conjunctive normal form (CNF).
Formula substitute (carl::Variable::Arg _var, const Pol &_pol) const
Substitutes all occurrences of the given variable in this formula by the given polynomial.
Formula substitute (const std::map< carl::Variable, Pol > &_arithmeticSubstitutions) const
Substitutes all occurrences of the given arithmetic variables in this formula by the given polynomials.
Formula substitute (const std::map< carl::Variable, Formula > &_booleanSubstitutions) const
Substitutes all occurrences of the given Boolean variables in this formula by the given formulas.
Formula substitute (const std::map< carl::Variable, Formula > &_booleanSubstitutions, const std::map< carl::Variable, Pol > &_arithmeticSubstitutions) const
Substitutes all occurrences of the given Boolean and arithmetic variables in this formula by the given formulas resp.
Static Public Member Functions
static void addConstraintProperties (const Constraint< Pol > &_constraint, Condition &_properties)
Adds the propositions of the given constraint to the propositions of this formula.
static void init (FormulaContent< Pol > &_content)
Gets the propositions of this formula.
static Formula addConstraintBound (ConstraintBounds &_constraintBounds, const Formula &_constraint, bool _inConjunction)
Adds the bound to the bounds of the polynomial specified by this constraint.
static bool swapConstraintBounds (ConstraintBounds &_constraintBounds, Formulas< Pol > &_intoAsts, bool _inConjunction)
Stores for every polynomial for which we determined bounds for given constraints a minimal set of constraints representing these bounds into the given set of sub-formulas of a conjunction (_inConjunction == true) or disjunction (_inConjunction == false) to construct.
Private Member Functions
Formula (const FormulaContent< Pol > *_content)
void initHash ()
Private Attributes
const FormulaContent< Pol > * mpContent
The content of this formula.
Friends
class FormulaPool< Pol >
class FormulaContent< Pol >
template<typename P >
std::ostream & operator<< (std::ostream &_out, const Formula< P > &_formula)
The output operator of a formula.
Detailed Description
template<typename Pol>
singleton carl::Formula< Pol >
The formula class representing a SMT formula.
Definition at line 30 of file Formula.h.
Member Function Documentation
template<typename Pol> double carl::Formula< Pol >::activity () const inline
Returns
The activity for this formula, which means, how much is this formula involved in the solving procedure.
Definition at line 219 of file Formula.h.
template<typename Pol> static Formula carl::Formula< Pol >::addConstraintBound (ConstraintBounds & _constraintBounds, const Formula< Pol > & _constraint, bool _inConjunction) static
Adds the bound to the bounds of the polynomial specified by this constraint.
E.g., if the constraint is p+b~0, where p is a sum of terms, being a rational (actually integer) coefficient times a non-trivial (!=1) monomial(product of variables to the power of an exponent), b is a rational and ~ is any constraint relation. Furthermore, the leading coefficient of p is 1. Then we add the bound -b to the bounds of p (means that p ~ -b) stored in the given constraint bounds.
Parameters
_constraintBounds An object collecting bounds of polynomials.
_constraint The constraint to find a bound for a polynomial for.
_inConjunction true, if the constraint is part of a conjunction. false, if the constraint is part of a disjunction.
Returns
Formula(FALSE), if the yet determined bounds imply that the conjunction (_inConjunction == true) or disjunction (_inConjunction == false) of which we got the given constraint is invalid resp. valid; false, the added constraint.
template<typename Pol> static void carl::Formula< Pol >::addConstraintProperties (const Constraint< Pol > & _constraint, Condition & _properties) static
Adds the propositions of the given constraint to the propositions of this formula.
Parameters
_constraint The constraint to add propositions for.
_properties
template<typename Pol> void carl::Formula< Pol >::allVars (Variables & _vars) const inline
Collects all variables occurring in this formula.
Parameters
_vars The container to collect the variables in.
Definition at line 347 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::arithmeticVars (Variables & _arithmeticVars) const inline
Collects all arithmetic variables occurring in this formula.
Parameters
_arithmeticVars The container to collect the arithmetic variables in.
Definition at line 329 of file Formula.h.
template<typename Pol> const Formula& carl::Formula< Pol >::back () const inline
Returns
A reference to the last sub-formula of this formula.
Definition at line 542 of file Formula.h.
template<typename Pol> const_iterator carl::Formula< Pol >::begin () const inline
Returns
A constant iterator to the beginning of the list of sub-formulas of this formula.
Definition at line 505 of file Formula.h.
template<typename Pol> carl::Variable::Arg carl::Formula< Pol >::boolean () const inline
Returns
The name of the Boolean variable represented by this formula. Note, that this formula has to be of type BOOL, if you invoke this method.
Definition at line 459 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::booleanVars (Variables & _booleanVars) const inline
Collects all boolean variables occurring in this formula.
Parameters
_booleanVars The container to collect the boolean variables in.
Definition at line 338 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::collectVariables (Variables & _vars, bool _booleanVars, bool _realVars, bool _integerVars, bool _uninterpretedVars, bool _bitvectorVars) const
Collects all Boolean variables occurring in this formula.
Parameters
_vars The container to collect the Boolean variables in.
_type
_ofThisType
Referenced by carl::Formula< Pol >::allVars(), carl::Formula< Pol >::arithmeticVars(), carl::Formula< Pol >::booleanVars(), carl::Formula< Pol >::integerValuedVars(), and carl::Formula< Pol >::realValuedVars().
template<typename Pol> size_t carl::Formula< Pol >::complexity () const
Returns
The formula's complexity, which is mainly the number of operations within this formula.
template<typename Pol> const Formula& carl::Formula< Pol >::conclusion () const inline
Returns
A constant reference to the conclusion, in case this formula is an implication.
Definition at line 378 of file Formula.h.
template<typename Pol> const Formula& carl::Formula< Pol >::condition () const inline
Returns
A constant reference to the condition, in case this formula is an ite-expression of formulas.
Definition at line 387 of file Formula.h.
template<typename Pol> Formula carl::Formula< Pol >::connectPrecedingSubformulas () const
[Auxiliary method]
Returns
The formula combining the first to the second last sub-formula of this formula by the same operator as the one of this formula. Example: this = (op a1 a2 .. an) -> return = (op a1 .. an-1) If n = 2, return = a1
template<typename Pol> const Constraint<Pol>& carl::Formula< Pol >::constraint () const inline
Returns
A constant reference to the constraint represented by this formula. Note, that this formula has to be of type CONSTRAINT, if you invoke this method.
Definition at line 443 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::contains (const Formula< Pol > & _formula) const inline
Parameters
_formula The pointer to the formula for which to check whether it points to a sub-formula of this formula.
Returns
true, the given pointer to a formula points to a sub-formula of this formula; false, otherwise.
Definition at line 636 of file Formula.h.
template<typename Pol> double carl::Formula< Pol >::difficulty () const inline
Returns
Some value stating an expected difficulty of solving this formula for satisfiability.
Definition at line 238 of file Formula.h.
Referenced by carl::Formula< Pol >::setDifficulty().
template<typename Pol> bool carl::Formula< Pol >::empty () const inline
Returns
true, if this formula has sub-formulas; false, otherwise.
Definition at line 492 of file Formula.h.
template<typename Pol> const_iterator carl::Formula< Pol >::end () const inline
Returns
A constant iterator to the end of the list of sub-formulas of this formula.
Definition at line 514 of file Formula.h.
template<typename Pol> const Formula& carl::Formula< Pol >::firstCase () const inline
Returns
A constant reference to the then-case, in case this formula is an ite-expression of formulas.
Definition at line 396 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::getConstraints (std::vector< Constraint< Pol >> & _constraints) const inline
Collects all constraint occurring in this formula.
Parameters
_constraints The container to insert the constraint into.
Definition at line 652 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::getConstraints (std::vector< Formula< Pol > > & _constraints) const inline
Collects all constraint occurring in this formula.
Parameters
_constraints The container to insert the constraint into.
Definition at line 669 of file Formula.h.
template<typename Pol> size_t carl::Formula< Pol >::getHash () const inline
Returns
A hash value for this formula.
Definition at line 265 of file Formula.h.
Referenced by std::hash< carl::Formula< Pol > >::operator()().
template<typename Pol> size_t carl::Formula< Pol >::getId () const inline
Returns
The unique id for this formula.
Definition at line 273 of file Formula.h.
Referenced by carl::Formula< Pol >::operator<(), carl::Formula< Pol >::operator<=(), carl::Formula< Pol >::operator>(), and carl::Formula< Pol >::operator>=().
template<typename Pol> FormulaType carl::Formula< Pol >::getType () const inline
Returns
The type of this formula.
Definition at line 257 of file Formula.h.
template<typename Pol> static void carl::Formula< Pol >::init (FormulaContent< Pol > & _content) static
Gets the propositions of this formula.
It updates and stores the propositions if they are not up to date, hence this method is quite efficient.
template<typename Pol> void carl::Formula< Pol >::initHash () private
Returns
template<typename Pol> void carl::Formula< Pol >::integerValuedVars (Variables & _intVars) const inline
Collects all integer valued variables occurring in this formula.
Parameters
_intVars The container to collect the integer valued variables in.
Definition at line 320 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::isAtom () const inline
Returns
true, if this formula is a Boolean atom.
Definition at line 565 of file Formula.h.
Referenced by carl::Formula< Pol >::contains(), and carl::Formula< Pol >::isBooleanCombination().
template<typename Pol> bool carl::Formula< Pol >::isBooleanCombination () const inline
Returns
true, if the outermost operator of this formula is Boolean; false, otherwise.
Definition at line 581 of file Formula.h.
Referenced by carl::Formula< Pol >::back().
template<typename Pol> bool carl::Formula< Pol >::isConstraintConjunction () const inline
Returns
true, if this formula is a conjunction of constraints; false, otherwise.
Definition at line 598 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::isFalse () const inline
Returns
true, if this formula represents FALSE.
Definition at line 289 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::isIntegerConstraintConjunction () const inline
Returns
true, if this formula is a conjunction of integer constraints; false, otherwise.
Definition at line 622 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::isNary () const inline
Returns
true, if the type of this formulas allows n-ary combinations of sub-formulas, for an arbitrary n.
Definition at line 589 of file Formula.h.
Referenced by carl::Formula< Pol >::begin(), carl::Formula< Pol >::getConstraints(), carl::Formula< Pol >::rbegin(), carl::Formula< Pol >::rend(), and carl::Formula< Pol >::subformulas().
template<typename Pol> bool carl::Formula< Pol >::isRealConstraintConjunction () const inline
Returns
true, if this formula is a conjunction of real constraints; false, otherwise.
Definition at line 610 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::isTrue () const inline
Returns
true, if this formula represents TRUE.
Definition at line 281 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::operator!= (const Formula< Pol > & _formula) const inline
Parameters
_formula The formula to compare with.
Returns
true, if this formula and the given formula are not equal.
Definition at line 710 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::operator< (const Formula< Pol > & _formula) const inline
Parameters
_formula The formula to compare with.
Returns
true, if the id of this formula is less than the id of the given one.
Definition at line 719 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::operator<= (const Formula< Pol > & _formula) const inline
Parameters
_formula The formula to compare with.
Returns
true, if the id of this formula is less or equal than the id of the given one.
Definition at line 741 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::operator== (const Formula< Pol > & _formula) const inline
Parameters
_formula The formula to compare with.
Returns
true, if this formula and the given formula are equal; false, otherwise.
Definition at line 701 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::operator> (const Formula< Pol > & _formula) const inline
Parameters
_formula The formula to compare with.
Returns
true, if the id of this formula is greater than the id of the given one.
Definition at line 730 of file Formula.h.
template<typename Pol> bool carl::Formula< Pol >::operator>= (const Formula< Pol > & _formula) const inline
Parameters
_formula The formula to compare with.
Returns
true, if the id of this formula is greater or equal than the id of the given one.
Definition at line 752 of file Formula.h.
template<typename Pol> const Formula& carl::Formula< Pol >::premise () const inline
Returns
A constant reference to the premise, in case this formula is an implication.
Definition at line 369 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::printProposition (std::ostream & _out = std::cout, const std::string _init = "") const
Prints the propositions of this formula.
Parameters
_out The stream to print on.
_init The string to print initially in every row.
template<typename Pol> const Condition& carl::Formula< Pol >::properties () const inline
Returns
The bit-vector representing the propositions of this formula. For further information see the Condition class.
Definition at line 297 of file Formula.h.
Referenced by carl::Formula< Pol >::isConstraintConjunction(), carl::Formula< Pol >::isIntegerConstraintConjunction(), and carl::Formula< Pol >::isRealConstraintConjunction().
template<typename Pol> bool carl::Formula< Pol >::propertyHolds (const Condition & _property) const inline
Checks if the given property holds for this formula.
(Very cheap operation which only relies on bit checks)
Parameters
_property The property to check this formula for.
Returns
true, if the given property holds for this formula; false, otherwise.
Definition at line 557 of file Formula.h.
template<typename Pol> const Formula& carl::Formula< Pol >::quantifiedFormula () const inline
Returns
A constant reference to the bound formula, in case this formula is a quantified formula.
Definition at line 423 of file Formula.h.
template<typename Pol> const std::vector<carl::Variable>& carl::Formula< Pol >::quantifiedVariables () const inline
Returns
A constant reference to the quantifed variables, in case this formula is a quantified formula.
Definition at line 414 of file Formula.h.
template<typename Pol> const_reverse_iterator carl::Formula< Pol >::rbegin () const inline
Returns
A constant reverse iterator to the beginning of the list of sub-formulas of this formula.
Definition at line 524 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::realValuedVars (Variables & _realVars) const inline
Collects all real valued variables occurring in this formula.
Parameters
_realVars The container to collect the real valued variables in.
Definition at line 311 of file Formula.h.
template<typename Pol> const_reverse_iterator carl::Formula< Pol >::rend () const inline
Returns
A constant reverse iterator to the end of the list of sub-formulas of this formula.
Definition at line 533 of file Formula.h.
template<typename Pol> Formula carl::Formula< Pol >::resolveNegation (bool _keepConstraints = true) const
Resolves the outermost negation of this formula.
Parameters
_keepConstraints A flag indicating whether to change constraints in order to resolve the negation in front of them, or to keep the constraints and leave the negation.
template<typename Pol> unsigned carl::Formula< Pol >::satisfiedBy (const EvaluationMap< typename Pol::NumberType > & _assignment) const
Parameters
_assignment The assignment for which to check whether this formula is satisfied by it.
Returns
0, if this formula is violated by the given assignment; 1, if this formula is satisfied by the given assignment; 2, otherwise.
template<typename Pol> const Formula& carl::Formula< Pol >::secondCase () const inline
Returns
A constant reference to the else-case, in case this formula is an ite-expression of formulas.
Definition at line 405 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::setActivity (double _activity) const inline
Sets the activity to the given value.
Parameters
_activity The value to set the activity to.
Definition at line 229 of file Formula.h.
template<typename Pol> void carl::Formula< Pol >::setDifficulty (double difficulty) const inline
Sets the difficulty to the given value.
Parameters
difficulty The value to set the difficulty to.
Definition at line 248 of file Formula.h.
template<typename Pol> size_t carl::Formula< Pol >::size () const inline
Returns
The number of sub-formulas of this formula.
Definition at line 478 of file Formula.h.
template<typename Pol> const Formula& carl::Formula< Pol >::subformula () const inline
Returns
A constant reference to the only sub-formula, in case this formula is an negation.
Definition at line 360 of file Formula.h.
template<typename Pol> const Formulas<Pol>& carl::Formula< Pol >::subformulas () const inline
Returns
A constant reference to the list of sub-formulas of this formula. Note, that this formula has to be a Boolean combination, if you invoke this method.
Definition at line 433 of file Formula.h.
template<typename Pol> Formula carl::Formula< Pol >::substitute (carl::Variable::Arg _var, const Pol & _pol) const inline
Substitutes all occurrences of the given variable in this formula by the given polynomial.
Parameters
_var The variable to substitute.
_var The polynomial to substitute the variable for.
Returns
The resulting formula after substitution.
Definition at line 866 of file Formula.h.
Referenced by carl::Formula< Pol >::substitute().
template<typename Pol> Formula carl::Formula< Pol >::substitute (const std::map< carl::Variable, Pol > & _arithmeticSubstitutions) const inline
Substitutes all occurrences of the given arithmetic variables in this formula by the given polynomials.
Parameters
_arithmeticSubstitutions A substitution-mapping of arithmetic variables to polynomials.
Returns
The resulting formula after substitution.
Definition at line 879 of file Formula.h.
template<typename Pol> Formula carl::Formula< Pol >::substitute (const std::map< carl::Variable, Formula< Pol > > & _booleanSubstitutions) const inline
Substitutes all occurrences of the given Boolean variables in this formula by the given formulas.
Parameters
_booleanSubstitutions A substitution-mapping of Boolean variables to formulas.
Returns
The resulting formula after substitution.
Definition at line 890 of file Formula.h.
template<typename Pol> Formula carl::Formula< Pol >::substitute (const std::map< carl::Variable, Formula< Pol > > & _booleanSubstitutions, const std::map< carl::Variable, Pol > & _arithmeticSubstitutions) const
Substitutes all occurrences of the given Boolean and arithmetic variables in this formula by the given formulas resp.
polynomials.
Parameters
_booleanSubstitutions A substitution-mapping of Boolean variables to formulas.
_arithmeticSubstitutions A substitution-mapping of arithmetic variables to polynomials.
Returns
The resulting formula after substitution.
template<typename Pol> static bool carl::Formula< Pol >::swapConstraintBounds (ConstraintBounds & _constraintBounds, Formulas< Pol > & _intoAsts, bool _inConjunction) static
Stores for every polynomial for which we determined bounds for given constraints a minimal set of constraints representing these bounds into the given set of sub-formulas of a conjunction (_inConjunction == true) or disjunction (_inConjunction == false) to construct.
Parameters
_constraintBounds An object collecting bounds of polynomials.
_intoAsts A set of sub-formulas of a conjunction (_inConjunction == true) or disjunction (_inConjunction == false) to construct.
_inConjunction true, if constraints representing the polynomial's bounds are going to be part of a conjunction. false, if constraints representing the polynomial's bounds are going to be part of a disjunction.
Returns
true, if the yet added bounds imply that the conjunction (_inConjunction == true) or disjunction (_inConjunction == false) to which the bounds are added is invalid resp. valid; false, otherwise.
template<typename Pol> Formula carl::Formula< Pol >::toCNF (bool _keepConstraints = true, bool _simplifyConstraintCombinations = false, bool _tseitinWithEquivalence = true) const
Transforms this formula to conjunctive normal form (CNF).
Parameters
_keepConstraints A flag indicating whether to keep the constraints as they are, or to resolve constraints p!=0 to (or p<0 p>0) and to resolve negations in front of constraints, e.g., (not p<0) gets p>=0.
_simplifyConstraintCombinations A flag, which is true, if simplifications shall be applied to conjunctions disjunctions of constraints.
_tseitinWithEquivalence A flag, which is true, if variables, which are introduced by the tseitin encoding are set to be equivalent to the formula they represent. Otherwise, they imply the formula, which is also valid, as the current formula context is in NNF.
template<typename Pol> Formula carl::Formula< Pol >::toQF (QuantifiedVariables & variables, unsigned level = 0, bool negated = false) const
Transforms this formula to its quantifier free equivalent.
The quantifiers are represented by the parameter variables. Each entry in variables contains all variables between two quantifier alternations. The even entries (starting with 0) are quantified existentially, the odd entries are quantified universally.
Parameters
variables Contains the quantified variables.
level Used for internal recursion.
negated Used for internal recursion.
Returns
The quantifier-free version of this formula.
template<typename Pol> std::string carl::Formula< Pol >::toRedlogFormat (bool _withVariables = true) const
Parameters
_withVariables A flag indicating whether the variables shall be displayed before the formula.
Returns
A string which represents this formula in the input format of the tool Redlog.
template<typename Pol> std::string carl::Formula< Pol >::toString (bool _withActivity = false, unsigned _resolveUnequal = 0, const std::string _init = "", bool _oneline = true, bool _infix = false, bool _friendlyNames = true, bool _withVariableDefinition = false) const
Gives the string representation of this formula.
Parameters
_withActivity A flag which indicates whether to add the formula's activity to the result.
_resolveUnequal A switch which indicates how to represent the relation symbol for unequal. (for further description see documentation of Constraint::toString(..))
_init The initial string of every row of the result.
_oneline A flag indicating whether the formula shall be printed on one line.
_infix A flag indicating whether to print the formula in infix or prefix notation.
_friendlyNames A flag that indicates whether to print the variables with their internal representation (false) or with their dedicated names.
Returns
The resulting string representation of this formula.
template<typename Pol> const UEquality& carl::Formula< Pol >::uequality () const inline
Returns
A constant reference to the uninterpreted equality represented by this formula. Note, that this formula has to be of type UEQ, if you invoke this method.
Definition at line 469 of file Formula.h.
template<typename Pol> std::string carl::Formula< Pol >::variableListToString (std::string _separator = ",", const std::unordered_map< std::string, std::string > & _variableIds = (std::unordered_map< std::string, std::string >())) const
Gets a string, which represents all variables occurring in this formula in a row, separated by the given separator.
Parameters
_separator The separator between the variables.
_variableIds Maps variable names to names, which shall be used instead in the result.
Returns
The string, which represents all variables occurring in this formula in a row, separated by the given separator.
Friends And Related Function Documentation
template<typename Pol> template<typename P > std::ostream& operator<< (std::ostream & _out, const Formula< P > & _formula) friend
The output operator of a formula.
Parameters
_out The stream to print on.
_formula
The documentation for this singleton was generated from the following file:
carl/formula/Formula.h