carl: carl::Term< Coefficient > Class Template Reference
carl::Term< Coefficient > Class Template Reference
Polynomials » Multivariate Represented Polynomials
Represents a single term, that is a numeric coefficient and a monomial.
#include <Term.h>
Public Member Functions
Term ()
Default constructor.
Term (const Term &t)
Term (Term &&t)
Term & operator= (const Term &t)
Term & operator= (Term &&t)
Term (const Coefficient &c)
Constructs a term of value .
Term (Variable::Arg v)
Constructs a term of value .
Term (const Monomial::Arg &m)
Constructs a term of value .
Term (const Coefficient &c, const Monomial::Arg &m)
Constructs a term of value .
Term (Coefficient &&c, const Monomial::Arg &m)
Constructs a term of value .
Term (const Coefficient &c, Variable::Arg v, exponent e)
Constructs a term of value .
Coefficient & coeff ()
Get the coefficient.
const Coefficient & coeff () const
const Monomial::Arg & monomial () const
Get the monomial.
exponent tdeg () const
Gives the total degree, i.e.
bool isZero () const
Checks whether the term is zero.
bool isOne () const
Checks whether the term equals one.
bool isConstant () const
Checks whether the monomial is a constant.
bool integerValued () const
bool isLinear () const
Checks whether the monomial has exactly the degree one.
size_t getNrVariables () const
size_t complexity () const
bool has (Variable::Arg v) const
bool hasNoOtherVariable (Variable::Arg v) const
Checks if the monomial is either a constant or the only variable occuring is the variable v.
bool isSingleVariable () const
Variable::Arg getSingleVariable () const
For terms with exactly one variable, get this variable.
bool isSquare () const
Checks if the term is a square.
void clear ()
Set the term to zero with the canonical representation.
void negate ()
Negates the term by negating the coefficient.
Term divide (const Coefficient &c) const
bool divide (const Coefficient &c, Term &res) const
bool divide (Variable::Arg v, Term &res) const
bool divide (const Monomial::Arg &m, Term &res) const
bool divide (const Term &, Term &res) const
Term calcLcmAndDivideBy (const Monomial::Arg &m) const
bool sqrt (Term &res) const
Calculates the square root of this term.
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
bool divisible (const Term &) const
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy>
bool divisible (const Term &) const
Term derivative (Variable::Arg) const
Definiteness definiteness () const
template<typename SubstitutionType = Coefficient>
Term substitute (const std::map< Variable, SubstitutionType > &substitutions) const
Term substitute (const std::map< Variable, Term< Coefficient >> &substitutions) const
template<bool gatherCoeff, typename CoeffType >
void gatherVarInfo (Variable::Arg var, VariableInformation< gatherCoeff, CoeffType > &varinfo) const
template<bool gatherCoeff, typename CoeffType >
void gatherVarInfo (VariablesInformation< gatherCoeff, CoeffType > &varinfo) const
void gatherVariables (std::set< Variable > &variables) const
Term pow (unsigned exp) const
template<typename C = Coefficient, DisableIf< is_interval< C >> = dummy>
std::string toString (bool infix=true, bool friendlyVarNames=true) const
template<typename C = Coefficient, EnableIf< is_interval< C >> = dummy>
std::string toString (bool infix=true, bool friendlyVarNames=true) const
bool isConsistent () const
Term< Coefficient > operator- () const
In-place multiplication operators
Term & operator*= (const Coefficient &rhs)
Multiply this term with something and return the changed term.
Term & operator*= (Variable::Arg rhs)
Multiply this term with something and return the changed term.
Term & operator*= (const Monomial::Arg &rhs)
Multiply this term with something and return the changed term.
Term & operator*= (const Term &rhs)
Multiply this term with something and return the changed term.
Static Public Member Functions
static bool monomialEqual (const Term &lhs, const Term &rhs)
Checks if two terms have the same monomial.
static bool monomialEqual (std::shared_ptr< const Term > lhs, std::shared_ptr< const Term > rhs)
static bool monomialLess (const Term &lhs, const Term &rhs)
static bool monomialLess (std::shared_ptr< const Term > lhs, std::shared_ptr< const Term > rhs)
static Term gcd (std::shared_ptr< const Term > t1, std::shared_ptr< const Term > t2)
Calculates the gcd of (t1, t2).
static Term gcd (const Term &t1, const Term &t2)
Calculates the gcd of (t1, t2).
Private Attributes
Coefficient mCoeff = constant_zero<Coefficient>::get()
Monomial::Arg mMonomial
Friends
template<typename Coeff >
std::ostream & operator<< (std::ostream &os, const Term< Coeff > &rhs)
Streaming operator for Term.
Division operators
template<typename Coeff >
const Term< Coeff > operator/ (const Term< Coeff > &lhs, unsigned long rhs)
Perform a division involving a term.
Detailed Description
template<typename Coefficient>
class carl::Term< Coefficient >
Represents a single term, that is a numeric coefficient and a monomial.
Definition at line 25 of file Monomial.h.
Constructor & Destructor Documentation
template<typename Coefficient> carl::Term< Coefficient >::Term ()
Default constructor.
Constructs a term of value zero.
template<typename Coefficient> carl::Term< Coefficient >::Term (const Coefficient & c) explicit
Constructs a term of value .
Parameters
c Coefficient.
template<typename Coefficient> carl::Term< Coefficient >::Term (Variable::Arg v) explicit
Constructs a term of value .
Parameters
v Variable.
template<typename Coefficient> carl::Term< Coefficient >::Term (const Monomial::Arg & m) explicit
Constructs a term of value .
Parameters
m Monomial pointer.
template<typename Coefficient> carl::Term< Coefficient >::Term (const Coefficient & c, const Monomial::Arg & m)
Constructs a term of value .
Parameters
c Coefficient.
m Monomial pointer.
template<typename Coefficient> carl::Term< Coefficient >::Term (Coefficient && c, const Monomial::Arg & m)
Constructs a term of value .
Parameters
c Coefficient.
m Monomial pointer.
template<typename Coefficient> carl::Term< Coefficient >::Term (const Coefficient & c, Variable::Arg v, exponent e)
Constructs a term of value .
Parameters
c Coefficient.
v Variable.
e Exponent.
Member Function Documentation
template<typename Coefficient> Coefficient& carl::Term< Coefficient >::coeff () inline
Get the coefficient.
Returns
Coefficient.
Definition at line 95 of file Term.h.
Referenced by carl::ReductorEntry< Polynomial >::addCoefficient(), std::hash< carl::Term< Coefficient > >::operator()(), and carl::Monomial::substitute().
template<typename Coefficient> size_t carl::Term< Coefficient >::complexity () const inline
Returns
An approximation of the complexity of this monomial.
Definition at line 177 of file Term.h.
template<typename Coefficient> Term carl::Term< Coefficient >::divide (const Coefficient & c) const
Parameters
c a non-zero coefficient.
Returns
Referenced by carl::IdealDatastructureVector< Polynomial >::getDivisor().
template<typename Coefficient> static Term carl::Term< Coefficient >::gcd (std::shared_ptr< const Term< Coefficient > > t1, std::shared_ptr< const Term< Coefficient > > t2) static
Calculates the gcd of (t1, t2).
If t1 or t2 are not set, undefined. If t1 or t2 is zero, undefined.
Parameters
t1 first term
t2 second term
Returns
gcd(t1,t2);
template<typename Coefficient> static Term carl::Term< Coefficient >::gcd (const Term< Coefficient > & t1, const Term< Coefficient > & t2) static
Calculates the gcd of (t1, t2).
If t1 or t2 is zero, undefined.
Parameters
t1 first term
t2 second term
Returns
gcd(t1,t2)
template<typename Coefficient> size_t carl::Term< Coefficient >::getNrVariables () const inline
Returns
Definition at line 168 of file Term.h.
Referenced by carl::Term< Rational >::getSingleVariable().
template<typename Coefficient> Variable::Arg carl::Term< Coefficient >::getSingleVariable () const inline
For terms with exactly one variable, get this variable.
Returns
The only variable occuring in the term.
Definition at line 213 of file Term.h.
Referenced by carl::MultivariatePolynomial< Rational >::getSingleVariable().
template<typename Coefficient> bool carl::Term< Coefficient >::has (Variable::Arg v) const inline
Parameters
v The variable to check for its occurrence.
Returns
true, if the variable occurs in this term.
Definition at line 187 of file Term.h.
template<typename Coefficient> bool carl::Term< Coefficient >::hasNoOtherVariable (Variable::Arg v) const inline
Checks if the monomial is either a constant or the only variable occuring is the variable v.
Parameters
v The variable which may occur.
Returns
true if no variable occurs, or just v occurs.
Definition at line 198 of file Term.h.
template<typename Coefficient> bool carl::Term< Coefficient >::integerValued () const inline
Returns
true, if the image of this term is integer-valued.
Definition at line 149 of file Term.h.
template<typename Coefficient> bool carl::Term< Coefficient >::isConstant () const inline
Checks whether the monomial is a constant.
Returns
Definition at line 141 of file Term.h.
Referenced by carl::Term< Rational >::isOne(), and std::hash< carl::Term< Coefficient > >::operator()().
template<typename Coefficient> bool carl::Term< Coefficient >::isLinear () const inline
Checks whether the monomial has exactly the degree one.
Returns
Definition at line 159 of file Term.h.
template<typename Coefficient> bool carl::Term< Coefficient >::isOne () const inline
Checks whether the term equals one.
Returns
Definition at line 133 of file Term.h.
template<typename Coefficient> bool carl::Term< Coefficient >::isSquare () const inline
Checks if the term is a square.
Returns
If this is square.
Definition at line 223 of file Term.h.
template<typename Coefficient> bool carl::Term< Coefficient >::isZero () const inline
Checks whether the term is zero.
Returns
Definition at line 124 of file Term.h.
Referenced by carl::ReductorEntry< Polynomial >::empty(), carl::Reductor< InputPolynomial, PolynomialInIdeal, Datastructure, Configuration >::reduce(), carl::ReductorEntry< Polynomial >::ReductorEntry(), and carl::ReductorEntry< Polynomial >::removeLeadingTerm().
template<typename Coefficient> const Monomial::Arg& carl::Term< Coefficient >::monomial () const inline
Get the monomial.
Returns
Monomial.
Definition at line 106 of file Term.h.
Referenced by carl::ReductorEntry< Polynomial >::addCoefficient(), std::hash< carl::Term< Coefficient > >::operator()(), and carl::Monomial::substitute().
template<typename Coefficient> static bool carl::Term< Coefficient >::monomialEqual (const Term< Coefficient > & lhs, const Term< Coefficient > & rhs) inline static
Checks if two terms have the same monomial.
Parameters
lhs First term.
rhs Second term.
Returns
If both terms have the same monomial.
Definition at line 362 of file Term.h.
template<typename Coefficient> Term& carl::Term< Coefficient >::operator*= (const Coefficient & rhs)
Multiply this term with something and return the changed term.
Parameters
rhs Right hand side.
Returns
Changed term.
template<typename Coefficient> Term& carl::Term< Coefficient >::operator*= (Variable::Arg rhs)
Multiply this term with something and return the changed term.
Parameters
rhs Right hand side.
Returns
Changed term.
template<typename Coefficient> Term& carl::Term< Coefficient >::operator*= (const Monomial::Arg & rhs)
Multiply this term with something and return the changed term.
Parameters
rhs Right hand side.
Returns
Changed term.
template<typename Coefficient> Term& carl::Term< Coefficient >::operator*= (const Term< Coefficient > & rhs)
Multiply this term with something and return the changed term.
Parameters
rhs Right hand side.
Returns
Changed term.
template<typename Coefficient> bool carl::Term< Coefficient >::sqrt (Term< Coefficient > & res) const
Calculates the square root of this term.
Returns true, iff the term is a square as checked by isSquare(). In that case, res will changed to be the square root. Otherwise, res is undefined.
Parameters
res Square root of this term.
Returns
If square root could be calculated.
template<typename Coefficient> exponent carl::Term< Coefficient >::tdeg () const inline
Gives the total degree, i.e.
the sum of all exponents.
Returns
Total degree.
Definition at line 114 of file Term.h.
Friends And Related Function Documentation
template<typename Coefficient> template<typename Coeff > const Term<Coeff> operator/ (const Term< Coeff > & lhs, unsigned long rhs) friend
Perform a division involving a term.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
template<typename Coefficient> template<typename Coeff > std::ostream& operator<< (std::ostream & os, const Term< Coeff > & rhs) friend
Streaming operator for Term.
Parameters
os Output stream.
rhs Term.
Returns
os
The documentation for this class was generated from the following files:
carl/core/Monomial.h
carl/core/Term.h