carl: carl::MultivariatePolynomial< Coeff, Ordering, Policies > Class Template Reference
carl::MultivariatePolynomial< Coeff, Ordering, Policies > Class Template Reference
Polynomials » Multivariate Represented Polynomials
The general-purpose multivariate polynomial class.
#include <MultivariatePolynomial.h>
Public Types
enum ConstructorOperation : unsigned { ADD, SUB, MUL, DIV }
typedef Ordering OrderedBy
The ordering of the terms.
typedef Term< Coeff > TermType
Type of the terms.
typedef Monomial MonomType
Type of the monomials within the terms.
typedef Coeff CoeffType
Type of the coefficients.
typedef Policies Policy
Policies for this monomial.
typedef UnderlyingNumberType
< Coeff >::type NumberType
Number type within the coefficients.
typedef IntegralType
< NumberType >::type IntNumberType
Integer type associated with the number type.
typedef MultivariatePolynomial
< Coeff, Ordering, Policies > PolyType
typedef std::vector< int > CACHE
The type of the cache. Multivariate polynomials do not need a cache, we set it to something.
typedef std::vector< Term
< Coeff > > TermsType
Type our terms vector.f.
Public Member Functions
virtual bool isUnivariateRepresented () const override
virtual bool isMultivariateRepresented () const override
bool isOrdered () const
Check if the terms are ordered.
void makeOrdered () const
Ensure that the terms are ordered.
const Monomial::Arg & lmon () const
The leading monomial.
const Term< Coeff > & lterm () const
The leading term.
Term< Coeff > & lterm ()
const Coeff & lcoeff () const
Returns the coefficient of the leading term.
MultivariatePolynomial lcoeff (Variable::Arg var) const
Returns the leading coefficient with respect to the given variable.
std::size_t totalDegree () const
Calculates the max.
std::size_t degree (Variable::Arg var) const
Calculates the degree of this polynomial with respect to the given variable.
MultivariatePolynomial coeff (Variable::Arg var, std::size_t exp) const
Calculates the coefficient of var^exp.
bool isZero () const
Checks if the polynomial is zero.
bool isOne () const
bool isConstant () const
Checks if the polynomial is constant.
bool isLinear () const
Checks if the polynomial is linear.
bool isNumber () const
Checks if the polynomial is a number.
Definiteness definiteness () const
Retrieves information about the definiteness of the polynomial.
std::vector< std::pair< Coeff,
MultivariatePolynomial< Coeff,
Ordering, Policies > > > sosDecomposition (bool _notTrivial=false) const
size_t nrTerms () const
Calculates the number of terms.
size_t size () const
size_t complexity () const
const Term< Coeff > & trailingTerm () const
Gives the last term according to Ordering.
Term< Coeff > & trailingTerm ()
bool hasConstantTerm () const
Checks if the polynomial has a constant term that is not zero.
bool integerValued () const
const Coeff & constantPart () const
Retrieves the constant term of this polynomial or zero, if there is no constant term.
TermsType::const_iterator begin () const
TermsType::const_iterator end () const
TermsType::const_reverse_iterator rbegin () const
TermsType::const_reverse_iterator rend () const
TermsType::iterator eraseTerm (typename TermsType::iterator pos)
TermsType & getTerms ()
MultivariatePolynomial tail (bool fullOrdered=false) const
For the polynomial p, the function calculates a polynomial p - lt(p).
MultivariatePolynomial & stripLT ()
Drops the leading term.
Variable::Arg getSingleVariable () const
For terms with exactly one variable, get this variable.
const CoeffType & coefficient () const
const PolyType & polynomial () const
bool isUnivariate () const
Checks whether only one variable occurs.
bool isTsos () const
Checks whether the polynomial is a trivial sum of squares.
void gatherVariables (std::set< Variable > &vars) const
Iterates through all terms to find variables occuring in this polynomial.
std::set< Variable > gatherVariables () const
bool has (Variable::Arg v) const
bool isReducibleIdentity () const
void subtractProduct (const Term< Coeff > &factor, const MultivariatePolynomial &p)
Subtract a term times a polynomial from this polynomial.
void addTerm (const Term< Coeff > &term)
Adds a single term without using a TermAdditionManager or changing the ordering status.
template<typename C = Coeff, EnableIf< is_field< C >> = dummy>
MultivariatePolynomial divideBy (const Coeff &divisor) const
Divides the polynomial by the given coefficient.
template<typename C = Coeff, EnableIf< is_field< C >> = dummy>
bool divideBy (const MultivariatePolynomial &divisor, MultivariatePolynomial &quotient) const
Divides the polynomial by another polynomial.
DivisionResult
< MultivariatePolynomial > divideBy (const MultivariatePolynomial &divisor) const
Calculating the quotient and the remainder, such that for a given polynomial p we have p = divisor * quotient + remainder.
MultivariatePolynomial quotient (const MultivariatePolynomial &divisor) const
Calculates the quotient.
MultivariatePolynomial remainder (const MultivariatePolynomial &divisor) const
Calculates the remainder.
MultivariatePolynomial prem (const MultivariatePolynomial &divisor, Variable::Arg var) const
MultivariatePolynomial derivative (Variable::Arg v, unsigned nth=1) const
bool sqrt (MultivariatePolynomial &res) const
Calculates the square of this multivariate polynomial if it is a square.
template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy>
Coeff coprimeFactor () const
template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy>
Coeff coprimeFactorWithoutConstant () const
MultivariatePolynomial coprimeCoefficients () const
MultivariatePolynomial normalize () const
For a polynomial p, returns p/lc(p)
void substituteIn (Variable::Arg var, const MultivariatePolynomial &value)
Replace the given variable by the given polynomial within this multivariate polynomial.
MultivariatePolynomial substitute (Variable::Arg var, const MultivariatePolynomial &value) const
Replace the given variable by the given value.
MultivariatePolynomial substitute (const std::map< Variable, MultivariatePolynomial > &substitutions) const
Replace all variables by a value given in their map.
template<typename SubstitutionType = Coeff>
MultivariatePolynomial substitute (const std::map< Variable, SubstitutionType > &substitutions) const
Replace all variables by a value given in their map.
MultivariatePolynomial substitute (const std::map< Variable, Term< Coeff >> &substitutions) const
Replace all variables by a Term in which the variable does not occur.
template<typename SubstitutionType = Coeff>
Coeff evaluate (const std::map< Variable, SubstitutionType > &substitutions) const
Like substitute, but expects substitutions for all variables.
bool divides (const MultivariatePolynomial &b) const
void square ()
MultivariatePolynomial pow (std::size_t exp) const
MultivariatePolynomial naive_pow (unsigned exp) const
std::string toString (bool infix=true, bool friendlyVarNames=true) const
MultivariatePolynomial
< typename IntegralType< Coeff >
::type, Ordering, Policies > toIntegerDomain () const
UnivariatePolynomial< Coeff > toUnivariatePolynomial () const
UnivariatePolynomial
< MultivariatePolynomial > toUnivariatePolynomial (Variable::Arg mainVar) const
const Term< Coeff > & operator[] (unsigned) const
MultivariatePolynomial mod (const typename IntegralType< Coeff >::type &modulo) const
template<bool gatherCoeff>
VariableInformation
< gatherCoeff,
MultivariatePolynomial > getVarInfo (Variable::Arg v) const
template<bool gatherCoeff>
VariablesInformation
< gatherCoeff,
MultivariatePolynomial > getVarInfo () const
template<typename C = Coeff, EnableIf< is_number< C >> = dummy>
Coeff numericContent () const
template<typename C = Coeff, DisableIf< is_number< C >> = dummy>
UnderlyingNumberType< C >::type numericContent () const
template<typename C = Coeff, EnableIf< is_number< C >> = dummy>
IntNumberType mainDenom () const
MultivariatePolynomial operator- () const
template<bool findConstantTerm = true, bool findLeadingTerm = true>
void makeMinimallyOrdered () const
Make sure that the terms are at least minimally ordered.
bool isConsistent () const
Asserts that this polynomial complies with the requirements and assumptions for MultivariatePolynomial objects.
Constructors
MultivariatePolynomial ()
MultivariatePolynomial (const MultivariatePolynomial< Coeff, Ordering, Policies > &)
MultivariatePolynomial (MultivariatePolynomial< Coeff, Ordering, Policies > &&)
MultivariatePolynomial & operator= (const MultivariatePolynomial &p)
MultivariatePolynomial & operator= (MultivariatePolynomial &&p)
MultivariatePolynomial (int c)
MultivariatePolynomial (unsigned c)
MultivariatePolynomial (const Coeff &c)
MultivariatePolynomial (Variable::Arg v)
MultivariatePolynomial (const Term< Coeff > &t)
MultivariatePolynomial (const std::shared_ptr< const Monomial > &m)
MultivariatePolynomial (const UnivariatePolynomial< MultivariatePolynomial< Coeff, Ordering, Policy >> &pol)
MultivariatePolynomial (const UnivariatePolynomial< Coeff > &pol)
template<class OtherPolicies , DisableIf< std::is_same< Policies, OtherPolicies >> = dummy>
MultivariatePolynomial (const MultivariatePolynomial< Coeff, Ordering, OtherPolicies > &)
MultivariatePolynomial (TermsType &&terms, bool duplicates=true, bool ordered=false)
MultivariatePolynomial (const TermsType &terms, bool duplicates=true, bool ordered=false)
MultivariatePolynomial (const std::initializer_list< Term< Coeff >> &terms)
MultivariatePolynomial (const std::initializer_list< Variable > &terms)
MultivariatePolynomial (const std::pair< ConstructorOperation, std::vector< MultivariatePolynomial >> &p)
MultivariatePolynomial (ConstructorOperation op, const std::vector< MultivariatePolynomial > &operands)
In-place addition operators
MultivariatePolynomial & operator+= (const MultivariatePolynomial &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const TermType &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const std::shared_ptr< const TermType > &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const Monomial::Arg &rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (Variable::Arg rhs)
Add something to this polynomial and return the changed polynomial.
MultivariatePolynomial & operator+= (const Coeff &rhs)
Add something to this polynomial and return the changed polynomial.
In-place subtraction operators
MultivariatePolynomial & operator-= (const MultivariatePolynomial &rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (const Term< Coeff > &rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (const Monomial::Arg &rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (Variable::Arg rhs)
Subtract something from this polynomial and return the changed polynomial.
MultivariatePolynomial & operator-= (const Coeff &rhs)
Subtract something from this polynomial and return the changed polynomial.
In-place multiplication operators
MultivariatePolynomial & operator*= (const MultivariatePolynomial &rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (const Term< Coeff > &rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (const Monomial::Arg &rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
MultivariatePolynomial & operator*= (const Coeff &rhs)
Multiply this polynomial with something and return the changed polynomial.
In-place division operators
MultivariatePolynomial & operator/= (const MultivariatePolynomial &rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (const Term< Coeff > &rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (const Monomial::Arg &rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (Variable::Arg rhs)
Divide this polynomial by something and return the changed polynomial.
MultivariatePolynomial & operator/= (const Coeff &rhs)
Divide this polynomial by something and return the changed polynomial.
Static Public Member Functions
static MultivariatePolynomial SPolynomial (const MultivariatePolynomial &p, const MultivariatePolynomial &q)
Calculates the S-Polynomial.
static bool compareByLeadingTerm (const MultivariatePolynomial &p1, const MultivariatePolynomial &p2)
static bool compareByNrTerms (const MultivariatePolynomial &p1, const MultivariatePolynomial &p2)
Static Public Attributes
static TermAdditionManager
< MultivariatePolynomial,
Ordering > mTermAdditionManager
Protected Types
template<bool gatherCoeff>
using VarInfo = VariableInformation< gatherCoeff, MultivariatePolynomial >
Protected Attributes
TermsType mTerms
A vector of all terms.
bool mOrdered
Flag that indicates if the terms are ordered.
Private Member Functions
void makeMinimallyOrdered (typename TermsType::iterator &lterm, typename TermsType::iterator &cterm) const
Make sure that the terms are at least minimally ordered.
Friends
template<typename Polynomial , typename Order >
class TermAdditionManager
std::ostream & operator<< (std::ostream &os, ConstructorOperation op)
template<typename C , typename O , typename P >
std::ostream & operator<< (std::ostream &os, const MultivariatePolynomial< C, O, P > &rhs)
Streaming operator for multivariate polynomials.
template<typename C , typename O , typename P >
bool operator== (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Checks if the two arguments are equal.
Division operators
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator/ (const MultivariatePolynomial< C, O, P > &lhs, const MultivariatePolynomial< C, O, P > &rhs)
Perform a division involving a polynomial.
template<typename C , typename O , typename P >
MultivariatePolynomial< C, O, P > operator/ (const MultivariatePolynomial< C, O, P > &lhs, unsigned long rhs)
Perform a division involving a polynomial.
Detailed Description
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>>
class carl::MultivariatePolynomial< Coeff, Ordering, Policies >
The general-purpose multivariate polynomial class.
It is represented as a sum of terms, being a coefficient and a monomial.
A polynomial is always minimally ordered. By that, we mean that the leading term and the constant term (if there is any) are at the correct positions. For some operations, the terms may be fully ordered. isOrdered() checks if the polynomial is fully ordered while makeOrdered() makes the polynomial fully ordered.
Definition at line 15 of file MultivariateFactor.h.
Member Function Documentation
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::addTerm (const Term< Coeff > & term)
Adds a single term without using a TermAdditionManager or changing the ordering status.
Parameters
term Term.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coeff (Variable::Arg var, std::size_t exp) const inline
Calculates the coefficient of var^exp.
Parameters
var Variable.
exp Exponent.
Returns
Coefficient of var^exp.
Definition at line 205 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::lcoeff().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const CoeffType& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coefficient () const inline
Returns
Coefficient of the polynomial (this makes only sense for polynomials storing the gcd of all coefficients separately)
Definition at line 378 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::complexity () const inline
Returns
An approximation of the complexity of this polynomial.
Definition at line 284 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Coeff& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::constantPart () const
Retrieves the constant term of this polynomial or zero, if there is no constant term.
Returns
Constant term.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimeCoefficients () const
Returns
p * p.coprimeFactor()
See also
coprimeFactor()
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy> Coeff carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimeFactor () const
Returns
The lcm of the denominators of the coefficients in p divided by the gcd of numerators of the coefficients in p.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_subset_of_rationals< C >> = dummy> Coeff carl::MultivariatePolynomial< Coeff, Ordering, Policies >::coprimeFactorWithoutConstant () const
Returns
The lcm of the denominators of the coefficients (without the constant one) in p divided by the gcd of numerators of the coefficients in p.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> Definiteness carl::MultivariatePolynomial< Coeff, Ordering, Policies >::definiteness () const
Retrieves information about the definiteness of the polynomial.
Returns
Definiteness of this.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::degree (Variable::Arg var) const inline
Calculates the degree of this polynomial with respect to the given variable.
Parameters
var Variable.
Returns
Degree w.r.t. var.
Definition at line 189 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::lcoeff().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_field< C >> = dummy> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divideBy (const Coeff & divisor) const
Divides the polynomial by the given coefficient.
Applies if the coefficients are from a field.
Parameters
divisor
Returns
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C = Coeff, EnableIf< is_field< C >> = dummy> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divideBy (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor, MultivariatePolynomial< Coeff, Ordering, Policies > & quotient) const
Divides the polynomial by another polynomial.
If the divisor divides this polynomial, quotient contains the result of the division and true is returned. Otherwise, false is returned and the content of quotient remains unchanged. Applies if the coefficients are from a field. Note that the quotient must not be *this.
Parameters
divisor
quotient
Returns
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> DivisionResult<MultivariatePolynomial> carl::MultivariatePolynomial< Coeff, Ordering, Policies >::divideBy (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor) const
Calculating the quotient and the remainder, such that for a given polynomial p we have p = divisor * quotient + remainder.
Parameters
divisor Another polynomial
Returns
A divisionresult, holding the quotient and the remainder.
See also
Note
Division is only defined on fields
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> TermsType::iterator carl::MultivariatePolynomial< Coeff, Ordering, Policies >::eraseTerm (typename TermsType::iterator pos) inline
Todo:
find new lterm or constant term
Definition at line 335 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename SubstitutionType = Coeff> Coeff carl::MultivariatePolynomial< Coeff, Ordering, Policies >::evaluate (const std::map< Variable, SubstitutionType > & substitutions) const
Like substitute, but expects substitutions for all variables.
Returns
For a polynomial p, the function value p(x_1,...,x_n).
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::gatherVariables (std::set< Variable > & vars) const
Iterates through all terms to find variables occuring in this polynomial.
Parameters
vars Holds the variables occuring in the polynomial at return.
Referenced by carl::cad::Constraint< carl::Number >::checkVariables(), carl::MultivariateGCD< GCDCalculation, Coeff, Ordering, Policies >::getMainVar(), and carl::EZGCD< Coeff, Ordering, Policies >::getMainVar().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> Variable::Arg carl::MultivariatePolynomial< Coeff, Ordering, Policies >::getSingleVariable () const inline
For terms with exactly one variable, get this variable.
Returns
The only variable occuring in the term.
Definition at line 369 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::has (Variable::Arg v) const
Parameters
v The variable to check for its occurrence.
Returns
true, if the variable occurs in this term.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::hasConstantTerm () const
Checks if the polynomial has a constant term that is not zero.
Returns
If there is a constant term unequal to zero.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::integerValued () const
Returns
true, if the image of this polynomial is integer-valued.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isConsistent () const
Asserts that this polynomial complies with the requirements and assumptions for MultivariatePolynomial objects.
All terms are actually valid and not nullptr or alike
Only the trailing term may be constant.
Referenced by carl::cad::Constraint< carl::Number >::Constraint(), carl::MultivariatePolynomial< Rational >::makeOrdered(), and std::hash< carl::MultivariatePolynomial< C, O, P > >::operator()().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isConstant () const
Checks if the polynomial is constant.
Returns
If this is constant.
Referenced by carl::MultivariatePolynomial< Rational >::getSingleVariable(), and carl::MultivariatePolynomial< Rational >::isNumber().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isLinear () const
Checks if the polynomial is linear.
Returns
If this is linear.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> virtual bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isMultivariateRepresented () const inline override virtual
See also
class Polynomial
Returns
Implements carl::Polynomial.
Definition at line 129 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isNumber () const inline
Checks if the polynomial is a number.
This is basically the same as being a constant.
Returns
If this is a number.
Definition at line 245 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isOne () const
Returns
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isOrdered () const inline
Check if the terms are ordered.
Returns
If terms are ordered.
Definition at line 138 of file MultivariatePolynomial.h.
Referenced by carl::MultivariatePolynomial< Rational >::makeOrdered().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isTsos () const
Checks whether the polynomial is a trivial sum of squares.
Returns
true if polynomial is of the form \sum a_im_i^2 with a_i > 0 for all i.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isUnivariate () const
Checks whether only one variable occurs.
Returns
Notice that it might be better to use the variable information if several pieces of information are requested.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> virtual bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isUnivariateRepresented () const inline override virtual
See also
class Polynomial
Returns
Implements carl::Polynomial.
Definition at line 121 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::isZero () const
Checks if the polynomial is zero.
Returns
If this is zero.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Coeff& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lcoeff () const
Returns the coefficient of the leading term.
Notice that this is not defined for zero polynomials.
Returns
Leading coefficient.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lcoeff (Variable::Arg var) const inline
Returns the leading coefficient with respect to the given variable.
Parameters
var Variable.
Returns
Leading coefficient.
Definition at line 173 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Monomial::Arg& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lmon () const
The leading monomial.
Returns
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::lterm () const
The leading term.
Returns
Referenced by carl::MultivariatePolynomial< Rational >::getSingleVariable().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::makeMinimallyOrdered (typename TermsType::iterator & lterm, typename TermsType::iterator & cterm) const private
Make sure that the terms are at least minimally ordered.
Iterators to the important terms are given as arguments, so that we don't need to scan the whole vector.
Parameters
lterm Iterator to leading term.
cterm Iterator to constant term.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::normalize () const
For a polynomial p, returns p/lc(p)
Returns
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::nrTerms () const inline
Calculates the number of terms.
Returns
the number of terms
Definition at line 267 of file MultivariatePolynomial.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const Term< Coeff > & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const Monomial::Arg & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator*= (const Coeff & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const TermType & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const std::shared_ptr< const TermType > & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const Monomial::Arg & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (Variable::Arg rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator+= (const Coeff & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const Term< Coeff > & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const Monomial::Arg & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (Variable::Arg rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator-= (const Coeff & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const MultivariatePolynomial< Coeff, Ordering, Policies > & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const Term< Coeff > & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const Monomial::Arg & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (Variable::Arg rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::operator/= (const Coeff & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const PolyType& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::polynomial () const inline
Returns
The coprimeCoefficients of this polyomial, if this is stored internally, otherwise this polynomial.
Definition at line 386 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::quotient (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor) const
Calculates the quotient.
Parameters
divisor
Returns
See also
MultivariatePolynomial::divideBy
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::remainder (const MultivariatePolynomial< Coeff, Ordering, Policies > & divisor) const
Calculates the remainder.
Parameters
divisor
Returns
See also
MultivariatePolynomial::divideBy
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::size () const inline
Returns
A rough estimation of the size of this polynomial being the number of its terms. (Note, that this method is required, as it is provided of other polynomials not necessarily being straightforward.)
Definition at line 276 of file MultivariatePolynomial.h.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::vector<std::pair<Coeff,MultivariatePolynomial<Coeff,Ordering,Policies> > > carl::MultivariatePolynomial< Coeff, Ordering, Policies >::sosDecomposition (bool _notTrivial = false) const
Parameters
_notTrivial If this flag is true, this polynomial is not yet in form of a sos (the method than avoids checking this).
Returns
The sum-of-squares (sos) decomposition ((q1,p1), .., (qn,pn)) with this = q1*p1^2+..+qn*pn^2, qi being positive rational numbers and pi being polynomials. If the result is empty, no sos could be found (which does not mean, that there exists no one).
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> static MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::SPolynomial (const MultivariatePolynomial< Coeff, Ordering, Policies > & p, const MultivariatePolynomial< Coeff, Ordering, Policies > & q) static
Calculates the S-Polynomial.
Parameters
p
q
Returns
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> bool carl::MultivariatePolynomial< Coeff, Ordering, Policies >::sqrt (MultivariatePolynomial< Coeff, Ordering, Policies > & res) const
Calculates the square of this multivariate polynomial if it is a square.
Parameters
res Used to store the result in.
Returns
true, if this multivariate polynomial is a square; false, otherwise.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::stripLT ()
Drops the leading term.
The function assumes the polynomial to be nonzero, otherwise the leading term is not defined.
Returns
A reference to this.
Todo:
find new lterm
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (Variable::Arg var, const MultivariatePolynomial< Coeff, Ordering, Policies > & value) const
Replace the given variable by the given value.
Returns
A new polynomial without resulting from this substitution.
Referenced by carl::UnivariatePolynomial< Coeff >::replaceVariable(), and carl::DiophantineEquations< Integer >::solveMultivariateDiophantine().
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (const std::map< Variable, MultivariatePolynomial< Coeff, Ordering, Policies > > & substitutions) const
Replace all variables by a value given in their map.
Returns
A new polynomial without the variables in map.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename SubstitutionType = Coeff> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (const std::map< Variable, SubstitutionType > & substitutions) const
Replace all variables by a value given in their map.
Returns
A new polynomial without the variables in map.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substitute (const std::map< Variable, Term< Coeff >> & substitutions) const
Replace all variables by a Term in which the variable does not occur.
Parameters
substitutions
Returns
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::substituteIn (Variable::Arg var, const MultivariatePolynomial< Coeff, Ordering, Policies > & value)
Replace the given variable by the given polynomial within this multivariate polynomial.
Todo:
find new lterm
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> void carl::MultivariatePolynomial< Coeff, Ordering, Policies >::subtractProduct (const Term< Coeff > & factor, const MultivariatePolynomial< Coeff, Ordering, Policies > & p)
Subtract a term times a polynomial from this polynomial.
Parameters
factor Term.
p Polynomial.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> MultivariatePolynomial carl::MultivariatePolynomial< Coeff, Ordering, Policies >::tail (bool fullOrdered = false) const
For the polynomial p, the function calculates a polynomial p - lt(p).
The function assumes the polynomial to be nonzero, otherwise, lt(p) is not defined.
Returns
A new polynomial p - lt(p).
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> std::size_t carl::MultivariatePolynomial< Coeff, Ordering, Policies >::totalDegree () const
Calculates the max.
degree over all monomials occurring in the polynomial. As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[2], page 48
Returns
Total degree.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> const Term<Coeff>& carl::MultivariatePolynomial< Coeff, Ordering, Policies >::trailingTerm () const
Gives the last term according to Ordering.
Notice that if there is a constant part, it is always trailing.
Returns
Friends And Related Function Documentation
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> operator/ (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) friend
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > MultivariatePolynomial<C,O,P> operator/ (const MultivariatePolynomial< C, O, P > & lhs, unsigned long rhs) friend
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > std::ostream& operator<< (std::ostream & os, const MultivariatePolynomial< C, O, P > & rhs) friend
Streaming operator for multivariate polynomials.
Parameters
os Output stream.
rhs Polynomial.
Returns
os.
template<typename Coeff, typename Ordering = GrLexOrdering, typename Policies = StdMultivariatePolynomialPolicies<>> template<typename C , typename O , typename P > bool operator== (const MultivariatePolynomial< C, O, P > & lhs, const MultivariatePolynomial< C, O, P > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
The documentation for this class was generated from the following files:
carl/core/MultivariateFactor.h
carl/core/MultivariatePolynomial.h