carl: carl::UnivariatePolynomial< Coefficient > Class Template Reference
carl::UnivariatePolynomial< Coefficient > Class Template Reference
Polynomials » Univariate Represented Polynomials
This class represents a univariate polynomial with coefficients of an arbitrary type.
#include <UnivariatePolynomial.h>
Public Types
typedef UnderlyingNumberType
< Coefficient >::type NumberType
The number type that is ultimately used for the coefficients.
typedef IntegralType
< NumberType >::type IntNumberType
The integral type that belongs to the number type.
Public Member Functions
UnivariatePolynomial ()=delete
Default constructor shall not exist.
UnivariatePolynomial (const UnivariatePolynomial &p)
Copy constructor.
UnivariatePolynomial (UnivariatePolynomial &&p)
Move constructor.
UnivariatePolynomial & operator= (const UnivariatePolynomial &p)
Copy assignment operator.
UnivariatePolynomial & operator= (UnivariatePolynomial &&p)
Move assignment operator.
UnivariatePolynomial (Variable::Arg mainVar)
Construct a zero polynomial with the given main variable.
UnivariatePolynomial (Variable::Arg mainVar, const Coefficient &coeff, std::size_t degree=0)
Construct .
UnivariatePolynomial (Variable::Arg mainVar, std::initializer_list< Coefficient > coefficients)
Construct polynomial with the given coefficients.
template<typename C = Coefficient, DisableIf< std::is_same< C, typename UnderlyingNumberType< C >::type >> = dummy>
UnivariatePolynomial (Variable::Arg mainVar, std::initializer_list< typename UnderlyingNumberType< C >::type > coefficients)
Construct polynomial with the given coefficients from the underlying number type of the coefficient type.
UnivariatePolynomial (Variable::Arg mainVar, const std::vector< Coefficient > &coefficients)
Construct polynomial with the given coefficients.
UnivariatePolynomial (Variable::Arg mainVar, std::vector< Coefficient > &&coefficients)
Construct polynomial with the given coefficients, moving the coefficients.
UnivariatePolynomial (Variable::Arg mainVar, const std::map< unsigned, Coefficient > &coefficients)
Construct polynomial with the given coefficients.
virtual ~UnivariatePolynomial ()
Destructor.
virtual bool isUnivariateRepresented () const override
Checks if the polynomial is represented univariately.
virtual bool isMultivariateRepresented () const override
Checks if the polynomial is represented multivariately.
bool isZero () const
Checks if the polynomial is equal to zero.
bool isOne () const
Checks if the polynomial is equal to one.
template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial one () const
Creates a polynomial of value one with the same main variable.
template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial one () const
Creates a polynomial of value one with the same main variable.
const Coefficient & lcoeff () const
Returns the leading coefficient.
const Coefficient & tcoeff () const
Returns the trailing coefficient.
bool isConstant () const
Checks whether the polynomial is constant with respect to the main variable.
bool isLinearInMainVar () const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool isNumber () const
Checks whether the polynomial is only a number.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool isNumber () const
Checks whether the polynomial is only a number.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
NumberType constantPart () const
Returns the constant part of this polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
NumberType constantPart () const
Returns the constant part of this polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool isUnivariate () const
Checks if the polynomial is univariate, that means if only one variable occurs.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool isUnivariate () const
Checks if the polynomial is univariate, that means if only one variable occurs.
unsigned degree () const
Get the maximal exponent of the main variable.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
unsigned totalDegree () const
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
unsigned totalDegree () const
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
void truncate ()
Removes the leading term from the polynomial.
const std::vector< Coefficient > & coefficients () const
Retrieves the coefficients defining this polynomial.
Variable::Arg mainVar () const
Retrieves the main variable of this polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial
< MultivariatePolynomial
< NumberType > > switchVariable (Variable::Arg newVar) const
Switches the main variable using a purely syntactical restructuring.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial switchVariable (Variable::Arg newVar) const
Switches the main variable using a purely syntactical restructuring.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial replaceVariable (Variable::Arg newVar) const
Replaces the main variable.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial replaceVariable (Variable::Arg newVar) const
Replaces the main variable.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
std::set< Variable > gatherVariables () const
Gathers all variables that occur in the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
std::set< Variable > gatherVariables () const
Gathers all variables that occur in the polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
unsigned has (Variable::Arg v) const
Checks if the given variable occurs in the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
unsigned has (Variable::Arg v) const
Checks if the given variable occurs in the polynomial.
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
Coefficient coprimeFactor () const
Calculates a factor that would make the coefficients of this polynomial coprime integers.
template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy>
UnderlyingNumberType
< Coefficient >::type coprimeFactor () const
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
UnivariatePolynomial< typename
IntegralType< Coefficient >
::type > coprimeCoefficients () const
Constructs a new polynomial that is scaled such that the coefficients are coprime.
template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy>
UnivariatePolynomial< Coefficient > coprimeCoefficients () const
bool isNormal () const
Checks whether the polynomial is unit normal.
UnivariatePolynomial normalized () const
The normal part of a polynomial is the polynomial divided by the unit part.
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
const Coefficient & unitPart () const
The unit part of a polynomial over a field is its leading coefficient for nonzero polynomials, and one for zero polynomials.
template<typename C = Coefficient, EnableIf< Not< is_number< C >> > = dummy>
Coefficient unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
template<typename C = Coefficient, EnableIf< Not< is_field< C >>, is_number< C >> = dummy>
Coefficient unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
Coefficient content () const
The content of a polynomial is the gcd of the coefficients of the normal part of a polynomial.
UnivariatePolynomial primitivePart () const
The primitive part of p is the normal part of p divided by the content of p.
UnivariatePolynomial derivative (unsigned nth=1) const
The n'th derivative of the polynomial in its main variable.
UnivariatePolynomial remainder (const UnivariatePolynomial &divisor, const Coefficient &prefactor) const
UnivariatePolynomial remainder (const UnivariatePolynomial &divisor) const
UnivariatePolynomial prem_old (const UnivariatePolynomial &divisor) const
Calculates the pseudo-remainder.
UnivariatePolynomial prem (const UnivariatePolynomial &divisor) const
UnivariatePolynomial sprem (const UnivariatePolynomial &divisor) const
UnivariatePolynomial negateVariable () const
Constructs a new polynomial q such that where p is this polynomial.
template<typename C = Coefficient, EnableIf< is_integer< C >> = dummy>
DivisionResult
< UnivariatePolynomial > divideBy (const UnivariatePolynomial &divisor) const
Divides the polynomial by another polynomial.
template<typename C = Coefficient, DisableIf< is_integer< C >> = dummy, EnableIf< is_field< C >> = dummy>
DivisionResult
< UnivariatePolynomial > divideBy (const UnivariatePolynomial &divisor) const
Divides the polynomial by another polynomial.
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
DivisionResult
< UnivariatePolynomial > divideBy (const Coefficient &divisor) const
Divides the polynomial by a coefficient.
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy>
bool divideBy (const Coefficient &divisor, UnivariatePolynomial &quotient) const
Divides the polynomial by a coefficient.
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy, EnableIf< is_field< typename UnderlyingNumberType< C >::type >> = dummy>
DivisionResult
< UnivariatePolynomial > divideBy (const NumberType &divisor) const
Divides the polynomial by a number.
bool divides (const UnivariatePolynomial &divisor) const
Checks if this polynomial is divisible by the given divisor, that is if the remainder is zero.
UnivariatePolynomial & mod (const Coefficient &modulus)
Replaces every coefficient c by c mod modulus.
UnivariatePolynomial mod (const Coefficient &modulus) const
Constructs a new polynomial where every coefficient c is replaced by c mod modulus.
UnivariatePolynomial pow (std::size_t exp) const
Returns this polynomial to the given power.
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
UnivariatePolynomial squareFreePart () const
template<typename C = Coefficient, DisableIf< is_subset_of_rationals< C >> = dummy>
UnivariatePolynomial squareFreePart () const
Coefficient evaluate (const Coefficient &value) const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
void substituteIn (Variable::Arg var, const Coefficient &value)
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
void substituteIn (Variable::Arg var, const Coefficient &value)
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial substitute (Variable::Arg var, const Coefficient &value) const
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial substitute (Variable::Arg var, const Coefficient &value) const
carl::Sign sgn (const Coefficient &value) const
Calculates the sign of the polynomial at some point.
bool isRoot (const Coefficient &value) const
template<typename SubstitutionType , typename C = Coefficient, EnableIf< is_instantiation_of< MultivariatePolynomial, C >> = dummy>
UnivariatePolynomial< Coefficient > evaluateCoefficient (const std::map< Variable, SubstitutionType > &) const
template<typename SubstitutionType , typename C = Coefficient, DisableIf< is_instantiation_of< MultivariatePolynomial, C >> = dummy>
UnivariatePolynomial< Coefficient > evaluateCoefficient (const std::map< Variable, SubstitutionType > &) const
template<typename T = Coefficient, EnableIf< has_normalize< T >> = dummy>
UnivariatePolynomial & normalizeCoefficients ()
template<typename T = Coefficient, DisableIf< has_normalize< T >> = dummy>
UnivariatePolynomial & normalizeCoefficients ()
template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial< typename
IntegralType< Coefficient >
::type > toIntegerDomain () const
Works only from rationals, if the numbers are already integers.
template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy>
UnivariatePolynomial< typename
IntegralType< Coefficient >
::type > toIntegerDomain () const
UnivariatePolynomial< GFNumber
< typename IntegralType
< Coefficient >::type > > toFiniteDomain (const GaloisField< typename IntegralType< Coefficient >::type > *galoisField) const
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial< NumberType > toNumberCoefficients (bool check=true) const
template<typename NewCoeff >
UnivariatePolynomial< NewCoeff > convert () const
template<typename NewCoeff >
UnivariatePolynomial< NewCoeff > convert (const std::function< NewCoeff(const Coefficient &)> &f) const
Coefficient cauchyBound () const
Notice, Cauchy bounds are only defined for polynomials over fields.
Coefficient modifiedCauchyBound () const
template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy>
IntNumberType maximumNorm () const
The maximum norm of a polynomial is the maximum absolute value of the coefficients of the corresponding integral polynomial (as calculated by coprimeCoefficients()).
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
NumberType numericContent (unsigned int i) const
Returns the numeric content part of the i'th coefficient.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
NumberType numericContent (unsigned int i) const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
NumberType numericUnit () const
Returns the numeric unit part of the polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
NumberType numericUnit () const
template<typename N = NumberType, EnableIf< is_subset_of_rationals< N >> = dummy>
UnderlyingNumberType
< Coefficient >::type numericContent () const
Obtains the numeric content part of this polynomial.
UnivariatePolynomial pseudoPrimpart () const
Returns this/divisor where divisor is the numeric content of this polynomial.
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
IntNumberType mainDenom () const
Compute the main denominator of all numeric coefficients of this polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
IntNumberType mainDenom () const
std::map< UnivariatePolynomial,
unsigned > factorization () const
Coefficient syntheticDivision (const Coefficient &_zeroOfDivisor)
std::map< unsigned,
UnivariatePolynomial > squareFreeFactorization () const
bool zeroIsRoot () const
Checks if zero is a real root of this polynomial.
void eliminateZeroRoots ()
Reduces the polynomial such that zero is not a root anymore.
void eliminateRoot (const Coefficient &root)
Reduces the polynomial such that the given root is not a root anymore.
std::list< UnivariatePolynomial > standardSturmSequence () const
std::list< UnivariatePolynomial > standardSturmSequence (const UnivariatePolynomial &polynomial) const
unsigned int signVariations (const Interval< Coefficient > &interval) const
Counts the sign variations (i.e.
int countRealRoots (const Interval< Coefficient > &interval) const
Count the number of real roots within the given interval using Sturm sequences.
UnivariatePolynomial< Coefficient > resultant (const UnivariatePolynomial< Coefficient > &p, const SubresultantStrategy strategy=SubresultantStrategy::Default) const
UnivariatePolynomial< Coefficient > discriminant (const SubresultantStrategy strategy=SubresultantStrategy::Default) const
bool less (const UnivariatePolynomial< Coefficient > &rhs, const PolynomialComparisonOrder &order=PolynomialComparisonOrder::Default) const
UnivariatePolynomial operator- () const
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
bool isConsistent () const
Asserts that this polynomial over numeric coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
bool isConsistent () const
Asserts that this polynomial over polynomial coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
In-place addition operators
UnivariatePolynomial & operator+= (const Coefficient &rhs)
Add something to this polynomial and return the changed polynomial.
UnivariatePolynomial & operator+= (const UnivariatePolynomial &rhs)
Add something to this polynomial and return the changed polynomial.
In-place subtraction operators
UnivariatePolynomial & operator-= (const Coefficient &rhs)
Subtract something from this polynomial and return the changed polynomial.
UnivariatePolynomial & operator-= (const UnivariatePolynomial &rhs)
Subtract something from this polynomial and return the changed polynomial.
In-place multiplication operators
template<typename C = Coefficient, EnableIf< is_number< C >> = dummy>
UnivariatePolynomial & operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
template<typename C = Coefficient, DisableIf< is_number< C >> = dummy>
UnivariatePolynomial & operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
UnivariatePolynomial & operator*= (const Coefficient &rhs)
Multiply this polynomial with something and return the changed polynomial.
template<typename I = Coefficient, DisableIf< std::is_same< Coefficient, I >> ...>
UnivariatePolynomial & operator*= (const typename IntegralType< Coefficient >::type &rhs)
Multiply this polynomial with something and return the changed polynomial.
UnivariatePolynomial & operator*= (const UnivariatePolynomial &rhs)
Multiply this polynomial with something and return the changed polynomial.
In-place division operators
template<typename C = Coefficient, EnableIf< is_field< C >> = dummy>
UnivariatePolynomial & operator/= (const Coefficient &rhs)
Divide this polynomial by something and return the changed polynomial.
template<typename C = Coefficient, DisableIf< is_field< C >> = dummy>
UnivariatePolynomial & operator/= (const Coefficient &rhs)
Divide this polynomial by something and return the changed polynomial.
Static Public Member Functions
static UnivariatePolynomial gcd (const UnivariatePolynomial &a, const UnivariatePolynomial &b)
Calculates the greatest common divisor of two polynomials.
static UnivariatePolynomial extended_gcd (const UnivariatePolynomial &a, const UnivariatePolynomial &b, UnivariatePolynomial &s, UnivariatePolynomial &t)
Calculates the extended greatest common divisor g of two polynomials.
template<typename Integer >
static UnivariatePolynomial excludeLinearFactors (const UnivariatePolynomial &_poly, std::map< UnivariatePolynomial, unsigned > &_linearFactors, const Integer &maxNum=0)
template<typename C = Coefficient, typename Number = typename UnderlyingNumberType<C>::type>
static int countRealRoots (const std::list< UnivariatePolynomial< Coefficient >> &seq, const Interval< Number > &interval)
Calculate the number of real roots of a polynomial within a given interval based on a sturm sequence of this polynomial.
static const std::list
< UnivariatePolynomial > subresultants (const UnivariatePolynomial &p, const UnivariatePolynomial &q, const SubresultantStrategy strategy=SubresultantStrategy::Default)
Implements subresultants algorithm with optimizations described in [1] .
static const std::vector
< UnivariatePolynomial > principalSubresultantsCoefficients (const UnivariatePolynomial &p, const UnivariatePolynomial &q, const SubresultantStrategy strategy=SubresultantStrategy::Default)
Private Member Functions
void reverse ()
Reverses the order of the coefficients of this polynomial.
void scale (const Coefficient &factor)
Scale the variable, i.e.
void shift (const Coefficient &a)
Shift the variable by a, i.e.
UnivariatePolynomial remainder_helper (const UnivariatePolynomial &divisor, const Coefficient *prefactor=nullptr) const
Calculates the remainder of polynomial division.
void stripLeadingZeroes ()
Static Private Member Functions
static UnivariatePolynomial gcd_recursive (const UnivariatePolynomial &p, const UnivariatePolynomial &q)
Private Attributes
Variable mMainVar
The main variable.
std::vector< Coefficient > mCoefficients
The coefficients.
Friends
template<class T >
class UnivariatePolynomial
Declare all instantiations of univariate polynomials as friends.
template<typename C >
bool operator< (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
template<typename C >
std::ostream & operator<< (std::ostream &os, const UnivariatePolynomial< C > &rhs)
Streaming operator for univariate polynomials.
Equality comparison operators
template<typename C >
bool operator== (const C &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are equal.
template<typename C >
bool operator== (const UnivariatePolynomial< C > &lhs, const C &rhs)
Checks if the two arguments are equal.
template<typename C >
bool operator== (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are equal.
template<typename C >
bool operator== (const UnivariatePolynomialPtr< C > &lhs, const UnivariatePolynomialPtr< C > &rhs)
Checks if the two arguments are equal.
Inequality comparison operators
template<typename C >
bool operator!= (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Checks if the two arguments are not equal.
template<typename C >
bool operator!= (const UnivariatePolynomialPtr< C > &lhs, const UnivariatePolynomialPtr< C > &rhs)
Checks if the two arguments are not equal.
Addition operators
template<typename C >
UnivariatePolynomial< C > operator+ (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Performs an addition involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator+ (const C &lhs, const UnivariatePolynomial< C > &rhs)
Performs an addition involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator+ (const UnivariatePolynomial< C > &lhs, const C &rhs)
Performs an addition involving a polynomial.
Subtraction operators
template<typename C >
UnivariatePolynomial< C > operator- (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Performs a subtraction involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator- (const C &lhs, const UnivariatePolynomial< C > &rhs)
Performs a subtraction involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator- (const UnivariatePolynomial< C > &lhs, const C &rhs)
Performs a subtraction involving a polynomial.
Multiplication operators
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, Variable::Arg rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (Variable::Arg lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const C &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, const C &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const typename IntegralType< C >::type &lhs, const UnivariatePolynomial< C > &rhs)
Perform a multiplication involving a polynomial.
template<typename C >
UnivariatePolynomial< C > operator* (const UnivariatePolynomial< C > &lhs, const typename IntegralType< C >::type &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
UnivariatePolynomial
< MultivariatePolynomial< C, O,
P > > operator* (const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> &lhs, const C &rhs)
Perform a multiplication involving a polynomial.
template<typename C , typename O , typename P >
UnivariatePolynomial
< MultivariatePolynomial< C, O,
P > > operator* (const C &lhs, const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> &rhs)
Perform a multiplication involving a polynomial.
Division operators
template<typename C >
UnivariatePolynomial< C > operator/ (const UnivariatePolynomial< C > &lhs, const C &rhs)
Perform a division involving a polynomial.
Detailed Description
template<typename Coefficient>
class carl::UnivariatePolynomial< Coefficient >
This class represents a univariate polynomial with coefficients of an arbitrary type.
A univariate polynomial is defined by a variable (the main variable) and the coefficients. The coefficients may be of any type. The intention is to use a numbers or polynomials as coefficients. If polynomials are used as coefficients, this can be seen as a multivariate polynomial with a distinguished main variable.
Most methods are specifically adapted for polynomial coefficients, if necessary.
Definition at line 21 of file MultivariateGCD.h.
Constructor & Destructor Documentation
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial () delete
Default constructor shall not exist.
Use UnivariatePolynomial(Variable::Arg) instead.
Referenced by carl::UnivariatePolynomial< Coeff >::one().
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar) explicit
Construct a zero polynomial with the given main variable.
Parameters
mainVar New main variable.
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar, const Coefficient & coeff, std::size_t degree = 0)
Construct .
Parameters
mainVar New main variable.
coeff Leading coefficient.
degree Degree.
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar, std::initializer_list< Coefficient > coefficients)
Construct polynomial with the given coefficients.
Parameters
mainVar New main variable.
coefficients List of coefficients.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< std::is_same< C, typename UnderlyingNumberType< C >::type >> = dummy> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar, std::initializer_list< typename UnderlyingNumberType< C >::type > coefficients)
Construct polynomial with the given coefficients from the underlying number type of the coefficient type.
Parameters
mainVar New main variable.
coefficients List of coefficients.
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar, const std::vector< Coefficient > & coefficients)
Construct polynomial with the given coefficients.
Parameters
mainVar New main variable.
coefficients Vector of coefficients.
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar, std::vector< Coefficient > && coefficients)
Construct polynomial with the given coefficients, moving the coefficients.
Parameters
mainVar New main variable.
coefficients Vector of coefficients.
template<typename Coefficient> carl::UnivariatePolynomial< Coefficient >::UnivariatePolynomial (Variable::Arg mainVar, const std::map< unsigned, Coefficient > & coefficients)
Construct polynomial with the given coefficients.
Parameters
mainVar New main variable.
coefficients Assignment of degree to coefficients.
Member Function Documentation
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::cauchyBound () const
Notice, Cauchy bounds are only defined for polynomials over fields.
This is
Returns
template<typename Coefficient> const std::vector<Coefficient>& carl::UnivariatePolynomial< Coefficient >::coefficients () const inline
Retrieves the coefficients defining this polynomial.
Returns
Coefficients.
Definition at line 379 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::isUnivariate(), and std::hash< carl::UnivariatePolynomial< Coefficient > >::operator()().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::constantPart () const inline
Returns the constant part of this polynomial.
Applies, if the coefficients are numbers.
Returns
Constant part.
Definition at line 283 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::constantPart () const inline
Returns the constant part of this polynomial.
Applies, if the coefficients are not numbers. Calls constantPart() on the trailing coefficient recursively.
Returns
Constant part.
Definition at line 295 of file UnivariatePolynomial.h.
template<typename Coefficient> Coefficient carl::UnivariatePolynomial< Coefficient >::content () const
The content of a polynomial is the gcd of the coefficients of the normal part of a polynomial.
The content of zero is zero.
See also
[2], page 52
Returns
The content of the polynomial.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy> UnivariatePolynomial<typename IntegralType<Coefficient>::type> carl::UnivariatePolynomial< Coefficient >::coprimeCoefficients () const
Constructs a new polynomial that is scaled such that the coefficients are coprime.
It is calculated by multiplying it with the coprime factor. By definition, this results in a polynomial with integral coefficients.
Returns
This polynomial multiplied with the coprime factor.
Referenced by carl::Resultant::preprocessing().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy> Coefficient carl::UnivariatePolynomial< Coefficient >::coprimeFactor () const
Calculates a factor that would make the coefficients of this polynomial coprime integers.
We consider a set of integers coprime, if they share no common factor. Technically, the coprime factor is where N is the set of the numerators and D is the set of the denominators of all coefficients.
Returns
Coprime factor of this polynomial.
template<typename Coefficient> int carl::UnivariatePolynomial< Coefficient >::countRealRoots (const Interval< Coefficient > & interval) const
Count the number of real roots within the given interval using Sturm sequences.
Parameters
interval Count roots within this interval.
Returns
Number of real roots within the interval.
template<typename Coefficient> template<typename C = Coefficient, typename Number = typename UnderlyingNumberType<C>::type> static int carl::UnivariatePolynomial< Coefficient >::countRealRoots (const std::list< UnivariatePolynomial< Coefficient >> & seq, const Interval< Number > & interval) static
Calculate the number of real roots of a polynomial within a given interval based on a sturm sequence of this polynomial.
Parameters
seq Sturm sequence.
interval Interval.
Returns
Number of real roots in the interval.
template<typename Coefficient> unsigned carl::UnivariatePolynomial< Coefficient >::degree () const inline
Get the maximal exponent of the main variable.
As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[2], page 38
Returns
Degree.
Definition at line 329 of file UnivariatePolynomial.h.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::Resultant::eliminate(), and carl::UnivariatePolynomial< Coeff >::totalDegree().
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::derivative (unsigned nth = 1) const
The n'th derivative of the polynomial in its main variable.
Parameters
nth how many times the derivative should be applied.
Returns
A polynomial where is the input polynomial.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_integer< C >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const UnivariatePolynomial< Coefficient > & divisor) const
Divides the polynomial by another polynomial.
Applies if the polynomial both have integer coefficients.
Parameters
divisor Divisor.
Returns
this / divisor.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate(), carl::DiophantineEquations< Integer >::EEAlift(), and carl::UnivariatePolynomial< Coeff >::pseudoPrimpart().
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_integer< C >> = dummy, EnableIf< is_field< C >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const UnivariatePolynomial< Coefficient > & divisor) const
Divides the polynomial by another polynomial.
Applies if the polynomial both have coefficients over a field.
Parameters
divisor Divisor.
Returns
this / divisor.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const Coefficient & divisor) const
Divides the polynomial by a coefficient.
Applies if the polynomial has coefficients from a field.
Parameters
divisor Divisor.
Returns
this / divisor.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::divideBy (const Coefficient & divisor, UnivariatePolynomial< Coefficient > & quotient) const
Divides the polynomial by a coefficient.
If the divisor divides this polynomial, quotient contains the result of the division and true is returned. Otherwise, false is returned and the content of quotient is undefined. Applies if the polynomial has coefficients that are neither numeric nor from a field.
Parameters
divisor Divisor.
quotient Resulting quotient.
Returns
If remainder was zero.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy, DisableIf< is_number< C >> = dummy, EnableIf< is_field< typename UnderlyingNumberType< C >::type >> = dummy> DivisionResult<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::divideBy (const NumberType & divisor) const
Divides the polynomial by a number.
Applies if the polynomial has coefficients that are polynomials with coefficients from a field.
Parameters
divisor Divisor.
Returns
Quotient and remainder.
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::divides (const UnivariatePolynomial< Coefficient > & divisor) const
Checks if this polynomial is divisible by the given divisor, that is if the remainder is zero.
Parameters
divisor Polynomial.
Returns
If divisor divides this polynomial.
Referenced by carl::EZGCD< Coeff, Ordering, Policies >::calculate().
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::eliminateRoot (const Coefficient & root)
Reduces the polynomial such that the given root is not a root anymore.
The reduction is achieved by removing the linear factor (mainVar - root) from the polynomial, possibly multiple times.
This method assumes that the given root is an actual real root of this polynomial. If this is not the case, i.e. evaluate(root) != 0, the polynomial will contain meaningless garbage.
Parameters
root Root to be eliminated.
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::eliminateZeroRoots ()
Reduces the polynomial such that zero is not a root anymore.
Is functionally equivalent to eliminateRoot(0), but much faster.
template<typename Coefficient> static UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::extended_gcd (const UnivariatePolynomial< Coefficient > & a, const UnivariatePolynomial< Coefficient > & b, UnivariatePolynomial< Coefficient > & s, UnivariatePolynomial< Coefficient > & t) static
Calculates the extended greatest common divisor g of two polynomials.
The output polynomials s and t are computed such that .
Parameters
a First polynomial.
b Second polynomial.
s First output polynomial.
t Second output polynomial.
See also
[2], Algorithm 2.2
Returns
gcd(a,b)
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> std::set<Variable> carl::UnivariatePolynomial< Coefficient >::gatherVariables () const inline
Gathers all variables that occur in the polynomial.
Applies, if the coefficients are numbers.
Returns
Set of variables.
Definition at line 443 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> std::set<Variable> carl::UnivariatePolynomial< Coefficient >::gatherVariables () const inline
Gathers all variables that occur in the polynomial.
Applies, if the coefficients are not numbers.
Returns
Set of variables.
Definition at line 452 of file UnivariatePolynomial.h.
template<typename Coefficient> static UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::gcd (const UnivariatePolynomial< Coefficient > & a, const UnivariatePolynomial< Coefficient > & b) static
Calculates the greatest common divisor of two polynomials.
Parameters
a First polynomial.
b Second polynomial.
Returns
gcd(a,b)
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> unsigned carl::UnivariatePolynomial< Coefficient >::has (Variable::Arg v) const inline
Checks if the given variable occurs in the polynomial.
Applies, if the coefficients are numbers.
Parameters
v Variable.
Returns
If v occurs in the polynomial.
Definition at line 468 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> unsigned carl::UnivariatePolynomial< Coefficient >::has (Variable::Arg v) const inline
Checks if the given variable occurs in the polynomial.
Applies, if the coefficients are not numbers.
Parameters
v Variable.
Returns
If v occurs in the polynomial.
Definition at line 478 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isConsistent () const
Asserts that this polynomial over numeric coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
The leading term is not zero.
Referenced by carl::UnivariatePolynomial< Coeff >::isConstant(), and carl::UnivariatePolynomial< Coeff >::switchVariable().
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isConsistent () const
Asserts that this polynomial over polynomial coefficients complies with the requirements and assumptions for UnivariatePolynomial objects.
The leading term is not zero.
The main variable does not occur in any coefficient.
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isConstant () const inline
Checks whether the polynomial is constant with respect to the main variable.
Returns
If polynomial is constant.
Definition at line 242 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::isNumber(), and carl::Resultant::preprocessing().
template<typename Coefficient> virtual bool carl::UnivariatePolynomial< Coefficient >::isMultivariateRepresented () const inline override virtual
Checks if the polynomial is represented multivariately.
See also
Polynomial::isMultivariateRepresented
Returns
false.
Implements carl::Polynomial.
Definition at line 174 of file UnivariatePolynomial.h.
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isNormal () const
Checks whether the polynomial is unit normal.
A polynomial is unit normal, if the leading coefficient is unit normal, that is if it is either one or minus one.
See also
[2], page 39
Returns
If polynomial is normal.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isNumber () const inline
Checks whether the polynomial is only a number.
Applies if the coefficients are numbers.
Returns
If polynomial is a number.
Definition at line 260 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isNumber () const inline
Checks whether the polynomial is only a number.
Applies if the coefficients are not numbers. Calls isNumber() on the constant coefficient recursively.
Returns
If polynomial is a number.
Definition at line 271 of file UnivariatePolynomial.h.
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isOne () const inline
Checks if the polynomial is equal to one.
Returns
If polynomial is one.
Definition at line 192 of file UnivariatePolynomial.h.
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isUnivariate () const inline
Checks if the polynomial is univariate, that means if only one variable occurs.
Applies, if the coefficients are numbers.
Returns
true.
Definition at line 307 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> bool carl::UnivariatePolynomial< Coefficient >::isUnivariate () const inline
Checks if the polynomial is univariate, that means if only one variable occurs.
Applies, if the coefficients are not numbers.
Returns
If polynomial is univariate.
Definition at line 316 of file UnivariatePolynomial.h.
template<typename Coefficient> virtual bool carl::UnivariatePolynomial< Coefficient >::isUnivariateRepresented () const inline override virtual
Checks if the polynomial is represented univariately.
See also
Polynomial::isUnivariateRepresented
Returns
true.
Implements carl::Polynomial.
Definition at line 164 of file UnivariatePolynomial.h.
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::isZero () const inline
Checks if the polynomial is equal to zero.
Returns
If polynomial is zero.
Definition at line 183 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::constantPart(), carl::UnivariatePolynomial< Coeff >::degree(), carl::UnivariatePolynomial< Coeff >::isNumber(), carl::Resultant::preprocessing(), carl::UnivariatePolynomial< Coeff >::totalDegree(), and carl::UnivariatePolynomial< Coeff >::zeroIsRoot().
template<typename Coefficient> const Coefficient& carl::UnivariatePolynomial< Coefficient >::lcoeff () const inline
Returns the leading coefficient.
Asserts, that the polynomial is not empty.
Returns
The leading coefficient.
Definition at line 223 of file UnivariatePolynomial.h.
Referenced by carl::Resultant::eliminate(), carl::UnivariatePolynomial< Coeff >::isNumber(), carl::UnivariatePolynomial< Coeff >::numericUnit(), carl::UnivariatePolynomial< Coeff >::one(), and carl::Resultant::preprocessing().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> IntNumberType carl::UnivariatePolynomial< Coefficient >::mainDenom () const
Compute the main denominator of all numeric coefficients of this polynomial.
This method only applies if the Coefficient type is a number.
Returns
the main denominator of all coefficients of this polynomial.
template<typename Coefficient> Variable::Arg carl::UnivariatePolynomial< Coefficient >::mainVar () const inline
Retrieves the main variable of this polynomial.
Returns
Main variable.
Definition at line 387 of file UnivariatePolynomial.h.
Referenced by carl::DiophantineEquations< Integer >::EEAlift(), carl::Resultant::eliminate(), carl::UnivariatePolynomial< Coeff >::gatherVariables(), carl::UnivariatePolynomial< Coeff >::has(), carl::Resultant::preprocessing(), and carl::UnivariatePolynomial< Coeff >::replaceVariable().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_subset_of_rationals< C >> = dummy> IntNumberType carl::UnivariatePolynomial< Coefficient >::maximumNorm () const
The maximum norm of a polynomial is the maximum absolute value of the coefficients of the corresponding integral polynomial (as calculated by coprimeCoefficients()).
Returns
Maximum-norm of the polynomial in case it has numeric coefficients.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::mod (const Coefficient & modulus)
Replaces every coefficient c by c mod modulus.
Parameters
modulus Modulus.
Returns
This.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::mod (const Coefficient & modulus) const
Constructs a new polynomial where every coefficient c is replaced by c mod modulus.
Parameters
modulus Modulus.
Returns
New polynomial.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::negateVariable () const inline
Constructs a new polynomial q such that where p is this polynomial.
Returns
New polynomial with negated variable.
Definition at line 587 of file UnivariatePolynomial.h.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::normalized () const
The normal part of a polynomial is the polynomial divided by the unit part.
See also
[2], page 42.
Returns
This polynomial divided by the unit part.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::numericContent (unsigned int i) const inline
Returns the numeric content part of the i'th coefficient.
If the coefficients are numbers, this is simply the i'th coefficient. If the coefficients are polynomials, this is the numeric content part of the i'th coefficient.
Parameters
i number of the coefficient
Returns
numeric content part of i'th coefficient.
Definition at line 794 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename N = NumberType, EnableIf< is_subset_of_rationals< N >> = dummy> UnderlyingNumberType<Coefficient>::type carl::UnivariatePolynomial< Coefficient >::numericContent () const
Obtains the numeric content part of this polynomial.
The numeric content part of a polynomial is defined as the gcd() of the numeric content parts of all coefficients. This is only possible if the underlying number type is either integral or fractional.
As for fractional numbers, we consider the following definition: gcd(a/b, c/d) = gcd(a/b*l, c/d*l) / l where l = lcm(b,d).
Returns
numeric content part of the polynomial.
See also
UnivariatePolynomials::numericContent(unsigned int)
Referenced by carl::UnivariatePolynomial< Coeff >::pseudoPrimpart().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> NumberType carl::UnivariatePolynomial< Coefficient >::numericUnit () const inline
Returns the numeric unit part of the polynomial.
If the coefficients are numbers, this is the sign of the leading coefficient. If the coefficients are polynomials, this is the unit part of the leading coefficient.s
Returns
unit part of the polynomial.
Definition at line 812 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::one () const inline
Creates a polynomial of value one with the same main variable.
Applies if the Coefficient are GFNumber values.
Returns
One.
Definition at line 203 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::one () const inline
Creates a polynomial of value one with the same main variable.
Applies if the Coefficient are not GFNumber values.
Returns
One.
Definition at line 213 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (Variable::Arg rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (const Coefficient & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> template<typename I = Coefficient, DisableIf< std::is_same< Coefficient, I >> ...> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (const typename IntegralType< Coefficient >::type & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator*= (const UnivariatePolynomial< Coefficient > & rhs)
Multiply this polynomial with something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator+= (const Coefficient & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator+= (const UnivariatePolynomial< Coefficient > & rhs)
Add something to this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator-= (const Coefficient & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator-= (const UnivariatePolynomial< Coefficient > & rhs)
Subtract something from this polynomial and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator/= (const Coefficient & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_field< C >> = dummy> UnivariatePolynomial& carl::UnivariatePolynomial< Coefficient >::operator/= (const Coefficient & rhs)
Divide this polynomial by something and return the changed polynomial.
Parameters
rhs Right hand side.
Returns
Changed polynomial.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::pow (std::size_t exp) const
Returns this polynomial to the given power.
Parameters
exp Exponent.
Returns
This to the power of exp.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::prem_old (const UnivariatePolynomial< Coefficient > & divisor) const
Calculates the pseudo-remainder.
See also
[2], page 55, Pseudo-Division Property
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::primitivePart () const
The primitive part of p is the normal part of p divided by the content of p.
The primitive part of zero is zero.
See also
[2], page 53
Returns
The primitive part of the polynomial.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::pseudoPrimpart () const inline
Returns this/divisor where divisor is the numeric content of this polynomial.
Returns
Definition at line 841 of file UnivariatePolynomial.h.
template<typename Coefficient> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::remainder_helper (const UnivariatePolynomial< Coefficient > & divisor, const Coefficient * prefactor = nullptr) const private
Calculates the remainder of polynomial division.
Parameters
divisor
prefactor
See also
[2], page 55, Pseudo-Division Property
Returns
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::replaceVariable (Variable::Arg newVar) const inline
Replaces the main variable.
Applies, if the coefficients are numbers.
Parameters
newVar New main variable.
Returns
New polynomial.
Definition at line 423 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::replaceVariable (Variable::Arg newVar) const inline
Replaces the main variable.
Applies, if the coefficients are not numbers.
Parameters
newVar New main variable.
Returns
New polynomial.
Definition at line 433 of file UnivariatePolynomial.h.
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::reverse () private
Reverses the order of the coefficients of this polynomial.
This method is meant to be called by signVariations only.
Runtime complexity:
O(n)
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::scale (const Coefficient & factor) private
Scale the variable, i.e.
apply This method is meant to be called by signVariations only.
Parameters
factor Factor to scale x.
Runtime complexity:
O(n)
template<typename Coefficient> carl::Sign carl::UnivariatePolynomial< Coefficient >::sgn (const Coefficient & value) const inline
Calculates the sign of the polynomial at some point.
Parameters
value Point to evaluate.
Returns
Sign at value.
Definition at line 713 of file UnivariatePolynomial.h.
template<typename Coefficient> void carl::UnivariatePolynomial< Coefficient >::shift (const Coefficient & a) private
Shift the variable by a, i.e.
apply This method is meant to be called by signVariations only.
Parameters
a Offset to shift x.
Runtime complexity:
O(n^2)
template<typename Coefficient> unsigned int carl::UnivariatePolynomial< Coefficient >::signVariations (const Interval< Coefficient > & interval) const
Counts the sign variations (i.e.
an upper bound for the number of real roots) via Descarte's rule of signs. This is an upper bound for countRealRoots().
Parameters
interval Count roots within this interval.
Returns
Upper bound for number of real roots within the interval.
template<typename Coefficient> static const std::list<UnivariatePolynomial> carl::UnivariatePolynomial< Coefficient >::subresultants (const UnivariatePolynomial< Coefficient > & p, const UnivariatePolynomial< Coefficient > & q, const SubresultantStrategy strategy = SubresultantStrategy::Default) static
Implements subresultants algorithm with optimizations described in [1] .
Parameters
p First polynomial.
q First polynomial.
strategy Strategy.
Returns
Subresultants of p and q.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> UnivariatePolynomial<MultivariatePolynomial<NumberType> > carl::UnivariatePolynomial< Coefficient >::switchVariable (Variable::Arg newVar) const inline
Switches the main variable using a purely syntactical restructuring.
The resulting polynomial will be algebraicly identical, but have the given variable as its main variable. Applies, if the coefficients are numbers.
Parameters
newVar New main variable.
Returns
Restructured polynomial.
Definition at line 399 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> UnivariatePolynomial carl::UnivariatePolynomial< Coefficient >::switchVariable (Variable::Arg newVar) const inline
Switches the main variable using a purely syntactical restructuring.
The resulting polynomial will be algebraicly identical, but have the given variable as its main variable. Applies, if the coefficients are not numbers.
Parameters
newVar New main variable.
Returns
Restructured polynomial.
Definition at line 411 of file UnivariatePolynomial.h.
template<typename Coefficient> const Coefficient& carl::UnivariatePolynomial< Coefficient >::tcoeff () const inline
Returns the trailing coefficient.
Asserts, that the polynomial is not empty.
Returns
The trailing coefficient.
Definition at line 233 of file UnivariatePolynomial.h.
Referenced by carl::UnivariatePolynomial< Coeff >::constantPart(), and carl::Resultant::preprocessing().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_instantiation_of< GFNumber, C >> = dummy> UnivariatePolynomial<typename IntegralType<Coefficient>::type> carl::UnivariatePolynomial< Coefficient >::toIntegerDomain () const
Works only from rationals, if the numbers are already integers.
Returns
Referenced by carl::DiophantineEquations< Integer >::EEAlift().
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_number< C >> = dummy> unsigned carl::UnivariatePolynomial< Coefficient >::totalDegree () const inline
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
Applies, if the coefficients are numbers. In this case, the total degree is the degree. As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[2], page 38
Returns
Total degree.
Definition at line 342 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, DisableIf< is_number< C >> = dummy> unsigned carl::UnivariatePolynomial< Coefficient >::totalDegree () const inline
Returns the total degree of the polynomial, that is the maximum degree of any monomial.
Applies, if the coefficients are not numbers. In this case, the total degree of all coefficients must be considered. As the degree of the zero polynomial is , we assert that this polynomial is not zero. This must be checked by the caller before calling this method.
See also
[2], page 48
Returns
Total degree.
Definition at line 354 of file UnivariatePolynomial.h.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< is_field< C >> = dummy> const Coefficient& carl::UnivariatePolynomial< Coefficient >::unitPart () const
The unit part of a polynomial over a field is its leading coefficient for nonzero polynomials, and one for zero polynomials.
See also
[2], page 42.
Returns
The unit part of the polynomial.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< Not< is_number< C >> > = dummy> Coefficient carl::UnivariatePolynomial< Coefficient >::unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
See also
[2], page 42.
Returns
The unit part of the polynomial.
template<typename Coefficient> template<typename C = Coefficient, EnableIf< Not< is_field< C >>, is_number< C >> = dummy> Coefficient carl::UnivariatePolynomial< Coefficient >::unitPart () const
The unit part of a polynomial over a ring is the sign of the polynomial for nonzero polynomials, and one for zero polynomials.
See also
[2], page 42.
Returns
The unit part of the polynomial.
template<typename Coefficient> bool carl::UnivariatePolynomial< Coefficient >::zeroIsRoot () const inline
Checks if zero is a real root of this polynomial.
Returns
True if zero is a root.
Definition at line 870 of file UnivariatePolynomial.h.
Friends And Related Function Documentation
template<typename Coefficient> template<typename C > bool operator!= (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
template<typename Coefficient> template<typename C > bool operator!= (const UnivariatePolynomialPtr< C > & lhs, const UnivariatePolynomialPtr< C > & rhs) friend
Checks if the two arguments are not equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs != rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, Variable::Arg rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (Variable::Arg lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const typename IntegralType< C >::type & lhs, const UnivariatePolynomial< C > & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator* (const UnivariatePolynomial< C > & lhs, const typename IntegralType< C >::type & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C , typename O , typename P > UnivariatePolynomial<MultivariatePolynomial<C,O,P> > operator* (const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> & lhs, const C & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C , typename O , typename P > UnivariatePolynomial<MultivariatePolynomial<C,O,P> > operator* (const C & lhs, const UnivariatePolynomial< MultivariatePolynomial< C, O, P >> & rhs) friend
Perform a multiplication involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs * rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator+ (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator+ (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator+ (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Performs an addition involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs + rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator- (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs a subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator- (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Performs a subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator- (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Performs a subtraction involving a polynomial.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs - rhs
template<typename Coefficient> template<typename C > UnivariatePolynomial<C> operator/ (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Perform a division involving a polynomial.
Parameters
lhs Left hand side.
rhs Right hand side.
Returns
lhs / rhs
template<typename Coefficient> template<typename C > std::ostream& operator<< (std::ostream & os, const UnivariatePolynomial< C > & rhs) friend
Streaming operator for univariate polynomials.
Parameters
os Output stream.
rhs Polynomial.
Returns
os
template<typename Coefficient> template<typename C > bool operator== (const C & lhs, const UnivariatePolynomial< C > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
template<typename Coefficient> template<typename C > bool operator== (const UnivariatePolynomial< C > & lhs, const C & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
template<typename Coefficient> template<typename C > bool operator== (const UnivariatePolynomial< C > & lhs, const UnivariatePolynomial< C > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
template<typename Coefficient> template<typename C > bool operator== (const UnivariatePolynomialPtr< C > & lhs, const UnivariatePolynomialPtr< C > & rhs) friend
Checks if the two arguments are equal.
Parameters
lhs First argument.
rhs Second argument.
Returns
lhs == rhs
The documentation for this class was generated from the following files:
carl/core/MultivariateGCD.h
carl/core/UnivariatePolynomial.h