carl: carl::parser::ExpressionParser< Pol > Struct Template Reference
carl::parser::ExpressionParser< Pol > Struct Template Reference
#include <ExpressionParser.h>
Data Structures
class perform_addition
class perform_division
class perform_multiplication
class perform_negate
class perform_power
class perform_subtraction
class print_expr_type
Public Types
typedef Pol::CoeffType CoeffType
using expr_type = ExpressionType< Pol >
Public Member Functions
ExpressionParser ()
void addVariable (Variable::Arg v)
Private Types
enum Operation {
ADD, SUB, MUL, DIV,
POW, NEG
}
Private Member Functions
Variable newVariable (const std::string &s)
expr_type makeBool (bool value)
expr_type booleanBinaryExpr (const expr_type &first, const std::vector< boost::fusion::vector2< carl::FormulaType, expr_type >> &ops)
expr_type booleanUnaryExpr (const std::vector< carl::FormulaType > &ops, const expr_type &first)
expr_type arithmeticExpr (const expr_type &first, const std::vector< boost::fusion::vector2< Operation, expr_type >> &ops)
expr_type powExpr (const expr_type &first, const std::vector< boost::fusion::vector2< Operation, exponent >> &ops)
expr_type signExpr (const std::vector< Operation > &ops, const expr_type &first)
Private Attributes
qi::symbols< char, carl::FormulaType > operationNot
qi::symbols< char, carl::FormulaType > operationImp
qi::symbols< char, carl::FormulaType > operationIff
qi::symbols< char, carl::FormulaType > operationAnd
qi::symbols< char, Operation > operationShift
qi::symbols< char, Operation > operationScale
qi::symbols< char, Operation > operationPow
qi::symbols< char, Operation > operationSign
qi::symbols< char, Variable > varmap
qi::rule< Iterator, std::string(), Skipper > varname
qi::uint_parser< exponent, 10, 1,-1 > exponentVal
qi::real_parser< CoeffType, RationalPolicies< CoeffType > > coeff
qi::rule< Iterator, Variable(), Skipper > variable
qi::rule< Iterator, Operation(), Skipper > operationScaleLA
qi::rule< Iterator, expr_type(), Skipper > boolean
qi::rule< Iterator, expr_type(), Skipper > monomial
qi::rule< Iterator, expr_type(), Skipper > atom
qi::rule< Iterator, expr_type(), Skipper > expr
qi::rule< Iterator, expr_type(), Skipper > expr_sign
qi::rule< Iterator, expr_type(), Skipper > expr_product
qi::rule< Iterator, expr_type(), Skipper > expr_power
qi::rule< Iterator, expr_type(), Skipper > expr_sum
qi::rule< Iterator, expr_type(), Skipper > main
Detailed Description
template<typename Pol>
struct carl::parser::ExpressionParser< Pol >
Definition at line 83 of file ExpressionParser.h.
Member Typedef Documentation
CoeffType
template<typename Pol > typedef Pol::CoeffType carl::parser::ExpressionParser< Pol >::CoeffType
Definition at line 84 of file ExpressionParser.h.
expr_type
template<typename Pol > using carl::parser::ExpressionParser< Pol >::expr_type = ExpressionType<Pol>
Definition at line 85 of file ExpressionParser.h.
Member Enumeration Documentation
Operation
template<typename Pol > enum carl::parser::ExpressionParser::Operation private
Enumerator
ADD
SUB
MUL
DIV
POW
NEG
Definition at line 399 of file ExpressionParser.h.
Constructor & Destructor Documentation
ExpressionParser()
template<typename Pol > carl::parser::ExpressionParser< Pol >::ExpressionParser () inline
Tokens
Rules
Definition at line 353 of file ExpressionParser.h.
Member Function Documentation
addVariable()
template<typename Pol > void carl::parser::ExpressionParser< Pol >::addVariable (Variable::Arg v) inline
Definition at line 393 of file ExpressionParser.h.
arithmeticExpr()
template<typename Pol > expr_type carl::parser::ExpressionParser< Pol >::arithmeticExpr (const expr_type & first, const std::vector< boost::fusion::vector2< Operation, expr_type >> & ops) inline private
Definition at line 463 of file ExpressionParser.h.
booleanBinaryExpr()
template<typename Pol > expr_type carl::parser::ExpressionParser< Pol >::booleanBinaryExpr (const expr_type & first, const std::vector< boost::fusion::vector2< carl::FormulaType, expr_type >> & ops) inline private
Definition at line 425 of file ExpressionParser.h.
booleanUnaryExpr()
template<typename Pol > expr_type carl::parser::ExpressionParser< Pol >::booleanUnaryExpr (const std::vector< carl::FormulaType > & ops, const expr_type & first) inline private
Definition at line 450 of file ExpressionParser.h.
makeBool()
template<typename Pol > expr_type carl::parser::ExpressionParser< Pol >::makeBool (bool value) inline private
Definition at line 417 of file ExpressionParser.h.
newVariable()
template<typename Pol > Variable carl::parser::ExpressionParser< Pol >::newVariable (const std::string & s) inline private
Definition at line 401 of file ExpressionParser.h.
powExpr()
template<typename Pol > expr_type carl::parser::ExpressionParser< Pol >::powExpr (const expr_type & first, const std::vector< boost::fusion::vector2< Operation, exponent >> & ops) inline private
Definition at line 488 of file ExpressionParser.h.
signExpr()
template<typename Pol > expr_type carl::parser::ExpressionParser< Pol >::signExpr (const std::vector< Operation > & ops, const expr_type & first) inline private
Definition at line 501 of file ExpressionParser.h.
Field Documentation
atom
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::atom private
Definition at line 535 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
boolean
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::boolean private
Definition at line 533 of file ExpressionParser.h.
coeff
template<typename Pol > qi::real_parser<CoeffType,RationalPolicies<CoeffType> > carl::parser::ExpressionParser< Pol >::coeff private
Definition at line 528 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser(), and carl::parser::ExpressionParser< Pol >::perform_division::operator()().
exponentVal
template<typename Pol > qi::uint_parser<exponent,10,1,-1> carl::parser::ExpressionParser< Pol >::exponentVal private
Definition at line 527 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
expr
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::expr private
Definition at line 537 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser(), and carl::parser::ExpressionParser< Pol >::print_expr_type::operator()().
expr_power
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::expr_power private
Definition at line 540 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
expr_product
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::expr_product private
Definition at line 539 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
expr_sign
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::expr_sign private
Definition at line 538 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
expr_sum
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::expr_sum private
Definition at line 541 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
main
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::main private
Definition at line 542 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
monomial
template<typename Pol > qi::rule<Iterator, expr_type(), Skipper> carl::parser::ExpressionParser< Pol >::monomial private
Definition at line 534 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationAnd
template<typename Pol > qi::symbols<char, carl::FormulaType> carl::parser::ExpressionParser< Pol >::operationAnd private
Definition at line 519 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationIff
template<typename Pol > qi::symbols<char, carl::FormulaType> carl::parser::ExpressionParser< Pol >::operationIff private
Definition at line 518 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationImp
template<typename Pol > qi::symbols<char, carl::FormulaType> carl::parser::ExpressionParser< Pol >::operationImp private
Definition at line 517 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationNot
template<typename Pol > qi::symbols<char, carl::FormulaType> carl::parser::ExpressionParser< Pol >::operationNot private
Definition at line 516 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationPow
template<typename Pol > qi::symbols<char, Operation> carl::parser::ExpressionParser< Pol >::operationPow private
Definition at line 522 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationScale
template<typename Pol > qi::symbols<char, Operation> carl::parser::ExpressionParser< Pol >::operationScale private
Definition at line 521 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationScaleLA
template<typename Pol > qi::rule<Iterator, Operation(), Skipper> carl::parser::ExpressionParser< Pol >::operationScaleLA private
Definition at line 531 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationShift
template<typename Pol > qi::symbols<char, Operation> carl::parser::ExpressionParser< Pol >::operationShift private
Definition at line 520 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
operationSign
template<typename Pol > qi::symbols<char, Operation> carl::parser::ExpressionParser< Pol >::operationSign private
Definition at line 523 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
variable
template<typename Pol > qi::rule<Iterator, Variable(), Skipper> carl::parser::ExpressionParser< Pol >::variable private
Definition at line 529 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
varmap
template<typename Pol > qi::symbols<char, Variable> carl::parser::ExpressionParser< Pol >::varmap private
Definition at line 524 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::addVariable(), and carl::parser::ExpressionParser< Pol >::newVariable().
varname
template<typename Pol > qi::rule<Iterator, std::string(), Skipper> carl::parser::ExpressionParser< Pol >::varname private
Definition at line 526 of file ExpressionParser.h.
Referenced by carl::parser::ExpressionParser< Pol >::ExpressionParser().
The documentation for this struct was generated from the following file:
carl/util/parser/ExpressionParser.h