carl: carl::ran::NumberContent< Number > Struct Template Reference
carl::ran::NumberContent< Number > Struct Template Reference
#include <RealAlgebraicNumber_Number.h>
Public Member Functions
NumberContent ()
NumberContent (const Number &n)
const auto & value () const
std::size_t size () const
bool is_integral () const
bool is_zero () const
bool contained_in (const Interval< Number > &i) const
Number integer_below () const
Sign sgn () const
Sign sgn (const UnivariatePolynomial< Number > &p) const
Data Fields
Number mContent = carl::constant_zero<Number>::get()
Detailed Description
template<typename Number>
struct carl::ran::NumberContent< Number >
Definition at line 9 of file RealAlgebraicNumber_Number.h.
Constructor & Destructor Documentation
NumberContent() [1/2]
template<typename Number> carl::ran::NumberContent< Number >::NumberContent () inline
Definition at line 14 of file RealAlgebraicNumber_Number.h.
NumberContent() [2/2]
template<typename Number> carl::ran::NumberContent< Number >::NumberContent (const Number & n) inline
Definition at line 15 of file RealAlgebraicNumber_Number.h.
Member Function Documentation
contained_in()
template<typename Number> bool carl::ran::NumberContent< Number >::contained_in (const Interval< Number > & i) const inline
Definition at line 31 of file RealAlgebraicNumber_Number.h.
integer_below()
template<typename Number> Number carl::ran::NumberContent< Number >::integer_below () const inline
Definition at line 35 of file RealAlgebraicNumber_Number.h.
is_integral()
template<typename Number> bool carl::ran::NumberContent< Number >::is_integral () const inline
Definition at line 25 of file RealAlgebraicNumber_Number.h.
is_zero()
template<typename Number> bool carl::ran::NumberContent< Number >::is_zero () const inline
Definition at line 28 of file RealAlgebraicNumber_Number.h.
sgn() [1/2]
template<typename Number> Sign carl::ran::NumberContent< Number >::sgn () const inline
Definition at line 38 of file RealAlgebraicNumber_Number.h.
Referenced by carl::RealAlgebraicNumber< Rational >::isRootOf().
sgn() [2/2]
template<typename Number> Sign carl::ran::NumberContent< Number >::sgn (const UnivariatePolynomial< Number > & p) const inline
Definition at line 41 of file RealAlgebraicNumber_Number.h.
size()
template<typename Number> std::size_t carl::ran::NumberContent< Number >::size () const inline
Definition at line 21 of file RealAlgebraicNumber_Number.h.
value()
template<typename Number> const auto& carl::ran::NumberContent< Number >::value () const inline
Definition at line 17 of file RealAlgebraicNumber_Number.h.
Referenced by carl::ran::abs(), carl::ran::branching_point(), carl::ran::NumberContent< Number >::contained_in(), carl::ran::get_interval(), carl::ran::get_number(), carl::ran::NumberContent< Number >::integer_below(), carl::ran::NumberContent< Number >::is_integral(), carl::ran::NumberContent< Number >::is_zero(), carl::RealAlgebraicNumber< Rational >::isRootOf(), carl::ran::operator<(), carl::ran::operator==(), carl::ran::sample_above(), carl::ran::sample_below(), carl::ran::sample_between(), carl::ran::NumberContent< Number >::sgn(), and carl::ran::NumberContent< Number >::size().
Field Documentation
mContent
template<typename Number> Number carl::ran::NumberContent< Number >::mContent = carl::constant_zero<Number>::get()
Definition at line 10 of file RealAlgebraicNumber_Number.h.
Referenced by carl::ran::NumberContent< Number >::value().
The documentation for this struct was generated from the following file:
carl/formula/model/ran/RealAlgebraicNumber_Number.h