carl: carl::ran::Z3Content< Number > Struct Template Reference
carl::ran::Z3Content< Number > Struct Template Reference
#include <RealAlgebraicNumber_Z3.h>
Data Structures
struct Content
Public Member Functions
Z3Content (const Z3Ran< Number > &ran)
auto & z3_ran ()
const auto & z3_ran () const
const auto & polynomial () const
const auto & interval () const
std::size_t size () const
bool is_integral () const
bool is_zero () const
bool contained_in (const Interval< Number > &i) const
Number integer_below () const
Sign sgn () const
Sign sgn (const UnivariatePolynomial< Number > &p) const
Private Attributes
std::shared_ptr< Content > mContent
Friends
template<typename Num >
bool operator== (Z3Content< Num > &lhs, Z3Content< Num > &rhs)
template<typename Num >
bool operator< (const Z3Content< Num > &lhs, const Z3Content< Num > &rhs)
Detailed Description
template<typename Number>
struct carl::ran::Z3Content< Number >
Definition at line 12 of file RealAlgebraicNumber_Z3.h.
Constructor & Destructor Documentation
Z3Content()
template<typename Number> carl::ran::Z3Content< Number >::Z3Content (const Z3Ran< Number > & ran) inline
Definition at line 27 of file RealAlgebraicNumber_Z3.h.
Member Function Documentation
contained_in()
template<typename Number> bool carl::ran::Z3Content< Number >::contained_in (const Interval< Number > & i) const inline
Definition at line 55 of file RealAlgebraicNumber_Z3.h.
integer_below()
template<typename Number> Number carl::ran::Z3Content< Number >::integer_below () const inline
Definition at line 59 of file RealAlgebraicNumber_Z3.h.
interval()
template<typename Number> const auto& carl::ran::Z3Content< Number >::interval () const inline
Definition at line 42 of file RealAlgebraicNumber_Z3.h.
Referenced by carl::ran::operator==().
is_integral()
template<typename Number> bool carl::ran::Z3Content< Number >::is_integral () const inline
Definition at line 49 of file RealAlgebraicNumber_Z3.h.
is_zero()
template<typename Number> bool carl::ran::Z3Content< Number >::is_zero () const inline
Definition at line 52 of file RealAlgebraicNumber_Z3.h.
polynomial()
template<typename Number> const auto& carl::ran::Z3Content< Number >::polynomial () const inline
Definition at line 38 of file RealAlgebraicNumber_Z3.h.
Referenced by carl::ran::operator==().
sgn() [1/2]
template<typename Number> Sign carl::ran::Z3Content< Number >::sgn () const inline
Definition at line 62 of file RealAlgebraicNumber_Z3.h.
sgn() [2/2]
template<typename Number> Sign carl::ran::Z3Content< Number >::sgn (const UnivariatePolynomial< Number > & p) const inline
Definition at line 65 of file RealAlgebraicNumber_Z3.h.
size()
template<typename Number> std::size_t carl::ran::Z3Content< Number >::size () const inline
Definition at line 46 of file RealAlgebraicNumber_Z3.h.
z3_ran() [1/2]
template<typename Number> auto& carl::ran::Z3Content< Number >::z3_ran () inline
Definition at line 31 of file RealAlgebraicNumber_Z3.h.
Referenced by carl::ran::abs(), carl::ran::branching_point(), carl::ran::Z3Content< Number >::contained_in(), carl::ran::get_interval(), carl::ran::get_number(), carl::ran::get_polynomial(), carl::ran::Z3Content< Number >::integer_below(), carl::ran::Z3Content< Number >::interval(), carl::ran::Z3Content< Number >::is_integral(), carl::ran::is_integral(), carl::ran::is_number(), carl::ran::Z3Content< Number >::is_zero(), carl::ran::is_zero(), carl::ran::operator<(), carl::ran::operator==(), carl::ran::Z3Content< Number >::polynomial(), carl::ran::sample_above(), carl::ran::sample_below(), carl::ran::sample_between(), carl::ran::Z3Content< Number >::sgn(), and carl::ran::sgn().
z3_ran() [2/2]
template<typename Number> const auto& carl::ran::Z3Content< Number >::z3_ran () const inline
Definition at line 34 of file RealAlgebraicNumber_Z3.h.
Friends And Related Function Documentation
operator<
template<typename Number> template<typename Num > bool operator< (const Z3Content< Num > & lhs, const Z3Content< Num > & rhs) friend
operator==
template<typename Number> template<typename Num > bool operator== (Z3Content< Num > & lhs, Z3Content< Num > & rhs) friend
Field Documentation
mContent
template<typename Number> std::shared_ptr<Content> carl::ran::Z3Content< Number >::mContent private
Definition at line 25 of file RealAlgebraicNumber_Z3.h.
Referenced by carl::ran::operator==().
The documentation for this struct was generated from the following file:
carl/formula/model/ran/RealAlgebraicNumber_Z3.h