carl: carl::parser::PolynomialParser< Pol > Struct Template Reference
carl::parser::PolynomialParser< Pol > Struct Template Reference
#include <PolynomialParser.h>
Public Member Functions
PolynomialParser ()
void addVariable (Variable::Arg v)
Private Types
enum Operation { ADD, SUB }
Private Member Functions
Variable newVariable (const std::string &s)
Monomial::Arg newMonomial (const std::vector< boost::fusion::vector2< Variable, typename Pol::CoeffType >> &data) const
Term< typename Pol::CoeffType > newTerm (const boost::optional< typename Pol::CoeffType > &c, const boost::optional< Monomial::Arg > &m)
Pol addTerms (const Term< typename Pol::CoeffType > &first, const std::vector< boost::fusion::vector2< Operation, Term< typename Pol::CoeffType >>> &ops)
Pol mul (const std::vector< Pol > &ops)
Pol addPolynomials (const Pol &first, const std::vector< boost::fusion::vector2< Operation, Pol >> &ops)
Private Attributes
qi::symbols< char, Operation > operation
qi::symbols< char, Variable > varmap
qi::rule< Iterator, std::string(), Skipper > varname
qi::real_parser< typename Pol::CoeffType, RationalPolicies< typename Pol::CoeffType > > number
qi::rule< Iterator, Variable(), Skipper > variable
qi::rule< Iterator, Monomial::Arg(), Skipper > monomial
qi::rule< Iterator, Term< typename Pol::CoeffType >), Skipper > term
qi::rule< Iterator, Pol(), Skipper, qi::locals< Pol > > polynomial
qi::rule< Iterator, Pol(), Skipper > expr
qi::rule< Iterator, Pol(), Skipper > expr_product
qi::rule< Iterator, Pol(), Skipper, qi::locals< Pol > > expr_sum
qi::rule< Iterator, Pol(), Skipper > main
Detailed Description
template<typename Pol>
struct carl::parser::PolynomialParser< Pol >
Definition at line 83 of file PolynomialParser.h.
Member Enumeration Documentation
Operation
template<typename Pol> enum carl::parser::PolynomialParser::Operation private
Enumerator
ADD
SUB
Definition at line 107 of file PolynomialParser.h.
Constructor & Destructor Documentation
PolynomialParser()
template<typename Pol> carl::parser::PolynomialParser< Pol >::PolynomialParser () inline
Definition at line 84 of file PolynomialParser.h.
Member Function Documentation
addPolynomials()
template<typename Pol> Pol carl::parser::PolynomialParser< Pol >::addPolynomials (const Pol & first, const std::vector< boost::fusion::vector2< Operation, Pol >> & ops) inline private
Definition at line 143 of file PolynomialParser.h.
addTerms()
template<typename Pol> Pol carl::parser::PolynomialParser< Pol >::addTerms (const Term< typename Pol::CoeffType > & first, const std::vector< boost::fusion::vector2< Operation, Term< typename Pol::CoeffType >>> & ops) inline private
Definition at line 128 of file PolynomialParser.h.
addVariable()
template<typename Pol> void carl::parser::PolynomialParser< Pol >::addVariable (Variable::Arg v) inline
Definition at line 102 of file PolynomialParser.h.
mul()
template<typename Pol> Pol carl::parser::PolynomialParser< Pol >::mul (const std::vector< Pol > & ops) inline private
Definition at line 138 of file PolynomialParser.h.
newMonomial()
template<typename Pol> Monomial::Arg carl::parser::PolynomialParser< Pol >::newMonomial (const std::vector< boost::fusion::vector2< Variable, typename Pol::CoeffType >> & data) const inline private
Definition at line 114 of file PolynomialParser.h.
newTerm()
template<typename Pol> Term<typename Pol::CoeffType> carl::parser::PolynomialParser< Pol >::newTerm (const boost::optional< typename Pol::CoeffType > & c, const boost::optional< Monomial::Arg > & m) inline private
Definition at line 121 of file PolynomialParser.h.
newVariable()
template<typename Pol> Variable carl::parser::PolynomialParser< Pol >::newVariable (const std::string & s) inline private
Definition at line 109 of file PolynomialParser.h.
Field Documentation
expr
template<typename Pol> qi::rule<Iterator, Pol(), Skipper> carl::parser::PolynomialParser< Pol >::expr private
Definition at line 162 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
expr_product
template<typename Pol> qi::rule<Iterator, Pol(), Skipper> carl::parser::PolynomialParser< Pol >::expr_product private
Definition at line 163 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
expr_sum
template<typename Pol> qi::rule<Iterator, Pol(), Skipper, qi::locals<Pol> > carl::parser::PolynomialParser< Pol >::expr_sum private
Definition at line 164 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
main
template<typename Pol> qi::rule<Iterator, Pol(), Skipper> carl::parser::PolynomialParser< Pol >::main private
Definition at line 165 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
monomial
template<typename Pol> qi::rule<Iterator, Monomial::Arg(), Skipper> carl::parser::PolynomialParser< Pol >::monomial private
Definition at line 159 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
number
template<typename Pol> qi::real_parser<typename Pol::CoeffType,RationalPolicies<typename Pol::CoeffType> > carl::parser::PolynomialParser< Pol >::number private
Definition at line 157 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
operation
template<typename Pol> qi::symbols<char, Operation> carl::parser::PolynomialParser< Pol >::operation private
Definition at line 154 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
polynomial
template<typename Pol> qi::rule<Iterator, Pol(), Skipper, qi::locals<Pol> > carl::parser::PolynomialParser< Pol >::polynomial private
Definition at line 161 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
term
template<typename Pol> qi::rule<Iterator, Term<typename Pol::CoeffType>), Skipper> carl::parser::PolynomialParser< Pol >::term private
Definition at line 160 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::newMonomial(), and carl::parser::PolynomialParser< Pol >::PolynomialParser().
variable
template<typename Pol> qi::rule<Iterator, Variable(), Skipper> carl::parser::PolynomialParser< Pol >::variable private
Definition at line 158 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
varmap
template<typename Pol> qi::symbols<char, Variable> carl::parser::PolynomialParser< Pol >::varmap private
Definition at line 155 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::addVariable(), carl::parser::PolynomialParser< Pol >::newVariable(), and carl::parser::PolynomialParser< Pol >::PolynomialParser().
varname
template<typename Pol> qi::rule<Iterator, std::string(), Skipper> carl::parser::PolynomialParser< Pol >::varname private
Definition at line 156 of file PolynomialParser.h.
Referenced by carl::parser::PolynomialParser< Pol >::PolynomialParser().
The documentation for this struct was generated from the following file:
carl/util/parser/PolynomialParser.h