carl: carl::settings::binary_quantity Struct Reference
carl::settings::binary_quantity Struct Reference
Helper type to parse quantities with binary SI-style suffixes.
#include <settings_utils.h>
Public Member Functions
constexpr binary_quantity ()=default
constexpr binary_quantity (std::size_t n)
constexpr auto n () const
constexpr auto kibi () const
constexpr auto mebi () const
constexpr auto gibi () const
constexpr auto tebi () const
constexpr auto pebi () const
constexpr auto exbi () const
Private Attributes
std::size_t mN = 0
Detailed Description
Helper type to parse quantities with binary SI-style suffixes.
Intended usage:
use boost to parse values as quantity
access values with q.mibi()
Definition at line 75 of file settings_utils.h.
Constructor & Destructor Documentation
binary_quantity() [1/2]
constexpr carl::settings::binary_quantity::binary_quantity () default
binary_quantity() [2/2]
constexpr carl::settings::binary_quantity::binary_quantity (std::size_t n) inline explicit
Definition at line 80 of file settings_utils.h.
Member Function Documentation
exbi()
constexpr auto carl::settings::binary_quantity::exbi () const inline
Definition at line 87 of file settings_utils.h.
gibi()
constexpr auto carl::settings::binary_quantity::gibi () const inline
Definition at line 84 of file settings_utils.h.
kibi()
constexpr auto carl::settings::binary_quantity::kibi () const inline
Definition at line 82 of file settings_utils.h.
mebi()
constexpr auto carl::settings::binary_quantity::mebi () const inline
Definition at line 83 of file settings_utils.h.
n()
constexpr auto carl::settings::binary_quantity::n () const inline
Definition at line 81 of file settings_utils.h.
Referenced by carl::settings::operator<(), carl::settings::operator<<(), and carl::settings::operator==().
pebi()
constexpr auto carl::settings::binary_quantity::pebi () const inline
Definition at line 86 of file settings_utils.h.
tebi()
constexpr auto carl::settings::binary_quantity::tebi () const inline
Definition at line 85 of file settings_utils.h.
Field Documentation
mN
std::size_t carl::settings::binary_quantity::mN = 0 private
Definition at line 77 of file settings_utils.h.
The documentation for this struct was generated from the following file:
carl-settings/settings_utils.h