carl: carl::detail_field_extensions::CoCoAConverter Struct Reference
carl::detail_field_extensions::CoCoAConverter Struct Reference
#include <FieldExtensions.h>
Data Structures
struct ConversionInfo
Public Member Functions
CoCoA::BigRat convert (const mpq_class &n) const
template<typename T >
T convert (const CoCoA::BigRat &n) const
CoCoA::BigRat convert (const cln::cl_RA &n) const
template<typename Poly >
Poly convertMV (const CoCoA::RingElem &p, const ConversionInfo &ci) const
template<typename Poly >
CoCoA::RingElem convertUV (const Poly &p, const ConversionInfo &ci) const
Detailed Description
Definition at line 14 of file FieldExtensions.h.
Member Function Documentation
convert() [1/3]
CoCoA::BigRat carl::detail_field_extensions::CoCoAConverter::convert (const mpq_class & n) const inline
Definition at line 21 of file FieldExtensions.h.
Referenced by convertUV().
convert() [2/3]
template<typename T > T carl::detail_field_extensions::CoCoAConverter::convert (const CoCoA::BigRat & n) const inline
Definition at line 25 of file FieldExtensions.h.
convert() [3/3]
CoCoA::BigRat carl::detail_field_extensions::CoCoAConverter::convert (const cln::cl_RA & n) const inline
Definition at line 41 of file FieldExtensions.h.
convertMV()
template<typename Poly > Poly carl::detail_field_extensions::CoCoAConverter::convertMV (const CoCoA::RingElem & p, const ConversionInfo & ci) const inline
Definition at line 49 of file FieldExtensions.h.
Referenced by carl::FieldExtensions< Rational, Poly >::evaluatesToZero(), and carl::FieldExtensions< Rational, Poly >::extend().
convertUV()
template<typename Poly > CoCoA::RingElem carl::detail_field_extensions::CoCoAConverter::convertUV (const Poly & p, const ConversionInfo & ci) const inline
Definition at line 79 of file FieldExtensions.h.
Referenced by carl::FieldExtensions< Rational, Poly >::extend().
The documentation for this struct was generated from the following file:
carl/core/polynomialfunctions/FieldExtensions.h