carl: carl::detail_lazard::CoCoAConverter Struct Reference
carl::detail_lazard::CoCoAConverter Struct Reference
#include <LazardEvaluation.h>
Data Structures
struct ConversionInfo
Public Member Functions
CoCoA::BigRat convert (const mpq_class &n) const
mpq_class convert (const CoCoA::BigRat &n) const
template<typename Poly >
Poly convertMV (const CoCoA::RingElem &p, const ConversionInfo &ci) const
template<typename Poly >
CoCoA::RingElem convertUV (const Poly &p, const ConversionInfo &ci) const
Detailed Description
Definition at line 13 of file LazardEvaluation.h.
Member Function Documentation
convert() [1/2]
CoCoA::BigRat carl::detail_lazard::CoCoAConverter::convert (const mpq_class & n) const inline
Definition at line 20 of file LazardEvaluation.h.
Referenced by convertMV(), and convertUV().
convert() [2/2]
mpq_class carl::detail_lazard::CoCoAConverter::convert (const CoCoA::BigRat & n) const inline
Definition at line 23 of file LazardEvaluation.h.
convertMV()
template<typename Poly > Poly carl::detail_lazard::CoCoAConverter::convertMV (const CoCoA::RingElem & p, const ConversionInfo & ci) const inline
Definition at line 28 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::evaluatesToZero(), and carl::LazardEvaluation< Rational, Poly >::getSubstitution().
convertUV()
template<typename Poly > CoCoA::RingElem carl::detail_lazard::CoCoAConverter::convertUV (const Poly & p, const ConversionInfo & ci) const inline
Definition at line 58 of file LazardEvaluation.h.
Referenced by carl::LazardEvaluation< Rational, Poly >::getSubstitution().
The documentation for this struct was generated from the following file:
carl/core/polynomialfunctions/LazardEvaluation.h