carl: carl::tree_detail::PostorderIterator< T, reverse > Struct Template Reference
carl::tree_detail::PostorderIterator< T, reverse > Struct Template Reference
Iterator class for post-order iterations over all elements.
#include <carlTree.h>
Public Types
using Base = BaseIterator< T, PostorderIterator< T, reverse >, reverse >
Public Member Functions
PostorderIterator (const tree< T > *t)
PostorderIterator (const tree< T > *t, std::size_t root)
PostorderIterator & next ()
PostorderIterator & previous ()
template<typename It >
PostorderIterator (const BaseIterator< T, It, reverse > &ii)
PostorderIterator (const PostorderIterator &ii)
PostorderIterator (PostorderIterator &&ii)
PostorderIterator & operator= (const PostorderIterator &it)
PostorderIterator & operator= (PostorderIterator &&it)
virtual ~PostorderIterator () noexcept=default
const auto & nodes () const
const auto & node (std::size_t id) const
const auto & curnode () const
std::size_t depth () const
std::size_t id () const
bool isRoot () const
bool isValid () const
T * operator-> ()
T const * operator-> () const
Data Fields
std::size_t current
Protected Attributes
const tree< T > * mTree
Detailed Description
template<typename T, bool reverse = false>
struct carl::tree_detail::PostorderIterator< T, reverse >
Iterator class for post-order iterations over all elements.
Definition at line 245 of file carlTree.h.
Member Typedef Documentation
Base
template<typename T, bool reverse = false> using carl::tree_detail::PostorderIterator< T, reverse >::Base = BaseIterator<T, PostorderIterator<T, reverse>,reverse>
Definition at line 249 of file carlTree.h.
Constructor & Destructor Documentation
PostorderIterator() [1/5]
template<typename T, bool reverse = false> carl::tree_detail::PostorderIterator< T, reverse >::PostorderIterator (const tree< T > * t) inline
Definition at line 250 of file carlTree.h.
PostorderIterator() [2/5]
template<typename T, bool reverse = false> carl::tree_detail::PostorderIterator< T, reverse >::PostorderIterator (const tree< T > * t, std::size_t root) inline
Definition at line 251 of file carlTree.h.
PostorderIterator() [3/5]
template<typename T, bool reverse = false> template<typename It > carl::tree_detail::PostorderIterator< T, reverse >::PostorderIterator (const BaseIterator< T, It, reverse > & ii) inline
Definition at line 285 of file carlTree.h.
PostorderIterator() [4/5]
template<typename T, bool reverse = false> carl::tree_detail::PostorderIterator< T, reverse >::PostorderIterator (const PostorderIterator< T, reverse > & ii) inline
Definition at line 286 of file carlTree.h.
PostorderIterator() [5/5]
template<typename T, bool reverse = false> carl::tree_detail::PostorderIterator< T, reverse >::PostorderIterator (PostorderIterator< T, reverse > && ii) inline
Definition at line 287 of file carlTree.h.
~PostorderIterator()
template<typename T, bool reverse = false> virtual carl::tree_detail::PostorderIterator< T, reverse >::~PostorderIterator () virtual default noexcept
Member Function Documentation
curnode()
const auto& carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::curnode () const inline inherited
Definition at line 85 of file carlTree.h.
Referenced by carl::tree_detail::ChildrenIterator< T, reverse >::ChildrenIterator(), carl::tree_detail::PostorderIterator< T, reverse >::next(), carl::tree_detail::DepthIterator< T, reverse >::next(), carl::tree_detail::ChildrenIterator< T, reverse >::next(), carl::tree_detail::PathIterator< T >::next(), carl::tree_detail::PostorderIterator< T, reverse >::previous(), carl::tree_detail::DepthIterator< T, reverse >::previous(), and carl::tree_detail::ChildrenIterator< T, reverse >::previous().
depth()
std::size_t carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::depth () const inline inherited
Definition at line 95 of file carlTree.h.
Referenced by carl::tree< carl::RealAlgebraicNumber< carl::Number > >::begin_depth(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::createNode(), carl::tree_detail::DepthIterator< T, reverse >::DepthIterator(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::newNode(), carl::tree_detail::DepthIterator< T, reverse >::operator=(), carl::tree_detail::DepthIterator< T, reverse >::previous(), and carl::tree< carl::RealAlgebraicNumber< carl::Number > >::rbegin_depth().
id()
std::size_t carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::id () const inline inherited
Definition at line 98 of file carlTree.h.
Referenced by carl::tree< carl::RealAlgebraicNumber< carl::Number > >::erase(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::eraseChildren(), and carl::tree< carl::RealAlgebraicNumber< carl::Number > >::eraseNode().
isRoot()
bool carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::isRoot () const inline inherited
Definition at line 102 of file carlTree.h.
isValid()
bool carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::isValid () const inline inherited
Definition at line 105 of file carlTree.h.
next()
template<typename T, bool reverse = false> PostorderIterator& carl::tree_detail::PostorderIterator< T, reverse >::next () inline
Definition at line 252 of file carlTree.h.
Referenced by carl::tree< carl::RealAlgebraicNumber< carl::Number > >::insert().
node()
const auto& carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::node (std::size_t id) const inline inherited
Definition at line 81 of file carlTree.h.
Referenced by carl::tree< carl::RealAlgebraicNumber< carl::Number > >::isConsistent().
nodes()
const auto& carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::nodes () const inline inherited
Definition at line 78 of file carlTree.h.
Referenced by carl::tree< carl::RealAlgebraicNumber< carl::Number > >::append(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::begin_leaf(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::begin_postorder(), carl::tree_detail::ChildrenIterator< T, reverse >::ChildrenIterator(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::clear(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::createNode(), carl::tree_detail::DepthIterator< T, reverse >::DepthIterator(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::erase(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::eraseChildren(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::eraseNode(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::get_parent(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::insert(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_leaf(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_leftmost(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_rightmost(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::is_valid(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::isConsistent(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::left_sibling(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::newNode(), carl::tree_detail::LeafIterator< T, reverse >::next(), carl::tree_detail::LeafIterator< T, reverse >::previous(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::rbegin_leaf(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::rbegin_preorder(), carl::tree< carl::RealAlgebraicNumber< carl::Number > >::replace(), and carl::tree< carl::RealAlgebraicNumber< carl::Number > >::setRoot().
operator->() [1/2]
T* carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::operator-> () inline inherited
Definition at line 108 of file carlTree.h.
operator->() [2/2]
T const* carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::operator-> () const inline inherited
Definition at line 111 of file carlTree.h.
operator=() [1/2]
template<typename T, bool reverse = false> PostorderIterator& carl::tree_detail::PostorderIterator< T, reverse >::operator= (const PostorderIterator< T, reverse > & it) inline
Definition at line 288 of file carlTree.h.
operator=() [2/2]
template<typename T, bool reverse = false> PostorderIterator& carl::tree_detail::PostorderIterator< T, reverse >::operator= (PostorderIterator< T, reverse > && it) inline
Definition at line 292 of file carlTree.h.
previous()
template<typename T, bool reverse = false> PostorderIterator& carl::tree_detail::PostorderIterator< T, reverse >::previous () inline
Definition at line 265 of file carlTree.h.
Field Documentation
current
std::size_t carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::current inherited
Definition at line 88 of file carlTree.h.
Referenced by carl::tree_detail::ChildrenIterator< T, reverse >::ChildrenIterator(), carl::tree_detail::DepthIterator< T, reverse >::DepthIterator(), carl::tree_detail::PostorderIterator< T, reverse >::next(), carl::tree_detail::LeafIterator< T, reverse >::next(), carl::tree_detail::DepthIterator< T, reverse >::next(), carl::tree_detail::ChildrenIterator< T, reverse >::next(), carl::tree_detail::PathIterator< T >::next(), carl::tree_detail::PostorderIterator< T, reverse >::previous(), carl::tree_detail::LeafIterator< T, reverse >::previous(), carl::tree_detail::DepthIterator< T, reverse >::previous(), and carl::tree_detail::ChildrenIterator< T, reverse >::previous().
mTree
const tree<T>* carl::tree_detail::BaseIterator< T, PostorderIterator< T, reverse > , reverse >::mTree protected inherited
Definition at line 75 of file carlTree.h.
Referenced by carl::tree_detail::ChildrenIterator< T, reverse >::ChildrenIterator(), carl::tree_detail::PostorderIterator< T, reverse >::next(), carl::tree_detail::LeafIterator< T, reverse >::next(), carl::tree_detail::DepthIterator< T, reverse >::next(), carl::tree_detail::ChildrenIterator< T, reverse >::next(), carl::tree_detail::PostorderIterator< T, reverse >::previous(), carl::tree_detail::LeafIterator< T, reverse >::previous(), carl::tree_detail::DepthIterator< T, reverse >::previous(), and carl::tree_detail::ChildrenIterator< T, reverse >::previous().
The documentation for this struct was generated from the following file:
carl/util/carlTree.h