carl: carl::BaseRepresentation< Number > Struct Template Reference
carl::BaseRepresentation< Number > Struct Template Reference
#include <MultiplicationTable.h>
Public Types
using Monomial = Term< Number >
Public Member Functions
BaseRepresentation ()=default
BaseRepresentation (const std::vector< Monomial > &base, const MultivariatePolynomial< Number > &p)
bool isZero () const
bool contains (uint i) const
Number get (uint index) const
Data Fields
K keys
STL member.
T elements
STL member.
Detailed Description
template<typename Number>
struct carl::BaseRepresentation< Number >
Definition at line 20 of file MultiplicationTable.h.
Member Typedef Documentation
Monomial
template<typename Number> using carl::BaseRepresentation< Number >::Monomial = Term<Number>
Definition at line 21 of file MultiplicationTable.h.
Constructor & Destructor Documentation
BaseRepresentation() [1/2]
template<typename Number> carl::BaseRepresentation< Number >::BaseRepresentation () default
BaseRepresentation() [2/2]
template<typename Number> carl::BaseRepresentation< Number >::BaseRepresentation (const std::vector< Monomial > & base, const MultivariatePolynomial< Number > & p) inline
Definition at line 25 of file MultiplicationTable.h.
Member Function Documentation
contains()
template<typename Number> bool carl::BaseRepresentation< Number >::contains (uint i) const inline
Definition at line 37 of file MultiplicationTable.h.
get()
template<typename Number> Number carl::BaseRepresentation< Number >::get (uint index) const inline
Definition at line 38 of file MultiplicationTable.h.
Referenced by carl::MultiplicationTable< carl::Number >::multiply(), and carl::MultiplicationTable< carl::Number >::trace().
isZero()
template<typename Number> bool carl::BaseRepresentation< Number >::isZero () const inline
Definition at line 36 of file MultiplicationTable.h.
Referenced by carl::MultiplicationTable< carl::Number >::init().
Field Documentation
elements
T std::map< K, T >::elements inherited
STL member.
keys
K std::map< K, T >::keys inherited
STL member.
The documentation for this struct was generated from the following file:
carl/thom/TarskiQuery/MultiplicationTable.h