carl: carl::cad::SampleSet< Number >::SampleComparator Struct Reference
carl::cad::SampleSet< Number >::SampleComparator Struct Reference
A functor compatible to std::less<RealAlgebraicNumber<Number>> that compares two samples according to a given order.
#include <SampleSet.h>
Public Member Functions
SampleComparator (SampleOrdering ordering)
Constructor from a given ordering.
bool operator() (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs) const
Comparison function implemented by this functor.
bool isOptimal (const RealAlgebraicNumber< Number > &s) const
Checks if the given sample is optimal with respect to the ordering.
SampleOrdering ordering () const
Returns the current ordering.
Private Member Functions
std::pair< bool, bool > compare (bool l, bool r) const
Creates a comparison result from the information if a certain property holds for two objects.
template<typename T >
std::pair< bool, bool > compare (T l, T r) const
Creates a comparison result from the rankings for a certain property of two objects.
std::pair< bool, bool > compareInt (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs) const
Compares two samples checking if they are integers.
std::pair< bool, bool > compareRat (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs) const
Compares two samples checking if they are rationals.
std::pair< bool, bool > compareSize (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs) const
Compares two samples with respect to their representation size.
std::pair< bool, bool > compareRoot (const RealAlgebraicNumber< Number > &lhs, const RealAlgebraicNumber< Number > &rhs) const
Compares two samples checking if they are roots.
Private Attributes
SampleOrdering mOrdering
Ordering used by this functor.
Detailed Description
template<typename Number>
struct carl::cad::SampleSet< Number >::SampleComparator
A functor compatible to std::less<RealAlgebraicNumber<Number>> that compares two samples according to a given order.
Definition at line 33 of file SampleSet.h.
Constructor & Destructor Documentation
SampleComparator()
template<typename Number> carl::cad::SampleSet< Number >::SampleComparator::SampleComparator (SampleOrdering ordering) inline explicit
Constructor from a given ordering.
Parameters
ordering Ordering to be used by the resulting functor.
Definition at line 42 of file SampleSet.h.
Member Function Documentation
compare() [1/2]
template<typename Number> std::pair<bool, bool> carl::cad::SampleSet< Number >::SampleComparator::compare (bool l, bool r) const inline private
Creates a comparison result from the information if a certain property holds for two objects.
a is less than b if the property does not hold for a, but does for b.
Parameters
l Property of a.
r Property of b.
Returns
(true, a<b) if a<b or a>b, (false, undefined) if a==b (with respect to the inspected property).
Definition at line 75 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::SampleComparator::compareInt(), carl::cad::SampleSet< Number >::SampleComparator::compareRat(), carl::cad::SampleSet< Number >::SampleComparator::compareRoot(), and carl::cad::SampleSet< Number >::SampleComparator::compareSize().
compare() [2/2]
template<typename Number> template<typename T > std::pair<bool, bool> carl::cad::SampleSet< Number >::SampleComparator::compare (T l, T r) const inline private
Creates a comparison result from the rankings for a certain property of two objects.
a is less than b if the ranking of a is less than the one of b.
Parameters
l Ranking of a.
r Ranking of b.
Returns
(true, a<b) if a<b or a>b, (false, undefined) if a==b (with respect to the inspected property).
Definition at line 87 of file SampleSet.h.
compareInt()
template<typename Number> std::pair<bool, bool> carl::cad::SampleSet< Number >::SampleComparator::compareInt (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) const inline private
Compares two samples checking if they are integers.
Parameters
lhs First Sample.
rhs Second Sample.
Returns
Comparison result.
Definition at line 98 of file SampleSet.h.
compareRat()
template<typename Number> std::pair<bool, bool> carl::cad::SampleSet< Number >::SampleComparator::compareRat (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) const inline private
Compares two samples checking if they are rationals.
Parameters
lhs First Sample.
rhs Second Sample.
Returns
Comparison result.
Definition at line 107 of file SampleSet.h.
compareRoot()
template<typename Number> std::pair<bool, bool> carl::cad::SampleSet< Number >::SampleComparator::compareRoot (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) const inline private
Compares two samples checking if they are roots.
Parameters
lhs First Sample.
rhs Second Sample.
Returns
Comparison result.
Definition at line 127 of file SampleSet.h.
compareSize()
template<typename Number> std::pair<bool, bool> carl::cad::SampleSet< Number >::SampleComparator::compareSize (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) const inline private
Compares two samples with respect to their representation size.
Requires that both samples have a numeric value.
Parameters
lhs First Sample.
rhs Second Sample.
Returns
Comparison result.
Definition at line 117 of file SampleSet.h.
isOptimal()
template<typename Number> bool carl::cad::SampleSet< Number >::SampleComparator::isOptimal (const RealAlgebraicNumber< Number > & s) const
Checks if the given sample is optimal with respect to the ordering.
Parameters
s Sample.
Returns
True if s is optimal.
Referenced by carl::cad::SampleSet< Number >::hasOptimal().
operator()()
template<typename Number> bool carl::cad::SampleSet< Number >::SampleComparator::operator() (const RealAlgebraicNumber< Number > & lhs, const RealAlgebraicNumber< Number > & rhs) const
Comparison function implemented by this functor.
Checks if lhs is less than rhs according to the ordering.
Parameters
lhs Left sample.
rhs Right sample.
Returns
True if lhs < rhs.
ordering()
template<typename Number> SampleOrdering carl::cad::SampleSet< Number >::SampleComparator::ordering () const inline
Returns the current ordering.
Returns
Ordering.
Definition at line 64 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::ordering().
Field Documentation
mOrdering
template<typename Number> SampleOrdering carl::cad::SampleSet< Number >::SampleComparator::mOrdering private
Ordering used by this functor.
Definition at line 36 of file SampleSet.h.
Referenced by carl::cad::SampleSet< Number >::SampleComparator::ordering().
The documentation for this struct was generated from the following file:
carl/cad/SampleSet.h