carl: carl::OPBParser Struct Reference
carl::OPBParser Struct Reference
Public Member Functions
OPBParser ()
boost::optional< OPBFile > parse (std::istream &in)
Private Member Functions
Variable addVariable (const std::string &s)
OPBFile createFile (const OPBPolynomial &obj, const std::vector< OPBConstraint > &constraints)
Private Attributes
qi::symbols< char, Relation > mRelation
qi::symbols< char, Variable > mVariables
qi::rule< Iterator, std::string(), Skipper > mVarname
qi::rule< Iterator, Variable(), Skipper > mNewVarWrapper
qi::rule< Iterator, std::pair< int, Variable >), Skipper > mTerm
qi::rule< Iterator, OPBPolynomial(), Skipper > mPolynomial
qi::rule< Iterator, OPBConstraint(), Skipper > mConstraint
qi::rule< Iterator, OPBPolynomial(), Skipper > mObjective
qi::rule< Iterator, OPBFile(), Skipper > mMain
px::function< ErrorHandler > errorHandler
Detailed Description
Definition at line 33 of file OPBImporter.cpp.
Constructor & Destructor Documentation
OPBParser()
carl::OPBParser::OPBParser () inline
Definition at line 34 of file OPBImporter.cpp.
Member Function Documentation
addVariable()
Variable carl::OPBParser::addVariable (const std::string & s) inline private
Definition at line 74 of file OPBImporter.cpp.
Referenced by OPBParser().
createFile()
OPBFile carl::OPBParser::createFile (const OPBPolynomial & obj, const std::vector< OPBConstraint > & constraints) inline private
Definition at line 79 of file OPBImporter.cpp.
Referenced by OPBParser().
parse()
boost::optional<OPBFile> carl::OPBParser::parse (std::istream & in) inline
Definition at line 52 of file OPBImporter.cpp.
Referenced by carl::parseOPBFile().
Field Documentation
errorHandler
px::function<ErrorHandler> carl::OPBParser::errorHandler private
Definition at line 92 of file OPBImporter.cpp.
Referenced by OPBParser().
mConstraint
qi::rule<Iterator, OPBConstraint(), Skipper> carl::OPBParser::mConstraint private
Definition at line 89 of file OPBImporter.cpp.
Referenced by OPBParser().
mMain
qi::rule<Iterator, OPBFile(), Skipper> carl::OPBParser::mMain private
Definition at line 91 of file OPBImporter.cpp.
Referenced by OPBParser().
mNewVarWrapper
qi::rule<Iterator, Variable(), Skipper> carl::OPBParser::mNewVarWrapper private
Definition at line 86 of file OPBImporter.cpp.
Referenced by OPBParser().
mObjective
qi::rule<Iterator, OPBPolynomial(), Skipper> carl::OPBParser::mObjective private
Definition at line 90 of file OPBImporter.cpp.
Referenced by OPBParser().
mPolynomial
qi::rule<Iterator, OPBPolynomial(), Skipper> carl::OPBParser::mPolynomial private
Definition at line 88 of file OPBImporter.cpp.
Referenced by OPBParser().
mRelation
qi::symbols<char, Relation> carl::OPBParser::mRelation private
Definition at line 83 of file OPBImporter.cpp.
Referenced by OPBParser().
mTerm
qi::rule<Iterator, std::pair<int,Variable>), Skipper> carl::OPBParser::mTerm private
Definition at line 87 of file OPBImporter.cpp.
Referenced by OPBParser().
mVariables
qi::symbols<char, Variable> carl::OPBParser::mVariables private
Definition at line 84 of file OPBImporter.cpp.
Referenced by addVariable(), and OPBParser().
mVarname
qi::rule<Iterator, std::string(), Skipper> carl::OPBParser::mVarname private
Definition at line 85 of file OPBImporter.cpp.
Referenced by OPBParser().
The documentation for this struct was generated from the following file:
carl/formula/parser/OPBImporter.cpp