carl: carl::cad::ProjectionOperator< Poly > Struct Template Reference
carl::cad::ProjectionOperator< Poly > Struct Template Reference
#include <Projection.h>
Public Member Functions
template<typename Inserter >
void operator() (ProjectionType pt, const Poly &p, Variable::Arg variable, Inserter &i) const
template<typename Inserter >
void operator() (ProjectionType pt, const Poly &p, const Poly &q, Variable::Arg variable, Inserter &i) const
template<typename PolyCoeff >
bool doesNotVanish (const PolyCoeff &p) const
Tries to determine whether the given polynomial vanishes for some assignment.
template<typename Inserter >
void Brown (const Poly &p, const Poly &q, Variable::Arg variable, Inserter &i) const
template<typename Inserter >
void Brown (const Poly &p, Variable::Arg variable, Inserter &i) const
template<typename Inserter >
void McCallum (const Poly &p, const Poly &q, Variable::Arg variable, Inserter &i) const
template<typename Inserter >
void McCallum (const Poly &p, Variable::Arg variable, Inserter &i) const
Detailed Description
template<typename Poly>
struct carl::cad::ProjectionOperator< Poly >
Definition at line 16 of file Projection.h.
Member Function Documentation
Brown() [1/2]
template<typename Poly> template<typename Inserter > void carl::cad::ProjectionOperator< Poly >::Brown (const Poly & p, const Poly & q, Variable::Arg variable, Inserter & i) const inline
Definition at line 54 of file Projection.h.
Referenced by carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::operator()().
Brown() [2/2]
template<typename Poly> template<typename Inserter > void carl::cad::ProjectionOperator< Poly >::Brown (const Poly & p, Variable::Arg variable, Inserter & i) const inline
Definition at line 59 of file Projection.h.
doesNotVanish()
template<typename Poly> template<typename PolyCoeff > bool carl::cad::ProjectionOperator< Poly >::doesNotVanish (const PolyCoeff & p) const inline
Tries to determine whether the given polynomial vanishes for some assignment.
Returns true if the polynomial is guaranteed not to vanish. Returns false otherwise.
Definition at line 44 of file Projection.h.
Referenced by carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::Brown().
McCallum() [1/2]
template<typename Poly> template<typename Inserter > void carl::cad::ProjectionOperator< Poly >::McCallum (const Poly & p, const Poly & q, Variable::Arg variable, Inserter & i) const inline
Definition at line 82 of file Projection.h.
Referenced by carl::cad::ProjectionOperator< const carl::UnivariatePolynomial *>::operator()().
McCallum() [2/2]
template<typename Poly> template<typename Inserter > void carl::cad::ProjectionOperator< Poly >::McCallum (const Poly & p, Variable::Arg variable, Inserter & i) const inline
Definition at line 87 of file Projection.h.
operator()() [1/2]
template<typename Poly> template<typename Inserter > void carl::cad::ProjectionOperator< Poly >::operator() (ProjectionType pt, const Poly & p, Variable::Arg variable, Inserter & i) const inline
Definition at line 18 of file Projection.h.
operator()() [2/2]
template<typename Poly> template<typename Inserter > void carl::cad::ProjectionOperator< Poly >::operator() (ProjectionType pt, const Poly & p, const Poly & q, Variable::Arg variable, Inserter & i) const inline
Definition at line 28 of file Projection.h.
The documentation for this struct was generated from the following file:
carl/cad/Projection.h