carl: carl::ran::ThomContent< Number > Struct Template Reference
carl::ran::ThomContent< Number > Struct Template Reference
#include <RealAlgebraicNumber_Thom.h>
Data Structures
struct Content
Public Member Functions
ThomContent (const ThomEncoding< Number > &te)
auto & thom_encoding ()
const auto & thom_encoding () const
const auto & polynomial () const
const auto & mainVar () const
auto sign_condition () const
const auto & point () const
std::size_t size () const
std::size_t dimension () const
bool is_integral () const
bool is_zero () const
bool contained_in (const Interval< Number > &i) const
Number integer_below () const
Sign sgn () const
Sign sgn (const UnivariatePolynomial< Number > &p) const
Private Attributes
std::shared_ptr< Content > mContent
Friends
template<typename Num >
bool operator== (const ThomContent< Num > &lhs, const ThomContent< Num > &rhs)
template<typename Num >
bool operator< (const ThomContent< Num > &lhs, const ThomContent< Num > &rhs)
Detailed Description
template<typename Number>
struct carl::ran::ThomContent< Number >
Definition at line 11 of file RealAlgebraicNumber_Thom.h.
Constructor & Destructor Documentation
ThomContent()
template<typename Number> carl::ran::ThomContent< Number >::ThomContent (const ThomEncoding< Number > & te) inline
Definition at line 26 of file RealAlgebraicNumber_Thom.h.
Member Function Documentation
contained_in()
template<typename Number> bool carl::ran::ThomContent< Number >::contained_in (const Interval< Number > & i) const inline
Definition at line 64 of file RealAlgebraicNumber_Thom.h.
dimension()
template<typename Number> std::size_t carl::ran::ThomContent< Number >::dimension () const inline
Definition at line 54 of file RealAlgebraicNumber_Thom.h.
integer_below()
template<typename Number> Number carl::ran::ThomContent< Number >::integer_below () const inline
Definition at line 68 of file RealAlgebraicNumber_Thom.h.
is_integral()
template<typename Number> bool carl::ran::ThomContent< Number >::is_integral () const inline
Definition at line 58 of file RealAlgebraicNumber_Thom.h.
is_zero()
template<typename Number> bool carl::ran::ThomContent< Number >::is_zero () const inline
Definition at line 61 of file RealAlgebraicNumber_Thom.h.
mainVar()
template<typename Number> const auto& carl::ran::ThomContent< Number >::mainVar () const inline
Definition at line 40 of file RealAlgebraicNumber_Thom.h.
point()
template<typename Number> const auto& carl::ran::ThomContent< Number >::point () const inline
Definition at line 46 of file RealAlgebraicNumber_Thom.h.
Referenced by carl::ran::evaluate().
polynomial()
template<typename Number> const auto& carl::ran::ThomContent< Number >::polynomial () const inline
Definition at line 37 of file RealAlgebraicNumber_Thom.h.
sgn() [1/2]
template<typename Number> Sign carl::ran::ThomContent< Number >::sgn () const inline
Definition at line 71 of file RealAlgebraicNumber_Thom.h.
Referenced by carl::ran::evaluate().
sgn() [2/2]
template<typename Number> Sign carl::ran::ThomContent< Number >::sgn (const UnivariatePolynomial< Number > & p) const inline
Definition at line 74 of file RealAlgebraicNumber_Thom.h.
sign_condition()
template<typename Number> auto carl::ran::ThomContent< Number >::sign_condition () const inline
Definition at line 43 of file RealAlgebraicNumber_Thom.h.
size()
template<typename Number> std::size_t carl::ran::ThomContent< Number >::size () const inline
Definition at line 50 of file RealAlgebraicNumber_Thom.h.
thom_encoding() [1/2]
template<typename Number> auto& carl::ran::ThomContent< Number >::thom_encoding () inline
Definition at line 30 of file RealAlgebraicNumber_Thom.h.
Referenced by carl::ran::branching_point(), carl::ran::ThomContent< Number >::contained_in(), carl::ran::ThomContent< Number >::dimension(), carl::ran::get_interval(), carl::ran::get_number(), carl::ran::ThomContent< Number >::integer_below(), carl::ran::ThomContent< Number >::is_integral(), carl::ran::is_number(), carl::ran::ThomContent< Number >::is_zero(), carl::ran::ThomContent< Number >::mainVar(), carl::ran::operator<(), carl::ran::operator==(), carl::ran::ThomContent< Number >::point(), carl::ran::ThomContent< Number >::polynomial(), carl::ran::sample_above(), carl::ran::sample_below(), carl::ran::sample_between(), carl::ran::ThomContent< Number >::sgn(), carl::ran::ThomContent< Number >::sign_condition(), and carl::ran::ThomContent< Number >::size().
thom_encoding() [2/2]
template<typename Number> const auto& carl::ran::ThomContent< Number >::thom_encoding () const inline
Definition at line 33 of file RealAlgebraicNumber_Thom.h.
Friends And Related Function Documentation
operator<
template<typename Number> template<typename Num > bool operator< (const ThomContent< Num > & lhs, const ThomContent< Num > & rhs) friend
operator==
template<typename Number> template<typename Num > bool operator== (const ThomContent< Num > & lhs, const ThomContent< Num > & rhs) friend
Field Documentation
mContent
template<typename Number> std::shared_ptr<Content> carl::ran::ThomContent< Number >::mContent private
Definition at line 24 of file RealAlgebraicNumber_Thom.h.
Referenced by carl::ran::operator==().
The documentation for this struct was generated from the following file:
carl/formula/model/ran/RealAlgebraicNumber_Thom.h